/**
 * Sign Doc · Session UX in every language (operator 2026-09-09: "all UX translations, 33 languages"). One file per language,
 * loaded on demand when the Globe selects it (the Divinity Guide's LANG_LOADERS pattern, R-CORE); nothing of them rides in the
 * first bundle. EN is the lexicon's englishDefault; ES is lib/lexicon-translations-es-sign.ts (the first full second language).
 * GENERATED by scripts/gen-i18n-index.mjs from the files present — do not edit by hand.
 */
export const APP_LOCALES = [] as const;
export type SignLocale = (typeof APP_LOCALES)[number];
const LOADERS: Record<SignLocale, () => Promise<{ default: Record<string, string> }>> = {

};
/** the language's strings from this store, or null when the code has no file */
export async function loadAppLocale(code: string): Promise<Record<string, string> | null> {
  const l = (LOADERS as Record<string, (() => Promise<{ default: Record<string, string> }>) | undefined>)[code];
  if (!l) return null;
  try { return (await l()).default; } catch { return null; }
}
