// eXeL WIREFRAME-CORE · FOIL · 1.111 m × 0.7777 m (demo / laser-tag scale) · v00.00 r0.030
// eXeL v0.030-2026.09.16-foil
// Generated by scripts/wire-export.mjs from foil-1.111.json — DO NOT EDIT; edit the model.
// Axes: Unreal (Z-up, cm). Vertices 901 · segments 1755.
// Source: docs/security-2525/xbat-wireframe/xbat.wire.json scaled by airframe.geometry (foil-1.111 family)
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Foil1111WireframeActor.generated.h"

USTRUCT()
struct FWireSegment { GENERATED_BODY() FVector A; FVector B; };

UCLASS()
class AFoil1111WireframeActor : public AActor
{
    GENERATED_BODY()
public:
    AFoil1111WireframeActor();
    UPROPERTY(EditAnywhere) FColor LineColor = FColor(0, 255, 255);
    UPROPERTY(EditAnywhere) float LineThickness = 1.0f;
    virtual void Tick(float DeltaSeconds) override;
    static const TArray<FWireSegment>& Segments();
};
