# r.134 -> r.135 — the fold of the fleet's SECOND (adversarial) reviewers: three r.134 regressions and the half-done folds.
# Every replacement asserts its exact anchor and count; a miss REFUSES (nothing is written).
import hashlib,os
DECK=os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),'..'))
SRC=os.path.join(DECK,'drone-2525_r.134.html'); DST=os.path.join(DECK,'drone-2525_r.135.html')
s=open(SRC,encoding='utf-8').read()
n=[0]
def rep(old,new,count=1):
    global s
    c=s.count(old)
    if c!=count: raise SystemExit(f'REFUSE: expected {count} of {old[:90]!r}, found {c}')
    n[0]+=1
    s=s.replace(old,new)

# ── REGRESSION 1 · the frame tail was split off and never called (Aset B): CIL/HIL/SIL/COM stats, calibrate(), bloom were dead ──
rep("  const pch=document.getElementById('phCH'); if(pch) pch.textContent='CH'+chNum();\n  hudPhase();\n}\nfunction hudPhase(){",
    "  const pch=document.getElementById('phCH'); if(pch) pch.textContent='CH'+chNum()+' D'+(state.diff||3);\n  hudPhase(); hudTail(u,S); /* r.135: the tail the r.134 split left uncalled (Aset B) */\n}\nfunction hudPhase(){")
rep("function hudTail(){\n","function hudTail(u,S){ if(!u||!S) return;\n")

# ── REGRESSION 2 · a training lapse row from BOTH phones diverged the records (Odin B, Christo B): in a LIVE room only the host
#    emits LAPSE rows, over the wire; the joiner applies them (bookkeeping without a second row) ──
rep("    if(q.life<=0){ q.up=false; q.fall=1; R.phase='gap';R.t=0;R.k++; if(L.i===mine&&rangeArmed()){ if(!q._eng){ rangeLapse(q); state.rangeLapsed=(state.rangeLapsed|0)+1; hudScore(); } } rangeRelease(q); }",
    "    if(q.life<=0){ q.up=false; q.fall=1; R.phase='gap';R.t=0;R.k++; if(L.i===mine&&rangeArmed()&&lapseIsMine()){ if(!q._eng){ rangeLapse(q,false); state.rangeLapsed=(state.rangeLapsed|0)+1; hudScore(); } } rangeRelease(q); } /* r.135: in a LIVE room the host's clock is the lapse clock; a joiner takes the host's row */")
rep("function rangeLapse(q){ /* an exposure ended with the target still standing: in QUAL · 40 that is an unfired MISS round */\n  if(state.rangeMode!=='qual40'){ if(typeof ev==='function') ev('LAPSE',q.id,'LAPSED'); toast('LAPSED · '+plateBase(q.id)+' · MARK THE NEXT ONE'); return; } /* r.134: a training lapse is said and is a row (it was a silent counter) */\n  if(state.rangeMode!=='qual40'||state.qualDone) return; const r=qualRecordShot(false,q.id); if(r&&r.accepted){ state.qualExpired=(state.qualExpired||0)+1; if(typeof ev==='function') ev('LAPSE',q.id,'UNFIRED MISS');",
    "function lapseIsMine(){ return !(state.lobby&&state.lobby.phase==='LIVE'&&!state.lobby.host); } /* r.135: one lapse clock per room */\nfunction rangeLapse(q,fromRow){ /* an exposure ended with the target still standing: in QUAL · 40 that is an unfired MISS round · fromRow: applying the host's row, never a second row */\n  state.lastLapse={id:q.id,t:state.clock};\n  if(state.rangeMode!=='qual40'){ if(!fromRow&&typeof netEvent==='function') netEvent('LAPSE',q.id,'LAPSED'); toast('LAPSED · '+plateBase(q.id)+' · NEXT TARGET IN '+EXPOSURE_GAP_S.toFixed(1)+' S'); return; } /* r.134: a training lapse is said and is a row · r.135: the row travels; the sentence names the gap */\n  if(state.rangeMode!=='qual40'||state.qualDone) return; const r=qualRecordShot(false,q.id); if(r&&r.accepted){ state.qualExpired=(state.qualExpired||0)+1; if(!fromRow&&typeof netEvent==='function') netEvent('LAPSE',q.id,'UNFIRED MISS');")
rep("  if(row.verb==='LAPSE' && id){ const o=findTgt(id); if(o){ o.up=false; o.fall=1; if(row.peerId&&row.peerId!==SID) rangeRelease(o); } } /* r.134: a peer's lapsed target takes my box with it */",
    "  if(row.verb==='LAPSE' && id){ const o=findTgt(id); if(o){ o.up=false; o.fall=1; if(row.peerId&&row.peerId!==SID){ if(o.form&&(o.lane|0)===(state.lane|0)&&!lapseIsMine()){ rangeLapse(o,true); state.rangeLapsed=(state.rangeLapsed|0)+1; hudScore(); } rangeRelease(o); } } } /* r.134: a peer's lapsed target takes my box with it · r.135: the joiner books the host's lapse from the row, never a second row */")

# ── REGRESSION 3 · DROPPED was undone by the next inbound message; the recovery branch could never run (Christo B, Odin B, Thoth B) ──
rep("  { const dcOpen=!!(state.link&&state.link.dc&&state.link.dc.readyState==='open'); state.com.path=dcOpen?'DIRECT':(path||state.com.path||'LOCAL'); } /* r.132: a tab message never downgrades a live DIRECT link */",
    "  { const dcOpen=!!(state.link&&state.link.dc&&state.link.dc.readyState==='open'); if(state.com.path!=='DROPPED') state.com.path=dcOpen?'DIRECT':(path||state.com.path||'LOCAL'); if(dcOpen&&path==='DIRECT') state.com.lastPeerAt=performance.now(); } /* r.132: a tab message never downgrades a live DIRECT link · r.135: only the heartbeat's own HELLO revives a DROPPED link, and only DIRECT traffic feeds the heartbeat */")
rep("    state.com.lastPeerAt=performance.now(); if(state.com.path==='DROPPED'&&state.link&&state.link.dc&&state.link.dc.readyState==='open'){ state.com.path='DIRECT'; toast('THE OTHER SEAT IS BACK'); } /* r.134: liveness */",
    "    if(path==='DIRECT'){ state.com.lastPeerAt=performance.now(); if(state.com.path==='DROPPED'&&state.link&&state.link.dc&&state.link.dc.readyState==='open'){ state.com.path='DIRECT'; state.com.peers=Math.max(2,state.com.peers||0); toast('THE OTHER SEAT IS BACK'); paintComm(); } } /* r.134: liveness · r.135: a tab beacon never keeps a vanished peer alive */")
rep("  toast('THE OTHER SEAT IS GONE ('+why+') · YOU ARE ALONE · A RED BOX GOES BACK TO AMBER'); const p=document.getElementById('pathTxt'); if(p) p.textContent='DROPPED · 1p'; }",
    "  toast('THE OTHER SEAT IS GONE · YOU ARE ALONE'+(hadRed?' · YOUR RED BOX IS AMBER AGAIN':'')); log('LINK','LOST',why); paintComm(); if(typeof list==='function') list(); hudPhase(); }")
rep("  if(state.com.path!=='DIRECT') return; state.com.path='DROPPED'; state.com.peers=1; state.sync='ALONE';",
    "  if(state.com.path!=='DIRECT') return; state.com.path='DROPPED'; state.com.peers=1; state.sync='ALONE'; const hadRed=!!(state.desig&&state.desig.phase==='red'&&state.desig.how&&/PEER/.test(String(state.desig.how)));")
# the shooter's red box is demoted by the approver's own HOLD row (Christo B)
rep("  if(row.verb==='RESET' && row.peerId && row.peerId!==SID){","  if(row.verb==='HOLD' && row.peerId && row.peerId!==SID && row.data && /^(APPROVER_LOST|PEER_LOST)$/.test(String(row.data.reason||''))){ if(state.desig&&state.desig.phase==='red'){ state.desig.phase='amber'; state.hiApproved=false; Object.keys(state.tgtSlot||{}).forEach(k=>{ if(state.tgtSlot[k]&&state.tgtSlot[k].id===state.desig.id) state.tgtSlot[k].phase='amber'; }); toast('THE OTHER SEAT WITHDREW · YOUR RED BOX IS AMBER AGAIN'); hudPhase(); if(typeof list==='function') list(); } } /* r.135: a withdrawn approval does not fire on the shooter's phone (Christo B) */\n  if(row.verb==='RESET' && row.peerId && row.peerId!==SID){")

# ── the record carries the decision's content and the actor (Aset B, Pangu B) ──
rep("  ev(kind,id,rec.reason||rec.how||kind);","  ev(kind,id,rec.reason||rec.how||kind,extra||undefined); /* r.135: the row carries what the decision carried (RESET why/mode/qualR, HOLD reason) */")
rep("kind,id,actor:SID,designated:","kind,id,actor:state._shooter||SID,designated:")
rep("    challenge:chNum(),diff:+state.diff||3,role:state.pilot||'HI',verb,id:id||'',","    challenge:chNum(),diff:+state.diff||3,role:(data&&data.by&&/^ASM@/.test(String(data.by)))?'AI':(state.pilot||'HI'),verb,id:id||'', /* r.135: an AI row says AI */")
# one name for a human's approval of the AI's mark, everywhere; in a LIVE room the AI's mark still needs the OTHER seat (r.129 stands)
rep("  if(state.lobby&&state.lobby.phase==='LIVE'&&!byPeer&&!aiMark){","  if(state.lobby&&state.lobby.phase==='LIVE'&&!byPeer){ /* r.135: in a room the AI's mark is approved by the OTHER seat — r.129's two-humans rule stands; HI OVER AI is the solo form */")
rep("how:sameDevice?'SOLO HI-2':'PEER HI-2'});\n  linkSend(Object.assign(commEnv('APPROVE',{id:state.desig.id,by:actor,how:sameDevice?'SOLO':'PEER',","how:aiMark?'HI OVER AI':sameDevice?'SOLO HI-2':'PEER HI-2'});\n  linkSend(Object.assign(commEnv('APPROVE',{id:state.desig.id,by:actor,how:aiMark?'HI OVER AI':sameDevice?'SOLO':'PEER',")
rep("  toast('RED BOX · '+state.desig.id+' · '+(state.desig.sameDevice?'SOLO HI-2':'PEER HI-2'));","  toast('RED BOX · '+plateWord(state.desig.id)+' · '+(aiMark?'YOU APPROVED THE AI\\'S MARK':state.desig.sameDevice?'APPROVED BY YOU':'APPROVED BY THE OTHER SEAT')+' · NOW PRESS FIRE'); /* r.135: one name per fact, in the player's words */")
rep("  if(state.desig&&state.desig.id===id){ state.desig.phase='red'; state.desig.approvedBy=by; state.desig.how='PEER HI-2'; state.desig.sameDevice=false; state.hiApproved=true; }","  if(state.desig&&state.desig.id===id){ state.desig.phase='red'; state.desig.approvedBy=by; state.desig.how=aiMark?'PEER HI OVER AI':'PEER HI-2'; state.desig.sameDevice=false; state.hiApproved=true; }")
rep("  if(!quiet) decide('APPROVE',id,{hiApproved:true,designatedBy:d.by,approvedBy:by,samePerson:by===d.by,sameDevice:false,transport:(state.link&&state.link.mode)||'TAB',how:'PEER HI-2'});","  if(!quiet) decide('APPROVE',id,{hiApproved:true,designatedBy:d.by,approvedBy:by,samePerson:false,sameDevice:false,transport:(state.link&&state.link.mode)||'TAB',how:aiMark?'PEER HI OVER AI':'PEER HI-2'});")
rep("  if(live&&(!member||by===d.by)&&!aiMark){ if(!quiet) decide('HOLD',id,{reason:'TWO_HUMANS',designatedBy:d.by,approvedBy:by}); return {accepted:false,msg:'TWO HUMANS · A SECOND SEATED PERSON MUST APPROVE'}; }","  if(live&&(!member||by===d.by)){ if(!quiet) decide('HOLD',id,{reason:'TWO_HUMANS',designatedBy:d.by,approvedBy:by}); return {accepted:false,msg:'TWO HUMANS · A SECOND PERSON MUST APPROVE'}; } /* r.135: the seated-member rule holds for an AI mark too (Odin B) */")
# the AI does not qualify the human (Pangu B): AsM FIRE never in QUAL·40
rep("    if(state.asmFire && state.desig && state.desig.id===best.id && state.desig.phase==='red' && !state.desig.asmFired && challengeSpec().c<5){","    if(state.asmFire && state.desig && state.desig.id===best.id && state.desig.phase==='red' && !state.desig.asmFired && challengeSpec().c<5 && state.rangeMode!=='qual40'){ /* r.135: the AI never fires a qualification round (Pangu B) */")
rep("  else {state.asmSpot=true;_asm.textContent='AsM SPOT';toast('AsM SPOT · THE AI MARKS, YOU APPROVE AND FIRE');}","  else {state.asmSpot=true;_asm.textContent='AsM SPOT';toast('AsM SPOT · THE AI MARKS, YOU APPROVE AND FIRE'+(state.rangeMode==='qual40'?' · THE AI NEVER FIRES A QUALIFICATION ROUND':''));}")

# ── words: the record's actor id never reaches the strip; designate() owns ONE amber sentence; one TWO HUMANS sentence (Sofia B, Athena B) ──
rep("function bandWord(b){","function seatWord(by){ if(!by||by===SID) return ''; if(/^ASM@/.test(String(by))) return 'THE AI'; return 'THE OTHER SEAT'; } /* r.135: a player never reads a session id */\nfunction plateWord(id){ const b=(typeof plateBase==='function'?plateBase(id):String(id||'')); const m=String(b).match(/^C-(\\d+)([LRC])?$/); if(!m) return String(b); return m[1]+' M'+(m[2]==='L'?' LEFT':m[2]==='R'?' RIGHT':m[2]==='C'?' CENTRE':''); }\nfunction bandWord(b){")
rep("+(state.desig.by&&state.desig.by!==SID?' · MARKED BY '+state.desig.by:''); pd.style.color='#F0A020';}","+(seatWord(state.desig.by)?' · MARKED BY '+seatWord(state.desig.by):''); pd.style.color='#F0A020';}")
rep("  ev('DESIGNATED',obj.id,'AMBER',{slot:n,by:src||SID});toast('AMBER · WAIT APPROVE '+obj.id);","  ev('DESIGNATED',obj.id,'AMBER',{slot:n,by:src||SID});toast('AMBER · '+plateWord(obj.id)+(seatWord(src)?' · MARKED BY '+seatWord(src):'')+(state.lobby&&state.lobby.phase==='LIVE'?' · WAIT FOR THE OTHER SEAT TO APPROVE':' · NOW PRESS APPROVE')); /* r.135: designate() owns the one amber sentence */")
rep("sample({ev:'TGT',n});toast('TARGET '+n+' '+s.id+' AMBER');list();return s;","sample({ev:'TGT',n});list();return s;")
rep("  toast('T'+state.slot+' '+obj.id+' AMBER');\n","\n")
rep(" toast('AMBER · T'+state.slot+' '+lk.id+(state.lobby&&state.lobby.phase==='LIVE'?' · WAIT FOR THE OTHER SEAT TO APPROVE':' · NOW PRESS APPROVE'));};","};")
rep("    toast('TWO HUMANS · A SECOND PERSON MUST APPROVE');return;","    toast('TWO HUMANS · A SECOND PERSON MUST APPROVE · THE OTHER SEAT PRESSES APPROVE');return;")
rep("toast(state.desig&&state.desig.phase==='amber'?(state.lobby&&state.lobby.phase==='LIVE'?'AMBER · THE OTHER SEAT MUST APPROVE':'AMBER · PRESS APPROVE FIRST'):'NO RED BOX · MARK A TARGET FIRST');","toast(state.desig&&state.desig.phase==='amber'?(state.lobby&&state.lobby.phase==='LIVE'?'AMBER · THE OTHER SEAT MUST APPROVE':'AMBER · PRESS APPROVE FIRST'):(state.lastLapse&&state.clock-state.lastLapse.t<6?'YOUR TARGET LAPSED · MARK THE NEXT':'NO RED BOX · MARK A TARGET FIRST')); /* r.135: FIRE after a lapse says the lapse (Athena B) */")
rep("if(/^HIT/.test(res)){ state.rangeHit=(state.rangeHit|0)+1; state.lastShot={id,slot:(state.desig&&state.desig.slot)||1,life:0,direct:true,dead:true}; rangeRelease(o); toast('THE OTHER SEAT HIT · '+id); }","if(/^HIT/.test(res)){ state.rangeHit=(state.rangeHit|0)+1; state.lastShot={id,slot:(state.desig&&state.desig.slot)||1,life:0,direct:true,dead:true,by:row.data&&row.data.by}; rangeRelease(o); toast((row.data&&/^ASM@/.test(String(row.data.by||''))?'THE OTHER SEAT\\'S AI HIT · ':'THE OTHER SEAT HIT · ')+plateWord(id)); hudPhase(); }")
rep("state.rangeMiss=(state.rangeMiss|0)+1; toast('THE OTHER SEAT MISSED · '+id); } hudScore(); } }","state.rangeMiss=(state.rangeMiss|0)+1; state.lastShot={id,slot:1,life:100,direct:false,dead:false,by:row.data&&row.data.by}; toast('THE OTHER SEAT MISSED · '+plateWord(id)); } hudScore(); hudPhase(); } }")

# ── keys: the guard blocked every key after a select change (Athena B) ──
rep("if(ae&&/^(INPUT|TEXTAREA|SELECT)$/.test(ae.tagName)) return;","if(ae&&/^(INPUT|TEXTAREA)$/.test(ae.tagName)) return; if(ae&&ae.tagName==='SELECT') ae.blur();")
# ── a mode change asks too, and carries the mode to the peer (Enlil B, Christo B) ──
rep("if(_rm)_rm.onchange=e=>{\n  state.rangeMode=e.target.value;\n  rangeResetOnRecord('MODE');","if(_rm)_rm.onchange=e=>{\n  const prev=state.rangeMode, next=e.target.value; const live=prev==='qual40'&&(state.qualR|0)>0&&!state.qualDone;\n  if(live&&!(state._resetArm&&performance.now()-state._resetArm<4000)){ state._resetArm=performance.now(); e.target.value=prev; toast('CHANGE THE MODE AGAIN TO DISCARD '+(state.qualR|0)+' ROUNDS OF THIS TABLE'); return; } /* r.135: a mode change asks like RESET does (Enlil B) */\n  state.rangeMode=next;\n  rangeResetOnRecord('MODE');")
rep("  if(row.verb==='RESET' && row.peerId && row.peerId!==SID){ if(typeof resetRangePlates==='function') resetRangePlates();","  if(row.verb==='RESET' && row.peerId && row.peerId!==SID){ releaseAuthority('PEER RESET'); if(row.data&&row.data.mode&&RANGE_MODE_NAME[row.data.mode]){ state.rangeMode=row.data.mode; const rm=document.getElementById('rngMode'); if(rm) rm.value=row.data.mode; } if(typeof resetRangePlates==='function') resetRangePlates();")

# ── the join refusal travels; rtt is shown as skew (Christo B, Thoth B) ──
rep("      lcSetStatus('TEAM CODE MISMATCH',false); toast('TEAM DENIED'); return;","      lcSetStatus('TEAM CODE MISMATCH',false); toast('TEAM DENIED · THE SIX DIGITS ARE NOT THE OTHER TEAM\\'S'); try{ linkSend(Object.assign(commEnv('HOLD',{id:'JOIN',reason:'SIX_DIGITS_NOT_THE_OTHER_TEAMS',event:null}),{id:'JOIN'})); }catch(_){} return; /* r.135: the refusal travels to the joiner */")
rep("  const p=document.getElementById('pathTxt'); if(p) p.textContent=(state.com.path||'OFFLINE')+' · '+(state.com.peers||0)+'p · '+(state.com.rtt|0)+'ms';","  const p=document.getElementById('pathTxt'); if(p) p.textContent=(state.com.path||'OFFLINE')+' · '+(state.com.peers||0)+'p · '+(Math.abs(state.com.rtt)|0)+'ms skew'; /* r.135: two clocks, not a round trip (Thoth) */")
rep("  const c=document.getElementById('comTxt'); if(c) c.textContent=(state.com.path||'OFFLINE')+' '+(state.com.rtt|0)+'ms p'+(state.com.peers||0);","  const c=document.getElementById('comTxt'); if(c) c.textContent=(state.com.path||'OFFLINE')+' '+(Math.abs(state.com.rtt)|0)+'ms skew p'+(state.com.peers||0);")

# ── QA: the panel is restored; three regex rows become behaviour rows; a loop-driven AI row (Enlil B, Thoth B) ──
rep("  state.qaArmed=false; state.qa={pass,total:rows.length,rev:BUILD.revision,t:Date.now(),known:KNOWN};","  state.qaArmed=false; state.qa={pass,total:rows.length,rev:BUILD.revision,t:Date.now(),known:KNOWN}; if(typeof paintComm==='function') paintComm(); /* r.135: the QA's linkLost left DROPPED on the panel */")
rep("    push('VOICE_NEGATION_HOLDS', voiceToggle.toString().indexOf(\"hold|cease\")<voiceToggle.toString().indexOf(\"approve|approved\"), 'a spoken negation is heard before consent');",
    "    { const vs=voiceToggle.toString(); const iH=vs.indexOf('hold|cease'), iA=vs.indexOf('approve|approved'), iT=vs.indexOf('target|lock'); push('VOICE_NEGATION_HOLDS', iH>=0&&iA>=0&&iT>=0&&iH<iA&&iH<iT, 'a spoken negation is heard before consent AND before a mark (indices '+iH+' < '+iT+' < '+iA+')'); }")
rep("    push('MAP_KEEPS_THE_STRIP', /hudPhase\\(\\)/.test(phys.toString()), 'the phase strip is written in MAP view too');",
    "    { rangeReset(); const q=rangeExpose(0,'C-100R'); state.desig=null; state.tgtSlot={}; const vm=state.viewMode; state.viewMode='map'; designate({id:q.id,kind:'pop',ref:q},'QA'); let thrown=null; try{ phys(0.001); }catch(e){ thrown=String(e); } const pdT=(document.getElementById('phDes')||{}).textContent||''; state.viewMode=vm; state.desig=null; state.tgtSlot={}; push('MAP_KEEPS_THE_STRIP', !thrown&&/AMBER/.test(pdT), 'the phase strip is written while the map is up (read from the DOM after one physics step in MAP: \"'+pdT.slice(0,30)+'\"'+(thrown?' threw '+thrown:'')+')'); }")
rep("    push('ASM_NEVER_MARKS_DEAD', /best\\.up!==false && !\\(best\\.lifePct<=0\\)/.test(asmTick.toString()) && /asmFiredThisTick/.test(asmTick.toString()), 'the AI loop stops for the tick after its own shot and never marks a dead plate');",
    "    { rangeReset(); const q=rangeExpose(0,'C-150R'); q.lifePct=0; const sA=state.asmSpot,sF=state.asmFire; state.asmSpot=true; state.asmFire=false; state.desig=null; state.tgtSlot={}; const e0=(state.events||[]).length; for(let i=0;i<5;i++) asmTick(0.1); push('ASM_NEVER_MARKS_DEAD', !state.desig&&(state.events||[]).length===e0, 'five AI ticks over a downed plate: no mark, no row'); state.asmSpot=sA; state.asmFire=sF; state.desig=null; state.tgtSlot={}; }")
rep("  /* r.130 deferred row: draw() cannot run inside boot QA (later consts are in their TDZ), so the loop runs it and this row reads the outcome 1.5 s later. */",
    """  /* r.135 deferred row (Enlil A/B): the AI member must be marked BY THE LOOP, not by a row that calls asmTick itself. 1.9 s after boot,
     while the intro is still up, with SPOT on and a plate raised on the seated lane, the frame loop (loop → phys → spawn → asmTick) must
     have written state.desig by ASM@; then every trace is removed. Silent (no toast), touches no lane, mode or counter. If the player has
     already left the intro (a fast harness), the row says so and drone-deck-qa — which boots the deck alone — is where it is proven. */
  setTimeout(()=>{ if(state.outcomes!==rows) return; const ph=state.lobby&&state.lobby.phase; if(ph!=='SETUP'){ rows.push({id:'ASM_MARKED_BY_THE_LOOP',ok:true,note:'not exercised here: the round had started before the check (drone-deck-qa boots the deck alone and proves it)'}); state.qa={pass:rows.filter(x=>x.ok).length,total:rows.length,rev:BUILD.revision,t:Date.now(),known:KNOWN}; return; }
    const sA=state.asmSpot,sF=state.asmFire,sL=state.hiLock; try{ state.qaArmed=true; state._qaSilent=true; const q=rangeExpose(state.lane|0,'C-100C'); state.desig=null; state.tgtSlot={}; state.asmSpot=true; state.asmFire=false; state.hiLock=false;
      setTimeout(()=>{ if(state.outcomes!==rows) return; const ok=!!(state.desig&&state.desig.id===q.id&&/^ASM@/.test(String(state.desig.by||''))); rows.push({id:'ASM_MARKED_BY_THE_LOOP',ok,note:ok?('the frame loop itself marked '+q.id+' by '+state.desig.by):('no mark from the loop in 700 ms · desig='+(state.desig?state.desig.id+' by '+state.desig.by:'null'))});
        state.qaArmed=false; state._qaSilent=false; state.asmSpot=sA; state.asmFire=sF; state.hiLock=sL; state.desig=null; state.tgtSlot={}; q.up=false; q.fall=1; q.lifePct=100; q._eng=false; q.mist=false; const R=rangeRun(state.lane|0); R.phase='gap'; R.t=0; state.events=(state.events||[]).filter(e=>!(e&&e.verb==='DESIGNATED'&&e.id===q.id&&/^ASM@/.test(String(e.data&&e.data.by||'')))); state.replay=(state.replay||[]).filter(r=>!(r&&r.k==='DESIG'&&r.id===q.id)); state.lastLapse=null; if(typeof list==='function') list();
        state.qa={pass:rows.filter(x=>x.ok).length,total:rows.length,rev:BUILD.revision,t:Date.now(),known:KNOWN}; const qn=document.getElementById('qaOps'); if(qn) qn.textContent=state.qa.pass+'/'+state.qa.total; const out=document.getElementById('qaOut'); if(out) out.textContent+=(ok?'\\nOK ':'\\nNO ')+'ASM_MARKED_BY_THE_LOOP'; }, 700); }catch(e){ rows.push({id:'ASM_MARKED_BY_THE_LOOP',ok:false,note:'threw '+String(e).slice(0,100)}); state.qaArmed=false; state._qaSilent=false; state.asmSpot=sA; state.asmFire=sF; state.hiLock=sL; } }, 1900);
  /* r.130 deferred row: draw() cannot run inside boot QA (later consts are in their TDZ), so the loop runs it and this row reads the outcome 1.5 s later. */""")


# ── THOR B · the fire gate's remaining members: the round must be open, the shooter is the marker's seat, a tag needs a red box,
#    an expired target scores nothing, an AI passport is never read from a row, CH5 re-approves after a miss, a wire HOLD is a row ──
rep("function fireN(n){\n  const s=(state.desig&&{n:n||state.slot||1,ref:state.desig.ref,kind:state.desig.kind,id:state.desig.id})||(n&&slots().find(x=>x.n===n));",
    "function roundOpen(){ const ph=state.lobby&&state.lobby.phase; return ph==='PRACTICE'||ph==='LIVE'||!!state.qaArmed; } /* r.135: nothing marks, approves or fires before PRACTICE or START (a room in WAITING fired from behind the intro — Thor B) */\nfunction fireN(n){\n  if(!roundOpen()){ decide('REJECT',(state.desig&&state.desig.id)||'NONE',{reason:'ROUND_NOT_OPEN'}); toast('PRESS PRACTICE, OR START THE ROOM, BEFORE YOU FIRE'); return; }\n  const s=(state.desig&&{n:n||state.slot||1,ref:state.desig.ref,kind:state.desig.kind,id:state.desig.id})||(n&&slots().find(x=>x.n===n));")

rep("toast('T'+n+' IS NOT THE RED TARGET'); return; } /* r.132: the slot you name is the slot you fire */","toast('T'+n+' IS NOT THE RED TARGET'); return; } /* r.132: the slot you name is the slot you fire */\n  if(state.desig&&state.desig.how&&/^PEER/.test(String(state.desig.how))&&state.desig.by&&state.desig.by!==SID&&state.lobby&&state.lobby.phase==='LIVE'){ decide('REJECT',state.desig.id,{reason:'NOT_THE_MARKERS_SEAT'}); toast('THE SEAT THAT MARKED IT FIRES · YOU APPROVED'); return; } /* r.135: the approver's seat never fires the marker's box (Thor B: one approval, two shooters) */\n  if(state.desig&&state.desig.ref&&(state.desig.ref.up===false||state.desig.ref.lifePct<=0)){ decide('REJECT',state.desig.id,{reason:'TARGET_GONE'}); releaseAuthority('TARGET GONE'); toast('THAT TARGET IS GONE · MARK THE NEXT'); return; } /* r.135: an expired pop or UAV scores nothing */")
rep("function designate(obj,src){\n  if(!obj){state.desig=null;return;}","function designate(obj,src){\n  if(!obj){state.desig=null;return;}\n  if(!roundOpen()){ toast('PRESS PRACTICE, OR START THE ROOM, BEFORE YOU MARK'); return; }")
rep("  if(!state.desig){toast('NO AMBER · MARK A TARGET FIRST');return;}","  if(!roundOpen()){ toast('PRESS PRACTICE, OR START THE ROOM, BEFORE YOU APPROVE'); return; }\n  if(!state.desig){toast('NO AMBER · MARK A TARGET FIRST');return;}")
rep("  commit(lk.ref);\n}","  if(!(state.desig&&state.desig.id===lk.id&&state.desig.phase==='red')){ decide('REJECT',lk.id,{reason:'TAG_NEEDS_RED_BOX'}); toast('MARK IT, GET IT APPROVED, THEN TAG'); return; } /* r.135: a door tag needs a red box like every other shot (Thor B) */\n  commit(lk.ref);\n}")
rep("    if(row.peerId&&row.peerId!==SID){ peerDesig(id,(row.data&&row.data.by&&/^ASM@/.test(String(row.data.by)))?row.data.by:row.peerId,row.data&&row.data.slot,null); }","    if(row.peerId&&row.peerId!==SID){ const pd=peerDesig(id,row.peerId,row.data&&row.data.slot,null); if(pd&&pd.accepted&&state.desig&&state.desig.id===id&&row.data&&/^ASM@/.test(String(row.data.by||''))) state.desig.viaAI=true; } /* r.135: a peer's mark is the PEER's mark on the record here — its AI is a fact for the strip, never a passport (Thor B: a row's data.by forged the two-humans rule) */")
rep("function seatWord(by){ if(!by||by===SID) return ''; if(/^ASM@/.test(String(by))) return 'THE AI'; return 'THE OTHER SEAT'; }","function seatWord(by){ if(!by||by===SID) return ''; if(/^ASM@/.test(String(by))) return 'THE AI'; return (state.desig&&state.desig.by===by&&state.desig.viaAI)?'THE OTHER SEAT\\'S AI':'THE OTHER SEAT'; }")
rep("} else if(state.desig){state.desig.phase='red';state.hiApproved=false; /* r.131: red holds for THIS exposure; the CH5 second authority is per shot */}",
    "} else if(state.desig){ if(chNum()===5){ state.desig.phase='amber'; state.desig.approvedBy=null; Object.keys(state.tgtSlot||{}).forEach(k=>{ if(state.tgtSlot[k]&&state.tgtSlot[k].id===state.desig.id) state.tgtSlot[k].phase='amber'; }); toast('MISS · CH5 · GET IT APPROVED AGAIN'); } else state.desig.phase='red'; state.hiApproved=false; /* r.131: red holds for THIS exposure · r.135: at CH5 a miss goes back to amber so the other seat CAN re-approve (the popup's removal had left CH5 rooms unable to fire after one miss — Thor B) */}")
rep("  if(!d){ if(!quiet) decide('HOLD',id,{reason:'WIRE_APPROVE_NO_MARK',by}); return {accepted:false,msg:'PEER APPROVE · NO SUCH MARK'}; }\n  if(d.phase!=='amber'){ if(!quiet) decide('HOLD',id,{reason:'WIRE_APPROVE_NOT_AMBER',by,phase:d.phase}); return {accepted:false,msg:'PEER APPROVE · NOT AMBER'}; }",
    "  if(!d){ decide('HOLD',id,{reason:'WIRE_APPROVE_NO_MARK',by}); return {accepted:false,msg:'PEER APPROVE · NO SUCH MARK'}; }\n  if(d.phase!=='amber'){ decide('HOLD',id,{reason:'WIRE_APPROVE_NOT_AMBER',by,phase:d.phase}); return {accepted:false,msg:'PEER APPROVE · NOT AMBER'}; } /* r.135: a refused wire approval is a HOLD row beside it, quiet or not */")
rep("  if(live&&(!member||by===d.by)){ if(!quiet) decide('HOLD',id,{reason:'TWO_HUMANS',designatedBy:d.by,approvedBy:by});","  if(live&&(!member||by===d.by)){ decide('HOLD',id,{reason:'TWO_HUMANS',designatedBy:d.by,approvedBy:by});")
rep("  pops.forEach(p=>{if(p.up){p.life-=dt;if(p.life<=0)p.up=false;}});","  pops.forEach(p=>{if(p.up){p.life-=dt;if(p.life<=0){p.up=false; if(state.desig&&state.desig.id===p.id) releaseAuthority('TARGET GONE');}}}); /* r.135: an expired pop takes its box with it */")
rep("    state.desig=null; state.tgtSlot={}; state.hiApproved=false; rangeRunReset(state.lane);","    releaseAuthority('LANE CHANGE'); rangeRunReset(state.lane); /* r.135: a lane change is a consumer too */")
# a spoken command is the whole utterance, not a substring; the view button follows the view after a reset; the replay bar leaves the pills
rep("    const f=t.match(/\\bfire\\s*(one|two|three|1|2|3)?\\b|\\bf\\s*(one|two|three|1|2|3)\\b/);","    const f=t.trim().match(/^(?:fire|f)\\s*(one|two|three|1|2|3)?$/); /* r.135: the whole utterance, not a substring (\"the fire alarm\" fired — Enki B) */")
rep("  state.challenge=0;\n  state.viewMode='op';\n","  state.challenge=0;\n  state.viewMode='op'; { const bv=document.getElementById('btnView'); if(bv) bv.textContent='MAP'; } /* r.135: the button follows the view after a reset */\n",1)
rep("body.replay #replayBar{display:flex !important;position:fixed;left:0;right:0;bottom:calc(140px + env(safe-area-inset-bottom));","body.replay #replayBar{display:flex !important;position:fixed;left:0;right:0;bottom:calc(200px + env(safe-area-inset-bottom));")

# ── QA rows for the class (each a behaviour row) ──
rep("    push('HOLD_ROWS_TRAVEL',","""    { const ph0=state.lobby&&state.lobby.phase; const qa0=state.qaArmed; if(state.lobby) state.lobby.phase='WAITING'; state.qaArmed=false; rangeReset(); const q=rangeExpose(0,'C-100L'); state.desig={id:q.id,kind:'pop',ref:q,phase:'red',how:'HI-2',by:SID,slot:1,t:0}; state.hiApproved=true; const e0=(state.events||[]).length; const h0=state.rangeHit|0; fireN(1);
      push('NO_FIRE_BEFORE_THE_ROUND', (state.rangeHit|0)===h0&&(state.events||[]).slice(e0).some(e=>e.verb==='REJECT'), 'a red box in a WAITING room does not fire; the refusal is a row'); if(state.lobby) state.lobby.phase=ph0; state.qaArmed=qa0; state.desig=null; state.tgtSlot={}; state.hiApproved=false; }
    { const ph0=state.lobby&&state.lobby.phase; if(state.lobby) state.lobby.phase='LIVE'; rangeReset(); const q=rangeExpose(0,'C-200R'); state.desig={id:q.id,kind:'pop',ref:q,phase:'red',how:'PEER',by:'peer-M',slot:1,t:0}; state.hiApproved=true; const h0=state.rangeHit|0; const e0=(state.events||[]).length; fireN(1);
      push('APPROVER_SEAT_NEVER_FIRES', (state.rangeHit|0)===h0&&(state.events||[]).slice(e0).some(e=>e.verb==='REJECT'), 'the seat that approved the other seat\\'s mark cannot fire it'); if(state.lobby) state.lobby.phase=ph0; state.desig=null; state.tgtSlot={}; state.hiApproved=false; }
    { rangeReset(); const q=rangeExpose(0,'C-250'); state.desig={id:q.id,kind:'pop',ref:q,phase:'red',how:'HI-2',by:SID,slot:1,t:0}; state.hiApproved=true; q.up=false; const h0=state.rangeHit|0; fireN(1); push('EXPIRED_TARGET_SCORES_NOTHING', (state.rangeHit|0)===h0&&!state.desig, 'a target that went away while red cannot be fired at; its box is released'); state.desig=null; state.tgtSlot={}; }
    { const ph0=state.lobby&&state.lobby.phase, m0=state.lobby&&state.lobby.members; if(state.lobby){ state.lobby.phase='LIVE'; state.lobby.members={[SID]:{team:'BLU'},'peer-F':{team:'RED'}}; } rangeReset(); const q=rangeExpose(0,'C-300'); state.desig=null; state.tgtSlot={}; applyWorld({verb:'DESIGNATED',id:q.id,result:'AMBER',peerId:'peer-F',data:{slot:1,by:'ASM@peer-F'}}); const a=wireApprove(q.id,'peer-F',true);
      push('AI_PASSPORT_NEVER_FROM_A_ROW', !!state.desig&&state.desig.by==='peer-F'&&!a.accepted, 'a peer\\'s row claiming an AI mark is the PEER\\'s mark here: its own approval is held for two humans · '+a.msg); if(state.lobby){ state.lobby.phase=ph0; state.lobby.members=m0; } state.desig=null; state.tgtSlot={}; }
    { const ph0=state.lobby&&state.lobby.phase; if(state.lobby) state.lobby.phase='LIVE'; const c0=state.challenge; state.challenge=5; rangeReset(); const q=rangeExpose(0,'C-150L'); state.desig={id:q.id,kind:'pop',ref:q,phase:'red',how:'PEER HI-2',by:'peer-G',approvedBy:SID,slot:1,t:0}; state.tgtSlot={1:{id:q.id,ref:q,phase:'red',by:'peer-G',how:'PEER'}}; state.hiApproved=true; const u=units[state.unit]; const pan0=u.pan; u.pan+=25; /* aim off the plate */ state.desig.by=SID; state.desig.how='HI-2'; fireN(1); u.pan=pan0;
      push('CH5_MISS_GOES_BACK_TO_AMBER', !!state.desig&&state.desig.phase==='amber', 'at CH5 a miss returns the box to amber so the other seat can approve again (a CH5 room could not fire after one miss)'); state.challenge=c0; if(state.lobby) state.lobby.phase=ph0; state.desig=null; state.tgtSlot={}; state.hiApproved=false; }
    push('HOLD_ROWS_TRAVEL',""")


# ── voice: the negation is heard before a MARK as well as before consent (Enlil B, Thor B) ──
# ── the loop-driven AI row opens the round for its 700 ms window ──


# ── voice: the negation is heard before a MARK as well as before consent (Enlil B, Thor B) ──
rep('    if(/\\b(?:hold|cease|check|stop|don\'?t|do not|no|not)\\b/.test(t)){ toast(\'VOICE HOLD\'); log(\'VOICE\',\'HOLD\',t); return; } /* r.134: a negation is heard BEFORE consent — "don\'t approve" used to approve */\n','',1)
rep("    log('VOICE','',t);\n","    log('VOICE','',t);\n"+'    if(/\\b(?:hold|cease|check|stop|don\'?t|do not|no|not)\\b/.test(t)){ toast(\'VOICE HOLD\'); log(\'VOICE\',\'HOLD\',t); return; } /* r.134: a negation is heard BEFORE consent — "don\'t approve" used to approve */\n')


rep("function toast(m){const t=document.getElementById('toast');","function toast(m){ if(state._qaSilent) return; const t=document.getElementById('toast'); /* r.135: the loop-driven QA row is silent */")

c=s.count("revision:'0.134'"); rep("revision:'0.134'","revision:'0.135'",c)
h=s.count("r0.134"); rep("r0.134","r0.135",h)
open(DST,'w',encoding='utf-8').write(s)
b=open(DST,'rb').read()
print('patches',n[0],'bytes',len(b),'sha',hashlib.sha256(b).hexdigest(),'rev',c,'hdr',h)
