// GENERATED by scripts/financial-render.mjs from docs/financial-2525/financial-2525.v.000.json — do not hand-edit.
// The app imports THIS, never the docs file: a static export may not reach outside the frontend root, and a
// typed module is checked by tsc where a raw JSON import is not. `node scripts/financial-render.mjs --check`
// (in test:ci) refuses any drift between the two, so there is still exactly one editable source.
export interface FinancialCrsRow {
  id: string; title: string; statement: string; in: string; out: string; section: string; uwf: string[];
  phase: string; mode: string; metric: string; verify: string; dtm: string; stretch: string; status: string;
}
export interface FinancialDecision { id: string; decision: string; status: string; basis: string }
export interface FinancialReview { round: number; revision: string; subject: string; lenses: number; record: string; sha256?: string; commit?: string; status: string }
export interface FinancialDomain {
  project: { name: string; family: string; version: string; revision: string; stamp: string; stampPrefix: string;
             handoff: string; handoffSha256: string; handoffHistory?: { sha256: string; date: string; note: string }[];
             ledger: string; route: string; disclaimer: string; mode: string; phase: string; tenant: string };
  revisions: { revision: string; date: string; kind: string; why: string; commit: string; shipped?: string }[];
  mot: Record<string, unknown> & { law: string; full: string; payMotDays: number; ltu: Record<string, number> };
  calendar: Record<string, unknown> & { quarterDays: number; gridDays: number; downDay: number; personalFrames: number[] };
  accrual: { law: string; holdHours: number; states: string[]; invariants: string[]; source: string };
  example: { amountUsd: number; postedDate: string; depositStamp: string; motDays: number; memo: string; ratePerMinUsd: number; perDayUsd: number; perHourUsd: number; perSecUsd: number; withdrawableAt3hUsd: number; note: string };
  budget: { categories: string[]; kinds: string[]; sheetSeedPer33Days: Record<string, number>; ladder: string; sheetSlips: string[]; source: string };
  tokenization: { yugCeiling: number; law: string; status: string };
  business: { status: string; grid: string; pnlLadder: string[]; escrow: string };
  crs: FinancialCrsRow[];
  decisions: FinancialDecision[];
  reviews: FinancialReview[];
  status: Record<string, string>;
}

export const FINANCIAL_DOMAIN = {
 "project": {
  "name": "Financial-2525",
  "family": "Vision • 2525 Level-3 Domain Play — the MoT Financial System",
  "version": "000",
  "revision": "0.010",
  "stamp": "v.000_r.010",
  "stampPrefix": "eXeL v0.001",
  "handoff": "docs/asks/2026-09-30_financial_2525_mot_financial_system.md",
  "handoffSha256": "7b7a9ab6412fec38e826bb338c80c85cdda5afe281666f04a2728550b890d9e5",
  "handoffHistory": [
   {
    "sha256": "5880abb0cbe60208c87073e24d9b7ec8d3b5ad807af6049fa4b68c2b5318dd6d",
    "date": "2026-09-30",
    "note": "the ask with addenda 1–6 — what r.001 was built from"
   },
   {
    "sha256": "7dc5bd9494b76064e9e349b8c353c0a520b4041c3a074f46f89577235aab49db",
    "date": "2026-09-30",
    "note": "+ addendum 7 (the ◬ ♡ 웃 Session shell as the UI/UX starting point) — r.001 shipped against this hash"
   },
   {
    "sha256": "fe4768a6a10f45ff7c406349c66ca07c6d5cba5bd71b3143fcd643f07d3fbb30",
    "date": "2026-09-30",
    "note": "+ addendum 8 (max R-CORE reuse; A.B..C behind the scenes, day · hour · minute on the chart)"
   },
   {
    "sha256": "d2d9b6e4307eed898be90c51844dbde71a9a6515fe228bac87d4da87fb42cd47",
    "date": "2026-09-30",
    "note": "+ addendum 9 (the Trinity wheel's seats: HI top · AI tokens bottom-left · SI minutes bottom-right) — r.002 built against this hash"
   },
   {
    "sha256": "c5176ce276c0ea06fbf499eea271b3f24be0f47572b3123fdab4dcbf69231f61",
    "date": "2026-09-30",
    "note": "+ addendum 10 (A.B..C IS the Earth's revolution: 3600 · 3600 · 3600) — r.003 built against this hash"
   },
   {
    "sha256": "31efe32759c5045763bd7aecbc57b2f94709934c0cdbee6248d64dda8e3fbab0",
    "date": "2026-09-30",
    "note": "+ addenda 11–13 and two clarifications (365 days = 3600 A exactly; the day ladder derived; A.B..C...D declared; Mars perihelion→perihelion on Earth hours for now; LTU tables per planet in the Admin panel — Month 91, offline Dec 31; the MoT ⇄ Clock icon toggle) — r.005 built against this hash"
   },
   {
    "sha256": "92f4caee2858c3c5f1e9a8a86e9a520872a0646f759c83b65f239d89284c44e9",
    "date": "2026-09-30",
    "note": "+ addendum 14 (\"A.B..C always\" — the notation is always A.B..C, never A.B.C; the card opens on the Clock icon with the MoT toggle) — r.005 shipped against this hash"
   },
   {
    "sha256": "6d467c4dead4f07ba45dd3141a800ec3d0bfe247aabfab8121e43e64524dae96",
    "date": "2026-09-30",
    "note": "+ addendum 15 (the web site must be https://exel-ai-polling.explore-096.workers.dev/financial-2525 — the canonical route; /main/Financial-2525 an alias) — r.005 shipped against this hash"
   },
   {
    "sha256": "0a62efd68c4afbd3b0ff2b80949713dd7e2f37cdb43477db09ec4cf766625ace",
    "date": "2026-09-30",
    "note": "+ addenda 16–17 (a category dropdown of the personal-finance elements on the transaction forms; the budget as a table with a unit toggle — $/min, day, week, month …) with the two phone screenshots — r.006 built against this hash"
   },
   {
    "sha256": "dbc66801dfb4143f48dc733f1d9d2d70339e65333b146725ca8683d3cc98aedc",
    "date": "2026-09-30",
    "note": "+ addendum 18 (the year is the EXACT revolution, \"365.25 etc.\"; the perihelion instant in Austin CST standard) — persisted 25ec03d during the r.006 gate chain; owed as r.007, not folded into r.006"
   },
   {
    "sha256": "f900715a5063928d9f80458cf77491babd624ee98567ef0f28b2fa7032218ac6",
    "date": "2026-09-30",
    "note": "+ addendum 19 (every category carries its icon — Income · Mortgage · Car · Insurance · Food · Fitness · Fun; the PERSONAL sheet photographed) — persisted 589d223 during the r.007 gate chain; owed as r.008, not folded into r.007"
   },
   {
    "sha256": "15c8e44b1db9df751ec7b3194b363c512d99650d88d127fb36bb8b9290be9f88",
    "date": "2026-09-30",
    "note": "+ addendum 20 (\"use drop down\" — the budget's unit picker, with his phone view of the r.006 capture) — persisted 756075a; folded as r.009"
   },
   {
    "sha256": "7b7a9ab6412fec38e826bb338c80c85cdda5afe281666f04a2728550b890d9e5",
    "date": "2026-09-30",
    "note": "+ addendum 21 (the unit dropdown is the full width of the panel in portrait — 'FOR PER HOUR ETC') — persisted 0f842a9; folded as r.010"
   }
  ],
  "ledger": "docs/traceability/financial-2525.ledger.json",
  "route": "/financial-2525",
  "disclaimer": "A personal pilot on the operator's own figures. Money on this surface is a RECORD of what a person typed, never advice, never a bank; the cloud half is best-effort and says so.",
  "mode": "Manual (MODE_R-CORE_SPEC: no commit without a named Human-Authority event)",
  "phase": "pilot",
  "tenant": "personal — the business frame is declared and tested only after the personal framework has received feedback (operator addendum 5)",
  "routeAlias": "/main/Financial-2525"
 },
 "revisions": [
  {
   "revision": "0.001",
   "date": "2026-09-30",
   "kind": "ask",
   "why": "Financial-2525 opens at v.000_r.001 (operator: \"we start Financial-2525 at revision 0.001 · v.000_r.001\"): the MoT Financial System ask persisted verbatim with six addenda and the three MoT sheets transcribed; the pure laws (MoT in A.B..C, the perihelion calendar, escrow that releases $/min, the append-only record, the personal budget on the $/min · $/sec ladder), the wireframe surface on the ◬ ♡ 웃 Session basis, the R-CORE badge and this ladder — all gated in test:ci from the first line.",
   "commit": "e31cc45",
   "shipped": "39f44c1"
  },
  {
   "revision": "0.002",
   "date": "2026-09-30",
   "kind": "decision",
   "why": "The UI/UX STARTS FROM the ◬ ♡ 웃 Session shell (operator addendum 7) and the chart's glass reads day · hour · minute with A.B..C behind the scenes (addendum 8, max R-CORE reuse): the surface is rebuilt on /soi-session's own root, header (globe + Trinity glyphs), card, phase rail (PodPhaseRail gains additive `phases`/`countFor` props — DEPOSIT ◬ · HOLD ♡ · RELEASE ♡ · WITHDRAW 웃 · RECORD 웃), guide card, roster (PodRosterList), ACTIVE clock block (the big mono number is money released), phone strip and folded Trinity (SoITrinity: ◬ M_SS · 웃 M_33 · ♡ M_LTU); sign-in returns the person here; the chart stays under the vector law. Decisions FD-10, FD-11.",
   "commit": "d5d2b72",
   "shipped": "5838c67"
  },
  {
   "revision": "0.003",
   "date": "2026-09-30",
   "kind": "correction",
   "why": "A.B..C IS the Earth's revolution around the Sun (operator addendum 10): one revolution — perihelion to perihelion, the financial year — split into 3600 A-units · 3600 B sub-units · 3600 C sub-sub-units. r.001–r.002 read a pay period as its own whole (its end printed 3600.3600..3600); corrected: the A.B..C of an instant is its position in the current revolution (positionInYear, the sourced perihelion instants) and a MoT LENGTH converts INTO the scale — the 30.333-day pay MoT is ≈ 298.97 A. FIN-01 superseded by FIN-01.01; FD-13 supersedes FD-01; the chart's reveal now reads the revolution's coordinate at each axis mark and the elapsed span in A-units.",
   "commit": "fe6f8e6",
   "shipped": "13028c0"
  },
  {
   "revision": "0.004",
   "date": "2026-09-30",
   "kind": "decision",
   "why": "The twelve-lens review of the MoT Financials notes (round 1, FIN-09) is persisted beside the revisions — docs/financial-2525/reviews/r001_twelve_lenses.md, sha256 97ff0c06… on the ledger, committed alone at 8990b2d — and its stop rule for \"until simulated sufficiently\" is adopted as FD-14. Grades: median B (7 B · 5 B−); all twelve agree the notes were enough to build from and that r.001–r.003 already hold the money law; what they rule is on the record as r.005's backlog: one perihelion table, one MoT number on glass and gate, a withdrawal checked at every instant, the chart drawing available and its hold vertex, a record that survives a full phone, no machine word on the person's screen, the ×32 fill. The gate now proves the record file exists with 12 lens sections and hashes to reviews[].sha256. Addenda 6–10 (arrived mid-review) supersede any lens reading they contradict.",
   "commit": "8990b2d",
   "shipped": "78b4cdf"
  },
  {
   "revision": "0.005",
   "date": "2026-09-30",
   "kind": "correction",
   "why": "The 365-day financial year IS 3600 A exactly (operator addendum 11, clarified: \"365 days is 3600.0000..0000 … Half year … = 1800\"): one A = 8,760 s (r.003 measured lengths on the 365.259636-day mean anomalistic year — 298.97 A for the pay MoT — superseded: 91 ÷ 3 days = 299.0641..0345 A); the day · hour · minute · second ladder is DERIVED from the scale (one day = 9.3106..3058 A); every writing prints its true A (365 d → 3600.0000..0000, r.003 substituted 3600.3600..3600); positions are never clamped and flagged pastFull past day 365; the fourth tier D (A.BBBB..CCCC...DDDD, 0.18776 µs) is declared. Every planet's whole is its own revolution, perihelion to perihelion (addendum 12: Mars 686.98 Earth days; 668.5991 sols the future form), A.B..C the standard for all, converted to the planet's LTU — Earth hours · minutes · seconds for Mars for now; the PER-PLANET LTU TABLE IS MASTER DATA IN THE ADMIN PANEL under the seed law (lib/planet-ltu.ts; SoI-2525 › Business Setup › Planet LTU; the cloud config bundle) and Financial-2525 reads it — a change there adjusts every conversion with no code change. For now the Earth row reads Month = 91 days with ONE system-offline day on Dec 31 (addendum 13), so the calendar year (Jan 1 → Dec 31) is the default anchor and Dec 31 the offline day 365; the perihelion anchor stays selectable. The reveal is the MoT-icon ⇄ Clock-icon toggle, one state for the whole card. FIN-01.01 → FIN-01.02, FIN-02 → FIN-02.01, FIN-13 → FIN-13.01 + FIN-13.02; FD-15..18. The lenses' round-1 backlog carries to r.006. Addendum 14 (\"A.B..C always\"): the notation is always A.B..C, never A.B.C; the card opens on the Clock icon with the MoT toggle — as built. Addendum 15: the canonical address is /financial-2525 (the launcher, the record's route and the sign-in return point there; /main/Financial-2525 stays an alias).",
   "commit": "c27628d",
   "shipped": "a8f6acd"
  },
  {
   "revision": "0.006",
   "date": "2026-09-30",
   "kind": "decision",
   "why": "Every transaction carries its personal-finance element (operator addendum 16, with his phone screenshot of the live forms): the deposit and withdrawal forms gain a dropdown grouped Income · Fixed · Variable over the sheet's categories — Mortgage/Rent (the sheet's Home, in the operator's word) · Auto · Insurance · Utilities · Fitness · Fun · Groceries · Dining Out · Other — recorded on the entry (FinTx.category, inside the chain hash), shown on the roster and the record; CATEGORY_KIND is the one map. The budget is a TABLE with a UNIT TOGGLE (addendum 17, with his screenshot of the wrapping ladder): category · kind · one figure in the unit the person picks — $/second · $/minute · $/hour · per day · per week · per 33 days (the sheet, the default) · per month (the LTU table's 91) · per year — the units read the selected planet's LTU row. The record's sentence stops naming a vendor (the lenses' owed item; the signer-voice law). FIN-03 → FIN-03.01, FIN-06 → FIN-06.01, FD-19, FD-20; eight lexicon keys staged (fin.category · fin.cat.home re-worded Mortgage/Rent · per_week · per_month · per_year · unit · kind · device_only re-worded) — ×32 fill follows.",
   "commit": "0f41042",
   "shipped": "419e85b"
  },
  {
   "revision": "0.007",
   "date": "2026-09-30",
   "kind": "correction",
   "why": "The year is the EXACT revolution, never a rounded 365 (operator addendum 18: '365 should be exact amount 365.25 etc. · remember perihelion exact time for Austin Texas CST is Standard'). mot.ts: FINANCIAL_YEAR_DAYS = EARTH_REVOLUTION_DAYS = 365.259636 (the anomalistic year, SOURCED, one primitive) = 3600 A, so one A = 8,766.23 s, one B = 2.4351 s, one C = 0.6764 ms, one D = 0.18789 µs; half 182.629818 d = 1800; the pay MoT (91 ÷ 3 d) reads 298.3475..1826 A (≈ 298.97, r.003's reading on the exact year — r.005's 299.0641..0345 on exactly 365 d superseded on the record); one day 9.3081..2196 A; 365 calendar days read 3597.1587..2508. calendar.ts: the PERIHELION is the default anchor again ('calendar' stays selectable in the Planet LTU table), and the perihelion instant is written in Austin CST STANDARD (UTC−6, never daylight) beside the sourced UTC (perihelionCst; 2026 opens 2026.01.03_11.15..00 CST) — printed on the year panel. planet-ltu.ts: the Earth seed row reads yearDays 365.259636 · anchor perihelion (the seed law carries it into every saved copy an operator has not edited). Month 91 and the Dec 31 offline day stay calendar dates. The A.B..C axis marks are three lines (A / .B / ..C — the r.006 Mars capture showed B and C overprinting at 390 px). FIN-01.02 → FIN-01.03, FIN-02.01 → FIN-02.02, FD-21 (supersedes FD-15's exact-365 whole and FD-17's calendar default); one lexicon key (fin.perihelion_cst) staged. r.005's numbers stay on the record in orbitUnitsEarth365 and the correction line.",
   "commit": "25ec03d",
   "shipped": "71935d2"
  },
  {
   "revision": "0.008",
   "date": "2026-09-30",
   "kind": "decision",
   "why": "Every category carries its icon (operator addendum 19, with his PERSONAL sheet photographed again: an icon drawn before every Fixed/Variable line — 'Ensure all have icons: Income · Mortgage · Car · Insurance · Food · Fitness · Fun'). components/financial-2525/category-icon.tsx: ONE map, CATEGORY_ICON, keyed by every BudgetCategory — the seven he named (Income banknote · Home/Mortgage house · Auto car · Insurance shield · Groceries/Food basket · Fitness dumbbell · Fun party) and the three the sheet does not name (Utilities = the sheet's Electric bolt · Dining Out crossed utensils · Other ellipsis) — strokes only (the vector law), aria-hidden, the word beside it always; shown on the budget table rows, before the category dropdown on both forms (the chosen category's icon), and on the record's lines. Labels unchanged: his Car and Food match the sheet's CAR and FOOD; the glass reads Auto and Groceries from the r.001 transcription — flagged for his word, not renamed. Also folded (fix the class): the year position now takes the planet's revolution — positionInYear/frameOf gain yearDays and the surface passes the selected row's — because the r.007 Mars capture showed the axis reading Earth positions (the head already read the Martian whole). FIN-06.02 (additive beside FIN-06.01), FIN-13.03 (the Mars position on its own revolution), FD-22.",
   "commit": "589d223",
   "shipped": "b83dff3"
  },
  {
   "revision": "0.009",
   "date": "2026-09-30",
   "kind": "decision",
   "why": "The budget's unit is picked from ONE dropdown (operator addendum 20 'use drop down', with his phone view of the r.006 capture: the eight unit pills wrapped over three rows above the table). command-ux1.tsx: the role=group pill toggle becomes a labelled <select data-fin-budget-unit> whose options are the same eight units — per second · per minute · per hour · per day · per week · per 33 days (the sheet, the default) · per month (the LTU table's 91) · per year — the same default, the same conversions, the same control on every width. FIN-06.01 → FIN-06.03 (the toggle's wording superseded; FIN-06.02's icons stand), FD-23. No new lexicon key (fin.unit labels the select).",
   "commit": "756075a",
   "shipped": "af028ab"
  },
  {
   "revision": "0.010",
   "date": "2026-09-30",
   "kind": "decision",
   "why": "The unit dropdown spans the full width of the panel in portrait (operator addendum 21, on the r.009 capture: 'thats full width of UX on portrait mode FOR PER HOUR ETC'). command-ux1.tsx: the label sits above a w-full select on a phone held upright, so every option — per hour, per month (91), per year — reads at the full line; in landscape the select keeps its own width beside the label (landscape:w-auto, min 14rem). Same options, default and conversions. FIN-06.03 → FIN-06.04, FD-24. No new lexicon key.",
   "commit": "0f842a9",
   "shipped": "PENDING"
  }
 ],
 "mot": {
  "law": "A.B..C IS THE REVOLUTION (addendum 10, r.003): one revolution of the planet around its star — for Earth, perihelion to perihelion, the financial year — is split into 3600 A-units; each A into 3600 B sub-units; each B into 3600 C sub-sub-units — exactly the celestial UCRS-2525 orbit (HU 0 = perihelion, 3600.3600..3600 = a full orbit). The A.B..C of an INSTANT is its position in the current revolution (0.0000..0000 at perihelion, 3600.3600..3600 at the next). The A.B..C of a LENGTH (a MoT) is days ÷ revolution-days × 3600: the 30.333-day pay MoT is ≈ 298.97 A-units — that is '30.33 converted into the 3600.3600..3600 scale'. The scale never names a planet: on Mars the same functions take sols and the Martian revolution in sols. Behind the scenes only — the glass reads day · hour · minute. · r.005 (addenda 11–13): for EARTH the financial year is EXACTLY 365 days = 3600 A (also written 3600), half = 1800; one A = 8,760 s; the day · hour · minute · second ladder is DERIVED from the scale (one day = 3600 ÷ 365 = 9.3106..3058 A — '24 hr day is split to 3600.3600..3600' is that translation, never a second whole); positions are never clamped (past day 365 reads past 3600, flagged); lengths print their true A (730 d = 7200); below C there is D. Every planet's whole is ITS revolution, perihelion to perihelion; A.B..C is the standard for all planets and the glass converts to the planet's LTU from the Admin panel's Planet LTU table (Mars: Earth hours · minutes · seconds for now). · r.007 (addendum 18): the whole is the EXACT revolution — 365.259636 days = 3600 A (one A = 8,766.23 s), never a rounded 365; the perihelion instant opens the year (default anchor again) and is written in Austin CST STANDARD (UTC−6, never daylight).",
  "revolution": {
   "earthDaysMean": 365.259636,
   "earthNote": "365.259636 d — the mean anomalistic year, perihelion to perihelion — IS the financial year's whole (r.007, addendum 18 '365.25 etc.'; r.003 had measured on it; r.005's exact 365 superseded). The position is elapsed ÷ 365.259636 d × 3600 on the year's anchor — the sourced perihelion by default (calendar.ts), the calendar year selectable.",
   "marsSols": 668.5991,
   "units": 3600,
   "subUnits": 3600,
   "subSubUnits": 3600,
   "financialYearDays": 365.259636,
   "halfYearDays": 182.629818,
   "halfYearInA": 1800,
   "fullInA": 3600,
   "marsEarthDays": 686.98,
   "marsLtu": "Earth hours · minutes · seconds for now (FD-16); a 24-unit split of the sol is the future form"
  },
  "orbitUnitsEarth": {
   "aSeconds": 8766.231264,
   "bSeconds": 2.43506,
   "cSeconds": 0.000676407,
   "dSeconds": 1.8789e-7
  },
  "payMotInA": 298.97,
  "correction": "r.001–r.002 read a pay period as its own whole (its end printed 3600.3600..3600). Superseded by this law; the record keeps both. · r.003 measured lengths on 365.259636 d and printed every whole as 3600.3600..3600; r.005: 365 d exactly, the true A printed, positions unclamped — the record keeps all three readings. · r.007 (addendum 18): the exact revolution 365.259636 d = 3600 A again — r.005's 365 superseded on the record; the perihelion the default anchor again, its instant written in Austin CST standard. · r.008: the year position takes the planet's revolution (positionInYear yearDays) — until then the Mars axis read Earth positions (r.007 capture); found by the capture, fixed at its class.",
  "full": "3600.3600..3600",
  "equalWritings": [
   "3600.0000..0000",
   "3600.3600..3600",
   "3599.3599..3599"
  ],
  "stampFormat": "YYYY.MM.DD_HH.MM..SS (CST standard, UTC−6, no daylight shift — Austin, Texas)",
  "durationFormat": "0000.00.DD_HH.MM..SS (33 days = 0000.00.33_00.00..00 · 16.5 days = 0000.00.16_12.00..00)",
  "ltu": {
   "D": 1,
   "W": 7,
   "M": 33,
   "Q": 99,
   "Y": 365.259636,
   "minutesPerDay": 1440,
   "analysisMonth": 91,
   "analysisNote": "Month 91 for now (addendum 13) — the analysis ladder comes from the Admin panel's Planet LTU table (ltuDays(row)); D · W 7 · M 33 · Q 99 · Y 365 remain the SHEET's personal frame · r.007: Y is the exact revolution 365.259636 d"
  },
  "payMotDays": 30.333,
  "payMotNote": "one third of a 91-day quarter (91 ÷ 3 = 30.333…) — the operator's worked example; 299.0641..0345 A of the 365-day whole (r.003's 298.97 was on the mean anomalistic year) · r.007: 298.3475..1826 A of the exact 365.259636-day whole (≈ 298.97 — r.003's reading again; r.005's 299.0641..0345 superseded)",
  "trinity": {
   "♡": "M_LTU — local time, the witness",
   "웃": "M_33 — the 33-day personal month",
   "◬": "M_SS — the sub-second 3600 scale, the machine's clock"
  },
  "projectValue": {
   "♡": "minutes",
   "웃": "minutes × minimum wage",
   "◬": "minutes × efficiency gain",
   "tradedFor": "$"
  },
  "source": "frontend/lib/financial-2525/mot.ts · frontend/lib/abc-3600.ts · frontend/lib/ucrs-2525.ts",
  "orbitUnitsEarthMean": {
   "aSeconds": 8766.2,
   "bSeconds": 2.435,
   "cSeconds": 0.000676,
   "note": "r.003 — on the mean anomalistic year; superseded"
  },
  "positions": "on the exact 365.259636-day whole, never clamped; past 3600 flagged pastFull until the year resets (the reset is the anchor — the perihelion by default, Jan 1 selectable — never the number)",
  "fullPrint": "3600.0000..0000 (= 3600) at exactly 365.259636 days; 365 calendar days read 3597.1587..2508; 3600.3600..3600 is the sheet's writing of the same whole (isFull), a predicate, never substituted",
  "ltuInA": {
   "day": 9.856003,
   "hour": 0.4106668,
   "minute": 0.00684445,
   "second": 0.00011407,
   "dayABC": "9.3081..2196",
   "hourABC": "0.1478..1442",
   "minuteABC": "0.0024..2304",
   "secondABC": "0.0000..1478"
  },
  "tierD": {
   "notation": "A.BBBB..CCCC...DDDD",
   "seconds": 1.8789e-7,
   "status": "DECLARED — not on the glass (operator: 'if smaller time splits are needed we use A.B..C…D')"
  },
  "planetLtuTable": {
   "where": "Admin panel — SoI-2525 › Business Setup › Planet LTU (lib/planet-ltu.ts seeds it; localStorage innovation-planet-ltu + its tombstone list ride the cloud config bundle; lib/financial-2525/planets.ts reads it)",
   "rows": [
    "earth",
    "mars"
   ],
   "columns": [
    "year (days = 3600 A)",
    "month (91)",
    "offline day (12-31)",
    "year opens (Jan 1 · perihelion)",
    "day in A.B..C (derived, editable — back-solves the year)",
    "hours/day",
    "minutes/hour",
    "seconds/minute",
    "one A in seconds (derived)",
    "status"
   ],
   "law": "the seed law — merged into every saved copy, a person's edit wins, tombstones hold; an edit adjusts every conversion with no code change (addendum 12)"
  },
  "orbitUnitsEarth365": {
   "aSeconds": 8760,
   "bSeconds": 2.4333,
   "cSeconds": 0.000675926,
   "dSeconds": 1.8776e-7,
   "note": "r.005's units on exactly 365 days (FD-15) — kept on the record, superseded by r.007"
  },
  "anchor": {
   "default": "perihelion",
   "cst": "the perihelion instant is written in Austin CST STANDARD (UTC−6, never daylight) beside its sourced UTC — calendar.ts perihelionCst; 2026 opens 2026.01.03_11.15..00 CST, 2028 opens 2028.01.05_06.28..00 CST — printed on the year panel (data-fin-perihelion)",
   "selectable": "calendar (Jan 1, r.005's default for one edition) in the Planet LTU table",
   "basis": "addendum 18 — 'remember perihelion exact time for Austin Texas CST is Standard'"
  }
 },
 "calendar": {
  "anchor": "PERIHELION — day 1 of every Financial-2525 year begins at the perihelion instant (the SoI calendar's own anchor; Celestial-2525's HU 0)",
  "timezone": "CST standard (UTC−6, fixed) — how a day is NAMED; the instants are universal",
  "quarterDays": 91,
  "gridDays": 364,
  "downDay": 365,
  "downNote": "day 365, and whatever fraction of the orbit remains until the next perihelion, is the DOWN day — no quarter owns it",
  "personalFrames": [
   33,
   66,
   99
  ],
  "analysisUnits": {
   "D": 1,
   "W": 7,
   "M": 33,
   "Q": 99,
   "Y": 365.259636
  },
  "businessGrid": "4-4-5 weeks · 13 weeks · 91 days per quarter (declared, test later)",
  "perihelionTable": "frontend/lib/financial-2525/calendar.ts — 2024–2035 SOURCED (Espenak via the Farmers' Almanac, EST→UTC; NASA APOD 2025; EarthSky 2026); outside the table DECLARED and shown as such",
  "discrepancies": [
   "2028: 12:28 UTC here (Espenak) vs 12:11 UTC in the older lib/soi-calendar.ts seed — recorded, not hidden",
   "2027: 02:33 UTC (Espenak/Almanac) vs 02:07 UTC (in-the-sky.org) — the Almanac value carried"
  ],
  "anchorNote": "r.005 made 'calendar' (Jan 1) the default for one edition (addendum 13); r.007 restores the perihelion (addendum 18); Dec 31 stays the one system-offline day by calendar date on either anchor"
 },
 "accrual": {
  "law": "The payer puts a period's pay UP FRONT into escrow (two weeks or one month for a business). From the deposit day and time the escrow releases amount ÷ (MoT × 1440) per minute, linearly, for the MoT. Released money is visible at once; it is WITHDRAWABLE only from 3 hours after the deposit. A withdrawal is its own transaction and can never take more than is withdrawable then.",
  "holdHours": 3,
  "states": [
   "pending",
   "releasing",
   "released"
  ],
  "invariants": [
   "money released is never more than money deposited",
   "a withdrawal never makes the available balance negative",
   "the rate is amount ÷ MoT-minutes and nothing else",
   "a transaction is amount · deposit day and time · MoT — always the three fields",
   "the record is append-only and chain-hashed"
  ],
  "source": "frontend/lib/financial-2525/accrual.ts · frontend/lib/financial-2525/record.ts"
 },
 "example": {
  "amountUsd": 3604.49,
  "postedDate": "2026-09-29",
  "depositStamp": "2026.10.01_07.00..00",
  "motDays": 30.333,
  "memo": "PAYROLL · PENDING DIRECT DEPOSIT",
  "ratePerMinUsd": 0.0825,
  "perDayUsd": 118.83,
  "perHourUsd": 4.95,
  "perSecUsd": 0.001375,
  "withdrawableAt3hUsd": 14.85,
  "motInA": 298.97,
  "note": "the operator's own paycheck, transcribed from his bank screen; a record, never an invention"
 },
 "budget": {
  "categories": [
   "Income",
   "Home",
   "Auto",
   "Insurance",
   "Utilities",
   "Fitness",
   "Fun",
   "Groceries",
   "Dining Out",
   "Other"
  ],
  "kinds": [
   "income",
   "fixed",
   "variable"
  ],
  "sheetSeedPer33Days": {
   "Income": 3200,
   "Home": 700,
   "Auto": 1800,
   "Insurance": 200,
   "Utilities": 150,
   "Groceries": 300,
   "Fitness": 50,
   "Fun": 200
  },
  "ladder": "$/day · $/hour · $/min · $/sec and per D · W · M33 · Q99 · Y365 (the sheet's 144 $/D = 0.1 $/m · 1,008 $/W · 4,752 $/M33 · 14,256 $/Q99)",
  "sheetSlips": [
   "47,620 min written for 33 days (33 × 1440 = 47,520)",
   "4,762 $/M33 written (0.1 $/min × 47,520 = 4,752; the quarter figure 14,256 = 3 × 4,752 is consistent)"
  ],
  "source": "frontend/lib/financial-2525/budget.ts"
 },
 "tokenization": {
  "yugCeiling": 9999,
  "law": "Tokenization honours the 9,999 HI (웃) token cap — the YUG_CEILING the POD session already enforces (frontend/lib/pod-yug.ts); Financial-2525 reuses it and never declares a second ceiling.",
  "status": "declared for revision 0.001; wired when the personal framework has received feedback"
 },
 "business": {
  "status": "TEST LATER (operator addendum 5: once the personal framework receives feedback we test business)",
  "grid": "4-4-5 · 13 weeks · 91 days",
  "pnlLadder": [
   "Revenue",
   "− COGS",
   "= Margin",
   "− R&D",
   "− Marketing",
   "− Sales",
   "− SG&A",
   "= Operating Income",
   "− DA",
   "= EBITDA",
   "− DA",
   "= EBIT"
  ],
  "escrow": "the business pays two weeks or one month up front; the same accrual law releases it to each person at $/min"
 },
 "crs": [
  {
   "id": "FIN-01",
   "title": "MoT in A.B..C — the measure of time",
   "statement": "A MoT is one whole and a moment inside it is its elapsed fraction in Base-3600 A.B..C, 0.0000..0000 at the start and 3600.3600..3600 at completion, converting to Earth LTU (D · W · M33 · Q99 · Y365 · h · min · s) and back within one C; timestamps read YYYY.MM.DD_HH.MM..SS in CST standard and durations 0000.00.DD_HH.MM..SS.",
   "in": "FIN-01.IN",
   "out": "FIN-01.OUT",
   "section": "VII",
   "uwf": [
    "U-WF-12"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "SUPERSEDED by FIN-01.01 (addendum 10): a pay period is not its own whole — the revolution is",
   "verify": "tests/financial-mot.test.mjs",
   "dtm": "superseded",
   "stretch": "superseded",
   "status": "superseded"
  },
  {
   "id": "FIN-01.01",
   "title": "A.B..C is the revolution — the measure of time",
   "statement": "One revolution of the planet around its star (for Earth, perihelion to perihelion — the financial year) is split into 3600 A-units, each A into 3600 B, each B into 3600 C; the A.B..C of an instant is its position in the current revolution (0.0000..0000 at perihelion, 3600.3600..3600 at the next) and the A.B..C of a MoT length is days ÷ revolution-days × 3600 (the 30.333-day pay MoT ≈ 298.97 A), converting to Earth LTU and back within one C; timestamps read YYYY.MM.DD_HH.MM..SS in CST standard, durations 0000.00.DD_HH.MM..SS; the glass reads day · hour · minute, A.B..C on reveal.",
   "in": "FIN-01.01.IN",
   "out": "FIN-01.01.OUT",
   "section": "VII",
   "uwf": [
    "U-WF-12"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "SUPERSEDED by FIN-01.02 (addendum 11): the financial year is exactly 365 days = 3600 A — 298.97 A and 8,766 s were measured on the mean anomalistic year",
   "verify": "tests/financial-mot.test.mjs",
   "dtm": "the chart's reveal shows the revolution's coordinate at each axis mark and the elapsed span in A-units",
   "stretch": "a 30-sol MoT on Mars converts to 161 A of the Martian revolution and back",
   "status": "superseded"
  },
  {
   "id": "FIN-02",
   "title": "The calendar resets at perihelion",
   "statement": "Day 1 of every Financial-2525 year begins at the perihelion instant on a sourced table (2024–2035), named in CST standard; quarters are 91 days, the grid is 364, day 365 is DOWN; personal frames run 33 / 66 / 99 days from day 1 and the year's own A.B..C is the celestial orbit position.",
   "in": "FIN-02.IN",
   "out": "FIN-02.OUT",
   "section": "VI",
   "uwf": [
    "U-WF-06"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "SUPERSEDED by FIN-02.01 (addendum 13): for now the year opens Jan 1 and Dec 31 is the one offline day; the perihelion anchor stays selectable in the Admin panel's LTU table",
   "verify": "tests/financial-mot.test.mjs",
   "dtm": "twelve sourced years with provenance; a year outside the table is DECLARED and says so",
   "stretch": "the table refreshed from an ephemeris the operator confirms annually",
   "status": "superseded"
  },
  {
   "id": "FIN-03",
   "title": "The transaction — $, deposit day and time, MoT",
   "statement": "Every deposit on the record carries exactly the operator's three fields — amount, the deposit day and time, and the MoT length of time — and every withdrawal carries its amount and day and time; nothing else is required to accrue.",
   "in": "FIN-03.IN",
   "out": "FIN-03.OUT",
   "section": "V",
   "uwf": [
    "U-WF-06"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "SUPERSEDED by FIN-03.01 (addendum 16): a transaction also carries its personal-finance category",
   "verify": "tests/financial-accrual.test.mjs",
   "dtm": "a deposit typed on the phone appears on the record with its stamp and MoT",
   "stretch": "a bank export imported as transactions with the same three fields",
   "status": "superseded"
  },
  {
   "id": "FIN-04",
   "title": "Escrow releases $/min",
   "statement": "From the deposit day and time the escrow releases amount ÷ (MoT × 1440) per minute, linearly, for the MoT; released money is visible at once and withdrawable only from 3 hours after the deposit; a withdrawal can never take more than is withdrawable and the balance never goes negative.",
   "in": "FIN-04.IN",
   "out": "FIN-04.OUT",
   "section": "IV",
   "uwf": [
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "at +3 h the example shows $14.85 released and withdrawable; a minute earlier it is visible but held; $14.86 is refused INSUFFICIENT",
   "verify": "tests/financial-accrual.test.mjs",
   "dtm": "a person sees the balance rise every second and can withdraw after the hold",
   "stretch": "an employer's escrow deposit arrives as a message on the record, not a typed row",
   "status": "implemented"
  },
  {
   "id": "FIN-05",
   "title": "The record — append-only, chain-hashed, replayable",
   "statement": "A person's transactions are an append-only ledger per login: every entry carries the hash of the entry before it, an id already on the record is never written twice, the record replays to any revision, and a changed amount breaks the chain where it was changed; revision control is on from the first line, the Drone-2525 way.",
   "in": "FIN-05.IN",
   "out": "FIN-05.OUT",
   "section": "II",
   "uwf": [
    "U-WF-06"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "verify() holds on every record written and names the broken revision on a tampered one",
   "verify": "tests/financial-accrual.test.mjs",
   "dtm": "the device half in localStorage under the person's own key",
   "stretch": "a cloud half appending to the same shape with the same hashes",
   "status": "implemented"
  },
  {
   "id": "FIN-06",
   "title": "The personal budget on the $/min · $/sec ladder",
   "statement": "A personal budget is Income and Fixed / Variable lines — Home, Auto, Insurance, Utilities, Fitness, Fun, Groceries, Dining Out, Other — each expressed per day · hour · minute · second and per D · W · M33 · Q99 · Y365, with the net on the same ladder; the sheet's figures are seed data the person edits, never advice.",
   "in": "FIN-06.IN",
   "out": "FIN-06.OUT",
   "section": "I",
   "uwf": [
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "SUPERSEDED by FIN-06.01 (addendum 17): the budget is a table with a unit toggle, every unit from $/second to per year",
   "verify": "tests/financial-accrual.test.mjs",
   "dtm": "the operator's own lines in his order, each with its ladder",
   "stretch": "a line's actual spend logged as withdrawals against it",
   "status": "superseded"
  },
  {
   "id": "FIN-07",
   "title": "The real-time chart, on a phone",
   "statement": "The surface shows one person's money as time: the released, withdrawable and escrowed series over the current MoT, the live $/min, the A.B..C position of the deposit's MoT and of the year, the 3-hour hold mark and every withdrawal as a mark — strokes only, on the black ground, in the 13 colours, ticking every second, legible at 390 px.",
   "in": "FIN-07.IN",
   "out": "FIN-07.OUT",
   "section": "III",
   "uwf": [
    "U-WF-07",
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "the chart renders the worked example from the pure series with no fill, no gradient, one accent; the vector-law gate holds",
   "verify": "tests/financial-surface.test.mjs",
   "dtm": "the worked example runs live before sign-in; a person's record after",
   "stretch": "the twelve lenses' chart specification folded in revision 0.002",
   "status": "implemented"
  },
  {
   "id": "FIN-08",
   "title": "Each user their own login",
   "statement": "A person signs in (the app's Auth0 gate) before recording; the record is keyed to that person on the device; the cloud half is honest — today the app's Supabase isolation is a per-browser bearer owner key, not the login, so cross-device cloud isolation per login waits on wiring the login into Supabase (an operator infrastructure item, declared, never faked).",
   "in": "FIN-08.IN",
   "out": "FIN-08.OUT",
   "section": "IX",
   "uwf": [
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "an unsigned visitor sees the example and a sign-in, never another person's record",
   "verify": "tests/financial-surface.test.mjs",
   "dtm": "sign-in on the route; the record under the signed-in person's key",
   "stretch": "Supabase third-party auth on the app's login → per-login RLS on a financial_transactions table",
   "status": "draft"
  },
  {
   "id": "FIN-09",
   "title": "Twelve lenses every revision, until simulated sufficiently",
   "statement": "Every Financial-2525 revision is reviewed by all twelve reviewer lenses and their review is persisted beside the revision; the loop continues until the simulated system is judged sufficient by a measurable stop rule the lenses themselves state.",
   "in": "FIN-09.IN",
   "out": "FIN-09.OUT",
   "section": "XI",
   "uwf": [
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "a review record exists for the revision; its stop rule is stated",
   "verify": "tests/financial-crs.test.mjs",
   "dtm": "round 1 on the MoT sheets persisted with this revision",
   "stretch": "the twelve run as a repeatable harness on every push",
   "status": "approved"
  },
  {
   "id": "FIN-10",
   "title": "Tokenization under the 9,999 웃 cap",
   "statement": "Whatever Financial-2525 tokenizes honours the 9,999 HI (웃) token cap the POD session already enforces (YUG_CEILING), reused and never redeclared; 웃 = M × hours stays the only mint.",
   "in": "FIN-10.IN",
   "out": "FIN-10.OUT",
   "section": "X",
   "uwf": [
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "the cap read from lib/pod-yug.ts, no second constant on this surface",
   "verify": "tests/financial-crs.test.mjs",
   "dtm": "declared in revision 0.001",
   "stretch": "an hour witnessed in a POD settles onto the person's record at the stamped rate",
   "status": "draft"
  },
  {
   "id": "FIN-11",
   "title": "Every word in 33 languages",
   "statement": "Every string a person reads on the surface is a lexicon key with an English default and a translator context, filled in all 33 languages; a key added after the last fill is staged, listed, never silent.",
   "in": "FIN-11.IN",
   "out": "FIN-11.OUT",
   "section": "XIII",
   "uwf": [
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "zero hardcoded English in the surface; every fin.* key declared with a context over 15 characters",
   "verify": "tests/financial-i18n.test.mjs",
   "dtm": "the fin.* group staged in AFTER_FILL",
   "stretch": "×32 fill landed and AFTER_FILL cleared",
   "status": "implemented"
  },
  {
   "id": "FIN-12",
   "title": "Business after personal feedback",
   "statement": "The business frame — 4-4-5 weeks, 13 weeks, 91-day quarters, the P&L ladder Revenue − COGS = Margin − R&D − Marketing − Sales − SG&A = Operating Income − DA → EBITDA → EBIT, escrow paid two weeks or a month up front — is declared here and tested only after the personal framework has received feedback.",
   "in": "FIN-12.IN",
   "out": "FIN-12.OUT",
   "section": "XII",
   "uwf": [
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "the ladder and grid declared as data; no business surface built before feedback",
   "verify": "tests/financial-crs.test.mjs",
   "dtm": "declared",
   "stretch": "a business login whose deposits and outflows run the same accrual law",
   "status": "draft"
  },
  {
   "id": "FIN-13",
   "title": "Mars and future planets on the same scale",
   "statement": "Because a MoT's A.B..C never names a planet, a Martian sol-period reads the same position at every fraction as an Earth period; only the LTU conversion changes — proven on a 30-sol MoT in the gate.",
   "in": "FIN-13.IN",
   "out": "FIN-13.OUT",
   "section": "VIII",
   "uwf": [
    "U-WF-12"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "SUPERSEDED by FIN-13.01 + FIN-13.02 (addendum 12): Mars' whole is its own revolution in Earth days with Earth hours as LTU for now; the per-planet LTU table lives in the Admin panel",
   "verify": "tests/financial-mot.test.mjs",
   "dtm": "one Martian case in the gate",
   "stretch": "a planet selector on the surface reading UCRS-2525's PLANETS",
   "status": "superseded"
  },
  {
   "id": "FIN-01.02",
   "title": "365 days = 3600 A exactly — the measure of time, pinned",
   "section": "VII",
   "uwf": [
    "U-WF-12"
   ],
   "statement": "Every planet's whole is its own revolution, perihelion to perihelion, = 3600 A; for Earth the financial year is EXACTLY 365 days = 3600.0000..0000 (also written 3600), half = 1800, so one A = 8,760 s, one B = 2.4333 s, one C = 0.6759 ms and one D = 0.18776 µs (A.BBBB..CCCC...DDDD, declared); the day · hour · minute · second ladder is DERIVED from the scale (one day = 9.3106..3058 A); a length prints its true A even past 3600; a position past day 365 is shown and flagged, never clamped; the glass reads the planet's day · hour · minute, A.B..C on the MoT-icon ⇄ Clock-icon reveal — one state for the whole card.",
   "metric": "SUPERSEDED by FIN-01.03 (addendum 18): the whole is the exact revolution 365.259636 d, never a rounded 365",
   "dtm": "the reveal and the clock ladder read A-units of the 365-day whole; the toggle is two stroke icons (Orbit · Clock) with the existing keys as their names; the year panel carries the pastFull hook",
   "stretch": "the D tier shown on request; one perihelion table shared with lib/soi-calendar (the lenses' backlog)",
   "in": "FIN-01.02.IN",
   "out": "FIN-01.02.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "verify": "tests/financial-mot.test.mjs",
   "status": "superseded"
  },
  {
   "id": "FIN-02.01",
   "title": "The year opens on its anchor — Jan 1 for now, the perihelion selectable",
   "section": "VI",
   "uwf": [
    "U-WF-06"
   ],
   "statement": "Which instant opens the year is a field of the Admin panel's Planet LTU table: 'calendar' (the default for now, addendum 13) opens Jan 1 at midnight CST and makes Dec 31 the one system-offline day (day 365, DOWN); 'perihelion' (r.001–r.004) opens at the sourced perihelion instant. On either anchor the position is elapsed ÷ 365 d × 3600, never clamped: a leap Dec 31 is day 366 and past full; a 367-day perihelion interval reads past 3600 on days 366–368; a 363-day one never reaches day 365 — the reset is the anchor, never the number. Quarters are 91 days, the grid 364, personal frames 33 / 66 / 99.",
   "metric": "SUPERSEDED by FIN-02.02 (addendum 18): the perihelion instant opens the year again, written in Austin CST standard",
   "dtm": "the anchor is edited in the Admin panel and the surface follows; twelve sourced perihelion years with provenance",
   "stretch": "SHORT / LONG badges on every sourced perihelion year; a Mars perihelion epoch table",
   "in": "FIN-02.01.IN",
   "out": "FIN-02.01.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "verify": "tests/financial-mot.test.mjs",
   "status": "superseded"
  },
  {
   "id": "FIN-13.01",
   "title": "Mars on its own revolution, Earth hours for now",
   "section": "VIII",
   "uwf": [
    "U-WF-12"
   ],
   "statement": "Mars' whole is its revolution, perihelion to perihelion — 686.98 Earth days (= UCRS-2525 PLANETS mars.tDays, one primitive) — and its LTU is, FOR NOW, Earth hours · minutes · seconds (addendum 12 / clarification: 'since mars does not have 24 unit split of time; we'll use Earth Hours for now'); 668.5991 sols × 88,775.244 s is the same whole in sols, the future form once a 24-unit split of the sol is declared.",
   "metric": "on Mars one A = 16,487.5 s = 4.58 Earth hours; a quarter of the Martian revolution reads 900.0000..0000 on either LTU; a 30-sol MoT is 161 A and 30 Earth days 157 A; the two wholes agree within 30 s",
   "dtm": "the Mars row in the Planet LTU table; the planet selector on the surface converts from it",
   "stretch": "a 24-unit split of the sol declared in the table (hoursPerDay 24.66 …) — everything adjusts modularly",
   "in": "FIN-13.01.IN",
   "out": "FIN-13.01.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "verify": "tests/financial-mot.test.mjs",
   "status": "implemented"
  },
  {
   "id": "FIN-13.02",
   "title": "The per-planet LTU table is master data in the Admin panel",
   "section": "VIII",
   "uwf": [
    "U-WF-06",
    "U-WF-12"
   ],
   "verify": "tests/planet-ltu.test.mjs",
   "statement": "A.B..C is the standard unit for all planets; the conversion to a planet's Local Time Units reads ONE table the operator edits in the Admin panel (SoI-2525 › Business Setup › Planet LTU): per planet the year in days (= 3600 A), the month (91 for now), the offline day (Dec 31), which instant opens the year, the Day in A.B..C beside hours · minutes · seconds — every field editable, the derived ones re-solved on edit. Seeded in code, merged into every saved copy under the seed law (local mirror + cloud config bundle), tombstoned by ✕; Financial-2525 reads it, so a change there adjusts every conversion with no code change.",
   "metric": "editing Mars's hours/day in a saved copy changes the Mars ladder (one A = 16,940.9 s at 24.66 h) with no code change; editing Day-in-A.B..C to 10 makes the year 360 days; a tombstoned planet never re-seeds; a seeded row's untouched field follows a seed change; the table and its tombstone list ride the config bundle",
   "dtm": "the Planet LTU section in Business Setup; the planet selector and the LTU labels on the Financial surface",
   "stretch": "login-bound sync of the table (FD-18); more planets from UCRS-2525's PLANETS",
   "in": "FIN-13.02.IN",
   "out": "FIN-13.02.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "status": "implemented"
  },
  {
   "id": "FIN-03.01",
   "title": "The transaction — $, day and time, MoT, and its category",
   "section": "V",
   "uwf": [
    "U-WF-06"
   ],
   "verify": "tests/financial-surface.test.mjs",
   "statement": "Every deposit carries the operator's three fields — amount, deposit day and time, MoT — and every withdrawal its amount and day and time; each also carries its personal-finance element from ONE grouped dropdown (Income · Fixed · Variable → Mortgage/Rent, Auto, Insurance, Utilities, Fitness, Fun, Groceries, Dining Out, Other), recorded inside the chain hash and shown on the roster and the record; a category is never required to accrue.",
   "metric": "both forms carry the grouped dropdown; the entry's category is inside its hash (a changed category breaks the chain where it changed); the roster and the record print it; the worked example is Income",
   "dtm": "a withdrawal typed on the phone as Groceries appears on the record as Groceries",
   "stretch": "a line's actual spend summed against the budget row of the same category",
   "in": "FIN-03.01.IN",
   "out": "FIN-03.01.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "status": "implemented"
  },
  {
   "id": "FIN-06.01",
   "title": "The personal budget as a table with a unit toggle",
   "section": "I",
   "uwf": [
    "U-WF-09"
   ],
   "verify": "tests/financial-surface.test.mjs",
   "statement": "The personal budget is a table — category · kind · one figure — under a segmented unit toggle: $/second · $/minute · $/hour · per day · per week · per 33 days (the sheet, the default) · per month (the LTU table's month, 91 for now) · per year; every view is possible, $/min among them; the units come from the selected planet's LTU row; the net is the last row on the same unit; the sheet's figures stay seed data the person edits, never advice.",
   "metric": "SUPERSEDED by FIN-06.03 (addendum 20): the unit is picked from one dropdown, not a segmented pill toggle",
   "dtm": "the table on the phone with the toggle above it",
   "stretch": "actuals per category beside the plan, from the record",
   "in": "FIN-06.01.IN",
   "out": "FIN-06.01.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "status": "superseded"
  },
  {
   "id": "FIN-01.03",
   "title": "The exact revolution IS the whole — 365.259636 days = 3600 A",
   "section": "VII",
   "uwf": [
    "U-WF-07"
   ],
   "verify": "tests/financial-mot.test.mjs",
   "statement": "Every planet's whole is its own revolution, perihelion to perihelion, = 3600 A; for Earth the financial year is the EXACT revolution, 365.259636 days (the anomalistic year, SOURCED — '365.25 etc.') = 3600.0000..0000 (also written 3600), half 182.629818 d = 1800, so one A = 8,766.23 s, one B = 2.4351 s, one C = 0.6764 ms and one D = 0.18789 µs; the day · hour · minute · second ladder is DERIVED from the scale (one day = 9.3081..2196 A); a length prints its true A; a position past the whole is shown and flagged, never clamped; the Earth row of the Planet LTU table reads the same primitive; the glass reads day · hour · minute, A.B..C on the MoT-icon ⇄ Clock-icon reveal.",
   "metric": "the exact year reads 3600.0000..0000 and half 1800.0000..0000; one A = 8,766.231264 s; the pay MoT is 298.3475..1826 A and back to 30.333 d; 365 calendar days read 3597.1587..2508 and 730 read 7194.3175..1416 (never 3600 / 7200 — r.005 superseded); two exact years 7200; A.B..C...D round-trips within one D; FINANCIAL_YEAR_DAYS === EARTH_REVOLUTION_DAYS; the Earth seed row's yearDays is that constant",
   "dtm": "the reveal reads 298.3475..1826 at the pay MoT's end; the Admin panel's Earth row reads 365.259636 and a day 9.3081..2196",
   "stretch": "the per-year perihelion-to-perihelion interval (363–368 d) as the whole instead of the mean — an operator decision, not taken",
   "in": "FIN-01.03.IN",
   "out": "FIN-01.03.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "status": "implemented"
  },
  {
   "id": "FIN-02.02",
   "title": "The perihelion opens the year, written in Austin CST standard",
   "section": "VI",
   "uwf": [
    "U-WF-06"
   ],
   "verify": "tests/financial-mot.test.mjs",
   "statement": "The perihelion instant opens the year (the default anchor again; 'calendar' — Jan 1 — stays selectable in the Planet LTU table); its exact time is written in Austin, Texas CST STANDARD (UTC−6, never daylight) beside the sourced UTC and printed on the year panel; Dec 31 stays the one system-offline day by calendar date; on either anchor the position is elapsed ÷ 365.259636 d × 3600, never clamped — a 367-day interval reads past 3600 on its last days, flagged; a 363-day one never reaches the whole — the reset is the perihelion, never the number. Quarters are 91 days, the grid 364, personal frames 33 / 66 / 99.",
   "metric": "DEFAULT_ANCHOR is 'perihelion' and the Earth seed row's anchor is 'perihelion'; 2026 opens 2026.01.03_11.15..00 CST (17:15 UTC), 2028 opens 2028.01.05_06.28..00 CST; the minute before the 2027 perihelion reads 3591.… (a 364.39-day orbit, not full, resets anyway); exactly 365.259636 d into 2027 reads 3600.0000..0000; day 367 of 2027 reads 3607.1069..1104 past full; the minute before the 2028 perihelion is day 368 at 3621.…; 2028 ends on day 364; on the calendar anchor Jan 1 is day 1, noon Jul 2 reads 1798.2593..3054, Dec 31 is day 365 down and not past full",
   "dtm": "the year panel reads 'Perihelion (Austin CST standard) · 2026.01.03_11.15..00 CST' under the position",
   "stretch": "a perihelion epoch table for Mars (FIN-13's next stretch); one perihelion table shared with lib/soi-calendar (the lenses' backlog)",
   "in": "FIN-02.02.IN",
   "out": "FIN-02.02.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "status": "implemented"
  },
  {
   "id": "FIN-06.02",
   "title": "Every category carries its icon",
   "section": "I",
   "uwf": [
    "U-WF-09"
   ],
   "verify": "tests/financial-surface.test.mjs",
   "statement": "Every personal-finance category on the glass carries one stroke icon — Income · Mortgage/Rent · Auto · Insurance · Utilities · Groceries · Dining Out · Fitness · Fun · Other — before its word on the budget table, before the category dropdown on both forms (the chosen category's), and on the record's lines; the icon never replaces the word and is never a fill; no category is ever bare.",
   "metric": "CATEGORY_ICON's keys are exactly BUDGET_CATEGORIES (a category without an icon fails the gate); the table row, the dropdown label and the record line each render CategoryIcon; the icons are lucide strokes at strokeWidth 1.5, aria-hidden",
   "dtm": "the sheet's icons on the phone: a house before Mortgage/Rent 700, a car before Auto 1,800, a bolt before Utilities 150, a basket before Groceries 300",
   "stretch": "the operator's own glyphs (the sheet's drawings) as the icon set; Car / Food as the labels if he says so",
   "in": "FIN-06.02.IN",
   "out": "FIN-06.02.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "status": "implemented"
  },
  {
   "id": "FIN-13.03",
   "title": "A planet's positions are A-units of ITS revolution",
   "section": "VIII",
   "uwf": [
    "U-WF-06"
   ],
   "verify": "tests/financial-mot.test.mjs",
   "statement": "The year position and the personal frame take the selected planet's revolution (the Planet LTU row's yearDays), not Earth's: on Mars an instant's A.B..C is elapsed ÷ 686.98 d × 3600 on the perihelion anchor (an Earth epoch table for now, DECLARED), so the axis, the year line and the frame read the Martian whole the head already read.",
   "metric": "positionInYear(ms, 'perihelion', 686.98).abc differs from positionInYear(ms).abc by the ratio 365.259636 ÷ 686.98 (within one C); the surface passes planet.yearDays to positionInYear and frameOf at every call; the r.007 Mars capture (the axis equal to Earth's) cannot recur",
   "dtm": "the Mars axis at 390 px reads A-units of the Martian revolution",
   "stretch": "a Mars perihelion epoch table (FIN-13's stretch)",
   "in": "FIN-13.03.IN",
   "out": "FIN-13.03.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "status": "implemented"
  },
  {
   "id": "FIN-06.03",
   "title": "The personal budget as a table under ONE unit dropdown",
   "section": "I",
   "uwf": [
    "U-WF-09"
   ],
   "verify": "tests/financial-surface.test.mjs",
   "statement": "The personal budget is a table — category (with its icon) · kind · one figure — under ONE labelled dropdown of eight units: $/second · $/minute · $/hour · per day · per week · per 33 days (the sheet, the default) · per month (the LTU table's month) · per year; week, month and year read the selected planet's LTU row; the same control on the phone and the desk, never a pill row that wraps.",
   "metric": "SUPERSEDED by FIN-06.04 (addendum 21): the dropdown is the panel's full width in portrait",
   "dtm": "one dropdown reading 'per minute' above the table on the phone, the eight units in its list",
   "stretch": "actuals per category beside the plan, from the record",
   "in": "FIN-06.03.IN",
   "out": "FIN-06.03.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "status": "superseded"
  },
  {
   "id": "FIN-06.04",
   "title": "The unit dropdown — full width in portrait, its own width in landscape",
   "section": "I",
   "uwf": [
    "U-WF-09"
   ],
   "verify": "tests/financial-surface.test.mjs",
   "statement": "The personal budget is a table — category (with its icon) · kind · one figure — under ONE labelled dropdown of eight units; in portrait the dropdown stretches to the panel's full width with its label above it, so every option (per hour · per month (91) · per year …) reads at the full line; in landscape it sits at its own width beside the label. Same default (per 33 days) and conversions.",
   "metric": "the select carries w-full with the landscape variants (landscape:w-auto landscape:min-w-[14rem]) and its label stacks (flex-col) in portrait, rows (landscape:flex-row) in landscape; at 390 × 844 the select's width equals the panel's inner width; the eight options and the m33 default unchanged",
   "dtm": "on the phone upright the dropdown reads across the whole panel: 'per hour'",
   "stretch": "actuals per category beside the plan, from the record",
   "in": "FIN-06.04.IN",
   "out": "FIN-06.04.OUT",
   "phase": "pilot",
   "mode": "Manual",
   "status": "implemented"
  }
 ],
 "decisions": [
  {
   "id": "FD-01",
   "decision": "MoT in A.B..C = the elapsed fraction of ONE WHOLE in Base-3600 (start 0.0000..0000, end 3600.3600..3600), exactly the celestial orbit convention; the three writings the sheet calls Equal all read FULL.",
   "status": "DECLARED",
   "basis": "operator: \"MoT = 30.33 converted to 3600.3600..3600 from Celestial-2525 scale\"; lib/ucrs-2525.ts FULL_ORBIT"
  },
  {
   "id": "FD-02",
   "decision": "CST standard is UTC−6 all year (no daylight shift).",
   "status": "DECLARED",
   "basis": "operator: \"Austin Texas as CST standard\"; lib/ucrs-2525.ts tzFromLon −6 CST"
  },
  {
   "id": "FD-03",
   "decision": "Released money is withdrawable from exactly 3 hours after the deposit day and time (not 3 hours after each release).",
   "status": "DECLARED",
   "basis": "operator: \"3 hrs later individual can withdraw\""
  },
  {
   "id": "FD-04",
   "decision": "The pay MoT is 30.333 days = 91 ÷ 3 (one third of the business quarter); the personal analysis month is 33 days.",
   "status": "DECLARED",
   "basis": "operator: \"October 1, 2026 at 07:00, 30.333\"; sheet 3 \"M = month = 33D\""
  },
  {
   "id": "FD-05",
   "decision": "Release is linear at amount ÷ MoT-minutes from the deposit instant forward (arrears vs advance is a memo, not a rule).",
   "status": "DECLARED",
   "basis": "operator: \"releases $/min\""
  },
  {
   "id": "FD-06",
   "decision": "The personal framework ships first; business is declared and tested after feedback.",
   "status": "OPERATOR",
   "basis": "addendum 5"
  },
  {
   "id": "FD-07",
   "decision": "The cloud half is honest: per-login isolation in Supabase waits on wiring the app's login into Supabase; until then the record lives on the device under the person's key and any cloud mirror uses the app's bearer owner key.",
   "status": "DECLARED",
   "basis": "supabase/migrations/030 — \"this is a bearer-capability model, not identity\""
  },
  {
   "id": "FD-08",
   "decision": "Numbering: version 000, revision 0.001, stamp v.000_r.001; every later edition appends.",
   "status": "OPERATOR",
   "basis": "addendum 6"
  },
  {
   "id": "FD-09",
   "decision": "The 9,999 웃 cap is YUG_CEILING from lib/pod-yug.ts — never a second constant.",
   "status": "OPERATOR",
   "basis": "addendum 4"
  },
  {
   "id": "FD-10",
   "decision": "The surface starts from the ◬ ♡ 웃 Session shell — its root, header, card, phase rail, guide card, roster, clock block, phone strip and folded Trinity are imported or carry the Session's exact classes; the financial laws render inside it. The chart alone stays under the vector law (strokes only, the 13 colours).",
   "status": "OPERATOR",
   "basis": "addendum 7; max R-CORE reuse (addendum 8); pod-invariant pins the Session's own JSX, so reuse means importing its components, never moving them"
  },
  {
   "id": "FD-11",
   "decision": "Behind the scenes is A.B..C; the glass defaults to day · hour · minute (Earth LTU) on the chart and the clock, and A.B..C is a reveal (a toggle), never the default.",
   "status": "OPERATOR",
   "basis": "addendum 8"
  },
  {
   "id": "FD-12",
   "decision": "The Trinity wheel's seats: TOP = HI 웃 (the person) · BOTTOM-LEFT = AI ◬ (AI tokens) · BOTTOM-RIGHT = SI ♡ (minutes contribution — volunteer / time logged). SoITrinity's tuple order is [top, bottom-right, bottom-left], so the surface passes [HI, SI, AI] with glyphs [웃, ♡, ◬].",
   "status": "OPERATOR",
   "basis": "addendum 9"
  },
  {
   "id": "FD-13",
   "decision": "A.B..C IS the Earth's revolution around the Sun: one revolution (perihelion to perihelion) = 3600 A · 3600 B · 3600 C. An instant's A.B..C is its position in the current revolution (the sourced perihelion instants); a MoT length converts into the scale as days ÷ revolution-days × 3600 (mean anomalistic year 365.259636 d). SUPERSEDES FD-01, which read a pay period as its own whole.",
   "status": "OPERATOR",
   "basis": "addendum 10; lib/ucrs-2525.ts (HU 0 = perihelion, 3600 = a full orbit)"
  },
  {
   "id": "FD-14",
   "decision": "The stop rule for \"until simulated sufficiently\" (FIN-09): the twelve stop iterating on the PERSONAL framework — and FIN-12 (business) may open — only when all seven hold on one commit: (1) one full real MoT has run on the operator's own phone (the worked paycheck, 2026.10.01_07.00..00 → 2026.10.31_15.00..00 CST, one Q3→Q4 crossing) with at least one recorded withdrawal, and his feedback is persisted as a hashed addendum in the ask file and as a feedback entry in reviews[]; (2) two consecutive twelve-lens rounds on consecutive revisions raise zero new FD, zero new gate and zero grade below B; (3) determinism — the same ledger replayed at the same instant on two devices and nine runs yields the same cent for released, withdrawable and available, and the same A.B..C to the C; (4) every gate the round names exists and is green in test:ci with tsc at 0, and the round's review file is on disk with 12 lens sections and its sha256 on the ledger; (5) no redeclared primitive — one perihelion table, one YUG_CEILING, one $/min spread, one MoT number on glass and gate; (6) the ×32 fin.* fill has landed and the banned-word regex finds zero machine words in any of the 33 languages; (7) npm run status reports cloudflare LIVE for the commit that satisfies (1)–(6). Until all seven hold, each round appends a revision and the next round runs; nothing in the business frame is built.",
   "status": "DECLARED",
   "basis": "the twelve-lens synthesis, round 1 (docs/financial-2525/reviews/r001_twelve_lenses.md § the stop rule); addendum 5 makes the operator's feedback the trigger"
  },
  {
   "id": "FD-15",
   "decision": "The financial year is EXACTLY 365 days = 3600 A (one A = 8,760 s; half 182.5 d = 1800); the day · hour · minute · second ladder is DERIVED from the scale (one day = 9.3106..3058 A) — '24 hr day is split to 3600.3600..3600' is a translation, not a second whole; positions on that whole are never clamped and flagged pastFull past day 365; lengths print their true A; A.B..C...D (0.18776 µs) is declared, not shown. SUPERSEDES FD-13's length constant (365.259636 d kept as the astronomical note).",
   "status": "OPERATOR",
   "basis": "addendum 11 + clarification 1 ('365 days is 3600.0000..0000 … Half year … 1800 … we use A.B..C…D')"
  },
  {
   "id": "FD-16",
   "decision": "Mars' whole is its own revolution, perihelion to perihelion (686.98 Earth days = UCRS-2525 PLANETS mars.tDays; 668.5991 sols the same whole in sols), and its LTU is Earth hours · minutes · seconds FOR NOW; a 24-unit split of the sol is the future form, declared in the LTU table when it comes.",
   "status": "OPERATOR",
   "basis": "addendum 12 + clarification 2 ('we use full revolution around sun as A.B..C schedule … we'll use Earth Hours for now')"
  },
  {
   "id": "FD-17",
   "decision": "A.B..C is the standard unit for all planets; the per-planet LTU tables are MASTER DATA IN THE ADMIN PANEL under the seed law and every conversion reads them (a change adjusts everything modularly). For now the Earth row reads Month = 91 days with one system-offline day on Dec 31 — so the year opens Jan 1 and Dec 31 is the offline day 365; the perihelion anchor stays selectable; the sheet's 33 · 66 · 99 stay personal frames. The Day in A.B..C is shown beside hours · minutes · seconds, every field editable.",
   "status": "OPERATOR",
   "basis": "addendum 12 ('LTU tables for each planet are in admin panel') + addendum 13 ('Month 91 for now (with 1 day system off line Dec 31). Day in A.B..C as well as Hours, Minutes, and Seconds with ability to edit')"
  },
  {
   "id": "FD-18",
   "decision": "The reach of the table's mirror, said plainly: this browser's copy (the owner key is per browser) plus the cloud config bundle the pod hydrates; login-bound sync arrives when auth reaches Supabase. On the server the seed is read, so the first paint never differs from the seed. The reveal on the surface is the MoT-icon ⇄ Clock-icon toggle, one state for the whole card, named by the existing keys.",
   "status": "DECLARED",
   "basis": "addendum 13 ('have MoT Icon toggle with Clock icon toggle'); lib/innovation-store.ts ownerKeyOrNull (per-browser owner key); migration 030"
  },
  {
   "id": "FD-19",
   "decision": "Every transaction carries its personal-finance element, chosen from ONE grouped dropdown (Income · Fixed · Variable over the sheet's categories); the sheet's Home reads Mortgage/Rent in the operator's word; the category is recorded inside the entry's chain hash and shown on the roster and the record; it is never required to accrue.",
   "status": "OPERATOR",
   "basis": "addendum 16 ('place input transaction, have drop down of mentioned elements of personal finance: fixed · variable · income · Mortgage/Rent · Auto · Insurance · etc')"
  },
  {
   "id": "FD-20",
   "decision": "The budget is a table with a unit toggle — $/second · $/minute · $/hour · per day · per week · per 33 days · per month · per year — one figure per row in the unit the person picks; the sheet's 33-day month is the default; week, month and year read the selected planet's LTU row. The record's sentence names no vendor: 'On this phone only — a cloud copy follows once sign-in carries it'.",
   "status": "OPERATOR",
   "basis": "addendum 17 ('Ensure table and toggle to finance · View must be possible in $/min · Day, Week, Month etc'); the signer-voice law for the sentence"
  },
  {
   "id": "FD-21",
   "decision": "The financial year's whole is the EXACT revolution — 365.259636 days (the anomalistic year, SOURCED) = 3600 A, one A = 8,766.23 s — never a rounded 365 ('365 should be exact amount 365.25 etc.'); the perihelion instant opens the year (the default anchor again; 'calendar' stays selectable) and its exact time is written in Austin, Texas CST STANDARD — UTC−6, never daylight. SUPERSEDES FD-15's exact-365 whole and FD-17's calendar default; Month 91, the Dec 31 offline day, the derived ladder, unclamped positions and tier D stand.",
   "status": "OPERATOR",
   "basis": "addendum 18 (verbatim: '365 should be exact amount 365.25 etc. · remember perihelion exact time for Austin Texas CST is Standard'); reading item 26 of the ask"
  },
  {
   "id": "FD-22",
   "decision": "Every category carries exactly one stroke icon, from ONE map keyed by the category (the seven the operator named and the three the sheet leaves unnamed), shown wherever the category is named on the glass — beside the word, never instead of it; the labels are not changed by this decision (Car / Food vs Auto / Groceries flagged for the operator's word).",
   "status": "OPERATOR",
   "basis": "addendum 19 (verbatim: 'Ensure all have icons · Income · Mortgage · Car · Insurance · Food · Fitness · Fun') with the PERSONAL sheet; reading item 27"
  },
  {
   "id": "FD-23",
   "decision": "The budget's unit is picked from ONE dropdown of the eight units — the same default (per 33 days) and the same conversions as the toggle it replaces; a control that wraps on the phone is not the control.",
   "status": "OPERATOR",
   "basis": "addendum 20 (verbatim: 'use drop down') with his phone view of the r.006 capture; reading item 28"
  },
  {
   "id": "FD-24",
   "decision": "In portrait every picker on the Financial-2525 panel is the panel's full width with its label above; in landscape a picker may sit beside its label at its own width. The unit dropdown is the first; the same rule reaches the category and planet pickers when the operator asks.",
   "status": "OPERATOR",
   "basis": "addendum 21 (verbatim: 'thats full width of UX on portrait mode FOR PER HOUR ETC'); reading item 29"
  }
 ],
 "reviews": [
  {
   "round": 1,
   "revision": "0.001",
   "subject": "the MoT Financials notes (three sheets + six addenda)",
   "lenses": 12,
   "record": "docs/financial-2525/reviews/r001_twelve_lenses.md",
   "sha256": "97ff0c063b4f466f96401dd436f9cd9b05ec172d9257e693b196b14f1254c75d",
   "commit": "8990b2d",
   "status": "PERSISTED r.004 — 12/12 lenses + synthesis; median B (7 B · 5 B−); 22 invariants each with a gate, 35 declared defaults, the stop rule adopted as FD-14; addenda 6–10 supersede any lens reading they contradict"
  },
  {
   "round": 2,
   "revision": "0.007",
   "subject": "r.005 — the 365-day whole, the Planet LTU table in the Admin panel, the MoT ⇄ Clock toggle",
   "lenses": 12,
   "record": "docs/financial-2525/reviews/r002_twelve_lenses.md",
   "status": "PENDING — the twelve run on r.007 after it ships (r.005 and r.006 folded); persisted when they return"
  }
 ],
 "status": {
  "conceptual_critique": "Amber",
  "build": "Amber",
  "human_testing": "Red",
  "operations": "Red"
 }
} as unknown as FinancialDomain;
export default FINANCIAL_DOMAIN;
