/**
 * Sign Doc · Session UX in every language (operator 2026-09-09: "all UX translations, 33 languages"). One file per language,
 * loaded on demand when the Globe selects it (the Divinity Guide's LANG_LOADERS pattern, R-CORE); nothing of them rides in the
 * first bundle. EN is the lexicon's englishDefault; ES is lib/lexicon-translations-es-sign.ts (the first full second language).
 * GENERATED by scripts/gen-i18n-index.mjs from the files present — do not edit by hand.
 */
export const SIGN_LOCALES = ["ar", "bn", "cs", "da", "de", "el", "fi", "fr", "he", "hi", "id", "it", "ja", "ko", "ms", "ne", "nl", "no", "pa", "pl", "pt", "ro", "ru", "sv", "sw", "th", "tl", "tr", "uk", "vi", "zh"] as const;
export type SignLocale = (typeof SIGN_LOCALES)[number];
const LOADERS: Record<SignLocale, () => Promise<{ default: Record<string, string> }>> = {
  ar: () => import("./ar"),
  bn: () => import("./bn"),
  cs: () => import("./cs"),
  da: () => import("./da"),
  de: () => import("./de"),
  el: () => import("./el"),
  fi: () => import("./fi"),
  fr: () => import("./fr"),
  he: () => import("./he"),
  hi: () => import("./hi"),
  id: () => import("./id"),
  it: () => import("./it"),
  ja: () => import("./ja"),
  ko: () => import("./ko"),
  ms: () => import("./ms"),
  ne: () => import("./ne"),
  nl: () => import("./nl"),
  no: () => import("./no"),
  pa: () => import("./pa"),
  pl: () => import("./pl"),
  pt: () => import("./pt"),
  ro: () => import("./ro"),
  ru: () => import("./ru"),
  sv: () => import("./sv"),
  sw: () => import("./sw"),
  th: () => import("./th"),
  tl: () => import("./tl"),
  tr: () => import("./tr"),
  uk: () => import("./uk"),
  vi: () => import("./vi"),
  zh: () => import("./zh"),
};
/** the language's strings from this store, or null when the code has no file */
export async function loadSignLocale(code: string): Promise<Record<string, string> | null> {
  const l = (LOADERS as Record<string, (() => Promise<{ default: Record<string, string> }>) | undefined>)[code];
  if (!l) return null;
  try { return (await l()).default; } catch { return null; }
}
