// THE OPERATOR'S NORTH STAR IS A SINGLE FILE (2026-09-17: "7MB FILE THAT CAN BE USED FOR ON DEMAND GAMING that
// lives on phone or PC HTML FILE"). The carried deck IS that file and R-CORE says the best solution ships regardless
// of which AI wrote it — so it is served as-is at /drone-2525/play.html. This gate holds the things that make that
// honest: the served file is byte-identical to the carried, hashed deck (nothing quietly edited on the way to
// production), it is under the 7.77 MB ceiling measured in BYTES (r.094's lesson), and the revision's operator
// changes are present in the served bytes (the deck's own boot QA proves they WORK at runtime).
import fs from 'node:fs';
import crypto from 'node:crypto';
import { DECK_REV } from './deck-head.mjs';
let pass = 0, fail = 0;
const ok = (c, m) => { if (c) pass++; else { fail++; console.log('FAIL:', m); } };
const REV = DECK_REV;
const FILE_BUDGET = 7_770_000;
const served = fs.readFileSync('public/drone-2525/play.html');
const carried = fs.readFileSync(new URL(`../../docs/drone-2525/operator-deck/drone-2525_r.${REV}.html`, import.meta.url));
const sha = (b) => crypto.createHash('sha256').update(b).digest('hex');
ok(served.length <= FILE_BUDGET, `the served playable is ${served.length} B, under the ${FILE_BUDGET} B ceiling (bytes, not chars)`);
ok(sha(served) === sha(carried), `the served playable is byte-identical to the carried, hashed r.${REV} deck (nothing edited on the way to production)`);
const hashes = fs.readFileSync(new URL(`../../docs/drone-2525/operator-deck/HASHES_r${REV}.sha256`, import.meta.url), 'utf8');
ok(hashes.includes(sha(carried)) && new RegExp(`drone-2525_r\\.${REV}\\.html`).test(hashes), `r.${REV} is in the deck hash ledger`);
const src = served.toString('utf8');
ok(new RegExp(`revision:'0\\.${REV}'`).test(src) && !/r0\.130\b/.test(src) && !/r0\.129\b/.test(src) && !/r0\.123/.test(src), `r.${REV} declares itself and carries no stale bookkeeping`);
// r.129 — still present
ok(/function bullseye\(/.test(src) && /bullseye\(p\.x,p\.y\+1\.2,p\.z,segs\)/.test(src) && /function bullseye\(x,y,z,segs\)/.test(src), 'standing targets carry the white-circle bullseye (r.129)');
ok(/reason:'TWO_HUMANS'/.test(src) && /state\.lobby\.phase==='LIVE'&&!byPeer/.test(src), 'in a live room the red box needs two separate humans (r.129)');
// r.130 — the range with turrets actually works
ok(/function fwdOf\(yaw,tilt\)\{const ct=Math\.cos\(tilt\|\|0\);return \{fx:-Math\.sin\(yaw\)\*ct,fy:Math\.sin\(tilt\|\|0\),fz:Math\.cos\(yaw\)\*ct\};\}/.test(src), 'ONE forward basis: fwdOf is the projector\'s forward (−sin yaw, cos yaw)');
ok(/const f=fwdOf\(yaw,tilt\); return \{x,y:ey,z,yaw,tilt,fx:f\.fx,fy:f\.fy,fz:f\.fz\};/.test(src) && /const fb=fwdOf\(u\.yaw,0\), fx=fb\.fx, fz=fb\.fz;/.test(src) && /const fb=fwdOf\(byaw,0\),fx=fb\.fx,fz=fb\.fz;/.test(src), 'camOf, phys and the driveSign QA all read fwdOf — nothing else derives a forward');
ok(!/Math\.atan2\(dx,-dz\)/.test(src) && (src.match(/aimUnitAt\(/g) || []).length >= 5 && (src.match(/yawTo\(/g) || []).length >= 3, 'every aim goes through aimUnitAt/yawTo (no atan2(dx,−dz) survivor of the old basis)');
ok(!/u\.yaw=Math\.PI;/.test(src) && /Math\.abs\(p0u\.yaw\)<1e-6/.test(src), 'the range pit parks at yaw 0 and faces its plates under the one basis');
ok(/const EXPOSURE_BY_COUNT=\{1:5,2:8,3:12,4:16\};/.test(src) && /const ENG_GAP_S=3;/.test(src) && /function engagementAt\(lane,k\)/.test(src) && /function rangeTick\(dt\)/.test(src) && /if\(\+state\.challenge===0\) rangeTick\(dt\);/.test(src) && !/const EXPOSURE_S=/.test(src), 'r.137: IWQ Table VI engagements — 5/8/12/16 s by count, 3 s between, driven from spawn; the by-distance exposures are gone');
ok(/function plateHit\(q\)/.test(src) && /const hit=!!state\.simDirect \|\| \(ph\?ph\.hit:off<32\);/.test(src) && /const PIP_FLOOR_MRAD=3;/.test(src), 'a silhouette is hit when the pip is inside its projected outline (scale-true), with a declared angular floor');
ok(/function slotBoxes\(\)/.test(src) && /slotBoxes\(\)\.forEach\(b=>segs\(b\.s,b\.col\)\);/.test(src) && !/hc\.moveTo\(r\.cx-hw-4,t\+6\)/.test(src), 'r.149: no edge marker on an unmarked silhouette; the voxel box around every marked slot, amber then red');
ok(/reason:'TARGET_OFF_PICTURE'/.test(src) && /YOUR RED BOX IS ON THE '\+plateWord\(s\.id\)\+' · YOUR BULLSEYE IS NOT/.test(src) && /const ASM_READ_S=1\.4;/.test(src) && /function commit\(d\)\{ \{ let on=false;/.test(src) && /reason:'TAG_NEEDS_RED_BOX'/.test(src) && /reason:'NOT_A_RANGE_TARGET'/.test(src) && !/push\('SSSES'/.test(src) && !/!state\.hiLock &&/.test(src), 'r.150: the fire gate reads the picture (TARGET_OFF_PICTURE, the sentence names the box), a tag needs a red box, a forged red never shoots the bull, the AI reads the HIT for 1.4 s, the SSSES row and the dead hiLock guard are gone');
// r.151 — pop-up targets fire again: the FIRE gate's non-plate branch accepts what the LOCK accepts (LOCK_REACH_PX, never 32), so a marked+approved lawn pop is fireable (its base sits 1.2 m below the drawn silhouette).
ok(/pr\.y>=0&&pr\.y<=H&&Math\.hypot\(pr\.x-W\/2,pr\.y-H\*\.46\)<=LOCK_REACH_PX;/.test(src) && !/Math\.hypot\(pr\.x-W\/2,pr\.y-H\*\.46\)<=32\b/.test(src) && /push\('FIRE_HITS_A_POP'/.test(src), 'r.151: the FIRE gate non-plate branch uses LOCK_REACH_PX (a pop the LOCK reaches is fireable), never the 32 px that refused a marked, approved lawn pop; the FIRE_HITS_A_POP boot-QA row is present in the served bytes');
ok(/function pipOn\(o,c\)/.test(src) && /function markLock\(lk,via\)/.test(src) && /if\(!s\|\|s\.px==null\|\|s\.px>LOCK_REACH_PX\)/.test(src) && /markLock\(lockOn\(\),'BTN'\)/.test(src) && /targetN\(map\[m\[1\]\]\); return;\}/.test(src) && !/if\(s\.dot>0\.82\) return \{id:o\.id/.test(src) && !/aimUnitAt\(su,best,-40,20\)/.test(src) && /const by=m\.peerId\|\|m\.sid\|\|m\.by\|\|pay\.by;/.test(src) && /HIT_WITHOUT_RED_BOX/.test(src) && /state\._asmWhy=why;/.test(src) && /\|\|null; \/\* r\.148: with no mark the refusal names NONE/.test(src), 'r.148: a mark is held only while the bullseye is on it; one door (markLock) for the button, keys and voice; every key obeys the reach; the AI spots through the pip and never moves the seat; APPROVE author from the envelope; a peer HIT needs red on record; FIRE with no box names NONE');
ok(/const LOCK_REACH_PX=48;/.test(src) && /function pipRank\(cands,c,W,H\)/.test(src) && /function pipNearest\(cands,c,W,H\)/.test(src) && !/s\.dot>\.82&&s\.dist<340&&s\.dist<bd/.test(src) && !/s\.dot>\.97&&s\.dist<70&&s\.dist<dd/.test(src) && /return pipRank\(cand,c,W,H\)\.slice\(0,3\)/.test(src), 'r.147: LOCK, T1·T2·T3 and key 1 are the targets nearest the bullseye on the picture (never the nearest in metres, never off the picture), one rule for the range, the Capital and every kind');
ok(/const DRAW_ROW_CEIL_MS=20000, t0=Date\.now\(\);/.test(src) && /const ASM_ROW_CEIL_MS=5000, t1=Date\.now\(\);/.test(src) && !/\},1500\);/.test(src) && !/\}, 700\); \}catch\(e\)\{/.test(src), 'r.146: the deferred QA rows (DRAW_COMPLETES, ASM_MARKED_BY_THE_LOOP) decide on evidence up to a declared ceiling, never on a fixed 1.5 s / 700 ms timer');
ok(/const LANE_MARKER_Z=\[100,200,300\];/.test(src) && /function laneMarkers\(lane\)/.test(src) && /drawPlates\(segs\); drawLaneMarkers\(segs\);/.test(src), 'r.145: numbered lane markers at 100, 200 and 300 m at the lane edges, drawn with the plates');
ok(!/if\(!mine && q\.base!=='C-50'\) return;/.test(src) && /42 lanes × 11 silhouettes = 462 plates/.test(src), 'r.144: the neighbouring lanes draw every silhouette, not only the 50; 42 × 11 = 462 plates');
ok(/function reticleNear\(\)/.test(src) && /const col=near\?T13\.LOCK:T13\.SI;/.test(src) && !/v\.moveTo\(0,H\*\.46\);v\.lineTo\(W,H\*\.46\)/.test(src), 'r.143: no horizon line; a white bullseye that turns red near a target; the bracket red with it');
ok(/eng:\[\['C-50'\],\['C-100C'\],\['C-150L'\]/.test(src) && !/mulberry32\(2525\+\(lane\|0\)\*97/.test(src) && !/magLoad\('PHASE'\)/.test(src) && /PRESS RELOAD · MOVE/.test(src) && /reason:'NO_MAGAZINE'/.test(src), 'r.142: the program names its silhouettes (no per-lane seed); the rest says PRESS RELOAD; four magazines only');
ok(/const EYE=\{inches:12,pxPerIn:926\/6\.08,device:'iPhone 12 Pro Max'\};/.test(src) && /function focalPx\(\)\{ return EYE\.inches\*EYE\.pxPerIn\*zoomClamp\(state\.zoom\); \}/.test(src) && !/38\/zoomClamp/.test(src) && /x:-4\.6,y:0,z:50/.test(src) && /x:4\.6,y:0,z:50/.test(src), 'r.141: life-size at 12 in (one focal length, no 38° field); the 50 L / 50 R at ±4.6 m, the edges of a portrait phone');
ok(/id="tgtPick"/.test(src) && /ALT-C SHEET · 25 M<\/option>/.test(src) && /const SHEET=\{w:0\.4318,h:0\.5588,z:25,base:1\.1\};/.test(src) && /function plateDims\(q\)/.test(src) && /w:0\.660,h:0\.533,form:'F'\}/.test(src) && !/w:0\.495,h:0\.508/.test(src), 'r.140: the F-type is 26 × 21 in; the 25 m Alt-C sheet is a target option; every plate size goes through plateDims');
ok(/function deviceClass\(w,h\)\{ return Math\.min\(w,h\)<600\?'phone':'desk'; \}/.test(src) && /#stage\{grid-row:3\}/.test(src) && /#app\.full\{grid-template-rows:minmax\(0,1fr\)\}/.test(src) && /addEventListener\('orientationchange'/.test(src) && !/innerWidth<820/.test(src), 'r.139: a phone is a phone by its short side; the grid rows are named so FULL fills the screen; rotation re-lays out');
ok(/id="magBar"/.test(src) && /id="btnReload"/.test(src) && /id="btnFull"/.test(src) && /EMPTY_MAGAZINE/.test(src) && /function zoomClamp\(z\)/.test(src) && /function zoomMax\(\)/.test(src) && !/Math\.min\(3\.2,/.test(src) && /function plateCaptionRects\(hc,W,H\)/.test(src) && /#app\.full \.bar/.test(src), 'r.138: reload + counter at the top, full screen, one zoom clamp under the zoom law, one caption placement');
ok(/TRAINING · RESET<\/option>/.test(src) && /TRAINING · DOWN<\/option>/.test(src) && /QUAL · 40<\/option>/.test(src) && /const RANGE_MODE_NAME=\{bounce:'TRAINING · RESET',stay:'TRAINING · DOWN',qual40:'QUAL · 40'\};/.test(src), 'the three range modes carry the operator\'s names');
ok(/function rangeLapse\(q(?:,fromRow)?\)/.test(src) && /qualRecordShot\(false,q\.id\)/.test(src) && /NOT ENGAGED · /.test(src), 'in QUAL · 40 a target not engaged in its window is an unfired MISS round');
ok(/id:'C-100C'/.test(src) && !/C-250B/.test(src) && /id:'C-50L'/.test(src) && /id:'C-50',pos:'50M F',x:4\.6/.test(src), 'the eleven silhouettes follow the 9127 sheet plus the operator\'s 50 L/R (100 m ×3, one 250, one 300, 50 left and right)');
ok(/function kindOfRef\(ref\)/.test(src) && /kind:kindOfRef\(o\)/.test(src) && /by:\(same&&same\.by\)\|\|row\.peerId\|\|SID/.test(src), 'the reducer keeps the target\'s kind and the designator\'s identity — the author designate() wrote comes first (r.133: the AI member\'s mark was re-stamped with the human\'s id)');
ok(/if\(typeof buoys!=='undefined' && u\.kind!=='turret'\) ?buoys\.forEach/.test(src), 'a turret never locks a buoy');
const qaBlock = src.slice(src.indexOf('the range with turrets actually works — one forward basis'), src.indexOf("state.simDirect=sv2.sd; }"));
ok(qaBlock.length > 2000 && !/simDirect=true/.test(qaBlock) && /state\.simDirect=false;/.test(qaBlock), 'the r.130 range QA fires AIMED shots only — no simDirect anywhere in it');
ok(/state\.drawErr=String\(e\);/.test(src) && /id:'DRAW_COMPLETES'/.test(src) && /state\.drawDone=\(state\.drawDone\|\|0\)\+1;/.test(src), 'a render exception is recorded, never hidden, and a deferred QA row reads whether frames ran to their last line');
ok(/function drawPlates\(segs\)/.test(src) && /if\(chNum\(\)===0\)\{ drawPlates\(segs\); (drawLaneMarkers\(segs\); )?RANGE_WIRE\.forEach/.test(src) && /else \{ drawTargets\(segs\); WIRE\.g\.forEach/.test(src), 'what you must hit takes the segment budget before the world — on the range AND on every Capitol channel (r.131)');
for (const row of ['PIT_SEES_300_RIGHT_250_LEFT', 'PAN_RIGHT_MOVES_WORLD_LEFT', 'FWD_AT_YAW90', 'TARGETN_HITS_THE_EXPOSED_PLATE', 'LAPSE_RELEASES_THE_BOX', 'SHEET_SCALES_TO_ANGLE', 'SHEET_HIT_IS_A_HOLE', 'SHEET_DOWN_SCORES_OUT', 'SHEET_QUAL_ENGAGES', 'QUAL_ONE_ROUND_PER_TARGET', 'REDUCER_HIT_AND_LAPSE_DOWN_THE_PLATE', 'IWQ_PROGRAM_IS_40', 'QUAL_EXPOSURE_BY_COUNT', 'QA_LEAVES_NO_TRACE', 'PROJ_FWD_AGREES', 'FWD_IS_WHAT_YOU_SEE_', 'RANGE_SEES_PLATES', 'ALTC_LAYOUT', 'QUAL_50R_FIRST', 'QUAL_SAME_ORDER_EVERY_LANE', 'RANGE_LOCK_PLATE', 'RANGE_HIT_50', 'RANGE_HIT_300', 'RANGE_MISS_300_OFF20', 'EVERY_LANE_HAS_THE_TARGETS', 'NEIGHBOUR_LANES_DRAWN', 'LANE_MARKERS_100_200_300', 'RETICLE_RED_NEAR_TARGET', 'LOCK_IS_THE_THING_IN_THE_CROSSHAIR', 'NO_HORIZON_LINE', 'EYE_SCALE_12_IN', 'FIFTY_AT_THE_EDGES', 'RANGE_HIT_50_OFF2', 'SILHOUETTES_TRUE_SCALE', 'LABELS_DO_NOT_OVERLAP', 'ZOOM_LAW', 'TRAINING_MAG_30', 'EMPTY_MAG_REFUSES', 'RELOAD_ON_RECORD', 'PHASE_NEEDS_RELOAD', 'QUAL_FOUR_MAGS', 'FULL_SCREEN_KEEPS_CONTROLS', 'FULL_FILLS_THE_STAGE', 'FULL_BEATS_DESK', 'TOP_LINES_NEVER_OVERLAP', 'DEVICE_CLASS_BY_SHORT_SIDE', 'TRAIN_ALL_UP', 'TRAIN_NO_LAPSE', 'MODE_RESET_RETURNS', 'MODE_DOWN_STAYS', 'MODE_DOWN_ALL_DOWN', 'QUAL_ENG_TOGETHER', 'QUAL_UNENGAGED_IS_MISS', 'QUAL_PHASE_GAP', 'QUAL_IS_40_ROUNDS']) ok(src.includes(`push('${row}`), `QA row ${row} present`);
ok(/lobby/i.test(src) && /TEAM CODE/.test(src) && /appendCanonicalEvent/.test(src) && /applyWorld/.test(src), 'r.128 carries the lobby, the team codes and the reducer law');
const ux = fs.readFileSync('components/drone-2525/command-ux1.tsx', 'utf8');
ok(/data-drone-play\b/.test(ux) && /\/drone-2525\/play\.html/.test(ux) && /DECK_REV/.test(ux), 'the /drone-2525 shell offers PLAY → the served deck, labelled with the served revision');
const rev2 = (fs.readFileSync('lib/drone-2525/deck-rev.ts', 'utf8').match(/DECK_REV = "(\d+)"/) || [])[1];
ok(rev2 === REV, `lib/drone-2525/deck-rev.ts (${rev2}) and tests/deck-head.mjs (${REV}) name the same HEAD`);
ok(fs.existsSync('public/drone-2525/play.html'), 'the PLAY link target exists in public/ (a soft-404 would serve the SPA)');
console.log(`\ndrone-playable: ${pass} passed, ${fail} failed · r.${REV} served byte-identical, under 7.77 MB, the range changes present in the served bytes`);
process.exit(fail ? 1 : 0);
