// financial-surface — the Financial-2525 screen is wired the way the laws say (operator 2026-09-30, v.000_r.005).
// Source-level gate over the two route pages, the component and the launcher: the route mounts one component; the
// component reads the generated domain, ticks one clock, feeds every number through the pure libraries, converts time
// from the Admin panel's Planet LTU table (the selected planet's whole, day, hours, minutes, anchor), gates recording
// behind the app's login, draws the chart as strokes on the black ground with the MoT ⇄ Clock icon toggle as the card's
// one reveal, carries the R-CORE badge last, and the export (when out/ exists) emits both routes. The pure laws
// themselves are gated in financial-mot / financial-accrual / planet-ltu.
import fs from 'node:fs';
import path from 'node:path';

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) pass++; else { fail++; console.log('FAIL:', m); } };
const read = (p) => fs.readFileSync(p, 'utf8');
const strip = (s) => s.replace(/\/\/[^\n]*\n/g, '\n').replace(/\/\*[\s\S]*?\*\//g, '').trim();

// 1 — two routes, one component, identical bodies (the Drone-2525 route pattern)
const ROUTES = ['app/main/Financial-2525/page.tsx', 'app/financial-2525/page.tsx'];
const bodies = ROUTES.map((r) => { const s = read(r); ok(/^"use client";/.test(s), `${r} is a client page`); ok(/import \{ FinancialCommandUX1 \} from "@\/components\/financial-2525\/command-ux1"/.test(s) && /<FinancialCommandUX1 \/>/.test(s), `${r} mounts the one component`); return strip(s); });
ok(bodies[0] === bodies[1], 'both route bodies are identical once comments are stripped');

// 2 — the component
const ux = read('components/financial-2525/command-ux1.tsx');
ok(/data-financial-ux1/.test(ux), 'the root carries data-financial-ux1 (the live probe hook)');
ok(/from "@\/lib\/financial-2525\/domain\.gen"/.test(ux) && !/docs\/financial-2525/.test(ux), 'reads the generated domain, never docs/');
ok(/setInterval\(\(\) => setNow\(Date\.now\(\)\), 1000\)/.test(ux) && /useState<number \| null>\(null\)/.test(ux), 'one 1 Hz clock, null until mounted (no hydration mismatch)');
ok(!/Math\.random/.test(ux), 'nothing random on the surface');
for (const fn of ['balanceAt', 'series', 'validateWithdrawal']) ok(new RegExp(`\\b${fn}\\b`).test(ux), `every number goes through the pure accrual law (${fn})`);
ok(!/HOLD_MS/.test(ux), "r.025 (addendum 53 + his answer 'Remove from chart'): the surface draws no 180-minute mark; the rule stays inside the accrual law");
for (const fn of ['spanABC', 'fmtMot', 'fmtStampCST', 'parseStampCST']) ok(new RegExp(`\\b${fn}\\b`).test(ux), `MoT in A.B..C and CST stamps come from lib/financial-2525/mot (${fn})`);
ok(/const axis = \[0, 0\.25, 0\.5, 0\.75, 1\]\.map\(\(f\) => fmtMot\(positionInYear\(from \+ f \* len, planet\.yearAnchor, planet\.yearDays\)\.abc\)\);/.test(ux) && /spanABC\(elapsed \/ dayMs, planet\.yearDays\)/.test(ux) && !/\bmotABC\(/.test(ux) && !/MS_PER_DAY/.test(ux), "A.B..C IS the revolution (addenda 10–12): the reveal reads the year position at each axis mark on the planet's anchor and the elapsed span in A-units of the planet's whole — never a period as its own 0→3600, never an Earth constant typed on the surface");
ok(/positionInYear\(now, planet\.yearAnchor, planet\.yearDays\)/.test(ux) && !/frameOf\(/.test(ux) && /data-fin-past-full/.test(ux) && /data-fin-year-table/.test(ux), "r.028 (addendum 58): the year position is a TABLE; no 33-day frame; a year past day 365 carries its flag");
// r.008 (addendum 19) — every category carries its icon from ONE map; the year position takes the planet's revolution
const iconSrc = fs.readFileSync(path.join(process.cwd(), "components/financial-2525/category-icon.tsx"), "utf8");
const catList = /export const BUDGET_CATEGORIES[^=]*=\s*\[([^\]]+)\]/.exec(fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/budget.ts"), "utf8"));
const cats = catList ? [...catList[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]) : [];
ok(cats.length === 10 && cats.every((c) => new RegExp(`(^|\\n)\\s*"?${c.replace(/ /g, " ")}"?:\\s*[A-Z][A-Za-z]+,`).test(iconSrc)), `every one of the ${cats.length} categories has an icon in CATEGORY_ICON (a bare category fails here)`);
ok(/strokeWidth=\{1\.5\}/.test(iconSrc) && /aria-hidden/.test(iconSrc) && !/fill=/.test(iconSrc), "the icons are strokes (1.5), aria-hidden — the word beside them carries the meaning");
ok(/<SectionIcon section=\{section\} className="mr-1" \/>\{t\("fin\.section"\)\}/.test(ux) && /<SectionIcon section=\{fieldOf\(l\.fieldId\)\?\.section \?\? "L"\} className="mr-1\.5" \/>\{fieldLabel\(l\.fieldId\)\}/.test(ux) && /\{txWhat\(e\.tx\)\}/.test(ux) && /<SectionIcon section=\{sec\} className="mr-1" \/>\{fieldLabel\(tx\.field\)\}/.test(ux) && /<CategoryIcon category=\{tx\.category\} className="mr-1" \/>\{catLabel\(tx\.category\)\}/.test(ux), "the icon sits before the section dropdown's label, on every budget line and in the record table's field cell (an r.006–r.011 entry keeps its category icon)");
ok(/positionInYear\(now, planet\.yearAnchor, planet\.yearDays\)/.test(ux) && /positionInYear\(from \+ f \* len, planet\.yearAnchor, planet\.yearDays\)/.test(ux), "every year position on the glass takes the selected planet's revolution (the r.007 Mars axis read Earth positions)");
// r.007 (addendum 18) — the perihelion instant that opens the year is written on the glass in Austin CST standard; the axis marks are three lines
ok(/\[t\("fin\.perihelion_cst"\), `\$\{fmtStampCST\(year\.startMs\)\} CST`\]/.test(ux) && ux.indexOf('t("fin.perihelion_cst")') < ux.indexOf('t("fin.year_today")'), "r.028 (addendum 58 'perihelion is first'): in MoT mode the year table's first row is the perihelion that opened the year, in CST standard");
ok(/a\.replace\("\.", "\\n\."\)\.replace\("\.\.", "\\n\.\."\)/.test(ux), "an A.B..C axis mark is three lines — A / .B / ..C — so B and C never overprint a neighbour at phone width (the r.006 Mars capture)");
// r.005 — the Planet LTU table (Admin panel) drives every conversion; the planet selector; the MoT ⇄ Clock icon toggle is the card's one state
ok(/readPlanetLtu\(\)/.test(ux) && /PLANET_LTU_KEYS\.includes\(e\.key\)/.test(ux) && /planetRow\(planets, planetCode\)/.test(ux) && /daySecOf\(planet\) \* 1000/.test(ux), "every conversion reads the selected planet's row from the Admin panel's LTU table (seed on the server, the device copy after mount, other tabs via storage)");
ok(/useState<PlanetLtuRow\[\]>\(\(\) => \[\.\.\.PLANET_LTU_SEED\]\)/.test(ux) && /setPlanets\(readPlanetLtu\(\)\)/.test(ux), 'the first paint is the seed, the device copy arrives after mount (never a hydration mismatch)');
ok(/data-fin-planet/.test(ux) && /planets\.map\(\(p\) => <option key=\{p\.code\} value=\{p\.code\}>\{p\.name\}<\/option>\)/.test(ux), "a planet selector lists the table's rows (Earth default · Mars)");
ok(/import \{ Check, ChevronDown, ChevronRight, Clock, Orbit, Pencil, Settings, X \} from "lucide-react"/.test(ux) && /function ClockMotToggle\(/.test(ux) && /role="group" data-fin-abc-toggle=\{hook\}/.test(ux) && /aria-pressed=\{abc\} aria-label=\{t\("fin\.show_abc"\)\}/.test(ux) && /aria-pressed=\{!abc\} aria-label=\{t\("fin\.show_ltu"\)\}/.test(ux) && /data-fin-abc-toggle=\{hook\}[\s\S]{0,200}aria-label=\{t\("fin\.show_ltu"\)\}[\s\S]{0,400}aria-label=\{t\("fin\.show_abc"\)\}/.test(ux) && /<ClockMotToggle abc=\{showAbc\} onChange=\{onToggle\} t=\{t\} hook="chart" \/>/.test(ux), "the reveal is one shared Clock ⇄ MoT toggle — Clock on the LEFT, MoT on the RIGHT — used by the chart (r.025) and the year card (r.030)");
ok(/ring-1 ring-inset ring-cyan-500/.test(ux) && !/bg-cyan-500\/15/.test(ux), 'the pressed icon is ringed, never filled (the vector law)');
ok(/const \[yearAbc, setYearAbc\] = useState\(false\);/.test(ux) && /<ClockMotToggle abc=\{yearAbc\} onChange=\{setYearAbc\} t=\{t\} hook="year" \/>/.test(ux) && /\.\.\.\(yearAbc && planet\.code === "earth" \? \[\[t\("fin\.perihelion_cst"\)/.test(ux) && /\.\.\.\(yearAbc \? \[\[t\("fin\.orbit_position"\), fmtMot\(year\.abc\)\]/.test(ux) && /yearAbc \? t\("fin\.year_position"\) : t\("fin\.year_title"\)/.test(ux), "r.030 (addendum 61): the year card has its own Clock / MoT toggle, standard by default; MoT unlocks the perihelion and the orbit position");
ok(/planet\.code !== "earth" && <p[^>]*>\{t\("fin\.anchor_note"\)\}<\/p>/.test(ux), 'on a planet without a perihelion table the year line says so (declared, not sourced)');
// r.006 — every transaction carries its personal-finance category (addendum 16); the budget is a table with a unit toggle (addendum 17)
ok(/<select data-fin-section=\{hook\}/.test(ux) && /\{FLOW_SECTIONS\.map\(\(sec\) => <option key=\{sec\} value=\{sec\}>\{secLabel\(sec\)\}<\/option>\)\}/.test(ux) && /<select data-fin-field=\{hook\}/.test(ux) && /\{fieldsOf\(section\)\.map\(\(f\) => <option key=\{f\.id\} value=\{f\.id\}>\{fieldLabel\(f\.id\)\}<\/option>\)\}/.test(ux) && /<select data-fin-length=\{hook\}/.test(ux) && /\{RECURRENCES\.filter\(\(r\) => r !== "days33" \|\| rec === "days33"\)\.map\(\(r\) => <option key=\{r\} value=\{r\}>\{t\(`fin\.rec\.\$\{r\}`\)\}<\/option>\)\}/.test(ux) && /rec === "other" && \(/.test(ux) && /<input data-fin-length-n=\{hook\}/.test(ux) && /<select data-fin-length-unit=\{hook\}/.test(ux) && /\{LENGTH_UNITS\.map\(\(u\) => <option key=\{u\} value=\{u\}>\{t\(`fin\.u\.\$\{u\}`\)\}<\/option>\)\}/.test(ux) && (ux.match(/<LadderPicker /g) || []).length === 1 && /<LadderPicker[^>]*hook="transaction"/.test(ux) && !/data-fin-category/.test(ux) && !/data-fin-timeline/.test(ux), "the one form carries the SECTION A–M, the FIELD within it, and the LENGTH — presets with Other opening a number in years · days · hours · minutes (addenda 22, 24, 25); one picker, hook transaction; no category or timeline dropdown remains");
ok(/motDays: lengthDays\(rec, Number\(otherN\), otherUnit\), memo: memo\.trim\(\) \|\| undefined, field, recurrence: rec \}\);/.test(ux) && /atMs: instant, motDays: lengthDays\(rec, Number\(otherN\), otherUnit\), memo: memo\.trim\(\) \|\| undefined, field, recurrence: rec \};/.test(ux) && /if \(tx\.field\) \{ const sec = fieldOf\(tx\.field\)\?\.section/.test(ux) && /if \(tx\.category\) return <span>/.test(ux), "the field, the length (as motDays) and the timeline are recorded on the entry of either kind (inside its hash) and shown on the record; an r.006–r.011 entry still prints its category");
// r.013 (addendum 24) — ONE transaction form: the type is the first dropdown; the MoT length is never a typed field; one button whose word follows the type
ok(/data-testid="fin-transaction-form" data-fin-tx-type=\{txType \|\| "none"\}/.test(ux) && /<select data-fin-type className=\{PICK\} value=\{txType\} onChange=\{\(e\) => chooseType\(e\.target\.value as TxKind \| ""\)\}>/.test(ux) && /<option value="" disabled>\{t\("fin\.type_select"\)\}<\/option>/.test(ux) && /<option value="deposit">\{t\("fin\.type_deposit"\)\}<\/option>/.test(ux) && /<option value="withdrawal">\{t\("fin\.type_withdrawal"\)\}<\/option>/.test(ux) && !/fin-deposit-form/.test(ux) && !/fin-withdraw-form/.test(ux) && !/t\("fin\.mot_days"\)/.test(ux) && /data-fin-record disabled=\{!txType\}/.test(ux) && /\{txType === "withdrawal" \? t\("fin\.withdraw"\) : t\("fin\.record_it"\)\}/.test(ux) && /const recordTransaction = \(\) => \{ if \(txType === "deposit"\) recordDeposit\(\); else if \(txType === "withdrawal"\) recordWithdrawal\(\); \};/.test(ux) && /if \(k === "deposit"\) \{ setSec\("A"\); setField\("A\.income_wages"\); setRec\("paymot"\); \} else \{ setSec\("B"\); setField\("B\.rent_mortgage"\); setRec\("once"\); \}/.test(ux) && /useState\("" as TxKind \| ""\)/.test(ux), "ONE transaction form: the type is its first dropdown, BLANK until the person picks Deposit / Funds or Withdrawal / Expense (r.023, addendum 39 + 55); the record button waits until a type is picked; picking re-seats the picker's default; both record paths behind it");
ok(/<select data-fin-budget-unit value=\{budgetUnit\}/.test(ux) && !/role="group" data-fin-budget-unit/.test(ux) && /\{UNITS\.map\(\(u\) => <option key=\{u\.key\} value=\{u\.key\}>\{u\.label\}<\/option>\)\}/.test(ux) && /<table className="mt-2 w-full font-mono text-xs">/.test(ux) && /data-fin-kind=\{g\.kind\}/.test(ux) && /\{groups\.map\(\(g\) => \(/.test(ux) && !/data-fin-budget-row/.test(ux) && /data-fin-ladder-field=\{l\.fieldId\}/.test(ux) && /data-fin-budget-net/.test(ux) && /totals\.net < 0 \? "text-red-500"/.test(ux) && /\{t\("fin\.stock_note"\)\}/.test(ux), "the budget is the ladder grouped by KIND — one row per kind with its total, the lines beneath when opened, Net last and red when negative — under ONE unit dropdown (addenda 20 + 22 → 31); the N–T note under it");
ok(/<select data-fin-budget-unit value=\{budgetUnit\}[^\n]*className="w-full [^"]*landscape:w-auto landscape:min-w-\[14rem\][^"]*"/.test(ux) && /<label className="flex w-full flex-col gap-1 [^"]*landscape:w-auto landscape:flex-row[^"]*">\{t\("fin\.unit"\)\}/.test(ux), "in portrait the unit dropdown is the panel's full width with its label above (addendum 21 — per hour etc. read at the full line); landscape keeps it at its own width beside the label");
ok(/\{ key: "min", label: t\("fin\.per_min"\), period: "minute" \}/.test(ux) && /\{ key: "day", label: t\("fin\.per_day"\), period: "day" \}/.test(ux) && /\{ key: "week", label: t\("fin\.per_week"\), period: "week" \}/.test(ux) && /\{ key: "month", label: t\("fin\.per_month"\), period: "month" \}, \{ key: "quarter", label: t\("fin\.per_quarter"\), period: "quarter" \}/.test(ux) && !/\(91\)`/.test(ux) && /\{ key: "year", label: t\("fin\.per_year"\), period: "year" \}/.test(ux) && /useState<BudgetUnit>\("month"\)/.test(ux), "every view is possible — $/s · $/min · $/h · day · week · 33 days · month (30.333 days) · quarter (91 days) · year — each a fixed PERIOD (FD-25, the month by addendum 34); per month (30.3 repeating days) by default (r.024, addendum 41)");
ok(/const totals = useMemo\(\(\) => netLadder\(plan, period\), \[plan, period\]\);/.test(ux) && /toPeriod\(l\.amountNative, l\.nativePeriod, period\)/.test(ux) && !/ltuDays\(planet\)/.test(ux) && !/\b(86400|1440|525600)\b/.test(ux), "the ladder's figures come from netLadder / toPeriod on the brief's fixed factors (FD-25) — never typed on the surface; the planet's LTU row still drives the clock ladder (daySecOf)");
ok(!/Supabase/.test(ux) && !/Supabase/.test(fs.readFileSync("lib/lexicon-data.ts", "utf8").match(/key: "fin\.device_only"[^\n]*/)[0]), "the record sentence names no vendor (the signer-voice law)");
ok(/append\(record, tx, at\)/.test(ux) && /loadRecord\(owner\)/.test(ux) && /saveRecord\(next\)/.test(ux), 'the record is appended, loaded and saved through lib/financial-2525/record');
ok(/import { type BudgetCategory } from "@\/lib\/financial-2525\/budget"/.test(ux) && /from "@\/lib\/financial-2525\/plan"/.test(ux) && /from "@\/lib\/financial-2525\/ladder"/.test(ux) && !/summarize\(/.test(ux), 'the ladder comes from lib/financial-2525/ladder over the plan of the person (lib/financial-2525/plan, the sheet bridged in budget.ts until they edit); the r.001 summarize is no longer on the glass');
ok(/useAuth0\(\)/.test(ux) && /loginWithRedirect\(\{ appState: \{ returnTo: /.test(ux) && /user\?\.sub/.test(ux), 'each user their own login: Auth0 gates recording, keys the record, and returns the person HERE after login');
ok(/\{owner \? \(/.test(ux) && /data-fin-forms/.test(ux), 'the deposit / withdrawal forms render only for a signed-in person');
// r.002 — the surface STARTS FROM the ◬ ♡ 웃 Session shell (operator addendum 7): its root, header, rail, guide, roster, clock, strip, Trinity
ok(/className="mx-auto max-w-3xl px-4 pb-20 pt-10 sm:pb-10"/.test(ux) && /<SoiGlobe \/>/.test(ux) && /<TrinityGlyphs size="text-3xl"/.test(ux), 'the Session root and header: the globe and the Trinity glyphs');
ok(/<PodPhaseRail phase=\{phase\} phases=\{FIN_PHASES\} countFor=\{countFor\}/.test(ux) && !/PodRosterList/.test(ux), "the Session rail (five financial phases), reused not redrawn; the \"Your deposits\" list is gone (r.025 — his answer to \"remove transactions\")");
ok(!/data-testid="fin-your-turn"/.test(ux) && /font-mono text-2xl tabular-nums text-cyan-500/.test(ux) && !/data-testid="fin-strip"/.test(ux) && /<SoITrinity /.test(ux), "r.028 (addendum 58 'remove gold top box'): no YOUR TURN card, no strip; the Accrual Units figure and the folded Trinity keep the Session's classes");
ok(/const CARD = "mt-8 rounded-xl border border-border bg-card p-5"/.test(ux) && !/VECTOR_LAW\.ground/.test(ux), 'the chrome is the app theme card (bg-card), not a fresh black console');
ok(/<SoITrinity labels=\{\[t\("fin\.wheel\.hi"\), t\("fin\.wheel\.si"\), t\("fin\.wheel\.ai"\)\]\}/.test(ux), 'the Trinity wheel seats the operator\'s way: TOP HI 웃 · BOTTOM-RIGHT SI ♡ minutes · BOTTOM-LEFT AI ◬ tokens (addendum 9; SoITrinity tuple = [top, bottom-right, bottom-left])');
ok(/const ticks = showAbc \? \[\] : dayTicks\(from, to, fit\);/.test(ux) && /rotate\(-\$\{angle\}deg\)/.test(ux) && !/<g data-fin-date-axis/.test(ux) && /\{dateLabel\(tk, dateFmt\)\}/.test(ux) && /\{showAbc && <div data-fin-axis/.test(ux), "the chart's Clock mode reads CALENDAR DATES at the chosen angle — as many whole days as fit at that angle; A.B..C is the reveal");
ok(/data-fin-signin/.test(ux) && /fin\.example_badge/.test(ux), 'an unsigned visitor sees the example badge and a sign-in');
ok(/const EXAMPLE: FinTx = \{[\s\S]*?SRC\.example\.amountUsd[\s\S]*?SRC\.example\.depositStamp[\s\S]*?SRC\.example\.motDays/.test(ux), 'the worked example is read from the domain source, never typed on the surface');
ok(/data-fin-chart/.test(ux) && /<svg viewBox/.test(ux) && /<polyline fill="none"/.test(ux) && !/fill="#/.test(ux), 'the chart is strokes on the black ground — no face is painted');
ok(/const \[dateFmt, setDateFmt\] = useState\("full" as DateFmt\);/.test(ux) && /localStorage\.getItem\("fin-date-fmt"\)/.test(ux) && /localStorage\.setItem\("fin-date-fmt", f\)/.test(ux) && /data-fin-date-gear aria-expanded=\{gear\} aria-label=\{t\("fin\.settings"\)\}/.test(ux) && /\{DATE_FMTS\.map\(\(f\) => \(/.test(ux) && /\{DATE_ANGLES\.map\(\(a\) => \(/.test(ux) && /localStorage\.setItem\("fin-date-angle", String\(a\)\)/.test(ux) && /new Intl\.DateTimeFormat\(locale \|\| "en", \{ month: "long"/.test(ux), "r.028 (addendum 58 'Settings should open up date format for table, and angle for chart text'): the chart's gear opens the date format AND the angle (0° · 30° · 45° · 90°), both remembered on this phone");
ok(/data-fin-chart-svg onClick=\{probeAt\}>/.test(ux) && !/touch-none/.test(ux) && !/onPointerMove/.test(ux) && /data-fin-chart-probe-line/.test(ux) && /<p data-fin-chart-probe className="mt-1 font-mono text-xs text-foreground">\{fmtStampCST\(probe\)\} CST<\/p>/.test(ux) && /aria-label=\{t\("fin\.chart_tap"\)\}/.test(ux), "r.025 (addendum 42 'find way to click on to see day / time stamp'): a tap on the chart draws a line there and reads its day and time; r.026 — the chart no longer captures swipes, so the page still scrolls over it on a phone");
ok(!/\{tx\.motDays\} ·/.test(ux) && !/\$\{e\.tx\.motDays\}/.test(ux) && /\{fmtDays\(tx\.motDays \?\? 0\)\}/.test(ux) && /fmtDays\(e\.tx\.motDays\)/.test(ux) && /\{fmtDays\(EXAMPLE\.motDays \?\? 0\)\}/.test(ux), "every MoT-day count on the surface prints through fmtDays — 30.3̅, never 30.333333333333332");
ok(/<summary className="min-h-\[36px\] cursor-pointer py-2 text-xs text-muted-foreground" aria-label=\{t\("fin\.trinity_aria"\)\} title=\{t\("fin\.trinity_aria"\)\} \/>/.test(ux) && !/t\("fin\.trinity_caption"\)/.test(ux) && /labels=\{\[t\("fin\.wheel\.hi"\), t\("fin\.wheel\.si"\), t\("fin\.wheel\.ai"\)\]\}/.test(ux), "r.025 (addendum 40 + his answer 'Folded, bare arrow'): the Trinity wheel folds behind a bare arrow — no words on the glass, an accessible name for screen readers; its rings read the three keys");
ok(/VECTOR_LAW\.stroke/.test(ux) && /TRINITY_COLORS/.test(ux), 'the chart stays under the vector law: stroke widths from VECTOR_LAW, colours from the 13');
ok(/data-fin-balance/.test(ux) && /data-fin-budget/.test(ux) && /data-fin-ledger/.test(ux) && /data-fin-year/.test(ux), 'balance, budget, record and year panels carry their hooks');
ok(/<RCoreBadge history=\{FINANCIAL_RCORE_HISTORY\} accent=/.test(ux) && /fromLedgerJson\(FINANCIAL_LEDGER\)/.test(ux), 'the R-CORE badge is mounted last from the Financial ledger');
const lastTag = ux.lastIndexOf('<RCoreBadge'); const rootClose = ux.lastIndexOf('</div>\n  );\n}', ux.indexOf('function MotChart'));
ok(lastTag > 0 && rootClose > lastTag, 'the badge is the last child of the root (bottom of the page)');
ok(/versionStamp\(/.test(ux), 'the U-WF-12 version stamp is printed');
ok(/fin\.device_only/.test(ux) && /fin\.chain_broken/.test(ux), 'the record says where it lives and whether its chain held');

// 3 — the launcher tile
const launcher = read('components/vision-2525-launcher.tsx');
ok(/code: "FINANCIAL-2525"/.test(launcher) && /router\.push\("\/financial-2525"\)/.test(launcher), 'the VISION • 2525 launcher carries the FINANCIAL tile → /financial-2525 (the canonical address, addendum 15; /main/Financial-2525 the alias)');

// 4 — the export emits both routes when out/ exists
for (const r of ['out/main/Financial-2525/index.html', 'out/financial-2525/index.html']) {
  if (!fs.existsSync('out')) { pass++; continue; }
  ok(fs.existsSync(r) && fs.statSync(r).size > 2000, `${r} is exported (> 2 KB)`);
}
ok(path.basename(process.cwd()) === 'frontend', 'runs from frontend/');

// r.014 — THE PICKER LAW (operator addendum 26 "this drop down goes away quick!"): a dropdown stays open until the person picks.
// A component declared inside the render body is a new type every render; the once-a-second clock remounts its <select> and the
// phone dismisses the picker sheet. Every picker is a module-level component with a stable identity.
ok(/^function LadderPicker\(\{ section, field, rec, onSection, onField, onRec, otherN, onOtherN, otherUnit, onOtherUnit, t, hook \}/m.test(ux), 'LadderPicker is declared at module level (column 0), its Other state and t passed as props');
ok(!/^\s+const [A-Z][A-Za-z]+ = \(/m.test(ux) && !/^\s+function [A-Z][A-Za-z]+\(/m.test(ux), 'no component is declared inside the render body (a nested component remounts its <select> on every clock tick — r.006 CategorySelect, r.012 LadderPicker)');
ok(/^const PICK = "w-full rounded-md/m.test(ux), 'the picker class string is module-level too');
ok(/<LadderPicker section=\{sec\} field=\{field\} rec=\{rec\} onSection=\{setSec\} onField=\{setField\} onRec=\{setRec\} otherN=\{otherN\} onOtherN=\{setOtherN\} otherUnit=\{otherUnit\} onOtherUnit=\{setOtherUnit\} t=\{t\} hook="transaction" \/>/.test(ux), 'the one form mounts the module-level picker with the Other state from the surface');
ok(/THE PICKER LAW \(r\.014/.test(ux), 'the law is written into the file beside the component');

// r.015 (addendum 27) — every section A–T has its OWN stroke; U (the amortize rule) has none by design
{
  const ladderSrc = fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/ladder.ts"), "utf8");
  const secIds = [...ladderSrc.matchAll(/\{ id: "([A-Z])", name: "[^"]+", plane: "[^"]+", key: "[a-z]" \}/g)].map((m) => m[1]);
  const map = /export const SECTION_ICON: Record<SectionId, LucideIcon> = \{([^}]+)\}/.exec(iconSrc);
  const entries = map ? [...map[1].matchAll(/\b([A-Z]): ([A-Z][A-Za-z]+),/g)].map((m) => [m[1], m[2]]) : [];
  const icons = Object.fromEntries(entries);
  ok(secIds.length === 20 && secIds.join("") === "ABCDEFGHIJKLMNOPQRST", `the ladder declares the twenty sections A–T (${secIds.join("")})`);
  ok(secIds.every((id) => icons[id]), `every section A–T has an icon in SECTION_ICON (missing: ${secIds.filter((id) => !icons[id]).join(" ") || "none"})`);
  ok(new Set(Object.values(icons)).size === entries.length && entries.length === 20, `the twenty section strokes are all distinct (${entries.length} entries, ${new Set(Object.values(icons)).size} strokes)`);
  ok(!icons.U && !/\bU: /.test(map ? map[1] : ""), "U is the amortize rule, never a section — it has no icon by design");
  ok(entries.every(([, name]) => new RegExp(`\\b${name}\\b`).test(iconSrc.split("\n").find((l) => l.startsWith("import {")) ?? "")), "every section stroke is imported from lucide (a name that is not imported would render nothing)");
  ok(/data-fin-tx-field=\{tx\.field\}><SectionIcon section=\{sec\}/.test(ux) && /<tr key=\{l\.fieldId\} data-fin-ladder-field=\{l\.fieldId\}[^\n]*<SectionIcon section=\{fieldOf\(l\.fieldId\)\?\.section \?\? "L"\}/.test(ux), "the record table and every budget line draw the section's stroke before its word (r.018: the letter never)");
}

// R-CORE toggle (operator 2026-09-30) — the page's last element must clear the phone strip: the maximized icon under the badge
// measured UNDER the fixed strip (elementFromPoint returned the strip's span) until the surface gained phone bottom padding.
ok(/<div data-financial-ux1 className="mx-auto max-w-3xl px-4 pb-20 pt-10 sm:pb-10">/.test(ux), "the surface pads its bottom on the phone (pb-20) so the R-CORE badge and its icon sit above the app's bottom bar");
// r.017 (addendum 29 "your deposit withdrawal floats; very odd") — NOTHING ON THE SURFACE FLOATS: the strip is the Released card's last row
ok(!/className="fixed |className="sticky /.test(ux) && !/position: "fixed"/.test(ux), "no fixed or sticky element inside the surface (a fixed element positioned against another element's assumed height is the class)");
ok(!/data-fin-tx-open-strip/.test(ux) && (ux.match(/data-fin-tx-open /g) || []).length === 1 && ux.indexOf("data-fin-tx-top") < ux.indexOf("data-fin-balance"), "r.028 (addendum 58 'one primary at top'): ONE + Transaction, above the Accrual Units card; no strip button, no YOUR TURN button");


// r.016 (addendum 28) — EDIT MODE behind an icon on the budget: the plan drives the ladder; typed in the unit, stored on the base
ok(/import \{ loadPlan, savePlan, clearPlan, sheetPlan, planOrSheet, setLineAmount, addLine, removeLine, lineInUnit \} from "@\/lib\/financial-2525\/plan"/.test(ux) && !/SHEET_LINES/.test(ux), "the surface reads the person's plan through lib/financial-2525/plan and never the sheet constant directly");
ok(/const totals = useMemo\(\(\) => netLadder\(plan, period\), \[plan, period\]\);/.test(ux) && /const groups = useMemo\(\(\) => groupByKind\(plan, period\), \[plan, period\]\);/.test(ux) && /isOpen\(g\.kind\) && g\.lines\.map\(\(l\) =>/.test(ux), "every kind total, every line and Net follow the plan (the lines through groupByKind)");
ok(/<button type="button" data-fin-budget-edit aria-pressed=\{editing\} aria-label=\{editing \? t\("fin\.done"\) : t\("fin\.edit"\)\}/.test(ux) && /\{editing \? <Check size=\{14\} strokeWidth=\{1\.5\} aria-hidden \/> : <Pencil size=\{14\} strokeWidth=\{1\.5\} aria-hidden \/>\}/.test(ux) && /ring-1 ring-inset ring-cyan-500" : "border-border"/.test(ux), "the pencil icon opens edit mode and the check closes it; the pressed state is a stroke ring, never a fill");
ok(/data-fin-plan-amount=\{l\.fieldId\}[^\n]*inputMode="decimal"/.test(ux) && /value=\{drafts\[l\.fieldId\] \?\? String\(editFigure\(l\)\)\}/.test(ux) && /const editFigure = \(l: LadderLine\) => \{ const v = toPeriod\(l\.amountNative, l\.nativePeriod, period\); return Math\.abs\(v\) < 100 \? Math\.round\(v \* 10000\) \/ 10000 : lineInUnit\(l, period\); \};/.test(ux) && /writePlan\(setLineAmount\(plan, fieldId, n, period\)\)/.test(ux), "in edit mode each line's amount is a field in the picked unit, held as a draft while typing and written on the 33-day base");
ok(/data-fin-plan-remove=\{l\.fieldId\}[^\n]*onClick=\{\(\) => writePlan\(removeLine\(plan, l\.fieldId\)\)\}/.test(ux), "a line can be removed");
ok(/data-fin-plan-add\b/.test(ux) && /<select data-fin-plan-section className=\{PICK\}/.test(ux) && /<select data-fin-plan-field className=\{PICK\}/.test(ux) && /data-fin-plan-add-btn[^\n]*writePlan\(addLine\(plan, id\)\)/.test(ux), "a line can be added — section, then a field not yet on the plan, full-width pickers (FD-24), inline (the picker law)");
ok(/data-fin-plan-reset onClick=\{\(\) => \{ if \(owner\) clearPlan\(owner\); setPlan\(sheetPlan\(\)\);/.test(ux) && /if \(owner && !savePlan\(owner, next\)\) setSaveFailed\(true\)/.test(ux) && /setPlan\(planOrSheet\(loadPlan\(owner\)\)\)/.test(ux), "the plan is saved on the device under the person's key, loaded at sign-in, and Reset returns to the sheet");
ok(/\{owner && \(\s*<button type="button" data-fin-budget-edit/.test(ux), "only a signed-in person sees the pencil (the sheet stays the read-only example)");

// r.018 (addendum 31 "order by fixed vs financial, and have expand button so this is not so busy. Don't show A-U letters")
ok(!/\{sec\} · /.test(ux) && !/A–M|A–U|A-M|A-U/.test(ux.replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*/g, "")), "no A–U letter reaches the glass: no '{sec} · ' prefix and no A–M / A–U in rendered text (comments excepted)");
ok(/<tr data-fin-kind=\{g\.kind\} data-fin-kind-open=\{isOpen\(g\.kind\) \? "1" : "0"\}/.test(ux) && /<button type="button" data-fin-kind-toggle=\{g\.kind\} aria-expanded=\{isOpen\(g\.kind\)\} aria-label=\{isOpen\(g\.kind\) \? t\("fin\.collapse"\) : t\("fin\.expand"\)\}/.test(ux) && /\{isOpen\(g\.kind\) \? <ChevronDown size=\{14\} strokeWidth=\{1\.5\} aria-hidden \/> : <ChevronRight size=\{14\} strokeWidth=\{1\.5\} aria-hidden \/>\}\{kindLabel\(g\.kind\)\}/.test(ux), "one row per kind with a chevron (aria-expanded, Show the lines / Hide the lines) and the kind's name");
ok(/const \[openKinds, setOpenKinds\] = useState\(\[\] as FieldKind\[\]\);/.test(ux) && /const isOpen = \(k: FieldKind\) => editing \|\| openKinds\.includes\(k\);/.test(ux), "the groups start collapsed; edit mode opens every group so its fields are reachable");
ok(/const kindLabel = \(k: FieldKind\) => \(k === "Transfer" \? t\("fin\.sec\.m"\) : t\(`fin\.\$\{k\.toLowerCase\(\)\}`\)\);/.test(ux), "the kinds read Income · Fixed · Variable (r.006's keys) and Transfers (the section's own name)");
ok(/<th className="py-1 pr-2">\{t\("fin\.category"\)\}<\/th>/.test(ux), "the table's first column is headed Category, not Section");

// r.019 (addendum 33 "make table 2x2") — the Released card's four figures as a 2 × 2 table, each word above its figure
{
  const order = ["escrowed", "released", "spent"];
  const cellOk = (c) => new RegExp('data-fin-cell="' + c + '"><dt[^>]*>\\{t\\("fin\\.' + c + '"\\)\\}</dt><dd[^>]*>\\{usd\\(bal\\.' + (c === "spent" ? "withdrawn" : c) + 'Cents\\)\\}</dd>').test(ux);
  const pos = order.map((c) => ux.indexOf('data-fin-cell="' + c + '"'));
  ok(/<dl data-fin-balance-grid className="mt-3 grid w-full grid-cols-3 gap-x-3">/.test(ux) && order.every(cellOk) && pos.every((x, i) => x > 0 && (i === 0 || x > pos[i - 1])) && !/data-fin-cell="available"/.test(ux) && !/data-fin-cell="withdrawable"/.test(ux), "r.029 (addendum 60): three boxes — In Escrow · Released · Spent — across the card; Available is the figure above, never repeated");
  ok(!/\{t\("fin\.escrowed"\)\}:<\/span>/.test(ux), "the run-on line of four figures is gone");
}

// r.021 (addendum 35 "on input of transaction or budget, must be able to specify time (MoT of transaction)") — every budget line its own MoT
ok(!/data-fin-plan-rec=/.test(ux) && !/data-fin-plan-n=/.test(ux) && !/data-fin-plan-unit=/.test(ux) && !/data-fin-plan-add-amount/.test(ux) && !/data-fin-plan-add-rec/.test(ux) && !/switchRec|isValidSpec|lineSpec|setLineSpec|BUDGET_RECURRENCES/.test(ux), "r.024 (addenda 48 · 50: \"don't change budget inplementetion; this is way too complicated and I never asked for it\"): no per-line MoT dropdown, no Other field, no add-row amount or MoT — the r.021–r.022 editor is gone");
ok(/<select data-fin-budget-unit value=\{budgetUnit\}/.test(ux) && (ux.match(/data-fin-budget-unit/g) || []).length === 1 && /writePlan\(setLineAmount\(plan, fieldId, n, period\)\)/.test(ux), "r.024 (his answer \"One, shared\"): ONE Unit dropdown — in edit mode the amounts are typed in the unit picked, out of edit mode it converts the view");
ok(/const \[rateUnit, setRateUnit\] = useState\("hr" as RateUnit\);/.test(ux) && /const RATE_UNITS: readonly RateUnit\[\] = \["sec", "min", "hr", "day"\];/.test(ux) && /<select data-fin-rate-unit aria-label=\{t\("fin\.rate_unit"\)\} value=\{rateUnit\}/.test(ux) && /\{RATE_UNITS\.map\(\(u\) => <option key=\{u\} value=\{u\}>\{t\(`fin\.rate\.\$\{u\}`\)\}<\/option>\)\}/.test(ux) && !/t\("fin\.per_hour"\)\} · \{usd/.test(ux) && /u === "hr" \? bal\.ratePerMinCents \* planet\.minPerHour/.test(ux), "r.024 (addendum 46 + his answer): the Released card shows ONE rate figure with a /sec · /min · /hr · /day dropdown, per hour by default; the three-figure line is gone; the figure is the live $/min times the planet's units");
ok(/const \[formOpen, setFormOpen\] = useState\(false\);/.test(ux) && /\{!formOpen \? \(\s*<button type="button" data-fin-tx-open aria-expanded=\{false\} onClick=\{openForm\}[^>]*>\{t\("fin\.tx_open"\)\}<\/button>\s*\) : \(\s*<div id="fin-transaction-form"/.test(ux) && /data-fin-tx-close[^>]*onClick=\{foldForm\}/.test(ux), "r.023 (addendum 38): the transaction entry is folded behind + Transaction and opens only when pressed; an X folds it back");
ok(/const openForm = \(\) => \{ if \(formOpen\) \{ goTo\("fin-transaction-form"\); return; \} setTxType\(""\); setRefusal\(null\);/.test(ux) && !/action: openForm \}/.test(ux) && !/openForm\("(deposit|withdrawal)"\)/.test(ux) && !/t\("fin\.guide\.first_deposit"\)/.test(ux), "r.028: the one door opens the ONE form with the type blank; no door names a deposit or a withdrawal");
ok(/setAmt\(""\); setMemo\(""\); setWhen\(""\); foldForm\(\);\n  \};/.test(ux) && /commit\(w\); setAmt\(""\); setMemo\(""\); setWhen\(""\); foldForm\(\);/.test(ux) && (ux.match(/foldForm\(\);/g) || []).length >= 2 && /\{saveFailed && <p className="mb-2 text-sm text-amber-500">\{t\("fin\.save_failed"\)\}<\/p>\}\s*\{\/\*[^*]*\*\/\}\s*\{!formOpen \?/.test(ux), "r.023 (his answer 'Folds back'): after a recorded deposit or withdrawal the entry folds back; a failed save is said OUTSIDE the fold");
ok(/reason === "INSUFFICIENT" \? `\$\{t\("fin\.reason_insufficient_by"\)\} \$\{fmtStampCST\(v\.atMs \?\? instant\)\}`/.test(ux) && !/reason === "HOLD"/.test(ux), "a refused withdrawal names the minute it would run short; there is no HOLD refusal (r.028, addendum 57)");
ok(/querySelector\("select\[data-fin-type\], input"\)/.test(ux), "r.023: a door lands on the form's TYPE dropdown — the first choice the person makes");
ok(/id: `d-\$\{instant\}-\$\{cents\}-\$\{record\.entries\.length \+ 1\}`/.test(ux) && /id: `w-\$\{instant\}-\$\{cents\}-\$\{record\.entries\.length \+ 1\}`/.test(ux), "r.026: two entries with the same amount at the same typed day and time are two entries — the id carries the record's next number, so the second is never taken for the first and silently dropped");
ok(ux.indexOf("data-fin-date-months") > 0 && ux.indexOf("data-fin-date-months") < ux.indexOf("<div data-fin-date-axis data-fin-angle"), "r.026: the month name sits OVER the day numbers (his \"October / with / 01, 02, 03\")");
ok(/\{!showAbc && ticks\.length === 0 && <div data-fin-axis/.test(ux), "r.026: a MoT that crosses no midnight keeps the day · hour · minute marks instead of an empty axis");
ok(/className="min-h-\[36px\] rounded-md border border-border bg-background px-1 py-0\.5 text-xs text-cyan-500"/.test(ux), "r.026: the rate dropdown is a 36 px touch target (mobile rule)");
{ const pg = fs.readFileSync(new URL("../app/SoI-2525/page.tsx", import.meta.url), "utf8");
  ok(/const numBox = \(key: string, shown: string, onNum: \(n: number\) => void\) => \(\{/.test(pg) && /\{\.\.\.numBox\(`\$\{r\.code\}:monthDays`/.test(pg) && /\{\.\.\.numBox\(`\$\{r\.code\}:yearDays`/.test(pg) && !/numOf\(/.test(pg) && /<span data-planet-month-repeat[^>]*>\{fmtDays\(r\.monthDays\)\}<\/span>/.test(pg), "r.026: the Admin panel's planet number boxes keep what is typed (\"30.\" stays) so 30.333 and 365.25 can be typed; the Month shows 30.3 repeating beside it"); }
ok(/\{txType && <LadderPicker section=\{sec\}/.test(ux), "r.027 (decision 5): Section, Field and Length appear only once a type is picked");
ok(!/data-fin-hold-line/.test(ux) && !/holdUntilMs/.test(ux) && !/t\("fin\.(hold_180|reason_hold_180|reason_hold|hold_mark|guide\.held|ph\.hold)"\)/.test(ux) && !/key: "hold"/.test(ux), "r.028 (addendum 57 'THERE IS NO 180 min hold'): no hold line, no hold refusal, no HOLD step on the rail");
ok(!/centerGlyphs/.test(ux), "r.027 (decision 10): the wheel's centre symbols are gone — each symbol shows once, on its ring");
ok(/<select data-fin-length=\{hook\}/.test(ux) && /RECURRENCES\.filter\(/.test(ux), "the transaction form keeps its own MoT (Length) for every type; the 33-day preset is not offered (r.028)");

// ── r.028 (addenda 57 · 58, the morning feedback) ──────────────────────────────────────────────
ok(!/fin\.version|SRC\.project\.revision\}<\/p>/.test(ux.slice(ux.indexOf("<header"), ux.indexOf("</header>"))) && /<p data-fin-subtitle[^>]*><span className="block">\{t\("fin\.title_l1"\)\}<\/span><span[^>]*>\{t\("fin\.title_l2"\)\}<\/span><\/p>/.test(ux), "r.028: the header reads 'Measure of Time' / 'A Universal Standard' and carries no version (it is at the bottom)");
ok(!/t\("fin\.chart_title"\)/.test(ux), "r.028: 'Money as time — this MoT' is gone from every place on the surface");
ok(/data-fin-balance[\s\S]*?t\("fin\.accrual_units"\)[\s\S]*?data-fin-accrual-gear[\s\S]*?data-fin-current[\s\S]*?\{t\("fin\.available"\)\}:[\s\S]*?data-fin-rate[\s\S]*?data-fin-rate-unit/.test(ux) && !/WITHDRAW|data-fin-phase-pill/.test(ux.slice(ux.indexOf("data-fin-balance"), ux.indexOf("{/* the chart"))), "r.028: Accrual Units — gear upper right, 'Available:' balance on the LEFT, the $/min and its selector on the RIGHT, no Withdraw pill");
ok(/data-fin-balance className="-mx-2 [^"]*sm:mx-0"/.test(ux), "r.028: the Accrual Units card runs the full width on a phone in portrait");
ok(/data-fin-chart-controls className="mt-2 flex items-center justify-between gap-2">\s*\{selector\}/.test(ux), "r.028: Planet on the left, the Clock · MoT toggle and the gear on the right");
ok(/<details data-fin-ledger/.test(ux) && /data-fin-ledger-scroll className="mt-2 overflow-x-auto"/.test(ux) && /data-fin-ledger-table className="min-w-full whitespace-nowrap/.test(ux), "r.028: the Record folds behind a chevron; opened, a table with one entry per line that scrolls sideways");
ok(!/t\("fin\.frame"\)|t\("fin\.per_33"\)|\/33</.test(ux) && !/key: "m33"/.test(ux), "r.028 (addendum 58 'remove all 33 day reference'): no 33-day frame, unit or label on the glass");

ok(/data-fin-accrual-defs/.test(ux) && /\(\["available", "escrowed", "released", "spent"\] as const\)\.map/.test(ux) && /t\(`fin\.def\.\$\{k\}`\)/.test(ux), "r.029 (addendum 60 'what each does … in settings'): the Accrual Units gear explains Available, In Escrow, Released and Spent");

ok(/\{ key: "calmonth", label: calDays \? `\$\{t\("fin\.per_cal_month"\)\} \(\$\{calName\} · \$\{calDays\} \$\{t\("fin\.days"\)\}\)` : t\("fin\.per_cal_month"\), period: "calmonth" \},\s*\{ key: "month"/.test(ux) && /setCalendarMonth\(now\)/.test(ux), "r.031 (addendum 62): the standard calendar month (its name and real length) sits in the unit list right before the 30.3̅-day month");

{ const th = (ux.match(/data-fin-ledger-table[\s\S]*?<\/thead>/) || [""])[0]; const order = ["fin.amount", "fin.category", "fin.memo", "fin.when", "fin.length", "fin.type"].map((k) => th.indexOf(`t("${k}")`)); const hashAt = th.indexOf('t("fin.hash")');
  ok(order.every((x, i) => x > 0 && (i === 0 || x > order[i - 1])) && hashAt > order[5] && /\{e\.tx\.kind === "deposit" \? "\+" : "−"\}\{usd\(e\.tx\.amountCents\)\}/.test(ux), "r.032 (addendum 63): the Record leads with the signed Amount, then Category; then Memo · Day and time · Length · Type; # and Hash last"); }

console.log(`\nfinancial-surface: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
