// financial-surface — the Financial-2525 screen is wired the way the laws say (operator 2026-09-30, v.000_r.005).
// Source-level gate over the two route pages, the component and the launcher: the route mounts one component; the
// component reads the generated domain, ticks one clock, feeds every number through the pure libraries, converts time
// from the Admin panel's Planet LTU table (the selected planet's whole, day, hours, minutes, anchor), gates recording
// behind the app's login, draws the chart as strokes on the black ground with the MoT ⇄ Clock icon toggle as the card's
// one reveal, carries the R-CORE badge last, and the export (when out/ exists) emits both routes. The pure laws
// themselves are gated in financial-mot / financial-accrual / planet-ltu.
import fs from 'node:fs';
import path from 'node:path';

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) pass++; else { fail++; console.log('FAIL:', m); } };
const read = (p) => fs.readFileSync(p, 'utf8');
const strip = (s) => s.replace(/\/\/[^\n]*\n/g, '\n').replace(/\/\*[\s\S]*?\*\//g, '').trim();

// 1 — two routes, one component, identical bodies (the Drone-2525 route pattern)
const ROUTES = ['app/main/Financial-2525/page.tsx', 'app/financial-2525/page.tsx'];
const bodies = ROUTES.map((r) => { const s = read(r); ok(/^"use client";/.test(s), `${r} is a client page`); ok(/import \{ FinancialCommandUX1 \} from "@\/components\/financial-2525\/command-ux1"/.test(s) && /<FinancialCommandUX1 \/>/.test(s), `${r} mounts the one component`); return strip(s); });
ok(bodies[0] === bodies[1], 'both route bodies are identical once comments are stripped');

// 2 — the component
const ux = read('components/financial-2525/command-ux1.tsx');
ok(/data-financial-ux1/.test(ux), 'the root carries data-financial-ux1 (the live probe hook)');
ok(/from "@\/lib\/financial-2525\/domain\.gen"/.test(ux) && !/docs\/financial-2525/.test(ux), 'reads the generated domain, never docs/');
ok(/setInterval\(\(\) => setNow\(Date\.now\(\)\), 1000\)/.test(ux) && /useState<number \| null>\(null\)/.test(ux), 'one 1 Hz clock, null until mounted (no hydration mismatch)');
ok(!/Math\.random/.test(ux), 'nothing random on the surface');
// r.071 AsM: the check is validateRecord over the record exactly as the card counts it (validateWithdrawal stays in the library for a single entry)
for (const fn of ['balanceAt', 'series', 'validateRecord']) ok(new RegExp(`\\b${fn}\\b`).test(ux), `every number goes through the pure accrual law (${fn})`);
ok(!/HOLD_MS/.test(ux), "r.025 (addendum 53 + his answer 'Remove from chart'): the surface draws no 180-minute mark; the rule stays inside the accrual law");
for (const fn of ['spanABC', 'fmtMot', 'fmtStampCST', 'parseStampCST']) ok(new RegExp(`\\b${fn}\\b`).test(ux), `MoT in A.B..C and CST stamps come from lib/financial-2525/mot (${fn})`);
ok(/const axis = \[0, 0\.25, 0\.5, 0\.75, 1\]\.map\(\(f\) => fmtMot\(positionInYear\(from \+ f \* len, planet\.yearAnchor, planet\.yearDays\)\.abc\)\);/.test(ux) && /function respread\(/.test(ux) && !/\bmotABC\(/.test(ux) && !/MS_PER_DAY/.test(ux), "A.B..C IS the revolution (addenda 10–12): the reveal reads the year position at each axis mark on the planet's anchor and the elapsed span in A-units of the planet's whole — never a period as its own 0→3600, never an Earth constant typed on the surface");
ok(/positionInYear\(now, planet\.yearAnchor, planet\.yearDays\)/.test(ux) && !/frameOf\(/.test(ux) && /data-fin-past-full/.test(ux) && /data-fin-year-table/.test(ux), "r.028 (addendum 58): the year position is a TABLE; no 33-day frame; a year past day 365 carries its flag");
// r.008 (addendum 19) — every category carries its icon from ONE map; the year position takes the planet's revolution
const iconSrc = fs.readFileSync(path.join(process.cwd(), "components/financial-2525/category-icon.tsx"), "utf8");
const catList = /export const BUDGET_CATEGORIES[^=]*=\s*\[([^\]]+)\]/.exec(fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/budget.ts"), "utf8"));
const cats = catList ? [...catList[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]) : [];
ok(cats.length === 10 && cats.every((c) => new RegExp(`(^|\\n)\\s*"?${c.replace(/ /g, " ")}"?:\\s*[A-Z][A-Za-z]+,`).test(iconSrc)), `every one of the ${cats.length} categories has an icon in CATEGORY_ICON (a bare category fails here)`);
ok(/strokeWidth=\{1\.5\}/.test(iconSrc) && /aria-hidden/.test(iconSrc) && !/fill=/.test(iconSrc), "the icons are strokes (1.5), aria-hidden — the word beside them carries the meaning");
ok(/<SectionIcon section=\{section\} className="mr-1" \/>\{t\("fin\.section"\)\}/.test(ux) && /<FieldIcon field=\{l\.fieldId\} section=\{fieldOf\(l\.fieldId\)\?\.section \?\? "L"\} className="mr-1\.5" \/>\{shortLabel\(l\.fieldId\)\}/.test(ux) && /\{txWhat\(x\)\}/.test(ux) && /<FieldIcon field=\{tx\.field\} section=\{sec\} className="mr-1" \/>\{fieldLabel\(tx\.field\)\}/.test(ux) && /<CategoryIcon category=\{tx\.category\} className="mr-1" \/>\{catLabel\(tx\.category\)\}/.test(ux), "the icon sits before the section dropdown's label, on every budget line and in the record table's field cell (an r.006–r.011 entry keeps its category icon)");
ok(/positionInYear\(now, planet\.yearAnchor, planet\.yearDays\)/.test(ux) && /positionInYear\(from \+ f \* len, planet\.yearAnchor, planet\.yearDays\)/.test(ux), "every year position on the glass takes the selected planet's revolution (the r.007 Mars axis read Earth positions)");
// r.007 (addendum 18) — the perihelion instant that opens the year is written on the glass in Austin CST standard; the axis marks are three lines
ok(/\[t\("fin\.perihelion_abc"\), fmtMot\(\{ a: 0, b: 0, c: 0 \}\)\]/.test(ux) && ux.indexOf('t("fin.perihelion_abc")') < ux.indexOf('t("fin.now_abc")'), "r.038 (addendum 58 'perihelion is first' + addendum 72): on MoT the year table's first row is the perihelion, written as the A.B..C origin 0.0000..0000 — no date");
ok(/a\.replace\("\.", "\\n\."\)\.replace\("\.\.", "\\n\.\."\)/.test(ux), "an A.B..C axis mark is three lines — A / .B / ..C — so B and C never overprint a neighbour at phone width (the r.006 Mars capture)");
// r.005 — the Planet LTU table (Admin panel) drives every conversion; the planet selector; the MoT ⇄ Clock icon toggle is the card's one state
ok(/readPlanetLtu\(\)/.test(ux) && /PLANET_LTU_KEYS\.includes\(e\.key\)/.test(ux) && /planetRow\(planets, planetCode\)/.test(ux) && /daySecOf\(planet\) \* 1000/.test(ux), "every conversion reads the selected planet's row from the Admin panel's LTU table (seed on the server, the device copy after mount, other tabs via storage)");
ok(/useState<PlanetLtuRow\[\]>\(\(\) => \[\.\.\.PLANET_LTU_SEED\]\)/.test(ux) && /setPlanets\(readPlanetLtu\(\)\)/.test(ux), 'the first paint is the seed, the device copy arrives after mount (never a hydration mismatch)');
ok(/data-fin-planet/.test(ux) && /planets\.map\(\(p\) => <option key=\{p\.code\} value=\{p\.code\}>\{p\.name\}<\/option>\)/.test(ux), "a planet selector lists the table's rows (Earth default · Mars)");
ok(/import \{ Check, ChevronDown, ChevronRight, Clock, Maximize2, Orbit, Pencil, Plus, Settings, X \} from "lucide-react"/.test(ux) && /function ClockMotToggle\(/.test(ux) && /role="group" data-fin-abc-toggle=\{hook\}/.test(ux) && /aria-pressed=\{abc\} aria-label=\{t\("fin\.show_abc"\)\}/.test(ux) && /aria-pressed=\{!abc\} aria-label=\{t\("fin\.show_ltu"\)\}/.test(ux) && /data-fin-abc-toggle=\{hook\}[\s\S]{0,200}aria-label=\{t\("fin\.show_ltu"\)\}[\s\S]{0,400}aria-label=\{t\("fin\.show_abc"\)\}/.test(ux) && /<ClockMotToggle abc=\{showAbc\} onChange=\{onToggle\} t=\{t\} hook="chart" \/>/.test(ux), "the reveal is one shared Clock ⇄ MoT toggle — Clock on the LEFT, MoT on the RIGHT — used by the chart (r.025) and the year card (r.030)");
ok(/ring-1 ring-inset ring-primary/.test(ux) && !/bg-primary\/15/.test(ux), 'the pressed icon is ringed, never filled (the vector law)');
ok(/const \[yearAbc, setYearAbc\] = useState\(false\);/.test(ux) && /<ClockMotToggle abc=\{yearAbc\} onChange=\{setYearAbc\} t=\{t\} hook="year" \/>/.test(ux) && /const rows: \[string, string\]\[\] = yearAbc \? \[/.test(ux), "r.030 → r.038: the year card has its own Clock / MoT toggle, standard by default; MoT shows its own rows, Clock its own (never both)");
ok(/planet\.code !== "earth" && <p[^>]*>\{t\("fin\.anchor_note"\)\}<\/p>/.test(ux), 'on a planet without a perihelion table the year line says so (declared, not sourced)');
// r.006 — every transaction carries its personal-finance category (addendum 16); the budget is a table with a unit toggle (addendum 17)
ok(/<select data-fin-section=\{hook\}/.test(ux) && /\{FLOW_SECTIONS\.map\(\(sec\) => <option key=\{sec\} value=\{sec\}>\{secLabel\(sec\)\}<\/option>\)\}/.test(ux) && /<select data-fin-field=\{hook\}/.test(ux) && /\{fieldsOf\(section\)\.map\(\(f\) => <option key=\{f\.id\} value=\{f\.id\}>\{fieldLabel\(f\.id\)\}<\/option>\)\}/.test(ux) && /<select data-fin-length=\{hook\}/.test(ux) && /\{RECURRENCES\.filter\(\(r\) => r !== "days33" \|\| rec === "days33"\)\.map\(\(r\) => <option key=\{r\} value=\{r\}>\{t\(`fin\.rec\.\$\{r\}`\)\}<\/option>\)\}/.test(ux) && /rec === "other" && \(/.test(ux) && /<input data-fin-length-n=\{hook\}/.test(ux) && /<select data-fin-length-unit=\{hook\}/.test(ux) && /\{LENGTH_UNITS\.map\(\(u\) => <option key=\{u\} value=\{u\}>\{t\(`fin\.u\.\$\{u\}`\)\}<\/option>\)\}/.test(ux) && (ux.match(/<LadderPicker /g) || []).length === 1 && /<LadderPicker[^>]*hook="transaction"/.test(ux) && !/data-fin-category/.test(ux) && !/data-fin-timeline/.test(ux), "the one form carries the SECTION A–M, the FIELD within it, and the LENGTH — presets with Other opening a number in years · days · hours · minutes (addenda 22, 24, 25); one picker, hook transaction; no category or timeline dropdown remains");
ok(/kind: "deposit", amountCents: cents, atMs: instant, motDays: len\.days, memo: memo\.trim\(\) \|\| undefined, field, recurrence: rec \}\)\);/.test(ux) && /atMs: instant, motDays: len\.days, memo: memo\.trim\(\) \|\| undefined, field, recurrence: rec, \.\.\.\(paidFrom !== DEBIT/.test(ux) && /const days = lengthDays\(rec, n, otherUnit\);/.test(ux) && /if \(tx\.field\) \{ const sec = fieldOf\(tx\.field\)\?\.section/.test(ux) && /if \(tx\.category\) return <span>/.test(ux), "the field, the length (as motDays) and the timeline are recorded on the entry of either kind (inside its hash) and shown on the record; an r.006–r.011 entry still prints its category");
// r.013 (addendum 24) — ONE transaction form: the type is the first dropdown; the MoT length is never a typed field; one button whose word follows the type
ok(/data-testid="fin-transaction-form" data-fin-tx-type=\{txType \|\| "none"\}/.test(ux) && /<select data-fin-type className=\{PICK\} value=\{txType\} onChange=\{\(e\) => chooseType\(e\.target\.value as TxKind \| ""\)\}>/.test(ux) && /<option value="" disabled>\{t\("fin\.type_select"\)\}<\/option>/.test(ux) && /<option value="deposit">\{t\("fin\.type_deposit"\)\}<\/option>/.test(ux) && /<option value="withdrawal">\{t\("fin\.type_withdrawal"\)\}<\/option>/.test(ux) && !/fin-deposit-form/.test(ux) && !/fin-withdraw-form/.test(ux) && !/t\("fin\.mot_days"\)/.test(ux) && /data-fin-record disabled=\{!txType\}/.test(ux) && /\{retrying \? t\("fin\.save_retry"\) : txType === "withdrawal" \? t\("fin\.withdraw"\) : t\("fin\.record_it"\)\}/.test(ux) && /const recordTransaction = \(\) => \{ if \(txType === "deposit"\) recordDeposit\(\); else if \(txType === "withdrawal"\) recordWithdrawal\(\); \};/.test(ux) && /if \(k === "deposit"\) \{ setSec\("A"\); setField\("A\.income_wages"\); setRec\("paymot"\); \} else \{ setSec\("B"\); setField\("B\.rent_mortgage"\); setRec\("once"\); \}/.test(ux) && /useState\("" as TxKind \| ""\)/.test(ux), "ONE transaction form: the type is its first dropdown, BLANK until the person picks Deposit / Funds or Withdrawal / Expense (r.023, addendum 39 + 55); the record button waits until a type is picked; picking re-seats the picker's default; both record paths behind it");
ok(/<select data-fin-budget-unit value=\{budgetUnit\}/.test(ux) && !/role="group" data-fin-budget-unit/.test(ux) && /\{UNITS\.map\(\(u\) => <option key=\{u\.key\} value=\{u\.key\}>\{u\.label\}<\/option>\)\}/.test(ux) && /<table className="mt-2 w-full font-mono text-xs">/.test(ux) && /data-fin-kind=\{g\.kind\}/.test(ux) && /\{groups\.map\(\(g\) => \(/.test(ux) && !/data-fin-budget-row/.test(ux) && /data-fin-ladder-field=\{l\.fieldId\}/.test(ux) && /data-fin-budget-net/.test(ux) && /totals\.net < 0 \? "text-red-500"/.test(ux), "the budget is the ladder grouped by KIND — one row per kind with its total, the lines beneath when opened, Net last and red when negative — under ONE unit dropdown (addenda 20 + 22 → 31); no note under it (r.054)");
ok(/<label data-fin-mot-unit-row className="(?:ml-auto )?flex min-w-0 items-center justify-end gap-1\.5 whitespace-nowrap[^"]*">\{t\("fin\.mot_unit"\)\}/.test(ux) && /<span data-fin-unit-short aria-hidden[^\n]*\{UNIT_SHORT\[budgetUnit\] \?\? budgetUnit\} ▾<\/span>/.test(ux) && /<select data-fin-budget-unit value=\{budgetUnit\}[^\n]*className="absolute inset-0 h-full w-full cursor-pointer opacity-0"/.test(ux) && /<div className="flex flex-(?:no)?wrap items-center justify-between gap-2">\n\s*<div className="flex shrink-0 items-center gap-2">\n\s*<div className=\{LABEL\}>\{t\("fin\.ladder_title"\)\}/.test(ux), "r.065 (addendum 139, superseding addendum 21's full-width row): the budget unit sits on the header line, upper right, labelled MoT Unit");
ok(/\{ key: "min", label: t\("fin\.per_min"\), period: "minute" \}/.test(ux) && /\{ key: "day", label: t\("fin\.per_day"\), period: "day" \}/.test(ux) && /\{ key: "week", label: t\("fin\.per_week"\), period: "week" \}/.test(ux) && /\{ key: "month", label: t\("fin\.per_month"\), period: "month" \}, \{ key: "quarter", label: t\("fin\.per_quarter"\), period: "quarter" \}/.test(ux) && !/\(91\)`/.test(ux) && /\{ key: "year", label: t\("fin\.per_year"\), period: "year" \}/.test(ux) && /useState<BudgetUnit>\("month"\)/.test(ux), "every view is possible — $/s · $/min · $/h · day · week · 33 days · month (30.333 days) · quarter (91 days) · year — each a fixed PERIOD (FD-25, the month by addendum 34); per month (30.3 repeating days) by default (r.024, addendum 41)");
ok(/const totals = useMemo\(\(\) => netLadder\(budget, period\), \[budget, period\]\);/.test(ux) && /toPeriod\(l\.amountNative, l\.nativePeriod, period\)/.test(ux) && !/ltuDays\(planet\)/.test(ux) && !/\b(86400|1440|525600)\b/.test(ux), "the ladder's figures come from netLadder / toPeriod on the brief's fixed factors (FD-25) — never typed on the surface; the planet's LTU row still drives the clock ladder (daySecOf)");
ok(!/Supabase/.test(ux) && !/Supabase/.test(fs.readFileSync("lib/lexicon-data.ts", "utf8").match(/key: "fin\.device_only"[^\n]*/)[0]), "the record sentence names no vendor (the signer-voice law)");
ok(/append\(recordRef\.current, \{ \.\.\.tx, id: freshId\(recordRef\.current, tx\.id\) \}, at\)/.test(ux) && /loadRecord\(owner\)/.test(ux) && /const saved = saveRecord\(next\), shown = saved \?\? next;/.test(ux), 'the record is appended (to the latest record, under an id no entry holds — r.073), loaded and saved through lib/financial-2525/record');
ok(/import { type BudgetCategory } from "@\/lib\/financial-2525\/budget"/.test(ux) && /from "@\/lib\/financial-2525\/plan"/.test(ux) && /from "@\/lib\/financial-2525\/ladder"/.test(ux) && !/summarize\(/.test(ux), 'the ladder comes from lib/financial-2525/ladder over the plan of the person (lib/financial-2525/plan, the sheet bridged in budget.ts until they edit); the r.001 summarize is no longer on the glass');
ok(/useAuth0\(\)/.test(ux) && /loginWithRedirect\(\{ appState: \{ returnTo: /.test(ux) && /user\?\.sub/.test(ux), 'each user their own login: Auth0 gates recording, keys the record, and returns the person HERE after login');
ok(/\{owner \? \(/.test(ux) && /data-fin-forms/.test(ux), 'the deposit / withdrawal forms render only for a signed-in person');
// r.002 — the surface STARTS FROM the ◬ ♡ 웃 Session shell (operator addendum 7): its root, header, rail, guide, roster, clock, strip, Trinity
ok(/className="mx-auto max-w-3xl px-4 pb-20 pt-3 sm:pb-10"/.test(ux) && /<SoiGlobe \/>/.test(ux) && !/<TrinityGlyphs size="text-3xl"/.test(ux), 'r.042: the Session root, a smaller header, the globe; no ◬ ♡ 웃 row (the Trinity logo replaces it)');
ok(!/PodPhaseRail|FIN_PHASES|phaseOf|countFor/.test(ux) && !/PodRosterList/.test(ux), "r.038 (addendum 73 'get rid of this; adds no value'): no step rail on the surface; the \"Your deposits\" list stays gone (r.025)");
ok(!/data-testid="fin-your-turn"/.test(ux) && /font-mono text-2xl tabular-nums text-primary/.test(ux) && !/data-testid="fin-strip"/.test(ux) && /<SoITrinity /.test(ux), "r.028 (addendum 58 'remove gold top box'): no YOUR TURN card, no strip; the Accrual Units figure and the folded Trinity keep the Session's classes");
ok(/const CARD = "mt-8 rounded-xl border border-border bg-card p-5"/.test(ux) && !/VECTOR_LAW\.ground/.test(ux), 'the chrome is the app theme card (bg-card), not a fresh black console');
ok(/<SoITrinity labels=\{\[t\("fin\.wheel\.hi"\), t\("fin\.wheel\.si"\), t\("fin\.wheel\.ai"\)\]\}/.test(ux), 'the Trinity wheel seats the operator\'s way: TOP HI 웃 · BOTTOM-RIGHT SI ♡ minutes · BOTTOM-LEFT AI ◬ tokens (addendum 9; SoITrinity tuple = [top, bottom-right, bottom-left])');
ok(/const ticks = showAbc \? \[\] : dayTicks\(from, to, fit\);/.test(ux) && /rotate\(-\$\{angle\}deg\)/.test(ux) && !/<g data-fin-date-axis/.test(ux) && /\{dateLabel\(tk, dateFmt\)\}/.test(ux) && /\{showAbc && <div data-fin-axis/.test(ux), "the chart's Clock mode reads CALENDAR DATES at the chosen angle — as many whole days as fit at that angle; A.B..C is the reveal");
ok(/data-fin-signin/.test(ux) && /fin\.example_badge/.test(ux), 'an unsigned visitor sees the example badge and a sign-in');
ok(/const EXAMPLE: FinTx = \{[\s\S]*?SRC\.example\.amountUsd[\s\S]*?SRC\.example\.depositStamp[\s\S]*?SRC\.example\.motDays/.test(ux), 'the worked example is read from the domain source, never typed on the surface');
ok(/data-fin-chart/.test(ux) && /<svg viewBox/.test(ux) && /<polyline fill="none"/.test(ux) && !/fill="#/.test(ux), 'the chart is strokes on the black ground — no face is painted');
ok(/const \[dateFmt, setDateFmt\] = useState\("full" as DateFmt\);/.test(ux) && /localStorage\.getItem\("fin-date-fmt"\)/.test(ux) && /localStorage\.setItem\("fin-date-fmt", f\)/.test(ux) && /data-fin-date-gear aria-expanded=\{gear\} aria-label=\{t\("fin\.settings"\)\}/.test(ux) && /\{DATE_FMTS\.map\(\(f\) => \(/.test(ux) && /\{DATE_ANGLES\.map\(\(a\) => \(/.test(ux) && /localStorage\.setItem\("fin-date-angle", String\(a\)\)/.test(ux) && /new Intl\.DateTimeFormat\(locale \|\| "en", \{ month: "long"/.test(ux), "r.028 (addendum 58 'Settings should open up date format for table, and angle for chart text'): the chart's gear opens the date format AND the angle (0° · 30° · 45° · 90°), both remembered on this phone");
ok(/data-fin-chart-svg onClick=\{probeAt\} onPointerDown=\{onPDown\}/.test(ux) && !/touch-none/.test(ux) && /style=\{live \? \{ touchAction: "pan-y" \} : undefined\}/.test(ux) && !/touchAction: "none"/.test(ux) && /data-fin-chart-probe-line/.test(ux) && /<p data-fin-chart-probe className="mt-2 min-h-\[16px\] font-mono text-xs text-foreground">\{probe !== null && \(showAbc \? fmtMot\(positionInYear\(probe, planet\.yearAnchor, planet\.yearDays\)\.abc\) : `\$\{fmtStampCST\(probe\)\} CST`\)\}<\/p>/.test(ux) && /aria-label=\{t\("fin\.chart_tap"\)\}/.test(ux), "r.025 + r.038: a tap on the chart draws a line there and reads that point — its day and time on Clock, its A.B..C position on MoT; the page still scrolls over the chart");
ok(!/\{tx\.motDays\} ·/.test(ux) && !/\$\{x\.motDays\}/.test(ux) && /fmtDays\(withMonthLaw\(x\)\.motDays \?\? 0\)/.test(ux) && /\{fmtDays\(withMonthLaw\(EXAMPLE\)\.motDays \?\? 0\)\}/.test(ux), "every MoT-day count on the surface prints through fmtDays, after the month law (r.046) — never 30.333333333333332");
ok(/<button type="button" data-fin-trinity aria-expanded=\{trinityBig\} aria-label=\{t\("fin\.trinity_aria"\)\}/.test(ux) && /<SoITrinity labels=\{\["", "", ""\]\} color=\{hue\.bright\}[^\n]*size=\{63\} \/>/.test(ux) && /labels=\{\[t\("fin\.wheel\.hi"\), t\("fin\.wheel\.si"\), t\("fin\.wheel\.ai"\)\]\}[^\n]*size=\{190\} fontSize=\{16\} centerLabels \/>/.test(ux) && !/fin-details-trinity/.test(ux) && ux.indexOf("data-fin-trinity") < ux.indexOf("</header>"), "r.042 (addendum 78): the Trinity logo replaces ◬ ♡ 웃 in the header — 63 px (one-third of 190), no text, the selected colour; a tap grows it in place to 190 px with its labels; the wheel at the bottom is gone");
ok(/VECTOR_LAW\.stroke/.test(ux) && /TRINITY_COLORS/.test(ux), 'the chart stays under the vector law: stroke widths from VECTOR_LAW, colours from the 13');
ok(/data-fin-balance/.test(ux) && /data-fin-budget/.test(ux) && /data-fin-ledger/.test(ux) && /data-fin-year/.test(ux), 'balance, budget, record and year panels carry their hooks');
ok(/<RCoreBadge history=\{FINANCIAL_RCORE_HISTORY\} accent=/.test(ux) && /fromLedgerJson\(FINANCIAL_LEDGER\)/.test(ux), 'the R-CORE badge is mounted last from the Financial ledger');
const lastTag = ux.lastIndexOf('<RCoreBadge'); const rootClose = ux.lastIndexOf('</div>\n  );\n}', ux.indexOf('function MotChart'));
ok(lastTag > 0 && rootClose > lastTag, 'the badge is the last child of the root (bottom of the page)');
ok(/versionStamp\(/.test(ux), 'the U-WF-12 version stamp is printed');
ok(/fin\.chain_broken/.test(ux), 'the record says whether its chain held (where it lives: no line since r.054)');

// 3 — the launcher tile
const launcher = read('components/vision-2525-launcher.tsx');
ok(/code: "FINANCIAL-2525"/.test(launcher) && /router\.push\("\/financial-2525"\)/.test(launcher), 'the VISION • 2525 launcher carries the FINANCIAL tile → /financial-2525 (the canonical address, addendum 15; /main/Financial-2525 the alias)');

// 4 — the export emits both routes when out/ exists
for (const r of ['out/main/Financial-2525/index.html', 'out/financial-2525/index.html']) {
  if (!fs.existsSync('out')) { pass++; continue; }
  ok(fs.existsSync(r) && fs.statSync(r).size > 2000, `${r} is exported (> 2 KB)`);
}
ok(path.basename(process.cwd()) === 'frontend', 'runs from frontend/');

// r.014 — THE PICKER LAW (operator addendum 26 "this drop down goes away quick!"): a dropdown stays open until the person picks.
// A component declared inside the render body is a new type every render; the once-a-second clock remounts its <select> and the
// phone dismisses the picker sheet. Every picker is a module-level component with a stable identity.
ok(/^function LadderPicker\(\{ section, field, rec, onSection, onField, onRec, otherN, onOtherN, otherUnit, onOtherUnit, t, hook \}/m.test(ux), 'LadderPicker is declared at module level (column 0), its Other state and t passed as props');
ok(!/^\s+const [A-Z][A-Za-z]+ = \(/m.test(ux) && !/^\s+function [A-Z][A-Za-z]+\(/m.test(ux), 'no component is declared inside the render body (a nested component remounts its <select> on every clock tick — r.006 CategorySelect, r.012 LadderPicker)');
ok(/^const PICK = "w-full rounded-md/m.test(ux), 'the picker class string is module-level too');
ok(/<LadderPicker section=\{sec\} field=\{field\} rec=\{rec\} onSection=\{setSec\} onField=\{setField\} onRec=\{setRec\} otherN=\{otherN\} onOtherN=\{setOtherN\} otherUnit=\{otherUnit\} onOtherUnit=\{setOtherUnit\} t=\{t\} hook="transaction" \/>/.test(ux), 'the one form mounts the module-level picker with the Other state from the surface');
ok(/THE PICKER LAW \(r\.014/.test(ux), 'the law is written into the file beside the component');

// r.015 (addendum 27) — every section A–T has its OWN stroke; U (the amortize rule) has none by design
{
  const ladderSrc = fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/ladder.ts"), "utf8");
  const secIds = [...ladderSrc.matchAll(/\{ id: "([A-Z])", name: "[^"]+", plane: "[^"]+", key: "[a-z]" \}/g)].map((m) => m[1]);
  const map = /export const SECTION_ICON: Record<SectionId, LucideIcon> = \{([^}]+)\}/.exec(iconSrc);
  const entries = map ? [...map[1].matchAll(/\b([A-Z]): ([A-Z][A-Za-z]+),/g)].map((m) => [m[1], m[2]]) : [];
  const icons = Object.fromEntries(entries);
  ok(secIds.length === 20 && secIds.join("") === "ABCDEFGHIJKLMNOPQRST", `the ladder declares the twenty sections A–T (${secIds.join("")})`);
  ok(secIds.every((id) => icons[id]), `every section A–T has an icon in SECTION_ICON (missing: ${secIds.filter((id) => !icons[id]).join(" ") || "none"})`);
  ok(new Set(Object.values(icons)).size === entries.length && entries.length === 20, `the twenty section strokes are all distinct (${entries.length} entries, ${new Set(Object.values(icons)).size} strokes)`);
  ok(!icons.U && !/\bU: /.test(map ? map[1] : ""), "U is the amortize rule, never a section — it has no icon by design");
  ok(entries.every(([, name]) => new RegExp(`\\b${name}\\b`).test(iconSrc.split("\n").find((l) => l.startsWith("import {")) ?? "")), "every section stroke is imported from lucide (a name that is not imported would render nothing)");
  ok(/data-fin-tx-field=\{tx\.field\}><FieldIcon field=\{tx\.field\} section=\{sec\}/.test(ux) && /<tr key=\{l\.fieldId\} data-fin-ladder-field=\{l\.fieldId\}[^\n]*<FieldIcon field=\{l\.fieldId\} section=\{fieldOf\(l\.fieldId\)\?\.section \?\? "L"\}/.test(ux), "the record table and every budget line draw the section's stroke before its word (r.018: the letter never)");
}

// R-CORE toggle (operator 2026-09-30) — the page's last element must clear the phone strip: the maximized icon under the badge
// measured UNDER the fixed strip (elementFromPoint returned the strip's span) until the surface gained phone bottom padding.
ok(/<div data-financial-ux1 className="mx-auto max-w-3xl px-4 pb-20 pt-3 sm:pb-10">/.test(ux), "the surface pads its bottom on the phone (pb-20) so the R-CORE badge and its icon sit above the app's bottom bar");
// r.017 (addendum 29 "your deposit withdrawal floats; very odd") — NOTHING ON THE SURFACE FLOATS: the strip is the Released card's last row
ok(!/className="fixed /.test(ux) && !/className="sticky (?!right-0 bg-card)/.test(ux) && (ux.match(/className="sticky right-0 bg-card/g) || []).length === 3 && !/position: "fixed"/.test(ux), "no fixed or sticky element floats over the page (r.017, addendum 29); the one exception is the record's edit column, pinned right INSIDE the table's own sideways scroll (r.067, addendum 152) — it never covers the page");
{ const top = ux.slice(ux.indexOf("<div data-fin-accrual-top"), ux.indexOf("<dl data-fin-balance-grid")); const l1 = top.slice(0, top.indexOf("<div data-fin-figures-row ")); const l2 = top.slice(top.indexOf("<div data-fin-figures-row ")); ok((ux.match(/data-fin-tx-open/g) || []).length === 1 && /data-fin-tx-open[^\n]*className="h-8 shrink-0 rounded-md bg-primary/.test(l1) && l1.indexOf("data-fin-tx-open") < l1.indexOf("data-fin-accrual-gear"), "r.042 (addendum 81 'swap these two'): ONE + Transaction, on the Accrual Units top line immediately left of the gear, the gear's height (h-8)"); }


// r.016 (addendum 28) — EDIT MODE behind an icon on the budget: the plan drives the ladder; typed in the unit, stored on the base
ok(/import \{ loadPlan, savePlan, clearPlan, sheetPlan, planOrSheet, planKey, DEVICE_OWNER, setLineAmount, addLine, removeLine, lineInUnit \} from "@\/lib\/financial-2525\/plan"/.test(ux) && !/SHEET_LINES/.test(ux), "the surface reads the person's plan through lib/financial-2525/plan and never the sheet constant directly");
ok(/const totals = useMemo\(\(\) => netLadder\(budget, period\), \[budget, period\]\);/.test(ux) && /const groups = useMemo\(\(\) => groupByKind\(budget, period\), \[budget, period\]\);/.test(ux) && /isOpen\(g\.kind\) && g\.lines\.map\(\(l\) =>/.test(ux) && /const recIncome = owner \? recordIncomeLines\(txs, at\) : \[\];/.test(ux) && /recIncome\.length \? \[\.\.\.recIncome, \.\.\.plan\.filter\(\(l\) => fieldOf\(l\.fieldId\)\?\.kind !== "Income"\)\] : plan/.test(ux) && /editing && !fromRecord\(l\.fieldId\)/.test(ux), "every kind total, every line and Net follow the budget: Income from his record when he has deposits (r.048, addendum 80), the plan for the rest; record lines are not typed in edit mode");
ok(/<button type="button" data-fin-budget-edit aria-pressed=\{editing\} aria-label=\{editing \? t\("fin\.done"\) : t\("fin\.edit"\)\}/.test(ux) && /\{editing \? <Check size=\{14\} strokeWidth=\{1\.5\} aria-hidden \/> : <Pencil size=\{14\} strokeWidth=\{1\.5\} aria-hidden \/>\}/.test(ux) && /ring-1 ring-inset ring-primary" : "border-border"/.test(ux), "the pencil icon opens edit mode and the check closes it; the pressed state is a stroke ring, never a fill");
ok(/data-fin-plan-amount=\{l\.fieldId\}[^\n]*inputMode="decimal"/.test(ux) && /value=\{drafts\[l\.fieldId\] \?\? String\(editFigure\(l\)\)\}/.test(ux) && /const editFigure = \(l: LadderLine\) => \{ const v = toPeriod\(l\.amountNative, l\.nativePeriod, period\); return Math\.abs\(v\) < 100 \? Math\.round\(v \* 10000\) \/ 10000 : lineInUnit\(l, period\); \};/.test(ux) && /writePlan\(setLineAmount\(plan, fieldId, n, period\)\)/.test(ux), "in edit mode each line's amount is a field in the picked unit, held as a draft while typing and written on the 33-day base");
ok(/data-fin-plan-remove=\{l\.fieldId\}[^\n]*onClick=\{\(\) => writePlan\(removeLine\(plan, l\.fieldId\)\)\}/.test(ux), "a line can be removed");
ok(/data-fin-plan-add\b/.test(ux) && /<select data-fin-plan-section className=\{PICK\}/.test(ux) && /<select data-fin-plan-field className=\{PICK\}/.test(ux) && /data-fin-plan-add-btn[^\n]*writePlan\(addLine\(plan, id\)\)/.test(ux), "a line can be added — section, then a field not yet on the plan, full-width pickers (FD-24), inline (the picker law)");
ok(/data-fin-plan-reset onClick=\{\(\) => \{ clearPlan\(planOwner\); setPlan\(sheetPlan\(\)\);/.test(ux) && /if \(!savePlan\(planOwner, next\)\) setSaveFailed\(true\)/.test(ux) && /setPlan\(planOrSheet\(loadPlan\(planOwner\)\)\)/.test(ux) && /const planOwner = owner \?\? DEVICE_OWNER;/.test(ux), "the plan is saved under the person's key signed in, this phone's own signed out (r.052), and Reset returns to the sheet");
ok(/\{\(\s*<button type="button" data-fin-budget-edit/.test(ux) && !/\{owner && \(\s*<button type="button" data-fin-budget-edit/.test(ux), "r.052 (addendum 103 'wheres my edit button on personal budget'): the pencil is there signed in or not");

// r.018 (addendum 31 "order by fixed vs financial, and have expand button so this is not so busy. Don't show A-U letters")
ok(!/\{sec\} · /.test(ux) && !/A–M|A–U|A-M|A-U/.test(ux.replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*/g, "")), "no A–U letter reaches the glass: no '{sec} · ' prefix and no A–M / A–U in rendered text (comments excepted)");
ok(/<tr data-fin-kind=\{g\.kind\} data-fin-kind-open=\{isOpen\(g\.kind\) \? "1" : "0"\}/.test(ux) && /<button type="button" data-fin-kind-toggle=\{g\.kind\} aria-expanded=\{isOpen\(g\.kind\)\} aria-label=\{isOpen\(g\.kind\) \? t\("fin\.collapse"\) : t\("fin\.expand"\)\}/.test(ux) && /\{isOpen\(g\.kind\) \? <ChevronDown size=\{14\} strokeWidth=\{1\.5\} aria-hidden \/> : <ChevronRight size=\{14\} strokeWidth=\{1\.5\} aria-hidden \/>\}\{kindLabel\(g\.kind\)\}/.test(ux), "one row per kind with a chevron (aria-expanded, Show the lines / Hide the lines) and the kind's name");
ok(/const \[openKinds, setOpenKinds\] = useState\(\[\] as FieldKind\[\]\);/.test(ux) && /const isOpen = \(k: FieldKind\) => editing \|\| openKinds\.includes\(k\);/.test(ux), "the groups start collapsed; edit mode opens every group so its fields are reachable");
ok(/const kindLabel = \(k: FieldKind\) => \(k === "Transfer" \? t\("fin\.sec\.m"\) : t\(`fin\.\$\{k\.toLowerCase\(\)\}`\)\);/.test(ux), "the kinds read Income · Fixed · Variable (r.006's keys) and Transfers (the section's own name)");
ok(/<th className="py-1 pr-2">\{t\("fin\.category"\)\}<\/th>/.test(ux), "the table's first column is headed Category, not Section");

// r.019 (addendum 33 "make table 2x2") — the Released card's four figures as a 2 × 2 table, each word above its figure
{
  const order = ["escrowed", "released", "spent"];
  const cellOk = (c) => new RegExp('data-fin-cell="' + c + '"(?: className="text-(?:left|center|right)")?><dt[^>]*>\\{t\\("fin\\.' + c + '"\\)\\}</dt><dd[^>]*>\\{usd\\(bal\\.' + (c === "spent" ? "withdrawn" : c) + 'Cents\\)\\}</dd>').test(ux);
  const pos = order.map((c) => ux.indexOf('data-fin-cell="' + c + '"'));
  ok(/<dl data-fin-balance-grid className="mt-3 grid w-full grid-cols-3 gap-x-3"(?: style=\{\{ containerType: "inline-size" \}\})?>/.test(ux) && order.every(cellOk) && pos.every((x, i) => x > 0 && (i === 0 || x > pos[i - 1])) && !/data-fin-cell="available"/.test(ux) && !/data-fin-cell="withdrawable"/.test(ux), "r.029 (addendum 60): three boxes — In Escrow · Released · Spent — across the card; Available is the figure above, never repeated");
  ok(!/\{t\("fin\.escrowed"\)\}:<\/span>/.test(ux), "the run-on line of four figures is gone");
}

// r.021 (addendum 35 "on input of transaction or budget, must be able to specify time (MoT of transaction)") — every budget line its own MoT
ok(!/data-fin-plan-rec=/.test(ux) && !/data-fin-plan-n=/.test(ux) && !/data-fin-plan-unit=/.test(ux) && !/data-fin-plan-add-amount/.test(ux) && !/data-fin-plan-add-rec/.test(ux) && !/switchRec|isValidSpec|lineSpec|setLineSpec|BUDGET_RECURRENCES/.test(ux), "r.024 (addenda 48 · 50: \"don't change budget inplementetion; this is way too complicated and I never asked for it\"): no per-line MoT dropdown, no Other field, no add-row amount or MoT — the r.021–r.022 editor is gone");
ok(/<select data-fin-budget-unit value=\{budgetUnit\}/.test(ux) && (ux.match(/data-fin-budget-unit/g) || []).length === 1 && /writePlan\(setLineAmount\(plan, fieldId, n, period\)\)/.test(ux), "r.024 (his answer \"One, shared\"): ONE Unit dropdown — in edit mode the amounts are typed in the unit picked, out of edit mode it converts the view");
ok(/const \[rateUnit, setRateUnit\] = useState\("hr" as RateUnit\);/.test(ux) && /const RATE_UNITS: readonly RateUnit\[\] = \["sec", "min", "hr", "day"\];/.test(ux) && /<select data-fin-rate-unit aria-label=\{t\("fin\.rate_unit"\)\} value=\{rateUnit\}/.test(ux) && /\{RATE_UNITS\.map\(\(u\) => <option key=\{u\} value=\{u\}>\{t\(`fin\.rate\.\$\{u\}`\)\}<\/option>\)\}/.test(ux) && !/t\("fin\.per_hour"\)\} · \{usd/.test(ux) && /u === "hr" \? bal\.netRatePerMinCents \* planet\.minPerHour/.test(ux), "r.024 (addendum 46 + his answer): the Released card shows ONE rate figure with a /sec · /min · /hr · /day dropdown, per hour by default; the three-figure line is gone; the figure is the live $/min times the planet's units");
ok(/const \[formOpen, setFormOpen\] = useState\(false\);/.test(ux) && /\{formOpen && \(\s*<div id="fin-transaction-form"/.test(ux) && /data-fin-tx-open aria-expanded=\{formOpen\} onClick=\{openForm\}/.test(ux) && /data-fin-tx-close[^>]*onClick=\{foldForm\}/.test(ux), "r.023 (addendum 38): the transaction entry is folded behind + Transaction and opens only when pressed; an X folds it back");
ok(/const openForm = \(\) => \{ if \(formOpen\) \{ goTo\("fin-transaction-form"\); return; \} setTxType\(""\); setRefusal\(null\);/.test(ux) && !/action: openForm \}/.test(ux) && !/openForm\("(deposit|withdrawal)"\)/.test(ux) && !/t\("fin\.guide\.first_deposit"\)/.test(ux), "r.028: the one door opens the ONE form with the type blank; no door names a deposit or a withdrawal");
ok(/const afterRecord = \(saved: boolean\) => \{ if \(saved\) \{ setAmt\(""\); setMemo\(""\); setWhen\(""\); foldForm\(\); \} else setUnsaved\(formKey\); \};/.test(ux) && /afterRecord\(commit\(\{ id: `d-/.test(ux) && /setRefusal\(null\); afterRecord\(commit\(w\)\);/.test(ux) && /\{saveFailed && !retrying && <p role="alert" data-fin-save-failed className="mb-2 text-sm text-amber-500">\{cloudState === "saved" \? t\("fin\.save_failed_cloud"\) : t\("fin\.save_failed"\)\}<\/p>\}\s*\{formOpen && \(/.test(ux), "r.023 (his answer 'Folds back'): after a recorded deposit or withdrawal the entry folds back; a failed save is said OUTSIDE the fold — r.073: only when the phone KEPT it (a full phone keeps the form open, below)");
ok(/if \(!v\.ok\) return setRefusal\(`\$\{t\("fin\.reason_insufficient_by"\)\} \$\{fmtStampCST\(v\.atMs\)\}`\);/.test(ux) && !/reason === "HOLD"/.test(ux), "a refused withdrawal names the minute it would run short; there is no HOLD refusal (r.028, addendum 57)");
ok(/querySelector\("select\[data-fin-type\], input"\)/.test(ux), "r.023: a door lands on the form's TYPE dropdown — the first choice the person makes");
ok(/id: `d-\$\{instant\}-\$\{cents\}-\$\{recordRef\.current\.entries\.length \+ 1\}`/.test(ux) && /id: `w-\$\{instant\}-\$\{cents\}-\$\{recordRef\.current\.entries\.length \+ 1\}`/.test(ux) && /id: freshId\(recordRef\.current, tx\.id\)/.test(ux), "r.026: two entries with the same amount at the same typed day and time are two entries — the id carries the record's next number, so the second is never taken for the first and silently dropped");
ok(ux.indexOf("data-fin-date-months") > 0 && ux.indexOf("data-fin-date-months") < ux.indexOf("<div data-fin-date-axis data-fin-angle"), "r.026: the month name sits OVER the day numbers (his \"October / with / 01, 02, 03\")");
ok(/\{!showAbc && ticks\.length === 0 && <div data-fin-axis/.test(ux), "r.026: a MoT that crosses no midnight keeps the day · hour · minute marks instead of an empty axis");
ok(/className="min-h-\[36px\] rounded-md border border-border bg-background px-1 py-0\.5 text-xs text-primary"/.test(ux), "r.026: the rate dropdown is a 36 px touch target (mobile rule)");
{ const pg = fs.readFileSync(new URL("../app/SoI-2525/page.tsx", import.meta.url), "utf8");
  ok(/const numBox = \(key: string, shown: string, onNum: \(n: number\) => void\) => \(\{/.test(pg) && /\{\.\.\.numBox\(`\$\{r\.code\}:monthDays`/.test(pg) && /\{\.\.\.numBox\(`\$\{r\.code\}:yearDays`/.test(pg) && !/numOf\(/.test(pg) && /<span data-planet-month-repeat[^>]*>\{fmtDays\(r\.monthDays\)\}<\/span>/.test(pg), "r.026: the Admin panel's planet number boxes keep what is typed (\"30.\" stays) so 30.333 and 365.25 can be typed; the Month shows 30.3 repeating beside it"); }
ok(/\{txType && <LadderPicker section=\{sec\}/.test(ux), "r.027 (decision 5): Section, Field and Length appear only once a type is picked");
ok(!/data-fin-hold-line/.test(ux) && !/holdUntilMs/.test(ux) && !/t\("fin\.(hold_180|reason_hold_180|reason_hold|hold_mark|guide\.held|ph\.hold)"\)/.test(ux) && !/key: "hold"/.test(ux), "r.028 (addendum 57 'THERE IS NO 180 min hold'): no hold line, no hold refusal, no HOLD step on the rail");
ok(!/centerGlyphs/.test(ux), "r.027 (decision 10): the wheel's centre symbols are gone — each symbol shows once, on its ring");
ok(/<select data-fin-length=\{hook\}/.test(ux) && /RECURRENCES\.filter\(/.test(ux), "the transaction form keeps its own MoT (Length) for every type; the 33-day preset is not offered (r.028)");

// ── r.028 (addenda 57 · 58, the morning feedback) ──────────────────────────────────────────────
ok(!/fin\.version|SRC\.project\.revision\}<\/p>/.test(ux.slice(ux.indexOf("<header"), ux.indexOf("</header>"))) && /<p data-fin-subtitle className="text-sm">/.test(ux) && /<span data-fin-subtitle-mot className="text-primary">\{t\("fin\.title_mot"\)\}<\/span><span className="text-muted-foreground">: \{t\("fin\.title_std"\)\}<\/span>/.test(ux) && !/fin\.title_l2/.test(ux) && /"fin\.title_l1", englishDefault: "Measure of Time: A Universal Standard"/.test(fs.readFileSync("lib/lexicon-data.ts", "utf8")), "r.039 (addendum 74): the header is ONE line, 'Measure of Time: A Universal Standard', and carries no version; r.043 (addendum 90): 'Measure of Time' in the eXeL colour, 'A Universal Standard' in the AI colour");
{ const rec = ux.slice(ux.indexOf("<table data-fin-ledger-table"), ux.indexOf("</table>", ux.indexOf("<table data-fin-ledger-table")));
  const bud = ux.slice(ux.indexOf("<thead", ux.indexOf("data-fin-budget")), ux.indexOf("</table>", ux.indexOf("data-fin-budget")));
  ok(!/usd\(|usd4\(|usdDollars\(/.test(rec) && !/usd\(|usd4\(|usdDollars\(/.test(bud) && (rec.match(/<td data-fin-amount/g) || []).length === 2 && /<span className="flex justify-between gap-4"><span>\{x\.kind === "deposit" \? "\+" : "−"\}<\/span><span>\{num2\(x\.amountCents\)\}<\/span><\/span>/.test(rec) && /\{unitHead\(UNITS\.find\(\(u\) => u\.key === budgetUnit\)\?\.label \?\? "", curMark\)\}<\/th>/.test(bud) && /\},\\u00a0\$\{cur\}`;/.test(ux), "r.043 (addenda 86, 88, 89): no currency symbol inside a table cell — the Record's amount has the sign at the far left and the bare number right-justified; the budget header carries ', <currency mark>' (r.049)"); }
ok(!/t\("fin\.chart_title"\)/.test(ux), "r.028: 'Money as time — this MoT' is gone from every place on the surface");
{ const top = ux.slice(ux.indexOf("<div data-fin-accrual-top"), ux.indexOf("<dl data-fin-balance-grid")); const l1 = top.slice(0, top.indexOf("<div data-fin-figures-row ")); const l2 = top.slice(top.indexOf("<div data-fin-figures-row ")); ok(l1.indexOf("fin.accrual_units") < l1.indexOf("data-fin-tx-open") && !/data-fin-rate/.test(l1) && l2.indexOf("data-fin-current") < l2.indexOf("data-fin-rate-block") && !/fin\.withdraw_open|data-fin-withdraw/.test(top), "r.042 (addendum 81): line 1 = ACCRUAL UNITS · + Transaction · gear; line 2 = Available (left) · Accrual Rate (right); no Withdraw pill"); }
ok(/data-fin-balance className="-mx-2 [^"]*sm:mx-0"/.test(ux), "r.028: the Accrual Units card runs the full width on a phone in portrait");
ok(/data-fin-chart-controls className="mt-2 flex items-center justify-between gap-2">\s*\{selector\}/.test(ux), "r.028: Planet on the left, the Clock · MoT toggle and the gear on the right");
ok(/<details data-fin-ledger/.test(ux) && /data-fin-ledger-scroll className="mt-2 overflow-x-auto"/.test(ux) && /data-fin-ledger-table className="min-w-full whitespace-nowrap/.test(ux), "r.028: the Record folds behind a chevron; opened, a table with one entry per line that scrolls sideways");
ok(!/t\("fin\.frame"\)|t\("fin\.per_33"\)|\/33</.test(ux) && !/key: "m33"/.test(ux), "r.028 (addendum 58 'remove all 33 day reference'): no 33-day frame, unit or label on the glass");

ok(/data-fin-accrual-defs/.test(ux) && /\(\["available", "escrowed", "released", "spent"\] as const\)\.map/.test(ux) && /t\(`fin\.def\.\$\{k\}`\)/.test(ux), "r.029 (addendum 60 'what each does … in settings'): the Accrual Units gear explains Available, In Escrow, Released and Spent");

ok(/\{ key: "calmonth", label: t\("fin\.per_cal_month"\), period: "calmonth" \},[^\n]*\n\s*\{ key: "month"/.test(ux) && /setCalendarMonth\(now\)/.test(ux) && /"fin\.per_cal_month", englishDefault: "Standard Month"/.test(fs.readFileSync("lib/lexicon-data.ts", "utf8")), "r.031 + r.039 (addenda 62, 74): the standard calendar month sits right before the 30.3̅-day month and reads 'Standard Month' — no extra text; it still converts by the real month's length");

{ const th = (ux.match(/data-fin-ledger-table[\s\S]*?<\/thead>/) || [""])[0]; const order = ["fin.amount_col", "fin.category", "fin.memo", "fin.when", "fin.length", "fin.type"].map((k) => th.indexOf(`t("${k}")`)); const hashAt = th.indexOf('t("fin.hash")');
  ok(order.every((x, i) => x > 0 && (i === 0 || x > order[i - 1])) && hashAt > order[5] && /\{x\.kind === "deposit" \? "\+" : "−"\}<\/span><span>\{num2\(x\.amountCents\)\}/.test(ux), "r.032 (addendum 63): the Record leads with the signed Amount, then Category; then Memo · Day and time · Length · Type; # and Hash last"); }

{ const card = ux.slice(ux.indexOf("data-fin-balance className"), ux.indexOf("{/* the chart"));
  ok(/const \[accrualGear, setAccrualGear\] = useState\(false\);/.test(ux) && /\{accrualGear && \(\s*<dl data-fin-accrual-defs/.test(card) && /\{accrualGear && focusView && \(\s*<ul data-fin-accrual-menu/.test(card) && !/elapsed/.test(card.replace(/\{accrualGear[\s\S]*$/, "")) && (card.match(/fin\.def\./g) || []).length === 1, "addendum 66: the four definitions and the elapsed / per-minute lines show ONLY when the Accrual Units gear is open; closed on load"); }

ok(!/cyan/.test(ux), "r.034 (addendum 67 'we stick to color per selector'): no fixed cyan anywhere on the surface — every accent is the theme's primary");
{ const head = ux.slice(ux.indexOf("<header"), ux.indexOf("</header>"));
  ok(/<a href="\/main\/" data-fin-home aria-label=\{t\("fin\.home"\)\}[\s\S]*?<ExelWordmark /.test(head) && head.indexOf("data-fin-home") < head.indexOf("<SoiGlobe") && head.indexOf("<SoiGlobe") < head.indexOf("data-fin-settings") && /onClick=\{\(\) => setSettingsOpen\(true\)\}/.test(head) && /<ModeratorSettings open=\{settingsOpen\} onClose=\{\(\) => setSettingsOpen\(false\)\}/.test(ux), "r.034 (addendum 67): eXeL AI upper left links to /main; the globe, then the Settings gear, upper right (r.042, addendum 76)"); }

ok(!/p\.withdrawable\)/.test(ux) && !/C\.consciousness/.test(ux) && !/t\("fin\.withdrawable"\)/.test(ux), "r.034: no separate Withdrawable stroke or cyan legend word — with no hold it is the Released line; the tap line takes the theme colour");

{ const top = ux.slice(ux.indexOf("<div data-fin-accrual-top"), ux.indexOf("<dl data-fin-balance-grid")); const l1 = top.slice(0, top.indexOf("<div data-fin-figures-row ")); const l2 = top.slice(top.indexOf("<div data-fin-figures-row ")); ok(/<div data-fin-rate-block className="ml-auto flex shrink-0 flex-col items-end">\s*<span data-fin-rate-label[^>]*>\{t\("fin\.accrual_rate"\)\}<\/span>\s*<div data-fin-rate-row/.test(l2), "r.035 + r.042: the words 'Accrual Rate' sit directly above the rate and its selector — now on the Available row, right-aligned"); }
{ const cur = ux.slice(ux.indexOf("<div data-fin-current"), ux.indexOf("{bal.ratePerMinCents > 0 &&")); const rb = ux.slice(ux.indexOf("<div data-fin-rate-block"), ux.indexOf("<select data-fin-rate-unit")); ok(/text-xs text-muted-foreground/.test(cur) && /data-fin-rate-label className="text-xs text-muted-foreground"/.test(rb) && /flex h-9 items-center font-mono text-2xl/.test(cur) && /data-fin-rate-row className="flex h-9 items-center/.test(rb) && /data-fin-rate className="font-mono text-2xl/.test(rb), "r.044 (addendum 93): 'Available:' and 'Accrual Rate' on one line at the same size; the two figures on the next line, both text-2xl in equal-height rows"); }

ok(/data-fin-cell="escrowed" className="text-left"/.test(ux) && /data-fin-cell="released" className="text-center"/.test(ux) && /data-fin-cell="spent" className="text-right"/.test(ux), "r.036 (addendum 69): the three boxes spread evenly across the card — left edge · centre · right edge");

// ── r.038 (addenda 72 + 73): no rail; Accrual · Budget · Chart · Record · Year; the year card folded; one system at a time ──
{
  const at = (re) => { const m = ux.match(re); return m ? m.index : -1; };
  const iBal = at(/<div data-fin-balance /), iBud = at(/<div data-fin-budget /), iChart = at(/<MotChart tx=\{focus\}/), iLed = at(/<details data-fin-ledger /), iYear = at(/<details data-fin-year /), iSign = at(/<div data-fin-forms>/);
  ok(iBal > 0 && iBal < iBud && iBud < iChart && iChart < iLed && iLed < iYear && iYear < iSign, "r.038 → r.042: the cards read Accrual Units · Personal budget · Chart · Record · Year position · sign-in, in that order (the Trinity moved to the header)");
  ok(/<details data-fin-year className=\{`group \$\{SUB\}`\}/.test(ux) && !/<details data-fin-year[^>]*\bopen\b/.test(ux) && /<span className=\{LABEL\}>\{t\("fin\.year_title"\)\}<\/span>/.test(ux), "r.038 (his answer 'defaulted just title'): the year card is folded to its title; opening it shows the toggle and the rows");
  const mot = ux.slice(ux.indexOf("const rows: [string, string][] = yearAbc ? ["), ux.indexOf("] : [", ux.indexOf("const rows: [string, string][] = yearAbc ? [")));
  ok(mot.length > 50 && !/fmtStampCST|fmtDays|CST|\/ 91|year\.day\b/.test(mot) && /abcPart\(year\.abc, 900\)/.test(ux) && /abcPart\(year\.abc, 300\)/.test(ux) && /\/ 900`/.test(mot) && /\/ 300`/.test(mot) && /\/ 3600`/.test(mot), "r.038 (addendum 72 + 'Equal parts of 3600'): the MoT rows are A.B..C only — no date, no day count, no 91 / 30.3̅ — quarter of 900 A, month of 300 A, now out of 3600");
  ok(!/data-fin-chart-line/.test(ux) && /data-fin-chart-span/.test(ux), "r.047 (addendum 95 'remove this from charting'): the chart's top line is gone in both modes; the span toggle stands in its place");
  ok(/const parts = \[showAbc \? `\$\{fmtMot\(spanABC\(/.test(ux) && /: `\$\{hhmmss\(Math\.max\(0, at - focus!\.atMs\)\)\} \$\{t\("fin\.elapsed"\)\}`,/.test(ux) && /`· \$\{usd4\(bal\.netRatePerMinCents\)\} \$\{t\("fin\.rate\.min"\)\}`, `· \$\{usd4\(bal\.netRatePerMinCents \/ planet\.secPerMin\)\} \$\{t\("fin\.rate\.sec"\)\}`\];/.test(ux) && /<li data-fin-elapsed-line className="flex flex-wrap gap-x-1" style=\{\{ fontSize: fitLine\(parts\.join\(""\)\.length\) \}\}>\{parts\.map\(\(p, i\) => <span key=\{i\} className="whitespace-nowrap">\{p\}<\/span>\)\}<\/li>/.test(ux), "r.038 ('Yes, everywhere'): the Accrual gear's elapsed line is h:m:s on Clock, A.B..C on MoT — never both; r.043 (addendum 84): elapsed · $/min · $/sec on ONE line, fitted to the card (r.071 AsM)");
}

// ── r.040 (addendum 75): one line per budget entry — a short name, "…" if still long, the full name on hold ──
{
  const lexs = fs.readFileSync("lib/lexicon-data.ts", "utf8");
  const flow = [...lexs.matchAll(/key: "fin\.field\.([a-m]_[a-z0-9_]+)"/g)].map((m) => m[1]);
  const short = new Map([...lexs.matchAll(/key: "fin\.fshort\.([a-z0-9_]+)", englishDefault: "([^"]+)"/g)].map((m) => [m[1], m[2]]));
  ok(flow.length === 46 && flow.every((k) => short.has(k)) && [...short.values()].every((v) => v.length <= 16), `every budget line (A–M, ${flow.length}) has a short name of 16 characters or fewer`);
  ok(short.get("g_mental_physical") === "Fitness & Health", "his example: 'Mental Health / Physical Fitness' reads 'Fitness & Health' (addendum 85)");
  ok(/<td data-fin-line-name className="max-w-0 truncate whitespace-nowrap[^"]*" title=\{fieldLabel\(l\.fieldId\)\}>[^\n]*\{shortLabel\(l\.fieldId\)\}<\/td>/.test(ux), "the budget row shows the short name on one line, ends in … if it overflows, and carries the full name as its title");
}

// ── r.041 (addenda 76–77): the record reads TRANSACTION RECORD; the chart reads REAL-TIME FINANCIALS ──
ok(/<span className=\{LABEL\}>\{t\("fin\.tx_record"\)\}/.test(ux) && !/t\("fin\.ledger_title"\)/.test(ux) && /"fin\.tx_record", englishDefault: "Transaction Record"/.test(fs.readFileSync("lib/lexicon-data.ts", "utf8")), "r.041 (his third ask): the record header reads TRANSACTION RECORD — no 'The record · Chain verified · 3'");
ok(/<div className=\{LABEL\}>\{t\("fin\.realtime"\)\}<\/div>/.test(ux) && /"fin\.realtime", englishDefault: "Real-Time Financials"/.test(fs.readFileSync("lib/lexicon-data.ts", "utf8")), "r.041: the chart header reads REAL-TIME FINANCIALS");

ok(/<td data-fin-budget-net-label className="py-1 pr-2 text-\[11px\] min-\[360px\]:whitespace-nowrap">[^<]*\{totals\.net < 0 \? t\("fin\.net_down"\) : t\("fin\.net_up"\)\}<\/td>/.test(ux) && /"fin\.net_up", englishDefault: "Net • Upside \/ Savings"/.test(fs.readFileSync("lib/lexicon-data.ts", "utf8")) && /"fin\.net_down", englishDefault: "Net • Downside \/ Risk"/.test(fs.readFileSync("lib/lexicon-data.ts", "utf8")), "r.045 (addendum 94): green Net reads 'Net • Upside / Savings', red Net reads 'Net • Downside / Risk'");
ok(/\.map\(withMonthLaw\)/.test(ux) && /fmtDays\(withMonthLaw\(x\)\.motDays \?\? 0\)/.test(ux) && /const monthDays = 30;/.test(ux) && /const qDown = !year\.down && year\.dayInQuarter === 91;/.test(ux) && /\$\{month\} · \$\{dayInMonth\} \/ \$\{monthDays\}/.test(ux) && !/91 \/ 3/.test(ux), "r.046 month law: the balance, the chart and the Record read old Monthly entries as 30 days; the year card counts three 30-day months and day 91 of a quarter as its down day; no 91 ÷ 3 remains on the surface");
{ const sp = ux.slice(ux.indexOf("type ChartSpan"), ux.indexOf("function MotChart"));
  ok(/const CHART_SPANS: readonly ChartSpan\[\] = \["1x", "1W", "1M", "30D", "91D", "Y"\];/.test(ux) && /if \(sp === "1x"\) return 0;/.test(sp) && /if \(sp === "1M"\) return calendarMonthDays\(nowMs\);/.test(sp) && /if \(sp === "30D"\) return 30;/.test(sp) && /if \(sp === "91D"\) return 91;/.test(sp) && /% 400 === 0 \? 366 : 365/.test(sp) && /const all = respread\(txs\.length \? txs : \[tx\], span, now, showAbc, planet\.yearDays\);/.test(ux) && /const pts = rate \? \[\] : series\(all, from, to, len \/ 120\);/.test(ux) && /data-fin-span=\{sp\} aria-pressed=\{span === sp \|\|/.test(ux) && /localStorage\.setItem\(SPAN_KEY, v\)/.test(ux), "r.047 (addenda 95–98): the span toggle 1x (instant) · 1W · 1M (the Standard Month) · 30D · 91D · the year (366 in a leap year) re-spreads every transaction over the span; remembered on this phone"); }
{ const C = fs.readFileSync("lib/financial-2525/currency.ts", "utf8"); const mw = fs.readFileSync("lib/min-wage.ts", "utf8"); const countries = [...(mw.match(/COUNTRY_RATES: Record<string, number> = \{([\s\S]*?)\};/) || ["", ""])[1].matchAll(/([A-Z][A-Za-z ]+):/g)].map((m) => m[1].trim());
  ok(countries.length >= 9 && countries.every((c) => new RegExp(`\\b${c}: \\{ code: "[A-Z]{3}"`).test(C)) && /"United States": \{ code: "USD"/.test(C) && !/rate|convert|fx/i.test(C.replace(/COUNTRY_RATES/g, "").replace(/never a conversion/g, "")) && /<select data-fin-currency/.test(ux) && /CUR_SYM = cur\.symbol \?\? "";/.test(ux) && /\{!cur\.symbol && <div data-fin-currency-label className="text-\[11px\] text-muted-foreground">/.test(ux) && /\{t\("fin\.amount_col"\)\}, \{curMark\}/.test(ux), "r.049 (addenda 86–87): every minimum-wage country has a currency row; the picker sits in the Accrual gear; the symbol replaces $ (a label, never a conversion); no symbol → a gray code under ACCRUAL UNITS; the headers carry the mark"); }
{ const ms = fs.readFileSync("components/moderator-settings.tsx", "utf8"); const nm = ms.slice(ms.indexOf('data-settings-variant="nonMaster"'), ms.indexOf(") : (", ms.indexOf('data-settings-variant="nonMaster"')));
  ok((nm.match(/data-settings-item="/g) || []).length === 3 && /data-settings-item="language-colour"[\s\S]*SettingsLanguageSelector[\s\S]*ThemeCustomizer/.test(nm) && /data-settings-item="atlantis"><AtlantisAccordViewer \/>/.test(nm) && /data-settings-item="vision-2525"/.test(nm) && !/CostEstimateTable|AiProviderSelector|LanguageLexicon|CubeArchitectureStatus/.test(nm) && /variant="nonMaster"/.test(ux), "r.050 (addendum 76 + 'Exactly 3 items'): Financial-2525 mounts the non-Master settings — language and colour · Atlantis Accords · Vision • 2525, nothing else; eXeL AI Polling keeps Master"); }
ok(!/height="auto"/.test(ux) && !/TrinityGlyphs inline/.test(ux) && /raw === null \|\| raw === "" \? NaN : Number\(raw\)/.test(ux) && ux.indexOf("data-fin-chart-probe className") < ux.indexOf("<svg viewBox={`0 0 ${W} ${H}`}") && !/Balance view/.test(fs.readFileSync("lib/lexicon-data.ts", "utf8").match(/"fin\.stock_note"[^\n]*/)[0]), "r.051 (r.041 review + backlog B-05..B-07): no invalid svg height, no ◬ ♡ 웃 in the footer, an unset date angle keeps the 30° default, the tap readout sits above the chart, the budget note names no Balance view; the open logo's labels at 20 (≈12 px)");
// ── r.052 (addendum 101 + his answers, addendum 102): $ on the left y axis · Net at the budget's $/min to the span's end · 1x live, pinch widens ──
ok(/<div data-fin-y-axis aria-hidden/.test(ux) && /yTicks\.map\(\(v\) => <span key=\{v\}[^\n]*\{yLabel\(v\)\}<\/span>/.test(ux) && /const PL = Math\.max\(Y_AXIS_W,/.test(ux) && /CUR_SYM \+ Math\.round\(Math\.abs\(c\) \/ 100\)/.test(ux), "r.052 (addendum 101 'i need $ on left y axis'): a $ scale on the left in the picked currency, and the plot starts right of it");
ok(/const totalsPerSec = useMemo\(\(\) => netLadder\(budget, "second"\), \[budget\]\)/.test(ux) && /<MotChart tx=\{focus\} netPerSec=\{totalsPerSec\.net\}/.test(ux) && /const netFrom = Math\.max\(from, to - spanMs\)/.test(ux) && /<polyline data-fin-net-line[^\n]*strokeDasharray="5 3"/.test(ux) && !/data-fin-net-end/.test(ux), "r.052 (his answers 'Budget table' · 'Net + Released + Escrow'): Net runs at the budget table's $/s over the span's last stretch, dashed; r.056 (addendum 127 'remove this line'): the legend line '- - Net • Upside / Savings +… · date' is gone");
ok(/const yMin = Math\.min\(0, netEnd\), yMax = Math\.max\(total, netEnd\)/.test(ux) && /\{yMin < 0 && <line data-fin-zero/.test(ux), "r.052: the y axis spans negative to positive when Net goes below zero, with a zero line");
ok(/const from = live \? now - LIVE_WINDOWS\[zoom\]\.h \* 3600 \* 1000/.test(ux) && /const to = live \? now :/.test(ux) && !/data-fin-zoom="wide"/.test(ux) && !/data-fin-zoom="narrow"/.test(ux) && !/data-fin-live-zoom/.test(ux) && /if \(d > pc\.d0 \* 1\.25\) \{ widen\(1\)/.test(ux) && /\{ h: 1, label: "1 h" \}/.test(ux), "r.052 → r.065 (addendum 138 'get rid of +- map guidance'): 1x is a live window ending now, 1 h at first; two fingers widen or narrow it — the + / − row is gone");
// ── r.053 (addenda 106 · 110): his entries put back; a stock-chart readout at the tapped point ──
ok(/\{owner && cloudReady && isOperator\(user\?\.email\) && record\.entries\.length === 0 && \(/.test(ux) && /data-fin-restore-btn onClick=\{restoreMine\}/.test(ux) && /for \(const d of operatorDeposits\(\)\) next = append\(next, d, at\);/.test(ux) && /setAmt\(OPERATOR_WITHDRAWAL\.amount\)/.test(ux), "r.053 (addendum 110 'now enter my transactions back in'): signed in as him with an empty record, one tap appends his two deposits and opens the withdrawal form at 250.66 — append only");
ok(/const probeBal = probe === null \|\| rate \? null : balanceAt\(all, probe\)/.test(ux) && /data-fin-chart-values[^\n]*t\("fin\.released"\)[^\n]*t\("fin\.escrowed"\)[^\n]*t\("fin\.available"\)[^\n]*t\("fin\.net"\)/.test(ux), "r.053 (addendum 110 'Like a stock chart I should be able to click and see values at that day/time'): a tap shows Released · In Escrow · Available · Net at that point");
// ── r.054 (addendum 115 + his answer "Current implementation looks good accept unneeded text"): the two machine-language lines are gone ──
ok(!/t\("fin\.stock_note"\)/.test(ux) && !/t\("fin\.device_only"\)/.test(ux), "r.054: no 'balances, not per-minute flows' note under the budget and no 'On this phone only — a cloud copy follows' line under the record");
// ── r.055 (addendum 112 "make sure push is made automatically as well as every 12 hours"; addendum 119 the purpose line) ──
ok(/const \{ r, p, c \} = await readAll\(key\);/.test(ux) && /const m = mergeRecords\(recordRef\.current, r\.data\);/.test(ux) && /const kept = m\.keep \? await cloudPut\(key, `fin-record-kept-\$\{Date\.now\(\)\}`, m\.keep\) : "saved";/.test(ux), "r.055: on sign-in the account copy is read back and merged — r.073: UNITED with this device's (every entry of both); only a copy that fails its chain is kept whole");
ok(/\}, \[record, plan, cards, cloudReady\]\);/.test(ux) && /cloudPut\(key, "fin-record", recordRef\.current\)/.test(ux) && /cloudPut\(key, "fin-plan",/.test(ux), "r.055: every change to the record or the budget is pushed to the account — r.073: read first, the latest record sent");
ok(/setInterval\(\(\) => \{ void syncRef\.current\(\); \}, PUSH_EVERY_MS\)/.test(ux) && /visibilitychange/.test(ux), "r.055: pushed every 12 hours, and on return to the page when 12 hours have passed");
ok(/<p data-fin-budget-purpose[^\n]*\{t\("fin\.budget_purpose"\)\}/.test(ux) && /data-fin-cloud=\{cloudState\}/.test(ux), "r.055: the purpose line under the budget; a cloud icon beside the record");
// ── r.056 (addenda 122 · 123 · 124 · 127: "$/min is main view" · numbers upper right · the R-CORE charting engine · "where is $/min chart?!?")
ok(/import \{ RCoreChart \} from "@\/components\/2525-core\/rcore-chart"/.test(ux) && /<RCoreChart /.test(ux), "r.056: the $/min view draws on the shared R-CORE chart engine");
ok(/useState<ChartUnit>\("min"\)/.test(ux) && /const CHART_UNITS: readonly ChartUnit\[\] = \["min", "sec", "hr", "day", "usd"\]/.test(ux) && /data-fin-chart-unit/.test(ux), "r.056: the chart opens on $/min (unit dropdown $/min · /sec · /hr · /day · $), remembered on the phone");
ok(/\{rate && <RateView /.test(ux) && /\{!rate && <>/.test(ux), "r.056: $/min shows the rate view; $ keeps the balance view of r.025–r.053 unchanged");
ok(!/data-fin-rate-hud/.test(ux) && /readout=\{figuresAt\}/.test(ux) && /const figuresAt = \(ms: number\) => \{[^\n]*color: C\.abundance, text: rateMoney[^\n]*color: C\.evolution, text: rateMoney[^\n]*color: C\.temporal, text: rateMoney/.test(ux) && !/const figuresAt[^\n]*fin\.income/.test(ux) && !/data-fin-rate-net-by/.test(ux), "r.057 (addendum 129 'numbers only in same color as line … just figures near vertical line on selected date'): figures only, line-coloured, beside the selected date line — no box, no words; r.064 (addendum 137) the Net-by figure is removed");
ok(/angle=\{angle\} tall=/.test(ux) && /ticksFor=\{ticksFor\} formatTick=\{tick\}/.test(ux) && /initialRange=\{\{ from, to \}\}/.test(ux) && /const dataFrom = Math\.min\(from, firstAt\) - spanMs, dataTo = Math\.max\(to, lastAt \+ spanMs\) \+ spanMs/.test(ux), "r.057–r.059 (addenda 129 · 130): the dates tilt at the Settings angle; the lines run over a wide range and the chart OPENS on the split window — pinch shows more dates (30D is the split, not the x range)");
ok(/id: "income"[^\n]*id: "spending"[^\n]*id: "net"/.test(ux), "r.056: three lines — income, spending, net — per minute");

const rc = fs.readFileSync(path.join(process.cwd(), "components/2525-core/rcore-chart.tsx"), "utf8");
ok(/getContext\("2d"\)/.test(rc) && /g\.rotate\(-a\)/.test(rc) && /kind: "pinch"/.test(rc) && /addEventListener\("wheel", onWheel, \{ passive: false \}\)/.test(rc) && !/data-rcore-date-axis/.test(rc), "r.059 → r.064 (addenda 130 · 135): the dates (tilted) and the figures are drawn on the chart's own canvas — they follow pinch, wheel and drag every frame; no HTML axis left");
ok(/data-fin-chart-unit-row className="mt-2 flex justify-end"/.test(ux) && ux.indexOf("data-fin-chart-unit-row") > ux.indexOf("{rate && <RateView") && ux.indexOf("data-fin-chart-unit-row") > ux.indexOf("{!rate && <>"), "r.060 (addendum 131): the Unit dropdown sits at the chart card's bottom right, after both views");
ok(/const strip = axisPx\(p\.angle, p\.tall\), plotH = H - strip;/.test(rc) && /const a = \(p\.angle \* Math\.PI\) \/ 180, base = plotH \+ 6;/.test(rc), "r.061 → r.064: the tilted dates live in their own strip under the plot (axisPx), so the value scale never runs into them");
ok(/\.\.\.\(typed\("amt"\) && cents !== cur\.amountCents \? \{ amountCents: cents \} : \{\}\),/.test(ux) && /\.\.\.\(typed\("when"\) && instant !== cur\.atMs \? \{ atMs: instant \} : \{\}\),/.test(ux) && /const next = correctTx\(recordRef\.current, cur\.id, edit, at\);/.test(ux) && /Math\.min\(cur\.atMs, edit\.atMs \?\? cur\.atMs\)/.test(ux) && /data-fin-edit=\{e\.rev\}/.test(ux) && /data-fin-edit-save/.test(ux) && /record\.entries\.filter\(\(e\) => !e\.tx\.corrects\)/.test(ux) && /\{ const v = validateRecord\(accrualTxs\(replay\(next\)\.map\(withMonthLaw\)\), Math\.min\(cur\.atMs, edit\.atMs \?\? cur\.atMs\)\);/.test(ux), "r.062 (addendum 133): a pencil on every record row edits amount, memo, day and time, length — saved as an appended correction (the original stays); every edit — a deposit's too (r.071 AsM) — passes the same refusal over the corrected record as the card counts it; corrections are not rows of their own");
ok(/if \(gs\?\.kind === "pan" && !gs\.moved && e\.type === "pointerup"\) \{ const at = msAt\(e\.clientX\); if \(at !== null\) \{ pinned\.current = at;/.test(rc) && /const sel = cross\.current \?\? pinned\.current \?\? p\.readoutAt \?\? null/.test(rc) && /p\.formatSelected\(sel\)/.test(rc) && /formatSelected=\{\(ms\) =>/.test(ux), "r.063 → r.064 (addendum 134 'click on map to see a specific day'): a tap (no drag) pins the day — its figures beside the line and its date boxed on the strip — until the next tap");
// ── r.064 (addendum 135 "i said dont use light wight trding view chart · wheres my expand for financial chart"; his answer "Full screen")
const pkg = JSON.parse(fs.readFileSync(path.join(process.cwd(), "package.json"), "utf8"));
ok(!/lightweight-charts|tradingview|TradingView/i.test(rc) && !(pkg.dependencies ?? {})["lightweight-charts"] && !(pkg.devDependencies ?? {})["lightweight-charts"] && !/data-rcore-chart-credit/.test(rc), "r.064: no TradingView — the chart is our own canvas engine; the dependency and its credit line are gone");
ok(/data-fin-chart-expand aria-pressed=\{full\}/.test(ux) && /full \? "fixed inset-0 z-\[60\] overflow-y-auto bg-background p-3" : SUB/.test(ux) && /if \(e\.key === "Escape"\) setFull\(false\)/.test(ux) && /height=\{full \? Math\.max\(300, vh - 260\) : 300\}/.test(ux) && /t\("fin\.chart_close"\)/.test(ux) && /t\("fin\.chart_expand"\)/.test(ux), "r.064: an expand button at the top right of REAL-TIME FINANCIALS opens the card full screen (the chart grows to the screen); the same button, now ✕, or Escape, brings it back");
// ── r.065 (addenda 136 · 138 · 139)
ok(/const ORBIT_SPANS: readonly ChartSpan\[\] = \["1x", "1W", "1M", "91D", "Y"\];/.test(ux) && /const ORBIT_A: Record<ChartSpan, number> = \{ "1x": 0, "1W": 75, "1M": 300, "30D": 300, "91D": 900, Y: 3600 \};/.test(ux) && /\(showAbc \? ORBIT_SPANS : CHART_SPANS\)\.map/.test(ux) && /\{showAbc \? orbitLabel\(sp\) : spanLabel\(sp, now\)\}/.test(ux) && /orbital \? \(ORBIT_A\[sp\] \/ 3600\) \* yearDays/.test(ux), "r.065 (addendum 138): the orbital view's spans are A.B..C only — 1X · 75 · 300 · 900 · 3600 A of the revolution, no days or calendar words");
ok(/const marks = txs\.map\(\(w\) => \(w\.kind === "withdrawal" \? \{[^\n]*value: w\.amountCents \} : \{ t: w\.atMs, color: C\.abundance, dot: false \}\)\);/.test(ux) && /formatMarkSum=\{/.test(ux) && /g\.setLineDash\(\[1, 3\]\)/.test(rc) && /export function layoutMarks\(/.test(rc) && /2: \["left", "right"\], 3: \["tl", "bc", "tr"\], 4: \["tl", "bl", "br", "tr"\]/.test(rc) && /Math\.hypot\(d\.x - last\.x, d\.y - last\.y\) < 2 \* r/.test(rc), "r.065 (addendum 136): a very thin dotted line at every deposit and spend; close spend labels sit left/right (2), top-left/bottom-centre/top-right (3), the four corners (4); only dots that actually overlap merge into one summed label");
ok(/<td data-fin-edit-cell className="sticky right-0 bg-card py-1 pl-2"><button type="button" data-fin-edit=\{e\.rev\}/.test(ux) && ux.indexOf("data-fin-edit-cell") > ux.indexOf("{e.hash.slice(0, 8)}") && /<CloudMark saved=\{cloudState === "saved"\} \/>/.test(ux) && /M8\.6 14\.4l2\.3 2\.3 4\.6-4\.6/.test(ux), "r.065 → r.067 (addenda 140 · 152 'edit button … somewhere on right'): the edit pencil is pinned to the right edge of every record row, in view while the table scrolls; the cloud mark is the standard cloud-with-check (saved) / cloud-with-slash (not yet)");
{ const ci = fs.readFileSync(path.join(process.cwd(), "components/financial-2525/category-icon.tsx"), "utf8"); ok(/export const FIELD_ICON: Record<string, LucideIcon> = \{ "F\.dining_work": UtensilsCrossed \};/.test(ci) && /<FieldIcon field=\{l\.fieldId\}/.test(ux) && /<FieldIcon field=\{tx\.field\}/.test(ux), "r.065 (addendum 141): Dining wears the fork and knife, never the groceries basket — on the budget and the record"); }
ok(/const rateIn = \(u: RateUnit\): number => \(u === "sec" \? bal\.netRatePerMinCents/.test(ux) && /r\.066: the labels are drawn OUTSIDE the plot's clip and kept on the canvas/.test(rc) && /const shift = Math\.max\(2 - left, Math\.min\(0, W - 2 - \(left \+ w\)\)\);/.test(rc), "r.066 (addenda 142 · 143): the Accrual Rate shows what is left after a spend ahead of accrual is spread over the rest; a spend label at the chart's edge is kept whole on the canvas (r.065 cut it)");
// ── r.067 (addenda 142–145, 147): the cockpit
{ const cd = fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/cards.ts"), "utf8"); ok(/\{owner && <CardsPanel cards=\{cards\} txs=\{recTxs\} now=\{at\} onSave=\{saveCards\} onPay=\{payCard\} t=\{t\} \/>\}/.test(ux) && ux.indexOf("<CardsPanel") > ux.indexOf("data-fin-ledger className") && /data-fin-card-toggle/.test(ux) && /\[\["limit", "fin\.card_limit"\]/.test(ux) && /data-fin-card-balance/.test(ux) && /data-fin-card-available/.test(ux) && /<RCoreChart height=\{200\} ariaLabel=\{spoken\}/.test(ux) && !/CARD_SEED|seedFor|73527/.test(cd) && !/seedFor|cardSeed/.test(ux), "r.067 (addenda 143 · 144) as of r.070 (addendum 157): a read view of the person's own cards below the record — toggle between them, balance · available, the balance chart; no card is seeded for anyone"); }
ok(/data-fin-card-warning=\{lv\}/.test(ux) && ux.indexOf("data-fin-card-warning") > ux.indexOf("data-fin-accrual-top") && /⚠ \{t\(ALERT_WORD\[lv\]\)\} · \{c\.name\}/.test(ux), "r.067 (addendum 144 'warnings of credit card overspend'): a card at the person's amber or red level is named at the top of the cockpit, in words as well as colour");
ok(/<select data-fin-paid-from/.test(ux) && /<option value=\{DEBIT\}>\{t\("fin\.debit_account"\)\}<\/option>/.test(ux) && /<select data-fin-pays-card/.test(ux) && /txType === "withdrawal" && paidFrom === DEBIT && !!cards\.length && \(/.test(ux), "r.067 (addendum 143): a withdrawal says what paid it — Debit Account or a card; a Debt-service payment from the Debit Account names the card it pays down");
ok(/tail=\{unitPicker\}/.test(ux) && /\{tail && <span className="ml-auto">\{tail\}<\/span>\}/.test(ux) && /<label data-fin-chart-unit-label className="inline-flex items-center gap-1\.5 text-xs text-muted-foreground">\{rate && t\("fin\.mot"\)\}/.test(ux), "r.067 (addendum 145): MoT beside $/hr, on the same line as Income · Spending · Net, at its right");
ok(/const UNIT_SHORT: Record<string, string> = \{ sec: "\/sec", min: "\/min", hour: "\/hr", day: "\/1D", week: "\/7D", calmonth: "\/1M", month: "\/30D", quarter: "\/91D", year: "\/1Y" \};/.test(ux), "r.067 (addendum 147): the closed MoT Unit box reads shorthand /30D · /7D · /1M …; the open list keeps the words");
ok(/const c2 = applyCardSettings\(card, \{ name: draft\.name, limitCents: cents\(draft\.limit\), amberCents: cents\(draft\.amber\), redCents: cents\(draft\.red\), openingCents: cents\(draft\.opening\) \}, bal, now\);/.test(ux) && /\.\.\.\(edit\.openingCents === balanceNowCents \? \{\} : \{ openingCents: edit\.openingCents, openingAtMs: nowMs \}\)/.test(fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/cards.ts"), "utf8")) && /\.\.\.\(paidFrom === DEBIT && paysCard \? \{ paysCard \} : \{\}\)/.test(ux) && /data-fin-edit-paid-from/.test(ux) && /"paidFrom" \| "paysCard">>/.test(fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/record.ts"), "utf8")) && /marks=\{cardMoves\(card, txs\)/.test(ux) && /let cardsAt = 0;/.test(ux) && /out\.includes\("offline"\)/.test(ux) && /else if \(!cc \|\| cardsAt > cc\.at\)/.test(ux), "r.067 AsM review fixes: a new balance-as-of-today re-bases at now; a hidden Card-paid choice is never recorded; the payer is editable; card marks match the balance; the cloud copy never overwrites a newer edit with the seed");
ok(/const top = plotH - 7 - h;/.test(rc), "r.067 (addendum 149): the boxed day label sits above the x axis with a 7 px gap — it never covers the date marks");
// r.069 (addendum 154): the card shows Balance and Available credit, side by side; the Limit is set in the gear (its first field), never on the face
ok(/<div data-fin-card-figures className="mt-3 grid grid-cols-2 gap-2 text-xs">\s*<div><div className="text-muted-foreground">\{t\("fin\.card_balance"\)\}<\/div><div data-fin-card-balance [^\n]*\n\s*<div className="text-right"><div className="text-muted-foreground">\{t\("fin\.card_available"\)\}/.test(ux) && !/data-fin-card-limit/.test(ux) && /\(\[\["limit", "fin\.card_limit"\], \["opening", "fin\.card_opening"\]/.test(ux), "r.069 (addendum 154): Balance and Available credit on the card's face; the Limit only in its settings");
// r.070 (addendum 155 "put key for Alerts · Show Red - - - Red Alert · Show Amber - - - Amber Alert · move as much unneeded text from Credit
// cards"): a key under the card chart with the chart's own dashes and colours, red first; the level line is gone; the chart says nothing at rest
// (the Balance above says it) and still shows the value and its date on a tap; the alert words are his; the state is spoken, not only coloured
{ const lx = fs.readFileSync(path.join(process.cwd(), "lib/lexicon-data.ts"), "utf8"); const rc2 = fs.readFileSync(path.join(process.cwd(), "components/2525-core/rcore-chart.tsx"), "utf8");
  const en = (k) => (lx.match(new RegExp(`key: "${k.replace(/\./g, "\\.")}", englishDefault: "([^"]*)"`)) || [])[1];
  ok(/<div data-fin-card-alerts aria-hidden="true" className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground">\s*<span className="font-medium">\{t\("fin\.card_alerts"\)\}<\/span>\s*\{\(\[\["red", C\.evolution, "fin\.card_level_red"\], \["amber", C\.temporal, "fin\.card_level_amber"\]\] as const\)/.test(ux)
    && /strokeDasharray="5 4"/.test(ux) && /dashed: true/.test(ux) && ux.indexOf("data-fin-card-alerts") > ux.indexOf('<RCoreChart height={200} ariaLabel={t("fin.cards_title")}')
    && !/data-fin-card-level/.test(ux) && !/const pct = /.test(ux)
    && /initialRange=\{\{ from, to \}\} quietAtRest readoutAt=\{now\}/.test(ux) && !/ms === now/.test(ux) && /const quiet = p\.quietAtRest && cross\.current === null && pinned\.current === null;/.test(rc2) && /if \(!quiet\) p\.readout\(sel\)/.test(rc2) && /if \(sel !== null && p\.formatSelected && !quiet\) \{/.test(rc2)
    && /\{lv !== "ok" && <span className="sr-only"> · \{t\(ALERT_WORD\[lv\]\)\}<\/span>\}/.test(ux)
    && en("fin.card_alerts") === "Alerts" && en("fin.card_level_red") === "Red Alert" && en("fin.card_level_amber") === "Amber Alert" && en("fin.card_available") === "Available" && !/"fin\.card_level_ok"/.test(lx),
    "r.070 (addendum 155): an Alerts key — red dashes Red Alert, amber dashes Amber Alert — under the card chart; no level line; no figures on the chart at rest; his alert words everywhere; the state spoken to a screen reader"); }
// r.070 (addendum 156 "have CC default minimized"): the Credit cards panel is a closed <details> like the Record and the Year card — chevron +
// title in the summary, no button inside it; Pay card and the settings on the first row once opened; the cockpit warning stays outside it
ok(/<details data-fin-cards className=\{`group \$\{SUB\}`\}>\s*<summary className="flex min-h-\[36px\] cursor-pointer list-none items-center gap-1" aria-label=\{t\("fin\.cards_title"\)\}>\s*<ChevronRight size=\{14\} strokeWidth=\{1\.5\} aria-hidden className="transition-transform group-open:rotate-90" \/>\s*<span className=\{LABEL\}>\{t\("fin\.cards_title"\)\}<\/span>\s*<\/summary>\s*<div className="mt-2 flex items-center justify-end gap-2">\s*\{card \? \(<>\s*<button type="button" data-fin-card-pay/.test(ux)
  && !/<details data-fin-cards[^>]*\bopen\b/.test(ux) && /<\/details>\s*\);\s*\}\s*$/.test(ux.slice(ux.indexOf("function CardsPanel"), ux.indexOf("\nfunction CardChart")).replace(/\n\/\*\*[^\n]*\*\/\s*$/, ""))
  && ux.indexOf("data-fin-card-warning") < ux.indexOf("<CardsPanel"),
  "r.070 (addendum 156): Credit cards starts minimized — a closed details with a chevron and the title; Pay card and settings inside; the alert stays at the top");
// r.070 (addendum 157 "allow user to set up their own CC (don't default Capital One and USAA)"): no card is seeded; the panel shows for every
// signed-in person — an empty list offers Add card, a list ends in a "+"; the add form takes a name, the limit, the balance as of now and
// the two alert levels (blank = half / two-thirds of the limit); settings rename a card and remove it in two taps; a number-like name is refused
{ const cd = fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/cards.ts"), "utf8");
  ok(!/CARD_SEED|seedFor|OPENING_AT/.test(cd) && /export function mergeCards\(saved: unknown, seed: readonly Card\[\] = \[\]\): Card\[\]/.test(cd) && /export function newCard\(/.test(cd) && /amberCents: Math\.round\(input\.amberCents \?\? limitCents \* 0\.5\), redCents: Math\.round\(input\.redCents \?\? \(limitCents \* 2\) \/ 3\)/.test(cd) && /const ANY_DIGIT = new RegExp\("\\\\p\{Nd\}", "gu"\);/.test(cd) && /export const looksLikeCardNumber = \(name: string\): boolean => \(name\.match\(ANY_DIGIT\)\?\.length \?\? 0\) > 6;/.test(cd) && /!looksLikeCardNumber\(c\.name\)/.test(cd)
    && /\{owner && <CardsPanel /.test(ux) && /setCards\(mergeCards\(JSON\.parse\(localStorage\.getItem\(CARDS_KEY\(owner\)\) \?\? "null"\)\)\); \} catch \{ setCards\(\[\]\); \}/.test(ux) && /const m2 = mergeCards\(cc\.cards as Card\[\]\);/.test(ux)
    && /\) : \(\s*<button type="button" data-fin-card-add aria-expanded=\{adding\} onClick=\{openAdd\}/.test(ux) && /<button type="button" data-fin-card-add aria-expanded=\{adding\} aria-label=\{t\("fin\.card_add"\)\} title=\{t\("fin\.card_add"\)\} onClick=\{openAdd\}/.test(ux)
    && /<div data-fin-card-add-form /.test(ux) && /data-fin-card-new="name"/.test(ux) && /placeholder=\{k === "amber" \? hint\(0\.5\) : k === "red" \? hint\(2 \/ 3\) : undefined\}/.test(ux) && /data-fin-card-input="name"/.test(ux)
    && /data-fin-card-remove onClick=\{\(\) => setRemoving\(true\)\}/.test(ux) && /data-fin-card-remove-yes onClick=\{remove\}/.test(ux) && /if \(!draft\.name\.trim\(\) \|\| looksLikeCardNumber\(draft\.name\)\) \{ setBad\("name"\); return; \}/.test(ux)
    && /\{payerGone && <option value=\{ed\.paidFrom\}>—<\/option>\}/.test(ux) && /, now, uniqueCardId\(cards, now\)\);/.test(ux) && /export function uniqueCardId\(cards: readonly Card\[\], nowMs: number\): string \{/.test(cd),
    "r.070 (addendum 157): each person sets up their own cards — no seed; Add card / +; name · limit · balance · amber · red (half / two-thirds by default); rename and remove in settings; a card number is refused as a name"); }
// r.070 AsM folds (three reviewers, twelve lenses, FIX-FIRST): (1) the class of the clock reset — the card chart's window moves once a day and
// the shared chart keeps a tap and a zoom when its window only slides or grows; (2) the settings save never counts a move twice; (3) a tapped
// figure takes its own moment's colour; (4) the key is for the eye, the chart speaks the balance and both levels; (5) his alert words in
// the settings; (6) red-400 for the card's alert text (contrast); and the gate gaps the reviewers' planted defects slipped through
{ const rc3 = fs.readFileSync(path.join(process.cwd(), "components/2525-core/rcore-chart.tsx"), "utf8"); const lx3 = fs.readFileSync(path.join(process.cwd(), "lib/lexicon-data.ts"), "utf8");
  ok(/const from = card\.openingAtMs - D, to = Math\.floor\(Math\.max\(now, card\.openingAtMs\) \/ D\) \* D \+ 8 \* D;/.test(ux)
    && /const drift = !!prev && \(Math\.abs\(\(nt - nf\) - \(prev\.to - prev\.from\)\) < 1 \|\| \(nf === prev\.from && nt >= prev\.to\)\);/.test(rc3) && /if \(drift && view\.current && \(userView\.current \|\| pinned\.current !== null\)\) \{/.test(rc3) && (rc3.match(/userView\.current = true/g) || []).length === 3
    && /const tone = \(cents: number\) => \{ const l = cardLevel\(card, cents\);/.test(ux) && /readout=\{\(ms\) => \[\{ color: tone\(Math\.round\(at\(ms\)\)\), text: usd\(Math\.round\(at\(ms\)\)\) \}\]\}/.test(ux)
    && /const spoken = `\$\{t\("fin\.cards_title"\)\} · \$\{card\.name\} · \$\{t\("fin\.card_balance"\)\} \$\{usd\(Math\.round\(at\(now\)\)\)\} · \$\{t\("fin\.card_level_amber"\)\} \$\{usd\(card\.amberCents\)\} · \$\{t\("fin\.card_level_red"\)\} \$\{usd\(card\.redCents\)\}`;/.test(ux)
    && /key: "fin\.card_amber_at", englishDefault: "Amber Alert at"/.test(lx3) && /key: "fin\.card_red_at", englishDefault: "Red Alert at"/.test(lx3)
    && /red: "text-red-400", over: "text-red-400" \}\[lv\]/.test(ux) && /"border-red-500\/60 text-red-400"/.test(ux)
    && /const ALERT_WORD: Record<CardLevel, string> = \{ ok: "", amber: "fin\.card_level_amber", red: "fin\.card_level_red", over: "fin\.card_level_over" \};/.test(ux)
    && /g\.setLineDash\(l\.dashed \? \[5, 4\] : \[\]\)/.test(rc3) && /strokeDasharray="5 4"/.test(ux)
    && /\.filter\(\(\{ c, b \}\) => cardLevel\(c, b\) !== "ok"\)/.test(ux)
    && ux.indexOf('{ id: "amber", color: C.temporal') < ux.indexOf('{ id: "red", color: C.evolution'),
    "r.070 AsM folds: a tap survives the clock (both charts), the settings save never double-counts, a tapped figure has its own moment's colour, the key is for the eye and the chart speaks, his alert words in the settings, contrast, and the gate gaps closed"); }
// r.071 (addendum 158 "and fix this", his photo: −$2,309.48 beside $2.0900 /hr): the two figures keep one line and one size (r.044) but the
// size is fitted to the row (a CSS size container; monospace width = characters × advance), between 0.875rem and the r.044 1.5rem; past the
// floor the rate wraps under — the Available block never shrinks under its own text, so the two never overlap
{ const fit = fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/fit.ts"), "utf8");
  ok(/<div data-fin-figures-row className="mt-2 flex flex-wrap items-start justify-between gap-x-3 gap-y-1" style=\{\{ containerType: "inline-size" \}\}>\s*<div data-fin-current className="shrink-0">/.test(ux)
    && /data-fin-current[\s\S]{0,400}style=\{figFont\} data-testid="fin-clock"/.test(ux) && /<span data-fin-rate className="font-mono text-2xl tabular-nums" style=\{figFont\}>\{rateText\}<\/span>/.test(ux)
    && /const figFont = \{ fontSize: bal\.ratePerMinCents > 0 \? fitFigures\(usd\(bal\.availableCents\)\.length \+ rateText\.length, figReserve\(RATE_UNITS\.map\(\(u\) => t\(`fin\.rate\.\$\{u\}`\)\)\)\) : fitFigures\(usd\(bal\.availableCents\)\.length, 8\) \};/.test(ux)
    && /return `min\(1\.5rem, max\(0\.875rem, calc\(\(100cqw - \$\{Math\.max\(0, Math\.round\(reservePx\)\)\}px\) \/ \$\{em\}\)\)\)`;/.test(fit) && /export const FIG_ADVANCE_EM = 0\.62;/.test(fit),
    "r.071 (addendum 158): Available and the Accrual Rate share one fitted size and never overlap (wrap as the last resort)"); }
// r.071 (addendum 160 "Trinity text does not render anymore when clicked"): r.051 recorded the opened logo's labels at 16 but shipped 20
// — taller than the ring's 18-unit coloured band — so the dark labels vanished where they left it. Every label now fits its band:
// 16 units, centred across the band (the top ring's glyphs stand outward, the bottom rings' inward). Proven on the glyph envelope.
{ const tri = fs.readFileSync(path.join(process.cwd(), "components/soi-trinity.tsx"), "utf8");
  const mid = Number((tri.match(/export const LABEL_MID_EM = ([\d.]+);/) || [])[1]), fit = Number((tri.match(/export const LABEL_FIT = ([\d.]+);/) || [])[1]);
  const band = 21 - 2 * 1.5, size = Math.min(16, band * fit), base = size * mid;           // the default ring geometry, the Financial font
  const lo = -0.12 * size - base, hi = 0.92 * size - base;                                  // the glyph envelope around the band's centre line
  ok(/textColor=\{hue\.ink\} size=\{190\} fontSize=\{16\} centerLabels \/>/.test(ux)
    && /const fs = centerLabels \? Math\.min\(fontSize, \(ringWidth - borderWidth \* 2\) \* LABEL_FIT\) : fontSize;/.test(tri)
    && /const textRadii = centerLabels \? \[ringMidR - mid, ringMidR \+ mid, ringMidR \+ mid\]/.test(tri) && /fill=\{textColor\} fontSize=\{fs\}/.test(tri)
    && /centerLabels = false,/.test(tri) && lo > -band / 2 && hi < band / 2 && fit <= 0.9,
    `r.071 (addendum 160): the opened Trinity's labels fit their bands — glyphs ${lo.toFixed(1)}…${hi.toFixed(1)} inside ±${band / 2}`); }
// r.071 AsM review (Krishna · Athena): a new withdrawal is checked over the record EXACTLY as the card counts it (accrualTxs of the record with
// the entry), so a covered card payment is never refused for money it never takes; the $ view alone pays for the balance series
ok(/const v = validateRecord\(accrualTxs\(\[\.\.\.recTxs, withMonthLaw\(w\)\]\), instant\);/.test(ux) && !/validateWithdrawal\(/.test(ux),
  "r.071 AsM: every withdrawal and every edit is checked over the record as the card counts it — no check reads a different record");
// r.071 AsM (Sofia · Thoth · Thor): the gear line never leaves the card (fitted like the figures; it was cut off at 390 px and scrolled the
// page at 320); the Available figure is read as its amount (a generic element named "Available" hid the number from screen readers);
// the record is built once per record, not once per second; a length the calendar cannot hold is refused, never saved as one-time
{ const fit = fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/fit.ts"), "utf8");
  ok(/<ul data-fin-accrual-menu [^>]*style=\{\{ containerType: "inline-size" \}\}>/.test(ux) && /return `min\(0\.75rem, max\(0\.5625rem, calc\(\(100cqw - 8px\) \/ \$\{em\}\)\)\)`;/.test(fit)
    && !/data-testid="fin-clock" aria-label/.test(ux)
    && /const recTxs: FinTx\[\] = useMemo\(\(\) => \(owner \? replay\(record\) : \[EXAMPLE\]\)\.map\(withMonthLaw\), \[owner, record\]\);/.test(ux) && /const txs: FinTx\[\] = useMemo\(\(\) => accrualTxs\(recTxs\), \[recTxs\]\);/.test(ux)
    && /return lengthFits\(instant, days\) \? \{ days \} : \{ why: t\("fin\.reason_length"\) \};/.test(ux) && (ux.match(/const len = lengthOf\(instant\); if \("why" in len\) return setRefusal\(len\.why\);/g) || []).length === 2
    && /if \(!lengthFits\(instant, days\)\) return edRefuse\(t\("fin\.reason_length"\)\);/.test(ux),
    "r.071 AsM: the gear line fits the card, the Available figure reads as its amount, the record is built once per record, impossible lengths are refused"); }
// r.072 (addendum 161 "remove linit from CC", with his r.067 photo): FD-90's RULE, not one line — inside the Credit cards panel and its
// chart, a card's limit is read ONLY by the settings (the gear's draft, the add form's newCard, applyCardSettings) and by Available
// (limit − balance); the cockpit warning names the balance alone (r.072 AsM, Odin: four planted limit displays passed the first gate)
{ const warn = ux.slice(ux.indexOf("data-fin-card-warning={lv}"), ux.indexOf("</p>;", ux.indexOf("data-fin-card-warning={lv}")));
  const panel = ux.slice(ux.indexOf("function CardsPanel("), ux.indexOf("function MotChart("));
  const reads = panel.split("\n").filter((l) => /limitCents/.test(l));
  const allowed = (l) => /setDraft\(\{ name: card\.name, limit: \(card\.limitCents \/ 100\)\.toFixed\(2\)/.test(l) || /newCard\(\{ name: draft\.name, limitCents: cents\(draft\.limit\)/.test(l)
    || /applyCardSettings\(card, \{ name: draft\.name, limitCents: cents\(draft\.limit\)/.test(l) || /\{usd\(card\.limitCents - bal\)\}/.test(l);
  ok(/⚠ \{t\(ALERT_WORD\[lv\]\)\} · \{c\.name\} \{usd\(b\)\}$/.test(warn.trim()) && !/limitCents/.test(warn) && reads.length >= 4 && reads.every(allowed),
    `r.072 (addendum 161): the limit is read only by the settings and by Available — ${reads.filter((l) => !allowed(l)).length} other read(s)`); }
// r.072 AsM (Enlil · Krishna · Christo · Enki): nothing on the budget or the cards pushes a phone sideways — below 360 px the Net label
// wraps and the edit box is narrower; from 360 px the unit header holds one line, and its "$" never stands alone; the title row wraps;
// a long card name wraps inside the warning and a name is 40 characters at most; a level crossed is announced
ok(/<th className="py-1 text-right min-\[360px\]:whitespace-nowrap">\{unitHead\(/.test(ux) && /const unitHead = \(label: string, cur: string\): string => `\$\{label\.replace\(\/ \\\(\/g, "\\u00a0\("\)\.replace\(\/\(\\d\) \/g, "\$1\\u00a0"\)\},\\u00a0\$\{cur\}`;/.test(ux)
  && /<td data-fin-budget-net-label className="py-1 pr-2 text-\[11px\] min-\[360px\]:whitespace-nowrap">/.test(ux) && /data-fin-plan-amount=\{l\.fieldId\} className="w-24 min-\[360px\]:w-28 /.test(ux)
  && /<div data-fin-budget className=\{SUB\}>[\s\S]{0,200}<div className="flex flex-wrap items-center justify-between gap-2">/.test(ux) && /<label data-fin-mot-unit-row className="ml-auto /.test(ux)
  && /<div data-fin-card-warnings aria-live="polite">/.test(ux) && /className=\{`mt-2 break-words rounded-md border/.test(ux) && (ux.match(/maxLength=\{CARD_NAME_MAX\}/g) || []).length === 2 && /const CARD_NAME_MAX = 40;/.test(ux),
  "r.072 AsM: the budget and the cards fit a 320 px phone in view and edit mode; the warning wraps a long name and is announced");
// r.071 AsM fold (Enlil · Enki): the fit is PINNED — a reserve of 0 or 40, an em that ignores the advance, a unit word that grows without
// widening the reserve, or the three grid figures left at a fixed size (they ran into each other at 320 px and with COP amounts) all go red
{ const fit = fs.readFileSync(path.join(process.cwd(), "lib/financial-2525/fit.ts"), "utf8");
  const num = (re) => { const m = fit.match(re); return m ? Number(m[1]) : NaN; };
  const reserve = num(/export const FIG_RESERVE_PX = (\d+);/), adv = num(/export const FIG_ADVANCE_EM = ([\d.]+);/);
  const perChar = num(/export const FIG_UNIT_PX_PER_CHAR = (\d+);/), baseChars = num(/export const FIG_UNIT_BASE_CHARS = (\d+);/);
  // what is not a figure on the row measured 69–73 px with the English picker (57 px): the reserve must cover it and not starve the figures
  ok(reserve >= 80 && reserve <= 120 && adv >= 0.60 && adv <= 0.66 && perChar >= 6 && baseChars === 4
    && /const em = \(Math\.max\(1, Math\.round\(chars\)\) \* FIG_ADVANCE_EM\)\.toFixed\(2\);/.test(fit)
    && /return reservePx \+ FIG_UNIT_PX_PER_CHAR \* Math\.max\(0, widest - FIG_UNIT_BASE_CHARS\);/.test(fit)
    && /const labelChars = \(s: string\): number => Array\.from\(s\)\.reduce\(\(n, ch\) => n \+ \(WIDE_CHAR\.test\(ch\) \? 2 : 1\), 0\);/.test(fit),
    "r.071 AsM fold: the row's reserve is pinned (80–120 px, advance 0.60–0.66 em) and grows ~7 px per unit character past four");
  ok(/<dl data-fin-balance-grid className="mt-3 grid w-full grid-cols-3 gap-x-3" style=\{\{ containerType: "inline-size" \}\}>/.test(ux)
    && (ux.match(/<dd className="break-words font-mono tabular-nums text-foreground" style=\{gridFont\}>/g) || []).length === 3
    && /const gridFont = \{ fontSize: fitGrid\(Math\.max\(usd\(bal\.escrowedCents\)\.length, usd\(bal\.releasedCents\)\.length, usd\(bal\.withdrawnCents\)\.length\)\) \};/.test(ux)
    && /return `min\(0\.875rem, max\(0\.6875rem, calc\(\(\(100cqw - \$\{Math\.max\(0, cols - 1\) \* gapPx\}px\) \/ \$\{Math\.max\(1, cols\)\} - 4px\) \/ \$\{em\}\)\)\)`;/.test(fit),
    "r.071 AsM fold: In Escrow · Released · Spent share one size fitted to a third of the row, and past the floor a figure wraps in its own cell"); }
// r.071 (addendum 159): the gear's $/min · $/sec line is the rate escrow is releasing NOW — the same lower rate as the Accrual Rate after a
// spend ahead, never the deposit's original schedule
ok(/`· \$\{usd4\(bal\.netRatePerMinCents\)\} \$\{t\("fin\.rate\.min"\)\}`/.test(ux) && /const rateIn = \(u: RateUnit\): number => \(u === "sec" \? bal\.netRatePerMinCents/.test(ux), "r.071 (addendum 159): the gear's rate line and the Accrual Rate show the same live rate");
// r.068 (addendum 153): a card payment is found where a person pays a card — a Pay card button on the card (Debit · Debt service ›
// Credit Cards · that card, amount and time his) and the Pays card picker on EVERY Debit withdrawal, recorded whatever the field
ok(/data-fin-card-pay onClick=\{\(\) => onPay\(card\.id\)\}/.test(ux) && /\{t\("fin\.card_pay"\)\}/.test(ux) && /const payCard = \(id: string\) => \{ setTxType\("withdrawal"\); setPaidFrom\(DEBIT\); setSec\("I"\); setField\("I\.cards_student"\); setRec\("once"\); setPaysCard\(id\); setAmt\(""\);/.test(ux) && !/sec === "I"/.test(ux) && !/isDebt/.test(ux) && /ed\.paidFrom === DEBIT && <label/.test(ux), "r.068 (addendum 153): Pay card on each card opens a Debit payment to that card; the Pays card picker shows on every Debit withdrawal and is recorded whatever the field");
ok(/record\.entries\.filter\(\(e\) => !e\.tx\.corrects\)\.sort\(\(a, b\) => \(effective\.get\(a\.tx\.id\)\?\.atMs \?\? a\.tx\.atMs\) - \(effective\.get\(b\.tx\.id\)\?\.atMs \?\? b\.tx\.atMs\) \|\| a\.rev - b\.rev\)/.test(ux), "r.067 (addendum 151): the Transaction Record is always in chronological order, oldest first by (corrected) day and time");
// r.073 ROUND 1 OF 33 (the reviewer lenses on the transaction journey): the should-fix set, each gated where it lives
{ const ed0 = ux.slice(ux.indexOf("const openEdit = (x: FinTx) =>"), ux.indexOf("const edRefuse ="));
  ok(/useEffect\(\(\) => \{ if \(!editId \|\| !scrollEdit\.current\) return; scrollEdit\.current = false; const el = document\.querySelector\("\[data-fin-edit-panel\]"\); el\?\.scrollIntoView\(\{ behavior: "smooth", block: "center" \}\); \(el\?\.querySelector\("\[data-fin-edit-amount\]"\) as HTMLElement \| null\)\?\.focus\(\{ preventScroll: true \}\); \}, \[editId\]\);/.test(ed0) && /scrollEdit\.current = true;/.test(ed0),
    "r.073 (Athena): the pencil's editor comes into view with the focus on its Amount (below a long record it opened off-screen)");
  ok(/const foldForm = \(\) => \{ setFormOpen\(false\); setTxType\(""\); setRefusal\(null\); setUnsaved\(null\); refocusDoor\.current = true; \};/.test(ux) && /if \(!formOpen && refocusDoor\.current\) \{ refocusDoor\.current = false; doorRef\.current\?\.focus\(\); \}/.test(ux) && /onClick=\{openForm\} ref=\{doorRef\}/.test(ux),
    "r.073 (Athena): folding the form hands the focus back to + Transaction (it dropped to the top of the page)");
  ok(/<label className="col-span-2 text-\[10px\] uppercase">\{t\("fin\.when"\)\}<input data-fin-edit-when/.test(ux), "r.073 (Athena): the editor's Day and time takes the whole row on a phone (it showed \"2026.09.3\")");
  ok(/data-fin-tx-close [^\n]*className="flex h-8 w-9 items-center justify-center rounded-md border border-border"/.test(ux), "r.073 (Athena): the form's X is the gears' size (it was 24 px)");
  ok(/const chooseType = \(k: TxKind \| ""\) => \{ setTxType\(k\); setPaidFrom\(DEBIT\); setPaysCard\(""\); setRefusal\(null\);/.test(ux), "r.073 (Aset): changing the type clears the last refusal (a withdrawal's refusal stayed on a deposit)");
  const sum = ux.slice(ux.indexOf("<details data-fin-ledger"), ux.indexOf("<div data-fin-ledger-scroll"));
  ok(!/aria-label/.test(sum.slice(0, sum.indexOf("<ChevronRight"))) && /data-fin-cloud=\{cloudState\} role="img"/.test(sum), "r.073 (Sofia): the Record's summary is read as what it shows — title, a broken chain, the cloud (an image with its name)");
  ok(/aria-label=\{`\$\{t\("fin\.edit_tx"\)\} · #\$\{e\.rev\} · \$\{x\.kind === "deposit" \? "\+" : "−"\}\$\{num2\(x\.amountCents\)\} · \$\{fmtStampCST\(x\.atMs\)\}`\}/.test(ux), "r.073 (Sofia): every pencil says which entry it edits — its number, amount and day");
  ok(/<select data-fin-length-unit=\{hook\} aria-label=\{t\("fin\.unit"\)\}/.test(ux), "r.073 (Sofia): the Other length's unit picker has a name");
  ok(/\{refusal && <p role="alert" className="mt-2 text-sm text-red-500">/.test(ux) && /\{edRefusal && <p role="alert" data-fin-edit-refusal/.test(ux) && /<p role="alert" data-fin-save-failed/.test(ux) && /<p role="alert" data-fin-save-retry/.test(ux), "r.073 (Sofia): refusals and the save warnings are announced");
  ok(/const edRefuse = \(why: string\) => setEdRefusal\(`\$\{t\("fin\.refused"\)\} · \$\{why\}`\);/.test(ux) && !/setEdRefusal\(t\(/.test(ux), "r.073 (Aset): the editor's refusals carry the same \"Refused ·\" as the form's");
  ok(/\{t\("fin\.amount_col"\)\}, \{curMark\}<input data-fin-amount-input/.test(ux) && /\{t\("fin\.amount_col"\)\}, \{curMark\}<input data-fin-edit-amount/.test(ux) && !/t\("fin\.amount"\)/.test(ux), "r.073 (Aset): the form's and the editor's Amount name the picked currency, as the Record does");
  ok((ux.match(/parseAmountCents\(/g) || []).length === 3 && !/Number\(amt\)|Number\(ed\.amt\)|Number\(ed\.days\)|Number\(otherN\)/.test(ux) && /const n = rec === "other" \? parsePositive\(otherN\) : 0;/.test(ux), "r.073 (Enki): one reader for every typed amount and length — no bare Number() of what a person typed");
  ok(/if \(wasEmpty && m\.current\.entries\.length\) setTampered\(false\);/.test(ux) && /recordRef\.current = shown; setRecord\(shown\); setSaveFailed\(!saved\);/.test(ux), "r.073 (Aset): a warning ends when it stops being true — the broken chain once the account puts the record back, a failed save at the next good one");
  ok((ux.match(/return setRefusal\(stampWhy\(when\)\);/g) || []).length === 2 && /if \(instant === null\) return edRefuse\(stampWhy\(ed\.when\)\);/.test(ux) && !/t\("fin\.reason_stamp"\)\);/.test(ux.replace("stampProblem(text) === \"day\" ? t(\"fin.reason_stamp_day\") : t(\"fin.reason_stamp\")", "")), "r.073 (Enki): an impossible day is refused as a day not on the calendar, a bad shape as the shape — on the form and in the editor");
  ok(!/data-fin-edited/.test(ux) && !/correctionsOf/.test(ux) && /<td className="py-1 pr-3">\{e\.rev\}<\/td>/.test(ux), "r.073 (addendum 163 'remove history in Cyan'): the Record's # column shows the entry number only — no edit mark on the glass (every correction stays on the record and in the account copy)");
  ok(/\{saveFailed && !retrying && <p role="alert" data-fin-save-failed className="mb-2 text-sm text-amber-500">\{cloudState === "saved" \? t\("fin\.save_failed_cloud"\) : t\("fin\.save_failed"\)\}/.test(ux), "r.073 (Aset): the warning never says \"memory only\" while the account holds the entry");
}
console.log(`\nfinancial-surface: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);

