// Slice 3 — mock↔backend voxel-partition PARITY lock (pure-node).
// The JS partition in lib/sim-sections.ts (what MOCK_MODE renders on workers.dev) MUST be
// byte-identical to the Python sections.py the backend serves. This asserts it against a
// committed oracle generated by `export_partition_oracle.py`; regenerate that JSON whenever
// the partition/ordering/codes change, or this test catches the drift.
import assert from "node:assert";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { partitionSections, _sha256hex } from "../lib/sim-sections.ts";

const here = dirname(fileURLToPath(import.meta.url));
let pass = 0;
const ok = (name, cond) => { assert.ok(cond, name); console.log("PASS " + name); pass++; };

// 0) The SHA-256 must match a FIPS test vector (else the seed diverges from hashlib).
assert.strictEqual(_sha256hex("abc"),
  "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad", "sha256(abc)");
assert.strictEqual(_sha256hex(""),
  "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "sha256(empty)");
ok("sha256 matches FIPS vectors (seed parity with Python hashlib)", true);

// 1) Every oracle entry (cube.count) → the JS partition must reproduce cells + codes exactly.
const oracle = JSON.parse(readFileSync(join(here, "fixtures", "sim-partition-oracle.json"), "utf8"));
let entries = 0;
for (const [key, want] of Object.entries(oracle)) {
  const [cube, count] = key.split(".").map(Number);
  const got = partitionSections(cube, count).map((s) => ({ cells: s.cells, code: s.code }));
  const wantNorm = want.map((s) => ({ cells: s.cells, code: s.code }));
  assert.deepStrictEqual(got, wantNorm, `partition drift at cube ${cube} × ${count}`);
  entries++;
}
ok(`JS partition == Python oracle for all ${entries} cube×count entries`, entries === Object.keys(oracle).length);

// 2) Coverage + face-connectivity sanity on the JS side (defense in depth).
const faceN = (i) => {
  const x = i % 3, y = Math.floor(i / 3) % 3, z = Math.floor(i / 9), o = [];
  for (const [dx, dy, dz] of [[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]]) {
    const nx = x+dx, ny = y+dy, nz = z+dz;
    if (nx>=0&&nx<3&&ny>=0&&ny<3&&nz>=0&&nz<3) o.push(nz*9+ny*3+nx);
  }
  return o;
};
const connected = (cells) => {
  if (!cells.length) return true;
  const want = new Set(cells), seen = new Set([cells[0]]), stack = [cells[0]];
  while (stack.length) { const c = stack.pop(); for (const nb of faceN(c)) if (want.has(nb) && !seen.has(nb)) { seen.add(nb); stack.push(nb); } }
  return seen.size === want.size;
};
for (const n of [2, 3, 4, 6, 9, 27]) for (let c = 1; c <= 9; c++) {
  const secs = partitionSections(c, n);
  const all = secs.flatMap((s) => s.cells).sort((a, b) => a - b);
  assert.deepStrictEqual(all, Array.from({ length: 27 }, (_, i) => i), `cube ${c} n=${n} covers 27 once`);
  for (const s of secs) assert.ok(connected(s.cells), `cube ${c} n=${n} block ${s.code} face-connected`);
}
ok("JS blocks cover all 27 once + stay face-connected (n=2,3,4,6,9,27)", true);

console.log(`\nSIM-PARTITION-PARITY ${pass}/${pass} passed`);
