// GENERATED by frontend/scripts/gen-rcore-revisions.mjs — DO NOT EDIT BY HAND.
// Source (read-only, owned by another workflow): docs/traceability/security-2525.ledger.json
// Re-run: node scripts/gen-rcore-revisions.mjs

import type { LedgerInput } from "@/lib/2525-core/revisions";

/** Security-2525 append-only traceability ledger — 4 entries, extracted at build time. */
export const SECURITY_LEDGER: LedgerInput = {
  "section": "Security-2525",
  "route": "/main/Security-2525",
  "note": "Append-only Vision 2525 traceability for the SECURITY-2525 Autonomous Command Network surface. rev monotonic; append, never edit. Opened 2026-09-25 (R-CORE Stage 2, operator ask docs/asks/2026-09-25_rcore_button_revision_tracking.md). Seeded from real reachable commits on components/security-2525/command-ux1.tsx + mission-planning.tsx; this shallow history reaches back to ef8b1c3 (2026-08-28), which is the earliest commit that touched the surface in the clone, not necessarily its creation.",
  "entries": [
    {
      "rev": 1,
      "date": "2026-08-28",
      "kind": "release",
      "text": "Genesis — opens the append-only R-CORE record for SECURITY-2525, the eXeL AI Autonomous Command Network command shell: a self-contained tactical dark-ground dashboard with OVERVIEW, SENSORS, THREAT VIEW, PLANNING, SIMULATION, ENGAGEMENT, LOGISTICS, MISSION HEALTH, TRAINING & VR and AFTER ACTION tabs, the Mission Planning map, MIL-STD-2525 / eXeL-STD-2525 iconology toggle and a global settings gear. Earliest commit reachable in this shallow history that touched the surface: ef8b1c3.",
      "commit": "ef8b1c3"
    },
    {
      "rev": 2,
      "date": "2026-09-13",
      "kind": "release",
      "text": "Site-UX keyify batch 4 — hardcoded strings across the security-2525 tree routed through t() so the surface renders in all 33 languages via the shared lexicon fallback chain.",
      "commit": "d2806d1"
    },
    {
      "rev": 3,
      "date": "2026-09-13",
      "kind": "release",
      "text": "Site-UX keyify batch 5 — 99 hardcoded strings in security-2525 (command-ux1 + mission-planning) routed through t(), completing lexicon coverage on the command shell.",
      "commit": "993a456"
    },
    {
      "rev": 4,
      "date": "2026-09-25",
      "kind": "decision",
      "text": "R-CORE version-history badge mounted on SECURITY-2525 (Stage 2): the bottom-centre two-click R-CORE reticle icon expands to the '⊕ R-CORE' pill and then opens the R-CORE · Version History compare panel, reading this surface's own append-only ledger. The record opens here and grows as features land (operator 2026-09-25 ask docs/asks/2026-09-25_rcore_button_revision_tracking.md).",
      "commit": ""
    }
  ]
};
