import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_CS: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Kde začíná inovace`,
    content: {
      7: `Vůdci začínají, co žádné století nezačalo.`,
      33: `Tři regiony — Kambodža, Honduras, Austin — otevírají slib, na jehož budování se podílejí občané: hostit ty, kdo se učí, chránit je, předat jim nástroje budoucnosti. Vláda, Vzdělávání a Inovace podepisují jako správci; občané jej drží. Jeden začátek.`,
      111: `Atlantidská dohoda je dohoda mezi občany světa — slib, který může vytvořit a držet kdokoli, kdekoli, bez ohledu na to, co podepíše jeho vláda nebo dovolí jeho zaměstnavatel. Její zakládající regiony, Kambodža, Honduras a Austin v Texasu, byly vybrány pro jednu vzácnou vlastnost: ochotu svěřit mladým nástroje budoucnosti, dokud je ještě čas je to naučit. Vlády, vzdělavatelé a inovátoři podepisují jako správci svých regionů — po třech vizionářských podpisech z každého regionu, Vláda, Vzdělávání, Inovace — ale dohodu financují, sledují a přímo za ni nesou odpovědnost občané. Ke členství není potřeba svolení žádné vlády ani požehnání žádného zaměstnavatele. Tři regiony, jeden společný začátek.`,
      333: `Každou civilizaci si pamatujeme podle toho, co si zvolila začít. Atlantidská dohoda je slib mezi občany světa — může ji začít kdokoli, kdekoli, bez ohledu na to, co podepíše jeho vláda. Její zakládající regiony, Kambodža, Honduras a Austin v Texasu, nebyly vybrány pro hospodářskou sílu, vojenskou moc ani institucionální prestiž, ale pro vzácnější vlastnost: ochotu svěřit mladým nástroje budoucnosti. To je smysl vůdcovství v nadcházejícím století — odvaha předat klíče další generaci, dokud je ještě čas ji naučit řídit.

Dohodu svolává eXeL, organizační síla stvořená přímo pro tuto chvíli, existující mimo koordinační kanály, které utvářely minulé století — mimo struktury diplomatických smluv, mnohostranné byrokracie i politické zapletení jakéhokoli jednotlivého národního státu. eXeL je důvěryhodný svolavatel, který svádí dohromady vizionářské vůdce kolem sdíleného rámce, sdíleného setrvačníku a sdíleného pětisetletého horizontu. Každý signatář si zachovává plnou suverenitu, plnou pravomoc nad vlastními občany a plnou svobodu kdykoli odstoupit. Co signatáři získávají — a co získává každý občan, za cenu Seed, sedminy hodiny místní minimální mzdy — je síťový efekt, který dokáže poskytnout jen rámec stvořený přesně k tomuto účelu: koordinace bez jakékoli formy politické nadvlády.

Podepsat dohodu znamená podepsat slib: že region bude hostit ty, kdo se učí, napříč kulturami, přispěje tím, co může nabídnout jen on, a bude se držet standardu vyššího, než vyžadují současné předpisy — veřejně, transparentně, se zodpovědností vůči občanům, kteří ji financují, sledují a drží za ni odpovědnost, přičemž ke členství není potřeba svolení žádné vlády ani požehnání žádného zaměstnavatele. Z každého regionu jsou vyžadovány tři podpisy — Vláda, Vzdělávání a Inovace — podepisující jako správci, nikoli vlastníci. Je potřeba tří vizionářů, aby řekli ano, a občanů, aby drželi, co podepsali. Tři vizionáři, tři regiony, jeden začátek — takto rámec vstupuje do života skrze důvěru vůdců ochotných jej svým podpisem přivést k životu.`,
      999: `Každou civilizaci si pamatujeme podle toho, co si zvolila začít, a Vision 2525 žádá zakladatele té naší, aby začali s pokorou, nikoli s dobýváním. Atlantidská dohoda je slib vůdců ochotných začít něco, co dosud neexistovalo — sdílený základ pro lidskou inovaci, který dosáhne do každého kouta světa, ctí každý hlas a přetrvá napříč generacemi měřenými nikoli v letech, ale ve staletích. Její zakládající signatáři v Kambodži, Hondurasu a Austinu v Texasu nebyli vybráni pro hospodářskou sílu, vojenskou moc ani institucionální prestiž. Byli vybráni pro vzácnější vlastnost: ochotu svěřit mladým nástroje budoucnosti a trpělivost nechat pětisetletý horizont přetrvat potlesk kterékoli vlády. To je smysl vůdcovství v nadcházejícím století — odvaha předat klíče další generaci, dokud je ještě čas ji naučit řídit.

Dohodu svolává eXeL, organizační síla stvořená přímo pro tuto chvíli. eXeL existuje mimo koordinační kanály, které utvářely minulé století — mimo struktury diplomatických smluv, mimo mnohostranné byrokracie, mimo politické zapletení jakéhokoli národního státu. eXeL je důvěryhodný svolavatel, který svádí dohromady vizionářské vůdce kolem sdíleného rámce, sdíleného setrvačníku a sdíleného pětisetletého horizontu. Každý signatář si zachovává plnou suverenitu, plnou pravomoc nad vlastními občany a plnou svobodu kdykoli odstoupit. Co signatáři získávají, je síťový efekt, který dokáže poskytnout jen rámec stvořený přesně k tomuto účelu. Vstup každého účastníka do tohoto rámce začíná stejně skromně: se Seed, jednorázovým členstvím oceněným na sedminu hodiny místní minimální mzdy, nepřevoditelným a nenesoucím žádný ekonomický nárok jakéhokoli druhu. Seed nekupuje žádné vlastnictví ani příslib odměny — pouze příslušnost, právo stát uvnitř rámce a začít. To je koordinace bez jakékoli formy politické nadvlády, postavená na začátku dost malém na to, aby si jej mohl dovolit kdokoli.

Protože suverenita je zachována, nikoli vzdaná, je dohoda postavena na principu Continuity Without Evasion. Žádná nepostradatelná vláda, banka, zakladatel ani model nesmí držet celý rámec jako rukojmí vlastního přežití. Každá jurisdikce je obsluhována prostřednictvím svého zákonného adaptéru, ve výchozím stavu odmítajícího, dokud není prokázán soulad, takže hodnota proudí pouze skrze kanály, které by soud v dané jurisdikci uznal za legitimní. Pokud regulátor v jednom regionu vydá nepříznivé rozhodnutí, tento jediný kanál se bezpečně uzavře — transparentně, aniž by poškodil kteréhokoli účastníka uvnitř něj — zatímco všechny ostatní regiony pokračují nerušeně. Celá dohoda nikdy nepadne jen proto, že jedna vláda změnila názor. Toto je přenositelnost navržená jako zakládající slib, nikoli jako nouzové řešení objevené až po krizi.

Podepsat dohodu znamená podepsat slib. Že region bude hostit ty, kdo se učí, napříč kulturami. Že region přispěje tím, co může nabídnout jen on. Že region se bude držet standardu vyššího, než vyžadují současné předpisy. Že to region učiní veřejně, transparentně, před zraky každého občana, kterému slouží. Z každého regionu jsou vyžadovány tři podpisy — Vláda, Vzdělávání a Inovace. Žádný jediný úřad nezavazuje dohodu sám. Je potřeba tří vizionářů, aby řekli ano. Tento trojí podpis je prvním vyjádřením Human Authority: smysl, peníze a právo zůstávají v lidských rukou na suverénní úrovni, úrovni trvale uzavřené strojům, ať se jakkoli zdokonalí. Measurement of Time, MoT, začíná zaznamenávat od okamžiku podpisu — skutečné minuty skutečné lidské práce, oddělené od jakéhokoli automatizovaného odhadu — a každé následující vydání práce dohody je navrženo tak, aby je bylo možné rekonstruovat prostřednictvím Replay, aby občan narozený za století mohl zpětně vysledovat, jak byla dnešní zakládající rozhodnutí učiněna.

Pilotní projekt zakládá především měření, teprve poté peníze. Každá inovace vstupující do rámce je hodnocena pomocí Qualified Innovation Score, QIS — průměru z Revenue, Gross Profit, Operating Income a Effective R&D spending, děleného čtyřmi. QIS není platba a nikdy není vlastnictví; je to nástroj, jímž se zakládající kohorta učí vidět vlastní pokrok dřív, než je určena velikost jakékoli odměny. Růst QIS, jakmile je splněna kvalifikace, určuje velikost následujícího fondu odměn — ale samotný růst QIS sám o sobě nic nerazí. Tři regiony, jeden začátek a jedna sdílená disciplína: nejprve prokázat skóre, teprve poté sáhnout na pokladnu.

Hodnota vydělaná ověřenou prací nese vlastní jméno, 웃, vypočtené jako jedna hodina násobená místní minimální mzdou, škálovaná Multiple uplatněným na odsloužené hodiny. 웃 se vydává pouze za práci ověřenou v rámci vymezeného, rozpočtem schváleného úkolu; cokoli pod touto úrovní schválení je stále jen plánování a samotné plánování nic nerazí. Zúčtovací strop 9 999 웃 za rok chrání každého účastníka před nekontrolovanou koncentrací, přičemž jakýkoli přebytek se převádí do dalšího roku, nikoli mizí. Za každým 웃 stojí ♡, Shared Intention, nesoucí důvod, proč byl úkol vůbec schválen, a ◬, ověřené zrychlení, které úkol vytvořil vůči zmrazené výchozí úrovni — pouze delta, nikdy nezaměňovaná za ukazatel zisku. Pilotní projekt existuje proto, aby prokázal, že tyto tři glyfy se dokážou pohybovat společně a poctivě, region po regionu, dřív, než se rámec rozroste za hranice svých zakladatelů.

Když hodnota dosáhne k člověku, dosáhne k němu skrze Livelihood Direct — 🏠 — kvalifikované licencované místní kanály, které eXeL nikdy nedrží v úschově jako vlastní fond. Klasifikace vždy předchází zúčtování a uznání přínosu nikdy samo o sobě neotevírá dveře k lůžku na noc; to určuje pouze role dané osoby ve vymezeném úkolu. Růst nad rámec pilotního projektu je rovněž podmíněný: každá kostka rámce postupuje z Manual přes Semi-Automated do Autonomous teprve poté, co splní pravidlo 11,1 procenta, jednu devítinu měřeného zlepšení, vydobytou kostku po kostce a nikdy nenárokovanou paušálně — a nikdy, za žádných okolností, nad suverénní úrovní smyslu, peněz a práva. Takto se tři vizionáři na region, tři regiony a jeden začátek stávají pětisetletým slibem: ne rychlým postupem, ale prokazováním, před zraky veřejnosti, že každý krok si vydobyl krok následující.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Učení skrze simulaci`,
    content: {
      7: `Tisíckrát cvičit, než se dotkneš.`,
      33: `Nic zásadního se neučí poprvé na živém hardwaru. Kterýkoli občan si může nacvičit v simulaci, rotovat mezi třemi regiony, slavit — úcta k mladému člověku, jehož první chyba nesmí nikdy stát život.`,
      111: `Každou disciplínu, kterou stojí za to ovládnout, se někdo naučil dřív, než byla známa. Atlantidská dohoda vrací tuto starobylou moudrost do středu toho, jak jsou mladí — a kterýkoli občan, který se připojí — připravováni budovat budoucnost. Nic zásadního se neučí poprvé na živém hardwaru, na skutečných lidech nebo v nezvratných podmínkách; není k tomu potřeba svolení žádné vlády ani požehnání žádného zaměstnavatele. Každý účastník cvičí v simulaci, dokud se cvik nestane zdatností a poté připraveností. Rotační model provádí každého účastníka třemi zakládajícími regiony a každá rotace končí veřejnou oslavou otevřenou hostitelské komunitě. To je úcta k mladému člověku, jehož první chyba nesmí nikdy stát život.`,
      333: `Každou disciplínu, kterou stojí za to ovládnout, se někdo naučil dřív, než byla známa. Mistři svého řemesla nacvičují před vystoupením, piloti před letem, lékaři před operací, děti prostřednictvím hry. Atlantidská dohoda vrací tuto starobylou moudrost do středu toho, jak jsou mladí — a kterýkoli občan, který se připojí, bez potřeby svolení vlády nebo požehnání zaměstnavatele — připravováni budovat budoucnost. Nic zásadního se neučí poprvé na živém hardwaru, na skutečných lidech nebo v nezvratných podmínkách. Každý účastník cvičí v simulaci, dokud se cvik nestane zdatností a poté připraveností. Není to opatrnost — je to úcta k mladému člověku, jehož první chyba nesmí nikoho stát život.

Rotační model dohody provádí každého účastníka třemi zakládajícími regiony. Co se naučí v Kambodži, zdokonalí se v Hondurasu a dokončí v Austinu. Co se objeví v Austinu, prověří se v Kambodži a integruje se v Hondurasu. Každý účastník žije, učí se a je veden mentory napříč kulturami, které by jinak zůstaly vzdálené. Vzdělávací osnovy čerpají z tradic disciplinované simulace napříč mnoha kulturami — ze strategické vzdělávací tradice Sun Tzua, z Musašiho nácviku hrou, z cyklické teorie učení Ibn Chaldúna, z mnišské dialektiky Nálandy, z civilního letového simulátoru — syntetizovány tak, aby respektovaly každou kognitivní fázi a kulturní dědictví. Žádná jediná tradice nedominuje.

Každá rotace končí veřejnou oslavou otevřenou hostitelské komunitě, kde sousedé, rodiny a návštěvníci vidí, co se kohorta naučila. Tyto události činí sofistikovanou technologii přístupnou a oslavovanou, nikoli děsivou — společnost, která vyrůstá s porozuměním kooperativním systémům skrze hru, jí nelze snadno manipulovat strachem z nich. Toto je odstrašení skrze vzdělávání, nikoli skrze sílu. Slib dohody každému rodiči: vaše dítě si bezpečně nacvičí tisíckrát, než se dotkne čehokoli, co by mu mohlo ublížit, vše ověřeno tak, aby občan — kterýkoli občan, i za sto let — mohl ověřit, že se to stalo přesně tak, jak je zaznamenáno. To je úcta k mladému člověku zabudovaná do rámce a je to, co vůdcovství dluží dalšímu občanovi, který se připojí, dřív, než to bude muset tento občan požadovat.`,
      999: `Každou disciplínu, kterou stojí za to ovládnout, se někdo naučil dřív, než byla známa, a každá civilizace, která přetrvala, tak učinila proto, že chránila prostor, v němž se toto učení mohlo dít bezpečně, dřív, než na něm začalo záležet. Mistři svého řemesla nacvičují před vystoupením, piloti nacvičují před letem, lékaři nacvičují před operací a děti nacvičují svět skrze hru. Atlantidská dohoda vrací tuto starobylou moudrost do středu toho, jak jsou mladí připravováni budovat budoucnost, a dává této moudrosti jméno a mechanismus: Replay. Nic zásadního se neučí poprvé na živém hardwaru, na skutečných lidech nebo v nezvratných podmínkách. Každý účastník cvičí v simulaci, dokud se cvik nestane zdatností a poté připraveností, a každá hodina tohoto cvičení je zaznamenána, aby ji bylo možné později rekonstruovat, prozkoumat a důvěřovat jí. Není to opatrnost — je to úcta k mladému člověku, jehož první chyba nesmí nikoho stát život, a je to úcta k záznamu, který tuto chybu tak jako tak přetrvá.

Rotační model dohody provádí každého účastníka třemi zakládajícími regiony. Co se naučí v Kambodži, zdokonalí se v Hondurasu a dokončí v Austinu. Co se objeví v Austinu, prověří se v Kambodži a integruje se v Hondurasu. Každý účastník žije, učí se a je veden mentory napříč kulturami, které by jinak zůstaly vzdálené, a každá rotace začíná tak, jak začíná každá lidská instituce, které stojí za to důvěřovat: se Seed. Seed je jednorázové členství, oceněné na sedminu hodiny místní minimální mzdy, nepřevoditelné, nenesoucí žádný ekonomický nárok jakéhokoli druhu. Není to poplatek za přístup k příležitosti. Je to práh — dost nízký, aby z něj nebyl vyloučen žádný ochotný účastník, dost záměrný, aby vstup byl volbou, ne náhodou. Od tohoto prahu dál patří každý účastník rotaci a rotace nepatří jedinému regionu.

Vzdělávací osnovy čerpají z tradic disciplinované simulace napříč mnoha kulturami — ze strategické vzdělávací tradice Sun Tzua, z Musašiho nácviku hrou, z cyklické teorie učení Ibn Chaldúna, z mnišské dialektiky Nálandy, z civilního letového simulátoru — syntetizovány tak, aby respektovaly každou kognitivní fázi a kulturní dědictví. Žádná jediná tradice nedominuje. A v rámci těchto osnov dohoda vytyčuje hranici, kterou se každý účastník naučí brzy a nikdy nezapomene: simulace je místem, kde se Qualified Innovation Score chápe, nikoli kde se utrácí. QIS je měřítko, nikdy platba, a QIS nikdy není vlastnictví — existuje proto, aby popsal, jak dobře návrh obstojí, drží se a slouží regionu, kterému má sloužit. Růst QIS může po skutečné kvalifikaci určit velikost fondu odměn, ale sám o sobě nic nerazí. Účastník může odehrát stovku bezchybných simulací a dosáhnout rostoucího skóre, aniž by se jeho účtu dotkla jediná hodina 웃, protože 웃 se vydává pouze za práci ověřenou v rámci vymezeného, rozpočtem schváleného úkolu. Před tímto schválením je vše — jakkoli zdatné, jakkoli slibné — pouze plánování. Dohoda tento rozdíl učí hned první den, aby žádný mladý člověk nezaměnil nácvik za odměnu a aby žádný mladý člověk nebyl nikdy uveden v omyl ohledně toho, k čemu simulace slouží.

Stejná disciplína určuje, kolik autonomie smí jakýkoli systém, lidský či umělý, uplatňovat uvnitř rotace. Provozní režimy dohody postupují v pořadí — Manual, poté Semi-Automated, poté Autonomous — a žádná kostka nepostoupí do dalšího režimu, dokud nesplní pravidlo 11,1 procenta měřeného zlepšení, jednu devítinu, prokázanou vůči zmrazené výchozí úrovni a ověřenou, nikoli jen tvrzenou. Simulace je místem, kde se tento důkaz buduje. Nástroj si vydobude právo jednat s menším dohledem stejným způsobem, jakým si účastník vydobude právo na větší odpovědnost: prostřednictvím prokázaného, zaznamenaného a rekonstruovatelného zlepšení, kostku po kostce, nikdy najednou a nikdy nad úrovní, kde se rozhoduje o smyslu, penězích a právu. Tato úroveň patří výhradně Human Authority, v simulaci i v živém provozu, protože nácvikový prostor, který učí špatnou hranici, učí špatnou lekci natrvalo.

Každá rotace končí veřejnou a společnou oslavou otevřenou hostitelské komunitě. Sousedé, rodiny a návštěvníci se scházejí, aby viděli, co se kohorta naučila, a to, čeho jsou svědky, není předvedení rychlosti pro rychlost samotnou, ale předvedení ◬ — měřené delty mezi zmrazenou výchozí úrovní a tím, čeho disciplinovaný nácvik skutečně dosáhl, prezentované poctivě, nikdy vydávané za ukazatel zisku, nikdy prezentované jako víc, než skutečně je. Tyto události činí sofistikovanou technologii přístupnou a oslavovanou, nikoli děsivou. Společnost, která vyrůstá s porozuměním kooperativním systémům skrze hru, jí nelze snadno manipulovat strachem z těchto systémů. Toto je odstrašení skrze vzdělávání, nikoli skrze sílu, a funguje to proto, že komunita není žádána, aby věřila tvrzení — je zvána, aby sledovala Replay.

Slib dohody každému rodiči přesahuje bezpečnost a dosahuje až k trvalosti: vaše dítě si nacvičí tisíckrát, než se dotkne čehokoli, co by mu mohlo ublížit, komunita bude po celou dobu svědkem jeho růstu a nic z toho se neztratí v čase. Measurement of Time zaznamenává skutečné minuty odděleně od každé jiné účetní knihy, kterou dohoda vede, aby nacvičené hodiny a ověřené hodiny nebyly nikdy navzájem zaměněny a aby skutečná vývojová historie účastníka — nikoli shrnutí, nikoli přiblížení, ale samotný rekonstruovatelný záznam — zůstala tomuto účastníkovi dostupná tak dlouho, jak dlouho ji bude chtít nahlížet. Rodič v Phnompenhu, mentor v Tegucigalpě, auditor v Austinu nebo vnouče čtoucí záznam za sto let — všichni mohou dosáhnout stejného Replay a spatřit stejnou pravdu.

Takto vypadá úcta k mladému člověku, když je zabudovaná do rámce, a ne pouze rámcem slibovaná, a toto je to, co vůdcovství předává další generaci účastníků dřív, než to tato generace musí požadovat: nácvikový prostor dost rozlehlý, aby v něm bylo bezpečné selhat, dost poctivý, aby věrně zaznamenával, a dost disciplinovaný, aby držel odměnu, autonomii a pravomoc přesně tam, kde si je zdatnost vydobyla — nikdy před ní, nikdy za ní.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Bezpečnost ověřena dříve, než je poskytnuta důvěra`,
    content: {
      7: `Bezpečnost prokázána nejdřív, pak důvěra.`,
      33: `Každé zařízení a každá rotace se nachází uvnitř ochranné obálky s včasným varováním. Hardware odmítá zbrojní použití — prokazatelně, nikoli jen slíbeně, ověřitelně občany. Záznamy přežívají otřesy. Bezpečnost je den co den navrhována kolem nejmladšího účastníka.`,
      111: `Než je udělena důvěra, musí být prokázána bezpečnost — nikoli vládě, ale kterémukoli občanovi, který ji prověřuje. Atlantidská dohoda je dohoda mezi občany světa; jejím zakládajícím závazkem je toto: každé zařízení dohody, každá trasa rotace, každé místo, kde mladý účastník spí nebo studuje, se nachází uvnitř zdokumentované ochranné obálky se schopností včasného varování, která dává komunitě hodiny, nikoli minuty, na reakci na jakékoli věrohodné riziko. Každé zařízení, každý senzor, každý koordinační systém je na úrovni hardwaru vázán odmítnout přeprogramování k integraci do zbraňových systémů. Toto není politika — toto je fyzika. Dohoda zůstává čestná i v turbulentních dobách, protože každý plán klade lidskou důstojnost na první místo.`,
      333: `Než je udělena důvěra, musí být prokázána bezpečnost — prokázána občanům, nikoli jen tvrzena. Atlantidská dohoda je dohoda mezi občany světa: kterákoli osoba kdekoli může pomáhat ji držet, bez ohledu na to, co podepíše její vláda. Každé zařízení dohody, každá trasa rotace, každé místo, kde mladý účastník spí nebo studuje, se nachází uvnitř zdokumentované ochranné obálky se schopností včasného varování, která dává komunitě hodiny, nikoli minuty, na reakci na jakékoli věrohodné riziko. Technologie, která je chrání, je táž technologie, kterou je dohoda učí budovat. Mladí lidé se učí bezpečnosti zevnitř ven, nikoli tím, že jim je řečeno, že jsou v bezpečí, ale tím, že vidí, jak je kolem nich den co den navrhována, a vědí, že kterýkoli občan může záznam ověřit prostřednictvím Replay.

Dohoda dává neporušitelný slib o tom, čím se její technologie nikdy nesmí stát. Každé zařízení, každý senzor, každý koordinační systém je na úrovni hardwaru vázán odmítnout přeprogramování k integraci do zbraňových systémů. Toto není formulace politiky, ani přání. Toto je fyzická nemožnost, vynucená kryptograficky, ověřená každým signatářským regionem a ověřitelná každým občanem, který ji financuje. Nástroje, které chrání dítě v Phnompenhu, nelze přeprogramovat, aby ublížily dítěti v Austinu. Nástroje, které propojují cvičení rojů v Tegucigalpě, nelze přenastavit tak, aby se zaměřily na člověka kdekoli. Toto je odpověď dohody na století strachu z dvojího užití. Ne politika — fyzika.

Dohoda zůstává čestná i v turbulentních dobách. Pokud region ztratí politickou stabilitu, o účastníky se postarají zbývající regiony. Pokud se zúží financování, stipendia jsou chráněna jako první — financovaná měsíčně občany, nikdy ne skrze pomocný kanál, každý dolar vysledovatelný. Pokud jsou napadeny digitální záznamy, přetrvávají offline zálohy. Pokud se cestování stane nemožným, substrát pokračuje virtuálně. Každý plán klade lidskou důstojnost — Human Authority nad smyslem, penězi a právem — jako svůj první návrhový požadavek. Vůdci, kteří tuto dohodu podepisují, slibují, že bezpečnost je navržena, nikoli předpokládána: ochrana, kterou by kterýkoli vůdce požadoval pro vlastní dítě, nyní rozšířená na každého občana, který pomáhá ji držet.`,
      999: `Než je udělena důvěra, musí být prokázána bezpečnost — to je zakládající závazek Atlantidské dohody, a je prokazován stejně, jako je prokazováno každé jiné tvrzení uvnitř Vision 2525: ne tvrzením, ale důkazy, které mohou občané prověřit. Každé zařízení dohody, každá trasa rotace, každé místo, kde mladý účastník spí nebo studuje, se nachází uvnitř zdokumentované ochranné obálky se schopností včasného varování, která dává komunitě hodiny, nikoli minuty, na reakci na jakékoli věrohodné riziko. Technologie použitá k ochraně účastníků je táž technologie, kterou je dohoda učí budovat — senzory, koordinace, odolnost komunikace, distribuovaná inteligence. Mladí lidé se učí bezpečnosti zevnitř ven, ve vlastním jazyce a ve vlastním regionu, nikoli tím, že jim je řečeno, že jsou v bezpečí, ale tím, že hodinu po hodině sledují, jak je kolem nich den co den bezpečnost navrhována.

Toto sledování není ponecháno na paměti ani na důvěře ve slovo instruktora. Measurement of Time zaznamenává skutečné minuty každého cvičení, každé rotace, každého nácviku reakce — odděleně od jakéhokoli tvrzení o pokroku, odděleně od jakéhokoli příběhu vyprávěného toho dne. Replay činí každé vydání vzdělávacích osnov, každou bezpečnostní aktualizaci, každou revizi hardwaru plně rekonstruovatelnou, takže rodič v Tegucigalpě nebo regulátor v Phnompenhu může zpětně projít přesně to, co se změnilo, kdy se to změnilo a proč se to změnilo. Ochranná obálka, kterou nelze přehrát skrze Replay, je jen slib. Ochranná obálka, kterou lze přehrát, minutu po zaznamenané minutě, je důkaz. Dohoda volí důkaz.

Dohoda dává neporušitelný slib o tom, čím se její technologie nikdy nesmí stát. Každé zařízení, každý senzor, každý koordinační systém je na úrovni hardwaru vázán odmítnout přeprogramování k integraci do zbraňových systémů. Toto není formulace politiky, ani přání. Toto je fyzická nemožnost, vynucená kryptograficky, ověřená každým signatářským regionem a ověřitelná každým občanem. Nástroje, které chrání dítě v Phnompenhu, nelze přeprogramovat, aby ublížily dítěti v Austinu. Nástroje, které propojují cvičení rojů v Tegucigalpě, nelze přenastavit tak, aby se zaměřily na člověka kdekoli. Toto je odpověď dohody na století strachu z dvojího užití. Ne politika — fyzika.

Jednou prokázaná bezpečnost není bezpečnost udržená napříč pětisetletým horizontem. Dohoda pojmenovává svůj druhý závazek Continuity Without Evasion: zákonná přenositelnost napříč každou jurisdikcí, které se dohoda dotýká, bez jediné nepostradatelné vlády, banky, zakladatele nebo modelu stojícího mezi účastníkem a jeho ochranou. Každá jurisdikce je obsluhována vlastním adaptérem, bezpečně se uzavírajícím a ve výchozím stavu odmítajícím, takže nepříznivé rozhodnutí v kterémkoli regionu uzavře pouze tento jeden kanál — nikdy celý rámec, nikdy všechny regiony, nikdy všechny účastníky kdekoli najednou. Soudní rozhodnutí na jednom signatářském území nemůže vypnout ochrannou obálku účastníka jinde. To je smysl budování systému, který přežije obyčejné otřesy práva, politiky a institucionálních změn, aniž by kdy žádal účastníka, aby kvůli ochraně obcházel zákon.

Každá vrstva této ochranné architektury se v konečném důsledku zodpovídá Human Authority. Smysl, peníze a právo nejsou nikdy delegovány na stroje — suverénní úroveň, která rozhoduje, co bezpečnost vyžaduje, co se počítá za věrohodné riziko a jakou reakci komunita dluží svým nejmladším členům, zůstává uzavřená umělé inteligenci, ať se jakkoli zdokonalí. Systémy dohody procházejí pouze třemi provozními režimy — Manual, Semi-Automated, Autonomous — a žádný systém nepostoupí do dalšího režimu bez ověřeného, měřeného zlepšení o nejméně jednu devítinu, jedenáct a jednu desetinu procenta, ověřeného, reprodukovatelného. Autonomie se vydobývá kostku po kostce, funkci po funkci, nikdy se neuděluje paušálně a nikdy se nerozšiřuje nad otázky, které určují smysl, peníze nebo právo. Senzor se může naučit detekovat rychleji. Koordinační systém se může naučit směrovat efektivněji. Ani jeden z nich nesmí nikdy sám rozhodnout, co má komunita svěřit svým dětem.

Dohoda je navržena tak, aby zůstala čestná i v turbulentních dobách, a tyto turbulence pojmenovává předem, místo aby je objevovala až v krizi. Pokud signatářský region ztratí politickou stabilitu, o účastníky se postarají zbývající regiony. Pokud se zúží financování, stipendia účastníků jsou chráněna jako první, před správou a infrastrukturou. Pokud jsou napadeny digitální záznamy, přetrvávají offline zálohy, nedosažitelné jakoukoli poruchou, která zasáhla síť. Pokud se cestování stane nemožným, substrát pokračuje virtuálně, takže rotace se nezastaví jen proto, že se uzavřela hranice. Na každý scénář je myšleno předem a každý plán klade lidskou důstojnost jako svůj první návrhový požadavek — ne jako poslední úvahu, až budou vyřešeny rozpočty a vnější dojem.

Vstup do tohoto prokázaného systému začíná se Seed — jednorázovým členstvím, oceněným na sedminu hodiny místní minimální mzdy, nepřevoditelným a nenesoucím žádný ekonomický nárok na cokoli, co dohoda následně vybuduje. Seed nekupuje bezpečnost; bezpečnost je navržena dlouho předtím, než je jakýkoli Seed vůbec zasazen. Co Seed kupuje, je postavení — právo vstoupit do rámce, který je již prokázaný, již prověřený, již vázaný hardwarem, jenž nelze obrátit proti samotné osobě, kterou má chránit. Toto oddělení je záměrné. Slib bezpečnosti, který musí být zakoupen za skutečnou ekonomickou hodnotu, není slibem bezpečnosti vůbec, je jen bezpečnostním produktem. Dohoda oba tyto pojmy drží zcela odděleně, aby žádná rodina nikdy nemusela vážit ochranu svého dítěte proti měsíčnímu rozpočtu domácnosti.

Vůdci, kteří tuto dohodu podepisují, podepisují slib, že bezpečnost je navržena, nikoli předpokládána, a prokázána, nikoli jen tvrzena. Co rozšiřují svým občanům, není pouze příležitost, ale ochrana vybudovaná na standardu, který si zaslouží nejmladší účastník — zaznamenaná prostřednictvím Measurement of Time, rekonstruovatelná prostřednictvím Replay, vázaná na úrovni hardwaru proti každému zneužití, jaké si dokázalo představit ustrašené století, a zodpovídající se vždy a pouze Human Authority. Toto je táž ochrana, kterou by každý vůdce požadoval pro vlastní dítě přecházející neznámou hranici samo, nyní rozšířená na každé dítě, kterému bude dohoda kdy sloužit, napříč jejími třemi zakládajícími regiony Kambodže, Hondurasu a Austinu, a napříč pěti stoletími, po která dohoda hodlá tento slib dodržet.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Odměna, blaho a lidská důstojnost`,
    content: {
      7: `Stipendium, mentor, domov.`,
      33: `Každý občan dostává stipendium od prvního dne — bez svolení vlády, bez požehnání zaměstnavatele. Láska, ztráta a bezpečí jsou infrastruktura. Úspěch se měří podle nejzranitelnějších. Důstojnost je substrát, nikdy ozdoba.`,
      111: `Atlantidská dohoda zachází s každým účastníkem jako s lidskou bytostí od prvního dne — jako s občanem, který se připojil právem, ne vládním výnosem ani svolením zaměstnavatele. Stipendium je poskytováno od okamžiku, kdy účast začíná, vázané na životní náklady daného regionu, a každá ověřená hodina vydělává 웃, vyplacené osobě prostřednictvím Livelihood Direct, nikdy skrze účetnictví zaměstnavatele. S blahobytem se zachází jako s prvořadou infrastrukturou — ne jako s výhodou, ale jako se substrátem, na němž stojí všechno ostatní. Podporovány jsou tři oblasti: Láska, Ztráta a Bezpečí. Dohoda měří úspěch podle svého nejzranitelnějšího účastníka, nikoli podle průměru. Nikdo není zapomenut jen proto, aby průměry vypadaly dobře. Důstojnost jako substrát, ne ozdoba.`,
      333: `Atlantidská dohoda zachází s každým účastníkem jako s lidskou bytostí od prvního dne — jako s občanem, který patří právem a nepotřebuje k tomu svolení vlády ani požehnání zaměstnavatele. Stipendium je poskytováno od okamžiku, kdy účast začíná, vázané na životní náklady daného regionu, přicházející dřív, než se rodinné závazky změní v nouzi. Toto není charita. Toto je uznání skutečnosti, že obyčejná lidská inovace vyžaduje především lidské zajištění — mysl nemůže vzkvétat, pokud je domácnost ohrožena.

Co se vydělá nad rámec stipendia, se vydělává tak, jak si to vydělá občan: skrze Seed, oceněný na sedminu hodiny místní minimální mzdy, a skrze 웃, vyplácené pouze za ověřené hodiny. QIS měří příslib, ale nic nerazí — je to měřítko, nikdy platba. Každá platba dosahuje k účastníkovi prostřednictvím Livelihood Direct, licencovaných místních kanálů, které dohoda nikdy nedrží v úschově, postavených na principu Continuity Without Evasion.

S blahobytem se zachází jako s prvořadou infrastrukturou — ne jako s výhodou, ale jako se substrátem, na němž stojí všechno ostatní. Dohoda pojmenovává tři oblasti, v nichž je každý účastník podporován: Láska, tedy propojení a zdravá hranice; Ztráta, protože zármutek se musí procházet s někým, ne obcházet; a Bezpečí, tedy vědět, komu volat, v každém regionu, ve vlastním jazyce. Je poskytováno poradenství, skupinové kruhy a kulturní či duchovní praktiky ctěné podle vlastní tradice. Nulová vnucená ideologie; Human Authority, nikdy stroj, rozhoduje o tom, jakou péči občan potřebuje.

Dohoda měří úspěch podle svého nejzranitelnějšího účastníka, nikoli podle průměru. Venkovští občané bez vysoké přenosové rychlosti jsou obslouženi. Neurodivergentní účastníci dostávají přizpůsobení jako standard. Účastníci se zdravotním postižením shledávají každé zařízení přístupným. Genderově rozmanití účastníci dostávají bezpečné ubytování a spárování s mentorem. Mluvčí, jejichž mateřský jazyk není místním jazykem, nacházejí každý materiál ve svém jazyce. Původní obyvatelé nacházejí své kulturní praktiky ctěné a své tradiční poznání chráněné. Vůdci, kteří tuto dohodu podepisují, slibují, že žádný občan nebude zapomenut jen proto, aby průměry vypadaly dobře. To je důstojnost jako substrát, ne ozdoba. Co se měří, je to, co bude ctěno, a to, co je zde ctěno, je celý člověk — mysl, tělo a duch, držený spoluobčany, bez výjimky.`,
      999: `Atlantidská dohoda zachází s každým účastníkem jako s plnohodnotnou lidskou bytostí od prvního dne, zabudováno do mechanismu, nikoli pouze do slov. Stipendium je poskytováno od okamžiku, kdy účast začíná, vázané na životní náklady daného regionu tak, aby jeho dopad ctil místní důstojnost práce. Stipendium přichází dřív, než se rodinné závazky změní v nouzi, a dřív, než je narušena důstojnost. Signalizuje každému mladému člověku, že jeho čas má hodnotu, že se s jeho přínosem počítá a že stabilita jeho rodiny je součástí odpovědnosti dohody. Toto není charita. Toto je uznání skutečnosti, že obyčejná lidská inovace vyžaduje především lidské zajištění. Mysl nemůže vzkvétat, pokud je domácnost ohrožena. Samotný vstup nese malý, záměrný práh: Seed, jednorázové členství oceněné na sedminu hodiny místní minimální mzdy, nepřevoditelné a nenesoucí vlastní ekonomický nárok. Seed říká pouze to, že se osoba připojila; neplatí jí nic ani neslibuje nic nad rámec dveří, které otevírá.

Co se vydělá poté, co se tyto dveře otevřou, se řídí stejnou přesností, jakou dohoda přináší každému jinému slibu. 웃, měřítko Human Intelligence dohody, se počítá jednoduše — jedna hodina za místní minimální mzdu, násobená Multiple, který odráží náročnost a hodnotu úkolu, krát skutečně odpracované hodiny. Ale 웃 se vydává pouze za práci ověřenou v rámci vymezeného, rozpočtem schváleného úkolu. Před tímto schválením je to, co účastník dělá, plánování, nikoli výdělek — rozdíl, na němž dohoda pevně trvá, protože chrání jak pokladnu, tak účastníka před sliby učiněnými rychleji, než je hodnota ověřena. Measurement of Time, MoT, zaznamenává skutečně odpracované minuty odděleně od jakéhokoli výpočtu odměny, takže čas zůstává poctivým, prověřitelným faktem nezávislým na platbě. Hodiny žádného účastníka nejsou nadhodnoceny a hodiny žádného účastníka nemizí. Zúčtovací strop 9 999 웃 za rok platí pro každého účastníka, přičemž jakýkoli přebytek se převádí do dalšího roku, místo aby zmizel, takže výjimečný přínos je uznán napříč lety, místo aby byl v rámci jednoho roku omezen do neviditelnosti.

Odměňování je záměrně drženo odděleně od měření inovace. Qualified Innovation Score, QIS, zprůměrňuje Revenue, Gross Profit, Operating Income a Effective R&D spending, aby popsal, o kolik inovace skutečně vzrostla. Její růst v čase může, jakmile je splněna kvalifikace, určit velikost fondu odměn, ale samotné QIS nerazí žádné 웃 a nic přímo nevyrovnává — je to měřítko, nikdy platba, a nikdy se nezaměňuje za vlastnictví toho, co bylo vybudováno. Toto oddělení má význam, protože udržuje stipendium a mzdu poctivé: účastník je placen za ověřené hodiny skutečné práce, ne za skóre, které by se dalo obejít, nadhodnotit nebo o němž by se dalo dohadovat. ♡, Shared Intention, nese důvod za každým úkolem, který účastník přijme; ◬, ověřené zrychlení, které úkol přináší vůči zmrazené výchozí úrovni, je zaznamenáno pouze jako delta, nikdy vydávané za ukazatel zisku připsaný k práci kterékoli osoby. Odměňování zůstává tím, čím je: poctivou mzdou za poctivý, ověřený čas.

Hodnota se nezastavuje u výpočtu — musí také dosáhnout k účastníkovi jako k žijící osobě, a přesně to je práce 🏠, Livelihood Direct. Každá jednotka hodnoty, kterou účastník vydělá, k němu dosahuje prostřednictvím kvalifikovaných, licencovaných místních kanálů — bank, operátorů mobilních plateb, družstev již důvěryhodných a regulovaných v daném regionu — nikdy prostřednictvím fondu, který by dohoda sama držela v úschově nebo kontrolovala. Klasifikace statusu účastníka vždy předchází jakémukoli zúčtování; nic není vyplaceno dřív, než je řádně pochopeno, komu se platí a za co. A uznání talentu, jakkoli oslavované, samo o sobě neotevírá přístup k lůžku, jídlu ani místu v kohortě — to určuje pouze skutečná role účastníka. Toto je záměrné odmítnutí nechat prestiž nahradit zaopatření. Skvělý přispěvatel i tichý přispěvatel spí pod stejnou chráněnou střechou, za stejných podmínek, protože závazky dohody vůči důstojnosti nejsou cenou udělovanou za výjimečnost — jsou podlahou pod každým.

S blahobytem se zachází jako s prvořadou infrastrukturou — ne jako s volitelnou výhodou, ne jako s wellness benefitem, ale jako se substrátem, na němž stojí všechno ostatní. Dohoda pojmenovává tři základní oblasti, v nichž je každý účastník podporován: Láska, ve smyslu propojení, vztahu a zdravé hranice; Ztráta, protože každý účastník zažije zármutek a musí se s ním procházet, ne kolem něj; a Bezpečí, ve smyslu toho, že každý účastník ví, komu volat, v každém regionu, ve vlastním jazyce. Je poskytováno individuální poradenství, skupinové kruhy, somatické praktiky a kulturní či duchovní praktiky ctěné podle vlastní tradice účastníka. Nulová vnucená ideologie. Dohoda drží prostor s úctou; nešíří žádný systém víry. Human Authority řídí každé z těchto rozhodnutí — smysl, peníze a právo zůstávají uzavřené strojovému rozhodování, ať je rozpoznávání vzorů podporující rozhodující lidi jakkoli sofistikované.

Dohoda měří úspěch podle výsledku svého nejzranitelnějšího účastníka, nikoli podle průměru. Venkovští účastníci bez vysoké přenosové rychlosti jsou obslouženi. Neurodivergentní účastníci dostávají přizpůsobení jako standard. Účastníci se zdravotním postižením shledávají každé zařízení přístupným. Genderově rozmanití účastníci dostávají bezpečné ubytování a spárování s mentorem. Mluvčí, jejichž mateřský jazyk není místním jazykem, nacházejí každý materiál ve svém jazyce. Původní obyvatelé nacházejí své kulturní praktiky ctěné a své tradiční poznání chráněné. Vůdci, kteří tuto dohodu podepisují, slibují, že žádný účastník nebude tiše zapomenut jen proto, aby průměry vypadaly dobře.

Každá platební cesta zde popsaná — Seed, stipendium, 웃 vydělané za ověřenou práci, kanál Livelihood Direct, který je doručuje — je navržena pro Continuity Without Evasion. Žádná jediná banka, vláda ani místní operátor není nepostradatelný pro odměnu kteréhokoli účastníka; pokud je jeden licencovaný kanál v jedné jurisdikci uzavřen nepříznivým rozhodnutím, selže pouze tento jeden kanál, nikdy celý systém, a nikdy nárok účastníka na to, co mu bylo dlužno. To je důstojnost jako substrát, ne ozdoba. Co se měří, je to, co bude ctěno, a to, co je zde ctěno, je celý člověk — mysl, tělo a duch dohromady, poctivě placený, plně chráněný a nezapomenutý žádným účetnictvím, zcela bez výjimky.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Financování a správa`,
    content: {
      7: `Občané financují příští generaci přímo.`,
      33: `Atlantidská dohoda je dohoda mezi občany — financovat a držet ji může kdokoli. Žádný pomocný kanál, žádný zahraniční dobrodinec, žádné politické podmínky. Každý dolar vysledovatelný, vyúčtování zveřejňováno měsíčně, v každém jazyce.`,
      111: `Atlantidská dohoda je dohoda mezi občany světa — kterákoli osoba kdekoli může pomáhat ji vytvářet a držet, bez ohledu na to, co podepíše její vláda nebo kdo ji zaměstnává. Vlády, vzdělavatelé a inovátoři podepisují jako správci svých regionů; dohodu financují, sledují a přímo za ni nesou odpovědnost občané, z nichž každý přispívá malými dobrovolnými částkami každý měsíc, dost skromnými, aby si to mohl dovolit každý dospělý. Neexistuje žádný pomocný kanál, žádný zahraniční dobrodinec, žádná politická podmínka. Dohoda stojí nezávisle na mnohostranných institucích, které utvářely minulé století — nejde o politické prohlášení, ale o návrhové rozhodnutí. Každý dolar je vysledovatelný; každé vyúčtování je zveřejňováno měsíčně, v každém jazyce.`,
      333: `Atlantidská dohoda je dohoda mezi občany světa — kterákoli osoba kdekoli může pomáhat ji vytvářet a držet, bez ohledu na to, co podepíše její vláda nebo kdo ji zaměstnává. Financují ji občané, kterým slouží: obyvatelé zúčastněných regionů přispívají malými dobrovolnými částkami každý měsíc, dost skromnými, aby si to mohl dovolit každý dospělý, a dost výraznými, aby celkový součet udržel práci dohody v potřebném rozsahu. Když občan přímo financuje další generaci, tento občan přímo nese odpovědnost za dohodu. Neexistuje žádný pomocný kanál, žádný zahraniční dobrodinec, žádná politická podmínka. Duší dohody je občan, který přispívá jednou malou částkou každý měsíc a jehož účast to všechno umožňuje.

Vláda, Vzdělávání a Inovace podepisují jako správci svých regionů — tři vizionářské podpisy zavazující region hostit, chránit a učit — ale správcovství není vlastnictví. Dohoda je nezávislá na mnohostranných institucích, které utvářely minulé století — Severoatlantické alianci, Světové zdravotnické organizaci, Organizaci spojených národů, Mezinárodním měnovém fondu, Světové bance a každém národním kanálu zahraniční pomoci. Toto je návrhové rozhodnutí, ne politické prohlášení: rámec sloužící každému regionu bez ohledu na geopolitické spojenectví se nemůže zaplést s žádným jednotlivým spojenectvím. Národní vlády mohou přispívat dobrovolně. Příspěvky jsou transparentní. Žádný příspěvek nikdy nekupuje vliv na řízení dohody, ať pochází odkudkoli.

Každý dolar a každá jednotka hodnoty vstupující do dohody je zaznamenána trvale, veřejně a vysledovatelně — rekonstruovatelná prostřednictvím Replay, takže občan i za sto let může ověřit nepřerušený řetězec. Hodnota dosahuje k účastníkovi prostřednictvím ověřených hodin 웃 a licencovaných místních kanálů, nikdy skrze fond, který by dohoda sama držela v úschově; QIS měří poctivě, nikdy neplatí. Administrativní režie je omezena stropem, firemní dary jsou omezeny stropem vedle ní. Úplné vyúčtování je doručováno v jazyce každého signatářského regionu každý měsíc. Vůdci, kteří dohodu podepisují, slibují transparentnost, jakou málokdy nabízí kterákoli instituce. To je důvěra, kterou dohoda vyžaduje — vydobytá jeden malý vysledovatelný příspěvek za druhým, před zraky každého občana.`,
      999: `Atlantidská dohoda samotná je financována občany, kterým slouží, a tato jediná skutečnost utváří vše, co z ní vychází — každý kanál, každou účetní knihu, každou bránu, kterou musí mladý člověk projít, aby byl viděn. Obyčejní obyvatelé zúčastněných regionů přispívají malými dobrovolnými částkami každý měsíc, částkami dost skromnými, aby si účast mohl dovolit každý dospělý v kterémkoli hostitelském regionu, a dost výraznými, aby celkový součet udržel práci dohody ve smysluplném rozsahu. Tento návrh je záměrný a není náhodný vůči poslání — je důkazem tohoto poslání. Když občan přímo financuje vzdělávání další generace, tento občan v témže okamžiku přímo nese odpovědnost za dohodu, bez prostředníka, který by mohl vyúčtování zjemnit nebo oddálit zúčtování. Neexistuje žádný pomocný kanál, žádný zahraniční dobrodinec, žádná politická podmínka připojená k platbě. Duší dohody je občan, který přispívá jednou malou částkou každý měsíc, jehož účast umožňuje vše ostatní a jehož pokračující účast je jediným hlasem důvěry, na kterém v konečném důsledku napříč pěti stoletími záleží.

Dohoda je záměrně nezávislá na mnohostranných institucích, které utvářely minulé století — Severoatlantické alianci, Světové zdravotnické organizaci, Organizaci spojených národů, Mezinárodním měnovém fondu, Světové bance a každém národním kanálu zahraniční pomoci. Toto není politické prohlášení o hodnotě těchto institucí ani jejich přínosu. Je to návrhové rozhodnutí, a je to totéž návrhové rozhodnutí, které řídí každý technický kanál pod samotnou dohodou: Continuity Without Evasion. Pravidlem je zákonná přenositelnost — žádná jediná nepostradatelná vláda, banka, zakladatel ani model nesmí ležet pod celou stavbou, protože pětisetletý horizont nelze vsadit na trvalost jediného aktéra. Každá jurisdikce nese vlastní adaptér, bezpečně se uzavírající a ve výchozím stavu odmítající, takže nepříznivé rozhodnutí v jednom národě uzavře pouze tento jeden kanál a nic víc — nikdy nesrazí účty rodiny v regionu vzdáleném přes oceán. Národní vlády mohou přispívat dobrovolně. Příspěvky jsou transparentní. Žádný příspěvek nikdy nekupuje vliv na řízení dohody, ať pochází odkudkoli — ani od vlády, ani od korporace, ani od samotných zakladatelů rámce.

Human Authority je druhým nosným pilířem pod tímto návrhem financování. Smysl, peníze a právo zůstávají lidskými záležitostmi, rozhodovanými lidmi před zraky ostatních lidí; suverénní úroveň, kde se stanovuje účel dohody a řídí se její prostředky, zůstává uzavřená strojům, ať se v úlohách pod ní jakkoli zdokonalí. Measurement of Time zaznamenává skutečně odpracované minuty odděleně od jakéhokoli tvrzení o jejich hodnotě, takže nikdo — člověk ani stroj — nemůže záznam tiše nadhodnotit. Za každým z těchto záznamů stojí Replay, díky němuž je každé vydání, které dohoda kdy vydá, rekonstruovatelné od svého počátku, navždy otevřené k napadení, navždy otevřené k opravě. Občan, který dnes přispívá malou částkou, věří, že za padesát let, za dvě stě let bude ještě někdo moci projít řetězec zpět k účetní knize tohoto měsíce a najít ji přesně takovou, jaká byla.

Vstup do tohoto systému důvěry začíná se Seed — jednorázovým členstvím, oceněným na sedminu hodiny místní minimální mzdy, nepřevoditelným a nenesoucím žádný ekonomický nárok jakéhokoli druhu. Seed nekupuje žádný podíl, žádný hlas vážený majetkem, žádné výsadní postavení v účetnictví, které následuje. Kupuje pouze příslušnost, za cenu dost nízkou, aby mladý člověk kdekoli, kde dohoda působí, si mohl dovolit začít. Vše, co člen vydělá po tomto okamžiku, je vyděláno, nikdy zakoupeno, a tento rozdíl je celou morální architekturou dohody v malém.

Hodnota, která k člověku skutečně proudí, proudí prostřednictvím 🏠 Livelihood Direct — kvalifikovaných, licencovaných místních kanálů, které nesou platbu k dané osobě, nikdy do fondu, který by sám rámec držel v úschově nebo kontroloval. Klasifikace vždy předchází zúčtování; lůžko, stipendium, místo v další fázi výcviku je podmíněno rolí a připraveností, nikdy pouze uznáním, protože uznání je levné a živobytí ne. Toto je řetězec, kterým skutečně putuje měsíční příspěvek občana: z účtu občana, přes auditovaný kanál, do stipendia, které mladý člověk dostává, do inovačního projektu, jímž se práce tohoto mladého člověka stává, a zpět ven jako veřejný účet, který si může přečíst kterýkoli občan.

Hodnota této práce se měří, nikoli předpokládá. Qualified Innovation Score zprůměrňuje připravenost, růstový potenciál, dopad výsledku a připravenost k realizaci do jediného čísla a růst tohoto skóre určuje velikost fondu odměn teprve poté, co je splněna kvalifikace — samotné QIS nic nerazí a nic přímo nevyrovnává; je to měřítko, nikdy platba, a měření se zde nikdy nezaměňuje za vlastnictví. Platba za lidskou práci přichází místo toho jako 웃, oceněné jako jedna hodina krát místní minimální mzda, násobená vymezeným, rozpočtem schváleným násobkem skutečně odpracovaných a ověřených hodin. Dokud úkol nenese toto schválení, práce za ním je plánování, nikoli placená práce, a za plánování se neplatí nikomu. Strop 9 999 웃 za rok, s jakýmkoli přebytkem převáděným do dalšího roku místo mizení, brání tomu, aby se účet jediného roku stal buď neočekávaným ziskem, nebo pastí.

Nic z toho nepostupuje rychleji než vlastní důkaz. Dohoda sama postupuje z Manual přes Semi-Automated do Autonomous provozu jednu kostku po druhé, a to pouze tam, kde byl skutečně prokázán, nikdy předem předpokládán, celý řád měřeného zlepšení — jedna devítina. Autonomie se vydobývá přesně tam a nikde poblíž smyslu, peněz nebo práva, které zůstávají vždy lidské. Administrativní režie je omezena stropem. Firemní a institucionální dary jsou vítány a omezeny stropem vedle ní. Úplné vyúčtování je doručováno v jazyce každého signatářského regionu každý měsíc, počínaje Kambodžou, Hondurasem a Austinem, a má být doručováno a čitelné i za pět set let. To je důvěra, kterou dohoda vyžaduje. To je důvěra, kterou si dohoda vydobývá, jeden malý vysledovatelný příspěvek za druhým, před zraky každého občana, kterému bude kdy sloužit.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Mezikulturní výměna a globální přínos`,
    content: {
      7: `Každý student ve svém vlastním jazyce.`,
      33: `Každá aktivita v jazyce účastníka — otevřená kterémukoli občanovi, bez potřeby svolení vlády. Umělá, Lidská a Sdílená inteligence drženy v produktivním napětí. Osnovy zveřejňovány otevřeně. Co se naučí jeden region, zdědí všichni.`,
      111: `Atlantidská dohoda vrací vzdělávání k jeho nejhlubšímu účelu: výměně moudrosti napříč hranicemi, které by jinak rozdělovaly. Do těchto osnov může vstoupit kterýkoli občan, bez ohledu na to, co podepsala jeho vláda. Každá aktivita je dostupná v jazyce účastníka, v jazyce hostitelského regionu a ve sdíleném záznamu. Jazyk není ozdoba — jazyk je jurisdikce, jazyk je důstojnost učiněná čitelnou. Vzdělávací rámec spočívá na trojici inteligencí: Umělá navrhuje, Lidská rozhoduje, Sdílený záměr ověřuje. Každý student se učí držet všechny tři v napětí. Co se dohoda naučí, to vrací zpět. Osnovy, výsledky inovace, výzkum blahobytu a rozhodnutí o řízení jsou zveřejňovány otevřeně. Co se naučí jeden region, zdědí všichni občané.`,
      333: `Atlantidská dohoda vrací vzdělávání k jeho nejhlubšímu účelu: výměně moudrosti napříč hranicemi, které by jinak rozdělovaly. Toto je dohoda mezi občany světa — kterýkoli občan ji může budovat a držet, ať jeho vláda podepsala cokoli. Každá aktivita je dostupná v jazyce účastníka, v jazyce hostitelského regionu a ve sdíleném záznamu, takže žádný účastník se dohodou neprobírá v jazyce, který si nezvolil. Jazyk není ozdoba. Jazyk je jurisdikce. Jazyk je důstojnost učiněná čitelnou. Mladý člověk v Kambodži čte svůj záznam o stipendiu v khmerštině, v Hondurasu ve španělštině, v Austinu v angličtině — všechny tři ctěny stejně, žádný z nich nepotřebuje ke svému začátku požehnání vlády.

Vzdělávací rámec spočívá na trojici inteligencí, kterou Vision 2525 činí viditelnou. Umělá inteligence navrhuje vzorce a možnosti rychleji, než by dokázal kterýkoli člověk sám. Lidská inteligence rozhoduje o bezpečnosti, etice a směřování — otázkách, na které by neměl odpovídat žádný stroj, ponechaných pod Human Authority. Sdílený záměr ověřuje, že rozhodnutí slouží zásadám dohody, aby žádný účastník nevolil výjimečnost na úkor společného dobra. Žádný student se nespoléhá pouze na jednu inteligenci; každý student se učí držet všechny tři v napětí. Příslušnost začíná se Seed, členstvím oceněným na sedminu hodiny místní minimální mzdy — dost malým, aby si jej mohl dovolit kterýkoli občan. To připravuje další generaci na řízení, v němž žádná inteligence nejedná bez kontroly.

Co se dohoda naučí, to vrací zpět. Osnovy se zveřejňují pod otevřenou licencí, aby si je kterýkoli region — signatářský či nikoli — mohl přizpůsobit místní kultuře. Výsledky inovace se zveřejňují. Výzkum blahobytu se zveřejňuje v souhrnné podobě pro výzkumníky kdekoli. Rozhodnutí o řízení se zveřejňují včetně odůvodnění, aby je mohl ověřit kterýkoli občan, nejen podepisující vláda — a Replay umožňuje témuž občanovi zpětně vysledovat toto odůvodnění i za sto let. Úspěch se neměří jen podle jejích účastníků, ale podle vzdělávacích a kulturních iniciativ, které v jejím důsledku vznikají, v regionech, jež nikdy nepodepsaly pilotní projekt, přesto však stavěly na jeho sdílené moudrosti. Co se naučí jeden region, zdědí každý občan.`,
      999: `Atlantidská dohoda vrací vzdělávání k jeho nejhlubšímu účelu: výměně moudrosti napříč hranicemi, které by jinak rozdělovaly, a tuto výměnu zahajuje dřív, než je odučena jediná lekce. Prvním úkonem každého účastníka uvnitř rámce je Seed — jednorázové členství oceněné na sedminu hodiny místní minimální mzdy, nepřevoditelné, nenesoucí žádný ekonomický nárok jakéhokoli druhu. Je dost malé, aby z něj nebyla vyloučena žádná rodina, a dost skutečné, aby žádný účastník nevstupoval jako pouhý divák. Toto je první lekce dohody: příslušnost se vydělává levně, ale přesto se vydělává a nepřiznává žádné vlastnictví toho, co následuje. Každá další aktivita dohody je dostupná v jazyce účastníka, v jazyce hostitelského regionu a ve sdíleném záznamu, takže žádný účastník se dohodou neprobírá v jazyce, který si nezvolil. Jazyk není ozdoba. Jazyk je jurisdikce. Jazyk je důstojnost učiněná čitelnou. Když mladý člověk z kambodžské vesnice čte svůj záznam o stipendiu v khmerštině, z honduraského města ve španělštině a ze čtvrti v Austinu v angličtině, všechny tři jsou ctěny stejně toutéž dohodou, v týchž zakládajících regionech, které se poprvé domluvily učit se navzájem.

Vzdělávací rámec dohody spočívá na trojici inteligencí, kterou Vision 2525 činí viditelnou, a osnovy učí každou z nich jako něco, co si účastník může osahat vlastníma rukama, ne jako abstrakci. ♡, Shared Intention, nese důvod — nit, kterou se každý student učí držet dřív, než se dotkne jakéhokoli nástroje, otázku, zda tato práce stále slouží lidem, kterým má sloužit. ◬, ověřené zrychlení, se učí jako delta a nic víc — měřená pouze vůči zmrazené výchozí úrovni, nikdy vydávaná za ukazatel zisku, nikdy nárokovaná jako osobní úspěch odděleně od okolního týmu. 웃, Human Intelligence ctěná v čase, se učí nejpečlivěji: jedna hodina ověřené práce se rovná jedné hodině za místní minimální mzdu, a to, co účastník vydělá, je tato mzda násobená odpracovanými hodinami — Multiple krát Time, nic skryto ve výpočtu. Studenti se brzy učí, že 웃 se vydává pouze za práci ověřenou v rámci vymezeného, rozpočtem schváleného úkolu. Před tímto schválením je stejné úsilí pouhým plánováním — cenným, ale nezaplaceným, a každý účastník je učen tento rozdíl rozpoznat na první pohled.

Protože tento rozdíl lze snadno rozostřit, osnovy učí QIS, Qualified Innovation Score, jako zrcadlo, nikoli jako ukazatel skóre. QIS je průměr čtyř finančních absolutních veličin — Revenue, Gross Profit, Operating Income a Effective R&D — děleno čtyřmi, a každý student se učí je počítat, zpochybňovat a nikdy si je neplést s penězi. Růst QIS určuje velikost fondu odměn teprve poté, co je kvalifikace nezávisle potvrzena, a tento růst sám o sobě nerazí žádné 웃. QIS je měřítko. QIS není nikdy platba. QIS není nikdy vlastnictví. Studenta, který si tento rozdíl osvojil, nelze přesvědčit, že vysoké skóre mu dává nárok, jaký dohoda nikdy neslíbila.

Osnovy rozšiřují tuto gramotnost i na to, jak hodnota skutečně dosahuje k člověku, prostřednictvím toho, čemu dohoda říká Livelihood Direct — zásada 🏠, podle níž peníze proudí skrze kvalifikované, licencované místní kanály a nikdy skrze fond, který by rámec sám držel v úschově. Studenti se učí vysledovat své stipendium a později vlastní výdělky skrze tyto kanály jako občanské cvičení, ne jako finanční záhadu odehrávající se kdesi jinde jejich jménem. Učí se, že klasifikace vždy předchází zúčtování a že uznání — vysoké QIS, veřejné ocenění — samo o sobě neotevírá přístup k lůžku, stipendiu ani místu v rotaci. To určuje role. Toto je ochrana proti velmi starému selhání: záměně chvály za zaopatření.

Vedle finanční gramotnosti stojí občanská gramotnost, vyučovaná skrze Continuity Without Evasion. Každý účastník se učí, že dohoda je postavena na zákonné přenositelnosti — že žádná jediná nepostradatelná vláda, banka, zakladatel ani model nestojí mezi ním a sliby rámce. Učí se, co v tomto návrhu způsobí nepříznivé rozhodnutí: bezpečně uzavře jeden kanál, v jedné jurisdikci, podle výchozího odmítajícího nastavení daného adaptéru, a nikdy nesrazí celek. S tím je spojena nejhlubší lekce, kterou dohoda učí: Human Authority drží smysl, peníze a právo a suverénní úroveň, na níž se tato rozhodnutí činí, zůstává trvale uzavřená strojům. Measurement of Time, MoT, zaznamenává skutečné minuty každého účastníka odděleně od jakéhokoli skóre a Replay činí každé vydání, které dohoda vydá, plně rekonstruovatelným — takže student, který chce vědět, proč bylo rozhodnutí učiněno, může jej i po letech sám zpětně vysledovat, místo aby jen věřil něčímu slovu.

Tato struktura vydobyté důvěry se stává pedagogickým modelem dohody, nejen jejím modelem řízení. Každý účastník postupuje skrze režimy Manual, Semi-Automated a Autonomous se stále větší volností, podmíněné stejným prahem měřeného zlepšení, který podmiňuje i samotnou technologii — ověřeným přírůstkem jedenácti a jedné devítiny procenta, než se otevře další režim. Autonomie, když je vydobyta, je vydobyta úzce a po jednotlivých oblastech, nikdy nad smyslem, penězi nebo právem. Student, který tímto postupem prošel, chápe zcela na vlastní kůži, proč suverénní úroveň nesmí být nikdy automatizována pryč — protože si vlastní autonomii vydobyl jeden měřený krok po druhém a přesně ví, co tato autonomie zahrnovala a co ne.

Co se dohoda naučí, to dohoda vrací zpět. Osnovy se zveřejňují pod otevřenou licencí, aby si je kterýkoli region — signatářský či nikoli — mohl přizpůsobit místní kultuře a pedagogické tradici. Výsledky inovace se zveřejňují. Výzkum blahobytu se zveřejňuje v souhrnné podobě pro výzkumníky kdekoli. Rozhodnutí o řízení se zveřejňují s neporušeným plným odůvodněním. Úspěch dohody se neměří jen podle jejích vlastních účastníků v Kambodži, Hondurasu a Austinu, ale podle iniciativ, které v jejím důsledku vznikají, v regionech, jež nikdy nepodepsaly zakládající pilotní projekt, přesto však stavěly na jeho otevřeně sdílené moudrosti, napříč horizontem, jehož dokončení se zakladatelé nedožijí. Co se naučí jeden region, zdědí všechny ostatní regiony — a co je této generaci poctivě odučeno, to nebude muset dalších pět set let odnaučovat.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Udržitelný růst sítě`,
    content: {
      7: `Nikdy rychleji, než může cestovat důstojnost.`,
      33: `Tři zakládající regiony dokončí jeden pilotní cyklus, než se připojí čtvrtý — budovat ji může kterýkoli občan. Záznamy zakotvené tak, aby přetrvaly pět století. Signatáři si zachovávají suverenitu; pro dalšího připojujícího se nic není oslabeno.`,
      111: `Atlantidská dohoda neporoste rychleji, než dokáže ctít vlastní kvalitu. Tři zakládající regiony musí dokončit celý pilotní cyklus, s každým účastníkem ctěným a každou zásadou ověřenou, než se připojí čtvrtý region. To je zásada, která se konečně stala fungující disciplínou. Ale dohoda je dohoda mezi občany světa — kterákoli osoba kdekoli ji může budovat a držet, jeden Seed od ní, bez ohledu na to, co podepíše vláda nebo dovolí zaměstnavatel. Horizont dohody je pět století. Její záznamy jsou zakotveny prostřednictvím Replay, takže občan, který si je přečte i za sto let, může věřit tomuto odůvodnění. Každý signatář si zachovává suverenitu; pro dalšího připojujícího se nic není oslabeno.`,
      333: `Atlantidská dohoda neporoste rychleji, než dokáže ctít vlastní kvalitu. Každé rozšíření je slibem účastníkům, kteří jsou uvnitř již nyní — že zakládající standard nebude rozředěn rozsahem. Tři zakládající regiony musí dokončit celý pilotní cyklus, s každým účastníkem ctěným a každou zásadou ověřenou, než se připojí čtvrtý region. To je zásada, která se konečně stala fungující disciplínou. A dveře nikdy nebyly jen regionální: toto je dohoda mezi občany světa a kterákoli osoba ji může budovat, financovat a nést za ni odpovědnost — bez potřeby svolení vlády nebo požehnání zaměstnavatele. Vůdci, kteří podepisují pilotní projekt, slibují signatářům tentýž substrát, ochranu a důstojnost, jaké se dostalo zakládající kohortě. Pro dalšího se nic neoslabuje.

Horizont dohody je záměrně dlouhý — navržený tak, aby přetrval patnáct až dvacet lidských generací, pět století od zakládajícího dne. Její záznamy jsou zakotveny prostřednictvím Replay, takže občan, který si je přečte i za sto let, může toto odůvodnění ověřit, ne mu jen věřit. Její souřadnicový rámec, její role Human Authority a její mezigenerační cykly řízení jsou vybudovány tak, aby přežily přechod od kterékoli jednotlivé technologie. Dohoda přežije každého člověka, který podepíše její zakládající pilotní projekt, i každého občana, který zasadí Seed a měsíčně ji financuje. To je její slib dítěti, které podepisuje smlouvu o stipendiu, občanovi, který se připojil bez potřeby svolení vlády, vnoučatům tohoto dítěte, která mohou dohodu řídit v polovině století, a každé generaci, jež zdědí to, co zakladatelé — oficiální i občanští — budují právě teď.

Každý signatář si zachovává svobodu odstoupit, plnou suverenitu a pravomoc nad vlastními občany, s právem pozměňovat a utvářet vývoj dohody. Každý občan si zachovává stejné postavení zakládat, financovat, sledovat a nést za ni odpovědnost — s podpisem vlády nebo bez něj. Co nesmí nikdo, je narušit zakládající zásady, protože tento slib musí přežít každý odchod. Vůdci i občané společně podepisují další století dohody do horizontu, který zdědí a dokončí jejich vnoučata.`,
      999: `Atlantidská dohoda neporoste rychleji, než dokáže ctít vlastní kvalitu, a tato zdrženlivost není sentiment — je to inženýrství, zapsané do téže disciplíny měření, která řídí každý slib dohody. Tři zakládající regiony, Kambodža, Honduras a Austin, musí dokončit celý pilotní cyklus, s každým účastníkem ctěným a každou zásadou ověřenou, než se připojí čtvrtý region. Růst, který předběhne ověření, není růst; je to vystavení riziku v přestrojení za ambici. Zakládající pilotní projekt existuje proto, aby dohoda mohla prokázat, v rozsahu dost malém na to, aby jej bylo možné prověřit, a dost velkém na to, aby na tom záleželo, že její sliby přežijí střet se skutečností dřív, než budou tyto sliby rozšířeny do světa sledujícího zvenčí jejích tří hranic. Čtvrtý region zatím nemá jméno a nebude jej mít, dokud první tři nebudou stát za každým tvrzením tohoto dokumentu.

Co prokazuje připravenost k růstu, není nadšení, ale číslo, které dohoda dokáže veřejně obhájit. Qualified Innovation Score — QIS, počítané jako Revenue plus Gross Profit plus Operating Income plus Effective R&D spending, děleno čtyřmi — je nástroj, který dohoda používá k tomu, aby zjistila, zda se region, kohorta nebo kostka skutečně zlepšily, a ne že se tak pouze zdálo. Růst QIS určuje velikost fondu odměn teprve poté, co je splněna kvalifikace, nikdy dřív, a samotné QIS nerazí žádné 웃 ani nekupuje žádné vlastnictví. QIS je měřítko, ne platba; měřítko, ne podíl; zrcadlo, které dohoda staví před vlastní práci, nikdy měna, kterou utrácí. Region navrhující rozšíření sítě musí ukázat své QIS poctivě, před zraky regionů, které mu předcházely, jinak se nerozšíří.

Udržitelný růst znamená růst, který si vlastní autoritu vydobývá jeden přírůstek po druhém. Každá kostka a každý region začíná v režimu Manual, kde o všem rozhodují lidé a systém pouze asistuje. Postup do Semi-Automated a nakonec Autonomous provozu v rámci dané kostky je podmíněn jediným prahem platným napříč celou dohodou — ověřeným, reprodukovatelným měřeným zlepšením jedenácti a jedné devítiny procenta, jedné devítiny, než je udělen další stupeň autonomie. Autonomie se vydobývá kostku po kostce, nikdy se nenárokuje paušálně ani se nerozšiřuje nad oblasti, které musí zůstat lidské, ať se systém jakkoli zdokonalí: smysl, peníze a právo zůstávají uzavřené strojům bez ohledu na to, kolik prahů bylo splněno jinde. Síť, která rozšiřuje svou automatizaci rychleji, než rozšiřuje své důkazy, se nemodernizuje. Hazarduje s důvěrou, kterou si dosud nevydobyla.

Odměňování se se sítí škáluje stejně jako autorita — záměrně a se stropem, který chrání celý systém před jeho vlastním úspěchem. 웃, token Human Intelligence, se rovná jedné hodině ověřené práce násobené místní minimální mzdou; to, co kterýkoli účastník vydělá, je tento Multiple krát odpracované hodiny, a vydává se pouze za práci vykonanou v rámci vymezeného, rozpočtem schváleného úkolu. Před schválením je i sebelepší plán pouhým plánováním a samotné plánování nic nerazí. Zúčtování každého účastníka je omezeno stropem 9 999 웃 za rok, přičemž jakýkoli přebytek se převádí do dalšího roku, místo aby mizel nebo narušoval fond. Jak se připojují nové regiony a aktivita sítě se násobí, právě tento strop brání tomu, aby se růst změnil v inflaci — hodnota zůstává ukotvena ve skutečných, ověřených, místních hodinách bez ohledu na to, jak velká se dohoda stane.

Za každým 웃 stojí důvod, který žádná účetní kniha nedokáže vypočítat sama. ♡, Shared Intention, tento důvod nese vpřed skrze každé rozhodnutí o rozšíření, které dohoda učiní, zatímco ◬, přínos umělé inteligence, se počítá jako ověřené zrychlení měřené vůči zmrazené výchozí úrovni — delta, a nikdy, za žádných okolností, ukazatel zisku optimalizovaný pro sebe sama. Vstup do této sítě začíná pro každého účastníka stejně, bez ohledu na to, do kterého regionu nebo v kterém desetiletí se připojí: se Seed, jednorázovým členstvím oceněným na sedminu hodiny místní minimální mzdy, nepřevoditelným a nenesoucím žádný ekonomický nárok jakéhokoli druhu. Seed říká pouze to, že osoba dorazila. Vše, co poté vybuduje, buduje před zraky tří dalších měn dohody, nikdy skrze samotný Seed.

Skutečný růst musí být také růstem, který dosahuje ke skutečnému člověku, ne k fondu, který rámec drží jménem někoho jiného. 🏠 Livelihood Direct vyžaduje, aby hodnota putovala k účastníkovi pouze prostřednictvím kvalifikovaných, licencovaných místních kanálů, které dohoda prověřila region po regionu, a nikdy prostřednictvím úschovy, kterou by si sám rámec ponechával. Klasifikace vždy předchází zúčtování, takže žádná hodnota se nepřesune, dokud nejsou nade vši pochybnost stanoveny její účel i příjemce. A protože uznání není totéž co přístup, lůžko, místo v rotaci, místo u stolu je podmíněno rolí a připraveností, nikdy skóre nebo postavením účastníka. Jak se síť rozšiřuje do čtvrtého regionu a dál, každé nové území musí nejprve kvalifikovat vlastní licencované kanály, než k jeho lidem může dosáhnout Livelihood Direct — rozšíření důvěry, ne pouhé rozšíření území.

Nic z toho nepřetrvá bez sítě vybudované tak, aby přežila vlastní úspěch, a proto Continuity Without Evasion řídí každý region, který se k dohodě kdy připojí. Zákonná přenositelnost je povinná; žádná jediná vláda, banka, zakladatel ani model se nesmí stát nepostradatelným pro celek. Každá jurisdikce provozuje vlastní adaptér, bezpečně se uzavírající a ve výchozím stavu odmítající, takže nepříznivé rozhodnutí kdekoli uzavře jeden kanál, nikdy celou dohodu. Human Authority drží smysl, peníze a právo v každém rozsahu, jehož síť dosáhne, uzamčené proti pronikání strojů návrhem, nikoli pouhým slibem. Measurement of Time zaznamenává každou skutečnou minutu odděleně od každého tvrzení o ní a Replay zajišťuje, že jakékoli vydání, v kterémkoli regionu, v kterémkoli okamžiku napříč pěti stoletími, může kdokoli, kdo se zeptá, rekonstruovat a znovu prozkoumat. Síti, kterou nelze přehrát skrze Replay, nelze věřit, ať se k ní připojilo jakkoli mnoho regionů nebo ať se její růst zvenčí zdá jakkoli působivý. Takto Vision 2525 roste, aniž by kdy přerostla důvěru, k jejímuž udržení byla vybudována — jeden ověřený region, jedno poctivé QIS, jedna ověřená hodina za druhou.`,
    },
  },
];
