import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_CS: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Kde začíná inovace`,
    content: {
      7: `Vůdci začínají, co žádné století nezačalo.`,
      33: `Tři regiony — Kambodža, Honduras, Austin — slibují přijmout mladé studenty, chránit je a předat jim nástroje budoucnosti. Vláda, Vzdělávání, Inovace: tři vizionářské podpisy za region. Jeden společný začátek.`,
      111: `Atlantské dohody jsou slibem vůdců ochotných začít něco, co dosud neexistovalo. Jejich zakladatelští signatáři v Kambodži, Hondurasu a Austinu v Texasu byli vybráni pro jednu vzácnou vlastnost: ochotu svěřit mladým nástroje budoucnosti, dokud je ještě čas je jim naučit. Podpis dohody zavazuje region přijmout studenty napříč kulturami, přispět tím, co jen on může nabídnout jedinečně, a držet se standardu vyššího, než jaký vyžaduje současná regulace. Tři vizionářské podpisy — Vláda, Vzdělávání, Inovace — vstupují do dohody společně. Tři vizionáři, tři regiony, jeden společný začátek.`,
      333: `Každá civilizace je připomínána podle toho, co se rozhodla začít. Atlantské dohody jsou slibem vůdců ochotných začít něco, co dosud neexistovalo — společný základ pro obyčejnou lidskou inovaci, který dosahuje do každého koutu světa, ctí každý hlas a přetrvává napříč generacemi. Jejich zakladatelští signatáři v Kambodži, Hondurasu a Austinu v Texasu nebyli vybráni pro hospodářskou moc, vojenskou sílu ani institucionální prestiž. Byli vybráni pro vzácnější vlastnost: ochotu svěřit mladým nástroje budoucnosti. To je smysl vůdcovství v nadcházejícím století — odvaha předat klíče příští generaci, dokud je ještě čas naučit ji řídit.\n\nDohodu svolává eXeL, organizující síla úmyslně vybudovaná pro tento okamžik. eXeL existuje záměrně mimo tradiční koordinační kanály, které utvářely minulé století — mimo struktury diplomatických smluv, mimo mnohostranné byrokracie, mimo politická spletení jakéhokoli jednotlivého národního státu. eXeL je důvěryhodný svolavatel, který sdružuje vizionářské vůdce kolem sdíleného rámce, sdíleného setrvačníku a sdíleného pětisetletého horizontu. Každý signatář si zachovává plnou suverenitu, plnou pravomoc nad svými vlastními občany a plnou svobodu kdykoli odstoupit. Co signatáři získávají, je síťový efekt, jaký může poskytnout jen účelově vybudovaný rámec. Toto je koordinace bez jakékoli formy politické nadvlády.\n\nPodepsat dohodu znamená podepsat slib. Že region přijme mladé studenty napříč kulturami. Že region přispěje tím, co jen on může nabídnout jedinečně. Že se region bude držet standardu vyššího, než jaký vyžaduje současná regulace. Že to region učiní veřejně, transparentně, na očích každého občana, jemuž slouží. Od každého regionu se vyžadují tři podpisy — Vláda, Vzdělávání a Inovace. Žádný jednotlivý úřad neváže dohodu sám. K vyslovení souhlasu jsou zapotřebí tři vizionáři. Tři vizionáři, tři regiony, jeden začátek — tak jakýkoli rámec vstupuje do života skrze vzájemnou důvěru vůdců ochotných jej podpisem uvést v život.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Učení skrze simulaci`,
    content: {
      7: `Tisíckrát cvičit, než se dotkneš.`,
      33: `Nic závažného se neučí nejprve na živém vybavení. Každý účastník cvičí v simulaci, rotuje mezi třemi regiony a slaví veřejně. To je úcta k mladému člověku, jehož první chyba by nikdy neměla stát život.`,
      111: `Každý obor hodný mistrovství se někdo naučil dřív, než byl znám. Atlantské dohody vracejí tuto starobylou moudrost do středu toho, jak jsou mladí připravováni budovat budoucnost. Nic závažného se neučí nejprve na živém vybavení, na skutečných lidech nebo v nevratných podmínkách. Každý účastník cvičí v simulaci, dokud se cvik nestane dovedností a dovednost připraveností. Rotační model provádí každého účastníka třemi zakladatelskými regiony a každá rotace končí veřejnou a společnou oslavou otevřenou širší hostitelské komunitě. To je úcta k mladému člověku, jehož první chyba by nikdy neměla stát život.`,
      333: `Každý obor hodný mistrovství se někdo naučil dřív, než byl znám. Mistři řemeslníci zkoušejí před vystoupením, piloti zkoušejí před letem, lékaři zkoušejí před operací a děti zkoušejí svět skrze hru. Atlantské dohody vracejí tuto starobylou moudrost do středu toho, jak jsou mladí připravováni budovat budoucnost. Nic závažného se neučí nejprve na živém vybavení, na skutečných lidech nebo v nevratných podmínkách. Každý účastník cvičí v simulaci, dokud se cvik nestane dovedností a dovednost připraveností. Toto není opatrnost — je to úcta k mladému člověku, jehož první chyba by nikdy neměla nikoho stát život.\n\nRotační model dohody provádí každého účastníka třemi zakladatelskými regiony. Co se naučí v Kambodži, se zdokonalí v Hondurasu a dokončí v Austinu. Co se objeví v Austinu, je zpochybněno v Kambodži a integrováno v Hondurasu. Každý účastník žije, učí se a je veden mentory napříč kulturami, které by jinak zůstaly vzdálené. Učební plán čerpá z tradic disciplinované simulace z mnoha kultur — z tradice strategického vzdělávání Sun-c', z Musašiho praxe skrze hru, z cyklické teorie učení Ibn Chaldúna, z klášterní dialektiky Nálandy, z civilního leteckého simulátoru — sjednocených tak, aby ctily každé kognitivní stadium a každé kulturní dědictví. Žádná jediná tradice nedominuje.\n\nKaždá rotace končí veřejnou a společnou oslavou otevřenou širší hostitelské komunitě. Sousedé, rodiny a zvědaví návštěvníci se scházejí, aby viděli, co se skupina naučila. Tyto události činí sofistikovanou technologii přístupnou a oslavovanou, nikoli obávanou. Společnost, která vyrůstá s porozuměním kooperativním systémům skrze hru, nemůže být snadno manipulována strachem z těchto systémů. To je odstrašení skrze vzdělávání, nikoli odstrašení skrze sílu. Slib dohody každému rodiči: vaše dítě bude tisíckrát cvičit v bezpečí, než se dotkne čehokoli, co by mu mohlo ublížit, a komunita bude svědkem jeho růstu na každém kroku cesty. Tak vypadá úcta k mladému člověku, když je zabudována do rámce, a to je to, co vůdcovství předává příští generaci účastníků dřív, než si to ta generace musí vynutit.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Bezpečnost ověřena dříve, než je poskytnuta důvěra`,
    content: {
      7: `Bezpečnost prokázána nejdřív, pak důvěra.`,
      33: `Každé zařízení a každá rotace se nachází uvnitř ochranného obalu s včasným varováním. Hardware odmítá ozbrojení. Záznamy přežívají turbulence. Bezpečnost je navržena kolem nejmladšího účastníka každý den, nikoli pouze slibována.`,
      111: `Než je poskytnuta důvěra, musí být prokázána bezpečnost. Atlantské dohody z toho činí svůj zakladatelský závazek. Každé zařízení dohody, každá trasa rotace, každé místo, kde mladý účastník spí nebo studuje, se nachází uvnitř zdokumentovaného ochranného obalu se schopností včasného varování, jež komunitě dává hodiny, nikoli minuty, aby reagovala na jakékoli věrohodné riziko. Každé zařízení, každý senzor, každý koordinační systém je na úrovni hardwaru vázán tak, aby odmítl přeúčelování k integraci se zbraňovými systémy. To není politika — to je fyzika. Dohoda je navržena tak, aby zůstala čestná i skrze turbulence: politickou nestabilitu, útlum financování, kybernetický útok nebo narušení cestování. S každým scénářem se počítá a každý plán klade lidskou důstojnost jako své první konstrukční omezení.`,
      333: `Než je poskytnuta důvěra, musí být prokázána bezpečnost. Atlantské dohody z toho činí svůj zakladatelský závazek. Každé zařízení dohody, každá trasa rotace, každé místo, kde mladý účastník spí nebo studuje, se nachází uvnitř zdokumentovaného ochranného obalu se schopností včasného varování, jež komunitě dává hodiny, nikoli minuty, aby reagovala na jakékoli věrohodné riziko. Technologie používaná k ochraně účastníků je tatáž technologie, kterou je dohoda učí budovat — senzory, koordinace, přežití komunikací, distribuovaná inteligence. Mladí lidé se učí bezpečnosti zevnitř ven, ve svém vlastním jazyce a ve svém vlastním regionu, ne tím, že se jim řekne, že jsou v bezpečí, ale tím, že vidí, jak je bezpečnost kolem nich každý den navrhována.\n\nDohoda dává neporušitelný slib o tom, čím se její technologie nemůže stát. Každé zařízení, každý senzor, každý koordinační systém je na úrovni hardwaru vázán tak, aby odmítl přeúčelování k integraci se zbraňovými systémy. To není jazyk politiky. To není aspirace. To je fyzická nemožnost, vynucená kryptograficky, ověřená každým signatářským regionem a kontrolovatelná každým občanem. Nástroje, které chrání dítě v Phnompenhu, nemohou být přeúčelovány k ublížení dítěti v Austinu. Nástroje, které koordinují rojové cvičení v Tegucigalpě, nemohou být rekonfigurovány k zaměření na člověka kdekoli. To je odpověď dohody na století strachu z dvojího užití. Ne politika — fyzika.\n\nDohoda je navržena tak, aby zůstala čestná i skrze turbulence. Pokud signatářský region ztratí politickou stabilitu, účastníky přijmou zbývající regiony. Pokud se financování zmenší, stipendia účastníků jsou chráněna jako první, dříve než administrativa a infrastruktura. Pokud jsou napadeny digitální záznamy, offline zálohy přetrvávají. Pokud se cestování stane nemožným, substrát pokračuje virtuálně. S každým scénářem se počítá a každý plán klade lidskou důstojnost jako své první konstrukční omezení. Vůdci, kteří podepisují tuto dohodu, podepisují slib, že bezpečnost je navržena, nikoli předpokládána. Co poskytují svým občanům, není pouhá příležitost, ale ochrana vybudovaná na standardu, který si nejmladší účastník zaslouží — tatáž ochrana, jakou by každý vůdce vyžadoval pro své vlastní dítě přecházející samo neznámou hranici.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Odměna, blaho a lidská důstojnost`,
    content: {
      7: `Stipendium, mentor, domov.`,
      33: `Každý účastník dostává životní stipendium od prvního dne. Láska, ztráta a bezpečí jsou brány jako prvořadá infrastruktura. Úspěch se měří nejzranitelnějším účastníkem, nikdy průměrem. Důstojnost je substrát, nikdy dekorace.`,
      111: `Atlantské dohody zacházejí s každým účastníkem jako s plnohodnotnou lidskou bytostí od prvního dne. Stipendium je poskytováno od okamžiku, kdy účast začíná, indexováno k životním nákladům regionu, aby jeho dopad ctil místní důstojnost práce. Blaho je bráno jako prvořadá infrastruktura — nikoli volitelná výhoda, nikoli benefit, ale substrát, na němž vše ostatní stojí. Podporovány jsou tři základní oblasti: Láska, Ztráta a Bezpečí. Dohoda měří úspěch výsledkem svého nejzranitelnějšího účastníka, nikoli průměrem. Žádný účastník nebude potichu zapomenut, aby průměry vypadaly dobře. Důstojnost jako substrát, nikoli dekorace.`,
      333: `Atlantské dohody zacházejí s každým účastníkem jako s plnohodnotnou lidskou bytostí od prvního dne. Stipendium je poskytováno od okamžiku, kdy účast začíná, indexováno k životním nákladům regionu, aby jeho dopad ctil místní důstojnost práce. Stipendium přichází dříve, než se rodinné povinnosti stanou nouzí, a dříve, než je narušena důstojnost. Signalizuje každému mladému člověku, že jeho čas je cenný, jeho přínos je očekáván a stabilita jeho rodiny je součástí odpovědnosti dohody. Toto není dobročinnost. Je to uznání, že obyčejná lidská inovace vyžaduje nejprve obyčejné lidské bezpečí. Mysl nemůže vzkvétat, dokud je její domácnost ohrožena.\n\nBlaho je bráno jako prvořadá infrastruktura — nikoli volitelná výhoda, nikoli benefit, ale substrát, na němž vše ostatní stojí. Dohoda pojmenovává tři základní oblasti, jimiž je každý účastník podporován: Láska ve smyslu spojení, přimknutí a zdravé hranice; Ztráta, neboť každý účastník zažije zármutek a musí být provázen, ne obcházen; a Bezpečí ve smyslu, že každý účastník ví, na koho se obrátit, v každém regionu, ve svém vlastním jazyce. Individuální poradenství, skupinové kruhy, somatické praxe a kulturní či duchovní praxe ctěné podle vlastní tradice účastníka jsou vše poskytovány. Nulová vnucovaná ideologie. Dohoda drží prostor s úctou; neproselytizuje žádný systém víry.\n\nDohoda měří úspěch výsledkem svého nejzranitelnějšího účastníka, nikoli průměrem. Venkovští účastníci bez vysokého datového toku jsou obslouženi. Neurodivergentní účastníci dostávají přizpůsobení jako normu. Účastníci se zdravotním postižením shledávají každé zařízení přístupným. Genderově rozmanití účastníci dostávají bezpečné ubytování a spárování s mentorem. Nerodilí mluvčí shledávají každý dokument ve svém jazyce. Domorodí účastníci shledávají své kulturní praxe ctěny a své tradiční znalosti chráněny. Vůdci, kteří podepisují tuto dohodu, slibují, že žádný účastník nebude potichu zapomenut, aby průměry vypadaly dobře. Toto je důstojnost jako substrát, nikoli jako dekorace. Co se měří, to bude ctěno, a co se zde ctí, je celý člověk — mysl, tělo a duch pospolu, bez jakékoli výjimky.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Financování a správa`,
    content: {
      7: `Občané financují příští generaci přímo.`,
      33: `Obyčejní obyvatelé přispívají malými měsíčními částkami. Žádný kanál pomoci, žádný zahraniční dobrodinec, žádné politické provázky. Každý dolar je vysledovatelný. Každé účetnictví je zveřejňováno, v jazyce každého regionu, každý měsíc, veřejně.`,
      111: `Atlantské dohody jsou financovány občany, jimž slouží. Obyčejní obyvatelé přispívají malými dobrovolnými částkami každý měsíc — dost skromnými, aby žádný dospělý nebyl cenově vyloučen, dost rezonantními, aby jejich součet udržel práci dohody ve smysluplném měřítku. Když občan financuje příští generaci přímo, tento občan volá dohodu k odpovědnosti přímo. Dohoda je záměrně nezávislá na mnohostranných institucích, které utvářely minulé století. Toto není politické prohlášení — je to konstrukční rozhodnutí. Každý dolar je zaznamenán trvale a vysledovatelně. Každý občanský příspěvek lze sledovat od původu ke stipendiu a k inovaci. Transparentnost, jakou málokterá instituce nabízí.`,
      333: `Atlantské dohody jsou financovány občany, jimž slouží. Obyčejní obyvatelé zúčastněných regionů přispívají malými dobrovolnými částkami každý měsíc — částkami dost skromnými, aby žádný dospělý v žádném hostitelském regionu nebyl vyloučen z účasti, dost rezonantními, aby jejich součet udržel práci dohody ve smysluplném měřítku. Tento návrh je záměrný. Když občan financuje vzdělávání příští generace přímo, tento občan volá dohodu k odpovědnosti přímo. Není zde žádný kanál pomoci, žádný zahraniční dobrodinec, žádný politický provázek přivázaný k šeku. Duší dohody je občan, který přispívá jednou malou částkou každý měsíc a jehož účast činí celek možným.\n\nDohoda je záměrně nezávislá na mnohostranných institucích, které utvářely minulé století — na Organizaci Severoatlantické smlouvy, Světové zdravotnické organizaci, Organizaci spojených národů, Mezinárodním měnovém fondu, Světové bance a každém národním kanálu zahraniční pomoci. Toto není politické prohlášení o hodnotě těchto institucí nebo jejich přínosech. Je to konstrukční rozhodnutí. Závislosti na jediném bodě ohrožují trvanlivost v pětisetletém horizontu. Rámec určený sloužit každému regionu bez ohledu na geopolitické ukotvení nemůže být spleten s žádným jediným ukotvením. Národní vlády mohou přispívat dobrovolně. Příspěvky jsou transparentní. Žádný příspěvek nekupuje vliv na správu, z jakéhokoli zdroje, nikdy.\n\nKaždý dolar a každá jednotka hodnoty vstupující do dohody je zaznamenána trvale, veřejně a vysledovatelně. Každý občanský příspěvek lze sledovat od jeho původu ke stipendiu, jímž se stane, k mladému člověku, jemuž slouží, k inovačnímu projektu, který z práce toho mladého člověka vzejde. Administrativní režie je zastropována. Firemní a institucionální dary jsou vítány a zastropovány. Úplné účetnictví je předáváno v jazyce každého signatářského regionu každý měsíc. Vůdci, kteří podepisují dohodu, slibují svým občanům transparentnost, jakou málokterá instituce nabízí — transparentnost, která zůstane čitelná po staletí poté, co každý signatář opustí úřad. To je důvěra, kterou dohoda vyžaduje. To je důvěra, kterou si dohoda získává, jedním malým vysledovatelným příspěvkem po druhém, na očích každého občana.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Mezikulturní výměna a globální přínos`,
    content: {
      7: `Každý student ve svém vlastním jazyce.`,
      33: `Každá aktivita dostupná v jazyce účastníka. Umělá, Lidská a Sdílená inteligence drženy v produktivním napětí — žádný student se nespoléhá jen na jednu. Učební plány a výsledky zveřejňovány otevřeně. Co se jeden region naučí, všechny zdědí.`,
      111: `Atlantské dohody vracejí vzdělávání jeho nejhlubší účel: výměnu moudrosti přes hranice, které by jinak rozdělovaly. Každá aktivita je dostupná v jazyce účastníka, v jazyce hostitelského regionu a v kanonickém sdíleném záznamu. Jazyk není dekorace — jazyk je jurisdikce, jazyk je důstojnost učiněná čitelnou. Vzdělávací rámec spočívá na trojici inteligencí: Umělá navrhuje, Lidská rozhoduje, Sdílený záměr ověřuje. Každý student se učí držet všechny tři v produktivním napětí. Co se dohoda naučí, to dohoda vrací. Učební plány, výsledky inovací, výzkum blaha a rozhodnutí o správě jsou zveřejňovány otevřeně. Co se jeden region naučí, všechny regiony zdědí.`,
      333: `Atlantské dohody vracejí vzdělávání jeho nejhlubší účel: výměnu moudrosti přes hranice, které by jinak rozdělovaly. Každá aktivita dohody je dostupná ve vlastním jazyce účastníka, v oficiálním jazyce hostitelského regionu a v kanonickém sdíleném záznamu, aby žádný účastník neprocházel dohodou v jazyce, který si nevybral. Jazyk není dekorace. Jazyk je jurisdikce. Jazyk je důstojnost učiněná čitelnou. Když si mladý člověk z kambodžské vesnice čte svůj vlastní záznam o stipendiu v khmerštině, když si jej mladý člověk z honduraského městečka čte ve španělštině, když si jej mladý člověk z austinské čtvrti čte v angličtině, všichni tři jsou ctěni stejně toutéž dohodou.\n\nVzdělávací rámec dohody spočívá na trojici inteligencí, kterou Vision 2525 činí viditelnou. Umělá inteligence navrhuje vzorce, možnosti a příležitosti rychleji, než by dokázal jakýkoli člověk sám. Lidská inteligence rozhoduje o bezpečnosti, etice a směru — o otázkách, které by žádný stroj neměl zodpovídat. Sdílený záměr ověřuje, že rozhodnutí jsou v souladu se zakladatelskými principy dohody, a zajišťuje, že žádný účastník není nucen volit mezi individuální excelencí a společným dobrem. Žádný student není učen spoléhat se na jedinou inteligenci. Každý student se učí držet všechny tři v produktivním napětí. Tak je příští generace vůdců připravována vládnout odpovědně a moudře ve světě, kde žádná z těchto tří inteligencí nikdy nebude jednat sama nebo bez kontroly.\n\nCo se dohoda naučí, to dohoda vrací. Učební plány jsou zveřejňovány pod otevřenou licencí, aby je jakýkoli region — signatářský či nikoli — mohl volně přizpůsobit místní kultuře a pedagogické tradici. Výsledky inovací jsou zveřejňovány. Výzkum blaha je zveřejňován v agregované podobě pro výzkumníky všude na světě. Rozhodnutí o správě jsou zveřejňována s jejich úplným zdůvodněním. Úspěch dohody se neměří pouze jejími vlastními účastníky, ale počtem vzdělávacích, inovačních a kulturních iniciativ, které vzniknou v jejím kýlu, v regionech, které nikdy nepodepsaly zakladatelský pilot, a přesto stavěly na její otevřeně sdílené moudrosti. Co se jeden region naučí, všechny ostatní regiony zdědí.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Udržitelný růst sítě`,
    content: {
      7: `Nikdy rychleji, než může cestovat důstojnost.`,
      33: `Tři zakladatelské regiony dokončí jeden pilotní cyklus, než se přidá čtvrtý. Záznamy ukotveny tak, aby přetrvaly pět staletí. Každý signatář si zachovává suverenitu. Nic není zhoršeno, aby udělalo místo dalšímu signatáři.`,
      111: `Atlantské dohody nebudou růst rychleji, než jakou kvalitu dokážou ctít. Tři zakladatelské regiony musí dokončit úplný pilotní cyklus, s každým účastníkem ctěným a každým principem ověřeným, než se přidá čtvrtý region. To je princip, který se konečně stal živou disciplínou. Horizont dohody je záměrně dlouhý — pět staletí ode dne založení. Její záznamy jsou ukotveny tak, aby občan, který je bude číst za sto let, mohl důvěřovat jejich úvaze. Každý signatář si zachovává plnou suverenitu, plnou pravomoc a plnou svobodu odstoupit. Žádný signatář nemůže ohrozit zakladatelské principy — protože ty principy jsou slibem dohody jejím účastníkům napříč každou generací.`,
      333: `Atlantské dohody nebudou růst rychleji, než jakou kvalitu dokážou ctít. Každé rozšíření je slibem účastníkům již uvnitř — že zakladatelský standard dohody nebude rozředěn nadšením z měřítka. Tři zakladatelské regiony musí dokončit úplný pilotní cyklus, s každým účastníkem ctěným a každým principem ověřeným, než se přidá čtvrtý region. Toto není opatrnost převlečená za princip. To je princip, který se konečně stal živou disciplínou napříč každým zakladatelským regionem. Vůdci, kteří podepisují zakladatelský pilot, slibují budoucím signatářům tentýž substrát, tutéž ochranu, tutéž důstojnost, jakou obdržela zakladatelská skupina. Nic není zhoršeno, aby udělalo místo dalšímu.\n\nHorizont dohody je záměrně dlouhý. Je navržena tak, aby přetrvala přibližně patnáct až dvacet lidských generací — pět staletí ode dne založení. Její záznamy jsou ukotveny tak, aby občan, který je bude číst za sto let, mohl důvěřovat jejich úvaze. Její souřadnicový rámec, její role lidské pravomoci a její mezigenerační cykly správy jsou vše vybudovány tak, aby přežily jakýkoli přechod jediné technologie. Dohoda přežije každého člověka, který podepíše její zakladatelský pilot. To je její slib dítěti, které podepíše dohodu o stipendiu v roce následujícím po ratifikaci, vnoučatům toho dítěte, která možná budou dohodě vládnout v polovině století, a každé generaci, jež zdědí to, co zakladatelé nyní budují.\n\nKaždý signatář si zachovává svobodu odstoupit s výpovědí. Každý signatář si zachovává plnou suverenitu. Každý signatář si zachovává pravomoc nad svými vlastními občany. Každý signatář si zachovává právo navrhovat dodatky, vznášet spory a utvářet vývoj dohody spolu s každým dalším signatářem. Co žádný signatář nemůže učinit, je ohrozit zakladatelské principy substrátu — protože ty principy jsou slibem dohody jejím účastníkům a ten slib musí přežít odchod jakéhokoli podpisu. Vůdci, kteří tuto dohodu nyní podepisují, se připojují k něčemu většímu než jakékoli funkční období politického úřadu. Podepisují příští století dohody, a staletí za ním, do horizontu, který zdědí a dokončí jejich vlastní vnoučata.`,
    },
  },
];
