import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_DA: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Hvor innovation begynder`,
    content: {
      7: `Ledere begynder hvad intet århundrede har begyndt.`,
      33: `Tre regioner — Cambodia, Honduras, Austin — lover at være vært for unge lærende, beskytte dem og overrække dem fremtidens værktøjer. Regering, Uddannelse, Innovation: tre visionære underskrifter per region. En begyndelse sammen.`,
      111: `The Atlantis Accords er et løfte givet af ledere villige til at begynde noget, der ikke har eksisteret før. Dens stiftende underskrivere i Cambodia, Honduras og Austin, Texas blev valgt for én sjælden kvalitet: viljen til at betro de unge fremtidens værktøjer, mens der stadig er tid til at lære dem det. At underskrive accorden forpligter regionen til at være vært for lærende på tværs af kulturer, bidrage med hvad kun den unikt kan tilbyde, og holde sig til en højere standard end nuværende regulering kræver. Tre visionære underskrifter — Regering, Uddannelse, Innovation — går ind i accorden sammen. Tre visionære, tre regioner, én fælles begyndelse.`,
      333: `Enhver civilisation huskes for det, den valgte at begynde. The Atlantis Accords er et løfte givet af ledere villige til at begynde noget, der ikke har eksisteret før — et fælles fundament for almindelig menneskelig innovation, der når hvert hjørne af verden, ærer hver stemme og består gennem generationer. Dens stiftende underskrivere i Cambodia, Honduras og Austin, Texas blev ikke valgt for økonomisk magt, militær styrke eller institutionel prestige. De blev valgt for en sjældnere kvalitet: viljen til at betro de unge fremtidens værktøjer. Dette er hvad lederskab betyder i det kommende århundrede — modet til at overdrage nøglerne til næste generation, mens der stadig er tid til at lære dem at køre.

Accorden indkaldes af eXeL, en organiserende kraft bygget særligt til dette øjeblik. eXeL eksisterer bevidst uden for de traditionelle koordineringskanaler, der formede det sidste århundrede — uden for diplomatiske traktatstrukturer, uden for multilaterale bureaukratier, uden for nogen enkelt nationalstats politiske forviklinger. eXeL er den betroede indkalder, der bringer visionære ledere sammen omkring en fælles ramme, et fælles hjul og en fælles femhundredårig horisont. Hver underskriver bevarer fuld suverænitet, fuld autoritet over sine egne borgere og fuld frihed til at trække sig ud når som helst. Hvad underskrivere vinder er netværkseffekten, som kun en formålsbygget ramme kan give. Dette er koordinering uden nogen enkelt form for politisk dominans.

At underskrive accorden er at underskrive et løfte. At regionen vil være vært for unge lærende på tværs af kulturer. At regionen vil bidrage med hvad kun den unikt kan tilbyde. At regionen vil holde sig til en højere standard end nuværende regulering kræver. At regionen vil gøre det offentligt, gennemsigtigt, i syne af hver borger den tjener. Tre underskrifter kræves fra hver region — Regering, Uddannelse og Innovation. Intet enkelt embede binder accorden alene. Det tager tre visionære at sige ja. Tre visionære, tre regioner, én begyndelse — sådan træder enhver ramme ind i livet gennem den gensidige tillid hos ledere villige til at underskrive den til eksistens.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Læring gennem simulering`,
    content: {
      7: `Øv tusind gange før du rører.`,
      33: `Intet betydningsfuldt læres først på skarp hardware. Hver deltager øver i simulering, roterer på tværs af tre regioner, fejrer offentligt. Dette er respekt for det unge menneske, hvis første fejl aldrig bør koste et liv.`,
      111: `Hver disciplin værd at mestre blev lært af nogen, før den var kendt. The Atlantis Accords returnerer denne ældgamle visdom til centrum af, hvordan de unge forberedes til at bygge fremtiden. Intet betydningsfuldt læres først på skarp hardware, på virkelige mennesker eller under uigenkaldelige forhold. Hver deltager øver i simulering, indtil øvelse bliver kompetence, og kompetence bliver parathed. Rotationsmodellen bærer hver deltager gennem de tre grundregioner, og hver rotation slutter i en offentlig og samarbejdende fest åben for det bredere værtssamfund. Dette er respekt for det unge menneske, hvis første fejl aldrig bør koste et liv.`,
      333: `Hver disciplin værd at mestre blev lært af nogen, før den var kendt. Mesterhåndværkere øver før optræden, piloter øver før flyvning, læger øver før operation, og børn øver verden gennem leg. The Atlantis Accords returnerer denne ældgamle visdom til centrum af, hvordan de unge forberedes til at bygge fremtiden. Intet betydningsfuldt læres først på skarp hardware, på virkelige mennesker eller under uigenkaldelige forhold. Hver deltager øver i simulering, indtil øvelse bliver kompetence, og kompetence bliver parathed. Dette er ikke forsigtighed — dette er respekt for det unge menneske, hvis første fejl aldrig bør koste nogen livet.

Accordens rotationsmodel bærer hver deltager gennem de tre grundregioner. Hvad der læres i Cambodia forfines i Honduras og fuldendes i Austin. Hvad der opdages i Austin sættes til debat i Cambodia og integreres i Honduras. Hver deltager lever, lærer og mentoreres på tværs af kulturer, som ellers ville forblive fjerne. Undervisningsplanen henter fra disciplinerede simulationstraditioner på tværs af mange kulturer — fra Sun Tzu's strategiske uddannelsestradition, fra Musashi's øvelse-gennem-leg, fra Ibn Khaldun's cykliske læringsteori, fra Nalanda's klosterdialektik, fra den civile flyvesimulator — syntetiseret til at respektere hvert kognitivt stadie og hver kulturarv. Ingen enkelt tradition dominerer.

Hver rotation slutter i en offentlig og samarbejdende fest åben for det bredere værtssamfund. Naboer, familier og nysgerrige besøgende samles for at se, hvad kohorten har lært. Disse begivenheder gør sofistikeret teknologi tilgængelig og fejret snarere end frygtet. Et samfund, der vokser op med forståelse for samarbejdende systemer gennem leg, kan ikke let manipuleres af frygt for disse systemer. Dette er afskrækkelse gennem uddannelse, ikke afskrækkelse gennem magt. Accordens løfte til hver forælder: dit barn vil øve tusind gange i sikkerhed, før det rører noget, der kan skade det, og samfundet vil bevidne dets vækst hvert skridt på vejen. Dette er, hvordan respekt for det unge menneske ser ud, når det konstrueres ind i en ramme, og dette er, hvad lederskabet overdrager til næste generation af deltagere, før den generation må kræve det.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Sikkerhed bevist før tillid gives`,
    content: {
      7: `Sikkerhed bevist først, så tillid givet.`,
      33: `Hver facilitet og hver rotation ligger inde i en beskyttende kappe med tidlig varsling. Hardware nægter våbengørelse. Optegnelser overlever turbulens. Sikkerhed konstrueres omkring den yngste deltager hver dag, ikke blot lovet eller antaget.`,
      111: `Før tillid gives, må sikkerhed bevises. The Atlantis Accords gør dette til sit stiftende engagement. Hver accord-facilitet, hver rotationsrute, hvert sted en ung deltager sover eller studerer, ligger inde i en dokumenteret beskyttende kappe med tidlig varslingskapacitet, der giver samfundet timer, ikke minutter, til at reagere på enhver troværdig risiko. Hver enhed, hver sensor, hvert koordineringssystem er bundet på hardwarelaget til at nægte genanvendelse til våbensystemintegration. Dette er ikke politik — dette er fysik. Accorden er designet til at forblive ærbar gennem turbulens: politisk ustabilitet, finansieringssammentrækning, cyberangreb eller rejseforstyrrelse. Hvert scenarie planlægges for, og hver plan placerer menneskelig værdighed som sin første designbegrænsning.`,
      333: `Før tillid gives, må sikkerhed bevises. The Atlantis Accords gør dette til sit stiftende engagement. Hver accord-facilitet, hver rotationsrute, hvert sted en ung deltager sover eller studerer, ligger inde i en dokumenteret beskyttende kappe med tidlig varslingskapacitet, der giver samfundet timer, ikke minutter, til at reagere på enhver troværdig risiko. Teknologien brugt til at beskytte deltagere er den samme teknologi, accorden lærer dem at bygge — sensorer, koordinering, kommunikationsoverlevelsesevne, distribueret intelligens. Unge mennesker lærer sikkerhed indefra og ud, på deres eget sprog og i deres egen region, ikke ved at få at vide, at de er sikre, men ved at se, hvordan sikkerhed konstrueres omkring dem hver dag.

Accorden giver et ubrydeligt løfte om, hvad dens teknologi ikke kan blive. Hver enhed, hver sensor, hvert koordineringssystem er bundet på hardwarelaget til at nægte genanvendelse til våbensystemintegration. Dette er ikke politiksprog. Dette er ikke stræben. Dette er en fysisk umulighed, håndhævet kryptografisk, verificeret af hver underskriverregion og inspicerbar af hver borger. Værktøjerne, der beskytter et barn i Phnom Penh, kan ikke genanvendes til at skade et barn i Austin. Værktøjerne, der forbinder en svermøvelse i Tegucigalpa, kan ikke omkonfigureres til at ramme et menneske nogetsteds. Dette er accordens svar på et århundrede af dobbeltanvendelsesfrygt. Ikke politik — fysik.

Accorden er designet til at forblive ærbar gennem turbulens. Hvis en underskriverregion mister politisk stabilitet, holdes deltagere af de resterende regioner. Hvis finansieringen trækker sig sammen, beskyttes deltagerstipendier først, før administration og infrastruktur. Hvis digitale optegnelser angribes, består offline-sikkerhedskopier. Hvis rejser bliver umulige, fortsætter substratet virtuelt. Hvert scenarie planlægges for, og hver plan placerer menneskelig værdighed som sin første designbegrænsning. Ledere, der underskriver denne accord, underskriver et løfte om, at sikkerhed er konstrueret, ikke antaget. Hvad de giver deres borgere, er ikke blot mulighed, men beskyttelse bygget ved den standard, den yngste deltager fortjener — den samme beskyttelse hver leder ville kræve for sit eget barn, der krydser en ukendt grænse alene.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Kompensation, velvære og menneskelig værdighed`,
    content: {
      7: `Et stipendium, en mentor, et hjem.`,
      33: `Hver deltager modtager et levende stipendium fra dag ét. Kærlighed, tab og sikkerhed behandles som førsteklasses infrastruktur. Succes måles ved den mest udsatte deltager, aldrig gennemsnittet. Værdighed er substrat, aldrig dekoration.`,
      111: `The Atlantis Accords behandler hver deltager som et helt menneske fra den første dag. Et stipendium gives fra det øjeblik, deltagelse begynder, indekseret til regionens leveomkostninger, så dens indflydelse respekterer arbejdets lokale værdighed. Velvære behandles som førsteklasses infrastruktur — ikke valgfri fordel, ikke velværebonus, men substratet, hvorpå alt andet står. Tre grundlæggende domæner støttes: Kærlighed, Tab og Sikkerhed. Accorden måler succes ved udfaldet for sin mest udsatte deltager, ikke gennemsnittet. Ingen deltager vil stilfærdigt blive glemt, for at gennemsnit kan se godt ud. Værdighed som substrat, ikke dekoration.`,
      333: `The Atlantis Accords behandler hver deltager som et helt menneske fra den første dag. Et stipendium gives fra det øjeblik, deltagelse begynder, indekseret til regionens leveomkostninger, så dens indflydelse respekterer arbejdets lokale værdighed. Stipendiet ankommer, før familieforpligtelser bliver nødsituationer, og før værdighed kompromitteres. Det signalerer til hver ung person, at deres tid er værdifuld, deres bidrag forventes, og deres families stabilitet er del af accordens ansvar. Dette er ikke velgørenhed. Dette er anerkendelsen af, at almindelig menneskelig innovation kræver almindelig menneskelig tryghed først. Et sind kan ikke blomstre, mens dets husstand er truet.

Velvære behandles som førsteklasses infrastruktur — ikke valgfri fordel, ikke velværebonus, men substratet, hvorpå alt andet står. Accorden navngiver tre grundlæggende domæner, som hver deltager støttes gennem: Kærlighed, i betydningen forbindelse, tilknytning og sund grænse; Tab, da hver deltager vil opleve sorg og må gås med, ikke uden om; og Sikkerhed, i den betydning at hver deltager ved, hvem de skal ringe til, i hver region, på deres eget sprog. Individuel rådgivning, gruppecirkler, somatiske praksisser og kulturelle eller åndelige praksisser hædret efter deltagerens egen tradition gives alle. Nul påtvunget ideologi. Accorden holder rum med ærbødighed; den missionerer intet trossystem.

Accorden måler succes ved udfaldet for sin mest udsatte deltager, ikke gennemsnittet. Landdeltagere uden høj båndbredde tjenes. Neurodivergente deltagere modtager tilpasning som norm. Handicappede deltagere finder hver facilitet tilgængelig. Kønsdiversificerede deltagere modtager sikker bolig og mentorparring. Ikke-modersmålstalere finder hver artefakt på deres sprog. Oprindelige deltagere finder deres kulturelle praksisser hædret og deres traditionelle viden beskyttet. Ledere, der underskriver denne accord, lover, at ingen deltager stilfærdigt vil blive glemt, for at gennemsnit kan se godt ud. Dette er værdighed som substrat, ikke dekoration. Hvad der måles, er hvad der vil blive hædret, og hvad der hædres her, er hele mennesket — sind, krop og ånd sammen, uden nogen undtagelse overhovedet.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finansiering og styring`,
    content: {
      7: `Borgere finansierer næste generation direkte.`,
      33: `Almindelige beboere bidrager med små månedlige beløb. Ingen bistandspipeline, ingen udenlandsk velgører, ingen politiske tråde. Hver krone er sporbar. Hver regnskabsføring offentliggøres, på hver regions sprog, hver måned, offentligt.`,
      111: `The Atlantis Accords finansieres af de borgere, den tjener. Almindelige beboere bidrager med små frivillige beløb hver måned — beskedne nok til, at ingen voksen prissættes ud, resonante nok til, at totalen opretholder accordens arbejde i meningsfuld skala. Når en borger finansierer næste generation direkte, holder den borger accorden direkte ansvarlig. Accorden er bevidst uafhængig af de multilaterale institutioner, der formede det sidste århundrede. Dette er ikke et politisk udsagn — det er et designvalg. Hver krone registreres permanent og sporbart. Hvert borgerbidrag kan følges fra oprindelse til stipendium til innovation. Gennemsigtighed af en art, sjældent tilbudt af nogen institution.`,
      333: `The Atlantis Accords finansieres af de borgere, den tjener. Almindelige beboere i deltagende regioner bidrager med små frivillige beløb hver måned — beløb beskedne nok til, at ingen voksen i nogen værtsregion prissættes ud af deltagelse, resonante nok til, at totalen opretholder accordens arbejde i meningsfuld skala. Dette design er bevidst. Når en borger finansierer uddannelsen af næste generation direkte, holder den borger accorden direkte ansvarlig. Der er ingen bistandspipeline, ingen udenlandsk velgører, ingen politisk tråd knyttet til checken. Accordens sjæl er borgeren, der bidrager med ét lille beløb hver måned, hvis deltagelse gør helheden mulig.

Accorden er bevidst uafhængig af de multilaterale institutioner, der har formet det sidste århundrede — Den Nordatlantiske Traktatorganisation, Verdenssundhedsorganisationen, De Forenede Nationer, Den Internationale Valutafond, Verdensbanken og hver national udenlandsk bistandskanal. Dette er ikke et politisk udsagn om disse institutioners værd eller bidrag. Det er et designvalg. Enkeltpunktsafhængigheder kompromitterer holdbarhed over en femhundredårig horisont. En ramme ment til at tjene hver region uanset geopolitisk tilpasning kan ikke forviklet med nogen enkelt tilpasning. Nationale regeringer kan bidrage frivilligt. Bidrag er gennemsigtige. Intet bidrag køber styringsindflydelse, fra nogen kilde, nogensinde.

Hver krone og hver værdienhed, der kommer ind i accorden, registreres permanent, offentligt og sporbart. Hvert borgerbidrag kan følges fra dets oprindelse til stipendiet, det bliver, til den unge person, det tjener, til innovationsprojektet, der udspringer af den unge persons arbejde. Administrativ omkostning er loftlagt. Virksomheds- og institutionelle gaver bydes velkommen og loftlagges. Fuld regnskabsføring leveres på hver underskriverregions sprog hver måned. Ledere, der underskriver accorden, lover deres borgere gennemsigtighed af en art, sjældent tilbudt af nogen institution — gennemsigtighed, der forbliver læsbar i århundreder efter, at hver underskriver har forladt embedet. Dette er den tillid, accorden kræver. Dette er den tillid, accorden fortjener, ét lille sporbart bidrag ad gangen, i syne af hver borger.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Tværkulturel udveksling og globalt bidrag`,
    content: {
      7: `Hver lærende på deres eget sprog.`,
      33: `Hver aktivitet tilgængelig på deltagerens sprog. Kunstig, Menneskelig og Delt intelligens holdes i produktiv spænding — ingen elev underkaster sig én alene. Læseplaner og udfald offentliggøres åbent. Hvad en region lærer, arver alle.`,
      111: `The Atlantis Accords returnerer uddannelse til dens dybeste formål: udvekslingen af visdom på tværs af grænser, som ellers ville dele. Hver aktivitet er tilgængelig på deltagerens eget sprog, værtsregionens sprog og en kanonisk delt optegnelse. Sprog er ikke dekoration — sprog er jurisdiktion, sprog er værdighed gjort læsbar. Uddannelsesrammen hviler på treenigheden af intelligenser: Kunstig foreslår, Menneskelig beslutter, Delt Hensigt validerer. Hver elev lærer at holde alle tre i produktiv spænding. Hvad accorden lærer, giver accorden tilbage. Læseplaner, innovationsudfald, velværeforskning og styringsbeslutninger offentliggøres alle åbent. Hvad en region lærer, arver alle regioner.`,
      333: `The Atlantis Accords returnerer uddannelse til dens dybeste formål: udvekslingen af visdom på tværs af grænser, som ellers ville dele. Hver accord-aktivitet er tilgængelig på deltagerens eget sprog, på værtsregionens officielle sprog og i en kanonisk delt optegnelse, så ingen deltager navigerer accorden på et tungemål, de ikke valgte. Sprog er ikke dekoration. Sprog er jurisdiktion. Sprog er værdighed gjort læsbar. Når en ung person fra en cambodjansk landsby læser sin egen stipendieoptegnelse på khmer, når en ung person fra en honduransk by læser den på spansk, når en ung person fra et Austin-kvarter læser den på engelsk, æres alle tre lige af den samme accord.

Accordens uddannelsesramme hviler på treenigheden af intelligenser, som Vision 2525 gør synlig. Kunstig Intelligens foreslår mønstre, muligheder og potentialer hurtigere, end noget menneske alene kunne. Menneskelig Intelligens beslutter om sikkerhed, etik og retning — de spørgsmål, som ingen maskine bør svare på. Delt Hensigt validerer, at beslutninger flugter med accordens stiftende principper, og sikrer, at ingen deltager bliver bedt om at vælge mellem individuel ekspertise og kollektivt gode. Ingen elev læres at underkaste sig nogen enkelt intelligens. Hver elev lærer at holde alle tre i produktiv spænding. Sådan forberedes næste generation af ledere til at styre ansvarligt og klogt i en verden, hvor ingen af disse tre intelligenser nogensinde vil handle alene eller ukontrolleret.

Hvad accorden lærer, giver accorden tilbage. Læseplaner offentliggøres under åben licens, så enhver region — underskriver eller ej — frit kan tilpasse dem til lokal kultur og pædagogisk tradition. Innovationsudfald offentliggøres. Velværeforskning offentliggøres i aggregeret form for forskere overalt. Styringsbeslutninger offentliggøres med deres fulde ræsonnement. Accordens succes måles ikke kun ved dens egne deltagere, men ved antallet af uddannelses-, innovations- og kulturinitiativer, der opstår i dens kølvand, i regioner, der aldrig underskrev den stiftende pilot, men byggede på dens åbent delte visdom. Hvad en region lærer, arver alle andre regioner.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Bæredygtig vækst af netværket`,
    content: {
      7: `Aldrig hurtigere end værdighed kan rejse.`,
      33: `Tre grundregioner fuldender én pilotcyklus, før en fjerde tilslutter sig. Optegnelser forankret til at bestå fem århundreder. Hver underskriver bevarer suverænitet. Intet nedgraderes for at gøre plads til, at næste underskriver kan tilslutte sig.`,
      111: `The Atlantis Accords vil ikke vokse hurtigere end den kvalitet, den kan ære. Tre grundregioner må fuldende en fuld pilotcyklus, med hver deltager æret og hvert princip verificeret, før en fjerde region tilslutter sig. Dette er princip, der endelig bliver arbejdende disciplin. Accordens horisont er bevidst lang — fem århundreder fra grunddagen. Dens optegnelser er forankret, så en borger, der læser dem hundrede år frem, kan stole på ræsonnementet. Hver underskriver bevarer fuld suverænitet, fuld autoritet og fuld frihed til at trække sig. Ingen underskriver kan kompromittere grundprincipperne — fordi disse principper er accordens løfte til dens deltagere på tværs af hver generation.`,
      333: `The Atlantis Accords vil ikke vokse hurtigere end den kvalitet, den kan ære. Hver ekspansion er et løfte til de deltagere, der allerede er indenfor — at accordens stiftende standard ikke vil blive udvandet af skalaens begejstring. Tre grundregioner må fuldende en fuld pilotcyklus, med hver deltager æret og hvert princip verificeret, før en fjerde region tilslutter sig. Dette er ikke forsigtighed forklædt som princip. Dette er princip, der endelig bliver arbejdende disciplin på tværs af hver grundregion. Ledere, der underskriver den stiftende pilot, lover fremtidige underskrivere det samme substrat, den samme beskyttelse, den samme værdighed, som stiftende kohorte modtog. Intet nedgraderes for at gøre plads til den næste.

Accordens horisont er bevidst lang. Den er designet til at bestå i cirka femten til tyve menneskegenerationer — fem århundreder fra grunddagen. Dens optegnelser er forankret, så en borger, der læser dem hundrede år frem, kan stole på ræsonnementet. Dens koordinatramme, dens menneskelige autoritetsroller og dens generationsoverskridende styringscyklusser er alle bygget til at overleve enhver enkeltteknologisk overgang. Accorden vil overleve hvert menneske, der underskriver dens stiftende pilot. Det er dens løfte til barnet, der underskriver en stipendieaftale i året efter ratificering, til det barns børnebørn, som måske vil styre accorden i midten af århundredet, og til hver generation, der arver, hvad grundlæggerne bygger nu.

Hver underskriver bevarer friheden til at trække sig med varsel. Hver underskriver bevarer fuld suverænitet. Hver underskriver bevarer autoritet over sine egne borgere. Hver underskriver bevarer retten til at foreslå ændringer, at rejse tvister og at forme accordens udvikling ved siden af hver anden underskriver. Hvad ingen underskriver kan gøre, er at kompromittere substratets stiftende principper — fordi disse principper er accordens løfte til dens deltagere, og det løfte må overleve enhver enkelt underskrifts afgang. Ledere, der underskriver denne accord nu, tilslutter sig noget større end nogen enkelt politisk embedsperiode. De underskriver accordens næste århundrede og århundreder derefter ind i en horisont, som deres egne børnebørn vil arve og fuldende.`,
    },
  },
];
