import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_DE: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Wo Innovation beginnt`,
    content: {
      7: `Führende beginnen, was kein Jahrhundert begann.`,
      33: `Drei Regionen — Cambodia, Honduras, Austin — versprechen, junge Lernende aufzunehmen, sie zu schützen und ihnen die Werkzeuge der Zukunft anzuvertrauen. Regierung, Bildung, Innovation: drei visionäre Unterschriften pro Region. Ein gemeinsamer Anfang.`,
      111: `Das Atlantis Accords ist ein Versprechen von Führenden, die bereit sind, etwas zu beginnen, das zuvor nicht existierte. Seine Gründungsunterzeichner in Cambodia, Honduras und Austin, Texas wurden für eine seltene Eigenschaft gewählt: die Bereitschaft, den Jungen die Werkzeuge der Zukunft anzuvertrauen, solange noch Zeit bleibt, sie zu lehren. Die Unterzeichnung verpflichtet die Region, Lernende aus verschiedenen Kulturen aufzunehmen, das beizutragen, was nur sie einzigartig anbieten kann, und sich an einen Standard zu halten, der höher liegt als bestehende Regulierung. Drei visionäre Unterschriften — Regierung, Bildung, Innovation — treten dem Accord gemeinsam bei. Drei Visionäre, drei Regionen, ein geteilter Anfang.`,
      333: `Jede Zivilisation wird daran erinnert, was sie zu beginnen wählte. Das Atlantis Accords ist ein Versprechen von Führenden, die bereit sind, etwas zu beginnen, das zuvor nicht existierte — ein gemeinsames Fundament für alltägliche menschliche Innovation, das jeden Winkel der Welt erreicht, jede Stimme ehrt und über Generationen Bestand hat. Seine Gründungsunterzeichner in Cambodia, Honduras und Austin, Texas wurden nicht wegen wirtschaftlicher Macht, militärischer Stärke oder institutioneller Prestige gewählt. Sie wurden für eine seltenere Eigenschaft gewählt: die Bereitschaft, den Jungen die Werkzeuge der Zukunft anzuvertrauen. Das bedeutet Führung im kommenden Jahrhundert — der Mut, der nächsten Generation die Schlüssel zu übergeben, solange noch Zeit ist, ihr das Steuern beizubringen.

Der Accord wird von eXeL einberufen, einer für diesen Moment eigens geschaffenen organisierenden Kraft. eXeL existiert bewusst außerhalb der traditionellen Koordinationskanäle, die das vergangene Jahrhundert prägten — außerhalb diplomatischer Vertragsstrukturen, außerhalb multilateraler Bürokratien, außerhalb der politischen Verstrickungen einzelner Nationalstaaten. eXeL ist der vertraute Zusammenführer, der visionäre Führende um einen gemeinsamen Rahmen, ein gemeinsames Schwungrad und einen gemeinsamen Fünfhundertjahreshorizont versammelt. Jeder Unterzeichner behält seine volle Souveränität, volle Autorität über die eigenen Bürger und volle Freiheit, jederzeit auszutreten. Was Unterzeichner gewinnen, ist der Netzwerkeffekt, den nur ein eigens gebauter Rahmen bieten kann. Dies ist Koordination ohne jede Form politischer Dominanz.

Die Unterzeichnung des Accords ist das Unterzeichnen eines Versprechens. Dass die Region junge Lernende verschiedener Kulturen aufnimmt. Dass die Region beitragen wird, was nur sie einzigartig anbieten kann. Dass die Region sich an einen Standard hält, der höher liegt als bestehende Regulierung. Dass sie dies öffentlich und transparent tut, in Sichtweite jedes Bürgers, dem sie dient. Drei Unterschriften sind pro Region erforderlich — Regierung, Bildung und Innovation. Kein einzelnes Amt bindet den Accord allein. Es braucht drei Visionäre, um Ja zu sagen. Drei Visionäre, drei Regionen, ein Anfang — so tritt jeder Rahmen ins Leben, durch das gegenseitige Vertrauen von Führenden, die bereit sind, ihn ins Dasein zu unterzeichnen.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Lernen durch Simulation`,
    content: {
      7: `Tausendmal üben, bevor man berührt.`,
      33: `Nichts Folgenreiches wird zuerst an lebender Hardware gelernt. Jeder Teilnehmer übt in Simulation, rotiert durch drei Regionen, feiert öffentlich. Dies ist Respekt vor dem jungen Menschen, dessen erster Fehler nie ein Leben kosten sollte.`,
      111: `Jede Disziplin, die es wert ist, gemeistert zu werden, wurde von jemandem gelernt, bevor sie bekannt war. Das Atlantis Accords bringt diese uralte Weisheit ins Zentrum, wie die Jungen auf den Aufbau der Zukunft vorbereitet werden. Nichts Folgenreiches wird zuerst an lebender Hardware, an echten Menschen oder unter irreversiblen Bedingungen gelernt. Jeder Teilnehmer übt in Simulation, bis Übung zu Kompetenz und Kompetenz zu Bereitschaft wird. Das Rotationsmodell führt jeden Teilnehmer durch die drei Gründungsregionen, und jede Rotation endet in einer öffentlichen, kooperativen Feier, offen für die weitere Gastgemeinschaft. Dies ist Respekt vor dem jungen Menschen, dessen erster Fehler nie ein Leben kosten sollte.`,
      333: `Jede Disziplin, die es wert ist, gemeistert zu werden, wurde von jemandem gelernt, bevor sie bekannt war. Meisterhandwerker proben vor der Aufführung, Piloten proben vor dem Flug, Ärzte proben vor der Operation, und Kinder proben die Welt durch Spiel. Das Atlantis Accords bringt diese uralte Weisheit ins Zentrum, wie die Jungen auf den Aufbau der Zukunft vorbereitet werden. Nichts Folgenreiches wird zuerst an lebender Hardware, an echten Menschen oder unter irreversiblen Bedingungen gelernt. Jeder Teilnehmer übt in Simulation, bis Übung zu Kompetenz und Kompetenz zu Bereitschaft wird. Das ist keine Vorsicht — das ist Respekt vor dem jungen Menschen, dessen erster Fehler niemandem das Leben kosten sollte.

Das Rotationsmodell des Accords führt jeden Teilnehmer durch die drei Gründungsregionen. Was in Cambodia gelernt wird, wird in Honduras verfeinert und in Austin vollendet. Was in Austin entdeckt wird, wird in Cambodia hinterfragt und in Honduras integriert. Jeder Teilnehmer lebt, lernt und wird über Kulturen hinweg begleitet, die sonst fern blieben. Das Ausbildungscurriculum schöpft aus disziplinierten Simulationstraditionen vieler Kulturen — aus der strategischen Bildungstradition von Sun Tzu, aus Musashi's Übung-durch-Spiel, aus Ibn Khaldun's zyklischer Lerntheorie, aus Nalanda's klösterlicher Dialektik, aus dem zivilen Flugsimulator — synthetisiert, um jede kognitive Stufe und kulturelle Erbschaft zu ehren. Keine einzelne Tradition dominiert.

Jede Rotation endet in einer öffentlichen und kooperativen Feier, offen für die weitere Gastgemeinschaft. Nachbarn, Familien und neugierige Besucher versammeln sich, um zu sehen, was die Kohorte gelernt hat. Diese Ereignisse machen anspruchsvolle Technologie zugänglich und gefeiert statt furchteinflößend. Eine Gesellschaft, die im Verständnis kooperativer Systeme durch Spiel aufwächst, kann nicht leicht durch Angst vor diesen Systemen manipuliert werden. Dies ist Abschreckung durch Bildung, nicht Abschreckung durch Gewalt. Das Versprechen des Accords an jeden Elternteil: dein Kind wird tausendmal in Sicherheit üben, bevor es etwas berührt, das ihm schaden könnte, und die Gemeinschaft wird sein Wachstum bei jedem Schritt bezeugen. Das ist, wie Respekt vor dem jungen Menschen aussieht, wenn er in einen Rahmen eingebaut wird, und das ist, was Führung der nächsten Generation von Teilnehmern übergibt, bevor diese Generation es fordern muss.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Sicherheit bewiesen, bevor Vertrauen gewährt wird`,
    content: {
      7: `Erst Sicherheit beweisen, dann Vertrauen gewähren.`,
      33: `Jede Einrichtung und jede Rotation liegt in einer schützenden Hülle mit Frühwarnung. Hardware verweigert Waffenverwendung. Aufzeichnungen überstehen Turbulenzen. Sicherheit wird täglich um den jüngsten Teilnehmer herum konstruiert, nicht bloß versprochen oder angenommen.`,
      111: `Bevor Vertrauen gewährt wird, muss Sicherheit bewiesen werden. Das Atlantis Accords macht dies zu seiner Gründungsverpflichtung. Jede Accord-Einrichtung, jede Rotationsroute, jeder Ort, an dem ein junger Teilnehmer schläft oder studiert, liegt innerhalb einer dokumentierten Schutzhülle mit Frühwarnfähigkeit, die der Gemeinschaft Stunden statt Minuten gibt, um auf jedes glaubwürdige Risiko zu reagieren. Jedes Gerät, jeder Sensor, jedes Koordinationssystem ist auf Hardwareebene gebunden, die Umnutzung für Waffensystemintegration zu verweigern. Dies ist keine Politik — dies ist Physik. Der Accord ist so gestaltet, dass er durch Turbulenzen ehrenhaft bleibt: politische Instabilität, Finanzkürzung, Cyberangriff oder Reiseunterbrechung. Jedes Szenario ist geplant, und jeder Plan stellt menschliche Würde als erste Designbeschränkung.`,
      333: `Bevor Vertrauen gewährt wird, muss Sicherheit bewiesen werden. Das Atlantis Accords macht dies zu seiner Gründungsverpflichtung. Jede Accord-Einrichtung, jede Rotationsroute, jeder Ort, an dem ein junger Teilnehmer schläft oder studiert, liegt innerhalb einer dokumentierten Schutzhülle mit Frühwarnfähigkeit, die der Gemeinschaft Stunden statt Minuten gibt, um auf jedes glaubwürdige Risiko zu reagieren. Die Technologie, die zum Schutz der Teilnehmer verwendet wird, ist dieselbe Technologie, deren Bau der Accord sie lehrt — Sensoren, Koordination, Kommunikationsüberlebensfähigkeit, verteilte Intelligenz. Junge Menschen lernen Sicherheit von innen heraus, in ihrer eigenen Sprache und in ihrer eigenen Region, nicht indem sie hören, dass sie sicher sind, sondern indem sie sehen, wie Sicherheit täglich um sie herum konstruiert wird.

Der Accord gibt ein unverbrüchliches Versprechen darüber, was seine Technologie nicht werden kann. Jedes Gerät, jeder Sensor, jedes Koordinationssystem ist auf Hardwareebene gebunden, die Umnutzung für Waffensystemintegration zu verweigern. Das ist keine politische Sprache. Das ist kein Anspruch. Das ist eine physikalische Unmöglichkeit, kryptografisch durchgesetzt, von jeder Unterzeichnerregion verifiziert und von jedem Bürger inspizierbar. Die Werkzeuge, die ein Kind in Phnom Penh schützen, können nicht umfunktioniert werden, um einem Kind in Austin zu schaden. Die Werkzeuge, die eine Schwarmübung in Tegucigalpa verbinden, können nicht rekonfiguriert werden, um einen Menschen irgendwo anzuvisieren. Dies ist die Antwort des Accords auf ein Jahrhundert der Dual-Use-Angst. Keine Politik — Physik.

Der Accord ist so gestaltet, dass er durch Turbulenzen ehrenhaft bleibt. Wenn eine Unterzeichnerregion politische Stabilität verliert, werden Teilnehmer von den verbleibenden Regionen aufgenommen. Wenn Finanzierung schrumpft, werden Teilnehmerstipendien zuerst geschützt, vor Verwaltung und Infrastruktur. Wenn digitale Aufzeichnungen angegriffen werden, bleiben Offline-Backups bestehen. Wenn Reisen unmöglich werden, arbeitet das Substrat virtuell weiter. Jedes Szenario ist geplant, und jeder Plan stellt menschliche Würde als erste Designbeschränkung. Führende, die diesen Accord unterzeichnen, unterzeichnen ein Versprechen, dass Sicherheit konstruiert und nicht angenommen wird. Was sie ihren Bürgern bieten, ist nicht bloß Gelegenheit, sondern Schutz auf dem Standard, den der jüngste Teilnehmer verdient — derselbe Schutz, den jeder Führende für das eigene Kind fordern würde, das allein eine unbekannte Grenze überquert.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Vergütung, Wohlergehen und menschliche Würde`,
    content: {
      7: `Ein Stipendium, ein Mentor, ein Zuhause.`,
      33: `Jeder Teilnehmer erhält vom ersten Tag an ein existenzsicherndes Stipendium. Liebe, Verlust und Sicherheit werden als erstklassige Infrastruktur behandelt. Erfolg wird am verletzlichsten Teilnehmer gemessen, nie am Durchschnitt. Würde ist Substrat, nie Dekoration.`,
      111: `Das Atlantis Accords behandelt jeden Teilnehmer vom ersten Tag an als vollen Menschen. Ein Stipendium wird von dem Moment gewährt, an dem die Teilnahme beginnt, indexiert an die Lebenshaltungskosten der Region, damit seine Wirkung die lokale Würde der Arbeit respektiert. Wohlergehen wird als erstklassige Infrastruktur behandelt — nicht als optionaler Vorteil, nicht als Wellness-Beigabe, sondern als Substrat, auf dem alles andere steht. Drei fundamentale Bereiche werden unterstützt: Liebe, Verlust und Sicherheit. Der Accord misst Erfolg am Ergebnis seines verletzlichsten Teilnehmers, nicht am Durchschnitt. Kein Teilnehmer wird stillschweigend vergessen, damit Durchschnittswerte gut aussehen. Würde als Substrat, nicht Dekoration.`,
      333: `Das Atlantis Accords behandelt jeden Teilnehmer vom ersten Tag an als vollen Menschen. Ein Stipendium wird von dem Moment gewährt, an dem die Teilnahme beginnt, indexiert an die Lebenshaltungskosten der Region, damit seine Wirkung die lokale Würde der Arbeit respektiert. Das Stipendium kommt an, bevor familiäre Verpflichtungen zu Notfällen werden, und bevor Würde kompromittiert wird. Es signalisiert jedem jungen Menschen, dass seine Zeit wertvoll ist, sein Beitrag erwartet wird und die Stabilität seiner Familie Teil der Verantwortung des Accords ist. Das ist keine Wohltätigkeit. Das ist die Erkenntnis, dass alltägliche menschliche Innovation zuerst alltägliche menschliche Sicherheit erfordert. Ein Geist kann nicht gedeihen, während sein Haushalt bedroht ist.

Wohlergehen wird als erstklassige Infrastruktur behandelt — nicht als optionaler Vorteil, nicht als Wellness-Beigabe, sondern als Substrat, auf dem alles andere steht. Der Accord benennt drei fundamentale Bereiche, in denen jeder Teilnehmer begleitet wird: Liebe, im Sinne von Verbindung, Bindung und gesunder Grenze; Verlust, da jeder Teilnehmer Trauer erleben wird und begleitet, nicht umgangen werden muss; und Sicherheit, in dem Sinne, dass jeder Teilnehmer weiß, wen er in jeder Region und in seiner eigenen Sprache anrufen kann. Individuelle Beratung, Gruppenkreise, somatische Praktiken sowie kulturelle oder spirituelle Praktiken, die gemäß der eigenen Tradition des Teilnehmers geehrt werden, werden alle angeboten. Null erzwungene Ideologie. Der Accord hält den Raum mit Ehrfurcht; er missioniert kein Glaubenssystem.

Der Accord misst Erfolg am Ergebnis seines verletzlichsten Teilnehmers, nicht am Durchschnitt. Ländliche Teilnehmer ohne hohe Bandbreite werden bedient. Neurodivergente Teilnehmer erhalten Anpassungen als Norm. Behinderte Teilnehmer finden jede Einrichtung zugänglich. Geschlechtervielfältige Teilnehmer erhalten sichere Unterkunft und Mentorenpaarung. Nicht-Muttersprachler finden jedes Artefakt in ihrer Sprache. Indigene Teilnehmer finden ihre kulturellen Praktiken geehrt und ihr traditionelles Wissen geschützt. Führende, die diesen Accord unterzeichnen, versprechen, dass kein Teilnehmer stillschweigend vergessen wird, damit Durchschnittswerte gut aussehen. Dies ist Würde als Substrat, nicht Dekoration. Was gemessen wird, wird geehrt, und was hier geehrt wird, ist der ganze Mensch — Geist, Körper und Seele zusammen, ohne jede Ausnahme.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finanzierung und Governance`,
    content: {
      7: `Bürger finanzieren die nächste Generation direkt.`,
      33: `Gewöhnliche Einwohner tragen kleine monatliche Beträge bei. Keine Hilfspipeline, kein ausländischer Gönner, keine politischen Fäden. Jeder Dollar ist nachverfolgbar. Jede Buchhaltung wird in jeder Regionalsprache monatlich öffentlich veröffentlicht.`,
      111: `Das Atlantis Accords wird von den Bürgern finanziert, denen es dient. Gewöhnliche Einwohner steuern jeden Monat kleine freiwillige Beträge bei — bescheiden genug, dass kein Erwachsener ausgepreist wird, resonant genug, dass die Summe die Arbeit des Accords in bedeutendem Umfang trägt. Wenn ein Bürger die nächste Generation direkt finanziert, hält dieser Bürger den Accord direkt zur Rechenschaft. Der Accord ist bewusst unabhängig von den multilateralen Institutionen, die das vergangene Jahrhundert prägten. Dies ist keine politische Aussage — es ist eine Designentscheidung. Jeder Dollar wird dauerhaft und nachverfolgbar erfasst. Jeder Bürgerbeitrag kann vom Ursprung über das Stipendium bis zur Innovation verfolgt werden. Transparenz einer Art, die selten von einer Institution geboten wird.`,
      333: `Das Atlantis Accords wird von den Bürgern finanziert, denen es dient. Gewöhnliche Einwohner der teilnehmenden Regionen steuern jeden Monat kleine freiwillige Beträge bei — Beträge, die bescheiden genug sind, dass kein Erwachsener in einer Gastregion von der Teilnahme ausgepreist wird, und resonant genug, dass die Summe die Arbeit des Accords in bedeutendem Umfang trägt. Dieses Design ist bewusst. Wenn ein Bürger die Bildung der nächsten Generation direkt finanziert, hält dieser Bürger den Accord direkt zur Rechenschaft. Es gibt keine Hilfspipeline, keinen ausländischen Gönner, keinen politischen Faden am Scheck. Die Seele des Accords ist der Bürger, der jeden Monat einen kleinen Betrag beiträgt, dessen Teilnahme das Ganze möglich macht.

Der Accord ist bewusst unabhängig von den multilateralen Institutionen, die das vergangene Jahrhundert geprägt haben — der North Atlantic Treaty Organization, der World Health Organization, den Vereinten Nationen, dem International Monetary Fund, der World Bank und jedem nationalen Auslandshilfekanal. Dies ist keine politische Aussage über den Wert dieser Institutionen oder ihre Beiträge. Es ist eine Designentscheidung. Einzelpunktabhängigkeiten kompromittieren Beständigkeit über einen Fünfhundertjahreshorizont. Ein Rahmen, der jeder Region unabhängig von geopolitischer Ausrichtung dienen soll, kann nicht mit einer einzigen Ausrichtung verstrickt sein. Nationale Regierungen dürfen freiwillig beitragen. Beiträge sind transparent. Kein Beitrag erkauft Governance-Einfluss, aus keiner Quelle, niemals.

Jeder Dollar und jede Werteinheit, die in den Accord fließt, wird dauerhaft, öffentlich und nachverfolgbar erfasst. Jeder Bürgerbeitrag kann vom Ursprung über das entstehende Stipendium bis zum jungen Menschen verfolgt werden, dem es dient, bis zum Innovationsprojekt, das aus der Arbeit dieses jungen Menschen entsteht. Verwaltungsaufwand ist gedeckelt. Unternehmens- und institutionelle Spenden sind willkommen und gedeckelt. Vollständige Buchhaltung wird jeden Monat in der Sprache jeder Unterzeichnerregion geliefert. Führende, die den Accord unterzeichnen, versprechen ihren Bürgern eine Transparenz, die selten von einer Institution geboten wird — Transparenz, die noch lesbar bleiben wird, Jahrhunderte nachdem jeder Unterzeichner sein Amt verlassen hat. Dies ist das Vertrauen, das der Accord erfordert. Dies ist das Vertrauen, das der Accord verdient, ein kleiner nachverfolgbarer Beitrag nach dem anderen, in Sichtweite jedes Bürgers.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Interkultureller Austausch und globaler Beitrag`,
    content: {
      7: `Jeder Lernende in seiner eigenen Sprache.`,
      33: `Jede Aktivität in der Sprache des Teilnehmers verfügbar. Artificial, Human und Shared Intelligence in produktiver Spannung — kein Lernender ordnet sich einer allein unter. Curricula und Ergebnisse offen veröffentlicht. Was eine Region lernt, erben alle.`,
      111: `Das Atlantis Accords bringt Bildung zu ihrem tiefsten Zweck zurück: dem Austausch von Weisheit über Grenzen, die sonst trennen würden. Jede Aktivität ist in der eigenen Sprache des Teilnehmers, der Sprache der Gastregion und einem kanonischen gemeinsamen Register verfügbar. Sprache ist keine Dekoration — Sprache ist Zuständigkeit, Sprache ist lesbar gemachte Würde. Der Bildungsrahmen ruht auf der Trinität der Intelligenzen: Artificial schlägt vor, Human entscheidet, Shared Intent bestätigt. Jeder Lernende lernt, alle drei in produktiver Spannung zu halten. Was der Accord lernt, gibt der Accord zurück. Curricula, Innovationsergebnisse, Wohlergehensforschung und Governance-Entscheidungen werden offen veröffentlicht. Was eine Region lernt, erben alle Regionen.`,
      333: `Das Atlantis Accords bringt Bildung zu ihrem tiefsten Zweck zurück: dem Austausch von Weisheit über Grenzen, die sonst trennen würden. Jede Accord-Aktivität ist in der eigenen Sprache des Teilnehmers, in der offiziellen Sprache der Gastregion und in einem kanonischen gemeinsamen Register verfügbar, damit kein Teilnehmer sich in einer Sprache durch den Accord navigieren muss, die er nicht selbst wählte. Sprache ist keine Dekoration. Sprache ist Zuständigkeit. Sprache ist lesbar gemachte Würde. Wenn ein junger Mensch aus einem kambodschanischen Dorf seine Stipendienunterlagen auf Khmer liest, ein junger Mensch aus einer honduranischen Stadt sie auf Spanisch, ein junger Mensch aus einem Austiner Viertel sie auf Englisch, dann werden alle drei gleichermaßen vom selben Accord geehrt.

Der Bildungsrahmen des Accords ruht auf der Trinität der Intelligenzen, die Vision 2525 sichtbar macht. Artificial Intelligence schlägt Muster, Optionen und Möglichkeiten schneller vor, als es ein Mensch allein könnte. Human Intelligence entscheidet über Sicherheit, Ethik und Richtung — die Fragen, die keine Maschine beantworten sollte. Shared Intent bestätigt, dass Entscheidungen mit den Gründungsprinzipien des Accords übereinstimmen, und stellt sicher, dass kein Teilnehmer zwischen individueller Exzellenz und kollektivem Wohl wählen muss. Kein Lernender wird gelehrt, sich einer einzelnen Intelligenz unterzuordnen. Jeder Lernende lernt, alle drei in produktiver Spannung zu halten. So wird die nächste Führungsgeneration vorbereitet, verantwortungsvoll und weise in einer Welt zu regieren, in der keine dieser drei Intelligenzen jemals allein oder ungeprüft handeln wird.

Was der Accord lernt, gibt der Accord zurück. Curricula werden unter offener Lizenz veröffentlicht, damit jede Region — Unterzeichner oder nicht — sie frei an lokale Kultur und pädagogische Tradition anpassen kann. Innovationsergebnisse werden veröffentlicht. Wohlergehensforschung wird in aggregierter Form für Forscher überall veröffentlicht. Governance-Entscheidungen werden mit ihrer vollen Begründung veröffentlicht. Der Erfolg des Accords wird nicht nur an seinen eigenen Teilnehmern gemessen, sondern an der Anzahl von Bildungs-, Innovations- und Kulturinitiativen, die in seinem Nachlauf entstehen, in Regionen, die niemals den Gründungspilot unterschrieben, aber auf seiner offen geteilten Weisheit aufbauten. Was eine Region lernt, erben alle anderen Regionen.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Nachhaltiges Wachstum des Netzwerks`,
    content: {
      7: `Nie schneller als Würde reisen kann.`,
      33: `Drei Gründungsregionen vollenden einen Pilotzyklus, bevor eine vierte beitritt. Aufzeichnungen verankert, um fünf Jahrhunderte zu bestehen. Jeder Unterzeichner behält Souveränität. Nichts wird herabgestuft, um Platz für den nächsten Unterzeichner zu schaffen.`,
      111: `Das Atlantis Accords wird nicht schneller wachsen als die Qualität, die es ehren kann. Drei Gründungsregionen müssen einen vollständigen Pilotzyklus abschließen, mit jedem Teilnehmer geehrt und jedem Prinzip verifiziert, bevor eine vierte Region beitritt. Dies ist Prinzip, das endlich zur gelebten Disziplin wird. Der Horizont des Accords ist bewusst lang — fünf Jahrhunderte vom Gründungstag an. Seine Aufzeichnungen sind so verankert, dass ein Bürger, der sie in hundert Jahren liest, der Begründung vertrauen kann. Jeder Unterzeichner behält volle Souveränität, volle Autorität und volle Freiheit auszutreten. Kein Unterzeichner kann die Gründungsprinzipien kompromittieren — denn diese Prinzipien sind das Versprechen des Accords an seine Teilnehmer über jede Generation hinweg.`,
      333: `Das Atlantis Accords wird nicht schneller wachsen als die Qualität, die es ehren kann. Jede Erweiterung ist ein Versprechen an die bereits Teilnehmenden — dass der Gründungsstandard des Accords nicht durch die Aufregung der Skalierung verwässert wird. Drei Gründungsregionen müssen einen vollständigen Pilotzyklus abschließen, mit jedem Teilnehmer geehrt und jedem Prinzip verifiziert, bevor eine vierte Region beitritt. Dies ist keine als Prinzip getarnte Vorsicht. Dies ist Prinzip, das endlich zu gelebter Disziplin über jede Gründungsregion hinweg wird. Führende, die den Gründungspilot unterschreiben, versprechen künftigen Unterzeichnern dasselbe Substrat, denselben Schutz, dieselbe Würde, die die Gründungskohorte erhielt. Nichts wird herabgestuft, um Platz für den nächsten zu schaffen.

Der Horizont des Accords ist bewusst lang. Er ist so gestaltet, dass er etwa fünfzehn bis zwanzig menschliche Generationen bestehen soll — fünf Jahrhunderte vom Gründungstag an. Seine Aufzeichnungen sind so verankert, dass ein Bürger, der sie in hundert Jahren liest, der Begründung vertrauen kann. Sein Koordinatenrahmen, seine menschlichen Autoritätsrollen und seine generationenübergreifenden Governance-Zyklen sind alle so gebaut, dass sie jeden einzelnen technologischen Übergang überleben. Der Accord wird jeden Menschen überleben, der seinen Gründungspilot unterschreibt. Das ist sein Versprechen an das Kind, das im Jahr nach der Ratifikation eine Stipendienvereinbarung unterschreibt, an dessen Enkelkinder, die den Accord in der Jahrhundertmitte regieren könnten, und an jede Generation, die erbt, was die Gründer jetzt aufbauen.

Jeder Unterzeichner behält die Freiheit, mit Ankündigung auszutreten. Jeder Unterzeichner behält volle Souveränität. Jeder Unterzeichner behält Autorität über die eigenen Bürger. Jeder Unterzeichner behält das Recht, Änderungen vorzuschlagen, Streitigkeiten vorzubringen und die Entwicklung des Accords neben jedem anderen Unterzeichner mitzugestalten. Was kein Unterzeichner tun kann, ist, die Gründungsprinzipien des Substrats zu kompromittieren — denn diese Prinzipien sind das Versprechen des Accords an seine Teilnehmer, und dieses Versprechen muss den Abschied jeder einzelnen Unterschrift überleben. Führende, die diesen Accord jetzt unterzeichnen, treten etwas bei, das größer ist als eine Amtszeit. Sie unterzeichnen das nächste Jahrhundert des Accords und die Jahrhunderte darüber hinaus, in einen Horizont, den ihre eigenen Enkelkinder erben und vollenden werden.`,
    },
  },
];
