import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_ES: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Donde comienza la innovación`,
    content: {
      7: `Los líderes inician lo que ningún siglo inició.`,
      33: `Tres regiones —Camboya, Honduras, Austin— abren una promesa que los ciudadanos ayudan a construir: acoger a quienes aprenden, protegerlos, entregarles las herramientas del futuro. Gobierno, Educación e Innovación firman como custodios; los ciudadanos la sostienen. Un solo comienzo.`,
      111: `Los Acuerdos de Atlantis son un pacto entre ciudadanos del mundo: una promesa que cualquier persona, en cualquier lugar, puede crear y sostener, sin importar lo que firme su gobierno o permita su empleador. Sus regiones fundadoras, Camboya, Honduras y Austin, Texas, fueron elegidas por una cualidad poco común: la disposición a confiar a los jóvenes las herramientas del futuro mientras aún hay tiempo de enseñarles a usarlas. Gobiernos, educadores e innovadores firman como custodios de sus regiones —tres firmas visionarias cada una: Gobierno, Educación, Innovación— pero son los ciudadanos quienes financian el acuerdo, presencian su trabajo y lo hacen rendir cuentas directamente. No se requiere el permiso de ningún gobierno ni la bendición de ningún empleador para pertenecer. Tres regiones, un mismo comienzo.`,
      333: `Toda civilización se recuerda por aquello que eligió comenzar. Los Acuerdos de Atlantis son una promesa entre ciudadanos del mundo: cualquier persona, en cualquier lugar, puede comenzarla, sin importar lo que firme su gobierno. Sus regiones fundadoras, Camboya, Honduras y Austin, Texas, no fueron elegidas por poder económico, fuerza militar o prestigio institucional, sino por una cualidad más rara: la disposición a confiar a los jóvenes las herramientas del futuro. Esto es lo que significa el liderazgo en el siglo que viene: el coraje de entregar las llaves a la siguiente generación mientras aún hay tiempo de enseñarle a conducir.

El acuerdo es convocado por eXeL, una fuerza organizadora construida a propósito para este momento, que existe fuera de los canales de coordinación que definieron el siglo pasado: fuera de las estructuras de tratados diplomáticos, de las burocracias multilaterales y de las ataduras políticas de cualquier Estado-nación en particular. eXeL es el convocante de confianza que reúne a líderes visionarios en torno a un marco compartido, un volante de impulso compartido y un horizonte compartido de quinientos años. Cada firmante conserva su plena soberanía, su plena autoridad sobre sus propios ciudadanos y su plena libertad de retirarse en cualquier momento. Lo que los firmantes ganan —y lo que gana cualquier ciudadano, al precio de un Seed, una séptima parte de una hora de salario mínimo local— es el efecto de red que solo un marco construido a propósito puede ofrecer: coordinación sin ninguna forma de dominación política.

Firmar el acuerdo es firmar una promesa: que la región acogerá a quienes aprenden a través de las culturas, aportará lo que solo ella puede ofrecer, y se exigirá a sí misma un estándar más alto que el que exige la regulación vigente —de forma pública, transparente, respondiendo ante los ciudadanos que la financian, la presencian y la hacen rendir cuentas, sin que se requiera el permiso de ningún gobierno ni la bendición de ningún empleador para pertenecer. Cada región debe reunir tres firmas —Gobierno, Educación e Innovación— que firman como custodios, no como dueños. Hacen falta tres visionarios para decir que sí, y ciudadanos para sostener lo que firmaron. Tres visionarios, tres regiones, un comienzo: así es como un marco cobra vida, a través de la confianza de líderes dispuestos a firmarlo para que exista.`,
      999: `Toda civilización se recuerda por aquello que eligió comenzar, y Vision • 2525 pide a los fundadores de esta que comiencen con humildad y no con conquista. Los Acuerdos de Atlantis son una promesa hecha por líderes dispuestos a comenzar algo que nunca antes existió: un cimiento compartido para la innovación humana que llega a cada rincón del mundo, honra cada voz y perdura a través de generaciones medidas no en años, sino en siglos. Sus firmantes fundadores en Camboya, Honduras y Austin, Texas, no fueron elegidos por poder económico, fuerza militar o prestigio institucional. Fueron elegidos por una cualidad más rara: la disposición a confiar a los jóvenes las herramientas del futuro, y la paciencia de dejar que un horizonte de quinientos años sobreviva al aplauso de cualquier gobierno de turno. Esto es lo que significa el liderazgo en el siglo que viene: el coraje de entregar las llaves a la siguiente generación mientras aún hay tiempo de enseñarle a conducir.

El acuerdo es convocado por eXeL, una fuerza organizadora construida a propósito para este momento. eXeL existe fuera de los canales de coordinación que definieron el siglo pasado: fuera de las estructuras de tratados diplomáticos, fuera de las burocracias multilaterales, fuera de las ataduras políticas de cualquier Estado-nación. eXeL es el convocante de confianza que reúne a líderes visionarios en torno a un marco compartido, un volante de impulso compartido y un horizonte compartido de quinientos años. Cada firmante conserva su plena soberanía, su plena autoridad sobre sus propios ciudadanos y su plena libertad de retirarse en cualquier momento. Lo que los firmantes ganan es el efecto de red que solo un marco construido a propósito puede ofrecer. El ingreso de cada participante a ese marco comienza siempre del mismo modo modesto: con un Seed, una membresía única cuyo precio es una séptima parte de una hora de salario mínimo local, intransferible y sin conllevar ningún tipo de reclamo económico. Un Seed no compra propiedad ni promesa de recompensa alguna, solo pertenencia: el derecho a situarse dentro del marco y comenzar. Esto es coordinación sin ninguna forma de dominación política, construida sobre un comienzo lo bastante pequeño como para que cualquiera pueda costearlo.

Porque la soberanía se conserva en lugar de cederse, el acuerdo está construido para la Continuity Without Evasion. Ningún gobierno, banco, fundador o modelo indispensable puede retener como rehén al marco entero para garantizar su propia supervivencia. Cada jurisdicción se atiende a través de su adaptador legal propio, en modo de rechazo por defecto hasta que se demuestre el cumplimiento, de manera que el valor solo circule por vías que un tribunal de esa jurisdicción reconocería como legítimas. Si un regulador de una región emite un fallo adverso, esa única vía se cierra de forma segura —de manera transparente, sin dañar a ningún participante dentro de ella— mientras todas las demás regiones continúan sin alteración. El acuerdo entero nunca cae porque un gobierno haya cambiado de parecer. Esto es portabilidad diseñada como promesa fundacional, no como contingencia descubierta después de la crisis.

Firmar el acuerdo es firmar una promesa. Que la región acogerá a quienes aprenden a través de las culturas. Que la región aportará lo que solo ella puede ofrecer. Que la región se exigirá a sí misma un estándar más alto que el que exige la regulación vigente. Que la región lo hará de forma pública, transparente, a la vista de cada ciudadano al que sirve. Cada región debe reunir tres firmas —Gobierno, Educación e Innovación—. Ningún cargo por sí solo compromete al acuerdo. Hacen falta tres visionarios para decir que sí. Esta firma triple es la primera expresión de Human Authority: el sentido, el dinero y la ley permanecen en manos humanas en la capa soberana, una capa cerrada de manera permanente a las máquinas, sin importar cuán capaces lleguen a ser. El Measurement of Time, MoT, comienza a registrar desde el momento de la firma —minutos reales de trabajo humano real, mantenidos aparte de cualquier estimación automatizada— y cada entrega posterior del trabajo del acuerdo está construida para poder reconstruirse mediante Replay, de modo que un ciudadano que nazca dentro de un siglo pueda rastrear cómo se tomaron hoy las decisiones fundacionales.

Lo que el piloto funda es medición antes que dinero. Toda innovación que ingresa al marco se puntúa mediante el Puntaje de Innovación Calificada, QIS: el promedio de Ingresos, Utilidad Bruta, Utilidad Operativa y gasto efectivo en I+D, dividido entre cuatro. El QIS no es pago ni jamás propiedad; es el instrumento con el que una cohorte fundadora aprende a ver su propio progreso antes de que se dimensione recompensa alguna. El crecimiento del QIS, una vez cumplida la calificación, dimensiona el fondo de recompensas que sigue, pero el crecimiento del QIS no acuña nada por sí mismo. Tres regiones, un comienzo, y una disciplina compartida: probar el puntaje antes de tocar el tesoro.

El valor obtenido mediante trabajo presenciado lleva su propio nombre, 웃, calculado como una hora multiplicada por el salario mínimo local, escalado por un Múltiplo aplicado sobre las horas servidas. El 웃 se emite únicamente por trabajo presenciado dentro de una tarea acotada y aprobada en presupuesto; cualquier cosa que no alcance esa aprobación sigue siendo planificación, y la planificación por sí sola no acuña nada. Un tope de liquidación de 9,999 웃 por año protege a cada participante de una concentración desbordada, y todo excedente se traslada hacia adelante en lugar de desvanecerse. Detrás de cada 웃 está ♡, la Intención Compartida, que lleva el porqué por el cual una tarea fue aprobada en primer lugar, y ◬, la aceleración presenciada que una tarea produjo frente a una línea base congelada: un delta únicamente, jamás confundido con una métrica de ganancia. El piloto existe para probar que estos tres glifos pueden moverse juntos con honestidad, región tras región, antes de que el marco escale más allá de sus fundadores.

Cuando el valor llega a una persona, le llega a través de Livelihood Direct —🏠— vías locales licenciadas y calificadas que eXeL nunca custodia como fondo propio. La clasificación precede a la liquidación en todos los casos, y el reconocimiento de una contribución nunca es la puerta de acceso a una cama para pasar la noche; solo lo es el rol de la persona dentro de una tarea acotada. El crecimiento más allá del piloto también está condicionado: cada cubo del marco avanza de Manual a Semiautomático y a Autónomo solo tras superar la regla del 11,1 por ciento, una parte en nueve de mejora medida, ganada cubo por cubo y nunca reclamada en bloque, y nunca, bajo ninguna circunstancia, sobre la capa soberana del sentido, el dinero y la ley. Así es como tres visionarios por región, tres regiones y un comienzo se convierten en una promesa de quinientos años: no avanzando rápido, sino demostrando, a la vista de todos, que cada paso ganó el paso que le siguió.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Aprender a través de la simulación`,
    content: {
      7: `Practicar mil veces antes de tocar.`,
      33: `Nada consecuente se aprende primero en equipo real. Todo ciudadano puede ensayar en simulación, rotar entre tres regiones, celebrar: respeto por el joven humano cuyo primer error nunca debería costarle la vida.`,
      111: `Toda disciplina que vale la pena dominar fue aprendida por alguien antes de ser conocida. Los Acuerdos de Atlantis devuelven esta sabiduría ancestral al centro de cómo se prepara a los jóvenes —y a todo ciudadano que se sume— para construir el futuro. Nada consecuente se aprende primero en equipo real, con personas reales, o en condiciones irreversibles; no se requiere el permiso de ningún gobierno ni la bendición de ningún empleador. Cada participante practica en simulación hasta que la práctica se convierte en competencia, y luego en preparación. El modelo de rotación lleva a cada participante a través de las tres regiones fundadoras, y cada rotación culmina en una celebración pública abierta a la comunidad anfitriona. Esto es respeto por el joven humano cuyo primer error nunca debería costarle la vida.`,
      333: `Toda disciplina que vale la pena dominar fue aprendida por alguien antes de ser conocida. Los maestros artesanos ensayan antes de actuar, los pilotos antes de volar, los médicos antes de operar, los niños a través del juego. Los Acuerdos de Atlantis devuelven esta sabiduría ancestral al centro de cómo se prepara a los jóvenes —y a todo ciudadano que se sume, sin requerir el permiso de ningún gobierno ni la bendición de ningún empleador— para construir el futuro. Nada consecuente se aprende primero en equipo real, con personas reales, o en condiciones irreversibles. Cada participante practica en simulación hasta que la práctica se convierte en competencia, y luego en preparación. Esto no es cautela: es respeto por el joven humano cuyo primer error nunca debería costarle la vida a nadie.

El modelo de rotación del acuerdo lleva a cada participante a través de las tres regiones fundadoras. Lo que se aprende en Camboya se refina en Honduras y se completa en Austin. Lo que se descubre en Austin se cuestiona en Camboya y se integra en Honduras. Cada participante vive, aprende y recibe mentoría a través de culturas que de otro modo permanecerían distantes. El plan de formación se nutre de tradiciones de simulación disciplinada de muchas culturas —de la tradición de educación estratégica de Sun Tzu, del aprendizaje a través del juego de Musashi, de la teoría del aprendizaje cíclico de Ibn Khaldun, de la dialéctica monástica de Nalanda, del simulador de vuelo civil— sintetizadas para respetar cada etapa cognitiva y cada herencia cultural. Ninguna tradición predomina sobre las demás.

Cada rotación culmina en una celebración pública abierta a la comunidad anfitriona, donde vecinos, familias y visitantes ven lo que la cohorte ha aprendido. Estos eventos hacen que la tecnología sofisticada resulte accesible y celebrada en lugar de temida: una sociedad que crece entendiendo los sistemas cooperativos a través del juego no puede ser manipulada fácilmente por el miedo hacia ellos. Esto es disuasión a través de la educación, no a través de la fuerza. La promesa del acuerdo a cada padre y madre: su hijo o hija practicará mil veces en condiciones seguras antes de tocar algo que pudiera hacerle daño, todo presenciado, de modo que un ciudadano —cualquier ciudadano, dentro de un siglo— pueda verificar que ocurrió exactamente como quedó registrado. Esto es respeto por el joven humano diseñado dentro de un marco, y es lo que el liderazgo le debe al próximo ciudadano que se sume, antes de que ese ciudadano tenga que exigirlo.`,
      999: `Toda disciplina que vale la pena dominar fue aprendida por alguien antes de ser conocida, y toda civilización que perduró lo hizo porque protegió el espacio donde ese aprendizaje podía ocurrir con seguridad, antes de que se le pidiera importar de verdad. Los maestros artesanos ensayan antes de actuar, los pilotos ensayan antes de volar, los médicos ensayan antes de operar, y los niños ensayan el mundo a través del juego. Los Acuerdos de Atlantis devuelven esta sabiduría ancestral al centro de cómo se prepara a los jóvenes para construir el futuro, y le dan a esa sabiduría un nombre y un mecanismo: Replay. Nada consecuente se aprende primero en equipo real, con personas reales, o en condiciones irreversibles. Cada participante practica en simulación hasta que la práctica se convierte en competencia, y luego en preparación, y cada hora de esa práctica queda registrada para poder reconstruirse después, examinarse después, confiarse después. Esto no es cautela: es respeto por el joven humano cuyo primer error nunca debería costarle la vida a nadie, y es respeto por el registro que, de cualquier modo, sobrevivirá al error.

El modelo de rotación del acuerdo lleva a cada participante a través de las tres regiones fundadoras. Lo que se aprende en Camboya se refina en Honduras y se completa en Austin. Lo que se descubre en Austin se cuestiona en Camboya y se integra en Honduras. Cada participante vive, aprende y recibe mentoría a través de culturas que de otro modo permanecerían distantes, y cada rotación comienza como comienza toda institución humana digna de confianza: con un Seed. El Seed es una membresía única, cuyo precio es una séptima parte de una hora de salario mínimo local, intransferible, sin conllevar ningún tipo de reclamo económico. No es una tarifa de acceso a la oportunidad. Es un umbral, lo bastante pequeño como para que ningún participante dispuesto quede excluido por precio, y lo bastante deliberado como para que el ingreso sea una elección y no una deriva. A partir de ese umbral, cada participante pertenece a la rotación, y la rotación no pertenece a una sola región.

El plan de formación se nutre de tradiciones de simulación disciplinada de muchas culturas —de la tradición de educación estratégica de Sun Tzu, del aprendizaje a través del juego de Musashi, de la teoría del aprendizaje cíclico de Ibn Khaldun, de la dialéctica monástica de Nalanda, del simulador de vuelo civil— sintetizadas para respetar cada etapa cognitiva y cada herencia cultural. Ninguna tradición predomina. Y dentro de este plan de formación, el acuerdo traza una línea que cada participante aprende temprano y nunca olvida: la simulación es donde se comprende el Puntaje de Innovación Calificada, no donde se gasta. El QIS es medición, nunca pago, y el QIS nunca es propiedad: existe para describir qué tan bien razona una propuesta, si se sostiene, y a quién sirve la región que dice servir. El crecimiento del QIS puede dimensionar un fondo de recompensas después de una calificación real, pero no acuña nada por sí mismo. Un participante puede correr cien simulaciones impecables y obtener un puntaje ascendente sin que ni una sola hora de 웃 toque su registro, porque el 웃 se emite únicamente por trabajo presenciado realizado dentro de una tarea acotada y aprobada en presupuesto. Antes de esa aprobación, todo —por hábil, por prometedor que sea— es planificación. El acuerdo enseña esta distinción desde el primer día, para que ningún joven confunda el ensayo con la recompensa, y para que ningún joven sea jamás engañado sobre el propósito de la simulación.

Esta misma disciplina gobierna cuánta autonomía puede ejercer cualquier sistema, humano o artificial, dentro de la rotación. Los modos de operación del acuerdo avanzan en secuencia —Manual, luego Semiautomático, luego Autónomo— y ningún cubo avanza de modo hasta superar la regla del 11,1 por ciento de mejora medida, una parte en nueve, demostrada frente a una línea base congelada y presenciada, no simplemente afirmada. La simulación es donde se construye esa prueba. Una herramienta gana el derecho a actuar con menos supervisión del mismo modo en que un participante gana el derecho a mayor responsabilidad: mediante mejora demostrada, registrada y reconstruible, cubo por cubo, nunca de una sola vez, y nunca sobre la capa donde se decide el sentido, el dinero y la ley. Esa capa pertenece únicamente a Human Authority, tanto en la simulación como en la operación real, porque un espacio de ensayo que enseña el límite equivocado enseña la lección equivocada de manera permanente.

Cada rotación culmina en una celebración pública y cooperativa, abierta a la comunidad anfitriona. Vecinos, familias y visitantes se reúnen para ver lo que la cohorte ha aprendido, y lo que presencian no es una demostración de velocidad por sí misma, sino una demostración de ◬: el delta medido entre una línea base congelada y lo que la práctica disciplinada realmente logró, presentado con honestidad, jamás disfrazado de métrica de ganancia, jamás presentado como algo más de lo que es. Estos eventos hacen que la tecnología sofisticada resulte accesible y celebrada en lugar de temida. Una sociedad que crece entendiendo los sistemas cooperativos a través del juego no puede ser manipulada fácilmente por el miedo hacia esos sistemas. Esto es disuasión a través de la educación, no disuasión a través de la fuerza, y funciona porque a la comunidad no se le pide que confíe en una afirmación: se le invita a presenciar el Replay.

La promesa del acuerdo a cada padre y madre va más allá de la seguridad y llega hasta la permanencia: su hijo o hija practicará mil veces antes de tocar algo que pudiera hacerle daño, la comunidad presenciará su crecimiento en todo momento, y nada de eso se perderá con el tiempo. El Measurement of Time registra los minutos reales por separado de cualquier otro libro que lleve el acuerdo, de modo que las horas practicadas y las horas presenciadas nunca se confundan entre sí, y de modo que la verdadera historia de desarrollo de un participante —no un resumen, no una aproximación, sino el registro reconstruible mismo— permanezca disponible para ese participante durante todo el tiempo que desee consultarla. Un padre en Phnom Penh, un mentor en Tegucigalpa, un auditor en Austin, o un nieto que lea el registro dentro de un siglo, pueden todos acceder al mismo Replay y ver la misma verdad.

Esto es lo que significa el respeto por el joven humano cuando se lo diseña dentro de un marco en lugar de solo prometerlo, y esto es lo que el liderazgo entrega a la próxima generación de participantes antes de que esa generación tenga que exigirlo: un espacio de ensayo lo bastante amplio como para fallar con seguridad, lo bastante honesto como para registrar con fidelidad, y lo bastante disciplinado como para mantener la recompensa, la autonomía y la autoridad exactamente donde la maestría las ha ganado: en ningún punto por delante de ella, y en ninguno por detrás.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Seguridad probada antes de extender la confianza`,
    content: {
      7: `Seguridad probada primero, luego confianza extendida.`,
      33: `Cada instalación y cada rotación se ubican dentro de una envolvente protectora con alerta temprana. El hardware se niega a la militarización: demostrable, no prometida, inspeccionable por los ciudadanos. Los registros sobreviven a la turbulencia. La seguridad se diseña, día a día, alrededor del participante más joven.`,
      111: `Antes de extender la confianza, la seguridad debe demostrarse: no ante un gobierno, sino ante cualquier ciudadano que la inspeccione. Los Acuerdos de Atlantis son un pacto entre ciudadanos del mundo; su compromiso fundacional es este: cada instalación del acuerdo, cada ruta de rotación, cada lugar donde un joven participante duerme o estudia se ubica dentro de una envolvente protectora documentada con capacidad de alerta temprana que da a la comunidad horas, no minutos, para responder a cualquier riesgo creíble. Cada dispositivo, cada sensor, cada sistema de coordinación está atado a nivel de hardware para negarse a ser reconvertido en integración de sistemas de armas. Esto no es política: es física. El acuerdo permanece honorable a través de la turbulencia, porque cada plan pone primero la dignidad humana.`,
      333: `Antes de extender la confianza, la seguridad debe demostrarse: demostrarse ante los ciudadanos, no simplemente afirmarse. Los Acuerdos de Atlantis son un pacto entre ciudadanos del mundo: cualquier persona, en cualquier lugar, puede ayudar a sostenerlo, sin importar lo que firme su gobierno. Cada instalación del acuerdo, cada ruta de rotación, cada lugar donde un joven participante duerme o estudia se ubica dentro de una envolvente protectora documentada con capacidad de alerta temprana que da a la comunidad horas, no minutos, para responder a cualquier riesgo creíble. La tecnología que los protege es la misma tecnología que el acuerdo les enseña a construir. Los jóvenes aprenden la seguridad de adentro hacia afuera, no porque se les diga que están seguros, sino al ver cómo se la diseña a su alrededor cada día, y al saber que cualquier ciudadano puede verificar el registro a través de Replay.

El acuerdo hace una promesa inquebrantable sobre aquello en lo que su tecnología no puede convertirse. Cada dispositivo, cada sensor, cada sistema de coordinación está atado a nivel de hardware para negarse a ser reconvertido en integración de sistemas de armas. Esto no es lenguaje de política, ni aspiración. Es una imposibilidad física, impuesta criptográficamente, verificada por cada región firmante, e inspeccionable por cada ciudadano que la financia. Las herramientas que protegen a un niño en Phnom Penh no pueden reconvertirse para dañar a un niño en Austin. Las herramientas que conectan un ejercicio de enjambre en Tegucigalpa no pueden reconfigurarse para apuntar contra ningún ser humano en ningún lugar. Esta es la respuesta del acuerdo a un siglo de temor por el uso dual. No política: física.

El acuerdo permanece honorable a través de la turbulencia. Si una región pierde estabilidad política, las regiones restantes sostienen a los participantes. Si el financiamiento se contrae, los estipendios se protegen primero —financiados mensualmente por los ciudadanos, nunca a través de un canal de ayuda, cada dólar trazable—. Si los registros digitales son atacados, persisten las copias de respaldo fuera de línea. Si el viaje se vuelve imposible, el sustrato continúa de forma virtual. Cada plan pone la dignidad humana —Human Authority sobre el sentido, el dinero y la ley— como su primera restricción de diseño. Los líderes que firman este acuerdo prometen que la seguridad se diseña, no se da por sentada: la protección que cualquier líder exigiría para su propio hijo, extendida ahora a cada ciudadano que ayuda a sostenerlo.`,
      999: `Antes de extender la confianza, la seguridad debe demostrarse: este es el compromiso fundacional de los Acuerdos de Atlantis, y se demuestra del mismo modo en que se demuestra cualquier otra afirmación dentro de Vision • 2525: no por aserción, sino por evidencia que los ciudadanos pueden inspeccionar. Cada instalación del acuerdo, cada ruta de rotación, cada lugar donde un joven participante duerme o estudia se ubica dentro de una envolvente protectora documentada con capacidad de alerta temprana que da a la comunidad horas, no minutos, para responder a cualquier riesgo creíble. La tecnología usada para proteger a los participantes es la misma tecnología que el acuerdo les enseña a construir: sensores, coordinación, capacidad de supervivencia de las comunicaciones, inteligencia distribuida. Los jóvenes aprenden la seguridad de adentro hacia afuera, en su propio idioma y en su propia región, no porque se les diga que están seguros, sino al observar, hora tras hora, cómo se diseña la seguridad a su alrededor cada día.

Esa observación no queda librada a la memoria ni a la confianza en la palabra de un facilitador. El Measurement of Time registra los minutos reales de cada simulacro, cada rotación, cada ejercicio de respuesta —por separado de cualquier afirmación de progreso, por separado de cualquier relato contado ese día—. El Replay hace que cada entrega del plan de formación, cada actualización de seguridad, cada revisión de hardware sea totalmente reconstruible, de modo que un padre en Tegucigalpa o un regulador en Phnom Penh pueda recorrer hacia atrás exactamente qué cambió, cuándo cambió y por qué cambió. Una envolvente protectora que no puede reproducirse mediante Replay es solo una promesa. Una envolvente protectora que puede reproducirse, minuto a minuto registrado, es una prueba. El acuerdo elige la prueba.

El acuerdo hace una promesa inquebrantable sobre aquello en lo que su tecnología no puede convertirse. Cada dispositivo, cada sensor, cada sistema de coordinación está atado a nivel de hardware para negarse a ser reconvertido en integración de sistemas de armas. Esto no es lenguaje de política, ni aspiración. Es una imposibilidad física, impuesta criptográficamente, verificada por cada región firmante, e inspeccionable por cada ciudadano. Las herramientas que protegen a un niño en Phnom Penh no pueden reconvertirse para dañar a un niño en Austin. Las herramientas que conectan un ejercicio de enjambre en Tegucigalpa no pueden reconfigurarse para apuntar contra ningún ser humano en ningún lugar. Esta es la respuesta del acuerdo a un siglo de temor por el uso dual. No política: física.

Una seguridad demostrada una vez no es una seguridad sostenida a lo largo de un horizonte de quinientos años. El acuerdo nombra su segundo compromiso Continuity Without Evasion: portabilidad legal a través de cada jurisdicción que el acuerdo toca, sin que ningún gobierno, banco, fundador o modelo indispensable se interponga entre un participante y su protección. Cada jurisdicción es atendida por su propio adaptador, de cierre seguro y rechazo por defecto, de modo que un fallo adverso en cualquier región cierra únicamente esa vía, nunca el marco entero, nunca todas las regiones, nunca a todos los participantes en todas partes a la vez. Una decisión judicial en un territorio firmante no puede apagar la envolvente de seguridad de un participante en otro lugar. Esto es lo que significa construir un sistema que sobrevive a la turbulencia ordinaria de la ley, la política y el cambio institucional, sin jamás pedirle a un participante que evada la ley para seguir protegido.

Cada capa de esta arquitectura protectora responde, en última instancia, a Human Authority. El sentido, el dinero y la ley nunca se delegan a las máquinas: la capa soberana que decide qué exige la seguridad, qué cuenta como riesgo creíble, y qué respuesta le debe una comunidad a sus miembros más jóvenes permanece cerrada a la inteligencia artificial, sin importar cuán capaz llegue a ser. Los sistemas del acuerdo se mueven únicamente a través de tres modos de operación —Manual, Semiautomático, Autónomo— y ningún sistema avanza de modo sin una mejora presenciada y medida de al menos una parte en nueve, el 11,1 por ciento, verificada y reproducible. La autonomía se gana, cubo por cubo, función por función, nunca se otorga en bloque, y nunca se extiende sobre las preguntas que determinan el sentido, el dinero o la ley. Un sensor puede aprender a detectar más rápido. Un sistema de coordinación puede aprender a enrutar con más eficiencia. A ninguno de los dos se le permite jamás decidir, por sí solo, qué debe confiarle una comunidad a sus niños.

El acuerdo está diseñado para permanecer honorable a través de la turbulencia, y nombra esa turbulencia de antemano en lugar de descubrirla en medio de una crisis. Si una región firmante pierde estabilidad política, las regiones restantes sostienen a los participantes. Si el financiamiento se contrae, los estipendios de los participantes se protegen primero, antes que la administración y la infraestructura. Si los registros digitales son atacados, persisten copias de respaldo fuera de línea, inalcanzables por cualquier falla que haya llegado a la red. Si el viaje se vuelve imposible, el sustrato continúa de forma virtual, de modo que una rotación no se detiene porque una frontera se cerró. Cada escenario está previsto, y cada plan pone la dignidad humana como su primera restricción de diseño, no como su última consideración una vez resueltos los presupuestos y la imagen pública.

El ingreso a este sistema ya demostrado comienza con el Seed: una membresía única, cuyo precio es una séptima parte de una hora de salario mínimo local, intransferible, y sin conllevar ningún reclamo económico sobre nada de lo que el acuerdo construya después. El Seed no compra seguridad; la seguridad se diseña mucho antes de que se plante cualquier Seed. Lo que el Seed compra es posición: el derecho a entrar a un marco ya demostrado, ya inspeccionado, ya atado por un hardware que no puede volverse contra la misma persona a la que existe para proteger. Esta separación es deliberada. Una promesa de seguridad que debe comprarse con un peso económico real no es una promesa de seguridad en absoluto, sino solo un producto de seguridad. El acuerdo mantiene ambas cosas absolutamente separadas, para que ninguna familia tenga jamás que sopesar la protección de su hijo frente al presupuesto mensual del hogar.

Los líderes que firman este acuerdo firman una promesa: que la seguridad se diseña, no se da por sentada, y se demuestra, no simplemente se afirma. Lo que extienden a sus ciudadanos no es solo oportunidad, sino protección construida al estándar que merece el participante más joven —registrada por el Measurement of Time, reconstruible a través de Replay, atada a nivel de hardware contra todo mal uso que un siglo temeroso haya imaginado, y respondiendo, siempre y únicamente, a Human Authority. Esta es la misma protección que cualquier líder exigiría para su propio hijo al cruzar solo una frontera desconocida, ahora extendida a cada niño al que el acuerdo llegue a servir, a través de sus tres regiones fundadoras de Camboya, Honduras y Austin, y a través de los cinco siglos durante los cuales el acuerdo se propone mantener esta promesa.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Compensación, bienestar y dignidad humana`,
    content: {
      7: `Un estipendio, un mentor, un hogar.`,
      33: `Cada ciudadano recibe un estipendio desde el primer día: sin permiso de ningún gobierno, sin bendición de ningún empleador. El amor, la pérdida y la seguridad son infraestructura. El éxito se mide por el participante más vulnerable. La dignidad es sustrato, nunca decoración.`,
      111: `Los Acuerdos de Atlantis tratan a cada participante como un ser humano completo desde el primer día: un ciudadano que se sumó por derecho propio, no por decreto de gobierno ni por permiso de su empleador. Se proporciona un estipendio desde el momento en que comienza la participación, indexado al costo de vida de la región, y cada hora presenciada gana 웃, pagado a la persona a través de Livelihood Direct, nunca a través del libro contable de un empleador. El bienestar se trata como infraestructura de primer nivel, no como un beneficio adicional, sino como el sustrato sobre el cual se sostiene todo lo demás. Se sostienen tres dominios: Amor, Pérdida y Seguridad. El acuerdo mide el éxito por su participante más vulnerable, no por el promedio. Nadie queda olvidado para que los promedios luzcan bien. La dignidad como sustrato, no como decoración.`,
      333: `Los Acuerdos de Atlantis tratan a cada participante como un ser humano completo desde el primer día: un ciudadano que pertenece por derecho propio, sin necesitar el permiso de ningún gobierno ni la bendición de ningún empleador. Se proporciona un estipendio desde el momento en que comienza la participación, indexado al costo de vida de la región, y que llega antes de que las obligaciones familiares se conviertan en emergencias. Esto no es caridad. Es el reconocimiento de que la innovación humana común requiere, ante todo, seguridad humana: una mente no puede florecer mientras su hogar está bajo amenaza.

Lo que se gana más allá del estipendio se gana como lo gana cualquier ciudadano: a través del Seed, cuyo precio es una séptima parte de una hora de salario mínimo local, y a través del 웃, pagado únicamente por horas presenciadas. El QIS mide la promesa, pero no acuña nada: medición, nunca pago. Cada pago llega al participante a través de Livelihood Direct, vías locales licenciadas que el acuerdo nunca custodia, construidas para la Continuity Without Evasion.

El bienestar se trata como infraestructura de primer nivel, no como un beneficio adicional, sino como el sustrato sobre el cual se sostiene todo lo demás. El acuerdo nombra tres dominios en los que se sostiene a cada participante: Amor, en el sentido de conexión y límites saludables; Pérdida, porque el duelo debe acompañarse, no evitarse; y Seguridad, saber a quién llamar, en cada región, en el propio idioma. Se ofrece asesoramiento psicológico, círculos grupales, y prácticas culturales o espirituales honradas según la tradición de cada quien. Cero ideología impuesta; Human Authority, nunca una máquina, decide qué cuidado necesita un ciudadano.

El acuerdo mide el éxito por su participante más vulnerable, no por el promedio. Se atiende a los ciudadanos rurales sin banda ancha. Los participantes neurodivergentes reciben adaptaciones como norma. Los participantes con discapacidad encuentran cada instalación accesible. Los participantes de género diverso reciben vivienda segura y emparejamiento con mentores. Quienes no hablan el idioma local encuentran cada material en su propio idioma. Los participantes indígenas encuentran sus prácticas culturales honradas y su conocimiento tradicional protegido. Los líderes que firman este acuerdo prometen que ningún ciudadano será olvidado para que los promedios luzcan bien. Esto es dignidad como sustrato, no como decoración. Lo que se mide es lo que se honrará, y lo que aquí se honra es el ser humano entero —mente, cuerpo y espíritu—, sostenido por sus conciudadanos, sin excepción.`,
      999: `Los Acuerdos de Atlantis tratan a cada participante como un ser humano completo desde el primer día, construido en mecanismo, no solo en lenguaje. Se proporciona un estipendio desde el momento en que comienza la participación, indexado al costo de vida de la región, de modo que su impacto respete la dignidad local del trabajo. El estipendio llega antes de que las obligaciones familiares se conviertan en emergencias, y antes de que la dignidad se vea comprometida. Le señala a cada joven que su tiempo es valioso, que se anticipa su contribución, y que la estabilidad de su familia es parte de la responsabilidad del acuerdo. Esto no es caridad. Es el reconocimiento de que la innovación humana común requiere, ante todo, seguridad humana. Una mente no puede florecer mientras su hogar está bajo amenaza. El ingreso mismo conlleva un umbral pequeño y deliberado: el Seed, una membresía única cuyo precio es una séptima parte de una hora de salario mínimo local, intransferible y sin conllevar ningún reclamo económico propio. El Seed solo dice que una persona se ha sumado; no le paga nada ni le promete nada más allá de la puerta que le abre.

Lo que se gana después de que esa puerta se abre se gobierna con la misma precisión que el acuerdo aplica a cualquier otra promesa. El 웃, la medida de Inteligencia Humana del acuerdo, se calcula de manera simple: una hora al salario mínimo local, multiplicada por el Múltiplo que refleja la dificultad y el valor de la tarea, por las horas realmente trabajadas. Pero el 웃 se emite únicamente por trabajo presenciado realizado dentro de una tarea acotada y aprobada en presupuesto. Antes de que exista esa aprobación, lo que hace un participante es planificar, no ganar; una distinción que el acuerdo sostiene con firmeza porque protege tanto al tesoro como al participante de promesas hechas más rápido de lo que el valor puede verificarse. El Measurement of Time, MoT, registra los minutos realmente trabajados por separado de cualquier cálculo de compensación, de modo que el tiempo permanece como un hecho honesto y auditable, independiente del pago. Las horas de ningún participante se inflan, y las horas de ningún participante desaparecen. Un tope de liquidación de 9,999 웃 por año se aplica a cada participante, y todo excedente se traslada hacia adelante en lugar de desaparecer, de modo que una contribución excepcional se reconoce a lo largo de los años en lugar de quedar invisible dentro de uno solo.

La compensación se mantiene deliberadamente separada de la medición de la innovación. El Puntaje de Innovación Calificada, QIS, promedia los Ingresos, la Utilidad Bruta, la Utilidad Operativa y el gasto efectivo en I+D para describir cuánto creció realmente la innovación. Su crecimiento a lo largo del tiempo puede dimensionar un fondo de recompensas una vez cumplida la calificación, pero el QIS en sí mismo no acuña 웃 ni liquida nada directamente: es una medición, nunca un pago, y jamás se confunde con la propiedad de lo construido. Esta separación importa porque mantiene honestos tanto al estipendio como al salario: a un participante se le paga por horas presenciadas de trabajo real, no por un puntaje que pudiera manipularse, inflarse o discutirse. ♡, la Intención Compartida, lleva el porqué detrás de cada tarea que asume un participante; ◬, la aceleración presenciada que una tarea entrega frente a una línea base congelada, se registra únicamente como un delta, nunca disfrazada de métrica de ganancia atribuida al trabajo de ninguna persona. La compensación permanece siendo lo que es: un salario honesto por un tiempo honesto y presenciado.

El valor no se detiene en el cálculo: también debe llegar al participante como persona viva, y aquí es donde actúa 🏠, Livelihood Direct. Cada unidad de valor que gana un participante le llega a través de vías locales calificadas y licenciadas —bancos, operadores de dinero móvil, cooperativas ya confiables y reguladas en esa región— nunca a través de un fondo que el propio acuerdo custodie o controle. La clasificación del estatus de un participante precede a toda liquidación; nada se paga antes de que se comprenda apropiadamente a quién se le paga y por qué. Y el reconocimiento del talento, por más celebrado que sea, no es la puerta de acceso a una cama, una comida o un lugar en la cohorte; solo lo es el rol real del participante. Esta es una negativa deliberada a dejar que el prestigio sustituya a la provisión. Un colaborador brillante y uno discreto duermen bajo el mismo techo protegido, en los mismos términos, porque los compromisos de dignidad del acuerdo no son un premio otorgado por excelencia: son un piso bajo todos por igual.

El bienestar se trata como infraestructura de primer nivel, no como beneficio opcional, no como un extra de bienestar, sino como el sustrato sobre el cual se sostiene todo lo demás. El acuerdo nombra tres dominios fundacionales en los que se sostiene a cada participante: Amor, en el sentido de conexión, apego y límites saludables; Pérdida, porque todo participante experimentará duelo y debe ser acompañado, no evitado; y Seguridad, en el sentido de que todo participante sabe a quién llamar, en cada región, en su propio idioma. Se ofrece asesoramiento individual, círculos grupales, prácticas somáticas, y prácticas culturales o espirituales honradas según la propia tradición de cada participante. Cero ideología impuesta. El acuerdo sostiene ese espacio con reverencia; no hace proselitismo de ningún sistema de creencias. Human Authority gobierna cada una de estas decisiones: el sentido, el dinero y la ley permanecen cerrados a la determinación de las máquinas, sin importar cuán sofisticado sea el reconocimiento de patrones que asista a los seres humanos que deciden.

El acuerdo mide el éxito por el resultado de su participante más vulnerable, no por el promedio. Se atiende a los participantes rurales sin banda ancha. Los participantes neurodivergentes reciben adaptaciones como norma. Los participantes con discapacidad encuentran cada instalación accesible. Los participantes de género diverso reciben vivienda segura y emparejamiento con mentores. Quienes no hablan el idioma local encuentran cada material en su propio idioma. Los participantes indígenas encuentran sus prácticas culturales honradas y su conocimiento tradicional protegido. Los líderes que firman este acuerdo prometen que ningún participante será olvidado en silencio para que los promedios luzcan bien.

Cada vía de pago descrita aquí —el Seed, el estipendio, el 웃 ganado por trabajo presenciado, la vía de Livelihood Direct que lo entrega— está diseñada para la Continuity Without Evasion. Ningún banco, gobierno u operador local en particular es indispensable para la compensación de ningún participante; si una vía licenciada en una jurisdicción se cierra por un fallo adverso, solo esa vía falla, nunca el sistema entero, y nunca el derecho del participante a lo que se le debía. Esto es dignidad como sustrato, no como decoración. Lo que se mide es lo que se honrará, y lo que aquí se honra es el ser humano entero —mente, cuerpo y espíritu juntos—, pagado con honestidad, protegido plenamente, y jamás olvidado por ninguna contabilidad, sin excepción alguna.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Financiación y gobernanza`,
    content: {
      7: `Los ciudadanos financian directamente la próxima generación.`,
      33: `Los Acuerdos de Atlantis son un pacto entre ciudadanos: cualquiera puede financiarlo y sostenerlo. Sin canal de ayuda, sin benefactor extranjero, sin condicionamientos políticos. Cada dólar trazable, con cuentas publicadas mensualmente, en cada idioma.`,
      111: `Los Acuerdos de Atlantis son un pacto entre ciudadanos del mundo: cualquier persona, en cualquier lugar, puede ayudar a crearlo y a sostenerlo, sin importar lo que firme su gobierno o quién sea su empleador. Gobiernos, educadores e innovadores firman como custodios de sus regiones; son los ciudadanos quienes financian el acuerdo, lo presencian y lo hacen rendir cuentas directamente, cada uno aportando pequeñas cantidades voluntarias cada mes, lo bastante modestas como para que ningún adulto quede excluido por precio. No hay canal de ayuda, no hay benefactor extranjero, no hay condicionamiento político alguno. El acuerdo se mantiene independiente de las instituciones multilaterales que definieron el siglo pasado, no como declaración política, sino como una decisión de diseño. Cada dólar es trazable; las cuentas se publican mensualmente, en cada idioma.`,
      333: `Los Acuerdos de Atlantis son un pacto entre ciudadanos del mundo: cualquier persona, en cualquier lugar, puede ayudar a crearlo y a sostenerlo, sin importar lo que firme su gobierno o quién sea su empleador. Se financia con los ciudadanos a quienes sirve: los residentes de las regiones participantes aportan pequeñas cantidades voluntarias cada mes, lo bastante modestas como para que ningún adulto quede excluido por precio, y lo bastante significativas en conjunto como para sostener el trabajo del acuerdo a escala. Cuando un ciudadano financia directamente a la próxima generación, ese mismo ciudadano hace rendir cuentas al acuerdo directamente. No hay canal de ayuda, no hay benefactor extranjero, no hay condicionamiento político alguno. El alma del acuerdo es el ciudadano que aporta una pequeña cantidad cada mes, cuya participación lo hace posible.

Gobierno, Educación e Innovación firman como custodios de sus regiones —tres firmas visionarias que comprometen a una región a acoger, proteger y enseñar—, pero la custodia no es propiedad. El acuerdo es independiente de las instituciones multilaterales que han definido el siglo pasado: la Organización del Tratado del Atlántico Norte, la Organización Mundial de la Salud, las Naciones Unidas, el Fondo Monetario Internacional, el Banco Mundial, y todo canal nacional de ayuda exterior. Esta es una decisión de diseño, no una declaración política: un marco que sirve a cada región sin importar su alineamiento geopolítico no puede quedar atado a un solo alineamiento. Los gobiernos nacionales pueden contribuir de manera voluntaria. Las contribuciones son transparentes. Ninguna contribución compra influencia sobre el gobierno del acuerdo, venga de donde venga, jamás.

Cada dólar y cada unidad de valor que ingresa al acuerdo queda registrado de forma permanente, pública y trazable —reconstruible a través de Replay, de modo que un ciudadano dentro de un siglo pueda verificar la cadena intacta. El valor llega a un participante a través de horas de 웃 presenciadas y vías locales licenciadas, nunca a través de un fondo que el propio acuerdo custodie; el QIS mide con honestidad, nunca paga. El gasto administrativo tiene un tope, y los donativos corporativos tienen un tope junto a él. Se entrega una contabilidad completa en el idioma de cada región firmante, cada mes. Los líderes que firman el acuerdo prometen una transparencia que rara vez ofrece institución alguna. Esta es la confianza que el acuerdo exige: ganada una pequeña contribución trazable a la vez, a la vista de cada ciudadano.`,
      999: `Los Acuerdos de Atlantis se financian, en sí mismos, con los ciudadanos a quienes sirven, y ese único hecho define todo lo que se deriva de él: cada vía, cada libro contable, cada puerta que un joven debe atravesar para ser visto. Los residentes comunes de las regiones participantes aportan pequeñas cantidades voluntarias cada mes, lo bastante modestas como para que ningún adulto en ninguna región anfitriona quede excluido por precio, y lo bastante significativas en conjunto como para sostener el trabajo del acuerdo a una escala relevante. Este diseño es deliberado, y no es incidental a la misión: es la prueba de la misión. Cuando un ciudadano financia directamente la educación de la próxima generación, ese mismo ciudadano hace rendir cuentas al acuerdo directamente, en el mismo aliento, sin un intermediario que pudiera suavizar el balance o postergar la rendición de cuentas. No hay canal de ayuda, no hay benefactor extranjero, no hay condicionamiento político alguno atado al cheque. El alma del acuerdo es el ciudadano que aporta una pequeña cantidad cada mes, cuya participación hace posible el conjunto, y cuya participación sostenida es el único voto de confianza que, en última instancia, importa a lo largo de quinientos años.

El acuerdo es deliberadamente independiente de las instituciones multilaterales que han definido el siglo pasado: la Organización del Tratado del Atlántico Norte, la Organización Mundial de la Salud, las Naciones Unidas, el Fondo Monetario Internacional, el Banco Mundial, y todo canal nacional de ayuda exterior. Esto no es una declaración política sobre el valor de esas instituciones ni de sus contribuciones. Es una decisión de diseño, y es la misma decisión de diseño que gobierna cada vía técnica bajo el propio acuerdo: la Continuity Without Evasion. La portabilidad legal es la regla: ningún gobierno, banco, fundador o modelo indispensable en particular puede sostener por sí solo la estructura entera, porque un horizonte de quinientos años no puede depender de la permanencia de un solo actor. Cada jurisdicción lleva su propio adaptador, de cierre seguro y rechazo por defecto, de modo que un fallo adverso en una nación cierra únicamente esa vía, y solo esa: nunca derrumba las cuentas de una familia en una región al otro lado del océano. Los gobiernos nacionales pueden contribuir de manera voluntaria. Las contribuciones son transparentes. Ninguna contribución compra influencia sobre el gobierno del acuerdo, venga de donde venga, jamás: ni de un gobierno, ni de una corporación, ni de los propios fundadores del marco.

Human Authority es el segundo pilar de carga bajo este diseño de financiamiento. El sentido, el dinero y la ley siguen siendo asuntos humanos, decididos por seres humanos a la vista de otros seres humanos; la capa soberana donde se fija el propósito del acuerdo y se gobiernan sus fondos permanece cerrada a las máquinas, sin importar cuán capaces lleguen a ser en las tareas que quedan por debajo de ella. El Measurement of Time registra los minutos realmente trabajados por separado de cualquier afirmación sobre su valor, de modo que nadie —humano o artificial— pueda inflar el registro en silencio. El Replay respalda cada uno de esos registros, haciendo que cada entrega que el acuerdo emita sea reconstruible desde su origen, siempre abierta al cuestionamiento, siempre abierta a la corrección. Un ciudadano que aporta una pequeña cantidad hoy está confiando en que dentro de cincuenta años, dentro de doscientos años, alguien todavía pueda recorrer la cadena hasta el libro contable de este mes y encontrarlo exactamente como era.

El ingreso a este sistema de confianza comienza con el Seed: una membresía única, cuyo precio es una séptima parte de una hora de salario mínimo local, intransferible y sin conllevar ningún tipo de reclamo económico. El Seed no compra participación accionaria, ni voto ponderado por riqueza, ni posición privilegiada en la contabilidad que sigue. Compra únicamente pertenencia, a un precio lo bastante bajo como para que un joven en cualquier lugar donde opere el acuerdo pueda costear su ingreso. Todo lo que un miembro gana después de ese punto se gana, nunca se compra, y esa distinción es toda la arquitectura moral del acuerdo en miniatura.

El valor que sí fluye hacia una persona lo hace a través de 🏠 Livelihood Direct: vías locales calificadas y licenciadas que llevan el pago hasta la persona, nunca hacia un fondo que el propio marco custodie o controle. La clasificación precede a la liquidación en todos los casos; una cama, un estipendio, un lugar en la siguiente etapa de formación están condicionados por el rol y la preparación, nunca por el reconocimiento por sí solo, porque el reconocimiento es barato y un sustento no lo es. Esta es la cadena que realmente recorre la contribución mensual de un ciudadano: desde la cuenta del ciudadano, a través de una vía auditada, hacia el estipendio que recibe un joven, hacia el proyecto de innovación en el que se convierte el trabajo de ese joven, y de vuelta hacia afuera como una cuenta pública que cualquier ciudadano puede leer.

Cuánto vale ese trabajo se mide, no se da por sentado. El Puntaje de Innovación Calificada promedia la preparación, el potencial de crecimiento, el impacto de resultados y la preparación de ejecución en un solo número, y el crecimiento de ese puntaje dimensiona el fondo de recompensas solo después de cumplida la calificación: el QIS en sí mismo no acuña nada ni liquida nada; es medición, nunca pago, y aquí la medición nunca se confunde con propiedad. El pago por el trabajo humano llega, en cambio, como 웃, valorado en una hora multiplicada por el salario mínimo local, multiplicado a su vez por un múltiplo de horas realmente trabajadas y presenciadas, acotado y aprobado en presupuesto. Antes de que una tarea cuente con esa aprobación, el trabajo detrás de ella es planificación, no labor compensable, y a nadie se le paga por planificar. Un tope de 9,999 웃 por año, con todo excedente trasladándose hacia adelante en lugar de desvanecerse, evita que la cuenta de un solo año se convierta en una ganancia inesperada o en una trampa.

Nada de esto avanza más rápido que su propia prueba. El acuerdo mismo avanza de la operación Manual a la Semiautomática y a la Autónoma un cubo a la vez, y solo allí donde un orden completo de mejora medida —una parte en nueve— se ha demostrado realmente, nunca dado por sentado de antemano. La autonomía se gana exactamente ahí, y en ningún lugar cerca del sentido, el dinero o la ley, que permanecen humanos siempre. El gasto administrativo tiene un tope. Los donativos corporativos e institucionales son bienvenidos y también tienen un tope. Se entrega una contabilidad completa en el idioma de cada región firmante, cada mes, comenzando en Camboya, Honduras y Austin, y pensada para seguir entregándose, y seguir siendo legible, dentro de quinientos años. Esta es la confianza que el acuerdo exige. Esta es la confianza que el acuerdo se gana, una pequeña contribución trazable a la vez, a la vista de cada ciudadano al que llegue a servir.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Intercambio intercultural y contribución global`,
    content: {
      7: `Cada aprendiz en su propio idioma.`,
      33: `Cada actividad en el idioma del participante, abierta a todo ciudadano, sin requerir el permiso de ningún gobierno. Las inteligencias Artificial, Humana y Compartida se sostienen en tensión productiva. Los planes de estudio se publican abiertamente. Lo que aprende una región, lo heredan todos.`,
      111: `Los Acuerdos de Atlantis devuelven a la educación su propósito más profundo: el intercambio de sabiduría a través de fronteras que de otro modo dividirían. Todo ciudadano puede sumarse a este plan de estudios, sin importar lo que su gobierno haya firmado. Cada actividad está disponible en el idioma del participante, en el idioma de la región anfitriona, y en un registro compartido. El idioma no es decoración: el idioma es jurisdicción, el idioma es dignidad hecha legible. El marco educativo se sostiene sobre la trinidad de inteligencias: la Artificial propone, la Humana decide, la Intención Compartida valida. Cada estudiante aprende a sostener las tres en tensión. Lo que el acuerdo aprende, lo devuelve. Los planes de estudio, los resultados de innovación, la investigación sobre bienestar y las decisiones de gobierno se publican abiertamente. Lo que aprende una región, lo heredan todos los ciudadanos.`,
      333: `Los Acuerdos de Atlantis devuelven a la educación su propósito más profundo: el intercambio de sabiduría a través de fronteras que de otro modo dividirían. Este es un pacto entre ciudadanos del mundo: todo ciudadano puede construirlo y sostenerlo, sin importar lo que haya firmado su gobierno. Cada actividad está disponible en el idioma del participante, en el idioma de la región anfitriona, y en un registro compartido, de modo que ningún participante navega el acuerdo en una lengua que no eligió. El idioma no es decoración. El idioma es jurisdicción. El idioma es dignidad hecha legible. Un joven en Camboya lee el registro de su estipendio en jemer, en Honduras en español, en Austin en inglés: los tres honrados por igual, ninguno necesitando la bendición de un gobierno para comenzar.

El marco educativo se sostiene sobre la trinidad de inteligencias que Vision • 2525 hace visible. La Inteligencia Artificial propone patrones y posibilidades más rápido de lo que cualquier humano podría hacerlo solo. La Inteligencia Humana decide sobre seguridad, ética y dirección: preguntas que ninguna máquina debería responder, mantenidas bajo Human Authority. La Intención Compartida valida que las decisiones sirvan a los principios del acuerdo, de modo que ningún participante elija la excelencia por encima del bien colectivo. Ningún estudiante se somete a una sola inteligencia; cada estudiante aprende a sostener las tres en tensión. La pertenencia comienza con el Seed, una membresía cuyo precio es una séptima parte de una hora de salario mínimo local, lo bastante pequeña como para que cualquier ciudadano pueda costearla. Esto prepara a la próxima generación para gobernar, allí donde ninguna inteligencia actúa sin control.

Lo que el acuerdo aprende, lo devuelve. Los planes de estudio se publican bajo licencia abierta para que cualquier región —firmante o no— pueda adaptarlos a su cultura local. Los resultados de innovación se publican. La investigación sobre bienestar se publica de forma agregada para investigadores en todas partes. Las decisiones de gobierno se publican junto con su razonamiento, de modo que cualquier ciudadano, no solo un gobierno firmante, pueda verificarlas —y el Replay le permite a ese mismo ciudadano rastrear el razonamiento dentro de un siglo. El éxito se mide no solo por sus participantes, sino por las iniciativas educativas y culturales que surgen a su paso, en regiones que nunca firmaron el piloto pero que construyeron sobre su sabiduría compartida. Lo que aprende una región, lo hereda cada ciudadano.`,
      999: `Los Acuerdos de Atlantis devuelven a la educación su propósito más profundo: el intercambio de sabiduría a través de fronteras que de otro modo dividirían, y ese intercambio comienza antes de que se dicte una sola lección. El primer acto de cada participante dentro del marco es el Seed: una membresía única cuyo precio es una séptima parte de una hora de salario mínimo local, intransferible, sin conllevar ningún tipo de reclamo económico. Es lo bastante pequeña como para que ninguna familia quede excluida, y lo bastante real como para que ningún participante ingrese como espectador. Esta es la primera lección del acuerdo: la pertenencia se gana barato, pero se gana de todos modos, y no confiere propiedad alguna sobre lo que viene después. Cada actividad del acuerdo que sigue está disponible en el idioma del participante, en el idioma de la región anfitriona, y en un registro compartido, de modo que ningún participante navega el acuerdo en una lengua que no eligió. El idioma no es decoración. El idioma es jurisdicción. El idioma es dignidad hecha legible. Cuando un joven de una aldea camboyana lee el registro de su estipendio en jemer, uno de un pueblo hondureño en español, y uno de un barrio de Austin en inglés, los tres son honrados por igual por el mismo acuerdo, en las mismas regiones fundadoras que primero acordaron enseñarse mutuamente.

El marco educativo del acuerdo se sostiene sobre la trinidad de inteligencias que Vision • 2525 hace visible, y el plan de estudios enseña cada una como algo que un participante puede sentir con sus propias manos, no como abstracción. ♡, la Intención Compartida, lleva el porqué: el hilo que cada estudiante aprende a sostener antes de tocar cualquier herramienta, la pregunta de si este trabajo todavía sirve a las personas a las que dice servir. ◬, la aceleración presenciada, se enseña como un delta y nada más: medida únicamente frente a una línea base congelada, jamás disfrazada de métrica de ganancia, jamás reclamada como logro personal aparte del equipo que rodea a quien la produjo. 웃, la Inteligencia Humana honrada en el tiempo, se enseña con el mayor cuidado: una hora de trabajo presenciado equivale a una hora al salario mínimo local, y lo que gana un participante es ese salario multiplicado por las horas trabajadas: Múltiplo por Tiempo, sin nada oculto en la aritmética. Los estudiantes aprenden temprano que el 웃 se emite únicamente por trabajo presenciado realizado dentro de una tarea acotada y aprobada en presupuesto. Antes de que exista esa aprobación, el mismo esfuerzo es solo planificación: valiosa, pero no pagada, y a cada participante se le enseña a reconocer la diferencia a simple vista.

Porque esa diferencia se difumina con facilidad, el plan de estudios enseña el QIS, el Puntaje de Innovación Calificada, como un espejo y no como un marcador. El QIS es el promedio de cuatro cifras financieras absolutas —Ingresos, Utilidad Bruta, Utilidad Operativa y gasto efectivo en I+D— dividido entre cuatro, y cada estudiante aprende a calcularlo, a cuestionarlo, y a nunca confundirlo con dinero. El crecimiento del QIS dimensiona el fondo de recompensas solo después de que la calificación se confirma de manera independiente, y ese crecimiento no acuña ningún 웃 por sí mismo. El QIS es medición. El QIS nunca es pago. El QIS nunca es propiedad. Un estudiante que ha internalizado esta distinción no puede ser persuadido de que un puntaje alto le da derecho a un reclamo que el acuerdo nunca prometió.

El plan de estudios extiende esta alfabetización hasta cómo el valor realmente llega a una persona, a través de lo que el acuerdo llama Livelihood Direct: el principio 🏠 de que el dinero se mueve a través de vías locales calificadas y licenciadas, y nunca a través de un fondo que el propio marco custodie. A los estudiantes se les enseña a rastrear su estipendio, y más tarde sus propias ganancias, a través de estas vías como un ejercicio cívico, no como un misterio financiero resuelto en otro lugar en su nombre. Aprenden que la clasificación siempre precede a la liquidación, y que el reconocimiento —un QIS alto, una mención pública— no es, por sí solo, la puerta de acceso a una cama, un estipendio o un lugar en la rotación. Lo es el rol. Esto es protección contra una falla muy antigua: confundir el elogio con la provisión.

Junto a la alfabetización financiera se encuentra la alfabetización cívica, enseñada a través de la Continuity Without Evasion. Cada participante aprende que el acuerdo está construido para la portabilidad legal: que ningún gobierno, banco, fundador o modelo indispensable en particular se interpone entre ellos y las promesas del marco. Aprenden qué hace un fallo adverso dentro de este diseño: cierra una vía, en una jurisdicción, bajo la postura de rechazo por defecto de ese adaptador, y nunca derrumba el conjunto. Junto a esto está la lección más profunda que enseña el acuerdo: Human Authority conserva el sentido, el dinero y la ley, y la capa soberana donde se toman esas decisiones permanece cerrada de manera permanente a las máquinas. El Measurement of Time, MoT, registra los minutos reales de cada participante por separado de cualquier puntaje, y el Replay hace que cada entrega que emite el acuerdo sea totalmente reconstruible, de modo que un estudiante que quiera saber por qué se tomó una decisión, años después, pueda rastrearla por sí mismo en lugar de fiarse de la palabra de alguien.

Esta estructura de confianza ganada se convierte en el modelo pedagógico del acuerdo, no solo en su modelo de gobierno. Cada participante avanza a través de los modos Manual, Semiautomático y Autónomo, de latitud creciente, condicionados por el mismo umbral de mejora medida que condiciona a la propia tecnología: una ganancia verificada del 11,1 por ciento antes de que se abra el siguiente modo. La autonomía, cuando se gana, se gana de forma estrecha y por dominio, nunca sobre el sentido, el dinero o la ley. Un estudiante que ha vivido esta progresión comprende, de manera visceral, por qué la capa soberana nunca debe automatizarse, porque ganó su propia autonomía un paso medido a la vez, y sabe exactamente qué incluyó esa autonomía y qué no.

Lo que el acuerdo aprende, el acuerdo lo devuelve. Los planes de estudio se publican bajo licencia abierta para que cualquier región —firmante o no— pueda adaptarlos a su cultura y a su tradición pedagógica local. Los resultados de innovación se publican. La investigación sobre bienestar se publica de forma agregada para investigadores en todas partes. Las decisiones de gobierno se publican con su razonamiento completo intacto. El éxito del acuerdo se mide no solo por sus propios participantes en Camboya, Honduras y Austin, sino por las iniciativas que surgen a su paso, en regiones que nunca firmaron el piloto fundacional pero que construyeron sobre su sabiduría compartida abiertamente, a lo largo de un horizonte que los fundadores no vivirán para ver completado. Lo que aprende una región, lo heredan todas las demás, y lo que esta generación aprende con honestidad, los próximos quinientos años no tendrán que desaprender.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Crecimiento sostenible de la red`,
    content: {
      7: `Nunca más rápido que la dignidad.`,
      33: `Tres regiones fundadoras completan un ciclo piloto entero antes de que se sume una cuarta: cualquier ciudadano puede construirlo. Los registros quedan anclados para perdurar cinco siglos. Los firmantes conservan su soberanía; nada se rebaja para el siguiente que se sume.`,
      111: `Los Acuerdos de Atlantis no crecerán más rápido de lo que la calidad les permite honrar. Tres regiones fundadoras deben completar un ciclo piloto entero, con cada participante honrado y cada principio verificado, antes de que se sume una cuarta región. Este es el principio convertido, por fin, en disciplina de trabajo. Pero el acuerdo es un pacto entre ciudadanos del mundo: cualquier persona, en cualquier lugar, puede construirlo y sostenerlo, a solo un Seed de distancia, sin importar lo que firme un gobierno o permita un empleador. El horizonte del acuerdo es de cinco siglos. Sus registros quedan anclados a través de Replay, de modo que un ciudadano que los lea dentro de un siglo pueda confiar en el razonamiento. Cada firmante conserva su soberanía; nada se rebaja para el siguiente que se sume.`,
      333: `Los Acuerdos de Atlantis no crecerán más rápido de lo que la calidad les permite honrar. Cada expansión es una promesa a los participantes que ya están dentro: que el estándar fundacional no se diluirá con la escala. Tres regiones fundadoras deben completar un ciclo piloto entero, con cada participante honrado y cada principio verificado, antes de que se sume una cuarta región. Este es el principio convertido, por fin, en disciplina de trabajo. Y la puerta nunca fue solo regional: este es un pacto entre ciudadanos del mundo, y cualquier persona puede construirlo, financiarlo y hacerlo rendir cuentas, sin requerir el permiso de ningún gobierno ni la bendición de ningún empleador. Los líderes que firman el piloto prometen a los futuros firmantes el mismo sustrato, la misma protección y la misma dignidad que recibió la cohorte fundadora. Nada se rebaja para el siguiente.

El horizonte del acuerdo es deliberadamente largo: diseñado para perdurar entre quince y veinte generaciones humanas, cinco siglos desde el día fundacional. Sus registros quedan anclados a través de Replay, de modo que un ciudadano que los lea dentro de un siglo pueda verificar el razonamiento, no solo confiar en él. Su marco de coordenadas, sus roles de Human Authority, y sus ciclos de gobierno intergeneracionales están construidos para sobrevivir a cualquier transición de una sola tecnología. El acuerdo sobrevivirá a todo ser humano que firme su piloto fundacional, y a todo ciudadano que plante un Seed y lo financie mensualmente. Esa es su promesa al niño que firma un acuerdo de estipendio, al ciudadano que se sumó sin deber el permiso de ningún gobierno, a los nietos de ese niño que quizás gobiernen el acuerdo a mediados de siglo, y a cada generación que herede lo que los fundadores —oficiales y ciudadanos por igual— construyen ahora.

Cada firmante conserva la libertad de retirarse, su plena soberanía y su autoridad sobre sus propios ciudadanos, con el derecho de enmendar y dar forma a la evolución del acuerdo. Cada ciudadano conserva la misma posición para fundarlo, financiarlo, presenciarlo y hacerlo rendir cuentas, con o sin firma de gobierno. Lo que ninguno puede hacer es comprometer los principios fundacionales, porque esa promesa debe sobrevivir a cualquier retiro. Líderes y ciudadanos por igual firman el próximo siglo del acuerdo hacia un horizonte que sus nietos heredarán y completarán.`,
      999: `Los Acuerdos de Atlantis no crecerán más rápido de lo que la calidad les permite honrar, y esta contención no es sentimentalismo: es ingeniería, escrita dentro de la misma disciplina de medición que gobierna cada promesa que hace el acuerdo. Tres regiones fundadoras, Camboya, Honduras y Austin, deben completar un ciclo piloto entero, con cada participante honrado y cada principio verificado, antes de que se sume una cuarta región. Un crecimiento que se adelanta a la verificación no es crecimiento; es exposición disfrazada de ambición. El piloto fundacional existe para que el acuerdo pueda demostrar, a una escala lo bastante pequeña como para inspeccionarse y lo bastante grande como para importar, que sus promesas sobreviven al contacto con la realidad antes de extenderlas a un mundo que observa desde fuera de sus tres fronteras. La cuarta región aún no tiene nombre, y no lo tendrá hasta que las primeras tres respalden cada afirmación que hace este documento.

Lo que demuestra la preparación para crecer no es el entusiasmo, sino un número que el acuerdo pueda defender en público. El Puntaje de Innovación Calificada —QIS, calculado como Ingresos más Utilidad Bruta más Utilidad Operativa más gasto efectivo en I+D, dividido entre cuatro— es el instrumento que el acuerdo usa para saber si una región, una cohorte o un cubo ha mejorado, en lugar de simplemente haber sentido que mejoró. El crecimiento del QIS dimensiona el fondo de recompensas solo después de cumplida la calificación, nunca antes, y el QIS en sí mismo no acuña 웃 ni compra propiedad. El QIS es medición, no pago; medición, no participación accionaria; un espejo que el acuerdo se sostiene frente a su propio trabajo, nunca una moneda que gasta. Una región que se propone expandir la red debe mostrar su QIS con honestidad, a la vista de las regiones que la precedieron, o no se expande.

Crecimiento sostenible significa crecimiento que gana su propia autoridad un incremento a la vez. Todo cubo y toda región comienzan en modo Manual, donde los humanos deciden todo y el sistema asiste. El avance hacia la operación Semiautomática, y eventualmente Autónoma, dentro de un cubo determinado, está condicionado por un único umbral en todo el acuerdo: una mejora medida del 11,1 por ciento, una parte en nueve, demostrada y reproducible antes de conceder el siguiente grado de autonomía. La autonomía se gana cubo por cubo, nunca se reclama en bloque ni se extiende sobre los dominios que deben permanecer humanos sin importar cuán avanzado llegue a ser el sistema: el sentido, el dinero y la ley permanecen cerrados a las máquinas, sin importar cuántos umbrales se superen en otros lugares. Una red que expande su automatización más rápido de lo que expande su evidencia no se está modernizando. Está apostando con una confianza que aún no ha ganado.

La compensación escala junto con la red del mismo modo en que lo hace la autoridad: de manera deliberada, y con un tope que protege al sistema entero de su propio éxito. El 웃, el token de la Inteligencia Humana, equivale a una hora de trabajo presenciado multiplicada por el salario mínimo local; lo que gana cualquier participante es ese Múltiplo por las horas trabajadas, y se emite únicamente por labor realizada dentro de una tarea acotada y aprobada en presupuesto. Antes de la aprobación, el plan más refinado es solo planificación, y la planificación por sí sola no acuña nada. La liquidación de cada participante tiene un tope de 9,999 웃 por año, con todo excedente trasladándose hacia adelante en lugar de desaparecer o distorsionar el fondo. A medida que nuevas regiones se suman y la actividad de la red se multiplica, este tope es lo que evita que el crecimiento se convierta en inflación: el valor permanece atado a horas reales, presenciadas y locales, sin importar cuán grande llegue a ser el acuerdo.

Detrás de cada 웃 hay un porqué que ningún libro contable puede calcular por sí solo. ♡, la Intención Compartida, lleva ese porqué a través de cada decisión de expansión que toma el acuerdo, mientras que ◬, la contribución de la Inteligencia Artificial, se cuenta como aceleración presenciada medida frente a una línea base congelada: un delta, y nunca, bajo ninguna circunstancia, una métrica de ganancia que se optimice por sí misma. El ingreso a esta red comienza de la misma manera para cada participante, sin importar en qué región o en qué década se sume: con un Seed, una membresía única cuyo precio es una séptima parte de una hora de salario mínimo local, intransferible y sin conllevar ningún tipo de reclamo económico. El Seed solo dice que una persona ha llegado. Todo lo que construya después, lo construye plenamente a la vista de las otras tres monedas del acuerdo, nunca a través del propio Seed.

Un crecimiento real también debe ser un crecimiento que llegue a una persona de verdad, no a un fondo que el marco retenga en nombre de alguien. 🏠 Livelihood Direct exige que el valor viaje hasta un participante únicamente a través de vías locales calificadas y licenciadas que el acuerdo ha verificado región por región, y nunca a través de una custodia que el propio marco conserve. La clasificación siempre precede a la liquidación, de modo que ningún valor se mueve antes de que su propósito y su destinatario estén ambos establecidos sin lugar a dudas. Y porque el reconocimiento no es lo mismo que el acceso, una cama, un lugar en la rotación, un asiento en la mesa está condicionado por el rol y la preparación, nunca por el puntaje o la posición de un participante. A medida que la red se expande hacia una cuarta región y más allá, cada nuevo territorio debe calificar sus propias vías licenciadas antes de que Livelihood Direct pueda llegar a su gente: expansión de la confianza, no solo expansión de territorio.

Nada de esto perdura sin una red construida para sobrevivir a su propio éxito, razón por la cual la Continuity Without Evasion gobierna cada región que el acuerdo llegue a sumar. La portabilidad legal es obligatoria; ningún gobierno, banco, fundador o modelo en particular puede volverse indispensable para el conjunto. Cada jurisdicción opera su propio adaptador, de cierre seguro y rechazo por defecto, de modo que un fallo adverso en cualquier lugar cierre una sola vía, nunca el acuerdo entero. Human Authority sostiene el sentido, el dinero y la ley en cada escala que alcance la red, sellada contra el avance de las máquinas por diseño y no por promesa. El Measurement of Time registra cada minuto real por separado de cualquier afirmación sobre él, y el Replay garantiza que cualquier entrega, en cualquier región, en cualquier punto a lo largo de cinco siglos, pueda reconstruirse y volver a examinarse por cualquiera que lo pida. Una red que no puede reproducirse mediante Replay no puede merecer confianza, sin importar cuántas regiones se hayan sumado ni cuán impresionante parezca su crecimiento desde afuera. Así es como Vision • 2525 crece sin jamás sobrepasar la confianza que fue construida para conservar: una región verificada, un QIS honesto, una hora presenciada a la vez.`,
    },
  },
];
