import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_ES: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Donde comienza la innovación`,
    content: {
      7: `Los líderes inician lo que ningún siglo inició.`,
      33: `Tres regiones — Camboya, Honduras, Austin — prometen acoger a los jóvenes aprendices, protegerlos y entregarles las herramientas del futuro. Gobierno, Educación, Innovación: tres firmas visionarias por región. Un comienzo compartido.`,
      111: `El Acuerdo de Atlántida es una promesa hecha por líderes dispuestos a comenzar algo que no ha existido antes. Sus firmantes fundadores en Camboya, Honduras y Austin, Texas fueron elegidos por una cualidad rara: la voluntad de confiar a los jóvenes las herramientas del futuro mientras aún haya tiempo para enseñárselas. Firmar el acuerdo compromete a la región a acoger aprendices de todas las culturas, aportar lo que solo ella puede ofrecer de manera única, y sostenerse a un estándar más alto que el que la regulación actual exige. Tres firmas visionarias — Gobierno, Educación, Innovación — entran juntas en el acuerdo. Tres visionarios, tres regiones, un comienzo compartido.`,
      333: `Toda civilización es recordada por lo que eligió comenzar. El Acuerdo de Atlántida es una promesa hecha por líderes dispuestos a comenzar algo que no ha existido antes — un cimiento compartido para la innovación humana ordinaria que alcanza cada rincón del mundo, honra cada voz y perdura a través de las generaciones. Sus firmantes fundadores en Camboya, Honduras y Austin, Texas no fueron elegidos por su poder económico, su fuerza militar o su prestigio institucional. Fueron elegidos por una cualidad más rara: la voluntad de confiar a los jóvenes las herramientas del futuro. Esto es lo que significa liderar en el siglo venidero — el coraje de entregar las llaves a la próxima generación mientras aún haya tiempo para enseñarles a conducir.\n\nEl acuerdo es convocado por eXeL, una fuerza organizadora construida deliberadamente para este momento. eXeL existe fuera de los canales tradicionales de coordinación que dieron forma al siglo pasado — fuera de las estructuras de tratados diplomáticos, fuera de las burocracias multilaterales, fuera de los enredos políticos de cualquier Estado-nación. eXeL es el convocante de confianza que reúne a líderes visionarios en torno a un marco compartido, un motor compartido y un horizonte compartido de quinientos años. Cada firmante conserva plena soberanía, plena autoridad sobre sus propios ciudadanos y plena libertad para retirarse en cualquier momento. Lo que los firmantes ganan es el efecto de red que solo un marco diseñado a tal fin puede ofrecer. Esto es coordinación sin ninguna forma de dominación política.\n\nFirmar el acuerdo es firmar una promesa. Que la región acogerá a jóvenes aprendices de todas las culturas. Que la región aportará lo que solo ella puede ofrecer de manera única. Que la región se sostendrá a un estándar más alto que el que la regulación actual exige. Que la región lo hará públicamente, de manera transparente, a la vista de cada ciudadano al que sirve. Se requieren tres firmas de cada región — Gobierno, Educación e Innovación. Ninguna oficina por sí sola vincula el acuerdo. Se necesitan tres visionarios para decir sí. Tres visionarios, tres regiones, un comienzo — así es como cualquier marco entra en la vida a través de la confianza mutua de los líderes dispuestos a firmarlo.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Aprender a través de la simulación`,
    content: {
      7: `Practicar mil veces antes de tocar.`,
      33: `Nada consecuente se aprende primero en equipos reales. Cada participante practica en simulación, rota entre las tres regiones y celebra públicamente. Esto es respeto por el joven humano cuyo primer error nunca debería costar una vida.`,
      111: `Toda disciplina digna de dominarse fue aprendida por alguien antes de ser conocida. El Acuerdo de Atlántida devuelve esta antigua sabiduría al centro de cómo se prepara a los jóvenes para construir el futuro. Nada consecuente se aprende primero en equipos reales, sobre personas reales o en condiciones irreversibles. Cada participante practica en simulación hasta que la práctica se vuelve competencia, y la competencia, preparación. El modelo de rotación lleva a cada participante a través de las tres regiones fundadoras, y cada rotación culmina en una celebración pública y cooperativa abierta a la comunidad anfitriona más amplia. Esto es respeto por el joven humano cuyo primer error nunca debería costar una vida.`,
      333: `Toda disciplina digna de dominarse fue aprendida por alguien antes de ser conocida. Los maestros artesanos ensayan antes de la representación, los pilotos ensayan antes del vuelo, los médicos ensayan antes de la cirugía, y los niños ensayan el mundo a través del juego. El Acuerdo de Atlántida devuelve esta antigua sabiduría al centro de cómo se prepara a los jóvenes para construir el futuro. Nada consecuente se aprende primero en equipos reales, sobre personas reales o en condiciones irreversibles. Cada participante practica en simulación hasta que la práctica se vuelve competencia, y la competencia, preparación. Esto no es cautela — es respeto por el joven humano cuyo primer error nunca debería costarle la vida a nadie.\n\nEl modelo de rotación del acuerdo lleva a cada participante a través de las tres regiones fundadoras. Lo aprendido en Camboya se refina en Honduras y se completa en Austin. Lo descubierto en Austin se cuestiona en Camboya y se integra en Honduras. Cada participante vive, aprende y es mentoreado a través de culturas que de otro modo permanecerían distantes. El currículo se nutre de tradiciones de simulación disciplinada de muchas culturas — de la tradición de educación estratégica de Sun Tzu, de la práctica-por-el-juego de Musashi, de la teoría cíclica del aprendizaje de Ibn Khaldun, de la dialéctica monástica de Nalanda, del simulador civil de vuelo — sintetizadas para respetar cada etapa cognitiva y cada herencia cultural. Ninguna tradición domina.\n\nCada rotación culmina en una celebración pública y cooperativa abierta a la comunidad anfitriona más amplia. Vecinos, familias y visitantes curiosos se reúnen para ver lo que la cohorte ha aprendido. Estos eventos hacen que la tecnología sofisticada sea accesible y celebrada en lugar de temida. Una sociedad que crece entendiendo los sistemas cooperativos a través del juego no puede ser fácilmente manipulada por el miedo hacia esos sistemas. Esto es disuasión mediante educación, no disuasión mediante fuerza. La promesa del acuerdo a cada padre: su hijo practicará mil veces en seguridad antes de tocar algo que pueda dañarlo, y la comunidad será testigo de su crecimiento en cada paso del camino. Así se ve el respeto por el joven humano cuando se inscribe en un marco, y esto es lo que el liderazgo entrega a la próxima generación de participantes antes de que esa generación deba exigirlo.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Seguridad probada antes de extender la confianza`,
    content: {
      7: `Seguridad probada primero, luego confianza extendida.`,
      33: `Cada instalación y cada rotación se ubican dentro de un envolvente protector con alerta temprana. El hardware rehúsa la militarización. Los registros sobreviven a la turbulencia. La seguridad se diseña alrededor del participante más joven, jamás simplemente prometida.`,
      111: `Antes de que se extienda la confianza, la seguridad debe probarse. El Acuerdo de Atlántida convierte esto en su compromiso fundacional. Cada instalación del acuerdo, cada ruta de rotación, cada lugar donde un joven participante duerme o estudia se ubica dentro de un envolvente protector documentado, con capacidad de alerta temprana que otorga a la comunidad horas, no minutos, para responder a cualquier riesgo creíble. Cada dispositivo, cada sensor, cada sistema de coordinación queda vinculado a nivel de hardware para rechazar la reasignación a la integración con sistemas de armas. Esto no es política — es física. El acuerdo está diseñado para permanecer honorable a través de la turbulencia: inestabilidad política, contracción de fondos, ciberataque o interrupción de viajes. Cada escenario es planificado, y cada plan sitúa la dignidad humana como su primera restricción de diseño.`,
      333: `Antes de que se extienda la confianza, la seguridad debe probarse. El Acuerdo de Atlántida convierte esto en su compromiso fundacional. Cada instalación del acuerdo, cada ruta de rotación, cada lugar donde un joven participante duerme o estudia se ubica dentro de un envolvente protector documentado, con capacidad de alerta temprana que otorga a la comunidad horas, no minutos, para responder a cualquier riesgo creíble. La tecnología usada para proteger a los participantes es la misma tecnología que el acuerdo les enseña a construir — sensores, coordinación, supervivencia de las comunicaciones, inteligencia distribuida. Los jóvenes aprenden la seguridad de adentro hacia afuera, en su propio idioma y en su propia región, no porque se les diga que están seguros, sino viendo cómo la seguridad se diseña a su alrededor cada día.\n\nEl acuerdo hace una promesa irrompible sobre en qué no puede convertirse su tecnología. Cada dispositivo, cada sensor, cada sistema de coordinación queda vinculado a nivel de hardware para rechazar la reasignación a la integración con sistemas de armas. Esto no es lenguaje de política. No es aspiración. Es una imposibilidad física, aplicada criptográficamente, verificada por cada región firmante e inspeccionable por cada ciudadano. Las herramientas que protegen a un niño en Phnom Penh no pueden reasignarse para dañar a un niño en Austin. Las herramientas que coordinan un ejercicio de enjambre en Tegucigalpa no pueden reconfigurarse para atacar a un humano en cualquier lugar. Esta es la respuesta del acuerdo a un siglo de miedo al doble uso. No política — física.\n\nEl acuerdo está diseñado para permanecer honorable a través de la turbulencia. Si una región firmante pierde estabilidad política, los participantes son acogidos por las regiones restantes. Si los fondos se contraen, los estipendios de los participantes se protegen primero, antes que la administración y la infraestructura. Si los registros digitales son atacados, las copias fuera de línea persisten. Si viajar se vuelve imposible, el sustrato continúa virtualmente. Cada escenario es planificado, y cada plan sitúa la dignidad humana como su primera restricción de diseño. Los líderes que firman este acuerdo firman la promesa de que la seguridad se diseña, no se asume. Lo que extienden a sus ciudadanos no es meramente oportunidad, sino protección construida al estándar que el participante más joven merece — la misma protección que cualquier líder exigiría para su propio hijo cruzando solo una frontera desconocida.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Compensación, bienestar y dignidad humana`,
    content: {
      7: `Un estipendio, un mentor, un hogar.`,
      33: `Cada participante recibe un estipendio de subsistencia desde el primer día. Amor, pérdida y seguridad son tratados como infraestructura de primer orden. El éxito se mide por el participante más vulnerable, jamás por el promedio. Dignidad como sustrato, nunca decoración.`,
      111: `El Acuerdo de Atlántida trata a cada participante como un ser humano pleno desde el primer día. Se entrega un estipendio desde el momento en que comienza la participación, indexado al costo de vida de la región para que su impacto respete la dignidad local del trabajo. El bienestar se trata como infraestructura de primer orden — no un beneficio opcional, no un privilegio, sino el sustrato sobre el que todo lo demás descansa. Se sostienen tres dominios fundacionales: Amor, Pérdida y Seguridad. El acuerdo mide el éxito por el resultado de su participante más vulnerable, no por el promedio. Ningún participante será silenciosamente olvidado para que los promedios luzcan bien. Dignidad como sustrato, no decoración.`,
      333: `El Acuerdo de Atlántida trata a cada participante como un ser humano pleno desde el primer día. Se entrega un estipendio desde el momento en que comienza la participación, indexado al costo de vida de la región para que su impacto respete la dignidad local del trabajo. El estipendio llega antes de que las obligaciones familiares se conviertan en emergencias, y antes de que la dignidad se vea comprometida. Le señala a cada joven que su tiempo es valioso, que su contribución es esperada y que la estabilidad de su familia es parte de la responsabilidad del acuerdo. Esto no es caridad. Es el reconocimiento de que la innovación humana ordinaria requiere primero la seguridad humana ordinaria. Una mente no puede florecer mientras su hogar esté amenazado.\n\nEl bienestar se trata como infraestructura de primer orden — no un beneficio opcional, no un privilegio, sino el sustrato sobre el que todo lo demás descansa. El acuerdo nombra tres dominios fundacionales a través de los cuales cada participante es sostenido: el Amor, en el sentido de conexión, vínculo y límites saludables; la Pérdida, ya que cada participante experimentará duelo y debe ser acompañado, no evitado; y la Seguridad, en el sentido de que cada participante sabe a quién llamar, en cada región, en su propio idioma. Se ofrecen consejería individual, círculos grupales, prácticas somáticas y prácticas culturales o espirituales honradas según la propia tradición del participante. Cero ideología forzada. El acuerdo sostiene el espacio con reverencia; no proselitiza ningún sistema de creencias.\n\nEl acuerdo mide el éxito por el resultado de su participante más vulnerable, no por el promedio. Los participantes rurales sin alto ancho de banda son atendidos. Los participantes neurodivergentes reciben adaptaciones como norma. Los participantes con discapacidad encuentran cada instalación accesible. Los participantes de género diverso reciben vivienda segura y emparejamiento con mentores. Los hablantes de idiomas no nativos encuentran cada documento en su idioma. Los participantes indígenas encuentran honradas sus prácticas culturales y protegidos sus saberes tradicionales. Los líderes que firman este acuerdo prometen que ningún participante será silenciosamente olvidado para que los promedios luzcan bien. Esto es dignidad como sustrato, no como decoración. Lo que se mide es lo que se honrará, y lo que se honra aquí es el humano entero — mente, cuerpo y espíritu juntos, sin excepción alguna.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Financiación y gobernanza`,
    content: {
      7: `Los ciudadanos financian directamente la próxima generación.`,
      33: `Los residentes comunes aportan pequeñas cantidades mensuales. Sin canal de ayuda, sin benefactor extranjero, sin ataduras políticas. Cada dólar es rastreable. Cada contabilidad se publica, en el idioma de cada región, cada mes, públicamente.`,
      111: `El Acuerdo de Atlántida es financiado por los ciudadanos a los que sirve. Residentes comunes aportan pequeñas cantidades voluntarias cada mes — lo bastante modestas para que ningún adulto quede excluido, lo bastante resonantes para que el total sostenga el trabajo del acuerdo a escala significativa. Cuando un ciudadano financia directamente a la próxima generación, ese ciudadano responsabiliza al acuerdo directamente. El acuerdo es deliberadamente independiente de las instituciones multilaterales que dieron forma al siglo pasado. Esto no es una declaración política — es una decisión de diseño. Cada dólar se registra de forma permanente y rastreable. Cada contribución ciudadana puede seguirse desde el origen hasta el estipendio y hasta la innovación. Una transparencia rara vez ofrecida por cualquier institución.`,
      333: `El Acuerdo de Atlántida es financiado por los ciudadanos a los que sirve. Residentes comunes de las regiones participantes aportan pequeñas cantidades voluntarias cada mes — cantidades lo bastante modestas para que ningún adulto de ninguna región anfitriona quede excluido de la participación, lo bastante resonantes para que el total sostenga el trabajo del acuerdo a escala significativa. Este diseño es deliberado. Cuando un ciudadano financia directamente la educación de la próxima generación, ese ciudadano responsabiliza al acuerdo directamente. No hay canal de ayuda, no hay benefactor extranjero, no hay atadura política ligada al cheque. El alma del acuerdo es el ciudadano que aporta una pequeña cantidad cada mes, cuya participación hace posible el todo.\n\nEl acuerdo es deliberadamente independiente de las instituciones multilaterales que han dado forma al siglo pasado — la Organización del Tratado del Atlántico Norte, la Organización Mundial de la Salud, las Naciones Unidas, el Fondo Monetario Internacional, el Banco Mundial y todo canal nacional de ayuda exterior. Esto no es una declaración política sobre el valor de esas instituciones o sus contribuciones. Es una decisión de diseño. Las dependencias de punto único comprometen la durabilidad en un horizonte de quinientos años. Un marco destinado a servir a cada región, sin importar su alineación geopolítica, no puede enredarse con ninguna alineación. Los gobiernos nacionales pueden contribuir voluntariamente. Las contribuciones son transparentes. Ninguna contribución compra influencia de gobernanza, de ninguna fuente, jamás.\n\nCada dólar y cada unidad de valor que entra en el acuerdo se registra de manera permanente, pública y rastreable. Cada contribución ciudadana puede seguirse desde su origen hasta el estipendio en que se convierte, hasta el joven al que sirve, hasta el proyecto de innovación que emerge del trabajo de ese joven. Los gastos administrativos están limitados. Los aportes corporativos e institucionales son bienvenidos y limitados. Se entrega contabilidad completa en el idioma de cada región firmante cada mes. Los líderes que firman el acuerdo prometen a sus ciudadanos una transparencia rara vez ofrecida por cualquier institución — transparencia que permanecerá legible por siglos después de que cada firmante haya dejado el cargo. Esta es la confianza que el acuerdo exige. Esta es la confianza que el acuerdo se gana, una pequeña contribución rastreable a la vez, a la vista de cada ciudadano.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Intercambio intercultural y contribución global`,
    content: {
      7: `Cada aprendiz en su propio idioma.`,
      33: `Cada actividad disponible en el idioma del participante. Inteligencias Artificial, Humana y Compartida mantenidas en tensión productiva — ningún estudiante se remite a una sola. Currículos y resultados publicados abiertamente. Lo que una región aprende, todas heredan.`,
      111: `El Acuerdo de Atlántida devuelve a la educación su propósito más profundo: el intercambio de sabiduría a través de fronteras que de otro modo dividirían. Cada actividad está disponible en el idioma del participante, en el idioma de la región anfitriona y en un registro canónico compartido. El idioma no es decoración — el idioma es jurisdicción, el idioma es dignidad hecha legible. El marco educativo descansa sobre la trinidad de inteligencias: la Artificial propone, la Humana decide, la Intención Compartida valida. Cada estudiante aprende a sostener las tres en tensión productiva. Lo que el acuerdo aprende, el acuerdo lo devuelve. Currículos, resultados de innovación, investigación de bienestar y decisiones de gobernanza se publican abiertamente. Lo que una región aprende, todas las regiones lo heredan.`,
      333: `El Acuerdo de Atlántida devuelve a la educación su propósito más profundo: el intercambio de sabiduría a través de fronteras que de otro modo dividirían. Cada actividad del acuerdo está disponible en el idioma propio del participante, en el idioma oficial de la región anfitriona y en un registro canónico compartido, de modo que ningún participante navegue el acuerdo en una lengua que no eligió. El idioma no es decoración. El idioma es jurisdicción. El idioma es dignidad hecha legible. Cuando un joven de una aldea camboyana lee su propio registro de estipendio en jemer, cuando un joven de un pueblo hondureño lo lee en español, cuando un joven de un barrio de Austin lo lee en inglés, los tres son honrados por igual por el mismo acuerdo.\n\nEl marco educativo del acuerdo descansa sobre la trinidad de inteligencias que Vision 2525 hace visible. La Inteligencia Artificial propone patrones, opciones y posibilidades más rápido que cualquier humano por sí solo. La Inteligencia Humana decide sobre seguridad, ética y dirección — las preguntas que ninguna máquina debería responder. La Intención Compartida valida que las decisiones se alineen con los principios fundacionales del acuerdo, asegurando que ningún participante sea forzado a elegir entre excelencia individual y bien colectivo. A ningún estudiante se le enseña a remitirse a una sola inteligencia. Cada estudiante aprende a sostener las tres en tensión productiva. Así se prepara a la próxima generación de líderes para gobernar responsable y sabiamente en un mundo donde ninguna de estas tres inteligencias actuará jamás sola o sin control.\n\nLo que el acuerdo aprende, el acuerdo lo devuelve. Los currículos se publican bajo licencia abierta para que cualquier región — firmante o no — pueda adaptarlos libremente a su cultura local y tradición pedagógica. Los resultados de innovación se publican. La investigación de bienestar se publica en forma agregada para investigadores de todo el mundo. Las decisiones de gobernanza se publican con su razonamiento completo. El éxito del acuerdo se mide no solo por sus propios participantes, sino por la cantidad de iniciativas educativas, de innovación y culturales que surgen en su estela, en regiones que jamás firmaron el piloto fundador pero construyeron sobre su sabiduría abiertamente compartida. Lo que una región aprende, todas las demás regiones lo heredan.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Crecimiento sostenible de la red`,
    content: {
      7: `Nunca más rápido que la dignidad.`,
      33: `Tres regiones fundadoras completan un ciclo piloto antes de que se sume una cuarta. Registros anclados para perdurar cinco siglos. Cada firmante conserva su soberanía. Nada se rebaja para dar paso al próximo firmante.`,
      111: `El Acuerdo de Atlántida no crecerá más rápido que la calidad que pueda honrar. Tres regiones fundadoras deben completar un ciclo piloto completo, con cada participante honrado y cada principio verificado, antes de que se sume una cuarta región. Este es un principio finalmente convertido en disciplina viva. El horizonte del acuerdo es deliberadamente largo — cinco siglos desde el día fundador. Sus registros están anclados para que un ciudadano que los lea dentro de cien años pueda confiar en el razonamiento. Cada firmante conserva plena soberanía, plena autoridad y plena libertad de retirarse. Ningún firmante puede comprometer los principios fundacionales — porque esos principios son la promesa del acuerdo a sus participantes a través de cada generación.`,
      333: `El Acuerdo de Atlántida no crecerá más rápido que la calidad que pueda honrar. Cada expansión es una promesa a los participantes ya dentro — que el estándar fundador del acuerdo no será diluido por el entusiasmo de la escala. Tres regiones fundadoras deben completar un ciclo piloto completo, con cada participante honrado y cada principio verificado, antes de que se sume una cuarta región. Esto no es cautela disfrazada de principio. Este es un principio finalmente convertido en disciplina viva a través de cada región fundadora. Los líderes que firman el piloto fundador prometen a futuros firmantes el mismo sustrato, la misma protección, la misma dignidad que recibió la cohorte fundadora. Nada se rebaja para dar paso al próximo.\n\nEl horizonte del acuerdo es deliberadamente largo. Está diseñado para perdurar aproximadamente entre quince y veinte generaciones humanas — cinco siglos desde el día fundador. Sus registros están anclados para que un ciudadano que los lea dentro de cien años pueda confiar en el razonamiento. Su marco de coordenadas, sus roles de autoridad humana y sus ciclos de gobernanza intergeneracionales están todos construidos para sobrevivir a cualquier transición tecnológica única. El acuerdo sobrevivirá a cada humano que firme su piloto fundador. Esa es su promesa al niño que firme un acuerdo de estipendio en el año siguiente a la ratificación, a los nietos de ese niño que quizá gobiernen el acuerdo a mediados de siglo, y a cada generación que herede lo que los fundadores construyan ahora.\n\nCada firmante conserva la libertad de retirarse con aviso. Cada firmante conserva plena soberanía. Cada firmante conserva autoridad sobre sus propios ciudadanos. Cada firmante conserva el derecho de proponer enmiendas, plantear disputas y dar forma a la evolución del acuerdo junto con cada otro firmante. Lo que ningún firmante puede hacer es comprometer los principios fundacionales del sustrato — porque esos principios son la promesa del acuerdo a sus participantes, y esa promesa debe sobrevivir a la partida de cualquier firma. Los líderes que firman este acuerdo ahora se unen a algo más grande que cualquier mandato político. Están firmando el próximo siglo del acuerdo, y los siglos más allá, hacia un horizonte que sus propios nietos heredarán y completarán.`,
    },
  },
];
