import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_FI: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Missä innovaatio alkaa`,
    content: {
      7: `Johtajat aloittavat sen, mitä yksikään vuosisata ei aloittanut.`,
      33: `Kolme aluetta — Kambodža, Honduras, Austin — avaavat lupauksen, jota kansalaiset ovat rakentamassa: he ottavat vastaan oppijoita, suojelevat heitä ja antavat heille tulevaisuuden työkalut. Hallitus, koulutus ja innovaatio allekirjoittavat huoltajina; kansalaiset pitävät siitä kiinni. Yksi alku.`,
      111: `Atlantis-sopimus on maailman kansalaisten välinen sopimus — lupaus, jonka kuka tahansa, missä tahansa, voi luoda ja jota hän voi kantaa, riippumatta siitä, mitä hänen hallituksensa allekirjoittaa tai mitä hänen työnantajansa sallii. Sen perustajaalueet, Kambodža, Honduras ja Austin Texasissa, valittiin yhden harvinaisen ominaisuuden vuoksi: halukkuuden luottaa nuorille tulevaisuuden työkalut, kun opettamiseen on vielä aikaa. Hallitukset, kasvattajat ja innovaattorit allekirjoittavat alueidensa huoltajina — kolme visionääristä allekirjoitusta kukin, Hallitus, Koulutus, Innovaatio — mutta kansalaiset rahoittavat sopimuksen, todistavat sen työtä ja pitävät sitä tilivelvollisena suoraan. Kuulumiseen ei tarvita hallituksen lupaa eikä työnantajan siunausta. Kolme aluetta, yksi yhteinen alku.`,
      333: `Jokainen sivilisaatio muistetaan siitä, minkä se valitsi aloittaa. Atlantis-sopimus on lupaus maailman kansalaisten kesken — kuka tahansa, missä tahansa, voi aloittaa sen, riippumatta siitä, mitä hänen hallituksensa allekirjoittaa. Sen perustajaalueita, Kambodžaa, Hondurasia ja Austinia Texasissa, ei valittu taloudellisen vallan, sotilaallisen voiman tai institutionaalisen arvovallan vuoksi, vaan harvinaisemman ominaisuuden vuoksi: halukkuuden luottaa nuorille tulevaisuuden työkalut. Tämä on sitä, mitä johtajuus tarkoittaa tulevalla vuosisadalla — rohkeutta luovuttaa avaimet seuraavalle sukupolvelle, kun opettamiseen ajaa on vielä aikaa.

Sopimuksen koolle kutsuu eXeL, tätä hetkeä varten rakennettu organisoiva voima, joka toimii viime vuosisataa muovanneiden koordinaatiokanavien ulkopuolella — diplomaattisten sopimusrakenteiden, monenkeskisten byrokratioiden ja minkä tahansa yksittäisen kansallisvaltion poliittisten sidonnaisuuksien ulkopuolella. eXeL on luotettu koollekutsuja, joka tuo visionääriset johtajat yhteen jaetun viitekehyksen, jaetun vauhtipyörän ja jaetun viisisataavuotisen aikahorisontin ympärille. Jokainen allekirjoittaja säilyttää täyden suvereniteettinsa, täyden vallan omiin kansalaisiinsa ja täyden vapauden vetäytyä milloin tahansa. Se, minkä allekirjoittajat saavat — ja minkä kuka tahansa kansalainen saa Seedin hinnalla, joka on seitsemäsosa paikallisen minimipalkan tunnista — on verkostovaikutus, jota vain tätä varten rakennettu viitekehys voi tarjota: koordinaatiota ilman minkäänlaista poliittista alistamista.

Sopimuksen allekirjoittaminen on lupauksen allekirjoittamista: että alue ottaa vastaan oppijoita eri kulttuureista, antaa sen, mitä vain se voi tarjota, ja pitää itsensä nykyistä sääntelyä korkeamman standardin mittapuussa — julkisesti, läpinäkyvästi, vastuussa kansalaisille, jotka rahoittavat, todistavat ja pitävät sitä tilivelvollisena, ilman että kuulumiseen tarvitaan hallituksen lupaa tai työnantajan siunausta. Jokaiselta alueelta vaaditaan kolme allekirjoitusta — Hallitus, Koulutus ja Innovaatio — jotka allekirjoittavat huoltajina, ei omistajina. Kolmen visionäärin tulee sanoa kyllä, ja kansalaisten tulee pitää kiinni siitä, minkä he allekirjoittivat. Kolme visionääriä, kolme aluetta, yksi alku — näin viitekehys astuu elämään sellaisten johtajien luottamuksen kautta, jotka ovat valmiita allekirjoittamaan sen olemassaoloon.`,
      999: `Jokainen sivilisaatio muistetaan siitä, minkä se valitsi aloittaa, ja Vision • 2525 pyytää tämän aloittajia aloittamaan nöyryydellä valloituksen sijaan. Atlantis-sopimus on lupaus, jonka antavat johtajat, jotka ovat valmiita aloittamaan jotain ennennäkemätöntä — jaetun perustan inhimilliselle innovaatiolle, joka ulottuu maailman joka kolkkaan, kunnioittaa jokaista ääntä ja kestää sukupolvien yli, joita mitataan ei vuosissa vaan vuosisadoissa. Sen perustajaallekirjoittajia Kambodžassa, Hondurasissa ja Austinissa Texasissa ei valittu taloudellisen vallan, sotilaallisen voiman tai institutionaalisen arvovallan vuoksi. Heidät valittiin harvinaisemman ominaisuuden vuoksi: halukkuuden luottaa nuorille tulevaisuuden työkalut ja kärsivällisyyden antaa viisisataavuotisen aikahorisontin elää pidempään kuin minkään hallinnon suosionosoitukset. Tämä on sitä, mitä johtajuus tarkoittaa tulevalla vuosisadalla — rohkeutta luovuttaa avaimet seuraavalle sukupolvelle, kun opettamiseen ajaa on vielä aikaa.

Sopimuksen koolle kutsuu eXeL, tätä hetkeä varten rakennettu organisoiva voima. eXeL toimii viime vuosisataa muovanneiden koordinaatiokanavien ulkopuolella — diplomaattisten sopimusrakenteiden ulkopuolella, monenkeskisten byrokratioiden ulkopuolella, minkä tahansa kansallisvaltion poliittisten sidonnaisuuksien ulkopuolella. eXeL on luotettu koollekutsuja, joka tuo visionääriset johtajat yhteen jaetun viitekehyksen, jaetun vauhtipyörän ja jaetun viisisataavuotisen aikahorisontin ympärille. Jokainen allekirjoittaja säilyttää täyden suvereniteettinsa, täyden vallan omiin kansalaisiinsa ja täyden vapauden vetäytyä milloin tahansa. Se, minkä allekirjoittajat saavat, on verkostovaikutus, jota vain tätä varten rakennettu viitekehys voi tarjota. Jokaisen osallistujan astuminen tähän viitekehykseen alkaa samalla vaatimattomalla tavalla: Seedillä, kertaluonteisella jäsenyydellä, jonka hinta on seitsemäsosa paikallisen minimipalkan tunnista, ei-siirrettävissä ja ilman minkäänlaista taloudellista vaadetta. Seed ei osta omistajuutta eikä lupausta palkinnosta — vain kuulumisen, oikeuden seistä viitekehyksen sisällä ja aloittaa. Tämä on koordinaatiota ilman minkäänlaista poliittista alistamista, rakennettu alulle, joka on riittävän pieni kenen tahansa varaan.

Koska suvereniteetti säilytetään sen sijaan, että se luovutettaisiin, sopimus on rakennettu Continuity Without Evasion -periaatteen mukaisesti. Mikään korvaamaton hallitus, pankki, perustaja tai malli ei saa pitää koko viitekehystä panttivankina omaa selviytymistään varten. Jokaista lainkäyttöaluetta palvellaan sen omalla laillisella sovittimella, joka on oletusarvoisesti kielletty kunnes vaatimustenmukaisuus on osoitettu, jotta arvo liikkuu vain sellaisten kanavien kautta, jotka kyseisen lainkäyttöalueen tuomioistuin tunnustaisi laillisiksi. Jos yhden alueen sääntelyviranomainen antaa kielteisen päätöksen, vain tämä yksi kanava sulkeutuu — läpinäkyvästi, vahingoittamatta ketään sen sisällä olevaa osallistujaa — kun jokainen muu alue jatkaa häiriintymättä. Koko sopimus ei koskaan kaadu siksi, että yksi hallitus muutti mielensä. Tämä on siirrettävyyttä, joka on suunniteltu perustavaksi lupaukseksi, ei kriisin jälkeen löydettyä varasuunnitelmaa.

Sopimuksen allekirjoittaminen on lupauksen allekirjoittamista. Sitä, että alue ottaa vastaan oppijoita eri kulttuureista. Sitä, että alue antaa sen, mitä vain se voi tarjota. Sitä, että alue pitää itsensä nykyistä sääntelyä korkeamman standardin mittapuussa. Sitä, että alue tekee tämän julkisesti, läpinäkyvästi, jokaisen palvelemansa kansalaisen silmien edessä. Jokaiselta alueelta vaaditaan kolme allekirjoitusta — Hallitus, Koulutus ja Innovaatio. Yksikään yksittäinen taho ei sido sopimusta yksinään. Kolmen visionäärin täytyy sanoa kyllä. Tämä kolminkertainen allekirjoitus on ensimmäinen ilmaus Human Authority -periaatteesta: merkitys, raha ja laki pysyvät ihmisten käsissä suvereenilla tasolla, tasolla, joka on pysyvästi suljettu koneilta riippumatta siitä, kuinka kyvykkäiksi ne kehittyvät. Measurement of Time (MoT) alkaa tallentaa allekirjoitushetkestä alkaen — todellisia minuutteja todellista inhimillistä työtä, pidettynä erillään mistä tahansa automaattisesta arviosta — ja jokainen sopimuksen työn myöhempi julkaisu on rakennettu niin, että se voidaan rekonstruoida Replayn kautta, jotta vuosisata tästä hetkestä syntyvä kansalainen voi jäljittää, miten tämän päivän perustavat päätökset tehtiin.

Se, minkä pilotti perustaa, on mittaus ennen kuin se on rahaa. Jokainen viitekehykseen astuva innovaatio pisteytetään Hyväksytyllä Innovaatiopisteytyksellä (Qualified Innovation Score, QIS) — Liikevaihdon, Bruttovoiton, Liiketoiminnan tuloksen ja Tehokkaan T&K-kulutuksen keskiarvolla, jaettuna neljällä. QIS ei ole maksu eikä koskaan omistajuutta; se on väline, jolla perustajakohortti oppii näkemään oman edistymisensä ennen kuin mitään palkintoa mitoitetaan. QIS:n kasvu, kun kelpoisuusehdot on täytetty, mitoittaa seuraavan palkintopoolin — mutta QIS:n kasvu ei lyö mitään omasta takaa. Kolme aluetta, yksi alku ja yksi jaettu kurinalaisuus: todista pisteet ennen kuin kosketat kassaa.

Todistetun työn kautta ansaittu arvo kantaa omaa nimeään, 웃, joka lasketaan yhtenä tuntina kerrottuna paikallisella minimipalkalla, skaalattuna Kertoimella, jota sovelletaan palveltuihin tunteihin. 웃 myönnetään vain työstä, joka on todistettu rajatun, budjetoidun ja hyväksytyn tehtävän alaisuudessa; kaikki tätä hyväksyntää vähäisempi on yhä suunnittelua, eikä pelkkä suunnittelu lyö mitään. Vuotuinen 9 999 웃:n selvityskatto suojaa jokaista osallistujaa hallitsemattomalta keskittymiseltä, ja mahdollinen ylijäämä siirtyy eteenpäin sen sijaan, että se katoaisi. Jokaisen 웃:n takana seisoo ♡, Jaettu Aikomus (Shared Intention), joka kantaa syyn siihen, miksi tehtävä alun perin hyväksyttiin, ja ◬, todistettu kiihtyvyys, jonka tehtävä tuotti jäädytettyä lähtötasoa vasten — vain delta, ei koskaan sekoitettuna voittomittariin. Pilotti on olemassa todistaakseen, että nämä kolme symbolia voivat liikkua yhdessä rehellisesti, alue toisensa jälkeen, ennen kuin viitekehys skaalautuu perustajiensa ulkopuolelle.

Kun arvo saavuttaa henkilön, se saavuttaa hänet Livelihood Directin — 🏠 — kautta, hyväksyttyjen ja lisensoitujen paikallisten kanavien kautta, joita eXeL ei koskaan säilytä omana rahastonaan. Luokittelu edeltää selvitystä joka tapauksessa, eikä panoksen tunnustaminen koskaan avaa yösijaa; sen tekee vain henkilön rooli rajatussa tehtävässä. Kasvu pilotin ulkopuolelle on niin ikään porrastettua: jokainen viitekehyksen kuutio siirtyy Manuaalisesta Puoliautomatisoituun ja edelleen Autonomiseen tilaan vasta sen jälkeen, kun se on läpäissyt 11,1 prosentin säännön, yhden yhdeksäsosan mitattua parannusta, ansaittuna kuutio kuutiolta eikä koskaan väitettynä kokonaisuutena — eikä koskaan, missään olosuhteissa, merkityksen, rahan ja lain suvereenin tason yli. Näin kolmesta visionääristä aluetta kohti, kolmesta alueesta ja yhdestä alusta tulee viisisataavuotinen lupaus: ei nopeasti liikkumalla, vaan todistamalla julkisesti, että jokainen askel ansaitsi seuraavan askeleen.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Oppiminen simulaation kautta`,
    content: {
      7: `Harjoittele tuhat kertaa ennen koskettamista.`,
      33: `Mitään merkityksellistä ei opita ensin elävällä laitteistolla. Kuka tahansa kansalainen voi harjoitella simulaatiossa, kiertää kolmea aluetta ja juhlia — kunnioitusta nuorta ihmistä kohtaan, jonka ensimmäinen virhe ei saa koskaan maksaa henkeä.`,
      111: `Jokainen hallitsemisen arvoinen taito opittiin joltakulta ennen kuin se tunnettiin. Atlantis-sopimus palauttaa tämän muinaisen viisauden sen keskiöön, miten nuoria — ja ketä tahansa liittyvää kansalaista — valmistetaan rakentamaan tulevaisuutta. Mitään merkityksellistä ei opita ensin elävällä laitteistolla, todellisilla ihmisillä tai peruuttamattomissa olosuhteissa; siihen ei tarvita hallituksen lupaa eikä työnantajan siunausta. Jokainen osallistuja harjoittelee simulaatiossa, kunnes harjoittelusta tulee osaamista ja sitten valmiutta. Kiertomalli vie jokaisen osallistujan kolmen perustajaalueen läpi, ja jokainen kierros päättyy julkiseen juhlaan, joka on avoin isäntäyhteisölle. Tämä on kunnioitusta nuorta ihmistä kohtaan, jonka ensimmäinen virhe ei saa koskaan maksaa henkeä.`,
      333: `Jokainen hallitsemisen arvoinen taito opittiin joltakulta ennen kuin se tunnettiin. Mestarikäsityöläiset harjoittelevat ennen esitystä, lentäjät ennen lentoa, lääkärit ennen leikkausta, lapset leikin kautta. Atlantis-sopimus palauttaa tämän muinaisen viisauden sen keskiöön, miten nuoria — ja ketä tahansa liittyvää kansalaista, ilman hallituksen lupaa tai työnantajan siunausta — valmistetaan rakentamaan tulevaisuutta. Mitään merkityksellistä ei opita ensin elävällä laitteistolla, todellisilla ihmisillä tai peruuttamattomissa olosuhteissa. Jokainen osallistuja harjoittelee simulaatiossa, kunnes harjoittelusta tulee osaamista ja sitten valmiutta. Tämä ei ole varovaisuutta — tämä on kunnioitusta nuorta ihmistä kohtaan, jonka ensimmäinen virhe ei saa koskaan maksaa kenellekään hänen henkeään.

Sopimuksen kiertomalli vie jokaisen osallistujan kolmen perustajaalueen läpi. Se, mikä opitaan Kambodžassa, hiotaan Hondurasissa ja viimeistellään Austinissa. Se, mikä keksitään Austinissa, kyseenalaistetaan Kambodžassa ja yhdistetään Hondurasissa. Jokainen osallistuja elää, oppii ja saa mentorointia kulttuurien välillä, jotka muuten pysyisivät etäisinä. Koulutusohjelma ammentaa monien kulttuurien kurinalaisista simulaatioperinteistä — Sun Tzun strategisesta kasvatusperinteestä, Musashin leikin kautta harjoittelusta, Ibn Khaldunin syklisestä oppimisteoriasta, Nalandan luostaridialektiikasta, siviili-lentosimulaattorista — yhdistettynä kunnioittamaan jokaista kognitiivista vaihetta ja kulttuuriperintöä. Yksikään yksittäinen perinne ei hallitse.

Jokainen kierros päättyy julkiseen juhlaan, joka on avoin isäntäyhteisölle ja jossa naapurit, perheet ja vierailijat näkevät, mitä kohortti on oppinut. Nämä tapahtumat tekevät kehittyneestä teknologiasta saavutettavaa ja juhlittavaa pelottavan sijaan — yhteiskuntaa, joka kasvaa ymmärtäen yhteistoiminnalliset järjestelmät leikin kautta, ei voida helposti manipuloida pelolla niitä kohtaan. Tämä on pelotetta koulutuksen, ei voiman, kautta. Sopimuksen lupaus jokaiselle vanhemmalle: lapsesi harjoittelee tuhat kertaa turvallisesti ennen kuin koskettaa mitään, joka voisi vahingoittaa häntä, todistettuna niin, että kansalainen — kuka tahansa kansalainen, vuosisata tästä eteenpäin — voi vahvistaa, että se tapahtui täsmälleen niin kuin tallennettiin. Tämä on kunnioitusta nuorta ihmistä kohtaan, rakennettuna viitekehykseen, ja se on sitä, mitä johtajuus on velkaa seuraavalle liittyvälle kansalaiselle ennen kuin hänen täytyy vaatia sitä.`,
      999: `Jokainen hallitsemisen arvoinen taito opittiin joltakulta ennen kuin se tunnettiin, ja jokainen kestänyt sivilisaatio kesti juuri siksi, että se suojeli tilaa, jossa tämä oppiminen saattoi tapahtua turvallisesti, ennen kuin siltä vaadittiin merkitystä. Mestarikäsityöläiset harjoittelevat ennen esitystä, lentäjät harjoittelevat ennen lentoa, lääkärit harjoittelevat ennen leikkausta, ja lapset harjoittelevat maailmaa leikin kautta. Atlantis-sopimus palauttaa tämän muinaisen viisauden sen keskiöön, miten nuoria valmistetaan rakentamaan tulevaisuutta, ja se antaa tälle viisaudelle nimen ja mekanismin: Replay. Mitään merkityksellistä ei opita ensin elävällä laitteistolla, todellisilla ihmisillä tai peruuttamattomissa olosuhteissa. Jokainen osallistuja harjoittelee simulaatiossa, kunnes harjoittelusta tulee osaamista ja sitten valmiutta, ja jokainen harjoittelutunti tallennetaan, jotta se voidaan myöhemmin rekonstruoida, tutkia ja siihen voidaan luottaa. Tämä ei ole varovaisuutta — tämä on kunnioitusta nuorta ihmistä kohtaan, jonka ensimmäinen virhe ei saa koskaan maksaa kenellekään hänen henkeään, ja se on kunnioitusta tallennetta kohtaan, joka elää virheen yli joka tapauksessa.

Sopimuksen kiertomalli vie jokaisen osallistujan kolmen perustajaalueen läpi. Se, mikä opitaan Kambodžassa, hiotaan Hondurasissa ja viimeistellään Austinissa. Se, mikä keksitään Austinissa, kyseenalaistetaan Kambodžassa ja yhdistetään Hondurasissa. Jokainen osallistuja elää, oppii ja saa mentorointia kulttuurien välillä, jotka muuten pysyisivät etäisinä, ja jokainen kierros alkaa samalla tavalla kuin jokainen luottamuksen arvoinen inhimillinen instituutio alkaa: Seedillä. Seed on kertaluonteinen jäsenyys, jonka hinta on seitsemäsosa paikallisen minimipalkan tunnista, ei-siirrettävissä, eikä se kanna minkäänlaista taloudellista vaadetta. Se ei ole maksu mahdollisuuden saamisesta. Se on kynnys — riittävän pieni, ettei kukaan halukas osallistuja jää sen ulkopuolelle, ja riittävän tarkoituksellinen, että osallistumiseen liitytään valiten, ei ajelehtien. Tästä kynnyksestä eteenpäin jokainen osallistuja kuuluu kiertoon, eikä kierto kuulu yksinään millekään yksittäiselle alueelle.

Koulutusohjelma ammentaa monien kulttuurien kurinalaisista simulaatioperinteistä — Sun Tzun strategisesta kasvatusperinteestä, Musashin leikin kautta harjoittelusta, Ibn Khaldunin syklisestä oppimisteoriasta, Nalandan luostaridialektiikasta, siviili-lentosimulaattorista — yhdistettynä kunnioittamaan jokaista kognitiivista vaihetta ja kulttuuriperintöä. Yksikään yksittäinen perinne ei hallitse. Ja tämän ohjelman sisällä sopimus vetää rajan, jonka jokainen osallistuja oppii varhain eikä koskaan unohda: simulaatio on paikka, jossa Hyväksytty Innovaatiopisteytys ymmärretään, ei paikka, jossa se käytetään. QIS on mittaus, ei koskaan maksu, eikä QIS ole koskaan omistajuutta — se on olemassa kuvaamaan, kuinka hyvin ehdotus perustelee itsensä, kestää tarkastelun ja palvelee aluetta, jota se väittää palvelevansa. QIS:n kasvu voi mitoittaa palkintopoolin todellisen kelpoisuuden jälkeen, mutta se ei lyö mitään omasta takaa. Osallistuja voi ajaa sata virheetöntä simulaatiota ja ansaita nousevan pisteytyksen ilman että yksikään 웃-tunti koskettaa hänen tiliään, koska 웃 myönnetään vain todistetusta työstä, joka tehdään rajatun, budjetoidun ja hyväksytyn tehtävän alaisuudessa. Ennen tätä hyväksyntää kaikki — kuinka taitavaa tai lupaavaa tahansa — on suunnittelua. Sopimus opettaa tämän eron heti ensimmäisenä päivänä, jotta yksikään nuori ei sekoita harjoittelua palkintoon eikä yksikään nuori tule koskaan johdetuksi harhaan siitä, mihin simulaatio on tarkoitettu.

Tämä sama kurinalaisuus säätelee, kuinka paljon autonomiaa mille tahansa järjestelmälle, ihmiselle tai keinotekoiselle, sallitaan kierron sisällä. Sopimuksen toimintatilat etenevät järjestyksessä — Manuaalinen, sitten Puoliautomatisoitu, sitten Autonominen — eikä yksikään kuutio etene tilasta toiseen ennen kuin se läpäisee 11,1 prosentin mitatun parannuksen säännön, yhden yhdeksäsosan, todistettuna jäädytettyä lähtötasoa vasten ja tosiasiassa todistettuna, ei väitettynä. Simulaatio on paikka, jossa tämä todiste rakennetaan. Työkalu ansaitsee oikeuden toimia vähemmällä valvonnalla samalla tavalla kuin osallistuja ansaitsee oikeuden suurempaan vastuuseen: osoitetun, tallennetun ja rekonstruoitavissa olevan parannuksen kautta, kuutio kuutiolta, ei koskaan kaikkea kerralla, eikä koskaan sen tason yli, jolla merkitys, raha ja laki päätetään. Tämä taso kuuluu yksin Human Authoritylle, sekä simulaatiossa että elävässä toiminnassa, koska harjoittelutila, joka opettaa väärän rajan, opettaa väärän opetuksen pysyvästi.

Jokainen kierros päättyy julkiseen ja yhteistoiminnalliseen juhlaan, joka on avoin isäntäyhteisölle. Naapurit, perheet ja vierailijat kokoontuvat näkemään, mitä kohortti on oppinut, ja se, mitä he todistavat, ei ole nopeuden esittelyä sen itsensä vuoksi vaan ◬:n esittely — mitattu delta jäädytetyn lähtötason ja sen välillä, mitä kurinalainen harjoittelu todella saavutti, esitettynä rehellisesti, ei koskaan puettuna voittomittariksi, ei koskaan esitettynä enempänä kuin se on. Nämä tapahtumat tekevät kehittyneestä teknologiasta saavutettavaa ja juhlittavaa pelottavan sijaan. Yhteiskuntaa, joka kasvaa ymmärtäen yhteistoiminnalliset järjestelmät leikin kautta, ei voida helposti manipuloida pelolla näitä järjestelmiä kohtaan. Tämä on pelotetta koulutuksen, ei voiman, kautta, ja se toimii, koska yhteisöä ei pyydetä luottamaan väitteeseen — sitä kutsutaan katsomaan Replay.

Sopimuksen lupaus jokaiselle vanhemmalle ulottuu turvallisuuden yli pysyvyyteen: lapsesi harjoittelee tuhat kertaa ennen kuin koskettaa mitään, joka voisi vahingoittaa häntä, yhteisö todistaa hänen kasvunsa koko ajan, eikä mikään siitä katoa ajan mukana. Measurement of Time tallentaa todelliset minuutit erillään jokaisesta muusta sopimuksen pitämästä tilikirjasta, jotta harjoitellut tunnit ja todistetut tunnit eivät koskaan sekoitu keskenään, ja jotta osallistujan todellinen kehityshistoria — ei tiivistelmä, ei arvio, vaan itse rekonstruoitavissa oleva tallenne — pysyy hänen saatavillaan niin kauan kuin hän haluaa sitä tarkastella. Vanhempi Phnom Penhissä, mentori Tegucigalpassa, tarkastaja Austinissa tai lapsenlapsi, joka lukee tallennetta vuosisata tästä eteenpäin, voivat kaikki saavuttaa saman Replayn ja nähdä saman totuuden.

Tältä näyttää kunnioitus nuorta ihmistä kohtaan, kun se on rakennettu viitekehykseen sen sijaan, että sitä vain luvattaisiin, ja tätä johtajuus antaa seuraavalle osallistujasukupolvelle ennen kuin sen sukupolven täytyy vaatia sitä: harjoittelutila, joka on tarpeeksi laaja epäonnistuakseen siinä turvallisesti, tarpeeksi rehellinen tallentaakseen uskollisesti, ja tarpeeksi kurinalainen pitääkseen palkinnon, autonomian ja vallan täsmälleen siellä, minne osaaminen on ne ansainnut — ei koskaan niiden edellä, eikä koskaan niiden jäljessä.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Turvallisuus varmennettu ennen luottamuksen ojentamista`,
    content: {
      7: `Turvallisuus ensin todistettu, sitten luottamus ojennettu.`,
      33: `Jokainen tila ja kierto sijaitsee suojaavan kehän sisällä varhaisvaroituksella. Laitteisto kieltäytyy aseistamisesta — todistettavasti, ei vain luvattuna, kansalaisten tarkastettavissa. Tallenteet kestävät myllerryksen. Turvallisuus rakennetaan nuorimman osallistujan ympärille, päivittäin.`,
      111: `Ennen kuin luottamusta laajennetaan, turvallisuus täytyy todistaa — ei hallitukselle, vaan kenelle tahansa kansalaiselle, joka sitä tarkastaa. Atlantis-sopimus on maailman kansalaisten välinen sopimus; sen perustava sitoumus on tämä: jokainen sopimuksen tila, jokainen kiertoreitti, jokainen paikka, jossa nuori osallistuja nukkuu tai opiskelee, sijaitsee dokumentoidun suojaavan kehän sisällä, jolla on varhaisvaroituskyky, joka antaa yhteisölle tunteja, ei minuutteja, reagoida mihin tahansa uskottavaan riskiin. Jokainen laite, jokainen anturi, jokainen koordinaatiojärjestelmä on sidottu laitteistotasolla kieltäytymään uudelleenkäytöstä asejärjestelmien integroinnissa. Tämä ei ole politiikkaa — tämä on fysiikkaa. Sopimus säilyy kunnioitettavana myllerryksen läpi, koska jokainen suunnitelma asettaa inhimillisen arvokkuuden ensimmäiseksi.`,
      333: `Ennen kuin luottamusta laajennetaan, turvallisuus täytyy todistaa — todistaa kansalaisille, ei vain väittää. Atlantis-sopimus on maailman kansalaisten välinen sopimus: kuka tahansa, missä tahansa, voi auttaa pitämään siitä kiinni, riippumatta siitä, mitä hänen hallituksensa allekirjoittaa. Jokainen sopimuksen tila, jokainen kiertoreitti, jokainen paikka, jossa nuori osallistuja nukkuu tai opiskelee, sijaitsee dokumentoidun suojaavan kehän sisällä, jolla on varhaisvaroituskyky, joka antaa yhteisölle tunteja, ei minuutteja, reagoida mihin tahansa uskottavaan riskiin. Teknologia, joka suojelee heitä, on sama teknologia, jota sopimus opettaa heitä rakentamaan. Nuoret oppivat turvallisuuden sisältä ulospäin, ei kertomalla heille, että he ovat turvassa, vaan näkemällä sen rakennettuna heidän ympärilleen joka päivä, ja tietäen, että kuka tahansa kansalainen voi vahvistaa tallenteen Replayn kautta.

Sopimus antaa rikkomattoman lupauksen siitä, mitä sen teknologia ei voi koskaan muuttua. Jokainen laite, jokainen anturi, jokainen koordinaatiojärjestelmä on sidottu laitteistotasolla kieltäytymään uudelleenkäytöstä asejärjestelmien integroinnissa. Tämä ei ole politiikan kieltä, ei toivetta. Tämä on fyysinen mahdottomuus, kryptografisesti täytäntöönpantu, jokaisen allekirjoittajaalueen vahvistama ja jokaisen sitä rahoittavan kansalaisen tarkastettavissa. Työkaluja, jotka suojelevat lasta Phnom Penhissä, ei voida ottaa uudelleenkäyttöön vahingoittamaan lasta Austinissa. Työkaluja, jotka yhdistävät parviharjoituksen Tegucigalpassa, ei voida määrittää uudelleen kohdistumaan ihmiseen missään. Tämä on sopimuksen vastaus vuosisadan mittaiseen kaksikäyttöteknologian pelkoon. Ei politiikkaa — fysiikkaa.

Sopimus säilyy kunnioitettavana myllerryksen läpi. Jos alue menettää poliittisen vakautensa, jäljelle jäävät alueet pitävät osallistujista huolen. Jos rahoitus supistuu, apurahat suojataan ensin — kansalaisten kuukausittain rahoittamina, ei koskaan apureittinä, jokainen dollari jäljitettävissä. Jos digitaalisia tallenteita vastaan hyökätään, offline-varmuuskopiot säilyvät. Jos matkustaminen muuttuu mahdottomaksi, alusta jatkuu virtuaalisesti. Jokainen suunnitelma asettaa inhimillisen arvokkuuden — Human Authorityn merkityksen, rahan ja lain yli — ensimmäiseksi suunnittelurajoitteekseen. Johtajat, jotka allekirjoittavat tämän sopimuksen, lupaavat, että turvallisuus rakennetaan, ei oleteta: sama suoja, jonka mikä tahansa johtaja vaatisi omalle lapselleen, ulotettuna nyt jokaiseen kansalaiseen, joka auttaa pitämään siitä kiinni.`,
      999: `Ennen kuin luottamusta laajennetaan, turvallisuus täytyy todistaa — tämä on Atlantis-sopimuksen perustava sitoumus, ja se todistetaan samalla tavalla kuin jokainen muu Vision • 2525:n sisäinen väite todistetaan: ei väittämällä, vaan todisteilla, joita kansalaiset voivat tarkastaa. Jokainen sopimuksen tila, jokainen kiertoreitti, jokainen paikka, jossa nuori osallistuja nukkuu tai opiskelee, sijaitsee dokumentoidun suojaavan kehän sisällä, jolla on varhaisvaroituskyky, joka antaa yhteisölle tunteja, ei minuutteja, reagoida mihin tahansa uskottavaan riskiin. Teknologia, jota käytetään osallistujien suojelemiseen, on sama teknologia, jota sopimus opettaa heitä rakentamaan — antureita, koordinaatiota, viestinnän selviytymiskykyä, hajautettua älykkyyttä. Nuoret oppivat turvallisuuden sisältä ulospäin, omalla kielellään ja omalla alueellaan, ei kertomalla heille, että he ovat turvassa, vaan seuraamalla tunti tunnilta, miten turvallisuus rakennetaan heidän ympärilleen päivittäin.

Tätä seuraamista ei jätetä muistin tai fasilitaattorin sanaan luottamisen varaan. Measurement of Time tallentaa jokaisen harjoituksen, jokaisen kierron, jokaisen vastausharjoituksen todelliset minuutit — erillään mistä tahansa edistymisväitteestä, erillään mistä tahansa sinä päivänä kerrotusta tarinasta. Replay tekee jokaisesta koulutusohjelman julkaisusta, jokaisesta turvallisuuspäivityksestä, jokaisesta laitteistorevisiosta täysin rekonstruoitavissa olevan, jotta vanhempi Tegucigalpassa tai sääntelyviranomainen Phnom Penhissä voi kävellä taaksepäin täsmälleen sen läpi, mikä muuttui, milloin se muuttui ja miksi se muuttui. Suojaava kehä, jota ei voida toistaa Replayn kautta, on vain lupaus. Suojaava kehä, joka voidaan toistaa, minuutti tallennettu minuutilta, on todiste. Sopimus valitsee todisteen.

Sopimus antaa rikkomattoman lupauksen siitä, mitä sen teknologia ei voi koskaan muuttua. Jokainen laite, jokainen anturi, jokainen koordinaatiojärjestelmä on sidottu laitteistotasolla kieltäytymään uudelleenkäytöstä asejärjestelmien integroinnissa. Tämä ei ole politiikan kieltä, ei toivetta. Tämä on fyysinen mahdottomuus, kryptografisesti täytäntöönpantu, jokaisen allekirjoittajaalueen vahvistama ja jokaisen kansalaisen tarkastettavissa. Työkaluja, jotka suojelevat lasta Phnom Penhissä, ei voida ottaa uudelleenkäyttöön vahingoittamaan lasta Austinissa. Työkaluja, jotka yhdistävät parviharjoituksen Tegucigalpassa, ei voida määrittää uudelleen kohdistumaan ihmiseen missään. Tämä on sopimuksen vastaus vuosisadan mittaiseen kaksikäyttöteknologian pelkoon. Ei politiikkaa — fysiikkaa.

Kerran todistettu turvallisuus ei ole ylläpidettyä turvallisuutta viisisataavuotisen aikahorisontin yli. Sopimus nimeää toisen sitoumuksensa nimellä Continuity Without Evasion: laillista siirrettävyyttä jokaisella lainkäyttöalueella, jota sopimus koskettaa, ilman että yksikään korvaamaton hallitus, pankki, perustaja tai malli seisoisi osallistujan ja hänen suojansa välissä. Jokaista lainkäyttöaluetta palvellaan sen omalla sovittimella, joka epäonnistuu suljettuna ja on oletusarvoisesti kielletty, jotta kielteinen päätös millä tahansa yhdellä alueella sulkee vain sen yhden kanavan — ei koskaan koko viitekehystä, ei koskaan jokaista aluetta, ei koskaan jokaista osallistujaa kaikkialla kerralla. Tuomioistuimen päätös yhdellä allekirjoittaja-alueella ei voi sammuttaa osallistujan turvakehää toisaalla. Tämä tarkoittaa järjestelmän rakentamista, joka selviää lain, politiikan ja institutionaalisen muutoksen tavanomaisesta myllerryksestä ilman, että osallistujaa koskaan pyydetään kiertämään lakia pysyäkseen suojattuna.

Jokainen tämän suojaavan arkkitehtuurin taso vastaa loppujen lopuksi Human Authoritylle. Merkitystä, rahaa ja lakia ei koskaan delegoida koneille — suvereeni taso, joka päättää, mitä turvallisuus vaatii, mikä lasketaan uskottavaksi riskiksi ja minkä vastauksen yhteisö on velkaa nuorimmille jäsenilleen, pysyy suljettuna tekoälyltä, riippumatta siitä, kuinka kyvykkääksi se kehittyy. Sopimuksen järjestelmät etenevät vain kolmen toimintatilan läpi — Manuaalinen, Puoliautomatisoitu, Autonominen — eikä yksikään järjestelmä etene tilasta toiseen ilman todistettua, mitattua vähintään yhden yhdeksäsosan parannusta, yhtätoista ja yhtä kymmenesosaprosenttia, vahvistettuna ja toistettavissa olevana. Autonomia ansaitaan kuutio kuutiolta, toiminto toiminnolta, ei koskaan myönnetä kokonaisuutena, eikä koskaan ulotu kysymyksiin, jotka määrittävät merkityksen, rahan tai lain. Anturi voi oppia havaitsemaan nopeammin. Koordinaatiojärjestelmä voi oppia reitittämään tehokkaammin. Kumpaakaan ei koskaan sallita päättää yksin, mihin yhteisön tulisi luottaa lastensa kanssa.

Sopimus on suunniteltu säilymään kunnioitettavana myllerryksen läpi, ja se nimeää myllerryksen etukäteen sen sijaan, että löytäisi sen kriisissä. Jos allekirjoittaja-alue menettää poliittisen vakautensa, jäljelle jäävät alueet pitävät osallistujista huolen. Jos rahoitus supistuu, osallistujien apurahat suojataan ensin, ennen hallintoa ja infrastruktuuria. Jos digitaalisia tallenteita vastaan hyökätään, offline-varmuuskopiot säilyvät, tavoittamattomissa mistä tahansa häiriöstä, joka ylsi verkkoon. Jos matkustaminen muuttuu mahdottomaksi, alusta jatkuu virtuaalisesti, jotta kierto ei pysähdy rajan sulkeutuessa. Jokaiseen skenaarioon on varauduttu, ja jokainen suunnitelma asettaa inhimillisen arvokkuuden ensimmäiseksi suunnittelurajoitteekseen — ei viimeiseksi huomioksi sen jälkeen, kun budjetit ja mielikuvat on sovittu.

Astuminen tähän todistettuun järjestelmään alkaa Seedillä — kertaluonteisella jäsenyydellä, jonka hinta on seitsemäsosa paikallisen minimipalkan tunnista, ei-siirrettävissä, eikä se kanna minkäänlaista taloudellista vaadetta mihinkään, mitä sopimus rakentaa jälkeenpäin. Seed ei osta turvallisuutta; turvallisuus rakennetaan kauan ennen kuin yhtään Seediä koskaan istutetaan. Se, minkä Seed ostaa, on asema — oikeus astua viitekehykseen, joka on jo todistettu, jo tarkastettu, jo sidottu laitteistoon, jota ei voida kääntää sitä henkilöä vastaan, jota se on olemassa suojellakseen. Tämä erottelu on tarkoituksellinen. Turvallisuuslupaus, joka täytyy ostaa todellisella taloudellisella painolla, ei ole turvallisuuslupaus lainkaan, vaan pelkkä turvallisuustuote. Sopimus pitää nämä kaksi täysin erillään, jotta yhdenkään perheen ei koskaan tarvitse punnita lapsensa suojaa kotitaloutensa kuukausibudjettia vasten.

Johtajat, jotka allekirjoittavat tämän sopimuksen, allekirjoittavat lupauksen siitä, että turvallisuus rakennetaan, ei oleteta, ja todistetaan, ei vain väitetä. Se, minkä he ulottavat kansalaisilleen, ei ole vain mahdollisuus, vaan suojaus, joka on rakennettu sen standardin mukaisesti, jonka nuorin osallistuja ansaitsee — Measurement of Timen tallentamana, Replayn kautta rekonstruoitavissa, laitteistotasolla sidottuna jokaista väärinkäyttöä vastaan, jonka pelokas vuosisata on kuvitellut, ja vastuussa aina ja yksinomaan Human Authoritylle. Tämä on sama suoja, jonka mikä tahansa johtaja vaatisi omalle lapselleen, joka ylittää tuntemattoman rajan yksin, ulotettuna nyt jokaiseen lapseen, jota sopimus koskaan tulee palvelemaan, sen kolmella perustaja-alueella Kambodžassa, Hondurasissa ja Austinissa, sekä viiden vuosisadan yli, joiden aikana sopimus aikoo pitää tämän lupauksen.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Korvaus, hyvinvointi ja ihmisarvo`,
    content: {
      7: `Apuraha, mentori, koti.`,
      33: `Jokainen kansalainen saa apurahan ensimmäisestä päivästä lähtien — ei hallituksen lupaa, ei työnantajan siunausta. Rakkaus, menetys ja turvallisuus ovat infrastruktuuria. Menestystä mitataan haavoittuvaimman mukaan. Arvokkuus on perusta, ei koskaan koristelu.`,
      111: `Atlantis-sopimus kohtelee jokaista osallistujaa ihmisenä ensimmäisestä päivästä lähtien — kansalaisena, joka liittyi oikeutensa nojalla, ei hallituksen määräyksestä eikä työnantajan luvalla. Apuraha annetaan siitä hetkestä lähtien, kun osallistuminen alkaa, indeksoituna alueen elinkustannuksiin, ja jokainen todistettu tunti ansaitsee 웃:n, joka maksetaan henkilölle Livelihood Directin kautta, ei koskaan työnantajan tilikirjan kautta. Hyvinvointia kohdellaan ensiluokkaisena infrastruktuurina — ei etuna, vaan perustana, jonka varaan kaikki muu seisoo. Kolmea aluetta tuetaan: Rakkautta, Menetystä ja Turvallisuutta. Sopimus mittaa menestystä haavoittuvaimman osallistujansa mukaan, ei keskiarvon. Ketään ei unohdeta, jotta keskiarvot näyttäisivät hyviltä. Arvokkuus perustana, ei koristeluna.`,
      333: `Atlantis-sopimus kohtelee jokaista osallistujaa ihmisenä ensimmäisestä päivästä lähtien — kansalaisena, joka kuuluu joukkoon oikeutensa nojalla, tarvitsematta hallituksen lupaa eikä työnantajan siunausta. Apuraha annetaan siitä hetkestä lähtien, kun osallistuminen alkaa, indeksoituna alueen elinkustannuksiin, saapuen ennen kuin perhevelvoitteista tulee hätätilanteita. Tämä ei ole hyväntekeväisyyttä. Tämä on tunnustus siitä, että tavallinen inhimillinen innovaatio vaatii ensin inhimillistä turvaa — mieli ei voi kukoistaa, kun sen kotitalous on uhattuna.

Se, mikä ansaitaan apurahan lisäksi, ansaitaan samoin kuin kansalainen sen ansaitsee: Seedin kautta, jonka hinta on seitsemäsosa paikallisen minimipalkan tunnista, ja 웃:n kautta, joka maksetaan vain todistetuista tunneista. QIS mittaa lupausta, mutta ei lyö mitään — mittausta, ei koskaan maksua. Jokainen maksu saavuttaa osallistujan Livelihood Directin kautta, lisensoitujen paikallisten kanavien kautta, joita sopimus ei koskaan säilytä, rakennettuna Continuity Without Evasion -periaatteelle.

Hyvinvointia kohdellaan ensiluokkaisena infrastruktuurina — ei etuna, vaan perustana, jonka varaan kaikki muu seisoo. Sopimus nimeää kolme aluetta, joiden kautta jokaista osallistujaa tuetaan: Rakkaus, yhteys ja terve rajanveto; Menetys, sillä suru täytyy kulkea läpi, ei sen ohi; ja Turvallisuus, tietäen kenelle soittaa, jokaisella alueella, omalla kielellään. Neuvontaa, ryhmäpiirejä sekä kulttuurisia tai hengellisiä käytäntöjä, joita kunnioitetaan perinteen mukaan, tarjotaan. Ei pakotettua ideologiaa; Human Authority, ei koskaan kone, päättää, millaista hoivaa kansalainen tarvitsee.

Sopimus mittaa menestystä haavoittuvaimman osallistujansa mukaan, ei keskiarvon. Maaseudun kansalaisia ilman nopeaa yhteyttä palvellaan. Neuroepätyypilliset osallistujat saavat mukautuksia normina. Vammaiset osallistujat huomaavat jokaisen tilan esteettömäksi. Sukupuoleltaan moninaiset osallistujat saavat turvallisen majoituksen ja mentoriparituksen. Ei-äidinkielenään puhuvat löytävät jokaisen materiaalin omalla kielellään. Alkuperäiskansojen osallistujat huomaavat kulttuurikäytäntönsä kunnioitetuiksi ja perinteisen tietonsa suojatuksi. Johtajat, jotka allekirjoittavat tämän sopimuksen, lupaavat, ettei yhtäkään kansalaista unohdeta, jotta keskiarvot näyttäisivät hyviltä. Tämä on arvokkuutta perustana, ei koristeluna. Se, mitä mitataan, on se, mitä kunnioitetaan, ja se, mitä täällä kunnioitetaan, on koko ihminen — mieli, keho ja henki, jota kanssakansalaiset kannattelevat, poikkeuksetta.`,
      999: `Atlantis-sopimus kohtelee jokaista osallistujaa täytenä ihmisenä ensimmäisestä päivästä lähtien, rakennettuna mekanismiksi, ei vain kieleksi. Apuraha annetaan siitä hetkestä lähtien, kun osallistuminen alkaa, indeksoituna alueen elinkustannuksiin niin, että sen vaikutus kunnioittaa paikallista työn arvokkuutta. Apuraha saapuu ennen kuin perhevelvoitteista tulee hätätilanteita ja ennen kuin arvokkuus vaarantuu. Se osoittaa jokaiselle nuorelle, että hänen aikansa on arvokasta, hänen panostaan odotetaan ja hänen perheensä vakaus on osa sopimuksen vastuuta. Tämä ei ole hyväntekeväisyyttä. Tämä on tunnustus siitä, että tavallinen inhimillinen innovaatio vaatii ensin inhimillistä turvaa. Mieli ei voi kukoistaa, kun sen kotitalous on uhattuna. Itse liittyminen kantaa pienen, tarkoituksellisen kynnyksen: Seedin, kertaluonteisen jäsenyyden, jonka hinta on seitsemäsosa paikallisen minimipalkan tunnista, ei-siirrettävissä eikä kantaen omaa taloudellista vaadetta. Seed kertoo vain, että henkilö on liittynyt; se ei maksa hänelle mitään eikä lupaa hänelle mitään sen oven lisäksi, jonka se avaa.

Se, mikä ansaitaan tämän oven avautumisen jälkeen, hallitaan samalla tarkkuudella, jonka sopimus tuo jokaiseen muuhun lupaukseensa. 웃, sopimuksen Inhimillisen Älyn mittari, lasketaan yksinkertaisesti — yksi tunti paikallista minimipalkkaa, kerrottuna Kertoimella, joka heijastaa tehtävän vaikeutta ja arvoa, kerrottuna todella tehdyillä tunneilla. Mutta 웃 myönnetään vain todistetusta työstä, joka tehdään rajatun, budjetoidun ja hyväksytyn tehtävän alaisuudessa. Ennen tämän hyväksynnän olemassaoloa se, mitä osallistuja tekee, on suunnittelua, ei ansaitsemista — ero, jota sopimus pitää tiukasti kiinni, koska se suojaa sekä kassaa että osallistujaa lupauksilta, jotka tehdään nopeammin kuin arvo vahvistetaan. Measurement of Time, MoT, tallentaa tehdyt todelliset minuutit erillään mistä tahansa korvauslaskelmasta, jotta aika pysyy rehellisenä, tarkastettavissa olevana tosiasiana riippumatta maksusta. Yhdenkään osallistujan tunteja ei paisuteta, eikä yhdenkään osallistujan tunteja katoa. Vuotuinen 9 999 웃:n selvityskatto koskee jokaista osallistujaa, ja mahdollinen ylijäämä siirtyy eteenpäin sen sijaan, että se katoaisi, jotta poikkeuksellinen panos tunnustetaan vuosien yli sen sijaan, että se rajoittuisi näkymättömiin yhden vuoden sisällä.

Korvaus pidetään tarkoituksellisesti erillään innovaation mittauksesta. Hyväksytty Innovaatiopisteytys, QIS, laskee keskiarvon Liikevaihdosta, Bruttovoitosta, Liiketoiminnan tuloksesta ja Tehokkaasta T&K-kulutuksesta kuvatakseen, kuinka paljon innovaatio todella kasvoi. Sen kasvu ajan mittaan voi mitoittaa palkintopoolin, kun kelpoisuus on täytetty, mutta QIS itsessään ei lyö yhtään 웃:aa eikä selvitä mitään suoraan — se on mittaus, ei koskaan maksu, eikä sitä koskaan sekoiteta rakennetun omistajuuteen. Tämä erottelu on tärkeä, koska se pitää apurahan ja palkan rehellisinä: osallistujalle maksetaan todistetuista todellisen työn tunneista, ei pisteytyksestä, jota voitaisiin manipuloida, paisuttaa tai kiistellä. ♡, Jaettu Aikomus, kantaa syyn jokaisen osallistujan ottaman tehtävän takana; ◬, todistettu kiihtyvyys, jonka tehtävä tuottaa jäädytettyä lähtötasoa vasten, tallennetaan vain deltana, ei koskaan puettuna voittomittariksi, joka liitettäisiin kenenkään työhön. Korvaus pysyy sinä, mitä se on: rehellinen palkka rehellisestä, todistetusta ajasta.

Arvo ei pysähdy laskelmaan — sen täytyy myös saavuttaa osallistuja elävänä ihmisenä, ja tässä 🏠, Livelihood Direct, tekee työnsä. Jokainen arvoyksikkö, jonka osallistuja ansaitsee, saavuttaa hänet hyväksyttyjen, lisensoitujen paikallisten kanavien kautta — pankkien, mobiilirahaoperaattoreiden, osuuskuntien, jotka jo nauttivat luottamusta ja sääntelyä kyseisellä alueella — ei koskaan rahaston kautta, jota sopimus itse säilyttää tai hallitsee. Osallistujan aseman luokittelu edeltää mitä tahansa selvitystä; mitään ei makseta ennen kuin on kunnolla ymmärretty, kenelle maksetaan ja mistä. Ja lahjakkuuden tunnustaminen, kuinka juhlittua tahansa, ei avaa pääsyä sänkyyn, ateriaan tai paikkaan kohortissa — sen tekee vain osallistujan todellinen rooli. Tämä on tarkoituksellinen kieltäytyminen antamasta arvovallan korvata huolenpitoa. Loistava panostaja ja hiljainen panostaja nukkuvat saman suojatun katon alla, samoin ehdoin, koska sopimuksen arvokkuussitoumukset eivät ole palkinto erinomaisuudesta myönnettynä — ne ovat lattia kaikkien alla.

Hyvinvointia kohdellaan ensiluokkaisena infrastruktuurina — ei valinnaisena etuna, ei hyvinvointibonuksena, vaan perustana, jonka varaan kaikki muu seisoo. Sopimus nimeää kolme perustavaa aluetta, joiden kautta jokaista osallistujaa tuetaan: Rakkaus, yhteyden, kiintymyksen ja terveen rajanvedon merkityksessä; Menetys, koska jokainen osallistuja kokee surua ja täytyy kulkea sen läpi, ei sen ohi; ja Turvallisuus, siinä merkityksessä, että jokainen osallistuja tietää kenelle soittaa, jokaisella alueella, omalla kielellään. Yksilöllistä neuvontaa, ryhmäpiirejä, kehollisia harjoitteita sekä kulttuurisia tai hengellisiä käytäntöjä, joita kunnioitetaan osallistujan oman perinteen mukaan, tarjotaan kaikkia. Ei pakotettua ideologiaa. Sopimus pitää tilaa kunnioituksella; se ei käännytä mihinkään uskomusjärjestelmään. Human Authority hallitsee jokaista näistä päätöksistä — merkitys, raha ja laki pysyvät suljettuina koneelliselta päätöksenteolta, riippumatta siitä, kuinka hienostunutta on se kuvionhaku, joka avustaa päättäviä ihmisiä.

Sopimus mittaa menestystä haavoittuvaimman osallistujansa lopputuloksen mukaan, ei keskiarvon. Maaseudun osallistujia ilman nopeaa yhteyttä palvellaan. Neuroepätyypilliset osallistujat saavat mukautuksia normina. Vammaiset osallistujat huomaavat jokaisen tilan esteettömäksi. Sukupuoleltaan moninaiset osallistujat saavat turvallisen majoituksen ja mentoriparituksen. Ei-äidinkielenään puhuvat löytävät jokaisen materiaalin omalla kielellään. Alkuperäiskansojen osallistujat huomaavat kulttuurikäytäntönsä kunnioitetuiksi ja perinteisen tietonsa suojatuksi. Johtajat, jotka allekirjoittavat tämän sopimuksen, lupaavat, ettei yhtäkään osallistujaa hiljaa unohdeta, jotta keskiarvot näyttäisivät hyviltä.

Jokainen tässä kuvattu maksureitti — Seed, apuraha, todistetusta työstä ansaittu 웃, sen toimittava Livelihood Directin kanava — on suunniteltu Continuity Without Evasionia varten. Yksikään pankki, hallitus tai paikallinen toimija ei ole korvaamaton minkään osallistujan korvaukselle; jos yksi lisensoitu kanava yhdellä lainkäyttöalueella suljetaan kielteisellä päätöksellä, vain se kanava epäonnistuu, ei koskaan koko järjestelmä, eikä koskaan osallistujan oikeus siihen, mikä hänelle kuului. Tämä on arvokkuutta perustana, ei koristeluna. Se, mitä mitataan, on se, mitä kunnioitetaan, ja se, mitä täällä kunnioitetaan, on koko ihminen — mieli, keho ja henki yhdessä, rehellisesti maksettuna, täysin suojattuna ja unohtamattomana missään kirjanpidossa, ilman poikkeuksia lainkaan.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Rahoitus ja hallinto`,
    content: {
      7: `Kansalaiset rahoittavat suoraan seuraavan sukupolven.`,
      33: `Atlantis-sopimus on kansalaisten välinen sopimus — kuka tahansa voi rahoittaa sitä ja pitää siitä kiinni. Ei apureittiä, ei ulkomaista hyväntekijää, ei poliittisia siteitä. Jokainen dollari on jäljitettävissä, ja kirjanpito julkaistaan kuukausittain jokaisella kielellä.`,
      111: `Atlantis-sopimus on maailman kansalaisten välinen sopimus — kuka tahansa, missä tahansa, voi auttaa luomaan sen ja pitämään siitä kiinni, riippumatta siitä, mitä hänen hallituksensa allekirjoittaa tai kuka häntä työllistää. Hallitukset, kasvattajat ja innovaattorit allekirjoittavat alueidensa huoltajina; kansalaiset rahoittavat, todistavat ja pitävät sopimuksen tilivelvollisena suoraan, kukin osallistuen pienillä vapaaehtoisilla summilla joka kuukausi, riittävän vaatimattomilla, ettei kukaan aikuinen jää niiden ulkopuolelle. Mukana ei ole apureittiä, ei ulkomaista hyväntekijää, ei poliittista sidettä. Sopimus seisoo itsenäisenä niistä monenkeskisistä instituutioista, jotka muovasivat viime vuosisataa — ei poliittinen kannanotto, vaan suunnitteluvalinta. Jokainen dollari on jäljitettävissä; jokainen kirjanpito julkaistaan kuukausittain, jokaisella kielellä.`,
      333: `Atlantis-sopimus on maailman kansalaisten välinen sopimus — kuka tahansa, missä tahansa, voi auttaa luomaan sen ja pitämään siitä kiinni, riippumatta siitä, mitä hänen hallituksensa allekirjoittaa tai kuka häntä työllistää. Sitä rahoittavat kansalaiset, joita se palvelee: osallistuvien alueiden asukkaat antavat pieniä vapaaehtoisia summia joka kuukausi, riittävän vaatimattomia, ettei kukaan aikuinen jää niiden ulkopuolelle, ja riittävän merkityksellisiä, että kokonaissumma kannattelee sopimuksen työtä laajassa mittakaavassa. Kun kansalainen rahoittaa seuraavaa sukupolvea suoraan, tämä kansalainen pitää sopimuksen tilivelvollisena suoraan. Mukana ei ole apureittiä, ei ulkomaista hyväntekijää, ei poliittista sidettä. Sopimuksen sielu on kansalainen, joka antaa yhden pienen summan joka kuukausi, jonka osallistuminen tekee kaiken mahdolliseksi.

Hallitus, Koulutus ja Innovaatio allekirjoittavat alueidensa huoltajina — kolme visionääristä allekirjoitusta, jotka sitovat alueen ottamaan vastaan, suojelemaan ja opettamaan — mutta huoltajuus ei ole omistajuutta. Sopimus on itsenäinen niistä monenkeskisistä instituutioista, jotka ovat muovanneet viime vuosisataa — Pohjois-Atlantin liitosta, Maailman terveysjärjestöstä, Yhdistyneistä kansakunnista, Kansainvälisestä valuuttarahastosta, Maailmanpankista ja jokaisesta kansallisesta ulkomaanavun kanavasta. Tämä on suunnitteluvalinta, ei poliittinen kannanotto: viitekehys, joka palvelee jokaista aluetta geopoliittisesta liittolaisuudesta riippumatta, ei voi olla sidoksissa mihinkään yksittäiseen liittolaisuuteen. Kansalliset hallitukset voivat osallistua vapaaehtoisesti. Osallistumiset ovat läpinäkyviä. Mikään osallistuminen ei osta hallinnollista vaikutusvaltaa, mistään lähteestä, koskaan.

Jokainen dollari ja jokainen sopimukseen astuva arvoyksikkö tallennetaan pysyvästi, julkisesti ja jäljitettävästi — Replayn kautta rekonstruoitavissa, jotta vuosisata tästä eteenpäin kansalainen voi vahvistaa ketjun katkeamattomaksi. Arvo saavuttaa osallistujan todistettujen 웃-tuntien ja lisensoitujen paikallisten kanavien kautta, ei koskaan rahaston, jota sopimus itse säilyttää; QIS mittaa rehellisesti, se ei koskaan maksa. Hallinnollisille kuluille on katto, ja yritysten lahjoituksille katto sen rinnalla. Täysi kirjanpito toimitetaan jokaisen allekirjoittaja-alueen kielellä joka kuukausi. Johtajat, jotka allekirjoittavat sopimuksen, lupaavat läpinäkyvyyttä, jota harva instituutio tarjoaa. Tämä on luottamus, jota sopimus vaatii — ansaittuna yksi pieni jäljitettävä osallistuminen kerrallaan, jokaisen kansalaisen silmien edessä.`,
      999: `Atlantis-sopimus itse on kansalaisten rahoittama, joita se palvelee, ja tämä yksi tosiasia muovaa kaikkea siitä alaspäin — jokaista kanavaa, jokaista tilikirjaa, jokaista porttia, jonka nuoren täytyy läpäistä tullakseen nähdyksi. Osallistuvien alueiden tavalliset asukkaat antavat pieniä vapaaehtoisia summia joka kuukausi, summia, jotka ovat riittävän vaatimattomia, ettei kukaan aikuinen millään isäntäalueella jää osallistumisen ulkopuolelle, ja riittävän merkityksellisiä, että kokonaissumma kannattelee sopimuksen työtä merkittävässä mittakaavassa. Tämä suunnittelu on tarkoituksellista, eikä se ole tehtävälle satunnaista — se on tehtävän todiste. Kun kansalainen rahoittaa seuraavan sukupolven koulutusta suoraan, tämä kansalainen pitää sopimuksen tilivelvollisena suoraan, samassa hengenvedossa, ilman välikättä, joka voisi pehmentää tiliä tai viivyttää tilintekoa. Mukana ei ole apureittiä, ei ulkomaista hyväntekijää, ei poliittista sidettä sekkiin. Sopimuksen sielu on kansalainen, joka antaa yhden pienen summan joka kuukausi, jonka osallistuminen tekee kokonaisuuden mahdolliseksi, ja jonka jatkuva osallistuminen on ainoa luottamuslause, joka lopulta merkitsee viiden vuosisadan aikana.

Sopimus on tarkoituksellisesti itsenäinen niistä monenkeskisistä instituutioista, jotka ovat muovanneet viime vuosisataa — Pohjois-Atlantin liitosta, Maailman terveysjärjestöstä, Yhdistyneistä kansakunnista, Kansainvälisestä valuuttarahastosta, Maailmanpankista ja jokaisesta kansallisesta ulkomaanavun kanavasta. Tämä ei ole poliittinen kannanotto näiden instituutioiden tai niiden panosten arvosta. Se on suunnitteluvalinta, ja se on sama suunnitteluvalinta, joka hallitsee jokaista teknistä kanavaa sopimuksen itsensä alla: Continuity Without Evasion. Laillinen siirrettävyys on sääntö — yksikään korvaamaton hallitus, pankki, perustaja tai malli ei saa istua koko rakenteen alla, koska viisisataavuotista aikahorisonttia ei voida panostaa minkään yksittäisen toimijan pysyvyyteen. Jokainen lainkäyttöalue kantaa oman sovittimensa, joka epäonnistuu suljettuna ja on oletusarvoisesti kielletty, jotta kielteinen päätös yhdessä kansakunnassa sulkee vain sen yhden kanavan yksinään — se ei koskaan kaada perheen tilejä valtameren takaisella alueella. Kansalliset hallitukset voivat osallistua vapaaehtoisesti. Osallistumiset ovat läpinäkyviä. Mikään osallistuminen ei osta hallinnollista vaikutusvaltaa, mistään lähteestä, koskaan — ei hallitukselta, ei yritykseltä, ei viitekehyksen omilta perustajilta.

Human Authority on toinen kantava pilari tämän rahoitussuunnittelun alla. Merkitys, raha ja laki pysyvät inhimillisinä asioina, joita ihmiset päättävät muiden ihmisten silmien edessä; suvereeni taso, jolla sopimuksen tarkoitus asetetaan ja sen varoja hallitaan, pysyy suljettuna koneilta, kuinka kyvykkäiksi tahansa ne kehittyvät sen alla olevissa tehtävissä. Measurement of Time tallentaa tehdyt todelliset minuutit erillään mistä tahansa niiden arvoa koskevasta väitteestä, jotta kukaan — ihminen tai keinotekoinen — ei voi hiljaa paisuttaa tallennetta. Replay seisoo jokaisen näistä tallenteista takana, tehden jokaisesta julkaisusta, jonka sopimus itse koskaan antaa, rekonstruoitavissa olevan alkuperästään lähtien, ikuisesti avoinna haastamiselle, ikuisesti avoinna korjaukselle. Kansalainen, joka antaa pienen summan tänään, luottaa siihen, että viidenkymmenen vuoden, kahdensadan vuoden kuluttua joku voi yhä kävellä ketjun takaisin tämän kuukauden tilikirjaan ja löytää sen täsmälleen sellaisena kuin se oli.

Astuminen tähän luottamusjärjestelmään alkaa Seedillä — kertaluonteisella jäsenyydellä, jonka hinta on seitsemäsosa paikallisen minimipalkan tunnista, ei-siirrettävissä eikä kantaen minkäänlaista taloudellista vaadetta. Seed ei osta osuutta, ei varallisuudella painotettua ääntä, ei etuoikeutettua asemaa seuraavassa kirjanpidossa. Se ostaa vain kuulumisen, hinnalla, joka on tarpeeksi matala, että nuori missä tahansa, missä sopimus itse toimii, voi varaa aloittaa. Kaikki, minkä jäsen ansaitsee sen jälkeen, ansaitaan, ei koskaan osteta, ja tämä ero on sopimuksen koko moraalinen arkkitehtuuri pienoiskoossa.

Arvo, joka todella virtaa henkilölle, virtaa 🏠 Livelihood Directin kautta — hyväksyttyjen, lisensoitujen paikallisten kanavien kautta, jotka kuljettavat maksun henkilölle, ei koskaan rahastoon, jota viitekehys itse säilyttää tai hallitsee. Luokittelu edeltää selvitystä joka tapauksessa; sänky, apuraha, paikka koulutuksen seuraavassa vaiheessa on porrastettu roolin ja valmiuden mukaan, ei koskaan pelkän tunnustuksen mukaan, koska tunnustus on halpaa eikä toimeentulo ole. Tämä on ketju, jota pitkin kansalaisen kuukausittainen osallistuminen todella kulkee: kansalaisen tililtä, tarkastetun kanavan kautta, apurahaan, jonka nuori saa, innovaatioprojektiin, joksi tämän nuoren työ muuttuu, ja takaisin ulos julkisena tilinä, jota kuka tahansa kansalainen voi lukea.

Se, minkä arvoinen tämä työ on, mitataan, ei oleteta. Hyväksytty Innovaatiopisteytys laskee keskiarvon valmiudesta, kasvupotentiaalista, lopputuloksen vaikutuksesta ja toteutusvalmiudesta yhdeksi luvuksi, ja tämän pisteytyksen kasvu mitoittaa palkintopoolin vasta kelpoisuuden täyttymisen jälkeen — QIS itsessään ei lyö mitään eikä selvitä mitään; se on mittaus, ei koskaan maksu, eikä mittausta koskaan sekoiteta täällä omistajuuteen. Maksu inhimillisestä työstä saapuu sen sijaan 웃:na, arvotettuna yhtenä tuntina kertaa paikallinen minimipalkka, kerrottuna rajatulla, budjetoidulla ja hyväksytyllä kertoimella todella tehdyistä ja todistetuista tunneista. Ennen kuin tehtävällä on tämä hyväksyntä, sen takana oleva työ on suunnittelua, ei korvattavaa työtä, eikä ketään makseta suunnittelusta. Vuotuinen 9 999 웃:n katto, jolloin mahdollinen ylijäämä siirtyy eteenpäin sen sijaan, että se katoaisi, estää minkä tahansa yksittäisen vuoden tiliä muuttumasta joko odottamattomaksi voitoksi tai ansaksi.

Mikään tästä ei etene nopeammin kuin oma todisteensa. Sopimus itse etenee Manuaalisesta Puoliautomatisoituun ja edelleen Autonomiseen toimintaan yksi kuutio kerrallaan, ja vain siellä, missä täysi mitatun parannuksen aste — yksi yhdeksäsosa — on todella osoitettu, ei koskaan etukäteen oletettu. Autonomia ansaitaan täsmälleen siellä eikä lähelläkään merkitystä, rahaa tai lakia, jotka pysyvät aina inhimillisinä. Hallinnollisille kuluille on katto. Yritysten ja instituutioiden lahjoitukset toivotetaan tervetulleiksi ja niille on katto sen rinnalla. Täysi kirjanpito toimitetaan jokaisen allekirjoittaja-alueen kielellä joka kuukausi, alkaen Kambodžasta, Hondurasista ja Austinista, ja on tarkoitus, että se toimitetaan yhä, ja on yhä luettavissa, viisisataa vuotta myöhemmin. Tämä on luottamus, jota sopimus vaatii. Tämä on luottamus, jonka sopimus ansaitsee, yksi pieni jäljitettävä osallistuminen kerrallaan, jokaisen kansalaisen silmien edessä, jota se koskaan tulee palvelemaan.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Kulttuurienvälinen vaihto ja globaali panos`,
    content: {
      7: `Jokainen oppija omalla kielellään.`,
      33: `Jokainen toiminto osallistujan omalla kielellä — avoin kenelle tahansa kansalaiselle, ilman hallituksen lupaa. Keinotekoinen, Inhimillinen ja Jaettu äly pidetään tuottavassa jännitteessä. Opetusohjelmat julkaistaan avoimesti. Sen, minkä yksi alue oppii, kaikki perivät.`,
      111: `Atlantis-sopimus palauttaa koulutuksen syvimpään tarkoitukseensa: viisauden vaihtoon rajojen yli, jotka muuten jakaisivat. Kuka tahansa kansalainen voi astua tähän opetusohjelmaan riippumatta siitä, mitä hänen hallituksensa on allekirjoittanut. Jokainen toiminto on saatavilla osallistujan omalla kielellä, isäntäalueen kielellä ja jaetussa tallenteessa. Kieli ei ole koristelua — kieli on lainkäyttöä, kieli on arvokkuutta luettavaksi tehtynä. Koulutuksen viitekehys nojaa älyjen kolminaisuuteen: Keinotekoinen ehdottaa, Inhimillinen päättää, Jaettu Aikomus vahvistaa. Jokainen opiskelija oppii pitämään kaikki kolme jännitteessä. Sen, minkä sopimus oppii, se antaa takaisin. Opetusohjelmat, innovaatiotulokset, hyvinvointitutkimus ja hallinnolliset päätökset julkaistaan avoimesti. Sen, minkä yksi alue oppii, kaikki kansalaiset perivät.`,
      333: `Atlantis-sopimus palauttaa koulutuksen syvimpään tarkoitukseensa: viisauden vaihtoon rajojen yli, jotka muuten jakaisivat. Tämä on maailman kansalaisten välinen sopimus — kuka tahansa kansalainen voi rakentaa sitä ja pitää siitä kiinni, riippumatta siitä, mitä hänen hallituksensa on allekirjoittanut. Jokainen toiminto on saatavilla osallistujan omalla kielellä, isäntäalueen kielellä ja jaetussa tallenteessa, jotta yksikään osallistuja ei kulje sopimuksen läpi kielellä, jota hän ei valinnut. Kieli ei ole koristelua. Kieli on lainkäyttöä. Kieli on arvokkuutta luettavaksi tehtynä. Nuori Kambodžassa lukee apurahatallenteensa khmeriksi, Hondurasissa espanjaksi, Austinissa englanniksi — kaikkia kolmea kunnioitetaan yhtäläisesti, eikä yksikään tarvitse hallituksen siunausta aloittaakseen.

Koulutuksen viitekehys nojaa älyjen kolminaisuuteen, jonka Vision • 2525 tekee näkyväksi. Tekoäly ehdottaa kuvioita ja mahdollisuuksia nopeammin kuin mikään yksittäinen ihminen voisi. Inhimillinen äly päättää turvallisuudesta, etiikasta ja suunnasta — kysymyksistä, joihin minkään koneen ei tulisi vastata, pidettyinä Human Authorityn alla. Jaettu Aikomus vahvistaa, että päätökset palvelevat sopimuksen periaatteita, jotta yksikään osallistuja ei valitse erinomaisuutta yhteisen hyvän kustannuksella. Yksikään opiskelija ei alistu vain yhdelle älylle; jokainen opiskelija oppii pitämään kaikki kolme jännitteessä. Kuuluminen alkaa Seedillä, jäsenyydellä, jonka hinta on seitsemäsosa paikallisen minimipalkan tunnista — riittävän pieni, että kuka tahansa kansalainen voi sen varaa. Tämä valmistaa seuraavaa sukupolvea hallitsemaan, siellä missä yksikään äly ei toimi tarkistamattomana.

Sen, minkä sopimus oppii, se antaa takaisin. Opetusohjelmat julkaistaan avoimella lisenssillä, jotta mikä tahansa alue — allekirjoittaja tai ei — voi mukauttaa niitä paikalliseen kulttuuriin. Innovaatiotulokset julkaistaan. Hyvinvointitutkimus julkaistaan koostettuna tutkijoille kaikkialla. Hallinnolliset päätökset julkaistaan perusteluineen, jotta kuka tahansa kansalainen, ei vain allekirjoittava hallitus, voi vahvistaa ne — ja Replay antaa saman kansalaisen jäljittää perustelut vuosisata tästä eteenpäin. Menestystä mitataan ei vain sen osallistujien, vaan myös niiden koulutus- ja kulttuurialoitteiden mukaan, jotka syntyvät sen jäljissä, alueilla, jotka eivät koskaan allekirjoittaneet pilottia mutta rakensivat sen jaetulle viisaudelle. Sen, minkä yksi alue oppii, jokainen kansalainen perii.`,
      999: `Atlantis-sopimus palauttaa koulutuksen syvimpään tarkoitukseensa: viisauden vaihtoon rajojen yli, jotka muuten jakaisivat, ja se aloittaa tämän vaihdon ennen kuin yhtään oppituntia opetetaan. Jokaisen osallistujan ensimmäinen teko viitekehyksen sisällä on Seed — kertaluonteinen jäsenyys, jonka hinta on seitsemäsosa paikallisen minimipalkan tunnista, ei-siirrettävissä, eikä se kanna minkäänlaista taloudellista vaadetta. Se on riittävän pieni, ettei yksikään perhe jää ulkopuolelle, ja riittävän todellinen, ettei yksikään osallistuja astu sisään katsojana. Tämä on sopimuksen ensimmäinen oppitunti: kuuluminen ansaitaan halvalla, mutta se silti ansaitaan, eikä se anna omistajuutta siihen, mitä tulee jälkeen. Jokainen sitä seuraava sopimuksen toiminto on saatavilla osallistujan omalla kielellä, isäntäalueen kielellä ja jaetussa tallenteessa, jotta yksikään osallistuja ei kulje sopimuksen läpi kielellä, jota hän ei valinnut. Kieli ei ole koristelua. Kieli on lainkäyttöä. Kieli on arvokkuutta luettavaksi tehtynä. Kun nuori kambodžalaisesta kylästä lukee apurahatallenteensa khmeriksi, hondurasilainen kaupunki espanjaksi ja austinilainen kaupunginosa englanniksi, kaikkia kolmea kunnioittaa yhtäläisesti sama sopimus, samoilla perustaja-alueilla, jotka ensimmäisenä sopivat opettavansa toisiaan.

Sopimuksen koulutuksen viitekehys nojaa älyjen kolminaisuuteen, jonka Vision • 2525 tekee näkyväksi, ja opetusohjelma opettaa kutakin niistä jonain, minkä osallistuja voi tuntea omissa käsissään, ei abstraktiona. ♡, Jaettu Aikomus, kantaa syyn — punaisen langan, jonka jokainen opiskelija oppii pitämään kiinni ennen kuin koskettaa mitään työkalua, kysymyksen siitä, palveleeko tämä työ yhä niitä ihmisiä, joita se väittää palvelevansa. ◬, todistettu kiihtyvyys, opetetaan deltana eikä mitään muuta — mitattuna vain jäädytettyä lähtötasoa vasten, ei koskaan puettuna voittomittariksi, ei koskaan väitettynä henkilökohtaiseksi saavutukseksi erillään ympärillä olevasta tiimistä. 웃, ajassa kunnioitettu Inhimillinen Äly, opetetaan huolellisimmin: yksi todistettu työtunti vastaa yhtä tuntia paikallista minimipalkkaa, ja se, minkä osallistuja ansaitsee, on tämä palkka kerrottuna tehdyillä tunneilla — Kerroin kertaa Aika, ei mitään piilotettuna laskutoimituksessa. Opiskelijat oppivat varhain, että 웃 myönnetään vain todistetusta työstä, joka tehdään rajatun, budjetoidun ja hyväksytyn tehtävän alaisuudessa. Ennen tämän hyväksynnän olemassaoloa sama ponnistus on vain suunnittelua — arvokasta, mutta palkatonta, ja jokaiselle osallistujalle opetetaan tunnistamaan ero heti.

Koska tämä ero hämärtyy helposti, opetusohjelma opettaa QIS:n, Hyväksytyn Innovaatiopisteytyksen, peilinä pikemminkin kuin tulostauluna. QIS on neljän taloudellisen absoluutin — Liikevaihdon, Bruttovoiton, Liiketoiminnan tuloksen ja Tehokkaan T&K:n — keskiarvo jaettuna neljällä, ja jokainen opiskelija oppii laskemaan sen, kyseenalaistamaan sen eikä koskaan sekoittamaan sitä rahaan. QIS:n kasvu mitoittaa palkintopoolin vasta sen jälkeen, kun kelpoisuus on riippumattomasti vahvistettu, eikä tämä kasvu lyö yhtään omaa 웃:aan. QIS on mittaus. QIS ei ole koskaan maksu. QIS ei ole koskaan omistajuutta. Opiskelija, joka on sisäistänyt tämän eron, ei voi vakuuttua siitä, että korkea pisteytys oikeuttaisi häntä vaateeseen, jota sopimus ei koskaan luvannut.

Opetusohjelma laajentaa tätä lukutaitoa siihen, miten arvo todella saavuttaa henkilön, sen kautta, mitä sopimus kutsuu Livelihood Directiksi — 🏠-periaatteeksi, jonka mukaan raha liikkuu hyväksyttyjen, lisensoitujen paikallisten kanavien kautta eikä koskaan rahaston kautta, jota viitekehys itse säilyttää. Opiskelijoita opetetaan jäljittämään apurahansa, ja myöhemmin omat ansionsa, näiden kanavien läpi kansalaistoimintana, ei jonkin muualla heidän puolestaan suoritettuna taloudellisena mysteerinä. He oppivat, että luokittelu edeltää aina selvitystä, ja että tunnustus — korkea QIS, julkinen kiitos — ei sinänsä avaa sänkyä, apurahaa tai paikkaa kierrossa. Sen tekee rooli. Tämä on suoja hyvin vanhaa virhettä vastaan: kiitosta, joka sekoitetaan huolenpitoon.

Taloudellisen lukutaidon rinnalla on kansalaislukutaito, jota opetetaan Continuity Without Evasion -periaatteen kautta. Jokainen osallistuja oppii, että sopimus on rakennettu laillista siirrettävyyttä varten — ettei yksikään korvaamaton hallitus, pankki, perustaja tai malli seiso hänen ja viitekehyksen lupausten välissä. He oppivat, mitä kielteinen päätös tekee tämän suunnittelun sisällä: se sulkee yhden kanavan yhdellä lainkäyttöalueella, tuon sovittimen oletusarvoisesti kielletyn asennon mukaisesti, eikä koskaan kaada koko kokonaisuutta. Tämän rinnalla on syvin oppitunti, jonka sopimus opettaa: Human Authority pitää merkityksen, rahan ja lain, ja suvereeni taso, jolla nämä päätökset tehdään, pysyy pysyvästi suljettuna koneilta. Measurement of Time, MoT, tallentaa jokaisen osallistujan todelliset minuutit erillään mistä tahansa pisteytyksestä, ja Replay tekee jokaisesta sopimuksen antamasta julkaisusta täysin rekonstruoitavissa olevan — jotta opiskelija, joka vuosia myöhemmin haluaa tietää, miksi päätös tehtiin, voi jäljittää sen itse sen sijaan, että luottaisi kenenkään sanaan.

Tästä ansaitun luottamuksen rakenteesta tulee sopimuksen pedagoginen malli, ei vain sen hallintomalli. Jokainen osallistuja etenee Manuaalisen, Puoliautomatisoidun ja Autonomisen tilan läpi, joissa liikkumavara kasvaa, porrastettuna samalla mitatun parannuksen kynnyksellä, joka porrastaa itse teknologiaa — yhdentoista ja yhdeksäsosaprosentin vahvistettu edistys ennen kuin seuraava tila avautuu. Autonomia, kun se ansaitaan, ansaitaan kapeasti ja alueittain, ei koskaan merkityksen, rahan tai lain yli. Opiskelija, joka on elänyt tämän etenemisen, ymmärtää konkreettisesti, miksi suvereenia tasoa ei koskaan saa automatisoida pois — koska hän ansaitsi oman autonomiansa yksi mitattu askel kerrallaan ja tietää tarkalleen, mitä tämä autonomia sisälsi ja mitä ei.

Sen, minkä sopimus oppii, sopimus antaa takaisin. Opetusohjelmat julkaistaan avoimella lisenssillä, jotta mikä tahansa alue — allekirjoittaja tai ei — voi mukauttaa niitä paikalliseen kulttuuriin ja pedagogiseen perinteeseen. Innovaatiotulokset julkaistaan. Hyvinvointitutkimus julkaistaan koostettuna tutkijoille kaikkialla. Hallinnolliset päätökset julkaistaan täysin perusteluineen. Sopimuksen menestystä mitataan ei vain sen omien osallistujien mukaan Kambodžassa, Hondurasissa ja Austinissa, vaan myös niiden aloitteiden mukaan, jotka syntyvät sen jäljissä, alueilla, jotka eivät koskaan allekirjoittaneet perustavaa pilottia mutta rakensivat sen avoimesti jaetulle viisaudelle, aikahorisontin yli, jonka valmistumista perustajat eivät elä nähdäkseen. Sen, minkä yksi alue oppii, jokainen muu alue perii — ja sitä, mitä tälle sukupolvelle opetetaan rehellisesti, seuraavan viidensadan vuoden ei tarvitse opetella pois.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Verkoston kestävä kasvu`,
    content: {
      7: `Ei koskaan nopeammin kuin arvokkuus ehtii.`,
      33: `Kolme perustaja-aluetta viimeistelee yhden pilottikierron ennen kuin neljäs liittyy — kuka tahansa kansalainen voi rakentaa sitä. Tallenteet ankkuroitu kestämään viisi vuosisataa. Allekirjoittajat säilyttävät suvereniteettinsa; mitään ei heikennetä seuraavaa liittymistä varten.`,
      111: `Atlantis-sopimus ei kasva nopeammin kuin se laatu, jota se voi kunnioittaa. Kolmen perustaja-alueen täytyy viimeistellä täysi pilottikierto, jokainen osallistuja kunnioitettuna ja jokainen periaate vahvistettuna, ennen kuin neljäs alue liittyy. Tämä on periaate, joka on lopulta muuttunut toimivaksi kurinalaisuudeksi. Mutta sopimus on maailman kansalaisten välinen sopimus — kuka tahansa, missä tahansa, voi rakentaa sitä ja pitää siitä kiinni, yhden Seedin päässä, riippumatta siitä, mitä hallitus allekirjoittaa tai mitä työnantaja sallii. Sopimuksen aikahorisontti on viisi vuosisataa. Sen tallenteet on ankkuroitu Replayn kautta, jotta niitä vuosisata tästä eteenpäin lukeva kansalainen voi luottaa perusteluihin. Jokainen allekirjoittaja säilyttää suvereniteettinsa; mitään ei heikennetä seuraavaa liittymistä varten.`,
      333: `Atlantis-sopimus ei kasva nopeammin kuin se laatu, jota se voi kunnioittaa. Jokainen laajentuminen on lupaus jo mukana oleville osallistujille — että perustavaa standardia ei laimenneta mittakaavan kasvaessa. Kolmen perustaja-alueen täytyy viimeistellä täysi pilottikierto, jokainen osallistuja kunnioitettuna ja jokainen periaate vahvistettuna, ennen kuin neljäs alue liittyy. Tämä on periaate, joka on lopulta muuttunut toimivaksi kurinalaisuudeksi. Eikä ovi ollut koskaan vain alueellinen: tämä on maailman kansalaisten välinen sopimus, ja kuka tahansa voi rakentaa sitä, rahoittaa sitä ja pitää sitä tilivelvollisena — ilman hallituksen lupaa, ilman työnantajan siunausta. Johtajat, jotka allekirjoittavat pilotin, lupaavat allekirjoittajille saman perustan, suojan ja arvokkuuden, jonka perustajakohortti sai. Mitään ei heikennetä seuraavaa varten.

Sopimuksen aikahorisontti on tarkoituksellisen pitkä — suunniteltu kestämään viisitoista–kaksikymmentä ihmissukupolvea, viisi vuosisataa perustamispäivästä. Sen tallenteet on ankkuroitu Replayn kautta, jotta niitä vuosisata tästä eteenpäin lukeva kansalainen voi vahvistaa perustelut, ei vain luottaa niihin. Sen koordinaattikehys, sen Human Authorityn roolit ja sen sukupolvien väliset hallintosyklit on rakennettu selviytymään mistä tahansa yksittäisen teknologian murroksesta. Sopimus elää pidempään kuin jokainen ihminen, joka allekirjoittaa sen perustavan pilotin, ja jokainen kansalainen, joka istuttaa Seedin ja rahoittaa sitä kuukausittain. Se on sen lupaus lapselle, joka allekirjoittaa apurahasopimuksen, kansalaiselle, joka liittyi ilman minkään hallituksen lupaa, tuon lapsen lapsenlapsille, jotka saattavat hallita sopimusta vuosisadan puolivälissä, ja jokaiselle sukupolvelle, joka perii sen, minkä perustajat — viralliset ja kansalaiset yhtä lailla — rakentavat nyt.

Jokainen allekirjoittaja säilyttää vapauden vetäytyä, täyden suvereniteetin ja vallan omiin kansalaisiinsa, oikeudella muuttaa ja muovata sopimuksen kehitystä. Jokainen kansalainen säilyttää saman aseman perustaa, rahoittaa, todistaa ja pitää sitä tilivelvollisena — hallituksen allekirjoituksella tai ilman. Se, mitä kukaan ei voi tehdä, on vaarantaa perustavia periaatteita, koska tuon lupauksen täytyy selvitä mistä tahansa lähdöstä. Johtajat ja kansalaiset yhtä lailla allekirjoittavat sopimuksen seuraavan vuosisadan aikahorisonttiin, jonka heidän lapsenlapsensa perivät ja viimeistelevät.`,
      999: `Atlantis-sopimus ei kasva nopeammin kuin se laatu, jota se voi kunnioittaa, eikä tämä pidättyvyys ole tunnetta — se on insinöörityötä, kirjoitettuna samaan mittauskurinalaisuuteen, joka hallitsee jokaista sopimuksen antamaa lupausta. Kolmen perustaja-alueen, Kambodžan, Hondurasin ja Austinin, täytyy viimeistellä täysi pilottikierto, jokainen osallistuja kunnioitettuna ja jokainen periaate vahvistettuna, ennen kuin neljäs alue liittyy. Kasvu, joka ylittää vahvistuksen, ei ole kasvua; se on riskiä kunnianhimon puvussa. Perustava pilotti on olemassa, jotta sopimus voi todistaa, mittakaavassa, joka on riittävän pieni tarkastettavaksi ja riittävän suuri merkitäkseen, että sen lupaukset selviävät kosketuksesta todellisuuteen ennen kuin näitä lupauksia ulotetaan maailmaan, joka katselee sen kolmen rajan ulkopuolelta. Neljättä aluetta ei ole vielä nimetty, eikä sitä nimetä ennen kuin ensimmäiset kolme seisovat jokaisen tämän asiakirjan väitteen takana.

Se, mikä todistaa valmiuden kasvaa, ei ole innostus vaan luku, jota sopimus voi puolustaa julkisesti. Hyväksytty Innovaatiopisteytys — QIS, laskettuna Liikevaihtona plus Bruttovoittona plus Liiketoiminnan tuloksena plus Tehokkaana T&K-kulutuksena, jaettuna neljällä — on väline, jota sopimus käyttää tietääkseen, onko alue, kohortti tai kuutio parantunut, sen sijaan että se vain tuntuisi parantuneen. QIS:n kasvu mitoittaa palkintopoolin vasta kelpoisuuden täyttymisen jälkeen, ei koskaan ennen sitä, eikä QIS itsessään lyö yhtään 웃:aa eikä osta omistajuutta. QIS on mittaus, ei maksu; mittaus, ei osuus; peili, jonka sopimus nostaa omaa työtään vasten, ei koskaan valuutta, jota se käyttää. Alueen, joka ehdottaa verkoston laajentamista, täytyy näyttää QIS:nsa rehellisesti, sitä edeltäneiden alueiden silmien edessä, tai se ei laajene.

Kestävä kasvu tarkoittaa kasvua, joka ansaitsee oman valtansa yksi lisäys kerrallaan. Jokainen kuutio ja jokainen alue alkaa Manuaalisessa tilassa, jossa ihmiset päättävät kaikesta ja järjestelmä avustaa. Eteneminen Puoliautomatisoituun ja lopulta Autonomiseen toimintaan tietyn kuution sisällä on porrastettu yhdellä kynnyksellä läpi koko sopimuksen — yhdentoista ja yhdeksäsosaprosentin mitatulla parannuksella, yhdellä yhdeksäsosalla, todistettuna ja toistettavissa olevana ennen kuin seuraava autonomian aste myönnetään. Autonomia ansaitaan kuutio kuutiolta, ei koskaan väitetä kokonaisuutena eikä ulotetaan alueille, joiden täytyy pysyä inhimillisinä riippumatta siitä, kuinka kehittyneeksi järjestelmä muuttuu: merkitys, raha ja laki pysyvät suljettuina koneilta riippumatta siitä, kuinka moni kynnys ylitetään muualla. Verkosto, joka laajentaa automaatiotaan nopeammin kuin se laajentaa todisteitaan, ei modernisoidu. Se uhkapelaa luottamuksella, jota se ei ole vielä ansainnut.

Korvaus skaalautuu verkoston mukana samalla tavalla kuin valta — tarkoituksellisesti, ja katolla, joka suojaa koko järjestelmää sen omalta menestykseltä. 웃, Inhimillisen Älyn token, vastaa yhtä todistettua työtuntia kerrottuna paikallisella minimipalkalla; se, minkä osallistuja ansaitsee, on tämä Kerroin kertaa tehdyt tunnit, ja se myönnetään vain työstä, joka tehdään rajatun, budjetoidun ja hyväksytyn tehtävän alaisuudessa. Ennen hyväksyntää hienoinkin suunnitelma on vain suunnittelua, eikä pelkkä suunnittelu lyö mitään. Jokaisen osallistujan selvitys on rajattu 9 999 웃:aan vuodessa, ja mahdollinen ylijäämä siirtyy eteenpäin sen sijaan, että se katoaisi tai vääristäisi poolia. Kun uusia alueita liittyy ja verkoston toiminta moninkertaistuu, tämä katto on se, mikä estää kasvua muuttumasta inflaatioksi — arvo pysyy sidottuna todellisiin, todistettuihin, paikallisiin tunteihin riippumatta siitä, kuinka suureksi sopimus kasvaa.

Jokaisen 웃:n takana on syy, jota mikään tilikirja ei voi laskea itsestään. ♡, Jaettu Aikomus, kantaa tätä syytä eteenpäin jokaisen laajentumispäätöksen läpi, jonka sopimus tekee, kun taas ◬, Tekoälyn panos, lasketaan todistettuna kiihtyvyytenä, mitattuna jäädytettyä lähtötasoa vasten — deltana, eikä koskaan, missään olosuhteissa, voittomittarina, jota optimoidaan sen itsensä vuoksi. Astuminen tähän verkostoon alkaa samalla tavalla jokaiselle osallistujalle riippumatta siitä, mille alueelle tai millä vuosikymmenellä hän liittyy: Seedillä, kertaluonteisella jäsenyydellä, jonka hinta on seitsemäsosa paikallisen minimipalkan tunnista, ei-siirrettävissä eikä kantaen minkäänlaista taloudellista vaadetta. Seed kertoo vain, että henkilö on saapunut. Kaiken, minkä hän rakentaa sen jälkeen, hän rakentaa sopimuksen kolmen muun valuutan täydessä näkyvyydessä, ei koskaan itse Seedin kautta.

Kasvun, joka on todellista, täytyy olla myös kasvua, joka saavuttaa todellisen henkilön, ei rahastoa, jota viitekehys pitää jonkun puolesta. 🏠 Livelihood Direct edellyttää, että arvo kulkee osallistujalle vain hyväksyttyjen, lisensoitujen paikallisten kanavien kautta, jotka sopimus on tarkastanut alue alueelta, eikä koskaan säilytyksen kautta, jonka viitekehys itse pitää. Luokittelu edeltää aina selvitystä, jotta mikään arvo ei liiku ennen kuin sekä sen tarkoitus että vastaanottaja on molemmat vahvistettu epäilemättä. Ja koska tunnustus ei ole sama asia kuin pääsy, sänky, paikka kierrossa, paikka pöydässä on porrastettu roolin ja valmiuden mukaan, ei koskaan osallistujan pisteytyksen tai aseman mukaan. Kun verkosto laajenee neljänteen alueeseen ja sen ulkopuolelle, jokaisen uuden alueen täytyy kelpuuttaa omat lisensoidut kanavansa ennen kuin Livelihood Direct voi saavuttaa sen ihmiset — luottamuksen laajentumista, ei vain alueen laajentumista.

Mikään tästä ei kestä ilman verkostoa, joka on rakennettu selviytymään omasta menestyksestään, minkä vuoksi Continuity Without Evasion hallitsee jokaista aluetta, jonka sopimus koskaan lisää. Laillinen siirrettävyys on pakollinen; yksikään hallitus, pankki, perustaja tai malli ei saa tulla korvaamattomaksi kokonaisuudelle. Jokainen lainkäyttöalue ajaa omaa sovitintaan, joka epäonnistuu suljettuna ja on oletusarvoisesti kielletty, jotta kielteinen päätös missä tahansa sulkee vain yhden kanavan, ei koskaan koko sopimusta. Human Authority pitää merkityksen, rahan ja lain jokaisessa mittakaavassa, jonka verkosto saavuttaa, sinetöitynä koneellista tunkeutumista vastaan suunnittelun, ei lupauksen, kautta. Measurement of Time tallentaa jokaisen todellisen minuutin erillään jokaisesta sitä koskevasta väitteestä, ja Replay varmistaa, että mikä tahansa julkaisu, millä tahansa alueella, missä tahansa kohdassa viiden vuosisadan aikana, voidaan rekonstruoida ja tutkia uudelleen kenen tahansa sitä kysyvän toimesta. Verkostoon, jota ei voida toistaa Replayn kautta, ei voida luottaa, riippumatta siitä, kuinka moni alue on siihen liittynyt tai kuinka vaikuttavalta sen kasvu näyttää ulkopuolelta. Näin Vision • 2525 kasvaa koskaan kasvamatta ohi sen luottamuksen, jonka pitämiseksi se rakennettiin — yksi vahvistettu alue, yksi rehellinen QIS, yksi todistettu tunti kerrallaan.`,
    },
  },
];
