import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_FI: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Missä innovaatio alkaa`,
    content: {
      7: `Johtajat aloittavat sen, mitä yksikään vuosisata ei aloittanut.`,
      33: `Kolme aluetta — Kambodža, Honduras, Austin — lupaavat isännöidä nuoria oppijoita, suojella heitä ja ojentaa heille tulevaisuuden työkalut. Hallinto, koulutus, innovaatio: kolme visionääristä allekirjoitusta alueelta. Yksi yhteinen alku.`,
      111: `Atlantiksen sopimus on lupaus, jonka antavat johtajat, jotka ovat valmiita aloittamaan jotain, mitä ei ole aiemmin ollut olemassa. Sen perustajaksi allekirjoittaneet Kambodžassa, Hondurasissa ja Austinissa, Texasissa valittiin yhden harvinaisen ominaisuuden vuoksi: valmiuden uskoa nuorille tulevaisuuden työkalut, kun on vielä aikaa opettaa heitä. Sopimuksen allekirjoittaminen sitoo alueen isännöimään oppijoita eri kulttuureista, tuomaan sen, mitä vain se voi ainutlaatuisesti tarjota, ja pitämään itsensä korkeammassa mitassa kuin nykyinen sääntely edellyttää. Kolme visionääristä allekirjoitusta — hallinto, koulutus, innovaatio — astuvat sopimukseen yhdessä. Kolme visionääriä, kolme aluetta, yksi yhteinen alku.`,
      333: `Jokainen sivilisaatio muistetaan siitä, mitä se valitsi aloittaa. Atlantiksen sopimus on lupaus, jonka antavat johtajat, jotka ovat valmiita aloittamaan jotain, mitä ei ole aiemmin ollut olemassa — yhteinen perusta tavalliselle inhimilliselle innovaatiolle, joka ulottuu maailman jokaiseen kolkkaan, kunnioittaa jokaista ääntä ja kestää sukupolvien yli. Sen perustajaksi allekirjoittaneita Kambodžassa, Hondurasissa ja Austinissa, Texasissa ei valittu taloudellisen vallan, sotilaallisen voiman tai institutionaalisen arvovallan vuoksi. Heidät valittiin harvinaisemman ominaisuuden vuoksi: valmiuden uskoa nuorille tulevaisuuden työkalut. Tätä johtajuus tarkoittaa tulevalla vuosisadalla — rohkeutta ojentaa avaimet seuraavalle sukupolvelle, kun on vielä aikaa opettaa heitä ajamaan.\n\nSopimuksen kutsuu koolle eXeL, tähän hetkeen tarkoituksella rakennettu järjestävä voima. eXeL on olemassa tietoisesti perinteisten koordinointikanavien ulkopuolella, jotka muovasivat viime vuosisataa — diplomaattisten sopimusrakenteiden ulkopuolella, monenkeskisten byrokratioiden ulkopuolella, minkään yksittäisen kansallisvaltion poliittisten kytkösten ulkopuolella. eXeL on luotettu koollekutsuja, joka tuo visionääriset johtajat yhteen jaetun viitekehyksen, jaetun vauhtipyörän ja jaetun viidensadan vuoden horisontin ympärille. Jokainen allekirjoittaja säilyttää täyden suvereniteetin, täyden vallan omiin kansalaisiinsa ja täyden vapauden vetäytyä milloin tahansa. Sen, mitä allekirjoittajat saavat, on verkostovaikutus, jonka vain tarkoitukseen rakennettu viitekehys voi tarjota. Tämä on koordinaatiota ilman mitään poliittisen ylivallan muotoa.\n\nSopimuksen allekirjoittaminen on lupauksen allekirjoittamista. Että alue isännöi nuoria oppijoita eri kulttuureista. Että alue tuo sen, mitä vain se voi ainutlaatuisesti tarjota. Että alue pitää itsensä korkeammassa mitassa kuin nykyinen sääntely edellyttää. Että alue tekee näin julkisesti, läpinäkyvästi, jokaisen palvelemansa kansalaisen nähden. Jokaiselta alueelta vaaditaan kolme allekirjoitusta — hallinto, koulutus ja innovaatio. Yksikään virasto ei sido sopimusta yksin. Tarvitaan kolme visionääriä sanomaan kyllä. Kolme visionääriä, kolme aluetta, yksi alku — näin mikä tahansa viitekehys astuu elämään sen allekirjoittamiseen valmiiden johtajien keskinäisen luottamuksen kautta.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Oppiminen simulaation kautta`,
    content: {
      7: `Harjoittele tuhat kertaa ennen koskettamista.`,
      33: `Mitään merkittävää ei opita ensin oikealla laitteistolla. Jokainen osallistuja harjoittelee simulaatiossa, kiertää kolmen alueen välillä ja juhlii julkisesti. Tämä on kunnioitusta nuorta ihmistä kohtaan, jonka ensimmäinen virhe ei koskaan saisi maksaa ihmishenkeä.`,
      111: `Jokainen hallitsemisen arvoinen taito opittiin jonkun toimesta ennen kuin se tunnettiin. Atlantiksen sopimus palauttaa tämän muinaisen viisauden keskiöön siitä, kuinka nuoret valmistellaan rakentamaan tulevaisuutta. Mitään merkittävää ei opita ensin oikealla laitteistolla, oikeilla ihmisillä tai peruuttamattomissa olosuhteissa. Jokainen osallistuja harjoittelee simulaatiossa, kunnes harjoittelusta tulee osaamista ja osaamisesta valmiutta. Kiertomalli vie jokaisen osallistujan kolmen perustaja-alueen läpi, ja jokainen kierros päättyy julkiseen ja yhteistoiminnalliseen juhlaan, joka on avoin laajemmalle isäntäyhteisölle. Tämä on kunnioitusta nuorta ihmistä kohtaan, jonka ensimmäinen virhe ei koskaan saisi maksaa ihmishenkeä.`,
      333: `Jokainen hallitsemisen arvoinen taito opittiin jonkun toimesta ennen kuin se tunnettiin. Mestarikäsityöläiset harjoittelevat ennen esitystä, lentäjät harjoittelevat ennen lentoa, lääkärit harjoittelevat ennen leikkausta, ja lapset harjoittelevat maailmaa leikin kautta. Atlantiksen sopimus palauttaa tämän muinaisen viisauden keskiöön siitä, kuinka nuoret valmistellaan rakentamaan tulevaisuutta. Mitään merkittävää ei opita ensin oikealla laitteistolla, oikeilla ihmisillä tai peruuttamattomissa olosuhteissa. Jokainen osallistuja harjoittelee simulaatiossa, kunnes harjoittelusta tulee osaamista ja osaamisesta valmiutta. Tämä ei ole varovaisuutta — tämä on kunnioitusta nuorta ihmistä kohtaan, jonka ensimmäinen virhe ei koskaan saisi maksaa kenenkään henkeä.\n\nSopimuksen kiertomalli vie jokaisen osallistujan kolmen perustaja-alueen läpi. Se, mitä Kambodžassa opitaan, hiotaan Hondurasissa ja saatetaan päätökseen Austinissa. Se, mitä Austinissa löydetään, kyseenalaistetaan Kambodžassa ja integroidaan Hondurasissa. Jokainen osallistuja elää, oppii ja saa mentorointia kulttuureissa, jotka muutoin pysyisivät etäisinä. Opetussuunnitelma ammentaa monien kulttuurien kurinalaisen simulaation perinteistä — Sun Tzun strategisen kasvatuksen perinteestä, Musashin leikin kautta harjoittelun tavasta, Ibn Khaldunin syklisestä oppimisteoriasta, Nalandan luostaridialektiikasta, siviili-ilmailun lentosimulaattorista — koottuina kunnioittamaan jokaista kognitiivista vaihetta ja kulttuuriperintöä. Yksikään perinne ei hallitse.\n\nJokainen kierros päättyy julkiseen ja yhteistoiminnalliseen juhlaan, joka on avoin laajemmalle isäntäyhteisölle. Naapurit, perheet ja uteliaat vierailijat kokoontuvat näkemään, mitä ryhmä on oppinut. Nämä tapahtumat tekevät kehittyneestä teknologiasta lähestyttävää ja juhlittua pelottavan sijaan. Yhteiskuntaa, joka kasvaa ymmärtäen yhteistoiminnallisia järjestelmiä leikin kautta, ei voi helposti manipuloida pelolla noita järjestelmiä kohtaan. Tämä on pelotetta koulutuksen kautta, ei pelotetta voiman kautta. Sopimuksen lupaus jokaiselle vanhemmalle: lapsesi harjoittelee tuhat kertaa turvassa ennen kuin koskee mihinkään, mikä voisi vahingoittaa häntä, ja yhteisö todistaa hänen kasvuaan joka askeleella. Tältä näyttää nuoren ihmisen kunnioitus, kun se on suunniteltu viitekehykseen, ja tämän johtajuus ojentaa seuraavalle osallistujien sukupolvelle ennen kuin tuon sukupolven täytyy sitä vaatia.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Turvallisuus varmennettu ennen luottamuksen ojentamista`,
    content: {
      7: `Turvallisuus ensin todistettu, sitten luottamus ojennettu.`,
      33: `Jokainen laitos ja jokainen kierros sijaitsevat suojaavan vaipan sisällä varhaisvaroituksin. Laitteisto kieltäytyy aseellistamisesta. Tiedot selviävät myrskyistä. Turvallisuus suunnitellaan nuorimman osallistujan ympärille joka päivä, ei vain luvata tai oleteta.`,
      111: `Ennen kuin luottamus ojennetaan, turvallisuus on todistettava. Atlantiksen sopimus tekee tästä perustavan sitoumuksensa. Jokainen sopimuksen laitos, jokainen kierrosreitti, jokainen paikka, jossa nuori osallistuja nukkuu tai opiskelee, sijaitsee dokumentoidun suojaavan vaipan sisällä, jonka varhaisvaroituskyky antaa yhteisölle tunteja, ei minuutteja, aikaa vastata mihin tahansa uskottavaan riskiin. Jokainen laite, jokainen anturi, jokainen koordinointijärjestelmä on sidottu laitteistotasolla kieltäytymään uudelleenkäytöstä asejärjestelmien integrointiin. Tämä ei ole politiikkaa — tämä on fysiikkaa. Sopimus on suunniteltu pysymään kunniallisena myrskyjen läpi: poliittinen epävakaus, rahoituksen supistuminen, kyberhyökkäys tai matkustushäiriö. Jokainen skenaario on suunniteltu, ja jokainen suunnitelma asettaa ihmisarvon ensimmäiseksi suunnittelurajoitteekseen.`,
      333: `Ennen kuin luottamus ojennetaan, turvallisuus on todistettava. Atlantiksen sopimus tekee tästä perustavan sitoumuksensa. Jokainen sopimuksen laitos, jokainen kierrosreitti, jokainen paikka, jossa nuori osallistuja nukkuu tai opiskelee, sijaitsee dokumentoidun suojaavan vaipan sisällä, jonka varhaisvaroituskyky antaa yhteisölle tunteja, ei minuutteja, aikaa vastata mihin tahansa uskottavaan riskiin. Teknologia, jota käytetään osallistujien suojaamiseen, on samaa teknologiaa, jota sopimus opettaa heitä rakentamaan — anturit, koordinointi, viestinnän selviytymiskyky, hajautettu älykkyys. Nuoret oppivat turvallisuuden sisältä ulospäin, omalla kielellään ja omalla alueellaan, ei siten, että heille kerrotaan heidän olevan turvassa, vaan näkemällä, kuinka turvallisuus suunnitellaan heidän ympärilleen joka päivä.\n\nSopimus antaa rikkomattoman lupauksen siitä, miksi sen teknologia ei voi muuttua. Jokainen laite, jokainen anturi, jokainen koordinointijärjestelmä on sidottu laitteistotasolla kieltäytymään uudelleenkäytöstä asejärjestelmien integrointiin. Tämä ei ole politiikan kieltä. Tämä ei ole tavoite. Tämä on fyysinen mahdottomuus, kryptografisesti valvottu, jokaisen allekirjoittaja-alueen varmentama ja jokaisen kansalaisen tarkastettavissa. Työkaluja, jotka suojaavat lasta Phnom Penhissä, ei voi käyttää uudelleen vahingoittamaan lasta Austinissa. Työkaluja, jotka yhdistävät parviharjoituksen Tegucigalpassa, ei voi konfiguroida uudelleen kohdistamaan iskua ihmiseen missään. Tämä on sopimuksen vastaus vuosisadan mittaiseen kaksikäyttöisyyden pelkoon. Ei politiikkaa — fysiikkaa.\n\nSopimus on suunniteltu pysymään kunniallisena myrskyjen läpi. Jos allekirjoittaja-alue menettää poliittisen vakauden, jäljellä olevat alueet ottavat osallistujat huostaansa. Jos rahoitus supistuu, osallistujien apurahat suojataan ensin, ennen hallintoa ja infrastruktuuria. Jos digitaalisiin tietoihin hyökätään, offline-varmuuskopiot säilyvät. Jos matkustaminen käy mahdottomaksi, substraatti jatkuu virtuaalisesti. Jokainen skenaario on suunniteltu, ja jokainen suunnitelma asettaa ihmisarvon ensimmäiseksi suunnittelurajoitteekseen. Johtajat, jotka allekirjoittavat tämän sopimuksen, allekirjoittavat lupauksen, että turvallisuus suunnitellaan, ei oleteta. Sen, mitä he ojentavat kansalaisilleen, ei ole pelkkä mahdollisuus, vaan suojelu, joka on rakennettu siihen mittaan, jonka nuorin osallistuja ansaitsee — sama suojelu, jota jokainen johtaja vaatisi omalle lapselleen, joka ylittää yksin vieraan rajan.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Korvaus, hyvinvointi ja ihmisarvo`,
    content: {
      7: `Apuraha, mentori, koti.`,
      33: `Jokainen osallistuja saa toimeentuloapurahan ensimmäisestä päivästä lähtien. Rakkautta, menetystä ja turvallisuutta kohdellaan ensiluokkaisena infrastruktuurina. Menestystä mitataan haavoittuvimman osallistujan mukaan, ei koskaan keskiarvon. Arvokkuus on substraatti, ei koskaan koriste.`,
      111: `Atlantiksen sopimus kohtelee jokaista osallistujaa täytenä ihmisenä ensimmäisestä päivästä lähtien. Apuraha annetaan siitä hetkestä, kun osallistuminen alkaa, indeksoituna alueen elinkustannuksiin, jotta sen vaikutus kunnioittaa työn paikallista arvoa. Hyvinvointia kohdellaan ensiluokkaisena infrastruktuurina — ei valinnaisena etuna, ei hyvinvointilisänä, vaan substraattina, jonka päällä kaikki muu seisoo. Kolmea perustavaa aluetta tuetaan: rakkautta, menetystä ja turvallisuutta. Sopimus mittaa menestystä haavoittuvimman osallistujansa tuloksen mukaan, ei keskiarvon. Yksikään osallistuja ei jää hiljaa unohdetuksi, jotta keskiarvot näyttäisivät hyviltä. Arvokkuus substraattina, ei koristeena.`,
      333: `Atlantiksen sopimus kohtelee jokaista osallistujaa täytenä ihmisenä ensimmäisestä päivästä lähtien. Apuraha annetaan siitä hetkestä, kun osallistuminen alkaa, indeksoituna alueen elinkustannuksiin, jotta sen vaikutus kunnioittaa työn paikallista arvoa. Apuraha saapuu ennen kuin perhevelvoitteista tulee hätätiloja ja ennen kuin arvokkuus vaarantuu. Se viestii jokaiselle nuorelle, että hänen aikansa on arvokasta, hänen panostaan odotetaan ja hänen perheensä vakaus on osa sopimuksen vastuuta. Tämä ei ole hyväntekeväisyyttä. Tämä on tunnustus siitä, että tavallinen inhimillinen innovaatio vaatii ensin tavallista inhimillistä turvaa. Mieli ei voi kukoistaa, kun sen koti on uhattuna.\n\nHyvinvointia kohdellaan ensiluokkaisena infrastruktuurina — ei valinnaisena etuna, ei hyvinvointilisänä, vaan substraattina, jonka päällä kaikki muu seisoo. Sopimus nimeää kolme perustavaa aluetta, joiden kautta jokaista osallistujaa tuetaan: rakkaus yhteyden, kiintymyksen ja terveiden rajojen merkityksessä; menetys, sillä jokainen osallistuja kokee surua ja häntä on saatettava, ei kierrettävä; ja turvallisuus siinä merkityksessä, että jokainen osallistuja tietää, kenelle soittaa, jokaisella alueella, omalla kielellään. Yksilöllistä ohjausta, ryhmäpiirejä, keholähtöisiä harjoituksia sekä osallistujan oman perinteen mukaan kunnioitettuja kulttuurisia tai hengellisiä käytäntöjä tarjotaan kaikkia. Nolla pakotettua ideologiaa. Sopimus pitää tilaa kunnioituksella; se ei käännytä mihinkään uskomusjärjestelmään.\n\nSopimus mittaa menestystä haavoittuvimman osallistujansa tuloksen mukaan, ei keskiarvon. Maaseudun osallistujia ilman suurta kaistanleveyttä palvellaan. Neuroepätyypilliset osallistujat saavat mukautukset normina. Vammaiset osallistujat löytävät jokaisen laitoksen esteettömäksi. Sukupuoleltaan moninaiset osallistujat saavat turvallisen asumisen ja mentoriparin. Muuta kuin äidinkieltään puhuvat löytävät jokaisen aineiston omalla kielellään. Alkuperäiskansojen osallistujat löytävät kulttuuriset käytäntönsä kunnioitettuina ja perinteisen tietonsa suojattuna. Johtajat, jotka allekirjoittavat tämän sopimuksen, lupaavat, ettei yksikään osallistuja jää hiljaa unohdetuksi, jotta keskiarvot näyttäisivät hyviltä. Tämä on arvokkuutta substraattina, ei koristeena. Se, mitä mitataan, on se, mitä kunnioitetaan, ja se, mitä täällä kunnioitetaan, on koko ihminen — mieli, keho ja henki yhdessä, ilman minkäänlaista poikkeusta.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Rahoitus ja hallinto`,
    content: {
      7: `Kansalaiset rahoittavat suoraan seuraavan sukupolven.`,
      33: `Tavalliset asukkaat lahjoittavat pieniä kuukausittaisia summia. Ei apukanavaa, ei ulkomaista hyväntekijää, ei poliittisia kytköksiä. Jokainen dollari on jäljitettävissä. Jokainen kirjanpito julkaistaan, jokaisen alueen kielellä, joka kuukausi, julkisesti.`,
      111: `Atlantiksen sopimusta rahoittavat ne kansalaiset, joita se palvelee. Tavalliset asukkaat lahjoittavat pieniä vapaaehtoisia summia joka kuukausi — riittävän vaatimattomia, ettei yhtäkään aikuista hinnoitella ulos, riittävän kaikuvia, että kokonaissumma ylläpitää sopimuksen työtä merkityksellisessä mittakaavassa. Kun kansalainen rahoittaa seuraavaa sukupolvea suoraan, tuo kansalainen pitää sopimuksen tilivelvollisena suoraan. Sopimus on tietoisesti riippumaton monenkeskisistä instituutioista, jotka muovasivat mennyttä vuosisataa. Tämä ei ole poliittinen kannanotto — se on suunnitteluvalinta. Jokainen dollari kirjataan pysyvästi ja jäljitettävästi. Jokaista kansalaisen lahjoitusta voidaan seurata alkuperästä apurahaan ja innovaatioon. Läpinäkyvyyttä, jollaista harva instituutio koskaan tarjoaa.`,
      333: `Atlantiksen sopimusta rahoittavat ne kansalaiset, joita se palvelee. Osallistuvien alueiden tavalliset asukkaat lahjoittavat pieniä vapaaehtoisia summia joka kuukausi — summia, jotka ovat riittävän vaatimattomia, ettei yhtäkään aikuista millään isäntäalueella hinnoitella ulos osallistumisesta, riittävän kaikuvia, että kokonaissumma ylläpitää sopimuksen työtä merkityksellisessä mittakaavassa. Tämä muotoilu on tarkoituksellinen. Kun kansalainen rahoittaa suoraan seuraavan sukupolven koulutusta, tuo kansalainen pitää sopimuksen tilivelvollisena suoraan. Ei ole apukanavaa, ei ulkomaista hyväntekijää, ei sekkiin kiinnitettyä poliittista kytköstä. Sopimuksen sielu on kansalainen, joka lahjoittaa yhden pienen summan joka kuukausi ja jonka osallistuminen tekee kokonaisuuden mahdolliseksi.\n\nSopimus on tietoisesti riippumaton monenkeskisistä instituutioista, jotka ovat muovanneet mennyttä vuosisataa — Pohjois-Atlantin liitosta, Maailman terveysjärjestöstä, Yhdistyneistä kansakunnista, Kansainvälisestä valuuttarahastosta, Maailmanpankista ja jokaisesta kansallisesta ulkomaanavun kanavasta. Tämä ei ole poliittinen kannanotto noiden instituutioiden arvosta tai niiden panoksista. Se on suunnitteluvalinta. Yhden pisteen riippuvuudet vaarantavat kestävyyden viidensadan vuoden horisontissa. Viitekehys, joka on tarkoitettu palvelemaan jokaista aluetta geopoliittisesta suuntautumisesta riippumatta, ei voi kietoutua mihinkään yhteen suuntautumiseen. Kansalliset hallitukset voivat lahjoittaa vapaaehtoisesti. Lahjoitukset ovat läpinäkyviä. Yksikään lahjoitus ei osta hallinnollista vaikutusvaltaa, mistään lähteestä, koskaan.\n\nJokainen dollari ja jokainen sopimukseen tuleva arvoyksikkö kirjataan pysyvästi, julkisesti ja jäljitettävästi. Jokaista kansalaisen lahjoitusta voidaan seurata sen alkuperästä apurahaan, joksi siitä tulee, siihen nuoreen, jota se palvelee, ja siihen innovaatiohankkeeseen, joka nousee tuon nuoren työstä. Hallinnollisille yleiskuluille on asetettu katto. Yritysten ja instituutioiden lahjat ovat tervetulleita ja niille on asetettu katto. Täysi kirjanpito toimitetaan jokaisen allekirjoittaja-alueen kielellä joka kuukausi. Johtajat, jotka allekirjoittavat sopimuksen, lupaavat kansalaisilleen läpinäkyvyyttä, jollaista harva instituutio koskaan tarjoaa — läpinäkyvyyttä, joka pysyy luettavana vuosisatoja sen jälkeen, kun jokainen allekirjoittaja on jättänyt virkansa. Tämä on luottamus, jota sopimus edellyttää. Tämä on luottamus, jonka sopimus ansaitsee, yksi pieni jäljitettävä lahjoitus kerrallaan, jokaisen kansalaisen nähden.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Kulttuurienvälinen vaihto ja globaali panos`,
    content: {
      7: `Jokainen oppija omalla kielellään.`,
      33: `Jokainen toiminta saatavilla osallistujan kielellä. Tekoäly, ihmisäly ja jaettu äly pidetään tuottavassa jännitteessä — yksikään opiskelija ei tukeudu vain yhteen. Opetussuunnitelmat ja tulokset julkaistaan avoimesti. Minkä yksi alue oppii, kaikki perivät.`,
      111: `Atlantiksen sopimus palauttaa koulutuksen syvimpään tarkoitukseensa: viisauden vaihtoon rajojen yli, jotka muutoin jakaisivat. Jokainen toiminta on saatavilla osallistujan omalla kielellä, isäntäalueen kielellä ja kanonisessa jaetussa tallenteessa. Kieli ei ole koriste — kieli on lainkäyttövalta, kieli on luettavaksi tehtyä arvokkuutta. Koulutusviitekehys nojaa älyjen kolminaisuuteen: tekoäly ehdottaa, ihminen päättää, jaettu tahto vahvistaa. Jokainen opiskelija oppii pitämään kaikki kolme tuottavassa jännitteessä. Minkä sopimus oppii, sopimus antaa takaisin. Opetussuunnitelmat, innovaatiotulokset, hyvinvointitutkimus ja hallintopäätökset julkaistaan kaikki avoimesti. Minkä yksi alue oppii, kaikki alueet perivät.`,
      333: `Atlantiksen sopimus palauttaa koulutuksen syvimpään tarkoitukseensa: viisauden vaihtoon rajojen yli, jotka muutoin jakaisivat. Jokainen sopimuksen toiminta on saatavilla osallistujan omalla kielellä, isäntäalueen virallisella kielellä ja kanonisessa jaetussa tallenteessa, jotta yksikään osallistuja ei kulje sopimuksen läpi kielellä, jota hän ei valinnut. Kieli ei ole koriste. Kieli on lainkäyttövalta. Kieli on luettavaksi tehtyä arvokkuutta. Kun nuori kambodžalaisesta kylästä lukee oman apurahatallenteensa khmeriksi, kun nuori honduraslaisesta kaupungista lukee sen espanjaksi, kun nuori austinilaisesta kaupunginosasta lukee sen englanniksi, kaikkia kolmea kunnioittaa tasapuolisesti sama sopimus.\n\nSopimuksen koulutusviitekehys nojaa älyjen kolminaisuuteen, jonka Vision 2525 tekee näkyväksi. Tekoäly ehdottaa kaavoja, vaihtoehtoja ja mahdollisuuksia nopeammin kuin yksikään ihminen yksin voisi. Ihmisäly päättää turvallisuudesta, etiikasta ja suunnasta — kysymyksistä, joihin yksikään kone ei saisi vastata. Jaettu tahto vahvistaa, että päätökset ovat sopimuksen perustavien periaatteiden mukaisia, varmistaen ettei yhtäkään osallistujaa pyydetä valitsemaan yksilöllisen erinomaisuuden ja yhteisen hyvän välillä. Yhtäkään opiskelijaa ei opeteta tukeutumaan vain yhteen älyyn. Jokainen opiskelija oppii pitämään kaikki kolme tuottavassa jännitteessä. Näin seuraava johtajien sukupolvi valmistellaan hallitsemaan vastuullisesti ja viisaasti maailmassa, jossa yksikään näistä kolmesta älystä ei koskaan toimi yksin tai valvomatta.\n\nMinkä sopimus oppii, sopimus antaa takaisin. Opetussuunnitelmat julkaistaan avoimella lisenssillä, jotta mikä tahansa alue — allekirjoittaja tai ei — voi mukauttaa niitä vapaasti paikalliseen kulttuuriin ja pedagogiseen perinteeseen. Innovaatiotulokset julkaistaan. Hyvinvointitutkimus julkaistaan koostetussa muodossa tutkijoille kaikkialla. Hallintopäätökset julkaistaan täydellisine perusteluineen. Sopimuksen menestystä ei mitata vain sen omilla osallistujilla, vaan niiden koulutuksellisten, innovatiivisten ja kulttuuristen aloitteiden määrällä, jotka nousevat sen jälkeen alueilla, jotka eivät koskaan allekirjoittaneet perustavaa pilottia mutta rakensivat sen avoimesti jaetun viisauden varaan. Minkä yksi alue oppii, kaikki muut alueet perivät.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Verkoston kestävä kasvu`,
    content: {
      7: `Ei koskaan nopeammin kuin arvokkuus ehtii.`,
      33: `Kolme perustaja-aluetta suorittaa yhden pilottikierroksen ennen kuin neljäs liittyy. Tiedot ankkuroitu kestämään viisi vuosisataa. Jokainen allekirjoittaja säilyttää suvereniteettinsa. Mitään ei alenneta tehdäkseen tilaa seuraavan allekirjoittajan liittymiselle.`,
      111: `Atlantiksen sopimus ei kasva nopeammin kuin laatu, jota se voi kunnioittaa. Kolmen perustaja-alueen on suoritettava täysi pilottikierros, jokainen osallistuja kunnioitettuna ja jokainen periaate varmennettuna, ennen kuin neljäs alue liittyy. Tämä on periaate, josta on vihdoin tullut toimiva kuri. Sopimuksen horisontti on tietoisesti pitkä — viisi vuosisataa perustamispäivästä. Sen tiedot on ankkuroitu niin, että sadan vuoden päästä niitä lukeva kansalainen voi luottaa päättelyyn. Jokainen allekirjoittaja säilyttää täyden suvereniteetin, täyden vallan ja täyden vapauden vetäytyä. Yksikään allekirjoittaja ei voi vaarantaa perustavia periaatteita — koska nuo periaatteet ovat sopimuksen lupaus osallistujilleen jokaisen sukupolven yli.`,
      333: `Atlantiksen sopimus ei kasva nopeammin kuin laatu, jota se voi kunnioittaa. Jokainen laajentuminen on lupaus jo sisällä oleville osallistujille — ettei sopimuksen perustavaa mittapuuta laimenneta mittakaavan innostuksella. Kolmen perustaja-alueen on suoritettava täysi pilottikierros, jokainen osallistuja kunnioitettuna ja jokainen periaate varmennettuna, ennen kuin neljäs alue liittyy. Tämä ei ole periaatteeksi naamioitua varovaisuutta. Tämä on periaate, josta on vihdoin tullut toimiva kuri jokaisella perustaja-alueella. Johtajat, jotka allekirjoittavat perustavan pilotin, lupaavat tuleville allekirjoittajille saman substraatin, saman suojelun, saman arvokkuuden, jonka perustajaryhmä sai. Mitään ei alenneta tehdäkseen tilaa seuraavalle.\n\nSopimuksen horisontti on tietoisesti pitkä. Se on suunniteltu kestämään noin viidestätoista kahteenkymmeneen ihmissukupolvea — viisi vuosisataa perustamispäivästä. Sen tiedot on ankkuroitu niin, että sadan vuoden päästä niitä lukeva kansalainen voi luottaa päättelyyn. Sen koordinaatisto, sen inhimillisen vallan roolit ja sen sukupolvien yli ulottuvat hallintosyklit on kaikki rakennettu selviytymään mistä tahansa yhden teknologian siirtymästä. Sopimus elää kauemmin kuin jokainen ihminen, joka allekirjoittaa sen perustavan pilotin. Se on sen lupaus lapselle, joka allekirjoittaa apurahasopimuksen ratifiointia seuraavana vuonna, tuon lapsen lapsenlapsille, jotka saattavat hallita sopimusta vuosisadan puolivälissä, ja jokaiselle sukupolvelle, joka perii sen, mitä perustajat nyt rakentavat.\n\nJokainen allekirjoittaja säilyttää vapauden vetäytyä ennakkoilmoituksella. Jokainen allekirjoittaja säilyttää täyden suvereniteetin. Jokainen allekirjoittaja säilyttää vallan omiin kansalaisiinsa. Jokainen allekirjoittaja säilyttää oikeuden ehdottaa muutoksia, nostaa erimielisyyksiä ja muovata sopimuksen kehitystä yhdessä jokaisen toisen allekirjoittajan kanssa. Se, mitä yksikään allekirjoittaja ei voi tehdä, on vaarantaa substraatin perustavia periaatteita — koska nuo periaatteet ovat sopimuksen lupaus osallistujilleen, ja tuon lupauksen on selviydyttävä minkä tahansa yksittäisen allekirjoituksen lähdöstä. Johtajat, jotka allekirjoittavat tämän sopimuksen nyt, liittyvät johonkin suurempaan kuin mihinkään yksittäiseen poliittiseen virkakauteen. He allekirjoittavat sopimuksen seuraavan vuosisadan, ja vuosisadat sen tuolla puolen, horisonttiin, jonka heidän omat lapsenlapsensa perivät ja saattavat päätökseen.`,
    },
  },
];
