import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_FR: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Là où commence l'innovation`,
    content: {
      7: `Les dirigeants commencent ce que nul siècle n'osa.`,
      33: `Trois régions — Cambodge, Honduras, Austin — ouvrent une promesse que les citoyens aident à construire : accueillir des apprenants, les protéger, leur remettre les outils de l'avenir. Gouvernement, Éducation, Innovation signent comme intendants ; les citoyens la garantissent. Un seul commencement.`,
      111: `Les Accords d'Atlantide sont un pacte entre citoyens du monde — une promesse que toute personne, où qu'elle soit, peut créer et soutenir, quoi que signe son gouvernement ou permette son employeur. Ses régions fondatrices, le Cambodge, le Honduras et Austin, au Texas, ont été choisies pour une qualité rare : la volonté de confier aux jeunes les outils de l'avenir tant qu'il est encore temps de les leur enseigner. Gouvernements, éducateurs et innovateurs signent comme intendants de leurs régions — trois signatures visionnaires chacune, Gouvernement, Éducation, Innovation — mais ce sont les citoyens qui financent l'accord, en sont témoins et le tiennent directement pour responsable. Nulle permission d'un gouvernement, nulle bénédiction d'un employeur n'est requise pour en faire partie. Trois régions, un commencement partagé.`,
      333: `Chaque civilisation est retenue par ce qu'elle a choisi de commencer. Les Accords d'Atlantide sont une promesse entre citoyens du monde — toute personne, où qu'elle se trouve, peut les initier, quoi que signe son gouvernement. Ses régions fondatrices, le Cambodge, le Honduras et Austin, au Texas, n'ont pas été choisies pour leur puissance économique, leur force militaire ou leur prestige institutionnel, mais pour une qualité plus rare encore : la volonté de confier aux jeunes les outils de l'avenir. C'est là ce que signifie le leadership dans le siècle qui vient — le courage de remettre les clés à la génération suivante tant qu'il est encore temps de lui apprendre à conduire.

L'accord est convoqué par eXeL, une force organisatrice conçue pour ce moment précis, existant en dehors des canaux de coordination qui ont façonné le siècle dernier — en dehors des structures de traités diplomatiques, des bureaucraties multilatérales et des enchevêtrements politiques propres à tel ou tel État-nation. eXeL est le convocateur de confiance qui réunit des dirigeants visionnaires autour d'un cadre partagé, d'une dynamique partagée et d'un horizon partagé de cinq cents ans. Chaque signataire conserve sa pleine souveraineté, sa pleine autorité sur ses propres citoyens et sa pleine liberté de se retirer à tout moment. Ce que gagnent les signataires — et ce que gagne tout citoyen, pour le prix d'un Seed, un septième d'une heure de salaire minimum local — c'est l'effet de réseau que seul un cadre conçu pour cela peut offrir : une coordination sans aucune forme de domination politique.

Signer l'accord, c'est signer une promesse : que la région accueillera des apprenants de toutes cultures, apportera ce qu'elle seule peut offrir, et se tiendra à une exigence plus élevée que ne le requiert la réglementation actuelle — publiquement, avec transparence, en répondant devant les citoyens qui le financent, en sont témoins et le tiennent pour responsable, sans qu'aucune permission d'un gouvernement ni bénédiction d'un employeur ne soit requise pour en faire partie. Trois signatures sont exigées de chaque région — Gouvernement, Éducation et Innovation — signant comme intendants, non comme propriétaires. Il faut trois visionnaires pour dire oui, et des citoyens pour tenir ce qu'ils ont signé. Trois visionnaires, trois régions, un commencement — c'est ainsi qu'un cadre entre dans l'existence, par la confiance de dirigeants prêts à le faire naître de leur signature.`,
      999: `Chaque civilisation est retenue par ce qu'elle a choisi de commencer, et Vision 2525 demande aux fondateurs de celle-ci de commencer par l'humilité plutôt que par la conquête. Les Accords d'Atlantide sont une promesse faite par des dirigeants prêts à entreprendre ce qui n'a jamais existé — un socle partagé pour l'innovation humaine, qui atteint chaque coin du monde, honore chaque voix, et perdure à travers des générations qui se comptent non pas en années mais en siècles. Ses signataires fondateurs, au Cambodge, au Honduras et à Austin, au Texas, n'ont pas été choisis pour leur puissance économique, leur force militaire ou leur prestige institutionnel. Ils ont été choisis pour une qualité plus rare : la volonté de confier aux jeunes les outils de l'avenir, et la patience de laisser un horizon de cinq cents ans survivre aux applaudissements de n'importe quelle administration. C'est là ce que signifie le leadership dans le siècle qui vient — le courage de remettre les clés à la génération suivante tant qu'il est encore temps de lui apprendre à conduire.

L'accord est convoqué par eXeL, une force organisatrice conçue pour ce moment précis. eXeL existe en dehors des canaux de coordination qui ont façonné le siècle dernier — en dehors des structures de traités diplomatiques, en dehors des bureaucraties multilatérales, en dehors des enchevêtrements politiques propres à tout État-nation. eXeL est le convocateur de confiance qui réunit des dirigeants visionnaires autour d'un cadre partagé, d'une dynamique partagée et d'un horizon partagé de cinq cents ans. Chaque signataire conserve sa pleine souveraineté, sa pleine autorité sur ses propres citoyens et sa pleine liberté de se retirer à tout moment. Ce que gagnent les signataires, c'est l'effet de réseau que seul un cadre conçu pour cela peut offrir. L'entrée de chaque participant dans ce cadre commence toujours de la même façon modeste : avec un Seed, une adhésion unique tarifée à un septième d'une heure de salaire minimum local, incessible et ne portant aucune créance économique d'aucune sorte. Un Seed n'achète ni propriété ni promesse de récompense — seulement l'appartenance, le droit de se tenir à l'intérieur du cadre et de commencer. C'est une coordination sans aucune forme de domination politique, bâtie sur un commencement assez modeste pour que chacun puisse se le permettre.

Parce que la souveraineté est conservée plutôt que cédée, l'accord est bâti pour la Continuity Without Evasion. Aucun gouvernement, banque, fondateur ou modèle indispensable ne peut tenir l'ensemble du cadre en otage de sa propre survie. Chaque juridiction est servie par son adaptateur légal, refusé par défaut tant que la conformité n'est pas prouvée, de sorte que la valeur ne circule que par des rails qu'un tribunal de cette juridiction reconnaîtrait comme légitimes. Si un régulateur d'une région rend une décision défavorable, ce seul rail se ferme en sécurité — de façon transparente, sans nuire à aucun participant qui s'y trouve — tandis que toutes les autres régions continuent sans être perturbées. L'ensemble de l'accord ne s'effondre jamais parce qu'un gouvernement a changé d'avis. C'est une portabilité conçue comme une promesse fondatrice, et non comme un plan de secours découvert après la crise.

Signer l'accord, c'est signer une promesse. Que la région accueillera des apprenants de toutes cultures. Que la région apportera ce qu'elle seule peut offrir. Que la région se tiendra à une exigence plus élevée que ne le requiert la réglementation actuelle. Que la région le fera publiquement, avec transparence, sous le regard de chaque citoyen qu'elle sert. Trois signatures sont exigées de chaque région — Gouvernement, Éducation et Innovation. Aucune fonction ne lie l'accord seule. Il faut trois visionnaires pour dire oui. Cette triple signature est la première expression de Human Authority : le sens, l'argent et le droit demeurent entre des mains humaines, à la couche souveraine, une couche fermée en permanence aux machines, quelle que soit la capacité que ces machines viendront à atteindre. Le Measurement of Time, MoT, commence à enregistrer dès l'instant de la signature — des minutes réelles de travail humain réel, tenues séparées de toute estimation automatisée — et chaque publication ultérieure du travail de l'accord est conçue pour être reconstituée par Replay, afin qu'un citoyen né dans un siècle puisse retracer comment les décisions fondatrices d'aujourd'hui ont été prises.

Ce que le pilote fonde, c'est la mesure avant que ce ne soit l'argent. Chaque innovation entrant dans le cadre est notée par le Qualified Innovation Score, QIS — la moyenne du chiffre d'affaires, du profit brut, du résultat d'exploitation et des dépenses de R&D effectives, divisée par quatre. Le QIS n'est ni un paiement ni jamais une propriété ; c'est l'instrument par lequel une cohorte fondatrice apprend à voir son propre progrès avant que toute récompense ne soit dimensionnée. La croissance du QIS, une fois la qualification atteinte, dimensionne la réserve de récompense qui suit — mais la croissance du QIS ne crée elle-même aucune valeur. Trois régions, un commencement, et une discipline partagée : prouver le score avant de toucher au trésor.

La valeur gagnée par un travail attesté porte son propre nom, 웃, calculé comme une heure multipliée par le salaire minimum local, mise à l'échelle par un Multiple appliqué aux heures accomplies. Le 웃 n'est émis que pour un travail attesté dans le cadre d'une tâche délimitée et approuvée au budget ; tout ce qui n'a pas franchi cette approbation reste de la planification, et la planification seule ne crée rien. Un plafond de règlement de 9 999 웃 par an protège chaque participant contre une concentration incontrôlée, tout excédent étant reporté plutôt que perdu. Derrière chaque 웃 se tient ♡, Shared Intention, qui porte la raison pour laquelle une tâche a été approuvée en premier lieu, et ◬, l'accélération attestée qu'une tâche a produite par rapport à une référence figée — un simple delta, jamais confondu avec un indicateur de profit. Le pilote existe pour prouver que ces trois glyphes peuvent avancer ensemble avec honnêteté, région après région, avant que le cadre ne s'étende au-delà de ses fondateurs.

Lorsque la valeur atteint une personne, elle l'atteint par Livelihood Direct — 🏠 — des rails locaux qualifiés et agréés qu'eXeL ne détient jamais en tant que fonds propre. La classification précède le règlement dans tous les cas, et la reconnaissance d'une contribution ne conditionne jamais un lit pour la nuit ; seul le rôle d'une personne dans une tâche délimitée le fait. La croissance au-delà du pilote est elle aussi conditionnée : chaque cube du cadre ne passe de Manuel à Semi-Automatisé puis à Autonome qu'après avoir franchi la règle des 11,1 %, un neuvième d'amélioration mesurée, gagné cube par cube et jamais revendiqué en bloc — et jamais, en aucune circonstance, sur la couche souveraine du sens, de l'argent et du droit. C'est ainsi que trois visionnaires par région, trois régions et un commencement deviennent une promesse de cinq cents ans : non pas en allant vite, mais en prouvant, au vu et au su de tous, que chaque étape a mérité celle qui suit.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Apprendre par la simulation`,
    content: {
      7: `S'entraîner mille fois avant de toucher.`,
      33: `Rien d'important ne s'apprend d'abord sur du matériel réel. Tout citoyen peut s'exercer en simulation, effectuer une rotation entre trois régions, célébrer — c'est le respect dû au jeune être humain dont la première erreur ne devrait jamais coûter une vie.`,
      111: `Toute discipline qui mérite d'être maîtrisée a d'abord été apprise par quelqu'un avant d'être connue. Les Accords d'Atlantide replacent cette sagesse ancienne au cœur de la façon dont les jeunes — et tout citoyen qui les rejoint — sont préparés à construire l'avenir. Rien d'important ne s'apprend d'abord sur du matériel réel, sur de vraies personnes, ou dans des conditions irréversibles ; aucune permission d'un gouvernement ni bénédiction d'un employeur n'est requise. Chaque participant s'exerce en simulation jusqu'à ce que la pratique devienne compétence, puis disposition à agir. Le modèle de rotation fait passer chaque participant par les trois régions fondatrices, et chaque rotation s'achève par une célébration publique ouverte à la communauté hôte. C'est le respect dû au jeune être humain dont la première erreur ne devrait jamais coûter une vie.`,
      333: `Toute discipline qui mérite d'être maîtrisée a d'abord été apprise par quelqu'un avant d'être connue. Les maîtres artisans répètent avant la représentation, les pilotes avant le vol, les médecins avant la chirurgie, les enfants par le jeu. Les Accords d'Atlantide replacent cette sagesse ancienne au cœur de la façon dont les jeunes — et tout citoyen qui les rejoint, sans permission d'un gouvernement ni bénédiction d'un employeur — sont préparés à construire l'avenir. Rien d'important ne s'apprend d'abord sur du matériel réel, sur de vraies personnes, ou dans des conditions irréversibles. Chaque participant s'exerce en simulation jusqu'à ce que la pratique devienne compétence, puis disposition à agir. Ce n'est pas de la prudence — c'est le respect dû au jeune être humain dont la première erreur ne devrait jamais coûter la vie à quiconque.

Le modèle de rotation de l'accord fait passer chaque participant par les trois régions fondatrices. Ce qui s'apprend au Cambodge s'affine au Honduras et s'achève à Austin. Ce qui se découvre à Austin se questionne au Cambodge et s'intègre au Honduras. Chaque participant vit, apprend et est encadré à travers des cultures qui, autrement, resteraient distantes. Le programme de formation puise dans des traditions de simulation disciplinée à travers de nombreuses cultures — la tradition d'éducation stratégique de Sun Tzu, l'apprentissage par le jeu de Musashi, la théorie de l'apprentissage cyclique d'Ibn Khaldoun, la dialectique monastique de Nalanda, le simulateur de vol civil — synthétisées dans le respect de chaque stade cognitif et de chaque héritage culturel. Aucune tradition unique ne domine.

Chaque rotation s'achève par une célébration publique ouverte à la communauté hôte, où voisins, familles et visiteurs voient ce que la cohorte a appris. Ces événements rendent une technologie sophistiquée accessible et célébrée plutôt que redoutée — une société qui grandit en comprenant les systèmes coopératifs par le jeu ne peut pas facilement être manipulée par la peur qu'ils inspirent. C'est une dissuasion par l'éducation, non par la force. La promesse de l'accord à chaque parent : votre enfant s'exercera mille fois en sécurité avant de toucher à quoi que ce soit qui pourrait lui nuire, sous témoin, afin qu'un citoyen — n'importe quel citoyen, dans un siècle — puisse vérifier que cela s'est déroulé exactement comme enregistré. C'est le respect du jeune être humain intégré à un cadre, et c'est ce que le leadership doit au prochain citoyen qui le rejoint, avant que ce citoyen n'ait à l'exiger.`,
      999: `Toute discipline qui mérite d'être maîtrisée a d'abord été apprise par quelqu'un avant d'être connue, et toute civilisation qui a duré l'a fait parce qu'elle a protégé l'espace où cet apprentissage pouvait se faire en sécurité, avant qu'on ne lui demande de compter réellement. Les maîtres artisans répètent avant la représentation, les pilotes répètent avant le vol, les médecins répètent avant la chirurgie, et les enfants répètent le monde par le jeu. Les Accords d'Atlantide replacent cette sagesse ancienne au cœur de la façon dont les jeunes sont préparés à construire l'avenir, et ils donnent à cette sagesse un nom et un mécanisme : Replay. Rien d'important ne s'apprend d'abord sur du matériel réel, sur de vraies personnes, ou dans des conditions irréversibles. Chaque participant s'exerce en simulation jusqu'à ce que la pratique devienne compétence, puis disposition à agir, et chaque heure de cette pratique est enregistrée afin de pouvoir être reconstituée plus tard, examinée plus tard, tenue pour fiable plus tard. Ce n'est pas de la prudence — c'est le respect dû au jeune être humain dont la première erreur ne devrait jamais coûter la vie à quiconque, et c'est aussi le respect dû à l'enregistrement qui, de toute façon, survivra à l'erreur.

Le modèle de rotation de l'accord fait passer chaque participant par les trois régions fondatrices. Ce qui s'apprend au Cambodge s'affine au Honduras et s'achève à Austin. Ce qui se découvre à Austin se questionne au Cambodge et s'intègre au Honduras. Chaque participant vit, apprend et est encadré à travers des cultures qui, autrement, resteraient distantes, et chaque rotation commence comme commence toute institution humaine digne de confiance : avec un Seed. Le Seed est une adhésion unique, tarifée à un septième d'une heure de salaire minimum local, incessible, ne portant aucune créance économique d'aucune sorte. Ce n'est pas un droit d'entrée pour accéder à une opportunité. C'est un seuil — assez modeste pour qu'aucun participant volontaire n'en soit exclu, assez délibéré pour que l'entrée soit choisie, et non subie par dérive. Passé ce seuil, chaque participant appartient à la rotation, et la rotation n'appartient à aucune région seule.

Le programme de formation puise dans des traditions de simulation disciplinée à travers de nombreuses cultures — la tradition d'éducation stratégique de Sun Tzu, l'apprentissage par le jeu de Musashi, la théorie de l'apprentissage cyclique d'Ibn Khaldoun, la dialectique monastique de Nalanda, le simulateur de vol civil — synthétisées dans le respect de chaque stade cognitif et de chaque héritage culturel. Aucune tradition unique ne domine. Et au sein de ce programme, l'accord trace une ligne que chaque participant apprend tôt et n'oublie jamais : la simulation est le lieu où l'on comprend le Qualified Innovation Score, non celui où on le dépense. Le QIS est une mesure, jamais un paiement, et le QIS n'est jamais une propriété — il existe pour décrire à quel point une proposition tient debout, résiste à l'examen et sert la région qu'elle prétend servir. La croissance du QIS peut dimensionner une réserve de récompense après une qualification réelle, mais elle ne crée rien par elle-même. Un participant peut mener cent simulations impeccables et voir son score progresser sans qu'une seule heure de 웃 ne touche son registre, car le 웃 n'est émis que pour un travail attesté accompli dans le cadre d'une tâche délimitée et approuvée au budget. Avant cette approbation, tout — aussi habile, aussi prometteur soit-il — n'est que planification. L'accord enseigne cette distinction dès le premier jour, afin qu'aucun jeune ne confonde l'entraînement avec la récompense, et qu'aucun jeune ne soit jamais trompé sur la finalité de la simulation.

Cette même discipline régit la quantité d'autonomie que tout système, humain ou artificiel, est autorisé à exercer au sein de la rotation. Les modes opérationnels de l'accord progressent en séquence — Manuel, puis Semi-Automatisé, puis Autonome — et aucun cube n'avance de mode tant qu'il n'a pas franchi la règle des 11,1 % d'amélioration mesurée, un neuvième, prouvée par rapport à une référence figée et attestée, non simplement affirmée. C'est en simulation que cette preuve se construit. Un outil gagne le droit d'agir avec moins de supervision de la même façon qu'un participant gagne le droit à une responsabilité plus grande : par une amélioration démontrée, enregistrée, reconstituable, cube par cube, jamais d'un seul coup, et jamais sur la couche où se décident le sens, l'argent et le droit. Cette couche appartient à Human Authority seule, en simulation comme en opération réelle, car un espace de répétition qui enseigne la mauvaise frontière enseigne définitivement la mauvaise leçon.

Chaque rotation s'achève par une célébration publique et coopérative ouverte à la communauté hôte. Voisins, familles et visiteurs se rassemblent pour voir ce que la cohorte a appris, et ce dont ils sont témoins n'est pas une démonstration de vitesse pour elle-même, mais une démonstration de ◬ — le delta mesuré entre une référence figée et ce que la pratique disciplinée a réellement accompli, présenté avec honnêteté, jamais habillé en indicateur de profit, jamais présenté comme davantage que ce qu'il est. Ces événements rendent une technologie sophistiquée accessible et célébrée plutôt que redoutée. Une société qui grandit en comprenant les systèmes coopératifs par le jeu ne peut pas facilement être manipulée par la peur que ces systèmes inspirent. C'est une dissuasion par l'éducation, non une dissuasion par la force, et cela fonctionne parce qu'on ne demande pas à la communauté de croire une affirmation — on l'invite à regarder le Replay.

La promesse de l'accord à chaque parent va au-delà de la sécurité, jusqu'à la permanence : votre enfant s'exercera mille fois avant de toucher à quoi que ce soit qui pourrait lui nuire, la communauté sera témoin de sa progression tout du long, et rien de tout cela ne se perdra dans le temps. Le Measurement of Time enregistre les minutes réelles séparément de tout autre registre que tient l'accord, de sorte que les heures d'entraînement et les heures attestées ne soient jamais confondues entre elles, et que l'histoire véritable du développement d'un participant — non pas un résumé, non pas une approximation, mais l'enregistrement reconstituable lui-même — reste accessible à ce participant aussi longtemps qu'il souhaite la consulter. Un parent à Phnom Penh, un mentor à Tegucigalpa, un auditeur à Austin, ou un petit-enfant lisant l'enregistrement dans un siècle, peuvent tous accéder au même Replay et voir la même vérité.

Voilà à quoi ressemble le respect du jeune être humain lorsqu'il est intégré à un cadre plutôt que simplement promis par lui, et voilà ce que le leadership remet à la prochaine génération de participants avant que cette génération n'ait à l'exiger : un espace de répétition assez vaste pour y échouer en sécurité, assez honnête pour enregistrer fidèlement, et assez discipliné pour maintenir la récompense, l'autonomie et l'autorité exactement là où la maîtrise les a méritées — jamais en avance sur elle, jamais en retard.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Sécurité prouvée avant confiance accordée`,
    content: {
      7: `Sécurité prouvée d'abord, confiance accordée ensuite.`,
      33: `Chaque installation et chaque rotation se trouve à l'intérieur d'une enveloppe de protection dotée d'une alerte précoce. Le matériel refuse toute militarisation — prouvé, non promis, inspectable par les citoyens. Les enregistrements survivent aux turbulences. La sécurité est conçue chaque jour autour du plus jeune participant.`,
      111: `Avant que la confiance ne soit accordée, la sécurité doit être prouvée — non pas à un gouvernement, mais à tout citoyen qui l'inspecte. Les Accords d'Atlantide sont un pacte entre citoyens du monde ; leur engagement fondateur est celui-ci : chaque installation de l'accord, chaque itinéraire de rotation, chaque lieu où un jeune participant dort ou étudie se trouve à l'intérieur d'une enveloppe de protection documentée, dotée d'une capacité d'alerte précoce qui laisse à la communauté des heures, non des minutes, pour répondre à tout risque crédible. Chaque appareil, chaque capteur, chaque système de coordination est lié, au niveau matériel, à un refus de toute réaffectation vers une intégration à des systèmes d'armement. Ce n'est pas une politique — c'est de la physique. L'accord reste honorable à travers les turbulences, parce que chaque plan place la dignité humaine en premier.`,
      333: `Avant que la confiance ne soit accordée, la sécurité doit être prouvée — prouvée aux citoyens, non pas affirmée. Les Accords d'Atlantide sont un pacte entre citoyens du monde : toute personne, où qu'elle soit, peut aider à le garantir, quoi que signe son gouvernement. Chaque installation de l'accord, chaque itinéraire de rotation, chaque lieu où un jeune participant dort ou étudie se trouve à l'intérieur d'une enveloppe de protection documentée, dotée d'une capacité d'alerte précoce qui laisse à la communauté des heures, non des minutes, pour répondre à tout risque crédible. La technologie qui les protège est la même technologie que l'accord leur enseigne à construire. Les jeunes apprennent la sécurité de l'intérieur, non pas en se faisant dire qu'ils sont en sécurité, mais en la voyant conçue autour d'eux chaque jour, et en sachant que tout citoyen peut vérifier l'enregistrement par Replay.

L'accord fait une promesse incassable sur ce que sa technologie ne peut jamais devenir. Chaque appareil, chaque capteur, chaque système de coordination est lié, au niveau matériel, à un refus de toute réaffectation vers une intégration à des systèmes d'armement. Ce ne sont pas des mots de politique, ni une aspiration. C'est une impossibilité physique, imposée cryptographiquement, vérifiée par chaque région signataire, et inspectable par chaque citoyen qui la finance. Les outils qui protègent un enfant à Phnom Penh ne peuvent pas être détournés pour nuire à un enfant à Austin. Les outils qui relient un exercice en essaim à Tegucigalpa ne peuvent pas être reconfigurés pour viser un être humain où que ce soit. C'est la réponse de l'accord à un siècle de crainte à double usage. Non pas une politique — de la physique.

L'accord reste honorable à travers les turbulences. Si une région perd sa stabilité politique, les participants sont pris en charge par les régions restantes. Si le financement se contracte, les allocations sont protégées en priorité — financées mensuellement par les citoyens, jamais par un circuit d'aide, chaque dollar étant traçable. Si les enregistrements numériques sont attaqués, des sauvegardes hors ligne subsistent. Si les déplacements deviennent impossibles, le substrat continue virtuellement. Chaque plan place la dignité humaine — Human Authority sur le sens, l'argent et le droit — comme première contrainte de conception. Les dirigeants qui signent cet accord promettent que la sécurité est conçue, non supposée : la protection que tout dirigeant exigerait pour son propre enfant, étendue désormais à chaque citoyen qui aide à le garantir.`,
      999: `Avant que la confiance ne soit accordée, la sécurité doit être prouvée — c'est là l'engagement fondateur des Accords d'Atlantide, et il est prouvé de la même façon que toute autre affirmation à l'intérieur de Vision 2525 : non par une simple assertion, mais par des preuves que les citoyens peuvent inspecter. Chaque installation de l'accord, chaque itinéraire de rotation, chaque lieu où un jeune participant dort ou étudie se trouve à l'intérieur d'une enveloppe de protection documentée, dotée d'une capacité d'alerte précoce qui laisse à la communauté des heures, non des minutes, pour répondre à tout risque crédible. La technologie utilisée pour protéger les participants est la même technologie que l'accord leur enseigne à construire — capteurs, coordination, résilience des communications, intelligence distribuée. Les jeunes apprennent la sécurité de l'intérieur, dans leur propre langue et dans leur propre région, non pas en se faisant dire qu'ils sont en sécurité, mais en observant, heure après heure, comment la sécurité est conçue autour d'eux chaque jour.

Cette observation n'est pas laissée à la mémoire ni à la confiance dans la parole d'un facilitateur. Measurement of Time enregistre les minutes réelles de chaque exercice, chaque rotation, chaque simulation d'intervention — séparément de toute affirmation de progrès, séparément de tout récit tenu ce jour-là. Replay rend chaque publication du programme de formation, chaque mise à jour de sécurité, chaque révision matérielle entièrement reconstituable, de sorte qu'un parent à Tegucigalpa ou un régulateur à Phnom Penh puisse remonter exactement ce qui a changé, quand cela a changé, et pourquoi cela a changé. Une enveloppe de protection qui ne peut pas être rejouée n'est qu'une promesse. Une enveloppe de protection qui peut être rejouée, minute enregistrée après minute enregistrée, est une preuve. L'accord choisit la preuve.

L'accord fait une promesse incassable sur ce que sa technologie ne peut jamais devenir. Chaque appareil, chaque capteur, chaque système de coordination est lié, au niveau matériel, à un refus de toute réaffectation vers une intégration à des systèmes d'armement. Ce ne sont pas des mots de politique, ni une aspiration. C'est une impossibilité physique, imposée cryptographiquement, vérifiée par chaque région signataire, et inspectable par chaque citoyen. Les outils qui protègent un enfant à Phnom Penh ne peuvent pas être détournés pour nuire à un enfant à Austin. Les outils qui relient un exercice en essaim à Tegucigalpa ne peuvent pas être reconfigurés pour viser un être humain où que ce soit. C'est la réponse de l'accord à un siècle de crainte à double usage. Non pas une politique — de la physique.

Une sécurité prouvée une fois n'est pas une sécurité soutenue sur un horizon de cinq cents ans. L'accord nomme son second engagement Continuity Without Evasion : une portabilité légale à travers chaque juridiction que l'accord touche, sans qu'aucun gouvernement, banque, fondateur ou modèle indispensable ne se dresse entre un participant et sa protection. Chaque juridiction est servie par son propre adaptateur, fermé en cas de défaillance et refusé par défaut, de sorte qu'une décision défavorable dans une région ferme ce seul rail — jamais l'ensemble du cadre, jamais toutes les régions, jamais tous les participants partout à la fois. Une décision de justice sur un territoire signataire ne peut pas couper l'enveloppe de sécurité d'un participant ailleurs. Voilà ce que signifie bâtir un système qui survit aux turbulences ordinaires du droit, de la politique et du changement institutionnel, sans jamais demander à un participant de contourner la loi pour rester protégé.

Chaque couche de cette architecture de protection répond, en dernier ressort, à Human Authority. Le sens, l'argent et le droit ne sont jamais délégués aux machines — la couche souveraine qui décide de ce que la sécurité exige, de ce qui constitue un risque crédible, et de la réponse qu'une communauté doit à ses plus jeunes membres, reste fermée à l'intelligence artificielle, quelle que soit la capacité qu'elle vient à atteindre. Les systèmes de l'accord ne se déplacent que par trois modes opérationnels — Manuel, Semi-Automatisé, Autonome — et aucun système n'avance de mode sans une amélioration attestée et mesurée d'au moins un neuvième, soit onze virgule un pour cent, vérifiée, reproductible. L'autonomie se gagne, cube par cube, fonction par fonction, jamais accordée en bloc, et jamais étendue aux questions qui déterminent le sens, l'argent ou le droit. Un capteur peut apprendre à détecter plus vite. Un système de coordination peut apprendre à acheminer plus efficacement. Ni l'un ni l'autre n'est jamais autorisé à décider, seul, de ce qu'une communauté doit confier à ses enfants.

L'accord est conçu pour rester honorable à travers les turbulences, et il nomme la turbulence à l'avance plutôt que de la découvrir dans la crise. Si une région signataire perd sa stabilité politique, les participants sont pris en charge par les régions restantes. Si le financement se contracte, les allocations des participants sont protégées en priorité, avant l'administration et l'infrastructure. Si les enregistrements numériques sont attaqués, des sauvegardes hors ligne subsistent, hors de portée de quelle que soit la défaillance ayant atteint le réseau. Si les déplacements deviennent impossibles, le substrat continue virtuellement, de sorte qu'une rotation ne s'arrête pas parce qu'une frontière s'est fermée. Chaque scénario est anticipé, et chaque plan place la dignité humaine comme première contrainte de conception — non comme dernière considération une fois les budgets et l'image réglés.

L'entrée dans ce système éprouvé commence par le Seed — une adhésion unique, tarifée à un septième d'une heure de salaire minimum local, incessible, et ne portant aucune créance économique sur quoi que ce soit que l'accord construira par la suite. Le Seed n'achète pas la sécurité ; la sécurité est conçue bien avant qu'aucun Seed ne soit jamais planté. Ce que le Seed achète, c'est une position — le droit d'entrer dans un cadre déjà éprouvé, déjà inspecté, déjà lié par du matériel qui ne peut pas être retourné contre la personne même qu'il existe pour protéger. Cette séparation est délibérée. Une promesse de sécurité qui doit être achetée à un vrai coût économique n'est pas une promesse de sécurité du tout, seulement un produit de sécurité. L'accord garde les deux absolument distincts, afin qu'aucune famille n'ait jamais à mettre en balance la protection de son enfant et le budget mensuel de son foyer.

Les dirigeants qui signent cet accord signent une promesse que la sécurité est conçue, non supposée, et prouvée, non simplement affirmée. Ce qu'ils étendent à leurs citoyens n'est pas seulement une opportunité, mais une protection bâtie au niveau que mérite le plus jeune participant — enregistrée par Measurement of Time, reconstituable par Replay, liée au niveau matériel contre tout mésusage qu'un siècle craintif a pu imaginer, et redevable, toujours et uniquement, à Human Authority. C'est la même protection que tout dirigeant exigerait pour son propre enfant traversant seul une frontière inconnue, désormais étendue à chaque enfant que l'accord servira, à travers ses trois régions fondatrices — le Cambodge, le Honduras et Austin — et à travers les cinq siècles durant lesquels l'accord entend tenir cette promesse.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Rémunération, bien-être et dignité humaine`,
    content: {
      7: `Une allocation, un mentor, un foyer.`,
      33: `Chaque citoyen reçoit une allocation dès le premier jour — sans permission d'un gouvernement, sans bénédiction d'un employeur. L'amour, le deuil et la sécurité sont une infrastructure. Le succès se mesure au plus vulnérable. La dignité est un substrat, jamais une décoration.`,
      111: `Les Accords d'Atlantide traitent chaque participant comme un être humain dès le premier jour — un citoyen qui a rejoint de plein droit, non par décret gouvernemental ni par la permission d'un employeur. Une allocation est versée dès l'instant où la participation commence, indexée sur le coût de la vie de la région, et chaque heure attestée gagne du 웃, versé à la personne par Livelihood Direct, jamais par le registre d'un employeur. Le bien-être est traité comme une infrastructure de premier plan — non pas un avantage, mais le substrat sur lequel tout repose. Trois domaines sont soutenus : l'Amour, le Deuil et la Sécurité. L'accord mesure le succès à l'aune de son participant le plus vulnérable, non de la moyenne. Personne n'est oublié pour que les moyennes paraissent bien. La dignité comme substrat, non comme décoration.`,
      333: `Les Accords d'Atlantide traitent chaque participant comme un être humain dès le premier jour — un citoyen qui appartient de plein droit, sans avoir besoin de la permission d'un gouvernement ni de la bénédiction d'un employeur. Une allocation est versée dès l'instant où la participation commence, indexée sur le coût de la vie de la région, et elle arrive avant que les obligations familiales ne deviennent des urgences. Ce n'est pas de la charité. C'est la reconnaissance que l'innovation humaine ordinaire exige d'abord la sécurité humaine — un esprit ne peut pas s'épanouir tant que son foyer est menacé.

Ce qui est gagné au-delà de l'allocation est gagné comme un citoyen le gagne : par le Seed, tarifé à un septième d'une heure de salaire minimum local, et par le 웃, versé uniquement pour des heures attestées. Le QIS mesure la promesse mais ne crée rien — une mesure, jamais un paiement. Chaque paiement atteint le participant par Livelihood Direct, des rails locaux agréés que l'accord ne détient jamais, bâtis pour la Continuity Without Evasion.

Le bien-être est traité comme une infrastructure de premier plan — non pas un avantage, mais le substrat sur lequel tout repose. L'accord nomme trois domaines dans lesquels chaque participant est soutenu : l'Amour, la connexion et la limite saine ; le Deuil, car le chagrin doit être accompagné, non contourné ; et la Sécurité, savoir qui appeler, dans chaque région, dans sa propre langue. Un accompagnement psychologique, des cercles de groupe, et des pratiques culturelles ou spirituelles honorées selon la tradition de chacun sont proposés. Aucune idéologie imposée ; c'est Human Authority, jamais une machine, qui décide des soins dont un citoyen a besoin.

L'accord mesure le succès à l'aune de son participant le plus vulnérable, non de la moyenne. Les citoyens ruraux sans large bande passante sont servis. Les participants neurodivergents reçoivent des aménagements comme norme, non comme exception. Les participants en situation de handicap trouvent chaque installation accessible. Les participants de genre divers reçoivent un hébergement sûr et un jumelage avec un mentor. Les locuteurs non natifs trouvent chaque document dans leur langue. Les participants autochtones voient leurs pratiques culturelles honorées et leurs savoirs traditionnels protégés. Les dirigeants qui signent cet accord promettent qu'aucun citoyen ne sera oublié pour que les moyennes paraissent bien. C'est la dignité comme substrat, non comme décoration. Ce qui est mesuré est ce qui sera honoré, et ce qui est honoré ici, c'est l'être humain tout entier — esprit, corps et âme, soutenu par ses concitoyens, sans exception.`,
      999: `Les Accords d'Atlantide traitent chaque participant comme un être humain à part entière dès le premier jour, intégré au mécanisme même, non pas simplement énoncé en paroles. Une allocation est versée dès l'instant où la participation commence, indexée sur le coût de la vie de la région afin que son incidence respecte la dignité locale du travail. L'allocation arrive avant que les obligations familiales ne deviennent des urgences, et avant que la dignité ne soit compromise. Elle signale à chaque jeune que son temps a de la valeur, que sa contribution est attendue, et que la stabilité de sa famille fait partie de la responsabilité de l'accord. Ce n'est pas de la charité. C'est la reconnaissance que l'innovation humaine ordinaire exige d'abord la sécurité humaine. Un esprit ne peut pas s'épanouir tant que son foyer est menacé. L'entrée elle-même comporte un seuil modeste et délibéré : le Seed, une adhésion unique tarifée à un septième d'une heure de salaire minimum local, incessible et ne portant aucune créance économique propre. Le Seed dit seulement qu'une personne a rejoint ; il ne la paie pas et ne lui promet rien au-delà de la porte qu'il ouvre.

Ce qui est gagné une fois cette porte ouverte est régi avec la même précision que l'accord apporte à chacune de ses autres promesses. Le 웃, la mesure que l'accord donne à Human Intelligence, se calcule simplement — une heure au salaire minimum local, multipliée par le Multiple qui reflète la difficulté et la valeur de la tâche, multiplié par les heures réellement travaillées. Mais le 웃 n'est émis que pour un travail attesté accompli dans le cadre d'une tâche délimitée et approuvée au budget. Avant que cette approbation n'existe, ce qu'un participant fait relève de la planification, non du gain — une distinction que l'accord maintient fermement, car elle protège à la fois le trésor et le participant contre des promesses faites plus vite que la valeur n'est vérifiée. Le Measurement of Time, MoT, enregistre les minutes réellement travaillées séparément de tout calcul de rémunération, de sorte que le temps reste un fait honnête et vérifiable, indépendant du paiement. Les heures d'aucun participant ne sont gonflées, et les heures d'aucun participant ne disparaissent. Un plafond de règlement de 9 999 웃 par an s'applique à chaque participant, tout excédent étant reporté plutôt que perdu, de sorte qu'une contribution exceptionnelle soit reconnue sur plusieurs années plutôt que plafonnée dans l'invisibilité en une seule.

La rémunération est délibérément maintenue distincte de la mesure de l'innovation. Le Qualified Innovation Score, QIS, fait la moyenne du chiffre d'affaires, du profit brut, du résultat d'exploitation et des dépenses de R&D effectives pour décrire l'ampleur réelle de la croissance de l'innovation. Sa croissance dans le temps peut dimensionner une réserve de récompense une fois la qualification atteinte, mais le QIS lui-même ne crée aucun 웃 et ne règle rien directement — c'est une mesure, jamais un paiement, et il n'est jamais confondu avec la propriété de ce qui a été construit. Cette séparation compte parce qu'elle garde l'allocation et le salaire honnêtes : un participant est payé pour des heures attestées de travail réel, non pour un score qui pourrait être manipulé, gonflé, ou contesté. ♡, Shared Intention, porte la raison derrière chaque tâche qu'un participant entreprend ; ◬, l'accélération attestée qu'une tâche produit par rapport à une référence figée, est enregistrée comme un simple delta, jamais habillé en indicateur de profit attaché au travail d'une personne. La rémunération reste ce qu'elle est : un salaire honnête pour un temps honnête et attesté.

La valeur ne s'arrête pas au calcul — elle doit aussi atteindre le participant en tant que personne vivante, et c'est là qu'intervient 🏠, Livelihood Direct. Chaque unité de valeur gagnée par un participant l'atteint par des rails locaux qualifiés et agréés — banques, opérateurs de mobile money, coopératives déjà reconnues et réglementées dans cette région — jamais par un fonds que l'accord détiendrait ou contrôlerait lui-même. La classification du statut d'un participant précède tout règlement ; rien n'est payé avant que l'on ne comprenne correctement qui est payé et pour quoi. Et la reconnaissance du talent, aussi célébrée soit-elle, ne conditionne l'accès ni à un lit, ni à un repas, ni à une place dans la cohorte — seul le rôle réel d'un participant le fait. C'est un refus délibéré de laisser le prestige se substituer à la subsistance. Un contributeur brillant et un contributeur discret dorment sous le même toit protégé, aux mêmes conditions, parce que les engagements de dignité de l'accord ne sont pas un prix décerné pour l'excellence — ils sont un plancher sous chacun.

Le bien-être est traité comme une infrastructure de premier plan — non pas un avantage optionnel, non pas un supplément de confort, mais le substrat sur lequel repose tout le reste. L'accord nomme trois domaines fondamentaux dans lesquels chaque participant est soutenu : l'Amour, au sens de la connexion, de l'attachement et de la limite saine ; le Deuil, car chaque participant connaîtra le chagrin et doit être accompagné, non contourné ; et la Sécurité, au sens où chaque participant sait qui appeler, dans chaque région, dans sa propre langue. Un accompagnement individuel, des cercles de groupe, des pratiques somatiques, et des pratiques culturelles ou spirituelles honorées selon la propre tradition du participant sont tous proposés. Aucune idéologie imposée. L'accord tient cet espace avec révérence ; il ne fait de prosélytisme pour aucun système de croyance. Human Authority régit chacune de ces décisions — le sens, l'argent et le droit demeurent fermés à toute détermination par une machine, quelle que soit la sophistication de la reconnaissance de motifs qui assiste les humains qui décident.

L'accord mesure le succès au résultat de son participant le plus vulnérable, non à la moyenne. Les participants ruraux sans large bande passante sont servis. Les participants neurodivergents reçoivent des aménagements comme norme. Les participants en situation de handicap trouvent chaque installation accessible. Les participants de genre divers reçoivent un hébergement sûr et un jumelage avec un mentor. Les locuteurs non natifs trouvent chaque document dans leur langue. Les participants autochtones voient leurs pratiques culturelles honorées et leurs savoirs traditionnels protégés. Les dirigeants qui signent cet accord promettent qu'aucun participant ne sera silencieusement oublié pour que les moyennes paraissent bien.

Chaque circuit de paiement décrit ici — le Seed, l'allocation, le 웃 gagné sur un travail attesté, le rail Livelihood Direct qui le délivre — est conçu pour la Continuity Without Evasion. Aucune banque, aucun gouvernement, aucun opérateur local n'est indispensable à la rémunération d'un participant ; si un rail agréé dans une juridiction est fermé par une décision défavorable, ce rail seul cesse de fonctionner, jamais l'ensemble du système, et jamais la créance du participant sur ce qui lui était dû. C'est la dignité comme substrat, non comme décoration. Ce qui est mesuré est ce qui sera honoré, et ce qui est honoré ici, c'est l'être humain tout entier — esprit, corps et âme ensemble, payé honnêtement, protégé pleinement, et oublié par aucune comptabilité, sans la moindre exception.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Financement et gouvernance`,
    content: {
      7: `Les citoyens financent directement la génération suivante.`,
      33: `Les Accords d'Atlantide sont un pacte entre citoyens — n'importe qui peut les financer et les garantir. Aucun circuit d'aide, aucun bienfaiteur étranger, aucune condition politique. Chaque dollar est traçable, la comptabilité est publiée chaque mois, dans chaque langue.`,
      111: `Les Accords d'Atlantide sont un pacte entre citoyens du monde — toute personne, où qu'elle soit, peut aider à les créer et à les garantir, quoi que signe son gouvernement ou quel que soit son employeur. Gouvernements, éducateurs et innovateurs signent comme intendants de leurs régions ; ce sont les citoyens qui financent l'accord, en sont témoins et le tiennent directement pour responsable, chacun contribuant chaque mois de petits montants volontaires, assez modestes pour qu'aucun adulte n'en soit exclu. Il n'y a aucun circuit d'aide, aucun bienfaiteur étranger, aucune condition politique attachée. L'accord se tient indépendant des institutions multilatérales qui ont façonné le siècle passé — non pas une déclaration politique, mais un choix de conception. Chaque dollar est traçable ; toute la comptabilité est publiée chaque mois, dans chaque langue.`,
      333: `Les Accords d'Atlantide sont un pacte entre citoyens du monde — toute personne, où qu'elle soit, peut aider à les créer et à les garantir, quoi que signe son gouvernement ou quel que soit son employeur. Ils sont financés par les citoyens qu'ils servent : les habitants des régions participantes contribuent chaque mois de petits montants volontaires, assez modestes pour qu'aucun adulte n'en soit exclu, assez significatifs pour que le total soutienne le travail de l'accord à grande échelle. Lorsqu'un citoyen finance directement la prochaine génération, ce citoyen tient directement l'accord pour responsable. Il n'y a aucun circuit d'aide, aucun bienfaiteur étranger, aucune condition politique attachée. L'âme de l'accord, c'est le citoyen qui contribue un petit montant chaque mois, dont la participation rend le tout possible.

Gouvernement, Éducation et Innovation signent comme intendants de leurs régions — trois signatures visionnaires engageant une région à accueillir, protéger et enseigner — mais l'intendance n'est pas la propriété. L'accord est indépendant des institutions multilatérales qui ont façonné le siècle passé — l'Organisation du traité de l'Atlantique Nord, l'Organisation mondiale de la santé, les Nations unies, le Fonds monétaire international, la Banque mondiale, et tout circuit national d'aide étrangère. C'est un choix de conception, non une déclaration politique : un cadre au service de chaque région, quel que soit son alignement géopolitique, ne peut être mêlé à un seul de ces alignements. Les gouvernements nationaux peuvent contribuer volontairement. Les contributions sont transparentes. Aucune contribution n'achète d'influence sur la gouvernance, de quelque source que ce soit, jamais.

Chaque dollar et chaque unité de valeur entrant dans l'accord est enregistré de façon permanente, publique et traçable — reconstituable par Replay, afin qu'un citoyen dans un siècle puisse vérifier la chaîne intacte. La valeur atteint un participant par des heures de 웃 attestées et des rails locaux agréés, jamais par un fonds que l'accord détiendrait lui-même ; le QIS mesure honnêtement, il ne paie jamais. Les frais administratifs sont plafonnés, les dons d'entreprise le sont tout autant. Une comptabilité complète est livrée dans la langue de chaque région signataire, chaque mois. Les dirigeants qui signent l'accord promettent une transparence rarement offerte par une institution. C'est la confiance qu'exige l'accord — gagnée une petite contribution traçable à la fois, sous le regard de chaque citoyen.`,
      999: `Les Accords d'Atlantide sont eux-mêmes financés par les citoyens qu'ils servent, et ce seul fait façonne tout ce qui en découle — chaque rail, chaque registre, chaque porte qu'un jeune doit franchir pour être vu. Les habitants ordinaires des régions participantes contribuent chaque mois de petits montants volontaires, assez modestes pour qu'aucun adulte, dans aucune région hôte, ne soit exclu de la participation, assez significatifs pour que le total soutienne le travail de l'accord à une échelle véritable. Cette conception est délibérée, et elle n'est pas accessoire à la mission — elle en est la preuve. Lorsqu'un citoyen finance directement l'éducation de la prochaine génération, ce citoyen tient directement l'accord pour responsable, dans le même geste, sans intermédiaire susceptible d'adoucir le compte ou d'en retarder le bilan. Il n'y a aucun circuit d'aide, aucun bienfaiteur étranger, aucune condition politique attachée au chèque. L'âme de l'accord, c'est le citoyen qui contribue un petit montant chaque mois, dont la participation rend le tout possible, et dont la participation continue est le seul vote de confiance qui compte réellement sur cinq cents ans.

L'accord est délibérément indépendant des institutions multilatérales qui ont façonné le siècle passé — l'Organisation du traité de l'Atlantique Nord, l'Organisation mondiale de la santé, les Nations unies, le Fonds monétaire international, la Banque mondiale, et tout circuit national d'aide étrangère. Ce n'est pas une déclaration politique sur la valeur de ces institutions ou de leurs contributions. C'est un choix de conception, et c'est le même choix de conception qui régit chaque rail technique sous l'accord lui-même : Continuity Without Evasion. La portabilité légale est la règle — aucun gouvernement, banque, fondateur ou modèle indispensable ne peut se trouver sous l'ensemble de la structure, car un horizon de cinq cents ans ne peut pas être misé sur la permanence d'un seul acteur. Chaque juridiction porte son propre adaptateur, fermé en cas de défaillance et refusé par défaut, de sorte qu'une décision défavorable dans une nation ferme ce seul rail, et lui seul — elle ne fait jamais s'effondrer les comptes d'une famille dans une région à un océan de distance. Les gouvernements nationaux peuvent contribuer volontairement. Les contributions sont transparentes. Aucune contribution n'achète d'influence sur la gouvernance, de quelque source que ce soit, jamais — ni d'un gouvernement, ni d'une entreprise, ni des fondateurs mêmes du cadre.

Human Authority est le second pilier porteur de cette conception du financement. Le sens, l'argent et le droit demeurent des affaires humaines, décidées par des êtres humains sous le regard d'autres êtres humains ; la couche souveraine où le but de l'accord est fixé et ses fonds sont gouvernés reste fermée aux machines, aussi capables que celles-ci deviennent dans les tâches situées en dessous. Measurement of Time enregistre les minutes réellement travaillées séparément de toute affirmation sur leur valeur, de sorte que personne — humain ou artificiel — ne puisse discrètement gonfler l'enregistrement. Replay se tient derrière chacun de ces enregistrements, rendant reconstituable depuis son origine chaque publication que l'accord émet jamais, à jamais ouverte à la contestation, à jamais ouverte à la correction. Un citoyen qui contribue aujourd'hui d'un petit montant fait confiance au fait que, dans cinquante ans, dans deux cents ans, quelqu'un pourra encore remonter la chaîne jusqu'au registre de ce mois-ci et le trouver exactement tel qu'il était.

L'entrée dans ce système de confiance commence par le Seed — une adhésion unique, tarifée à un septième d'une heure de salaire minimum local, incessible et ne portant aucune créance économique d'aucune sorte. Le Seed n'achète ni part, ni vote pondéré par la richesse, ni position privilégiée dans la comptabilité qui suit. Il n'achète que l'appartenance, à un prix assez bas pour qu'un jeune, partout où l'accord opère lui-même, puisse se permettre de commencer. Tout ce qu'un membre gagne au-delà de ce point est gagné, jamais acheté, et cette distinction résume à elle seule toute l'architecture morale de l'accord.

La valeur qui parvient bien jusqu'à une personne circule par 🏠 Livelihood Direct — des rails locaux qualifiés et agréés qui acheminent le paiement jusqu'à la personne, jamais dans un fonds que le cadre lui-même détiendrait ou contrôlerait. La classification précède le règlement dans tous les cas ; un lit, une allocation, une place dans l'étape suivante de la formation sont conditionnés par le rôle et la disposition à agir, jamais par la seule reconnaissance, car la reconnaissance ne coûte rien et une subsistance, si. Voici la chaîne que parcourt réellement la contribution mensuelle d'un citoyen : du compte du citoyen, à travers un rail audité, vers l'allocation que reçoit un jeune, vers le projet d'innovation que devient le travail de ce jeune, et de retour vers l'extérieur sous forme d'un compte public que tout citoyen peut lire.

Ce que vaut ce travail est mesuré, non supposé. Le Qualified Innovation Score fait la moyenne de la disposition à agir, du potentiel de croissance, de l'impact des résultats et de la disposition à l'exécution en un seul chiffre, et la croissance de ce score ne dimensionne la réserve de récompense qu'une fois la qualification atteinte — le QIS lui-même ne crée rien et ne règle rien ; c'est une mesure, jamais un paiement, et cette mesure n'est jamais confondue ici avec la propriété. Le paiement du travail humain arrive plutôt sous forme de 웃, évalué à une heure fois le salaire minimum local, multiplié par un multiple d'heures réellement travaillées et attestées, délimité et approuvé au budget. Avant qu'une tâche ne porte cette approbation, le travail qui la sous-tend est de la planification, non un travail rémunérable, et personne n'est payé pour planifier. Un plafond de 9 999 웃 par an, tout excédent étant reporté plutôt que perdu, empêche le compte d'une seule année de devenir soit une aubaine, soit un piège.

Rien de tout cela ne va plus vite que sa propre preuve. L'accord lui-même progresse du fonctionnement Manuel au Semi-Automatisé puis à l'Autonome, un cube à la fois, et seulement là où un ordre complet d'amélioration mesurée — un neuvième — a réellement été démontré, jamais supposé à l'avance. L'autonomie se gagne exactement là, et nulle part à proximité du sens, de l'argent ou du droit, qui restent toujours humains. Les frais administratifs sont plafonnés. Les dons d'entreprises et d'institutions sont bienvenus et tout aussi plafonnés. Une comptabilité complète est livrée dans la langue de chaque région signataire, chaque mois, en commençant par le Cambodge, le Honduras et Austin, et destinée à être encore livrée, et encore lisible, dans cinq cents ans. C'est la confiance qu'exige l'accord. C'est la confiance que l'accord gagne, une petite contribution traçable à la fois, sous le regard de chaque citoyen qu'il servira jamais.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Échange interculturel et contribution mondiale`,
    content: {
      7: `Chaque apprenant dans sa propre langue.`,
      33: `Chaque activité dans la langue du participant — ouverte à tout citoyen, sans permission d'un gouvernement requise. Les intelligences artificielle, humaine et partagée tenues en tension féconde. Les programmes publiés en accès libre. Ce qu'une région apprend, tous en héritent.`,
      111: `Les Accords d'Atlantide rendent à l'éducation sa vocation la plus profonde : l'échange de sagesse à travers des frontières qui, autrement, diviseraient. Tout citoyen peut entrer dans ce programme, quoi qu'ait signé son gouvernement. Chaque activité est proposée dans la langue du participant, dans la langue de la région hôte, et dans un registre partagé. La langue n'est pas une décoration — la langue est une juridiction, la langue est la dignité rendue lisible. Le cadre éducatif repose sur la trinité des intelligences : l'Artificielle propose, l'Humaine décide, l'Intention Partagée valide. Chaque étudiant apprend à tenir ces trois-là en tension. Ce que l'accord apprend, il le redonne. Programmes, résultats d'innovation, recherches sur le bien-être et décisions de gouvernance sont publiés en accès libre. Ce qu'une région apprend, tous les citoyens en héritent.`,
      333: `Les Accords d'Atlantide rendent à l'éducation sa vocation la plus profonde : l'échange de sagesse à travers des frontières qui, autrement, diviseraient. C'est un pacte entre citoyens du monde — tout citoyen peut le construire et le garantir, quoi qu'ait signé son gouvernement. Chaque activité est proposée dans la langue du participant, dans la langue de la région hôte, et dans un registre partagé, de sorte qu'aucun participant ne navigue dans l'accord dans une langue qu'il n'a pas choisie. La langue n'est pas une décoration. La langue est une juridiction. La langue est la dignité rendue lisible. Un jeune au Cambodge lit son relevé d'allocation en khmer, au Honduras en espagnol, à Austin en anglais — les trois honorés également, aucun n'ayant besoin de la bénédiction d'un gouvernement pour commencer.

Le cadre éducatif repose sur la trinité des intelligences que Vision 2525 rend visible. L'Intelligence Artificielle propose des schémas et des possibilités plus vite qu'aucun humain seul ne le pourrait. L'Intelligence Humaine décide de la sécurité, de l'éthique et de la direction — des questions auxquelles aucune machine ne devrait répondre, maintenues sous Human Authority. L'Intention Partagée valide que les décisions servent les principes de l'accord, afin qu'aucun participant ne choisisse l'excellence au détriment du bien collectif. Aucun étudiant ne s'en remet à une seule intelligence ; chaque étudiant apprend à tenir les trois en tension. L'appartenance commence par le Seed, une adhésion tarifée à un septième d'une heure de salaire minimum local — assez modeste pour que tout citoyen puisse se le permettre. Cela prépare la prochaine génération à gouverner, là où aucune intelligence n'agit sans contrôle.

Ce que l'accord apprend, il le redonne. Les programmes sont publiés sous licence ouverte afin que toute région — signataire ou non — puisse les adapter à sa culture locale. Les résultats d'innovation sont publiés. Les recherches sur le bien-être sont publiées de façon agrégée pour les chercheurs du monde entier. Les décisions de gouvernance sont publiées avec leur raisonnement, afin que tout citoyen, et non seulement un gouvernement signataire, puisse les vérifier — et Replay permet à ce même citoyen de retracer ce raisonnement dans un siècle. Le succès se mesure non seulement à ses participants, mais aux initiatives éducatives et culturelles qui naissent dans son sillage, dans des régions qui n'ont jamais signé le pilote mais qui ont bâti sur sa sagesse partagée. Ce qu'une région apprend, chaque citoyen en hérite.`,
      999: `Les Accords d'Atlantide rendent à l'éducation sa vocation la plus profonde : l'échange de sagesse à travers des frontières qui, autrement, diviseraient, et cet échange commence avant même qu'une seule leçon ne soit enseignée. Le premier acte de chaque participant à l'intérieur du cadre est le Seed — une adhésion unique, tarifée à un septième d'une heure de salaire minimum local, incessible, ne portant aucune créance économique d'aucune sorte. Il est assez modeste pour qu'aucune famille n'en soit exclue, et assez réel pour qu'aucun participant n'entre en simple spectateur. C'est la première leçon de l'accord : l'appartenance se gagne à bas prix, mais elle se gagne tout de même, et elle ne confère aucune propriété sur ce qui vient ensuite. Chaque activité de l'accord qui suit est proposée dans la langue du participant, dans la langue de la région hôte, et dans un registre partagé, de sorte qu'aucun participant ne navigue dans l'accord dans une langue qu'il n'a pas choisie. La langue n'est pas une décoration. La langue est une juridiction. La langue est la dignité rendue lisible. Quand un jeune d'un village cambodgien lit son relevé d'allocation en khmer, une ville hondurienne en espagnol, et un quartier d'Austin en anglais, les trois sont honorés également par le même accord, dans les mêmes régions fondatrices qui ont d'abord accepté de s'enseigner mutuellement.

Le cadre éducatif de l'accord repose sur la trinité des intelligences que Vision 2525 rend visible, et le programme enseigne chacune d'elles comme quelque chose qu'un participant peut sentir de ses propres mains, non comme une abstraction. ♡, Shared Intention, porte le pourquoi — le fil que chaque étudiant apprend à tenir avant de toucher à aucun outil, la question de savoir si ce travail sert encore les personnes qu'il prétend servir. ◬, l'accélération attestée, est enseignée comme un delta et rien de plus — mesurée uniquement par rapport à une référence figée, jamais habillée en indicateur de profit, jamais revendiquée comme un accomplissement personnel séparé de l'équipe environnante. 웃, Human Intelligence honorée dans le temps, est enseignée avec le plus grand soin : une heure de travail attesté équivaut à une heure au salaire minimum local, et ce qu'un participant gagne est ce salaire multiplié par les heures travaillées — Multiple fois Temps, rien de caché dans l'arithmétique. Les étudiants apprennent tôt que le 웃 n'est émis que pour un travail attesté accompli dans le cadre d'une tâche délimitée et approuvée au budget. Avant que cette approbation n'existe, le même effort n'est que de la planification — précieuse, mais non rémunérée, et chaque participant apprend à reconnaître la différence au premier coup d'œil.

Parce que cette différence se brouille facilement, le programme enseigne le QIS, le Qualified Innovation Score, comme un miroir plutôt que comme un tableau de score. Le QIS est la moyenne de quatre grandeurs financières absolues — chiffre d'affaires, profit brut, résultat d'exploitation et R&D effective — divisée par quatre, et chaque étudiant apprend à le calculer, à le questionner, et à ne jamais le confondre avec de l'argent. La croissance du QIS ne dimensionne la réserve de récompense qu'une fois la qualification confirmée de façon indépendante, et cette croissance ne crée aucun 웃 par elle-même. Le QIS est une mesure. Le QIS n'est jamais un paiement. Le QIS n'est jamais une propriété. Un étudiant qui a intégré cette distinction ne peut pas être persuadé qu'un score élevé lui donne droit à une créance que l'accord n'a jamais promise.

Le programme étend cette culture financière à la façon dont la valeur atteint réellement une personne, à travers ce que l'accord appelle Livelihood Direct — le principe 🏠 selon lequel l'argent circule par des rails locaux qualifiés et agréés, jamais par un fonds que le cadre lui-même détiendrait. Les étudiants apprennent à tracer leur allocation, puis plus tard leurs propres gains, à travers ces rails comme un exercice civique, non comme un mystère financier accompli ailleurs en leur nom. Ils apprennent que la classification précède toujours le règlement, et que la reconnaissance — un QIS élevé, une distinction publique — ne conditionne pas à elle seule un lit, une allocation, ou une place dans la rotation. C'est le rôle qui le fait. C'est une protection contre un échec très ancien : l'éloge confondu avec la subsistance.

Aux côtés de cette culture financière se trouve une culture civique, enseignée par Continuity Without Evasion. Chaque participant apprend que l'accord est bâti pour la portabilité légale — qu'aucun gouvernement, banque, fondateur ou modèle indispensable ne se dresse entre lui et les promesses du cadre. Il apprend ce que fait une décision défavorable à l'intérieur de cette conception : elle ferme un seul rail, dans une seule juridiction, sous la posture de refus par défaut de cet adaptateur, et ne fait jamais s'effondrer l'ensemble. À cela s'ajoute la leçon la plus profonde que l'accord enseigne : Human Authority garde le sens, l'argent et le droit, et la couche souveraine où ces décisions se prennent reste fermée en permanence aux machines. Le Measurement of Time, MoT, enregistre les minutes réelles de chaque participant séparément de tout score, et Replay rend entièrement reconstituable chaque publication que l'accord émet — de sorte qu'un étudiant qui veut savoir pourquoi une décision a été prise, des années plus tard, peut la retracer lui-même plutôt que de prendre la parole de quiconque pour argent comptant.

Cette structure de confiance méritée devient le modèle pédagogique de l'accord, non seulement son modèle de gouvernance. Chaque participant progresse à travers les modes Manuel, Semi-Automatisé et Autonome, offrant une latitude croissante, conditionnés par le même seuil d'amélioration mesurée qui conditionne la technologie elle-même — un gain vérifié de onze et un neuvième pour cent avant que le mode suivant ne s'ouvre. L'autonomie, lorsqu'elle est gagnée, l'est étroitement et par domaine, jamais sur le sens, l'argent ou le droit. Un étudiant qui a vécu cette progression comprend, viscéralement, pourquoi la couche souveraine ne doit jamais être automatisée — parce qu'il a gagné sa propre autonomie une étape mesurée à la fois, et sait exactement ce que cette autonomie incluait et n'incluait pas.

Ce que l'accord apprend, l'accord le redonne. Les programmes sont publiés sous licence ouverte afin que toute région — signataire ou non — puisse les adapter à sa culture locale et à sa tradition pédagogique. Les résultats d'innovation sont publiés. Les recherches sur le bien-être sont publiées de façon agrégée pour les chercheurs du monde entier. Les décisions de gouvernance sont publiées avec leur raisonnement intégral. Le succès de l'accord se mesure non seulement à ses propres participants au Cambodge, au Honduras et à Austin, mais aux initiatives qui naissent dans son sillage, dans des régions qui n'ont jamais signé le pilote fondateur mais qui ont bâti sur sa sagesse librement partagée, sur un horizon que les fondateurs ne vivront pas assez longtemps pour voir s'achever. Ce qu'une région apprend, toutes les autres régions en héritent — et ce que cette génération apprend honnêtement, les cinq cents prochaines années n'auront pas à le désapprendre.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Croissance durable du réseau`,
    content: {
      7: `Jamais plus vite que la dignité.`,
      33: `Trois régions fondatrices achèvent un cycle pilote complet avant qu'une quatrième ne les rejoigne — tout citoyen peut y contribuer. Les enregistrements sont ancrés pour durer cinq siècles. Les signataires conservent leur souveraineté ; rien n'est réduit pour la prochaine adhésion.`,
      111: `Les Accords d'Atlantide ne croîtront pas plus vite que la qualité qu'ils peuvent honorer. Trois régions fondatrices doivent achever un cycle pilote complet, chaque participant honoré et chaque principe vérifié, avant qu'une quatrième région ne les rejoigne. C'est un principe devenu enfin discipline opérante. Mais l'accord est un pacte entre citoyens du monde — toute personne, où qu'elle soit, peut le construire et le garantir, à un Seed près, quoi que signe un gouvernement ou permette un employeur. L'horizon de l'accord est de cinq siècles. Ses enregistrements sont ancrés par Replay, afin qu'un citoyen les lisant dans un siècle puisse se fier au raisonnement. Chaque signataire conserve sa souveraineté ; rien n'est réduit pour la prochaine adhésion.`,
      333: `Les Accords d'Atlantide ne croîtront pas plus vite que la qualité qu'ils peuvent honorer. Chaque expansion est une promesse faite aux participants déjà présents — que la norme fondatrice ne sera pas diluée par l'ampleur. Trois régions fondatrices doivent achever un cycle pilote complet, chaque participant honoré et chaque principe vérifié, avant qu'une quatrième région ne les rejoigne. C'est un principe devenu enfin discipline opérante. Et la porte n'a jamais été seulement régionale : ceci est un pacte entre citoyens du monde, et toute personne peut le construire, le financer, et le tenir pour responsable — sans permission d'un gouvernement, sans bénédiction d'un employeur requise. Les dirigeants qui signent le pilote promettent aux signataires le même substrat, la même protection et la même dignité que ceux reçus par la cohorte fondatrice. Rien n'est réduit pour la suivante.

L'horizon de l'accord est délibérément long — conçu pour durer quinze à vingt générations humaines, cinq siècles à partir du jour fondateur. Ses enregistrements sont ancrés par Replay, afin qu'un citoyen les lisant dans un siècle puisse vérifier le raisonnement, non simplement s'y fier. Son cadre de référence, ses rôles Human Authority, et ses cycles de gouvernance intergénérationnels sont bâtis pour survivre à toute transition technologique unique. L'accord survivra à chaque humain qui signe son pilote fondateur, et à chaque citoyen qui plante un Seed et le finance chaque mois. C'est là sa promesse à l'enfant qui signe un accord d'allocation, au citoyen qui a rejoint sans devoir la permission d'aucun gouvernement, aux petits-enfants de cet enfant qui pourraient gouverner l'accord au milieu du siècle, et à chaque génération qui hérite de ce que les fondateurs — officiels et citoyens de même — construisent aujourd'hui.

Chaque signataire conserve la liberté de se retirer, sa pleine souveraineté, et son autorité sur ses propres citoyens, avec le droit d'amender et de façonner l'évolution de l'accord. Chaque citoyen conserve la même légitimité pour le fonder, le financer, en être témoin, et le tenir pour responsable — avec ou sans signature gouvernementale. Ce qu'aucun ne peut faire, c'est compromettre les principes fondateurs, car cette promesse doit survivre à tout départ. Dirigeants et citoyens signent ensemble le siècle à venir de l'accord dans un horizon que leurs petits-enfants hériteront et achèveront.`,
      999: `Les Accords d'Atlantide ne croîtront pas plus vite que la qualité qu'ils peuvent honorer, et cette retenue n'est pas un sentiment — c'est de l'ingénierie, inscrite dans la même discipline de mesure qui régit chaque promesse que fait l'accord. Trois régions fondatrices, le Cambodge, le Honduras et Austin, doivent achever un cycle pilote complet, chaque participant honoré et chaque principe vérifié, avant qu'une quatrième région ne les rejoigne. Une croissance qui devance la vérification n'est pas une croissance ; c'est une exposition déguisée en ambition. Le pilote fondateur existe pour que l'accord puisse prouver, à une échelle assez petite pour être inspectée et assez grande pour compter, que ses promesses survivent au contact de la réalité avant d'être étendues à un monde qui observe depuis l'extérieur de ses trois frontières. La quatrième région n'est pas encore nommée, et ne le sera pas tant que les trois premières ne se porteront pas garantes de chaque affirmation de ce document.

Ce qui prouve la disposition à croître n'est pas l'enthousiasme mais un chiffre que l'accord peut défendre publiquement. Le Qualified Innovation Score — QIS, calculé comme la somme du chiffre d'affaires, du profit brut, du résultat d'exploitation et des dépenses de R&D effectives, divisée par quatre — est l'instrument que l'accord utilise pour savoir si une région, une cohorte, ou un cube s'est réellement amélioré, plutôt que d'avoir simplement eu l'impression de s'améliorer. La croissance du QIS ne dimensionne la réserve de récompense qu'une fois la qualification atteinte, jamais avant, et le QIS lui-même ne crée aucun 웃 et n'achète aucune propriété. Le QIS est une mesure, non un paiement ; une mesure, non une participation ; un miroir que l'accord tend à son propre travail, jamais une monnaie qu'il dépense. Une région proposant d'étendre le réseau doit montrer son QIS honnêtement, sous le regard des régions qui l'ont précédée, ou elle ne s'étend pas.

Une croissance durable est une croissance qui gagne sa propre autorité un incrément à la fois. Chaque cube et chaque région commence en mode Manuel, où les humains décident de tout et le système assiste. L'avancement vers un fonctionnement Semi-Automatisé, puis éventuellement Autonome, au sein d'un cube donné, est conditionné par un seuil unique à travers tout l'accord — une amélioration mesurée de onze et un neuvième pour cent, un neuvième, prouvée et reproductible avant que le degré d'autonomie suivant ne soit accordé. L'autonomie se gagne cube par cube, jamais revendiquée en bloc ni étendue aux domaines qui doivent rester humains quelle que soit la sophistication atteinte par le système : le sens, l'argent et le droit demeurent fermés aux machines, quel que soit le nombre de seuils franchis ailleurs. Un réseau qui étend son automatisation plus vite qu'il n'étend ses preuves ne se modernise pas. Il joue avec une confiance qu'il n'a pas encore méritée.

La rémunération s'étend avec le réseau de la même façon que l'autorité — délibérément, et avec un plafond qui protège l'ensemble du système de son propre succès. Le 웃, jeton de Human Intelligence, équivaut à une heure de travail attesté multipliée par le salaire minimum local ; ce que gagne tout participant est ce Multiple fois les heures travaillées, et il n'est émis que pour un travail accompli dans le cadre d'une tâche délimitée et approuvée au budget. Avant l'approbation, le plus beau plan n'est que planification, et la planification seule ne crée rien. Le règlement de chaque participant est plafonné à 9 999 웃 par an, tout excédent étant reporté plutôt que perdu ou déformant la réserve. Au fur et à mesure que de nouvelles régions rejoignent le réseau et que son activité se multiplie, c'est ce plafond qui empêche la croissance de devenir de l'inflation — la valeur reste attachée à des heures réelles, attestées et locales, quelle que soit l'ampleur atteinte par l'accord.

Derrière chaque 웃 se trouve un pourquoi qu'aucun registre ne peut calculer seul. ♡, Shared Intention, porte ce pourquoi à travers chaque décision d'expansion que prend l'accord, tandis que ◬, la contribution de l'Intelligence Artificielle, est comptée comme une accélération attestée mesurée par rapport à une référence figée — un delta, et jamais, en aucune circonstance, un indicateur de profit à optimiser pour lui-même. L'entrée dans ce réseau commence de la même façon pour chaque participant, quelle que soit la région ou la décennie où il rejoint : avec un Seed, une adhésion unique tarifée à un septième d'une heure de salaire minimum local, incessible et ne portant aucune créance économique d'aucune sorte. Le Seed dit seulement qu'une personne est arrivée. Tout ce qu'elle construit ensuite, elle le construit au vu et au su des trois autres monnaies de l'accord, jamais par le Seed lui-même.

Une croissance qui est réelle doit aussi être une croissance qui atteint une personne concrète, non un fonds que le cadre détiendrait au nom de quelqu'un. 🏠 Livelihood Direct exige que la valeur ne parvienne à un participant que par des rails locaux qualifiés et agréés, que l'accord a vérifiés région par région, et jamais par une garde que le cadre conserverait lui-même. La classification précède toujours le règlement, de sorte qu'aucune valeur ne circule avant que son but et son destinataire ne soient tous deux établis hors de tout doute. Et parce que la reconnaissance n'équivaut pas à l'accès, un lit, une place dans la rotation, une place à la table sont conditionnés par le rôle et la disposition à agir, jamais par le score ou le statut d'un participant. À mesure que le réseau s'étend à une quatrième région et au-delà, chaque nouveau territoire doit qualifier ses propres rails agréés avant que Livelihood Direct ne puisse atteindre sa population — une expansion de la confiance, non simplement une expansion du territoire.

Rien de tout cela ne dure sans un réseau bâti pour survivre à son propre succès, c'est pourquoi Continuity Without Evasion régit chaque région que l'accord ajoute jamais. La portabilité légale est obligatoire ; aucun gouvernement, banque, fondateur ou modèle unique ne peut devenir indispensable à l'ensemble. Chaque juridiction fait tourner son propre adaptateur, fermé en cas de défaillance et refusé par défaut, de sorte qu'une décision défavorable où que ce soit ferme un seul rail, jamais l'accord tout entier. Human Authority détient le sens, l'argent et le droit à chaque échelle que le réseau atteint, scellés contre tout empiètement des machines par conception, et non par simple promesse. Le Measurement of Time enregistre chaque minute réelle séparément de toute affirmation à son sujet, et Replay garantit que toute publication, dans toute région, à tout moment sur cinq siècles, peut être reconstituée et réexaminée par quiconque le demande. Un réseau qui ne peut pas être rejoué ne peut pas inspirer confiance, quel que soit le nombre de régions qui l'ont rejoint ou l'ampleur impressionnante que sa croissance semble avoir de l'extérieur. C'est ainsi que Vision 2525 croît sans jamais dépasser la confiance qu'elle a été bâtie pour préserver — une région vérifiée, un QIS honnête, une heure attestée à la fois.`,
    },
  },
];
