import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_ID: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Di Mana Inovasi Dimulai`,
    content: {
      7: `Para pemimpin memulai yang belum pernah dimulai.`,
      33: `Tiga wilayah — Cambodia, Honduras, Austin — berjanji untuk menampung pelajar muda, melindungi mereka, dan menyerahkan alat masa depan. Pemerintahan, Pendidikan, Inovasi: tiga tanda tangan visioner per wilayah. Satu permulaan bersama.`,
      111: `Atlantis Accords adalah janji yang dibuat oleh para pemimpin yang bersedia memulai sesuatu yang belum pernah ada sebelumnya. Para penanda tangan pendirinya di Cambodia, Honduras, dan Austin, Texas dipilih karena satu sifat langka: kesediaan untuk memercayai generasi muda dengan alat masa depan selagi masih ada waktu untuk mengajari mereka. Menandatangani accord ini mengikat wilayah tersebut untuk menampung pelajar lintas budaya, menyumbangkan apa yang hanya bisa ia berikan secara unik, dan menjaga dirinya pada standar yang lebih tinggi daripada regulasi yang berlaku. Tiga tanda tangan visioner — Pemerintahan, Pendidikan, Inovasi — memasuki accord ini bersama. Tiga visioner, tiga wilayah, satu permulaan bersama.`,
      333: `Setiap peradaban dikenang oleh apa yang ia pilih untuk mulai. Atlantis Accords adalah janji yang dibuat oleh para pemimpin yang bersedia memulai sesuatu yang belum pernah ada sebelumnya — sebuah fondasi bersama bagi inovasi manusia biasa yang menjangkau setiap sudut dunia, menghormati setiap suara, dan bertahan lintas generasi. Para penanda tangan pendirinya di Cambodia, Honduras, dan Austin, Texas tidak dipilih karena kekuatan ekonomi, kekuatan militer, atau prestise institusional. Mereka dipilih karena sifat yang lebih langka: kesediaan untuk memercayai generasi muda dengan alat masa depan. Inilah arti kepemimpinan di abad yang akan datang — keberanian untuk menyerahkan kunci kepada generasi berikutnya selagi masih ada waktu untuk mengajari mereka cara mengemudinya.

Accord ini diselenggarakan oleh eXeL, sebuah kekuatan pengorganisasi yang dibangun khusus untuk momen ini. eXeL sengaja berada di luar saluran koordinasi tradisional yang membentuk abad lalu — di luar struktur perjanjian diplomatik, di luar birokrasi multilateral, di luar keterikatan politik negara-bangsa mana pun. eXeL adalah penyelenggara terpercaya yang mempertemukan para pemimpin visioner di sekitar kerangka bersama, roda gila bersama, dan cakrawala lima ratus tahun bersama. Setiap penanda tangan mempertahankan kedaulatan penuh, otoritas penuh atas warganya sendiri, dan kebebasan penuh untuk mundur kapan saja. Yang diperoleh para penanda tangan adalah efek jaringan yang hanya dapat diberikan oleh kerangka yang dibangun khusus. Ini adalah koordinasi tanpa satu bentuk dominasi politik pun.

Menandatangani accord berarti menandatangani sebuah janji. Bahwa wilayah tersebut akan menampung pelajar muda lintas budaya. Bahwa wilayah tersebut akan menyumbangkan apa yang hanya bisa ia berikan secara unik. Bahwa wilayah tersebut akan menjaga dirinya pada standar yang lebih tinggi daripada regulasi yang berlaku. Bahwa wilayah tersebut akan melakukannya secara publik, transparan, di depan mata setiap warga yang dilayaninya. Tiga tanda tangan diperlukan dari setiap wilayah — Pemerintahan, Pendidikan, dan Inovasi. Tidak ada satu jabatan pun yang mengikat accord sendirian. Butuh tiga visioner untuk berkata ya. Tiga visioner, tiga wilayah, satu permulaan — inilah cara kerangka apa pun memasuki kehidupan melalui kepercayaan bersama para pemimpin yang bersedia menandatanganinya agar terwujud.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Belajar Melalui Simulasi`,
    content: {
      7: `Berlatih seribu kali sebelum menyentuh.`,
      33: `Tidak ada hal berkonsekuensi yang dipelajari pertama pada perangkat langsung. Setiap peserta berlatih dalam simulasi, berotasi lintas tiga wilayah, merayakan secara publik. Ini adalah penghormatan pada manusia muda yang kesalahan pertamanya tak boleh berharga nyawa.`,
      111: `Setiap disiplin yang layak dikuasai pernah dipelajari oleh seseorang sebelum ia dikenal. Atlantis Accords mengembalikan kebijaksanaan kuno ini ke pusat cara generasi muda dipersiapkan untuk membangun masa depan. Tidak ada hal berkonsekuensi yang dipelajari pertama pada perangkat langsung, pada manusia sungguhan, atau dalam kondisi yang tak bisa dibalikkan. Setiap peserta berlatih dalam simulasi hingga latihan menjadi kompetensi, dan kompetensi menjadi kesiapan. Model rotasi membawa setiap peserta melewati tiga wilayah pendiri, dan setiap rotasi berakhir dengan perayaan publik dan kooperatif yang terbuka untuk komunitas tuan rumah yang lebih luas. Ini adalah penghormatan pada manusia muda yang kesalahan pertamanya tak seharusnya berharga nyawa siapa pun.`,
      333: `Setiap disiplin yang layak dikuasai pernah dipelajari oleh seseorang sebelum ia dikenal. Para pengrajin ahli berlatih sebelum pertunjukan, pilot berlatih sebelum penerbangan, dokter berlatih sebelum operasi, dan anak-anak berlatih memahami dunia melalui permainan. Atlantis Accords mengembalikan kebijaksanaan kuno ini ke pusat cara generasi muda dipersiapkan untuk membangun masa depan. Tidak ada hal berkonsekuensi yang dipelajari pertama pada perangkat langsung, pada manusia sungguhan, atau dalam kondisi yang tak bisa dibalikkan. Setiap peserta berlatih dalam simulasi hingga latihan menjadi kompetensi, dan kompetensi menjadi kesiapan. Ini bukan kehati-hatian — ini adalah penghormatan pada manusia muda yang kesalahan pertamanya tak seharusnya berharga nyawa siapa pun.

Model rotasi accord membawa setiap peserta melewati tiga wilayah pendiri. Apa yang dipelajari di Cambodia disempurnakan di Honduras dan diselesaikan di Austin. Apa yang ditemukan di Austin dipertanyakan di Cambodia dan diintegrasikan di Honduras. Setiap peserta tinggal, belajar, dan dibimbing lintas budaya yang biasanya akan tetap jauh. Kurikulum pelatihan mengambil dari tradisi simulasi terdisiplin lintas banyak budaya — dari tradisi pendidikan strategis Sun Tzu, dari latihan-melalui-permainan Musashi, dari teori pembelajaran siklikal Ibn Khaldun, dari dialektika monastik Nalanda, dari simulator penerbangan sipil — disintesiskan untuk menghormati setiap tahap kognitif dan warisan budaya. Tidak ada satu tradisi pun yang mendominasi.

Setiap rotasi berakhir dengan perayaan publik dan kooperatif yang terbuka untuk komunitas tuan rumah yang lebih luas. Tetangga, keluarga, dan pengunjung yang penasaran berkumpul untuk menyaksikan apa yang telah dipelajari kelompok tersebut. Acara-acara ini membuat teknologi canggih menjadi dapat diakses dan dirayakan alih-alih ditakuti. Masyarakat yang tumbuh dengan memahami sistem kooperatif melalui permainan tidak mudah dimanipulasi oleh ketakutan tentang sistem itu. Ini adalah pencegahan melalui pendidikan, bukan pencegahan melalui kekuatan. Janji accord kepada setiap orang tua: anak Anda akan berlatih seribu kali dalam keamanan sebelum menyentuh apa pun yang dapat mencelakainya, dan komunitas akan menyaksikan pertumbuhan mereka di setiap langkahnya. Beginilah rupa penghormatan pada manusia muda ketika ia direkayasa ke dalam sebuah kerangka, dan inilah yang diserahkan kepemimpinan kepada generasi peserta berikutnya sebelum generasi itu harus menuntutnya.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Keamanan Terverifikasi Sebelum Kepercayaan Diberikan`,
    content: {
      7: `Keamanan dibuktikan dulu, baru kepercayaan diberikan.`,
      33: `Setiap fasilitas dan setiap rotasi berada dalam selubung pelindung dengan peringatan dini. Perangkat keras menolak penyenjataan. Rekam jejak bertahan menghadapi guncangan. Keamanan direkayasa mengelilingi peserta termuda setiap hari, bukan sekadar dijanjikan atau diasumsikan.`,
      111: `Sebelum kepercayaan diberikan, keamanan harus dibuktikan. Atlantis Accords menjadikan ini komitmen pendirinya. Setiap fasilitas accord, setiap rute rotasi, setiap tempat peserta muda tidur atau belajar berada dalam selubung pelindung terdokumentasi dengan kemampuan peringatan dini yang memberi komunitas waktu berjam-jam, bukan berhitung menit, untuk merespons setiap risiko yang kredibel. Setiap perangkat, setiap sensor, setiap sistem koordinasi terikat pada lapisan perangkat keras untuk menolak pengalihfungsian ke integrasi sistem senjata. Ini bukan kebijakan — ini adalah fisika. Accord dirancang untuk tetap terhormat menghadapi guncangan: ketidakstabilan politik, kontraksi pendanaan, serangan siber, atau gangguan perjalanan. Setiap skenario direncanakan, dan setiap rencana menempatkan martabat manusia sebagai batasan desain utamanya.`,
      333: `Sebelum kepercayaan diberikan, keamanan harus dibuktikan. Atlantis Accords menjadikan ini komitmen pendirinya. Setiap fasilitas accord, setiap rute rotasi, setiap tempat peserta muda tidur atau belajar berada dalam selubung pelindung terdokumentasi dengan kemampuan peringatan dini yang memberi komunitas waktu berjam-jam, bukan berhitung menit, untuk merespons setiap risiko yang kredibel. Teknologi yang digunakan untuk melindungi peserta adalah teknologi yang sama yang diajarkan accord untuk mereka bangun — sensor, koordinasi, keberlangsungan komunikasi, kecerdasan terdistribusi. Generasi muda belajar keamanan dari dalam ke luar, dalam bahasa mereka sendiri dan di wilayah mereka sendiri, bukan dengan diberi tahu bahwa mereka aman, tetapi dengan melihat bagaimana keamanan direkayasa di sekitar mereka setiap hari.

Accord membuat janji yang tak terpatahkan tentang apa yang tak boleh terjadi pada teknologinya. Setiap perangkat, setiap sensor, setiap sistem koordinasi terikat pada lapisan perangkat keras untuk menolak pengalihfungsian ke integrasi sistem senjata. Ini bukan bahasa kebijakan. Ini bukan aspirasi. Ini adalah ketidakmungkinan fisik, diberlakukan secara kriptografis, diverifikasi oleh setiap wilayah penanda tangan, dan dapat diperiksa oleh setiap warga. Alat-alat yang melindungi seorang anak di Phnom Penh tidak dapat dialihfungsikan untuk mencelakai anak di Austin. Alat-alat yang menghubungkan latihan swarm di Tegucigalpa tidak dapat dikonfigurasi ulang untuk menyasar manusia di mana pun. Inilah jawaban accord terhadap ketakutan penggunaan-ganda selama satu abad. Bukan kebijakan — fisika.

Accord dirancang untuk tetap terhormat menghadapi guncangan. Jika sebuah wilayah penanda tangan kehilangan stabilitas politik, para peserta ditampung oleh wilayah-wilayah yang tersisa. Jika pendanaan menyusut, tunjangan peserta dilindungi terlebih dahulu, sebelum administrasi dan infrastruktur. Jika catatan digital diserang, cadangan luring tetap ada. Jika perjalanan menjadi mustahil, substrat berlanjut secara virtual. Setiap skenario direncanakan, dan setiap rencana menempatkan martabat manusia sebagai batasan desain utamanya. Para pemimpin yang menandatangani accord ini menandatangani janji bahwa keamanan direkayasa, bukan diasumsikan. Yang mereka tawarkan kepada warganya bukan sekadar peluang, melainkan perlindungan yang dibangun pada standar yang layak diterima peserta termuda — perlindungan yang sama yang akan dituntut setiap pemimpin bagi anaknya sendiri yang melintasi perbatasan asing seorang diri.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Kompensasi, Kesejahteraan, dan Martabat Manusia`,
    content: {
      7: `Sebuah tunjangan, seorang mentor, sebuah rumah.`,
      33: `Setiap peserta menerima tunjangan hidup sejak hari pertama. Cinta, kehilangan, dan keamanan diperlakukan sebagai infrastruktur kelas satu. Keberhasilan diukur berdasarkan peserta paling rentan, bukan rata-rata. Martabat adalah substrat, bukan hiasan.`,
      111: `Atlantis Accords memperlakukan setiap peserta sebagai manusia utuh sejak hari pertama. Sebuah tunjangan diberikan sejak partisipasi dimulai, terindeks pada biaya hidup wilayah sehingga dampaknya menghormati martabat kerja setempat. Kesejahteraan diperlakukan sebagai infrastruktur kelas satu — bukan manfaat opsional, bukan sekadar tunjangan kesejahteraan, melainkan substrat tempat segala hal lain berdiri. Tiga domain fondasional didukung: Cinta, Kehilangan, dan Keamanan. Accord mengukur keberhasilan berdasarkan hasil dari peserta paling rentannya, bukan rata-rata. Tidak ada peserta yang akan dilupakan secara diam-diam agar rata-rata terlihat baik. Martabat sebagai substrat, bukan hiasan.`,
      333: `Atlantis Accords memperlakukan setiap peserta sebagai manusia utuh sejak hari pertama. Sebuah tunjangan diberikan sejak partisipasi dimulai, terindeks pada biaya hidup wilayah sehingga dampaknya menghormati martabat kerja setempat. Tunjangan tiba sebelum kewajiban keluarga menjadi keadaan darurat, dan sebelum martabat dikompromikan. Tunjangan ini memberi tanda kepada setiap orang muda bahwa waktunya berharga, kontribusinya diantisipasi, dan stabilitas keluarganya adalah bagian dari tanggung jawab accord. Ini bukan amal. Ini adalah pengakuan bahwa inovasi manusia biasa memerlukan keamanan manusia biasa terlebih dahulu. Sebuah pikiran tidak dapat berkembang selagi rumah tangganya terancam.

Kesejahteraan diperlakukan sebagai infrastruktur kelas satu — bukan manfaat opsional, bukan sekadar tunjangan kesejahteraan, melainkan substrat tempat segala hal lain berdiri. Accord menyebut tiga domain fondasional yang didukung untuk setiap peserta: Cinta, dalam arti keterhubungan, kelekatan, dan batasan yang sehat; Kehilangan, sebab setiap peserta akan mengalami dukacita dan harus ditemani, bukan dihindari; dan Keamanan, dalam arti bahwa setiap peserta tahu kepada siapa harus menelepon, di setiap wilayah, dalam bahasanya sendiri. Konseling individu, lingkaran kelompok, praktik somatik, dan praktik budaya atau spiritual yang dihormati sesuai tradisi peserta sendiri semuanya disediakan. Nol pemaksaan ideologi. Accord menyediakan ruang dengan hormat; ia tidak mendakwahkan sistem kepercayaan apa pun.

Accord mengukur keberhasilan berdasarkan hasil dari peserta paling rentannya, bukan rata-rata. Peserta pedesaan tanpa bandwidth tinggi dilayani. Peserta neurodivergen menerima akomodasi sebagai norma. Peserta penyandang disabilitas menemukan setiap fasilitas dapat diakses. Peserta beragam gender menerima hunian yang aman dan pemasangan mentor. Penutur bahasa non-asli menemukan setiap artefak dalam bahasanya. Peserta adat menemukan praktik budayanya dihormati dan pengetahuan tradisionalnya dilindungi. Para pemimpin yang menandatangani accord ini berjanji bahwa tidak ada peserta yang akan dilupakan secara diam-diam agar rata-rata terlihat baik. Inilah martabat sebagai substrat, bukan hiasan. Yang diukur adalah yang akan dihormati, dan yang dihormati di sini adalah manusia seutuhnya — pikiran, tubuh, dan jiwa bersama-sama, tanpa pengecualian apa pun.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Pendanaan dan Tata Kelola`,
    content: {
      7: `Warga mendanai generasi berikutnya secara langsung.`,
      33: `Warga biasa menyumbang jumlah bulanan yang kecil. Tanpa saluran bantuan, tanpa donatur asing, tanpa ikatan politik. Setiap dolar dapat dilacak. Setiap laporan keuangan diterbitkan, dalam bahasa setiap wilayah, setiap bulan, secara publik.`,
      111: `Atlantis Accords didanai oleh warga yang dilayaninya. Warga biasa menyumbang jumlah sukarela yang kecil setiap bulan — cukup sederhana sehingga tak ada orang dewasa yang tersingkir, cukup resonan sehingga totalnya menopang kerja accord pada skala yang bermakna. Ketika seorang warga mendanai generasi berikutnya secara langsung, warga itu meminta accord bertanggung jawab secara langsung. Accord ini sengaja independen dari lembaga multilateral yang membentuk abad lalu. Ini bukan pernyataan politik — ini adalah pilihan desain. Setiap dolar dicatat secara permanen dan dapat dilacak. Setiap kontribusi warga dapat diikuti dari sumbernya ke tunjangan ke inovasi. Transparansi yang jarang ditawarkan oleh institusi mana pun.`,
      333: `Atlantis Accords didanai oleh warga yang dilayaninya. Warga biasa dari wilayah-wilayah peserta menyumbang jumlah sukarela yang kecil setiap bulan — jumlah yang cukup sederhana sehingga tak ada orang dewasa di wilayah tuan rumah mana pun yang tersingkir dari partisipasi, cukup resonan sehingga totalnya menopang kerja accord pada skala yang bermakna. Desain ini disengaja. Ketika seorang warga mendanai pendidikan generasi berikutnya secara langsung, warga itu meminta accord bertanggung jawab secara langsung. Tidak ada saluran bantuan, tidak ada donatur asing, tidak ada ikatan politik yang menempel pada cek. Jiwa accord adalah warga yang menyumbang satu jumlah kecil setiap bulan, yang partisipasinya membuat keseluruhannya mungkin.

Accord ini sengaja independen dari lembaga-lembaga multilateral yang telah membentuk abad lalu — North Atlantic Treaty Organization, World Health Organization, United Nations, International Monetary Fund, World Bank, dan setiap saluran bantuan asing nasional. Ini bukan pernyataan politik tentang nilai lembaga-lembaga itu atau kontribusinya. Ini adalah pilihan desain. Ketergantungan pada satu titik mengkompromikan daya tahan lintas cakrawala lima ratus tahun. Sebuah kerangka yang dimaksudkan untuk melayani setiap wilayah tanpa memandang keberpihakan geopolitik tidak dapat terjerat dengan satu keberpihakan pun. Pemerintah nasional dapat menyumbang secara sukarela. Kontribusinya transparan. Tidak ada kontribusi yang membeli pengaruh tata kelola, dari sumber mana pun, kapan pun.

Setiap dolar dan setiap unit nilai yang masuk ke accord dicatat secara permanen, publik, dan dapat dilacak. Setiap kontribusi warga dapat diikuti dari sumbernya ke tunjangan yang menjadi wujudnya ke orang muda yang dilayaninya ke proyek inovasi yang muncul dari pekerjaan orang muda itu. Overhead administratif dibatasi. Hibah korporasi dan institusional diterima dan dibatasi. Laporan keuangan lengkap disampaikan dalam bahasa setiap wilayah penanda tangan setiap bulan. Para pemimpin yang menandatangani accord ini berjanji kepada warganya untuk transparansi yang jarang ditawarkan oleh institusi mana pun — transparansi yang akan tetap terbaca berabad-abad setelah setiap penanda tangan meninggalkan jabatannya. Inilah kepercayaan yang dituntut accord. Inilah kepercayaan yang diperoleh accord, satu kontribusi kecil yang dapat dilacak sekaligus, di depan mata setiap warga.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Pertukaran Lintas Budaya dan Kontribusi Global`,
    content: {
      7: `Setiap pelajar dalam bahasanya sendiri.`,
      33: `Setiap kegiatan tersedia dalam bahasa peserta. Kecerdasan Artifisial, Manusia, dan Bersama dipegang dalam ketegangan yang produktif — tidak ada siswa yang tunduk pada satu saja. Kurikulum dan hasil diterbitkan secara terbuka. Apa yang dipelajari satu wilayah, semua mewarisi.`,
      111: `Atlantis Accords mengembalikan pendidikan pada tujuannya yang paling dalam: pertukaran kebijaksanaan lintas batasan yang biasanya memisahkan. Setiap kegiatan tersedia dalam bahasa peserta sendiri, bahasa wilayah tuan rumah, dan catatan bersama yang kanonik. Bahasa bukan hiasan — bahasa adalah yurisdiksi, bahasa adalah martabat yang dapat dibaca. Kerangka pendidikan bertumpu pada trinitas kecerdasan: Artifisial mengusulkan, Manusia memutuskan, Shared Intent memvalidasi. Setiap siswa belajar memegang ketiganya dalam ketegangan yang produktif. Apa yang dipelajari accord, accord kembalikan. Kurikulum, hasil inovasi, penelitian kesejahteraan, dan keputusan tata kelola semuanya diterbitkan secara terbuka. Apa yang dipelajari satu wilayah, semua wilayah mewarisi.`,
      333: `Atlantis Accords mengembalikan pendidikan pada tujuannya yang paling dalam: pertukaran kebijaksanaan lintas batasan yang biasanya memisahkan. Setiap kegiatan accord tersedia dalam bahasa peserta sendiri, dalam bahasa resmi wilayah tuan rumah, dan dalam catatan bersama yang kanonik sehingga tidak ada peserta yang menjelajahi accord dalam bahasa yang tidak ia pilih. Bahasa bukan hiasan. Bahasa adalah yurisdiksi. Bahasa adalah martabat yang dapat dibaca. Ketika seorang muda dari desa Cambodia membaca catatan tunjangannya sendiri dalam bahasa Khmer, ketika seorang muda dari kota Honduras membacanya dalam bahasa Spanyol, ketika seorang muda dari lingkungan Austin membacanya dalam bahasa Inggris, ketiganya sedang dihormati secara setara oleh accord yang sama.

Kerangka pendidikan accord bertumpu pada trinitas kecerdasan yang dinampakkan Vision 2525. Kecerdasan Artifisial mengusulkan pola, opsi, dan kemungkinan lebih cepat dari yang bisa dilakukan manusia sendirian. Kecerdasan Manusia memutuskan tentang keamanan, etika, dan arah — pertanyaan yang seharusnya tidak dijawab oleh mesin. Shared Intent memvalidasi bahwa keputusan selaras dengan prinsip pendiri accord, memastikan tidak ada peserta yang diminta memilih antara keunggulan individual dan kebaikan bersama. Tidak ada siswa yang diajar tunduk pada satu kecerdasan pun. Setiap siswa belajar memegang ketiganya dalam ketegangan yang produktif. Beginilah cara generasi pemimpin berikutnya dipersiapkan untuk mengatur dengan bertanggung jawab dan bijaksana di dunia di mana tidak satu pun dari ketiga kecerdasan ini akan bertindak sendirian atau tanpa pengawasan.

Apa yang dipelajari accord, accord kembalikan. Kurikulum diterbitkan di bawah lisensi terbuka sehingga wilayah mana pun — penanda tangan atau bukan — dapat mengadaptasinya dengan bebas untuk budaya dan tradisi pedagogis setempat. Hasil inovasi diterbitkan. Penelitian kesejahteraan diterbitkan dalam bentuk agregat bagi para peneliti di mana pun. Keputusan tata kelola diterbitkan dengan alasannya secara lengkap. Keberhasilan accord diukur bukan hanya dari pesertanya sendiri tetapi juga dari jumlah inisiatif pendidikan, inovasi, dan budaya yang muncul di jejaknya, di wilayah-wilayah yang tidak pernah menandatangani pilot pendiri namun membangun di atas kebijaksanaan yang telah dibagikan secara terbuka. Apa yang dipelajari satu wilayah, semua wilayah lain mewarisi.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Pertumbuhan Jaringan yang Berkelanjutan`,
    content: {
      7: `Tak pernah lebih cepat dari kecepatan martabat.`,
      33: `Tiga wilayah pendiri menyelesaikan satu siklus pilot sebelum yang keempat bergabung. Catatan diangkurkan untuk bertahan lima abad. Setiap penanda tangan mempertahankan kedaulatan. Tidak ada yang direndahkan untuk memberi ruang bagi penanda tangan berikutnya untuk bergabung.`,
      111: `Atlantis Accords tidak akan tumbuh lebih cepat daripada kualitas yang dapat ia hormati. Tiga wilayah pendiri harus menyelesaikan siklus pilot penuh, dengan setiap peserta dihormati dan setiap prinsip diverifikasi, sebelum wilayah keempat bergabung. Ini adalah prinsip yang akhirnya menjadi disiplin yang bekerja. Cakrawala accord ini sengaja panjang — lima abad sejak hari pendirian. Catatannya diangkurkan sehingga warga yang membacanya seratus tahun dari sekarang dapat memercayai penalarannya. Setiap penanda tangan mempertahankan kedaulatan penuh, otoritas penuh, dan kebebasan penuh untuk mundur. Tidak ada penanda tangan yang dapat mengkompromikan prinsip pendiri — sebab prinsip-prinsip itu adalah janji accord kepada pesertanya lintas setiap generasi.`,
      333: `Atlantis Accords tidak akan tumbuh lebih cepat daripada kualitas yang dapat ia hormati. Setiap ekspansi adalah janji kepada para peserta yang sudah di dalamnya — bahwa standar pendiri accord tidak akan dilunturkan oleh kegembiraan skala. Tiga wilayah pendiri harus menyelesaikan siklus pilot penuh, dengan setiap peserta dihormati dan setiap prinsip diverifikasi, sebelum wilayah keempat bergabung. Ini bukan kehati-hatian yang disamarkan sebagai prinsip. Ini adalah prinsip yang akhirnya menjadi disiplin yang bekerja di setiap wilayah pendiri. Para pemimpin yang menandatangani pilot pendiri menjanjikan kepada penanda tangan berikutnya substrat, perlindungan, dan martabat yang sama yang diterima kohort pendiri. Tidak ada yang direndahkan untuk memberi ruang bagi yang berikutnya.

Cakrawala accord ini sengaja panjang. Ia dirancang untuk bertahan sekitar lima belas hingga dua puluh generasi manusia — lima abad sejak hari pendirian. Catatannya diangkurkan sehingga warga yang membacanya seratus tahun dari sekarang dapat memercayai penalarannya. Kerangka koordinatnya, peran otoritas manusianya, dan siklus tata kelola lintas generasinya semuanya dibangun untuk bertahan menghadapi transisi teknologi tunggal apa pun. Accord akan hidup lebih lama daripada setiap manusia yang menandatangani pilot pendirinya. Itulah janjinya kepada anak yang menandatangani perjanjian tunjangan pada tahun setelah ratifikasi, kepada cucu-cucu anak itu yang mungkin memerintah accord pada pertengahan abad, dan kepada setiap generasi yang mewarisi apa yang dibangun para pendiri sekarang.

Setiap penanda tangan mempertahankan kebebasan untuk mundur dengan pemberitahuan. Setiap penanda tangan mempertahankan kedaulatan penuh. Setiap penanda tangan mempertahankan otoritas atas warganya sendiri. Setiap penanda tangan mempertahankan hak untuk mengusulkan amendemen, mengajukan sengketa, dan membentuk evolusi accord bersama setiap penanda tangan lainnya. Yang tidak dapat dilakukan penanda tangan mana pun adalah mengkompromikan prinsip pendiri substrat — sebab prinsip-prinsip itu adalah janji accord kepada pesertanya, dan janji itu harus bertahan meski satu tanda tangan pergi. Para pemimpin yang menandatangani accord ini sekarang bergabung dengan sesuatu yang lebih besar daripada masa jabatan politik mana pun. Mereka menandatangani abad berikutnya accord ini, dan berabad-abad setelahnya, ke dalam cakrawala yang akan diwarisi dan diselesaikan oleh cucu-cucu mereka sendiri.`,
    },
  },
];
