import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_ID: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Di Mana Inovasi Dimulai`,
    content: {
      7: `Para pemimpin memulai yang belum pernah dimulai.`,
      33: `Tiga wilayah — Kamboja, Honduras, Austin — membuka sebuah janji yang dibangun bersama warga: menampung para pembelajar, melindungi mereka, dan menyerahkan alat-alat masa depan ke tangan mereka. Pemerintah, Pendidikan, Inovasi menandatangani sebagai pengampu; warga yang memegangnya. Satu permulaan.`,
      111: `Atlantis Accords adalah kesepakatan di antara warga dunia — sebuah janji yang dapat diciptakan dan dipegang oleh siapa pun, di mana pun, apa pun yang ditandatangani pemerintahnya atau diizinkan majikannya. Wilayah pendirinya, Kamboja, Honduras, dan Austin, Texas, dipilih karena satu kualitas langka: kesediaan untuk mempercayakan alat-alat masa depan kepada generasi muda selagi masih ada waktu untuk mengajari mereka. Pemerintah, pendidik, dan inovator menandatangani sebagai pengampu wilayah masing-masing — tiga tanda tangan visioner tiap wilayah, Pemerintah, Pendidikan, Inovasi — tetapi wargalah yang mendanai accord ini, menyaksikan kerjanya, dan memegangnya bertanggung jawab secara langsung. Tidak diperlukan izin pemerintah maupun restu majikan untuk menjadi bagian di dalamnya. Tiga wilayah, satu permulaan bersama.`,
      333: `Setiap peradaban dikenang dari apa yang dipilihnya untuk dimulai. Atlantis Accords adalah janji di antara warga dunia — siapa pun, di mana pun, dapat memulainya, apa pun yang ditandatangani pemerintahnya. Wilayah pendirinya, Kamboja, Honduras, dan Austin, Texas, tidak dipilih karena kekuatan ekonomi, kekuatan militer, atau prestise kelembagaan, melainkan karena kualitas yang lebih langka: kesediaan untuk mempercayakan alat-alat masa depan kepada generasi muda. Inilah makna kepemimpinan di abad mendatang — keberanian untuk menyerahkan kunci kepada generasi berikutnya selagi masih ada waktu untuk mengajari mereka cara mengemudikannya.

Accord ini diselenggarakan oleh eXeL, kekuatan pengorganisasi yang dibangun khusus untuk momen ini, berada di luar jalur-jalur koordinasi yang membentuk abad yang lalu — di luar struktur perjanjian diplomatik, birokrasi multilateral, dan keterikatan politik negara mana pun. eXeL adalah penyelenggara tepercaya yang mempertemukan para pemimpin visioner di sekitar satu kerangka kerja bersama, satu roda gerak (flywheel) bersama, dan satu cakrawala lima ratus tahun bersama. Setiap penanda tangan mempertahankan kedaulatan penuh, wewenang penuh atas warganya sendiri, dan kebebasan penuh untuk mengundurkan diri kapan pun. Yang diperoleh para penanda tangan — dan yang diperoleh setiap warga, dengan harga sebuah Seed, sepertujuh dari satu jam upah minimum setempat — adalah efek jaringan yang hanya dapat diberikan oleh kerangka kerja yang dibangun khusus untuk tujuan ini: koordinasi tanpa bentuk dominasi politik apa pun.

Menandatangani accord ini berarti menandatangani sebuah janji: bahwa wilayah tersebut akan menampung para pembelajar lintas budaya, menyumbangkan apa yang hanya bisa ditawarkannya, dan menegakkan standar yang lebih tinggi dari yang disyaratkan regulasi saat ini — secara publik, secara transparan, bertanggung jawab kepada warga yang mendanainya, menyaksikannya, dan memegangnya bertanggung jawab, tanpa memerlukan izin pemerintah atau restu majikan untuk menjadi bagian. Tiga tanda tangan diperlukan dari setiap wilayah — Pemerintah, Pendidikan, dan Inovasi — menandatangani sebagai pengampu, bukan pemilik. Dibutuhkan tiga visioner untuk berkata ya, dan warga untuk memegang apa yang mereka tandatangani. Tiga visioner, tiga wilayah, satu permulaan — begitulah sebuah kerangka kerja memasuki kehidupan, melalui kepercayaan para pemimpin yang bersedia menandatanganinya menjadi kenyataan.`,
      999: `Setiap peradaban dikenang dari apa yang dipilihnya untuk dimulai, dan Vision 2525 meminta para pendiri peradaban ini untuk memulainya dengan kerendahan hati, bukan penaklukan. Atlantis Accords adalah janji yang dibuat oleh para pemimpin yang bersedia memulai sesuatu yang belum pernah ada sebelumnya — sebuah fondasi bersama bagi inovasi manusia yang menjangkau setiap sudut dunia, menghormati setiap suara, dan bertahan lintas generasi yang diukur bukan dalam tahun, melainkan dalam abad. Para penanda tangan pendirinya di Kamboja, Honduras, dan Austin, Texas tidak dipilih karena kekuatan ekonomi, kekuatan militer, atau prestise kelembagaan. Mereka dipilih karena kualitas yang lebih langka: kesediaan untuk mempercayakan alat-alat masa depan kepada generasi muda, dan kesabaran untuk membiarkan cakrawala lima ratus tahun bertahan lebih lama daripada tepuk tangan pemerintahan mana pun. Inilah makna kepemimpinan di abad mendatang — keberanian untuk menyerahkan kunci kepada generasi berikutnya selagi masih ada waktu untuk mengajari mereka cara mengemudikannya.

Accord ini diselenggarakan oleh eXeL, kekuatan pengorganisasi yang dibangun khusus untuk momen ini. eXeL berada di luar jalur-jalur koordinasi yang membentuk abad yang lalu — di luar struktur perjanjian diplomatik, di luar birokrasi multilateral, di luar keterikatan politik negara mana pun. eXeL adalah penyelenggara tepercaya yang mempertemukan para pemimpin visioner di sekitar satu kerangka kerja bersama, satu roda gerak bersama, dan satu cakrawala lima ratus tahun bersama. Setiap penanda tangan mempertahankan kedaulatan penuh, wewenang penuh atas warganya sendiri, dan kebebasan penuh untuk mengundurkan diri kapan pun. Yang diperoleh para penanda tangan adalah efek jaringan yang hanya dapat diberikan oleh kerangka kerja yang dibangun khusus untuk tujuan ini. Setiap peserta memasuki kerangka kerja itu dengan cara yang sama-sama sederhana: melalui sebuah Seed, keanggotaan satu kali seharga sepertujuh dari satu jam upah minimum setempat, tidak dapat dipindahtangankan, dan tidak membawa klaim ekonomi apa pun. Sebuah Seed tidak membeli kepemilikan maupun janji imbalan — hanya keanggotaan, hak untuk berdiri di dalam kerangka kerja itu dan memulai. Inilah koordinasi tanpa bentuk dominasi politik apa pun, dibangun di atas permulaan yang cukup kecil untuk dijangkau siapa saja.

Karena kedaulatan dipertahankan, bukan diserahkan, accord ini dibangun demi Continuity Without Evasion (Kesinambungan Tanpa Pengelakan). Tidak ada pemerintah, bank, pendiri, atau model yang tak tergantikan yang boleh menyandera seluruh kerangka kerja demi kelangsungan hidupnya sendiri. Setiap yurisdiksi dilayani melalui adaptor sahnya masing-masing, default-deny hingga terbukti patuh, sehingga nilai hanya bergerak melalui jalur yang akan diakui sah oleh pengadilan di yurisdiksi tersebut. Jika regulator di satu wilayah mengeluarkan putusan yang merugikan, hanya jalur tunggal itu yang gagal secara tertutup — secara transparan, tanpa merugikan peserta mana pun di dalamnya — sementara setiap wilayah lain terus berjalan tanpa gangguan. Seluruh accord tidak pernah runtuh hanya karena satu pemerintah berubah pikiran. Inilah portabilitas yang direkayasa sebagai janji pendirian, bukan sebagai langkah darurat yang baru ditemukan setelah krisis terjadi.

Menandatangani accord ini berarti menandatangani sebuah janji. Bahwa wilayah tersebut akan menampung para pembelajar lintas budaya. Bahwa wilayah tersebut akan menyumbangkan apa yang hanya bisa ditawarkannya. Bahwa wilayah tersebut akan menegakkan standar yang lebih tinggi dari yang disyaratkan regulasi saat ini. Bahwa wilayah tersebut akan melakukannya secara publik, secara transparan, di hadapan setiap warga yang dilayaninya. Tiga tanda tangan diperlukan dari setiap wilayah — Pemerintah, Pendidikan, dan Inovasi. Tidak ada satu jabatan pun yang dapat mengikat accord ini sendirian. Dibutuhkan tiga visioner untuk berkata ya. Tanda tangan rangkap tiga ini adalah ungkapan pertama dari Human Authority: makna, uang, dan hukum tetap berada di tangan manusia pada lapisan berdaulat, sebuah lapisan yang tertutup secara permanen bagi mesin, betapa pun canggihnya mesin itu kelak. Measurement of Time, MoT, mulai mencatat sejak saat penandatanganan — menit-menit sungguhan dari kerja manusia yang sungguhan, dijaga terpisah dari perkiraan otomatis apa pun — dan setiap rilis berikutnya dari kerja accord ini dibangun agar dapat direkonstruksi melalui Replay, sehingga seorang warga yang lahir satu abad dari sekarang dapat menelusuri kembali bagaimana keputusan-keputusan pendirian hari ini dicapai.

Apa yang didirikan oleh pilot ini adalah pengukuran sebelum menjadi uang. Setiap inovasi yang memasuki kerangka kerja dinilai dengan Qualified Innovation Score, QIS — rata-rata dari Revenue (Pendapatan), Gross Profit (Laba Kotor), Operating Income (Laba Operasional), dan pengeluaran Effective R&D, dibagi empat. QIS bukanlah pembayaran dan bukan pula kepemilikan; ia adalah instrumen yang dengannya kohort pendiri belajar melihat kemajuannya sendiri sebelum imbalan apa pun ditentukan besarnya. Pertumbuhan QIS, setelah kualifikasi terpenuhi, menentukan besar kumpulan imbalan yang mengikutinya — tetapi pertumbuhan QIS itu sendiri tidak mencetak apa pun. Tiga wilayah, satu permulaan, dan satu disiplin bersama: buktikan skornya sebelum menyentuh kas.

Nilai yang diperoleh melalui kerja yang disaksikan memiliki namanya sendiri, 웃, dihitung sebagai satu jam dikalikan upah minimum setempat, diskalakan dengan sebuah Multiple (Pengali) yang diterapkan terhadap jam-jam yang dijalani. 웃 diterbitkan hanya untuk kerja yang disaksikan di bawah tugas yang lingkupnya jelas dan anggarannya disetujui; apa pun yang belum mencapai persetujuan itu masih berupa perencanaan, dan perencanaan semata tidak mencetak apa pun. Sebuah plafon penyelesaian sebesar 9.999 웃 per tahun melindungi setiap peserta dari konsentrasi yang tak terkendali, dengan kelebihan apa pun dibawa maju ke tahun berikutnya, bukan lenyap begitu saja. Di balik setiap 웃 berdiri ♡, Shared Intention (Niat Bersama), yang membawa alasan mengapa sebuah tugas disetujui sejak awal, dan ◬, akselerasi tersaksikan yang dihasilkan sebuah tugas terhadap garis dasar yang dibekukan — semata sebuah delta, tidak pernah dikelirukan sebagai metrik laba. Pilot ini ada untuk membuktikan bahwa ketiga glyph ini dapat bergerak bersama secara jujur, wilayah demi wilayah, sebelum kerangka kerja ini berkembang melampaui para pendirinya.

Ketika nilai sampai kepada seseorang, ia sampai melalui Livelihood Direct — 🏠 — jalur lokal berlisensi dan memenuhi syarat yang tidak pernah disimpan eXeL sebagai dananya sendiri. Klasifikasi selalu mendahului penyelesaian pembayaran, dan pengakuan atas sebuah kontribusi tidak pernah menjadi gerbang bagi tempat bermalam; hanya peran seseorang dalam tugas yang lingkupnya jelas yang menjadi gerbangnya. Pertumbuhan di luar pilot pun dijaga gerbangnya: setiap kubus dalam kerangka kerja ini bergerak dari Manual ke Semi-Otomatis ke Otonom hanya setelah melewati aturan 11,1 persen, satu bagian dari sembilan perbaikan yang terukur, diperoleh kubus demi kubus dan tidak pernah diklaim sekaligus secara menyeluruh — dan tidak pernah, dalam keadaan apa pun, atas lapisan berdaulat makna, uang, dan hukum. Begitulah tiga visioner per wilayah, tiga wilayah, dan satu permulaan menjadi janji lima ratus tahun: bukan dengan bergerak cepat, melainkan dengan membuktikan, di hadapan publik, bahwa setiap langkah memang berhak atas langkah berikutnya.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Belajar Melalui Simulasi`,
    content: {
      7: `Berlatih seribu kali sebelum menyentuh.`,
      33: `Tidak ada hal yang konsekuensinya besar dipelajari pertama kali di perangkat keras yang sungguhan. Setiap warga boleh berlatih dalam simulasi, berotasi lintas tiga wilayah, dan merayakannya — bentuk penghormatan bagi manusia muda yang kesalahan pertamanya tidak boleh pernah merenggut sebuah nyawa.`,
      111: `Setiap disiplin ilmu yang layak dikuasai pernah dipelajari oleh seseorang sebelum ia benar-benar dikenal. Atlantis Accords mengembalikan kebijaksanaan kuno ini ke pusat cara generasi muda — dan setiap warga yang bergabung — dipersiapkan untuk membangun masa depan. Tidak ada hal yang konsekuensinya besar dipelajari pertama kali di perangkat keras yang sungguhan, pada orang-orang sungguhan, atau dalam kondisi yang tak dapat dipulihkan; tidak diperlukan izin pemerintah maupun restu majikan. Setiap peserta berlatih dalam simulasi hingga latihan itu berubah menjadi kompetensi, lalu menjadi kesiapan. Model rotasi membawa setiap peserta melalui tiga wilayah pendiri, dan setiap rotasi berakhir dengan perayaan publik yang terbuka bagi komunitas tuan rumah. Inilah bentuk penghormatan bagi manusia muda yang kesalahan pertamanya tidak boleh pernah merenggut sebuah nyawa.`,
      333: `Setiap disiplin ilmu yang layak dikuasai pernah dipelajari oleh seseorang sebelum ia benar-benar dikenal. Para maestro berlatih sebelum tampil, pilot berlatih sebelum terbang, dokter berlatih sebelum menjalankan operasi, anak-anak belajar melalui permainan. Atlantis Accords mengembalikan kebijaksanaan kuno ini ke pusat cara generasi muda — dan setiap warga yang bergabung, tanpa memerlukan izin pemerintah maupun restu majikan — dipersiapkan untuk membangun masa depan. Tidak ada hal yang konsekuensinya besar dipelajari pertama kali di perangkat keras yang sungguhan, pada orang-orang sungguhan, atau dalam kondisi yang tak dapat dipulihkan. Setiap peserta berlatih dalam simulasi hingga latihan itu berubah menjadi kompetensi, lalu menjadi kesiapan. Ini bukan kehati-hatian belaka — ini adalah penghormatan bagi manusia muda yang kesalahan pertamanya tidak boleh pernah merenggut nyawa siapa pun.

Model rotasi accord ini membawa setiap peserta melalui tiga wilayah pendiri. Apa yang dipelajari di Kamboja diperhalus di Honduras dan disempurnakan di Austin. Apa yang ditemukan di Austin dipertanyakan di Kamboja dan diintegrasikan di Honduras. Setiap peserta hidup, belajar, dan dibimbing lintas budaya yang jika bukan karena accord ini akan tetap saling berjauhan. Kurikulum pelatihannya menimba dari tradisi-tradisi simulasi yang disiplin lintas berbagai budaya — dari tradisi pendidikan strategis Sun Tzu, dari praktik-melalui-permainan Musashi, dari teori pembelajaran siklikal Ibn Khaldun, dari dialektika biara Nalanda, dari simulator penerbangan sipil — disintesis untuk menghormati setiap tahap kognitif dan warisan budaya. Tidak ada satu tradisi pun yang mendominasi.

Setiap rotasi berakhir dengan perayaan publik yang terbuka bagi komunitas tuan rumah, tempat tetangga, keluarga, dan pengunjung menyaksikan apa yang telah dipelajari kohort tersebut. Acara-acara ini membuat teknologi canggih menjadi mudah dijangkau dan dirayakan, bukan ditakuti — masyarakat yang tumbuh memahami sistem-sistem kooperatif melalui permainan tidak mudah dimanipulasi oleh rasa takut terhadapnya. Inilah deterensi melalui pendidikan, bukan melalui kekuatan. Janji accord ini kepada setiap orang tua: anak Anda akan berlatih seribu kali dengan aman sebelum menyentuh apa pun yang dapat mencelakainya, disaksikan sedemikian rupa sehingga seorang warga — siapa pun, satu abad dari sekarang — dapat memverifikasi bahwa hal itu terjadi persis seperti yang tercatat. Inilah penghormatan bagi manusia muda yang direkayasa ke dalam sebuah kerangka kerja, dan inilah yang menjadi kewajiban kepemimpinan kepada warga berikutnya yang bergabung, sebelum warga itu harus menuntutnya sendiri.`,
      999: `Setiap disiplin ilmu yang layak dikuasai pernah dipelajari oleh seseorang sebelum ia benar-benar dikenal, dan setiap peradaban yang bertahan lama melakukannya karena ia melindungi ruang tempat pembelajaran itu dapat berlangsung dengan aman, sebelum ia dituntut untuk benar-benar berarti. Para maestro berlatih sebelum tampil, pilot berlatih sebelum terbang, dokter berlatih sebelum menjalankan operasi, dan anak-anak berlatih memahami dunia melalui permainan. Atlantis Accords mengembalikan kebijaksanaan kuno ini ke pusat cara generasi muda dipersiapkan untuk membangun masa depan, dan memberikan kebijaksanaan itu sebuah nama dan sebuah mekanisme: Replay. Tidak ada hal yang konsekuensinya besar dipelajari pertama kali di perangkat keras yang sungguhan, pada orang-orang sungguhan, atau dalam kondisi yang tak dapat dipulihkan. Setiap peserta berlatih dalam simulasi hingga latihan itu berubah menjadi kompetensi, lalu menjadi kesiapan, dan setiap jam dari latihan itu dicatat agar dapat direkonstruksi kelak, diperiksa kelak, dipercaya kelak. Ini bukan kehati-hatian belaka — ini adalah penghormatan bagi manusia muda yang kesalahan pertamanya tidak boleh pernah merenggut nyawa siapa pun, dan ini adalah penghormatan bagi catatan yang akan tetap ada jauh melampaui kesalahan itu sendiri.

Model rotasi accord ini membawa setiap peserta melalui tiga wilayah pendiri. Apa yang dipelajari di Kamboja diperhalus di Honduras dan disempurnakan di Austin. Apa yang ditemukan di Austin dipertanyakan di Kamboja dan diintegrasikan di Honduras. Setiap peserta hidup, belajar, dan dibimbing lintas budaya yang jika bukan karena accord ini akan tetap saling berjauhan, dan setiap rotasi dimulai dengan cara yang sama seperti dimulainya setiap lembaga manusia yang layak dipercaya: dengan sebuah Seed. Seed adalah keanggotaan satu kali, seharga sepertujuh dari satu jam upah minimum setempat, tidak dapat dipindahtangankan, dan tidak membawa klaim ekonomi apa pun. Ini bukan biaya untuk mengakses peluang. Ini adalah sebuah ambang batas — cukup kecil sehingga tidak ada peserta yang berkeinginan tersingkir karena harga, cukup disengaja sehingga keikutsertaan itu dipilih, bukan sekadar terseret masuk. Sejak ambang batas itu, setiap peserta menjadi bagian dari rotasi, dan rotasi itu bukan milik satu wilayah saja.

Kurikulum pelatihannya menimba dari tradisi-tradisi simulasi yang disiplin lintas berbagai budaya — dari tradisi pendidikan strategis Sun Tzu, dari praktik-melalui-permainan Musashi, dari teori pembelajaran siklikal Ibn Khaldun, dari dialektika biara Nalanda, dari simulator penerbangan sipil — disintesis untuk menghormati setiap tahap kognitif dan warisan budaya. Tidak ada satu tradisi pun yang mendominasi. Dan di dalam kurikulum ini, accord menarik sebuah garis yang dipelajari setiap peserta sejak awal dan tidak pernah dilupakan: simulasi adalah tempat Qualified Innovation Score dipahami, bukan tempat ia dibelanjakan. QIS adalah pengukuran, bukan pembayaran, dan QIS bukan pula kepemilikan — ia ada untuk menggambarkan seberapa baik sebuah proposal bernalar, bertahan, dan melayani wilayah yang diklaimnya untuk dilayani. Pertumbuhan QIS dapat menentukan besar kumpulan imbalan setelah kualifikasi sungguhan terpenuhi, tetapi ia tidak mencetak apa pun dengan sendirinya. Seorang peserta dapat menjalankan seratus simulasi sempurna dan memperoleh skor yang terus naik tanpa satu jam pun 웃 menyentuh buku besarnya, karena 웃 diterbitkan hanya untuk kerja yang disaksikan dan dilakukan di bawah tugas yang lingkupnya jelas dan anggarannya disetujui. Sebelum persetujuan itu, segalanya — betapa pun terampil, betapa pun menjanjikan — masih berupa perencanaan. Accord mengajarkan perbedaan ini sejak hari pertama, agar tidak ada anak muda yang mengelirukan latihan dengan imbalan, dan tidak ada anak muda yang pernah disesatkan tentang untuk apa simulasi itu ada.

Disiplin yang sama ini mengatur seberapa besar otonomi yang diizinkan dijalankan oleh sistem mana pun, manusia atau buatan, di dalam rotasi. Mode operasi accord ini bergerak berurutan — Manual, lalu Semi-Otomatis, lalu Otonom — dan tidak ada kubus yang naik mode sebelum melewati aturan perbaikan terukur 11,1 persen, satu bagian dari sembilan, dibuktikan terhadap garis dasar yang dibekukan dan disaksikan, bukan sekadar diklaim. Simulasi adalah tempat bukti itu dibangun. Sebuah alat memperoleh hak untuk bertindak dengan pengawasan yang lebih sedikit dengan cara yang sama seperti seorang peserta memperoleh hak atas tanggung jawab yang lebih besar: melalui perbaikan yang didemonstrasikan, dicatat, dan dapat direkonstruksi, kubus demi kubus, tidak pernah sekaligus, dan tidak pernah atas lapisan tempat makna, uang, dan hukum diputuskan. Lapisan itu hanya milik Human Authority, baik dalam simulasi maupun dalam operasi yang sungguhan, karena ruang latihan yang mengajarkan batas yang keliru akan mengajarkan pelajaran yang keliru secara permanen.

Setiap rotasi berakhir dengan perayaan publik yang kooperatif dan terbuka bagi komunitas tuan rumah. Tetangga, keluarga, dan pengunjung berkumpul untuk menyaksikan apa yang telah dipelajari kohort tersebut, dan yang mereka saksikan bukanlah demonstrasi kecepatan demi kecepatan itu sendiri, melainkan demonstrasi ◬ — delta terukur antara garis dasar yang dibekukan dan apa yang sungguh-sungguh dicapai oleh latihan yang disiplin, disajikan secara jujur, tidak pernah dibungkus sebagai metrik laba, tidak pernah disajikan lebih dari apa adanya. Acara-acara ini membuat teknologi canggih menjadi mudah dijangkau dan dirayakan, bukan ditakuti. Masyarakat yang tumbuh memahami sistem-sistem kooperatif melalui permainan tidak mudah dimanipulasi oleh rasa takut terhadap sistem-sistem itu. Inilah deterensi melalui pendidikan, bukan deterensi melalui kekuatan, dan ini berhasil karena komunitas tidak diminta untuk memercayai sebuah klaim — mereka diundang untuk menyaksikan Replay-nya sendiri.

Janji accord ini kepada setiap orang tua melampaui keselamatan hingga ke keabadian: anak Anda akan berlatih seribu kali sebelum menyentuh apa pun yang dapat mencelakainya, komunitas akan menyaksikan pertumbuhannya sepanjang proses itu, dan tak satu pun dari itu akan hilang ditelan waktu. Measurement of Time mencatat menit-menit sungguhan secara terpisah dari setiap buku besar lain yang disimpan accord ini, sehingga jam-jam latihan dan jam-jam yang disaksikan tidak pernah tertukar satu sama lain, dan sehingga riwayat perkembangan sejati seorang peserta — bukan ringkasan, bukan perkiraan, melainkan catatan yang dapat direkonstruksi itu sendiri — tetap tersedia bagi peserta tersebut selama ia ingin memeriksanya. Seorang orang tua di Phnom Penh, seorang mentor di Tegucigalpa, seorang auditor di Austin, atau seorang cucu yang membaca catatan itu satu abad dari sekarang, semuanya dapat mengakses Replay yang sama dan melihat kebenaran yang sama.

Begitulah rupa penghormatan bagi manusia muda ketika ia direkayasa ke dalam sebuah kerangka kerja, bukan sekadar dijanjikan olehnya, dan itulah yang diwariskan kepemimpinan kepada generasi peserta berikutnya sebelum generasi itu harus menuntutnya sendiri: sebuah ruang latihan yang cukup luas untuk gagal dengan aman, cukup jujur untuk mencatat dengan setia, dan cukup disiplin untuk menempatkan imbalan, otonomi, dan wewenang persis di tempat yang telah diperoleh melalui penguasaan — tidak pernah lebih maju darinya, dan tidak pernah tertinggal di belakangnya.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Keamanan Terverifikasi Sebelum Kepercayaan Diberikan`,
    content: {
      7: `Keamanan dibuktikan dulu, baru kepercayaan diberikan.`,
      33: `Setiap fasilitas dan rotasi berada di dalam selubung pelindung dengan sistem peringatan dini. Perangkat keras menolak persenjataan — dapat dibuktikan, bukan sekadar dijanjikan, dapat diperiksa oleh warga. Catatan bertahan menghadapi gejolak. Keselamatan direkayasa di sekeliling peserta termuda, setiap hari.`,
      111: `Sebelum kepercayaan diberikan, keselamatan harus dibuktikan — bukan kepada pemerintah, melainkan kepada warga mana pun yang memeriksanya. Atlantis Accords adalah kesepakatan di antara warga dunia; komitmen pendiriannya adalah ini: setiap fasilitas accord, setiap rute rotasi, setiap tempat seorang peserta muda tidur atau belajar berada di dalam selubung pelindung yang terdokumentasi dengan kemampuan peringatan dini yang memberi komunitas waktu berjam-jam, bukan bermenit-menit, untuk merespons risiko yang kredibel apa pun. Setiap perangkat, setiap sensor, setiap sistem koordinasi terikat pada lapisan perangkat keras untuk menolak dialihfungsikan menjadi bagian sistem persenjataan. Ini bukan kebijakan — ini adalah hukum fisika. Accord ini tetap terhormat menghadapi gejolak, karena setiap rencana menempatkan martabat manusia sebagai yang utama.`,
      333: `Sebelum kepercayaan diberikan, keselamatan harus dibuktikan — dibuktikan kepada warga, bukan sekadar diklaim. Atlantis Accords adalah kesepakatan di antara warga dunia: siapa pun, di mana pun, dapat membantu memegangnya, apa pun yang ditandatangani pemerintahnya. Setiap fasilitas accord, setiap rute rotasi, setiap tempat seorang peserta muda tidur atau belajar berada di dalam selubung pelindung yang terdokumentasi dengan kemampuan peringatan dini yang memberi komunitas waktu berjam-jam, bukan bermenit-menit, untuk merespons risiko yang kredibel apa pun. Teknologi yang melindungi mereka adalah teknologi yang sama yang diajarkan accord ini kepada mereka untuk dibangun. Generasi muda mempelajari keselamatan dari dalam ke luar, bukan dengan diberi tahu bahwa mereka aman, melainkan dengan melihatnya direkayasa di sekeliling mereka setiap hari, dan mengetahui bahwa warga mana pun dapat memverifikasi catatannya melalui Replay.

Accord ini membuat janji yang tak dapat dipatahkan tentang apa yang tidak boleh menjadi wujud dari teknologinya. Setiap perangkat, setiap sensor, setiap sistem koordinasi terikat pada lapisan perangkat keras untuk menolak dialihfungsikan menjadi bagian sistem persenjataan. Ini bukan bahasa kebijakan, bukan pula aspirasi. Ini adalah ketidakmungkinan fisik, ditegakkan secara kriptografis, diverifikasi oleh setiap wilayah penanda tangan, dan dapat diperiksa oleh setiap warga yang mendanainya. Alat-alat yang melindungi seorang anak di Phnom Penh tidak dapat dialihfungsikan untuk mencelakai seorang anak di Austin. Alat-alat yang menghubungkan latihan swarm di Tegucigalpa tidak dapat dikonfigurasi ulang untuk menyasar manusia di mana pun. Inilah jawaban accord ini atas satu abad ketakutan terhadap penggunaan-ganda (dual-use). Bukan kebijakan — hukum fisika.

Accord ini tetap terhormat menghadapi gejolak. Jika sebuah wilayah kehilangan stabilitas politiknya, para pesertanya ditopang oleh wilayah-wilayah lain yang tersisa. Jika pendanaan menyusut, tunjangan dilindungi terlebih dahulu — didanai bulanan oleh warga, bukan jalur bantuan asing, setiap dolar dapat dilacak. Jika catatan digital diserang, cadangan luring (offline) tetap bertahan. Jika perjalanan menjadi tidak mungkin, substratnya tetap berjalan secara virtual. Setiap rencana menempatkan martabat manusia — Human Authority atas makna, uang, dan hukum — sebagai batasan rancangan yang pertama. Para pemimpin yang menandatangani accord ini berjanji bahwa keselamatan itu direkayasa, bukan sekadar diasumsikan: perlindungan yang akan dituntut oleh pemimpin mana pun bagi anaknya sendiri, kini diperluas kepada setiap warga yang membantu memegang accord ini.`,
      999: `Sebelum kepercayaan diberikan, keselamatan harus dibuktikan — inilah komitmen pendirian dari Atlantis Accords, dan ia dibuktikan dengan cara yang sama seperti setiap klaim lain di dalam Vision 2525 dibuktikan: bukan dengan pernyataan, melainkan dengan bukti yang dapat diperiksa warga. Setiap fasilitas accord, setiap rute rotasi, setiap tempat seorang peserta muda tidur atau belajar berada di dalam selubung pelindung yang terdokumentasi dengan kemampuan peringatan dini yang memberi komunitas waktu berjam-jam, bukan bermenit-menit, untuk merespons risiko yang kredibel apa pun. Teknologi yang digunakan untuk melindungi para peserta adalah teknologi yang sama yang diajarkan accord ini kepada mereka untuk dibangun — sensor, koordinasi, ketahanan komunikasi, kecerdasan terdistribusi. Generasi muda mempelajari keselamatan dari dalam ke luar, dalam bahasa mereka sendiri dan di wilayah mereka sendiri, bukan dengan diberi tahu bahwa mereka aman, melainkan dengan menyaksikan, jam demi jam, bagaimana keselamatan direkayasa di sekeliling mereka setiap hari.

Penyaksian itu tidak digantungkan pada ingatan atau kepercayaan pada kata-kata seorang fasilitator. Measurement of Time mencatat menit-menit sungguhan dari setiap latihan, setiap rotasi, setiap simulasi respons — secara terpisah dari klaim kemajuan apa pun, secara terpisah dari cerita apa pun yang disampaikan hari itu. Replay membuat setiap rilis kurikulum pelatihan, setiap pembaruan keselamatan, setiap revisi perangkat keras sepenuhnya dapat direkonstruksi, sehingga seorang orang tua di Tegucigalpa atau seorang regulator di Phnom Penh dapat menelusuri mundur persis apa yang berubah, kapan ia berubah, dan mengapa ia berubah. Sebuah selubung pelindung yang tidak dapat di-Replay hanyalah sebuah janji. Sebuah selubung pelindung yang dapat di-Replay, menit demi menit yang tercatat, adalah sebuah bukti. Accord ini memilih bukti.

Accord ini membuat janji yang tak dapat dipatahkan tentang apa yang tidak boleh menjadi wujud dari teknologinya. Setiap perangkat, setiap sensor, setiap sistem koordinasi terikat pada lapisan perangkat keras untuk menolak dialihfungsikan menjadi bagian sistem persenjataan. Ini bukan bahasa kebijakan, bukan pula aspirasi. Ini adalah ketidakmungkinan fisik, ditegakkan secara kriptografis, diverifikasi oleh setiap wilayah penanda tangan, dan dapat diperiksa oleh setiap warga. Alat-alat yang melindungi seorang anak di Phnom Penh tidak dapat dialihfungsikan untuk mencelakai seorang anak di Austin. Alat-alat yang menghubungkan latihan swarm di Tegucigalpa tidak dapat dikonfigurasi ulang untuk menyasar manusia di mana pun. Inilah jawaban accord ini atas satu abad ketakutan terhadap penggunaan-ganda (dual-use). Bukan kebijakan — hukum fisika.

Keselamatan yang dibuktikan sekali bukanlah keselamatan yang bertahan sepanjang cakrawala lima ratus tahun. Accord ini menamai komitmen keduanya Continuity Without Evasion: portabilitas yang sah di seluruh yurisdiksi yang disentuh accord ini, tanpa satu pun pemerintah, bank, pendiri, atau model yang tak tergantikan berdiri di antara seorang peserta dan perlindungannya. Setiap yurisdiksi dilayani oleh adaptornya sendiri, fail-closed dan default-deny, sehingga putusan yang merugikan di satu wilayah mana pun membuat hanya jalur itu yang gagal secara tertutup — tidak pernah seluruh kerangka kerja, tidak pernah setiap wilayah, tidak pernah setiap peserta di mana-mana sekaligus. Keputusan pengadilan di satu wilayah penanda tangan tidak dapat mematikan selubung keselamatan seorang peserta di tempat lain. Inilah makna membangun sebuah sistem yang bertahan menghadapi gejolak biasa dari hukum, politik, dan perubahan kelembagaan, tanpa pernah meminta seorang peserta untuk melanggar hukum demi tetap terlindungi.

Setiap lapisan dari arsitektur pelindung ini pada akhirnya bertanggung jawab kepada Human Authority. Makna, uang, dan hukum tidak pernah didelegasikan kepada mesin — lapisan berdaulat yang memutuskan apa yang disyaratkan keselamatan, apa yang dianggap sebagai risiko kredibel, dan respons apa yang wajib diberikan sebuah komunitas kepada anggota termudanya, tetap tertutup bagi kecerdasan buatan, betapa pun canggihnya ia kelak. Sistem-sistem accord ini bergerak hanya melalui tiga mode operasi — Manual, Semi-Otomatis, Otonom — dan tidak ada sistem yang naik mode tanpa perbaikan terukur yang disaksikan sebesar setidaknya satu bagian dari sembilan, sebelas koma satu persen, terverifikasi, dapat direproduksi. Otonomi diperoleh, kubus demi kubus, fungsi demi fungsi, tidak pernah diberikan secara menyeluruh sekaligus, dan tidak pernah sekali pun diperluas atas pertanyaan-pertanyaan yang menentukan makna, uang, atau hukum. Sebuah sensor boleh belajar mendeteksi lebih cepat. Sebuah sistem koordinasi boleh belajar merutekan dengan lebih efisien. Tak satu pun dari keduanya pernah diizinkan untuk memutuskan, sendirian, apa yang harus dipercayakan sebuah komunitas kepada anak-anaknya.

Accord ini dirancang untuk tetap terhormat menghadapi gejolak, dan ia menamai gejolak itu terlebih dahulu, alih-alih baru menemukannya saat krisis terjadi. Jika sebuah wilayah penanda tangan kehilangan stabilitas politiknya, para pesertanya ditopang oleh wilayah-wilayah lain yang tersisa. Jika pendanaan menyusut, tunjangan peserta dilindungi terlebih dahulu, sebelum administrasi dan infrastruktur. Jika catatan digital diserang, cadangan luring tetap bertahan, tak terjangkau oleh kegagalan apa pun yang menimpa jaringan. Jika perjalanan menjadi tidak mungkin, substratnya tetap berjalan secara virtual, sehingga sebuah rotasi tidak berhenti hanya karena sebuah perbatasan ditutup. Setiap skenario direncanakan, dan setiap rencana menempatkan martabat manusia sebagai batasan rancangan yang pertama — bukan pertimbangan terakhir setelah anggaran dan citra diselesaikan.

Untuk memasuki sistem yang telah terbukti ini, dimulai dengan sebuah Seed — keanggotaan satu kali, seharga sepertujuh dari satu jam upah minimum setempat, tidak dapat dipindahtangankan, dan tidak membawa klaim ekonomi apa pun atas segala sesuatu yang dibangun accord ini setelahnya. Seed tidak membeli keselamatan; keselamatan direkayasa jauh sebelum Seed mana pun pernah ditanam. Yang dibeli oleh Seed adalah kedudukan — hak untuk melangkah masuk ke dalam kerangka kerja yang telah terbukti, telah diperiksa, telah terikat oleh perangkat keras yang tidak dapat dibalikkan melawan orang yang justru dilindunginya. Pemisahan ini disengaja. Sebuah janji keselamatan yang harus dibeli dengan bobot ekonomi yang sungguhan bukanlah janji keselamatan sama sekali, melainkan hanya produk keselamatan. Accord ini menjaga keduanya tetap terpisah secara mutlak, sehingga tidak ada keluarga yang pernah harus menimbang perlindungan anaknya melawan anggaran bulanan rumah tangganya.

Para pemimpin yang menandatangani accord ini menandatangani sebuah janji bahwa keselamatan itu direkayasa, bukan sekadar diasumsikan, dan dibuktikan, bukan sekadar diklaim. Yang mereka berikan kepada warganya bukan sekadar peluang, melainkan perlindungan yang dibangun pada standar yang layak diterima oleh peserta termuda — dicatat oleh Measurement of Time, dapat direkonstruksi melalui Replay, terikat pada lapisan perangkat keras terhadap setiap penyalahgunaan yang pernah dibayangkan oleh abad yang penuh ketakutan, dan bertanggung jawab, selalu dan hanya, kepada Human Authority. Inilah perlindungan yang sama yang akan dituntut oleh pemimpin mana pun bagi anaknya sendiri yang menyeberangi perbatasan asing seorang diri, kini diperluas kepada setiap anak yang akan pernah dilayani accord ini, di tiga wilayah pendirinya, Kamboja, Honduras, dan Austin, dan sepanjang lima abad yang diniatkan accord ini untuk menepati janji ini.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Kompensasi, Kesejahteraan, dan Martabat Manusia`,
    content: {
      7: `Sebuah tunjangan, seorang mentor, sebuah rumah.`,
      33: `Setiap warga menerima tunjangan sejak hari pertama — tanpa izin pemerintah, tanpa restu majikan. Cinta, kehilangan, dan keselamatan adalah infrastruktur. Keberhasilan diukur dari yang paling rentan. Martabat adalah substrat, bukan sekadar hiasan.`,
      111: `Atlantis Accords memperlakukan setiap peserta sebagai manusia seutuhnya sejak hari pertama — seorang warga yang bergabung karena haknya, bukan karena dekret pemerintah atau izin majikan. Tunjangan diberikan sejak saat keikutsertaan dimulai, disesuaikan dengan biaya hidup di wilayah tersebut, dan setiap jam yang disaksikan menghasilkan 웃, dibayarkan kepada orangnya melalui Livelihood Direct, tidak pernah melalui buku besar majikan. Kesejahteraan diperlakukan sebagai infrastruktur kelas utama — bukan tunjangan tambahan, melainkan substrat tempat segala sesuatu berpijak. Tiga ranah didukung: Cinta, Kehilangan, dan Keselamatan. Accord ini mengukur keberhasilan dari pesertanya yang paling rentan, bukan dari rata-rata. Tidak ada seorang pun yang dilupakan demi membuat rata-rata terlihat baik. Martabat sebagai substrat, bukan sekadar hiasan.`,
      333: `Atlantis Accords memperlakukan setiap peserta sebagai manusia seutuhnya sejak hari pertama — seorang warga yang menjadi bagiannya karena haknya, tanpa memerlukan izin pemerintah maupun restu majikan. Tunjangan diberikan sejak saat keikutsertaan dimulai, disesuaikan dengan biaya hidup di wilayah tersebut, tiba sebelum kewajiban keluarga berubah menjadi keadaan darurat. Ini bukan amal. Ini adalah pengakuan bahwa inovasi manusia yang wajar membutuhkan rasa aman manusiawi terlebih dahulu — sebuah pikiran tidak dapat berkembang selama rumah tangganya berada dalam ancaman.

Apa yang diperoleh di luar tunjangan diperoleh sebagaimana seorang warga memperolehnya: melalui Seed, seharga sepertujuh dari satu jam upah minimum setempat, dan melalui 웃, dibayarkan hanya untuk jam-jam yang disaksikan. QIS mengukur janji tetapi tidak mencetak apa pun — pengukuran, bukan pembayaran. Setiap pembayaran sampai kepada peserta melalui Livelihood Direct, jalur lokal berlisensi yang tidak pernah disimpan accord ini sendiri, dibangun demi Continuity Without Evasion.

Kesejahteraan diperlakukan sebagai infrastruktur kelas utama — bukan tunjangan tambahan, melainkan substrat tempat segala sesuatu berpijak. Accord ini menamai tiga ranah yang didukung bagi setiap peserta: Cinta, dalam arti keterhubungan dan batasan yang sehat; Kehilangan, karena duka harus dijalani bersama, bukan dihindari; dan Keselamatan, mengetahui siapa yang harus dihubungi, di setiap wilayah, dalam bahasa sendiri. Konseling, lingkaran kelompok, dan praktik budaya atau spiritual yang dihormati sesuai tradisi masing-masing disediakan. Nol ideologi paksaan; Human Authority, bukan mesin, yang memutuskan perawatan apa yang dibutuhkan seorang warga.

Accord ini mengukur keberhasilan dari pesertanya yang paling rentan, bukan dari rata-rata. Warga pedesaan tanpa bandwidth tinggi tetap dilayani. Peserta neurodivergen menerima akomodasi sebagai hal yang lumrah. Peserta penyandang disabilitas menemukan setiap fasilitas dapat diakses. Peserta dengan keberagaman gender menerima tempat tinggal yang aman dan pendampingan mentor. Penutur bahasa non-asli menemukan setiap artefak dalam bahasa mereka. Peserta masyarakat adat menemukan praktik budaya mereka dihormati dan pengetahuan tradisional mereka dilindungi. Para pemimpin yang menandatangani accord ini berjanji bahwa tidak ada warga yang akan dilupakan demi membuat rata-rata terlihat baik. Inilah martabat sebagai substrat, bukan sekadar hiasan. Apa yang diukur adalah apa yang akan dihormati, dan yang dihormati di sini adalah manusia seutuhnya — pikiran, tubuh, dan jiwa, dipegang oleh sesama warga, tanpa terkecuali.`,
      999: `Atlantis Accords memperlakukan setiap peserta sebagai manusia seutuhnya sejak hari pertama, dibangun ke dalam mekanisme, bukan sekadar ke dalam kata-kata. Tunjangan diberikan sejak saat keikutsertaan dimulai, disesuaikan dengan biaya hidup di wilayah tersebut, sehingga dampaknya menghormati martabat kerja setempat. Tunjangan itu tiba sebelum kewajiban keluarga berubah menjadi keadaan darurat, dan sebelum martabat terkompromikan. Ia menandakan kepada setiap anak muda bahwa waktu mereka berharga, kontribusi mereka dinantikan, dan stabilitas keluarga mereka adalah bagian dari tanggung jawab accord ini. Ini bukan amal. Ini adalah pengakuan bahwa inovasi manusia yang wajar membutuhkan rasa aman manusiawi terlebih dahulu. Sebuah pikiran tidak dapat berkembang selama rumah tangganya berada dalam ancaman. Keikutsertaan itu sendiri membawa ambang batas yang kecil dan disengaja: Seed, keanggotaan satu kali seharga sepertujuh dari satu jam upah minimum setempat, tidak dapat dipindahtangankan dan tidak membawa klaim ekonominya sendiri. Seed hanya menyatakan bahwa seseorang telah bergabung; ia tidak membayar mereka maupun menjanjikan apa pun kepada mereka selain pintu yang dibukanya.

Apa yang diperoleh setelah pintu itu terbuka diatur dengan ketelitian yang sama seperti yang dibawa accord ini pada setiap janji lainnya. 웃, ukuran Human Intelligence dari accord ini, dihitung dengan sederhana — satu jam pada upah minimum setempat, dikalikan Multiple yang mencerminkan tingkat kesulitan dan nilai tugas tersebut, dikalikan jam-jam yang sungguh-sungguh dikerjakan. Tetapi 웃 diterbitkan hanya untuk kerja yang disaksikan dan dilakukan di bawah tugas yang lingkupnya jelas dan anggarannya disetujui. Sebelum persetujuan itu ada, apa yang dilakukan seorang peserta adalah perencanaan, bukan penghasilan — sebuah perbedaan yang dipegang teguh oleh accord ini karena ia melindungi baik kas maupun peserta dari janji-janji yang dibuat lebih cepat daripada nilai yang dapat diverifikasi. Measurement of Time, MoT, mencatat menit-menit sungguhan yang dikerjakan secara terpisah dari perhitungan kompensasi apa pun, sehingga waktu tetap menjadi fakta yang jujur dan dapat diaudit, terlepas dari pembayaran. Tidak ada jam kerja peserta mana pun yang digelembungkan, dan tidak ada jam kerja peserta mana pun yang lenyap. Sebuah plafon penyelesaian sebesar 9.999 웃 per tahun berlaku bagi setiap peserta, dengan kelebihan apa pun dibawa maju ke tahun berikutnya, bukan lenyap begitu saja, sehingga kontribusi yang luar biasa diakui lintas tahun, bukan dibatasi hingga tak terlihat dalam satu tahun saja.

Kompensasi dengan sengaja dijaga tetap terpisah dari pengukuran inovasi. Qualified Innovation Score, QIS, merata-ratakan Revenue, Gross Profit, Operating Income, dan pengeluaran Effective R&D untuk menggambarkan seberapa besar inovasi itu sungguh-sungguh tumbuh. Pertumbuhannya dari waktu ke waktu dapat menentukan besar kumpulan imbalan setelah kualifikasi terpenuhi, tetapi QIS itu sendiri tidak mencetak 웃 dan tidak menyelesaikan pembayaran apa pun secara langsung — ia adalah pengukuran, bukan pembayaran, dan tidak pernah dikelirukan sebagai kepemilikan atas apa yang dibangun. Pemisahan ini penting karena ia menjaga kejujuran tunjangan dan upah: seorang peserta dibayar untuk jam-jam kerja sungguhan yang disaksikan, bukan untuk sebuah skor yang bisa direkayasa, digelembungkan, atau diperdebatkan. ♡, Shared Intention, membawa alasan di balik setiap tugas yang diambil seorang peserta; ◬, akselerasi tersaksikan yang dihasilkan sebuah tugas terhadap garis dasar yang dibekukan, dicatat semata sebagai sebuah delta, tidak pernah dibungkus sebagai metrik laba yang melekat pada kerja siapa pun. Kompensasi tetap menjadi apa adanya: sebuah upah yang jujur untuk waktu yang jujur dan disaksikan.

Nilai tidak berhenti pada perhitungan — ia juga harus sampai kepada peserta sebagai manusia yang hidup, dan di sinilah 🏠, Livelihood Direct, menjalankan tugasnya. Setiap unit nilai yang diperoleh seorang peserta sampai kepadanya melalui jalur lokal berlisensi dan memenuhi syarat — bank, operator uang seluler, koperasi yang sudah dipercaya dan diatur di wilayah tersebut — tidak pernah melalui dana yang disimpan atau dikendalikan accord ini sendiri. Klasifikasi status seorang peserta selalu mendahului penyelesaian pembayaran apa pun; tidak ada yang dibayarkan sebelum dipahami dengan tepat siapa yang dibayar dan untuk apa. Dan pengakuan atas bakat, betapa pun dirayakan, tidak menjadi gerbang untuk mengakses tempat tidur, makanan, atau tempat dalam kohort — hanya peran sungguhan seorang peserta yang menjadi gerbangnya. Ini adalah penolakan yang disengaja untuk membiarkan prestise menggantikan penyediaan kebutuhan. Seorang kontributor yang cemerlang dan seorang yang pendiam tidur di bawah atap yang sama-sama terlindungi, dengan syarat yang sama, karena komitmen martabat accord ini bukanlah hadiah yang diberikan untuk keunggulan — melainkan sebuah lantai dasar bagi setiap orang.

Kesejahteraan diperlakukan sebagai infrastruktur kelas utama — bukan manfaat opsional, bukan tunjangan kebugaran belaka, melainkan substrat tempat segala sesuatu yang lain berpijak. Accord ini menamai tiga ranah dasar yang didukung bagi setiap peserta: Cinta, dalam arti keterhubungan, keterikatan, dan batasan yang sehat; Kehilangan, karena setiap peserta akan mengalami duka dan harus dijalani bersama, bukan dihindari; dan Keselamatan, dalam arti bahwa setiap peserta mengetahui siapa yang harus dihubungi, di setiap wilayah, dalam bahasa mereka sendiri. Konseling perorangan, lingkaran kelompok, praktik somatik, dan praktik budaya atau spiritual yang dihormati sesuai tradisi peserta sendiri, semuanya disediakan. Nol ideologi paksaan. Accord ini menjaga ruang itu dengan penghormatan; ia tidak menyebarkan sistem kepercayaan apa pun. Human Authority mengatur setiap keputusan ini — makna, uang, dan hukum tetap tertutup bagi penentuan mesin, betapa pun canggihnya pencocokan pola yang membantu manusia yang memutuskan.

Accord ini mengukur keberhasilan dari hasil bagi pesertanya yang paling rentan, bukan dari rata-rata. Peserta pedesaan tanpa bandwidth tinggi tetap dilayani. Peserta neurodivergen menerima akomodasi sebagai hal yang lumrah. Peserta penyandang disabilitas menemukan setiap fasilitas dapat diakses. Peserta dengan keberagaman gender menerima tempat tinggal yang aman dan pendampingan mentor. Penutur bahasa non-asli menemukan setiap artefak dalam bahasa mereka. Peserta masyarakat adat menemukan praktik budaya mereka dihormati dan pengetahuan tradisional mereka dilindungi. Para pemimpin yang menandatangani accord ini berjanji bahwa tidak ada peserta yang akan diam-diam dilupakan demi membuat rata-rata terlihat baik.

Setiap jalur pembayaran yang diuraikan di sini — Seed, tunjangan, 웃 yang diperoleh dari kerja yang disaksikan, jalur Livelihood Direct yang menyampaikannya — dirancang demi Continuity Without Evasion. Tidak ada satu bank, pemerintah, atau operator lokal pun yang tak tergantikan bagi kompensasi peserta mana pun; jika satu jalur berlisensi di satu yurisdiksi ditutup oleh putusan yang merugikan, hanya jalur itu yang gagal, tidak pernah seluruh sistem, dan tidak pernah klaim peserta atas apa yang menjadi haknya. Inilah martabat sebagai substrat, bukan sekadar hiasan. Apa yang diukur adalah apa yang akan dihormati, dan yang dihormati di sini adalah manusia seutuhnya — pikiran, tubuh, dan jiwa bersama-sama, dibayar dengan jujur, dilindungi sepenuhnya, dan tidak dilupakan oleh pembukuan mana pun, tanpa terkecuali sama sekali.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Pendanaan dan Tata Kelola`,
    content: {
      7: `Warga mendanai generasi berikutnya secara langsung.`,
      33: `Atlantis Accords adalah kesepakatan di antara warga — siapa pun dapat mendanainya dan memegangnya. Tanpa jalur bantuan asing, tanpa donatur asing, tanpa syarat politik apa pun. Setiap dolar dapat dilacak, pembukuan diterbitkan setiap bulan, dalam setiap bahasa.`,
      111: `Atlantis Accords adalah kesepakatan di antara warga dunia — siapa pun, di mana pun, dapat membantu menciptakannya dan memegangnya, apa pun yang ditandatangani pemerintahnya atau siapa pun yang mempekerjakannya. Pemerintah, pendidik, dan inovator menandatangani sebagai pengampu wilayah masing-masing; wargalah yang mendanai, menyaksikan, dan memegang accord ini bertanggung jawab secara langsung, masing-masing menyumbangkan jumlah kecil secara sukarela setiap bulan, cukup sederhana sehingga tidak ada orang dewasa yang tersingkir karena harga. Tidak ada jalur bantuan asing, tidak ada donatur asing, tidak ada syarat politik yang melekat. Accord ini berdiri independen dari lembaga-lembaga multilateral yang membentuk abad yang lalu — bukan sebuah pernyataan politik, melainkan sebuah pilihan rancangan. Setiap dolar dapat dilacak; setiap pembukuan diterbitkan setiap bulan, dalam setiap bahasa.`,
      333: `Atlantis Accords adalah kesepakatan di antara warga dunia — siapa pun, di mana pun, dapat membantu menciptakannya dan memegangnya, apa pun yang ditandatangani pemerintahnya atau siapa pun yang mempekerjakannya. Ia didanai oleh warga yang dilayaninya: penduduk wilayah-wilayah yang berpartisipasi menyumbangkan jumlah kecil secara sukarela setiap bulan, cukup sederhana sehingga tidak ada orang dewasa yang tersingkir karena harga, cukup berarti sehingga totalnya mampu menopang kerja accord ini dalam skala besar. Ketika seorang warga mendanai generasi berikutnya secara langsung, warga itu memegang accord ini bertanggung jawab secara langsung pula. Tidak ada jalur bantuan asing, tidak ada donatur asing, tidak ada syarat politik yang melekat. Jiwa accord ini adalah warga yang menyumbangkan satu jumlah kecil setiap bulan, yang partisipasinya membuat semua ini mungkin.

Pemerintah, Pendidikan, dan Inovasi menandatangani sebagai pengampu wilayah masing-masing — tiga tanda tangan visioner yang mengikat sebuah wilayah untuk menampung, melindungi, dan mengajar — tetapi kepengampuan bukanlah kepemilikan. Accord ini independen dari lembaga-lembaga multilateral yang telah membentuk abad yang lalu — Organisasi Perjanjian Atlantik Utara (NATO), Organisasi Kesehatan Dunia (WHO), Perserikatan Bangsa-Bangsa, Dana Moneter Internasional, Bank Dunia, dan setiap jalur bantuan asing nasional mana pun. Ini adalah pilihan rancangan, bukan pernyataan politik: sebuah kerangka kerja yang melayani setiap wilayah tanpa memandang keberpihakan geopolitik tidak boleh terikat pada satu keberpihakan mana pun. Pemerintah nasional boleh menyumbang secara sukarela. Sumbangan bersifat transparan. Tidak ada sumbangan yang membeli pengaruh dalam tata kelola, dari sumber mana pun, kapan pun.

Setiap dolar dan setiap unit nilai yang masuk ke dalam accord ini dicatat secara permanen, secara publik, dan secara dapat dilacak — dapat direkonstruksi melalui Replay, sehingga seorang warga satu abad dari sekarang dapat memverifikasi rantainya utuh tanpa putus. Nilai sampai kepada seorang peserta melalui jam-jam 웃 yang disaksikan dan jalur lokal berlisensi, tidak pernah melalui dana yang disimpan accord ini sendiri; QIS mengukur dengan jujur, ia tidak pernah membayar. Biaya administrasi dibatasi, hadiah korporat pun dibatasi bersamanya. Pembukuan lengkap disampaikan dalam bahasa setiap wilayah penanda tangan setiap bulan. Para pemimpin yang menandatangani accord ini berjanji akan transparansi yang jarang ditawarkan lembaga mana pun. Inilah kepercayaan yang dituntut accord ini — diperoleh satu sumbangan kecil yang dapat dilacak pada satu waktu, di hadapan setiap warga.`,
      999: `Atlantis Accords sendiri didanai oleh warga yang dilayaninya, dan satu fakta ini membentuk segala sesuatu yang mengalir darinya — setiap jalur, setiap buku besar, setiap gerbang yang harus dilewati seorang anak muda agar dilihat. Penduduk biasa dari wilayah-wilayah yang berpartisipasi menyumbangkan jumlah kecil secara sukarela setiap bulan, jumlah yang cukup sederhana sehingga tidak ada orang dewasa di wilayah tuan rumah mana pun yang tersingkir dari partisipasi karena harga, cukup berarti sehingga totalnya menopang kerja accord ini dalam skala yang bermakna. Rancangan ini disengaja, dan ia bukan sekadar kebetulan dari misinya — ia adalah bukti dari misi itu sendiri. Ketika seorang warga mendanai pendidikan generasi berikutnya secara langsung, warga itu memegang accord ini bertanggung jawab secara langsung pula, dalam napas yang sama, tanpa perantara yang mungkin melunakkan pembukuan atau menunda perhitungannya. Tidak ada jalur bantuan asing, tidak ada donatur asing, tidak ada syarat politik yang melekat pada cek sumbangan itu. Jiwa accord ini adalah warga yang menyumbangkan satu jumlah kecil setiap bulan, yang partisipasinya membuat semua ini mungkin, dan yang partisipasinya yang berkelanjutan adalah satu-satunya mosi kepercayaan yang pada akhirnya berarti sepanjang lima ratus tahun.

Accord ini dengan sengaja independen dari lembaga-lembaga multilateral yang telah membentuk abad yang lalu — Organisasi Perjanjian Atlantik Utara (NATO), Organisasi Kesehatan Dunia (WHO), Perserikatan Bangsa-Bangsa, Dana Moneter Internasional, Bank Dunia, dan setiap jalur bantuan asing nasional mana pun. Ini bukan pernyataan politik tentang nilai lembaga-lembaga tersebut atau kontribusinya. Ini adalah pilihan rancangan, dan ia adalah pilihan rancangan yang sama yang mengatur setiap jalur teknis di balik accord ini sendiri: Continuity Without Evasion. Portabilitas yang sah adalah aturannya — tidak ada satu pemerintah, bank, pendiri, atau model yang tak tergantikan boleh berada di bawah seluruh struktur ini, karena cakrawala lima ratus tahun tidak dapat dipertaruhkan pada keabadian satu pelaku mana pun. Setiap yurisdiksi membawa adaptornya sendiri, fail-closed dan default-deny, sehingga putusan yang merugikan di satu negara membuat hanya jalur itu saja yang gagal secara tertutup — ia tidak pernah meruntuhkan rekening sebuah keluarga di wilayah yang terpisah samudra. Pemerintah nasional boleh menyumbang secara sukarela. Sumbangan bersifat transparan. Tidak ada sumbangan yang membeli pengaruh dalam tata kelola, dari sumber mana pun, kapan pun — bukan dari pemerintah, bukan dari korporasi, bukan pula dari para pendiri kerangka kerja itu sendiri.

Human Authority adalah pilar penopang kedua di balik rancangan pendanaan ini. Makna, uang, dan hukum tetap menjadi urusan manusia, diputuskan oleh manusia di hadapan manusia lainnya; lapisan berdaulat tempat tujuan accord ini ditetapkan dan dananya diatur tetap tertutup bagi mesin, betapa pun cakapnya mesin itu kelak dalam tugas-tugas di bawahnya. Measurement of Time mencatat menit-menit sungguhan yang dikerjakan secara terpisah dari klaim apa pun tentang nilainya, sehingga tidak seorang pun — manusia atau buatan — dapat diam-diam menggelembungkan catatan itu. Replay berdiri di belakang setiap catatan itu, membuat setiap rilis yang pernah diterbitkan accord ini sendiri dapat direkonstruksi dari asal-usulnya, selamanya terbuka untuk digugat, selamanya terbuka untuk dikoreksi. Seorang warga yang menyumbangkan jumlah kecil hari ini mempercayai bahwa lima puluh tahun lagi, dua ratus tahun lagi, seseorang masih dapat menelusuri rantai itu kembali ke buku besar bulan ini dan menemukannya persis seperti apa adanya.

Untuk memasuki sistem kepercayaan ini, dimulai dengan sebuah Seed — keanggotaan satu kali, seharga sepertujuh dari satu jam upah minimum setempat, tidak dapat dipindahtangankan dan tidak membawa klaim ekonomi apa pun. Seed tidak membeli saham, tidak membeli suara yang tertimbang kekayaan, tidak membeli kedudukan istimewa dalam pembukuan yang mengikutinya. Ia hanya membeli keanggotaan, dengan harga yang cukup rendah sehingga seorang anak muda di mana pun accord ini beroperasi mampu memulainya. Segala sesuatu yang diperoleh seorang anggota setelah titik itu adalah hasil kerja, tidak pernah dibeli, dan perbedaan ini adalah seluruh arsitektur moral accord ini dalam bentuk mininya.

Nilai yang memang mengalir kepada seseorang mengalir melalui 🏠 Livelihood Direct — jalur lokal berlisensi dan memenuhi syarat yang membawa pembayaran itu kepada orangnya, tidak pernah ke dalam dana yang disimpan atau dikendalikan kerangka kerja ini sendiri. Klasifikasi selalu mendahului penyelesaian pembayaran; tempat tidur, tunjangan, tempat di tahap pelatihan berikutnya digerbangi oleh peran dan kesiapan, tidak pernah oleh pengakuan semata, karena pengakuan itu murah dan penghidupan tidak. Inilah rantai yang sesungguhnya dilalui sumbangan bulanan seorang warga: dari rekening warga itu, melalui jalur yang diaudit, ke dalam tunjangan yang diterima seorang anak muda, ke dalam proyek inovasi yang menjadi wujud kerja anak muda itu, dan kembali keluar lagi sebagai catatan publik yang dapat dibaca warga mana pun.

Berapa nilai kerja itu diukur, bukan diasumsikan. Qualified Innovation Score merata-ratakan kesiapan, potensi pertumbuhan, dampak hasil, dan kesiapan eksekusi menjadi satu angka, dan pertumbuhan skor itu menentukan besar kumpulan imbalan hanya setelah kualifikasi terpenuhi — QIS itu sendiri tidak mencetak apa pun dan tidak menyelesaikan pembayaran apa pun; ia adalah pengukuran, bukan pembayaran, dan pengukuran di sini tidak pernah dikelirukan sebagai kepemilikan. Pembayaran untuk kerja manusia justru datang sebagai 웃, dinilai sebesar satu jam dikalikan upah minimum setempat, dikalikan pengali yang lingkupnya jelas dan anggarannya disetujui dari jam-jam yang sungguh-sungguh dikerjakan dan disaksikan. Sebelum sebuah tugas membawa persetujuan itu, kerja di baliknya adalah perencanaan, bukan kerja yang dapat dikompensasi, dan tidak seorang pun dibayar untuk merencanakan. Sebuah plafon sebesar 9.999 웃 per tahun, dengan kelebihan apa pun dibawa maju ke tahun berikutnya, bukan lenyap begitu saja, menjaga rekening satu tahun mana pun agar tidak menjadi baik keberuntungan mendadak maupun jebakan.

Tak satu pun dari semua ini berjalan lebih cepat daripada buktinya sendiri. Accord ini sendiri maju dari operasi Manual ke Semi-Otomatis ke Otonom satu kubus pada satu waktu, dan hanya di tempat perbaikan terukur satu tingkat penuh — satu bagian dari sembilan — telah sungguh-sungguh didemonstrasikan, tidak pernah diasumsikan terlebih dahulu. Otonomi diperoleh persis di sana dan tidak pernah di dekat makna, uang, atau hukum, yang selalu tetap menjadi urusan manusia. Biaya administrasi dibatasi. Hadiah korporat dan kelembagaan disambut dan dibatasi bersamanya. Pembukuan lengkap disampaikan dalam bahasa setiap wilayah penanda tangan setiap bulan, dimulai di Kamboja, Honduras, dan Austin, dan dimaksudkan untuk tetap disampaikan, dan tetap dapat dibaca, lima ratus tahun kemudian. Inilah kepercayaan yang dituntut accord ini. Inilah kepercayaan yang diperoleh accord ini, satu sumbangan kecil yang dapat dilacak pada satu waktu, di hadapan setiap warga yang akan pernah dilayaninya.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Pertukaran Lintas Budaya dan Kontribusi Global`,
    content: {
      7: `Setiap pelajar dalam bahasanya sendiri.`,
      33: `Setiap kegiatan dalam bahasa peserta — terbuka bagi warga mana pun, tanpa memerlukan izin pemerintah. Kecerdasan Buatan, Manusia, dan Bersama dijaga dalam ketegangan yang produktif. Kurikulum diterbitkan secara terbuka. Apa yang dipelajari satu wilayah, diwariskan kepada semua.`,
      111: `Atlantis Accords mengembalikan pendidikan ke tujuannya yang paling dalam: pertukaran kebijaksanaan lintas batas yang jika tidak akan memisahkan. Setiap warga boleh memasuki kurikulum ini, apa pun yang ditandatangani pemerintahnya. Setiap kegiatan tersedia dalam bahasa peserta, bahasa wilayah tuan rumah, dan sebuah catatan bersama. Bahasa bukan sekadar hiasan — bahasa adalah yurisdiksi, bahasa adalah martabat yang dibuat terbaca. Kerangka kerja pendidikan ini bertumpu pada trinitas kecerdasan: Kecerdasan Buatan mengusulkan, Manusia memutuskan, Shared Intent (Niat Bersama) memvalidasi. Setiap murid belajar menjaga ketiganya dalam ketegangan. Apa yang dipelajari accord ini, ia berikan kembali. Kurikulum, hasil inovasi, riset kesejahteraan, dan keputusan tata kelola diterbitkan secara terbuka. Apa yang dipelajari satu wilayah, diwariskan kepada semua warga.`,
      333: `Atlantis Accords mengembalikan pendidikan ke tujuannya yang paling dalam: pertukaran kebijaksanaan lintas batas yang jika tidak akan memisahkan. Ini adalah accord di antara warga dunia — warga mana pun boleh membangunnya dan memegangnya, apa pun yang ditandatangani pemerintahnya. Setiap kegiatan tersedia dalam bahasa peserta, bahasa wilayah tuan rumah, dan sebuah catatan bersama, sehingga tidak ada peserta yang menjalani accord ini dalam bahasa yang tidak dipilihnya sendiri. Bahasa bukan sekadar hiasan. Bahasa adalah yurisdiksi. Bahasa adalah martabat yang dibuat terbaca. Seorang anak muda di Kamboja membaca catatan tunjangannya dalam bahasa Khmer, di Honduras dalam bahasa Spanyol, di Austin dalam bahasa Inggris — ketiganya dihormati setara, tak satu pun memerlukan restu pemerintah untuk memulai.

Kerangka kerja pendidikan ini bertumpu pada trinitas kecerdasan yang dinampakkan Vision 2525. Artificial Intelligence mengusulkan pola dan kemungkinan lebih cepat daripada yang mampu dilakukan manusia sendirian. Human Intelligence memutuskan soal keselamatan, etika, dan arah — pertanyaan-pertanyaan yang tidak sepatutnya dijawab mesin, dijaga di bawah Human Authority. Shared Intent memvalidasi bahwa keputusan-keputusan itu melayani prinsip-prinsip accord ini, sehingga tidak ada peserta yang memilih keunggulan di atas kebaikan bersama. Tidak ada murid yang tunduk pada satu kecerdasan saja; setiap murid belajar menjaga ketiganya dalam ketegangan. Keanggotaan dimulai dengan Seed, sebuah keanggotaan seharga sepertujuh dari satu jam upah minimum setempat — cukup kecil sehingga warga mana pun mampu menjangkaunya. Ini mempersiapkan generasi berikutnya untuk memerintah, di tempat tidak ada satu kecerdasan pun yang bertindak tanpa pengawasan.

Apa yang dipelajari accord ini, ia berikan kembali. Kurikulum diterbitkan di bawah lisensi terbuka sehingga wilayah mana pun — baik penanda tangan maupun bukan — boleh mengadaptasinya ke budaya setempat. Hasil inovasi diterbitkan. Riset kesejahteraan diterbitkan secara agregat bagi para peneliti di mana pun. Keputusan tata kelola diterbitkan lengkap dengan alasannya, sehingga warga mana pun, tidak hanya pemerintah penanda tangan, dapat memverifikasinya — dan Replay memungkinkan warga yang sama itu menelusuri kembali alasan itu satu abad dari sekarang. Keberhasilan diukur bukan hanya dari para pesertanya, melainkan juga dari inisiatif pendidikan dan budaya yang muncul mengikutinya, di wilayah-wilayah yang tidak pernah menandatangani pilot ini namun membangun di atas kebijaksanaan bersamanya. Apa yang dipelajari satu wilayah, diwariskan kepada setiap warga.`,
      999: `Atlantis Accords mengembalikan pendidikan ke tujuannya yang paling dalam: pertukaran kebijaksanaan lintas batas yang jika tidak akan memisahkan, dan ia memulai pertukaran itu sebelum satu pun pelajaran diajarkan. Tindakan pertama setiap peserta di dalam kerangka kerja ini adalah Seed — keanggotaan satu kali seharga sepertujuh dari satu jam upah minimum setempat, tidak dapat dipindahtangankan, tidak membawa klaim ekonomi apa pun. Ia cukup kecil sehingga tidak ada keluarga yang tersisihkan dan cukup nyata sehingga tidak ada peserta yang masuk hanya sebagai penonton. Inilah pelajaran pertama accord ini: keanggotaan diperoleh dengan murah, tetapi tetap diperoleh, dan ia tidak memberikan kepemilikan apa pun atas apa yang datang setelahnya. Setiap kegiatan accord yang mengikutinya tersedia dalam bahasa peserta, dalam bahasa wilayah tuan rumah, dan dalam sebuah catatan bersama, sehingga tidak ada peserta yang menjalani accord ini dalam bahasa yang tidak dipilihnya sendiri. Bahasa bukan sekadar hiasan. Bahasa adalah yurisdiksi. Bahasa adalah martabat yang dibuat terbaca. Ketika seorang anak muda dari sebuah desa di Kamboja membaca catatan tunjangannya dalam bahasa Khmer, sebuah kota di Honduras dalam bahasa Spanyol, dan sebuah lingkungan di Austin dalam bahasa Inggris, ketiganya dihormati setara oleh accord yang sama, di wilayah-wilayah pendiri yang sama yang pertama kali sepakat untuk saling mengajar.

Kerangka kerja pendidikan accord ini bertumpu pada trinitas kecerdasan yang dinampakkan Vision 2525, dan kurikulumnya mengajarkan masing-masing sebagai sesuatu yang dapat dirasakan seorang peserta di tangannya sendiri, bukan sebagai abstraksi. ♡, Shared Intention, membawa alasannya — benang yang dipelajari setiap murid untuk dipegang sebelum menyentuh alat apa pun, pertanyaan tentang apakah kerja ini masih melayani orang-orang yang diklaimnya untuk dilayani. ◬, akselerasi tersaksikan, diajarkan semata sebagai sebuah delta — diukur hanya terhadap garis dasar yang dibekukan, tidak pernah dibungkus sebagai metrik laba, tidak pernah diklaim sebagai pencapaian pribadi terlepas dari tim di sekelilingnya. 웃, Human Intelligence yang dihormati dalam waktu, diajarkan dengan paling hati-hati: satu jam kerja yang disaksikan setara dengan satu jam pada upah minimum setempat, dan apa yang diperoleh seorang peserta adalah upah itu dikalikan jam yang dikerjakan — Multiple dikali Waktu, tidak ada yang tersembunyi dalam hitungannya. Para murid belajar sejak dini bahwa 웃 diterbitkan hanya untuk kerja yang disaksikan dan dilakukan di bawah tugas yang lingkupnya jelas dan anggarannya disetujui. Sebelum persetujuan itu ada, upaya yang sama hanyalah perencanaan — berharga, tetapi tidak dibayar, dan setiap peserta diajarkan untuk mengenali perbedaan ini sekali lihat.

Karena perbedaan itu mudah menjadi kabur, kurikulumnya mengajarkan QIS, Qualified Innovation Score, sebagai sebuah cermin, bukan papan skor. QIS adalah rata-rata dari empat angka finansial mutlak — Revenue, Gross Profit, Operating Income, dan Effective R&D — dibagi empat, dan setiap murid belajar menghitungnya, mempertanyakannya, dan tidak pernah mengelirukannya dengan uang. Pertumbuhan QIS menentukan besar kumpulan imbalan hanya setelah kualifikasi dikonfirmasi secara independen, dan pertumbuhan itu tidak mencetak 웃 apa pun dengan sendirinya. QIS adalah pengukuran. QIS tidak pernah menjadi pembayaran. QIS tidak pernah menjadi kepemilikan. Seorang murid yang telah menghayati perbedaan ini tidak dapat diyakinkan bahwa skor yang tinggi memberinya hak atas klaim yang tidak pernah dijanjikan accord ini.

Kurikulum ini memperluas literasi tersebut hingga ke bagaimana nilai sungguh-sungguh sampai kepada seseorang, melalui apa yang disebut accord ini Livelihood Direct — prinsip 🏠 bahwa uang bergerak melalui jalur lokal berlisensi dan memenuhi syarat, dan tidak pernah melalui dana yang disimpan kerangka kerja ini sendiri. Para murid diajarkan untuk melacak tunjangan mereka, dan kelak penghasilan mereka sendiri, melalui jalur-jalur ini sebagai latihan kewargaan, bukan sebagai misteri finansial yang dijalankan di tempat lain atas nama mereka. Mereka belajar bahwa klasifikasi selalu mendahului penyelesaian pembayaran, dan bahwa pengakuan — QIS yang tinggi, pujian publik — tidak dengan sendirinya menjadi gerbang bagi tempat tidur, tunjangan, atau tempat dalam rotasi. Perannyalah yang menjadi gerbangnya. Ini adalah perlindungan terhadap kegagalan yang sangat lama: pujian yang dikelirukan sebagai penyediaan kebutuhan.

Berdampingan dengan literasi finansial ada literasi kewargaan, diajarkan melalui Continuity Without Evasion. Setiap peserta belajar bahwa accord ini dibangun demi portabilitas yang sah — bahwa tidak ada satu pemerintah, bank, pendiri, atau model yang tak tergantikan berdiri di antara mereka dan janji-janji kerangka kerja ini. Mereka belajar apa yang dilakukan sebuah putusan yang merugikan di dalam rancangan ini: ia membuat satu jalur gagal secara tertutup, di satu yurisdiksi, di bawah sikap default-deny adaptor itu, dan tidak pernah meruntuhkan keseluruhannya. Berdampingan dengan ini adalah pelajaran terdalam yang diajarkan accord ini: Human Authority memegang makna, uang, dan hukum, dan lapisan berdaulat tempat keputusan-keputusan itu dibuat tetap tertutup secara permanen bagi mesin. Measurement of Time, MoT, mencatat menit-menit sungguhan setiap peserta secara terpisah dari skor apa pun, dan Replay membuat setiap rilis yang diterbitkan accord ini sepenuhnya dapat direkonstruksi — sehingga seorang murid yang ingin tahu mengapa sebuah keputusan dibuat, bertahun-tahun kemudian, dapat menelusurinya sendiri, alih-alih hanya memercayai kata-kata orang lain.

Struktur kepercayaan yang diperoleh ini menjadi model pedagogis accord ini, bukan sekadar model tata kelolanya. Setiap peserta maju melalui mode Manual, Semi-Otomatis, dan Otonom dengan keleluasaan yang meningkat, digerbangi oleh ambang batas perbaikan terukur yang sama yang menggerbangi teknologinya sendiri — sebuah kenaikan terverifikasi sebelas dan satu-persembilan persen sebelum mode berikutnya terbuka. Otonomi, ketika ia diperoleh, diperoleh secara sempit dan per domain, tidak pernah atas makna, uang, atau hukum. Seorang murid yang telah menjalani proses ini memahami, secara mendalam, mengapa lapisan berdaulat tidak boleh pernah diotomatisasi — karena mereka memperoleh otonomi mereka sendiri satu langkah terukur pada satu waktu, dan tahu persis apa yang tercakup dan tidak tercakup dalam otonomi itu.

Apa yang dipelajari accord ini, accord ini berikan kembali. Kurikulum diterbitkan di bawah lisensi terbuka sehingga wilayah mana pun — baik penanda tangan maupun bukan — boleh mengadaptasinya ke budaya dan tradisi pedagogis setempat. Hasil inovasi diterbitkan. Riset kesejahteraan diterbitkan dalam bentuk agregat bagi para peneliti di mana pun. Keputusan tata kelola diterbitkan lengkap dengan seluruh alasannya utuh. Keberhasilan accord ini diukur bukan hanya dari para pesertanya sendiri di Kamboja, Honduras, dan Austin, melainkan juga dari inisiatif-inisiatif yang muncul mengikutinya, di wilayah-wilayah yang tidak pernah menandatangani pilot pendirinya namun membangun di atas kebijaksanaan yang dibagikannya secara terbuka, sepanjang cakrawala yang tidak akan sempat disaksikan selesai oleh para pendirinya sendiri. Apa yang dipelajari satu wilayah, diwariskan kepada semua wilayah lain — dan apa yang diajarkan dengan jujur kepada generasi ini, lima ratus tahun berikutnya tidak akan perlu melupakannya kembali.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Pertumbuhan Jaringan yang Berkelanjutan`,
    content: {
      7: `Tak pernah lebih cepat dari kecepatan martabat.`,
      33: `Tiga wilayah pendiri menyelesaikan satu siklus pilot sebelum wilayah keempat bergabung — warga mana pun boleh membangunnya. Catatan ditambatkan agar bertahan lima abad. Para penanda tangan mempertahankan kedaulatan; tidak ada yang diturunkan mutunya bagi yang bergabung berikutnya.`,
      111: `Atlantis Accords tidak akan tumbuh lebih cepat daripada mutu yang dapat dihormatinya. Tiga wilayah pendiri harus menyelesaikan satu siklus pilot secara penuh, dengan setiap peserta dihormati dan setiap prinsip diverifikasi, sebelum wilayah keempat bergabung. Inilah prinsip yang akhirnya menjadi disiplin kerja. Tetapi accord ini adalah kesepakatan di antara warga dunia — siapa pun, di mana pun, boleh membangunnya dan memegangnya, hanya berjarak satu Seed, apa pun yang ditandatangani sebuah pemerintah atau diizinkan sebuah majikan. Cakrawala accord ini adalah lima abad. Catatannya ditambatkan melalui Replay, sehingga seorang warga yang membacanya satu abad dari sekarang dapat memercayai penalarannya. Setiap penanda tangan mempertahankan kedaulatannya; tidak ada yang diturunkan mutunya bagi yang bergabung berikutnya.`,
      333: `Atlantis Accords tidak akan tumbuh lebih cepat daripada mutu yang dapat dihormatinya. Setiap perluasan adalah sebuah janji kepada para peserta yang telah lebih dahulu berada di dalamnya — bahwa standar pendirian tidak akan diencerkan oleh skala. Tiga wilayah pendiri harus menyelesaikan satu siklus pilot secara penuh, dengan setiap peserta dihormati dan setiap prinsip diverifikasi, sebelum wilayah keempat bergabung. Inilah prinsip yang akhirnya menjadi disiplin kerja. Dan pintunya tidak pernah hanya bersifat regional: ini adalah kesepakatan di antara warga dunia, dan siapa pun boleh membangunnya, mendanainya, dan memegangnya bertanggung jawab — tanpa memerlukan izin pemerintah, tanpa memerlukan restu majikan. Para pemimpin yang menandatangani pilot ini menjanjikan kepada para penanda tangan berikutnya substrat, perlindungan, dan martabat yang sama seperti yang diterima kohort pendiri. Tidak ada yang diturunkan mutunya bagi yang berikutnya.

Cakrawala accord ini dengan sengaja dibuat panjang — dirancang untuk bertahan lima belas hingga dua puluh generasi manusia, lima abad sejak hari pendiriannya. Catatannya ditambatkan melalui Replay, sehingga seorang warga yang membacanya satu abad dari sekarang dapat memverifikasi penalarannya, bukan sekadar memercayainya. Kerangka koordinatnya, peran-peran Human Authority-nya, dan siklus tata kelola lintas generasinya dibangun untuk bertahan menghadapi transisi teknologi tunggal apa pun. Accord ini akan hidup lebih lama daripada setiap manusia yang menandatangani pilot pendiriannya, dan setiap warga yang menanam Seed dan mendanainya setiap bulan. Itulah janjinya kepada anak yang menandatangani perjanjian tunjangan, kepada warga yang bergabung tanpa berutang izin pemerintah mana pun, kepada cucu-cucu anak itu yang kelak mungkin memerintah accord ini di pertengahan abad, dan kepada setiap generasi yang mewarisi apa yang dibangun sekarang oleh para pendirinya — baik pejabat maupun warga biasa.

Setiap penanda tangan mempertahankan kebebasan untuk mengundurkan diri, kedaulatan penuh, dan wewenang atas warganya sendiri, dengan hak untuk mengubah dan membentuk evolusi accord ini. Setiap warga mempertahankan kedudukan yang sama untuk mendirikan, mendanai, menyaksikan, dan memegangnya bertanggung jawab — dengan atau tanpa tanda tangan pemerintah. Yang tidak dapat dilakukan siapa pun adalah mengompromikan prinsip-prinsip pendiriannya, karena janji itu harus bertahan menghadapi kepergian siapa pun. Para pemimpin dan warga sama-sama menandatangani abad berikutnya accord ini ke dalam sebuah cakrawala yang akan diwarisi dan disempurnakan oleh cucu-cucu mereka.`,
      999: `Atlantis Accords tidak akan tumbuh lebih cepat daripada mutu yang dapat dihormatinya, dan pengekangan ini bukanlah sentimen — ini adalah rekayasa, tertulis ke dalam disiplin pengukuran yang sama yang mengatur setiap janji yang dibuat accord ini. Tiga wilayah pendiri, Kamboja, Honduras, dan Austin, harus menyelesaikan satu siklus pilot secara penuh, dengan setiap peserta dihormati dan setiap prinsip diverifikasi, sebelum wilayah keempat bergabung. Pertumbuhan yang melampaui verifikasi bukanlah pertumbuhan; itu adalah risiko yang mengenakan kostum ambisi. Pilot pendirian ini ada agar accord dapat membuktikan, pada skala yang cukup kecil untuk diperiksa dan cukup besar untuk berarti, bahwa janji-janjinya bertahan bersentuhan dengan kenyataan sebelum janji-janji itu diperluas ke sebuah dunia yang menyaksikan dari luar ketiga perbatasannya. Wilayah keempat belum diberi nama, dan tidak akan diberi nama hingga ketiga wilayah pertama berdiri di belakang setiap klaim yang dibuat dokumen ini.

Yang membuktikan kesiapan untuk tumbuh bukanlah antusiasme, melainkan sebuah angka yang dapat dipertahankan accord ini di hadapan publik. Qualified Innovation Score — QIS, dihitung sebagai Revenue ditambah Gross Profit ditambah Operating Income ditambah pengeluaran Effective R&D, dibagi empat — adalah instrumen yang digunakan accord ini untuk mengetahui apakah sebuah wilayah, sebuah kohort, atau sebuah kubus telah benar-benar membaik, bukan sekadar terasa seolah-olah membaik. Pertumbuhan QIS menentukan besar kumpulan imbalan hanya setelah kualifikasi terpenuhi, tidak pernah sebelumnya, dan QIS itu sendiri tidak mencetak 웃 apa pun dan tidak membeli kepemilikan apa pun. QIS adalah pengukuran, bukan pembayaran; pengukuran, bukan ekuitas; sebuah cermin yang diangkat accord ini kepada kerjanya sendiri, tidak pernah menjadi mata uang yang dibelanjakannya. Sebuah wilayah yang mengusulkan untuk memperluas jaringan harus menunjukkan QIS-nya dengan jujur, di hadapan wilayah-wilayah sebelumnya, atau ia tidak akan meluas.

Pertumbuhan yang berkelanjutan berarti pertumbuhan yang memperoleh wewenangnya sendiri satu peningkatan pada satu waktu. Setiap kubus dan setiap wilayah dimulai dalam mode Manual, tempat manusia memutuskan segalanya dan sistem hanya membantu. Kenaikan ke operasi Semi-Otomatis, dan pada akhirnya Otonom, di dalam sebuah kubus tertentu digerbangi oleh satu ambang batas yang sama di seluruh accord ini — sebuah perbaikan terukur sebelas dan satu-persembilan persen, satu bagian dari sembilan, dibuktikan dan dapat direproduksi sebelum tingkat otonomi berikutnya diberikan. Otonomi diperoleh kubus demi kubus, tidak pernah diklaim sekaligus secara menyeluruh atau diperluas atas ranah-ranah yang harus tetap menjadi urusan manusia betapa pun majunya sistem itu kelak: makna, uang, dan hukum tetap tertutup bagi mesin, terlepas dari berapa banyak ambang batas yang telah dilewati di tempat lain. Sebuah jaringan yang memperluas otomatisasinya lebih cepat daripada memperluas buktinya bukanlah sedang memodernisasi diri. Ia sedang berjudi dengan kepercayaan yang belum diperolehnya.

Kompensasi berskala mengikuti jaringan dengan cara yang sama seperti wewenang — dengan sengaja, dan dengan sebuah plafon yang melindungi seluruh sistem dari keberhasilannya sendiri. 웃, token Human Intelligence, setara dengan satu jam kerja yang disaksikan dikalikan upah minimum setempat; apa yang diperoleh peserta mana pun adalah Multiple itu dikalikan jam yang dikerjakan, dan ia diterbitkan hanya untuk kerja yang dilakukan di bawah tugas yang lingkupnya jelas dan anggarannya disetujui. Sebelum persetujuan itu, rencana sebaik apa pun hanyalah perencanaan, dan perencanaan semata tidak mencetak apa pun. Penyelesaian pembayaran setiap peserta dibatasi pada 9.999 웃 per tahun, dengan kelebihan apa pun dibawa maju ke tahun berikutnya, bukan lenyap atau mendistorsi kumpulan imbalan itu. Seiring wilayah-wilayah baru bergabung dan aktivitas jaringan berlipat ganda, plafon inilah yang menjaga pertumbuhan agar tidak berubah menjadi inflasi — nilai tetap ditambatkan pada jam-jam lokal yang sungguhan dan disaksikan, betapa pun besarnya accord ini kelak.

Di balik setiap 웃 terdapat sebuah alasan yang tidak dapat dihitung oleh buku besar mana pun dengan sendirinya. ♡, Shared Intention, membawa alasan itu maju melalui setiap keputusan perluasan yang dibuat accord ini, sementara ◬, kontribusi Artificial Intelligence, dihitung sebagai akselerasi tersaksikan yang diukur terhadap garis dasar yang dibekukan — sebuah delta, dan tidak pernah, dalam keadaan apa pun, sebuah metrik laba yang dioptimalkan demi dirinya sendiri. Untuk memasuki jaringan ini, dimulai dengan cara yang sama bagi setiap peserta, apa pun wilayah atau dekade keikutsertaan mereka: dengan sebuah Seed, keanggotaan satu kali seharga sepertujuh dari satu jam upah minimum setempat, tidak dapat dipindahtangankan dan tidak membawa klaim ekonomi apa pun. Seed hanya menyatakan bahwa seseorang telah tiba. Segala sesuatu yang mereka bangun setelahnya, mereka bangun di hadapan penuh ketiga mata uang lain accord ini, tidak pernah melalui Seed itu sendiri.

Pertumbuhan yang sungguhan juga harus menjadi pertumbuhan yang sampai kepada orang yang sungguhan, bukan dana yang dipegang kerangka kerja ini atas nama seseorang. 🏠 Livelihood Direct mensyaratkan bahwa nilai berjalan kepada seorang peserta hanya melalui jalur lokal berlisensi dan memenuhi syarat yang telah diperiksa accord ini wilayah demi wilayah, dan tidak pernah melalui penyimpanan yang dipegang kerangka kerja ini sendiri. Klasifikasi selalu mendahului penyelesaian pembayaran, sehingga tidak ada nilai yang bergerak sebelum tujuan dan penerimanya sama-sama dipastikan tanpa keraguan. Dan karena pengakuan tidak sama dengan akses, tempat tidur, tempat dalam rotasi, kursi di meja perundingan digerbangi oleh peran dan kesiapan, tidak pernah oleh skor atau kedudukan seorang peserta. Seiring jaringan meluas ke wilayah keempat dan seterusnya, setiap wilayah baru harus mengkualifikasi jalur berlisensinya sendiri sebelum Livelihood Direct dapat menjangkau rakyatnya — perluasan kepercayaan, bukan sekadar perluasan wilayah.

Tak satu pun dari semua ini bertahan tanpa sebuah jaringan yang dibangun untuk bertahan menghadapi keberhasilannya sendiri, dan itulah sebabnya Continuity Without Evasion mengatur setiap wilayah yang pernah ditambahkan accord ini. Portabilitas yang sah bersifat wajib; tidak ada satu pemerintah, bank, pendiri, atau model pun yang boleh menjadi tak tergantikan bagi keseluruhannya. Setiap yurisdiksi menjalankan adaptornya sendiri, fail-closed dan default-deny, sehingga putusan yang merugikan di mana pun menutup satu jalur, tidak pernah seluruh accord. Human Authority memegang makna, uang, dan hukum pada setiap skala yang dijangkau jaringan ini, tersegel terhadap perambahan mesin melalui rancangan, bukan sekadar melalui janji. Measurement of Time mencatat setiap menit sungguhan secara terpisah dari setiap klaim tentangnya, dan Replay memastikan bahwa rilis apa pun, di wilayah mana pun, pada titik mana pun sepanjang lima abad, dapat direkonstruksi dan diperiksa ulang oleh siapa pun yang meminta. Sebuah jaringan yang tidak dapat di-Replay tidak dapat dipercaya, betapa pun banyak wilayah yang telah bergabung dengannya atau betapa pun mengesankan pertumbuhannya terlihat dari luar. Begitulah cara Vision 2525 tumbuh tanpa pernah melampaui kepercayaan yang dibangun untuk dijaganya — satu wilayah yang terverifikasi, satu QIS yang jujur, satu jam yang disaksikan pada satu waktu.`,
    },
  },
];
