import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_IT: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Dove Comincia l'Innovazione`,
    content: {
      7: `I leader iniziano ciò che nessun secolo iniziò.`,
      33: `Tre regioni — Cambodia, Honduras, Austin — promettono di ospitare i giovani studenti, proteggerli e consegnare loro gli strumenti del futuro. Governo, Educazione, Innovazione: tre firme visionarie per regione. Un inizio insieme.`,
      111: `L'Atlantis Accords è una promessa fatta da leader disposti a iniziare qualcosa che non è mai esistito prima. I suoi firmatari fondatori in Cambodia, Honduras e Austin, Texas sono stati scelti per una qualità rara: la volontà di affidare ai giovani gli strumenti del futuro mentre c'è ancora tempo per insegnarglieli. Firmare l'accordo impegna la regione ad ospitare studenti di diverse culture, contribuire con ciò che solo essa può offrire, e mantenere uno standard più alto di quanto l'attuale regolamentazione richieda. Tre firme visionarie — Governo, Educazione, Innovazione — entrano nell'accordo insieme. Tre visionari, tre regioni, un inizio condiviso.`,
      333: `Ogni civiltà è ricordata per ciò che scelse di iniziare. L'Atlantis Accords è una promessa fatta da leader disposti a iniziare qualcosa che non è mai esistito prima — una fondazione condivisa per l'ordinaria innovazione umana che raggiunge ogni angolo del mondo, onora ogni voce e dura attraverso le generazioni. I suoi firmatari fondatori in Cambodia, Honduras e Austin, Texas non sono stati scelti per potere economico, forza militare o prestigio istituzionale. Sono stati scelti per una qualità più rara: la volontà di affidare ai giovani gli strumenti del futuro. Questo è ciò che significa la leadership nel secolo che ci attende — il coraggio di consegnare le chiavi alla prossima generazione mentre c'è ancora tempo per insegnare loro come guidare.

L'accordo è convocato da eXeL, una forza organizzatrice costruita apposta per questo momento. eXeL esiste deliberatamente al di fuori dei tradizionali canali di coordinamento che hanno plasmato il secolo scorso — al di fuori delle strutture di trattati diplomatici, al di fuori delle burocrazie multilaterali, al di fuori delle implicazioni politiche di ogni singolo Stato-nazione. eXeL è il convocatore fidato che riunisce leader visionari attorno a un quadro condiviso, un volano condiviso e un orizzonte di cinquecento anni condiviso. Ogni firmatario conserva piena sovranità, piena autorità sui propri cittadini e piena libertà di ritirarsi in qualsiasi momento. Ciò che i firmatari guadagnano è l'effetto rete che solo un quadro costruito su misura può fornire. Questo è coordinamento senza alcuna forma di dominio politico.

Firmare l'accordo è firmare una promessa. Che la regione ospiterà giovani studenti di diverse culture. Che la regione contribuirà con ciò che solo essa può offrire in modo unico. Che la regione manterrà uno standard più alto di quanto l'attuale regolamentazione richieda. Che la regione lo farà pubblicamente, con trasparenza, sotto lo sguardo di ogni cittadino che serve. Tre firme sono richieste da ciascuna regione — Governo, Educazione e Innovazione. Nessun singolo ufficio vincola l'accordo da solo. Servono tre visionari per dire sì. Tre visionari, tre regioni, un inizio — così ogni quadro entra in vita, attraverso la fiducia reciproca di leader disposti a firmarlo all'esistenza.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Imparare Attraverso la Simulazione`,
    content: {
      7: `Esercitarsi mille volte prima di toccare.`,
      33: `Nulla di conseguenza si impara prima su hardware vivo. Ogni partecipante si esercita in simulazione, ruota tra tre regioni, celebra pubblicamente. Questo è rispetto per il giovane il cui primo errore non dovrebbe mai costare una vita.`,
      111: `Ogni disciplina degna di essere padroneggiata è stata appresa da qualcuno prima di essere conosciuta. L'Atlantis Accords riporta questa antica saggezza al centro del modo in cui i giovani sono preparati a costruire il futuro. Nulla di conseguenza si impara prima su hardware vivo, su persone reali o in condizioni irreversibili. Ogni partecipante si esercita in simulazione finché la pratica diventa competenza, e la competenza diventa prontezza. Il modello di rotazione porta ogni partecipante attraverso le tre regioni fondatrici, e ogni rotazione termina in una celebrazione pubblica e cooperativa aperta alla più ampia comunità ospitante. Questo è rispetto per il giovane il cui primo errore non dovrebbe mai costare una vita.`,
      333: `Ogni disciplina degna di essere padroneggiata è stata appresa da qualcuno prima di essere conosciuta. I maestri artigiani provano prima dell'esibizione, i piloti provano prima del volo, i medici provano prima della chirurgia, e i bambini provano il mondo attraverso il gioco. L'Atlantis Accords riporta questa antica saggezza al centro del modo in cui i giovani sono preparati a costruire il futuro. Nulla di conseguenza si impara prima su hardware vivo, su persone reali o in condizioni irreversibili. Ogni partecipante si esercita in simulazione finché la pratica diventa competenza, e la competenza diventa prontezza. Questa non è cautela — è rispetto per il giovane il cui primo errore non dovrebbe mai costare a nessuno la vita.

Il modello di rotazione dell'accordo porta ogni partecipante attraverso le tre regioni fondatrici. Ciò che si impara in Cambodia è raffinato in Honduras e completato ad Austin. Ciò che si scopre ad Austin è interrogato in Cambodia e integrato in Honduras. Ogni partecipante vive, impara ed è guidato attraverso culture che altrimenti rimarrebbero distanti. Il curriculum di formazione attinge da tradizioni di simulazione disciplinata di molte culture — dalla tradizione educativa strategica di Sun Tzu, dalla pratica-attraverso-il-gioco di Musashi, dalla teoria dell'apprendimento ciclico di Ibn Khaldun, dalla dialettica monastica di Nalanda, dal simulatore di volo civile — sintetizzato per rispettare ogni fase cognitiva e ogni eredità culturale. Nessuna singola tradizione domina.

Ogni rotazione termina in una celebrazione pubblica e cooperativa aperta alla più ampia comunità ospitante. Vicini, famiglie e visitatori curiosi si riuniscono per vedere ciò che la coorte ha imparato. Questi eventi rendono la tecnologia sofisticata accessibile e celebrata anziché temuta. Una società che cresce comprendendo i sistemi cooperativi attraverso il gioco non può essere facilmente manipolata dalla paura di quei sistemi. Questa è deterrenza attraverso l'educazione, non deterrenza attraverso la forza. La promessa dell'accordo a ogni genitore: tuo figlio si eserciterà mille volte in sicurezza prima di toccare qualsiasi cosa che potrebbe fargli male, e la comunità testimonierà la sua crescita ad ogni passo. Questo è come appare il rispetto per il giovane quando è ingegnerizzato in un quadro, e questo è ciò che la leadership consegna alla prossima generazione di partecipanti prima che quella generazione debba esigerlo.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Sicurezza Provata Prima che la Fiducia Sia Estesa`,
    content: {
      7: `Prima provata la sicurezza, poi estesa la fiducia.`,
      33: `Ogni struttura e ogni rotazione si trova all'interno di un involucro protettivo con preallarme. L'hardware rifiuta la militarizzazione. Gli archivi sopravvivono alle turbolenze. La sicurezza è ingegnerizzata attorno al partecipante più giovane ogni giorno, non semplicemente promessa o presunta.`,
      111: `Prima che la fiducia sia estesa, la sicurezza deve essere provata. L'Atlantis Accords ne fa il suo impegno fondativo. Ogni struttura dell'accordo, ogni rotta di rotazione, ogni luogo dove un giovane partecipante dorme o studia si trova all'interno di un involucro protettivo documentato con capacità di preallarme che dà alla comunità ore, non minuti, per rispondere a qualsiasi rischio credibile. Ogni dispositivo, ogni sensore, ogni sistema di coordinamento è vincolato a livello hardware a rifiutare il riutilizzo per l'integrazione in sistemi d'arma. Questa non è politica — questa è fisica. L'accordo è progettato per rimanere onorevole attraverso le turbolenze: instabilità politica, contrazione dei finanziamenti, attacco informatico o interruzione dei viaggi. Ogni scenario è pianificato, e ogni piano pone la dignità umana come suo primo vincolo di progettazione.`,
      333: `Prima che la fiducia sia estesa, la sicurezza deve essere provata. L'Atlantis Accords ne fa il suo impegno fondativo. Ogni struttura dell'accordo, ogni rotta di rotazione, ogni luogo dove un giovane partecipante dorme o studia si trova all'interno di un involucro protettivo documentato con capacità di preallarme che dà alla comunità ore, non minuti, per rispondere a qualsiasi rischio credibile. La tecnologia usata per proteggere i partecipanti è la stessa tecnologia che l'accordo insegna loro a costruire — sensori, coordinamento, sopravvivenza delle comunicazioni, intelligenza distribuita. I giovani imparano la sicurezza dall'interno, nella loro lingua e nella loro regione, non essendogli detto che sono al sicuro, ma vedendo come la sicurezza è ingegnerizzata attorno a loro ogni giorno.

L'accordo fa una promessa infrangibile su ciò che la sua tecnologia non può diventare. Ogni dispositivo, ogni sensore, ogni sistema di coordinamento è vincolato a livello hardware a rifiutare il riutilizzo per l'integrazione in sistemi d'arma. Questo non è linguaggio politico. Questa non è aspirazione. Questa è un'impossibilità fisica, imposta crittograficamente, verificata da ogni regione firmataria e ispezionabile da ogni cittadino. Gli strumenti che proteggono un bambino a Phnom Penh non possono essere riutilizzati per danneggiare un bambino ad Austin. Gli strumenti che collegano un'esercitazione di sciame a Tegucigalpa non possono essere riconfigurati per prendere di mira un essere umano ovunque. Questa è la risposta dell'accordo a un secolo di paura del duplice uso. Non politica — fisica.

L'accordo è progettato per rimanere onorevole attraverso le turbolenze. Se una regione firmataria perde stabilità politica, i partecipanti sono accolti dalle regioni rimanenti. Se i finanziamenti si contraggono, le borse dei partecipanti sono protette per prime, prima dell'amministrazione e dell'infrastruttura. Se gli archivi digitali sono attaccati, i backup offline persistono. Se viaggiare diventa impossibile, il substrato continua virtualmente. Ogni scenario è pianificato, e ogni piano pone la dignità umana come suo primo vincolo di progettazione. I leader che firmano questo accordo firmano una promessa che la sicurezza è ingegnerizzata, non presunta. Ciò che estendono ai propri cittadini non è mera opportunità, ma protezione costruita allo standard che il partecipante più giovane merita — la stessa protezione che ogni leader esigerebbe per il proprio figlio che attraversa da solo una frontiera sconosciuta.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Compenso, Benessere e Dignità Umana`,
    content: {
      7: `Una borsa, un mentore, una casa.`,
      33: `Ogni partecipante riceve una borsa di sostentamento dal primo giorno. Amore, perdita e sicurezza sono trattati come infrastruttura di prima classe. Il successo è misurato dal partecipante più vulnerabile, mai dalla media. La dignità è substrato, mai decorazione.`,
      111: `L'Atlantis Accords tratta ogni partecipante come un essere umano pieno fin dal primo giorno. Una borsa è fornita dal momento in cui inizia la partecipazione, indicizzata al costo della vita della regione affinché il suo impatto rispetti la dignità locale del lavoro. Il benessere è trattato come infrastruttura di prima classe — non un beneficio opzionale, non un vantaggio wellness, ma il substrato su cui tutto il resto si regge. Tre domini fondativi sono sostenuti: Amore, Perdita e Sicurezza. L'accordo misura il successo dal risultato del suo partecipante più vulnerabile, non dalla media. Nessun partecipante sarà silenziosamente dimenticato perché le medie possano apparire buone. Dignità come substrato, non decorazione.`,
      333: `L'Atlantis Accords tratta ogni partecipante come un essere umano pieno fin dal primo giorno. Una borsa è fornita dal momento in cui inizia la partecipazione, indicizzata al costo della vita della regione affinché il suo impatto rispetti la dignità locale del lavoro. La borsa arriva prima che gli obblighi familiari diventino emergenze, e prima che la dignità sia compromessa. Segnala a ogni giovane che il suo tempo è prezioso, il suo contributo è atteso, e la stabilità della sua famiglia è parte della responsabilità dell'accordo. Questa non è carità. Questo è il riconoscimento che l'ordinaria innovazione umana richiede prima l'ordinaria sicurezza umana. Una mente non può fiorire mentre la sua casa è sotto minaccia.

Il benessere è trattato come infrastruttura di prima classe — non un beneficio opzionale, non un vantaggio wellness, ma il substrato su cui tutto il resto si regge. L'accordo nomina tre domini fondativi attraverso cui ogni partecipante è sostenuto: Amore, nel senso di connessione, attaccamento e sano confine; Perdita, poiché ogni partecipante sperimenterà il dolore e deve essere accompagnato, non aggirato; e Sicurezza, nel senso che ogni partecipante sa chi chiamare, in ogni regione, nella propria lingua. Consulenza individuale, cerchi di gruppo, pratiche somatiche e pratiche culturali o spirituali onorate secondo la propria tradizione del partecipante sono tutte fornite. Zero ideologia forzata. L'accordo mantiene lo spazio con reverenza; non fa proselitismo di alcun sistema di credenze.

L'accordo misura il successo dal risultato del suo partecipante più vulnerabile, non dalla media. I partecipanti rurali senza alta banda sono serviti. I partecipanti neurodivergenti ricevono accomodamento come norma. I partecipanti disabili trovano ogni struttura accessibile. I partecipanti di genere diverso ricevono alloggio sicuro e abbinamento con mentore. I parlanti non madrelingua trovano ogni artefatto nella loro lingua. I partecipanti indigeni trovano le loro pratiche culturali onorate e la loro conoscenza tradizionale protetta. I leader che firmano questo accordo promettono che nessun partecipante sarà silenziosamente dimenticato perché le medie possano apparire buone. Questa è dignità come substrato, non decorazione. Ciò che è misurato è ciò che sarà onorato, e ciò che è onorato qui è l'intero essere umano — mente, corpo e spirito insieme, senza alcuna eccezione.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finanziamento e Governance`,
    content: {
      7: `I cittadini finanziano la prossima generazione direttamente.`,
      33: `Residenti ordinari contribuiscono piccoli importi mensili. Nessuna pipeline di aiuti, nessun benefattore straniero, nessun laccio politico. Ogni dollaro è tracciabile. Ogni contabilità è pubblicata, nella lingua di ogni regione, ogni mese, pubblicamente.`,
      111: `L'Atlantis Accords è finanziato dai cittadini che serve. Residenti ordinari contribuiscono piccoli importi volontari ogni mese — modesti quanto basta affinché nessun adulto sia escluso dal prezzo, risonanti quanto basta affinché il totale sostenga il lavoro dell'accordo a scala significativa. Quando un cittadino finanzia direttamente la prossima generazione, quel cittadino tiene direttamente responsabile l'accordo. L'accordo è deliberatamente indipendente dalle istituzioni multilaterali che hanno plasmato il secolo scorso. Questa non è una dichiarazione politica — è una scelta di progettazione. Ogni dollaro è registrato in modo permanente e tracciabile. Ogni contributo cittadino può essere seguito dall'origine alla borsa all'innovazione. Trasparenza di un tipo raramente offerto da alcuna istituzione.`,
      333: `L'Atlantis Accords è finanziato dai cittadini che serve. Residenti ordinari delle regioni partecipanti contribuiscono piccoli importi volontari ogni mese — importi modesti quanto basta affinché nessun adulto in nessuna regione ospitante sia escluso dal prezzo della partecipazione, risonanti quanto basta affinché il totale sostenga il lavoro dell'accordo a scala significativa. Questo design è deliberato. Quando un cittadino finanzia direttamente l'educazione della prossima generazione, quel cittadino tiene direttamente responsabile l'accordo. Non c'è alcuna pipeline di aiuti, nessun benefattore straniero, nessun laccio politico attaccato all'assegno. L'anima dell'accordo è il cittadino che contribuisce un piccolo importo ogni mese, la cui partecipazione rende possibile il tutto.

L'accordo è deliberatamente indipendente dalle istituzioni multilaterali che hanno plasmato il secolo scorso — la North Atlantic Treaty Organization, la World Health Organization, le Nazioni Unite, l'International Monetary Fund, la World Bank e ogni canale nazionale di aiuti esteri. Questa non è una dichiarazione politica sul valore di quelle istituzioni o sui loro contributi. È una scelta di progettazione. Le dipendenze a punto singolo compromettono la durata su un orizzonte di cinquecento anni. Un quadro destinato a servire ogni regione indipendentemente dall'allineamento geopolitico non può essere intrecciato con alcun singolo allineamento. I governi nazionali possono contribuire volontariamente. I contributi sono trasparenti. Nessun contributo compra influenza di governance, da alcuna fonte, mai.

Ogni dollaro e ogni unità di valore che entra nell'accordo è registrato in modo permanente, pubblico e tracciabile. Ogni contributo cittadino può essere seguito dall'origine fino alla borsa che diventa fino al giovane che serve fino al progetto di innovazione che emerge dal lavoro di quel giovane. Le spese amministrative sono limitate. I doni aziendali e istituzionali sono benvenuti e limitati. Contabilità completa è consegnata nella lingua di ogni regione firmataria ogni mese. I leader che firmano l'accordo promettono ai loro cittadini una trasparenza di un tipo raramente offerto da alcuna istituzione — trasparenza che rimarrà leggibile per secoli dopo che ogni firmatario avrà lasciato la carica. Questa è la fiducia che l'accordo richiede. Questa è la fiducia che l'accordo guadagna, un piccolo contributo tracciabile alla volta, sotto lo sguardo di ogni cittadino.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Scambio Interculturale e Contributo Globale`,
    content: {
      7: `Ogni studente nella propria lingua.`,
      33: `Ogni attività disponibile nella lingua del partecipante. Intelligenze Artificial, Human e Shared tenute in tensione produttiva — nessuno studente si rimette a una sola. Curricula e risultati pubblicati apertamente. Ciò che una regione impara, tutte ereditano.`,
      111: `L'Atlantis Accords riporta l'educazione al suo scopo più profondo: lo scambio di saggezza attraverso confini che altrimenti dividerebbero. Ogni attività è disponibile nella lingua propria del partecipante, nella lingua della regione ospitante e in un registro condiviso canonico. La lingua non è decorazione — la lingua è giurisdizione, la lingua è dignità resa leggibile. Il quadro educativo si regge sulla trinità delle intelligenze: Artificial propone, Human decide, Shared Intent convalida. Ogni studente impara a mantenere tutte e tre in tensione produttiva. Ciò che l'accordo apprende, l'accordo restituisce. Curricula, risultati di innovazione, ricerca sul benessere e decisioni di governance sono tutti pubblicati apertamente. Ciò che una regione apprende, tutte le regioni ereditano.`,
      333: `L'Atlantis Accords riporta l'educazione al suo scopo più profondo: lo scambio di saggezza attraverso confini che altrimenti dividerebbero. Ogni attività dell'accordo è disponibile nella lingua propria del partecipante, nella lingua ufficiale della regione ospitante, e in un registro condiviso canonico affinché nessun partecipante navighi l'accordo in una lingua che non ha scelto. La lingua non è decorazione. La lingua è giurisdizione. La lingua è dignità resa leggibile. Quando un giovane di un villaggio cambogiano legge il proprio registro di borsa in Khmer, quando un giovane di una città honduregna lo legge in spagnolo, quando un giovane di un quartiere di Austin lo legge in inglese, tutti e tre sono onorati equamente dallo stesso accordo.

Il quadro educativo dell'accordo si regge sulla trinità delle intelligenze che Vision 2525 rende visibile. Artificial Intelligence propone modelli, opzioni e possibilità più rapidamente di quanto qualsiasi essere umano da solo potrebbe. Human Intelligence decide sulla sicurezza, l'etica e la direzione — le domande a cui nessuna macchina dovrebbe rispondere. Shared Intent convalida che le decisioni si allineino con i principi fondativi dell'accordo, assicurando che a nessun partecipante sia chiesto di scegliere tra eccellenza individuale e bene collettivo. Nessuno studente è insegnato a rimettersi a una sola intelligenza. Ogni studente impara a mantenere tutte e tre in tensione produttiva. Così la prossima generazione di leader è preparata a governare responsabilmente e saggiamente in un mondo in cui nessuna di queste tre intelligenze agirà mai da sola o non controllata.

Ciò che l'accordo apprende, l'accordo restituisce. I curricula sono pubblicati sotto licenza aperta affinché ogni regione — firmataria o meno — possa adattarli liberamente alla cultura locale e alla tradizione pedagogica. I risultati dell'innovazione sono pubblicati. La ricerca sul benessere è pubblicata in forma aggregata per ricercatori ovunque. Le decisioni di governance sono pubblicate con il loro pieno ragionamento. Il successo dell'accordo è misurato non solo dai suoi stessi partecipanti ma dal numero di iniziative educative, di innovazione e culturali che sorgono nella sua scia, in regioni che non hanno mai firmato il pilota fondativo ma hanno costruito sulla sua saggezza apertamente condivisa. Ciò che una regione apprende, tutte le altre regioni ereditano.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Crescita Sostenibile della Rete`,
    content: {
      7: `Mai più veloce di quanto la dignità possa viaggiare.`,
      33: `Tre regioni fondatrici completano un ciclo pilota prima che una quarta si unisca. Archivi ancorati per durare cinque secoli. Ogni firmatario conserva la sovranità. Nulla è degradato per fare spazio al prossimo firmatario.`,
      111: `L'Atlantis Accords non crescerà più velocemente della qualità che può onorare. Tre regioni fondatrici devono completare un ciclo pilota completo, con ogni partecipante onorato e ogni principio verificato, prima che una quarta regione si unisca. Questo è principio finalmente diventato disciplina operativa. L'orizzonte dell'accordo è deliberatamente lungo — cinque secoli dal giorno fondativo. I suoi archivi sono ancorati affinché un cittadino che li legge tra cento anni possa fidarsi del ragionamento. Ogni firmatario conserva piena sovranità, piena autorità e piena libertà di ritirarsi. Nessun firmatario può compromettere i principi fondativi — perché quei principi sono la promessa dell'accordo ai suoi partecipanti attraverso ogni generazione.`,
      333: `L'Atlantis Accords non crescerà più velocemente della qualità che può onorare. Ogni espansione è una promessa ai partecipanti già all'interno — che lo standard fondativo dell'accordo non sarà diluito dall'eccitazione della scala. Tre regioni fondatrici devono completare un ciclo pilota completo, con ogni partecipante onorato e ogni principio verificato, prima che una quarta regione si unisca. Questa non è cautela travestita da principio. Questo è principio finalmente diventato disciplina operativa attraverso ogni regione fondatrice. I leader che firmano il pilota fondativo promettono ai futuri firmatari lo stesso substrato, la stessa protezione, la stessa dignità che la coorte fondatrice ha ricevuto. Nulla è degradato per fare spazio al prossimo.

L'orizzonte dell'accordo è deliberatamente lungo. È progettato per durare approssimativamente da quindici a venti generazioni umane — cinque secoli dal giorno fondativo. I suoi archivi sono ancorati affinché un cittadino che li legge tra cento anni possa fidarsi del ragionamento. Il suo quadro di coordinate, i suoi ruoli di autorità umana e i suoi cicli di governance intergenerazionali sono tutti costruiti per sopravvivere a qualsiasi transizione di singola tecnologia. L'accordo sopravviverà a ogni essere umano che firma il suo pilota fondativo. Questa è la sua promessa al bambino che firma un accordo di borsa nell'anno successivo alla ratifica, ai nipoti di quel bambino che potrebbero governare l'accordo a metà secolo, e a ogni generazione che eredita ciò che i fondatori costruiscono ora.

Ogni firmatario conserva la libertà di ritirarsi con preavviso. Ogni firmatario conserva piena sovranità. Ogni firmatario conserva l'autorità sui propri cittadini. Ogni firmatario conserva il diritto di proporre emendamenti, sollevare controversie e plasmare l'evoluzione dell'accordo insieme a ogni altro firmatario. Ciò che nessun firmatario può fare è compromettere i principi fondativi del substrato — perché quei principi sono la promessa dell'accordo ai suoi partecipanti, e quella promessa deve sopravvivere alla partenza di qualsiasi singola firma. I leader che firmano questo accordo ora si uniscono a qualcosa più grande di un singolo mandato politico. Stanno firmando il prossimo secolo dell'accordo, e i secoli oltre, in un orizzonte che i loro stessi nipoti erediteranno e completeranno.`,
    },
  },
];
