import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_IT: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Dove Comincia l'Innovazione`,
    content: {
      7: `I leader iniziano ciò che nessun secolo iniziò.`,
      33: `Tre regioni — Cambogia, Honduras, Austin — aprono una promessa che i cittadini contribuiscono a costruire: accogliere chi apprende, proteggerlo, consegnargli gli strumenti del futuro. Governo, Istruzione e Innovazione firmano come custodi; i cittadini la custodiscono. Un solo inizio.`,
      111: `L'Accordo di Atlantide è un patto tra i cittadini del mondo — una promessa che qualsiasi persona, ovunque, può creare e custodire, indipendentemente da ciò che il proprio governo firma o il proprio datore di lavoro consente. Le sue regioni fondatrici, Cambogia, Honduras e Austin, in Texas, sono state scelte per una qualità rara: la volontà di affidare ai giovani gli strumenti del futuro finché c'è ancora tempo per insegnare loro a usarli. Governi, educatori e innovatori firmano come custodi delle proprie regioni — tre firme visionarie ciascuna, Governo, Istruzione, Innovazione — ma sono i cittadini a finanziare l'accordo, a testimoniarne il lavoro e a chiederne conto direttamente. Non serve il permesso di alcun governo né la benedizione di alcun datore di lavoro per appartenervi. Tre regioni, un unico inizio condiviso.`,
      333: `Ogni civiltà viene ricordata per ciò che ha scelto di iniziare. L'Accordo di Atlantide è una promessa tra i cittadini del mondo — chiunque, ovunque, può darvi inizio, qualunque cosa il proprio governo firmi. Le sue regioni fondatrici, Cambogia, Honduras e Austin, in Texas, non sono state scelte per potenza economica, forza militare o prestigio istituzionale, ma per una qualità più rara: la volontà di affidare ai giovani gli strumenti del futuro. Questo è ciò che significa guidare nel secolo che ci attende — il coraggio di consegnare le chiavi alla generazione successiva finché c'è ancora tempo per insegnarle a guidare.

L'accordo è convocato da eXeL, una forza organizzatrice costruita apposta per questo momento, che esiste al di fuori dei canali di coordinamento che hanno plasmato il secolo scorso — al di fuori delle strutture dei trattati diplomatici, delle burocrazie multilaterali e degli intrecci politici di qualsiasi singolo stato nazionale. eXeL è il convocatore di fiducia che riunisce leader visionari attorno a un quadro condiviso, a un volano condiviso e a un orizzonte condiviso di cinquecento anni. Ogni firmatario mantiene piena sovranità, piena autorità sui propri cittadini e piena libertà di ritirarsi in qualsiasi momento. Ciò che i firmatari guadagnano — e ciò che ogni cittadino guadagna, al prezzo di un Seed, un settimo di un'ora al salario minimo locale — è l'effetto di rete che solo un quadro costruito apposta può offrire: coordinamento senza alcuna forma di dominio politico.

Firmare l'accordo significa firmare una promessa: che la regione accoglierà chi apprende attraverso le culture, contribuirà con ciò che solo essa può offrire, e si atterrà a uno standard più alto di quanto richieda la normativa attuale — pubblicamente, in modo trasparente, rispondendo ai cittadini che lo finanziano, lo testimoniano e ne chiedono conto, senza bisogno del permesso di alcun governo né della benedizione di alcun datore di lavoro per appartenervi. Sono richieste tre firme da ciascuna regione — Governo, Istruzione e Innovazione — che firmano come custodi, non come proprietari. Ci vogliono tre visionari per dire sì, e i cittadini per custodire ciò che hanno firmato. Tre visionari, tre regioni, un unico inizio — così un quadro prende vita attraverso la fiducia di leader disposti a firmarlo nell'esistenza.`,
      999: `Ogni civiltà viene ricordata per ciò che ha scelto di iniziare, e Vision • 2525 chiede ai fondatori di questa civiltà di iniziare con umiltà anziché con conquista. L'Accordo di Atlantide è una promessa fatta da leader disposti a dare inizio a qualcosa che non è mai esistito prima — un fondamento condiviso per l'innovazione umana che raggiunge ogni angolo del mondo, onora ogni voce e resiste attraverso generazioni misurate non in anni ma in secoli. I suoi firmatari fondatori in Cambogia, Honduras e Austin, in Texas, non sono stati scelti per potenza economica, forza militare o prestigio istituzionale. Sono stati scelti per una qualità più rara: la volontà di affidare ai giovani gli strumenti del futuro, e la pazienza di lasciare che un orizzonte di cinquecento anni sopravviva agli applausi di qualsiasi amministrazione. Questo è ciò che significa guidare nel secolo che ci attende — il coraggio di consegnare le chiavi alla generazione successiva finché c'è ancora tempo per insegnarle a guidare.

L'accordo è convocato da eXeL, una forza organizzatrice costruita apposta per questo momento. eXeL esiste al di fuori dei canali di coordinamento che hanno plasmato il secolo scorso — al di fuori delle strutture dei trattati diplomatici, al di fuori delle burocrazie multilaterali, al di fuori degli intrecci politici di qualsiasi stato nazionale. eXeL è il convocatore di fiducia che riunisce leader visionari attorno a un quadro condiviso, a un volano condiviso e a un orizzonte condiviso di cinquecento anni. Ogni firmatario mantiene piena sovranità, piena autorità sui propri cittadini e piena libertà di ritirarsi in qualsiasi momento. Ciò che i firmatari guadagnano è l'effetto di rete che solo un quadro costruito apposta può offrire. L'ingresso di ogni partecipante in quel quadro inizia sempre nello stesso modo modesto: con un Seed, un'iscrizione una tantum al prezzo di un settimo di un'ora al salario minimo locale, non trasferibile e priva di qualsiasi rivendicazione economica. Un Seed non compra alcuna proprietà né alcuna promessa di ricompensa — soltanto l'appartenenza, il diritto di stare dentro il quadro e di iniziare. Questo è coordinamento senza alcuna forma di dominio politico, costruito su un inizio abbastanza piccolo perché chiunque possa permetterselo.

Poiché la sovranità viene mantenuta e non ceduta, l'accordo è costruito per la Continuità Senza Evasione. Nessun governo, banca, fondatore o modello indispensabile può tenere in ostaggio l'intero quadro per la propria sopravvivenza. Ogni giurisdizione è servita tramite il proprio adattatore lecito, in modalità default-deny finché non ne è provata la conformità, così che il valore si muova solo attraverso canali che un tribunale di quella giurisdizione riconoscerebbe come legittimi. Se un'autorità di regolamentazione in una regione emette una decisione sfavorevole, quel singolo canale si chiude in modo sicuro — in modo trasparente, senza danneggiare alcun partecipante al suo interno — mentre ogni altra regione prosegue indisturbata. L'intero accordo non cade mai perché un governo ha cambiato idea. Questa è portabilità progettata come promessa fondativa, non come misura di emergenza scoperta dopo la crisi.

Firmare l'accordo significa firmare una promessa. Che la regione accoglierà chi apprende attraverso le culture. Che la regione contribuirà con ciò che solo essa può offrire. Che la regione si atterrà a uno standard più alto di quanto richieda la normativa attuale. Che la regione lo farà pubblicamente, in modo trasparente, alla vista di ogni cittadino che serve. Sono richieste tre firme da ciascuna regione — Governo, Istruzione e Innovazione. Nessun singolo ufficio vincola l'accordo da solo. Ci vogliono tre visionari per dire sì. Questa firma tripla è la prima espressione dell'Autorità Umana: significato, denaro e legge restano nelle mani umane al livello sovrano, un livello permanentemente precluso alle macchine, per quanto capaci possano diventare. La Misurazione del Tempo, MoT, inizia a registrare dal momento della firma — minuti reali di lavoro umano reale, tenuti separati da qualsiasi stima automatizzata — e ogni successiva pubblicazione del lavoro dell'accordo è costruita per essere ricostruita tramite Replay, così che un cittadino nato tra un secolo possa ripercorrere come sono state raggiunte le decisioni fondative di oggi.

Ciò che il pilota fonda è misurazione prima ancora che denaro. Ogni innovazione che entra nel quadro viene valutata dal Qualified Innovation Score, QIS — la media di Ricavi, Utile Lordo, Reddito Operativo e spesa Effettiva in R&S, divisa per quattro. Il QIS non è un pagamento e non è mai proprietà; è lo strumento con cui una coorte fondatrice impara a vedere i propri progressi prima che venga dimensionata qualsiasi ricompensa. La crescita del QIS, una volta soddisfatta la qualificazione, dimensiona il fondo ricompense che ne segue — ma la crescita del QIS non conia nulla da sola. Tre regioni, un inizio, e una disciplina condivisa: dimostrare il punteggio prima di toccare il tesoro.

Il valore guadagnato attraverso il lavoro testimoniato porta un nome proprio, 웃, calcolato come un'ora moltiplicata per il salario minimo locale, scalata da un Moltiplicatore applicato alle ore prestate. Il 웃 viene emesso solo per lavoro testimoniato svolto nell'ambito di un compito definito e approvato a budget; tutto ciò che non ha ricevuto tale approvazione è ancora pianificazione, e la sola pianificazione non conia nulla. Un tetto di liquidazione di 9.999 웃 all'anno protegge ogni partecipante da una concentrazione incontrollata, con qualsiasi eccedenza riportata all'anno successivo anziché svanire. Dietro ogni 웃 sta ♡, l'Intenzione Condivisa, che porta il perché un compito è stato approvato fin dall'inizio, e ◬, l'accelerazione testimoniata che un compito ha prodotto rispetto a una base di riferimento congelata — solo un delta, mai da confondere con un indicatore di profitto. Il pilota esiste per dimostrare che questi tre glifi possono muoversi insieme onestamente, regione dopo regione, prima che il quadro si espanda oltre i suoi fondatori.

Quando il valore raggiunge una persona, la raggiunge tramite Livelihood Direct — 🏠 — canali locali qualificati e autorizzati che eXeL non custodisce mai come fondo proprio. La classificazione precede sempre la liquidazione, e il riconoscimento di un contributo non condiziona mai un letto per la notte; solo il ruolo di una persona in un compito definito lo fa. Anche la crescita oltre il pilota è vincolata: ogni cubo del quadro passa da Manuale a Semi-Automatizzato ad Autonomo solo dopo aver superato la regola dell'11,1 percento, una parte su nove di miglioramento misurato, guadagnata cubo per cubo e mai rivendicata in blocco — e mai, in nessuna circostanza, sopra il livello sovrano di significato, denaro e legge. È così che tre visionari per regione, tre regioni e un inizio diventano una promessa di cinquecento anni: non muovendosi in fretta, ma dimostrando, alla vista di tutti, che ogni passo ha guadagnato il passo successivo.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Imparare Attraverso la Simulazione`,
    content: {
      7: `Esercitarsi mille volte prima di toccare.`,
      33: `Nulla di rilevante si impara per la prima volta su hardware reale. Ogni cittadino può esercitarsi in simulazione, ruotare tra tre regioni, festeggiare — rispetto per il giovane essere umano il cui primo errore non dovrebbe mai costare una vita.`,
      111: `Ogni disciplina degna di essere padroneggiata è stata appresa da qualcuno prima di essere conosciuta. L'Accordo di Atlantide riporta questa antica saggezza al centro del modo in cui i giovani — e ogni cittadino che vi aderisce — vengono preparati a costruire il futuro. Nulla di rilevante si impara per la prima volta su hardware reale, su persone reali, o in condizioni irreversibili; non serve il permesso di alcun governo né la benedizione di alcun datore di lavoro. Ogni partecipante si esercita in simulazione finché la pratica non diventa competenza, e poi prontezza. Il modello di rotazione porta ogni partecipante attraverso le tre regioni fondatrici, e ogni rotazione si conclude con una celebrazione pubblica aperta alla comunità ospitante. Questo è rispetto per il giovane essere umano il cui primo errore non dovrebbe mai costare una vita.`,
      333: `Ogni disciplina degna di essere padroneggiata è stata appresa da qualcuno prima di essere conosciuta. I maestri artigiani provano prima di esibirsi, i piloti prima di volare, i medici prima di operare, i bambini attraverso il gioco. L'Accordo di Atlantide riporta questa antica saggezza al centro del modo in cui i giovani — e ogni cittadino che vi aderisce, senza bisogno del permesso di alcun governo né della benedizione di alcun datore di lavoro — vengono preparati a costruire il futuro. Nulla di rilevante si impara per la prima volta su hardware reale, su persone reali, o in condizioni irreversibili. Ogni partecipante si esercita in simulazione finché la pratica non diventa competenza, e poi prontezza. Questo non è prudenza — è rispetto per il giovane essere umano il cui primo errore non dovrebbe mai costare la vita a nessuno.

Il modello di rotazione dell'accordo porta ogni partecipante attraverso le tre regioni fondatrici. Ciò che si impara in Cambogia viene affinato in Honduras e completato ad Austin. Ciò che si scopre ad Austin viene messo in discussione in Cambogia e integrato in Honduras. Ogni partecipante vive, apprende ed è seguito da mentori attraverso culture che altrimenti resterebbero distanti. Il curriculum formativo attinge a tradizioni di simulazione disciplinata da molte culture — dalla tradizione di educazione strategica di Sun Tzu, dalla pratica-attraverso-il-gioco di Musashi, dalla teoria dell'apprendimento ciclico di Ibn Khaldun, dalla dialettica monastica di Nalanda, dal simulatore di volo civile — sintetizzate nel rispetto di ogni fase cognitiva e di ogni eredità culturale. Nessuna singola tradizione domina.

Ogni rotazione si conclude con una celebrazione pubblica aperta alla comunità ospitante, dove vicini, famiglie e visitatori vedono ciò che la coorte ha imparato. Questi eventi rendono la tecnologia sofisticata accessibile e celebrata anziché temibile — una società che cresce comprendendo i sistemi cooperativi attraverso il gioco non può essere facilmente manipolata dalla paura di essi. Questa è deterrenza attraverso l'educazione, non attraverso la forza. La promessa dell'accordo a ogni genitore: tuo figlio si eserciterà mille volte in sicurezza prima di toccare qualsiasi cosa possa fargli del male, il tutto testimoniato così che un cittadino — qualsiasi cittadino, tra un secolo — possa verificare che sia accaduto esattamente come registrato. Questo è rispetto per il giovane essere umano incorporato in un quadro, ed è ciò che la leadership deve al prossimo cittadino che vi aderisce, prima che quel cittadino debba pretenderlo.`,
      999: `Ogni disciplina degna di essere padroneggiata è stata appresa da qualcuno prima di essere conosciuta, e ogni civiltà che è durata lo ha fatto perché ha protetto lo spazio in cui quell'apprendimento poteva avvenire in sicurezza, prima che gli venisse chiesto di contare davvero. I maestri artigiani provano prima di esibirsi, i piloti provano prima di volare, i medici provano prima di operare, e i bambini provano il mondo attraverso il gioco. L'Accordo di Atlantide riporta questa antica saggezza al centro del modo in cui i giovani vengono preparati a costruire il futuro, e dà a quella saggezza un nome e un meccanismo: Replay. Nulla di rilevante si impara per la prima volta su hardware reale, su persone reali, o in condizioni irreversibili. Ogni partecipante si esercita in simulazione finché la pratica non diventa competenza, e poi prontezza, e ogni ora di quella pratica viene registrata affinché possa essere ricostruita in seguito, esaminata in seguito, considerata affidabile in seguito. Questo non è prudenza — è rispetto per il giovane essere umano il cui primo errore non dovrebbe mai costare la vita a nessuno, ed è rispetto per il registro che, in ogni caso, sopravviverà all'errore stesso.

Il modello di rotazione dell'accordo porta ogni partecipante attraverso le tre regioni fondatrici. Ciò che si impara in Cambogia viene affinato in Honduras e completato ad Austin. Ciò che si scopre ad Austin viene messo in discussione in Cambogia e integrato in Honduras. Ogni partecipante vive, apprende ed è seguito da mentori attraverso culture che altrimenti resterebbero distanti, e ogni rotazione inizia nel modo in cui inizia ogni istituzione umana degna di fiducia: con un Seed. Il Seed è un'iscrizione una tantum, al prezzo di un settimo di un'ora al salario minimo locale, non trasferibile, priva di qualsiasi rivendicazione economica. Non è una tariffa per accedere a un'opportunità. È una soglia — abbastanza piccola perché nessun partecipante volenteroso ne sia escluso per il prezzo, abbastanza deliberata perché l'ingresso sia scelto, non subìto per inerzia. Da quella soglia in poi, ogni partecipante appartiene alla rotazione, e la rotazione non appartiene a una sola regione.

Il curriculum formativo attinge a tradizioni di simulazione disciplinata da molte culture — dalla tradizione di educazione strategica di Sun Tzu, dalla pratica-attraverso-il-gioco di Musashi, dalla teoria dell'apprendimento ciclico di Ibn Khaldun, dalla dialettica monastica di Nalanda, dal simulatore di volo civile — sintetizzate nel rispetto di ogni fase cognitiva e di ogni eredità culturale. Nessuna singola tradizione domina. E all'interno di questo curriculum, l'accordo traccia una linea che ogni partecipante impara presto e non dimentica mai: la simulazione è dove il Qualified Innovation Score si comprende, non dove si spende. Il QIS è misurazione, mai pagamento, e non è mai proprietà — esiste per descrivere quanto bene una proposta regge, tiene e serve la regione che dichiara di servire. La crescita del QIS può dimensionare un fondo ricompense dopo una qualificazione reale, ma non conia nulla da sola. Un partecipante può condurre cento simulazioni impeccabili e vedere crescere il proprio punteggio senza che una sola ora di 웃 tocchi il suo registro, perché il 웃 viene emesso solo per lavoro testimoniato svolto nell'ambito di un compito definito e approvato a budget. Prima di quell'approvazione, tutto — per quanto abile, per quanto promettente — è pianificazione. L'accordo insegna questa distinzione fin dal primo giorno, affinché nessun giovane confonda la prova con la ricompensa, e nessun giovane venga mai fuorviato su a cosa serva la simulazione.

Questa stessa disciplina governa quanta autonomia sia consentito esercitare, all'interno della rotazione, a qualsiasi sistema, umano o artificiale. Le modalità operative dell'accordo si susseguono in sequenza — Manuale, poi Semi-Automatizzata, poi Autonoma — e nessun cubo avanza di modalità finché non supera la regola dell'11,1 percento di miglioramento misurato, una parte su nove, dimostrata rispetto a una base di riferimento congelata e testimoniata, non semplicemente dichiarata. La simulazione è dove quella prova viene costruita. Uno strumento guadagna il diritto di agire con meno supervisione allo stesso modo in cui un partecipante guadagna il diritto a maggiore responsabilità: attraverso un miglioramento dimostrato, registrato, ricostruibile, cubo per cubo, mai tutto in una volta, e mai sopra il livello in cui si decidono significato, denaro e legge. Quel livello appartiene esclusivamente all'Autorità Umana, in simulazione come in esercizio reale, perché uno spazio di prova che insegna il confine sbagliato insegna la lezione sbagliata in modo permanente.

Ogni rotazione si conclude con una celebrazione pubblica e cooperativa aperta alla comunità ospitante. Vicini, famiglie e visitatori si riuniscono per vedere ciò che la coorte ha imparato, e ciò a cui assistono non è una dimostrazione di velocità fine a se stessa, ma una dimostrazione di ◬ — il delta misurato tra una base di riferimento congelata e ciò che la pratica disciplinata ha effettivamente raggiunto, presentato onestamente, mai travestito da indicatore di profitto, mai presentato come più di quello che è. Questi eventi rendono la tecnologia sofisticata accessibile e celebrata anziché temibile. Una società che cresce comprendendo i sistemi cooperativi attraverso il gioco non può essere facilmente manipolata dalla paura verso quei sistemi. Questa è deterrenza attraverso l'educazione, non deterrenza attraverso la forza, e funziona perché alla comunità non si chiede di fidarsi di un'affermazione — la si invita a guardare il Replay.

La promessa dell'accordo a ogni genitore va oltre la sicurezza, fino a raggiungere la permanenza: tuo figlio si eserciterà mille volte prima di toccare qualsiasi cosa possa fargli del male, la comunità testimonierà la sua crescita in ogni fase, e nulla di tutto ciò andrà perso nel tempo. La Misurazione del Tempo registra i minuti reali separatamente da ogni altro registro che l'accordo tiene, così che le ore di pratica e le ore testimoniate non vengano mai confuse tra loro, e così che la vera storia di crescita di un partecipante — non un riassunto, non un'approssimazione, ma il registro stesso, ricostruibile — resti disponibile a quel partecipante finché desidera consultarla. Un genitore a Phnom Penh, un mentore a Tegucigalpa, un revisore ad Austin, o un nipote che legge il registro tra un secolo, possono tutti accedere allo stesso Replay e vedere la stessa verità.

Ecco come appare il rispetto per il giovane essere umano quando è incorporato in un quadro anziché semplicemente promesso da esso, ed ecco cosa la leadership consegna alla prossima generazione di partecipanti prima che quella generazione debba pretenderlo: uno spazio di prova abbastanza ampio da poter fallire in sicurezza, abbastanza onesto da registrare fedelmente, e abbastanza disciplinato da mantenere ricompensa, autonomia e autorità esattamente dove la maestria le ha guadagnate — mai un passo avanti, mai un passo indietro.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Sicurezza Provata Prima che la Fiducia Sia Estesa`,
    content: {
      7: `Prima provata la sicurezza, poi estesa la fiducia.`,
      33: `Ogni struttura e ogni rotazione si trova all'interno di un involucro protettivo con allarme precoce. L'hardware rifiuta la militarizzazione — dimostrabile, non promessa, ispezionabile dai cittadini. I registri sopravvivono alle turbolenze. La sicurezza è progettata ogni giorno attorno al partecipante più giovane.`,
      111: `Prima che venga estesa fiducia, la sicurezza deve essere dimostrata — non a un governo, ma a qualsiasi cittadino che la ispezioni. L'Accordo di Atlantide è un patto tra i cittadini del mondo; il suo impegno fondativo è questo: ogni struttura dell'accordo, ogni percorso di rotazione, ogni luogo in cui un giovane partecipante dorme o studia si trova all'interno di un involucro protettivo documentato, dotato di capacità di allarme precoce che dà alla comunità ore, non minuti, per rispondere a qualsiasi rischio credibile. Ogni dispositivo, ogni sensore, ogni sistema di coordinamento è vincolato a livello hardware a rifiutare la riconversione per l'integrazione in sistemi d'arma. Questo non è una politica — è fisica. L'accordo resta onorevole attraverso le turbolenze, perché ogni piano pone al primo posto la dignità umana.`,
      333: `Prima che venga estesa fiducia, la sicurezza deve essere dimostrata — dimostrata ai cittadini, non semplicemente dichiarata. L'Accordo di Atlantide è un patto tra i cittadini del mondo: qualsiasi persona, ovunque, può contribuire a custodirlo, indipendentemente da ciò che il proprio governo firma. Ogni struttura dell'accordo, ogni percorso di rotazione, ogni luogo in cui un giovane partecipante dorme o studia si trova all'interno di un involucro protettivo documentato, dotato di capacità di allarme precoce che dà alla comunità ore, non minuti, per rispondere a qualsiasi rischio credibile. La tecnologia che li protegge è la stessa tecnologia che l'accordo insegna loro a costruire. I giovani imparano la sicurezza dall'interno verso l'esterno, non perché venga detto loro che sono al sicuro, ma vedendola progettata attorno a sé ogni giorno, e sapendo che qualsiasi cittadino può verificare il registro attraverso Replay.

L'accordo fa una promessa incrollabile su ciò che la sua tecnologia non può diventare. Ogni dispositivo, ogni sensore, ogni sistema di coordinamento è vincolato a livello hardware a rifiutare la riconversione per l'integrazione in sistemi d'arma. Questo non è un linguaggio di policy, non è un'aspirazione. È un'impossibilità fisica, applicata crittograficamente, verificata da ogni regione firmataria, e ispezionabile da ogni cittadino che la finanzia. Gli strumenti che proteggono un bambino a Phnom Penh non possono essere riconvertiti per fare del male a un bambino ad Austin. Gli strumenti che collegano un'esercitazione di sciame a Tegucigalpa non possono essere riconfigurati per colpire un essere umano in nessun luogo. Questa è la risposta dell'accordo a un secolo di timori sul duplice uso. Non policy — fisica.

L'accordo resta onorevole attraverso le turbolenze. Se una regione perde stabilità politica, i partecipanti vengono sostenuti dalle regioni rimanenti. Se i finanziamenti si contraggono, le indennità vengono protette per prime — finanziate mensilmente dai cittadini, mai un canale di aiuti, ogni dollaro tracciabile. Se i registri digitali vengono attaccati, i backup offline persistono. Se i viaggi diventano impossibili, il substrato continua in forma virtuale. Ogni piano pone la dignità umana — l'Autorità Umana su significato, denaro e legge — come primo vincolo di progettazione. I leader che firmano questo accordo promettono che la sicurezza è progettata, non presunta: la protezione che qualsiasi leader pretenderebbe per il proprio figlio, estesa ora a ogni cittadino che contribuisce a custodirlo.`,
      999: `Prima che venga estesa fiducia, la sicurezza deve essere dimostrata — questo è l'impegno fondativo dell'Accordo di Atlantide, e viene dimostrato nello stesso modo in cui viene dimostrata ogni altra affermazione dentro Vision • 2525: non per asserzione, ma con prove che i cittadini possono ispezionare. Ogni struttura dell'accordo, ogni percorso di rotazione, ogni luogo in cui un giovane partecipante dorme o studia si trova all'interno di un involucro protettivo documentato, dotato di capacità di allarme precoce che dà alla comunità ore, non minuti, per rispondere a qualsiasi rischio credibile. La tecnologia usata per proteggere i partecipanti è la stessa tecnologia che l'accordo insegna loro a costruire — sensori, coordinamento, sopravvivenza delle comunicazioni, intelligenza distribuita. I giovani imparano la sicurezza dall'interno verso l'esterno, nella propria lingua e nella propria regione, non perché venga detto loro che sono al sicuro, ma osservando, ora dopo ora, come la sicurezza venga progettata attorno a loro ogni giorno.

Quella osservazione non è affidata alla memoria o alla fiducia nella parola di un facilitatore. La Misurazione del Tempo registra i minuti reali di ogni esercitazione, ogni rotazione, ogni prova di risposta — separatamente da qualsiasi affermazione di progresso, separatamente da qualsiasi racconto fatto quel giorno. Replay rende pienamente ricostruibile ogni pubblicazione del curriculum formativo, ogni aggiornamento di sicurezza, ogni revisione dell'hardware, così che un genitore a Tegucigalpa o un'autorità di regolamentazione a Phnom Penh possa ripercorrere all'indietro esattamente cosa è cambiato, quando è cambiato e perché è cambiato. Un involucro protettivo che non può essere ripercorso con Replay è solo una promessa. Un involucro protettivo che può essere ripercorso, minuto per minuto registrato, è una prova. L'accordo sceglie la prova.

L'accordo fa una promessa incrollabile su ciò che la sua tecnologia non può diventare. Ogni dispositivo, ogni sensore, ogni sistema di coordinamento è vincolato a livello hardware a rifiutare la riconversione per l'integrazione in sistemi d'arma. Questo non è un linguaggio di policy, non è un'aspirazione. È un'impossibilità fisica, applicata crittograficamente, verificata da ogni regione firmataria, e ispezionabile da ogni cittadino. Gli strumenti che proteggono un bambino a Phnom Penh non possono essere riconvertiti per fare del male a un bambino ad Austin. Gli strumenti che collegano un'esercitazione di sciame a Tegucigalpa non possono essere riconfigurati per colpire un essere umano in nessun luogo. Questa è la risposta dell'accordo a un secolo di timori sul duplice uso. Non policy — fisica.

Una sicurezza dimostrata una sola volta non è una sicurezza sostenuta lungo un orizzonte di cinquecento anni. L'accordo chiama il suo secondo impegno Continuità Senza Evasione: portabilità lecita attraverso ogni giurisdizione toccata dall'accordo, senza che un singolo governo, banca, fondatore o modello indispensabile si frapponga tra un partecipante e la sua protezione. Ogni giurisdizione è servita dal proprio adattatore, a chiusura sicura e in modalità default-deny, così che una decisione sfavorevole in una qualsiasi regione chiuda solo quel canale — mai l'intero quadro, mai ogni regione, mai ogni partecipante ovunque nello stesso momento. Una decisione giudiziaria in un territorio firmatario non può disattivare l'involucro di sicurezza di un partecipante altrove. Questo è ciò che significa costruire un sistema che sopravvive alle normali turbolenze del diritto, della politica e del cambiamento istituzionale, senza mai chiedere a un partecipante di eludere la legge per restare protetto.

Ogni livello di questa architettura protettiva risponde, in ultima analisi, all'Autorità Umana. Significato, denaro e legge non sono mai delegati alle macchine — il livello sovrano che decide cosa richieda la sicurezza, cosa costituisca un rischio credibile e quale risposta una comunità debba ai suoi membri più giovani resta precluso all'intelligenza artificiale, per quanto capace possa diventare. I sistemi dell'accordo attraversano soltanto tre modalità operative — Manuale, Semi-Automatizzata, Autonoma — e nessun sistema avanza di modalità senza un miglioramento testimoniato e misurato di almeno una parte su nove, l'undici virgola uno percento, verificato, riproducibile. L'autonomia si guadagna, cubo per cubo, funzione per funzione, mai concessa in blocco, e mai estesa sopra le questioni che determinano significato, denaro o legge. Un sensore può imparare a rilevare più velocemente. Un sistema di coordinamento può imparare a instradare in modo più efficiente. A nessuno dei due è mai permesso decidere, da solo, cosa una comunità debba affidare ai propri figli.

L'accordo è progettato per restare onorevole attraverso le turbolenze, e nomina la turbolenza in anticipo anziché scoprirla in piena crisi. Se una regione firmataria perde stabilità politica, i partecipanti vengono sostenuti dalle regioni rimanenti. Se i finanziamenti si contraggono, le indennità dei partecipanti vengono protette per prime, prima dell'amministrazione e dell'infrastruttura. Se i registri digitali vengono attaccati, i backup offline persistono, irraggiungibili da qualsiasi guasto abbia colpito la rete. Se i viaggi diventano impossibili, il substrato continua in forma virtuale, così che una rotazione non si fermi perché un confine si è chiuso. Ogni scenario è pianificato in anticipo, e ogni piano pone la dignità umana come primo vincolo di progettazione — non come ultima considerazione una volta sistemati budget e immagine pubblica.

L'ingresso in questo sistema comprovato inizia con il Seed — un'iscrizione una tantum, al prezzo di un settimo di un'ora al salario minimo locale, non trasferibile, e priva di qualsiasi rivendicazione economica su tutto ciò che l'accordo costruirà in seguito. Il Seed non compra sicurezza; la sicurezza è progettata molto prima che qualsiasi Seed venga mai piantato. Ciò che il Seed compra è la posizione — il diritto di entrare in un quadro già comprovato, già ispezionato, già vincolato da un hardware che non può essere rivolto contro la stessa persona che esiste per proteggere. Questa separazione è deliberata. Una promessa di sicurezza che debba essere acquistata con un peso economico reale non è affatto una promessa di sicurezza, ma solo un prodotto di sicurezza. L'accordo tiene le due cose rigorosamente separate, così che nessuna famiglia debba mai soppesare la protezione del proprio figlio contro il bilancio mensile della casa.

I leader che firmano questo accordo firmano una promessa: che la sicurezza è progettata, non presunta, e dimostrata, non semplicemente dichiarata. Ciò che estendono ai propri cittadini non è soltanto opportunità, ma una protezione costruita allo standard che il partecipante più giovane merita — registrata dalla Misurazione del Tempo, ricostruibile attraverso Replay, vincolata a livello hardware contro ogni abuso che un secolo timoroso abbia immaginato, e responsabile, sempre e soltanto, verso l'Autorità Umana. È la stessa protezione che qualsiasi leader pretenderebbe per il proprio figlio nell'attraversare da solo un confine sconosciuto, ora estesa a ogni bambino che l'accordo servirà, attraverso le sue tre regioni fondatrici di Cambogia, Honduras e Austin, e attraverso i cinque secoli in cui l'accordo intende mantenere questa promessa.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Compenso, Benessere e Dignità Umana`,
    content: {
      7: `Una borsa, un mentore, una casa.`,
      33: `Ogni cittadino riceve un'indennità fin dal primo giorno — senza il permesso di alcun governo, senza la benedizione di alcun datore di lavoro. Amore, perdita e sicurezza sono infrastruttura. Il successo si misura dal partecipante più vulnerabile. La dignità è substrato, mai decorazione.`,
      111: `L'Accordo di Atlantide tratta ogni partecipante come un essere umano fin dal primo giorno — un cittadino che ha aderito per diritto, non per decreto governativo o concessione del datore di lavoro. Un'indennità viene erogata dal momento in cui inizia la partecipazione, indicizzata al costo della vita della regione, e ogni ora testimoniata guadagna 웃, pagato alla persona tramite Livelihood Direct, mai attraverso il registro di un datore di lavoro. Il benessere è trattato come infrastruttura di prim'ordine — non un privilegio, ma il substrato su cui tutto poggia. Vengono sostenuti tre ambiti: Amore, Perdita e Sicurezza. L'accordo misura il successo dal suo partecipante più vulnerabile, non dalla media. Nessuno viene dimenticato perché le medie sembrino migliori. Dignità come substrato, non come decorazione.`,
      333: `L'Accordo di Atlantide tratta ogni partecipante come un essere umano fin dal primo giorno — un cittadino che appartiene per diritto, senza bisogno del permesso di alcun governo né della benedizione di alcun datore di lavoro. Un'indennità viene erogata dal momento in cui inizia la partecipazione, indicizzata al costo della vita della regione, e arriva prima che gli obblighi familiari diventino emergenze. Questo non è carità. È il riconoscimento che l'innovazione umana ordinaria richiede prima di tutto sicurezza umana — una mente non può fiorire mentre la propria famiglia è sotto minaccia.

Ciò che si guadagna oltre l'indennità si guadagna come lo guadagna un cittadino: tramite il Seed, al prezzo di un settimo di un'ora al salario minimo locale, e tramite il 웃, pagato solo per le ore testimoniate. Il QIS misura la promessa ma non conia nulla — misurazione, mai pagamento. Ogni pagamento raggiunge il partecipante tramite Livelihood Direct, canali locali autorizzati che l'accordo non custodisce mai, costruiti per la Continuità Senza Evasione.

Il benessere è trattato come infrastruttura di prim'ordine — non un privilegio, ma il substrato su cui tutto poggia. L'accordo nomina tre ambiti in cui ogni partecipante viene sostenuto: Amore, inteso come connessione e confine sano; Perdita, poiché il lutto va accompagnato, non aggirato; e Sicurezza, sapere chi chiamare, in ogni regione, nella propria lingua. Vengono forniti supporto psicologico, cerchi di gruppo e pratiche culturali o spirituali onorate secondo la tradizione di ciascuno. Zero ideologia imposta; è l'Autorità Umana, mai una macchina, a decidere di quale cura un cittadino abbia bisogno.

L'accordo misura il successo dal suo partecipante più vulnerabile, non dalla media. I cittadini rurali senza connessioni ad alta banda vengono serviti. I partecipanti neurodivergenti ricevono accomodamenti come norma, non come eccezione. I partecipanti con disabilità trovano ogni struttura accessibile. I partecipanti di genere diverso ricevono alloggi sicuri e abbinamento con mentori. Chi non parla la lingua locale come madrelingua trova ogni documento nella propria lingua. I partecipanti indigeni trovano le proprie pratiche culturali onorate e il proprio sapere tradizionale protetto. I leader che firmano questo accordo promettono che nessun cittadino verrà dimenticato perché le medie sembrino migliori. Questa è dignità come substrato, non come decorazione. Ciò che viene misurato è ciò che verrà onorato, e ciò che qui si onora è l'essere umano intero — mente, corpo e spirito, sostenuto dai propri concittadini, senza eccezioni.`,
      999: `L'Accordo di Atlantide tratta ogni partecipante come un essere umano a tutti gli effetti fin dal primo giorno, incorporato nel meccanismo, non semplicemente affermato a parole. Un'indennità viene erogata dal momento in cui inizia la partecipazione, indicizzata al costo della vita della regione affinché il suo impatto rispetti la dignità locale del lavoro. L'indennità arriva prima che gli obblighi familiari diventino emergenze, e prima che la dignità venga compromessa. Segnala a ogni giovane che il proprio tempo ha valore, che il proprio contributo è atteso, e che la stabilità della propria famiglia fa parte della responsabilità dell'accordo. Questo non è carità. È il riconoscimento che l'innovazione umana ordinaria richiede prima di tutto sicurezza umana. Una mente non può fiorire mentre la propria famiglia è sotto minaccia. L'ingresso stesso comporta una soglia piccola e deliberata: il Seed, un'iscrizione una tantum al prezzo di un settimo di un'ora al salario minimo locale, non trasferibile e priva di qualsiasi rivendicazione economica propria. Il Seed dichiara soltanto che una persona ha aderito; non la paga né le promette nulla al di là della porta che apre.

Ciò che si guadagna una volta varcata quella porta è governato con la stessa precisione che l'accordo porta a ogni altra promessa. Il 웃, la misura dell'Intelligenza Umana secondo l'accordo, si calcola in modo semplice — un'ora al salario minimo locale, moltiplicata per il Moltiplicatore che riflette la difficoltà e il valore del compito, per le ore effettivamente lavorate. Ma il 웃 viene emesso solo per lavoro testimoniato svolto nell'ambito di un compito definito e approvato a budget. Prima che tale approvazione esista, ciò che un partecipante sta facendo è pianificazione, non guadagno — una distinzione che l'accordo mantiene fermamente perché protegge sia il tesoro sia il partecipante da promesse fatte più in fretta di quanto il valore possa essere verificato. La Misurazione del Tempo, MoT, registra i minuti effettivamente lavorati separatamente da qualsiasi calcolo di compenso, così che il tempo resti un fatto onesto e verificabile, indipendente dal pagamento. Le ore di nessun partecipante vengono gonfiate, e le ore di nessun partecipante svaniscono. Un tetto di liquidazione di 9.999 웃 all'anno si applica a ogni partecipante, con qualsiasi eccedenza riportata all'anno successivo anziché scomparire, così che un contributo eccezionale venga riconosciuto lungo più anni anziché essere reso invisibile entro uno solo.

Il compenso viene deliberatamente tenuto distinto dalla misurazione dell'innovazione. Il Qualified Innovation Score, QIS, fa la media di Ricavi, Utile Lordo, Reddito Operativo e spesa Effettiva in R&S per descrivere quanto l'innovazione sia realmente cresciuta. La sua crescita nel tempo può dimensionare un fondo ricompense una volta soddisfatta la qualificazione, ma il QIS in sé non conia alcun 웃 e non liquida nulla direttamente — è una misurazione, mai un pagamento, e non va mai confuso con la proprietà di ciò che è stato costruito. Questa separazione conta perché mantiene onesti l'indennità e il salario: un partecipante viene pagato per ore testimoniate di lavoro reale, non per un punteggio che potrebbe essere manipolato, gonfiato o contestato. ♡, l'Intenzione Condivisa, porta il perché dietro ogni compito che un partecipante intraprende; ◬, l'accelerazione testimoniata che un compito produce rispetto a una base di riferimento congelata, viene registrata solo come delta, mai travestita da indicatore di profitto legato al lavoro di una persona. Il compenso resta ciò che è: un salario onesto per un tempo onesto e testimoniato.

Il valore non si ferma al calcolo — deve anche raggiungere il partecipante come persona vivente, ed è qui che 🏠, Livelihood Direct, svolge il suo compito. Ogni unità di valore guadagnata da un partecipante lo raggiunge attraverso canali locali qualificati e autorizzati — banche, operatori di mobile-money, cooperative già affidabili e regolamentate in quella regione — mai attraverso un fondo che l'accordo stesso custodisce o controlla. La classificazione dello status di un partecipante precede sempre la liquidazione; nulla viene pagato prima che si sia correttamente compreso chi venga pagato e per cosa. E il riconoscimento del talento, per quanto celebrato, non condiziona l'accesso a un letto, a un pasto o a un posto nella coorte — solo il ruolo effettivo del partecipante lo fa. È un rifiuto deliberato di lasciare che il prestigio sostituisca il sostentamento. Un contributore brillante e uno silenzioso dormono sotto lo stesso tetto protetto, alle stesse condizioni, perché gli impegni di dignità dell'accordo non sono un premio assegnato per l'eccellenza — sono un pavimento sotto tutti.

Il benessere è trattato come infrastruttura di prim'ordine — non un beneficio opzionale, non un privilegio di wellness, ma il substrato su cui poggia tutto il resto. L'accordo nomina tre ambiti fondamentali in cui ogni partecipante viene sostenuto: Amore, nel senso di connessione, attaccamento e confine sano; Perdita, poiché ogni partecipante attraverserà il lutto e deve essere accompagnato, non aggirato; e Sicurezza, nel senso che ogni partecipante sa chi chiamare, in ogni regione, nella propria lingua. Vengono forniti supporto psicologico individuale, cerchi di gruppo, pratiche somatiche e pratiche culturali o spirituali onorate secondo la tradizione propria di ciascun partecipante. Zero ideologia imposta. L'accordo tiene questo spazio con riverenza; non fa proselitismo di alcun sistema di credenze. L'Autorità Umana governa ognuna di queste decisioni — significato, denaro e legge restano preclusi alla determinazione automatica, per quanto sofisticato sia il riconoscimento di schemi che assiste gli esseri umani che decidono.

L'accordo misura il successo dall'esito del suo partecipante più vulnerabile, non dalla media. I partecipanti rurali senza connessioni ad alta banda vengono serviti. I partecipanti neurodivergenti ricevono accomodamenti come norma. I partecipanti con disabilità trovano ogni struttura accessibile. I partecipanti di genere diverso ricevono alloggi sicuri e abbinamento con mentori. Chi non parla la lingua locale come madrelingua trova ogni documento nella propria lingua. I partecipanti indigeni trovano le proprie pratiche culturali onorate e il proprio sapere tradizionale protetto. I leader che firmano questo accordo promettono che nessun partecipante verrà dimenticato in silenzio perché le medie sembrino migliori.

Ogni percorso di pagamento qui descritto — il Seed, l'indennità, il 웃 guadagnato sul lavoro testimoniato, il canale Livelihood Direct che lo consegna — è progettato per la Continuità Senza Evasione. Nessuna singola banca, governo o operatore locale è indispensabile al compenso di alcun partecipante; se un canale autorizzato in una giurisdizione viene chiuso da una decisione sfavorevole, è quel canale soltanto a fallire, mai l'intero sistema, e mai la rivendicazione del partecipante su ciò che gli era dovuto. Questa è dignità come substrato, non come decorazione. Ciò che viene misurato è ciò che verrà onorato, e ciò che qui si onora è l'essere umano intero — mente, corpo e spirito insieme, pagato onestamente, protetto pienamente, e dimenticato da nessuna contabilità, senza eccezione alcuna.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finanziamento e Governance`,
    content: {
      7: `I cittadini finanziano la prossima generazione direttamente.`,
      33: `L'Accordo di Atlantide è un patto tra cittadini — chiunque può finanziarlo e custodirlo. Nessun canale di aiuti, nessun benefattore straniero, nessun vincolo politico. Ogni dollaro tracciabile, contabilità pubblicata ogni mese, in ogni lingua.`,
      111: `L'Accordo di Atlantide è un patto tra i cittadini del mondo — qualsiasi persona, ovunque, può contribuire a crearlo e custodirlo, indipendentemente da ciò che il proprio governo firma o da chi la impiega. Governi, educatori e innovatori firmano come custodi delle proprie regioni; sono i cittadini a finanziare l'accordo, a testimoniarlo e a chiederne conto direttamente, ciascuno contribuendo con piccole somme volontarie ogni mese, abbastanza modeste perché nessun adulto ne sia escluso per il prezzo. Non c'è alcun canale di aiuti, nessun benefattore straniero, nessun vincolo politico allegato. L'accordo resta indipendente dalle istituzioni multilaterali che hanno plasmato il secolo scorso — non una dichiarazione politica, ma una scelta di progettazione. Ogni dollaro è tracciabile; ogni contabilità viene pubblicata ogni mese, in ogni lingua.`,
      333: `L'Accordo di Atlantide è un patto tra i cittadini del mondo — qualsiasi persona, ovunque, può contribuire a crearlo e custodirlo, indipendentemente da ciò che il proprio governo firma o da chi la impiega. È finanziato dai cittadini che serve: i residenti delle regioni partecipanti contribuiscono con piccole somme volontarie ogni mese, abbastanza modeste perché nessun adulto ne sia escluso per il prezzo, abbastanza consistenti nell'insieme da sostenere il lavoro dell'accordo su larga scala. Quando un cittadino finanzia direttamente la prossima generazione, quel cittadino chiede conto dell'accordo direttamente. Non c'è alcun canale di aiuti, nessun benefattore straniero, nessun vincolo politico allegato. L'anima dell'accordo è il cittadino che contribuisce con una piccola somma ogni mese, la cui partecipazione lo rende possibile.

Governo, Istruzione e Innovazione firmano come custodi delle proprie regioni — tre firme visionarie che vincolano una regione ad accogliere, proteggere e insegnare — ma la custodia non è proprietà. L'accordo è indipendente dalle istituzioni multilaterali che hanno plasmato il secolo scorso — l'Organizzazione del Trattato del Nord Atlantico, l'Organizzazione Mondiale della Sanità, le Nazioni Unite, il Fondo Monetario Internazionale, la Banca Mondiale, e ogni canale nazionale di aiuti esteri. Questa è una scelta di progettazione, non una dichiarazione politica: un quadro che serve ogni regione a prescindere dall'allineamento geopolitico non può essere intrecciato con un solo allineamento. I governi nazionali possono contribuire volontariamente. I contributi sono trasparenti. Nessun contributo compra influenza sulla governance, da qualsiasi fonte provenga, mai.

Ogni dollaro e ogni unità di valore che entra nell'accordo viene registrato in modo permanente, pubblico e tracciabile — ricostruibile tramite Replay, così che un cittadino tra un secolo possa verificare la catena intatta. Il valore raggiunge un partecipante attraverso ore di 웃 testimoniate e canali locali autorizzati, mai un fondo che l'accordo stesso custodisce; il QIS misura onestamente, non paga mai. Le spese amministrative sono soggette a un tetto, e così pure le donazioni aziendali. La contabilità completa viene consegnata nella lingua di ogni regione firmataria ogni mese. I leader che firmano l'accordo promettono una trasparenza raramente offerta da qualsiasi istituzione. Questa è la fiducia che l'accordo richiede — guadagnata un piccolo contributo tracciabile alla volta, alla vista di ogni cittadino.`,
      999: `L'Accordo di Atlantide stesso è finanziato dai cittadini che serve, e questo unico fatto plasma tutto ciò che ne discende — ogni canale, ogni registro, ogni soglia che un giovane deve superare per essere visto. I comuni residenti delle regioni partecipanti contribuiscono con piccole somme volontarie ogni mese, somme abbastanza modeste perché nessun adulto in nessuna regione ospitante ne sia escluso per il prezzo, abbastanza consistenti nell'insieme da sostenere il lavoro dell'accordo su una scala significativa. Questa progettazione è deliberata, e non è incidentale rispetto alla missione — ne è la prova. Quando un cittadino finanzia direttamente l'istruzione della prossima generazione, quello stesso cittadino chiede conto dell'accordo direttamente, nello stesso respiro, senza un intermediario che possa attenuare il resoconto o ritardarne la resa dei conti. Non c'è alcun canale di aiuti, nessun benefattore straniero, nessun vincolo politico allegato all'assegno. L'anima dell'accordo è il cittadino che contribuisce con una piccola somma ogni mese, la cui partecipazione rende possibile il tutto, e la cui partecipazione continuata è l'unico voto di fiducia che conta davvero lungo cinquecento anni.

L'accordo è deliberatamente indipendente dalle istituzioni multilaterali che hanno plasmato il secolo scorso — l'Organizzazione del Trattato del Nord Atlantico, l'Organizzazione Mondiale della Sanità, le Nazioni Unite, il Fondo Monetario Internazionale, la Banca Mondiale, e ogni canale nazionale di aiuti esteri. Questa non è una dichiarazione politica sul valore di quelle istituzioni o dei loro contributi. È una scelta di progettazione, ed è la stessa scelta di progettazione che governa ogni canale tecnico sotto l'accordo stesso: la Continuità Senza Evasione. La portabilità lecita è la regola — nessun singolo governo, banca, fondatore o modello indispensabile può stare sotto l'intera struttura, perché un orizzonte di cinquecento anni non può essere scommesso sulla permanenza di un solo attore. Ogni giurisdizione porta il proprio adattatore, a chiusura sicura e in modalità default-deny, così che una decisione sfavorevole in una nazione chiuda solo quel canale, e soltanto quello — non fa mai cadere i conti di una famiglia in una regione dall'altra parte dell'oceano. I governi nazionali possono contribuire volontariamente. I contributi sono trasparenti. Nessun contributo compra influenza sulla governance, da qualsiasi fonte, mai — né da un governo, né da un'azienda, né dagli stessi fondatori del quadro.

L'Autorità Umana è il secondo pilastro portante sotto questa progettazione di finanziamento. Significato, denaro e legge restano questioni umane, decise da esseri umani alla vista di altri esseri umani; il livello sovrano in cui viene fissato lo scopo dell'accordo e vengono governati i suoi fondi resta precluso alle macchine, per quanto capaci possano diventare nei compiti sottostanti. La Misurazione del Tempo registra i minuti effettivamente lavorati separatamente da qualsiasi affermazione sul loro valore, così che nessuno — umano o artificiale — possa gonfiare silenziosamente il registro. Replay sta dietro ognuno di questi registri, rendendo ricostruibile dall'origine ogni pubblicazione che l'accordo stesso emetterà mai, per sempre aperta alla contestazione, per sempre aperta alla correzione. Un cittadino che oggi contribuisce con una piccola somma confida che tra cinquant'anni, tra duecento anni, qualcuno possa ancora ripercorrere la catena fino al registro di questo mese e trovarlo esattamente come era.

L'ingresso in questo sistema di fiducia inizia con il Seed — un'iscrizione una tantum, al prezzo di un settimo di un'ora al salario minimo locale, non trasferibile e priva di qualsiasi rivendicazione economica. Il Seed non compra alcuna quota, nessun voto ponderato dalla ricchezza, nessuna posizione privilegiata nella contabilità che segue. Compra soltanto l'appartenenza, a un prezzo abbastanza basso perché un giovane, ovunque l'accordo operi, possa permettersi di iniziare. Tutto ciò che un membro guadagna da quel punto in poi viene guadagnato, mai acquistato, e questa distinzione è l'intera architettura morale dell'accordo in miniatura.

Il valore che effettivamente fluisce verso una persona fluisce attraverso 🏠 Livelihood Direct — canali locali qualificati e autorizzati che portano il pagamento alla persona, mai verso un fondo che il quadro stesso custodisce o controlla. La classificazione precede sempre la liquidazione; un letto, un'indennità, un posto nella fase successiva della formazione è vincolato al ruolo e alla prontezza, mai al solo riconoscimento, perché il riconoscimento costa poco e il sostentamento no. Questa è la catena che il contributo mensile di un cittadino percorre realmente: dal conto del cittadino, attraverso un canale verificato, fino all'indennità che un giovane riceve, fino al progetto di innovazione in cui si trasforma il lavoro di quel giovane, e di nuovo verso l'esterno come un resoconto pubblico che qualsiasi cittadino può leggere.

Quanto vale quel lavoro viene misurato, non presunto. Il Qualified Innovation Score fa la media di prontezza, potenziale di crescita, impatto sui risultati e prontezza esecutiva in un unico numero, e la crescita di quel punteggio dimensiona il fondo ricompense solo dopo che la qualificazione è soddisfatta — il QIS in sé non conia nulla e non liquida nulla; è misurazione, mai pagamento, e qui la misurazione non viene mai confusa con la proprietà. Il pagamento per il lavoro umano arriva invece come 웃, valutato a un'ora moltiplicata per il salario minimo locale, per un moltiplicatore definito e approvato a budget delle ore effettivamente lavorate e testimoniate. Prima che un compito porti quell'approvazione, il lavoro dietro di esso è pianificazione, non lavoro compensabile, e nessuno viene pagato per pianificare. Un tetto di 9.999 웃 all'anno, con qualsiasi eccedenza riportata all'anno successivo anziché svanire, impedisce che il conto di un singolo anno diventi un colpo di fortuna o una trappola.

Nulla di tutto questo corre più veloce della propria prova. L'accordo stesso avanza da Manuale a Semi-Automatizzato ad Autonomo un cubo alla volta, e solo dove un intero ordine di miglioramento misurato — una parte su nove — è stato effettivamente dimostrato, mai presunto in anticipo. L'autonomia si guadagna esattamente lì, e in nessun luogo vicino a significato, denaro o legge, che restano sempre umani. Le spese amministrative sono soggette a un tetto. Le donazioni aziendali e istituzionali sono benvenute e soggette anch'esse a un tetto. La contabilità completa viene consegnata nella lingua di ogni regione firmataria ogni mese, a cominciare da Cambogia, Honduras e Austin, e destinata a essere consegnata, e resa leggibile, ancora tra cinquecento anni. Questa è la fiducia che l'accordo richiede. Questa è la fiducia che l'accordo guadagna, un piccolo contributo tracciabile alla volta, alla vista di ogni cittadino che servirà.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Scambio Interculturale e Contributo Globale`,
    content: {
      7: `Ogni studente nella propria lingua.`,
      33: `Ogni attività nella lingua del partecipante — aperta a qualsiasi cittadino, senza bisogno del permesso di alcun governo. Intelligenza Artificiale, Umana e Condivisa tenute in tensione produttiva. I curricula pubblicati apertamente. Ciò che una regione impara, tutti lo ereditano.`,
      111: `L'Accordo di Atlantide riporta l'educazione al suo scopo più profondo: lo scambio di saggezza attraverso confini che altrimenti dividerebbero. Qualsiasi cittadino può accedere a questo curriculum, indipendentemente da ciò che il proprio governo ha firmato. Ogni attività è disponibile nella lingua del partecipante, nella lingua della regione ospitante e in un registro condiviso. La lingua non è decorazione — la lingua è giurisdizione, la lingua è dignità resa leggibile. Il quadro educativo poggia sulla trinità delle intelligenze: l'Artificiale propone, l'Umana decide, l'Intento Condiviso convalida. Ogni studente impara a tenere tutte e tre in tensione. Ciò che l'accordo impara, lo restituisce. Curricula, risultati dell'innovazione, ricerca sul benessere e decisioni di governance vengono pubblicati apertamente. Ciò che una regione impara, tutti i cittadini lo ereditano.`,
      333: `L'Accordo di Atlantide riporta l'educazione al suo scopo più profondo: lo scambio di saggezza attraverso confini che altrimenti dividerebbero. Questo è un accordo tra i cittadini del mondo — qualsiasi cittadino può costruirlo e custodirlo, qualunque cosa il proprio governo abbia firmato. Ogni attività è disponibile nella lingua del partecipante, nella lingua della regione ospitante e in un registro condiviso, così che nessun partecipante navighi l'accordo in una lingua che non ha scelto. La lingua non è decorazione. La lingua è giurisdizione. La lingua è dignità resa leggibile. Un giovane in Cambogia legge il proprio registro d'indennità in khmer, in Honduras in spagnolo, ad Austin in inglese — tutte e tre onorate allo stesso modo, nessuna delle quali richiede la benedizione di un governo per iniziare.

Il quadro educativo poggia sulla trinità delle intelligenze che Vision • 2525 rende visibile. L'Intelligenza Artificiale propone schemi e possibilità più velocemente di quanto potrebbe fare un essere umano da solo. L'Intelligenza Umana decide su sicurezza, etica e direzione — domande a cui nessuna macchina dovrebbe rispondere, tenute sotto l'Autorità Umana. L'Intento Condiviso convalida che le decisioni servano i principi dell'accordo, così che nessun partecipante scelga l'eccellenza a discapito del bene collettivo. Nessuno studente si affida a una sola intelligenza; ogni studente impara a tenerle tutte e tre in tensione. L'appartenenza inizia con il Seed, un'iscrizione al prezzo di un settimo di un'ora al salario minimo locale — abbastanza piccola perché qualsiasi cittadino possa permettersela. Questo prepara la prossima generazione a governare, dove nessuna intelligenza agisce senza controllo.

Ciò che l'accordo impara, lo restituisce. I curricula vengono pubblicati con licenza aperta, così che qualsiasi regione — firmataria o meno — possa adattarli alla propria cultura locale. I risultati dell'innovazione vengono pubblicati. La ricerca sul benessere viene pubblicata in forma aggregata per i ricercatori di tutto il mondo. Le decisioni di governance vengono pubblicate con il loro ragionamento, così che qualsiasi cittadino, non solo un governo firmatario, possa verificarle — e Replay permette a quello stesso cittadino di ripercorrere il ragionamento tra un secolo. Il successo si misura non solo dai suoi partecipanti, ma dalle iniziative educative e culturali che sorgono sulla sua scia, in regioni che non hanno mai firmato il pilota eppure hanno costruito sulla sua saggezza condivisa. Ciò che una regione impara, ogni cittadino lo eredita.`,
      999: `L'Accordo di Atlantide riporta l'educazione al suo scopo più profondo: lo scambio di saggezza attraverso confini che altrimenti dividerebbero, e inizia quello scambio prima ancora che venga impartita una sola lezione. Il primo atto di ogni partecipante dentro il quadro è il Seed — un'iscrizione una tantum al prezzo di un settimo di un'ora al salario minimo locale, non trasferibile, priva di qualsiasi rivendicazione economica. È abbastanza piccola perché nessuna famiglia ne sia esclusa e abbastanza reale perché nessun partecipante entri come spettatore. Questa è la prima lezione dell'accordo: l'appartenenza si guadagna a poco prezzo, ma la si guadagna comunque, e non conferisce alcuna proprietà su ciò che viene dopo. Ogni attività dell'accordo che segue è disponibile nella lingua del partecipante, nella lingua della regione ospitante e in un registro condiviso, così che nessun partecipante navighi l'accordo in una lingua che non ha scelto. La lingua non è decorazione. La lingua è giurisdizione. La lingua è dignità resa leggibile. Quando un giovane di un villaggio cambogiano legge il proprio registro d'indennità in khmer, uno di una città honduregna in spagnolo, e uno di un quartiere di Austin in inglese, tutte e tre le lingue sono onorate allo stesso modo dallo stesso accordo, nelle stesse regioni fondatrici che per prime hanno accettato di insegnarsi reciprocamente.

Il quadro educativo dell'accordo poggia sulla trinità delle intelligenze che Vision • 2525 rende visibile, e il curriculum insegna ciascuna di esse come qualcosa che un partecipante può sentire tra le proprie mani, non come astrazione. ♡, l'Intenzione Condivisa, porta il perché — il filo che ogni studente impara a tenere prima di toccare qualsiasi strumento, la domanda se questo lavoro serva ancora le persone che dichiara di servire. ◬, l'accelerazione testimoniata, viene insegnata come un delta e nulla più — misurata solo rispetto a una base di riferimento congelata, mai travestita da indicatore di profitto, mai rivendicata come risultato personale separato dalla squadra che circonda il partecipante. 웃, l'Intelligenza Umana onorata nel tempo, viene insegnata con la massima cura: un'ora di lavoro testimoniato equivale a un'ora al salario minimo locale, e ciò che un partecipante guadagna è quel salario moltiplicato per le ore lavorate — Moltiplicatore per Tempo, nulla nascosto nell'aritmetica. Gli studenti imparano presto che il 웃 viene emesso solo per lavoro testimoniato svolto nell'ambito di un compito definito e approvato a budget. Prima che tale approvazione esista, lo stesso sforzo è solo pianificazione — prezioso, ma non pagato, e a ogni partecipante viene insegnato a riconoscere la differenza a colpo d'occhio.

Poiché quella differenza si offusca facilmente, il curriculum insegna il QIS, il Qualified Innovation Score, come uno specchio anziché un tabellone segnapunti. Il QIS è la media di quattro grandezze finanziarie assolute — Ricavi, Utile Lordo, Reddito Operativo e R&S Effettiva — divisa per quattro, e ogni studente impara a calcolarlo, a metterlo in discussione e a non confonderlo mai con il denaro. La crescita del QIS dimensiona il fondo ricompense solo dopo che la qualificazione è confermata in modo indipendente, e quella crescita non conia alcun 웃 da sola. Il QIS è misurazione. Il QIS non è mai pagamento. Il QIS non è mai proprietà. Uno studente che ha interiorizzato questa distinzione non può essere persuaso che un punteggio alto gli dia diritto a una rivendicazione che l'accordo non ha mai promesso.

Il curriculum estende questa alfabetizzazione al modo in cui il valore raggiunge realmente una persona, attraverso quello che l'accordo chiama Livelihood Direct — il principio 🏠 secondo cui il denaro si muove attraverso canali locali qualificati e autorizzati e mai attraverso un fondo che il quadro stesso custodisce. Agli studenti viene insegnato a tracciare la propria indennità, e in seguito i propri guadagni, attraverso questi canali come esercizio civico, non come un mistero finanziario svolto altrove per loro conto. Imparano che la classificazione precede sempre la liquidazione, e che il riconoscimento — un QIS alto, un elogio pubblico — non condiziona di per sé un letto, un'indennità o un posto nella rotazione. Lo fa il ruolo. Questa è protezione contro un fallimento molto antico: la lode scambiata per il sostentamento.

Accanto all'alfabetizzazione finanziaria siede l'alfabetizzazione civica, insegnata attraverso la Continuità Senza Evasione. Ogni partecipante impara che l'accordo è costruito per la portabilità lecita — che nessun singolo governo, banca, fondatore o modello indispensabile si frappone tra lui e le promesse del quadro. Impara cosa fa una decisione sfavorevole all'interno di questa progettazione: chiude un solo canale, in una sola giurisdizione, secondo la postura default-deny di quell'adattatore, e non fa mai cadere l'insieme. Accanto a questo sta la lezione più profonda che l'accordo insegna: l'Autorità Umana custodisce significato, denaro e legge, e il livello sovrano in cui quelle decisioni vengono prese resta permanentemente precluso alle macchine. La Misurazione del Tempo, MoT, registra i minuti effettivi di ogni partecipante separatamente da qualsiasi punteggio, e Replay rende pienamente ricostruibile ogni pubblicazione emessa dall'accordo — così che uno studente che voglia sapere perché una decisione è stata presa, anni dopo, possa ripercorrerla da solo anziché fidarsi della parola di qualcuno.

Questa struttura di fiducia guadagnata diventa il modello pedagogico dell'accordo, non solo il suo modello di governance. Ogni partecipante avanza attraverso modalità Manuale, Semi-Automatizzata e Autonoma di libertà crescente, vincolate dalla stessa soglia di miglioramento misurato che vincola la tecnologia stessa — un guadagno verificato dell'undici virgola uno percento prima che si apra la modalità successiva. L'autonomia, quando viene guadagnata, viene guadagnata in modo circoscritto e per dominio, mai sopra significato, denaro o legge. Uno studente che ha vissuto questa progressione capisce, visceralmente, perché il livello sovrano non debba mai essere automatizzato via — perché ha guadagnato la propria autonomia un passo misurato alla volta, e sa esattamente cosa quell'autonomia includesse e cosa no.

Ciò che l'accordo impara, l'accordo lo restituisce. I curricula vengono pubblicati con licenza aperta, così che qualsiasi regione — firmataria o meno — possa adattarli alla propria cultura e tradizione pedagogica locale. I risultati dell'innovazione vengono pubblicati. La ricerca sul benessere viene pubblicata in forma aggregata per i ricercatori di tutto il mondo. Le decisioni di governance vengono pubblicate con il loro intero ragionamento intatto. Il successo dell'accordo si misura non solo dai propri partecipanti in Cambogia, Honduras e Austin, ma dalle iniziative che sorgono sulla sua scia, in regioni che non hanno mai firmato il pilota fondativo eppure hanno costruito sulla sua saggezza condivisa apertamente, lungo un orizzonte che i fondatori non vivranno abbastanza da vedere completato. Ciò che una regione impara, tutte le altre regioni lo ereditano — e ciò che a questa generazione viene insegnato onestamente, i prossimi cinquecento anni non dovranno disimparare.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Crescita Sostenibile della Rete`,
    content: {
      7: `Mai più veloce di quanto la dignità possa viaggiare.`,
      33: `Tre regioni fondatrici completano un intero ciclo pilota prima che una quarta si unisca — qualsiasi cittadino può costruirlo. I registri sono ancorati per resistere cinque secoli. I firmatari mantengono la sovranità; nulla viene ridotto per chi si unisce dopo.`,
      111: `L'Accordo di Atlantide non crescerà più velocemente della qualità che può onorare. Tre regioni fondatrici devono completare un intero ciclo pilota, con ogni partecipante onorato e ogni principio verificato, prima che una quarta regione si unisca. Questo è un principio finalmente diventato disciplina operativa. Ma l'accordo è un patto tra i cittadini del mondo — qualsiasi persona, ovunque, può costruirlo e custodirlo, a un Seed di distanza, indipendentemente da ciò che un governo firma o un datore di lavoro consente. L'orizzonte dell'accordo è di cinque secoli. I suoi registri sono ancorati tramite Replay, così che un cittadino che li legga tra un secolo possa verificarne il ragionamento, non semplicemente fidarsi. Ogni firmatario mantiene la sovranità; nulla viene ridotto per chi si unisce dopo.`,
      333: `L'Accordo di Atlantide non crescerà più velocemente della qualità che può onorare. Ogni espansione è una promessa ai partecipanti già presenti — che lo standard fondativo non verrà diluito dalla scala. Tre regioni fondatrici devono completare un intero ciclo pilota, con ogni partecipante onorato e ogni principio verificato, prima che una quarta regione si unisca. Questo è un principio finalmente diventato disciplina operativa. E la porta non è mai stata solo regionale: questo è un patto tra i cittadini del mondo, e qualsiasi persona può costruirlo, finanziarlo e chiederne conto — senza bisogno del permesso di alcun governo né della benedizione di alcun datore di lavoro. I leader che firmano il pilota promettono ai futuri firmatari lo stesso substrato, la stessa protezione e la stessa dignità ricevuti dalla coorte fondatrice. Nulla viene ridotto per chi si unisce dopo.

L'orizzonte dell'accordo è deliberatamente lungo — progettato per durare da quindici a venti generazioni umane, cinque secoli dal giorno della fondazione. I suoi registri sono ancorati tramite Replay, così che un cittadino che li legga tra un secolo possa verificare il ragionamento, non semplicemente fidarsi. Il suo sistema di coordinate, i suoi ruoli di Autorità Umana e i suoi cicli di governance intergenerazionali sono costruiti per sopravvivere a qualsiasi transizione di una singola tecnologia. L'accordo sopravviverà a ogni essere umano che firma il suo pilota fondativo, e a ogni cittadino che pianta un Seed e lo finanzia mensilmente. Questa è la sua promessa al bambino che firma un accordo d'indennità, al cittadino che ha aderito senza dover nulla al permesso di alcun governo, ai nipoti di quel bambino che a metà secolo potranno governare l'accordo, e a ogni generazione che erediterà ciò che i fondatori — ufficiali e cittadini allo stesso modo — costruiscono ora.

Ogni firmatario mantiene la libertà di ritirarsi, la piena sovranità e l'autorità sui propri cittadini, con il diritto di emendare e plasmare l'evoluzione dell'accordo. Ogni cittadino mantiene la stessa posizione per fondare, finanziare, testimoniare e chiedere conto — con o senza la firma di un governo. Ciò che nessuno può fare è compromettere i principi fondativi, perché quella promessa deve sopravvivere a qualsiasi abbandono. Leader e cittadini firmano insieme il prossimo secolo dell'accordo dentro un orizzonte che i loro nipoti erediteranno e completeranno.`,
      999: `L'Accordo di Atlantide non crescerà più velocemente della qualità che può onorare, e questa moderazione non è un sentimento — è ingegneria, scritta nella stessa disciplina di misurazione che governa ogni promessa fatta dall'accordo. Tre regioni fondatrici, Cambogia, Honduras e Austin, devono completare un intero ciclo pilota, con ogni partecipante onorato e ogni principio verificato, prima che una quarta regione si unisca. Una crescita che supera la verifica non è crescita; è esposizione travestita da ambizione. Il pilota fondativo esiste perché l'accordo possa dimostrare, su una scala abbastanza piccola da poter essere ispezionata e abbastanza grande da contare, che le sue promesse sopravvivono al contatto con la realtà prima che quelle promesse vengano estese a un mondo che osserva dall'esterno dei suoi tre confini. La quarta regione non è ancora stata nominata, e non lo sarà finché le prime tre non saranno garanti di ogni affermazione contenuta in questo documento.

Ciò che dimostra la prontezza a crescere non è l'entusiasmo ma un numero che l'accordo può difendere in pubblico. Il Qualified Innovation Score — QIS, calcolato come Ricavi più Utile Lordo più Reddito Operativo più spesa Effettiva in R&S, diviso per quattro — è lo strumento che l'accordo usa per sapere se una regione, una coorte o un cubo è effettivamente migliorato, anziché avere semplicemente la sensazione di essere migliorato. La crescita del QIS dimensiona il fondo ricompense solo dopo che la qualificazione è soddisfatta, mai prima, e il QIS in sé non conia alcun 웃 e non compra alcuna proprietà. Il QIS è misurazione, non pagamento; misurazione, non equità; uno specchio che l'accordo pone di fronte al proprio lavoro, mai una valuta che spende. Una regione che propone di espandere la rete deve mostrare il proprio QIS onestamente, alla vista delle regioni che l'hanno preceduta, o non si espande.

Crescita sostenibile significa crescita che guadagna la propria autorità un incremento alla volta. Ogni cubo e ogni regione inizia in modalità Manuale, dove gli esseri umani decidono tutto e il sistema assiste. L'avanzamento all'operatività Semi-Automatizzata, e infine Autonoma, all'interno di un dato cubo è vincolato da un'unica soglia in tutto l'accordo — un miglioramento misurato dell'undici virgola uno percento, una parte su nove, dimostrato e riproducibile prima che venga concesso il grado di autonomia successivo. L'autonomia si guadagna cubo per cubo, mai rivendicata in blocco né estesa sopra i domini che devono restare umani per quanto avanzato diventi il sistema: significato, denaro e legge restano preclusi alle macchine indipendentemente da quante soglie vengano superate altrove. Una rete che espande la propria automazione più velocemente di quanto espanda le proprie prove non si sta modernizzando. Sta scommettendo con una fiducia che non ha ancora guadagnato.

Il compenso si scala con la rete allo stesso modo dell'autorità — deliberatamente, e con un tetto che protegge l'intero sistema dal proprio stesso successo. Il 웃, il token dell'Intelligenza Umana, equivale a un'ora di lavoro testimoniato moltiplicata per il salario minimo locale; ciò che qualsiasi partecipante guadagna è quel Moltiplicatore per le ore lavorate, ed esso viene emesso solo per lavoro svolto nell'ambito di un compito definito e approvato a budget. Prima dell'approvazione, anche il piano più raffinato è solo pianificazione, e la sola pianificazione non conia nulla. La liquidazione di ogni partecipante è soggetta a un tetto di 9.999 웃 all'anno, con qualsiasi eccedenza riportata all'anno successivo anziché scomparire o distorcere il fondo. Man mano che nuove regioni si uniscono e l'attività della rete si moltiplica, è questo tetto a impedire che la crescita diventi inflazione — il valore resta ancorato a ore reali, testimoniate, locali, per quanto grande diventi l'accordo.

Dietro ogni 웃 sta un perché che nessun registro può calcolare da solo. ♡, l'Intenzione Condivisa, porta quel perché avanti attraverso ogni decisione di espansione che l'accordo prende, mentre ◬, il contributo dell'Intelligenza Artificiale, viene conteggiato come accelerazione testimoniata misurata rispetto a una base di riferimento congelata — un delta, e mai, in nessuna circostanza, un indicatore di profitto da ottimizzare fine a se stesso. L'ingresso in questa rete inizia allo stesso modo per ogni partecipante, indipendentemente dalla regione o dal decennio in cui aderisce: con un Seed, un'iscrizione una tantum al prezzo di un settimo di un'ora al salario minimo locale, non trasferibile e priva di qualsiasi rivendicazione economica. Il Seed dichiara soltanto che una persona è arrivata. Tutto ciò che costruisce in seguito, lo costruisce alla piena vista delle altre tre valute dell'accordo, mai attraverso il Seed stesso.

Una crescita reale deve anche essere una crescita che raggiunge una persona effettiva, non un fondo che il quadro trattiene per conto di qualcuno. 🏠 Livelihood Direct richiede che il valore viaggi verso un partecipante solo attraverso canali locali qualificati e autorizzati che l'accordo ha verificato regione per regione, e mai attraverso una custodia trattenuta dal quadro stesso. La classificazione precede sempre la liquidazione, così che nessun valore si muova prima che il suo scopo e il suo destinatario siano entrambi stabiliti oltre ogni dubbio. E poiché il riconoscimento non è la stessa cosa dell'accesso, un letto, un posto nella rotazione, un posto al tavolo è vincolato al ruolo e alla prontezza, mai al punteggio o alla posizione di un partecipante. Man mano che la rete si espande in una quarta regione e oltre, ogni nuovo territorio deve qualificare i propri canali autorizzati prima che Livelihood Direct possa raggiungere la sua gente — espansione della fiducia, non semplicemente espansione del territorio.

Nulla di tutto questo dura senza una rete costruita per sopravvivere al proprio stesso successo, ed è per questo che la Continuità Senza Evasione governa ogni regione che l'accordo aggiungerà mai. La portabilità lecita è obbligatoria; nessun singolo governo, banca, fondatore o modello può diventare indispensabile all'insieme. Ogni giurisdizione fa funzionare il proprio adattatore, a chiusura sicura e in modalità default-deny, così che una decisione sfavorevole in un luogo qualsiasi chiuda un solo canale, mai l'intero accordo. L'Autorità Umana custodisce significato, denaro e legge a ogni scala raggiunta dalla rete, sigillata contro l'invasione delle macchine per progettazione, non per promessa. La Misurazione del Tempo registra ogni minuto reale separatamente da qualsiasi affermazione su di esso, e Replay garantisce che qualsiasi pubblicazione, in qualsiasi regione, in qualsiasi momento lungo cinque secoli, possa essere ricostruita e riesaminata da chiunque lo chieda. Una rete che non può essere ripercorsa con Replay non può essere considerata affidabile, per quante regioni si siano unite a essa o per quanto impressionante appaia la sua crescita dall'esterno. È così che Vision • 2525 cresce senza mai superare la fiducia che è stata costruita per custodire — una regione verificata, un QIS onesto, un'ora testimoniata alla volta.`,
    },
  },
];
