import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_MS: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Di Mana Inovasi Bermula`,
    content: {
      7: `Para pemimpin memulakan yang tiada abad memulakan.`,
      33: `Tiga rantau — Kemboja, Honduras, Austin — membuka satu janji yang dibina bersama warga: menempatkan pelajar, melindungi mereka, menyerahkan alat masa depan ke tangan mereka. Kerajaan, Pendidikan, Inovasi menandatangani sebagai pemegang amanah; warga yang memegangnya. Satu permulaan.`,
      111: `Atlantis Accords ialah perjanjian antara warga dunia — satu janji yang boleh dicipta dan dipegang oleh sesiapa sahaja, di mana-mana sahaja, tidak kira apa yang ditandatangani oleh kerajaan mereka atau apa yang dibenarkan oleh majikan mereka. Rantau pengasasnya — Kemboja, Honduras, dan Austin, Texas — dipilih kerana satu kualiti yang jarang ditemui: kesanggupan mempercayakan alat masa depan kepada golongan muda selagi masih ada masa untuk mengajar mereka menggunakannya. Kerajaan, pendidik, dan inovator menandatangani sebagai pemegang amanah rantau masing-masing — tiga tandatangan visioner bagi setiap rantau, iaitu Kerajaan, Pendidikan, Inovasi — tetapi warga sendirilah yang membiayai accord ini, menyaksikan kerjanya, dan mempertanggungjawabkannya secara langsung. Tiada keizinan kerajaan dan tiada restu majikan diperlukan untuk menjadi sebahagian daripadanya. Tiga rantau, satu permulaan yang dikongsi bersama.`,
      333: `Setiap tamadun dikenang kerana apa yang dipilihnya untuk dimulakan. Atlantis Accords ialah janji antara warga dunia — sesiapa sahaja, di mana-mana sahaja, boleh memulakannya, tidak kira apa yang ditandatangani oleh kerajaan mereka. Rantau pengasasnya — Kemboja, Honduras, dan Austin, Texas — tidak dipilih kerana kekuatan ekonomi, kekuatan tentera, atau prestij institusi, tetapi kerana satu kualiti yang lebih jarang ditemui: kesanggupan mempercayakan alat masa depan kepada golongan muda. Inilah erti kepimpinan pada abad yang mendatang — keberanian untuk menyerahkan kunci kepada generasi seterusnya selagi masih ada masa untuk mengajar mereka cara memandu.

Accord ini dianjurkan oleh eXeL, satu daya penganjur yang dibina khusus untuk detik ini, wujud di luar saluran penyelarasan yang membentuk abad yang lalu — di luar struktur perjanjian diplomatik, birokrasi multilateral, dan kekusutan politik mana-mana negara bangsa tunggal. eXeL ialah penganjur yang dipercayai, yang menghimpunkan para pemimpin visioner di sekeliling satu rangka kerja bersama, satu roda pemacu bersama, dan satu ufuk lima ratus tahun yang dikongsi bersama. Setiap penandatangan mengekalkan kedaulatan penuh, autoriti penuh ke atas warganya sendiri, dan kebebasan penuh untuk menarik diri pada bila-bila masa. Apa yang diperoleh oleh penandatangan — dan apa yang diperoleh oleh mana-mana warga, dengan harga satu Seed, iaitu satu pertujuh daripada sejam gaji minimum tempatan — ialah kesan rangkaian yang hanya mampu disediakan oleh rangka kerja yang dibina khusus: penyelarasan tanpa sebarang bentuk penguasaan politik.

Menandatangani accord ini bermakna menandatangani satu janji: bahawa rantau itu akan menempatkan pelajar merentas budaya, menyumbangkan apa yang hanya mampu ditawarkannya, dan mematuhi standard yang lebih tinggi daripada apa yang dituntut oleh peraturan semasa — secara terbuka, secara telus, bertanggungjawab kepada warga yang membiayainya, menyaksikannya, dan mempertanggungjawabkannya, tanpa memerlukan keizinan kerajaan atau restu majikan untuk menjadi sebahagian daripadanya. Tiga tandatangan diperlukan daripada setiap rantau — Kerajaan, Pendidikan, dan Inovasi — menandatangani sebagai pemegang amanah, bukan pemilik. Tiga orang visioner diperlukan untuk mengatakan ya, dan warga untuk memegang apa yang mereka tandatangani. Tiga visioner, tiga rantau, satu permulaan — beginilah cara sebuah rangka kerja memasuki kehidupan, melalui kepercayaan para pemimpin yang sanggup menandatanganinya menjadi kenyataan.`,
      999: `Setiap tamadun dikenang kerana apa yang dipilihnya untuk dimulakan, dan Vision 2525 meminta para pengasasnya memulakan sesuatu dengan kerendahan hati, bukan dengan penaklukan. Atlantis Accords ialah janji yang dibuat oleh para pemimpin yang sanggup memulakan sesuatu yang belum pernah wujud sebelum ini — satu asas bersama untuk inovasi insani yang menjangkau setiap ceruk dunia, menghormati setiap suara, dan bertahan merentasi generasi yang diukur bukan dalam tahun, tetapi dalam abad. Penandatangan pengasasnya di Kemboja, Honduras, dan Austin, Texas tidak dipilih kerana kekuatan ekonomi, kekuatan tentera, atau prestij institusi. Mereka dipilih kerana satu kualiti yang lebih jarang ditemui: kesanggupan mempercayakan alat masa depan kepada golongan muda, dan kesabaran untuk membiarkan ufuk lima ratus tahun itu bertahan lebih lama daripada tepukan mana-mana pentadbiran. Inilah erti kepimpinan pada abad yang mendatang — keberanian untuk menyerahkan kunci kepada generasi seterusnya selagi masih ada masa untuk mengajar mereka cara memandu.

Accord ini dianjurkan oleh eXeL, satu daya penganjur yang dibina khusus untuk detik ini. eXeL wujud di luar saluran penyelarasan yang membentuk abad yang lalu — di luar struktur perjanjian diplomatik, di luar birokrasi multilateral, di luar kekusutan politik mana-mana negara bangsa. eXeL ialah penganjur yang dipercayai, yang menghimpunkan para pemimpin visioner di sekeliling satu rangka kerja bersama, satu roda pemacu bersama, dan satu ufuk lima ratus tahun yang dikongsi bersama. Setiap penandatangan mengekalkan kedaulatan penuh, autoriti penuh ke atas warganya sendiri, dan kebebasan penuh untuk menarik diri pada bila-bila masa. Apa yang diperoleh oleh penandatangan ialah kesan rangkaian yang hanya mampu disediakan oleh rangka kerja yang dibina khusus. Kemasukan setiap peserta ke dalam rangka kerja itu bermula dengan cara yang sama, sederhana: dengan satu Seed, keahlian sekali sahaja yang berharga satu pertujuh daripada sejam gaji minimum tempatan, tidak boleh dipindah milik dan tidak membawa sebarang tuntutan ekonomi. Seed tidak membeli pemilikan dan tidak menjanjikan sebarang ganjaran — hanya keanggotaan, hak untuk berdiri di dalam rangka kerja itu dan memulakan. Inilah penyelarasan tanpa sebarang bentuk penguasaan politik, dibina di atas satu permulaan yang cukup kecil untuk mampu dimiliki oleh sesiapa sahaja.

Kerana kedaulatan itu dikekalkan, bukan diserahkan, accord ini dibina untuk Continuity Without Evasion. Tiada kerajaan, bank, pengasas, atau model yang tidak boleh diganti dibenarkan menyandera keseluruhan rangka kerja demi kelangsungan dirinya sendiri. Setiap bidang kuasa dilayani melalui penyesuainya yang sah, menolak secara lalai sehingga terbukti patuh, supaya nilai hanya bergerak melalui laluan yang diiktiraf sah oleh mahkamah di bidang kuasa itu. Jika seorang pengawal selia di satu rantau mengeluarkan keputusan yang memudaratkan, laluan tunggal itu sahaja yang tertutup — secara telus, tanpa memudaratkan mana-mana peserta di dalamnya — manakala setiap rantau lain terus berjalan tanpa gangguan. Keseluruhan accord ini tidak sekali-kali runtuh hanya kerana satu kerajaan berubah fikiran. Inilah kebolehalihan yang direka sebagai janji asas, bukan langkah kecemasan yang ditemui selepas krisis berlaku.

Menandatangani accord ini bermakna menandatangani satu janji. Bahawa rantau itu akan menempatkan pelajar merentas budaya. Bahawa rantau itu akan menyumbangkan apa yang hanya mampu ditawarkannya. Bahawa rantau itu akan mematuhi standard yang lebih tinggi daripada apa yang dituntut oleh peraturan semasa. Bahawa rantau itu akan melakukannya secara terbuka, secara telus, di hadapan mata setiap warga yang dilayaninya. Tiga tandatangan diperlukan daripada setiap rantau — Kerajaan, Pendidikan, dan Inovasi. Tiada satu pihak sahaja boleh mengikat accord ini. Tiga orang visioner diperlukan untuk mengatakan ya. Tandatangan tiga serangkai ini adalah ungkapan pertama Human Authority: makna, wang, dan undang-undang kekal di tangan manusia pada lapisan berdaulat, satu lapisan yang tertutup selama-lamanya kepada mesin, tidak kira sehebat mana mesin itu kelak. Measurement of Time, MoT, mula merekod sebaik sahaja tandatangan dibubuh — minit sebenar kerja insani yang sebenar, disimpan berasingan daripada sebarang anggaran automatik — dan setiap keluaran kerja accord yang berikutnya dibina supaya dapat dibina semula melalui Replay, agar seorang warga yang lahir seabad dari sekarang dapat menyusuri semula bagaimana keputusan asas hari ini dicapai.

Apa yang diasaskan oleh pilot ini ialah pengukuran, sebelum ia menjadi wang. Setiap inovasi yang memasuki rangka kerja ini dinilai melalui Qualified Innovation Score, QIS — purata Revenue, Gross Profit, Operating Income, dan perbelanjaan R&D Efektif, dibahagi empat. QIS bukan pembayaran dan bukan sekali-kali pemilikan; ia ialah instrumen yang membolehkan kohort pengasas melihat kemajuan mereka sendiri sebelum sebarang ganjaran ditentukan saiznya. Pertumbuhan dalam QIS, setelah kelayakan dipenuhi, menentukan saiz kumpulan wang ganjaran yang menyusul — tetapi pertumbuhan dalam QIS itu sendiri tidak mencipta apa-apa. Tiga rantau, satu permulaan, dan satu disiplin yang dikongsi bersama: buktikan skor itu sebelum menyentuh perbendaharaan.

Nilai yang diperoleh melalui kerja yang disaksikan membawa namanya sendiri, 웃, dikira sebagai satu jam didarab dengan gaji minimum tempatan, diskalakan dengan satu Multiple yang dikenakan ke atas jam yang dikhidmati. 웃 hanya dikeluarkan untuk kerja yang disaksikan di bawah tugasan yang berskop dan diluluskan bajetnya; apa-apa sahaja yang kurang daripada kelulusan itu masih dianggap perancangan, dan perancangan semata-mata tidak mencipta apa-apa. Siling penyelesaian sebanyak 9,999 웃 setahun melindungi setiap peserta daripada penumpuan yang tidak terkawal, dengan sebarang lebihan dibawa ke hadapan, bukan lenyap begitu sahaja. Di sebalik setiap 웃 berdiri ♡, Shared Intention, yang membawa sebab mengapa sesuatu tugasan diluluskan pada mulanya, dan ◬, pecutan yang disaksikan yang dihasilkan oleh sesuatu tugasan berbanding garis dasar yang dibekukan — hanya satu delta, tidak sekali-kali disalahertikan sebagai ukuran keuntungan. Pilot ini wujud untuk membuktikan bahawa ketiga-tiga glif ini boleh bergerak bersama secara jujur, rantau demi rantau, sebelum rangka kerja ini berkembang melangkaui para pengasasnya.

Apabila nilai sampai kepada seseorang, ia sampai melalui Livelihood Direct — 🏠 — laluan tempatan yang berlesen dan layak, yang tidak sekali-kali disimpan oleh eXeL sebagai dana miliknya sendiri. Pengelasan sentiasa mendahului penyelesaian dalam setiap kes, dan pengiktirafan terhadap sesuatu sumbangan tidak sekali-kali menjadi syarat untuk mendapatkan tempat tidur malam itu; hanya peranan seseorang dalam tugasan yang berskop yang menentukannya. Pertumbuhan melangkaui pilot ini juga dikawal: setiap cube rangka kerja ini bergerak daripada Manual kepada Semi-Automated kepada Autonomous hanya selepas memenuhi peraturan 11.1 peratus, satu bahagian daripada sembilan peningkatan yang diukur, diperoleh cube demi cube dan tidak sekali-kali dituntut secara borong — dan tidak sekali-kali, dalam apa jua keadaan, ke atas lapisan berdaulat makna, wang, dan undang-undang. Beginilah cara tiga visioner bagi setiap rantau, tiga rantau, dan satu permulaan menjadi janji lima ratus tahun: bukan dengan bergerak pantas, tetapi dengan membuktikan, di hadapan mata umum, bahawa setiap langkah layak mendapat langkah yang menyusul.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Pembelajaran Melalui Simulasi`,
    content: {
      7: `Berlatih seribu kali sebelum menyentuh.`,
      33: `Tiada apa-apa yang bermakna dipelajari buat kali pertama di atas perkakasan sebenar. Mana-mana warga boleh berlatih dalam simulasi, berputar merentas tiga rantau, dan meraikannya — penghormatan kepada insan muda yang kesilapan pertamanya tidak sepatutnya sekali-kali meragut nyawa.`,
      111: `Setiap disiplin yang bernilai untuk dikuasai pernah dipelajari oleh seseorang sebelum ia diketahui. Atlantis Accords mengembalikan kebijaksanaan purba ini ke pusat cara golongan muda — dan mana-mana warga yang menyertainya — disediakan untuk membina masa depan. Tiada apa-apa yang bermakna dipelajari buat kali pertama di atas perkakasan sebenar, ke atas manusia sebenar, atau dalam keadaan yang tidak boleh diundur; tiada keizinan kerajaan atau restu majikan diperlukan. Setiap peserta berlatih dalam simulasi sehingga latihan itu menjadi kecekapan, kemudian kesediaan. Model rotasi membawa setiap peserta melalui tiga rantau pengasas, dan setiap rotasi berakhir dengan sambutan awam yang terbuka kepada komuniti tuan rumah. Inilah penghormatan kepada insan muda yang kesilapan pertamanya tidak sepatutnya sekali-kali meragut nyawa.`,
      333: `Setiap disiplin yang bernilai untuk dikuasai pernah dipelajari oleh seseorang sebelum ia diketahui. Tukang mahir berlatih sebelum persembahan, juruterbang sebelum penerbangan, doktor sebelum pembedahan, kanak-kanak melalui permainan. Atlantis Accords mengembalikan kebijaksanaan purba ini ke pusat cara golongan muda — dan mana-mana warga yang menyertainya, tanpa memerlukan keizinan kerajaan atau restu majikan — disediakan untuk membina masa depan. Tiada apa-apa yang bermakna dipelajari buat kali pertama di atas perkakasan sebenar, ke atas manusia sebenar, atau dalam keadaan yang tidak boleh diundur. Setiap peserta berlatih dalam simulasi sehingga latihan itu menjadi kecekapan, kemudian kesediaan. Ini bukan berhati-hati semata-mata — ini adalah penghormatan kepada insan muda yang kesilapan pertamanya tidak sepatutnya sekali-kali meragut nyawa sesiapa pun.

Model rotasi accord ini membawa setiap peserta melalui tiga rantau pengasas. Apa yang dipelajari di Kemboja diperhalusi di Honduras dan disempurnakan di Austin. Apa yang ditemui di Austin dipersoalkan di Kemboja dan diintegrasikan di Honduras. Setiap peserta hidup, belajar, dan dibimbing merentas budaya yang sememangnya jauh antara satu sama lain. Kurikulum latihan ini mengambil inspirasi daripada tradisi simulasi berdisiplin merentas pelbagai budaya — daripada tradisi pendidikan strategik Sun Tzu, daripada pembelajaran-melalui-permainan Musashi, daripada teori pembelajaran kitaran Ibn Khaldun, daripada dialektik biara Nalanda, daripada simulator penerbangan awam — disintesis untuk menghormati setiap peringkat kognitif dan warisan budaya. Tiada satu tradisi tunggal yang mendominasi.

Setiap rotasi berakhir dengan sambutan awam yang terbuka kepada komuniti tuan rumah, di mana jiran, keluarga, dan pengunjung dapat melihat apa yang telah dipelajari oleh kohort itu. Acara sebegini menjadikan teknologi canggih sesuatu yang boleh didekati dan disambut, bukan sesuatu yang menakutkan — sesebuah masyarakat yang membesar dengan memahami sistem koperatif melalui permainan tidak mudah dimanipulasi oleh rasa takut terhadapnya. Inilah pencegahan melalui pendidikan, bukan melalui kekerasan. Janji accord ini kepada setiap ibu bapa: anak anda akan berlatih seribu kali dalam keadaan selamat sebelum menyentuh apa-apa yang boleh memudaratkan mereka, disaksikan supaya seorang warga — mana-mana warga, seabad dari sekarang — dapat mengesahkan bahawa ia berlaku tepat seperti yang direkodkan. Inilah penghormatan kepada insan muda yang direka masuk ke dalam sebuah rangka kerja, dan inilah yang wajib diberikan oleh kepimpinan kepada warga seterusnya yang menyertainya, sebelum warga itu terpaksa menuntutnya.`,
      999: `Setiap disiplin yang bernilai untuk dikuasai pernah dipelajari oleh seseorang sebelum ia diketahui, dan setiap tamadun yang bertahan berbuat demikian kerana ia melindungi ruang tempat pembelajaran itu boleh berlaku dengan selamat, sebelum ia dituntut untuk benar-benar bermakna. Tukang mahir berlatih sebelum persembahan, juruterbang berlatih sebelum penerbangan, doktor berlatih sebelum pembedahan, dan kanak-kanak berlatih memahami dunia melalui permainan. Atlantis Accords mengembalikan kebijaksanaan purba ini ke pusat cara golongan muda disediakan untuk membina masa depan, dan ia memberikan kebijaksanaan itu satu nama dan satu mekanisme: Replay. Tiada apa-apa yang bermakna dipelajari buat kali pertama di atas perkakasan sebenar, ke atas manusia sebenar, atau dalam keadaan yang tidak boleh diundur. Setiap peserta berlatih dalam simulasi sehingga latihan itu menjadi kecekapan, kemudian kesediaan, dan setiap jam latihan itu direkodkan supaya ia dapat dibina semula kelak, diteliti kelak, dipercayai kelak. Ini bukan berhati-hati semata-mata — ini adalah penghormatan kepada insan muda yang kesilapan pertamanya tidak sepatutnya sekali-kali meragut nyawa sesiapa pun, dan ini juga penghormatan kepada rekod yang akan terus wujud lebih lama daripada kesilapan itu sendiri, apa pun yang berlaku.

Model rotasi accord ini membawa setiap peserta melalui tiga rantau pengasas. Apa yang dipelajari di Kemboja diperhalusi di Honduras dan disempurnakan di Austin. Apa yang ditemui di Austin dipersoalkan di Kemboja dan diintegrasikan di Honduras. Setiap peserta hidup, belajar, dan dibimbing merentas budaya yang sememangnya akan kekal jauh sekiranya bukan kerana accord ini, dan setiap rotasi bermula dengan cara yang sama seperti setiap institusi insani yang layak dipercayai bermula: dengan satu Seed. Seed ialah keahlian sekali sahaja, berharga satu pertujuh daripada sejam gaji minimum tempatan, tidak boleh dipindah milik, tidak membawa sebarang tuntutan ekonomi. Ia bukan bayaran untuk mengakses peluang. Ia adalah satu ambang — cukup kecil supaya tiada peserta yang bersedia disisihkan kerana harga, namun cukup bersungguh supaya kemasukan itu dipilih, bukan dituruti secara sambil lewa. Selepas ambang itu, setiap peserta menjadi sebahagian daripada rotasi, dan rotasi itu bukan milik mana-mana satu rantau semata-mata.

Kurikulum latihan ini mengambil inspirasi daripada tradisi simulasi berdisiplin merentas pelbagai budaya — daripada tradisi pendidikan strategik Sun Tzu, daripada pembelajaran-melalui-permainan Musashi, daripada teori pembelajaran kitaran Ibn Khaldun, daripada dialektik biara Nalanda, daripada simulator penerbangan awam — disintesis untuk menghormati setiap peringkat kognitif dan warisan budaya. Tiada satu tradisi tunggal yang mendominasi. Dan dalam kurikulum ini, accord ini melukiskan satu garis yang dipelajari awal-awal oleh setiap peserta dan tidak sekali-kali dilupakan: simulasi ialah tempat Qualified Innovation Score difahami, bukan tempat ia dibelanjakan. QIS ialah ukuran, bukan sekali-kali pembayaran, dan QIS bukan sekali-kali pemilikan — ia wujud untuk menggambarkan sejauh mana sesuatu cadangan itu berhujah dengan baik, kukuh, dan melayani rantau yang didakwanya dilayani. Pertumbuhan dalam QIS boleh menentukan saiz kumpulan wang ganjaran selepas kelayakan sebenar dipenuhi, tetapi ia sendiri tidak mencipta apa-apa. Seorang peserta boleh menjalankan seratus simulasi yang sempurna dan memperoleh skor yang meningkat tanpa sejam pun 웃 menyentuh lejarnya, kerana 웃 hanya dikeluarkan untuk kerja yang disaksikan yang dilaksanakan di bawah tugasan yang berskop dan diluluskan bajetnya. Sebelum kelulusan itu, segala-galanya — biar sehebat mana pun, biar sebaik mana pun harapannya — hanyalah perancangan. Accord ini mengajar perbezaan ini sejak hari pertama supaya tiada seorang pun anak muda mengelirukan latihan dengan ganjaran, dan tiada seorang pun anak muda sesekali disesatkan tentang tujuan sebenar simulasi.

Disiplin yang sama ini mengawal sejauh mana autonomi yang dibenarkan dilaksanakan oleh mana-mana sistem, sama ada insan atau buatan, di dalam rotasi. Mod operasi accord ini bergerak mengikut turutan — Manual, kemudian Semi-Automated, kemudian Autonomous — dan tiada satu cube pun beralih mod sehingga ia memenuhi peraturan peningkatan terukur 11.1 peratus, satu bahagian daripada sembilan, dibuktikan berbanding garis dasar yang dibekukan dan disaksikan, bukan sekadar didakwa. Simulasi ialah tempat bukti itu dibina. Sesuatu alat memperoleh hak untuk bertindak dengan pengawasan yang lebih sedikit dengan cara yang sama seorang peserta memperoleh hak untuk tanggungjawab yang lebih besar: melalui peningkatan yang terbukti, direkodkan, dan boleh dibina semula, cube demi cube, tidak sekali gus, dan tidak sekali-kali ke atas lapisan tempat makna, wang, dan undang-undang diputuskan. Lapisan itu milik Human Authority semata-mata, sama ada dalam simulasi mahupun dalam operasi sebenar, kerana ruang latihan yang mengajar sempadan yang salah akan mengajar pengajaran yang salah secara kekal.

Setiap rotasi berakhir dengan sambutan awam yang koperatif dan terbuka kepada komuniti tuan rumah. Jiran, keluarga, dan pengunjung berkumpul untuk melihat apa yang telah dipelajari oleh kohort itu, dan apa yang mereka saksikan bukanlah demonstrasi kelajuan semata-mata, tetapi demonstrasi ◬ — delta terukur antara garis dasar yang dibekukan dengan apa yang benar-benar dicapai oleh latihan berdisiplin, dipersembahkan secara jujur, tidak sekali-kali dihias sebagai ukuran keuntungan, tidak sekali-kali dipersembahkan lebih daripada apa sebenarnya ia. Acara sebegini menjadikan teknologi canggih sesuatu yang boleh didekati dan disambut, bukan sesuatu yang menakutkan. Sesebuah masyarakat yang membesar dengan memahami sistem koperatif melalui permainan tidak mudah dimanipulasi oleh rasa takut terhadap sistem tersebut. Inilah pencegahan melalui pendidikan, bukan pencegahan melalui kekerasan, dan ia berkesan kerana komuniti tidak diminta mempercayai sesuatu dakwaan — sebaliknya, mereka dijemput untuk menyaksikan Replay itu sendiri.

Janji accord ini kepada setiap ibu bapa melangkaui keselamatan, meluas kepada kekekalan: anak anda akan berlatih seribu kali sebelum menyentuh apa-apa yang boleh memudaratkan mereka, komuniti akan menyaksikan perkembangan mereka sepanjang tempoh itu, dan tiada satu pun daripadanya akan hilang ditelan masa. Measurement of Time merekod minit sebenar secara berasingan daripada setiap lejar lain yang disimpan oleh accord ini, supaya jam berlatih dan jam disaksikan tidak sekali-kali dikelirukan antara satu sama lain, dan supaya sejarah perkembangan sebenar seseorang peserta — bukan ringkasan, bukan anggaran, tetapi rekod yang boleh dibina semula itu sendiri — kekal tersedia kepada peserta itu selama mana sahaja mereka mahu merujuknya. Seorang ibu bapa di Phnom Penh, seorang mentor di Tegucigalpa, seorang juruaudit di Austin, atau seorang cucu yang membaca rekod itu seabad dari sekarang, semuanya boleh mencapai Replay yang sama dan melihat kebenaran yang sama.

Beginilah rupa penghormatan kepada insan muda apabila ia direka masuk ke dalam sebuah rangka kerja, bukan sekadar dijanjikan olehnya, dan inilah yang diserahkan oleh kepimpinan kepada generasi peserta seterusnya sebelum generasi itu terpaksa menuntutnya: satu ruang latihan yang cukup luas untuk gagal dengan selamat, cukup jujur untuk merekod dengan setia, dan cukup berdisiplin untuk memastikan ganjaran, autonomi, dan autoriti kekal tepat di tempat yang layak diperoleh oleh penguasaan — tidak sekali-kali mendahuluinya, dan tidak sekali-kali ketinggalan di belakangnya.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Keselamatan Disahkan Sebelum Kepercayaan Diberikan`,
    content: {
      7: `Keselamatan dibuktikan dahulu, barulah kepercayaan diberikan.`,
      33: `Setiap fasiliti dan rotasi berada di dalam satu zon perlindungan yang dilengkapi amaran awal. Perkakasan menolak penyenjataan — dibuktikan, bukan sekadar dijanjikan, dan boleh diperiksa oleh warga. Rekod bertahan walau dalam gelora. Keselamatan direka di sekeliling peserta termuda, setiap hari.`,
      111: `Sebelum kepercayaan diberikan, keselamatan mesti dibuktikan — bukan kepada kerajaan, tetapi kepada mana-mana warga yang memeriksanya. Atlantis Accords ialah perjanjian antara warga dunia; komitmen asasnya ialah ini: setiap fasiliti accord, setiap laluan rotasi, setiap tempat peserta muda tidur atau belajar berada di dalam satu zon perlindungan yang didokumenkan dengan keupayaan amaran awal, yang memberi komuniti masa berjam-jam, bukan seminit dua, untuk bertindak balas terhadap sebarang risiko yang munasabah. Setiap peranti, setiap penderia, setiap sistem penyelarasan terikat pada lapisan perkakasan untuk menolak sebarang penggunaan semula demi integrasi sistem senjata. Ini bukan dasar — ini fizik. Accord ini kekal terhormat walau dalam gelora, kerana setiap rancangan meletakkan maruah insani sebagai keutamaan pertama.`,
      333: `Sebelum kepercayaan diberikan, keselamatan mesti dibuktikan — dibuktikan kepada warga, bukan sekadar didakwa. Atlantis Accords ialah perjanjian antara warga dunia: sesiapa sahaja, di mana-mana sahaja, boleh membantu memegangnya, tidak kira apa yang ditandatangani oleh kerajaan mereka. Setiap fasiliti accord, setiap laluan rotasi, setiap tempat peserta muda tidur atau belajar berada di dalam satu zon perlindungan yang didokumenkan dengan keupayaan amaran awal, yang memberi komuniti masa berjam-jam, bukan seminit dua, untuk bertindak balas terhadap sebarang risiko yang munasabah. Teknologi yang melindungi mereka adalah teknologi yang sama yang diajar oleh accord ini kepada mereka untuk dibina. Golongan muda mempelajari keselamatan dari dalam ke luar, bukan dengan diberitahu bahawa mereka selamat, tetapi dengan melihat sendiri bagaimana ia direka di sekeliling mereka setiap hari, serta mengetahui bahawa mana-mana warga boleh mengesahkan rekod itu melalui Replay.

Accord ini membuat satu janji yang tidak boleh dipatahkan tentang apa yang tidak boleh dijadikan oleh teknologinya. Setiap peranti, setiap penderia, setiap sistem penyelarasan terikat pada lapisan perkakasan untuk menolak sebarang penggunaan semula demi integrasi sistem senjata. Ini bukan bahasa dasar, bukan sekadar aspirasi. Ini adalah kemustahilan fizikal, dikuatkuasakan secara kriptografi, disahkan oleh setiap rantau penandatangan, dan boleh diperiksa oleh setiap warga yang membiayainya. Alat yang melindungi seorang kanak-kanak di Phnom Penh tidak boleh digunakan semula untuk memudaratkan seorang kanak-kanak di Austin. Alat yang menghubungkan latihan kumpulan di Tegucigalpa tidak boleh dikonfigurasi semula untuk menyasarkan sesiapa pun di mana-mana. Inilah jawapan accord ini terhadap sebuah abad ketakutan terhadap penggunaan dwiguna. Bukan dasar — fizik.

Accord ini kekal terhormat walau dalam gelora. Jika sesebuah rantau kehilangan kestabilan politik, para peserta akan ditampung oleh rantau-rantau yang lain. Jika pembiayaan mengecut, elaun dilindungi dahulu — dibiayai setiap bulan oleh warga, bukan sekali-kali saluran bantuan, setiap dolar boleh dikesan. Jika rekod digital diserang, sandaran luar talian kekal terpelihara. Jika perjalanan menjadi mustahil, substrat itu terus berfungsi secara maya. Setiap rancangan meletakkan maruah insani — Human Authority ke atas makna, wang, dan undang-undang — sebagai kekangan reka bentuk yang pertama. Para pemimpin yang menandatangani accord ini berjanji bahawa keselamatan itu direka, bukan sekadar diandaikan: perlindungan yang akan dituntut oleh mana-mana pemimpin untuk anak mereka sendiri, kini diperluaskan kepada setiap warga yang membantu memegangnya.`,
      999: `Sebelum kepercayaan diberikan, keselamatan mesti dibuktikan — inilah komitmen asas Atlantis Accords, dan ia dibuktikan dengan cara yang sama seperti setiap dakwaan lain dalam Vision 2525 dibuktikan: bukan dengan dakwaan semata-mata, tetapi dengan bukti yang boleh diperiksa oleh warga. Setiap fasiliti accord, setiap laluan rotasi, setiap tempat peserta muda tidur atau belajar berada di dalam satu zon perlindungan yang didokumenkan dengan keupayaan amaran awal, yang memberi komuniti masa berjam-jam, bukan seminit dua, untuk bertindak balas terhadap sebarang risiko yang munasabah. Teknologi yang digunakan untuk melindungi peserta adalah teknologi yang sama yang diajar oleh accord ini kepada mereka untuk dibina — penderia, penyelarasan, daya tahan komunikasi, kecerdasan teragih. Golongan muda mempelajari keselamatan dari dalam ke luar, dalam bahasa mereka sendiri dan di rantau mereka sendiri, bukan dengan diberitahu bahawa mereka selamat, tetapi dengan menyaksikan sendiri, jam demi jam, bagaimana keselamatan direka di sekeliling mereka setiap hari.

Penyaksian ini tidak diserahkan kepada ingatan atau kepercayaan semata-mata kepada kata-kata seorang fasilitator. Measurement of Time merekod minit sebenar bagi setiap latihan, setiap rotasi, setiap latihan tindak balas — secara berasingan daripada sebarang dakwaan kemajuan, secara berasingan daripada sebarang cerita yang diceritakan pada hari itu. Replay menjadikan setiap keluaran kurikulum latihan, setiap kemas kini keselamatan, setiap semakan perkakasan boleh dibina semula sepenuhnya, supaya seorang ibu bapa di Tegucigalpa atau seorang pengawal selia di Phnom Penh boleh menyusuri ke belakang dengan tepat apa yang berubah, bila ia berubah, dan mengapa ia berubah. Sesuatu zon perlindungan yang tidak boleh di-Replay hanyalah satu janji. Sesuatu zon perlindungan yang boleh di-Replay, minit demi minit yang direkodkan, adalah satu bukti. Accord ini memilih bukti.

Accord ini membuat satu janji yang tidak boleh dipatahkan tentang apa yang tidak boleh dijadikan oleh teknologinya. Setiap peranti, setiap penderia, setiap sistem penyelarasan terikat pada lapisan perkakasan untuk menolak sebarang penggunaan semula demi integrasi sistem senjata. Ini bukan bahasa dasar, bukan sekadar aspirasi. Ini adalah kemustahilan fizikal, dikuatkuasakan secara kriptografi, disahkan oleh setiap rantau penandatangan, dan boleh diperiksa oleh setiap warga. Alat yang melindungi seorang kanak-kanak di Phnom Penh tidak boleh digunakan semula untuk memudaratkan seorang kanak-kanak di Austin. Alat yang menghubungkan latihan kumpulan di Tegucigalpa tidak boleh dikonfigurasi semula untuk menyasarkan sesiapa pun di mana-mana. Inilah jawapan accord ini terhadap sebuah abad ketakutan terhadap penggunaan dwiguna. Bukan dasar — fizik.

Keselamatan yang dibuktikan sekali sahaja bukanlah keselamatan yang bertahan sepanjang ufuk lima ratus tahun. Accord ini menamakan komitmen keduanya Continuity Without Evasion: kebolehalihan yang sah merentas setiap bidang kuasa yang disentuh oleh accord ini, tanpa satu kerajaan, bank, pengasas, atau model tunggal yang tidak boleh diganti berdiri antara seseorang peserta dengan perlindungannya. Setiap bidang kuasa dilayani oleh penyesuainya sendiri, gagal-tertutup dan menolak secara lalai, supaya sebarang keputusan yang memudaratkan di mana-mana satu rantau hanya menutup laluan itu sahaja — tidak sekali-kali keseluruhan rangka kerja, tidak sekali-kali setiap rantau, tidak sekali-kali setiap peserta di merata tempat serentak. Sesuatu keputusan mahkamah di satu wilayah penandatangan tidak boleh mematikan zon keselamatan seseorang peserta di tempat lain. Inilah maksud membina sebuah sistem yang bertahan daripada gelora biasa undang-undang, politik, dan perubahan institusi, tanpa sesekali meminta seseorang peserta mengelak undang-undang demi kekal dilindungi.

Setiap lapisan seni bina perlindungan ini akhirnya bertanggungjawab kepada Human Authority. Makna, wang, dan undang-undang tidak sekali-kali diserahkan kepada mesin — lapisan berdaulat yang menentukan apa yang dituntut oleh keselamatan, apa yang dianggap sebagai risiko yang munasabah, dan apa tindak balas yang wajib diberikan oleh sesebuah komuniti kepada ahlinya yang termuda, kekal tertutup kepada kecerdasan buatan, tidak kira sehebat mana ia kelak. Sistem accord ini bergerak melalui tiga mod operasi sahaja — Manual, Semi-Automated, Autonomous — dan tiada satu sistem pun beralih mod tanpa peningkatan terukur yang disaksikan, sekurang-kurangnya satu bahagian daripada sembilan, iaitu 11.1 peratus, disahkan dan boleh diulang. Autonomi diperoleh, cube demi cube, fungsi demi fungsi, tidak sekali-kali diberikan secara borong, dan tidak sekali-kali diperluaskan ke atas persoalan yang menentukan makna, wang, atau undang-undang. Sesuatu penderia mungkin belajar mengesan dengan lebih pantas. Sesuatu sistem penyelarasan mungkin belajar untuk menghala dengan lebih cekap. Namun kedua-duanya tidak sekali-kali dibenarkan memutuskan, dengan sendirinya, apa yang patut dipercayakan oleh sesebuah komuniti dengan anak-anaknya.

Accord ini direka untuk kekal terhormat walau dalam gelora, dan ia menamakan gelora itu terlebih dahulu, bukan menemuinya semasa krisis melanda. Jika sesebuah rantau penandatangan kehilangan kestabilan politik, para peserta akan ditampung oleh rantau-rantau yang lain. Jika pembiayaan mengecut, elaun peserta dilindungi dahulu, sebelum pentadbiran dan infrastruktur. Jika rekod digital diserang, sandaran luar talian kekal terpelihara, tidak terjangkau oleh apa jua kegagalan yang melanda rangkaian. Jika perjalanan menjadi mustahil, substrat itu terus berfungsi secara maya, supaya sesuatu rotasi tidak terhenti hanya kerana sempadan ditutup. Setiap senario dirancang lebih awal, dan setiap rancangan meletakkan maruah insani sebagai kekangan reka bentuk yang pertama — bukan pertimbangan terakhir selepas bajet dan imej diselesaikan.

Kemasukan ke dalam sistem yang terbukti ini bermula dengan Seed — keahlian sekali sahaja, berharga satu pertujuh daripada sejam gaji minimum tempatan, tidak boleh dipindah milik, dan tidak membawa sebarang tuntutan ekonomi ke atas apa jua yang dibina oleh accord ini selepas itu. Seed tidak membeli keselamatan; keselamatan telah direka jauh sebelum sebarang Seed pernah ditanam. Apa yang dibeli oleh Seed ialah kedudukan — hak untuk melangkah masuk ke dalam sebuah rangka kerja yang telahpun terbukti, telahpun diperiksa, telahpun terikat oleh perkakasan yang tidak boleh digunakan untuk menentang orang yang sepatutnya dilindunginya. Pemisahan ini disengajakan. Sesuatu janji keselamatan yang mesti dibeli dengan nilai ekonomi sebenar bukanlah janji keselamatan langsung, sebaliknya hanya sekadar produk keselamatan. Accord ini memisahkan kedua-duanya secara mutlak, supaya tiada sebuah keluarga pun sesekali terpaksa menimbang antara perlindungan anak mereka dengan bajet bulanan isi rumah mereka.

Para pemimpin yang menandatangani accord ini menandatangani satu janji bahawa keselamatan itu direka, bukan sekadar diandaikan, dan dibuktikan, bukan sekadar didakwa. Apa yang mereka perluaskan kepada warga mereka bukan sekadar peluang, tetapi perlindungan yang dibina mengikut standard yang layak diterima oleh peserta termuda — direkodkan oleh Measurement of Time, boleh dibina semula melalui Replay, terikat pada lapisan perkakasan terhadap setiap penyalahgunaan yang pernah dibayangkan oleh sebuah abad yang penuh ketakutan, dan bertanggungjawab, sentiasa dan hanya, kepada Human Authority. Inilah perlindungan yang sama yang akan dituntut oleh mana-mana pemimpin untuk anak mereka sendiri yang melintasi sempadan asing seorang diri, kini diperluaskan kepada setiap anak yang akan dilayani oleh accord ini, merentas tiga rantau pengasasnya iaitu Kemboja, Honduras, dan Austin, serta merentas lima abad yang diazamkan oleh accord ini untuk menepati janji ini.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Pampasan, Kesejahteraan, dan Maruah Manusia`,
    content: {
      7: `Sebuah elaun, seorang mentor, sebuah rumah.`,
      33: `Setiap warga menerima elaun sejak hari pertama — tanpa keizinan kerajaan, tanpa restu majikan. Cinta, kehilangan, dan keselamatan adalah infrastruktur. Kejayaan diukur berdasarkan golongan yang paling rentan. Maruah adalah substrat, bukan sekadar hiasan.`,
      111: `Atlantis Accords memperlakukan setiap peserta sebagai insan sepenuhnya sejak hari pertama — seorang warga yang menyertainya sebagai hak, bukan atas dekri kerajaan atau kebenaran majikan. Elaun disediakan sebaik sahaja penyertaan bermula, diindekskan mengikut kos sara hidup rantau tersebut, dan setiap jam yang disaksikan memperoleh 웃, dibayar terus kepada individu melalui Livelihood Direct, tidak sekali-kali melalui lejar majikan. Kesejahteraan diperlakukan sebagai infrastruktur kelas pertama — bukan sekadar faedah tambahan, tetapi substrat tempat segala-galanya berdiri. Tiga domain disokong: Cinta, Kehilangan, dan Keselamatan. Accord ini mengukur kejayaan berdasarkan pesertanya yang paling rentan, bukan purata. Tiada seorang pun dilupakan semata-mata supaya purata kelihatan baik. Maruah sebagai substrat, bukan hiasan.`,
      333: `Atlantis Accords memperlakukan setiap peserta sebagai insan sepenuhnya sejak hari pertama — seorang warga yang menjadi sebahagian daripadanya sebagai hak, tidak memerlukan keizinan kerajaan mahupun restu majikan. Elaun disediakan sebaik sahaja penyertaan bermula, diindekskan mengikut kos sara hidup rantau tersebut, tiba sebelum tanggungjawab keluarga bertukar menjadi kecemasan. Ini bukan amal derma. Ini adalah pengiktirafan bahawa inovasi insani yang biasa memerlukan keselamatan insani terlebih dahulu — sesebuah minda tidak dapat berkembang selagi isi rumahnya berada dalam ancaman.

Apa yang diperoleh melangkaui elaun itu diperoleh sepertimana seorang warga memperolehinya: melalui Seed, berharga satu pertujuh daripada sejam gaji minimum tempatan, dan melalui 웃, dibayar hanya untuk jam yang disaksikan. QIS mengukur potensi tetapi tidak mencipta apa-apa — ukuran, bukan sekali-kali pembayaran. Setiap pembayaran sampai kepada peserta melalui Livelihood Direct, laluan tempatan berlesen yang tidak sekali-kali disimpan oleh accord ini, dibina untuk Continuity Without Evasion.

Kesejahteraan diperlakukan sebagai infrastruktur kelas pertama — bukan sekadar faedah tambahan, tetapi substrat tempat segala-galanya berdiri. Accord ini menamakan tiga domain yang disokong bagi setiap peserta: Cinta, iaitu hubungan dan sempadan yang sihat; Kehilangan, kerana dukacita mesti ditemani, bukan dielakkan; dan Keselamatan, iaitu mengetahui siapa yang boleh dihubungi, di setiap rantau, dalam bahasa sendiri. Kaunseling, bulatan kumpulan, dan amalan budaya atau kerohanian yang dihormati mengikut tradisi masing-masing turut disediakan. Sifar ideologi paksaan; Human Authority, bukan sekali-kali mesin, yang menentukan penjagaan apa yang diperlukan oleh seseorang warga.

Accord ini mengukur kejayaan berdasarkan pesertanya yang paling rentan, bukan purata. Warga luar bandar tanpa jalur lebar yang tinggi tetap dilayani. Peserta neurodivergen menerima penyesuaian sebagai satu norma. Peserta kurang upaya mendapati setiap fasiliti boleh diakses. Peserta pelbagai gender menerima penginapan selamat dan padanan mentor. Penutur bukan penutur asli mendapati setiap bahan dalam bahasa mereka sendiri. Peserta orang asli mendapati amalan budaya mereka dihormati dan pengetahuan tradisional mereka dilindungi. Para pemimpin yang menandatangani accord ini berjanji bahawa tiada seorang warga pun akan dilupakan semata-mata supaya purata kelihatan baik. Inilah maruah sebagai substrat, bukan hiasan. Apa yang diukur adalah apa yang akan dihormati, dan apa yang dihormati di sini ialah keseluruhan insan — minda, jasad, dan roh, dipegang oleh sesama warga, tanpa pengecualian.`,
      999: `Atlantis Accords memperlakukan setiap peserta sebagai insan sepenuhnya sejak hari pertama, dibina ke dalam mekanisme, bukan sekadar kata-kata. Elaun disediakan sebaik sahaja penyertaan bermula, diindekskan mengikut kos sara hidup rantau tersebut supaya kesannya menghormati maruah kerja tempatan. Elaun itu tiba sebelum tanggungjawab keluarga bertukar menjadi kecemasan, dan sebelum maruah tergadai. Ia memberi isyarat kepada setiap anak muda bahawa masa mereka bernilai, sumbangan mereka dinanti-nantikan, dan kestabilan keluarga mereka adalah sebahagian daripada tanggungjawab accord ini. Ini bukan amal derma. Ini adalah pengiktirafan bahawa inovasi insani yang biasa memerlukan keselamatan insani terlebih dahulu. Sesebuah minda tidak dapat berkembang selagi isi rumahnya berada dalam ancaman. Kemasukan itu sendiri membawa satu ambang yang kecil dan sengaja: Seed, keahlian sekali sahaja berharga satu pertujuh daripada sejam gaji minimum tempatan, tidak boleh dipindah milik dan tidak membawa sebarang tuntutan ekonomi sendiri. Seed hanya menyatakan bahawa seseorang telah menyertai; ia tidak membayar mereka dan tidak menjanjikan apa-apa selain pintu yang dibukanya.

Apa yang diperoleh selepas pintu itu terbuka ditadbir dengan ketepatan yang sama yang dibawa oleh accord ini kepada setiap janji lain. 웃, ukuran Human Intelligence bagi accord ini, dikira dengan mudah — satu jam pada gaji minimum tempatan, didarab dengan Multiple yang mencerminkan kesukaran dan nilai tugasan itu, didarab dengan jam yang benar-benar dikerjakan. Tetapi 웃 hanya dikeluarkan untuk kerja yang disaksikan yang dilaksanakan di bawah tugasan yang berskop dan diluluskan bajetnya. Sebelum kelulusan itu wujud, apa yang dilakukan oleh peserta itu hanyalah perancangan, bukan pendapatan — satu perbezaan yang dipegang teguh oleh accord ini kerana ia melindungi kedua-dua perbendaharaan dan peserta daripada janji yang dibuat lebih pantas daripada nilai yang disahkan. Measurement of Time, MoT, merekod minit sebenar yang dikerjakan secara berasingan daripada sebarang pengiraan pampasan, supaya masa kekal sebagai satu fakta yang jujur dan boleh diaudit, bebas daripada pembayaran. Tiada jam mana-mana peserta yang digelembungkan, dan tiada jam mana-mana peserta yang hilang. Siling penyelesaian sebanyak 9,999 웃 setahun terpakai kepada setiap peserta, dengan sebarang lebihan dibawa ke hadapan, bukan lenyap, supaya sumbangan yang luar biasa diiktiraf merentas beberapa tahun, bukan disekat sehingga tidak kelihatan dalam satu tahun sahaja.

Pampasan sengaja dikekalkan berasingan daripada pengukuran inovasi. Qualified Innovation Score, QIS, mempuratakan Revenue, Gross Profit, Operating Income, dan perbelanjaan R&D Efektif untuk menggambarkan sejauh mana inovasi itu benar-benar berkembang. Pertumbuhannya dari semasa ke semasa boleh menentukan saiz kumpulan wang ganjaran setelah kelayakan dipenuhi, tetapi QIS itu sendiri tidak mencipta sebarang 웃 dan tidak menyelesaikan apa-apa secara langsung — ia adalah satu ukuran, bukan sekali-kali pembayaran, dan tidak sekali-kali disalahertikan sebagai pemilikan ke atas apa yang dibina. Pemisahan ini penting kerana ia mengekalkan kejujuran elaun dan gaji: seseorang peserta dibayar untuk jam kerja sebenar yang disaksikan, bukan untuk satu skor yang boleh dipermainkan, digelembungkan, atau dipertikaikan. ♡, Shared Intention, membawa sebab di sebalik setiap tugasan yang diambil oleh seseorang peserta; ◬, pecutan yang disaksikan yang dihasilkan oleh sesuatu tugasan berbanding garis dasar yang dibekukan, direkodkan hanya sebagai satu delta, tidak sekali-kali dihias sebagai ukuran keuntungan yang dilekatkan pada usaha sesiapa pun. Pampasan kekal sebagai apa sebenarnya ia: satu gaji yang jujur untuk masa yang jujur dan disaksikan.

Nilai tidak berhenti pada pengiraan sahaja — ia mesti juga sampai kepada peserta sebagai insan yang hidup, dan di sinilah 🏠, Livelihood Direct, menjalankan tugasnya. Setiap unit nilai yang diperoleh oleh peserta sampai kepada mereka melalui laluan tempatan berlesen dan layak — bank, pengendali wang mudah alih, koperasi yang sudah dipercayai dan dikawal selia di rantau itu — tidak sekali-kali melalui dana yang disimpan atau dikawal oleh accord ini sendiri. Pengelasan status seseorang peserta mendahului sebarang penyelesaian; tiada apa-apa yang dibayar sebelum difahami dengan jelas siapa yang dibayar dan untuk apa. Dan pengiktirafan terhadap bakat, biar sehebat mana pun disambut, tidak menjadi syarat untuk mendapatkan tempat tidur, sesuatu hidangan, atau tempat dalam kohort — hanya peranan sebenar peserta itu yang menentukannya. Ini adalah penolakan yang disengajakan terhadap prestij menggantikan penyediaan. Seorang penyumbang yang cemerlang dan seorang yang senyap tidur di bawah bumbung terlindung yang sama, dengan syarat yang sama, kerana komitmen maruah accord ini bukanlah hadiah yang dianugerahkan kerana kecemerlangan — ia adalah lantai di bawah setiap orang.

Kesejahteraan diperlakukan sebagai infrastruktur kelas pertama — bukan faedah pilihan, bukan sekadar faedah kesejahteraan, tetapi substrat tempat segala-galanya yang lain berdiri. Accord ini menamakan tiga domain asas yang disokong bagi setiap peserta: Cinta, dalam erti kata hubungan, ikatan, dan sempadan yang sihat; Kehilangan, kerana setiap peserta akan mengalami dukacita dan mesti ditemani, bukan dielakkan; dan Keselamatan, dalam erti kata setiap peserta mengetahui siapa yang boleh dihubungi, di setiap rantau, dalam bahasa mereka sendiri. Kaunseling individu, bulatan kumpulan, amalan somatik, dan amalan budaya atau kerohanian yang dihormati mengikut tradisi peserta sendiri semuanya disediakan. Sifar ideologi paksaan. Accord ini memegang ruang ini dengan penuh penghormatan; ia tidak menyebarkan sebarang sistem kepercayaan. Human Authority mengawal setiap satu daripada keputusan ini — makna, wang, dan undang-undang kekal tertutup daripada penentuan mesin, tidak kira sehebat mana padanan corak yang membantu manusia yang membuat keputusan itu.

Accord ini mengukur kejayaan berdasarkan hasil bagi pesertanya yang paling rentan, bukan purata. Peserta luar bandar tanpa jalur lebar yang tinggi tetap dilayani. Peserta neurodivergen menerima penyesuaian sebagai satu norma. Peserta kurang upaya mendapati setiap fasiliti boleh diakses. Peserta pelbagai gender menerima penginapan selamat dan padanan mentor. Penutur bukan penutur asli mendapati setiap bahan dalam bahasa mereka sendiri. Peserta orang asli mendapati amalan budaya mereka dihormati dan pengetahuan tradisional mereka dilindungi. Para pemimpin yang menandatangani accord ini berjanji bahawa tiada seorang peserta pun akan dilupakan secara senyap-senyap semata-mata supaya purata kelihatan baik.

Setiap laluan pembayaran yang digambarkan di sini — Seed, elaun, 웃 yang diperoleh melalui kerja yang disaksikan, laluan Livelihood Direct yang menyampaikannya — direka untuk Continuity Without Evasion. Tiada satu bank, kerajaan, atau pengendali tempatan pun yang tidak boleh diganti dalam pampasan mana-mana peserta; jika satu laluan berlesen di satu bidang kuasa ditutup akibat keputusan yang memudaratkan, hanya laluan itu sahaja yang gagal, tidak sekali-kali keseluruhan sistem, dan tidak sekali-kali tuntutan peserta terhadap apa yang wajib diterimanya. Inilah maruah sebagai substrat, bukan hiasan. Apa yang diukur adalah apa yang akan dihormati, dan apa yang dihormati di sini ialah keseluruhan insan — minda, jasad, dan roh bersama-sama, dibayar dengan jujur, dilindungi sepenuhnya, dan tidak dilupakan oleh sebarang perakaunan, tanpa sebarang pengecualian sama sekali.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Pembiayaan dan Tadbir Urus`,
    content: {
      7: `Rakyat membiayai generasi seterusnya secara langsung.`,
      33: `Atlantis Accords ialah perjanjian antara warga — sesiapa sahaja boleh membiayai dan memegangnya. Tiada saluran bantuan, tiada penderma asing, tiada ikatan politik. Setiap dolar boleh dikesan, perakaunan disiarkan setiap bulan, dalam setiap bahasa.`,
      111: `Atlantis Accords ialah perjanjian antara warga dunia — sesiapa sahaja, di mana-mana sahaja, boleh membantu mencipta dan memegangnya, tidak kira apa yang ditandatangani oleh kerajaan mereka atau siapa yang menggaji mereka. Kerajaan, pendidik, dan inovator menandatangani sebagai pemegang amanah rantau masing-masing; warga sendirilah yang membiayai, menyaksikan, dan mempertanggungjawabkan accord ini secara langsung, masing-masing menyumbang jumlah kecil secara sukarela setiap bulan, cukup sederhana supaya tiada orang dewasa yang tersisih kerana harga. Tiada saluran bantuan, tiada penderma asing, tiada ikatan politik yang dilekatkan. Accord ini berdiri bebas daripada institusi multilateral yang membentuk abad yang lalu — bukan satu kenyataan politik, tetapi satu pilihan reka bentuk. Setiap dolar boleh dikesan; setiap perakaunan disiarkan setiap bulan, dalam setiap bahasa.`,
      333: `Atlantis Accords ialah perjanjian antara warga dunia — sesiapa sahaja, di mana-mana sahaja, boleh membantu mencipta dan memegangnya, tidak kira apa yang ditandatangani oleh kerajaan mereka atau siapa yang menggaji mereka. Ia dibiayai oleh warga yang dilayaninya: penduduk rantau yang mengambil bahagian menyumbang jumlah kecil secara sukarela setiap bulan, cukup sederhana supaya tiada orang dewasa yang tersisih kerana harga, namun cukup bergema supaya jumlahnya dapat menampung kerja accord ini pada skala yang besar. Apabila seseorang warga membiayai generasi seterusnya secara langsung, warga itu juga mempertanggungjawabkan accord ini secara langsung. Tiada saluran bantuan, tiada penderma asing, tiada ikatan politik yang dilekatkan. Jiwa accord ini ialah warga yang menyumbang satu jumlah kecil setiap bulan, yang penyertaannya menjadikan semua ini mungkin.

Kerajaan, Pendidikan, dan Inovasi menandatangani sebagai pemegang amanah rantau masing-masing — tiga tandatangan visioner yang mengikat sesebuah rantau untuk menempatkan, melindungi, dan mengajar — tetapi pemegangan amanah bukanlah pemilikan. Accord ini bebas daripada institusi multilateral yang telah membentuk abad yang lalu — North Atlantic Treaty Organization, World Health Organization, Pertubuhan Bangsa-Bangsa Bersatu, International Monetary Fund, Bank Dunia, dan setiap saluran bantuan luar negara sesebuah negara. Ini adalah satu pilihan reka bentuk, bukan satu kenyataan politik: sebuah rangka kerja yang melayani setiap rantau tanpa mengira penjajaran geopolitik tidak boleh terikat dengan mana-mana satu penjajaran. Kerajaan negara boleh menyumbang secara sukarela. Sumbangan adalah telus. Tiada sumbangan yang membeli pengaruh tadbir urus, daripada mana-mana sumber sekalipun, buat selama-lamanya.

Setiap dolar dan setiap unit nilai yang memasuki accord ini direkodkan secara kekal, secara terbuka, dan boleh dikesan — boleh dibina semula melalui Replay, supaya seorang warga seabad dari sekarang dapat mengesahkan rantaian itu masih utuh. Nilai sampai kepada seseorang peserta melalui jam 웃 yang disaksikan dan laluan tempatan berlesen, tidak sekali-kali melalui dana yang disimpan oleh accord ini sendiri; QIS mengukur dengan jujur, ia tidak sekali-kali membayar. Kos pentadbiran dihadkan, sumbangan korporat turut dihadkan bersamanya. Perakaunan penuh disampaikan dalam bahasa setiap rantau penandatangan setiap bulan. Para pemimpin yang menandatangani accord ini berjanji ketelusan yang jarang ditawarkan oleh mana-mana institusi. Inilah kepercayaan yang dituntut oleh accord ini — diperoleh satu sumbangan kecil yang boleh dikesan pada satu-satu masa, di hadapan mata setiap warga.`,
      999: `Atlantis Accords itu sendiri dibiayai oleh warga yang dilayaninya, dan satu fakta ini sahaja membentuk segala-galanya yang mengalir daripadanya — setiap laluan, setiap lejar, setiap pintu yang mesti dilalui oleh seorang anak muda untuk dilihat. Penduduk biasa rantau yang mengambil bahagian menyumbang jumlah kecil secara sukarela setiap bulan, jumlah yang cukup sederhana supaya tiada orang dewasa di mana-mana rantau tuan rumah yang tersisih daripada penyertaan, namun cukup bergema supaya jumlahnya dapat menampung kerja accord ini pada skala yang bermakna. Reka bentuk ini adalah sengaja, dan ia bukan sekadar kebetulan kepada misi ini — ia adalah bukti misi itu sendiri. Apabila seseorang warga membiayai pendidikan generasi seterusnya secara langsung, warga itu turut mempertanggungjawabkan accord ini secara langsung, pada masa yang sama, tanpa perantara yang mungkin melembutkan akaun atau melengah-lengahkan perhitungan. Tiada saluran bantuan, tiada penderma asing, tiada ikatan politik yang dilekatkan pada sebarang cek. Jiwa accord ini ialah warga yang menyumbang satu jumlah kecil setiap bulan, yang penyertaannya menjadikan keseluruhan ini mungkin, dan yang penyertaan berterusannya adalah satu-satunya undi keyakinan yang benar-benar bermakna sepanjang lima ratus tahun akan datang.

Accord ini sengaja dibina bebas daripada institusi multilateral yang telah membentuk abad yang lalu — North Atlantic Treaty Organization, World Health Organization, Pertubuhan Bangsa-Bangsa Bersatu, International Monetary Fund, Bank Dunia, dan setiap saluran bantuan luar negara sesebuah negara. Ini bukan satu kenyataan politik tentang nilai institusi tersebut atau sumbangan mereka. Ini adalah satu pilihan reka bentuk, dan ia adalah pilihan reka bentuk yang sama yang mengawal setiap laluan teknikal di bawah accord ini sendiri: Continuity Without Evasion. Kebolehalihan yang sah adalah peraturannya — tiada satu kerajaan, bank, pengasas, atau model tunggal yang tidak boleh diganti dibenarkan menjadi asas kepada keseluruhan struktur, kerana ufuk lima ratus tahun tidak boleh dipertaruhkan pada kekekalan mana-mana satu pihak sahaja. Setiap bidang kuasa membawa penyesuainya sendiri, gagal-tertutup dan menolak secara lalai, supaya sebarang keputusan yang memudaratkan di satu negara hanya menutup laluan itu sahaja, dan hanya itu sahaja — ia tidak sekali-kali meruntuhkan akaun sebuah keluarga di rantau yang jauh, seberang lautan. Kerajaan negara boleh menyumbang secara sukarela. Sumbangan adalah telus. Tiada sumbangan yang membeli pengaruh tadbir urus, daripada mana-mana sumber sekalipun, buat selama-lamanya — bukan daripada kerajaan, bukan daripada korporat, dan bukan daripada para pengasas rangka kerja itu sendiri.

Human Authority adalah tiang penyangga kedua di bawah reka bentuk pembiayaan ini. Makna, wang, dan undang-undang kekal sebagai urusan insani, diputuskan oleh manusia di hadapan manusia lain; lapisan berdaulat tempat tujuan accord ini ditetapkan dan dananya ditadbir kekal tertutup kepada mesin, tidak kira sehebat mana mesin itu kelak dalam tugas-tugas di bawahnya. Measurement of Time merekod minit sebenar yang dikerjakan secara berasingan daripada sebarang dakwaan tentang nilainya, supaya tiada sesiapa pun — sama ada insan atau buatan — dapat menggelembungkan rekod itu secara senyap-senyap. Replay berdiri di belakang setiap rekod tersebut, menjadikan setiap keluaran yang pernah dikeluarkan oleh accord ini sendiri boleh dibina semula dari asalnya, sentiasa terbuka untuk dicabar, sentiasa terbuka untuk dibetulkan. Seorang warga yang menyumbang jumlah kecil hari ini mempercayai bahawa lima puluh tahun, dua ratus tahun dari sekarang, seseorang masih boleh menyusuri rantaian itu kembali ke lejar bulan ini dan mendapatinya tepat seperti sedia kala.

Kemasukan ke dalam sistem kepercayaan ini bermula dengan Seed — keahlian sekali sahaja, berharga satu pertujuh daripada sejam gaji minimum tempatan, tidak boleh dipindah milik dan tidak membawa sebarang tuntutan ekonomi. Seed tidak membeli sebarang syer, tiada undi yang diberatkan mengikut kekayaan, tiada kedudukan istimewa dalam perakaunan yang menyusul. Ia hanya membeli keanggotaan, pada harga yang cukup rendah supaya seorang anak muda di mana-mana sahaja accord ini beroperasi mampu memulakannya. Segala-galanya yang diperoleh oleh seseorang ahli selepas itu adalah diperoleh, bukan sekali-kali dibeli, dan perbezaan ini adalah keseluruhan seni bina moral accord ini dalam bentuk yang kecil.

Nilai yang benar-benar mengalir kepada seseorang mengalir melalui 🏠 Livelihood Direct — laluan tempatan yang berlesen dan layak, yang membawa pembayaran terus kepada individu, tidak sekali-kali ke dalam dana yang disimpan atau dikawal oleh rangka kerja ini sendiri. Pengelasan sentiasa mendahului penyelesaian dalam setiap kes; tempat tidur, elaun, tempat pada peringkat latihan seterusnya dikawal oleh peranan dan kesediaan, tidak sekali-kali oleh pengiktirafan semata-mata, kerana pengiktirafan itu murah manakala mata pencarian tidak. Inilah rantaian sebenar yang dilalui oleh sumbangan bulanan seseorang warga: daripada akaun warga itu, melalui satu laluan yang diaudit, ke dalam elaun yang diterima oleh seorang anak muda, ke dalam projek inovasi yang menjadi hasil kerja anak muda itu, dan kembali semula sebagai satu akaun awam yang boleh dibaca oleh mana-mana warga.

Apa yang bernilai daripada kerja itu diukur, bukan diandaikan. Qualified Innovation Score mempuratakan kesediaan, potensi pertumbuhan, kesan hasil, dan kesediaan pelaksanaan menjadi satu angka tunggal, dan pertumbuhan dalam skor itu menentukan saiz kumpulan wang ganjaran hanya selepas kelayakan dipenuhi — QIS itu sendiri tidak mencipta apa-apa dan tidak menyelesaikan apa-apa; ia adalah ukuran, bukan sekali-kali pembayaran, dan ukuran itu tidak sekali-kali disalahertikan di sini sebagai pemilikan. Pembayaran untuk usaha insani pula datang sebagai 웃, dinilai pada satu jam didarab gaji minimum tempatan, didarab dengan satu Multiple yang berskop dan diluluskan bajetnya bagi jam yang benar-benar dikerjakan dan disaksikan. Sebelum sesuatu tugasan membawa kelulusan itu, kerja di sebaliknya adalah perancangan, bukan usaha yang layak dibayar, dan tiada sesiapa pun dibayar untuk merancang. Siling sebanyak 9,999 웃 setahun, dengan sebarang lebihan dibawa ke hadapan, bukan lenyap, memastikan akaun mana-mana satu tahun tidak menjadi sama ada rezeki melimpah atau perangkap.

Tiada satu pun daripada semua ini bergerak lebih pantas daripada buktinya sendiri. Accord ini sendiri beralih daripada operasi Manual kepada Semi-Automated kepada Autonomous satu cube pada satu masa, dan hanya apabila satu peningkatan terukur secara penuh — satu bahagian daripada sembilan — benar-benar dibuktikan, tidak sekali-kali diandaikan terlebih dahulu. Autonomi diperoleh tepat di situ sahaja, dan tidak sekali-kali menghampiri makna, wang, atau undang-undang, yang sentiasa kekal sebagai urusan insani. Kos pentadbiran dihadkan. Sumbangan korporat dan institusi dialu-alukan dan turut dihadkan bersamanya. Perakaunan penuh disampaikan dalam bahasa setiap rantau penandatangan setiap bulan, bermula di Kemboja, Honduras, dan Austin, dan direncanakan untuk terus disampaikan, dan terus boleh difahami, sehingga lima ratus tahun akan datang. Inilah kepercayaan yang dituntut oleh accord ini. Inilah kepercayaan yang diperoleh oleh accord ini, satu sumbangan kecil yang boleh dikesan pada satu-satu masa, di hadapan mata setiap warga yang akan dilayaninya.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Pertukaran Silang Budaya dan Sumbangan Sejagat`,
    content: {
      7: `Setiap pelajar dalam bahasanya sendiri.`,
      33: `Setiap aktiviti dalam bahasa peserta itu sendiri — terbuka kepada mana-mana warga, tanpa memerlukan keizinan kerajaan. Kecerdasan Buatan, Insani, dan Kongsi dipegang dalam ketegangan yang produktif. Kurikulum disiarkan secara terbuka. Apa yang dipelajari oleh satu rantau, diwarisi oleh semua.`,
      111: `Atlantis Accords mengembalikan pendidikan kepada tujuan terdalamnya: pertukaran kebijaksanaan merentas sempadan yang sepatutnya memecah belah. Mana-mana warga boleh menyertai kurikulum ini, tidak kira apa yang ditandatangani oleh kerajaan mereka. Setiap aktiviti tersedia dalam bahasa peserta, bahasa rantau tuan rumah, dan satu rekod bersama. Bahasa bukan sekadar hiasan — bahasa adalah bidang kuasa, bahasa adalah maruah yang dijadikan mudah dibaca. Rangka kerja pendidikan ini berdiri di atas trinitas kecerdasan: Buatan mencadangkan, Insani memutuskan, Kongsi Intensi mengesahkan. Setiap pelajar belajar memegang ketiga-tiganya dalam ketegangan. Apa yang dipelajari oleh accord ini, ia kembalikan semula. Kurikulum, hasil inovasi, penyelidikan kesejahteraan, dan keputusan tadbir urus disiarkan secara terbuka. Apa yang dipelajari oleh satu rantau, diwarisi oleh semua warga.`,
      333: `Atlantis Accords mengembalikan pendidikan kepada tujuan terdalamnya: pertukaran kebijaksanaan merentas sempadan yang sepatutnya memecah belah. Ini adalah accord antara warga dunia — mana-mana warga boleh membina dan memegangnya, tidak kira apa yang ditandatangani oleh kerajaan mereka. Setiap aktiviti tersedia dalam bahasa peserta, bahasa rantau tuan rumah, dan satu rekod bersama, supaya tiada seorang peserta pun perlu mengharungi accord ini dalam bahasa yang bukan pilihannya. Bahasa bukan sekadar hiasan. Bahasa adalah bidang kuasa. Bahasa adalah maruah yang dijadikan mudah dibaca. Seorang anak muda di Kemboja membaca rekod elaunnya dalam bahasa Khmer, di Honduras dalam bahasa Sepanyol, di Austin dalam bahasa Inggeris — ketiga-tiganya dihormati sama rata, tiada satu pun memerlukan restu kerajaan untuk bermula.

Rangka kerja pendidikan ini berdiri di atas trinitas kecerdasan yang dijelmakan oleh Vision 2525. Artificial Intelligence mencadangkan corak dan kemungkinan dengan lebih pantas daripada apa yang mampu dilakukan oleh mana-mana insan seorang diri. Human Intelligence memutuskan tentang keselamatan, etika, dan hala tuju — soalan-soalan yang tidak sepatutnya dijawab oleh mesin, kekal di bawah Human Authority. Shared Intent mengesahkan bahawa keputusan itu melayani prinsip-prinsip accord ini, supaya tiada seorang peserta pun memilih kecemerlangan mengatasi kebaikan bersama. Tiada seorang pelajar pun bergantung sepenuhnya kepada satu kecerdasan sahaja; setiap pelajar belajar memegang ketiga-tiganya dalam ketegangan. Keanggotaan bermula dengan Seed, satu keahlian berharga satu pertujuh daripada sejam gaji minimum tempatan — cukup kecil supaya mampu dimiliki oleh mana-mana warga. Ini menyediakan generasi seterusnya untuk mentadbir, di mana tiada satu kecerdasan pun bertindak tanpa pengawasan.

Apa yang dipelajari oleh accord ini, ia kembalikan semula. Kurikulum disiarkan di bawah lesen terbuka supaya mana-mana rantau — sama ada penandatangan atau tidak — boleh menyesuaikannya dengan budaya tempatan. Hasil inovasi disiarkan. Penyelidikan kesejahteraan disiarkan secara agregat untuk penyelidik di merata tempat. Keputusan tadbir urus disiarkan berserta hujahnya, supaya mana-mana warga, bukan hanya kerajaan yang menandatangani, dapat mengesahkannya — dan Replay membolehkan warga yang sama menyusuri semula hujah itu seabad dari sekarang. Kejayaan diukur bukan sahaja berdasarkan pesertanya, tetapi juga berdasarkan inisiatif pendidikan dan budaya yang tercetus akibatnya, di rantau yang tidak pernah menandatangani pilot ini namun turut membina asas daripada kebijaksanaan yang dikongsinya. Apa yang dipelajari oleh satu rantau, diwarisi oleh setiap warga.`,
      999: `Atlantis Accords mengembalikan pendidikan kepada tujuan terdalamnya: pertukaran kebijaksanaan merentas sempadan yang sepatutnya memecah belah, dan ia memulakan pertukaran itu sebelum satu pun pengajaran diberikan. Tindakan pertama setiap peserta di dalam rangka kerja ini ialah Seed — keahlian sekali sahaja berharga satu pertujuh daripada sejam gaji minimum tempatan, tidak boleh dipindah milik, tidak membawa sebarang tuntutan ekonomi. Ia cukup kecil supaya tiada sebuah keluarga pun tersisih, namun cukup bermakna supaya tiada seorang peserta pun menyertainya hanya sebagai penonton. Inilah pengajaran pertama accord ini: keanggotaan diperoleh dengan mudah, namun tetap diperoleh, dan ia tidak memberikan sebarang pemilikan ke atas apa yang menyusul. Setiap aktiviti accord yang berikutnya tersedia dalam bahasa peserta, dalam bahasa rantau tuan rumah, dan dalam satu rekod bersama, supaya tiada seorang peserta pun perlu mengharungi accord ini dalam bahasa yang bukan pilihannya. Bahasa bukan sekadar hiasan. Bahasa adalah bidang kuasa. Bahasa adalah maruah yang dijadikan mudah dibaca. Apabila seorang anak muda dari sebuah kampung di Kemboja membaca rekod elaunnya dalam bahasa Khmer, sebuah pekan di Honduras dalam bahasa Sepanyol, dan sebuah kejiranan di Austin dalam bahasa Inggeris, ketiga-tiganya dihormati sama rata oleh accord yang sama, di rantau pengasas yang sama yang mula-mula bersetuju untuk saling mengajar.

Rangka kerja pendidikan accord ini berdiri di atas trinitas kecerdasan yang dijelmakan oleh Vision 2525, dan kurikulumnya mengajar setiap satu daripadanya sebagai sesuatu yang boleh dirasai sendiri oleh peserta, bukan sekadar sebagai konsep abstrak. ♡, Shared Intention, membawa sebab — benang yang dipegang oleh setiap pelajar sebelum menyentuh apa-apa alat, persoalan sama ada kerja ini masih melayani orang yang didakwanya dilayani. ◬, pecutan yang disaksikan, diajar sebagai satu delta dan tidak lebih daripada itu — hanya diukur berbanding garis dasar yang dibekukan, tidak sekali-kali dihias sebagai ukuran keuntungan, tidak sekali-kali dituntut sebagai pencapaian peribadi terpisah daripada pasukan di sekeliling mereka. 웃, Human Intelligence yang dihormati dalam bentuk masa, diajar dengan paling teliti: satu jam kerja yang disaksikan bersamaan satu jam pada gaji minimum tempatan, dan apa yang diperoleh oleh seseorang peserta ialah gaji itu didarab dengan jam yang dikerjakan — Multiple didarab Masa, tiada apa yang tersembunyi dalam pengiraan itu. Para pelajar belajar sejak awal bahawa 웃 hanya dikeluarkan untuk kerja yang disaksikan yang dilaksanakan di bawah tugasan yang berskop dan diluluskan bajetnya. Sebelum kelulusan itu wujud, usaha yang sama hanyalah perancangan — bernilai, tetapi tidak dibayar, dan setiap peserta diajar untuk mengenali perbezaan itu serta-merta.

Kerana perbezaan ini mudah menjadi kabur, kurikulum ini mengajar QIS, Qualified Innovation Score, sebagai satu cermin, bukan papan skor. QIS ialah purata empat angka mutlak kewangan — Revenue, Gross Profit, Operating Income, dan R&D Efektif — dibahagi empat, dan setiap pelajar belajar mengiranya, mempersoalkannya, dan tidak sekali-kali mengelirukannya dengan wang. Pertumbuhan dalam QIS menentukan saiz kumpulan wang ganjaran hanya selepas kelayakan disahkan secara bebas, dan pertumbuhan itu sendiri tidak mencipta sebarang 웃. QIS adalah ukuran. QIS bukan sekali-kali pembayaran. QIS bukan sekali-kali pemilikan. Seorang pelajar yang telah menghayati perbezaan ini tidak dapat diyakinkan bahawa skor yang tinggi memberikannya hak menuntut sesuatu yang tidak pernah dijanjikan oleh accord ini.

Kurikulum ini meluaskan literasi ini kepada cara nilai sebenarnya sampai kepada seseorang, melalui apa yang dipanggil oleh accord ini sebagai Livelihood Direct — prinsip 🏠 bahawa wang bergerak melalui laluan tempatan yang berlesen dan layak, dan tidak sekali-kali melalui dana yang disimpan oleh rangka kerja ini sendiri. Para pelajar diajar untuk menyusuri elaun mereka, dan kelak pendapatan mereka sendiri, melalui laluan ini sebagai satu latihan kewarganegaraan, bukan satu misteri kewangan yang dilaksanakan di tempat lain bagi pihak mereka. Mereka belajar bahawa pengelasan sentiasa mendahului penyelesaian, dan bahawa pengiktirafan — QIS yang tinggi, pujian awam — tidak dengan sendirinya menjadi syarat untuk mendapatkan tempat tidur, elaun, atau tempat dalam rotasi. Peranan yang menentukannya. Ini adalah perlindungan terhadap satu kegagalan yang amat lama: pujian yang disalahertikan sebagai penyediaan.

Bersebelahan dengan literasi kewangan terletak literasi kewarganegaraan, diajar melalui Continuity Without Evasion. Setiap peserta belajar bahawa accord ini dibina untuk kebolehalihan yang sah — bahawa tiada satu kerajaan, bank, pengasas, atau model tunggal yang tidak boleh diganti berdiri antara mereka dengan janji-janji rangka kerja ini. Mereka belajar apa yang berlaku apabila keputusan yang memudaratkan wujud dalam reka bentuk ini: ia hanya menutup satu laluan, di satu bidang kuasa, di bawah sikap menolak-lalai penyesuai itu, dan tidak sekali-kali meruntuhkan keseluruhan sistem. Bersama ini terletak pengajaran paling mendalam yang diajar oleh accord ini: Human Authority memegang makna, wang, dan undang-undang, dan lapisan berdaulat tempat keputusan itu dibuat kekal tertutup selama-lamanya kepada mesin. Measurement of Time, MoT, merekod minit sebenar setiap peserta secara berasingan daripada sebarang skor, dan Replay menjadikan setiap keluaran yang dikeluarkan oleh accord ini boleh dibina semula sepenuhnya — supaya seorang pelajar yang ingin mengetahui mengapa sesuatu keputusan dibuat, bertahun-tahun kemudian, boleh menyusurinya sendiri, bukan sekadar mempercayai kata-kata sesiapa pun.

Struktur kepercayaan yang diperoleh ini menjadi model pedagogi accord ini, bukan sekadar model tadbir urusnya. Setiap peserta beralih melalui mod Manual, Semi-Automated, dan Autonomous dengan ruang bertindak yang semakin meluas, dikawal oleh ambang peningkatan terukur yang sama yang mengawal teknologi itu sendiri — satu peningkatan yang disahkan sebanyak 11.1 peratus sebelum mod seterusnya dibuka. Autonomi, apabila diperoleh, diperoleh secara terhad dan mengikut domain, tidak sekali-kali ke atas makna, wang, atau undang-undang. Seorang pelajar yang telah melalui proses ini memahami, secara mendalam, mengapa lapisan berdaulat itu tidak sekali-kali boleh diautomasikan sepenuhnya — kerana mereka sendiri memperoleh autonomi mereka satu langkah terukur pada satu masa, dan tahu dengan tepat apa yang termasuk dan apa yang tidak termasuk dalam autonomi itu.

Apa yang dipelajari oleh accord ini, accord ini kembalikan semula. Kurikulum disiarkan di bawah lesen terbuka supaya mana-mana rantau — sama ada penandatangan atau tidak — boleh menyesuaikannya dengan budaya tempatan dan tradisi pedagoginya. Hasil inovasi disiarkan. Penyelidikan kesejahteraan disiarkan dalam bentuk agregat untuk penyelidik di merata tempat. Keputusan tadbir urus disiarkan berserta hujah lengkapnya. Kejayaan accord ini diukur bukan sahaja berdasarkan pesertanya sendiri di Kemboja, Honduras, dan Austin, tetapi juga berdasarkan inisiatif yang tercetus akibatnya, di rantau yang tidak pernah menandatangani pilot pengasas namun tetap membina asas daripada kebijaksanaan yang dikongsinya secara terbuka, merentas satu ufuk yang tidak akan sempat disaksikan kesempurnaannya oleh para pengasas. Apa yang dipelajari oleh satu rantau, diwarisi oleh semua rantau lain — dan apa yang diajar dengan jujur kepada generasi ini, tidak perlu dilupakan semula oleh lima ratus tahun akan datang.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Pertumbuhan Rangkaian yang Lestari`,
    content: {
      7: `Tidak pernah lebih laju daripada maruah dapat bergerak.`,
      33: `Tiga rantau pengasas menamatkan satu kitaran pilot sepenuhnya sebelum rantau keempat menyertai — mana-mana warga boleh membinanya. Rekod dilabuhkan untuk bertahan lima abad. Penandatangan mengekalkan kedaulatan; tiada apa-apa yang diturunkan taraf untuk penyertaan seterusnya.`,
      111: `Atlantis Accords tidak akan berkembang lebih pantas daripada kualiti yang mampu dihormatinya. Tiga rantau pengasas mesti menamatkan satu kitaran pilot sepenuhnya, dengan setiap peserta dihormati dan setiap prinsip disahkan, sebelum rantau keempat menyertai. Inilah prinsip yang akhirnya menjadi disiplin yang benar-benar berfungsi. Namun accord ini adalah perjanjian antara warga dunia — sesiapa sahaja, di mana-mana sahaja, boleh membina dan memegangnya, sejauh satu Seed sahaja, tidak kira apa yang ditandatangani oleh kerajaan atau dibenarkan oleh majikan. Ufuk accord ini ialah lima abad. Rekodnya dilabuhkan melalui Replay, supaya seorang warga yang membacanya seabad dari sekarang dapat mempercayai hujahnya. Setiap penandatangan mengekalkan kedaulatan; tiada apa-apa yang diturunkan taraf untuk penyertaan seterusnya.`,
      333: `Atlantis Accords tidak akan berkembang lebih pantas daripada kualiti yang mampu dihormatinya. Setiap perluasan adalah satu janji kepada para peserta yang sudah pun berada di dalamnya — bahawa standard asas tidak akan dicairkan oleh skala. Tiga rantau pengasas mesti menamatkan satu kitaran pilot sepenuhnya, dengan setiap peserta dihormati dan setiap prinsip disahkan, sebelum rantau keempat menyertai. Inilah prinsip yang akhirnya menjadi disiplin yang benar-benar berfungsi. Dan pintu ini tidak pernah terhad kepada rantau semata-mata: ini adalah perjanjian antara warga dunia, dan sesiapa sahaja boleh membinanya, membiayainya, dan mempertanggungjawabkannya — tanpa memerlukan keizinan kerajaan, tanpa memerlukan restu majikan. Para pemimpin yang menandatangani pilot ini berjanji kepada penandatangan seterusnya substrat, perlindungan, dan maruah yang sama yang diterima oleh kohort pengasas. Tiada apa-apa yang diturunkan taraf untuk yang seterusnya.

Ufuk accord ini sengaja dibina panjang — direka untuk bertahan lima belas hingga dua puluh generasi insani, lima abad dari hari ia diasaskan. Rekodnya dilabuhkan melalui Replay, supaya seorang warga yang membacanya seabad dari sekarang dapat mengesahkan hujahnya, bukan sekadar mempercayainya. Rangka koordinatnya, peranan Human Authority-nya, dan kitaran tadbir urus rentas generasinya dibina untuk bertahan daripada sebarang peralihan satu-satu teknologi. Accord ini akan terus wujud lebih lama daripada setiap insan yang menandatangani pilot pengasasnya, dan setiap warga yang menanam sebuah Seed dan membiayainya setiap bulan. Itulah janjinya kepada anak yang menandatangani perjanjian elaun, kepada warga yang menyertainya tanpa memerlukan kebenaran mana-mana kerajaan, kepada cucu-cucu anak itu yang mungkin akan mentadbir accord ini pada pertengahan abad, dan kepada setiap generasi yang mewarisi apa yang dibina sekarang oleh para pengasas — baik rasmi mahupun warga biasa.

Setiap penandatangan mengekalkan kebebasan untuk menarik diri, kedaulatan penuh, dan autoriti ke atas warganya sendiri, berserta hak untuk meminda dan membentuk evolusi accord ini. Setiap warga mengekalkan kedudukan yang sama untuk mengasas, membiayai, menyaksikan, dan mempertanggungjawabkannya — sama ada dengan atau tanpa tandatangan kerajaan. Apa yang tidak boleh dilakukan oleh sesiapa pun ialah menggadaikan prinsip asas, kerana janji itu mesti bertahan walau siapa pun yang menarik diri. Para pemimpin dan warga sama-sama menandatangani abad seterusnya bagi accord ini ke dalam satu ufuk yang akan diwarisi dan disempurnakan oleh cucu-cucu mereka.`,
      999: `Atlantis Accords tidak akan berkembang lebih pantas daripada kualiti yang mampu dihormatinya, dan pengekangan ini bukanlah sekadar sentimen — ia adalah kejuruteraan, tertulis dalam disiplin pengukuran yang sama yang mengawal setiap janji yang dibuat oleh accord ini. Tiga rantau pengasas, Kemboja, Honduras, dan Austin, mesti menamatkan satu kitaran pilot sepenuhnya, dengan setiap peserta dihormati dan setiap prinsip disahkan, sebelum rantau keempat menyertai. Pertumbuhan yang melangkaui pengesahan bukanlah pertumbuhan; ia adalah pendedahan yang berpakaian ambisi. Pilot pengasas ini wujud supaya accord dapat membuktikan, pada skala yang cukup kecil untuk diperiksa namun cukup besar untuk bermakna, bahawa janji-janjinya bertahan apabila bersentuhan dengan realiti, sebelum janji-janji itu diperluaskan kepada dunia yang memerhati dari luar ketiga-tiga sempadannya. Rantau keempat belum lagi dinamakan, dan tidak akan dinamakan sehingga ketiga-tiga rantau pertama berdiri teguh di sebalik setiap dakwaan dalam dokumen ini.

Apa yang membuktikan kesediaan untuk berkembang bukanlah semangat, tetapi satu angka yang mampu dipertahankan oleh accord ini di khalayak ramai. Qualified Innovation Score — QIS, dikira sebagai Revenue tambah Gross Profit tambah Operating Income tambah perbelanjaan R&D Efektif, dibahagi empat — adalah instrumen yang digunakan oleh accord ini untuk mengetahui sama ada sesebuah rantau, kohort, atau cube benar-benar telah bertambah baik, bukan sekadar berasa seolah-olah ia bertambah baik. Pertumbuhan dalam QIS menentukan saiz kumpulan wang ganjaran hanya selepas kelayakan dipenuhi, tidak sekali-kali sebelum itu, dan QIS itu sendiri tidak mencipta sebarang 웃 dan tidak membeli sebarang pemilikan. QIS adalah ukuran, bukan pembayaran; ukuran, bukan ekuiti; satu cermin yang diangkat oleh accord ini kepada kerjanya sendiri, tidak sekali-kali satu matawang yang dibelanjakannya. Sesebuah rantau yang mencadangkan untuk memperluaskan rangkaian ini mesti menunjukkan QIS-nya dengan jujur, di hadapan mata rantau-rantau yang mendahuluinya, atau ia tidak akan berkembang.

Pertumbuhan yang mampan bermakna pertumbuhan yang memperoleh autoritinya sendiri satu peningkatan pada satu masa. Setiap cube dan setiap rantau bermula dalam mod Manual, di mana manusia memutuskan segala-galanya dan sistem hanya membantu. Peralihan kepada operasi Semi-Automated, dan akhirnya Autonomous, dalam sesuatu cube dikawal oleh satu ambang yang sama sepanjang accord ini — satu peningkatan terukur sebanyak 11.1 peratus, satu bahagian daripada sembilan, dibuktikan dan boleh diulang sebelum darjah autonomi yang seterusnya diberikan. Autonomi diperoleh cube demi cube, tidak sekali-kali dituntut secara borong atau diperluaskan ke atas domain yang mesti kekal sebagai urusan insani biar sehebat mana pun sistem itu kelak: makna, wang, dan undang-undang kekal tertutup kepada mesin, tidak kira berapa banyak ambang yang telah dipenuhi di tempat lain. Sesebuah rangkaian yang memperluaskan automasinya lebih pantas daripada memperluaskan buktinya bukanlah sedang memodenkan diri. Ia sedang berjudi dengan kepercayaan yang belum lagi diperolehinya.

Pampasan berkembang mengikut rangkaian ini dengan cara yang sama seperti autoriti — secara sengaja, dan dengan satu siling yang melindungi keseluruhan sistem daripada kejayaannya sendiri. 웃, token bagi Human Intelligence, bersamaan satu jam kerja yang disaksikan didarab dengan gaji minimum tempatan; apa yang diperoleh oleh mana-mana peserta ialah Multiple itu didarab dengan jam yang dikerjakan, dan ia hanya dikeluarkan untuk usaha yang dilaksanakan di bawah tugasan yang berskop dan diluluskan bajetnya. Sebelum kelulusan, rancangan yang paling hebat sekalipun hanyalah perancangan, dan perancangan semata-mata tidak mencipta apa-apa. Penyelesaian setiap peserta dihadkan pada 9,999 웃 setahun, dengan sebarang lebihan dibawa ke hadapan, bukan lenyap atau mengganggu kumpulan wang itu. Apabila rantau baharu menyertai dan aktiviti rangkaian ini berganda, siling inilah yang menghalang pertumbuhan daripada bertukar menjadi inflasi — nilai kekal terikat kepada jam tempatan yang benar, disaksikan, tidak kira sebesar mana accord ini kelak.

Di sebalik setiap 웃 terletak satu sebab yang tidak dapat dikira oleh mana-mana lejar dengan sendirinya. ♡, Shared Intention, membawa sebab itu ke hadapan melalui setiap keputusan perluasan yang dibuat oleh accord ini, manakala ◬, sumbangan Artificial Intelligence, dikira sebagai pecutan yang disaksikan, diukur berbanding garis dasar yang dibekukan — satu delta, dan tidak sekali-kali, dalam apa jua keadaan, satu ukuran keuntungan yang dioptimumkan demi dirinya sendiri. Kemasukan ke dalam rangkaian ini bermula dengan cara yang sama bagi setiap peserta, tidak kira rantau atau dekad mana mereka menyertainya: dengan satu Seed, keahlian sekali sahaja berharga satu pertujuh daripada sejam gaji minimum tempatan, tidak boleh dipindah milik dan tidak membawa sebarang tuntutan ekonomi. Seed hanya menyatakan bahawa seseorang telah tiba. Segala-galanya yang mereka bina selepas itu, mereka bina di hadapan mata tiga matawang lain accord ini, tidak sekali-kali melalui Seed itu sendiri.

Pertumbuhan yang benar mestilah juga pertumbuhan yang sampai kepada seseorang yang sebenar, bukan satu dana yang dipegang oleh rangka kerja ini bagi pihak seseorang. 🏠 Livelihood Direct menuntut supaya nilai bergerak kepada seseorang peserta hanya melalui laluan tempatan yang berlesen dan layak yang telah disemak oleh accord ini rantau demi rantau, dan tidak sekali-kali melalui simpanan yang dipegang oleh rangka kerja ini sendiri. Pengelasan sentiasa mendahului penyelesaian, supaya tiada nilai yang bergerak sebelum tujuan dan penerimanya sama-sama dipastikan tanpa sebarang keraguan. Dan kerana pengiktirafan bukanlah sama dengan akses, tempat tidur, tempat dalam rotasi, tempat duduk di meja perbincangan dikawal oleh peranan dan kesediaan, tidak sekali-kali oleh skor atau kedudukan seseorang peserta. Apabila rangkaian ini berkembang ke rantau keempat dan seterusnya, setiap wilayah baharu mesti melayakkan laluan berlesennya sendiri sebelum Livelihood Direct dapat sampai kepada penduduknya — perluasan kepercayaan, bukan sekadar perluasan wilayah.

Tiada satu pun daripada semua ini akan bertahan tanpa sebuah rangkaian yang dibina untuk bertahan daripada kejayaannya sendiri, dan itulah sebabnya Continuity Without Evasion mengawal setiap rantau yang pernah ditambah oleh accord ini. Kebolehalihan yang sah adalah mandatori; tiada satu kerajaan, bank, pengasas, atau model tunggal yang boleh menjadi sesuatu yang tidak boleh diganti kepada keseluruhan sistem. Setiap bidang kuasa menjalankan penyesuainya sendiri, gagal-tertutup dan menolak secara lalai, supaya sebarang keputusan yang memudaratkan di mana-mana sahaja hanya menutup satu laluan, tidak sekali-kali keseluruhan accord. Human Authority memegang makna, wang, dan undang-undang pada setiap skala yang dicapai oleh rangkaian ini, dimeteraikan terhadap pencerobohan mesin melalui reka bentuk, bukan sekadar melalui janji. Measurement of Time merekod setiap minit sebenar secara berasingan daripada setiap dakwaan tentangnya, dan Replay memastikan bahawa setiap keluaran, di mana-mana rantau, pada bila-bila masa sepanjang lima abad, dapat dibina semula dan diteliti semula oleh sesiapa sahaja yang bertanya. Sesebuah rangkaian yang tidak boleh di-Replay tidak boleh dipercayai, biar berapa banyak pun rantau yang telah menyertainya atau biar sehebat mana pun pertumbuhannya kelihatan dari luar. Beginilah cara Vision 2525 berkembang tanpa sesekali melangkaui kepercayaan yang dibina untuk dijaganya — satu rantau yang disahkan, satu QIS yang jujur, satu jam yang disaksikan pada satu-satu masa.`,
    },
  },
];
