import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_MS: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Di Mana Inovasi Bermula`,
    content: {
      7: `Para pemimpin memulakan yang tiada abad memulakan.`,
      33: `Tiga rantau — Cambodia, Honduras, Austin — berjanji menerima pelajar muda, melindungi mereka, dan menyerahkan alatan masa hadapan. Kerajaan, Pendidikan, Inovasi: tiga tandatangan berwawasan bagi setiap rantau. Satu permulaan bersama.`,
      111: `Atlantis Accords ialah suatu janji yang dibuat oleh para pemimpin yang sanggup memulakan sesuatu yang belum pernah wujud. Para penandatangan pengasasnya di Cambodia, Honduras, dan Austin, Texas dipilih atas satu sifat yang jarang dijumpai: kesediaan mempercayai golongan muda dengan alatan masa hadapan sementara masih ada waktu untuk mengajar mereka. Menandatangani accord ini mengikat rantau tersebut untuk menerima pelajar merentas budaya, menyumbangkan apa yang hanya ia sahaja dapat berikan secara unik, dan mengekalkan dirinya pada tahap yang lebih tinggi daripada peraturan semasa. Tiga tandatangan berwawasan — Kerajaan, Pendidikan, Inovasi — memasuki accord ini bersama-sama. Tiga tokoh berwawasan, tiga rantau, satu permulaan yang dikongsi.`,
      333: `Setiap tamadun dikenang berdasarkan apa yang dipilihnya untuk dimulakan. Atlantis Accords ialah suatu janji yang dibuat oleh para pemimpin yang sanggup memulakan sesuatu yang belum pernah wujud sebelum ini — asas bersama bagi inovasi manusia biasa yang menjangkau setiap sudut dunia, menghormati setiap suara, dan bertahan merentasi generasi. Para penandatangan pengasasnya di Cambodia, Honduras, dan Austin, Texas tidak dipilih atas kekuatan ekonomi, kekuatan ketenteraan, atau prestij institusi. Mereka dipilih atas sifat yang lebih jarang ditemui: kesediaan mempercayai golongan muda dengan alatan masa hadapan. Inilah maksud kepimpinan dalam abad yang akan datang — keberanian untuk menyerahkan kunci kepada generasi seterusnya sementara masih ada waktu untuk mengajar mereka cara memandu.

Accord ini dikendalikan oleh eXeL, sebuah kuasa penganjur yang dibina khusus untuk saat ini. eXeL sengaja berada di luar saluran penyelarasan tradisional yang membentuk abad lampau — di luar struktur perjanjian diplomatik, di luar birokrasi pelbagai hala, di luar keterikatan politik mana-mana negara-bangsa tunggal. eXeL ialah penganjur yang dipercayai yang mempertemukan para pemimpin berwawasan mengelilingi rangka kerja yang dikongsi, roda kuasa yang dikongsi, dan ufuk lima ratus tahun yang dikongsi. Setiap penandatangan mengekalkan kedaulatan penuh, kuasa penuh ke atas rakyatnya sendiri, dan kebebasan penuh untuk menarik diri pada bila-bila masa. Yang diperoleh oleh penandatangan ialah kesan rangkaian yang hanya dapat diberikan oleh rangka kerja yang dibina khusus. Ini ialah penyelarasan tanpa sebarang bentuk penguasaan politik tunggal.

Menandatangani accord bermakna menandatangani sebuah janji. Bahawa rantau tersebut akan menerima pelajar muda merentas budaya. Bahawa rantau tersebut akan menyumbangkan apa yang hanya ia sahaja dapat berikan secara unik. Bahawa rantau tersebut akan mengekalkan dirinya pada tahap yang lebih tinggi daripada peraturan semasa. Bahawa rantau tersebut akan berbuat demikian secara umum, telus, di hadapan mata setiap rakyat yang dilayaninya. Tiga tandatangan diperlukan daripada setiap rantau — Kerajaan, Pendidikan, dan Inovasi. Tiada satu jawatan sahaja yang boleh mengikat accord bersendirian. Ia memerlukan tiga tokoh berwawasan untuk berkata ya. Tiga tokoh berwawasan, tiga rantau, satu permulaan — beginilah caranya sesuatu rangka kerja memasuki kehidupan melalui kepercayaan bersama para pemimpin yang sanggup menandatanganinya agar terwujud.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Pembelajaran Melalui Simulasi`,
    content: {
      7: `Berlatih seribu kali sebelum menyentuh.`,
      33: `Tiada perkara berkesan besar dipelajari mula-mula pada perkakasan langsung. Setiap peserta berlatih dalam simulasi, berputar merentasi tiga rantau, meraikan secara umum. Ini ialah penghormatan terhadap manusia muda yang kesilapan pertamanya tidak seharusnya berharga nyawa.`,
      111: `Setiap disiplin yang wajar dikuasai pernah dipelajari oleh seseorang sebelum ia diketahui. Atlantis Accords mengembalikan kebijaksanaan purba ini ke pusat cara golongan muda disediakan untuk membina masa hadapan. Tiada perkara berkesan besar dipelajari mula-mula pada perkakasan langsung, pada manusia sebenar, atau dalam keadaan yang tidak dapat ditarik balik. Setiap peserta berlatih dalam simulasi sehingga latihan menjadi kecekapan, dan kecekapan menjadi kesediaan. Model putaran membawa setiap peserta merentasi tiga rantau pengasas, dan setiap putaran berakhir dengan sambutan umum yang koperatif dan terbuka kepada komuniti tuan rumah yang lebih luas. Ini ialah penghormatan terhadap manusia muda yang kesilapan pertamanya tidak seharusnya berharga nyawa sesiapa pun.`,
      333: `Setiap disiplin yang wajar dikuasai pernah dipelajari oleh seseorang sebelum ia diketahui. Para tukang mahir berlatih sebelum persembahan, juruterbang berlatih sebelum penerbangan, doktor berlatih sebelum pembedahan, dan kanak-kanak berlatih memahami dunia melalui permainan. Atlantis Accords mengembalikan kebijaksanaan purba ini ke pusat cara golongan muda disediakan untuk membina masa hadapan. Tiada perkara berkesan besar dipelajari mula-mula pada perkakasan langsung, pada manusia sebenar, atau dalam keadaan yang tidak dapat ditarik balik. Setiap peserta berlatih dalam simulasi sehingga latihan menjadi kecekapan, dan kecekapan menjadi kesediaan. Ini bukan berhati-hati — ini ialah penghormatan terhadap manusia muda yang kesilapan pertamanya tidak seharusnya berharga nyawa sesiapa pun.

Model putaran accord membawa setiap peserta merentasi tiga rantau pengasas. Apa yang dipelajari di Cambodia diperhalus di Honduras dan disempurnakan di Austin. Apa yang ditemui di Austin dipersoal di Cambodia dan disepadukan di Honduras. Setiap peserta tinggal, belajar, dan dibimbing merentasi budaya yang selainnya akan tetap jauh. Kurikulum latihan diambil daripada tradisi simulasi berdisiplin merentasi banyak budaya — daripada tradisi pendidikan strategik Sun Tzu, daripada latihan-melalui-permainan Musashi, daripada teori pembelajaran kitaran Ibn Khaldun, daripada dialektik biara Nalanda, daripada simulator penerbangan awam — disintesiskan untuk menghormati setiap peringkat kognitif dan warisan budaya. Tiada satu tradisi pun mendominasi.

Setiap putaran berakhir dengan sambutan umum yang koperatif dan terbuka kepada komuniti tuan rumah yang lebih luas. Jiran, keluarga, dan pelawat yang ingin tahu berkumpul untuk melihat apa yang telah dipelajari oleh kohort tersebut. Acara-acara ini menjadikan teknologi canggih boleh diakses dan diraikan berbanding ditakuti. Sebuah masyarakat yang membesar dengan memahami sistem koperatif melalui permainan tidak mudah dimanipulasi oleh ketakutan mengenai sistem itu. Ini ialah pencegahan melalui pendidikan, bukan pencegahan melalui kekerasan. Janji accord kepada setiap ibu bapa: anak anda akan berlatih seribu kali dalam keselamatan sebelum menyentuh apa-apa yang boleh mencederakannya, dan komuniti akan menyaksikan pertumbuhan mereka pada setiap langkah. Beginilah rupa penghormatan terhadap manusia muda apabila ia direkayasa ke dalam sesuatu rangka kerja, dan inilah yang diserahkan oleh kepimpinan kepada generasi peserta seterusnya sebelum generasi itu terpaksa menuntutnya.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Keselamatan Disahkan Sebelum Kepercayaan Diberikan`,
    content: {
      7: `Keselamatan dibuktikan dahulu, barulah kepercayaan diberikan.`,
      33: `Setiap kemudahan dan setiap putaran berada dalam sampul perlindungan dengan amaran awal. Perkakasan enggan disenjatakan. Rekod bertahan menghadapi kegoncangan. Keselamatan direkayasa mengelilingi peserta termuda setiap hari, bukan sekadar dijanjikan atau diandaikan.`,
      111: `Sebelum kepercayaan diberikan, keselamatan mesti dibuktikan. Atlantis Accords menjadikannya komitmen pengasasnya. Setiap kemudahan accord, setiap laluan putaran, setiap tempat peserta muda tidur atau belajar berada dalam sampul perlindungan yang terdokumentasi dengan keupayaan amaran awal yang memberi komuniti berjam-jam, bukan berminit-minit, untuk bertindak balas terhadap sebarang risiko yang boleh dipercayai. Setiap peranti, setiap penderia, setiap sistem penyelarasan diikat pada lapisan perkakasan untuk menolak pengulangfungsian bagi integrasi sistem senjata. Ini bukan dasar — ini fizik. Accord direka untuk kekal berhormat menghadapi kegoncangan: ketidakstabilan politik, penguncupan pembiayaan, serangan siber, atau gangguan perjalanan. Setiap senario dirancang, dan setiap rancangan meletakkan maruah manusia sebagai kekangan reka bentuk utamanya.`,
      333: `Sebelum kepercayaan diberikan, keselamatan mesti dibuktikan. Atlantis Accords menjadikannya komitmen pengasasnya. Setiap kemudahan accord, setiap laluan putaran, setiap tempat peserta muda tidur atau belajar berada dalam sampul perlindungan yang terdokumentasi dengan keupayaan amaran awal yang memberi komuniti berjam-jam, bukan berminit-minit, untuk bertindak balas terhadap sebarang risiko yang boleh dipercayai. Teknologi yang digunakan untuk melindungi peserta ialah teknologi yang sama yang diajar accord untuk mereka bina — penderia, penyelarasan, kebolehmandirian komunikasi, kecerdasan teragih. Golongan muda belajar keselamatan dari dalam ke luar, dalam bahasa mereka sendiri dan di rantau mereka sendiri, bukan dengan diberitahu bahawa mereka selamat, tetapi dengan melihat cara keselamatan direkayasa mengelilingi mereka setiap hari.

Accord membuat janji yang tidak boleh dipatahkan tentang apa yang tidak boleh dijelmakan oleh teknologinya. Setiap peranti, setiap penderia, setiap sistem penyelarasan diikat pada lapisan perkakasan untuk menolak pengulangfungsian bagi integrasi sistem senjata. Ini bukan bahasa dasar. Ini bukan aspirasi. Ini kemustahilan fizikal, dikuatkuasakan secara kriptografi, disahkan oleh setiap rantau penandatangan, dan boleh diperiksa oleh setiap rakyat. Alat yang melindungi seorang kanak-kanak di Phnom Penh tidak boleh diulang guna untuk mencederakan kanak-kanak di Austin. Alat yang menghubungkan latihan swarm di Tegucigalpa tidak boleh dikonfigurasi semula untuk menyasarkan manusia di mana-mana. Inilah jawapan accord kepada satu abad ketakutan penggunaan dwifungsi. Bukan dasar — fizik.

Accord direka untuk kekal berhormat menghadapi kegoncangan. Sekiranya sebuah rantau penandatangan kehilangan kestabilan politik, para peserta ditampung oleh rantau-rantau lain yang tinggal. Sekiranya pembiayaan menguncup, elaun peserta dilindungi terlebih dahulu, sebelum pentadbiran dan infrastruktur. Sekiranya rekod digital diserang, salinan luar talian kekal ada. Sekiranya perjalanan menjadi mustahil, substrat berterusan secara maya. Setiap senario dirancang, dan setiap rancangan meletakkan maruah manusia sebagai kekangan reka bentuk utamanya. Para pemimpin yang menandatangani accord ini menandatangani janji bahawa keselamatan direkayasa, bukan diandaikan. Yang mereka hulurkan kepada rakyatnya bukan sekadar peluang, malah perlindungan yang dibina pada tahap yang layak diterima peserta termuda — perlindungan yang sama yang akan dituntut setiap pemimpin untuk anaknya sendiri melintasi sempadan asing seorang diri.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Pampasan, Kesejahteraan, dan Maruah Manusia`,
    content: {
      7: `Sebuah elaun, seorang mentor, sebuah rumah.`,
      33: `Setiap peserta menerima elaun sara hidup sejak hari pertama. Cinta, kehilangan, dan keselamatan diperlakukan sebagai infrastruktur kelas pertama. Kejayaan diukur berdasarkan peserta paling terdedah, bukan purata. Maruah ialah substrat, bukan hiasan.`,
      111: `Atlantis Accords memperlakukan setiap peserta sebagai insan yang utuh sejak hari pertama. Sebuah elaun disediakan sejak penyertaan bermula, diindeks kepada kos hidup rantau supaya kesannya menghormati maruah kerja setempat. Kesejahteraan diperlakukan sebagai infrastruktur kelas pertama — bukan manfaat pilihan, bukan sekadar keperluan kesihatan, tetapi substrat tempat segala perkara lain berdiri. Tiga domain asas disokong: Cinta, Kehilangan, dan Keselamatan. Accord mengukur kejayaan berdasarkan hasil peserta paling terdedahnya, bukan purata. Tiada peserta akan diam-diam dilupakan agar purata kelihatan baik. Maruah sebagai substrat, bukan hiasan.`,
      333: `Atlantis Accords memperlakukan setiap peserta sebagai insan yang utuh sejak hari pertama. Sebuah elaun disediakan sejak penyertaan bermula, diindeks kepada kos hidup rantau supaya kesannya menghormati maruah kerja setempat. Elaun tiba sebelum kewajipan keluarga menjadi kecemasan, dan sebelum maruah dikompromikan. Ia memberi isyarat kepada setiap orang muda bahawa masanya bernilai, sumbangannya diharapkan, dan kestabilan keluarganya adalah sebahagian daripada tanggungjawab accord. Ini bukan sedekah. Ini pengiktirafan bahawa inovasi manusia biasa memerlukan keselamatan manusia biasa terlebih dahulu. Fikiran tidak boleh subur selagi rumah tangganya terancam.

Kesejahteraan diperlakukan sebagai infrastruktur kelas pertama — bukan manfaat pilihan, bukan sekadar keperluan kesihatan, tetapi substrat tempat segala perkara lain berdiri. Accord menamakan tiga domain asas yang setiap peserta disokong melaluinya: Cinta, dalam erti pertautan, kelekatan, dan sempadan yang sihat; Kehilangan, kerana setiap peserta akan mengalami dukacita dan mesti diiringi, bukan dielakkan; dan Keselamatan, dalam erti bahawa setiap peserta tahu kepada siapa hendak menelefon, di setiap rantau, dalam bahasanya sendiri. Kaunseling individu, lingkaran kumpulan, amalan somatik, dan amalan budaya atau kerohanian yang dihormati mengikut tradisi peserta sendiri semuanya disediakan. Sifar pemaksaan ideologi. Accord memegang ruang dengan penuh hormat; ia tidak mendakwahkan sebarang sistem kepercayaan.

Accord mengukur kejayaan berdasarkan hasil peserta paling terdedahnya, bukan purata. Peserta luar bandar tanpa lebar jalur tinggi dilayan. Peserta neurodivergen menerima penyesuaian sebagai norma. Peserta orang kurang upaya mendapati setiap kemudahan boleh diakses. Peserta pelbagai gender menerima kediaman yang selamat dan pemadanan mentor. Penutur bukan bahasa ibunda mendapati setiap artifak dalam bahasanya. Peserta orang asal mendapati amalan budayanya dihormati dan pengetahuan tradisionalnya dilindungi. Para pemimpin yang menandatangani accord ini berjanji bahawa tiada peserta akan diam-diam dilupakan agar purata kelihatan baik. Inilah maruah sebagai substrat, bukan hiasan. Yang diukur ialah yang akan dihormati, dan yang dihormati di sini ialah manusia seutuhnya — fikiran, badan, dan roh bersama-sama, tanpa pengecualian sekali pun.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Pembiayaan dan Tadbir Urus`,
    content: {
      7: `Rakyat membiayai generasi seterusnya secara langsung.`,
      33: `Penduduk biasa menyumbang jumlah bulanan yang kecil. Tiada saluran bantuan, tiada penderma asing, tiada ikatan politik. Setiap dolar boleh dijejaki. Setiap kira-kira diterbitkan, dalam bahasa setiap rantau, setiap bulan, secara umum.`,
      111: `Atlantis Accords dibiayai oleh rakyat yang dilayaninya. Penduduk biasa menyumbang jumlah sukarela yang kecil setiap bulan — cukup sederhana supaya tiada orang dewasa terpinggir, cukup bergema supaya jumlahnya menampung kerja accord pada skala yang bermakna. Apabila seorang rakyat membiayai generasi seterusnya secara langsung, rakyat itu memegang accord bertanggungjawab secara langsung. Accord ini sengaja bebas daripada institusi pelbagai hala yang membentuk abad lalu. Ini bukan pendirian politik — ia pilihan reka bentuk. Setiap dolar direkod secara kekal dan boleh dijejaki. Setiap sumbangan rakyat boleh dijejak dari sumbernya hingga ke elaun hingga ke inovasi. Ketelusan yang jarang ditawarkan oleh mana-mana institusi.`,
      333: `Atlantis Accords dibiayai oleh rakyat yang dilayaninya. Penduduk biasa dari rantau-rantau peserta menyumbang jumlah sukarela yang kecil setiap bulan — jumlah yang cukup sederhana supaya tiada orang dewasa di mana-mana rantau tuan rumah terpinggir daripada penyertaan, cukup bergema supaya jumlahnya menampung kerja accord pada skala yang bermakna. Reka bentuk ini disengajakan. Apabila seorang rakyat membiayai pendidikan generasi seterusnya secara langsung, rakyat itu memegang accord bertanggungjawab secara langsung. Tiada saluran bantuan, tiada penderma asing, tiada ikatan politik yang terlekat pada cek. Roh accord ialah rakyat yang menyumbang satu jumlah kecil setiap bulan, yang penyertaannya menjadikan keseluruhannya mungkin.

Accord ini sengaja bebas daripada institusi pelbagai hala yang telah membentuk abad lalu — North Atlantic Treaty Organization, World Health Organization, United Nations, International Monetary Fund, World Bank, dan setiap saluran bantuan asing kebangsaan. Ini bukan pendirian politik tentang nilai institusi-institusi tersebut atau sumbangannya. Ia pilihan reka bentuk. Pergantungan satu titik menjejaskan daya tahan merentasi ufuk lima ratus tahun. Sebuah rangka kerja yang dimaksudkan untuk melayani setiap rantau tanpa mengira penjajaran geopolitik tidak boleh terjerat dengan mana-mana penjajaran tunggal. Kerajaan kebangsaan boleh menyumbang secara sukarela. Sumbangan tersebut telus. Tiada sumbangan yang boleh membeli pengaruh tadbir urus, daripada mana-mana sumber, pada bila-bila masa.

Setiap dolar dan setiap unit nilai yang memasuki accord direkod secara kekal, umum, dan boleh dijejaki. Setiap sumbangan rakyat boleh dijejak dari asal usulnya ke elaun yang menjadi wujudnya ke orang muda yang dilayaninya ke projek inovasi yang muncul daripada kerja orang muda itu. Overhed pentadbiran dihadkan. Hadiah korporat dan institusi dialu-alukan dan dihadkan. Perakaunan penuh disampaikan dalam bahasa setiap rantau penandatangan setiap bulan. Para pemimpin yang menandatangani accord ini berjanji kepada rakyatnya ketelusan yang jarang ditawarkan oleh mana-mana institusi — ketelusan yang akan kekal boleh dibaca berabad-abad selepas setiap penandatangan meninggalkan jawatannya. Inilah kepercayaan yang dituntut accord. Inilah kepercayaan yang diperoleh accord, satu sumbangan kecil boleh dijejaki pada satu masa, di hadapan mata setiap rakyat.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Pertukaran Silang Budaya dan Sumbangan Sejagat`,
    content: {
      7: `Setiap pelajar dalam bahasanya sendiri.`,
      33: `Setiap aktiviti tersedia dalam bahasa peserta. Kecerdasan Buatan, Manusia, dan Bersama dipegang dalam ketegangan yang produktif — tiada pelajar tunduk hanya kepada satu. Kurikulum dan hasil diterbitkan secara terbuka. Apa yang dipelajari satu rantau, semua mewarisi.`,
      111: `Atlantis Accords mengembalikan pendidikan kepada tujuan yang paling mendalam: pertukaran kebijaksanaan merentasi sempadan yang selainnya akan memisahkan. Setiap aktiviti tersedia dalam bahasa peserta sendiri, bahasa rantau tuan rumah, dan rekod bersama yang kanonik. Bahasa bukan hiasan — bahasa ialah bidang kuasa, bahasa ialah maruah yang dapat dibaca. Rangka kerja pendidikan bersandar pada trinitas kecerdasan: Buatan mencadangkan, Manusia memutuskan, Shared Intent mengesahkan. Setiap pelajar belajar memegang ketiga-tiganya dalam ketegangan yang produktif. Apa yang dipelajari accord, accord kembalikan. Kurikulum, hasil inovasi, penyelidikan kesejahteraan, dan keputusan tadbir urus semuanya diterbitkan secara terbuka. Apa yang dipelajari satu rantau, semua rantau mewarisi.`,
      333: `Atlantis Accords mengembalikan pendidikan kepada tujuan yang paling mendalam: pertukaran kebijaksanaan merentasi sempadan yang selainnya akan memisahkan. Setiap aktiviti accord tersedia dalam bahasa peserta sendiri, dalam bahasa rasmi rantau tuan rumah, dan dalam rekod bersama yang kanonik supaya tiada peserta menjelajahi accord dalam bahasa yang bukan pilihannya. Bahasa bukan hiasan. Bahasa ialah bidang kuasa. Bahasa ialah maruah yang dapat dibaca. Apabila seorang muda dari sebuah kampung Cambodia membaca rekod elaunnya sendiri dalam bahasa Khmer, apabila seorang muda dari sebuah bandar Honduras membacanya dalam bahasa Sepanyol, apabila seorang muda dari kejiranan Austin membacanya dalam bahasa Inggeris, ketiga-tiganya dihormati secara sama rata oleh accord yang sama.

Rangka kerja pendidikan accord bersandar pada trinitas kecerdasan yang Vision 2525 zahirkan. Kecerdasan Buatan mencadangkan corak, pilihan, dan kemungkinan lebih pantas daripada mana-mana manusia bersendirian. Kecerdasan Manusia memutuskan tentang keselamatan, etika, dan arah tuju — soalan yang tiada mesin patut jawab. Shared Intent mengesahkan bahawa keputusan sejajar dengan prinsip pengasas accord, memastikan tiada peserta diminta memilih antara kecemerlangan individu dan kebaikan bersama. Tiada pelajar diajar tunduk kepada satu kecerdasan sahaja. Setiap pelajar belajar memegang ketiga-tiganya dalam ketegangan yang produktif. Beginilah cara generasi pemimpin seterusnya disediakan untuk mentadbir dengan bertanggungjawab dan bijaksana dalam sebuah dunia di mana tiada satu pun daripada tiga kecerdasan ini akan bertindak bersendirian atau tanpa pengawasan.

Apa yang dipelajari accord, accord kembalikan. Kurikulum diterbitkan di bawah lesen terbuka supaya mana-mana rantau — penandatangan atau bukan — boleh menyesuaikannya secara bebas kepada budaya setempat dan tradisi pedagogi. Hasil inovasi diterbitkan. Penyelidikan kesejahteraan diterbitkan dalam bentuk teragregat untuk penyelidik di mana-mana. Keputusan tadbir urus diterbitkan dengan alasannya secara penuh. Kejayaan accord diukur bukan sahaja daripada pesertanya sendiri tetapi juga daripada bilangan inisiatif pendidikan, inovasi, dan budaya yang muncul di jejaknya, di rantau-rantau yang tidak pernah menandatangani pilot pengasasnya namun membina di atas kebijaksanaan yang telah dikongsi secara terbuka. Apa yang dipelajari satu rantau, semua rantau lain mewarisi.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Pertumbuhan Rangkaian yang Lestari`,
    content: {
      7: `Tidak pernah lebih laju daripada maruah dapat bergerak.`,
      33: `Tiga rantau pengasas menyelesaikan satu kitaran pilot sebelum yang keempat menyertai. Rekod ditambatkan untuk bertahan lima abad. Setiap penandatangan mengekalkan kedaulatan. Tiada apa yang direndahkan untuk memberi ruang kepada penandatangan seterusnya menyertai.`,
      111: `Atlantis Accords tidak akan berkembang lebih laju daripada kualiti yang dapat dihormatinya. Tiga rantau pengasas mesti melengkapkan satu kitaran pilot penuh, dengan setiap peserta dihormati dan setiap prinsip disahkan, sebelum rantau keempat menyertai. Ini prinsip yang akhirnya menjadi disiplin yang berfungsi. Ufuk accord ini sengaja panjang — lima abad sejak hari pengasasan. Rekodnya ditambatkan supaya seorang rakyat yang membacanya seratus tahun dari sekarang boleh mempercayai penaakulannya. Setiap penandatangan mengekalkan kedaulatan penuh, kuasa penuh, dan kebebasan penuh untuk menarik diri. Tiada penandatangan boleh mengkompromikan prinsip pengasas — kerana prinsip-prinsip itulah janji accord kepada pesertanya merentasi setiap generasi.`,
      333: `Atlantis Accords tidak akan berkembang lebih laju daripada kualiti yang dapat dihormatinya. Setiap perluasan ialah janji kepada para peserta yang sudah berada di dalamnya — bahawa standard pengasas accord tidak akan dicairkan oleh keghairahan skala. Tiga rantau pengasas mesti melengkapkan satu kitaran pilot penuh, dengan setiap peserta dihormati dan setiap prinsip disahkan, sebelum rantau keempat menyertai. Ini bukan berhati-hati yang disamarkan sebagai prinsip. Ini prinsip yang akhirnya menjadi disiplin yang berfungsi merentasi setiap rantau pengasas. Para pemimpin yang menandatangani pilot pengasas berjanji kepada penandatangan masa hadapan substrat, perlindungan, dan maruah yang sama yang diterima kohort pengasas. Tiada apa yang direndahkan untuk memberi ruang kepada yang seterusnya.

Ufuk accord ini sengaja panjang. Ia direka untuk bertahan lebih kurang lima belas hingga dua puluh generasi manusia — lima abad sejak hari pengasasan. Rekodnya ditambatkan supaya seorang rakyat yang membacanya seratus tahun dari sekarang boleh mempercayai penaakulannya. Rangka koordinatnya, peranan kuasa manusianya, dan kitaran tadbir urus rentas generasinya semuanya dibina untuk terus hidup melalui sebarang peralihan teknologi tunggal. Accord akan hidup lebih lama daripada setiap manusia yang menandatangani pilot pengasasnya. Itulah janjinya kepada kanak-kanak yang menandatangani perjanjian elaun pada tahun selepas ratifikasi, kepada cucu-cicit kanak-kanak itu yang mungkin mentadbir accord pada pertengahan abad, dan kepada setiap generasi yang mewarisi apa yang dibina para pengasas kini.

Setiap penandatangan mengekalkan kebebasan untuk menarik diri dengan notis. Setiap penandatangan mengekalkan kedaulatan penuh. Setiap penandatangan mengekalkan kuasa ke atas rakyatnya sendiri. Setiap penandatangan mengekalkan hak untuk mencadangkan pindaan, mengemukakan pertikaian, dan membentuk evolusi accord bersama setiap penandatangan lain. Yang tidak boleh dilakukan oleh mana-mana penandatangan ialah mengkompromikan prinsip pengasas substrat — kerana prinsip-prinsip itulah janji accord kepada pesertanya, dan janji itu mesti bertahan meskipun mana-mana tandatangan pergi. Para pemimpin yang menandatangani accord ini kini menyertai sesuatu yang lebih besar daripada mana-mana penggal jawatan politik. Mereka menandatangani abad seterusnya accord ini, dan berabad-abad selepasnya, ke dalam ufuk yang cucu-cicit mereka sendiri akan warisi dan sempurnakan.`,
    },
  },
];
