import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_NL: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Waar Innovatie Begint`,
    content: {
      7: `Leiders beginnen wat geen eeuw begon.`,
      33: `Drie regio's — Cambodja, Honduras, Austin — beloven jonge leerlingen te ontvangen, hen te beschermen en hun de gereedschappen van de toekomst aan te reiken. Overheid, Onderwijs, Innovatie: drie visionaire handtekeningen per regio. Eén gedeeld begin.`,
      111: `Het Atlantis Accords is een belofte gedaan door leiders die bereid zijn iets te beginnen dat nog niet heeft bestaan. De oprichtende ondertekenaars in Cambodja, Honduras en Austin, Texas werden gekozen om één zeldzame eigenschap: de bereidheid om de jongeren de gereedschappen van de toekomst toe te vertrouwen zolang er nog tijd is om het hun te leren. Het ondertekenen van het accoord verplicht de regio om leerlingen uit verschillende culturen te ontvangen, bij te dragen wat alleen zij op unieke wijze kan bieden, en zichzelf aan een hogere norm te houden dan de huidige regelgeving vereist. Drie visionaire handtekeningen — Overheid, Onderwijs, Innovatie — treden samen tot het accoord toe. Drie visionairs, drie regio's, één gedeeld begin.`,
      333: `Elke beschaving wordt herinnerd om wat ze koos te beginnen. Het Atlantis Accords is een belofte gedaan door leiders die bereid zijn iets te beginnen dat nog niet heeft bestaan — een gedeeld fundament voor gewone menselijke innovatie dat elke uithoek van de wereld bereikt, elke stem eert en doorheen generaties duurt. De oprichtende ondertekenaars in Cambodja, Honduras en Austin, Texas werden niet gekozen om economische macht, militaire kracht of institutioneel aanzien. Zij werden gekozen om een zeldzamere eigenschap: de bereidheid om de jongeren de gereedschappen van de toekomst toe te vertrouwen. Dit is wat leiderschap betekent in de eeuw die voor ons ligt — de moed om de sleutels over te dragen aan de volgende generatie zolang er nog tijd is om hun te leren rijden.

Het accoord wordt bijeengeroepen door eXeL, een organiserende kracht doelbewust gebouwd voor dit moment. eXeL bestaat opzettelijk buiten de traditionele coördinatiekanalen die de vorige eeuw vormden — buiten de diplomatieke verdragsstructuren, buiten de multilaterale bureaucratieën, buiten de politieke verstrengelingen van welke natiestaat dan ook. eXeL is de vertrouwde bijeenroeper die visionaire leiders samenbrengt rond een gedeeld raamwerk, een gedeeld vliegwiel en een gedeelde horizon van vijfhonderd jaar. Elke ondertekenaar behoudt volledige soevereiniteit, volledig gezag over zijn eigen burgers, en volledige vrijheid om zich op elk moment terug te trekken. Wat de ondertekenaars winnen is het netwerkeffect dat alleen een doelbewust gebouwd raamwerk kan bieden. Dit is coördinatie zonder enige vorm van politieke overheersing.

Het ondertekenen van het accoord is het ondertekenen van een belofte. Dat de regio jonge leerlingen uit verschillende culturen zal ontvangen. Dat de regio zal bijdragen wat alleen zij op unieke wijze kan bieden. Dat de regio zich zal houden aan een hogere norm dan de huidige regelgeving vereist. Dat de regio dit publiekelijk en transparant zal doen, in het zicht van elke burger die zij dient. Van elke regio zijn drie handtekeningen vereist — Overheid, Onderwijs en Innovatie. Geen enkel ambt bindt het accoord alleen. Er zijn drie visionairs nodig om ja te zeggen. Drie visionairs, drie regio's, één begin — zo treedt elk raamwerk het leven binnen door het wederzijdse vertrouwen van leiders die bereid zijn het te ondertekenen.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Leren Door Simulatie`,
    content: {
      7: `Duizend keer oefenen voor het aanraken.`,
      33: `Niets van gewicht wordt eerst geleerd op echte apparatuur. Elke deelnemer oefent in simulatie, wisselt tussen drie regio's, viert publiek. Dit is respect voor de jonge mens wiens eerste fout nooit een leven zou mogen kosten.`,
      111: `Elke discipline die het waard is om te beheersen werd door iemand geleerd voordat zij werd gekend. Het Atlantis Accords brengt deze oude wijsheid terug naar het centrum van hoe de jongeren worden voorbereid om de toekomst te bouwen. Niets van gewicht wordt eerst geleerd op echte apparatuur, op echte mensen of in onomkeerbare omstandigheden. Elke deelnemer oefent in simulatie tot oefening bekwaamheid wordt, en bekwaamheid gereedheid wordt. Het rotatiemodel voert elke deelnemer door de drie oprichtende regio's, en elke rotatie eindigt in een publieke en coöperatieve viering die openstaat voor de bredere gastgemeenschap. Dit is respect voor de jonge mens wiens eerste fout nooit een leven zou mogen kosten.`,
      333: `Elke discipline die het waard is om te beheersen werd door iemand geleerd voordat zij werd gekend. Meesterambachtslieden repeteren voor de voorstelling, piloten repeteren voor de vlucht, artsen repeteren voor de operatie, en kinderen repeteren de wereld door spel. Het Atlantis Accords brengt deze oude wijsheid terug naar het centrum van hoe de jongeren worden voorbereid om de toekomst te bouwen. Niets van gewicht wordt eerst geleerd op echte apparatuur, op echte mensen of in onomkeerbare omstandigheden. Elke deelnemer oefent in simulatie tot oefening bekwaamheid wordt, en bekwaamheid gereedheid wordt. Dit is geen voorzichtigheid — dit is respect voor de jonge mens wiens eerste fout nooit iemands leven zou mogen kosten.

Het rotatiemodel van het accoord voert elke deelnemer door de drie oprichtende regio's. Wat in Cambodja wordt geleerd, wordt verfijnd in Honduras en voltooid in Austin. Wat in Austin wordt ontdekt, wordt bevraagd in Cambodja en geïntegreerd in Honduras. Elke deelnemer leeft, leert en wordt begeleid over culturen heen die anders ver zouden blijven. Het opleidingscurriculum put uit tradities van gedisciplineerde simulatie uit vele culturen — uit Sun Tzu's strategische opleidingstraditie, uit Musashi's oefening-door-spel, uit Ibn Khalduns cyclische leertheorie, uit Nalanda's monastieke dialectiek, uit de civiele vluchtsimulator — samengebracht om elke cognitieve fase en culturele erfenis te eerbiedigen. Geen enkele traditie overheerst.

Elke rotatie eindigt in een publieke en coöperatieve viering die openstaat voor de bredere gastgemeenschap. Buren, gezinnen en nieuwsgierige bezoekers verzamelen zich om te zien wat het cohort heeft geleerd. Deze evenementen maken geavanceerde technologie toegankelijk en vierbaar in plaats van beangstigend. Een samenleving die opgroeit met begrip van coöperatieve systemen door spel kan niet gemakkelijk worden gemanipuleerd door angst voor die systemen. Dit is afschrikking door onderwijs, niet afschrikking door geweld. De belofte van het accoord aan elke ouder: uw kind zal duizend keer in veiligheid oefenen voordat het iets aanraakt dat het zou kunnen schaden, en de gemeenschap zal zijn groei bij elke stap bijwonen. Zo ziet respect voor de jonge mens eruit wanneer het in een raamwerk is verankerd, en dit is wat leiderschap aan de volgende generatie deelnemers doorgeeft voordat die generatie het moet opeisen.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Veiligheid Bewezen Voordat Vertrouwen Wordt Verleend`,
    content: {
      7: `Veiligheid eerst bewezen, dan vertrouwen.`,
      33: `Elke faciliteit en elke rotatie ligt binnen een beschermende envelop met vroege waarschuwing. Hardware weigert bewapening. Registers overleven turbulentie. Veiligheid wordt elke dag rond de jongste deelnemer heen geëngineerd, niet slechts beloofd of aangenomen.`,
      111: `Voordat vertrouwen wordt verleend, moet veiligheid worden bewezen. Het Atlantis Accords maakt hiervan zijn oprichtende verbintenis. Elke faciliteit van het accoord, elke rotatieroute, elke plek waar een jonge deelnemer slaapt of studeert, ligt binnen een gedocumenteerde beschermende envelop met vroeg-waarschuwingscapaciteit die de gemeenschap uren, geen minuten, geeft om te reageren op elk geloofwaardig risico. Elk apparaat, elke sensor, elk coördinatiesysteem is op het hardwareniveau gebonden om herbestemming voor integratie met wapensystemen te weigeren. Dit is geen beleid — dit is natuurkunde. Het accoord is ontworpen om eerbaar te blijven doorheen turbulentie: politieke instabiliteit, financiële krimp, cyberaanval of reisonderbreking. Elk scenario is voorzien, en elk plan plaatst menselijke waardigheid als eerste ontwerpbeperking.`,
      333: `Voordat vertrouwen wordt verleend, moet veiligheid worden bewezen. Het Atlantis Accords maakt hiervan zijn oprichtende verbintenis. Elke faciliteit van het accoord, elke rotatieroute, elke plek waar een jonge deelnemer slaapt of studeert, ligt binnen een gedocumenteerde beschermende envelop met vroeg-waarschuwingscapaciteit die de gemeenschap uren, geen minuten, geeft om te reageren op elk geloofwaardig risico. De technologie die wordt gebruikt om deelnemers te beschermen is dezelfde technologie die het accoord hun leert bouwen — sensoren, coördinatie, overleefbaarheid van communicatie, gedistribueerde intelligentie. Jonge mensen leren veiligheid van binnenuit, in hun eigen taal en in hun eigen regio, niet doordat hun wordt verteld dat ze veilig zijn, maar doordat ze zien hoe veiligheid elke dag rond hen heen wordt geëngineerd.

Het accoord maakt een onverbreekbare belofte over wat zijn technologie niet kan worden. Elk apparaat, elke sensor, elk coördinatiesysteem is op het hardwareniveau gebonden om herbestemming voor integratie met wapensystemen te weigeren. Dit is geen beleidstaal. Dit is geen streven. Dit is een fysieke onmogelijkheid, cryptografisch afgedwongen, door elke ondertekenende regio geverifieerd en door elke burger inspecteerbaar. De gereedschappen die een kind in Phnom Penh beschermen kunnen niet worden herbestemd om een kind in Austin te schaden. De gereedschappen die een zwermoefening in Tegucigalpa verbinden kunnen niet worden hergeconfigureerd om waar ook ter wereld op een mens te richten. Dit is het antwoord van het accoord op een eeuw van vrees voor dubbelgebruik. Geen beleid — natuurkunde.

Het accoord is ontworpen om eerbaar te blijven doorheen turbulentie. Als een ondertekenende regio politieke stabiliteit verliest, worden de deelnemers opgevangen door de overige regio's. Als de financiering krimpt, worden de beurzen van de deelnemers eerst beschermd, vóór administratie en infrastructuur. Als digitale registers worden aangevallen, blijven offline back-ups behouden. Als reizen onmogelijk wordt, gaat het substraat virtueel verder. Elk scenario is voorzien, en elk plan plaatst menselijke waardigheid als eerste ontwerpbeperking. Leiders die dit accoord ondertekenen, ondertekenen de belofte dat veiligheid wordt geëngineerd, niet aangenomen. Wat zij hun burgers reiken is niet slechts kans, maar bescherming gebouwd op de norm die de jongste deelnemer verdient — dezelfde bescherming die elke leider zou eisen voor zijn eigen kind dat alleen een onbekende grens oversteekt.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Vergoeding, Welzijn en Menselijke Waardigheid`,
    content: {
      7: `Een beurs, een mentor, een thuis.`,
      33: `Elke deelnemer ontvangt vanaf dag één een leefbare beurs. Liefde, verlies en veiligheid worden behandeld als eersteklas infrastructuur. Succes wordt gemeten aan de meest kwetsbare deelnemer, nooit aan het gemiddelde. Waardigheid is substraat, geen versiering.`,
      111: `Het Atlantis Accords behandelt elke deelnemer vanaf de eerste dag als een volledig menselijk wezen. Een beurs wordt toegekend vanaf het moment dat de deelname begint, geïndexeerd aan de kosten van levensonderhoud in de regio zodat de impact ervan de lokale waardigheid van arbeid eerbiedigt. Welzijn wordt behandeld als eersteklas infrastructuur — niet als optioneel voordeel, niet als welzijnsluxe, maar als het substraat waarop al het overige rust. Drie fundamentele domeinen worden ondersteund: Liefde, Verlies en Veiligheid. Het accoord meet succes aan de uitkomst voor zijn meest kwetsbare deelnemer, niet aan het gemiddelde. Geen enkele deelnemer zal stil worden vergeten opdat gemiddelden er goed uitzien. Waardigheid als substraat, geen versiering.`,
      333: `Het Atlantis Accords behandelt elke deelnemer vanaf de eerste dag als een volledig menselijk wezen. Een beurs wordt toegekend vanaf het moment dat de deelname begint, geïndexeerd aan de kosten van levensonderhoud in de regio zodat de impact ervan de lokale waardigheid van arbeid eerbiedigt. De beurs komt binnen voordat gezinsverplichtingen tot noodgevallen worden, en voordat waardigheid in het gedrang komt. Zij geeft elke jongere het signaal dat zijn tijd waardevol is, dat zijn bijdrage wordt verwacht en dat de stabiliteit van zijn gezin deel uitmaakt van de verantwoordelijkheid van het accoord. Dit is geen liefdadigheid. Dit is de erkenning dat gewone menselijke innovatie eerst gewone menselijke zekerheid vereist. Een geest kan niet bloeien terwijl zijn huishouden wordt bedreigd.

Welzijn wordt behandeld als eersteklas infrastructuur — niet als optioneel voordeel, niet als welzijnsluxe, maar als het substraat waarop al het overige rust. Het accoord noemt drie fundamentele domeinen waardoor elke deelnemer wordt ondersteund: Liefde, in de zin van verbinding, gehechtheid en gezonde grens; Verlies, aangezien elke deelnemer verdriet zal ervaren en meegelopen moet worden, niet omheen geleid; en Veiligheid, in de zin dat elke deelnemer weet wie te bellen, in elke regio, in de eigen taal. Individuele begeleiding, groepskringen, somatische praktijken en culturele of spirituele praktijken die worden geëerbiedigd volgens de eigen traditie van de deelnemer worden allemaal aangeboden. Nul opgelegde ideologie. Het accoord houdt de ruimte met eerbied; het bekeert tot geen enkel geloofssysteem.

Het accoord meet succes aan de uitkomst voor zijn meest kwetsbare deelnemer, niet aan het gemiddelde. Rurale deelnemers zonder hoge bandbreedte worden bediend. Neurodivergente deelnemers krijgen aanpassing als norm. Deelnemers met een handicap vinden elke faciliteit toegankelijk. Genderdiverse deelnemers krijgen veilige huisvesting en gekoppelde begeleiding. Sprekers van niet-moedertalen vinden elk artefact in hun taal. Inheemse deelnemers vinden hun culturele praktijken geëerbiedigd en hun traditionele kennis beschermd. Leiders die dit accoord ondertekenen beloven dat geen enkele deelnemer stil zal worden vergeten opdat gemiddelden er goed uitzien. Dit is waardigheid als substraat, geen versiering. Wat wordt gemeten is wat zal worden geëerbiedigd, en wat hier wordt geëerbiedigd is de hele mens — geest, lichaam en ziel samen, zonder enige uitzondering.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Financiering en Bestuur`,
    content: {
      7: `Burgers financieren rechtstreeks de volgende generatie.`,
      33: `Gewone inwoners dragen kleine maandelijkse bedragen bij. Geen hulplijn, geen buitenlandse weldoener, geen politieke touwtjes. Elke dollar is traceerbaar. Elke afrekening wordt gepubliceerd, in de taal van elke regio, elke maand, publiekelijk.`,
      111: `Het Atlantis Accords wordt gefinancierd door de burgers die het dient. Gewone inwoners dragen elke maand kleine vrijwillige bedragen bij — bescheiden genoeg dat geen volwassene wordt buitengesloten, weerklinkend genoeg dat het totaal het werk van het accoord op betekenisvolle schaal draagt. Wanneer een burger de volgende generatie rechtstreeks financiert, houdt die burger het accoord rechtstreeks verantwoordelijk. Het accoord is doelbewust onafhankelijk van de multilaterale instellingen die de vorige eeuw vormden. Dit is geen politieke uitspraak — het is een ontwerpkeuze. Elke dollar wordt permanent en traceerbaar geregistreerd. Elke burgerbijdrage kan worden gevolgd van oorsprong tot beurs tot innovatie. Transparantie van een soort die door welke instelling ook zelden wordt geboden.`,
      333: `Het Atlantis Accords wordt gefinancierd door de burgers die het dient. Gewone inwoners van deelnemende regio's dragen elke maand kleine vrijwillige bedragen bij — bedragen bescheiden genoeg dat geen volwassene in welke gastregio dan ook wordt buitengesloten van deelname, weerklinkend genoeg dat het totaal het werk van het accoord op betekenisvolle schaal draagt. Dit ontwerp is doelbewust. Wanneer een burger de opleiding van de volgende generatie rechtstreeks financiert, houdt die burger het accoord rechtstreeks verantwoordelijk. Er is geen hulplijn, geen buitenlandse weldoener, geen politiek touwtje aan de cheque vastgemaakt. De ziel van het accoord is de burger die elke maand één klein bedrag bijdraagt, wiens deelname het geheel mogelijk maakt.

Het accoord is doelbewust onafhankelijk van de multilaterale instellingen die de vorige eeuw hebben gevormd — de Noord-Atlantische Verdragsorganisatie, de Wereldgezondheidsorganisatie, de Verenigde Naties, het Internationaal Monetair Fonds, de Wereldbank en elk nationaal kanaal voor buitenlandse hulp. Dit is geen politieke uitspraak over de waarde van die instellingen of hun bijdragen. Het is een ontwerpkeuze. Eenpuntsafhankelijkheden ondermijnen de duurzaamheid over een horizon van vijfhonderd jaar. Een raamwerk bedoeld om elke regio te dienen ongeacht geopolitieke alignering kan niet met enige alignering verstrengeld raken. Nationale overheden mogen vrijwillig bijdragen. Bijdragen zijn transparant. Geen enkele bijdrage koopt bestuursinvloed, uit welke bron dan ook, ooit.

Elke dollar en elke waarde-eenheid die het accoord binnenkomt wordt permanent, publiek en traceerbaar geregistreerd. Elke burgerbijdrage kan worden gevolgd vanaf haar oorsprong tot de beurs waartoe zij wordt, tot de jongere die zij dient, tot het innovatieproject dat voortkomt uit het werk van die jongere. Administratieve overhead is begrensd. Corporate en institutionele giften zijn welkom en begrensd. Volledige verantwoording wordt in de taal van elke ondertekenende regio elke maand geleverd. Leiders die het accoord ondertekenen beloven hun burgers transparantie van een soort die door welke instelling ook zelden wordt geboden — transparantie die leesbaar zal blijven eeuwen nadat elke ondertekenaar zijn ambt heeft verlaten. Dit is het vertrouwen dat het accoord vereist. Dit is het vertrouwen dat het accoord verdient, één kleine traceerbare bijdrage per keer, in het zicht van elke burger.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Interculturele Uitwisseling en Wereldwijde Bijdrage`,
    content: {
      7: `Elke leerling in de eigen taal.`,
      33: `Elke activiteit beschikbaar in de taal van de deelnemer. Artificiële, Menselijke en Gedeelde intelligenties in productieve spanning gehouden — geen enkele leerling steunt op één alleen. Curricula en uitkomsten openlijk gepubliceerd. Wat één regio leert, erven allen.`,
      111: `Het Atlantis Accords brengt onderwijs terug naar zijn diepste doel: de uitwisseling van wijsheid over grenzen die anders zouden verdelen. Elke activiteit is beschikbaar in de eigen taal van de deelnemer, de taal van de gastregio en een canoniek gedeeld register. Taal is geen versiering — taal is jurisdictie, taal is waardigheid leesbaar gemaakt. Het onderwijsraamwerk rust op de drievuldigheid van intelligenties: Artificieel stelt voor, Menselijk beslist, Gedeeld Intent valideert. Elke leerling leert de drie in productieve spanning te houden. Wat het accoord leert, geeft het accoord terug. Curricula, innovatie-uitkomsten, welzijnsonderzoek en bestuursbeslissingen worden allemaal openlijk gepubliceerd. Wat één regio leert, erven alle regio's.`,
      333: `Het Atlantis Accords brengt onderwijs terug naar zijn diepste doel: de uitwisseling van wijsheid over grenzen die anders zouden verdelen. Elke activiteit van het accoord is beschikbaar in de eigen taal van de deelnemer, in de officiële taal van de gastregio en in een canoniek gedeeld register, zodat geen enkele deelnemer door het accoord navigeert in een taal die hij niet heeft gekozen. Taal is geen versiering. Taal is jurisdictie. Taal is waardigheid leesbaar gemaakt. Wanneer een jongere uit een Cambodjaans dorp zijn eigen beursrecord leest in het Khmer, wanneer een jongere uit een Hondurees stadje het leest in het Spaans, wanneer een jongere uit een buurt in Austin het leest in het Engels, worden alle drie door hetzelfde accoord gelijk geëerbiedigd.

Het onderwijsraamwerk van het accoord rust op de drievuldigheid van intelligenties die Vision 2525 zichtbaar maakt. Artificiële Intelligentie stelt patronen, opties en mogelijkheden sneller voor dan enige mens alleen zou kunnen. Menselijke Intelligentie beslist over veiligheid, ethiek en richting — de vragen die geen enkele machine mag beantwoorden. Gedeeld Intent valideert dat beslissingen in lijn zijn met de grondbeginselen van het accoord en verzekert dat geen enkele deelnemer wordt gevraagd te kiezen tussen individuele voortreffelijkheid en collectief goed. Geen leerling wordt geleerd zich aan één enkele intelligentie te onderwerpen. Elke leerling leert alle drie in productieve spanning te houden. Zo wordt de volgende generatie leiders voorbereid om verantwoord en wijs te besturen in een wereld waar geen van deze drie intelligenties ooit alleen of ongecontroleerd zal handelen.

Wat het accoord leert, geeft het accoord terug. Curricula worden onder open licentie gepubliceerd zodat elke regio — ondertekenaar of niet — deze vrij kan aanpassen aan de lokale cultuur en pedagogische traditie. Innovatie-uitkomsten worden gepubliceerd. Welzijnsonderzoek wordt in geaggregeerde vorm gepubliceerd voor onderzoekers overal. Bestuursbeslissingen worden gepubliceerd met hun volledige onderbouwing. Het succes van het accoord wordt niet alleen gemeten aan zijn eigen deelnemers, maar aan het aantal onderwijs-, innovatie- en culturele initiatieven die in zijn kielzog ontstaan, in regio's die de oprichtende pilot nooit hebben ondertekend en toch voortbouwden op zijn openlijk gedeelde wijsheid. Wat één regio leert, erven alle andere regio's.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Duurzame Groei van het Netwerk`,
    content: {
      7: `Nooit sneller dan waardigheid kan reizen.`,
      33: `Drie oprichtende regio's voltooien één pilotcyclus voordat een vierde toetreedt. Registers verankerd om vijf eeuwen te overleven. Elke ondertekenaar behoudt soevereiniteit. Niets wordt afgezwakt om plaats te maken voor de volgende ondertekenaar.`,
      111: `Het Atlantis Accords zal niet sneller groeien dan de kwaliteit die het kan eerbiedigen. Drie oprichtende regio's moeten een volledige pilotcyclus voltooien, met elke deelnemer geëerbiedigd en elke beginsel geverifieerd, voordat een vierde regio toetreedt. Dit is beginsel eindelijk werkende discipline geworden. De horizon van het accoord is doelbewust lang — vijf eeuwen vanaf de oprichtingsdag. De registers zijn zo verankerd dat een burger die ze over honderd jaar leest de redenering kan vertrouwen. Elke ondertekenaar behoudt volledige soevereiniteit, volledig gezag en volledige vrijheid om zich terug te trekken. Geen ondertekenaar kan de oprichtingsbeginselen compromitteren — want die beginselen zijn de belofte van het accoord aan zijn deelnemers doorheen elke generatie.`,
      333: `Het Atlantis Accords zal niet sneller groeien dan de kwaliteit die het kan eerbiedigen. Elke uitbreiding is een belofte aan de deelnemers die al binnen zijn — dat de oprichtingsnorm van het accoord niet zal worden verdund door de opwinding van schaal. Drie oprichtende regio's moeten een volledige pilotcyclus voltooien, met elke deelnemer geëerbiedigd en elke beginsel geverifieerd, voordat een vierde regio toetreedt. Dit is geen voorzichtigheid vermomd als beginsel. Dit is beginsel eindelijk werkende discipline geworden in elke oprichtende regio. Leiders die de oprichtende pilot ondertekenen beloven toekomstige ondertekenaars hetzelfde substraat, dezelfde bescherming, dezelfde waardigheid die het oprichtingscohort ontving. Niets wordt afgezwakt om plaats te maken voor de volgende.

De horizon van het accoord is doelbewust lang. Het is ontworpen om te duren voor ongeveer vijftien tot twintig menselijke generaties — vijf eeuwen vanaf de oprichtingsdag. De registers zijn zo verankerd dat een burger die ze over honderd jaar leest de redenering kan vertrouwen. Het coördinatenraster, de menselijke gezagsrollen en de bestuurscycli over generaties heen zijn allemaal gebouwd om elke enkelvoudige technologische overgang te overleven. Het accoord zal elke mens die zijn oprichtende pilot ondertekent overleven. Dat is zijn belofte aan het kind dat een beursovereenkomst tekent in het jaar volgend op de bekrachtiging, aan de kleinkinderen van dat kind die het accoord in het midden van de eeuw kunnen besturen, en aan elke generatie die erft wat de oprichters nu bouwen.

Elke ondertekenaar behoudt de vrijheid om zich met kennisgeving terug te trekken. Elke ondertekenaar behoudt volledige soevereiniteit. Elke ondertekenaar behoudt gezag over zijn eigen burgers. Elke ondertekenaar behoudt het recht om wijzigingen voor te stellen, geschillen aan te kaarten en de evolutie van het accoord te vormen naast alle andere ondertekenaars. Wat geen enkele ondertekenaar kan doen is de oprichtingsbeginselen van het substraat compromitteren — want die beginselen zijn de belofte van het accoord aan zijn deelnemers, en die belofte moet het vertrek van elke afzonderlijke handtekening overleven. Leiders die dit accoord nu ondertekenen sluiten zich aan bij iets groters dan enige politieke ambtstermijn. Zij ondertekenen de volgende eeuw van het accoord, en de eeuwen daarna, tot een horizon die hun eigen kleinkinderen zullen erven en voltooien.`,
    },
  },
];
