import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_NO: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Der innovasjonen begynner`,
    content: {
      7: `Ledere begynner det intet århundre har begynt.`,
      33: `Tre regioner — Cambodia, Honduras, Austin — lover å ta imot unge lærende, beskytte dem og gi dem fremtidens verktøy. Myndighet, Utdanning, Innovasjon: tre visjonære signaturer per region. Én begynnelse sammen.`,
      111: `Atlantis-avtalen er et løfte gitt av ledere som er villige til å begynne noe som ikke har eksistert før. De grunnleggende signatarene i Cambodia, Honduras og Austin, Texas ble valgt for én sjelden egenskap: viljen til å betro de unge fremtidens verktøy mens det ennå er tid til å lære dem opp. Å signere avtalen forplikter regionen til å ta imot lærende på tvers av kulturer, bidra med det bare den unikt kan tilby, og holde seg til en høyere standard enn dagens regelverk krever. Tre visjonære signaturer — Myndighet, Utdanning, Innovasjon — trer inn i avtalen sammen. Tre visjonærer, tre regioner, én felles begynnelse.`,
      333: `Enhver sivilisasjon huskes for det den valgte å begynne. Atlantis-avtalen er et løfte gitt av ledere som er villige til å begynne noe som ikke har eksistert før — et felles fundament for alminnelig menneskelig innovasjon som når hver krok av verden, ærer hver stemme og består gjennom generasjoner. De grunnleggende signatarene i Cambodia, Honduras og Austin, Texas ble ikke valgt for økonomisk makt, militær styrke eller institusjonell prestisje. De ble valgt for en sjeldnere egenskap: viljen til å betro de unge fremtidens verktøy. Dette er hva lederskap betyr i århundret som kommer — motet til å overlate nøklene til den neste generasjonen mens det ennå er tid til å lære dem å kjøre.\n\nAvtalen sammenkalles av eXeL, en organiserende kraft bygget bevisst for dette øyeblikket. eXeL eksisterer med hensikt utenfor de tradisjonelle koordineringskanalene som formet det forrige århundret — utenfor diplomatiske traktatstrukturer, utenfor multilaterale byråkratier, utenfor de politiske forviklingene til enhver enkelt nasjonalstat. eXeL er den tillitsfulle sammenkalleren som samler visjonære ledere rundt et felles rammeverk, et felles svinghjul og en felles femhundreårshorisont. Hver signatar beholder full suverenitet, full myndighet over sine egne borgere og full frihet til å trekke seg når som helst. Det signatarene får, er nettverkseffekten som bare et formålsbygd rammeverk kan gi. Dette er koordinering uten noen form for politisk dominans.\n\nÅ signere avtalen er å signere et løfte. At regionen vil ta imot unge lærende på tvers av kulturer. At regionen vil bidra med det bare den unikt kan tilby. At regionen vil holde seg til en høyere standard enn dagens regelverk krever. At regionen vil gjøre det offentlig, åpent, i full åpenhet for hver borger den tjener. Det kreves tre signaturer fra hver region — Myndighet, Utdanning og Innovasjon. Intet enkelt embete binder avtalen alene. Det trengs tre visjonærer for å si ja. Tre visjonærer, tre regioner, én begynnelse — slik trer ethvert rammeverk inn i livet gjennom den gjensidige tilliten til ledere som er villige til å signere det til virkelighet.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Læring gjennom simulering`,
    content: {
      7: `Øve tusen ganger før man rører.`,
      33: `Ingenting av betydning læres først på virkelig utstyr. Hver deltaker øver i simulering, roterer mellom de tre regionene og feirer offentlig. Dette er respekt for det unge mennesket hvis første feil aldri bør koste et liv.`,
      111: `Enhver disiplin verdt å mestre ble lært av noen før den var kjent. Atlantis-avtalen fører denne gamle visdommen tilbake til kjernen av hvordan de unge forberedes på å bygge fremtiden. Ingenting av betydning læres først på virkelig utstyr, på virkelige mennesker eller under uopprettelige forhold. Hver deltaker øver i simulering til øvelse blir kompetanse, og kompetanse blir beredskap. Rotasjonsmodellen fører hver deltaker gjennom de tre grunnleggende regionene, og hver rotasjon ender i en offentlig og samarbeidende feiring åpen for det bredere vertssamfunnet. Dette er respekt for det unge mennesket hvis første feil aldri bør koste et liv.`,
      333: `Enhver disiplin verdt å mestre ble lært av noen før den var kjent. Mesterhåndverkere øver før fremføring, piloter øver før flyging, leger øver før kirurgi, og barn øver på verden gjennom lek. Atlantis-avtalen fører denne gamle visdommen tilbake til kjernen av hvordan de unge forberedes på å bygge fremtiden. Ingenting av betydning læres først på virkelig utstyr, på virkelige mennesker eller under uopprettelige forhold. Hver deltaker øver i simulering til øvelse blir kompetanse, og kompetanse blir beredskap. Dette er ikke forsiktighet — det er respekt for det unge mennesket hvis første feil aldri bør koste noen livet.\n\nAvtalens rotasjonsmodell fører hver deltaker gjennom de tre grunnleggende regionene. Det som læres i Cambodia foredles i Honduras og fullføres i Austin. Det som oppdages i Austin settes under spørsmål i Cambodia og integreres i Honduras. Hver deltaker lever, lærer og veiledes på tvers av kulturer som ellers ville forblitt fjerne. Læreplanen henter fra tradisjoner for disiplinert simulering på tvers av mange kulturer — fra Sun Tzus tradisjon for strategisk skolering, fra Musashis øvelse-gjennom-lek, fra Ibn Khalduns sykliske læringsteori, fra Nalandas monastiske dialektikk, fra den sivile flysimulatoren — syntetisert for å ære hvert kognitive stadium og hver kulturell arv. Ingen enkelt tradisjon dominerer.\n\nHver rotasjon ender i en offentlig og samarbeidende feiring åpen for det bredere vertssamfunnet. Naboer, familier og nysgjerrige besøkende samles for å se hva kullet har lært. Disse begivenhetene gjør avansert teknologi tilgjengelig og feiret snarere enn fryktet. Et samfunn som vokser opp med å forstå samarbeidende systemer gjennom lek, kan ikke lett manipuleres av frykt for disse systemene. Dette er avskrekking gjennom utdanning, ikke avskrekking gjennom makt. Avtalens løfte til hver forelder: barnet ditt vil øve tusen ganger i trygghet før det rører noe som kan skade det, og samfunnet vil være vitne til dets vekst hvert skritt på veien. Slik ser respekt for det unge mennesket ut når den bygges inn i et rammeverk, og dette er hva lederskapet overleverer til den neste generasjonen av deltakere før den generasjonen må kreve det.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Sikkerhet verifisert før tillit gis`,
    content: {
      7: `Sikkerhet bevist først, så gis tillit.`,
      33: `Hvert anlegg og hver rotasjon ligger innenfor en beskyttende kappe med tidlig varsling. Maskinvaren nekter våpengjøring. Registre overlever turbulens. Sikkerhet bygges rundt den yngste deltakeren hver dag, ikke bare loves eller antas.`,
      111: `Før tillit gis, må sikkerheten bevises. Atlantis-avtalen gjør dette til sin grunnleggende forpliktelse. Hvert avtaleanlegg, hver rotasjonsrute, hvert sted der en ung deltaker sover eller studerer, ligger innenfor en dokumentert beskyttende kappe med tidligvarslingsevne som gir samfunnet timer, ikke minutter, til å respondere på enhver troverdig risiko. Hver enhet, hver sensor, hvert koordineringssystem er bundet på maskinvarenivå til å nekte gjenbruk for integrering i våpensystemer. Dette er ikke politikk — det er fysikk. Avtalen er utformet for å forbli hederlig gjennom turbulens: politisk ustabilitet, sammentrekning av finansiering, cyberangrep eller reiseforstyrrelser. Hvert scenario planlegges for, og hver plan setter menneskelig verdighet som sin første designbegrensning.`,
      333: `Før tillit gis, må sikkerheten bevises. Atlantis-avtalen gjør dette til sin grunnleggende forpliktelse. Hvert avtaleanlegg, hver rotasjonsrute, hvert sted der en ung deltaker sover eller studerer, ligger innenfor en dokumentert beskyttende kappe med tidligvarslingsevne som gir samfunnet timer, ikke minutter, til å respondere på enhver troverdig risiko. Teknologien som brukes til å beskytte deltakerne, er den samme teknologien avtalen lærer dem å bygge — sensorer, koordinering, kommunikasjonsoverlevelse, distribuert intelligens. Unge mennesker lærer sikkerhet fra innsiden og ut, på sitt eget språk og i sin egen region, ikke ved å bli fortalt at de er trygge, men ved å se hvordan sikkerheten bygges rundt dem hver dag.\n\nAvtalen gir et ubrytelig løfte om hva teknologien dens ikke kan bli. Hver enhet, hver sensor, hvert koordineringssystem er bundet på maskinvarenivå til å nekte gjenbruk for integrering i våpensystemer. Dette er ikke politisk språk. Dette er ikke aspirasjon. Dette er en fysisk umulighet, håndhevet kryptografisk, verifisert av hver signatarregion og inspiserbar av hver borger. Verktøyene som beskytter et barn i Phnom Penh, kan ikke gjenbrukes til å skade et barn i Austin. Verktøyene som forbinder en svermøvelse i Tegucigalpa, kan ikke omkonfigureres til å angripe et menneske noe sted. Dette er avtalens svar på et århundre med frykt for dobbel bruk. Ikke politikk — fysikk.\n\nAvtalen er utformet for å forbli hederlig gjennom turbulens. Dersom en signatarregion mister politisk stabilitet, tas deltakerne imot av de gjenværende regionene. Dersom finansieringen trekker seg sammen, beskyttes deltakernes stipender først, før administrasjon og infrastruktur. Dersom digitale registre angripes, består sikkerhetskopier utenfor nett. Dersom reise blir umulig, fortsetter substratet virtuelt. Hvert scenario planlegges for, og hver plan setter menneskelig verdighet som sin første designbegrensning. Ledere som signerer denne avtalen, signerer løftet om at sikkerhet bygges, ikke antas. Det de gir sine borgere, er ikke bare mulighet, men beskyttelse bygget til den standarden den yngste deltakeren fortjener — den samme beskyttelsen enhver leder ville kreve for sitt eget barn som krysser en ukjent grense alene.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Godtgjørelse, velferd og menneskelig verdighet`,
    content: {
      7: `Et stipend, en mentor, et hjem.`,
      33: `Hver deltaker mottar et livsopphold-stipend fra første dag. Kjærlighet, tap og trygghet behandles som førsteklasses infrastruktur. Suksess måles ved den mest sårbare deltakeren, aldri ved gjennomsnittet. Verdighet som substrat, aldri utsmykning.`,
      111: `Atlantis-avtalen behandler hver deltaker som et helt menneske fra første dag. Et stipend gis fra det øyeblikket deltakelsen begynner, indeksert til regionens levekostnad slik at virkningen ærer den lokale verdigheten i arbeid. Velferd behandles som førsteklasses infrastruktur — ikke et valgfritt gode, ikke et velvære-frynsegode, men substratet som alt annet hviler på. Tre grunnleggende områder støttes: Kjærlighet, Tap og Trygghet. Avtalen måler suksess ved utfallet for sin mest sårbare deltaker, ikke ved gjennomsnittet. Ingen deltaker vil stille bli glemt for at gjennomsnittene skal se bra ut. Verdighet som substrat, ikke utsmykning.`,
      333: `Atlantis-avtalen behandler hver deltaker som et helt menneske fra første dag. Et stipend gis fra det øyeblikket deltakelsen begynner, indeksert til regionens levekostnad slik at virkningen ærer den lokale verdigheten i arbeid. Stipendet kommer før familieforpliktelser blir nødstilfeller, og før verdigheten kompromitteres. Det signaliserer til hvert ungt menneske at tiden deres er verdifull, at bidraget deres er forventet, og at familiens stabilitet er en del av avtalens ansvar. Dette er ikke veldedighet. Dette er erkjennelsen av at alminnelig menneskelig innovasjon først krever alminnelig menneskelig trygghet. Et sinn kan ikke blomstre mens hjemmet er truet.\n\nVelferd behandles som førsteklasses infrastruktur — ikke et valgfritt gode, ikke et velvære-frynsegode, men substratet som alt annet hviler på. Avtalen navngir tre grunnleggende områder som hver deltaker støttes gjennom: Kjærlighet, i betydningen tilknytning, binding og sunn grense; Tap, siden hver deltaker vil oppleve sorg og må følges gjennom den, ikke rundt den; og Trygghet, i betydningen at hver deltaker vet hvem de skal ringe, i hver region, på sitt eget språk. Individuell rådgivning, gruppesirkler, somatiske praksiser og kulturelle eller åndelige praksiser æret etter deltakerens egen tradisjon, tilbys alle. Null påtvunget ideologi. Avtalen holder rom med ærbødighet; den driver ikke misjon for noe trossystem.\n\nAvtalen måler suksess ved utfallet for sin mest sårbare deltaker, ikke ved gjennomsnittet. Deltakere på landsbygda uten høy båndbredde blir betjent. Nevrodivergente deltakere får tilrettelegging som norm. Deltakere med funksjonsnedsettelse finner hvert anlegg tilgjengelig. Kjønnsmangfoldige deltakere får trygg bolig og mentorparing. De som ikke har språket som morsmål, finner hvert dokument på sitt språk. Urfolksdeltakere finner sine kulturelle praksiser æret og sin tradisjonelle kunnskap beskyttet. Ledere som signerer denne avtalen, lover at ingen deltaker stille vil bli glemt for at gjennomsnittene skal se bra ut. Dette er verdighet som substrat, ikke som utsmykning. Det som måles, er det som vil bli æret, og det som æres her, er hele mennesket — sinn, kropp og ånd sammen, uten noe unntak overhodet.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finansiering og styresett`,
    content: {
      7: `Borgere finansierer neste generasjon direkte.`,
      33: `Vanlige innbyggere bidrar med små månedlige beløp. Ingen bistandskanal, ingen utenlandsk velgjører, ingen politiske tråder. Hver krone er sporbar. Hvert regnskap publiseres, på hver regions språk, hver måned, offentlig.`,
      111: `Atlantis-avtalen finansieres av de borgerne den tjener. Vanlige innbyggere bidrar med små frivillige beløp hver måned — beskjedne nok til at ingen voksen prises ut, resonante nok til at summen bærer avtalens arbeid i betydelig skala. Når en borger finansierer neste generasjon direkte, holder den borgeren avtalen ansvarlig direkte. Avtalen er bevisst uavhengig av de multilaterale institusjonene som formet det forrige århundret. Dette er ikke en politisk uttalelse — det er et designvalg. Hver krone registreres varig og sporbart. Hvert borgerbidrag kan følges fra opprinnelse til stipend til innovasjon. En åpenhet av et slag som sjelden tilbys av noen institusjon.`,
      333: `Atlantis-avtalen finansieres av de borgerne den tjener. Vanlige innbyggere i de deltakende regionene bidrar med små frivillige beløp hver måned — beløp beskjedne nok til at ingen voksen i noen vertsregion prises ut av deltakelse, resonante nok til at summen bærer avtalens arbeid i betydelig skala. Denne utformingen er bevisst. Når en borger finansierer utdanningen til neste generasjon direkte, holder den borgeren avtalen ansvarlig direkte. Det finnes ingen bistandskanal, ingen utenlandsk velgjører, ingen politisk tråd knyttet til sjekken. Avtalens sjel er borgeren som bidrar med ett lite beløp hver måned, hvis deltakelse gjør helheten mulig.\n\nAvtalen er bevisst uavhengig av de multilaterale institusjonene som har formet det forrige århundret — Den nordatlantiske traktatorganisasjonen, Verdens helseorganisasjon, De forente nasjoner, Det internasjonale pengefondet, Verdensbanken og hver nasjonal kanal for utenlandsk bistand. Dette er ikke en politisk uttalelse om verdien av disse institusjonene eller deres bidrag. Det er et designvalg. Avhengigheter av ett enkelt punkt kompromitterer holdbarheten over en femhundreårshorisont. Et rammeverk ment å tjene hver region uavhengig av geopolitisk tilhørighet, kan ikke floke seg inn med noen enkelt tilhørighet. Nasjonale myndigheter kan bidra frivillig. Bidrag er åpne. Intet bidrag kjøper styringsinnflytelse, fra noen kilde, noensinne.\n\nHver krone og hver verdienhet som kommer inn i avtalen, registreres varig, offentlig og sporbart. Hvert borgerbidrag kan følges fra sin opprinnelse til stipendet det blir til, til det unge mennesket det tjener, til innovasjonsprosjektet som springer ut av det unge menneskets arbeid. Administrative kostnader har et tak. Bedrifts- og institusjonsgaver ønskes velkommen og har et tak. Fullstendig regnskap leveres på hver signatarregions språk hver måned. Ledere som signerer avtalen, lover sine borgere en åpenhet av et slag som sjelden tilbys av noen institusjon — åpenhet som vil forbli leselig i århundrer etter at hver signatar har forlatt sitt embete. Dette er tilliten avtalen krever. Dette er tilliten avtalen fortjener, ett lite sporbart bidrag om gangen, i full åpenhet for hver borger.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Tverrkulturell utveksling og globalt bidrag`,
    content: {
      7: `Hver lærende på sitt eget språk.`,
      33: `Hver aktivitet tilgjengelig på deltakerens språk. Kunstig, Menneskelig og Delt intelligens holdt i produktiv spenning — ingen student føyer seg for én alene. Læreplaner og resultater publisert åpent. Det én region lærer, arver alle.`,
      111: `Atlantis-avtalen fører utdanningen tilbake til dens dypeste formål: utvekslingen av visdom over grenser som ellers ville skille. Hver aktivitet er tilgjengelig på deltakerens eget språk, på vertsregionens språk og i et kanonisk felles register. Språk er ikke utsmykning — språk er jurisdiksjon, språk er verdighet gjort leselig. Utdanningsrammeverket hviler på treenigheten av intelligenser: den Kunstige foreslår, den Menneskelige avgjør, den Delte Hensikten validerer. Hver student lærer å holde alle tre i produktiv spenning. Det avtalen lærer, gir avtalen tilbake. Læreplaner, innovasjonsresultater, velferdsforskning og styringsbeslutninger publiseres alle åpent. Det én region lærer, arver alle regioner.`,
      333: `Atlantis-avtalen fører utdanningen tilbake til dens dypeste formål: utvekslingen av visdom over grenser som ellers ville skille. Hver aktivitet i avtalen er tilgjengelig på deltakerens eget språk, på vertsregionens offisielle språk og i et kanonisk felles register, slik at ingen deltaker navigerer avtalen på en tunge de ikke valgte. Språk er ikke utsmykning. Språk er jurisdiksjon. Språk er verdighet gjort leselig. Når et ungt menneske fra en cambodiansk landsby leser sitt eget stipendregister på khmer, når et ungt menneske fra en honduransk by leser det på spansk, når et ungt menneske fra et nabolag i Austin leser det på engelsk, æres alle tre likt av den samme avtalen.\n\nAvtalens utdanningsrammeverk hviler på treenigheten av intelligenser som Vision 2525 gjør synlig. Kunstig Intelligens foreslår mønstre, alternativer og muligheter raskere enn noe menneske alene kunne. Menneskelig Intelligens avgjør om trygghet, etikk og retning — spørsmålene ingen maskin bør besvare. Delt Hensikt validerer at beslutninger stemmer overens med avtalens grunnleggende prinsipper, og sikrer at ingen deltaker blir bedt om å velge mellom individuell fortreffelighet og kollektivt gode. Ingen student læres opp til å føye seg for noen enkelt intelligens. Hver student lærer å holde alle tre i produktiv spenning. Slik forberedes den neste generasjonen av ledere til å styre ansvarlig og klokt i en verden der ingen av disse tre intelligensene noensinne vil handle alene eller uten kontroll.\n\nDet avtalen lærer, gir avtalen tilbake. Læreplaner publiseres under åpen lisens slik at enhver region — signatar eller ikke — fritt kan tilpasse dem til lokal kultur og pedagogisk tradisjon. Innovasjonsresultater publiseres. Velferdsforskning publiseres i aggregert form for forskere overalt. Styringsbeslutninger publiseres med sitt fulle resonnement. Avtalens suksess måles ikke bare ved sine egne deltakere, men ved antallet utdannings-, innovasjons- og kulturinitiativer som oppstår i dens kjølvann, i regioner som aldri signerte den grunnleggende piloten, men bygde videre på dens åpent delte visdom. Det én region lærer, arver alle andre regioner.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Bærekraftig vekst av nettverket`,
    content: {
      7: `Aldri raskere enn verdigheten kan reise.`,
      33: `Tre grunnleggende regioner fullfører én pilotsyklus før en fjerde slutter seg til. Registre forankret til å vare i fem århundrer. Hver signatar beholder sin suverenitet. Ingenting nedgraderes for å gi plass til neste signatar.`,
      111: `Atlantis-avtalen vil ikke vokse raskere enn kvaliteten den kan ære. Tre grunnleggende regioner må fullføre en full pilotsyklus, med hver deltaker æret og hvert prinsipp verifisert, før en fjerde region slutter seg til. Dette er et prinsipp som endelig er blitt levende disiplin. Avtalens horisont er bevisst lang — fem århundrer fra den grunnleggende dagen. Registrene er forankret slik at en borger som leser dem om hundre år, kan stole på resonnementet. Hver signatar beholder full suverenitet, full myndighet og full frihet til å trekke seg. Ingen signatar kan kompromittere de grunnleggende prinsippene — for disse prinsippene er avtalens løfte til sine deltakere gjennom hver generasjon.`,
      333: `Atlantis-avtalen vil ikke vokse raskere enn kvaliteten den kan ære. Hver utvidelse er et løfte til deltakerne som allerede er inne — at avtalens grunnleggende standard ikke vil bli utvannet av begeistringen over skala. Tre grunnleggende regioner må fullføre en full pilotsyklus, med hver deltaker æret og hvert prinsipp verifisert, før en fjerde region slutter seg til. Dette er ikke forsiktighet forkledd som prinsipp. Dette er et prinsipp som endelig er blitt levende disiplin på tvers av hver grunnleggende region. Ledere som signerer den grunnleggende piloten, lover fremtidige signatarer det samme substratet, den samme beskyttelsen, den samme verdigheten som det grunnleggende kullet fikk. Ingenting nedgraderes for å gi plass til den neste.\n\nAvtalens horisont er bevisst lang. Den er utformet for å vare i omtrent femten til tjue menneskegenerasjoner — fem århundrer fra den grunnleggende dagen. Registrene er forankret slik at en borger som leser dem om hundre år, kan stole på resonnementet. Dens koordinatramme, dens roller for menneskelig myndighet og dens tverrgenerasjonelle styringssykluser er alle bygget for å overleve enhver enkeltteknologisk overgang. Avtalen vil overleve hvert menneske som signerer dens grunnleggende pilot. Det er dens løfte til barnet som signerer en stipendavtale året etter ratifiseringen, til det barnets barnebarn som kanskje styrer avtalen midt i århundret, og til hver generasjon som arver det grunnleggerne bygger nå.\n\nHver signatar beholder friheten til å trekke seg med varsel. Hver signatar beholder full suverenitet. Hver signatar beholder myndighet over sine egne borgere. Hver signatar beholder retten til å foreslå endringer, reise tvister og forme avtalens utvikling sammen med hver annen signatar. Det ingen signatar kan gjøre, er å kompromittere substratets grunnleggende prinsipper — for disse prinsippene er avtalens løfte til sine deltakere, og det løftet må overleve enhver enkelt signaturs bortgang. Ledere som signerer denne avtalen nå, slutter seg til noe større enn noen enkelt periode i politisk embete. De signerer avtalens neste århundre, og århundrene deretter, inn i en horisont deres egne barnebarn vil arve og fullføre.`,
    },
  },
];
