import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_PL: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Tam, gdzie zaczyna się innowacja`,
    content: {
      7: `Przywódcy zaczynają, czego wieki nie zaczęły.`,
      33: `Trzy regiony — Kambodża, Honduras, Austin — obiecują gościć młodych uczniów, chronić ich i przekazać im narzędzia przyszłości. Rząd, Edukacja, Innowacja: trzy wizjonerskie podpisy z każdego regionu. Jeden wspólny początek.`,
      111: `Atlantis Accords jest obietnicą złożoną przez przywódców gotowych rozpocząć coś, co dotąd nie istniało. Jego założyciele w Kambodży, Hondurasie i Austin w Teksasie zostali wybrani ze względu na jedną rzadką cechę: gotowość powierzenia młodym narzędzi przyszłości, póki jest jeszcze czas, by ich nauczyć. Podpisanie zobowiązuje region do goszczenia uczących się z różnych kultur, wniesienia tego, co tylko on może zaoferować, i utrzymywania standardu wyższego niż wymagają obecne regulacje. Trzy wizjonerskie podpisy — Rząd, Edukacja, Innowacja — wchodzą w porozumienie razem. Trzech wizjonerów, trzy regiony, jeden wspólny początek.`,
      333: `Każda cywilizacja jest pamiętana przez to, co postanowiła rozpocząć. Atlantis Accords jest obietnicą złożoną przez przywódców gotowych rozpocząć coś, co dotąd nie istniało — wspólny fundament dla zwyczajnej ludzkiej innowacji, który sięga w każdy zakątek świata, honoruje każdy głos i trwa przez pokolenia. Jego założyciele w Kambodży, Hondurasie i Austin w Teksasie nie zostali wybrani ze względu na potęgę gospodarczą, siłę militarną ani prestiż instytucjonalny. Wybrano ich ze względu na rzadszą cechę: gotowość powierzenia młodym narzędzi przyszłości. To właśnie oznacza przywództwo w nadchodzącym stuleciu — odwaga przekazania kluczy następnemu pokoleniu, póki jest jeszcze czas, by nauczyć je prowadzić.

Porozumienie zwołuje eXeL, siła organizująca stworzona celowo na ten moment. eXeL istnieje świadomie poza tradycyjnymi kanałami koordynacji, które ukształtowały ubiegłe stulecie — poza strukturami traktatów dyplomatycznych, poza wielostronnymi biurokracjami, poza politycznymi uwikłaniami jakiegokolwiek pojedynczego państwa. eXeL jest zaufanym zwołującym, który skupia wizjonerskich przywódców wokół wspólnych ram, wspólnego koła zamachowego i wspólnego pięćsetletniego horyzontu. Każdy sygnatariusz zachowuje pełną suwerenność, pełną władzę nad własnymi obywatelami i pełną swobodę wycofania się w każdej chwili. To, co sygnatariusze zyskują, to efekt sieciowy, jakiego dostarczyć może jedynie celowo zbudowane ramy. Jest to koordynacja bez żadnej formy politycznej dominacji.

Podpisanie porozumienia jest podpisaniem obietnicy. Że region będzie gościł młodych uczących się z różnych kultur. Że region wniesie to, co tylko on może wyjątkowo zaoferować. Że region utrzyma się na standardzie wyższym niż wymagają obecne regulacje. Że uczyni to publicznie, przejrzyście, na oczach każdego obywatela, któremu służy. Wymagane są trzy podpisy z każdego regionu — Rząd, Edukacja i Innowacja. Żaden urząd sam nie wiąże porozumienia. Trzeba trzech wizjonerów, by powiedzieć tak. Trzech wizjonerów, trzy regiony, jeden początek — tak każde ramy wchodzą w życie przez wzajemne zaufanie przywódców gotowych je podpisać.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Uczenie się poprzez symulację`,
    content: {
      7: `Ćwiczyć tysiąc razy przed dotknięciem.`,
      33: `Nic doniosłego nie jest uczone najpierw na żywym sprzęcie. Każdy uczestnik ćwiczy w symulacji, przemieszcza się między trzema regionami, świętuje publicznie. To szacunek dla młodego człowieka, którego pierwszy błąd nigdy nie powinien kosztować życia.`,
      111: `Każda dyscyplina warta opanowania została nauczona przez kogoś, zanim została poznana. Atlantis Accords przywraca tę starożytną mądrość w samo centrum tego, jak młodych przygotowuje się do budowania przyszłości. Nic doniosłego nie jest uczone najpierw na żywym sprzęcie, na prawdziwych ludziach lub w warunkach nieodwracalnych. Każdy uczestnik ćwiczy w symulacji, aż ćwiczenie stanie się kompetencją, a kompetencja gotowością. Model rotacji przenosi każdego uczestnika przez trzy regiony założycielskie, a każda rotacja kończy się publiczną, wspólną celebracją otwartą dla szerszej społeczności goszczącej. Jest to szacunek dla młodego człowieka, którego pierwszy błąd nigdy nie powinien kosztować życia.`,
      333: `Każda dyscyplina warta opanowania została nauczona przez kogoś, zanim została poznana. Mistrzowie rzemieślnicy ćwiczą przed występem, piloci ćwiczą przed lotem, lekarze ćwiczą przed operacją, a dzieci ćwiczą świat poprzez zabawę. Atlantis Accords przywraca tę starożytną mądrość w samo centrum tego, jak młodych przygotowuje się do budowania przyszłości. Nic doniosłego nie jest uczone najpierw na żywym sprzęcie, na prawdziwych ludziach lub w warunkach nieodwracalnych. Każdy uczestnik ćwiczy w symulacji, aż ćwiczenie stanie się kompetencją, a kompetencja gotowością. To nie ostrożność — to szacunek dla młodego człowieka, którego pierwszy błąd nigdy nie powinien kosztować nikogo życia.

Model rotacji porozumienia przenosi każdego uczestnika przez trzy regiony założycielskie. To, czego uczy się w Kambodży, jest doskonalone w Hondurasie i dopełniane w Austin. To, co odkrywa się w Austin, jest kwestionowane w Kambodży i integrowane w Hondurasie. Każdy uczestnik żyje, uczy się i jest prowadzony przez mentorów w kulturach, które inaczej pozostałyby odległe. Program szkolenia czerpie z tradycji zdyscyplinowanej symulacji wielu kultur — z tradycji edukacji strategicznej Sun Tzu, z praktyki-przez-grę Musashiego, z cyklicznej teorii uczenia się Ibn Khalduna, z dialektyki klasztornej Nalanda, z cywilnego symulatora lotu — zsyntetyzowanych, by uszanować każdy etap poznawczy i dziedzictwo kulturowe. Żadna tradycja nie dominuje.

Każda rotacja kończy się publiczną, wspólną celebracją otwartą dla szerszej społeczności goszczącej. Sąsiedzi, rodziny i ciekawi goście gromadzą się, by zobaczyć, czego kohorta się nauczyła. Wydarzenia te sprawiają, że wyrafinowana technologia staje się dostępna i celebrowana, a nie budząca lęk. Społeczeństwo, które dorasta rozumiejąc systemy współpracy poprzez zabawę, nie może być łatwo manipulowane strachem wobec tych systemów. Jest to odstraszanie poprzez edukację, a nie odstraszanie poprzez siłę. Obietnica porozumienia dla każdego rodzica: twoje dziecko przećwiczy w bezpieczeństwie tysiąc razy, zanim dotknie czegokolwiek, co mogłoby mu zaszkodzić, a społeczność będzie świadkiem jego rozwoju na każdym kroku. Tak wygląda szacunek dla młodego człowieka, gdy jest wbudowany w ramy, i to właśnie przywództwo przekazuje następnemu pokoleniu uczestników, zanim to pokolenie samo musi tego zażądać.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Bezpieczeństwo zweryfikowane, zanim zaufanie zostanie udzielone`,
    content: {
      7: `Bezpieczeństwo najpierw udowodnione, potem zaufanie.`,
      33: `Każdy obiekt i każda rotacja mieści się wewnątrz ochronnej otoczki z wczesnym ostrzeganiem. Sprzęt odmawia militaryzacji. Zapisy przetrwają turbulencje. Bezpieczeństwo jest inżynierowane wokół najmłodszego uczestnika każdego dnia, nie jedynie obiecywane.`,
      111: `Zanim zaufanie zostanie udzielone, bezpieczeństwo musi zostać udowodnione. Atlantis Accords czyni to swoim założycielskim zobowiązaniem. Każdy obiekt porozumienia, każda trasa rotacji, każde miejsce, w którym młody uczestnik śpi lub studiuje, mieści się w udokumentowanej otoczce ochronnej z możliwością wczesnego ostrzegania, dającej społeczności godziny, a nie minuty, na reakcję na wiarygodne zagrożenie. Każde urządzenie, każdy czujnik, każdy system koordynacji jest związany na poziomie sprzętowym, by odmówić przystosowania do integracji z systemami broni. To nie polityka — to fizyka. Porozumienie zaprojektowano tak, by pozostało honorowe przez turbulencje: niestabilność polityczną, kurczenie się finansowania, atak cybernetyczny lub zakłócenia podróży. Każdy scenariusz jest zaplanowany, a każdy plan stawia ludzką godność jako pierwsze ograniczenie projektu.`,
      333: `Zanim zaufanie zostanie udzielone, bezpieczeństwo musi zostać udowodnione. Atlantis Accords czyni to swoim założycielskim zobowiązaniem. Każdy obiekt porozumienia, każda trasa rotacji, każde miejsce, w którym młody uczestnik śpi lub studiuje, mieści się w udokumentowanej otoczce ochronnej z możliwością wczesnego ostrzegania, dającej społeczności godziny, a nie minuty, na reakcję na wiarygodne zagrożenie. Technologia używana do ochrony uczestników jest tą samą technologią, której porozumienie uczy ich budować — czujniki, koordynacja, przeżywalność łączności, inteligencja rozproszona. Młodzi ludzie uczą się bezpieczeństwa od wewnątrz, w swoim własnym języku i we własnym regionie, nie przez to, że mówi się im, iż są bezpieczni, ale widząc, jak bezpieczeństwo jest inżynierowane wokół nich każdego dnia.

Porozumienie składa niezłamaną obietnicę dotyczącą tego, czym jego technologia nie może się stać. Każde urządzenie, każdy czujnik, każdy system koordynacji jest związany na warstwie sprzętowej, by odmówić przystosowania do integracji z systemami broni. To nie język polityki. To nie aspiracja. To fizyczna niemożliwość, egzekwowana kryptograficznie, weryfikowana przez każdy region sygnatariusza i inspekcyjna przez każdego obywatela. Narzędzia, które chronią dziecko w Phnom Penh, nie mogą zostać przekształcone, by skrzywdzić dziecko w Austin. Narzędzia, które łączą ćwiczenie roju w Tegucigalpie, nie mogą zostać przekonfigurowane, by kogokolwiek namierzyć. Jest to odpowiedź porozumienia na stulecie strachu przed podwójnym zastosowaniem. Nie polityka — fizyka.

Porozumienie jest zaprojektowane tak, by pozostać honorowe przez turbulencje. Jeśli region sygnatariusza traci stabilność polityczną, uczestnicy są trzymani przez pozostałe regiony. Jeśli finansowanie się kurczy, stypendia uczestników są chronione w pierwszej kolejności, przed administracją i infrastrukturą. Jeśli rejestry cyfrowe są atakowane, kopie offline przetrwają. Jeśli podróż staje się niemożliwa, substrat trwa wirtualnie. Każdy scenariusz jest zaplanowany, a każdy plan stawia ludzką godność jako pierwsze ograniczenie projektu. Przywódcy podpisujący to porozumienie podpisują obietnicę, że bezpieczeństwo jest inżynierowane, a nie zakładane. To, co dają swoim obywatelom, to nie jedynie szansa, lecz ochrona zbudowana na standardzie, na jaki zasługuje najmłodszy uczestnik — ta sama ochrona, jakiej każdy przywódca żądałby dla własnego dziecka przekraczającego samotnie nieznaną granicę.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Wynagrodzenie, dobrostan i godność człowieka`,
    content: {
      7: `Stypendium, mentor i dom.`,
      33: `Każdy uczestnik otrzymuje stypendium na życie od pierwszego dnia. Miłość, strata i bezpieczeństwo są traktowane jako infrastruktura pierwszej klasy. Sukces mierzy się losem najbardziej wrażliwego uczestnika, nigdy średnią. Godność jest substratem, nigdy ozdobą.`,
      111: `Atlantis Accords traktuje każdego uczestnika jako pełnego człowieka od pierwszego dnia. Stypendium jest zapewnione od chwili, gdy uczestnictwo się zaczyna, indeksowane do kosztu życia w regionie, tak by jego oddziaływanie szanowało lokalną godność pracy. Dobrostan jest traktowany jako infrastruktura pierwszej klasy — nie opcjonalna korzyść, nie dodatek wellness, lecz substrat, na którym opiera się wszystko inne. Wspierane są trzy fundamentalne obszary: Miłość, Strata i Bezpieczeństwo. Porozumienie mierzy sukces losem swojego najbardziej wrażliwego uczestnika, a nie średnią. Żaden uczestnik nie zostanie po cichu zapomniany po to, by średnie mogły wyglądać dobrze. Godność jako substrat, nie dekoracja.`,
      333: `Atlantis Accords traktuje każdego uczestnika jako pełnego człowieka od pierwszego dnia. Stypendium jest zapewnione od chwili, gdy uczestnictwo się zaczyna, indeksowane do kosztu życia w regionie, tak by jego oddziaływanie szanowało lokalną godność pracy. Stypendium przybywa, zanim obowiązki rodzinne staną się sytuacjami awaryjnymi i zanim godność zostanie naruszona. Sygnalizuje każdemu młodemu człowiekowi, że jego czas jest cenny, jego wkład jest oczekiwany, a stabilność jego rodziny jest częścią odpowiedzialności porozumienia. To nie dobroczynność. To uznanie, że zwyczajna ludzka innowacja wymaga najpierw zwyczajnego ludzkiego bezpieczeństwa. Umysł nie może rozkwitać, gdy jego dom jest zagrożony.

Dobrostan jest traktowany jako infrastruktura pierwszej klasy — nie opcjonalna korzyść, nie dodatek wellness, lecz substrat, na którym opiera się wszystko inne. Porozumienie wymienia trzy fundamentalne obszary, w których wspierany jest każdy uczestnik: Miłość, w sensie połączenia, przywiązania i zdrowej granicy; Stratę, ponieważ każdy uczestnik doświadczy żałoby i musi zostać przeprowadzony przez nią, nie obok niej; oraz Bezpieczeństwo, w sensie tego, że każdy uczestnik wie, do kogo zadzwonić, w każdym regionie, we własnym języku. Zapewnia się poradnictwo indywidualne, kręgi grupowe, praktyki somatyczne oraz praktyki kulturowe lub duchowe honorowane zgodnie z własną tradycją uczestnika. Zero narzuconej ideologii. Porozumienie trzyma przestrzeń z czcią; nie prozelityzuje żadnego systemu wierzeń.

Porozumienie mierzy sukces losem swojego najbardziej wrażliwego uczestnika, a nie średnią. Wiejscy uczestnicy bez szerokiego pasma internetu są wspierani. Neurodywergentni uczestnicy otrzymują udogodnienia jako normę. Niepełnosprawni uczestnicy znajdują każdy obiekt dostępny. Uczestnicy o różnorodnej płci otrzymują bezpieczne zakwaterowanie i dobór mentora. Osoby niebędące rodzimymi użytkownikami języka znajdują każdy dokument w swoim języku. Rdzenni uczestnicy znajdują swoje praktyki kulturowe honorowane, a swoją wiedzę tradycyjną chronioną. Przywódcy podpisujący to porozumienie obiecują, że żaden uczestnik nie zostanie po cichu zapomniany po to, by średnie mogły wyglądać dobrze. To godność jako substrat, nie dekoracja. To, co jest mierzone, jest tym, co będzie honorowane, a to, co honorowane tutaj, to cały człowiek — umysł, ciało i duch razem, bez żadnego wyjątku.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finansowanie i zarządzanie`,
    content: {
      7: `Obywatele finansują następne pokolenie bezpośrednio.`,
      33: `Zwykli mieszkańcy wnoszą małe miesięczne kwoty. Bez rurociągu pomocowego, bez zagranicznego dobroczyńcy, bez sznurków politycznych. Każdy dolar jest śledzony. Każde rozliczenie jest publikowane, w języku każdego regionu, co miesiąc, publicznie.`,
      111: `Atlantis Accords jest finansowany przez obywateli, którym służy. Zwykli mieszkańcy wnoszą małe dobrowolne kwoty co miesiąc — skromne na tyle, że żaden dorosły nie jest z nich wyłączony, rezonansowe na tyle, że suma podtrzymuje pracę porozumienia w znaczącej skali. Gdy obywatel finansuje następne pokolenie bezpośrednio, ten obywatel rozlicza porozumienie bezpośrednio. Porozumienie jest celowo niezależne od wielostronnych instytucji, które ukształtowały poprzednie stulecie. To nie wypowiedź polityczna — to decyzja projektowa. Każdy dolar jest zapisywany trwale i śledzalnie. Każdy wkład obywatela można prześledzić od pochodzenia przez stypendium po innowację. Przejrzystość rzadko oferowana przez jakąkolwiek instytucję.`,
      333: `Atlantis Accords jest finansowany przez obywateli, którym służy. Zwykli mieszkańcy regionów uczestniczących wnoszą małe dobrowolne kwoty co miesiąc — kwoty skromne na tyle, że żaden dorosły w żadnym regionie goszczącym nie jest wyłączony z uczestnictwa, rezonansowe na tyle, że suma podtrzymuje pracę porozumienia w znaczącej skali. Ten projekt jest celowy. Gdy obywatel finansuje edukację następnego pokolenia bezpośrednio, ten obywatel rozlicza porozumienie bezpośrednio. Nie ma rurociągu pomocowego, nie ma zagranicznego dobroczyńcy, nie ma politycznego sznurka doczepionego do czeku. Duszą porozumienia jest obywatel, który wnosi jedną małą kwotę co miesiąc, którego uczestnictwo czyni całość możliwą.

Porozumienie jest celowo niezależne od wielostronnych instytucji, które ukształtowały poprzednie stulecie — Organizacji Traktatu Północnoatlantyckiego, Światowej Organizacji Zdrowia, Organizacji Narodów Zjednoczonych, Międzynarodowego Funduszu Walutowego, Banku Światowego oraz każdego państwowego kanału pomocy zagranicznej. To nie wypowiedź polityczna o wartości tych instytucji ani o ich wkładzie. To decyzja projektowa. Zależności od pojedynczego punktu podważają trwałość na pięćsetletnim horyzoncie. Ramy mające służyć każdemu regionowi bez względu na sojusze geopolityczne nie mogą być uwikłane w żaden jeden sojusz. Rządy państwowe mogą wnosić wkład dobrowolnie. Wkłady są przejrzyste. Żaden wkład nie kupuje wpływu na zarządzanie, z żadnego źródła, nigdy.

Każdy dolar i każda jednostka wartości wchodząca do porozumienia jest rejestrowana trwale, publicznie i śledzalnie. Każdy wkład obywatela można prześledzić od jego pochodzenia, przez stypendium, które się nim staje, po młodego człowieka, któremu służy, i projekt innowacyjny, który wyłania się z pracy tego młodego człowieka. Koszty administracyjne są ograniczone. Dary korporacyjne i instytucjonalne są mile widziane i ograniczone pułapem. Pełne rozliczenie jest dostarczane w języku każdego regionu sygnatariusza co miesiąc. Przywódcy podpisujący porozumienie obiecują swoim obywatelom przejrzystość rzadko oferowaną przez jakąkolwiek instytucję — przejrzystość, która pozostanie czytelna przez wieki po tym, jak każdy sygnatariusz opuści urząd. To jest zaufanie, którego porozumienie wymaga. To jest zaufanie, na które porozumienie zasługuje, jeden mały śledzalny wkład za drugim, na oczach każdego obywatela.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Wymiana międzykulturowa i wkład globalny`,
    content: {
      7: `Każdy uczący się w swoim języku.`,
      33: `Każda czynność dostępna w języku uczestnika. Sztuczna, Ludzka i Wspólna Inteligencja utrzymywane w produktywnym napięciu — żaden student nie ulega jednej. Programy nauczania i wyniki publikowane otwarcie. Czego uczy się jeden region, dziedziczą wszystkie.`,
      111: `Atlantis Accords przywraca edukację jej najgłębszemu celowi: wymianie mądrości ponad granicami, które inaczej by dzieliły. Każda czynność jest dostępna w języku własnym uczestnika, w języku regionu goszczącego oraz w kanonicznym wspólnym zapisie. Język nie jest dekoracją — język jest jurysdykcją, język jest godnością uczynioną czytelną. Ramy edukacyjne opierają się na trójcy inteligencji: Sztuczna proponuje, Ludzka decyduje, Wspólny Zamiar potwierdza. Każdy uczeń uczy się trzymać wszystkie trzy w produktywnym napięciu. To, czego porozumienie się uczy, porozumienie oddaje. Programy nauczania, wyniki innowacji, badania nad dobrostanem i decyzje zarządcze są publikowane otwarcie. Czego uczy się jeden region, dziedziczą wszystkie.`,
      333: `Atlantis Accords przywraca edukację jej najgłębszemu celowi: wymianie mądrości ponad granicami, które inaczej by dzieliły. Każda czynność porozumienia jest dostępna w języku własnym uczestnika, w oficjalnym języku regionu goszczącego oraz w kanonicznym wspólnym zapisie, tak by żaden uczestnik nie poruszał się w porozumieniu w języku, którego nie wybrał. Język nie jest dekoracją. Język jest jurysdykcją. Język jest godnością uczynioną czytelną. Gdy młody człowiek z kambodżańskiej wioski czyta swój własny zapis stypendialny w języku khmerskim, gdy młody człowiek z honduraskiego miasteczka czyta go po hiszpańsku, gdy młody człowiek z dzielnicy Austin czyta go po angielsku, wszyscy trzej są honorowani równo przez to samo porozumienie.

Ramy edukacyjne porozumienia opierają się na trójcy inteligencji, którą Vision 2525 czyni widoczną. Sztuczna Inteligencja proponuje wzorce, opcje i możliwości szybciej, niż jakikolwiek człowiek w pojedynkę mógłby to zrobić. Ludzka Inteligencja decyduje o bezpieczeństwie, etyce i kierunku — o pytaniach, na które żadna maszyna odpowiadać nie powinna. Wspólny Zamiar potwierdza, że decyzje są zgodne z zasadami założycielskimi porozumienia, dbając o to, by żadnego uczestnika nie proszono o wybór między indywidualną doskonałością a wspólnym dobrem. Żadnego ucznia nie uczy się poddawać jednej inteligencji. Każdy uczeń uczy się trzymać wszystkie trzy w produktywnym napięciu. Tak następne pokolenie przywódców przygotowuje się, by rządzić odpowiedzialnie i mądrze w świecie, w którym żadna z tych trzech inteligencji nigdy nie zadziała samotnie ani bez sprawdzenia.

To, czego porozumienie się uczy, porozumienie oddaje. Programy nauczania są publikowane na otwartej licencji, tak by każdy region — sygnatariusz lub nie — mógł je swobodnie zaadaptować do lokalnej kultury i tradycji pedagogicznej. Wyniki innowacji są publikowane. Badania nad dobrostanem są publikowane w zagregowanej formie dla badaczy wszędzie. Decyzje zarządcze są publikowane z pełnym uzasadnieniem. Sukces porozumienia jest mierzony nie tylko jego własnymi uczestnikami, lecz także liczbą inicjatyw edukacyjnych, innowacyjnych i kulturowych, które pojawiają się w jego następstwie, w regionach, które nigdy nie podpisały pilotażu założycielskiego, a jednak zbudowały na jego otwarcie dzielonej mądrości. Czego uczy się jeden region, dziedziczą wszystkie inne regiony.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Zrównoważony wzrost sieci`,
    content: {
      7: `Nigdy szybciej, niż godność może podróżować.`,
      33: `Trzy regiony założycielskie kończą jeden cykl pilotażowy przed dołączeniem czwartego. Zapisy zakotwiczone tak, by przetrwać pięć wieków. Każdy sygnatariusz zachowuje suwerenność. Nic nie jest obniżane, by zrobić miejsce następnemu sygnatariuszowi.`,
      111: `Atlantis Accords nie rozrośnie się szybciej, niż może uszanować jakość. Trzy regiony założycielskie muszą ukończyć pełny cykl pilotażowy, z każdym uczestnikiem uhonorowanym i każdą zasadą zweryfikowaną, zanim czwarty region dołączy. To zasada wreszcie stająca się działającą dyscypliną. Horyzont porozumienia jest celowo długi — pięć wieków od dnia założenia. Jego zapisy są zakotwiczone tak, by obywatel czytający je za sto lat mógł zaufać rozumowaniu. Każdy sygnatariusz zachowuje pełną suwerenność, pełną władzę i pełną swobodę wycofania. Żaden sygnatariusz nie może naruszyć zasad założycielskich — ponieważ te zasady są obietnicą porozumienia wobec jego uczestników przez każde pokolenie.`,
      333: `Atlantis Accords nie rozrośnie się szybciej, niż może uszanować jakość. Każde rozszerzenie jest obietnicą złożoną uczestnikom już wewnątrz — że założycielski standard porozumienia nie zostanie rozcieńczony ekscytacją skalą. Trzy regiony założycielskie muszą ukończyć pełny cykl pilotażowy, z każdym uczestnikiem uhonorowanym i każdą zasadą zweryfikowaną, zanim czwarty region dołączy. To nie ostrożność przebrana za zasadę. To zasada, która wreszcie staje się działającą dyscypliną w każdym regionie założycielskim. Przywódcy podpisujący pilotaż założycielski obiecują przyszłym sygnatariuszom ten sam substrat, tę samą ochronę, tę samą godność, jaką otrzymała kohorta założycielska. Nic nie jest obniżane, by zrobić miejsce następnemu.

Horyzont porozumienia jest celowo długi. Zaprojektowano je tak, by przetrwało około piętnastu do dwudziestu pokoleń ludzkich — pięć wieków od dnia założenia. Jego zapisy są zakotwiczone tak, by obywatel czytający je za sto lat mógł zaufać rozumowaniu. Jego układ współrzędnych, jego role władzy ludzkiej i jego międzygeneracyjne cykle zarządzania są wszystkie zbudowane tak, by przetrwać każde pojedyncze przejście technologiczne. Porozumienie przeżyje każdego człowieka, który podpisze pilotaż założycielski. Taka jest jego obietnica wobec dziecka, które podpisze umowę stypendialną w roku po ratyfikacji, wobec wnuków tego dziecka, które mogą rządzić porozumieniem w połowie stulecia, i wobec każdego pokolenia, które odziedziczy to, co założyciele budują teraz.

Każdy sygnatariusz zachowuje swobodę wycofania się za wypowiedzeniem. Każdy sygnatariusz zachowuje pełną suwerenność. Każdy sygnatariusz zachowuje władzę nad swoimi obywatelami. Każdy sygnatariusz zachowuje prawo do proponowania poprawek, do wznoszenia sporów i do kształtowania ewolucji porozumienia obok każdego innego sygnatariusza. Czego żaden sygnatariusz uczynić nie może, to naruszyć założycielskich zasad substratu — ponieważ te zasady są obietnicą porozumienia wobec jego uczestników, a ta obietnica musi przetrwać odejście każdego pojedynczego podpisu. Przywódcy podpisujący to porozumienie teraz przyłączają się do czegoś większego niż jakakolwiek jedna kadencja urzędu politycznego. Podpisują następne stulecie porozumienia, i stulecia dalej, w horyzont, który odziedziczą i dopełnią ich własne wnuki.`,
    },
  },
];
