import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_PL: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Tam, gdzie zaczyna się innowacja`,
    content: {
      7: `Przywódcy zaczynają, czego wieki nie zaczęły.`,
      33: `Trzy regiony — Kambodża, Honduras, Austin — otwierają obietnicę, którą budują obywatele: przyjąć uczących się, chronić ich, przekazać im narzędzia przyszłości. Rząd, Edukacja i Innowacja podpisują jako powiernicy; obywatele ją utrzymują. Jeden początek.`,
      111: `Atlantis Accords to porozumienie między obywatelami świata — obietnica, którą każdy człowiek, gdziekolwiek by się znajdował, może stworzyć i utrzymać, niezależnie od tego, co podpisuje jego rząd czy na co pozwala jego pracodawca. Jego regiony założycielskie — Kambodża, Honduras i Austin w Teksasie — zostały wybrane ze względu na jedną rzadką cechę: gotowość, by zaufać młodym z narzędziami przyszłości, dopóki jest jeszcze czas, by ich tego nauczyć. Rządy, nauczyciele i innowatorzy podpisują akord jako powiernicy swoich regionów — po trzy wizjonerskie podpisy z każdego: Rząd, Edukacja, Innowacja — lecz to obywatele finansują akord, są świadkami jego działania i bezpośrednio rozliczają go z odpowiedzialności. Przynależność nie wymaga ani zgody żadnego rządu, ani błogosławieństwa żadnego pracodawcy. Trzy regiony, jeden wspólny początek.`,
      333: `Każda cywilizacja jest pamiętana przez to, co zdecydowała się zacząć. Atlantis Accords to obietnica między obywatelami świata — może ją zapoczątkować każdy człowiek, gdziekolwiek się znajduje, niezależnie od tego, co podpisuje jego rząd. Jego regiony założycielskie — Kambodża, Honduras i Austin w Teksasie — nie zostały wybrane za potęgę gospodarczą, siłę militarną czy instytucjonalny prestiż, lecz za rzadszą cechę: gotowość, by zaufać młodym z narzędziami przyszłości. Na tym polega przywództwo w nadchodzącym stuleciu — na odwadze, by przekazać klucze następnemu pokoleniu, dopóki jest jeszcze czas, by nauczyć je prowadzić.

Akord zwołuje eXeL, siła organizacyjna stworzona specjalnie na tę chwilę, istniejąca poza kanałami koordynacji, które ukształtowały minione stulecie — poza strukturami traktatów dyplomatycznych, wielostronnymi biurokracjami i politycznymi uwikłaniami jakiegokolwiek pojedynczego państwa narodowego. eXeL jest zaufanym zwołującym, który gromadzi wizjonerskich liderów wokół wspólnych ram, wspólnego koła zamachowego i wspólnego pięćsetletniego horyzontu. Każdy sygnatariusz zachowuje pełną suwerenność, pełną władzę nad własnymi obywatelami i pełną swobodę wycofania się w dowolnej chwili. To, co zyskują sygnatariusze — i co zyskuje każdy obywatel, za cenę Seed, równą siódmej części lokalnej godziny pracy za płacę minimalną — to efekt sieci, jaki może zapewnić wyłącznie framework stworzony do tego celu: koordynacja bez jakiejkolwiek formy politycznej dominacji.

Podpisanie akordu to podpisanie obietnicy: że region przyjmie uczących się z różnych kultur, wniesie to, co tylko on może zaoferować, i będzie trzymać się standardu wyższego, niż wymagają obecne przepisy — publicznie, przejrzyście, odpowiadając przed obywatelami, którzy go finansują, są jego świadkami i rozliczają go z odpowiedzialności, bez konieczności uzyskania zgody jakiegokolwiek rządu czy błogosławieństwa pracodawcy. Z każdego regionu wymagane są trzy podpisy — Rząd, Edukacja i Innowacja — składane jako podpisy powierników, nie właścicieli. Potrzeba trzech wizjonerów, by powiedzieć „tak”, i obywateli, by utrzymać to, co podpisali. Trzej wizjonerzy, trzy regiony, jeden początek — tak framework wchodzi w życie dzięki zaufaniu liderów gotowych podpisać go w istnienie.`,
      999: `Każda cywilizacja jest pamiętana przez to, co zdecydowała się zacząć, a Vision 2525 prosi założycieli tej cywilizacji, by zaczęli od pokory, nie podboju. Atlantis Accords to obietnica złożona przez liderów gotowych zapoczątkować coś, co nigdy wcześniej nie istniało — wspólny fundament ludzkiej innowacji, który dociera do każdego zakątka świata, szanuje każdy głos i trwa przez pokolenia mierzone nie w latach, lecz w stuleciach. Jego założycielscy sygnatariusze w Kambodży, Hondurasie i Austin w Teksasie nie zostali wybrani za potęgę gospodarczą, siłę militarną czy instytucjonalny prestiż. Zostali wybrani za rzadszą cechę: gotowość, by zaufać młodym z narzędziami przyszłości, oraz cierpliwość, by pozwolić pięćsetletniemu horyzontowi przetrwać dłużej niż aplauz dla jakiejkolwiek administracji. Na tym polega przywództwo w nadchodzącym stuleciu — na odwadze, by przekazać klucze następnemu pokoleniu, dopóki jest jeszcze czas, by nauczyć je prowadzić.

Akord zwołuje eXeL, siła organizacyjna stworzona specjalnie na tę chwilę. eXeL istnieje poza kanałami koordynacji, które ukształtowały minione stulecie — poza strukturami traktatów dyplomatycznych, poza wielostronnymi biurokracjami, poza politycznymi uwikłaniami jakiegokolwiek państwa narodowego. eXeL jest zaufanym zwołującym, który gromadzi wizjonerskich liderów wokół wspólnych ram, wspólnego koła zamachowego i wspólnego pięćsetletniego horyzontu. Każdy sygnatariusz zachowuje pełną suwerenność, pełną władzę nad własnymi obywatelami i pełną swobodę wycofania się w dowolnej chwili. To, co zyskują sygnatariusze, to efekt sieci, jaki może zapewnić wyłącznie framework stworzony do tego celu. Wejście każdego uczestnika do tego frameworku zaczyna się w ten sam skromny sposób: od Seed, jednorazowego członkostwa wycenionego na siódmą część lokalnej godziny pracy za płacę minimalną, niezbywalnego i niedającego żadnego roszczenia ekonomicznego. Seed nie kupuje ani własności, ani obietnicy nagrody — jedynie przynależność, prawo, by stanąć wewnątrz frameworku i zacząć. To koordynacja bez jakiejkolwiek formy politycznej dominacji, zbudowana na początku na tyle skromnym, że stać na niego każdego.

Ponieważ suwerenność jest zachowywana, a nie oddawana, akord został zbudowany z myślą o Continuity Without Evasion (Ciągłości Bez Uników). Żaden niezbędny rząd, bank, założyciel ani model nie może wziąć całego frameworku jako zakładnika własnego przetrwania. Każda jurysdykcja jest obsługiwana przez swój zgodny z prawem adapter, działający na zasadzie domyślnej odmowy aż do potwierdzenia zgodności, tak by wartość przepływała wyłącznie przez kanały, które sąd w danej jurysdykcji uznałby za legalne. Jeśli regulator w jednym regionie wyda niekorzystne orzeczenie, tylko ten jeden kanał zamyka się bezpiecznie — przejrzyście, bez szkody dla żadnego uczestnika wewnątrz niego — podczas gdy każdy inny region działa dalej bez zakłóceń. Cały akord nigdy nie upada dlatego, że jeden rząd zmienił zdanie. To przenośność zaprojektowana jako obietnica założycielska, a nie jako plan awaryjny odkryty po kryzysie.

Podpisanie akordu to podpisanie obietnicy. Że region przyjmie uczących się z różnych kultur. Że region wniesie to, co tylko on może zaoferować. Że region będzie trzymać się standardu wyższego, niż wymagają obecne przepisy. Że region będzie to robić publicznie, przejrzyście, w oczach każdego obywatela, któremu służy. Z każdego regionu wymagane są trzy podpisy — Rząd, Edukacja i Innowacja. Żaden urząd nie wiąże akordu samodzielnie. Potrzeba trzech wizjonerów, by powiedzieć „tak”. Ten potrójny podpis to pierwszy wyraz Human Authority (Ludzkiej Władzy): znaczenie, pieniądze i prawo pozostają w rękach ludzi na warstwie suwerennej — warstwie na stałe zamkniętej dla maszyn, bez względu na to, jak zdolne się one staną. Measurement of Time (Pomiar Czasu), MoT, zaczyna zapisywać od chwili podpisania — rzeczywiste minuty rzeczywistej ludzkiej pracy, prowadzone osobno od jakiegokolwiek zautomatyzowanego szacunku — a każde kolejne wydanie prac akordu jest zbudowane tak, by dało się je zrekonstruować dzięki Replay (Odtworzeniu), tak by obywatel urodzony za sto lat mógł prześledzić, jak zapadły dzisiejsze decyzje założycielskie.

To, co zakłada pilotaż, jest pomiarem, zanim stanie się pieniądzem. Każda innowacja wchodząca do frameworku jest oceniana przez Qualified Innovation Score (Kwalifikowany Wskaźnik Innowacji), QIS — średnią z Przychodu, Zysku Brutto, Zysku Operacyjnego i Efektywnych Wydatków na R&D, podzieloną przez cztery. QIS nie jest płatnością i nigdy nie jest własnością; to instrument, dzięki któremu założycielska kohorta uczy się dostrzegać własny postęp, zanim wyznaczona zostanie jakakolwiek nagroda. Wzrost QIS, po spełnieniu kwalifikacji, wyznacza wielkość puli nagród, która następuje — lecz wzrost QIS sam z siebie niczego nie tworzy. Trzy regiony, jeden początek i jedna wspólna dyscyplina: udowodnij wynik, zanim dotkniesz skarbca.

Wartość zdobyta przez potwierdzoną pracę nosi własną nazwę, 웃, obliczaną jako jedna godzina pomnożona przez lokalną płacę minimalną, skalowaną przez Multiple (Mnożnik) stosowany do przepracowanych godzin. 웃 przyznawane jest wyłącznie za pracę potwierdzoną w ramach zdefiniowanego, zatwierdzonego budżetowo zadania; wszystko poniżej tego zatwierdzenia to wciąż planowanie, a samo planowanie niczego nie tworzy. Pułap rozliczeniowy 9999 웃 rocznie chroni każdego uczestnika przed niekontrolowaną koncentracją, a każda nadwyżka przechodzi na kolejny rok, zamiast zniknąć. Za każdym 웃 stoi ♡, Shared Intention (Wspólna Intencja), niosąca powód, dla którego zadanie zostało w ogóle zatwierdzone, oraz ◬, potwierdzone przyspieszenie, jakie zadanie wytworzyło względem zamrożonej linii bazowej — wyłącznie delta, nigdy mylona ze wskaźnikiem zysku. Pilotaż istnieje po to, by udowodnić, że te trzy glify mogą poruszać się razem uczciwie, region po regionie, zanim framework rozrośnie się poza swoich założycieli.

Gdy wartość dociera do człowieka, dociera przez Livelihood Direct — 🏠 — kwalifikowane, licencjonowane lokalne kanały, których eXeL nigdy nie przechowuje jako własnego funduszu. Klasyfikacja zawsze poprzedza rozliczenie, a uznanie za wkład nigdy nie otwiera dostępu do noclegu — decyduje o tym wyłącznie rola danej osoby w zdefiniowanym zadaniu. Wzrost poza pilotaż również podlega bramkowaniu: każdy sześcian frameworku przechodzi z trybu Manual (Ręcznego) przez Semi-Automated (Częściowo Zautomatyzowany) do Autonomous (Autonomicznego) dopiero po spełnieniu zasady 11,1 procent — jednej dziewiątej mierzonej poprawy — zdobywanej sześcian po sześcianie, nigdy nie przyznawanej hurtowo — i nigdy, w żadnych okolicznościach, ponad warstwą suwerenną znaczenia, pieniędzy i prawa. Tak trzej wizjonerzy z każdego regionu, trzy regiony i jeden początek stają się pięćsetletnią obietnicą: nie przez szybkie działanie, lecz przez udowadnianie, publicznie, że każdy krok zasłużył na krok, który po nim następuje.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Uczenie się poprzez symulację`,
    content: {
      7: `Ćwiczyć tysiąc razy przed dotknięciem.`,
      33: `Nic istotnego nie jest uczone najpierw na żywym sprzęcie. Każdy obywatel może ćwiczyć w symulacji, przechodzić rotację przez trzy regiony, świętować — to szacunek dla młodego człowieka, którego pierwszy błąd nigdy nie powinien kosztować życia.`,
      111: `Każda dyscyplina warta opanowania była przez kogoś nauczona, zanim stała się znana. Atlantis Accords przywraca tę odwieczną mądrość do centrum sposobu, w jaki młodzi — i każdy obywatel, który dołącza — są przygotowywani do budowania przyszłości. Nic istotnego nie jest uczone najpierw na żywym sprzęcie, na prawdziwych ludziach ani w nieodwracalnych warunkach; nie jest do tego potrzebna ani zgoda żadnego rządu, ani błogosławieństwo pracodawcy. Każdy uczestnik ćwiczy w symulacji, aż praktyka stanie się kompetencją, a potem gotowością. Model rotacji prowadzi każdego uczestnika przez trzy regiony założycielskie, a każda rotacja kończy się publicznym świętem otwartym dla społeczności gospodarza. To szacunek dla młodego człowieka, którego pierwszy błąd nigdy nie powinien kosztować życia.`,
      333: `Każda dyscyplina warta opanowania była przez kogoś nauczona, zanim stała się znana. Mistrzowie rzemiosła ćwiczą przed występem, piloci przed lotem, lekarze przed operacją, dzieci — poprzez zabawę. Atlantis Accords przywraca tę odwieczną mądrość do centrum sposobu, w jaki młodzi — i każdy obywatel, który dołącza, bez potrzeby zgody rządu czy błogosławieństwa pracodawcy — są przygotowywani do budowania przyszłości. Nic istotnego nie jest uczone najpierw na żywym sprzęcie, na prawdziwych ludziach ani w nieodwracalnych warunkach. Każdy uczestnik ćwiczy w symulacji, aż praktyka stanie się kompetencją, a potem gotowością. To nie jest ostrożność — to szacunek dla młodego człowieka, którego pierwszy błąd nigdy nie powinien nikogo kosztować życia.

Model rotacji akordu prowadzi każdego uczestnika przez trzy regiony założycielskie. To, czego nauczono się w Kambodży, jest doskonalone w Hondurasie i dopełniane w Austin. To, co odkryto w Austin, jest kwestionowane w Kambodży i integrowane w Hondurasie. Każdy uczestnik żyje, uczy się i jest mentorowany pośród kultur, które w innym wypadku pozostałyby odległe. Program szkoleniowy czerpie z tradycji zdyscyplinowanej symulacji wielu kultur — z tradycji strategicznej edukacji Sun Tzu, z nauki-przez-zabawę Musashiego, z cyklicznej teorii uczenia się Ibn Chalduna, z monastycznej dialektyki Nalandy, z cywilnego symulatora lotu — zsyntetyzowanych z poszanowaniem każdego etapu poznawczego i dziedzictwa kulturowego. Żadna pojedyncza tradycja nie dominuje.

Każda rotacja kończy się publicznym świętem otwartym dla społeczności gospodarza, podczas którego sąsiedzi, rodziny i goście widzą, czego nauczyła się kohorta. Te wydarzenia sprawiają, że zaawansowana technologia staje się dostępna i celebrowana, a nie budząca lęk — społeczeństwo, które dorasta, rozumiejąc systemy kooperacyjne poprzez zabawę, nie da się łatwo zmanipulować strachem przed nimi. To odstraszanie przez edukację, nie przez siłę. Obietnica akordu wobec każdego rodzica: twoje dziecko będzie ćwiczyć tysiąc razy w bezpiecznych warunkach, zanim dotknie czegokolwiek, co mogłoby mu zaszkodzić, a wszystko to zostanie poświadczone, tak by obywatel — każdy obywatel, za sto lat — mógł zweryfikować, że wydarzyło się dokładnie tak, jak zostało zapisane. To szacunek dla młodego człowieka wbudowany w framework, i to jest to, co przywództwo jest winne kolejnemu obywatelowi, który dołącza, zanim ten obywatel będzie musiał się tego domagać.`,
      999: `Każda dyscyplina warta opanowania była przez kogoś nauczona, zanim stała się znana, a każda cywilizacja, która przetrwała, przetrwała dlatego, że chroniła przestrzeń, w której nauka mogła zachodzić bezpiecznie, zanim od tej nauki zaczęto wymagać, by się liczyła. Mistrzowie rzemiosła ćwiczą przed występem, piloci ćwiczą przed lotem, lekarze ćwiczą przed operacją, a dzieci ćwiczą świat poprzez zabawę. Atlantis Accords przywraca tę odwieczną mądrość do centrum sposobu, w jaki młodzi są przygotowywani do budowania przyszłości, i nadaje tej mądrości nazwę oraz mechanizm: Replay (Odtworzenie). Nic istotnego nie jest uczone najpierw na żywym sprzęcie, na prawdziwych ludziach ani w nieodwracalnych warunkach. Każdy uczestnik ćwiczy w symulacji, aż praktyka stanie się kompetencją, a potem gotowością, a każda godzina tej praktyki jest rejestrowana, tak by można ją było później zrekonstruować, zbadać i jej zaufać. To nie jest ostrożność — to szacunek dla młodego człowieka, którego pierwszy błąd nigdy nie powinien nikogo kosztować życia, i to szacunek dla zapisu, który tak czy inaczej przetrwa ten błąd.

Model rotacji akordu prowadzi każdego uczestnika przez trzy regiony założycielskie. To, czego nauczono się w Kambodży, jest doskonalone w Hondurasie i dopełniane w Austin. To, co odkryto w Austin, jest kwestionowane w Kambodży i integrowane w Hondurasie. Każdy uczestnik żyje, uczy się i jest mentorowany pośród kultur, które w innym wypadku pozostałyby odległe, a każda rotacja zaczyna się tak, jak zaczyna się każda ludzka instytucja warta zaufania: od Seed. Seed to jednorazowe członkostwo, wycenione na siódmą część lokalnej godziny pracy za płacę minimalną, niezbywalne i niedające żadnego roszczenia ekonomicznego. To nie jest opłata za dostęp do szansy. To próg — na tyle niski, że żaden chętny uczestnik nie zostaje wykluczony z powodu ceny, i na tyle świadomy, że wejście jest wyborem, a nie przypadkowym dryfem. Od tego progu każdy uczestnik należy do rotacji, a rotacja nie należy wyłącznie do jednego regionu.

Program szkoleniowy czerpie z tradycji zdyscyplinowanej symulacji wielu kultur — z tradycji strategicznej edukacji Sun Tzu, z nauki-przez-zabawę Musashiego, z cyklicznej teorii uczenia się Ibn Chalduna, z monastycznej dialektyki Nalandy, z cywilnego symulatora lotu — zsyntetyzowanych z poszanowaniem każdego etapu poznawczego i dziedzictwa kulturowego. Żadna pojedyncza tradycja nie dominuje. W ramach tego programu akord wyznacza granicę, którą każdy uczestnik poznaje wcześnie i nigdy nie zapomina: symulacja to miejsce, w którym Qualified Innovation Score jest rozumiany, a nie wydawany. QIS to pomiar, nigdy płatność, i QIS nigdy nie jest własnością — istnieje po to, by opisać, jak dobrze propozycja się broni, wytrzymuje próbę i służy regionowi, któremu twierdzi, że służy. Wzrost QIS może wyznaczyć wielkość puli nagród po rzeczywistym spełnieniu kwalifikacji, ale sam z siebie niczego nie tworzy. Uczestnik może przeprowadzić sto bezbłędnych symulacji i zdobyć rosnący wynik, nie mając ani jednej godziny 웃 na swoim koncie, ponieważ 웃 przyznawane jest wyłącznie za pracę potwierdzoną w ramach zdefiniowanego, zatwierdzonego budżetowo zadania. Przed takim zatwierdzeniem wszystko — jakkolwiek umiejętne, jakkolwiek obiecujące — jest planowaniem. Akord uczy tego rozróżnienia pierwszego dnia, tak by żaden młody człowiek nie mylił próby z nagrodą i nigdy nie został wprowadzony w błąd co do tego, czemu służy symulacja.

Ta sama dyscyplina rządzi tym, ile autonomii wolno wykonywać wewnątrz rotacji jakiemukolwiek systemowi, ludzkiemu czy sztucznemu. Tryby działania akordu przechodzą w sekwencji — Manual (Ręczny), potem Semi-Automated (Częściowo Zautomatyzowany), potem Autonomous (Autonomiczny) — i żaden sześcian nie awansuje do kolejnego trybu, dopóki nie spełni zasady 11,1 procent mierzonej poprawy, jednej dziewiątej, udowodnionej względem zamrożonej linii bazowej i poświadczonej, a nie jedynie deklarowanej. Symulacja to miejsce, w którym ten dowód powstaje. Narzędzie zdobywa prawo do działania z mniejszym nadzorem tak samo, jak uczestnik zdobywa prawo do większej odpowiedzialności: poprzez wykazaną, zarejestrowaną, dającą się zrekonstruować poprawę, sześcian po sześcianie, nigdy wszystko naraz, i nigdy ponad warstwą, na której decyduje się o znaczeniu, pieniądzach i prawie. Ta warstwa należy wyłącznie do Human Authority, zarówno w symulacji, jak i w rzeczywistym działaniu, ponieważ przestrzeń próby, która uczy złej granicy, uczy złej lekcji na stałe.

Każda rotacja kończy się publicznym i wspólnotowym świętem otwartym dla społeczności gospodarza. Sąsiedzi, rodziny i goście gromadzą się, by zobaczyć, czego nauczyła się kohorta, a to, czego są świadkami, nie jest pokazem szybkości dla samej szybkości, lecz pokazem ◬ — mierzonej delty między zamrożoną linią bazową a tym, co zdyscyplinowana praktyka rzeczywiście osiągnęła, przedstawionej uczciwie, nigdy niepodawanej jako wskaźnik zysku, nigdy nieprzedstawianej jako więcej, niż jest w rzeczywistości. Te wydarzenia sprawiają, że zaawansowana technologia staje się dostępna i celebrowana, a nie budząca lęk. Społeczeństwo, które dorasta, rozumiejąc systemy kooperacyjne poprzez zabawę, nie da się łatwo zmanipulować strachem przed tymi systemami. To odstraszanie przez edukację, nie przez siłę, i działa to dlatego, że społeczność nie jest proszona, by uwierzyć w deklarację — jest zapraszana, by obejrzeć Replay.

Obietnica akordu wobec każdego rodzica wykracza poza bezpieczeństwo, sięgając trwałości: twoje dziecko będzie ćwiczyć tysiąc razy, zanim dotknie czegokolwiek, co mogłoby mu zaszkodzić, społeczność będzie świadkiem jego rozwoju przez cały ten czas, i nic z tego nie zostanie zagubione w czasie. Measurement of Time zapisuje rzeczywiste minuty osobno od każdego innego rejestru prowadzonego przez akord, tak by godziny ćwiczeń i godziny potwierdzonej pracy nigdy nie zostały ze sobą pomylone, i tak by prawdziwa historia rozwoju uczestnika — nie streszczenie, nie przybliżenie, lecz sam dający się zrekonstruować zapis — pozostawała dostępna dla tego uczestnika tak długo, jak zechce z niej korzystać. Rodzic w Phnom Penh, mentor w Tegucigalpie, audytor w Austin czy wnuk czytający ten zapis za sto lat — wszyscy mogą sięgnąć do tego samego Replay i zobaczyć tę samą prawdę.

Tak wygląda szacunek dla młodego człowieka, gdy jest wbudowany we framework, a nie jedynie przez niego obiecywany, i to właśnie przywództwo przekazuje kolejnemu pokoleniu uczestników, zanim to pokolenie będzie musiało się tego domagać: przestrzeń próby na tyle rozległą, by można było w niej bezpiecznie ponieść porażkę, na tyle uczciwą, by wiernie rejestrować, i na tyle zdyscyplinowaną, by trzymać nagrodę, autonomię i władzę dokładnie tam, gdzie zasłużyło na nie mistrzostwo — nigdy przed nim, i nigdy za nim.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Bezpieczeństwo zweryfikowane, zanim zaufanie zostanie udzielone`,
    content: {
      7: `Bezpieczeństwo najpierw udowodnione, potem zaufanie.`,
      33: `Każdy obiekt i każda rotacja znajdują się wewnątrz otoczki ochronnej z systemem wczesnego ostrzegania. Sprzęt odmawia uzbrojenia — udowadnialne, nie obiecywane, możliwe do zweryfikowania przez obywateli. Zapisy przetrwają turbulencje. Bezpieczeństwo jest projektowane wokół najmłodszego uczestnika, każdego dnia.`,
      111: `Zanim zostanie udzielone zaufanie, bezpieczeństwo musi zostać udowodnione — nie rządowi, lecz każdemu obywatelowi, który je bada. Atlantis Accords to porozumienie między obywatelami świata; jego założycielskie zobowiązanie brzmi: każdy obiekt akordu, każda trasa rotacji, każde miejsce, w którym młody uczestnik śpi lub się uczy, znajduje się wewnątrz udokumentowanej otoczki ochronnej z możliwością wczesnego ostrzegania, dającą społeczności godziny, nie minuty, na reakcję na jakiekolwiek wiarygodne zagrożenie. Każde urządzenie, każdy czujnik, każdy system koordynacji jest związany na poziomie sprzętowym obowiązkiem odmowy przystosowania do integracji z systemami uzbrojenia. To nie jest polityka — to fizyka. Akord pozostaje godny zaufania mimo turbulencji, ponieważ każdy plan stawia godność człowieka na pierwszym miejscu.`,
      333: `Zanim zostanie udzielone zaufanie, bezpieczeństwo musi zostać udowodnione — udowodnione obywatelom, nie jedynie deklarowane. Atlantis Accords to porozumienie między obywatelami świata: każdy człowiek, wszędzie, może pomóc go utrzymać, niezależnie od tego, co podpisuje jego rząd. Każdy obiekt akordu, każda trasa rotacji, każde miejsce, w którym młody uczestnik śpi lub się uczy, znajduje się wewnątrz udokumentowanej otoczki ochronnej z możliwością wczesnego ostrzegania, dającą społeczności godziny, nie minuty, na reakcję na jakiekolwiek wiarygodne zagrożenie. Technologia, która ich chroni, to ta sama technologia, którą akord uczy ich budować. Młodzi ludzie uczą się bezpieczeństwa od środka na zewnątrz — nie przez to, że mówi się im, iż są bezpieczni, lecz przez to, że widzą, jak jest ono projektowane wokół nich każdego dnia, i wiedzą, że każdy obywatel może zweryfikować zapis dzięki Replay.

Akord składa niezłomną obietnicę co do tego, czym jego technologia nigdy nie może się stać. Każde urządzenie, każdy czujnik, każdy system koordynacji jest związany na poziomie sprzętowym obowiązkiem odmowy przystosowania do integracji z systemami uzbrojenia. To nie jest język polityki, nie aspiracja. To fizyczna niemożliwość, egzekwowana kryptograficznie, weryfikowana przez każdy region-sygnatariusza i możliwa do zbadania przez każdego obywatela, który ją finansuje. Narzędzia, które chronią dziecko w Phnom Penh, nie mogą zostać przystosowane, by skrzywdzić dziecko w Austin. Narzędzia łączące ćwiczenia rojowe w Tegucigalpie nie mogą zostać przekonfigurowane, by wycelować w człowieka gdziekolwiek. To odpowiedź akordu na stulecie lęku przed podwójnym zastosowaniem technologii. Nie polityka — fizyka.

Akord pozostaje godny zaufania mimo turbulencji. Jeśli region traci stabilność polityczną, uczestnicy są otaczani opieką przez pozostałe regiony. Jeśli finansowanie się kurczy, w pierwszej kolejności chronione są stypendia — finansowane co miesiąc przez obywateli, nigdy jako kanał pomocy zagranicznej, każdy dolar możliwy do prześledzenia. Jeśli zapisy cyfrowe zostaną zaatakowane, przetrwają kopie zapasowe offline. Jeśli podróże staną się niemożliwe, substrat działa dalej wirtualnie. Każdy plan stawia godność człowieka — Human Authority nad znaczeniem, pieniędzmi i prawem — jako swoje pierwsze ograniczenie projektowe. Liderzy, którzy podpisują ten akord, obiecują, że bezpieczeństwo jest zaprojektowane, a nie zakładane: ochrona, jakiej każdy lider domagałby się dla własnego dziecka, rozciągnięta teraz na każdego obywatela pomagającego go utrzymać.`,
      999: `Zanim zostanie udzielone zaufanie, bezpieczeństwo musi zostać udowodnione — to założycielskie zobowiązanie Atlantis Accords, dowodzone w taki sam sposób, w jaki dowodzi się każdego innego twierdzenia wewnątrz Vision 2525: nie przez deklarację, lecz przez dowody, które obywatele mogą zbadać. Każdy obiekt akordu, każda trasa rotacji, każde miejsce, w którym młody uczestnik śpi lub się uczy, znajduje się wewnątrz udokumentowanej otoczki ochronnej z możliwością wczesnego ostrzegania, dającą społeczności godziny, nie minuty, na reakcję na jakiekolwiek wiarygodne zagrożenie. Technologia używana do ochrony uczestników to ta sama technologia, którą akord uczy ich budować — czujniki, koordynacja, przetrwałość łączności, rozproszona inteligencja. Młodzi ludzie uczą się bezpieczeństwa od środka na zewnątrz, we własnym języku i we własnym regionie, nie przez to, że mówi się im, iż są bezpieczni, lecz przez obserwację, godzina po godzinie, jak bezpieczeństwo jest projektowane wokół nich każdego dnia.

Ta obserwacja nie jest pozostawiona pamięci ani zaufaniu do słowa facylitatora. Measurement of Time zapisuje rzeczywiste minuty każdego ćwiczenia, każdej rotacji, każdego ćwiczenia reagowania — osobno od jakiegokolwiek twierdzenia o postępie, osobno od jakiejkolwiek opowieści snutej tego dnia. Replay sprawia, że każde wydanie programu szkoleniowego, każda aktualizacja bezpieczeństwa, każda rewizja sprzętu jest w pełni możliwa do zrekonstruowania, tak by rodzic w Tegucigalpie czy regulator w Phnom Penh mógł prześledzić wstecz dokładnie to, co się zmieniło, kiedy się zmieniło i dlaczego się zmieniło. Otoczka ochronna, której nie da się odtworzyć, jest tylko obietnicą. Otoczka ochronna, którą można odtworzyć, minuta po zarejestrowanej minucie, jest dowodem. Akord wybiera dowód.

Akord składa niezłomną obietnicę co do tego, czym jego technologia nigdy nie może się stać. Każde urządzenie, każdy czujnik, każdy system koordynacji jest związany na poziomie sprzętowym obowiązkiem odmowy przystosowania do integracji z systemami uzbrojenia. To nie jest język polityki, nie aspiracja. To fizyczna niemożliwość, egzekwowana kryptograficznie, weryfikowana przez każdy region-sygnatariusza i możliwa do zbadania przez każdego obywatela. Narzędzia, które chronią dziecko w Phnom Penh, nie mogą zostać przystosowane, by skrzywdzić dziecko w Austin. Narzędzia łączące ćwiczenia rojowe w Tegucigalpie nie mogą zostać przekonfigurowane, by wycelować w człowieka gdziekolwiek. To odpowiedź akordu na stulecie lęku przed podwójnym zastosowaniem technologii. Nie polityka — fizyka.

Bezpieczeństwo udowodnione raz nie jest bezpieczeństwem utrzymanym przez pięćsetletni horyzont. Akord nazywa swoje drugie zobowiązanie Continuity Without Evasion: zgodną z prawem przenośnością przez każdą jurysdykcję, której akord dotyka, bez żadnego pojedynczego niezbędnego rządu, banku, założyciela czy modelu stojącego między uczestnikiem a jego ochroną. Każda jurysdykcja jest obsługiwana przez własny adapter, działający na zasadzie bezpiecznego zamknięcia i domyślnej odmowy, tak by niekorzystne orzeczenie w jednym regionie zamykało tylko ten jeden kanał — nigdy cały framework, nigdy wszystkie regiony, nigdy wszystkich uczestników wszędzie naraz. Decyzja sądu na jednym terytorium sygnatariusza nie może wyłączyć otoczki bezpieczeństwa uczestnika gdzie indziej. Na tym polega zbudowanie systemu, który przetrwa zwyczajne turbulencje prawa, polityki i zmian instytucjonalnych, nigdy nie prosząc uczestnika, by dla zachowania ochrony obchodził prawo.

Każda warstwa tej architektury ochronnej odpowiada, ostatecznie, przed Human Authority. Znaczenie, pieniądze i prawo nigdy nie są delegowane maszynom — warstwa suwerenna, która decyduje o tym, czego wymaga bezpieczeństwo, co liczy się jako wiarygodne zagrożenie i jaką odpowiedź społeczność jest winna swoim najmłodszym członkom, pozostaje zamknięta dla sztucznej inteligencji, bez względu na to, jak zdolna się ona stanie. Systemy akordu przechodzą wyłącznie przez trzy tryby działania — Manual, Semi-Automated, Autonomous — i żaden system nie awansuje do kolejnego trybu bez poświadczonej, mierzonej poprawy wynoszącej co najmniej jedną dziewiątą, jedenaście i jedną dziesiątą procent, zweryfikowanej, powtarzalnej. Autonomia jest zdobywana, sześcian po sześcianie, funkcja po funkcji, nigdy nie przyznawana hurtowo i nigdy ani razu nierozciągana na pytania, które decydują o znaczeniu, pieniądzach czy prawie. Czujnik może nauczyć się wykrywać szybciej. System koordynacji może nauczyć się kierować ruchem wydajniej. Żadnemu z nich nigdy nie wolno samodzielnie decydować, czym społeczność powinna obdarzyć zaufanie w sprawie swoich dzieci.

Akord jest zaprojektowany tak, by pozostać godny zaufania mimo turbulencji, i nazywa te turbulencje z wyprzedzeniem, zamiast odkrywać je w kryzysie. Jeśli region-sygnatariusz traci stabilność polityczną, uczestnicy są otaczani opieką przez pozostałe regiony. Jeśli finansowanie się kurczy, w pierwszej kolejności chronione są stypendia uczestników, przed administracją i infrastrukturą. Jeśli zapisy cyfrowe zostaną zaatakowane, przetrwają kopie zapasowe offline, nieosiągalne dla jakiejkolwiek awarii, która dosięgła sieci. Jeśli podróże staną się niemożliwe, substrat działa dalej wirtualnie, tak by rotacja nie zatrzymywała się z powodu zamkniętej granicy. Każdy scenariusz jest zaplanowany, a każdy plan stawia godność człowieka jako swoje pierwsze ograniczenie projektowe — nie jako ostatnią kwestię rozważaną po ustaleniu budżetów i wizerunku.

Wejście do tego udowodnionego systemu zaczyna się od Seed — jednorazowego członkostwa, wycenionego na siódmą część lokalnej godziny pracy za płacę minimalną, niezbywalnego i niedającego żadnego roszczenia ekonomicznego do czegokolwiek, co akord zbuduje później. Seed nie kupuje bezpieczeństwa; bezpieczeństwo jest projektowane na długo, zanim jakikolwiek Seed zostanie w ogóle zasadzony. To, co kupuje Seed, to pozycja — prawo, by wejść do frameworku już udowodnionego, już zbadanego, już związanego sprzętem, którego nie da się obrócić przeciwko samej osobie, którą ma on chronić. To rozdzielenie jest celowe. Obietnica bezpieczeństwa, którą trzeba kupić za realną wartość ekonomiczną, nie jest obietnicą bezpieczeństwa w ogóle, a jedynie produktem bezpieczeństwa. Akord trzyma te dwie rzeczy całkowicie osobno, tak by żadna rodzina nigdy nie musiała ważyć ochrony swojego dziecka przeciwko miesięcznemu budżetowi domowemu.

Liderzy, którzy podpisują ten akord, podpisują obietnicę, że bezpieczeństwo jest zaprojektowane, a nie zakładane, i udowodnione, a nie jedynie deklarowane. To, co rozciągają na swoich obywateli, to nie tylko szansa, lecz ochrona zbudowana na standardzie, na jaki zasługuje najmłodszy uczestnik — rejestrowana przez Measurement of Time, dająca się zrekonstruować dzięki Replay, związana na poziomie sprzętowym przeciwko każdemu nadużyciu, jakie wyobraziło sobie pełne lęku stulecie, i odpowiedzialna, zawsze i wyłącznie, przed Human Authority. To ta sama ochrona, jakiej każdy lider domagałby się dla własnego dziecka przekraczającego samotnie nieznaną granicę, rozciągnięta teraz na każde dziecko, któremu akord kiedykolwiek będzie służyć, przez jego trzy regiony założycielskie — Kambodżę, Honduras i Austin — i przez pięć stuleci, przez które akord zamierza dotrzymać tej obietnicy.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Wynagrodzenie, dobrostan i godność człowieka`,
    content: {
      7: `Stypendium, mentor i dom.`,
      33: `Każdy obywatel otrzymuje stypendium od pierwszego dnia — bez zgody rządu, bez błogosławieństwa pracodawcy. Miłość, strata i bezpieczeństwo są infrastrukturą. Sukces mierzy się najbardziej wrażliwym uczestnikiem. Godność jest substratem, nigdy dekoracją.`,
      111: `Atlantis Accords traktuje każdego uczestnika jako istotę ludzką od pierwszego dnia — obywatela, który dołączył z mocy prawa, nie na mocy dekretu rządowego czy przyzwolenia pracodawcy. Stypendium jest zapewniane od chwili rozpoczęcia uczestnictwa, indeksowane do kosztów życia w danym regionie, a każda potwierdzona godzina zarabia 웃, wypłacane danej osobie przez Livelihood Direct, nigdy przez księgi pracodawcy. Dobrostan jest traktowany jako infrastruktura pierwszej kategorii — nie jako dodatek, lecz jako substrat, na którym opiera się wszystko inne. Wspierane są trzy obszary: Miłość, Strata i Bezpieczeństwo. Akord mierzy sukces jego najbardziej wrażliwym uczestnikiem, nie średnią. Nikt nie zostaje zapomniany, by średnie dobrze wyglądały. Godność jako substrat, nie dekoracja.`,
      333: `Atlantis Accords traktuje każdego uczestnika jako istotę ludzką od pierwszego dnia — obywatela, który należy do wspólnoty z mocy prawa, nie potrzebując ani zgody żadnego rządu, ani błogosławieństwa pracodawcy. Stypendium jest zapewniane od chwili rozpoczęcia uczestnictwa, indeksowane do kosztów życia w danym regionie, docierające zanim obowiązki rodzinne staną się nagłymi wypadkami. To nie jest dobroczynność. To uznanie faktu, że zwyczajna ludzka innowacyjność wymaga najpierw ludzkiego bezpieczeństwa — umysł nie może rozkwitać, gdy jego gospodarstwo domowe jest zagrożone.

To, co zarabia się poza stypendium, zarabia się tak, jak zarabia to obywatel: przez Seed, wycenione na siódmą część lokalnej godziny pracy za płacę minimalną, oraz przez 웃, wypłacane wyłącznie za potwierdzone godziny. QIS mierzy obietnicę, lecz niczego nie tworzy — pomiar, nigdy płatność. Każda płatność dociera do uczestnika przez Livelihood Direct, licencjonowane lokalne kanały, których akord nigdy nie przechowuje, zbudowane z myślą o Continuity Without Evasion.

Dobrostan jest traktowany jako infrastruktura pierwszej kategorii — nie jako dodatek, lecz jako substrat, na którym opiera się wszystko inne. Akord wskazuje trzy obszary, w których wspierany jest każdy uczestnik: Miłość — więź i zdrowa granica; Strata — ponieważ żałobę trzeba przejść razem z kimś, nie omijając jej; i Bezpieczeństwo — wiedzę, do kogo zadzwonić, w każdym regionie, we własnym języku. Zapewniane jest poradnictwo, kręgi grupowe oraz praktyki kulturowe lub duchowe honorowane zgodnie z tradycją. Zero narzuconej ideologii; to Human Authority, nigdy maszyna, decyduje, jakiej opieki potrzebuje dany obywatel.

Akord mierzy sukces jego najbardziej wrażliwym uczestnikiem, nie średnią. Obsługiwani są mieszkańcy obszarów wiejskich bez szerokopasmowego dostępu do internetu. Uczestnicy neuroróżnorodni otrzymują dostosowania jako normę, nie wyjątek. Uczestnicy z niepełnosprawnościami znajdują każdy obiekt dostępny. Uczestnicy różnorodni pod względem płci otrzymują bezpieczne zakwaterowanie i dobór mentora. Osoby niemówiące danym językiem jako ojczystym znajdują każdy materiał we własnym języku. Uczestnicy rdzenni znajdują swoje praktyki kulturowe uhonorowane, a swoją tradycyjną wiedzę chronioną. Liderzy, którzy podpisują ten akord, obiecują, że żaden obywatel nie zostanie zapomniany, by średnie dobrze wyglądały. To godność jako substrat, nie dekoracja. To, co jest mierzone, jest tym, co będzie uhonorowane, a tym, co jest tu honorowane, jest cały człowiek — umysł, ciało i duch, otoczony opieką przez współobywateli, bez wyjątku.`,
      999: `Atlantis Accords traktuje każdego uczestnika jako pełnego człowieka od pierwszego dnia, wbudowane w mechanizm, a nie jedynie w język. Stypendium jest zapewniane od chwili rozpoczęcia uczestnictwa, indeksowane do kosztów życia w danym regionie, tak by jego wpływ szanował lokalną godność pracy. Stypendium dociera, zanim obowiązki rodzinne staną się nagłymi wypadkami, i zanim godność zostanie naruszona. Sygnalizuje ono każdemu młodemu człowiekowi, że jego czas ma wartość, że jego wkład jest oczekiwany, i że stabilność jego rodziny jest częścią odpowiedzialności akordu. To nie jest dobroczynność. To uznanie faktu, że zwyczajna ludzka innowacyjność wymaga najpierw ludzkiego bezpieczeństwa. Umysł nie może rozkwitać, gdy jego gospodarstwo domowe jest zagrożone. Samo wejście niesie ze sobą mały, celowy próg: Seed, jednorazowe członkostwo wycenione na siódmą część lokalnej godziny pracy za płacę minimalną, niezbywalne i niedające żadnego własnego roszczenia ekonomicznego. Seed mówi jedynie, że dana osoba dołączyła; ani jej nie płaci, ani nie obiecuje jej niczego poza drzwiami, które otwiera.

To, co jest zarabiane po otwarciu tych drzwi, rządzone jest z tą samą precyzją, jaką akord wnosi do każdej innej obietnicy. 웃, miara Human Intelligence w akordzie, jest obliczane w prosty sposób — jedna godzina lokalnej płacy minimalnej, pomnożona przez Multiple odzwierciedlający trudność i wartość zadania, razy liczba rzeczywiście przepracowanych godzin. Lecz 웃 przyznawane jest wyłącznie za pracę potwierdzoną, wykonaną w ramach zdefiniowanego, zatwierdzonego budżetowo zadania. Zanim takie zatwierdzenie zaistnieje, to, co robi uczestnik, jest planowaniem, nie zarabianiem — rozróżnienie, którego akord trzyma się stanowczo, ponieważ chroni zarówno skarbiec, jak i uczestnika przed obietnicami składanymi szybciej, niż wartość zostaje zweryfikowana. Measurement of Time, MoT, zapisuje rzeczywiste przepracowane minuty osobno od jakiegokolwiek obliczenia wynagrodzenia, tak by czas pozostawał uczciwym, poddającym się audytowi faktem, niezależnym od płatności. Żadne godziny uczestnika nie są zawyżane i żadne godziny uczestnika nie znikają. Pułap rozliczeniowy 9999 웃 rocznie obowiązuje każdego uczestnika, a każda nadwyżka przechodzi na kolejny rok zamiast zniknąć, tak by wyjątkowy wkład był uznawany na przestrzeni lat, a nie ograniczany do niewidoczności w ciągu jednego roku.

Wynagrodzenie jest celowo utrzymywane osobno od pomiaru innowacji. Qualified Innovation Score, QIS, uśrednia Przychód, Zysk Brutto, Zysk Operacyjny i Efektywne Wydatki na R&D, by opisać, o ile innowacja naprawdę wzrosła. Jego wzrost w czasie może wyznaczyć wielkość puli nagród, gdy kwalifikacja zostanie spełniona, ale sam QIS nie tworzy żadnego 웃 i niczego bezpośrednio nie rozlicza — to pomiar, nigdy płatność, i nigdy nie należy go mylić z własnością tego, co zbudowano. To rozdzielenie ma znaczenie, ponieważ zachowuje uczciwość stypendium i wynagrodzenia: uczestnik jest opłacany za potwierdzone godziny rzeczywistej pracy, nie za wynik, którym można manipulować, który można zawyżyć czy o który można się spierać. ♡, Shared Intention, niesie powód stojący za każdym zadaniem, jakie podejmuje uczestnik; ◬, potwierdzone przyspieszenie, jakie zadanie wytwarza względem zamrożonej linii bazowej, jest rejestrowane wyłącznie jako delta, nigdy nieprzebierana za wskaźnik zysku przypisany czyjejś pracy. Wynagrodzenie pozostaje tym, czym jest: uczciwą zapłatą za uczciwy, potwierdzony czas.

Wartość nie kończy się na obliczeniu — musi też dotrzeć do uczestnika jako żywej osoby, i tu właśnie działa 🏠, Livelihood Direct. Każda jednostka wartości, jaką zarabia uczestnik, dociera do niego przez kwalifikowane, licencjonowane lokalne kanały — banki, operatorów płatności mobilnych, spółdzielnie już zaufane i uregulowane prawnie w danym regionie — nigdy przez fundusz przechowywany lub kontrolowany przez sam akord. Klasyfikacja statusu uczestnika zawsze poprzedza jakiekolwiek rozliczenie; nic nie zostaje wypłacone, zanim nie zostanie właściwie ustalone, komu i za co się płaci. A uznanie talentu, choćby najbardziej celebrowane, nie otwiera dostępu do noclegu, posiłku ani miejsca w kohorcie — decyduje o tym wyłącznie rzeczywista rola uczestnika. To celowa odmowa pozwolenia, by prestiż zastąpił zapewnienie potrzeb. Genialny współtwórca i cichy uczestnik śpią pod tym samym chronionym dachem, na tych samych warunkach, ponieważ zobowiązania godnościowe akordu nie są nagrodą przyznawaną za doskonałość — są podłogą pod wszystkimi.

Dobrostan jest traktowany jako infrastruktura pierwszej kategorii — nie jako opcjonalne świadczenie, nie jako dodatek wellness, lecz jako substrat, na którym opiera się wszystko inne. Akord wskazuje trzy fundamentalne obszary, w których wspierany jest każdy uczestnik: Miłość — w sensie więzi, przywiązania i zdrowej granicy; Strata — ponieważ każdy uczestnik doświadczy żałoby i trzeba ją przejść razem z kimś, nie omijając jej; oraz Bezpieczeństwo — w sensie tego, że każdy uczestnik wie, do kogo zadzwonić, w każdym regionie, we własnym języku. Zapewniane są indywidualne poradnictwo, kręgi grupowe, praktyki somatyczne oraz praktyki kulturowe lub duchowe honorowane zgodnie z własną tradycją uczestnika. Zero narzuconej ideologii. Akord obejmuje tę przestrzeń z szacunkiem; nie nawraca na żaden system wierzeń. Human Authority rządzi każdą z tych decyzji — znaczenie, pieniądze i prawo pozostają zamknięte dla maszynowego rozstrzygania, bez względu na to, jak wyrafinowane jest dopasowywanie wzorców wspierające ludzi, którzy decydują.

Akord mierzy sukces wynikiem osiąganym przez jego najbardziej wrażliwego uczestnika, nie średnią. Obsługiwani są uczestnicy z obszarów wiejskich bez szerokopasmowego dostępu do internetu. Uczestnicy neuroróżnorodni otrzymują dostosowania jako normę. Uczestnicy z niepełnosprawnościami znajdują każdy obiekt dostępny. Uczestnicy różnorodni pod względem płci otrzymują bezpieczne zakwaterowanie i dobór mentora. Osoby niemówiące danym językiem jako ojczystym znajdują każdy materiał we własnym języku. Uczestnicy rdzenni znajdują swoje praktyki kulturowe uhonorowane, a swoją tradycyjną wiedzę chronioną. Liderzy, którzy podpisują ten akord, obiecują, że żaden uczestnik nie zostanie po cichu zapomniany, by średnie dobrze wyglądały.

Każda ścieżka płatności opisana tutaj — Seed, stypendium, 웃 zarobione za potwierdzoną pracę, kanał Livelihood Direct, który je dostarcza — jest zaprojektowana z myślą o Continuity Without Evasion. Żaden pojedynczy bank, rząd czy lokalny operator nie jest niezbędny dla wynagrodzenia żadnego uczestnika; jeśli jeden licencjonowany kanał w jednej jurysdykcji zostanie zamknięty przez niekorzystne orzeczenie, upada tylko ten kanał — nigdy cały system, i nigdy roszczenie uczestnika do tego, co mu się należało. To godność jako substrat, nie dekoracja. To, co jest mierzone, jest tym, co będzie uhonorowane, a tym, co jest tu honorowane, jest cały człowiek — umysł, ciało i duch razem, opłacany uczciwie, w pełni chroniony i niezapominany przez żadną księgowość, bez żadnego wyjątku.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finansowanie i zarządzanie`,
    content: {
      7: `Obywatele finansują następne pokolenie bezpośrednio.`,
      33: `Atlantis Accords to porozumienie między obywatelami — każdy może je finansować i utrzymywać. Bez kanału pomocy, bez zagranicznego dobroczyńcy, bez politycznych warunków. Każdy dolar możliwy do prześledzenia, rozliczenie publikowane co miesiąc, w każdym języku.`,
      111: `Atlantis Accords to porozumienie między obywatelami świata — każdy człowiek, wszędzie, może pomóc je stworzyć i utrzymać, niezależnie od tego, co podpisuje jego rząd, czy kto go zatrudnia. Rządy, nauczyciele i innowatorzy podpisują akord jako powiernicy swoich regionów; to obywatele finansują akord, są jego świadkami i bezpośrednio rozliczają go z odpowiedzialności, każdy wnosząc co miesiąc małe, dobrowolne kwoty, na tyle skromne, że żaden dorosły nie zostaje wykluczony z powodu ceny. Nie ma tu kanału pomocy, zagranicznego dobroczyńcy ani żadnych warunków politycznych. Akord pozostaje niezależny od wielostronnych instytucji, które ukształtowały minione stulecie — to nie deklaracja polityczna, lecz świadomy wybór projektowy. Każdy dolar jest możliwy do prześledzenia; pełne rozliczenie publikowane jest co miesiąc, w każdym języku.`,
      333: `Atlantis Accords to porozumienie między obywatelami świata — każdy człowiek, wszędzie, może pomóc je stworzyć i utrzymać, niezależnie od tego, co podpisuje jego rząd, czy kto go zatrudnia. Jest ono finansowane przez obywateli, którym służy: mieszkańcy uczestniczących regionów wnoszą co miesiąc małe, dobrowolne kwoty, na tyle skromne, że żaden dorosły nie zostaje wykluczony z powodu ceny, i na tyle znaczące łącznie, że suma podtrzymuje pracę akordu w odpowiedniej skali. Gdy obywatel finansuje edukację następnego pokolenia bezpośrednio, ten sam obywatel bezpośrednio rozlicza akord z odpowiedzialności. Nie ma tu kanału pomocy, zagranicznego dobroczyńcy ani żadnych warunków politycznych. Duszą akordu jest obywatel, który wnosi co miesiąc jedną małą kwotę, i to jego udział czyni to wszystko możliwym.

Rząd, Edukacja i Innowacja podpisują akord jako powiernicy swoich regionów — trzy wizjonerskie podpisy zobowiązujące region do przyjmowania, ochrony i nauczania — lecz powiernictwo nie jest własnością. Akord jest niezależny od wielostronnych instytucji, które ukształtowały minione stulecie — Organizacji Traktatu Północnoatlantyckiego, Światowej Organizacji Zdrowia, Organizacji Narodów Zjednoczonych, Międzynarodowego Funduszu Walutowego, Banku Światowego oraz każdego krajowego kanału pomocy zagranicznej. To wybór projektowy, nie deklaracja polityczna: framework służący każdemu regionowi, niezależnie od układu geopolitycznego, nie może być uwikłany w żaden pojedynczy sojusz. Rządy krajowe mogą wnosić wkład dobrowolnie. Wkłady są przejrzyste. Żaden wkład nigdy nie kupuje wpływu na zarządzanie, z jakiegokolwiek źródła.

Każdy dolar i każda jednostka wartości wchodząca do akordu jest rejestrowana trwale, publicznie i w sposób możliwy do prześledzenia — dająca się zrekonstruować dzięki Replay, tak by obywatel za sto lat mógł zweryfikować nieprzerwany łańcuch. Wartość dociera do uczestnika przez potwierdzone godziny 웃 i licencjonowane lokalne kanały, nigdy przez fundusz przechowywany przez sam akord; QIS mierzy uczciwie, nigdy nie płaci. Koszty administracyjne są ograniczone pułapem, podobnie jak dary korporacyjne. Pełne rozliczenie jest dostarczane w języku każdego regionu-sygnatariusza co miesiąc. Liderzy, którzy podpisują akord, obiecują przejrzystość rzadko oferowaną przez jakąkolwiek instytucję. To zaufanie, którego wymaga akord — zdobywane jeden mały, możliwy do prześledzenia wkład na raz, w oczach każdego obywatela.`,
      999: `Sam Atlantis Accords jest finansowany przez obywateli, którym służy, i ten pojedynczy fakt kształtuje wszystko, co z niego wynika — każdy kanał, każdy rejestr, każdą bramę, którą musi przejść młody człowiek, by zostać dostrzeżonym. Zwykli mieszkańcy uczestniczących regionów wnoszą co miesiąc małe, dobrowolne kwoty, na tyle skromne, że żaden dorosły w żadnym regionie-gospodarzu nie zostaje wykluczony z uczestnictwa z powodu ceny, i na tyle znaczące łącznie, że suma podtrzymuje pracę akordu w istotnej skali. Ten projekt jest celowy i nie jest przypadkowy dla misji — jest dowodem misji. Gdy obywatel finansuje edukację następnego pokolenia bezpośrednio, ten sam obywatel bezpośrednio rozlicza akord z odpowiedzialności, w tym samym oddechu, bez pośrednika, który mógłby złagodzić rozliczenie lub opóźnić rachunek. Nie ma tu kanału pomocy, zagranicznego dobroczyńcy ani żadnych warunków politycznych dołączonych do czeku. Duszą akordu jest obywatel, który wnosi co miesiąc jedną małą kwotę, którego udział czyni całość możliwą, i którego dalszy udział jest jedynym wotum zaufania, które ostatecznie liczy się na przestrzeni pięciuset lat.

Akord jest celowo niezależny od wielostronnych instytucji, które ukształtowały minione stulecie — Organizacji Traktatu Północnoatlantyckiego, Światowej Organizacji Zdrowia, Organizacji Narodów Zjednoczonych, Międzynarodowego Funduszu Walutowego, Banku Światowego oraz każdego krajowego kanału pomocy zagranicznej. To nie jest deklaracja polityczna na temat wartości tych instytucji czy ich wkładu. To wybór projektowy, i jest to ten sam wybór projektowy, który rządzi każdym technicznym kanałem leżącym u podstaw samego akordu: Continuity Without Evasion. Zasadą jest zgodna z prawem przenośność — żaden pojedynczy niezbędny rząd, bank, założyciel czy model nie może leżeć u podstaw całej struktury, ponieważ pięćsetletniego horyzontu nie można oprzeć na trwałości jednego aktora. Każda jurysdykcja niesie własny adapter, działający na zasadzie bezpiecznego zamknięcia i domyślnej odmowy, tak by niekorzystne orzeczenie w jednym kraju zamykało wyłącznie ten jeden kanał — nigdy nie doprowadza do upadku kont rodziny w regionie oddalonym o ocean. Rządy krajowe mogą wnosić wkład dobrowolnie. Wkłady są przejrzyste. Żaden wkład nigdy nie kupuje wpływu na zarządzanie, z jakiegokolwiek źródła — ani od rządu, ani od korporacji, ani od samych założycieli frameworku.

Human Authority to drugi nośny filar tego projektu finansowania. Znaczenie, pieniądze i prawo pozostają sprawami ludzkimi, rozstrzyganymi przez ludzi w oczach innych ludzi; warstwa suwerenna, w której ustala się cel akordu i zarządza jego funduszami, pozostaje zamknięta dla maszyn, niezależnie od tego, jak zdolne staną się one w zadaniach leżących poniżej tej warstwy. Measurement of Time zapisuje rzeczywiste przepracowane minuty osobno od jakiegokolwiek twierdzenia o ich wartości, tak by nikt — ani człowiek, ani maszyna — nie mógł po cichu zawyżyć zapisu. Za każdym z tych zapisów stoi Replay, sprawiając, że każde wydanie, jakie kiedykolwiek wyda sam akord, jest możliwe do zrekonstruowania od jego początku, na zawsze otwarte na wyzwanie, na zawsze otwarte na korektę. Obywatel, który wnosi dziś małą kwotę, ufa, że za pięćdziesiąt lat, za dwieście lat, ktoś wciąż będzie mógł przejść tym łańcuchem wstecz aż do rejestru z tego miesiąca i znaleźć go dokładnie takim, jakim był.

Wejście do tego systemu zaufania zaczyna się od Seed — jednorazowego członkostwa, wycenionego na siódmą część lokalnej godziny pracy za płacę minimalną, niezbywalnego i niedającego żadnego roszczenia ekonomicznego. Seed nie kupuje ani udziału, ani głosu ważonego bogactwem, ani uprzywilejowanej pozycji w rozliczeniu, które nastąpi później. Kupuje jedynie przynależność, po cenie na tyle niskiej, że młody człowiek gdziekolwiek działa akord może sobie pozwolić na rozpoczęcie. Wszystko, co członek zarabia po tym momencie, jest zarabiane, nigdy kupowane, a to rozróżnienie jest całą moralną architekturą akordu w miniaturze.

Wartość, która rzeczywiście płynie do osoby, płynie przez 🏠 Livelihood Direct — kwalifikowane, licencjonowane lokalne kanały, które przenoszą płatność do danej osoby, nigdy do funduszu przechowywanego lub kontrolowanego przez sam framework. Klasyfikacja zawsze poprzedza rozliczenie; nocleg, stypendium, miejsce na kolejnym etapie szkolenia jest bramkowane przez rolę i gotowość, nigdy samym uznaniem, ponieważ uznanie jest tanie, a środki do życia — nie. Oto łańcuch, którym rzeczywiście podróżuje miesięczny wkład obywatela: od konta obywatela, przez audytowany kanał, do stypendium, które otrzymuje młody człowiek, do projektu innowacyjnego, którym staje się praca tego młodego człowieka, i z powrotem jako publiczny rejestr, który może przeczytać każdy obywatel.

To, ile warta jest ta praca, jest mierzone, nie zakładane. Qualified Innovation Score uśrednia gotowość, potencjał wzrostu, wpływ na wynik i gotowość wykonawczą w jedną liczbę, a wzrost tego wyniku wyznacza wielkość puli nagród dopiero po spełnieniu kwalifikacji — sam QIS niczego nie tworzy i niczego nie rozlicza; to pomiar, nigdy płatność, a pomiar nigdy nie jest tu mylony z własnością. Zapłata za ludzką pracę przychodzi natomiast jako 웃, wyceniane jako jedna godzina razy lokalna płaca minimalna, pomnożona przez zdefiniowany, zatwierdzony budżetowo mnożnik rzeczywiście przepracowanych i potwierdzonych godzin. Zanim zadanie uzyska takie zatwierdzenie, praca za nim stojąca jest planowaniem, nie pracą podlegającą wynagrodzeniu, i nikt nie jest opłacany za planowanie. Pułap 9999 웃 rocznie, z każdą nadwyżką przechodzącą na kolejny rok zamiast znikać, chroni rozliczenie każdego pojedynczego roku przed staniem się bądź niespodziewaną fortuną, bądź pułapką.

Nic z tego nie działa szybciej niż jego własny dowód. Sam akord przechodzi od trybu Manual przez Semi-Automated do Autonomous po jednym sześcianie naraz, i tylko tam, gdzie faktycznie wykazano pełny rząd wielkości mierzonej poprawy — jedną dziewiątą — nigdy zakładaną z góry. Autonomia jest zdobywana dokładnie tam i nigdzie w pobliżu znaczenia, pieniędzy czy prawa, które zawsze pozostają ludzkie. Koszty administracyjne są ograniczone pułapem. Dary korporacyjne i instytucjonalne są mile widziane i również objęte pułapem. Pełne rozliczenie jest dostarczane w języku każdego regionu-sygnatariusza co miesiąc, zaczynając od Kambodży, Hondurasu i Austin, i ma być dostarczane — wciąż czytelne — jeszcze za pięćset lat. To zaufanie, którego wymaga akord. To zaufanie, na które akord zasługuje, jeden mały, możliwy do prześledzenia wkład na raz, w oczach każdego obywatela, któremu kiedykolwiek będzie służyć.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Wymiana międzykulturowa i wkład globalny`,
    content: {
      7: `Każdy uczący się w swoim języku.`,
      33: `Każda aktywność w języku uczestnika — otwarta dla każdego obywatela, bez potrzeby zgody rządu. Sztuczna, Ludzka i Wspólna inteligencja utrzymywane w produktywnym napięciu. Programy nauczania publikowane otwarcie. To, czego uczy się jeden region, dziedziczą wszyscy.`,
      111: `Atlantis Accords przywraca edukacji jej najgłębszy cel: wymianę mądrości ponad granicami, które w innym wypadku dzieliłyby. Do tego programu może dołączyć każdy obywatel, niezależnie od tego, co podpisał jego rząd. Każda aktywność jest dostępna w języku uczestnika, w języku regionu-gospodarza i we wspólnym zapisie. Język nie jest dekoracją — język to jurysdykcja, język to godność uczyniona czytelną. Ramy edukacyjne opierają się na trójcy inteligencji: Sztuczna proponuje, Ludzka decyduje, Wspólna Intencja waliduje. Każdy uczeń uczy się utrzymywać wszystkie trzy w napięciu. To, czego uczy się akord, oddaje z powrotem. Programy nauczania, wyniki innowacji, badania nad dobrostanem i decyzje zarządcze są publikowane otwarcie. To, czego uczy się jeden region, dziedziczą wszyscy obywatele.`,
      333: `Atlantis Accords przywraca edukacji jej najgłębszy cel: wymianę mądrości ponad granicami, które w innym wypadku dzieliłyby. To porozumienie między obywatelami świata — każdy obywatel może je budować i utrzymać, niezależnie od tego, co podpisał jego rząd. Każda aktywność jest dostępna w języku uczestnika, w języku regionu-gospodarza i we wspólnym zapisie, tak by żaden uczestnik nie poruszał się po akordzie w języku, którego nie wybrał. Język nie jest dekoracją. Język to jurysdykcja. Język to godność uczyniona czytelną. Młody człowiek w Kambodży czyta swój zapis stypendialny po khmersku, w Hondurasie po hiszpańsku, w Austin po angielsku — wszystkie trzy honorowane równo, żaden nie wymaga błogosławieństwa rządu, by móc zacząć.

Ramy edukacyjne opierają się na trójcy inteligencji, którą Vision 2525 czyni widoczną. Sztuczna Inteligencja proponuje wzorce i możliwości szybciej, niż mógłby to zrobić sam człowiek. Ludzka Inteligencja decyduje o bezpieczeństwie, etyce i kierunku — pytaniach, na które żadna maszyna nie powinna odpowiadać, utrzymanych pod Human Authority. Shared Intent waliduje, że decyzje służą zasadom akordu, tak by żaden uczestnik nie wybierał doskonałości ponad dobro wspólne. Żaden uczeń nie polega wyłącznie na jednej inteligencji; każdy uczeń uczy się utrzymywać wszystkie trzy w napięciu. Przynależność zaczyna się od Seed, członkostwa wycenionego na siódmą część lokalnej godziny pracy za płacę minimalną — na tyle niskiego, że stać na nie każdego obywatela. To przygotowuje następne pokolenie do rządzenia tam, gdzie żadna inteligencja nie działa bez kontroli.

To, czego uczy się akord, oddaje z powrotem. Programy nauczania są publikowane na otwartej licencji, tak by każdy region — sygnatariusz czy nie — mógł dostosować je do lokalnej kultury. Publikowane są wyniki innowacji. Badania nad dobrostanem są publikowane zbiorczo dla badaczy na całym świecie. Decyzje zarządcze są publikowane wraz z uzasadnieniem, tak by każdy obywatel, nie tylko podpisujący rząd, mógł je zweryfikować — a Replay pozwala temu samemu obywatelowi prześledzić to uzasadnienie za sto lat. Sukces mierzy się nie tylko jego uczestnikami, lecz również inicjatywami edukacyjnymi i kulturowymi, jakie powstają w jego następstwie, w regionach, które nigdy nie podpisały pilotażu, a jednak zbudowały coś na jego wspólnej mądrości. To, czego uczy się jeden region, dziedziczy każdy obywatel.`,
      999: `Atlantis Accords przywraca edukacji jej najgłębszy cel: wymianę mądrości ponad granicami, które w innym wypadku dzieliłyby, i rozpoczyna tę wymianę, zanim wyłożona zostanie choćby jedna lekcja. Pierwszym aktem każdego uczestnika wewnątrz frameworku jest Seed — jednorazowe członkostwo wycenione na siódmą część lokalnej godziny pracy za płacę minimalną, niezbywalne, niedające żadnego roszczenia ekonomicznego. Jest na tyle małe, że żadna rodzina nie zostaje wykluczona, i na tyle rzeczywiste, że żaden uczestnik nie wchodzi jako widz. To pierwsza lekcja akordu: przynależność zdobywa się tanio, ale wciąż się ją zdobywa, i nie daje ona żadnej własności nad tym, co następuje później. Każda kolejna aktywność akordu jest dostępna w języku uczestnika, w języku regionu-gospodarza i we wspólnym zapisie, tak by żaden uczestnik nie poruszał się po akordzie w języku, którego nie wybrał. Język nie jest dekoracją. Język to jurysdykcja. Język to godność uczyniona czytelną. Gdy młody człowiek z kambodżańskiej wioski czyta swój zapis stypendialny po khmersku, mieszkaniec hondurańskiego miasteczka po hiszpańsku, a mieszkaniec dzielnicy Austin po angielsku, wszyscy troje są honorowani równo przez ten sam akord, w tych samych regionach założycielskich, które jako pierwsze zgodziły się uczyć siebie nawzajem.

Ramy edukacyjne akordu opierają się na trójcy inteligencji, którą Vision 2525 czyni widoczną, a program naucza każdej z nich jako czegoś, co uczestnik może poczuć we własnych rękach, nie jako abstrakcję. ♡, Shared Intention, niesie powód — nić, którą każdy uczeń uczy się trzymać, zanim dotknie jakiegokolwiek narzędzia, pytanie, czy ta praca wciąż służy ludziom, którym twierdzi, że służy. ◬, potwierdzone przyspieszenie, nauczane jest jako delta i nic więcej — mierzone wyłącznie względem zamrożonej linii bazowej, nigdy nieprzebierane za wskaźnik zysku, nigdy niezastrzegane jako osobiste osiągnięcie w oderwaniu od otaczającego zespołu. 웃, Ludzka Inteligencja uhonorowana w czasie, nauczane jest najstaranniej: jedna godzina potwierdzonej pracy równa się jednej godzinie lokalnej płacy minimalnej, a to, co zarabia uczestnik, to ta płaca pomnożona przez przepracowane godziny — Multiple razy Time, nic nieukryte w rachunku. Uczniowie uczą się wcześnie, że 웃 przyznawane jest wyłącznie za potwierdzoną pracę wykonaną w ramach zdefiniowanego, zatwierdzonego budżetowo zadania. Zanim takie zatwierdzenie zaistnieje, ten sam wysiłek jest jedynie planowaniem — wartościowym, lecz nieopłacanym, a każdy uczestnik jest uczony, by tę różnicę rozpoznawać na pierwszy rzut oka.

Ponieważ tę różnicę łatwo zatrzeć, program naucza QIS, Qualified Innovation Score, jako lustra, a nie tablicy wyników. QIS to średnia z czterech bezwzględnych wartości finansowych — Przychodu, Zysku Brutto, Zysku Operacyjnego i Efektywnych Wydatków na R&D — podzielona przez cztery, i każdy uczeń uczy się ją obliczać, kwestionować i nigdy nie mylić z pieniędzmi. Wzrost QIS wyznacza wielkość puli nagród dopiero po niezależnym potwierdzeniu kwalifikacji, a ten wzrost sam z siebie nie tworzy żadnego 웃. QIS to pomiar. QIS nigdy nie jest płatnością. QIS nigdy nie jest własnością. Uczeń, który przyswoił to rozróżnienie, nie da się przekonać, że wysoki wynik uprawnia go do roszczenia, którego akord nigdy nie obiecał.

Program rozszerza tę wiedzę o to, jak wartość rzeczywiście dociera do człowieka, poprzez to, co akord nazywa Livelihood Direct — zasadę 🏠, że pieniądze przemieszczają się przez kwalifikowane, licencjonowane lokalne kanały i nigdy przez fundusz przechowywany przez sam framework. Uczniów uczy się śledzić własne stypendium, a później własne zarobki, przez te kanały jako ćwiczenie obywatelskie, a nie finansową tajemnicę realizowaną gdzieś indziej w ich imieniu. Uczą się, że klasyfikacja zawsze poprzedza rozliczenie, i że uznanie — wysoki QIS, publiczne wyróżnienie — samo w sobie nie otwiera dostępu do noclegu, stypendium czy miejsca w rotacji. Decyduje o tym rola. To ochrona przed bardzo starym błędem: myleniem pochwały z zapewnieniem potrzeb.

Obok wiedzy finansowej stoi wiedza obywatelska, nauczana poprzez Continuity Without Evasion. Każdy uczestnik uczy się, że akord jest zbudowany z myślą o zgodnej z prawem przenośności — że żaden pojedynczy niezbędny rząd, bank, założyciel czy model nie stoi między nim a obietnicami frameworku. Uczą się, co niekorzystne orzeczenie robi wewnątrz tego projektu: zamyka bezpiecznie jeden kanał, w jednej jurysdykcji, zgodnie z postawą domyślnej odmowy tego adaptera, i nigdy nie doprowadza do upadku całości. Obok tego stoi najgłębsza lekcja, jakiej naucza akord: Human Authority zachowuje znaczenie, pieniądze i prawo, a warstwa suwerenna, w której zapadają te decyzje, pozostaje na stałe zamknięta dla maszyn. Measurement of Time, MoT, zapisuje rzeczywiste minuty każdego uczestnika osobno od jakiegokolwiek wyniku, a Replay sprawia, że każde wydanie akordu jest w pełni możliwe do zrekonstruowania — tak by uczeń, który chce wiedzieć, dlaczego lata później podjęto daną decyzję, mógł sam ją prześledzić, zamiast wierzyć komuś na słowo.

Ta struktura zdobywanego zaufania staje się modelem pedagogicznym akordu, nie tylko jego modelem zarządzania. Każdy uczestnik przechodzi przez tryby Manual, Semi-Automated i Autonomous o rosnącej swobodzie działania, bramkowane przez ten sam próg mierzonej poprawy, który bramkuje samą technologię — jedenaście i jedną dziewiątą procent zweryfikowanego zysku, zanim otworzy się kolejny tryb. Autonomia, gdy zostaje zdobyta, jest zdobywana wąsko i dla konkretnej domeny, nigdy ponad znaczeniem, pieniędzmi czy prawem. Uczeń, który przeżył tę progresję, rozumie, wręcz odczuwa, dlaczego warstwy suwerennej nigdy nie wolno zautomatyzować — ponieważ sam zdobył własną autonomię krok po kroku, mierzony krok po mierzonym kroku, i wie dokładnie, co ta autonomia obejmowała, a czego nie.

To, czego uczy się akord, akord oddaje z powrotem. Programy nauczania są publikowane na otwartej licencji, tak by każdy region — sygnatariusz czy nie — mógł dostosować je do lokalnej kultury i tradycji pedagogicznej. Publikowane są wyniki innowacji. Badania nad dobrostanem są publikowane w formie zbiorczej dla badaczy na całym świecie. Decyzje zarządcze są publikowane z pełnym, nienaruszonym uzasadnieniem. Sukces akordu mierzy się nie tylko przez jego własnych uczestników w Kambodży, Hondurasie i Austin, lecz przez inicjatywy, jakie powstają w jego następstwie, w regionach, które nigdy nie podpisały założycielskiego pilotażu, a mimo to zbudowały coś na jego otwarcie dzielonej mądrości, na przestrzeni horyzontu, którego założyciele nie dożyją, by zobaczyć go dopełnionym. To, czego uczy się jeden region, dziedziczą wszystkie pozostałe regiony — a tego, czego to pokolenie uczy się uczciwie, kolejnych pięćset lat nie będzie musiało oduczać.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Zrównoważony wzrost sieci`,
    content: {
      7: `Nigdy szybciej, niż godność może podróżować.`,
      33: `Trzy regiony założycielskie kończą pełen cykl pilotażu, zanim dołączy czwarty — każdy obywatel może go budować. Zapisy zakotwiczone, by przetrwać pięć stuleci. Sygnatariusze zachowują suwerenność; nic nie zostaje obniżone dla kolejnego przystąpienia.`,
      111: `Atlantis Accords nie będzie rosnąć szybciej, niż jest w stanie honorować jakość. Trzy regiony założycielskie muszą ukończyć pełen cykl pilotażu, z każdym uczestnikiem uhonorowanym i każdą zasadą zweryfikowaną, zanim dołączy czwarty region. To zasada, która wreszcie stała się działającą dyscypliną. Lecz akord to porozumienie między obywatelami świata — każdy człowiek, wszędzie, może go budować i utrzymywać, o jeden Seed dalej, niezależnie od tego, co podpisuje rząd czy na co pozwala pracodawca. Horyzont akordu to pięć stuleci. Jego zapisy są zakotwiczone dzięki Replay, tak by obywatel czytający je za sto lat mógł zaufać temu rozumowaniu. Każdy sygnatariusz zachowuje suwerenność; nic nie zostaje obniżone dla kolejnego przystąpienia.`,
      333: `Atlantis Accords nie będzie rosnąć szybciej, niż jest w stanie honorować jakość. Każda ekspansja jest obietnicą wobec uczestników już będących w środku — że standard założycielski nie zostanie rozwodniony przez skalę. Trzy regiony założycielskie muszą ukończyć pełen cykl pilotażu, z każdym uczestnikiem uhonorowanym i każdą zasadą zweryfikowaną, zanim dołączy czwarty region. To zasada, która wreszcie stała się działającą dyscypliną. A drzwi nigdy nie były wyłącznie regionalne: to porozumienie między obywatelami świata, i każdy człowiek może je budować, finansować i rozliczać z odpowiedzialności — bez potrzeby zgody rządu czy błogosławieństwa pracodawcy. Liderzy, którzy podpisują pilotaż, obiecują sygnatariuszom ten sam substrat, ochronę i godność, jakie otrzymała kohorta założycielska. Nic nie zostaje obniżone dla kolejnych.

Horyzont akordu jest celowo długi — zaprojektowany, by przetrwać od piętnastu do dwudziestu ludzkich pokoleń, pięć stuleci od dnia założenia. Jego zapisy są zakotwiczone dzięki Replay, tak by obywatel czytający je za sto lat mógł zweryfikować to rozumowanie, a nie tylko mu zaufać. Jego ramy odniesienia, jego role Human Authority i jego międzypokoleniowe cykle zarządzania są zbudowane tak, by przetrwać każde przejście między pojedynczymi technologiami. Akord przetrwa każdego człowieka, który podpisuje jego założycielski pilotaż, oraz każdego obywatela, który sadzi Seed i finansuje go co miesiąc. To jego obietnica wobec dziecka, które podpisuje umowę stypendialną, wobec obywatela, który dołączył, nie będąc winnym przyzwolenia żadnemu rządowi, wobec wnuków tego dziecka, które mogą zarządzać akordem w połowie stulecia, i wobec każdego pokolenia, które dziedziczy to, co budują teraz założyciele — zarówno oficjalni, jak i obywatelscy.

Każdy sygnatariusz zachowuje swobodę wycofania się, pełną suwerenność i władzę nad własnymi obywatelami, z prawem do wprowadzania poprawek i kształtowania ewolucji akordu. Każdy obywatel zachowuje tę samą pozycję, by zakładać, finansować, być świadkiem i rozliczać go z odpowiedzialności — z podpisem rządu lub bez niego. Czego nikt nie może zrobić, to naruszyć zasad założycielskich, ponieważ ta obietnica musi przetrwać każde odejście. Liderzy i obywatele podpisują razem kolejne stulecie akordu w horyzont, który odziedziczą i dopełnią ich wnuki.`,
      999: `Atlantis Accords nie będzie rosnąć szybciej, niż jest w stanie honorować jakość, a ta powściągliwość nie jest sentymentem — to inżynieria, wpisana w tę samą dyscyplinę pomiaru, która rządzi każdą obietnicą składaną przez akord. Trzy regiony założycielskie, Kambodża, Honduras i Austin, muszą ukończyć pełen cykl pilotażu, z każdym uczestnikiem uhonorowanym i każdą zasadą zweryfikowaną, zanim dołączy czwarty region. Wzrost, który wyprzedza weryfikację, nie jest wzrostem; to narażenie przebrane za ambicję. Pilotaż założycielski istnieje po to, by akord mógł udowodnić, w skali na tyle małej, by dało się ją zbadać, i na tyle dużej, by miała znaczenie, że jego obietnice przetrwają zderzenie z rzeczywistością, zanim zostaną rozciągnięte na świat obserwujący spoza jego trzech granic. Czwarty region nie jest jeszcze nazwany i nie zostanie nazwany, dopóki pierwsze trzy nie staną za każdym twierdzeniem zawartym w tym dokumencie.

Gotowość do wzrostu udowadnia nie entuzjazm, lecz liczba, której akord może publicznie bronić. Qualified Innovation Score — QIS, obliczany jako Przychód plus Zysk Brutto plus Zysk Operacyjny plus Efektywne Wydatki na R&D, podzielone przez cztery — to instrument, którego akord używa, by wiedzieć, czy region, kohorta czy sześcian faktycznie się poprawiły, a nie jedynie odczuwali, że się poprawili. Wzrost QIS wyznacza wielkość puli nagród dopiero po spełnieniu kwalifikacji, nigdy wcześniej, a sam QIS nie tworzy żadnego 웃 ani nie kupuje żadnej własności. QIS to pomiar, nie płatność; pomiar, nie udział; lustro, które akord podnosi wobec własnej pracy, nigdy waluta, którą wydaje. Region proponujący rozszerzenie sieci musi uczciwie pokazać swój QIS, w oczach regionów, które były przed nim, albo nie rozszerza się.

Zrównoważony wzrost oznacza wzrost, który zdobywa własną władzę stopniowo, krok po kroku. Każdy sześcian i każdy region zaczyna w trybie Manual, w którym o wszystkim decydują ludzie, a system jedynie wspiera. Awans do trybu Semi-Automated, a ostatecznie Autonomous, w ramach danego sześcianu jest bramkowany przez jeden próg obowiązujący w całym akordzie — jedenaście i jedną dziewiątą procent mierzonej poprawy, jedną dziewiątą, udowodnioną i powtarzalną, zanim przyznany zostanie kolejny stopień autonomii. Autonomia jest zdobywana sześcian po sześcianie, nigdy przyznawana hurtowo ani rozciągana na domeny, które muszą pozostać ludzkie, niezależnie od tego, jak zaawansowany stanie się system: znaczenie, pieniądze i prawo pozostają zamknięte dla maszyn, bez względu na to, ile progów zostanie pokonanych gdzie indziej. Sieć, która rozszerza swoją automatyzację szybciej, niż rozszerza swoje dowody, nie modernizuje się. Ona hazarduje zaufaniem, na które jeszcze nie zasłużyła.

Wynagrodzenie skaluje się wraz z siecią w ten sam sposób, co władza — celowo, i z pułapem, który chroni cały system przed jego własnym sukcesem. 웃, token Human Intelligence, równa się jednej godzinie potwierdzonej pracy pomnożonej przez lokalną płacę minimalną; to, co zarabia dowolny uczestnik, to ten Multiple razy przepracowane godziny, i jest ono przyznawane wyłącznie za pracę wykonaną w ramach zdefiniowanego, zatwierdzonego budżetowo zadania. Przed zatwierdzeniem nawet najlepszy plan jest jedynie planowaniem, a samo planowanie niczego nie tworzy. Rozliczenie każdego uczestnika jest ograniczone pułapem 9999 웃 rocznie, a każda nadwyżka przechodzi na kolejny rok, zamiast zniknąć lub zniekształcić pulę. W miarę jak dołączają nowe regiony, a aktywność sieci mnoży się, to właśnie ten pułap powstrzymuje wzrost przed przekształceniem się w inflację — wartość pozostaje przywiązana do realnych, potwierdzonych, lokalnych godzin, bez względu na to, jak wielki stanie się akord.

Za każdym 웃 stoi powód, którego żaden rejestr nie potrafi obliczyć sam z siebie. ♡, Shared Intention, niesie ten powód naprzód przez każdą decyzję o ekspansji, jaką podejmuje akord, podczas gdy ◬, wkład Sztucznej Inteligencji, liczony jest jako potwierdzone przyspieszenie mierzone względem zamrożonej linii bazowej — delta, i nigdy, w żadnych okolicznościach, wskaźnik zysku optymalizowany dla samego siebie. Wejście do tej sieci zaczyna się w ten sam sposób dla każdego uczestnika, niezależnie od tego, do jakiego regionu czy w jakiej dekadzie dołącza: od Seed, jednorazowego członkostwa wycenionego na siódmą część lokalnej godziny pracy za płacę minimalną, niezbywalnego i niedającego żadnego roszczenia ekonomicznego. Seed mówi jedynie, że dana osoba przybyła. Wszystko, co buduje ona później, buduje w pełnym świetle pozostałych trzech walut akordu, nigdy przez sam Seed.

Wzrost, który jest rzeczywisty, musi też być wzrostem, który dociera do prawdziwej osoby, nie do funduszu, który framework przechowuje w czyimś imieniu. 🏠 Livelihood Direct wymaga, by wartość przemieszczała się do uczestnika wyłącznie przez kwalifikowane, licencjonowane lokalne kanały, które akord zweryfikował region po regionie, i nigdy przez przechowywanie, które sam framework zatrzymuje. Klasyfikacja zawsze poprzedza rozliczenie, tak by żadna wartość nie przemieszczała się, zanim jej cel i odbiorca nie zostaną ustalone ponad wszelką wątpliwość. A ponieważ uznanie nie jest tym samym co dostęp, nocleg, miejsce w rotacji, miejsce przy stole jest bramkowane przez rolę i gotowość, nigdy przez wynik czy pozycję uczestnika. W miarę jak sieć rozszerza się na czwarty region i dalej, każde nowe terytorium musi zakwalifikować własne licencjonowane kanały, zanim Livelihood Direct dotrze do jego mieszkańców — to ekspansja zaufania, nie jedynie ekspansja terytorium.

Nic z tego nie przetrwa bez sieci zbudowanej tak, by przetrwać własny sukces, dlatego właśnie Continuity Without Evasion rządzi każdym regionem, jaki akord kiedykolwiek dołączy. Zgodna z prawem przenośność jest obowiązkowa; żaden pojedynczy rząd, bank, założyciel czy model nie może stać się niezbędny dla całości. Każda jurysdykcja prowadzi własny adapter, działający na zasadzie bezpiecznego zamknięcia i domyślnej odmowy, tak by niekorzystne orzeczenie gdziekolwiek zamykało jeden kanał, nigdy cały akord. Human Authority utrzymuje znaczenie, pieniądze i prawo na każdej skali, jaką osiąga sieć, zabezpieczone przed wkroczeniem maszyn z założenia projektowego, nie jedynie obietnicą. Measurement of Time zapisuje każdą rzeczywistą minutę osobno od każdego twierdzenia na jej temat, a Replay zapewnia, że każde wydanie, w każdym regionie, w każdym momencie na przestrzeni pięciu stuleci, może zostać zrekonstruowane i ponownie zbadane przez każdego, kto o to poprosi. Sieci, której nie można odtworzyć, nie można zaufać, bez względu na to, ile regionów do niej dołączyło ani jak imponujący wydaje się jej wzrost z zewnątrz. Tak właśnie Vision 2525 rośnie, nigdy nie przerastając zaufania, które miało chronić — jeden zweryfikowany region, jeden uczciwy QIS, jedna potwierdzona godzina naraz.`,
    },
  },
];
