import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_PT: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Onde a Inovação Começa`,
    content: {
      7: `Líderes iniciam o que nenhum século iniciou.`,
      33: `Três regiões — Camboja, Honduras, Austin — abrem uma promessa que os cidadãos ajudam a construir: acolher aprendizes, protegê-los, entregar-lhes as ferramentas do futuro. Governo, Educação e Inovação assinam como guardiões; os cidadãos a sustentam. Um só começo.`,
      111: `O Acordo de Atlantis é um pacto entre cidadãos do mundo — uma promessa que qualquer pessoa, em qualquer lugar, pode criar e sustentar, independentemente do que seu governo assine ou seu empregador permita. Suas regiões fundadoras, Camboja, Honduras e Austin, no Texas, foram escolhidas por uma qualidade rara: a disposição de confiar aos jovens as ferramentas do futuro enquanto ainda há tempo de ensiná-los. Governos, educadores e inovadores assinam como guardiões de suas regiões — três assinaturas visionárias cada, Governo, Educação, Inovação — mas são os cidadãos que financiam o acordo, testemunham seu trabalho e o responsabilizam diretamente. Não é necessária permissão de governo nem bênção de empregador para pertencer. Três regiões, um só começo compartilhado.`,
      333: `Toda civilização é lembrada pelo que escolheu começar. O Acordo de Atlantis é uma promessa entre cidadãos do mundo — qualquer pessoa, em qualquer lugar, pode começá-la, independentemente do que seu governo assine. Suas regiões fundadoras, Camboja, Honduras e Austin, no Texas, não foram escolhidas por poder econômico, força militar ou prestígio institucional, mas por uma qualidade mais rara: a disposição de confiar aos jovens as ferramentas do futuro. É isso que liderança significa no século que se aproxima — a coragem de entregar as chaves à próxima geração enquanto ainda há tempo de ensiná-la a dirigir.

O acordo é convocado pela eXeL, uma força organizadora concebida especificamente para este momento, existindo fora dos canais de coordenação que moldaram o século passado — fora das estruturas de tratados diplomáticos, das burocracias multilaterais e dos entrelaçamentos políticos de qualquer Estado-nação isolado. A eXeL é a convocadora de confiança que reúne líderes visionários em torno de um arcabouço compartilhado, um volante compartilhado e um horizonte compartilhado de quinhentos anos. Cada signatário conserva soberania plena, autoridade plena sobre seus próprios cidadãos e plena liberdade para se retirar a qualquer momento. O que os signatários ganham — e o que qualquer cidadão ganha, pelo preço de uma Seed, um sétimo de uma hora de salário mínimo local — é o efeito de rede que somente um arcabouço concebido para esse fim pode oferecer: coordenação sem qualquer forma de dominação política.

Assinar o acordo é assinar uma promessa: que a região acolherá aprendizes de diferentes culturas, contribuirá com aquilo que só ela pode oferecer, e se manterá sob um padrão mais elevado do que a regulação vigente exige — publicamente, com transparência, prestando contas aos cidadãos que o financiam, o testemunham e o responsabilizam, sem exigir permissão de governo nem bênção de empregador para pertencer. Três assinaturas são exigidas de cada região — Governo, Educação e Inovação —, assinando como guardiões, não como proprietários. São necessários três visionários para dizer sim, e cidadãos para sustentar o que assinaram. Três visionários, três regiões, um só começo — é assim que um arcabouço ganha vida pela confiança de líderes dispostos a assiná-lo à existência.`,
      999: `Toda civilização é lembrada pelo que escolheu começar, e a Vision 2525 pede aos fundadores desta que comecem com humildade, não com conquista. O Acordo de Atlantis é uma promessa feita por líderes dispostos a começar algo que nunca existiu antes — um alicerce compartilhado para a inovação humana que alcança cada canto do mundo, honra cada voz e perdura ao longo de gerações medidas não em anos, mas em séculos. Seus signatários fundadores em Camboja, Honduras e Austin, no Texas, não foram escolhidos por poder econômico, força militar ou prestígio institucional. Foram escolhidos por uma qualidade mais rara: a disposição de confiar aos jovens as ferramentas do futuro, e a paciência de deixar que um horizonte de quinhentos anos sobreviva ao aplauso de qualquer administração. É isso que liderança significa no século que se aproxima — a coragem de entregar as chaves à próxima geração enquanto ainda há tempo de ensiná-la a dirigir.

O acordo é convocado pela eXeL, uma força organizadora concebida especificamente para este momento. A eXeL existe fora dos canais de coordenação que moldaram o século passado — fora das estruturas de tratados diplomáticos, fora das burocracias multilaterais, fora dos entrelaçamentos políticos de qualquer Estado-nação. A eXeL é a convocadora de confiança que reúne líderes visionários em torno de um arcabouço compartilhado, um volante compartilhado e um horizonte compartilhado de quinhentos anos. Cada signatário conserva soberania plena, autoridade plena sobre seus próprios cidadãos e plena liberdade para se retirar a qualquer momento. O que os signatários ganham é o efeito de rede que somente um arcabouço concebido para esse fim pode oferecer. A entrada de cada participante nesse arcabouço começa sempre do mesmo modo modesto: com uma Seed, uma adesão única, precificada em um sétimo de uma hora de salário mínimo local, intransferível e sem qualquer reivindicação econômica. Uma Seed não compra propriedade nem promessa de recompensa — apenas pertencimento, o direito de estar dentro do arcabouço e começar. Isso é coordenação sem qualquer forma de dominação política, construída sobre um começo pequeno o bastante para que qualquer pessoa possa pagar.

Porque a soberania é conservada, e não cedida, o acordo é construído para a Continuidade Sem Evasão. Nenhum governo, banco, fundador ou modelo indispensável pode manter o arcabouço inteiro refém da própria sobrevivência. Cada jurisdição é atendida por seu adaptador legal próprio, em recusa padrão até que a conformidade seja comprovada, de modo que o valor circule apenas por vias que um tribunal daquela jurisdição reconheceria como legítimas. Se um regulador de uma região emite uma decisão desfavorável, apenas essa via se fecha — de forma transparente, sem prejudicar nenhum participante dentro dela —, enquanto todas as demais regiões seguem intocadas. O acordo inteiro jamais cai porque um governo mudou de ideia. Isto é portabilidade projetada como promessa fundadora, não como contingência descoberta depois da crise.

Assinar o acordo é assinar uma promessa. De que a região acolherá aprendizes de diferentes culturas. De que a região contribuirá com aquilo que só ela pode oferecer. De que a região se manterá sob um padrão mais elevado do que a regulação vigente exige. De que a região fará isso publicamente, com transparência, à vista de cada cidadão que serve. Três assinaturas são exigidas de cada região — Governo, Educação e Inovação. Nenhum cargo vincula o acordo sozinho. São necessários três visionários para dizer sim. Essa assinatura tripla é a primeira expressão da Autoridade Humana: sentido, dinheiro e lei permanecem em mãos humanas na camada soberana, uma camada permanentemente fechada às máquinas, por mais capazes que se tornem. A Medição do Tempo, MoT, começa a registrar a partir do momento da assinatura — minutos reais de trabalho humano real, mantidos separados de qualquer estimativa automatizada — e cada versão subsequente do trabalho do acordo é construída para ser reconstruída por meio de Replay, de modo que um cidadão nascido daqui a um século possa refazer o caminho de como as decisões fundadoras de hoje foram tomadas.

O que o piloto funda é a medição antes do dinheiro. Cada inovação que entra no arcabouço é pontuada pela Pontuação de Inovação Qualificada, QIS — a média entre Receita, Lucro Bruto, Resultado Operacional e Gasto Efetivo em P&D, dividida por quatro. A QIS não é pagamento e nunca é propriedade; é o instrumento pelo qual uma coorte fundadora aprende a enxergar o próprio progresso antes que qualquer recompensa seja dimensionada. O crescimento da QIS, uma vez atingida a qualificação, dimensiona o fundo de recompensas que se segue — mas o crescimento da QIS nada emite por si só. Três regiões, um começo, e uma disciplina compartilhada: comprovar a pontuação antes de tocar no tesouro.

O valor obtido por meio de trabalho testemunhado carrega seu próprio nome, 웃, calculado como uma hora multiplicada pelo salário mínimo local, ajustado por um Múltiplo aplicado sobre as horas prestadas. O 웃 é emitido somente para trabalho testemunhado sob uma tarefa delimitada e aprovada por orçamento; qualquer coisa aquém dessa aprovação ainda é planejamento, e planejamento sozinho nada emite. Um teto de liquidação de 9.999 웃 por ano protege cada participante contra concentração descontrolada, com qualquer excedente transportado para o período seguinte, em vez de simplesmente desaparecer. Por trás de cada 웃 está o ♡, Intenção Compartilhada, que carrega o porquê pelo qual uma tarefa foi aprovada em primeiro lugar, e o ◬, a aceleração testemunhada que uma tarefa produziu em relação a uma linha de base congelada — apenas um delta, jamais confundido com uma métrica de lucro. O piloto existe para comprovar que esses três glifos podem se mover juntos com honestidade, região após região, antes que o arcabouço se expanda para além de seus fundadores.

Quando o valor chega até uma pessoa, chega por meio do Livelihood Direct — 🏠 — vias locais licenciadas e qualificadas que a eXeL jamais custodia como fundo próprio. A classificação precede a liquidação em todos os casos, e o reconhecimento de uma contribuição jamais franqueia uma cama para passar a noite; somente o papel de uma pessoa dentro de uma tarefa delimitada o faz. O crescimento além do piloto também é condicionado: cada cubo do arcabouço avança de Manual para Semiautomatizado e para Autônomo somente depois de superar a regra dos 11,1 por cento, uma parte em nove de melhoria mensurada, conquistada cubo a cubo e nunca reivindicada por atacado — e jamais, sob nenhuma circunstância, sobre a camada soberana de sentido, dinheiro e lei. É assim que três visionários por região, três regiões e um começo se tornam uma promessa de quinhentos anos: não avançando depressa, mas comprovando, à vista pública, que cada passo conquistou o passo seguinte.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Aprender Através da Simulação`,
    content: {
      7: `Praticar mil vezes antes de tocar.`,
      33: `Nada de consequência é aprendido primeiro em equipamento real. Qualquer cidadão pode ensaiar em simulação, rodar pelas três regiões, celebrar — respeito pelo jovem humano cujo primeiro erro jamais deveria custar uma vida.`,
      111: `Toda disciplina que vale a pena dominar foi aprendida por alguém antes de ser conhecida. O Acordo de Atlantis devolve essa sabedoria ancestral ao centro de como os jovens — e qualquer cidadão que se junte — são preparados para construir o futuro. Nada de consequência é aprendido primeiro em equipamento real, em pessoas reais ou em condições irreversíveis; não é exigida permissão de governo nem bênção de empregador. Cada participante pratica em simulação até que a prática se torne competência, e depois prontidão. O modelo de rotação conduz cada participante pelas três regiões fundadoras, e cada rotação termina em uma celebração pública aberta à comunidade anfitriã. Isto é respeito pelo jovem humano cujo primeiro erro jamais deveria custar uma vida.`,
      333: `Toda disciplina que vale a pena dominar foi aprendida por alguém antes de ser conhecida. Grandes artesãos ensaiam antes de se apresentar, pilotos antes de voar, médicos antes de operar, crianças por meio da brincadeira. O Acordo de Atlantis devolve essa sabedoria ancestral ao centro de como os jovens — e qualquer cidadão que se junte, sem exigir permissão de governo nem bênção de empregador — são preparados para construir o futuro. Nada de consequência é aprendido primeiro em equipamento real, em pessoas reais ou em condições irreversíveis. Cada participante pratica em simulação até que a prática se torne competência, e depois prontidão. Isto não é cautela — é respeito pelo jovem humano cujo primeiro erro jamais deveria custar a vida de ninguém.

O modelo de rotação do acordo conduz cada participante pelas três regiões fundadoras. O que se aprende no Camboja é refinado em Honduras e concluído em Austin. O que se descobre em Austin é questionado no Camboja e integrado em Honduras. Cada participante vive, aprende e é orientado por meio de culturas que, de outro modo, permaneceriam distantes. O currículo de treinamento se apoia em tradições de simulação disciplinada de muitas culturas — na tradição de educação estratégica de Sun Tzu, na prática pelo jogo de Musashi, na teoria do aprendizado cíclico de Ibn Khaldun, na dialética monástica de Nalanda, no simulador de voo civil — sintetizadas com respeito a cada estágio cognitivo e a cada herança cultural. Nenhuma tradição isolada domina.

Cada rotação termina em uma celebração pública aberta à comunidade anfitriã, onde vizinhos, famílias e visitantes veem o que a coorte aprendeu. Esses eventos tornam a tecnologia sofisticada acessível e celebrada, em vez de temida — uma sociedade que cresce entendendo sistemas cooperativos por meio da brincadeira não pode ser facilmente manipulada pelo medo deles. Isso é dissuasão pela educação, não pela força. A promessa do acordo a cada pai e mãe: seu filho vai praticar mil vezes em segurança antes de tocar em qualquer coisa que possa feri-lo, tudo testemunhado, para que um cidadão — qualquer cidadão, daqui a um século — possa verificar que aconteceu exatamente como registrado. Isto é respeito pelo jovem humano projetado dentro de um arcabouço, e é o que a liderança deve ao próximo cidadão que se junta, antes que esse cidadão precise exigi-lo.`,
      999: `Toda disciplina que vale a pena dominar foi aprendida por alguém antes de ser conhecida, e toda civilização que perdurou o fez porque protegeu o espaço onde esse aprendizado podia acontecer em segurança, antes de lhe ser exigido que importasse de verdade. Grandes artesãos ensaiam antes de se apresentar, pilotos ensaiam antes de voar, médicos ensaiam antes de operar, e crianças ensaiam o mundo por meio da brincadeira. O Acordo de Atlantis devolve essa sabedoria ancestral ao centro de como os jovens são preparados para construir o futuro, e dá a essa sabedoria um nome e um mecanismo: Replay. Nada de consequência é aprendido primeiro em equipamento real, em pessoas reais ou em condições irreversíveis. Cada participante pratica em simulação até que a prática se torne competência, e depois prontidão, e cada hora dessa prática é registrada para que possa ser reconstruída depois, examinada depois, confiada depois. Isto não é cautela — é respeito pelo jovem humano cujo primeiro erro jamais deveria custar a vida de ninguém, e é respeito pelo registro que, de qualquer forma, sobreviverá ao erro.

O modelo de rotação do acordo conduz cada participante pelas três regiões fundadoras. O que se aprende no Camboja é refinado em Honduras e concluído em Austin. O que se descobre em Austin é questionado no Camboja e integrado em Honduras. Cada participante vive, aprende e é orientado por meio de culturas que, de outro modo, permaneceriam distantes, e cada rotação começa da mesma forma que começa toda instituição humana digna de confiança: com uma Seed. A Seed é uma adesão única, precificada em um sétimo de uma hora de salário mínimo local, intransferível, sem qualquer reivindicação econômica. Não é uma taxa de acesso a uma oportunidade. É um limiar — pequeno o bastante para que nenhum participante disposto seja excluído pelo preço, deliberado o bastante para que a entrada seja escolhida, não algo em que se caia por acaso. A partir desse limiar, cada participante pertence à rotação, e a rotação não pertence a nenhuma região isolada.

O currículo de treinamento se apoia em tradições de simulação disciplinada de muitas culturas — na tradição de educação estratégica de Sun Tzu, na prática pelo jogo de Musashi, na teoria do aprendizado cíclico de Ibn Khaldun, na dialética monástica de Nalanda, no simulador de voo civil — sintetizadas com respeito a cada estágio cognitivo e a cada herança cultural. Nenhuma tradição isolada domina. E dentro desse currículo, o acordo traça uma linha que cada participante aprende cedo e nunca esquece: a simulação é onde a Pontuação de Inovação Qualificada é compreendida, não onde ela é gasta. A QIS é medição, nunca pagamento, e a QIS nunca é propriedade — ela existe para descrever quão bem uma proposta se sustenta, resiste ao escrutínio e serve à região que alega servir. O crescimento da QIS pode dimensionar um fundo de recompensas depois de uma qualificação real, mas nada emite por si só. Um participante pode rodar cem simulações impecáveis e ver sua pontuação subir sem que uma única hora de 웃 toque seu registro, porque o 웃 é emitido apenas para trabalho testemunhado, realizado sob uma tarefa delimitada e aprovada por orçamento. Antes dessa aprovação, tudo — por mais habilidoso, por mais promissor que seja — é planejamento. O acordo ensina essa distinção no primeiro dia, para que nenhum jovem confunda ensaio com recompensa, e para que nenhum jovem seja jamais enganado sobre para que serve a simulação.

Essa mesma disciplina governa quanta autonomia qualquer sistema, humano ou artificial, tem permissão para exercer dentro da rotação. Os modos de operação do acordo avançam em sequência — Manual, depois Semiautomatizado, depois Autônomo —, e nenhum cubo avança de modo até superar a regra dos 11,1 por cento de melhoria mensurada, uma parte em nove, comprovada contra uma linha de base congelada e testemunhada, não apenas alegada. A simulação é onde essa prova é construída. Uma ferramenta conquista o direito de agir com menos supervisão da mesma forma que um participante conquista o direito a maior responsabilidade: por meio de melhoria demonstrada, registrada, reconstruível, cubo a cubo, nunca de uma só vez, e nunca sobre a camada em que sentido, dinheiro e lei são decididos. Essa camada pertence unicamente à Autoridade Humana, na simulação e na operação real, porque um espaço de ensaio que ensina o limite errado ensina a lição errada de forma permanente.

Cada rotação termina em uma celebração pública e cooperativa aberta à comunidade anfitriã. Vizinhos, famílias e visitantes se reúnem para ver o que a coorte aprendeu, e o que testemunham não é uma demonstração de velocidade por si só, mas uma demonstração de ◬ — o delta mensurado entre uma linha de base congelada e o que a prática disciplinada de fato alcançou, apresentado com honestidade, jamais disfarçado de métrica de lucro, jamais apresentado como mais do que realmente é. Esses eventos tornam a tecnologia sofisticada acessível e celebrada, em vez de temida. Uma sociedade que cresce entendendo sistemas cooperativos por meio da brincadeira não pode ser facilmente manipulada pelo medo desses sistemas. Isso é dissuasão pela educação, não dissuasão pela força, e funciona porque não se pede à comunidade que confie numa alegação — convida-se a comunidade a assistir ao Replay.

A promessa do acordo a cada pai e mãe vai além da segurança e alcança a permanência: seu filho vai praticar mil vezes antes de tocar em qualquer coisa que possa feri-lo, a comunidade testemunhará seu crescimento ao longo de todo o processo, e nada disso se perderá com o tempo. A Medição do Tempo registra os minutos reais separadamente de todo outro registro que o acordo mantém, de modo que horas praticadas e horas testemunhadas nunca sejam confundidas entre si, e de modo que a verdadeira história de desenvolvimento de um participante — não um resumo, não uma aproximação, mas o próprio registro reconstruível — permaneça disponível para esse participante enquanto ele desejar consultá-la. Um pai em Phnom Penh, um mentor em Tegucigalpa, um auditor em Austin, ou um neto lendo o registro daqui a um século podem todos acessar o mesmo Replay e ver a mesma verdade.

É assim que o respeito pelo jovem humano se manifesta quando é projetado dentro de um arcabouço, e não apenas prometido por ele, e é isso que a liderança entrega à próxima geração de participantes antes que essa geração precise exigi-lo: um espaço de ensaio vasto o bastante para falhar com segurança, honesto o bastante para registrar com fidelidade, e disciplinado o bastante para manter recompensa, autonomia e autoridade exatamente onde a maestria as conquistou — nunca à frente dela, nunca atrás.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Segurança Verificada Antes de Estender a Confiança`,
    content: {
      7: `Segurança provada primeiro, depois confiança.`,
      33: `Cada instalação e cada rotação está dentro de um envelope de proteção com alerta antecipado. O hardware se recusa à armamentização — provado, não prometido, inspecionável pelos cidadãos. Os registros sobrevivem a turbulências. A segurança é projetada em torno do participante mais jovem, todos os dias.`,
      111: `Antes que a confiança seja estendida, a segurança precisa ser comprovada — não a um governo, mas a qualquer cidadão que a inspecione. O Acordo de Atlantis é um pacto entre cidadãos do mundo; seu compromisso fundador é este: cada instalação do acordo, cada rota de rotação, cada lugar onde um jovem participante dorme ou estuda está dentro de um envelope de proteção documentado, com capacidade de alerta antecipado que dá à comunidade horas, não minutos, para responder a qualquer risco crível. Todo dispositivo, todo sensor, todo sistema de coordenação é vinculado na camada de hardware a recusar sua reconversão para integração em sistemas de armas. Isto não é política — é física. O acordo permanece honrado através das turbulências, porque todo plano coloca a dignidade humana em primeiro lugar.`,
      333: `Antes que a confiança seja estendida, a segurança precisa ser comprovada — comprovada aos cidadãos, não apenas afirmada. O Acordo de Atlantis é um pacto entre cidadãos do mundo: qualquer pessoa, em qualquer lugar, pode ajudar a sustentá-lo, independentemente do que seu governo assine. Cada instalação do acordo, cada rota de rotação, cada lugar onde um jovem participante dorme ou estuda está dentro de um envelope de proteção documentado, com capacidade de alerta antecipado que dá à comunidade horas, não minutos, para responder a qualquer risco crível. A tecnologia que os protege é a mesma tecnologia que o acordo os ensina a construir. Os jovens aprendem segurança de dentro para fora, não por lhes dizerem que estão seguros, mas por verem essa segurança sendo projetada ao seu redor todos os dias, e sabendo que qualquer cidadão pode verificar o registro por meio do Replay.

O acordo faz uma promessa inquebrável sobre aquilo em que sua tecnologia não pode se transformar. Todo dispositivo, todo sensor, todo sistema de coordenação é vinculado na camada de hardware a recusar sua reconversão para integração em sistemas de armas. Isto não é linguagem de política, não é aspiração. É uma impossibilidade física, imposta criptograficamente, verificada por cada região signatária, e inspecionável por cada cidadão que a financia. As ferramentas que protegem uma criança em Phnom Penh não podem ser reconvertidas para prejudicar uma criança em Austin. As ferramentas que conectam um exercício de enxame em Tegucigalpa não podem ser reconfiguradas para visar a um ser humano em lugar nenhum. Esta é a resposta do acordo a um século de medo do uso duplo. Não é política — é física.

O acordo permanece honrado através das turbulências. Se uma região perde estabilidade política, os participantes são amparados pelas demais regiões. Se o financiamento se contrai, os estipêndios são protegidos primeiro — financiados mensalmente pelos cidadãos, nunca por um canal de ajuda externa, com cada dólar rastreável. Se os registros digitais são atacados, cópias de segurança offline persistem. Se o deslocamento se torna impossível, o substrato continua de forma virtual. Todo plano coloca a dignidade humana — a Autoridade Humana sobre sentido, dinheiro e lei — como sua primeira restrição de projeto. Os líderes que assinam este acordo prometem que a segurança é projetada, não presumida: a proteção que qualquer líder exigiria para seu próprio filho, estendida agora a cada cidadão que ajuda a sustentá-la.`,
      999: `Antes que a confiança seja estendida, a segurança precisa ser comprovada — este é o compromisso fundador do Acordo de Atlantis, e ele é comprovado da mesma forma que toda outra alegação dentro da Vision 2525 é comprovada: não por afirmação, mas por evidência que os cidadãos podem inspecionar. Cada instalação do acordo, cada rota de rotação, cada lugar onde um jovem participante dorme ou estuda está dentro de um envelope de proteção documentado, com capacidade de alerta antecipado que dá à comunidade horas, não minutos, para responder a qualquer risco crível. A tecnologia usada para proteger os participantes é a mesma tecnologia que o acordo os ensina a construir — sensores, coordenação, sobrevivência das comunicações, inteligência distribuída. Os jovens aprendem segurança de dentro para fora, em seu próprio idioma e em sua própria região, não por lhes dizerem que estão seguros, mas por observarem, hora após hora, como a segurança é projetada ao seu redor diariamente.

Essa observação não fica entregue à memória ou à confiança na palavra de um facilitador. A Medição do Tempo registra os minutos reais de cada simulado, cada rotação, cada exercício de resposta — separadamente de qualquer alegação de progresso, separadamente de qualquer história contada naquele dia. O Replay torna cada versão do currículo de treinamento, cada atualização de segurança, cada revisão de hardware totalmente reconstruível, de modo que um pai em Tegucigalpa ou um regulador em Phnom Penh possa percorrer de trás para frente exatamente o que mudou, quando mudou e por que mudou. Um envelope de proteção que não pode ser reproduzido por Replay é apenas uma promessa. Um envelope de proteção que pode ser reproduzido, minuto a minuto registrado, é uma prova. O acordo escolhe a prova.

O acordo faz uma promessa inquebrável sobre aquilo em que sua tecnologia não pode se transformar. Todo dispositivo, todo sensor, todo sistema de coordenação é vinculado na camada de hardware a recusar sua reconversão para integração em sistemas de armas. Isto não é linguagem de política, não é aspiração. É uma impossibilidade física, imposta criptograficamente, verificada por cada região signatária, e inspecionável por cada cidadão. As ferramentas que protegem uma criança em Phnom Penh não podem ser reconvertidas para prejudicar uma criança em Austin. As ferramentas que conectam um exercício de enxame em Tegucigalpa não podem ser reconfiguradas para visar a um ser humano em lugar nenhum. Esta é a resposta do acordo a um século de medo do uso duplo. Não é política — é física.

Segurança comprovada uma vez não é segurança sustentada ao longo de um horizonte de quinhentos anos. O acordo nomeia seu segundo compromisso Continuidade Sem Evasão: portabilidade legal por todas as jurisdições que o acordo alcança, sem que nenhum governo, banco, fundador ou modelo indispensável se interponha entre um participante e sua proteção. Cada jurisdição é atendida por seu próprio adaptador, com recusa em caso de falha e recusa padrão, de modo que uma decisão desfavorável em qualquer região feche apenas aquela via — nunca o arcabouço inteiro, nunca todas as regiões, nunca todos os participantes em todo lugar ao mesmo tempo. Uma decisão judicial em um território signatário não pode desligar o envelope de segurança de um participante em outro lugar. É isso que significa construir um sistema que sobrevive às turbulências ordinárias da lei, da política e da mudança institucional sem jamais pedir a um participante que burle a lei para permanecer protegido.

Cada camada dessa arquitetura de proteção responde, no fim, à Autoridade Humana. Sentido, dinheiro e lei nunca são delegados a máquinas — a camada soberana que decide o que a segurança exige, o que conta como risco crível e que resposta uma comunidade deve a seus membros mais jovens permanece fechada à inteligência artificial, por mais capaz que ela se torne. Os sistemas do acordo se movem por apenas três modos de operação — Manual, Semiautomatizado, Autônomo —, e nenhum sistema avança de modo sem uma melhoria testemunhada e mensurada de ao menos uma parte em nove, onze vírgula um por cento, verificada, reprodutível. A autonomia é conquistada, cubo a cubo, função a função, nunca concedida por atacado, e jamais estendida sobre as questões que determinam sentido, dinheiro ou lei. Um sensor pode aprender a detectar mais rápido. Um sistema de coordenação pode aprender a rotear com mais eficiência. Nenhum dos dois tem permissão para decidir, sozinho, no que uma comunidade deve confiar seus filhos.

O acordo é projetado para permanecer honrado através das turbulências, e nomeia essas turbulências com antecedência, em vez de descobri-las em crise. Se uma região signatária perde estabilidade política, os participantes são amparados pelas demais regiões. Se o financiamento se contrai, os estipêndios dos participantes são protegidos primeiro, antes da administração e da infraestrutura. Se os registros digitais são atacados, cópias de segurança offline persistem, inalcançáveis por qualquer falha que tenha atingido a rede. Se o deslocamento se torna impossível, o substrato continua de forma virtual, de modo que uma rotação não para porque uma fronteira fechou. Cada cenário é planejado com antecedência, e cada plano coloca a dignidade humana como sua primeira restrição de projeto — não como sua última consideração depois que orçamentos e aparências já foram resolvidos.

A entrada nesse sistema comprovado começa com a Seed — uma adesão única, precificada em um sétimo de uma hora de salário mínimo local, intransferível, e sem qualquer reivindicação econômica sobre o que quer que o acordo construa depois. A Seed não compra segurança; a segurança é projetada muito antes que qualquer Seed seja plantada. O que a Seed compra é posição — o direito de entrar em um arcabouço já comprovado, já inspecionado, já vinculado por um hardware que não pode ser voltado contra a própria pessoa que existe para proteger. Essa separação é deliberada. Uma promessa de segurança que precisa ser comprada com peso econômico real não é uma promessa de segurança, é apenas um produto de segurança. O acordo mantém as duas coisas absolutamente separadas, para que nenhuma família precise jamais pesar a proteção do próprio filho contra o orçamento mensal da casa.

Os líderes que assinam este acordo estão assinando uma promessa de que a segurança é projetada, não presumida, e comprovada, não apenas alegada. O que estendem a seus cidadãos não é apenas oportunidade, mas proteção construída no padrão que o participante mais jovem merece — registrada pela Medição do Tempo, reconstruível por meio do Replay, vinculada na camada de hardware contra todo mau uso que um século temeroso já imaginou, e responsável, sempre e somente, perante a Autoridade Humana. É a mesma proteção que qualquer líder exigiria para o próprio filho atravessando sozinho uma fronteira desconhecida, agora estendida a cada criança que o acordo algum dia servirá, em suas três regiões fundadoras — Camboja, Honduras e Austin — e ao longo dos cinco séculos em que o acordo pretende manter esta promessa.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Compensação, Bem-Estar e Dignidade Humana`,
    content: {
      7: `Uma bolsa, um mentor, um lar.`,
      33: `Todo cidadão recebe um estipêndio desde o primeiro dia — sem permissão de governo, sem bênção de empregador. Amor, perda e segurança são infraestrutura. O sucesso é medido pelo mais vulnerável. Dignidade é substrato, nunca decoração.`,
      111: `O Acordo de Atlantis trata cada participante como um ser humano desde o primeiro dia — um cidadão que se juntou por direito, não por decreto de governo ou licença de empregador. Um estipêndio é fornecido a partir do momento em que a participação começa, indexado ao custo de vida da região, e cada hora testemunhada rende 웃, pago diretamente à pessoa por meio do Livelihood Direct, nunca pelo registro contábil de um empregador. O bem-estar é tratado como infraestrutura de primeira classe — não um mimo, mas o substrato sobre o qual tudo se sustenta. Três domínios são amparados: Amor, Perda e Segurança. O acordo mede o sucesso pelo participante mais vulnerável, não pela média. Ninguém é esquecido para que as médias pareçam boas. Dignidade como substrato, não como decoração.`,
      333: `O Acordo de Atlantis trata cada participante como um ser humano desde o primeiro dia — um cidadão que pertence por direito, sem precisar de permissão de governo nem de bênção de empregador. Um estipêndio é fornecido a partir do momento em que a participação começa, indexado ao custo de vida da região, chegando antes que as obrigações familiares se tornem emergências. Isto não é caridade. É o reconhecimento de que a inovação humana comum exige, antes de tudo, segurança humana — uma mente não pode florescer enquanto seu lar está sob ameaça.

O que é ganho além do estipêndio é ganho como um cidadão o ganha: por meio da Seed, precificada em um sétimo de uma hora de salário mínimo local, e por meio do 웃, pago apenas por horas testemunhadas. A QIS mede promessa, mas nada emite — medição, nunca pagamento. Todo pagamento chega ao participante por meio do Livelihood Direct, vias locais licenciadas que o acordo jamais custodia, construídas para a Continuidade Sem Evasão.

O bem-estar é tratado como infraestrutura de primeira classe — não um mimo, mas o substrato sobre o qual tudo se sustenta. O acordo nomeia três domínios pelos quais cada participante é amparado: Amor, conexão e limites saudáveis; Perda, já que o luto precisa ser acompanhado, não contornado; e Segurança, saber a quem recorrer, em cada região, no próprio idioma. Aconselhamento, círculos de grupo e práticas culturais ou espirituais honradas conforme a tradição de cada um são oferecidos. Zero ideologia imposta; a Autoridade Humana, nunca uma máquina, decide de que cuidado um cidadão precisa.

O acordo mede o sucesso pelo participante mais vulnerável, não pela média. Cidadãos rurais sem banda larga de alta velocidade são atendidos. Participantes neurodivergentes recebem adaptação como norma, não como exceção. Participantes com deficiência encontram cada instalação acessível. Participantes de gênero diverso recebem moradia segura e pareamento com mentores. Falantes de idiomas não nativos encontram cada material em seu próprio idioma. Participantes indígenas encontram suas práticas culturais honradas e seu conhecimento tradicional protegido. Os líderes que assinam este acordo prometem que nenhum cidadão será esquecido para que as médias pareçam boas. Isto é dignidade como substrato, não como decoração. O que é medido é o que será honrado, e o que é honrado aqui é o ser humano inteiro — mente, corpo e espírito, amparado por seus concidadãos, sem exceção.`,
      999: `O Acordo de Atlantis trata cada participante como um ser humano completo desde o primeiro dia, incorporado em mecanismo, não apenas em linguagem. Um estipêndio é fornecido a partir do momento em que a participação começa, indexado ao custo de vida da região, de modo que seu impacto respeite a dignidade local do trabalho. O estipêndio chega antes que as obrigações familiares se tornem emergências, e antes que a dignidade seja comprometida. Ele sinaliza a cada jovem que seu tempo é valioso, sua contribuição é esperada, e a estabilidade de sua família é parte da responsabilidade do acordo. Isto não é caridade. É o reconhecimento de que a inovação humana comum exige, antes de tudo, segurança humana. Uma mente não pode florescer enquanto seu lar está sob ameaça. A própria entrada carrega um limiar pequeno e deliberado: a Seed, uma adesão única, precificada em um sétimo de uma hora de salário mínimo local, intransferível e sem qualquer reivindicação econômica própria. A Seed diz apenas que uma pessoa se juntou; não paga nada a ela nem promete nada além da porta que abre.

O que é ganho depois que essa porta se abre é regido com a mesma precisão que o acordo traz a toda outra promessa. O 웃, a medida de Inteligência Humana do acordo, é calculado de forma simples — uma hora ao salário mínimo local, multiplicada pelo Múltiplo que reflete a dificuldade e o valor da tarefa, vezes as horas efetivamente trabalhadas. Mas o 웃 é emitido apenas para trabalho testemunhado, realizado sob uma tarefa delimitada e aprovada por orçamento. Antes que essa aprovação exista, o que um participante está fazendo é planejamento, não ganho — uma distinção que o acordo mantém com firmeza, porque protege tanto o tesouro quanto o participante de promessas feitas mais depressa do que o valor pode ser verificado. A Medição do Tempo, MoT, registra os minutos efetivamente trabalhados separadamente de qualquer cálculo de compensação, de modo que o tempo permaneça um fato honesto e auditável, independente do pagamento. As horas de nenhum participante são infladas, e as horas de nenhum participante desaparecem. Um teto de liquidação de 9.999 웃 por ano se aplica a cada participante, com qualquer excedente transportado para o período seguinte em vez de simplesmente desaparecer, de modo que uma contribuição excepcional seja reconhecida ao longo de vários anos, em vez de ficar invisível, limitada a um único ano.

A compensação é deliberadamente mantida distinta da medição de inovação. A Pontuação de Inovação Qualificada, QIS, calcula a média entre Receita, Lucro Bruto, Resultado Operacional e Gasto Efetivo em P&D para descrever o quanto a inovação de fato cresceu. Seu crescimento ao longo do tempo pode dimensionar um fundo de recompensas assim que a qualificação é atingida, mas a QIS em si não emite nenhum 웃 nem liquida nada diretamente — é uma medição, nunca um pagamento, e jamais é confundida com propriedade sobre o que foi construído. Essa separação importa porque mantém honestos tanto o estipêndio quanto o salário: um participante é pago por horas testemunhadas de trabalho real, não por uma pontuação que poderia ser manipulada, inflada ou contestada. O ♡, Intenção Compartilhada, carrega o porquê por trás de cada tarefa que um participante assume; o ◬, a aceleração testemunhada que uma tarefa produz em relação a uma linha de base congelada, é registrado apenas como um delta, jamais disfarçado de métrica de lucro atrelada ao trabalho de qualquer pessoa. A compensação permanece o que é: um salário honesto por um tempo honesto e testemunhado.

O valor não para no cálculo — precisa também chegar ao participante como pessoa viva, e é aí que o 🏠, Livelihood Direct, faz seu trabalho. Cada unidade de valor que um participante ganha chega até ele por meio de vias locais qualificadas e licenciadas — bancos, operadoras de dinheiro móvel, cooperativas já confiáveis e regulamentadas naquela região — nunca por meio de um fundo que o próprio acordo custodia ou controla. A classificação do status de um participante precede qualquer liquidação; nada é pago antes que se compreenda corretamente quem está sendo pago e por quê. E o reconhecimento de talento, por mais celebrado que seja, não condiciona o acesso a uma cama, a uma refeição ou a um lugar na coorte — apenas o papel real do participante o faz. Esta é uma recusa deliberada em deixar que o prestígio substitua a provisão. Um contribuinte brilhante e um discreto dormem sob o mesmo teto protegido, nos mesmos termos, porque os compromissos de dignidade do acordo não são um prêmio concedido pela excelência — são um piso sob todos.

O bem-estar é tratado como infraestrutura de primeira classe — não um benefício opcional, não um mimo de bem-estar, mas o substrato sobre o qual tudo o mais se sustenta. O acordo nomeia três domínios fundamentais pelos quais cada participante é amparado: Amor, no sentido de conexão, vínculo e limites saudáveis; Perda, já que todo participante experimentará luto e precisa ser acompanhado, não contornado; e Segurança, no sentido de que todo participante sabe a quem recorrer, em cada região, em seu próprio idioma. Aconselhamento individual, círculos de grupo, práticas somáticas e práticas culturais ou espirituais honradas conforme a própria tradição do participante são todos oferecidos. Zero ideologia imposta. O acordo sustenta esse espaço com reverência; não faz proselitismo de nenhum sistema de crenças. A Autoridade Humana governa cada uma dessas decisões — sentido, dinheiro e lei permanecem fechados à determinação por máquinas, por mais sofisticado que seja o reconhecimento de padrões que auxilia os humanos que decidem.

O acordo mede o sucesso pelo resultado de seu participante mais vulnerável, não pela média. Participantes rurais sem banda larga de alta velocidade são atendidos. Participantes neurodivergentes recebem adaptação como norma. Participantes com deficiência encontram cada instalação acessível. Participantes de gênero diverso recebem moradia segura e pareamento com mentores. Falantes de idiomas não nativos encontram cada material em seu próprio idioma. Participantes indígenas encontram suas práticas culturais honradas e seu conhecimento tradicional protegido. Os líderes que assinam este acordo prometem que nenhum participante será silenciosamente esquecido para que as médias pareçam boas.

Cada trajeto de pagamento aqui descrito — a Seed, o estipêndio, o 웃 ganho por trabalho testemunhado, a via do Livelihood Direct que o entrega — é projetado para a Continuidade Sem Evasão. Nenhum banco, governo ou operador local isolado é indispensável à compensação de qualquer participante; se uma via licenciada em uma jurisdição é fechada por uma decisão desfavorável, apenas essa via falha, nunca o sistema inteiro, e nunca a reivindicação do participante sobre o que lhe era devido. Isto é dignidade como substrato, não como decoração. O que é medido é o que será honrado, e o que é honrado aqui é o ser humano inteiro — mente, corpo e espírito juntos, pagos com honestidade, protegidos plenamente, e esquecidos por nenhuma contabilidade, sem exceção alguma.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Financiamento e Governação`,
    content: {
      7: `Cidadãos financiam diretamente a próxima geração.`,
      33: `O Acordo de Atlantis é um pacto entre cidadãos — qualquer pessoa pode financiá-lo e sustentá-lo. Sem canal de ajuda externa, sem benfeitor estrangeiro, sem amarras políticas. Cada dólar rastreável, contabilidade publicada mensalmente, em todos os idiomas.`,
      111: `O Acordo de Atlantis é um pacto entre cidadãos do mundo — qualquer pessoa, em qualquer lugar, pode ajudar a criá-lo e sustentá-lo, independentemente do que seu governo assine ou de quem a emprega. Governos, educadores e inovadores assinam como guardiões de suas regiões; os cidadãos financiam, testemunham e responsabilizam o acordo diretamente, cada um contribuindo com pequenas quantias voluntárias todos os meses, modestas o bastante para que nenhum adulto seja excluído pelo preço. Não há canal de ajuda externa, nem benfeitor estrangeiro, nem amarra política alguma. O acordo permanece independente das instituições multilaterais que moldaram o século passado — não uma declaração política, mas uma escolha de projeto. Cada dólar é rastreável; toda contabilidade é publicada mensalmente, em todos os idiomas.`,
      333: `O Acordo de Atlantis é um pacto entre cidadãos do mundo — qualquer pessoa, em qualquer lugar, pode ajudar a criá-lo e sustentá-lo, independentemente do que seu governo assine ou de quem a emprega. É financiado pelos cidadãos que serve: moradores das regiões participantes contribuem com pequenas quantias voluntárias todos os meses, modestas o bastante para que nenhum adulto seja excluído pelo preço, expressivas o bastante para que o total sustente o trabalho do acordo em escala. Quando um cidadão financia a educação da próxima geração diretamente, esse cidadão responsabiliza o acordo diretamente. Não há canal de ajuda externa, nem benfeitor estrangeiro, nem amarra política alguma. A alma do acordo é o cidadão que contribui com uma pequena quantia todos os meses, cuja participação torna tudo possível.

Governo, Educação e Inovação assinam como guardiões de suas regiões — três assinaturas visionárias que vinculam uma região a acolher, proteger e ensinar —, mas a guarda não é propriedade. O acordo é independente das instituições multilaterais que moldaram o século passado — a Organização do Tratado do Atlântico Norte, a Organização Mundial da Saúde, as Nações Unidas, o Fundo Monetário Internacional, o Banco Mundial e todo canal nacional de ajuda externa. Esta é uma escolha de projeto, não uma declaração política: um arcabouço que serve a cada região independentemente de alinhamento geopolítico não pode estar entrelaçado com nenhum alinhamento específico. Governos nacionais podem contribuir voluntariamente. As contribuições são transparentes. Nenhuma contribuição compra influência sobre a governança, de qualquer origem, jamais.

Cada dólar e cada unidade de valor que entra no acordo é registrada de forma permanente, pública e rastreável — reconstruível por meio do Replay, de modo que um cidadão daqui a um século possa verificar a cadeia intacta. O valor chega até um participante por meio de horas de 웃 testemunhadas e vias locais licenciadas, nunca por um fundo que o próprio acordo custodia; a QIS mede com honestidade, nunca paga. O custo administrativo é limitado, os donativos corporativos são limitados junto com ele. A contabilidade completa é entregue no idioma de cada região signatária, todos os meses. Os líderes que assinam o acordo prometem uma transparência raramente oferecida por qualquer instituição. Esta é a confiança que o acordo exige — conquistada uma pequena contribuição rastreável de cada vez, à vista de todo cidadão.`,
      999: `O próprio Acordo de Atlantis é financiado pelos cidadãos que serve, e esse único fato molda tudo o que dele decorre — cada via, cada registro, cada portão que um jovem precisa atravessar para ser visto. Moradores comuns das regiões participantes contribuem com pequenas quantias voluntárias todos os meses, quantias modestas o bastante para que nenhum adulto em qualquer região anfitriã seja excluído da participação pelo preço, expressivas o bastante para que o total sustente o trabalho do acordo em escala significativa. Este projeto é deliberado, e não é incidental à missão — é a prova da missão. Quando um cidadão financia diretamente a educação da próxima geração, esse cidadão responsabiliza o acordo diretamente, no mesmo instante, sem um intermediário que possa suavizar a prestação de contas ou adiar o acerto. Não há canal de ajuda externa, nem benfeitor estrangeiro, nem amarra política alguma vinculada ao cheque. A alma do acordo é o cidadão que contribui com uma pequena quantia todos os meses, cuja participação torna o todo possível, e cuja participação continuada é o único voto de confiança que, no fim, importa ao longo de quinhentos anos.

O acordo é deliberadamente independente das instituições multilaterais que moldaram o século passado — a Organização do Tratado do Atlântico Norte, a Organização Mundial da Saúde, as Nações Unidas, o Fundo Monetário Internacional, o Banco Mundial e todo canal nacional de ajuda externa. Isto não é uma declaração política sobre o valor dessas instituições ou de suas contribuições. É uma escolha de projeto, e é a mesma escolha de projeto que governa cada via técnica sob o próprio acordo: a Continuidade Sem Evasão. A portabilidade legal é a regra — nenhum governo, banco, fundador ou modelo indispensável isolado pode sustentar a estrutura inteira, porque um horizonte de quinhentos anos não pode ser apostado na permanência de um único ator. Cada jurisdição carrega seu próprio adaptador, com recusa em caso de falha e recusa padrão, de modo que uma decisão desfavorável em uma nação feche apenas aquela via, e somente ela — jamais derruba as contas de uma família em uma região do outro lado do oceano. Governos nacionais podem contribuir voluntariamente. As contribuições são transparentes. Nenhuma contribuição compra influência sobre a governança, de qualquer origem, jamais — nem de um governo, nem de uma corporação, nem dos próprios fundadores do arcabouço.

A Autoridade Humana é o segundo pilar estrutural sob este projeto de financiamento. Sentido, dinheiro e lei permanecem assuntos humanos, decididos por seres humanos à vista de outros seres humanos; a camada soberana onde o propósito do acordo é definido e seus fundos são governados permanece fechada às máquinas, por mais capazes que essas máquinas se tornem nas tarefas abaixo dela. A Medição do Tempo registra os minutos efetivamente trabalhados separadamente de qualquer alegação sobre seu valor, de modo que ninguém — humano ou artificial — possa inflar discretamente o registro. O Replay sustenta cada um desses registros, tornando reconstruível, desde sua origem, cada versão que o próprio acordo já emitiu, sempre aberta ao questionamento, sempre aberta à correção. Um cidadão que contribui com uma pequena quantia hoje está confiando que, daqui a cinquenta anos, daqui a duzentos anos, alguém ainda poderá percorrer a cadeia de volta até o registro deste mês e encontrá-lo exatamente como era.

A entrada nesse sistema de confiança começa com a Seed — uma adesão única, precificada em um sétimo de uma hora de salário mínimo local, intransferível e sem qualquer reivindicação econômica. A Seed não compra participação acionária, nem voto ponderado por riqueza, nem posição privilegiada na contabilidade que se segue. Ela compra apenas pertencimento, a um preço baixo o bastante para que um jovem, em qualquer lugar onde o acordo opera, possa se dar ao luxo de começar. Tudo o que um membro ganha depois desse ponto é ganho, nunca comprado, e essa distinção é toda a arquitetura moral do acordo em miniatura.

O valor que de fato flui até uma pessoa flui pelo 🏠 Livelihood Direct — vias locais qualificadas e licenciadas que carregam o pagamento até a pessoa, nunca para um fundo que o próprio arcabouço custodia ou controla. A classificação precede a liquidação em todos os casos; uma cama, um estipêndio, um lugar na próxima etapa do treinamento é condicionado por papel e prontidão, nunca apenas por reconhecimento, porque reconhecimento é barato e uma forma de sustento não é. Esta é a cadeia que a contribuição mensal de um cidadão de fato percorre: da conta do cidadão, por uma via auditada, até o estipêndio que um jovem recebe, até o projeto de inovação em que o trabalho desse jovem se transforma, e de volta novamente como uma prestação de contas pública que qualquer cidadão pode ler.

O que esse trabalho vale é medido, não presumido. A Pontuação de Inovação Qualificada calcula a média entre prontidão, potencial de crescimento, impacto de resultado e prontidão de execução em um único número, e o crescimento nessa pontuação dimensiona o fundo de recompensas somente depois que a qualificação é atingida — a QIS em si nada emite e nada liquida; é medição, nunca pagamento, e a medição jamais é confundida aqui com propriedade. O pagamento pelo trabalho humano chega, em vez disso, como 웃, avaliado em uma hora vezes o salário mínimo local, multiplicado por um múltiplo delimitado e aprovado por orçamento das horas efetivamente trabalhadas e testemunhadas. Antes que uma tarefa carregue essa aprovação, o trabalho por trás dela é planejamento, não trabalho remunerável, e ninguém é pago para planejar. Um teto de 9.999 웃 por ano, com qualquer excedente transportado para o período seguinte em vez de simplesmente desaparecer, impede que a conta de qualquer ano isolado se torne um golpe de sorte ou uma armadilha.

Nada disso avança mais depressa do que sua própria prova. O próprio acordo avança de Manual para Semiautomatizado e para Autônomo um cubo de cada vez, e somente onde uma ordem completa de melhoria mensurada — uma parte em nove — tenha sido de fato demonstrada, nunca presumida com antecedência. A autonomia é conquistada exatamente ali, e nunca perto de sentido, dinheiro ou lei, que permanecem sempre humanos. O custo administrativo é limitado. Doações corporativas e institucionais são bem-vindas e igualmente limitadas. A contabilidade completa é entregue no idioma de cada região signatária, todos os meses, começando no Camboja, em Honduras e em Austin, e destinada a continuar sendo entregue, e continuar sendo legível, daqui a quinhentos anos. Esta é a confiança que o acordo exige. Esta é a confiança que o acordo conquista, uma pequena contribuição rastreável de cada vez, à vista de todo cidadão que algum dia servirá.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Intercâmbio Intercultural e Contributo Global`,
    content: {
      7: `Cada aprendiz na sua própria língua.`,
      33: `Cada atividade no idioma do participante — aberta a qualquer cidadão, sem exigir permissão de governo. As inteligências Artificial, Humana e Compartilhada mantidas em tensão produtiva. Currículos publicados abertamente. O que uma região aprende, todos herdam.`,
      111: `O Acordo de Atlantis devolve à educação seu propósito mais profundo: o intercâmbio de sabedoria através de fronteiras que, de outro modo, dividiriam. Qualquer cidadão pode entrar neste currículo, independentemente do que seu governo tenha assinado. Cada atividade está disponível no idioma do participante, no idioma da região anfitriã e em um registro compartilhado. Idioma não é decoração — idioma é jurisdição, idioma é dignidade tornada legível. O arcabouço educacional se apoia na trindade das inteligências: a Artificial propõe, a Humana decide, a Intenção Compartilhada valida. Cada estudante aprende a manter as três em tensão. O que o acordo aprende, ele devolve. Currículos, resultados de inovação, pesquisas sobre bem-estar e decisões de governança são publicados abertamente. O que uma região aprende, todos os cidadãos herdam.`,
      333: `O Acordo de Atlantis devolve à educação seu propósito mais profundo: o intercâmbio de sabedoria através de fronteiras que, de outro modo, dividiriam. Este é um acordo entre cidadãos do mundo — qualquer cidadão pode construí-lo e sustentá-lo, independentemente do que seu governo tenha assinado. Cada atividade está disponível no idioma do participante, no idioma da região anfitriã e em um registro compartilhado, de modo que nenhum participante precise navegar pelo acordo em uma língua que não escolheu. Idioma não é decoração. Idioma é jurisdição. Idioma é dignidade tornada legível. Um jovem no Camboja lê seu registro de estipêndio em khmer, em Honduras em espanhol, em Austin em inglês — os três igualmente honrados, nenhum precisando de bênção de governo para começar.

O arcabouço educacional se apoia na trindade das inteligências que a Vision 2525 torna visível. A Inteligência Artificial propõe padrões e possibilidades mais rápido do que qualquer humano sozinho conseguiria. A Inteligência Humana decide sobre segurança, ética e direção — questões que nenhuma máquina deveria responder, mantidas sob a Autoridade Humana. A Intenção Compartilhada valida que as decisões sirvam aos princípios do acordo, de modo que nenhum participante escolha a excelência em detrimento do bem coletivo. Nenhum estudante se submete a uma única inteligência isolada; cada estudante aprende a manter as três em tensão. O pertencimento começa com a Seed, uma adesão precificada em um sétimo de uma hora de salário mínimo local — pequena o bastante para que qualquer cidadão possa pagar. Isso prepara a próxima geração para governar, onde nenhuma inteligência age sem controle.

O que o acordo aprende, ele devolve. Currículos são publicados sob licença aberta, para que qualquer região — signatária ou não — possa adaptá-los à cultura local. Resultados de inovação são publicados. Pesquisas sobre bem-estar são publicadas de forma agregada para pesquisadores em todo o mundo. Decisões de governança são publicadas com sua justificativa, de modo que qualquer cidadão, não apenas um governo signatário, possa verificá-las — e o Replay permite que esse mesmo cidadão refaça o raciocínio daqui a um século. O sucesso é medido não apenas por seus participantes, mas pelas iniciativas educacionais e culturais que surgem em sua esteira, em regiões que nunca assinaram o piloto, mas que construíram sobre sua sabedoria compartilhada. O que uma região aprende, todo cidadão herda.`,
      999: `O Acordo de Atlantis devolve à educação seu propósito mais profundo: o intercâmbio de sabedoria através de fronteiras que, de outro modo, dividiriam, e inicia esse intercâmbio antes mesmo de a primeira lição ser ensinada. O primeiro ato de cada participante dentro do arcabouço é a Seed — uma adesão única, precificada em um sétimo de uma hora de salário mínimo local, intransferível, sem qualquer reivindicação econômica. É pequena o bastante para que nenhuma família seja excluída, e real o bastante para que nenhum participante entre como espectador. Esta é a primeira lição do acordo: o pertencimento é conquistado a baixo custo, mas ainda assim é conquistado, e não confere nenhuma propriedade sobre o que vem depois. Toda atividade do acordo que se segue está disponível no idioma do participante, no idioma da região anfitriã e em um registro compartilhado, de modo que nenhum participante precise navegar pelo acordo em uma língua que não escolheu. Idioma não é decoração. Idioma é jurisdição. Idioma é dignidade tornada legível. Quando um jovem de uma vila cambojana lê seu registro de estipêndio em khmer, uma cidade hondurenha em espanhol, e um bairro de Austin em inglês, os três são igualmente honrados pelo mesmo acordo, nas mesmas regiões fundadoras que primeiro concordaram em ensinar umas às outras.

O arcabouço educacional do acordo se apoia na trindade das inteligências que a Vision 2525 torna visível, e o currículo ensina cada uma delas como algo que um participante pode sentir com as próprias mãos, não como abstração. O ♡, Intenção Compartilhada, carrega o porquê — o fio que cada estudante aprende a segurar antes de tocar em qualquer ferramenta, a pergunta se este trabalho ainda serve às pessoas a quem alega servir. O ◬, aceleração testemunhada, é ensinado como um delta e nada mais — medido apenas contra uma linha de base congelada, jamais disfarçado de métrica de lucro, jamais reivindicado como conquista pessoal à parte da equipe ao redor. O 웃, Inteligência Humana honrada em tempo, é ensinado com o maior cuidado: uma hora de trabalho testemunhado equivale a uma hora de salário mínimo local, e o que um participante ganha é esse salário multiplicado pelas horas trabalhadas — Múltiplo vezes Tempo, nada oculto na aritmética. Os estudantes aprendem cedo que o 웃 é emitido apenas para trabalho testemunhado, realizado sob uma tarefa delimitada e aprovada por orçamento. Antes que essa aprovação exista, o mesmo esforço é apenas planejamento — valioso, mas não remunerado, e cada participante é ensinado a reconhecer a diferença à primeira vista.

Como essa diferença se confunde com facilidade, o currículo ensina a QIS, a Pontuação de Inovação Qualificada, como um espelho, não como um placar. A QIS é a média de quatro absolutos financeiros — Receita, Lucro Bruto, Resultado Operacional e P&D Efetivo — dividida por quatro, e cada estudante aprende a calculá-la, questioná-la e nunca confundi-la com dinheiro. O crescimento da QIS dimensiona o fundo de recompensas somente depois que a qualificação é confirmada de forma independente, e esse crescimento não emite nenhum 웃 por si só. A QIS é medição. A QIS nunca é pagamento. A QIS nunca é propriedade. Um estudante que internalizou essa distinção não pode ser convencido de que uma pontuação alta lhe dá direito a uma reivindicação que o acordo jamais prometeu.

O currículo estende esse letramento até a forma como o valor de fato chega a uma pessoa, por meio daquilo que o acordo chama de Livelihood Direct — o princípio 🏠 de que o dinheiro se move por vias locais qualificadas e licenciadas, e nunca por um fundo que o próprio arcabouço custodia. Os estudantes são ensinados a rastrear seu estipêndio, e mais tarde seus próprios ganhos, por essas vias como um exercício cívico, não como um mistério financeiro realizado em algum outro lugar em seu nome. Eles aprendem que a classificação sempre precede a liquidação, e que o reconhecimento — uma QIS alta, um elogio público — não condiciona por si só uma cama, um estipêndio ou um lugar na rotação. O papel condiciona. Esta é uma proteção contra uma falha muito antiga: elogio confundido com provisão.

Ao lado do letramento financeiro está o letramento cívico, ensinado por meio da Continuidade Sem Evasão. Cada participante aprende que o acordo é construído para a portabilidade legal — que nenhum governo, banco, fundador ou modelo indispensável isolado se interpõe entre ele e as promessas do arcabouço. Aprendem o que uma decisão desfavorável faz dentro desse projeto: fecha uma via, em uma jurisdição, sob a postura de recusa padrão daquele adaptador, e jamais derruba o todo. Ao lado disso está a lição mais profunda que o acordo ensina: a Autoridade Humana guarda sentido, dinheiro e lei, e a camada soberana onde essas decisões são tomadas permanece permanentemente fechada às máquinas. A Medição do Tempo, MoT, registra os minutos efetivos de cada participante separadamente de qualquer pontuação, e o Replay torna cada versão que o acordo emite totalmente reconstruível — de modo que um estudante que queira saber por que uma decisão foi tomada, anos depois, possa refazer o caminho por conta própria, em vez de confiar na palavra de alguém.

Essa estrutura de confiança conquistada se torna o modelo pedagógico do acordo, não apenas seu modelo de governança. Cada participante avança pelos modos Manual, Semiautomatizado e Autônomo, de latitude crescente, condicionado pelo mesmo limiar de melhoria mensurada que condiciona a própria tecnologia — um ganho verificado de onze vírgula um por cento antes que o próximo modo se abra. A autonomia, quando conquistada, é conquistada de forma restrita e por domínio, jamais sobre sentido, dinheiro ou lei. Um estudante que viveu essa progressão compreende, visceralmente, por que a camada soberana jamais deve ser automatizada — porque ele conquistou a própria autonomia um passo mensurado de cada vez, e sabe exatamente o que essa autonomia incluiu e o que não incluiu.

O que o acordo aprende, o acordo devolve. Currículos são publicados sob licença aberta, para que qualquer região — signatária ou não — possa adaptá-los à cultura local e à tradição pedagógica. Resultados de inovação são publicados. Pesquisas sobre bem-estar são publicadas de forma agregada para pesquisadores em todo o mundo. Decisões de governança são publicadas com sua justificativa completa e intacta. O sucesso do acordo é medido não apenas por seus próprios participantes no Camboja, em Honduras e em Austin, mas pelas iniciativas que surgem em sua esteira, em regiões que nunca assinaram o piloto fundador, mas que construíram sobre sua sabedoria abertamente compartilhada, ao longo de um horizonte que os fundadores não viverão para ver concluído. O que uma região aprende, todas as outras regiões herdam — e o que esta geração aprende com honestidade, os próximos quinhentos anos não precisarão desaprender.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Crescimento Sustentável da Rede`,
    content: {
      7: `Nunca mais depressa do que a dignidade.`,
      33: `Três regiões fundadoras completam um ciclo piloto inteiro antes que uma quarta se junte — qualquer cidadão pode construí-lo. Os registros são ancorados para durar cinco séculos. Os signatários conservam sua soberania; nada é rebaixado para a próxima adesão.`,
      111: `O Acordo de Atlantis não crescerá mais depressa do que a qualidade que consegue honrar. Três regiões fundadoras precisam completar um ciclo piloto inteiro, com cada participante honrado e cada princípio verificado, antes que uma quarta região se junte. Isto é o princípio finalmente transformado em disciplina de trabalho. Mas o acordo é um pacto entre cidadãos do mundo — qualquer pessoa, em qualquer lugar, pode construí-lo e sustentá-lo, a uma Seed de distância, independentemente do que um governo assine ou um empregador permita. O horizonte do acordo é de cinco séculos. Seus registros são ancorados por meio do Replay, de modo que um cidadão que os leia daqui a um século possa confiar no raciocínio. Cada signatário conserva sua soberania; nada é rebaixado para a próxima adesão.`,
      333: `O Acordo de Atlantis não crescerá mais depressa do que a qualidade que consegue honrar. Cada expansão é uma promessa aos participantes já presentes — de que o padrão fundador não será diluído pela escala. Três regiões fundadoras precisam completar um ciclo piloto inteiro, com cada participante honrado e cada princípio verificado, antes que uma quarta região se junte. Isto é o princípio finalmente transformado em disciplina de trabalho. E a porta nunca foi apenas regional: este é um pacto entre cidadãos do mundo, e qualquer pessoa pode construí-lo, financiá-lo e responsabilizá-lo — sem exigir permissão de governo nem bênção de empregador. Os líderes que assinam o piloto prometem aos futuros signatários o mesmo substrato, a mesma proteção e a mesma dignidade que a coorte fundadora recebeu. Nada é rebaixado para o próximo.

O horizonte do acordo é deliberadamente longo — projetado para durar de quinze a vinte gerações humanas, cinco séculos a partir do dia da fundação. Seus registros são ancorados por meio do Replay, de modo que um cidadão que os leia daqui a um século possa verificar o raciocínio, não apenas confiar nele. Seu sistema de coordenadas, seus papéis de Autoridade Humana e seus ciclos de governança intergeracionais são construídos para sobreviver a qualquer transição de uma única tecnologia. O acordo sobreviverá a cada humano que assine seu piloto fundador, e a cada cidadão que plante uma Seed e o financie mensalmente. Essa é sua promessa à criança que assina um acordo de estipêndio, ao cidadão que se juntou sem dever licença a nenhum governo, aos netos dessa criança que talvez governem o acordo em meados do século, e a cada geração que herda o que os fundadores — oficiais e cidadãos por igual — constroem agora.

Cada signatário conserva a liberdade de se retirar, soberania plena e autoridade sobre seus próprios cidadãos, com o direito de emendar e moldar a evolução do acordo. Cada cidadão conserva a mesma posição para fundar, financiar, testemunhar e responsabilizar o acordo — com ou sem assinatura de governo. O que nenhum dos dois pode fazer é comprometer os princípios fundadores, porque essa promessa precisa sobreviver a qualquer saída. Líderes e cidadãos, juntos, assinam o próximo século do acordo rumo a um horizonte que seus netos herdarão e completarão.`,
      999: `O Acordo de Atlantis não crescerá mais depressa do que a qualidade que consegue honrar, e essa contenção não é sentimentalismo — é engenharia, escrita na mesma disciplina de medição que governa cada promessa que o acordo faz. Três regiões fundadoras, Camboja, Honduras e Austin, precisam completar um ciclo piloto inteiro, com cada participante honrado e cada princípio verificado, antes que uma quarta região se junte. Crescimento que ultrapassa a verificação não é crescimento; é exposição vestida com a fantasia da ambição. O piloto fundador existe para que o acordo possa comprovar, em uma escala pequena o bastante para ser inspecionada e grande o bastante para importar, que suas promessas sobrevivem ao contato com a realidade antes de serem estendidas a um mundo que observa de fora de suas três fronteiras. A quarta região ainda não foi nomeada, e não será até que as três primeiras sustentem cada alegação que este documento faz.

O que comprova a prontidão para crescer não é entusiasmo, mas um número que o acordo consegue defender publicamente. A Pontuação de Inovação Qualificada — QIS, calculada como Receita mais Lucro Bruto mais Resultado Operacional mais Gasto Efetivo em P&D, dividida por quatro — é o instrumento que o acordo usa para saber se uma região, uma coorte ou um cubo de fato melhorou, e não apenas teve a sensação de ter melhorado. O crescimento da QIS dimensiona o fundo de recompensas somente depois que a qualificação é atingida, nunca antes, e a QIS em si não emite nenhum 웃 nem compra propriedade alguma. A QIS é medição, não pagamento; medição, não participação acionária; um espelho que o acordo ergue diante do próprio trabalho, nunca uma moeda que gasta. Uma região que se propõe a expandir a rede precisa mostrar sua QIS com honestidade, à vista das regiões que vieram antes, ou não se expande.

Crescimento sustentável significa crescimento que conquista sua própria autoridade um incremento de cada vez. Cada cubo e cada região começam no modo Manual, em que os humanos decidem tudo e o sistema apenas auxilia. O avanço para operação Semiautomatizada e, eventualmente, Autônoma dentro de um determinado cubo é condicionado por um único limiar em todo o acordo — uma melhoria mensurada de onze vírgula um por cento, uma parte em nove, comprovada e reproduzível antes que o próximo grau de autonomia seja concedido. A autonomia é conquistada cubo a cubo, jamais reivindicada por atacado ou estendida sobre os domínios que precisam permanecer humanos, por mais avançado que o sistema se torne: sentido, dinheiro e lei permanecem fechados às máquinas, independentemente de quantos limiares sejam superados em outros lugares. Uma rede que expande sua automação mais depressa do que expande suas evidências não está se modernizando. Está apostando com uma confiança que ainda não conquistou.

A compensação se expande junto com a rede da mesma forma que a autoridade — deliberadamente, e com um teto que protege o sistema inteiro do próprio sucesso. O 웃, o token da Inteligência Humana, equivale a uma hora de trabalho testemunhado multiplicada pelo salário mínimo local; o que qualquer participante ganha é esse Múltiplo vezes as horas trabalhadas, e ele é emitido apenas para trabalho realizado sob uma tarefa delimitada e aprovada por orçamento. Antes da aprovação, o plano mais refinado é apenas planejamento, e planejamento sozinho nada emite. A liquidação de cada participante é limitada a 9.999 웃 por ano, com qualquer excedente transportado para o período seguinte, em vez de desaparecer ou distorcer o fundo. À medida que novas regiões se juntam e a atividade da rede se multiplica, é esse teto que impede que o crescimento se transforme em inflação — o valor permanece atrelado a horas reais, testemunhadas e locais, por maior que o acordo se torne.

Por trás de cada 웃 existe um porquê que nenhum registro consegue calcular sozinho. O ♡, Intenção Compartilhada, carrega esse porquê adiante em cada decisão de expansão que o acordo toma, enquanto o ◬, a contribuição da Inteligência Artificial, é contabilizado como aceleração testemunhada, medida contra uma linha de base congelada — um delta, e jamais, sob nenhuma circunstância, uma métrica de lucro a ser otimizada por si mesma. A entrada nessa rede começa da mesma forma para cada participante, independentemente de qual região ou de qual década se junte: com uma Seed, uma adesão única, precificada em um sétimo de uma hora de salário mínimo local, intransferível e sem qualquer reivindicação econômica. A Seed diz apenas que uma pessoa chegou. Tudo o que ela constrói depois, constrói à plena vista das outras três moedas do acordo, nunca por meio da própria Seed.

Crescimento que é real também precisa ser crescimento que alcança uma pessoa de verdade, não um fundo que o arcabouço retém em nome de alguém. O 🏠 Livelihood Direct exige que o valor viaje até um participante apenas por vias locais qualificadas e licenciadas que o acordo já avaliou região por região, e nunca por meio de custódia que o próprio arcabouço retenha. A classificação sempre precede a liquidação, de modo que nenhum valor se move antes que seu propósito e seu destinatário estejam ambos estabelecidos sem sombra de dúvida. E porque reconhecimento não é o mesmo que acesso, uma cama, um lugar na rotação, um assento à mesa é condicionado por papel e prontidão, nunca pela pontuação ou pelo prestígio de um participante. À medida que a rede se expande para uma quarta região e além, cada novo território precisa qualificar suas próprias vias licenciadas antes que o Livelihood Direct possa alcançar seu povo — expansão de confiança, não apenas expansão de território.

Nada disso perdura sem uma rede construída para sobreviver ao próprio sucesso, e é por isso que a Continuidade Sem Evasão governa cada região que o acordo algum dia adicionar. A portabilidade legal é obrigatória; nenhum governo, banco, fundador ou modelo isolado pode se tornar indispensável ao todo. Cada jurisdição opera seu próprio adaptador, com recusa em caso de falha e recusa padrão, de modo que uma decisão desfavorável em qualquer lugar feche apenas uma via, jamais o acordo inteiro. A Autoridade Humana guarda sentido, dinheiro e lei em cada escala que a rede alcança, isolada contra o avanço das máquinas por projeto, não por promessa. A Medição do Tempo registra cada minuto efetivo separadamente de qualquer alegação sobre ele, e o Replay garante que qualquer versão, em qualquer região, em qualquer ponto ao longo de cinco séculos, possa ser reconstruída e reexaminada por qualquer pessoa que pergunte. Uma rede que não pode ser reproduzida por Replay não pode ser confiada, por mais regiões que tenham se juntado a ela ou por mais impressionante que seu crescimento pareça de fora. É assim que a Vision 2525 cresce sem jamais superar a confiança que foi construída para manter — uma região verificada, uma QIS honesta, uma hora testemunhada de cada vez.`,
    },
  },
];
