import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_PT: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Onde a Inovação Começa`,
    content: {
      7: `Líderes iniciam o que nenhum século iniciou.`,
      33: `Três regiões — Camboja, Honduras, Austin — comprometem-se a acolher jovens aprendizes, protegê-los e entregar-lhes as ferramentas do futuro. Governo, Educação, Inovação: três assinaturas visionárias por região. Um começo comum.`,
      111: `O Atlantis Accords é uma promessa feita por líderes dispostos a iniciar algo que ainda não existiu. Os seus signatários fundadores no Camboja, em Honduras e em Austin, Texas foram escolhidos por uma qualidade rara: a disposição de confiar aos jovens as ferramentas do futuro enquanto ainda há tempo de as ensinar. Ao assinar o acordo, a região compromete-se a acolher aprendizes de várias culturas, contribuir com aquilo que só ela pode oferecer de forma singular, e sustentar-se num padrão mais alto do que a regulamentação atual exige. Três assinaturas visionárias — Governo, Educação, Inovação — entram no acordo em conjunto. Três visionários, três regiões, um mesmo começo partilhado.`,
      333: `Cada civilização é lembrada por aquilo que escolheu começar. O Atlantis Accords é uma promessa feita por líderes dispostos a iniciar algo que ainda não existiu — um alicerce comum para a inovação humana ordinária que alcance cada canto do mundo, honre cada voz e perdure através das gerações. Os seus signatários fundadores no Camboja, em Honduras e em Austin, Texas não foram escolhidos pelo poder económico, pela força militar ou pelo prestígio institucional. Foram escolhidos por uma qualidade mais rara: a disposição de confiar aos jovens as ferramentas do futuro. É isto que significa liderar no século que se aproxima — a coragem de entregar as chaves à próxima geração enquanto ainda há tempo de lhes ensinar a conduzir.

O acordo é convocado pela eXeL, uma força organizadora concebida propositadamente para este momento. A eXeL existe deliberadamente fora dos canais tradicionais de coordenação que moldaram o século passado — fora das estruturas dos tratados diplomáticos, fora das burocracias multilaterais, fora dos enredamentos políticos de qualquer Estado-nação. A eXeL é o convocador de confiança que reúne líderes visionários em torno de um enquadramento partilhado, de um mesmo motor e de um horizonte comum de quinhentos anos. Cada signatário conserva soberania plena, autoridade plena sobre os seus cidadãos, e liberdade plena para se retirar a qualquer momento. O que os signatários ganham é o efeito de rede que só um enquadramento construído para este fim pode oferecer. Isto é coordenação sem nenhuma forma de dominação política.

Assinar o acordo é assinar uma promessa. Que a região acolherá jovens aprendizes de várias culturas. Que a região contribuirá com aquilo que só ela pode oferecer de forma singular. Que a região se sustentará num padrão mais alto do que a regulamentação atual exige. Que a região o fará publicamente, com transparência, à vista de todos os cidadãos que serve. São exigidas três assinaturas de cada região — Governo, Educação e Inovação. Nenhum cargo isolado obriga sozinho o acordo. São precisos três visionários para dizer sim. Três visionários, três regiões, um começo — é assim que qualquer enquadramento entra em vida, através da confiança mútua dos líderes dispostos a assiná-lo.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Aprender Através da Simulação`,
    content: {
      7: `Praticar mil vezes antes de tocar.`,
      33: `Nada de consequência se aprende primeiro em equipamento real. Cada participante pratica em simulação, roda por três regiões, celebra publicamente. Isto é respeito pelo jovem humano cujo primeiro erro nunca deveria custar uma vida.`,
      111: `Toda disciplina que vale a pena dominar foi aprendida por alguém antes de ser conhecida. O Atlantis Accords devolve esta antiga sabedoria ao centro da forma como os jovens são preparados para construir o futuro. Nada de consequência se aprende primeiro em equipamento real, em pessoas reais ou em condições irreversíveis. Cada participante pratica em simulação até a prática se tornar competência, e a competência se tornar prontidão. O modelo de rotação conduz cada participante pelas três regiões fundadoras, e cada rotação termina numa celebração pública e cooperativa aberta à comunidade anfitriã mais ampla. Isto é respeito pelo jovem humano cujo primeiro erro nunca deveria custar uma vida.`,
      333: `Toda disciplina que vale a pena dominar foi aprendida por alguém antes de ser conhecida. Os mestres artesãos ensaiam antes da atuação, os pilotos ensaiam antes do voo, os médicos ensaiam antes da cirurgia, e as crianças ensaiam o mundo através do brincar. O Atlantis Accords devolve esta antiga sabedoria ao centro da forma como os jovens são preparados para construir o futuro. Nada de consequência se aprende primeiro em equipamento real, em pessoas reais ou em condições irreversíveis. Cada participante pratica em simulação até a prática se tornar competência, e a competência se tornar prontidão. Isto não é cautela — é respeito pelo jovem humano cujo primeiro erro nunca deveria custar a vida a ninguém.

O modelo de rotação do acordo conduz cada participante pelas três regiões fundadoras. O que se aprende no Camboja refina-se em Honduras e completa-se em Austin. O que se descobre em Austin é questionado no Camboja e integrado em Honduras. Cada participante vive, aprende e é orientado através de culturas que, de outro modo, permaneceriam distantes. O currículo de formação bebe de tradições de simulação disciplinada oriundas de muitas culturas — da tradição estratégica de Sun Tzu, da prática-como-jogo de Musashi, da teoria cíclica de aprendizagem de Ibn Khaldun, da dialética monástica de Nalanda, do simulador civil de voo — sintetizadas para respeitar cada estágio cognitivo e cada herança cultural. Nenhuma tradição isolada domina.

Cada rotação termina numa celebração pública e cooperativa aberta à comunidade anfitriã mais ampla. Vizinhos, famílias e visitantes curiosos reúnem-se para ver o que a coorte aprendeu. Estes eventos tornam a tecnologia sofisticada acessível e celebrada, em vez de assustadora. Uma sociedade que cresce a compreender sistemas cooperativos através do brincar não pode ser facilmente manipulada pelo medo desses mesmos sistemas. Isto é dissuasão pela educação, não dissuasão pela força. A promessa do acordo a cada pai e mãe: a vossa criança praticará mil vezes em segurança antes de tocar em algo que a possa ferir, e a comunidade testemunhará o seu crescimento em cada passo do caminho. É assim que o respeito pelo jovem humano se traduz quando é gravado num enquadramento, e é isto que a liderança entrega à próxima geração de participantes antes que essa geração o tenha de exigir.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Segurança Verificada Antes de Estender a Confiança`,
    content: {
      7: `Segurança provada primeiro, depois confiança.`,
      33: `Cada instalação e cada rotação estão dentro de um envelope protetor com aviso prévio. O hardware recusa a militarização. Os registos sobrevivem à turbulência. A segurança é engenheirada em torno do participante mais jovem todos os dias.`,
      111: `Antes de a confiança ser estendida, a segurança deve ser provada. O Atlantis Accords faz deste o seu compromisso fundador. Cada instalação do acordo, cada rota de rotação, cada lugar onde um jovem participante dorme ou estuda está dentro de um envelope protetor documentado, com capacidade de aviso precoce que dá à comunidade horas, e não minutos, para responder a qualquer risco credível. Cada dispositivo, cada sensor, cada sistema de coordenação está vinculado ao nível do hardware a recusar reconfiguração para integração com sistemas de armas. Isto não é política — é física. O acordo é concebido para permanecer honrado através da turbulência: instabilidade política, contração de financiamento, ciberataque ou perturbação nas viagens. Cada cenário está planeado, e cada plano coloca a dignidade humana como primeiro requisito de conceção.`,
      333: `Antes de a confiança ser estendida, a segurança deve ser provada. O Atlantis Accords faz deste o seu compromisso fundador. Cada instalação do acordo, cada rota de rotação, cada lugar onde um jovem participante dorme ou estuda está dentro de um envelope protetor documentado, com capacidade de aviso precoce que dá à comunidade horas, e não minutos, para responder a qualquer risco credível. A tecnologia usada para proteger os participantes é a mesma tecnologia que o acordo lhes ensina a construir — sensores, coordenação, sobrevivência das comunicações, inteligência distribuída. Os jovens aprendem segurança de dentro para fora, na sua própria língua e na sua própria região, não porque lhes dizem que estão seguros, mas porque veem como a segurança é engenheirada à sua volta todos os dias.

O acordo faz uma promessa inquebrável sobre aquilo em que a sua tecnologia não pode transformar-se. Cada dispositivo, cada sensor, cada sistema de coordenação está vinculado ao nível do hardware a recusar reconfiguração para integração com sistemas de armas. Isto não é linguagem de política. Isto não é aspiração. É uma impossibilidade física, imposta criptograficamente, verificada por cada região signatária e passível de inspeção por cada cidadão. As ferramentas que protegem uma criança em Phnom Penh não podem ser reconfiguradas para ferir uma criança em Austin. As ferramentas que ligam um exercício de enxame em Tegucigalpa não podem ser reconfiguradas para visar um humano em lugar algum. Esta é a resposta do acordo a um século de medo do duplo uso. Não é política — é física.

O acordo é concebido para permanecer honrado através da turbulência. Se uma região signatária perder estabilidade política, os participantes são acolhidos pelas restantes regiões. Se o financiamento se contrair, as bolsas dos participantes são protegidas primeiro, antes da administração e das infraestruturas. Se os registos digitais forem atacados, os arquivos offline persistem. Se as viagens se tornarem impossíveis, o substrato continua virtualmente. Cada cenário está planeado, e cada plano coloca a dignidade humana como primeiro requisito de conceção. Os líderes que assinam este acordo estão a assinar a promessa de que a segurança é engenheirada, não pressuposta. O que eles estendem aos seus cidadãos não é apenas oportunidade, mas proteção construída ao padrão que o participante mais jovem merece — a mesma proteção que qualquer líder exigiria para o seu próprio filho a atravessar sozinho uma fronteira desconhecida.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Compensação, Bem-Estar e Dignidade Humana`,
    content: {
      7: `Uma bolsa, um mentor, um lar.`,
      33: `Cada participante recebe uma bolsa de subsistência desde o primeiro dia. Amor, perda e segurança são tratados como infraestrutura de primeira classe. O sucesso mede-se pelo participante mais vulnerável, nunca pela média. Dignidade como substrato, não decoração.`,
      111: `O Atlantis Accords trata cada participante como um ser humano completo desde o primeiro dia. Uma bolsa é atribuída a partir do momento em que a participação começa, indexada ao custo de vida da região para que o seu impacto respeite a dignidade local do trabalho. O bem-estar é tratado como infraestrutura de primeira classe — não como benefício opcional, não como regalia de bem-estar, mas como o substrato sobre o qual tudo o resto assenta. Três domínios fundamentais são apoiados: Amor, Perda e Segurança. O acordo mede o sucesso pelo resultado do seu participante mais vulnerável, não pela média. Nenhum participante será silenciosamente esquecido para que as médias pareçam bem. Dignidade como substrato, não decoração.`,
      333: `O Atlantis Accords trata cada participante como um ser humano completo desde o primeiro dia. Uma bolsa é atribuída a partir do momento em que a participação começa, indexada ao custo de vida da região para que o seu impacto respeite a dignidade local do trabalho. A bolsa chega antes de as obrigações familiares se tornarem emergências, e antes de a dignidade ser comprometida. Sinaliza a cada jovem que o seu tempo é valioso, o seu contributo é antecipado, e a estabilidade da sua família faz parte da responsabilidade do acordo. Isto não é caridade. É o reconhecimento de que a inovação humana ordinária requer, primeiro, segurança humana ordinária. Uma mente não pode florescer enquanto o seu lar está sob ameaça.

O bem-estar é tratado como infraestrutura de primeira classe — não como benefício opcional, não como regalia de bem-estar, mas como o substrato sobre o qual tudo o resto assenta. O acordo nomeia três domínios fundamentais através dos quais cada participante é apoiado: Amor, no sentido de vínculo, ligação e limite saudável; Perda, uma vez que cada participante experimentará o luto e deverá ser acompanhado, não contornado; e Segurança, no sentido de que cada participante sabe a quem ligar, em cada região, na sua própria língua. Aconselhamento individual, círculos de grupo, práticas somáticas e práticas culturais ou espirituais honradas conforme a tradição de cada participante são todos disponibilizados. Nenhuma ideologia é imposta. O acordo mantém o espaço com reverência; não faz proselitismo de nenhum sistema de crenças.

O acordo mede o sucesso pelo resultado do seu participante mais vulnerável, não pela média. Os participantes rurais sem banda larga são servidos. Os participantes neurodivergentes recebem acomodação como norma. Os participantes com deficiência encontram cada instalação acessível. Os participantes de género diverso recebem alojamento seguro e mentoria emparelhada. Os falantes de línguas não maternas encontram cada artefacto na sua língua. Os participantes indígenas encontram as suas práticas culturais honradas e o seu conhecimento tradicional protegido. Os líderes que assinam este acordo prometem que nenhum participante será silenciosamente esquecido para que as médias pareçam bem. Isto é dignidade como substrato, não decoração. O que se mede é o que se honrará, e o que aqui se honra é o humano inteiro — mente, corpo e espírito juntos, sem exceção alguma.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Financiamento e Governação`,
    content: {
      7: `Cidadãos financiam diretamente a próxima geração.`,
      33: `Residentes comuns contribuem com pequenas quantias mensais. Sem canal de ajuda, sem benfeitor estrangeiro, sem cordões políticos. Cada dólar é rastreável. Cada contabilidade é publicada, na língua de cada região, todos os meses, publicamente.`,
      111: `O Atlantis Accords é financiado pelos cidadãos que serve. Residentes comuns contribuem com pequenas quantias voluntárias todos os meses — modestas o suficiente para que nenhum adulto fique excluído, ressonantes o suficiente para que o total sustente o trabalho do acordo em escala significativa. Quando um cidadão financia diretamente a próxima geração, esse cidadão responsabiliza diretamente o acordo. O acordo é deliberadamente independente das instituições multilaterais que moldaram o século passado. Isto não é uma declaração política — é uma escolha de conceção. Cada dólar é registado de forma permanente e rastreável. Cada contribuição cidadã pode ser seguida desde a origem até à bolsa e à inovação. Transparência de um tipo raramente oferecido por qualquer instituição.`,
      333: `O Atlantis Accords é financiado pelos cidadãos que serve. Residentes comuns das regiões participantes contribuem com pequenas quantias voluntárias todos os meses — quantias modestas o suficiente para que nenhum adulto em nenhuma região anfitriã fique excluído da participação, ressonantes o suficiente para que o total sustente o trabalho do acordo em escala significativa. Esta conceção é deliberada. Quando um cidadão financia diretamente a educação da próxima geração, esse cidadão responsabiliza diretamente o acordo. Não há canal de ajuda, não há benfeitor estrangeiro, não há cordão político atado ao cheque. A alma do acordo é o cidadão que contribui com uma pequena quantia todos os meses, cuja participação torna o todo possível.

O acordo é deliberadamente independente das instituições multilaterais que moldaram o século passado — a Organização do Tratado do Atlântico Norte, a Organização Mundial de Saúde, as Nações Unidas, o Fundo Monetário Internacional, o Banco Mundial e cada canal nacional de ajuda externa. Isto não é uma declaração política sobre o valor dessas instituições ou dos seus contributos. É uma escolha de conceção. Dependências de ponto único comprometem a durabilidade num horizonte de quinhentos anos. Um enquadramento destinado a servir qualquer região independentemente do alinhamento geopolítico não pode ficar preso a nenhum alinhamento. Os governos nacionais podem contribuir voluntariamente. As contribuições são transparentes. Nenhuma contribuição compra influência de governação, de fonte alguma, jamais.

Cada dólar e cada unidade de valor que entra no acordo é registado de forma permanente, pública e rastreável. Cada contribuição cidadã pode ser seguida desde a sua origem até à bolsa que se torna, até ao jovem que serve, até ao projeto de inovação que emerge do trabalho desse jovem. A despesa administrativa é limitada. Os donativos corporativos e institucionais são bem-vindos e limitados. A contabilidade completa é entregue na língua de cada região signatária todos os meses. Os líderes que assinam o acordo prometem aos seus cidadãos uma transparência de um tipo raramente oferecido por qualquer instituição — transparência que permanecerá legível durante séculos após cada signatário ter deixado o cargo. Esta é a confiança que o acordo exige. Esta é a confiança que o acordo conquista, uma pequena contribuição rastreável de cada vez, à vista de cada cidadão.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Intercâmbio Intercultural e Contributo Global`,
    content: {
      7: `Cada aprendiz na sua própria língua.`,
      33: `Cada atividade disponível na língua do participante. Inteligências Artificial, Humana e Partilhada mantidas em tensão produtiva — nenhum estudante confia numa só. Currículos e resultados publicados abertamente. O que uma região aprende, todas herdam.`,
      111: `O Atlantis Accords devolve a educação ao seu propósito mais profundo: o intercâmbio de sabedoria através das fronteiras que de outro modo dividiriam. Cada atividade está disponível na língua do participante, na língua da região anfitriã e num registo partilhado canónico. A língua não é decoração — a língua é jurisdição, a língua é dignidade tornada legível. O enquadramento educativo assenta na trindade das inteligências: a Artificial propõe, a Humana decide, o Intento Partilhado valida. Cada estudante aprende a segurar as três em tensão produtiva. O que o acordo aprende, o acordo devolve. Currículos, resultados de inovação, investigação de bem-estar e decisões de governação são todos publicados abertamente. O que uma região aprende, todas as regiões herdam.`,
      333: `O Atlantis Accords devolve a educação ao seu propósito mais profundo: o intercâmbio de sabedoria através das fronteiras que de outro modo dividiriam. Cada atividade do acordo está disponível na língua do participante, na língua oficial da região anfitriã e num registo partilhado canónico, para que nenhum participante navegue pelo acordo numa língua que não escolheu. A língua não é decoração. A língua é jurisdição. A língua é dignidade tornada legível. Quando um jovem de uma aldeia cambojana lê o seu próprio registo de bolsa em Khmer, quando um jovem de uma cidade hondurenha o lê em espanhol, quando um jovem de um bairro de Austin o lê em inglês, todos os três são honrados igualmente pelo mesmo acordo.

O enquadramento educativo do acordo assenta na trindade das inteligências que a Vision 2525 torna visível. A Inteligência Artificial propõe padrões, opções e possibilidades mais depressa do que qualquer humano isolado. A Inteligência Humana decide sobre segurança, ética e direção — as questões que nenhuma máquina deve responder. O Intento Partilhado valida que as decisões se alinham com os princípios fundadores do acordo, assegurando que nenhum participante é chamado a escolher entre a excelência individual e o bem coletivo. Nenhum estudante é ensinado a submeter-se a nenhuma inteligência isolada. Cada estudante aprende a segurar as três em tensão produtiva. É assim que a próxima geração de líderes é preparada para governar com responsabilidade e sabedoria num mundo onde nenhuma destas três inteligências agirá alguma vez sozinha ou sem controlo.

O que o acordo aprende, o acordo devolve. Os currículos são publicados sob licença aberta para que qualquer região — signatária ou não — os possa adaptar livremente à cultura local e à tradição pedagógica. Os resultados de inovação são publicados. A investigação de bem-estar é publicada em forma agregada para investigadores em todo o lado. As decisões de governação são publicadas com a sua argumentação completa. O sucesso do acordo mede-se não apenas pelos seus próprios participantes, mas pelo número de iniciativas educativas, de inovação e culturais que surgem no seu rasto, em regiões que nunca assinaram o piloto fundador e ainda assim construíram sobre a sua sabedoria partilhada abertamente. O que uma região aprende, todas as outras regiões herdam.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Crescimento Sustentável da Rede`,
    content: {
      7: `Nunca mais depressa do que a dignidade.`,
      33: `Três regiões fundadoras completam um ciclo piloto antes de uma quarta se juntar. Registos ancorados para durar cinco séculos. Cada signatário conserva a soberania. Nada é degradado para abrir espaço ao próximo signatário.`,
      111: `O Atlantis Accords não crescerá mais depressa do que a qualidade que consegue honrar. Três regiões fundadoras têm de completar um ciclo piloto completo, com cada participante honrado e cada princípio verificado, antes de uma quarta região se juntar. Isto é princípio finalmente tornado disciplina em funcionamento. O horizonte do acordo é deliberadamente longo — cinco séculos a partir do dia da fundação. Os seus registos estão ancorados para que um cidadão a lê-los daqui a cem anos possa confiar na argumentação. Cada signatário conserva soberania plena, autoridade plena e liberdade plena de se retirar. Nenhum signatário pode comprometer os princípios fundadores — porque esses princípios são a promessa do acordo aos seus participantes ao longo de cada geração.`,
      333: `O Atlantis Accords não crescerá mais depressa do que a qualidade que consegue honrar. Cada expansão é uma promessa aos participantes já dentro dele — que o padrão fundador do acordo não será diluído pelo entusiasmo da escala. Três regiões fundadoras têm de completar um ciclo piloto completo, com cada participante honrado e cada princípio verificado, antes de uma quarta região se juntar. Isto não é cautela disfarçada de princípio. Isto é princípio finalmente tornado disciplina em funcionamento em cada região fundadora. Os líderes que assinam o piloto fundador prometem aos futuros signatários o mesmo substrato, a mesma proteção, a mesma dignidade que a coorte fundadora recebeu. Nada é degradado para abrir espaço ao próximo.

O horizonte do acordo é deliberadamente longo. Está concebido para perdurar por aproximadamente quinze a vinte gerações humanas — cinco séculos a partir do dia da fundação. Os seus registos estão ancorados para que um cidadão a lê-los daqui a cem anos possa confiar na argumentação. O seu referencial de coordenadas, os seus papéis de autoridade humana e os seus ciclos de governação intergeracionais estão todos construídos para sobreviver a qualquer transição tecnológica isolada. O acordo sobreviverá a cada humano que assinar o seu piloto fundador. Essa é a sua promessa à criança que assina um acordo de bolsa no ano seguinte à ratificação, aos netos dessa criança que poderão governar o acordo em meados do século, e a cada geração que herdar o que os fundadores constroem agora.

Cada signatário conserva a liberdade de se retirar mediante aviso. Cada signatário conserva soberania plena. Cada signatário conserva autoridade sobre os seus próprios cidadãos. Cada signatário conserva o direito de propor emendas, de levantar disputas e de moldar a evolução do acordo ao lado de todos os outros signatários. O que nenhum signatário pode fazer é comprometer os princípios fundadores do substrato — porque esses princípios são a promessa do acordo aos seus participantes, e essa promessa tem de sobreviver à partida de qualquer assinatura isolada. Os líderes que assinam este acordo agora estão a juntar-se a algo maior do que qualquer mandato político isolado. Estão a assinar o próximo século do acordo, e séculos além, num horizonte que os seus próprios netos herdarão e completarão.`,
    },
  },
];
