import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_RO: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Unde începe inovația`,
    content: {
      7: `Liderii încep ceea ce niciun secol nu a început.`,
      33: `Trei regiuni — Cambodgia, Honduras, Austin — promit să găzduiască tineri învățăcei, să îi protejeze și să le pună în mâini uneltele viitorului. Guvern, Educație, Inovație: trei semnături vizionare pe regiune. Un început împreună.`,
      111: `Acordurile Atlantida sunt o promisiune făcută de lideri dispuși să înceapă ceva ce nu a existat înainte. Semnatarii lor fondatori din Cambodgia, Honduras și Austin, Texas au fost aleși pentru o calitate rară: disponibilitatea de a le încredința tinerilor uneltele viitorului cât încă mai este timp să îi învețe. Semnarea acordului angajează regiunea să găzduiască învățăcei din toate culturile, să contribuie cu ceea ce numai ea poate oferi în mod unic și să se țină la un standard mai înalt decât cere reglementarea actuală. Trei semnături vizionare — Guvern, Educație, Inovație — intră împreună în acord. Trei vizionari, trei regiuni, un început împărtășit.`,
      333: `Fiecare civilizație este ținută minte prin ceea ce a ales să înceapă. Acordurile Atlantida sunt o promisiune făcută de lideri dispuși să înceapă ceva ce nu a existat înainte — o temelie împărtășită pentru inovația umană obișnuită care ajunge în fiecare colț al lumii, cinstește fiecare glas și dăinuie de-a lungul generațiilor. Semnatarii lor fondatori din Cambodgia, Honduras și Austin, Texas nu au fost aleși pentru putere economică, pentru forță militară sau pentru prestigiu instituțional. Au fost aleși pentru o calitate mai rară: disponibilitatea de a le încredința tinerilor uneltele viitorului. Iată ce înseamnă leadershipul în secolul care vine — curajul de a preda cheile generației următoare cât încă mai este timp să o înveți să conducă.\n\nAcordul este convocat de eXeL, o forță organizatoare construită anume pentru acest moment. eXeL există în mod deliberat în afara canalelor tradiționale de coordonare care au modelat secolul trecut — în afara structurilor de tratate diplomatice, în afara birocrațiilor multilaterale, în afara încrengăturilor politice ale oricărui stat-națiune. eXeL este convocatorul de încredere care aduce laolaltă lideri vizionari în jurul unui cadru împărtășit, al unui volant împărtășit și al unui orizont împărtășit de cinci sute de ani. Fiecare semnatar își păstrează deplina suveranitate, deplina autoritate asupra propriilor cetățeni și deplina libertate de a se retrage în orice moment. Ceea ce câștigă semnatarii este efectul de rețea pe care numai un cadru construit anume îl poate oferi. Aceasta este coordonare fără nicio formă de dominație politică.\n\nA semna acordul înseamnă a semna o promisiune. Că regiunea va găzdui tineri învățăcei din toate culturile. Că regiunea va contribui cu ceea ce numai ea poate oferi în mod unic. Că regiunea se va ține la un standard mai înalt decât cere reglementarea actuală. Că regiunea o va face public, transparent, sub privirea fiecărui cetățean pe care îl slujește. Sunt necesare trei semnături din fiecare regiune — Guvern, Educație și Inovație. Niciun singur oficiu nu leagă acordul de unul singur. E nevoie de trei vizionari ca să spună da. Trei vizionari, trei regiuni, un început — astfel intră orice cadru în viață, prin încrederea reciprocă a liderilor dispuși să îl semneze spre a-l aduce pe lume.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Învățare prin simulare`,
    content: {
      7: `Exersează de o mie de ori înainte de a atinge.`,
      33: `Nimic important nu se învață mai întâi pe echipamente reale. Fiecare participant exersează în simulare, se rotește prin cele trei regiuni și sărbătorește public. Aceasta este respect pentru tânărul a cărui primă greșeală nu ar trebui să coste niciodată o viață.`,
      111: `Fiecare disciplină demnă de a fi stăpânită a fost învățată de cineva înainte de a fi cunoscută. Acordurile Atlantida readuc această înțelepciune străveche în centrul modului în care tinerii sunt pregătiți să construiască viitorul. Nimic important nu se învață mai întâi pe echipamente reale, pe oameni reali sau în condiții ireversibile. Fiecare participant exersează în simulare până când exercițiul devine competență, iar competența devine pregătire. Modelul de rotație poartă fiecare participant prin cele trei regiuni fondatoare, iar fiecare rotație se încheie cu o sărbătoare publică și cooperativă, deschisă comunității gazdă mai largi. Aceasta este respect pentru tânărul a cărui primă greșeală nu ar trebui să coste niciodată o viață.`,
      333: `Fiecare disciplină demnă de a fi stăpânită a fost învățată de cineva înainte de a fi cunoscută. Meșterii pricepuți repetă înainte de reprezentație, piloții repetă înainte de zbor, medicii repetă înainte de operație, iar copiii repetă lumea prin joc. Acordurile Atlantida readuc această înțelepciune străveche în centrul modului în care tinerii sunt pregătiți să construiască viitorul. Nimic important nu se învață mai întâi pe echipamente reale, pe oameni reali sau în condiții ireversibile. Fiecare participant exersează în simulare până când exercițiul devine competență, iar competența devine pregătire. Aceasta nu este prudență — este respect pentru tânărul a cărui primă greșeală nu ar trebui să coste niciodată viața nimănui.\n\nModelul de rotație al acordului poartă fiecare participant prin cele trei regiuni fondatoare. Ceea ce se învață în Cambodgia se rafinează în Honduras și se desăvârșește în Austin. Ceea ce se descoperă în Austin se pune la îndoială în Cambodgia și se integrează în Honduras. Fiecare participant trăiește, învață și este îndrumat prin culturi care altfel ar rămâne îndepărtate. Programa se hrănește din tradiții de simulare disciplinată din multe culturi — din tradiția educației strategice a lui Sun Tzu, din practica-prin-joc a lui Musashi, din teoria ciclică a învățării a lui Ibn Khaldun, din dialectica monastică de la Nalanda, din simulatorul civil de zbor — sintetizate spre a respecta fiecare etapă cognitivă și fiecare moștenire culturală. Nicio tradiție nu domină.\n\nFiecare rotație se încheie cu o sărbătoare publică și cooperativă, deschisă comunității gazdă mai largi. Vecini, familii și vizitatori curioși se adună pentru a vedea ce a învățat cohorta. Aceste evenimente fac ca tehnologia sofisticată să fie accesibilă și sărbătorită, mai degrabă decât de temut. O societate care crește înțelegând sistemele cooperative prin joc nu poate fi ușor manipulată prin frica față de acele sisteme. Aceasta este descurajare prin educație, nu descurajare prin forță. Promisiunea acordului către fiecare părinte: copilul tău va exersa de o mie de ori în siguranță înainte de a atinge ceva ce l-ar putea vătăma, iar comunitatea îi va fi martoră la creștere la fiecare pas al drumului. Așa arată respectul pentru tânăr atunci când este inginerit într-un cadru, și iată ce predă leadershipul generației următoare de participanți înainte ca acea generație să fie nevoită să o ceară.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Siguranța verificată înainte de acordarea încrederii`,
    content: {
      7: `Siguranța dovedită întâi, apoi încrederea acordată.`,
      33: `Fiecare instalație și fiecare rotație se află într-un înveliș protector cu avertizare timpurie. Hardware-ul refuză înarmarea. Registrele supraviețuiesc turbulenței. Siguranța este ingineriă în jurul celui mai tânăr participant în fiecare zi, nu doar promisă sau presupusă.`,
      111: `Înainte ca încrederea să fie acordată, siguranța trebuie dovedită. Acordurile Atlantida fac din aceasta angajamentul lor fondator. Fiecare instalație a acordului, fiecare rută de rotație, fiecare loc unde un tânăr participant doarme sau studiază se află într-un înveliș protector documentat, cu capacitate de avertizare timpurie care oferă comunității ore, nu minute, pentru a răspunde oricărui risc credibil. Fiecare dispozitiv, fiecare senzor, fiecare sistem de coordonare este legat la nivel de hardware pentru a refuza reutilizarea în integrarea cu sisteme de armament. Aceasta nu este politică — este fizică. Acordul este proiectat să rămână onorabil prin turbulență: instabilitate politică, contracție a finanțării, atac cibernetic sau întrerupere a călătoriilor. Fiecare scenariu este planificat, iar fiecare plan așază demnitatea umană drept prima sa constrângere de proiectare.`,
      333: `Înainte ca încrederea să fie acordată, siguranța trebuie dovedită. Acordurile Atlantida fac din aceasta angajamentul lor fondator. Fiecare instalație a acordului, fiecare rută de rotație, fiecare loc unde un tânăr participant doarme sau studiază se află într-un înveliș protector documentat, cu capacitate de avertizare timpurie care oferă comunității ore, nu minute, pentru a răspunde oricărui risc credibil. Tehnologia folosită pentru a proteja participanții este aceeași tehnologie pe care acordul îi învață să o construiască — senzori, coordonare, supraviețuire a comunicațiilor, inteligență distribuită. Tinerii învață siguranța dinăuntru în afară, în propria limbă și în propria regiune, nu pentru că li se spune că sunt în siguranță, ci văzând cum siguranța este ingineriă în jurul lor în fiecare zi.\n\nAcordul face o promisiune de nezdruncinat despre ceea ce tehnologia sa nu poate deveni. Fiecare dispozitiv, fiecare senzor, fiecare sistem de coordonare este legat la nivel de hardware pentru a refuza reutilizarea în integrarea cu sisteme de armament. Aceasta nu este limbaj de politică. Nu este aspirație. Este o imposibilitate fizică, impusă criptografic, verificată de fiecare regiune semnatară și inspectabilă de fiecare cetățean. Uneltele care protejează un copil în Phnom Penh nu pot fi reutilizate pentru a vătăma un copil în Austin. Uneltele care coordonează un exercițiu de roi în Tegucigalpa nu pot fi reconfigurate pentru a viza un om oriunde. Acesta este răspunsul acordului la un secol de teamă față de dubla utilizare. Nu politică — fizică.\n\nAcordul este proiectat să rămână onorabil prin turbulență. Dacă o regiune semnatară își pierde stabilitatea politică, participanții sunt găzduiți de regiunile rămase. Dacă finanțarea se contractă, indemnizațiile participanților sunt protejate mai întâi, înaintea administrației și a infrastructurii. Dacă registrele digitale sunt atacate, copiile de rezervă offline persistă. Dacă a călători devine imposibil, substratul continuă virtual. Fiecare scenariu este planificat, iar fiecare plan așază demnitatea umană drept prima sa constrângere de proiectare. Liderii care semnează acest acord semnează promisiunea că siguranța este ingineriă, nu presupusă. Ceea ce le oferă cetățenilor lor nu este doar oportunitate, ci protecție construită la standardul pe care îl merită cel mai tânăr participant — aceeași protecție pe care orice lider ar cere-o pentru propriul copil traversând singur o graniță necunoscută.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Compensație, bunăstare și demnitate umană`,
    content: {
      7: `O indemnizație, un mentor, un cămin.`,
      33: `Fiecare participant primește o indemnizație de subzistență din prima zi. Iubirea, pierderea și siguranța sunt tratate ca infrastructură de prim rang. Succesul se măsoară prin cel mai vulnerabil participant, niciodată prin medie. Demnitatea este substrat, niciodată decor.`,
      111: `Acordurile Atlantida tratează fiecare participant ca pe o ființă umană deplină din prima zi. O indemnizație este oferită din clipa în care începe participarea, indexată la costul vieții din regiune, astfel încât impactul ei să respecte demnitatea locală a muncii. Bunăstarea este tratată ca infrastructură de prim rang — nu un beneficiu opțional, nu un privilegiu de wellness, ci substratul pe care stă totul. Sunt susținute trei domenii fondatoare: Iubirea, Pierderea și Siguranța. Acordul măsoară succesul prin rezultatul celui mai vulnerabil participant, nu prin medie. Niciun participant nu va fi uitat în tăcere pentru ca mediile să arate bine. Demnitate ca substrat, nu ca decor.`,
      333: `Acordurile Atlantida tratează fiecare participant ca pe o ființă umană deplină din prima zi. O indemnizație este oferită din clipa în care începe participarea, indexată la costul vieții din regiune, astfel încât impactul ei să respecte demnitatea locală a muncii. Indemnizația sosește înainte ca obligațiile familiale să devină urgențe și înainte ca demnitatea să fie compromisă. Îi semnalează fiecărui tânăr că timpul său este prețios, că i se așteaptă contribuția și că stabilitatea familiei sale face parte din responsabilitatea acordului. Aceasta nu este caritate. Este recunoașterea faptului că inovația umană obișnuită are nevoie mai întâi de securitate umană obișnuită. O minte nu poate înflori câtă vreme căminul îi este amenințat.\n\nBunăstarea este tratată ca infrastructură de prim rang — nu un beneficiu opțional, nu un privilegiu de wellness, ci substratul pe care stă totul. Acordul numește trei domenii fondatoare prin care este susținut fiecare participant: Iubirea, în sensul de conexiune, atașament și limită sănătoasă; Pierderea, întrucât fiecare participant va trece prin doliu și trebuie însoțit, nu ocolit; și Siguranța, în sensul că fiecare participant știe pe cine să sune, în fiecare regiune, în propria limbă. Sunt oferite consiliere individuală, cercuri de grup, practici somatice și practici culturale sau spirituale cinstite după propria tradiție a participantului. Zero ideologie impusă. Acordul ține spațiul cu venerație; nu face prozelitism pentru niciun sistem de credință.\n\nAcordul măsoară succesul prin rezultatul celui mai vulnerabil participant, nu prin medie. Participanții rurali fără lățime de bandă mare sunt slujiți. Participanții neurodivergenți primesc adaptări ca normă. Participanții cu dizabilități găsesc fiecare instalație accesibilă. Participanții cu gen divers primesc locuință sigură și asociere cu un mentor. Vorbitorii de limbi non-materne găsesc fiecare document în limba lor. Participanții indigeni își găsesc practicile culturale cinstite și cunoașterea tradițională protejată. Liderii care semnează acest acord promit că niciun participant nu va fi uitat în tăcere pentru ca mediile să arate bine. Aceasta este demnitate ca substrat, nu ca decor. Ceea ce se măsoară este ceea ce va fi cinstit, iar ceea ce se cinstește aici este omul întreg — minte, trup și spirit împreună, fără nicio excepție.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finanțare și guvernanță`,
    content: {
      7: `Cetățenii finanțează direct generația următoare.`,
      33: `Rezidenții obișnuiți contribuie cu sume lunare mici. Fără canal de ajutor, fără binefăcător străin, fără ațe politice. Fiecare dolar este trasabil. Fiecare contabilitate se publică, în limba fiecărei regiuni, în fiecare lună, public.`,
      111: `Acordurile Atlantida sunt finanțate de cetățenii pe care îi slujesc. Rezidenți obișnuiți contribuie cu mici sume voluntare în fiecare lună — îndeajuns de modeste încât niciun adult să nu fie exclus, îndeajuns de rezonante încât totalul să susțină munca acordului la o scară semnificativă. Când un cetățean finanțează direct generația următoare, acel cetățean trage la răspundere acordul în mod direct. Acordul este în mod deliberat independent de instituțiile multilaterale care au modelat secolul trecut. Aceasta nu este o declarație politică — este o alegere de proiectare. Fiecare dolar se înregistrează permanent și trasabil. Fiecare contribuție a cetățeanului poate fi urmărită de la origine până la indemnizație și până la inovație. O transparență rareori oferită de vreo instituție.`,
      333: `Acordurile Atlantida sunt finanțate de cetățenii pe care îi slujesc. Rezidenți obișnuiți ai regiunilor participante contribuie cu mici sume voluntare în fiecare lună — sume îndeajuns de modeste încât niciun adult din nicio regiune gazdă să nu fie exclus de la participare, îndeajuns de rezonante încât totalul să susțină munca acordului la o scară semnificativă. Această proiectare este deliberată. Când un cetățean finanțează direct educația generației următoare, acel cetățean trage la răspundere acordul în mod direct. Nu există canal de ajutor, nu există binefăcător străin, nu există ață politică legată de cec. Sufletul acordului este cetățeanul care contribuie cu o mică sumă în fiecare lună, a cărui participare face posibil întregul.\n\nAcordul este în mod deliberat independent de instituțiile multilaterale care au modelat secolul trecut — Organizația Tratatului Atlanticului de Nord, Organizația Mondială a Sănătății, Națiunile Unite, Fondul Monetar Internațional, Banca Mondială și fiecare canal național de ajutor extern. Aceasta nu este o declarație politică despre valoarea acelor instituții sau despre contribuțiile lor. Este o alegere de proiectare. Dependențele de un singur punct compromit durabilitatea de-a lungul unui orizont de cinci sute de ani. Un cadru menit să slujească fiecare regiune, indiferent de alinierea geopolitică, nu poate fi încâlcit cu nicio aliniere. Guvernele naționale pot contribui în mod voluntar. Contribuțiile sunt transparente. Nicio contribuție nu cumpără influență de guvernanță, din nicio sursă, niciodată.\n\nFiecare dolar și fiecare unitate de valoare care intră în acord se înregistrează permanent, public și trasabil. Fiecare contribuție a cetățeanului poate fi urmărită de la origine până la indemnizația în care se transformă, până la tânărul pe care îl slujește, până la proiectul de inovație care se ivește din munca acelui tânăr. Cheltuielile administrative sunt plafonate. Donațiile corporative și instituționale sunt binevenite și plafonate. Contabilitatea completă este livrată în limba fiecărei regiuni semnatare în fiecare lună. Liderii care semnează acordul le promit cetățenilor lor o transparență rareori oferită de vreo instituție — transparență care va rămâne lizibilă timp de secole după ce fiecare semnatar și-a părăsit funcția. Aceasta este încrederea pe care o cere acordul. Aceasta este încrederea pe care o câștigă acordul, câte o mică contribuție trasabilă pe rând, sub privirea fiecărui cetățean.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Schimb intercultural și contribuție globală`,
    content: {
      7: `Fiecare învățăcel în propria limbă.`,
      33: `Fiecare activitate disponibilă în limba participantului. Inteligențele Artificială, Umană și Împărtășită ținute într-o tensiune productivă — niciun elev nu se pleacă în fața uneia singure. Programe și rezultate publicate deschis. Ce învață o regiune, moștenesc toate.`,
      111: `Acordurile Atlantida readuc educației scopul ei cel mai adânc: schimbul de înțelepciune peste granițe care altfel ar dezbina. Fiecare activitate este disponibilă în limba participantului, în limba regiunii gazdă și într-un registru canonic împărtășit. Limba nu este decor — limba este jurisdicție, limba este demnitate făcută lizibilă. Cadrul educațional se sprijină pe trinitatea inteligențelor: cea Artificială propune, cea Umană decide, Intenția Împărtășită validează. Fiecare elev învață să le țină pe toate trei într-o tensiune productivă. Ce învață acordul, acordul dă înapoi. Programe, rezultate ale inovației, cercetare a bunăstării și decizii de guvernanță sunt publicate deschis. Ce învață o regiune, toate regiunile moștenesc.`,
      333: `Acordurile Atlantida readuc educației scopul ei cel mai adânc: schimbul de înțelepciune peste granițe care altfel ar dezbina. Fiecare activitate a acordului este disponibilă în limba proprie a participantului, în limba oficială a regiunii gazdă și într-un registru canonic împărtășit, astfel încât niciun participant să nu navigheze acordul într-o limbă pe care nu a ales-o. Limba nu este decor. Limba este jurisdicție. Limba este demnitate făcută lizibilă. Când un tânăr dintr-un sat cambodgian își citește propriul registru de indemnizație în khmeră, când un tânăr dintr-un oraș hondurian îl citește în spaniolă, când un tânăr dintr-un cartier din Austin îl citește în engleză, toți trei sunt cinstiți la fel de același acord.\n\nCadrul educațional al acordului se sprijină pe trinitatea inteligențelor pe care Vision 2525 o face vizibilă. Inteligența Artificială propune tipare, opțiuni și posibilități mai repede decât ar putea orice om de unul singur. Inteligența Umană decide asupra siguranței, eticii și direcției — întrebările la care nicio mașină nu ar trebui să răspundă. Intenția Împărtășită validează că deciziile se aliniază cu principiile fondatoare ale acordului, asigurându-se că niciun participant nu este pus să aleagă între excelența individuală și binele colectiv. Niciun elev nu este învățat să se plece în fața unei singure inteligențe. Fiecare elev învață să le țină pe toate trei într-o tensiune productivă. Astfel este pregătită generația următoare de lideri să guverneze responsabil și înțelept într-o lume în care niciuna dintre aceste trei inteligențe nu va acționa vreodată singură sau necontrolată.\n\nCe învață acordul, acordul dă înapoi. Programele sunt publicate sub licență deschisă, astfel încât orice regiune — semnatară sau nu — să le poată adapta liber la cultura locală și la tradiția pedagogică. Rezultatele inovației sunt publicate. Cercetarea bunăstării este publicată în formă agregată pentru cercetători de pretutindeni. Deciziile de guvernanță sunt publicate împreună cu raționamentul lor deplin. Succesul acordului se măsoară nu doar prin propriii participanți, ci prin numărul de inițiative educaționale, de inovație și culturale care se ivesc în urma sa, în regiuni care nu au semnat niciodată pilotul fondator, dar au clădit pe înțelepciunea sa împărtășită deschis. Ce învață o regiune, toate celelalte regiuni moștenesc.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Creșterea sustenabilă a rețelei`,
    content: {
      7: `Niciodată mai repede decât poate călători demnitatea.`,
      33: `Trei regiuni fondatoare încheie un ciclu-pilot înainte ca o a patra să se alăture. Registre ancorate să dăinuie cinci secole. Fiecare semnatar își păstrează suveranitatea. Nimic nu se coboară pentru a face loc următorului semnatar.`,
      111: `Acordurile Atlantida nu vor crește mai repede decât calitatea pe care o pot cinsti. Trei regiuni fondatoare trebuie să încheie un ciclu-pilot complet, cu fiecare participant cinstit și fiecare principiu verificat, înainte ca o a patra regiune să se alăture. Acesta este un principiu devenit în sfârșit disciplină vie. Orizontul acordului este în mod deliberat lung — cinci secole de la ziua fondatoare. Registrele sale sunt ancorate astfel încât un cetățean care le citește peste o sută de ani să poată avea încredere în raționament. Fiecare semnatar își păstrează deplina suveranitate, deplina autoritate și deplina libertate de a se retrage. Niciun semnatar nu poate compromite principiile fondatoare — pentru că acele principii sunt promisiunea acordului către participanții săi de-a lungul fiecărei generații.`,
      333: `Acordurile Atlantida nu vor crește mai repede decât calitatea pe care o pot cinsti. Fiecare extindere este o promisiune către participanții deja înăuntru — că standardul fondator al acordului nu va fi diluat de entuziasmul scării. Trei regiuni fondatoare trebuie să încheie un ciclu-pilot complet, cu fiecare participant cinstit și fiecare principiu verificat, înainte ca o a patra regiune să se alăture. Aceasta nu este prudență deghizată în principiu. Acesta este un principiu devenit în sfârșit disciplină vie de-a lungul fiecărei regiuni fondatoare. Liderii care semnează pilotul fondator le promit viitorilor semnatari același substrat, aceeași protecție, aceeași demnitate pe care le-a primit cohorta fondatoare. Nimic nu se coboară pentru a face loc următorului.\n\nOrizontul acordului este în mod deliberat lung. Este proiectat să dăinuie aproximativ cincisprezece până la douăzeci de generații umane — cinci secole de la ziua fondatoare. Registrele sale sunt ancorate astfel încât un cetățean care le citește peste o sută de ani să poată avea încredere în raționament. Cadrul său de coordonate, rolurile sale de autoritate umană și ciclurile sale de guvernanță intergeneraționale sunt toate construite să supraviețuiască oricărei tranziții către o singură tehnologie. Acordul va supraviețui fiecărui om care îi semnează pilotul fondator. Aceasta este promisiunea sa către copilul care semnează un acord de indemnizație în anul de după ratificare, către nepoții acelui copil care poate vor guverna acordul la mijlocul secolului și către fiecare generație care moștenește ceea ce clădesc fondatorii acum.\n\nFiecare semnatar își păstrează libertatea de a se retrage cu preaviz. Fiecare semnatar își păstrează deplina suveranitate. Fiecare semnatar își păstrează autoritatea asupra propriilor cetățeni. Fiecare semnatar își păstrează dreptul de a propune amendamente, de a ridica dispute și de a modela evoluția acordului alături de fiecare alt semnatar. Ceea ce niciun semnatar nu poate face este să compromită principiile fondatoare ale substratului — pentru că acele principii sunt promisiunea acordului către participanții săi, iar acea promisiune trebuie să supraviețuiască plecării oricărei semnături. Liderii care semnează acest acord acum se alătură unui lucru mai mare decât orice mandat politic. Ei semnează secolul următor al acordului, și secolele de dincolo de el, către un orizont pe care propriii lor nepoți îl vor moșteni și îl vor desăvârși.`,
    },
  },
];
