import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_RO: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Unde începe inovația`,
    content: {
      7: `Liderii încep ceea ce niciun secol nu a început.`,
      33: `Trei regiuni — Cambodgia, Honduras, Austin — deschid o promisiune pe care cetățenii ajută să o construiască: găzduiesc cei care învață, îi protejează, le pun în mâini uneltele viitorului. Guvernul, Educația și Inovația semnează ca administratori; cetățenii o susțin. Un singur început.`,
      111: `Acordurile Atlantis reprezintă un acord între cetățenii lumii — o promisiune pe care orice persoană, oriunde, o poate crea și susține, indiferent de ce semnează guvernul său sau ce permite angajatorul său. Regiunile sale fondatoare, Cambodgia, Honduras și Austin, Texas, au fost alese pentru o calitate rară: disponibilitatea de a încredința tinerilor uneltele viitorului cât timp mai există vreme să-i învețe să le folosească. Guvernele, educatorii și inovatorii semnează ca administratori ai regiunilor lor — câte trei semnături vizionare, Guvern, Educație, Inovație — dar cetățenii finanțează acordul, îi sunt martori lucrării și îl țin direct răspunzător. Nu este nevoie de permisiunea niciunui guvern și nici de binecuvântarea niciunui angajator pentru a face parte din el. Trei regiuni, un singur început comun.`,
      333: `Fiecare civilizație este ținută minte pentru ceea ce a ales să înceapă. Acordurile Atlantis reprezintă o promisiune între cetățenii lumii — orice persoană, oriunde, o poate începe, indiferent de ce semnează guvernul său. Regiunile sale fondatoare, Cambodgia, Honduras și Austin, Texas, nu au fost alese pentru putere economică, forță militară sau prestigiu instituțional, ci pentru o calitate mai rară: disponibilitatea de a încredința tinerilor uneltele viitorului. Aceasta înseamnă conducere în secolul care vine — curajul de a preda cheile generației următoare cât timp mai este vreme să o înveți să conducă.

Acordul este convocat de eXeL, o forță organizatoare construită special pentru acest moment, existând în afara canalelor de coordonare care au modelat secolul trecut — în afara structurilor de tratate diplomatice, a birocrațiilor multilaterale și a încurcăturilor politice ale oricărui stat-națiune. eXeL este convocatorul de încredere care reunește lideri vizionari în jurul unui cadru comun, al unui volant comun și al unui orizont comun de cinci sute de ani. Fiecare semnatar își păstrează suveranitatea deplină, autoritatea deplină asupra propriilor cetățeni și libertatea deplină de a se retrage în orice moment. Ceea ce câștigă semnatarii — și ceea ce câștigă orice cetățean, pentru prețul unui Seed, o șeptime dintr-o oră de salariu minim local — este efectul de rețea pe care doar un cadru construit special îl poate oferi: coordonare fără nicio formă de dominație politică.

A semna acordul înseamnă a semna o promisiune: că regiunea va găzdui cei care învață dincolo de granițele culturilor, va contribui cu ceea ce numai ea poate oferi și se va ține la un standard mai înalt decât cel cerut de reglementarea actuală — public, transparent, dând socoteală cetățenilor care îl finanțează, îi sunt martori și îl țin răspunzător, fără să fie nevoie de permisiunea niciunui guvern sau de binecuvântarea niciunui angajator pentru a face parte din el. Sunt necesare trei semnături din partea fiecărei regiuni — Guvern, Educație și Inovație — semnând ca administratori, nu ca proprietari. Este nevoie de trei vizionari care să spună da, și de cetățeni care să susțină ce au semnat. Trei vizionari, trei regiuni, un singur început — așa intră un cadru în viață, prin încrederea liderilor dispuși să-l aducă la existență prin semnătura lor.`,
      999: `Fiecare civilizație este ținută minte pentru ceea ce a ales să înceapă, iar Vision • 2525 le cere fondatorilor acesteia să înceapă cu smerenie, nu cu cucerire. Acordurile Atlantis reprezintă o promisiune făcută de lideri dispuși să înceapă ceva ce nu a mai existat până acum — o temelie comună pentru inovația umană, care ajunge în fiecare colț al lumii, onorează fiecare voce și dăinuie de-a lungul unor generații măsurate nu în ani, ci în secole. Semnatarii săi fondatori din Cambodgia, Honduras și Austin, Texas nu au fost aleși pentru putere economică, forță militară sau prestigiu instituțional. Au fost aleși pentru o calitate mai rară: disponibilitatea de a încredința tinerilor uneltele viitorului și răbdarea de a lăsa un orizont de cinci sute de ani să supraviețuiască aplauzelor oricărei administrații. Aceasta înseamnă conducere în secolul care vine — curajul de a preda cheile generației următoare cât timp mai este vreme să o înveți să conducă.

Acordul este convocat de eXeL, o forță organizatoare construită special pentru acest moment. eXeL există în afara canalelor de coordonare care au modelat secolul trecut — în afara structurilor de tratate diplomatice, în afara birocrațiilor multilaterale, în afara încurcăturilor politice ale oricărui stat-națiune. eXeL este convocatorul de încredere care reunește lideri vizionari în jurul unui cadru comun, al unui volant comun și al unui orizont comun de cinci sute de ani. Fiecare semnatar își păstrează suveranitatea deplină, autoritatea deplină asupra propriilor cetățeni și libertatea deplină de a se retrage în orice moment. Ceea ce câștigă semnatarii este efectul de rețea pe care doar un cadru construit special îl poate oferi. Intrarea fiecărui participant în acest cadru începe în același mod modest: cu un Seed, o apartenență unică, taxată la o șeptime dintr-o oră de salariu minim local, netransferabilă și fără nicio pretenție economică de orice fel. Un Seed nu cumpără proprietate și nici promisiunea vreunei răsplăți — ci doar apartenența, dreptul de a te afla înăuntrul cadrului și de a începe. Aceasta este coordonare fără nicio formă de dominație politică, construită pe un început suficient de mic pentru ca oricine să și-l poată permite.

Pentru că suveranitatea este păstrată, nu cedată, acordul este construit pentru Continuity Without Evasion. Niciun guvern, bancă, fondator sau model indispensabil nu poate ține întregul cadru ostatic propriei sale supraviețuiri. Fiecare jurisdicție este deservită prin adaptorul ei legal, cu refuz implicit până la dovedirea conformității, astfel încât valoarea circulă doar prin canale pe care o instanță din acea jurisdicție le-ar recunoaște drept legitime. Dacă un organism de reglementare dintr-o regiune emite o hotărâre nefavorabilă, doar acel canal se închide — transparent, fără a afecta niciun participant aflat înăuntrul lui — în timp ce fiecare altă regiune continuă neperturbată. Întregul acord nu cade niciodată pentru că un singur guvern și-a schimbat părerea. Aceasta este portabilitatea concepută ca promisiune fondatoare, nu ca soluție de urgență descoperită după criză.

A semna acordul înseamnă a semna o promisiune. Că regiunea va găzdui cei care învață dincolo de granițele culturilor. Că regiunea va contribui cu ceea ce numai ea poate oferi. Că regiunea se va ține la un standard mai înalt decât cel cerut de reglementarea actuală. Că regiunea va face asta public, transparent, sub privirea fiecărui cetățean pe care îl deservește. Sunt necesare trei semnături din partea fiecărei regiuni — Guvern, Educație și Inovație. Niciun singur birou nu leagă acordul de unul singur. Este nevoie de trei vizionari care să spună da. Această semnătură triplă este prima expresie a Human Authority: sensul, banii și legea rămân în mâini umane, la stratul suveran, un strat închis permanent mașinilor, oricât de capabile ar deveni acestea. Measurement of Time, MoT, începe să înregistreze din momentul semnării — minute reale de muncă umană reală, ținute separat de orice estimare automată — iar fiecare versiune ulterioară a lucrării acordului este construită pentru a putea fi reconstituită prin Replay, astfel încât un cetățean născut peste un secol să poată reface felul în care au fost luate deciziile fondatoare de astăzi.

Ceea ce fondează proiectul-pilot este măsurarea, înainte de a fi bani. Fiecare inovație care intră în cadru este evaluată prin Qualified Innovation Score, QIS — media dintre Venit, Profit Brut, Venit Operațional și cheltuielile Efective de C&D, împărțită la patru. QIS nu este o plată și nu înseamnă niciodată proprietate; este instrumentul prin care o generație fondatoare învață să-și vadă propriul progres înainte ca vreo răsplată să fie dimensionată. Creșterea QIS, odată îndeplinită calificarea, dimensionează fondul de recompense care urmează — dar creșterea QIS nu emite nimic de la sine. Trei regiuni, un singur început și o singură disciplină comună: dovedește scorul înainte de a atinge tezaurul.

Valoarea câștigată prin muncă atestată poartă propriul nume, 웃, calculat ca o oră înmulțită cu salariul minim local, scalat printr-un Multiplicator aplicat orelor prestate. 웃 se emite doar pentru munca atestată în cadrul unei sarcini definite și aprobate din buget; orice se află sub acest prag de aprobare este încă planificare, iar planificarea singură nu emite nimic. Un plafon de decontare de 9.999 웃 pe an protejează fiecare participant de o concentrare necontrolată, orice surplus reportându-se în loc să dispară. În spatele fiecărui 웃 se află ♡, Shared Intention, care poartă motivul pentru care o sarcină a fost aprobată în primul rând, și ◬, accelerarea atestată pe care o sarcină a produs-o față de o linie de bază înghețată — doar o diferență, niciodată confundată cu un indicator de profit. Proiectul-pilot există pentru a dovedi că aceste trei simboluri pot avansa împreună, cu onestitate, regiune după regiune, înainte ca acest cadru să se extindă dincolo de fondatorii săi.

Când valoarea ajunge la o persoană, ajunge prin Livelihood Direct — 🏠 — canale locale calificate și autorizate, pe care eXeL nu le administrează niciodată ca fond propriu. Clasificarea precede decontarea în fiecare caz, iar recunoașterea unei contribuții nu condiționează niciodată un loc de cazare pentru noapte; doar rolul unei persoane într-o sarcină definită o face. Creșterea dincolo de proiectul-pilot este de asemenea condiționată: fiecare cub al cadrului trece de la Manual la Semi-Automatizat la Autonom doar după ce depășește regula de 11,1 procente, o parte din nouă de îmbunătățire măsurată, câștigată cub cu cub și niciodată revendicată în bloc — și niciodată, sub nicio formă, peste stratul suveran al sensului, banilor și legii. Astfel devin trei vizionari per regiune, trei regiuni și un singur început o promisiune de cinci sute de ani: nu prin mișcare rapidă, ci prin dovedirea, sub privirea publicului, că fiecare pas a meritat pasul următor.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Învățare prin simulare`,
    content: {
      7: `Exersează de o mie de ori înainte de a atinge.`,
      33: `Nimic cu consecințe reale nu se învață mai întâi pe echipament real. Orice cetățean poate exersa în simulare, poate roti între trei regiuni, poate sărbători — respect pentru tânărul a cărui primă greșeală nu ar trebui niciodată să coste o viață.`,
      111: `Fiecare disciplină care merită stăpânită a fost învățată de cineva înainte de a fi cunoscută. Acordurile Atlantis readuc această înțelepciune străveche în centrul modului în care tinerii — și orice cetățean care se alătură — sunt pregătiți să construiască viitorul. Nimic cu consecințe reale nu se învață mai întâi pe echipament real, pe oameni reali sau în condiții ireversibile; nu este nevoie de permisiunea niciunui guvern sau de binecuvântarea niciunui angajator. Fiecare participant exersează în simulare până când exercițiul devine competență, apoi pregătire. Modelul de rotație poartă fiecare participant prin cele trei regiuni fondatoare, iar fiecare rotație se încheie cu o sărbătoare publică, deschisă comunității-gazdă. Acesta este respectul pentru tânărul a cărui primă greșeală nu ar trebui niciodată să coste o viață.`,
      333: `Fiecare disciplină care merită stăpânită a fost învățată de cineva înainte de a fi cunoscută. Meșterii desăvârșiți exersează înainte de spectacol, piloții înainte de zbor, medicii înainte de operație, copiii prin joacă. Acordurile Atlantis readuc această înțelepciune străveche în centrul modului în care tinerii — și orice cetățean care se alătură, fără să fie nevoie de permisiunea niciunui guvern sau de binecuvântarea niciunui angajator — sunt pregătiți să construiască viitorul. Nimic cu consecințe reale nu se învață mai întâi pe echipament real, pe oameni reali sau în condiții ireversibile. Fiecare participant exersează în simulare până când exercițiul devine competență, apoi pregătire. Aceasta nu este prudență — este respect pentru tânărul a cărui primă greșeală nu ar trebui niciodată să coste viața cuiva.

Modelul de rotație al acordului poartă fiecare participant prin cele trei regiuni fondatoare. Ce se învață în Cambodgia se rafinează în Honduras și se desăvârșește în Austin. Ce se descoperă în Austin se pune sub semnul întrebării în Cambodgia și se integrează în Honduras. Fiecare participant trăiește, învață și este îndrumat printre culturi care altfel ar rămâne îndepărtate. Programa de instruire se inspiră din tradiții de simulare disciplinată din multe culturi — din tradiția de educație strategică a lui Sun Tzu, din învățarea-prin-joc a lui Musashi, din teoria învățării ciclice a lui Ibn Khaldun, din dialectica monastică de la Nalanda, din simulatorul civil de zbor — sintetizate pentru a respecta fiecare etapă cognitivă și fiecare moștenire culturală. Nicio tradiție nu domină singură.

Fiecare rotație se încheie cu o sărbătoare publică, deschisă comunității-gazdă, unde vecinii, familiile și vizitatorii văd ce a învățat generația respectivă. Aceste evenimente fac tehnologia sofisticată accesibilă și sărbătorită, nu înspăimântătoare — o societate care crește înțelegând sistemele cooperative prin joc nu poate fi ușor manipulată prin frica de ele. Aceasta este descurajare prin educație, nu prin forță. Promisiunea acordului către fiecare părinte: copilul tău va exersa de o mie de ori în siguranță înainte de a atinge orice l-ar putea răni, totul atestat, astfel încât un cetățean — orice cetățean, peste un secol — să poată verifica faptul că s-a întâmplat exact așa cum este consemnat. Acesta este respectul pentru tânărul om, construit direct în structura unui cadru, și este ceea ce conducerea datorează următorului cetățean care se alătură, înainte ca acel cetățean să trebuiască să-l ceară.`,
      999: `Fiecare disciplină care merită stăpânită a fost învățată de cineva înainte de a fi cunoscută, iar fiecare civilizație care a dăinuit a făcut-o pentru că a protejat spațiul în care acea învățare se putea petrece în siguranță, înainte de a i se cere să conteze. Meșterii desăvârșiți exersează înainte de spectacol, piloții exersează înainte de zbor, medicii exersează înainte de operație, iar copiii exersează lumea prin joacă. Acordurile Atlantis readuc această înțelepciune străveche în centrul modului în care tinerii sunt pregătiți să construiască viitorul și îi dau acestei înțelepciuni un nume și un mecanism: Replay. Nimic cu consecințe reale nu se învață mai întâi pe echipament real, pe oameni reali sau în condiții ireversibile. Fiecare participant exersează în simulare până când exercițiul devine competență, apoi pregătire, iar fiecare oră din acel exercițiu este înregistrată pentru a putea fi reconstituită mai târziu, examinată mai târziu, în care să se poată avea încredere mai târziu. Aceasta nu este prudență — este respect pentru tânărul a cărui primă greșeală nu ar trebui niciodată să coste viața cuiva, și este respect pentru înregistrarea care va supraviețui greșelii, oricum ar fi.

Modelul de rotație al acordului poartă fiecare participant prin cele trei regiuni fondatoare. Ce se învață în Cambodgia se rafinează în Honduras și se desăvârșește în Austin. Ce se descoperă în Austin se pune sub semnul întrebării în Cambodgia și se integrează în Honduras. Fiecare participant trăiește, învață și este îndrumat printre culturi care altfel ar rămâne îndepărtate, iar fiecare rotație începe așa cum începe pentru orice instituție umană demnă de încredere: cu un Seed. Seed-ul este o apartenență unică, taxată la o șeptime dintr-o oră de salariu minim local, netransferabilă, fără nicio pretenție economică de orice fel. Nu este o taxă pentru acces la o oportunitate. Este un prag — suficient de mic încât niciun participant dispus să nu fie exclus prin cost, suficient de deliberat încât intrarea să fie aleasă, nu întâmplătoare. De la acest prag înainte, fiecare participant aparține rotației, iar rotația nu aparține unei singure regiuni.

Programă de instruire se inspiră din tradiții de simulare disciplinată din multe culturi — din tradiția de educație strategică a lui Sun Tzu, din învățarea-prin-joc a lui Musashi, din teoria învățării ciclice a lui Ibn Khaldun, din dialectica monastică de la Nalanda, din simulatorul civil de zbor — sintetizate pentru a respecta fiecare etapă cognitivă și fiecare moștenire culturală. Nicio tradiție nu domină singură. Iar în interiorul acestei programe, acordul trasează o linie pe care fiecare participant o învață devreme și nu o uită niciodată: simularea este locul unde Qualified Innovation Score se înțelege, nu locul unde se cheltuiește. QIS este măsurare, niciodată plată, și QIS nu înseamnă niciodată proprietate — există pentru a descrie cât de bine raționează o propunere, cât de bine rezistă și cât de bine servește regiunea pe care pretinde că o servește. Creșterea QIS poate dimensiona un fond de recompense după o calificare reală, dar nu emite nimic de la sine. Un participant poate rula o sută de simulări impecabile și poate obține un scor în creștere fără ca o singură oră de 웃 să-i atingă registrul, pentru că 웃 se emite doar pentru munca atestată, prestată în cadrul unei sarcini definite și aprobate din buget. Înainte de acea aprobare, totul — oricât de priceput, oricât de promițător — este planificare. Acordul învață această distincție din prima zi, astfel încât niciun tânăr să nu confunde exercițiul cu răsplata și niciun tânăr să nu fie vreodată indus în eroare cu privire la rostul simulării.

Aceeași disciplină guvernează cât de multă autonomie i se permite oricărui sistem, uman sau artificial, să exercite în interiorul rotației. Modurile de funcționare ale acordului avansează în secvență — Manual, apoi Semi-Automatizat, apoi Autonom — și niciun cub nu avansează un mod până nu îndeplinește regula de îmbunătățire măsurată de 11,1 procente, o parte din nouă, dovedită față de o linie de bază înghețată și atestată, nu doar afirmată. Simularea este locul unde se construiește această dovadă. Un instrument câștigă dreptul de a acționa cu mai puțină supraveghere în același fel în care un participant câștigă dreptul la mai multă responsabilitate: prin îmbunătățire demonstrată, înregistrată, reconstituibilă, cub cu cub, niciodată dintr-o dată și niciodată peste stratul unde se decid sensul, banii și legea. Acel strat aparține exclusiv Human Authority, atât în simulare, cât și în funcționarea reală, pentru că un spațiu de exercițiu care învață granița greșită învață o lecție greșită în mod permanent.

Fiecare rotație se încheie cu o sărbătoare publică și cooperativă, deschisă comunității-gazdă. Vecinii, familiile și vizitatorii se adună să vadă ce a învățat generația respectivă, iar ceea ce văd nu este o demonstrație de viteză de dragul vitezei, ci o demonstrație de ◬ — diferența măsurată dintre o linie de bază înghețată și ceea ce a reușit efectiv practica disciplinată, prezentată onest, niciodată deghizată în indicator de profit, niciodată prezentată ca fiind mai mult decât este. Aceste evenimente fac tehnologia sofisticată accesibilă și sărbătorită, nu înspăimântătoare. O societate care crește înțelegând sistemele cooperative prin joc nu poate fi ușor manipulată prin frica față de acele sisteme. Aceasta este descurajare prin educație, nu descurajare prin forță, și funcționează pentru că nu i se cere comunității să creadă o afirmație — este invitată să privească Replay-ul.

Promisiunea acordului către fiecare părinte se extinde dincolo de siguranță, spre permanență: copilul tău va exersa de o mie de ori înainte de a atinge orice l-ar putea răni, comunitatea îi va fi martoră creșterii pe tot parcursul, iar nimic din toate acestea nu se va pierde în timp. Measurement of Time înregistrează minutele reale separat de orice alt registru păstrat de acord, astfel încât orele de exercițiu și orele atestate să nu fie niciodată confundate între ele, și astfel încât adevărata istorie a dezvoltării unui participant — nu un rezumat, nu o aproximare, ci însăși înregistrarea reconstituibilă — să rămână disponibilă acelui participant atâta timp cât dorește să o consulte. Un părinte din Phnom Penh, un mentor din Tegucigalpa, un auditor din Austin sau un nepot care citește înregistrarea peste un secol pot ajunge cu toții la același Replay și pot vedea același adevăr.

Așa arată respectul pentru tânărul om atunci când este construit direct în structura unui cadru, nu doar promis de acesta, și acesta este ceea ce conducerea încredințează următoarei generații de participanți înainte ca acea generație să trebuiască să-l ceară: un spațiu de exercițiu suficient de vast pentru a greși în siguranță, suficient de onest pentru a înregistra fidel și suficient de disciplinat pentru a păstra răsplata, autonomia și autoritatea exact acolo unde măiestria le-a câștigat — nicăieri înaintea ei, nicăieri în urma ei.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Siguranța verificată înainte de acordarea încrederii`,
    content: {
      7: `Siguranța dovedită întâi, apoi încrederea acordată.`,
      33: `Fiecare facilitate și fiecare rotație se află într-un înveliș de protecție cu avertizare timpurie. Echipamentul refuză transformarea în armă — dovedit, nu doar promis, verificabil de către cetățeni. Înregistrările supraviețuiesc turbulențelor. Siguranța este construită zilnic în jurul celui mai tânăr participant.`,
      111: `Înainte ca încrederea să fie extinsă, siguranța trebuie dovedită — nu unui guvern, ci oricărui cetățean care o verifică. Acordurile Atlantis reprezintă un acord între cetățenii lumii; angajamentul său fondator este acesta: fiecare facilitate a acordului, fiecare traseu de rotație, fiecare loc în care un participant tânăr doarme sau studiază se află într-un înveliș de protecție documentat, cu capacitate de avertizare timpurie, care oferă comunității ore, nu minute, pentru a răspunde oricărui risc credibil. Fiecare dispozitiv, fiecare senzor, fiecare sistem de coordonare este legat la nivelul echipamentului să refuze reconvertirea pentru integrarea în sisteme de armament. Aceasta nu este politică — este fizică. Acordul rămâne onorabil în fața turbulențelor, pentru că fiecare plan pune demnitatea umană pe primul loc.`,
      333: `Înainte ca încrederea să fie extinsă, siguranța trebuie dovedită — dovedită cetățenilor, nu doar afirmată. Acordurile Atlantis reprezintă un acord între cetățenii lumii: orice persoană, oriunde, poate ajuta la susținerea lui, indiferent de ce semnează guvernul său. Fiecare facilitate a acordului, fiecare traseu de rotație, fiecare loc în care un participant tânăr doarme sau studiază se află într-un înveliș de protecție documentat, cu capacitate de avertizare timpurie, care oferă comunității ore, nu minute, pentru a răspunde oricărui risc credibil. Tehnologia care îi protejează este aceeași tehnologie pe care acordul îi învață să o construiască. Tinerii învață siguranța din interior spre exterior, nu pentru că li se spune că sunt în siguranță, ci pentru că o văd construită în jurul lor în fiecare zi și știu că orice cetățean poate verifica înregistrarea prin Replay.

Acordul face o promisiune de neîncălcat despre ceea ce tehnologia sa nu poate deveni. Fiecare dispozitiv, fiecare senzor, fiecare sistem de coordonare este legat la nivelul echipamentului să refuze reconvertirea pentru integrarea în sisteme de armament. Aceasta nu este o formulare de politică, nu este o aspirație. Este o imposibilitate fizică, impusă criptografic, verificată de fiecare regiune semnatară și verificabilă de fiecare cetățean care o finanțează. Uneltele care protejează un copil din Phnom Penh nu pot fi reconvertite pentru a face rău unui copil din Austin. Uneltele care conectează un exercițiu de tip roi în Tegucigalpa nu pot fi reconfigurate pentru a viza vreo ființă umană, oriunde. Acesta este răspunsul acordului la un secol de teamă legată de tehnologiile cu dublă utilizare. Nu politică — fizică.

Acordul rămâne onorabil în fața turbulențelor. Dacă o regiune își pierde stabilitatea politică, participanții sunt susținuți de celelalte regiuni. Dacă finanțarea se restrânge, indemnizațiile sunt protejate primele — finanțate lunar de cetățeni, niciodată printr-un canal de ajutor extern, fiecare dolar trasabil. Dacă înregistrările digitale sunt atacate, copiile de rezervă offline persistă. Dacă deplasarea devine imposibilă, substratul continuă virtual. Fiecare plan pune demnitatea umană — Human Authority asupra sensului, banilor și legii — drept prima sa constrângere de proiectare. Liderii care semnează acest acord promit că siguranța este construită, nu presupusă: protecția pe care orice lider ar cere-o pentru propriul copil, extinsă acum către fiecare cetățean care ajută la susținerea lui.`,
      999: `Înainte ca încrederea să fie extinsă, siguranța trebuie dovedită — acesta este angajamentul fondator al Acordurilor Atlantis, și este dovedit în același fel în care este dovedită orice altă afirmație din Vision • 2525: nu prin declarație, ci prin dovezi pe care cetățenii le pot verifica. Fiecare facilitate a acordului, fiecare traseu de rotație, fiecare loc în care un participant tânăr doarme sau studiază se află într-un înveliș de protecție documentat, cu capacitate de avertizare timpurie, care oferă comunității ore, nu minute, pentru a răspunde oricărui risc credibil. Tehnologia folosită pentru a proteja participanții este aceeași tehnologie pe care acordul îi învață să o construiască — senzori, coordonare, reziliența comunicațiilor, inteligență distribuită. Tinerii învață siguranța din interior spre exterior, în propria lor limbă și în propria lor regiune, nu pentru că li se spune că sunt în siguranță, ci privind, oră de oră, cum este construită siguranța în jurul lor, zi de zi.

Această observare nu este lăsată în seama memoriei sau a încrederii în cuvântul unui facilitator. Measurement of Time înregistrează minutele reale ale fiecărui exercițiu, fiecărei rotații, fiecărui exercițiu de răspuns — separat de orice afirmație de progres, separat de orice poveste spusă în acea zi. Replay face fiecare versiune a programei de instruire, fiecare actualizare de siguranță, fiecare revizuire de echipament pe deplin reconstituibilă, astfel încât un părinte din Tegucigalpa sau un organism de reglementare din Phnom Penh să poată parcurge înapoi exact ce s-a schimbat, când s-a schimbat și de ce s-a schimbat. Un înveliș de protecție care nu poate fi redat prin Replay este doar o promisiune. Un înveliș de protecție care poate fi redat, minut cu minut înregistrat, este o dovadă. Acordul alege dovada.

Acordul face o promisiune de neîncălcat despre ceea ce tehnologia sa nu poate deveni. Fiecare dispozitiv, fiecare senzor, fiecare sistem de coordonare este legat la nivelul echipamentului să refuze reconvertirea pentru integrarea în sisteme de armament. Aceasta nu este o formulare de politică, nu este o aspirație. Este o imposibilitate fizică, impusă criptografic, verificată de fiecare regiune semnatară și verificabilă de fiecare cetățean. Uneltele care protejează un copil din Phnom Penh nu pot fi reconvertite pentru a face rău unui copil din Austin. Uneltele care conectează un exercițiu de tip roi în Tegucigalpa nu pot fi reconfigurate pentru a viza vreo ființă umană, oriunde. Acesta este răspunsul acordului la un secol de teamă legată de tehnologiile cu dublă utilizare. Nu politică — fizică.

Siguranța dovedită o singură dată nu este siguranță susținută de-a lungul unui orizont de cinci sute de ani. Acordul numește al doilea său angajament Continuity Without Evasion: portabilitate legală în fiecare jurisdicție pe care o atinge acordul, fără ca vreun guvern, bancă, fondator sau model indispensabil să stea între un participant și protecția sa. Fiecare jurisdicție este deservită de propriul ei adaptor, cu închidere sigură în caz de eșec și refuz implicit, astfel încât o hotărâre nefavorabilă din orice regiune închide doar acel canal — niciodată întregul cadru, niciodată toate regiunile, niciodată toți participanții pretutindeni, deodată. O decizie judecătorească dintr-un teritoriu semnatar nu poate opri învelișul de siguranță al unui participant din altă parte. Așa arată construirea unui sistem care supraviețuiește turbulențelor obișnuite ale legii, politicii și schimbării instituționale, fără a-i cere vreodată unui participant să ocolească legea pentru a rămâne protejat.

Fiecare strat al acestei arhitecturi de protecție răspunde, în cele din urmă, în fața Human Authority. Sensul, banii și legea nu sunt niciodată delegate mașinilor — stratul suveran care decide ce anume cere siguranța, ce anume constituie un risc credibil și ce răspuns datorează o comunitate celor mai tineri membri ai săi rămâne închis inteligenței artificiale, oricât de capabilă ar deveni. Sistemele acordului avansează prin doar trei moduri de funcționare — Manual, Semi-Automatizat, Autonom — și niciun sistem nu avansează un mod fără o îmbunătățire atestată și măsurată de cel puțin o parte din nouă, unsprezece virgulă unu procente, verificată, reproductibilă. Autonomia se câștigă, cub cu cub, funcție cu funcție, niciodată acordată în bloc, și niciodată extinsă peste întrebările care determină sensul, banii sau legea. Un senzor poate învăța să detecteze mai rapid. Un sistem de coordonare poate învăța să dirijeze mai eficient. Niciunul dintre ele nu are voie vreodată să decidă, singur, ce anume ar trebui o comunitate să încredințeze copiilor săi.

Acordul este conceput să rămână onorabil în fața turbulențelor și numește turbulența dinainte, în loc să o descopere în criză. Dacă o regiune semnatară își pierde stabilitatea politică, participanții sunt susținuți de celelalte regiuni. Dacă finanțarea se restrânge, indemnizațiile participanților sunt protejate primele, înaintea administrației și infrastructurii. Dacă înregistrările digitale sunt atacate, copiile de rezervă offline persistă, inaccesibile oricărei defecțiuni care a afectat rețeaua. Dacă deplasarea devine imposibilă, substratul continuă virtual, astfel încât o rotație nu se oprește pentru că o frontieră s-a închis. Fiecare scenariu este planificat dinainte, iar fiecare plan pune demnitatea umană drept prima sa constrângere de proiectare — nu ultima considerație, după ce bugetele și imaginea publică au fost stabilite.

Intrarea în acest sistem dovedit începe cu Seed-ul — o apartenență unică, taxată la o șeptime dintr-o oră de salariu minim local, netransferabilă și fără nicio pretenție economică asupra a ceea ce construiește acordul ulterior. Seed-ul nu cumpără siguranța; siguranța este construită cu mult înainte ca vreun Seed să fie plantat. Ceea ce cumpără Seed-ul este statutul — dreptul de a păși într-un cadru deja dovedit, deja verificat, deja legat printr-un echipament care nu poate fi întors împotriva chiar a persoanei pe care există să o protejeze. Această separare este deliberată. O promisiune de siguranță care trebuie cumpărată cu o povară economică reală nu este deloc o promisiune de siguranță, ci doar un produs de siguranță. Acordul păstrează cele două lucruri complet separate, astfel încât nicio familie să nu trebuiască vreodată să cântărească protecția copilului ei față de bugetul lunar al gospodăriei.

Liderii care semnează acest acord semnează o promisiune că siguranța este construită, nu presupusă, și dovedită, nu doar afirmată. Ceea ce extind ei către cetățenii lor nu este doar oportunitate, ci protecție construită la standardul pe care îl merită cel mai tânăr participant — înregistrată de Measurement of Time, reconstituibilă prin Replay, legată la nivelul echipamentului împotriva oricărei utilizări greșite pe care un secol temător a imaginat-o, și răspunzătoare, întotdeauna și exclusiv, în fața Human Authority. Aceasta este aceeași protecție pe care orice lider ar cere-o pentru propriul copil care traversează singur o graniță necunoscută, extinsă acum către fiecare copil pe care acordul îl va deservi vreodată, în cele trei regiuni fondatoare ale sale — Cambodgia, Honduras și Austin — și de-a lungul celor cinci secole în care acordul intenționează să țină această promisiune.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Compensație, bunăstare și demnitate umană`,
    content: {
      7: `O indemnizație, un mentor, un cămin.`,
      33: `Fiecare cetățean primește o indemnizație din prima zi — fără permisiunea niciunui guvern, fără binecuvântarea niciunui angajator. Iubirea, pierderea și siguranța sunt infrastructură. Succesul se măsoară prin cel mai vulnerabil participant. Demnitatea este substrat, niciodată decor.`,
      111: `Acordurile Atlantis tratează fiecare participant ca pe o ființă umană din prima zi — un cetățean care s-a alăturat de drept, nu prin decret guvernamental sau prin voia unui angajator. O indemnizație este oferită din momentul în care începe participarea, indexată la costul vieții din regiune, iar fiecare oră atestată câștigă 웃, plătit persoanei prin Livelihood Direct, niciodată prin registrul unui angajator. Bunăstarea este tratată ca infrastructură de prim rang — nu un beneficiu suplimentar, ci substratul pe care se sprijină totul. Sunt susținute trei domenii: Iubirea, Pierderea și Siguranța. Acordul măsoară succesul prin cel mai vulnerabil participant al său, nu prin medie. Nimeni nu este uitat pentru ca mediile să arate bine. Demnitate ca substrat, nu ca decor.`,
      333: `Acordurile Atlantis tratează fiecare participant ca pe o ființă umană din prima zi — un cetățean care aparține de drept, fără să aibă nevoie de permisiunea niciunui guvern și de binecuvântarea niciunui angajator. O indemnizație este oferită din momentul în care începe participarea, indexată la costul vieții din regiune, ajungând înainte ca obligațiile familiale să devină urgențe. Aceasta nu este caritate. Este recunoașterea faptului că inovația umană obișnuită are nevoie, mai întâi, de securitate umană — o minte nu poate înflori cât timp gospodăria ei este amenințată.

Ceea ce se câștigă dincolo de indemnizație se câștigă așa cum câștigă un cetățean: prin Seed, taxat la o șeptime dintr-o oră de salariu minim local, și prin 웃, plătit doar pentru orele atestate. QIS măsoară promisiunea, dar nu emite nimic — măsurare, niciodată plată. Fiecare plată ajunge la participant prin Livelihood Direct, canale locale autorizate pe care acordul nu le administrează niciodată, construite pentru Continuity Without Evasion.

Bunăstarea este tratată ca infrastructură de prim rang — nu un beneficiu suplimentar, ci substratul pe care se sprijină totul. Acordul numește trei domenii prin care este susținut fiecare participant: Iubirea, conexiunea și limita sănătoasă; Pierderea, pentru că durerea trebuie însoțită, nu ocolită; și Siguranța, adică să știi pe cine să suni, în fiecare regiune, în propria limbă. Sunt oferite consiliere, cercuri de grup și practici culturale sau spirituale onorate potrivit fiecărei tradiții. Zero ideologie impusă; Human Authority, niciodată o mașină, decide de ce îngrijire are nevoie un cetățean.

Acordul măsoară succesul prin cel mai vulnerabil participant al său, nu prin medie. Cetățenii din mediul rural, fără conexiune de mare capacitate, sunt deserviți. Participanții neurodivergenți primesc adaptare ca normă, nu ca excepție. Participanții cu dizabilități găsesc fiecare facilitate accesibilă. Participanții cu identități de gen diverse primesc cazare sigură și asociere cu un mentor. Vorbitorii care nu au limba locală ca limbă maternă găsesc fiecare document în propria lor limbă. Participanții indigeni își găsesc practicile culturale onorate și cunoștințele tradiționale protejate. Liderii care semnează acest acord promit că niciun cetățean nu va fi uitat pentru ca mediile să arate bine. Aceasta este demnitatea ca substrat, nu ca decor. Ceea ce se măsoară este ceea ce va fi onorat, iar ceea ce este onorat aici este omul întreg — minte, corp și spirit, susținut de ceilalți cetățeni, fără excepție.`,
      999: `Acordurile Atlantis tratează fiecare participant ca pe o ființă umană întreagă din prima zi, construit în mecanism, nu doar în limbaj. O indemnizație este oferită din momentul în care începe participarea, indexată la costul vieții din regiune, astfel încât impactul ei să respecte demnitatea locală a muncii. Indemnizația ajunge înainte ca obligațiile familiale să devină urgențe și înainte ca demnitatea să fie compromisă. Ea semnalează fiecărui tânăr că timpul său este valoros, că se așteaptă contribuția sa și că stabilitatea familiei sale face parte din responsabilitatea acordului. Aceasta nu este caritate. Este recunoașterea faptului că inovația umană obișnuită are nevoie, mai întâi, de securitate umană. O minte nu poate înflori cât timp gospodăria ei este amenințată. Chiar intrarea presupune un prag mic și deliberat: Seed-ul, o apartenență unică, taxată la o șeptime dintr-o oră de salariu minim local, netransferabilă și fără nicio pretenție economică proprie. Seed-ul spune doar că o persoană s-a alăturat; nu o plătește și nu îi promite nimic dincolo de ușa pe care o deschide.

Ceea ce se câștigă după ce se deschide acea ușă este guvernat cu aceeași precizie pe care acordul o aduce oricărei alte promisiuni. 웃, măsura acordului pentru Human Intelligence, se calculează simplu — o oră la salariul minim local, înmulțită cu Multiplicatorul care reflectă dificultatea și valoarea sarcinii, ori numărul orelor efectiv lucrate. Dar 웃 se emite doar pentru munca atestată, prestată în cadrul unei sarcini definite și aprobate din buget. Înainte ca acea aprobare să existe, ceea ce face un participant este planificare, nu câștig — o distincție pe care acordul o menține ferm, pentru că protejează atât tezaurul, cât și participantul de promisiuni făcute mai repede decât poate fi verificată valoarea. Measurement of Time, MoT, înregistrează minutele efectiv lucrate separat de orice calcul de compensație, astfel încât timpul rămâne un fapt onest, verificabil, independent de plată. Orele niciunui participant nu sunt umflate, iar orele niciunui participant nu dispar. Un plafon de decontare de 9.999 웃 pe an se aplică fiecărui participant, orice surplus reportându-se în loc să dispară, astfel încât o contribuție excepțională este recunoscută de-a lungul mai multor ani, în loc să fie plafonată în invizibilitate într-un singur an.

Compensația este ținută în mod deliberat separată de măsurarea inovației. Qualified Innovation Score, QIS, mediază Venitul, Profitul Brut, Venitul Operațional și cheltuielile Efective de C&D pentru a descrie cât de mult a crescut cu adevărat inovația. Creșterea sa în timp poate dimensiona un fond de recompense odată îndeplinită calificarea, dar QIS în sine nu emite niciun 웃 și nu decontează nimic direct — este o măsurare, niciodată o plată, și nu este niciodată confundată cu proprietatea asupra a ceea ce a fost construit. Această separare contează pentru că menține onestă atât indemnizația, cât și salariul: un participant este plătit pentru ore atestate de muncă reală, nu pentru un scor care ar putea fi manipulat, umflat sau contestat. ♡, Shared Intention, poartă motivul din spatele fiecărei sarcini pe care o preia un participant; ◬, accelerarea atestată pe care o sarcină o produce față de o linie de bază înghețată, este înregistrată doar ca diferență, niciodată deghizată în indicator de profit atașat muncii vreunei persoane. Compensația rămâne ceea ce este: un salariu onest pentru un timp onest, atestat.

Valoarea nu se oprește la calcul — trebuie să ajungă și la participant, ca persoană vie, și aici își face treaba 🏠, Livelihood Direct. Fiecare unitate de valoare pe care o câștigă un participant ajunge la el prin canale locale calificate și autorizate — bănci, operatori de bani mobili, cooperative deja de încredere și reglementate în acea regiune — niciodată printr-un fond pe care acordul însuși îl administrează sau îl controlează. Clasificarea statutului unui participant precede orice decontare; nimic nu se plătește înainte de a se înțelege corect cine este plătit și pentru ce anume. Iar recunoașterea talentului, oricât de sărbătorită, nu condiționează accesul la un pat, la o masă sau la un loc în grup — doar rolul efectiv al participantului o face. Acesta este un refuz deliberat de a lăsa prestigiul să înlocuiască asigurarea traiului. Un contribuitor strălucit și unul discret dorm sub același acoperiș protejat, în aceleași condiții, pentru că angajamentele de demnitate ale acordului nu sunt un premiu acordat pentru excelență — sunt o podea sub picioarele tuturor.

Bunăstarea este tratată ca infrastructură de prim rang — nu un beneficiu opțional, nu un avantaj de wellness, ci substratul pe care se sprijină tot restul. Acordul numește trei domenii fundamentale prin care este susținut fiecare participant: Iubirea, în sensul conexiunii, atașamentului și limitei sănătoase; Pierderea, pentru că fiecare participant va trece prin durere și trebuie însoțit, nu ocolit; și Siguranța, în sensul că fiecare participant știe pe cine să sune, în fiecare regiune, în propria limbă. Sunt oferite consiliere individuală, cercuri de grup, practici somatice și practici culturale sau spirituale onorate potrivit propriei tradiții a participantului. Zero ideologie impusă. Acordul ține acest spațiu cu reverență; nu face prozelitism pentru niciun sistem de credințe. Human Authority guvernează fiecare dintre aceste decizii — sensul, banii și legea rămân închise deciziei mașinii, oricât de sofisticată ar fi recunoașterea de tipare care asistă oamenii care decid.

Acordul măsoară succesul prin rezultatul celui mai vulnerabil participant al său, nu prin medie. Participanții din mediul rural, fără conexiune de mare capacitate, sunt deserviți. Participanții neurodivergenți primesc adaptare ca normă. Participanții cu dizabilități găsesc fiecare facilitate accesibilă. Participanții cu identități de gen diverse primesc cazare sigură și asociere cu un mentor. Vorbitorii care nu au limba locală ca limbă maternă găsesc fiecare document în propria lor limbă. Participanții indigeni își găsesc practicile culturale onorate și cunoștințele tradiționale protejate. Liderii care semnează acest acord promit că niciun participant nu va fi uitat pe tăcute pentru ca mediile să arate bine.

Fiecare traseu de plată descris aici — Seed-ul, indemnizația, 웃 câștigat pentru muncă atestată, canalul Livelihood Direct care îl livrează — este proiectat pentru Continuity Without Evasion. Nicio bancă, niciun guvern sau operator local nu este indispensabil compensației vreunui participant; dacă un canal autorizat dintr-o jurisdicție este închis printr-o hotărâre nefavorabilă, doar acel canal cedează, niciodată întregul sistem și niciodată dreptul participantului la ceea ce i se cuvenea. Aceasta este demnitatea ca substrat, nu ca decor. Ceea ce se măsoară este ceea ce va fi onorat, iar ceea ce este onorat aici este omul întreg — minte, corp și spirit împreună, plătit onest, protejat pe deplin și uitat de nicio contabilitate, fără nicio excepție.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finanțare și guvernanță`,
    content: {
      7: `Cetățenii finanțează direct generația următoare.`,
      33: `Acordurile Atlantis reprezintă un acord între cetățeni — oricine îl poate finanța și susține. Fără canal de ajutor extern, fără binefăcător străin, fără condiționări politice. Fiecare dolar trasabil, contabilitatea publicată lunar, în fiecare limbă.`,
      111: `Acordurile Atlantis reprezintă un acord între cetățenii lumii — orice persoană, oriunde, poate ajuta la crearea și susținerea lui, indiferent de ce semnează guvernul său sau cine îl angajează. Guvernele, educatorii și inovatorii semnează ca administratori ai regiunilor lor; cetățenii finanțează, sunt martori și țin acordul direct răspunzător, fiecare contribuind cu sume mici, voluntare, în fiecare lună, suficient de modeste încât niciun adult să nu fie exclus prin cost. Nu există niciun canal de ajutor extern, niciun binefăcător străin, nicio condiționare politică atașată. Acordul stă independent de instituțiile multilaterale care au modelat secolul trecut — nu o declarație politică, ci o alegere de proiectare. Fiecare dolar este trasabil; fiecare raportare contabilă este publicată lunar, în fiecare limbă.`,
      333: `Acordurile Atlantis reprezintă un acord între cetățenii lumii — orice persoană, oriunde, poate ajuta la crearea și susținerea lui, indiferent de ce semnează guvernul său sau cine îl angajează. Este finanțat de cetățenii pe care îi deservește: locuitorii regiunilor participante contribuie cu sume mici, voluntare, în fiecare lună, suficient de modeste încât niciun adult să nu fie exclus prin cost, suficient de puternice cumulat încât totalul să susțină lucrarea acordului la scară. Când un cetățean finanțează direct generația următoare, acel cetățean ține acordul direct răspunzător. Nu există niciun canal de ajutor extern, niciun binefăcător străin, nicio condiționare politică atașată. Sufletul acordului este cetățeanul care contribuie cu o sumă mică în fiecare lună, a cărui participare îl face posibil.

Guvernul, Educația și Inovația semnează ca administratori ai regiunilor lor — trei semnături vizionare care leagă o regiune să găzduiască, să protejeze și să învețe — dar administrarea nu este proprietate. Acordul este independent de instituțiile multilaterale care au modelat secolul trecut — Organizația Tratatului Atlanticului de Nord, Organizația Mondială a Sănătății, Organizația Națiunilor Unite, Fondul Monetar Internațional, Banca Mondială și orice canal național de ajutor extern. Aceasta este o alegere de proiectare, nu o declarație politică: un cadru care deservește fiecare regiune, indiferent de alinierea geopolitică, nu se poate lăsa înlănțuit de nicio aliniere anume. Guvernele naționale pot contribui voluntar. Contribuțiile sunt transparente. Nicio contribuție nu cumpără influență asupra guvernanței, din nicio sursă, niciodată.

Fiecare dolar și fiecare unitate de valoare care intră în acord este înregistrată permanent, public și trasabil — reconstituibilă prin Replay, astfel încât un cetățean peste un secol să poată verifica lanțul neîntrerupt. Valoarea ajunge la un participant prin orele de 웃 atestate și prin canale locale autorizate, niciodată printr-un fond pe care acordul însuși îl administrează; QIS măsoară onest, nu plătește niciodată. Cheltuielile administrative sunt plafonate, iar donațiile corporative sunt plafonate la fel. O raportare contabilă completă este livrată în limba fiecărei regiuni semnatare, în fiecare lună. Liderii care semnează acordul promit o transparență rar oferită de vreo instituție. Aceasta este încrederea pe care o cere acordul — câștigată câte o contribuție mică și trasabilă odată, sub privirea fiecărui cetățean.`,
      999: `Acordurile Atlantis însele sunt finanțate de cetățenii pe care îi deservesc, iar acest singur fapt modelează tot ce decurge din el — fiecare canal, fiecare registru, fiecare prag pe care un tânăr trebuie să-l treacă pentru a fi văzut. Locuitorii obișnuiți ai regiunilor participante contribuie cu sume mici, voluntare, în fiecare lună, sume suficient de modeste încât niciun adult din vreo regiune-gazdă să nu fie exclus prin cost, suficient de puternice cumulat încât totalul să susțină lucrarea acordului la o scară semnificativă. Această proiectare este deliberată și nu este incidentală misiunii — este dovada misiunii. Când un cetățean finanțează direct educația generației următoare, acel cetățean ține acordul direct răspunzător, în aceeași suflare, fără un intermediar care ar putea îndulci contul sau întârzia socoteala. Nu există niciun canal de ajutor extern, niciun binefăcător străin, nicio condiționare politică atașată cecului. Sufletul acordului este cetățeanul care contribuie cu o sumă mică în fiecare lună, a cărui participare face posibil întregul, și a cărui participare continuă este singurul vot de încredere care contează, în ultimă instanță, de-a lungul a cinci sute de ani.

Acordul este independent în mod deliberat de instituțiile multilaterale care au modelat secolul trecut — Organizația Tratatului Atlanticului de Nord, Organizația Mondială a Sănătății, Organizația Națiunilor Unite, Fondul Monetar Internațional, Banca Mondială și orice canal național de ajutor extern. Aceasta nu este o declarație politică despre valoarea acelor instituții sau a contribuțiilor lor. Este o alegere de proiectare, și este aceeași alegere de proiectare care guvernează fiecare canal tehnic aflat la baza acordului însuși: Continuity Without Evasion. Portabilitatea legală este regula — niciun guvern, bancă, fondator sau model indispensabil nu poate sta la baza întregii structuri, pentru că un orizont de cinci sute de ani nu poate fi pariat pe permanența unui singur actor. Fiecare jurisdicție poartă propriul ei adaptor, cu închidere sigură în caz de eșec și refuz implicit, astfel încât o hotărâre nefavorabilă dintr-o națiune închide doar acel canal, și numai acela — niciodată nu prăbușește conturile unei familii dintr-o regiune aflată la un ocean distanță. Guvernele naționale pot contribui voluntar. Contribuțiile sunt transparente. Nicio contribuție nu cumpără influență asupra guvernanței, din nicio sursă, niciodată — nici de la un guvern, nici de la o corporație, nici de la fondatorii înșiși ai cadrului.

Human Authority este al doilea pilon de susținere al acestei proiectări de finanțare. Sensul, banii și legea rămân chestiuni umane, decise de ființe umane sub privirea altor ființe umane; stratul suveran în care se stabilește scopul acordului și se guvernează fondurile sale rămâne închis mașinilor, oricât de capabile ar deveni acestea în sarcinile aflate mai jos. Measurement of Time înregistrează minutele efectiv lucrate separat de orice afirmație despre valoarea lor, astfel încât nimeni — om sau mașină — să nu poată umfla pe tăcute înregistrarea. Replay stă în spatele fiecăreia dintre aceste înregistrări, făcând fiecare versiune pe care acordul însuși o emite vreodată reconstituibilă de la origine, permanent deschisă contestării, permanent deschisă corectării. Un cetățean care contribuie astăzi cu o sumă mică are încredere că, peste cincizeci de ani, peste două sute de ani, cineva va putea încă să parcurgă lanțul înapoi până la registrul lunii acesteia și să-l găsească exact așa cum era.

Intrarea în acest sistem de încredere începe cu Seed-ul — o apartenență unică, taxată la o șeptime dintr-o oră de salariu minim local, netransferabilă și fără nicio pretenție economică de orice fel. Seed-ul nu cumpără nicio cotă, niciun vot cântărit după avere, niciun statut privilegiat în contabilitatea care urmează. Cumpără doar apartenența, la un preț suficient de mic încât un tânăr, oriunde operează acordul, să și-l poată permite pentru a începe. Tot ce câștigă un membru după acel punct este câștigat, niciodată cumpărat, iar această distincție este întreaga arhitectură morală a acordului, în miniatură.

Valoarea care ajunge efectiv la o persoană curge prin 🏠 Livelihood Direct — canale locale calificate, autorizate, care duc plata la persoană, niciodată într-un fond pe care cadrul însuși îl administrează sau îl controlează. Clasificarea precede decontarea în fiecare caz; un pat, o indemnizație, un loc în etapa următoare de instruire este condiționat de rol și de pregătire, niciodată doar de recunoaștere, pentru că recunoașterea este ieftină, iar asigurarea traiului nu este. Acesta este lanțul pe care îl parcurge efectiv contribuția lunară a unui cetățean: din contul cetățeanului, printr-un canal auditat, în indemnizația pe care o primește un tânăr, în proiectul de inovație pe care îl devine munca acelui tânăr, și înapoi, ca o contabilitate publică pe care orice cetățean o poate citi.

Cât valorează acea muncă se măsoară, nu se presupune. Qualified Innovation Score mediază pregătirea, potențialul de creștere, impactul rezultatelor și pregătirea pentru execuție într-un singur număr, iar creșterea acestui scor dimensionează fondul de recompense doar după îndeplinirea calificării — QIS în sine nu emite nimic și nu decontează nimic; este măsurare, niciodată plată, iar măsurarea nu este niciodată confundată aici cu proprietatea. Plata pentru munca umană sosește în schimb ca 웃, evaluat la o oră înmulțită cu salariul minim local, înmulțit cu un multiplicator definit și aprobat din buget, aplicat orelor efectiv lucrate și atestate. Înainte ca o sarcină să poarte acea aprobare, munca din spatele ei este planificare, nu muncă remunerabilă, și nimeni nu este plătit ca să planifice. Un plafon de 9.999 웃 pe an, cu orice surplus reportat în loc să dispară, împiedică drept contul oricărui an anume să devină fie un câștig neașteptat, fie o capcană.

Nimic din toate acestea nu avansează mai repede decât propria sa dovadă. Acordul însuși avansează de la funcționarea Manuală la cea Semi-Automatizată și apoi Autonomă, un cub odată, și numai acolo unde a fost efectiv demonstrată o ordine întreagă de îmbunătățire măsurată — o parte din nouă — niciodată presupusă dinainte. Autonomia se câștigă exact acolo și nicăieri în apropierea sensului, banilor sau legii, care rămân întotdeauna umane. Cheltuielile administrative sunt plafonate. Donațiile corporative și instituționale sunt binevenite și plafonate la fel. O raportare contabilă completă este livrată în limba fiecărei regiuni semnatare, în fiecare lună, începând din Cambodgia, Honduras și Austin, menită să fie livrată în continuare, și încă lizibilă, și peste cinci sute de ani. Aceasta este încrederea pe care o cere acordul. Aceasta este încrederea pe care o câștigă acordul, câte o contribuție mică și trasabilă odată, sub privirea fiecărui cetățean pe care îl va deservi vreodată.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Schimb intercultural și contribuție globală`,
    content: {
      7: `Fiecare învățăcel în propria limbă.`,
      33: `Fiecare activitate în limba participantului — deschisă oricărui cetățean, fără să fie nevoie de permisiunea niciunui guvern. Inteligențele Artificială, Umană și Comună sunt ținute într-o tensiune productivă. Programele sunt publicate deschis. Ce învață o regiune, moștenesc toate.`,
      111: `Acordurile Atlantis readuc educația la scopul ei cel mai profund: schimbul de înțelepciune peste granițe care altfel ar diviza. Orice cetățean poate intra în această programă, indiferent de ce a semnat guvernul său. Fiecare activitate este disponibilă în limba participantului, în limba regiunii-gazdă și într-o înregistrare comună. Limba nu este decor — limba este jurisdicție, limba este demnitate făcută lizibilă. Cadrul educațional se sprijină pe trinitatea inteligențelor: cea Artificială propune, cea Umană decide, Shared Intent validează. Fiecare student învață să le țină pe toate trei în tensiune. Ceea ce învață acordul, dă înapoi. Programele, rezultatele inovației, cercetarea privind bunăstarea și deciziile de guvernanță sunt publicate deschis. Ce învață o regiune, moștenesc toți cetățenii.`,
      333: `Acordurile Atlantis readuc educația la scopul ei cel mai profund: schimbul de înțelepciune peste granițe care altfel ar diviza. Acesta este un acord între cetățenii lumii — orice cetățean îl poate construi și susține, indiferent de ce a semnat guvernul său. Fiecare activitate este disponibilă în limba participantului, în limba regiunii-gazdă și într-o înregistrare comună, astfel încât niciun participant să nu navigheze prin acord într-o limbă pe care nu a ales-o. Limba nu este decor. Limba este jurisdicție. Limba este demnitate făcută lizibilă. Un tânăr din Cambodgia își citește înregistrarea indemnizației în khmeră, unul din Honduras în spaniolă, unul din Austin în engleză — toate trei onorate în mod egal, niciuna nefiind nevoie de binecuvântarea vreunui guvern pentru a începe.

Cadrul educațional se sprijină pe trinitatea inteligențelor pe care Vision • 2525 o face vizibilă. Inteligența Artificială propune tipare și posibilități mai repede decât ar putea vreodată un om singur. Inteligența Umană decide asupra siguranței, eticii și direcției — întrebări la care nicio mașină nu ar trebui să răspundă, păstrate sub Human Authority. Shared Intent validează faptul că deciziile servesc principiile acordului, astfel încât niciun participant să nu aleagă excelența în locul binelui colectiv. Niciun student nu se supune unei singure inteligențe; fiecare student învață să le țină pe toate trei în tensiune. Apartenența începe cu Seed-ul, o apartenență taxată la o șeptime dintr-o oră de salariu minim local — suficient de mică încât orice cetățean să și-o poată permite. Aceasta pregătește generația următoare să guverneze, acolo unde nicio inteligență nu acționează nesupravegheată.

Ceea ce învață acordul, dă înapoi. Programele sunt publicate sub licență deschisă, astfel încât orice regiune — semnatară sau nu — le poate adapta la cultura locală. Rezultatele inovației sunt publicate. Cercetarea privind bunăstarea este publicată agregat, pentru cercetători de pretutindeni. Deciziile de guvernanță sunt publicate împreună cu raționamentul din spatele lor, astfel încât orice cetățean, nu doar un guvern semnatar, le poate verifica — iar Replay îi permite aceluiași cetățean să refacă raționamentul peste un secol. Succesul se măsoară nu doar prin participanții săi, ci prin inițiativele educaționale și culturale care apar în urma sa, în regiuni care nu au semnat niciodată proiectul-pilot, dar au construit pe înțelepciunea sa comună. Ce învață o regiune, moștenește fiecare cetățean.`,
      999: `Acordurile Atlantis readuc educația la scopul ei cel mai profund: schimbul de înțelepciune peste granițe care altfel ar diviza, iar acest schimb începe înainte ca vreo lecție să fie predată. Primul act al fiecărui participant în interiorul cadrului este Seed-ul — o apartenență unică, taxată la o șeptime dintr-o oră de salariu minim local, netransferabilă, fără nicio pretenție economică de orice fel. Este suficient de mic încât nicio familie să nu fie exclusă și suficient de real încât niciun participant să nu intre ca simplu spectator. Aceasta este prima lecție a acordului: apartenența se câștigă ieftin, dar tot se câștigă, și nu conferă nicio proprietate asupra a ceea ce urmează. Fiecare activitate a acordului care urmează este disponibilă în limba participantului, în limba regiunii-gazdă și într-o înregistrare comună, astfel încât niciun participant să nu navigheze prin acord într-o limbă pe care nu a ales-o. Limba nu este decor. Limba este jurisdicție. Limba este demnitate făcută lizibilă. Când un tânăr dintr-un sat cambodgian își citește înregistrarea indemnizației în khmeră, un oraș honduriens în spaniolă și un cartier din Austin în engleză, toate trei sunt onorate în mod egal de același acord, în aceleași regiuni fondatoare care au fost primele care au convenit să se învețe una pe alta.

Cadrul educațional al acordului se sprijină pe trinitatea inteligențelor pe care Vision • 2525 o face vizibilă, iar programa predă fiecare inteligență ca pe ceva ce un participant poate simți în propriile mâini, nu ca abstracție. ♡, Shared Intention, poartă motivul — firul pe care fiecare student învață să-l țină înainte de a atinge orice instrument, întrebarea dacă această muncă mai servește încă oamenilor cărora pretinde că le servește. ◬, accelerarea atestată, este predată ca o diferență și nimic mai mult — măsurată doar față de o linie de bază înghețată, niciodată deghizată în indicator de profit, niciodată revendicată drept realizare personală, separat de echipa din jur. 웃, Human Intelligence onorată în timp, este predată cel mai atent: o oră de muncă atestată echivalează cu o oră la salariul minim local, iar ceea ce câștigă un participant este acel salariu înmulțit cu orele lucrate — Multiplicator ori Timp, nimic ascuns în aritmetică. Studenții învață devreme că 웃 se emite doar pentru munca atestată, prestată în cadrul unei sarcini definite și aprobate din buget. Înainte ca acea aprobare să existe, același efort este doar planificare — valoros, dar neplătit, iar fiecare participant este învățat să recunoască diferența dintr-o privire.

Pentru că această diferență se estompează ușor, programa predă QIS, Qualified Innovation Score, ca pe o oglindă, nu ca pe un tabel de scor. QIS este media a patru mărimi financiare absolute — Venit, Profit Brut, Venit Operațional și C&D Efectiv — împărțită la patru, iar fiecare student învață să o calculeze, să o pună sub semnul întrebării și să nu o confunde niciodată cu banii. Creșterea QIS dimensionează fondul de recompense doar după ce calificarea este confirmată independent, iar acea creștere nu emite niciun 웃 de la sine. QIS este măsurare. QIS nu este niciodată plată. QIS nu înseamnă niciodată proprietate. Un student care a interiorizat această distincție nu poate fi convins că un scor mare îi dă dreptul la o pretenție pe care acordul nu a promis-o niciodată.

Programă extinde această educație spre modul în care valoarea ajunge efectiv la o persoană, prin ceea ce acordul numește Livelihood Direct — principiul 🏠 potrivit căruia banii circulă prin canale locale calificate și autorizate, niciodată printr-un fond pe care cadrul însuși îl administrează. Studenții sunt învățați să-și urmărească indemnizația, și mai târziu propriile câștiguri, prin aceste canale, ca exercițiu civic, nu ca pe un mister financiar desfășurat în altă parte, în numele lor. Ei învață că clasificarea precede întotdeauna decontarea și că recunoașterea — un QIS mare, o mențiune publică — nu condiționează, prin ea însăși, un pat, o indemnizație sau un loc în rotație. Rolul o face. Aceasta este o protecție împotriva unui eșec foarte vechi: lauda confundată cu asigurarea traiului.

Alături de educația financiară stă educația civică, predată prin Continuity Without Evasion. Fiecare participant învață că acordul este construit pentru portabilitate legală — că niciun guvern, bancă, fondator sau model indispensabil nu stă între ei și promisiunile cadrului. Ei învață ce face o hotărâre nefavorabilă în interiorul acestei proiectări: închide doar un canal, într-o singură jurisdicție, sub poziția de refuz implicit a acelui adaptor, și nu prăbușește niciodată întregul. Alături de aceasta stă cea mai profundă lecție pe care o predă acordul: Human Authority păstrează sensul, banii și legea, iar stratul suveran în care se iau acele decizii rămâne permanent închis mașinilor. Measurement of Time, MoT, înregistrează minutele reale ale fiecărui participant separat de orice scor, iar Replay face fiecare versiune emisă de acord pe deplin reconstituibilă — astfel încât un student care vrea să știe de ce a fost luată o decizie, ani mai târziu, o poate reface singur, în loc să creadă pe cuvânt pe cineva.

Această structură a încrederii câștigate devine modelul pedagogic al acordului, nu doar modelul său de guvernanță. Fiecare participant avansează prin moduri Manual, Semi-Automatizat și Autonom, de libertate crescândă, condiționate de același prag de îmbunătățire măsurată care condiționează tehnologia însăși — un câștig verificat de unsprezece virgulă unu la sută înainte ca modul următor să se deschidă. Autonomia, atunci când este câștigată, este câștigată îngust și pe domeniu, niciodată peste sens, bani sau lege. Un student care a trăit această progresie înțelege, visceral, de ce stratul suveran nu trebuie automatizat niciodată — pentru că și-a câștigat propria autonomie câte un pas măsurat odată, și știe exact ce a inclus și ce nu a inclus acea autonomie.

Ceea ce învață acordul, acordul dă înapoi. Programele sunt publicate sub licență deschisă, astfel încât orice regiune — semnatară sau nu — le poate adapta la cultura și tradiția pedagogică locală. Rezultatele inovației sunt publicate. Cercetarea privind bunăstarea este publicată agregat, pentru cercetători de pretutindeni. Deciziile de guvernanță sunt publicate cu întregul lor raționament intact. Succesul acordului se măsoară nu doar prin propriii săi participanți din Cambodgia, Honduras și Austin, ci și prin inițiativele care apar în urma sa, în regiuni care nu au semnat niciodată proiectul-pilot fondator, dar au construit pe înțelepciunea sa împărtășită deschis, de-a lungul unui orizont pe care fondatorii nu vor apuca să-l vadă încheiat. Ce învață o regiune, moștenesc toate celelalte regiuni — iar ceea ce această generație este învățată onest, următorii cinci sute de ani nu vor trebui să dezînvețe.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Creșterea sustenabilă a rețelei`,
    content: {
      7: `Niciodată mai repede decât poate călători demnitatea.`,
      33: `Trei regiuni fondatoare încheie un ciclu-pilot complet înainte ca o a patra să se alăture — orice cetățean o poate construi. Înregistrările sunt ancorate să dăinuie cinci secole. Semnatarii își păstrează suveranitatea; nimic nu este diminuat pentru cei care se alătură ulterior.`,
      111: `Acordurile Atlantis nu vor crește mai repede decât calitatea pe care o pot onora. Trei regiuni fondatoare trebuie să încheie un ciclu-pilot complet, cu fiecare participant onorat și fiecare principiu verificat, înainte ca o a patra regiune să se alăture. Acesta este principiul devenit, în sfârșit, disciplină funcțională. Dar acordul este un acord între cetățenii lumii — orice persoană, oriunde, îl poate construi și susține, la un Seed distanță, indiferent de ce semnează un guvern sau permite un angajator. Orizontul acordului este de cinci secole. Înregistrările sale sunt ancorate prin Replay, astfel încât un cetățean care le citește peste un secol să poată avea încredere în raționament. Fiecare semnatar își păstrează suveranitatea; nimic nu este diminuat pentru cei care se alătură ulterior.`,
      333: `Acordurile Atlantis nu vor crește mai repede decât calitatea pe care o pot onora. Fiecare extindere este o promisiune făcută participanților deja aflați înăuntru — că standardul fondator nu va fi diluat de scară. Trei regiuni fondatoare trebuie să încheie un ciclu-pilot complet, cu fiecare participant onorat și fiecare principiu verificat, înainte ca o a patra regiune să se alăture. Acesta este principiul devenit, în sfârșit, disciplină funcțională. Iar ușa nu a fost niciodată doar regională: acesta este un acord între cetățenii lumii, și orice persoană îl poate construi, finanța și ține răspunzător — fără să fie nevoie de permisiunea niciunui guvern sau de binecuvântarea niciunui angajator. Liderii care semnează proiectul-pilot promit semnatarilor același substrat, aceeași protecție și aceeași demnitate pe care le-a primit generația fondatoare. Nimic nu este diminuat pentru cei care urmează.

Orizontul acordului este în mod deliberat lung — conceput să dăinuie cincisprezece până la douăzeci de generații umane, cinci secole de la ziua fondării. Înregistrările sale sunt ancorate prin Replay, astfel încât un cetățean care le citește peste un secol să poată verifica raționamentul, nu doar să aibă încredere în el. Cadrul său de coordonate, rolurile sale de Human Authority și ciclurile sale de guvernanță transgenerațională sunt construite să supraviețuiască oricărei tranziții tehnologice singulare. Acordul va supraviețui fiecărui om care îi semnează proiectul-pilot fondator și fiecărui cetățean care plantează un Seed și îl finanțează lunar. Aceasta este promisiunea sa către copilul care semnează un acord de indemnizație, către cetățeanul care s-a alăturat fără să datoreze nimic vreunui guvern, către nepoții acelui copil care ar putea guverna acordul la mijlocul secolului, și către fiecare generație care moștenește ceea ce fondatorii — oficiali și cetățeni deopotrivă — construiesc acum.

Fiecare semnatar își păstrează libertatea de a se retrage, suveranitatea deplină și autoritatea asupra propriilor cetățeni, cu dreptul de a amenda și de a modela evoluția acordului. Fiecare cetățean își păstrează același statut de a fonda, finanța, atesta și ține acordul răspunzător — cu sau fără semnătura vreunui guvern. Ceea ce niciunul nu poate face este să compromită principiile fondatoare, pentru că acea promisiune trebuie să supraviețuiască oricărei retrageri. Liderii și cetățenii deopotrivă semnează următorul secol al acordului într-un orizont pe care nepoții lor îl vor moșteni și îl vor desăvârși.`,
      999: `Acordurile Atlantis nu vor crește mai repede decât calitatea pe care o pot onora, iar această reținere nu este sentiment — este inginerie, înscrisă în aceeași disciplină de măsurare care guvernează fiecare promisiune făcută de acord. Trei regiuni fondatoare, Cambodgia, Honduras și Austin, trebuie să încheie un ciclu-pilot complet, cu fiecare participant onorat și fiecare principiu verificat, înainte ca o a patra regiune să se alăture. O creștere care depășește verificarea nu este creștere; este expunere îmbrăcată în costumul ambiției. Proiectul-pilot fondator există pentru ca acordul să poată dovedi, la o scară suficient de mică pentru a fi verificată și suficient de mare pentru a conta, că promisiunile sale supraviețuiesc contactului cu realitatea înainte ca acele promisiuni să fie extinse către o lume care privește din afara celor trei granițe ale sale. A patra regiune nu este încă numită și nu va fi până ce primele trei nu vor sta în spatele fiecărei afirmații pe care o face acest document.

Ceea ce dovedește pregătirea pentru creștere nu este entuziasmul, ci un număr pe care acordul îl poate apăra public. Qualified Innovation Score — QIS, calculat ca Venit plus Profit Brut plus Venit Operațional plus cheltuielile Efective de C&D, împărțit la patru — este instrumentul folosit de acord pentru a ști dacă o regiune, o generație sau un cub s-a îmbunătățit, nu doar a simțit că s-a îmbunătățit. Creșterea QIS dimensionează fondul de recompense doar după îndeplinirea calificării, niciodată înainte, iar QIS în sine nu emite niciun 웃 și nu cumpără nicio proprietate. QIS este măsurare, nu plată; măsurare, nu capital; o oglindă pe care acordul o ține în fața propriei sale lucrări, niciodată o monedă pe care o cheltuiește. O regiune care propune extinderea rețelei trebuie să-și arate onest QIS-ul, sub privirea regiunilor dinaintea ei, sau nu se extinde.

Creșterea sustenabilă înseamnă creștere care își câștigă propria autoritate câte un increment odată. Fiecare cub și fiecare regiune încep în modul Manual, unde oamenii decid totul, iar sistemul doar asistă. Avansarea către funcționarea Semi-Automatizată, și în cele din urmă Autonomă, în interiorul unui cub dat, este condiționată de un singur prag de-a lungul întregului acord — o îmbunătățire măsurată de unsprezece virgulă unu la sută, o parte din nouă, dovedită și reproductibilă înainte ca următorul grad de autonomie să fie acordat. Autonomia se câștigă cub cu cub, niciodată revendicată în bloc și niciodată extinsă peste domeniile care trebuie să rămână umane, oricât de avansat ar deveni sistemul: sensul, banii și legea rămân închise mașinilor, indiferent de câte praguri sunt depășite în altă parte. O rețea care își extinde automatizarea mai repede decât își extinde dovezile nu se modernizează. Ea pariază cu o încredere pe care încă nu a câștigat-o.

Compensația crește odată cu rețeaua în același fel în care crește autoritatea — deliberat, și cu un plafon care protejează întregul sistem de propriul său succes. 웃, tokenul Human Intelligence, echivalează cu o oră de muncă atestată înmulțită cu salariul minim local; ceea ce câștigă orice participant este acel Multiplicator ori orele lucrate, și se emite doar pentru muncă prestată în cadrul unei sarcini definite și aprobate din buget. Înainte de aprobare, cel mai bun plan este doar planificare, iar planificarea singură nu emite nimic. Decontarea fiecărui participant este plafonată la 9.999 웃 pe an, orice surplus reportându-se în loc să dispară sau să distorsioneze fondul. Pe măsură ce noi regiuni se alătură, iar activitatea rețelei se multiplică, acest plafon este cel care împiedică creșterea să devină inflație — valoarea rămâne legată de ore reale, atestate, locale, indiferent cât de mare devine acordul.

În spatele fiecărui 웃 stă un motiv pe care niciun registru nu îl poate calcula de unul singur. ♡, Shared Intention, poartă acel motiv mai departe, prin fiecare decizie de extindere pe care o ia acordul, în timp ce ◬, contribuția Inteligenței Artificiale, este socotită ca accelerare atestată, măsurată față de o linie de bază înghețată — o diferență, și niciodată, sub nicio formă, un indicator de profit de optimizat de dragul lui însuși. Intrarea în această rețea începe în același fel pentru fiecare participant, indiferent de regiunea sau de decada în care se alătură: cu un Seed, o apartenență unică, taxată la o șeptime dintr-o oră de salariu minim local, netransferabilă și fără nicio pretenție economică de orice fel. Seed-ul spune doar că o persoană a sosit. Tot ce construiește ulterior, construiește sub privirea deplină a celorlalte trei monede ale acordului, niciodată prin Seed-ul însuși.

Creșterea reală trebuie să fie și o creștere care ajunge la o persoană reală, nu la un fond pe care cadrul îl deține în numele cuiva. 🏠 Livelihood Direct cere ca valoarea să circule către un participant doar prin canale locale calificate și autorizate, verificate de acord regiune cu regiune, și niciodată printr-o custodie pe care cadrul însuși o păstrează. Clasificarea precede întotdeauna decontarea, astfel încât nicio valoare nu circulă înainte ca scopul și destinatarul ei să fie amândouă stabilite dincolo de orice îndoială. Iar pentru că recunoașterea nu este același lucru cu accesul, un pat, un loc în rotație, un scaun la masă este condiționat de rol și de pregătire, niciodată de scorul sau statutul unui participant. Pe măsură ce rețeaua se extinde într-o a patra regiune și dincolo de ea, fiecare teritoriu nou trebuie să-și califice propriile canale autorizate înainte ca Livelihood Direct să poată ajunge la oamenii săi — extindere a încrederii, nu doar extindere a teritoriului.

Nimic din toate acestea nu dăinuie fără o rețea construită să supraviețuiască propriului ei succes, motiv pentru care Continuity Without Evasion guvernează fiecare regiune adăugată vreodată de acord. Portabilitatea legală este obligatorie; niciun guvern, bancă, fondator sau model singular nu poate deveni indispensabil întregului. Fiecare jurisdicție rulează propriul ei adaptor, cu închidere sigură în caz de eșec și refuz implicit, astfel încât o hotărâre nefavorabilă, oriunde ar apărea, închide un singur canal, niciodată întregul acord. Human Authority păstrează sensul, banii și legea la orice scară atinge rețeaua, sigilate împotriva încălcării de către mașini prin proiectare, nu doar prin promisiune. Measurement of Time înregistrează fiecare minut real separat de orice afirmație despre el, iar Replay asigură că orice versiune, în orice regiune, în orice moment de-a lungul a cinci secole, poate fi reconstituită și reexaminată de oricine solicită asta. O rețea care nu poate fi redată prin Replay nu poate fi de încredere, indiferent de câte regiuni i s-au alăturat sau cât de impresionantă pare creșterea ei privită din afară. Așa crește Vision • 2525 fără să depășească vreodată încrederea pe care a fost construită s-o păstreze — o regiune verificată, un QIS onest, o oră atestată odată.`,
    },
  },
];
