import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_SW: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Pale ubunifu unapoanzia`,
    content: {
      7: `Viongozi wanaanzisha ambacho hakuna karne iliyoanzisha.`,
      33: `Maeneo matatu — Kambodia, Honduras, Austin — yanafungua ahadi ambayo raia wanasaidia kuijenga: kukaribisha wanafunzi, kuwalinda, na kuwakabidhi zana za wakati ujao. Serikali, Elimu, na Ubunifu wanatia saini kama walezi; raia ndio wanaoishikilia. Mwanzo mmoja.`,
      111: `Mkataba wa Atlantis ni makubaliano baina ya raia wa dunia — ahadi ambayo mtu yeyote, popote alipo, anaweza kuianzisha na kuishikilia, bila kujali serikali yake inatia saini nini au mwajiri wake anaruhusu nini. Maeneo yake ya kianzilishi, Kambodia, Honduras, na Austin, Texas, yalichaguliwa kwa sifa moja adimu: utayari wa kuwaamini vijana na zana za wakati ujao wakati bado kuna muda wa kuwafundisha. Serikali, waelimishaji, na wabunifu wanatia saini kama walezi wa maeneo yao — saini tatu za kimaono kwa kila eneo, Serikali, Elimu, Ubunifu — lakini raia ndio wanaogharamia mkataba, kushuhudia kazi yake, na kuushikilia uwajibikaji moja kwa moja. Hakuna idhini ya serikali wala baraka ya mwajiri inayohitajika ili kuwa mwanachama. Maeneo matatu, mwanzo mmoja wa pamoja.`,
      333: `Kila ustaarabu unakumbukwa kwa kile ulichochagua kukianzisha. Mkataba wa Atlantis ni ahadi baina ya raia wa dunia — mtu yeyote, popote alipo, anaweza kuuanzisha, bila kujali serikali yake inatia saini nini. Maeneo yake ya kianzilishi, Kambodia, Honduras, na Austin, Texas, hayakuchaguliwa kwa nguvu za kiuchumi, uwezo wa kijeshi, au heshima ya kitaasisi, bali kwa sifa adimu zaidi: utayari wa kuwaamini vijana na zana za wakati ujao. Hii ndiyo maana ya uongozi katika karne ijayo — ujasiri wa kukabidhi funguo kwa kizazi kijacho wakati bado kuna muda wa kuwafundisha jinsi ya kuendesha.

Mkataba huu unaitishwa na eXeL, nguvu ya uratibu iliyojengwa mahususi kwa ajili ya wakati huu, ikiwepo nje ya njia za uratibu zilizounda karne iliyopita — nje ya miundo ya mikataba ya kidiplomasia, urasimu wa kimataifa, na mafungamano ya kisiasa ya taifa lolote moja. eXeL ndiye mwitishaji anayeaminika anayekutanisha viongozi wenye maono kuzunguka mfumo wa pamoja, gurudumu la nguvu la pamoja, na upeo wa pamoja wa miaka mia tano. Kila mtia-saini anabaki na uhuru kamili wa kujitawala, mamlaka kamili juu ya raia wake, na uhuru kamili wa kujiondoa wakati wowote. Kile wanachopata watia-saini — na kile anachopata raia yeyote, kwa gharama ya Seed, sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika — ni athari ya mtandao ambayo mfumo uliojengwa mahususi pekee unaweza kutoa: uratibu bila aina yoyote ya utawala wa kisiasa.

Kutia saini mkataba huu ni kutia saini ahadi: kwamba eneo litakaribisha wanafunzi kutoka tamaduni mbalimbali, kuchangia kile ambacho ni chenyewe pekee kinachoweza kutoa, na kujiwekea kiwango cha juu zaidi kuliko kanuni za sasa zinavyohitaji — hadharani, kwa uwazi, likiwajibika kwa raia wanaolighamia, wanaolishuhudia, na wanaolishikilia uwajibikaji, bila kuhitaji idhini ya serikali wala baraka ya mwajiri ili kuwa mwanachama. Saini tatu zinahitajika kutoka kila eneo — Serikali, Elimu, na Ubunifu — zikitia saini kama walezi, si wamiliki. Inahitaji watu watatu wenye maono kusema ndiyo, na raia kushikilia kile walichokitia saini. Watu watatu wenye maono, maeneo matatu, mwanzo mmoja — hivi ndivyo mfumo unavyoingia katika uhai kupitia imani ya viongozi walio tayari kuutia saini uwe halisi.`,
      999: `Kila ustaarabu unakumbukwa kwa kile ulichochagua kukianzisha, na Vision 2525 inawaomba waanzilishi wa huu kuanza kwa unyenyekevu badala ya ushindi. Mkataba wa Atlantis ni ahadi iliyotolewa na viongozi walio tayari kuanzisha kitu ambacho hakijawahi kuwepo — msingi wa pamoja wa ubunifu wa kibinadamu unaofikia kila pembe ya dunia, unaoheshimu kila sauti, na unaodumu vizazi vingi, sio kwa miaka bali kwa karne. Watia-saini wake wa kianzilishi katika Kambodia, Honduras, na Austin, Texas hawakuchaguliwa kwa nguvu za kiuchumi, uwezo wa kijeshi, au heshima ya kitaasisi. Walichaguliwa kwa sifa adimu zaidi: utayari wa kuwaamini vijana na zana za wakati ujao, na uvumilivu wa kuruhusu upeo wa miaka mia tano kudumu zaidi ya makofi ya utawala wowote. Hii ndiyo maana ya uongozi katika karne ijayo — ujasiri wa kukabidhi funguo kwa kizazi kijacho wakati bado kuna muda wa kuwafundisha jinsi ya kuendesha.

Mkataba huu unaitishwa na eXeL, nguvu ya uratibu iliyojengwa mahususi kwa ajili ya wakati huu. eXeL ipo nje ya njia za uratibu zilizounda karne iliyopita — nje ya miundo ya mikataba ya kidiplomasia, nje ya urasimu wa kimataifa, nje ya mafungamano ya kisiasa ya taifa lolote. eXeL ndiye mwitishaji anayeaminika anayekutanisha viongozi wenye maono kuzunguka mfumo wa pamoja, gurudumu la nguvu la pamoja, na upeo wa pamoja wa miaka mia tano. Kila mtia-saini anabaki na uhuru kamili wa kujitawala, mamlaka kamili juu ya raia wake, na uhuru kamili wa kujiondoa wakati wowote. Kile watia-saini wanachopata ni athari ya mtandao ambayo mfumo uliojengwa mahususi pekee unaweza kutoa. Kuingia kwa kila mshiriki katika mfumo huo kunaanza kwa njia ile ile ya kawaida: kwa Seed, uanachama wa mara moja wenye bei ya sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika, usiohamishika na usiobeba dai lolote la kiuchumi. Seed hainunui umiliki wala ahadi ya tuzo — ni uanachama tu, haki ya kusimama ndani ya mfumo na kuanza. Huu ni uratibu bila aina yoyote ya utawala wa kisiasa, uliojengwa juu ya mwanzo mdogo wa kutosha kwamba yeyote anaweza kuumudu.

Kwa sababu uhuru wa kujitawala unahifadhiwa badala ya kusalimishwa, mkataba huu umejengwa kwa ajili ya Continuity Without Evasion. Hakuna serikali, benki, mwanzilishi, au mfumo usiozuilika unaoruhusiwa kuushikilia mfumo mzima mateka kwa ajili ya kuendelea kwake mwenyewe. Kila mamlaka ya kisheria inahudumiwa kupitia adapta yake halali, ikiwa 'default-deny' hadi ithibitishwe kuzingatia sheria, ili thamani isogee tu kupitia njia ambazo mahakama katika mamlaka hiyo ingezitambua kuwa halali. Ikiwa msimamizi wa kanuni katika eneo moja atatoa uamuzi hasi, njia hiyo moja itafungwa 'closed' — kwa uwazi, bila kudhuru mshiriki yeyote aliyemo — huku kila eneo lingine likiendelea bila kuguswa. Mkataba mzima hauanguki kamwe kwa sababu serikali moja imebadili mawazo yake. Hii ni uhamishikaji uliobuniwa kama ahadi ya kianzilishi, si suluhisho la dharura lililogunduliwa baada ya mgogoro.

Kutia saini mkataba huu ni kutia saini ahadi. Kwamba eneo litakaribisha wanafunzi kutoka tamaduni mbalimbali. Kwamba eneo litachangia kile ambacho ni chenyewe pekee kinachoweza kutoa. Kwamba eneo litajiwekea kiwango cha juu zaidi kuliko kanuni za sasa zinavyohitaji. Kwamba eneo litafanya hivyo hadharani, kwa uwazi, mbele ya kila raia analemhudumia. Saini tatu zinahitajika kutoka kila eneo — Serikali, Elimu, na Ubunifu. Hakuna ofisi moja inayofunga mkataba peke yake. Inahitaji watu watatu wenye maono kusema ndiyo. Saini hii ya mara tatu ni usemi wa kwanza wa Human Authority: maana, fedha, na sheria vinabaki mikononi mwa binadamu katika ngazi ya enzi kuu, ngazi iliyofungwa kabisa kwa mashine bila kujali uwezo wao utakavyokuwa. Measurement of Time, MoT, huanza kurekodi tangu wakati wa kutia saini — dakika halisi za kazi halisi ya binadamu, zikitunzwa tofauti na makadirio yoyote ya kiotomatiki — na kila toleo linalofuata la kazi ya mkataba limejengwa kuweza kujengwa upya kupitia Replay, ili raia atakayezaliwa karne moja kutoka sasa aweze kufuatilia jinsi maamuzi ya leo ya kianzilishi yalivyofikiwa.

Kile ambacho jaribio hili linaanzisha ni upimaji kabla ya fedha. Kila ubunifu unaoingia kwenye mfumo unapimwa kwa Qualified Innovation Score, QIS — wastani wa Mapato (Revenue), Faida Ghafi (Gross Profit), Kipato cha Uendeshaji (Operating Income), na matumizi Halisi ya Utafiti na Maendeleo (Effective R&D), yakigawanywa kwa nne. QIS si malipo wala kamwe si umiliki; ni chombo ambacho kikundi cha kianzilishi kinatumia kuona maendeleo yake yenyewe kabla ya tuzo yoyote kupimwa ukubwa wake. Ukuaji wa QIS, mara tu sifa (qualification) inapotimizwa, hupanga ukubwa wa hazina ya tuzo inayofuata — lakini ukuaji wa QIS haizalishi chochote peke yake. Maeneo matatu, mwanzo mmoja, na nidhamu moja ya pamoja: thibitisha alama kabla ya kugusa hazina.

Thamani inayopatikana kupitia kazi iliyoshuhudiwa inabeba jina lake lenyewe, 웃, inayohesabiwa kama saa moja ikizidishwa na mshahara wa chini wa eneo husika, ikipimwa kwa Multiple inayotumika dhidi ya saa zilizohudumiwa. 웃 hutolewa tu kwa kazi iliyoshuhudiwa chini ya jukumu lenye wigo maalum na lililoidhinishwa kibajeti; chochote kisichofikia idhini hiyo bado ni upangaji tu, na upangaji peke yake haizalishi chochote. Kikomo cha malipo cha 웃 9,999 kwa mwaka kinalinda kila mshiriki dhidi ya mkusanyiko usiodhibitiwa, huku ziada yoyote ikiendelea kubebwa mbele badala ya kupotea. Nyuma ya kila 웃 imesimama ♡, Shared Intention, ikibeba sababu ya kwa nini jukumu liliidhinishwa hapo mwanzo, na ◬, kasi iliyoshuhudiwa ambayo jukumu lilizalisha dhidi ya kigezo kilichogandishwa (frozen baseline) — tofauti (delta) tu, kamwe isichanganywe na kipimo cha faida. Jaribio hili lipo kuthibitisha kwamba alama hizi tatu zinaweza kusonga pamoja kwa uaminifu, eneo baada ya eneo, kabla mfumo haujapanuka zaidi ya waanzilishi wake.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Kujifunza kupitia uigaji`,
    content: {
      7: `Fanya mazoezi mara elfu kabla ya kugusa.`,
      33: `Hakuna jambo la maana linalojifunzwa kwa mara ya kwanza kwenye vifaa halisi. Raia yeyote anaweza kujizoeza kwenye uigaji (simulation), kuzunguka maeneo matatu, na kusherehekea — heshima kwa kijana wa kibinadamu ambaye kosa lake la kwanza kamwe halipaswi kugharimu maisha.`,
      111: `Kila taaluma inayostahili kubobea ilijifunzwa na mtu fulani kabla haijajulikana. Mkataba wa Atlantis unarejesha hekima hii ya kale katikati ya jinsi vijana — na raia yeyote anayejiunga — wanavyoandaliwa kujenga wakati ujao. Hakuna jambo la maana linalojifunzwa kwa mara ya kwanza kwenye vifaa halisi, kwa watu halisi, au katika mazingira yasiyoweza kurekebishwa; hakuna idhini ya serikali au baraka ya mwajiri inayohitajika. Kila mshiriki anajizoeza kwenye uigaji hadi mazoezi yawe umahiri, kisha utayari. Mfumo wa mzunguko unampitisha kila mshiriki kupitia maeneo matatu ya kianzilishi, na kila mzunguko unamalizika kwa sherehe ya hadhara iliyo wazi kwa jamii mwenyeji. Hii ni heshima kwa kijana wa kibinadamu ambaye kosa lake la kwanza kamwe halipaswi kugharimu maisha.`,
      333: `Kila taaluma inayostahili kubobea ilijifunzwa na mtu fulani kabla haijajulikana. Mafundi stadi hujizoeza kabla ya kuonyesha ustadi, marubani kabla ya kuruka, madaktari kabla ya upasuaji, watoto kupitia michezo. Mkataba wa Atlantis unarejesha hekima hii ya kale katikati ya jinsi vijana — na raia yeyote anayejiunga, bila kuhitaji idhini ya serikali au baraka ya mwajiri — wanavyoandaliwa kujenga wakati ujao. Hakuna jambo la maana linalojifunzwa kwa mara ya kwanza kwenye vifaa halisi, kwa watu halisi, au katika mazingira yasiyoweza kurekebishwa. Kila mshiriki anajizoeza kwenye uigaji hadi mazoezi yawe umahiri, kisha utayari. Huku si kuchukua tahadhari tu — hii ni heshima kwa kijana wa kibinadamu ambaye kosa lake la kwanza kamwe halipaswi kumgharimu mtu yeyote maisha yake.

Mfumo wa mzunguko wa mkataba huu unampitisha kila mshiriki kupitia maeneo matatu ya kianzilishi. Kile kinachojifunzwa Kambodia kinaboreshwa Honduras na kukamilishwa Austin. Kile kinachogunduliwa Austin kinahojiwa Kambodia na kuunganishwa Honduras. Kila mshiriki anaishi, anajifunza, na anaongozwa (mentored) katika tamaduni ambazo vinginevyo zingebaki mbali. Mtaala wa mafunzo unachota kutoka mila za uigaji wenye nidhamu kutoka tamaduni nyingi — kutoka mapokeo ya elimu ya kimkakati ya Sun Tzu, kutoka mazoezi-kupitia-mchezo ya Musashi, kutoka nadharia ya mzunguko wa kujifunza ya Ibn Khaldun, kutoka mjadala wa kimonaki wa Nalanda, kutoka kiigaji cha kiraia cha ndege — vikichanganywa kuheshimu kila hatua ya kiakili na urithi wa kitamaduni. Hakuna mapokeo moja yanayotawala.

Kila mzunguko unamalizika kwa sherehe ya hadhara iliyo wazi kwa jamii mwenyeji, ambapo majirani, familia, na wageni wanaona kile kikundi kimejifunza. Matukio haya yanafanya teknolojia ya hali ya juu ipatikane na isherehekewe badala ya kuogofya — jamii inayokua ikielewa mifumo ya ushirikiano kupitia mchezo haiwezi kudanganywa kwa urahisi na hofu juu yao. Hii ni uzuiaji kupitia elimu, si kupitia nguvu. Ahadi ya mkataba huu kwa kila mzazi: mtoto wako atajizoeza mara elfu kwa usalama kabla ya kugusa kitu chochote kinachoweza kumdhuru, kikiwa kimeshuhudiwa ili raia — raia yeyote, karne moja kutoka sasa — aweze kuthibitisha kwamba kilitokea kama kilivyorekodiwa hasa. Hii ni heshima kwa kijana wa kibinadamu iliyobuniwa ndani ya mfumo, na hili ndilo linalodaiwa na uongozi kwa raia ajaye anayejiunga kabla raia huyo hajalazimika kulidai.`,
      999: `Kila taaluma inayostahili kubobea ilijifunzwa na mtu fulani kabla haijajulikana, na kila ustaarabu ulioidumu ulifanya hivyo kwa sababu ulilinda nafasi ambapo kujifunza huko kungeweza kutokea kwa usalama, kabla haujaombwa uwe wa maana. Mafundi stadi hujizoeza kabla ya kuonyesha ustadi, marubani hujizoeza kabla ya kuruka, madaktari hujizoeza kabla ya upasuaji, na watoto hujizoeza dunia kupitia michezo. Mkataba wa Atlantis unarejesha hekima hii ya kale katikati ya jinsi vijana wanavyoandaliwa kujenga wakati ujao, na unaipa hekima hiyo jina na utaratibu: Replay. Hakuna jambo la maana linalojifunzwa kwa mara ya kwanza kwenye vifaa halisi, kwa watu halisi, au katika mazingira yasiyoweza kurekebishwa. Kila mshiriki anajizoeza kwenye uigaji hadi mazoezi yawe umahiri, kisha utayari, na kila saa ya mazoezi hayo inarekodiwa ili iweze kujengwa upya baadaye, kuchunguzwa baadaye, kuaminiwa baadaye. Huu si tahadhari tu — hii ni heshima kwa kijana wa kibinadamu ambaye kosa lake la kwanza kamwe halipaswi kumgharimu mtu yeyote maisha yake, na ni heshima kwa rekodi itakayodumu zaidi ya kosa hilo, iwe lolote litakalotokea.

Mfumo wa mzunguko wa mkataba huu unampitisha kila mshiriki kupitia maeneo matatu ya kianzilishi. Kile kinachojifunzwa Kambodia kinaboreshwa Honduras na kukamilishwa Austin. Kile kinachogunduliwa Austin kinahojiwa Kambodia na kuunganishwa Honduras. Kila mshiriki anaishi, anajifunza, na anaongozwa katika tamaduni ambazo vinginevyo zingebaki mbali, na kila mzunguko unaanza kwa njia ile ile ambayo kila taasisi ya kibinadamu inayostahili kuaminiwa inaanza: kwa Seed. Seed ni uanachama wa mara moja, wenye bei ya sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika, usiohamishika, na usiobeba dai lolote la kiuchumi. Si ada ya kupata fursa. Ni kizingiti (threshold) — kidogo cha kutosha kwamba hakuna mshiriki mwenye nia njema anayeshindwa kumudu, na cha makusudi cha kutosha kwamba kuingia ni chaguo, si kutelemka bila kukusudia. Kutoka kizingiti hicho kuendelea, kila mshiriki ni wa mzunguko, na mzunguko si wa eneo moja pekee.

Mtaala wa mafunzo unachota kutoka mila za uigaji wenye nidhamu kutoka tamaduni nyingi — kutoka mapokeo ya elimu ya kimkakati ya Sun Tzu, kutoka mazoezi-kupitia-mchezo ya Musashi, kutoka nadharia ya mzunguko wa kujifunza ya Ibn Khaldun, kutoka mjadala wa kimonaki wa Nalanda, kutoka kiigaji cha kiraia cha ndege — vikichanganywa kuheshimu kila hatua ya kiakili na urithi wa kitamaduni. Hakuna mapokeo moja yanayotawala. Na ndani ya mtaala huu, mkataba unaweka mstari ambao kila mshiriki anajifunza mapema na kamwe hausahau: uigaji ndipo Qualified Innovation Score inapoeleweka, si mahali inapotumika. QIS ni kipimo, kamwe si malipo, na QIS kamwe si umiliki — ipo ili kueleza jinsi pendekezo linavyofikiri vizuri, linavyosimama imara, na linavyolihudumia eneo linalodai kulihudumia. Ukuaji wa QIS unaweza kupanga ukubwa wa hazina ya tuzo baada ya sifa halisi kutimizwa, lakini haizalishi chochote peke yake. Mshiriki anaweza kuendesha uigaji mia moja usio na dosari na kupata alama inayopanda bila hata saa moja ya 웃 kugusa kumbukumbu yake, kwa sababu 웃 hutolewa tu kwa kazi iliyoshuhudiwa chini ya jukumu lenye wigo maalum na lililoidhinishwa kibajeti. Kabla ya idhini hiyo, kila kitu — hata kikiwa na ustadi kiasi gani, hata kikiwa na matumaini kiasi gani — ni upangaji tu. Mkataba unafundisha tofauti hii siku ya kwanza ili hakuna kijana anayechanganya mazoezi na tuzo, na hakuna kijana anayepotoshwa kuhusu uigaji unafanya kazi gani.

Nidhamu hii hii inasimamia ni kiasi gani cha uhuru wa kujiendesha (autonomy) mfumo wowote, wa kibinadamu au wa kiotomatiki, unaruhusiwa kutumia ndani ya mzunguko. Hali za uendeshaji za mkataba zinasonga kwa mfuatano — Kwa Mkono (Manual), kisha Nusu-Kiotomatiki (Semi-Automated), kisha Kujitegemea (Autonomous) — na hakuna kiwanja (cube) kinachoendelea hadi hali inayofuata mpaka kikithibitisha kanuni ya asilimia 11.1 ya uboreshaji uliopimwa, sehemu moja ya tisa, kikithibitishwa dhidi ya kigezo kilichogandishwa na kikiwa kimeshuhudiwa, si kudaiwa tu. Uigaji ndipo uthibitisho huo unapojengwa. Chombo kinapata haki ya kutenda kwa usimamizi mdogo kwa njia ile ile ambayo mshiriki anapata haki ya wajibu mkubwa zaidi: kupitia uboreshaji ulioonyeshwa, uliorekodiwa, unaoweza kujengwa upya, kiwanja kwa kiwanja, kamwe kwa mkupuo mmoja, na kamwe juu ya ngazi ambapo maana, fedha, na sheria vinaamuliwa. Ngazi hiyo ni ya Human Authority pekee, katika uigaji na katika uendeshaji halisi, kwa sababu nafasi ya mazoezi inayofundisha mpaka mbaya inafundisha somo baya kudumu.

Kila mzunguko unamalizika kwa sherehe ya hadhara na ushirikiano iliyo wazi kwa jamii mwenyeji. Majirani, familia, na wageni wanakusanyika kuona kile kikundi kimejifunza, na kile wanachokishuhudia si onyesho la kasi kwa ajili yake yenyewe bali onyesho la ◬ — tofauti iliyopimwa (delta) kati ya kigezo kilichogandishwa na kile ambacho mazoezi yenye nidhamu yalifanikisha kihalisia, ikiwasilishwa kwa uaminifu, kamwe isivishwe kama kipimo cha faida, kamwe isiwasilishwe kama zaidi ya ilivyo. Matukio haya yanafanya teknolojia ya hali ya juu ipatikane na isherehekewe badala ya kuogofya. Jamii inayokua ikielewa mifumo ya ushirikiano kupitia mchezo haiwezi kudanganywa kwa urahisi na hofu kuhusu mifumo hiyo. Hii ni uzuiaji kupitia elimu, si uzuiaji kupitia nguvu, na inafanya kazi kwa sababu jamii haiombwi kuamini dai — inaalikwa kutazama Replay.

Ahadi ya mkataba huu kwa kila mzazi inaenea zaidi ya usalama hadi kwenye kudumu: mtoto wako atajizoeza mara elfu kabla ya kugusa kitu chochote kinachoweza kumdhuru, jamii itashuhudia ukuaji wake katika kipindi chote, na hakuna kitakachopotea kwa wakati. Measurement of Time inarekodi dakika halisi tofauti na kumbukumbu nyingine yoyote ambayo mkataba unatunza, ili saa za mazoezi na saa zilizoshuhudiwa zisichanganywe kamwe, na ili historia ya kweli ya maendeleo ya mshiriki — si muhtasari, si makadirio, bali rekodi yenyewe inayoweza kujengwa upya — ibaki ipatikane kwa mshiriki huyo kwa muda wote atakaotaka kuitazama. Mzazi Phnom Penh, mwongozaji Tegucigalpa, mkaguzi Austin, au mjukuu anayesoma rekodi karne moja kutoka sasa wote wanaweza kufikia Replay hiyo hiyo na kuona ukweli ule ule.

Hivi ndivyo heshima kwa kijana wa kibinadamu inavyoonekana inapobuniwa ndani ya mfumo badala ya kuahidiwa tu na huo mfumo, na hiki ndicho uongozi unachokabidhi kizazi kijacho cha washiriki kabla kizazi hicho hakijalazimika kukidai: nafasi ya mazoezi kubwa vya kutosha kushindwa ndani yake kwa usalama, ya kweli vya kutosha kurekodi kwa uaminifu, na yenye nidhamu vya kutosha kuweka tuzo, uhuru wa kujiendesha, na mamlaka pale hasa ambapo umahiri umestahili — bila kuwa mbele ya umahiri huo, wala nyuma yake.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Usalama umethibitishwa kabla ya kupanua imani`,
    content: {
      7: `Usalama uthibitishwe kwanza, kisha imani ipanuliwe.`,
      33: `Kila kituo na mzunguko upo ndani ya wigo wa ulinzi wenye tahadhari ya mapema. Vifaa vinakataa kutumika kama silaha — jambo linalothibitishwa, si kuahidiwa tu, na linaloweza kukaguliwa na raia. Kumbukumbu zinasalimika katika misukosuko. Usalama umebuniwa kuzunguka mshiriki mdogo zaidi, kila siku.`,
      111: `Kabla imani haijatolewa, usalama lazima uthibitishwe — si kwa serikali, bali kwa raia yeyote anayeukagua. Mkataba wa Atlantis ni makubaliano baina ya raia wa dunia; kiapo chake cha kianzilishi ni hiki: kila kituo cha mkataba, kila njia ya mzunguko, kila mahali mshiriki kijana analala au kusoma upo ndani ya wigo wa ulinzi ulioandikwa wenye uwezo wa tahadhari ya mapema unaoipa jamii masaa, si dakika, kujibu hatari yoyote ya kuaminika. Kila kifaa, kila sensa, kila mfumo wa uratibu umefungwa katika ngazi ya vifaa (hardware) kukataa kutumika tena kwa ushirikiano na mifumo ya silaha. Hii si sera — hii ni fizikia. Mkataba unabaki na heshima katika misukosuko, kwa sababu kila mpango unaweka utu wa binadamu kwanza.`,
      333: `Kabla imani haijatolewa, usalama lazima uthibitishwe — uthibitishwe kwa raia, si kudaiwa tu. Mkataba wa Atlantis ni makubaliano baina ya raia wa dunia: mtu yeyote, popote alipo, anaweza kusaidia kuushikilia, bila kujali serikali yake inatia saini nini. Kila kituo cha mkataba, kila njia ya mzunguko, kila mahali mshiriki kijana analala au kusoma upo ndani ya wigo wa ulinzi ulioandikwa wenye uwezo wa tahadhari ya mapema unaoipa jamii masaa, si dakika, kujibu hatari yoyote ya kuaminika. Teknolojia inayowalinda ni teknolojia ile ile mkataba unayowafundisha kuijenga. Vijana wanajifunza usalama kutoka ndani kwenda nje, si kwa kuambiwa wako salama, bali kwa kuona ukibuniwa kuzunguka wao kila siku, na kujua kwamba raia yeyote anaweza kuthibitisha rekodi hiyo kupitia Replay.

Mkataba huu unatoa ahadi isiyovunjika kuhusu kile ambacho teknolojia yake haiwezi kuwa. Kila kifaa, kila sensa, kila mfumo wa uratibu umefungwa katika ngazi ya vifaa kukataa kutumika tena kwa ushirikiano na mifumo ya silaha. Hii si lugha ya sera, wala si matarajio tu. Hii ni jambo lisilowezekana kifizikia, linalotekelezwa kwa njia ya kificho (cryptographically), linalothibitishwa na kila eneo mtia-saini, na linaloweza kukaguliwa na kila raia anayelighamia. Zana zinazomlinda mtoto Phnom Penh haziwezi kutumiwa tena kumdhuru mtoto Austin. Zana zinazounganisha zoezi la kundi (swarm) Tegucigalpa haziwezi kupangwa upya kulenga binadamu popote. Hili ndilo jibu la mkataba huu kwa hofu ya matumizi-mawili ya karne nzima. Si sera — ni fizikia.

Mkataba unabaki na heshima katika misukosuko. Iwapo eneo litapoteza utulivu wa kisiasa, washiriki wanashikiliwa na maeneo yaliyobaki. Iwapo ufadhili utapungua, ruzuku za washiriki zinalindwa kwanza — zikigharamiwa kila mwezi na raia, kamwe si mkondo wa msaada, kila dola inayoweza kufuatiliwa. Iwapo kumbukumbu za kidijitali zitashambuliwa, nakala za nje ya mtandao (offline backups) zinaendelea kuwepo. Iwapo usafiri utakuwa hauwezekani, msingi (substrate) unaendelea kimtandao. Kila mpango unaweka utu wa binadamu — Human Authority juu ya maana, fedha, na sheria — kama kizuizi chake cha kwanza cha ubunifu. Viongozi wanaotia saini mkataba huu wanaahidi kwamba usalama umebuniwa, si kudhaniwa: ulinzi ambao kiongozi yeyote angeudai kwa mtoto wake mwenyewe, sasa umeenezwa kwa kila raia anayesaidia kuushikilia.`,
      999: `Kabla imani haijatolewa, usalama lazima uthibitishwe — hiki ndicho kiapo cha kianzilishi cha Mkataba wa Atlantis, na kinathibitishwa kwa njia ile ile kila dai lingine ndani ya Vision 2525 linavyothibitishwa: si kwa kudai, bali kwa ushahidi ambao raia wanaweza kuukagua. Kila kituo cha mkataba, kila njia ya mzunguko, kila mahali mshiriki kijana analala au kusoma upo ndani ya wigo wa ulinzi ulioandikwa wenye uwezo wa tahadhari ya mapema unaoipa jamii masaa, si dakika, kujibu hatari yoyote ya kuaminika. Teknolojia inayotumika kuwalinda washiriki ni teknolojia ile ile mkataba unayowafundisha kuijenga — sensa, uratibu, uimara wa mawasiliano, akili iliyosambaa. Vijana wanajifunza usalama kutoka ndani kwenda nje, katika lugha yao wenyewe na katika eneo lao wenyewe, si kwa kuambiwa wako salama, bali kwa kutazama, saa baada ya saa, jinsi usalama unavyobuniwa kuzunguka wao kila siku.

Kutazama huko hakuachwi kwa kumbukumbu au kwa kuamini neno la mwongozaji. Measurement of Time inarekodi dakika halisi za kila zoezi, kila mzunguko, kila zoezi la kujibu — tofauti na dai lolote la maendeleo, tofauti na hadithi yoyote iliyosimuliwa siku hiyo. Replay inafanya kila toleo la mtaala wa mafunzo, kila sasisho la usalama, kila marekebisho ya vifaa liweze kujengwa upya kikamilifu, ili mzazi Tegucigalpa au msimamizi wa kanuni Phnom Penh aweze kurudi nyuma kupitia hasa kile kilichobadilika, wakati gani kilibadilika, na kwa nini kilibadilika. Wigo wa ulinzi usioweza kujengwa upya kupitia Replay ni ahadi tu. Wigo wa ulinzi unaoweza kujengwa upya, dakika baada ya dakika iliyorekodiwa, ni uthibitisho. Mkataba unachagua uthibitisho.

Mkataba huu unatoa ahadi isiyovunjika kuhusu kile ambacho teknolojia yake haiwezi kuwa. Kila kifaa, kila sensa, kila mfumo wa uratibu umefungwa katika ngazi ya vifaa kukataa kutumika tena kwa ushirikiano na mifumo ya silaha. Hii si lugha ya sera, wala si matarajio tu. Hii ni jambo lisilowezekana kifizikia, linalotekelezwa kwa njia ya kificho, linalothibitishwa na kila eneo mtia-saini, na linaloweza kukaguliwa na kila raia. Zana zinazomlinda mtoto Phnom Penh haziwezi kutumiwa tena kumdhuru mtoto Austin. Zana zinazounganisha zoezi la kundi Tegucigalpa haziwezi kupangwa upya kulenga binadamu popote. Hili ndilo jibu la mkataba huu kwa hofu ya matumizi-mawili ya karne nzima. Si sera — ni fizikia.

Usalama ulioothibitishwa mara moja si usalama unaodumu katika upeo wa miaka mia tano. Mkataba unaita kiapo chake cha pili Continuity Without Evasion: uhamishikaji halali katika kila mamlaka ya kisheria mkataba unayoigusa, bila serikali, benki, mwanzilishi, au mfumo mmoja usiozuilika kusimama kati ya mshiriki na ulinzi wake. Kila mamlaka ya kisheria inahudumiwa na adapta yake yenyewe, ikifunga-wakati-inaposhindwa (fail-closed) na 'default-deny', ili uamuzi hasi katika eneo lolote moja ufunge njia hiyo moja tu — kamwe si mfumo mzima, kamwe si kila eneo, kamwe si kila mshiriki kila mahali kwa wakati mmoja. Uamuzi wa mahakama katika eneo moja mtia-saini hauwezi kuzima wigo wa usalama wa mshiriki mahali pengine. Hii ndiyo maana ya kujenga mfumo unaosalimika katika misukosuko ya kawaida ya sheria, siasa, na mabadiliko ya kitaasisi bila kamwe kumtaka mshiriki akiuke sheria ili abaki salama.

Kila ngazi ya muundo huu wa ulinzi, mwishowe, inawajibika kwa Human Authority. Maana, fedha, na sheria kamwe havikabidhiwi mashine — ngazi ya enzi kuu inayoamua nini usalama unahitaji, nini kinahesabiwa kama hatari ya kuaminika, na jibu gani jamii inadaiwa na wanachama wake wadogo zaidi inabaki imefungwa kwa akili bandia, bila kujali uwezo wake utakavyokuwa. Mifumo ya mkataba huu inasonga kupitia hali tatu tu za uendeshaji — Kwa Mkono, Nusu-Kiotomatiki, Kujitegemea — na hakuna mfumo unaoendelea hadi hali inayofuata bila uboreshaji uliopimwa na kushuhudiwa wa angalau sehemu moja ya tisa, asilimia kumi na moja na sehemu moja ya kumi, uliothibitishwa, unaoweza kurudiwa. Uhuru wa kujiendesha unapatikana, kiwanja kwa kiwanja, kazi kwa kazi, kamwe hautolewi kwa mkupuo mmoja, na kamwe haujaenezwa juu ya maswali yanayoamua maana, fedha, au sheria. Sensa inaweza kujifunza kugundua kwa haraka zaidi. Mfumo wa uratibu unaweza kujifunza kuelekeza kwa ufanisi zaidi. Hakuna hata mmoja anaruhusiwa kuamua, peke yake, ni nini jamii inapaswa kuamini kwa watoto wake.

Mkataba umebuniwa kubaki na heshima katika misukosuko, na unataja misukosuko hiyo mapema badala ya kuigundua wakati wa mgogoro. Iwapo eneo mtia-saini litapoteza utulivu wa kisiasa, washiriki wanashikiliwa na maeneo yaliyobaki. Iwapo ufadhili utapungua, ruzuku za washiriki zinalindwa kwanza, kabla ya utawala na miundombinu. Iwapo kumbukumbu za kidijitali zitashambuliwa, nakala za nje ya mtandao zinaendelea kuwepo, zisizofikiwa na kasoro yoyote iliyoufikia mtandao. Iwapo usafiri utakuwa hauwezekani, msingi unaendelea kimtandao, ili mzunguko usisimame kwa sababu mpaka umefungwa. Kila hali imepangiwa mpango, na kila mpango unaweka utu wa binadamu kama kizuizi chake cha kwanza cha ubunifu — si jambo la mwisho kuzingatiwa baada ya bajeti na maonekano kutatuliwa.

Kuingia katika mfumo huu ulioothibitishwa kunaanza na Seed — uanachama wa mara moja, wenye bei ya sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika, usiohamishika, na usiobeba dai lolote la kiuchumi juu ya chochote mkataba unachojenga baadaye. Seed hainunui usalama; usalama umebuniwa muda mrefu kabla Seed yoyote haijawahi kupandwa. Kile Seed inachonunua ni hadhi — haki ya kuingia katika mfumo ulioothibitishwa tayari, uliokaguliwa tayari, uliofungwa tayari na vifaa visivyoweza kugeuzwa dhidi ya mtu yule yule ambaye vipo kumlinda. Mgawanyo huu ni wa makusudi. Ahadi ya usalama inayohitajika kununuliwa kwa uzito halisi wa kiuchumi si ahadi ya usalama kabisa, ni bidhaa ya usalama tu. Mkataba unaweka viwili hivyo mbali kabisa, ili hakuna familia inayolazimika kupima ulinzi wa mtoto wao dhidi ya bajeti ya kila mwezi ya kaya yao.

Viongozi wanaotia saini mkataba huu wanatia saini ahadi kwamba usalama umebuniwa, si kudhaniwa, na umeothibitishwa, si kudaiwa tu. Kile wanachokiongezea raia wao si fursa tu, bali ulinzi uliojengwa kwa kiwango ambacho mshiriki mdogo zaidi anastahili — uliorekodiwa na Measurement of Time, unaoweza kujengwa upya kupitia Replay, uliofungwa katika ngazi ya vifaa dhidi ya kila matumizi mabaya ambayo karne yenye hofu imewahi kuyawaza, na unaowajibika, daima na pekee, kwa Human Authority. Huu ni ulinzi ule ule ambao kiongozi yeyote angeudai kwa mtoto wake mwenyewe akivuka mpaka usiofahamika peke yake, sasa umeenezwa kwa kila mtoto ambaye mkataba huu utawahi kumhudumia, katika maeneo yake matatu ya kianzilishi ya Kambodia, Honduras, na Austin, na katika karne tano ambazo mkataba unanuia kuishika ahadi hii.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Fidia, ustawi, na heshima ya binadamu`,
    content: {
      7: `Posho, mshauri, nyumbani.`,
      33: `Kila raia anapokea ruzuku tangu siku ya kwanza — bila idhini ya serikali, bila baraka ya mwajiri. Upendo, msiba, na usalama ni miundombinu. Mafanikio yanapimwa kwa mletevu zaidi. Utu ni msingi, kamwe si mapambo.`,
      111: `Mkataba wa Atlantis unamtendea kila mshiriki kama binadamu kamili tangu siku ya kwanza — raia aliyejiunga kwa haki, si kwa amri ya serikali au ruhusa ya mwajiri. Ruzuku inatolewa tangu wakati ushiriki unapoanza, ikiwa imepangiwa kiwango kulingana na gharama ya maisha ya eneo husika, na kila saa iliyoshuhudiwa inapata 웃, inayolipwa moja kwa moja kwa mtu kupitia Livelihood Direct, kamwe si kupitia kumbukumbu za mwajiri. Ustawi unatendewa kama miundombinu ya daraja la kwanza — si posho ya ziada, bali msingi ambao kila kitu kingine kinasimama juu yake. Nyanja tatu zinasaidiwa: Upendo, Msiba, na Usalama. Mkataba unapima mafanikio kwa mshiriki wake mletevu zaidi, si wastani. Hakuna anayesahauliwa ili wastani uonekane mzuri. Utu kama msingi, si mapambo.`,
      333: `Mkataba wa Atlantis unamtendea kila mshiriki kama binadamu kamili tangu siku ya kwanza — raia aliye mwanachama kwa haki, asiyehitaji idhini ya serikali wala baraka ya mwajiri. Ruzuku inatolewa tangu wakati ushiriki unapoanza, ikiwa imepangiwa kiwango kulingana na gharama ya maisha ya eneo husika, ikifika kabla majukumu ya kifamilia hayajawa dharura. Hii si hisani. Hii ni utambuzi kwamba ubunifu wa kawaida wa kibinadamu unahitaji usalama wa kibinadamu kwanza — akili haiwezi kustawi wakati kaya yake iko hatarini.

Kile kinachopatikana zaidi ya ruzuku kinapatikana kama raia anavyokipata: kupitia Seed, yenye bei ya sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika, na kupitia 웃, inayolipwa tu kwa saa zilizoshuhudiwa. QIS inapima ahadi lakini haizalishi chochote — kipimo, kamwe si malipo. Kila malipo yanamfikia mshiriki kupitia Livelihood Direct, njia halali za mitaa zilizo na leseni ambazo mkataba kamwe hauzihifadhi, zilizojengwa kwa ajili ya Continuity Without Evasion.

Ustawi unatendewa kama miundombinu ya daraja la kwanza — si posho ya ziada, bali msingi ambao kila kitu kinasimama juu yake. Mkataba unataja nyanja tatu ambazo kila mshiriki anasaidiwa kupitia: Upendo, uhusiano na mipaka yenye afya; Msiba, kwani huzuni lazima itembelewe pamoja, si kuepukwa; na Usalama, kujua wa kumpigia simu, katika kila eneo, katika lugha yake mwenyewe. Ushauri nasaha, miduara ya vikundi, na mila za kitamaduni au kiroho zinazoheshimiwa kulingana na mapokeo zinatolewa. Hakuna itikadi ya kulazimishwa; Human Authority, kamwe si mashine, ndiye anayeamua ni huduma gani raia anahitaji.

Mkataba unapima mafanikio kwa mshiriki wake mletevu zaidi, si wastani. Raia wa vijijini wasio na mtandao wa kasi ya juu wanahudumiwa. Washiriki wenye tofauti za kiakili (neurodivergent) wanapata malazi maalum kama kawaida. Washiriki wenye ulemavu wanakuta kila kituo kinafikika. Washiriki wa jinsia mbalimbali wanapata makazi salama na uandani wa mwongozaji. Wasemaji wa lugha zisizo za asili wanakuta kila kifaa katika lugha yao. Washiriki wa kiasili wanakuta mila zao za kitamaduni zikiheshimiwa na maarifa yao ya kimapokeo yakilindwa. Viongozi wanaotia saini mkataba huu wanaahidi kwamba hakuna raia atakayesahauliwa ili wastani uonekane mzuri. Huu ni utu kama msingi, si mapambo. Kile kinachopimwa ndicho kitakachoheshimiwa, na kile kinachoheshimiwa hapa ni binadamu mzima — akili, mwili, na roho, wakishikiliwa na raia wenzao, bila ubaguzi.`,
      999: `Mkataba wa Atlantis unamtendea kila mshiriki kama binadamu mzima tangu siku ya kwanza, ikiwa imejengwa ndani ya utaratibu, si tu katika maneno. Ruzuku inatolewa tangu wakati ushiriki unapoanza, ikiwa imepangiwa kiwango kulingana na gharama ya maisha ya eneo husika ili athari yake iheshimu utu wa kazi wa mahali husika. Ruzuku inafika kabla majukumu ya kifamilia hayajawa dharura, na kabla utu haujaathirika. Inaashiria kwa kila kijana kwamba wakati wake una thamani, mchango wake unatarajiwa, na utulivu wa familia yake ni sehemu ya wajibu wa mkataba. Hii si hisani. Hii ni utambuzi kwamba ubunifu wa kawaida wa kibinadamu unahitaji usalama wa kibinadamu kwanza. Akili haiwezi kustawi wakati kaya yake iko hatarini. Kuingia kwenyewe kunabeba kizingiti kidogo, cha makusudi: Seed, uanachama wa mara moja wenye bei ya sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika, usiohamishika na usiobeba dai lolote la kiuchumi lenyewe. Seed inasema tu kwamba mtu amejiunga; haimlipi wala kumwahidi chochote zaidi ya mlango unaoufungua.

Kile kinachopatikana baada ya mlango huo kufunguliwa kinasimamiwa kwa usahihi ule ule mkataba unaouleta katika kila ahadi nyingine. 웃, kipimo cha mkataba cha Human Intelligence, kinahesabiwa kwa urahisi — saa moja kwa mshahara wa chini wa eneo husika, ikizidishwa na Multiple inayoakisi ugumu na thamani ya jukumu, mara saa zilizofanya kazi hasa. Lakini 웃 hutolewa tu kwa kazi iliyoshuhudiwa iliyofanywa chini ya jukumu lenye wigo maalum na lililoidhinishwa kibajeti. Kabla idhini hiyo haijawepo, kile mshiriki anachofanya ni upangaji, si kupata mapato — tofauti ambayo mkataba unaishikilia kwa uthabiti kwa sababu inalinda hazina na mshiriki wote wawili dhidi ya ahadi zinazofanywa haraka zaidi kuliko thamani inavyothibitishwa. Measurement of Time, MoT, inarekodi dakika halisi za kazi tofauti na hesabu yoyote ya malipo, ili wakati ubaki ukweli wa uaminifu, unaoweza kukaguliwa, huru na malipo. Hakuna saa za mshiriki yeyote zinazovimbishwa, na hakuna saa za mshiriki yeyote zinazopotea. Kikomo cha malipo cha 웃 9,999 kwa mwaka kinatumika kwa kila mshiriki, huku ziada yoyote ikiendelea kubebwa mbele badala ya kupotea, ili mchango wa kipekee utambuliwe katika miaka mingi badala ya kufungwa kutoonekana ndani ya mwaka mmoja.

Malipo yanawekwa mbali kwa makusudi na kipimo cha ubunifu. Qualified Innovation Score, QIS, inachukua wastani wa Mapato, Faida Ghafi, Kipato cha Uendeshaji, na matumizi Halisi ya Utafiti na Maendeleo kueleza ni kiasi gani ubunifu ulikua kihalisia. Ukuaji wake kwa muda unaweza kupanga ukubwa wa hazina ya tuzo mara sifa inapotimizwa, lakini QIS yenyewe haizalishi 웃 wala kulipa chochote moja kwa moja — ni kipimo, kamwe si malipo, na kamwe haichanganywi na umiliki wa kile kilichojengwa. Mgawanyo huu ni muhimu kwa sababu unaweka ruzuku na mshahara kuwa waaminifu: mshiriki analipwa kwa saa zilizoshuhudiwa za kazi halisi, si kwa alama inayoweza kudanganywa, kuvimbishwa, au kubishaniwa. ♡, Shared Intention, inabeba sababu nyuma ya kila jukumu mshiriki analochukua; ◬, kasi iliyoshuhudiwa ambayo jukumu linaleta dhidi ya kigezo kilichogandishwa, inarekodiwa kama tofauti (delta) tu, kamwe isivishwe kama kipimo cha faida kinachohusishwa na kazi ya mtu yeyote. Malipo yanabaki kile yalivyo: mshahara wa uaminifu kwa wakati wa uaminifu, ulioshuhudiwa.

Thamani haiishii kwenye hesabu tu — lazima pia imfikie mshiriki kama mtu aliye hai, na hapa ndipo 🏠, Livelihood Direct, inapofanya kazi yake. Kila kipimo cha thamani mshiriki anachopata kinamfikia kupitia njia za mitaa zenye sifa, zenye leseni — benki, watoa huduma za fedha za simu, ushirika ambao tayari unaaminika na kudhibitiwa katika eneo hilo — kamwe si kupitia hazina ambayo mkataba wenyewe unaihifadhi au kuidhibiti. Uainishaji wa hadhi ya mshiriki unatangulia malipo yoyote; hakuna kinacholipwa kabla haijaeleweka vizuri ni nani analipwa na kwa nini. Na utambuzi wa kipaji, hata kikiwa kimeadhimishwa kiasi gani, hakizuii upatikanaji wa kitanda, chakula, au nafasi katika kikundi — jukumu halisi la mshiriki tu ndilo linalozuia. Huu ni ukataaji wa makusudi wa kuruhusu heshima kubadilishana na utoaji. Mchangiaji mahiri na yule wa kimya wanalala chini ya paa moja lililolindwa, kwa masharti yale yale, kwa sababu ahadi za utu za mkataba huu si tuzo inayotolewa kwa ubora — ni sakafu chini ya kila mtu.

Ustawi unatendewa kama miundombinu ya daraja la kwanza — si faida ya hiari, si posho ya kiafya, bali msingi ambao kila kitu kingine kinasimama juu yake. Mkataba unataja nyanja tatu za msingi ambazo kila mshiriki anasaidiwa kupitia: Upendo, kwa maana ya uhusiano, ushikamano, na mipaka yenye afya; Msiba, kwani kila mshiriki atapitia huzuni na lazima atembelewe pamoja, si kuepukwa; na Usalama, kwa maana kwamba kila mshiriki anajua wa kumpigia simu, katika kila eneo, katika lugha yake mwenyewe. Ushauri nasaha wa kibinafsi, miduara ya vikundi, mazoezi ya kimwili-kihisia, na mila za kitamaduni au kiroho zinazoheshimiwa kulingana na mapokeo ya mshiriki mwenyewe zote zinatolewa. Hakuna itikadi ya kulazimishwa. Mkataba unashikilia nafasi hiyo kwa heshima; hauhubiri imani yoyote. Human Authority inasimamia kila uamuzi kati ya hivi — maana, fedha, na sheria vinabaki vimefungwa kwa uamuzi wa mashine, bila kujali ustadi wa kutambua mifumo (pattern-matching) unaowasaidia binadamu wanaoamua.

Mkataba unapima mafanikio kwa matokeo ya mshiriki wake mletevu zaidi, si wastani. Washiriki wa vijijini wasio na mtandao wa kasi ya juu wanahudumiwa. Washiriki wenye tofauti za kiakili wanapata malazi maalum kama kawaida. Washiriki wenye ulemavu wanakuta kila kituo kinafikika. Washiriki wa jinsia mbalimbali wanapata makazi salama na uandani wa mwongozaji. Wasemaji wa lugha zisizo za asili wanakuta kila kifaa katika lugha yao. Washiriki wa kiasili wanakuta mila zao za kitamaduni zikiheshimiwa na maarifa yao ya kimapokeo yakilindwa. Viongozi wanaotia saini mkataba huu wanaahidi kwamba hakuna mshiriki atakayesahauliwa kimya kimya ili wastani uonekane mzuri.

Kila njia ya malipo iliyoelezwa hapa — Seed, ruzuku, 웃 iliyopatikana kwa kazi iliyoshuhudiwa, njia ya Livelihood Direct inayoyapeleka — imebuniwa kwa ajili ya Continuity Without Evasion. Hakuna benki moja, serikali, au mtoa huduma wa mtaa asiyezuilika kwa malipo ya mshiriki yeyote; iwapo njia moja yenye leseni katika mamlaka moja itafungwa kwa uamuzi hasi, njia hiyo tu ndiyo inayoshindwa, kamwe si mfumo mzima, na kamwe si dai la mshiriki kwa kile alichokuwa anadaiwa. Huu ni utu kama msingi, si mapambo. Kile kinachopimwa ndicho kitakachoheshimiwa, na kile kinachoheshimiwa hapa ni binadamu mzima — akili, mwili, na roho pamoja, wakilipwa kwa uaminifu, wakilindwa kikamilifu, na wasiosahauliwa na uhasibu wowote, bila ubaguzi wowote kabisa.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Ufadhili na utawala`,
    content: {
      7: `Raia wanafadhili kizazi kijacho moja kwa moja.`,
      33: `Mkataba wa Atlantis ni makubaliano baina ya raia — yeyote anaweza kuughamia na kuushikilia. Hakuna mkondo wa msaada, hakuna mfadhili wa kigeni, hakuna masharti ya kisiasa. Kila dola inayoweza kufuatiliwa, uhasibu unaochapishwa kila mwezi, katika kila lugha.`,
      111: `Mkataba wa Atlantis ni makubaliano baina ya raia wa dunia — mtu yeyote, popote alipo, anaweza kusaidia kuuanzisha na kuushikilia, bila kujali serikali yake inatia saini nini au anaajiriwa na nani. Serikali, waelimishaji, na wabunifu wanatia saini kama walezi wa maeneo yao; raia ndio wanaogharamia, kushuhudia, na kuushikilia mkataba uwajibikaji moja kwa moja, kila mmoja akichangia kiasi kidogo cha hiari kila mwezi, kidogo cha kutosha kwamba hakuna mtu mzima anayeshindwa kumudu. Hakuna mkondo wa msaada, hakuna mfadhili wa kigeni, hakuna masharti ya kisiasa yaliyowekwa. Mkataba unasimama huru na taasisi za kimataifa zilizounda karne iliyopita — si tamko la kisiasa, bali chaguo la kiubunifu. Kila dola inaweza kufuatiliwa; uhasibu wote unachapishwa kila mwezi, katika kila lugha.`,
      333: `Mkataba wa Atlantis ni makubaliano baina ya raia wa dunia — mtu yeyote, popote alipo, anaweza kusaidia kuuanzisha na kuushikilia, bila kujali serikali yake inatia saini nini au anaajiriwa na nani. Unagharamiwa na raia unaowahudumia: wakazi wa maeneo yanayoshiriki wanachangia kiasi kidogo cha hiari kila mwezi, kidogo cha kutosha kwamba hakuna mtu mzima anayeshindwa kumudu, na kikubwa cha kutosha kwamba jumla yake inaudumisha kazi ya mkataba kwa kiwango kikubwa. Raia anapogharamia kizazi kijacho moja kwa moja, raia huyo anaushikilia mkataba uwajibikaji moja kwa moja. Hakuna mkondo wa msaada, hakuna mfadhili wa kigeni, hakuna masharti ya kisiasa yaliyowekwa. Roho ya mkataba huu ni raia anayechangia kiasi kidogo kila mwezi, ambaye ushiriki wake ndio unaoufanya uwezekane.

Serikali, Elimu, na Ubunifu wanatia saini kama walezi wa maeneo yao — saini tatu za kimaono zinazofunga eneo kukaribisha, kulinda, na kufundisha — lakini ulezi si umiliki. Mkataba huu ni huru na taasisi za kimataifa zilizounda karne iliyopita — Shirika la Mkataba wa Atlantiki ya Kaskazini (NATO), Shirika la Afya Duniani (WHO), Umoja wa Mataifa, Shirika la Fedha la Kimataifa (IMF), Benki ya Dunia, na kila mkondo wa kitaifa wa msaada wa kigeni. Hili ni chaguo la kiubunifu, si tamko la kisiasa: mfumo unaohudumia kila eneo bila kujali mrengo wa kijiografia-kisiasa hauwezi kufungamana na mrengo mmoja wowote. Serikali za kitaifa zinaweza kuchangia kwa hiari. Michango ni ya uwazi. Hakuna mchango unaonunua ushawishi wa uongozi, kutoka chanzo chochote, kamwe.

Kila dola na kila kipimo cha thamani kinachoingia kwenye mkataba kinarekodiwa kwa kudumu, hadharani, na kwa njia inayofuatilika — kinachoweza kujengwa upya kupitia Replay, ili raia karne moja kutoka sasa aweze kuthibitisha mnyororo huo haujavunjika. Thamani inamfikia mshiriki kupitia saa za 웃 zilizoshuhudiwa na njia za mitaa zenye leseni, kamwe si hazina ambayo mkataba wenyewe unaihifadhi; QIS inapima kwa uaminifu, kamwe halipi. Gharama za utawala zina kikomo, zawadi za mashirika zina kikomo pia. Uhasibu kamili unatolewa katika lugha ya kila eneo mtia-saini kila mwezi. Viongozi wanaotia saini mkataba wanaahidi uwazi ambao mara chache hutolewa na taasisi yoyote. Huu ndio uaminifu mkataba unaohitaji — unaopatikana mchango mmoja mdogo unaofuatilika kwa wakati mmoja, mbele ya kila raia.`,
      999: `Mkataba wa Atlantis wenyewe unagharamiwa na raia unaowahudumia, na ukweli huo mmoja unaunda kila kitu kinachofuata baada yake — kila njia, kila kumbukumbu, kila lango ambalo kijana lazima apite ili aonekane. Wakazi wa kawaida wa maeneo yanayoshiriki wanachangia kiasi kidogo cha hiari kila mwezi, viwango vidogo vya kutosha kwamba hakuna mtu mzima katika eneo lolote mwenyeji anayeshindwa kumudu ushiriki, na vikubwa vya kutosha kwamba jumla yake inaudumisha kazi ya mkataba kwa kiwango cha maana. Muundo huu ni wa makusudi, na si wa bahati mbaya kwa dhamira — ni uthibitisho wa dhamira hiyo. Raia anapogharamia elimu ya kizazi kijacho moja kwa moja, raia huyo anaushikilia mkataba uwajibikaji moja kwa moja, katika pumzi ile ile, bila mpatanishi ambaye angeweza kulainisha hesabu au kuchelewesha uwajibikaji. Hakuna mkondo wa msaada, hakuna mfadhili wa kigeni, hakuna masharti ya kisiasa yaliyoambatanishwa na hundi. Roho ya mkataba huu ni raia anayechangia kiasi kidogo kila mwezi, ambaye ushiriki wake ndio unaoufanya wote uwezekane, na ambaye ushiriki wake unaoendelea ndio kura pekee ya imani inayohesabika mwishowe katika miaka mia tano.

Mkataba huu ni huru kwa makusudi na taasisi za kimataifa zilizounda karne iliyopita — NATO, WHO, Umoja wa Mataifa, IMF, Benki ya Dunia, na kila mkondo wa kitaifa wa msaada wa kigeni. Hili si tamko la kisiasa kuhusu thamani ya taasisi hizo au michango yao. Ni chaguo la kiubunifu, na ni chaguo lile lile la kiubunifu linalosimamia kila njia ya kiufundi chini ya mkataba wenyewe: Continuity Without Evasion. Uhamishikaji halali ndio kanuni — hakuna serikali, benki, mwanzilishi, au mfumo mmoja usiozuilika unaoruhusiwa kukaa chini ya muundo mzima, kwa sababu upeo wa miaka mia tano hauwezi kutegemewa juu ya kudumu kwa mhusika mmoja yeyote. Kila mamlaka ya kisheria inabeba adapta yake yenyewe, ikifunga-wakati-inaposhindwa na 'default-deny', ili uamuzi hasi katika taifa moja ufunge njia hiyo moja tu — kamwe hauleti chini hesabu za familia katika eneo lililoko ng'ambo ya bahari. Serikali za kitaifa zinaweza kuchangia kwa hiari. Michango ni ya uwazi. Hakuna mchango unaonunua ushawishi wa uongozi, kutoka chanzo chochote, kamwe — si kutoka serikali, si kutoka shirika, wala si kutoka waanzilishi wa mfumo wenyewe.

Human Authority ni nguzo ya pili inayobeba muundo huu wa ufadhili. Maana, fedha, na sheria vinabaki mambo ya kibinadamu, yanayoamuliwa na binadamu mbele ya binadamu wenzao; ngazi ya enzi kuu ambapo dhamira ya mkataba inawekwa na fedha zake zinasimamiwa inabaki imefungwa kwa mashine, hata kama mashine hizo zitakuwa na uwezo kiasi gani katika kazi zilizo chini yake. Measurement of Time inarekodi dakika halisi za kazi tofauti na dai lolote kuhusu thamani yake, ili hakuna yeyote — binadamu au mashine — anayeweza kuvimbisha rekodi kimya kimya. Replay inasimama nyuma ya kila rekodi hizo, ikifanya kila toleo mkataba wenyewe unalotoa kuweze kujengwa upya kutoka chanzo chake, wazi milele kwa changamoto, wazi milele kwa marekebisho. Raia anayechangia kiasi kidogo leo anaamini kwamba baada ya miaka hamsini, baada ya miaka mia mbili, mtu bado ataweza kufuata mnyororo huo hadi kumbukumbu ya mwezi huu na kuikuta hasa kama ilivyokuwa.

Kuingia katika mfumo huu wa imani kunaanza na Seed — uanachama wa mara moja, wenye bei ya sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika, usiohamishika na usiobeba dai lolote la kiuchumi. Seed hainunui hisa, hainunui kura yenye uzito wa utajiri, wala hadhi ya upendeleo katika uhasibu unaofuata. Inanunua uanachama tu, kwa bei ya chini vya kutosha kwamba kijana popote mkataba wenyewe unapofanya kazi anaweza kumudu kuanza. Kila kitu mwanachama anachopata baada ya hapo kinapatikana, kamwe hakinunuliwi, na tofauti hiyo ndiyo muundo mzima wa kimaadili wa mkataba katika hali ndogo.

Thamani inayomfikia mtu inapita kupitia 🏠 Livelihood Direct — njia za mitaa zenye sifa, zenye leseni zinazobeba malipo hadi kwa mtu, kamwe si kwenye hazina ambayo mfumo wenyewe unaihifadhi au kuidhibiti. Uainishaji unatangulia malipo katika kila hali; kitanda, ruzuku, nafasi katika hatua inayofuata ya mafunzo inazuiliwa na jukumu na utayari, kamwe si utambuzi peke yake, kwa sababu utambuzi ni rahisi lakini riziki (livelihood) si rahisi. Huu ndio mnyororo ambao mchango wa kila mwezi wa raia hupitia kihalisia: kutoka akaunti ya raia, kupitia njia iliyokaguliwa, hadi ruzuku ambayo kijana anapokea, hadi mradi wa ubunifu ambao kazi ya kijana huyo inakuwa, na kurudi tena kama hesabu ya hadhara ambayo raia yeyote anaweza kuisoma.

Thamani ya kazi hiyo inapimwa, si kudhaniwa. Qualified Innovation Score inachukua wastani wa utayari, uwezo wa ukuaji, athari ya matokeo, na utayari wa utekelezaji katika namba moja, na ukuaji wa alama hiyo unapanga ukubwa wa hazina ya tuzo tu baada ya sifa kutimizwa — QIS yenyewe haizalishi chochote wala kulipa chochote; ni kipimo, kamwe si malipo, na kipimo hicho kamwe hakichanganywi hapa na umiliki. Malipo kwa kazi ya kibinadamu yanafika badala yake kama 웃, yenye thamani ya saa moja mara mshahara wa chini wa eneo husika, ikizidishwa na kizidishi (multiple) chenye wigo maalum, kilichoidhinishwa kibajeti, cha saa zilizofanywa hasa na kushuhudiwa. Kabla jukumu halijabeba idhini hiyo, kazi iliyo nyuma yake ni upangaji, si kazi inayolipwa, na hakuna anayelipwa kupanga. Kikomo cha 웃 9,999 kwa mwaka, huku ziada yoyote ikiendelea kubebwa mbele badala ya kupotea, kinazuia hesabu ya mwaka wowote mmoja kuwa faida ya ghafla au mtego.

Hakuna kati ya haya kinachosonga haraka zaidi kuliko uthibitisho wake wenyewe. Mkataba wenyewe unaendelea kutoka Kwa Mkono hadi Nusu-Kiotomatiki hadi uendeshaji wa Kujitegemea kiwanja kimoja kwa wakati mmoja, na tu pale ambapo kiwango kamili cha uboreshaji uliopimwa — sehemu moja ya tisa — kimeonyeshwa kihalisia, kamwe hakidhaniwi mapema. Uhuru wa kujiendesha unapatikana pale hasa na si karibu na maana, fedha, au sheria, ambavyo vinabaki vya kibinadamu daima. Gharama za utawala zina kikomo. Zawadi za mashirika na taasisi zinakaribishwa na zina kikomo pia. Uhasibu kamili unatolewa katika lugha ya kila eneo mtia-saini kila mwezi, ukianzia Kambodia, Honduras, na Austin, na unakusudiwa kuendelea kutolewa, na kuendelea kusomeka, hata baada ya miaka mia tano. Huu ndio uaminifu mkataba unaohitaji. Huu ndio uaminifu mkataba unaoupata, mchango mmoja mdogo unaofuatilika kwa wakati mmoja, mbele ya kila raia utakayemhudumia.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Ubadilishanaji wa tamaduni mbalimbali na mchango wa kimataifa`,
    content: {
      7: `Kila mwanafunzi katika lugha yake mwenyewe.`,
      33: `Kila shughuli katika lugha ya mshiriki — wazi kwa raia yeyote, bila kuhitaji idhini ya serikali. Akili Bandia, ya Kibinadamu, na Shirikishi zinashikiliwa katika mvutano wenye tija. Mitaala inachapishwa kwa uwazi. Kile eneo moja linalojifunza, wote wanarithi.`,
      111: `Mkataba wa Atlantis unairejesha elimu kwenye dhamira yake ya kina zaidi: kubadilishana hekima kuvuka mipaka ambayo vinginevyo ingegawanya. Raia yeyote anaweza kuingia mtaala huu, bila kujali serikali yake imetia saini nini. Kila shughuli inapatikana katika lugha ya mshiriki, lugha ya eneo mwenyeji, na kumbukumbu ya pamoja. Lugha si mapambo — lugha ni mamlaka ya kisheria, lugha ni utu uliofanywa usomeke. Mfumo wa elimu unategemea utatu wa akili: Akili Bandia inapendekeza, Akili ya Kibinadamu inaamua, Shared Intent inathibitisha. Kila mwanafunzi anajifunza kushikilia zote tatu katika mvutano. Kile mkataba unachojifunza, unakirudisha. Mitaala, matokeo ya ubunifu, utafiti wa ustawi, na maamuzi ya uongozi vinachapishwa kwa uwazi. Kile eneo moja linalojifunza, raia wote wanarithi.`,
      333: `Mkataba wa Atlantis unairejesha elimu kwenye dhamira yake ya kina zaidi: kubadilishana hekima kuvuka mipaka ambayo vinginevyo ingegawanya. Huu ni mkataba baina ya raia wa dunia — raia yeyote anaweza kuujenga na kuushikilia, bila kujali serikali yake imetia saini nini. Kila shughuli inapatikana katika lugha ya mshiriki, lugha ya eneo mwenyeji, na kumbukumbu ya pamoja, ili hakuna mshiriki anayepitia mkataba katika lugha asiyoichagua. Lugha si mapambo. Lugha ni mamlaka ya kisheria. Lugha ni utu uliofanywa usomeke. Kijana Kambodia anasoma kumbukumbu ya ruzuku yake kwa Kikhmer, Honduras kwa Kihispania, Austin kwa Kiingereza — zote tatu zikiheshimiwa sawa, bila hata moja kuhitaji baraka ya serikali kuanza.

Mfumo wa elimu unategemea utatu wa akili ambao Vision 2525 unaufanya uonekane. Akili Bandia inapendekeza mifumo na uwezekano kwa haraka zaidi kuliko binadamu peke yake angeweza. Akili ya Kibinadamu inaamua kuhusu usalama, maadili, na mwelekeo — maswali ambayo hakuna mashine inayopaswa kuyajibu, yakiwekwa chini ya Human Authority. Shared Intent inathibitisha kwamba maamuzi yanahudumia kanuni za mkataba, ili hakuna mshiriki anayechagua ubora kuliko manufaa ya pamoja. Hakuna mwanafunzi anayetegemea akili moja pekee; kila mwanafunzi anajifunza kushikilia zote tatu katika mvutano. Uanachama unaanza na Seed, uanachama wenye bei ya sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika — kidogo vya kutosha kwamba raia yeyote anaweza kuumudu. Hii inaandaa kizazi kijacho kutawala, ambapo hakuna akili inayotenda bila kudhibitiwa.

Kile mkataba unachojifunza, unakirudisha. Mitaala inachapishwa chini ya leseni huria ili eneo lolote — mtia-saini au la — liweze kuibadilisha kulingana na utamaduni wa mahali husika. Matokeo ya ubunifu yanachapishwa. Utafiti wa ustawi unachapishwa kwa muhtasari kwa watafiti kila mahali. Maamuzi ya uongozi yanachapishwa pamoja na sababu zake, ili raia yeyote, si serikali inayotia saini tu, aweze kuyathibitisha — na Replay inamruhusu raia huyo huyo kufuatilia sababu hizo karne moja kutoka sasa. Mafanikio yanapimwa si tu kwa washiriki wake bali kwa mipango ya kielimu na kitamaduni inayoibuka baada yake, katika maeneo ambayo hayakutia saini jaribio hilo lakini yalijenga juu ya hekima yake iliyoshirikiwa. Kile eneo moja linalojifunza, kila raia anarithi.`,
      999: `Mkataba wa Atlantis unairejesha elimu kwenye dhamira yake ya kina zaidi: kubadilishana hekima kuvuka mipaka ambayo vinginevyo ingegawanya, na unaanza kubadilishana huko kabla somo hata moja halijafundishwa. Tendo la kwanza la kila mshiriki ndani ya mfumo ni Seed — uanachama wa mara moja wenye bei ya sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika, usiohamishika, usiobeba dai lolote la kiuchumi. Ni kidogo vya kutosha kwamba hakuna familia inayotengwa na ni halisi vya kutosha kwamba hakuna mshiriki anayeingia kama mtazamaji. Hili ni somo la kwanza la mkataba: uanachama unapatikana kwa gharama nafuu, lakini bado unapatikana, na hauleti umiliki wowote juu ya kile kinachofuata. Kila shughuli ya mkataba inayofuata inapatikana katika lugha ya mshiriki, katika lugha ya eneo mwenyeji, na katika kumbukumbu ya pamoja, ili hakuna mshiriki anayepitia mkataba katika lugha asiyoichagua. Lugha si mapambo. Lugha ni mamlaka ya kisheria. Lugha ni utu uliofanywa usomeke. Kijana kutoka kijiji cha Kikambodia anaposoma kumbukumbu ya ruzuku yake kwa Kikhmer, mji wa Kihonduras kwa Kihispania, na kitongoji cha Austin kwa Kiingereza, zote tatu zinaheshimiwa sawa na mkataba ule ule, katika maeneo yale yale ya kianzilishi yaliyokubaliana kwanza kufundishana.

Mfumo wa elimu wa mkataba huu unategemea utatu wa akili ambao Vision 2525 unaufanya uonekane, na mtaala unafundisha kila mmoja kama kitu ambacho mshiriki anaweza kukishika kwa mikono yake mwenyewe, si kama dhana tu. ♡, Shared Intention, inabeba sababu — uzi ambao kila mwanafunzi anajifunza kuushikilia kabla ya kugusa chombo chochote, swali la iwapo kazi hii bado inahudumia watu inaodai kuwahudumia. ◬, kasi iliyoshuhudiwa, inafundishwa kama tofauti (delta) na hakuna zaidi — inapimwa tu dhidi ya kigezo kilichogandishwa, kamwe isivishwe kama kipimo cha faida, kamwe isidaiwe kama mafanikio ya kibinafsi mbali na timu inayozunguka. 웃, Akili ya Kibinadamu iliyoheshimiwa kwa wakati, inafundishwa kwa uangalifu zaidi: saa moja ya kazi iliyoshuhudiwa ni sawa na saa moja kwa mshahara wa chini wa eneo husika, na kile mshiriki anachopata ni mshahara huo ukizidishwa na saa alizofanya kazi — Multiple mara Time, hakuna kilichofichwa katika hesabu. Wanafunzi wanajifunza mapema kwamba 웃 hutolewa tu kwa kazi iliyoshuhudiwa iliyofanywa chini ya jukumu lenye wigo maalum na lililoidhinishwa kibajeti. Kabla idhini hiyo haijawepo, juhudi ile ile ni upangaji tu — yenye thamani, lakini isiyolipwa, na kila mshiriki anafundishwa kutambua tofauti hiyo mara moja.

Kwa sababu tofauti hiyo inachanganyikana kwa urahisi, mtaala unafundisha QIS, Qualified Innovation Score, kama kioo badala ya ubao wa alama. QIS ni wastani wa vipimo vinne kamili vya kifedha — Mapato, Faida Ghafi, Kipato cha Uendeshaji, na matumizi Halisi ya Utafiti na Maendeleo — vikigawanywa kwa nne, na kila mwanafunzi anajifunza kuihesabu, kuihoji, na kamwe asiichanganye na fedha. Ukuaji wa QIS unapanga ukubwa wa hazina ya tuzo tu baada ya sifa kuthibitishwa kwa uhuru, na ukuaji huo haizalishi 웃 yoyote yenyewe. QIS ni kipimo. QIS kamwe si malipo. QIS kamwe si umiliki. Mwanafunzi aliyeielewa tofauti hii moyoni hawezi kushawishika kwamba alama ya juu inampa haki ya dai ambalo mkataba haujawahi kuahidi.

Mtaala unaeneza ujuzi huu hadi jinsi thamani inavyomfikia kweli mtu, kupitia kile mkataba unachokiita Livelihood Direct — kanuni ya 🏠 kwamba fedha inasogea kupitia njia za mitaa zenye sifa, zenye leseni na kamwe si kupitia hazina ambayo mfumo wenyewe unaihifadhi. Wanafunzi wanafundishwa kufuatilia ruzuku yao, na baadaye mapato yao wenyewe, kupitia njia hizi kama zoezi la kiraia, si fumbo la kifedha linalofanywa mahali pengine kwa niaba yao. Wanajifunza kwamba uainishaji daima unatangulia malipo, na kwamba utambuzi — QIS ya juu, pongezi ya hadhara — havizuii vyenyewe kitanda, ruzuku, au nafasi katika mzunguko. Jukumu ndilo linalozuia. Hii ni ulinzi dhidi ya kasoro ya kale sana: sifa kuchanganywa na utoaji.

Pamoja na ujuzi wa kifedha kuna ujuzi wa uraia, unaofundishwa kupitia Continuity Without Evasion. Kila mshiriki anajifunza kwamba mkataba umejengwa kwa ajili ya uhamishikaji halali — kwamba hakuna serikali, benki, mwanzilishi, au mfumo mmoja usiozuilika unaosimama kati yao na ahadi za mfumo. Wanajifunza kile uamuzi hasi unachofanya ndani ya muundo huu: unafunga njia moja tu, katika mamlaka moja ya kisheria, chini ya msimamo wa 'default-deny' wa adapta hiyo, na kamwe haubomoi wote. Sambamba na hili ni somo la kina zaidi ambalo mkataba unafundisha: Human Authority inashikilia maana, fedha, na sheria, na ngazi ya enzi kuu ambapo maamuzi hayo yanafanywa inabaki imefungwa kwa kudumu kwa mashine. Measurement of Time, MoT, inarekodi dakika halisi za kila mshiriki tofauti na alama yoyote, na Replay inafanya kila toleo mkataba unalotoa liweze kujengwa upya kikamilifu — ili mwanafunzi anayetaka kujua kwa nini uamuzi ulifanywa, miaka baadaye, aweze kuufuatilia mwenyewe badala ya kuamini neno la mtu yeyote.

Muundo huu wa imani inayopatikana unakuwa mfano wa kielimu wa mkataba, si tu mfano wake wa uongozi. Kila mshiriki anaendelea kupitia hali za Kwa Mkono, Nusu-Kiotomatiki, na Kujitegemea za uhuru unaoongezeka, ukizuiwa na kizingiti kile kile cha uboreshaji uliopimwa kinachozuia teknolojia yenyewe — ongezeko lililothibitishwa la asilimia kumi na moja na sehemu moja ya tisa kabla hali inayofuata haijafunguka. Uhuru wa kujiendesha, unapopatikana, unapatikana kwa upana mdogo na kwa kila uwanja, kamwe si juu ya maana, fedha, au sheria. Mwanafunzi aliyeipitia mchakato huu anaelewa, moyoni, kwa nini ngazi ya enzi kuu kamwe haipaswi kuondolewa kwa kiotomatiki — kwa sababu alipata uhuru wake mwenyewe wa kujiendesha hatua moja iliyopimwa kwa wakati mmoja, na anajua hasa uhuru huo ulijumuisha nini na haukujumuisha nini.

Kile mkataba unachojifunza, mkataba unakirudisha. Mitaala inachapishwa chini ya leseni huria ili eneo lolote — mtia-saini au la — liweze kuibadilisha kulingana na utamaduni wa mahali husika na mapokeo ya kielimu. Matokeo ya ubunifu yanachapishwa. Utafiti wa ustawi unachapishwa kwa muhtasari kwa watafiti kila mahali. Maamuzi ya uongozi yanachapishwa pamoja na sababu zake kamili. Mafanikio ya mkataba yanapimwa si tu kwa washiriki wake katika Kambodia, Honduras, na Austin, bali kwa mipango inayoibuka baada yake, katika maeneo ambayo hayakutia saini jaribio la kianzilishi lakini yalijenga juu ya hekima yake iliyoshirikiwa kwa uwazi, katika upeo ambao waanzilishi hawataishi kuuona ukikamilika. Kile eneo moja linalojifunza, maeneo mengine yote yanarithi — na kile ambacho kizazi hiki kinafundishwa kwa uaminifu, miaka mia tano ijayo haitalazimika kukisahau.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Ukuaji endelevu wa mtandao`,
    content: {
      7: `Kamwe kwa kasi zaidi kuliko heshima inavyoweza kusafiri.`,
      33: `Maeneo matatu ya kianzilishi yanakamilisha mzunguko mmoja wa jaribio kabla eneo la nne halijajiunga — raia yeyote anaweza kuulijenga. Kumbukumbu zimewekwa nanga kudumu karne tano. Watia-saini wanabaki na uhuru wa kujitawala; hakuna kinachopunguzwa kwa ajili ya ujumuisho unaofuata.`,
      111: `Mkataba wa Atlantis hautakua haraka zaidi kuliko ubora unaoweza kuuheshimu. Maeneo matatu ya kianzilishi lazima yakamilishe mzunguko kamili wa jaribio, huku kila mshiriki akiheshimiwa na kila kanuni ikithibitishwa, kabla eneo la nne halijajiunga. Hii ni kanuni ambayo hatimaye imekuwa nidhamu ya kazi. Lakini mkataba huu ni makubaliano baina ya raia wa dunia — mtu yeyote, popote alipo, anaweza kuujenga na kuushikilia, Seed moja mbali, bila kujali serikali inatia saini nini au mwajiri anaruhusu nini. Upeo wa mkataba ni karne tano. Kumbukumbu zake zimewekwa nanga kupitia Replay, ili raia anayezisoma karne moja kutoka sasa aweze kuamini sababu zilizotolewa. Kila mtia-saini anabaki na uhuru wa kujitawala; hakuna kinachopunguzwa kwa ajili ya ujumuisho unaofuata.`,
      333: `Mkataba wa Atlantis hautakua haraka zaidi kuliko ubora unaoweza kuuheshimu. Kila upanuzi ni ahadi kwa washiriki ambao tayari wamo ndani — kwamba kiwango cha kianzilishi hakitapunguzwa na ukubwa. Maeneo matatu ya kianzilishi lazima yakamilishe mzunguko kamili wa jaribio, huku kila mshiriki akiheshimiwa na kila kanuni ikithibitishwa, kabla eneo la nne halijajiunga. Hii ni kanuni ambayo hatimaye imekuwa nidhamu ya kazi. Na mlango haukuwa wa kikanda pekee kamwe: huu ni makubaliano baina ya raia wa dunia, na mtu yeyote anaweza kuujenga, kuughamia, na kuushikilia uwajibikaji — bila kuhitaji idhini ya serikali, bila baraka ya mwajiri. Viongozi wanaotia saini jaribio hili wanaahidi watia-saini msingi ule ule, ulinzi ule ule, na utu ule ule ambao kikundi cha kianzilishi kilipokea. Hakuna kinachopunguzwa kwa ajili ya wafuatao.

Upeo wa mkataba huu ni mrefu kwa makusudi — umebuniwa kudumu vizazi kumi na tano hadi ishirini vya kibinadamu, karne tano tangu siku ya kianzilishi. Kumbukumbu zake zimewekwa nanga kupitia Replay, ili raia anayezisoma karne moja kutoka sasa aweze kuthibitisha sababu, si kuziamini tu. Mfumo wake wa kuratibu, majukumu yake ya Human Authority, na mizunguko yake ya uongozi wa vizazi mbalimbali vimejengwa kusalimika mpito wowote wa teknolojia moja. Mkataba huu utaishi zaidi ya kila binadamu anayetia saini jaribio lake la kianzilishi, na kila raia anayepanda Seed na kuughamia kila mwezi. Hiyo ndiyo ahadi yake kwa mtoto anayetia saini makubaliano ya ruzuku, kwa raia aliyejiunga bila kudai ruhusa ya serikali, kwa wajukuu wa mtoto huyo watakaoweza kuutawala mkataba katikati ya karne, na kwa kila kizazi kinachorithi kile ambacho waanzilishi — wa rasmi na wa kiraia sawa — wanajenga sasa.

Kila mtia-saini anabaki na uhuru wa kujiondoa, uhuru kamili wa kujitawala, na mamlaka juu ya raia wake mwenyewe, akiwa na haki ya kurekebisha na kuunda mabadiliko ya mkataba. Kila raia anabaki na hadhi ile ile ya kuanzisha, kughamia, kushuhudia, na kuushikilia uwajibikaji — akiwa na au bila saini ya serikali. Kile ambacho hakuna anayeweza kukifanya ni kuathiri kanuni za kianzilishi, kwa sababu ahadi hiyo lazima isalimike kutoka kwa mtu yeyote anayeondoka. Viongozi na raia sawa wanatia saini karne ijayo ya mkataba katika upeo ambao wajukuu wao watairithi na kuikamilisha.`,
      999: `Mkataba wa Atlantis hautakua haraka zaidi kuliko ubora unaoweza kuuheshimu, na kujizuia huku si hisia tu — ni uhandisi, ulioandikwa katika nidhamu ile ile ya upimaji inayosimamia kila ahadi mkataba unayoitoa. Maeneo matatu ya kianzilishi, Kambodia, Honduras, na Austin, lazima yakamilishe mzunguko kamili wa jaribio, huku kila mshiriki akiheshimiwa na kila kanuni ikithibitishwa, kabla eneo la nne halijajiunga. Ukuaji unaopita kasi ya uthibitisho si ukuaji; ni hatari iliyovaa vazi la matarajio makubwa. Jaribio la kianzilishi lipo ili mkataba uweze kuthibitisha, kwa kiwango kidogo cha kutosha kukaguliwa na kikubwa cha kutosha kuwa na maana, kwamba ahadi zake zinasalimika kugusana na uhalisia kabla ahadi hizo hazijaenezwa kwa dunia inayotazama kutoka nje ya mipaka yake mitatu. Eneo la nne bado halijataajwa, na halitatajwa mpaka matatu ya kwanza yasimame nyuma ya kila dai ambalo hati hii inatoa.

Kile kinachothibitisha utayari wa kukua si shauku tu bali namba ambayo mkataba unaweza kuitetea hadharani. Qualified Innovation Score — QIS, inayohesabiwa kama Mapato pamoja na Faida Ghafi pamoja na Kipato cha Uendeshaji pamoja na matumizi Halisi ya Utafiti na Maendeleo, yakigawanywa kwa nne — ni chombo ambacho mkataba unatumia kujua iwapo eneo, kikundi, au kiwanja kimeboreka, badala ya kuhisi kama kimeboreka. Ukuaji wa QIS unapanga ukubwa wa hazina ya tuzo tu baada ya sifa kutimizwa, kamwe si kabla, na QIS yenyewe haizalishi 웃 wala kununua umiliki. QIS ni kipimo, si malipo; kipimo, si hisa; kioo ambacho mkataba unakiinua juu ya kazi yake mwenyewe, kamwe si sarafu inayoitumia. Eneo linalopendekeza kupanua mtandao lazima lionyeshe QIS yake kwa uaminifu, mbele ya maeneo yaliyotangulia, la sivyo halipanuki.

Ukuaji endelevu unamaanisha ukuaji unaopata mamlaka yake yenyewe hatua moja kwa wakati mmoja. Kila kiwanja na kila eneo linaanza katika hali ya Kwa Mkono, ambapo binadamu wanaamua kila kitu na mfumo unasaidia tu. Kuendelea hadi Nusu-Kiotomatiki, na hatimaye uendeshaji wa Kujitegemea, ndani ya kiwanja fulani kunazuiwa na kizingiti kimoja katika mkataba mzima — uboreshaji uliopimwa wa asilimia kumi na moja na sehemu moja ya tisa, sehemu moja ya tisa, ulioothibitishwa na unaoweza kurudiwa kabla kiwango kinachofuata cha uhuru wa kujiendesha hakijatolewa. Uhuru wa kujiendesha unapatikana kiwanja kwa kiwanja, kamwe hautolewi kwa mkupuo mmoja wala kuenezwa juu ya nyanja ambazo lazima zibaki za kibinadamu bila kujali mfumo utakavyoendelea: maana, fedha, na sheria vinabaki vimefungwa kwa mashine bila kujali vizingiti vingapi vimethibitishwa kwingineko. Mtandao unaopanua uwezo wake wa kiotomatiki haraka zaidi kuliko unavyopanua ushahidi wake hauhalikishi. Unacheza kamari na imani ambayo bado haujaipata.

Malipo yanakua pamoja na mtandao kwa njia ile ile mamlaka inavyokua — kwa makusudi, na kwa kikomo kinacholinda mfumo mzima dhidi ya mafanikio yake yenyewe. 웃, ishara ya Human Intelligence, ni sawa na saa moja ya kazi iliyoshuhudiwa ikizidishwa na mshahara wa chini wa eneo husika; kile mshiriki yeyote anachopata ni Multiple hiyo mara saa alizofanya kazi, na inatolewa tu kwa kazi iliyofanywa chini ya jukumu lenye wigo maalum na lililoidhinishwa kibajeti. Kabla ya idhini, mpango bora zaidi ni upangaji tu, na upangaji peke yake haizalishi chochote. Malipo ya kila mshiriki yana kikomo cha 웃 9,999 kwa mwaka, huku ziada yoyote ikiendelea kubebwa mbele badala ya kupotea au kupotosha hazina. Maeneo mapya yanapojiunga na shughuli za mtandao zinapoongezeka, kikomo hiki ndicho kinachozuia ukuaji kuwa mfumuko wa bei — thamani inabaki imefungwa kwa saa halisi, zilizoshuhudiwa, za mitaa bila kujali mkataba utakuwa mkubwa kiasi gani.

Nyuma ya kila 웃 kuna sababu ambayo hakuna kumbukumbu inayoweza kuihesabu peke yake. ♡, Shared Intention, inabeba sababu hiyo mbele kupitia kila uamuzi wa upanuzi ambao mkataba unaufanya, huku ◬, mchango wa Akili Bandia, ukihesabiwa kama kasi iliyoshuhudiwa iliyopimwa dhidi ya kigezo kilichogandishwa — tofauti (delta), na kamwe, katika hali yoyote, kipimo cha faida kinachoboreshwa kwa ajili yake yenyewe. Kuingia katika mtandao huu kunaanza kwa njia ile ile kwa kila mshiriki bila kujali eneo gani au muongo gani anajiunga: kwa Seed, uanachama wa mara moja wenye bei ya sehemu ya saba ya saa moja ya mshahara wa chini wa eneo husika, usiohamishika na usiobeba dai lolote la kiuchumi. Seed inasema tu kwamba mtu amefika. Kila kitu wanachojenga baadaye, wanakijenga mbele ya macho ya sarafu nyingine tatu za mkataba, kamwe si kupitia Seed yenyewe.

Ukuaji ulio halisi lazima pia uwe ukuaji unaomfikia mtu halisi, si hazina ambayo mfumo unaishikilia kwa niaba ya mtu. 🏠 Livelihood Direct inahitaji kwamba thamani isafiri kwa mshiriki tu kupitia njia za mitaa zenye sifa, zenye leseni ambazo mkataba umezikagua eneo kwa eneo, na kamwe si kupitia uhifadhi ambao mfumo wenyewe unaubaki nao. Uainishaji daima unatangulia malipo, ili hakuna thamani inayosogea kabla ya lengo lake na mpokeaji wake vyote kuthibitishwa bila shaka. Na kwa sababu utambuzi si sawa na upatikanaji, kitanda, nafasi katika mzunguko, kiti mezani vinazuiliwa na jukumu na utayari, kamwe si alama ya mshiriki au hadhi yake. Mtandao unapopanuka hadi eneo la nne na kuendelea, kila eneo jipya lazima lithibitishe njia zake mwenyewe zenye leseni kabla Livelihood Direct haijaweza kuwafikia watu wake — upanuzi wa imani, si upanuzi wa eneo tu.

Hakuna kati ya haya kinachodumu bila mtandao uliojengwa kusalimika mafanikio yake yenyewe, ndiyo maana Continuity Without Evasion inasimamia kila eneo ambalo mkataba unawahi kuliongeza. Uhamishikaji halali ni wa lazima; hakuna serikali, benki, mwanzilishi, au mfumo mmoja unaoruhusiwa kuwa usiozuilika kwa wote. Kila mamlaka ya kisheria inaendesha adapta yake yenyewe, ikifunga-wakati-inaposhindwa na 'default-deny', ili uamuzi hasi popote ufunge njia moja, kamwe si mkataba mzima. Human Authority inashikilia maana, fedha, na sheria katika kila kiwango mtandao unaofikia, ikiwa imefungwa dhidi ya uvamizi wa mashine kwa ubunifu badala ya ahadi tu. Measurement of Time inarekodi kila dakika halisi tofauti na kila dai kuihusu, na Replay inahakikisha kwamba toleo lolote, katika eneo lolote, wakati wowote katika karne tano, linaweza kujengwa upya na kuchunguzwa upya na yeyote anayeuliza. Mtandao usioweza kujengwa upya kupitia Replay hauwezi kuaminiwa, hata kama maeneo mangapi yamejiunga nao au ukuaji wake unaonekana wa kuvutia kiasi gani kutoka nje. Hivi ndivyo Vision 2525 inavyokua bila kamwe kupita imani iliyojengwa kuishika — eneo moja lililothibitishwa, QIS moja ya uaminifu, saa moja iliyoshuhudiwa kwa wakati mmoja.`,
    },
  },
];
