import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_TL: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Kung Saan Nagsisimula ang Inobasyon`,
    content: {
      7: `Sinisimulan ng mga lider ang di pa nasimulan.`,
      33: `Tatlong rehiyon — Cambodia, Honduras, Austin — ang nagbubukas ng isang pangako na tinutulungang buuin ng mga mamamayan: paunlakan ang mga nag-aaral, ingatan sila, ipagkatiwala sa kanila ang mga kasangkapan ng hinaharap. Ang Pamahalaan, Edukasyon, at Innovation ay pumipirma bilang tagapangalaga; ang mga mamamayan ang may hawak nito. Isang simula.`,
      111: `Ang Atlantis Accords ay isang kasunduan sa hanay ng mga mamamayan ng daigdig — isang pangako na maaaring likhain at panindigan ng sinumang tao, saanman, anuman ang pinirmahan ng kanilang pamahalaan o pinapayagan ng kanilang employer. Ang mga rehiyong nagtatag nito, ang Cambodia, Honduras, at Austin, Texas, ay pinili dahil sa isang bihirang katangian: ang kahandaang ipagkatiwala sa kabataan ang mga kasangkapan ng hinaharap habang may panahon pa upang turuan sila. Ang mga pamahalaan, tagapagturo, at innovator ay pumipirma bilang tagapangalaga ng kanilang mga rehiyon — tatlong makabagbag-damdaming pirma bawat isa, Pamahalaan, Edukasyon, Innovation — ngunit ang mga mamamayan ang nagpopondo, sumasaksi, at direktang humahawak dito. Walang pahintulot ng pamahalaan o basbas ng employer na kinakailangan upang mabilang dito. Tatlong rehiyon, isang magkasamang simula.`,
      333: `Ang bawat sibilisasyon ay naaalala sa kung ano ang pinili nitong simulan. Ang Atlantis Accords ay isang pangako sa hanay ng mga mamamayan ng daigdig — sinumang tao, saanman, ay maaaring magsimula nito, anuman ang pinirmahan ng kanilang pamahalaan. Ang mga rehiyong nagtatag nito, ang Cambodia, Honduras, at Austin, Texas, ay hindi pinili dahil sa kapangyarihang pang-ekonomiya, lakas militar, o prestihiyong institusyonal, kundi dahil sa isang mas bihirang katangian: ang kahandaang ipagkatiwala sa kabataan ang mga kasangkapan ng hinaharap. Ito ang kahulugan ng pamumuno sa darating na siglo — ang lakas ng loob na isuko ang mga susi sa susunod na henerasyon habang may panahon pa upang turuan silang magmaneho.

Ang kasunduan ay tinipon ng eXeL, isang puwersang pang-organisa na ginawa para sa sandaling ito, umiiral sa labas ng mga daluyan ng koordinasyon na humubog sa nakaraang siglo — labas sa mga istruktura ng tratadong diplomatiko, mga burukrasyang multilateral, at mga pagkakasangkot pampulitika ng anumang solong bansang-estado. Ang eXeL ang pinagkakatiwalaang tagapag-anyaya na nagtitipon sa mga makabagbag-damdaming pinuno sa paligid ng isang magkasamang balangkas, isang magkasamang flywheel, at isang magkasamang limandaang-taong abot-tanaw. Bawat pumirma ay nananatiling ganap na soberano, may ganap na kapangyarihan sa sarili nitong mga mamamayan, at ganap na malaya na umatras anumang oras. Ang natatamo ng mga pumirma — at natatamo ng sinumang mamamayan, sa halagang isang Seed, ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod — ay ang epektong network na tanging isang balangkas na ginawa para sa layuning ito ang makapagbibigay: koordinasyon na walang anumang anyo ng pananakop pampulitika.

Ang pagpirma sa kasunduan ay pagpirma sa isang pangako: na ang rehiyon ay paguukulan ng mga nag-aaral sa iba't ibang kultura, mag-aambag ng natatangi lamang nitong kaya nitong ialay, at hahawak sa sarili sa isang pamantayang mas mataas kaysa sa hinihiling ng kasalukuyang regulasyon — nang hayagan, transparente, sumasagot sa mga mamamayang nagpopondo, sumasaksi, at humahawak dito, walang pahintulot ng pamahalaan o basbas ng employer na kinakailangan upang mabilang. Tatlong pirma ang hinihingi mula sa bawat rehiyon — Pamahalaan, Edukasyon, at Innovation — pumipirma bilang tagapangalaga, hindi bilang may-ari. Kailangan ng tatlong makabagbag-damdamin upang sumang-ayon, at ng mga mamamayan upang hawakan ang kanilang napagkasunduan. Tatlong makabagbag-damdamin, tatlong rehiyon, isang simula — ganito pumapasok sa buhay ang isang balangkas sa pamamagitan ng tiwala ng mga pinunong nagnanais itong ipirma tungo sa pagkabuhay.`,
      999: `Ang bawat sibilisasyon ay naaalala sa kung ano ang pinili nitong simulan, at hinihiling ng Vision 2525 sa mga tagapagtatag nito na magsimula sa pagpapakumbaba sa halip na pananakop. Ang Atlantis Accords ay isang pangako ng mga pinunong handang simulan ang isang bagay na hindi pa umiiral dati — isang magkasamang pundasyon para sa pagbabagong pantao na umaabot sa bawat sulok ng daigdig, gumagalang sa bawat tinig, at nananatili sa maraming henerasyon na sinusukat hindi sa taon kundi sa mga siglo. Ang mga naglagda sa pagtatatag nito sa Cambodia, Honduras, at Austin, Texas ay hindi pinili dahil sa kapangyarihang pang-ekonomiya, lakas militar, o prestihiyong institusyonal. Pinili sila dahil sa isang mas bihirang katangian: ang kahandaang ipagkatiwala sa kabataan ang mga kasangkapan ng hinaharap, at ang pasensiyang hayaang mabuhay nang higit pa sa palakpakan ng anumang administrasyon ang isang limandaang-taong abot-tanaw. Ito ang kahulugan ng pamumuno sa darating na siglo — ang lakas ng loob na isuko ang mga susi sa susunod na henerasyon habang may panahon pa upang turuan silang magmaneho.

Ang kasunduan ay tinipon ng eXeL, isang puwersang pang-organisa na ginawa para sa sandaling ito. Ang eXeL ay umiiral sa labas ng mga daluyan ng koordinasyon na humubog sa nakaraang siglo — labas sa mga istruktura ng tratadong diplomatiko, labas sa mga burukrasyang multilateral, labas sa mga pagkakasangkot pampulitika ng anumang bansang-estado. Ang eXeL ang pinagkakatiwalaang tagapag-anyaya na nagtitipon sa mga makabagbag-damdaming pinuno sa paligid ng isang magkasamang balangkas, isang magkasamang flywheel, at isang magkasamang limandaang-taong abot-tanaw. Bawat pumirma ay nananatiling ganap na soberano, may ganap na kapangyarihan sa sarili nitong mga mamamayan, at ganap na malaya na umatras anumang oras. Ang natatamo ng mga pumirma ay ang epektong network na tanging isang balangkas na ginawa para sa layuning ito ang makapagbibigay. Ang pagpasok ng bawat kalahok sa balangkas na iyon ay nagsisimula sa parehong mapagkumbabang paraan: sa pamamagitan ng isang Seed, isang minsanang pagiging kasapi na nagkakahalaga ng ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod, hindi maililipat at walang dalang anumang pagmamay-aring pang-ekonomiya. Ang Seed ay hindi bumibili ng pagmamay-ari at walang ipinangakong gantimpala — pagkabilang lamang, ang karapatang tumayo sa loob ng balangkas at magsimula. Ito ay koordinasyon na walang anumang anyo ng pananakop pampulitika, itinayo sa isang simulang sapat na maliit para maabot ng sinuman.

Dahil ang soberanya ay pinananatili sa halip na isinusuko, ang kasunduan ay itinayo para sa Continuity Without Evasion. Walang mapapalitang pamahalaan, bangko, tagapagtatag, o modelo ang maaaring humawak ng buong balangkas bilang sangla sa sariling kaligtasan. Bawat hurisdiksyon ay pinaglilingkuran sa pamamagitan ng sarili nitong legal na adapter, tinatanggihan bilang default hangga't hindi napatunayang sumusunod, upang ang halaga ay dumaloy lamang sa mga daanang kikilalanin ng isang hukuman sa hurisdiksyong iyon bilang lehitimo. Kung ang isang regulator sa isang rehiyon ay maglabas ng laban na desisyon, ang solong daang iyon lamang ang nagsasara — nang transparente, nang hindi nakasasakit sa sinumang kalahok sa loob nito — habang patuloy na tumatakbo ang bawat ibang rehiyon nang hindi nagagambala. Hindi bumabagsak ang buong kasunduan dahil lang nagbago ang isip ng isang pamahalaan. Ito ay portabilidad na dinisenyo bilang isang pangakong pantatag, hindi bilang isang kontingensiyang natuklasan matapos ang krisis.

Ang pagpirma sa kasunduan ay pagpirma sa isang pangako. Na ang rehiyon ay magpapaunlak ng mga nag-aaral mula sa iba't ibang kultura. Na ang rehiyon ay mag-aambag ng natatangi lamang nitong kaya nitong ialay. Na ang rehiyon ay hahawak sa sarili sa isang pamantayang mas mataas kaysa sa hinihiling ng kasalukuyang regulasyon. Na gagawin ito ng rehiyon nang hayagan, transparente, sa harap ng bawat mamamayang pinaglilingkuran nito. Tatlong pirma ang hinihingi mula sa bawat rehiyon — Pamahalaan, Edukasyon, at Innovation. Walang isang tanggapan lamang ang bumubuklod sa kasunduan. Kailangan ng tatlong makabagbag-damdamin upang sumang-ayon. Ang tatlong-panig na pirmang ito ang unang pagpapahayag ng Human Authority: ang kahulugan, salapi, at batas ay nananatili sa kamay ng tao sa antas na soberano, isang antas na permanenteng sarado sa mga makina anuman ang kanilang kakayahan sa hinaharap. Ang Measurement of Time, MoT, ay nagsisimulang magtala mula sa sandali ng pagpirma — tunay na mga minuto ng tunay na gawaing pantao, hiwalay na iniingatan sa anumang awtomatikong pagtatantya — at bawat susunod na paglalabas ng gawain ng kasunduan ay itinayong maibalik sa pamamagitan ng Replay, upang maaaring balikan ng isang mamamayang isisilang isang siglo mula ngayon kung paano nakamit ang mga pasyang pantatag sa kasalukuyan.

Ang itinatag ng pilot ay pagsukat bago ito pera. Bawat pagbabagong pumapasok sa balangkas ay pinapatunayan gamit ang Qualified Innovation Score, QIS — ang katamtaman ng Kita, Kabuuang Tubo, Kita sa Operasyon, at Epektibong gastos sa R&D, hinati sa apat. Ang QIS ay hindi bayad at hindi kailanman pagmamay-ari; ito ang sukatang natututuhan ng isang nagtatag na grupo upang makita ang sariling nilang pag-unlad bago sukatin ang anumang gantimpala. Ang paglago ng QIS, kapag natugunan na ang kwalipikasyon, ay nagtatakda ng laki ng susunod na pondo ng gantimpala — ngunit ang paglago ng QIS mismo ay walang nililikhang anuman. Tatlong rehiyon, isang simula, at isang magkasamang disiplina: patunayan ang iskor bago galawin ang ingatang-yaman.

Ang halagang natatamo sa pamamagitan ng sinaksihang gawain ay may sariling pangalan, 웃, na kinakalkula bilang isang oras na pinarami ng lokal na pinakamababang sahod, isinusukat sa pamamagitan ng isang Multiple na inilalapat sa mga oras ng paglilingkod. Ang 웃 ay lumalabas lamang para sa gawaing sinaksihan sa ilalim ng isang nakalimitahang gawain na aprubadong may budget; anumang kulang doon ay pagpaplano pa lamang, at ang pagpaplano lamang ay walang nililikhang anuman. Isang hangganan ng pag-aayos na 9,999 웃 bawat taon ang nagpoprotekta sa bawat kalahok mula sa hindi mapigilang pagkakalap, na ang anumang labis ay idinadala sa susunod na taon sa halip na mawala. Sa likod ng bawat 웃 ay ang ♡, Shared Intention, na nagdadala ng dahilan kung bakit inaprubahan ang isang gawain sa umpisa pa lang, at ang ◬, ang sinaksihang pagbilis na naidulot ng isang gawain laban sa isang naka-freeze na baseline — isang delta lamang, hindi kailanman ipagkakamaling sukatan ng tubo. Ang pilot ay umiiral upang patunayan na ang tatlong glyph na ito ay maaaring gumalaw nang magkasama nang tapat, rehiyon sa rehiyon, bago lumawak ang balangkas nang higit pa sa mga tagapagtatag nito.

Kapag ang halaga ay umabot sa isang tao, ito ay umaabot sa pamamagitan ng Livelihood Direct — 🏠 — mga kwalipikadong lisensyadong lokal na daan na hindi kailanman inaari ng eXeL bilang sariling pondo. Ang klasipikasyon ay nauuna sa pag-aayos sa bawat pagkakataon, at ang pagkilala sa isang ambag ay hindi kailanman nagbabantay sa isang higaan para sa gabi; ang tungkulin lamang ng isang tao sa isang nakalimitahang gawain ang nagbabantay dito. Ang paglawak sa kabila ng pilot ay mayroon ding pinto: bawat cube ng balangkas ay lumilipat mula Manual patungong Semi-Automated hanggang Autonomous lamang matapos malampasan ang panuntunang 11.1 porsyento, isang bahagi sa siyam na nasukat na pagpapabuti, kinita cube por cube at hindi kailanman inaangkin nang buo — at hindi kailanman, sa anumang pagkakataon, sa itaas ng antas na soberano ng kahulugan, salapi, at batas. Ganito nagiging isang limandaang-taong pangako ang tatlong makabagbag-damdamin bawat rehiyon, tatlong rehiyon, at isang simula: hindi sa pamamagitan ng pagmamadali, kundi sa pagpapatunay, sa harap ng publiko, na bawat hakbang ay nagkamit ng karapatan sa susunod na hakbang.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Pagkatuto sa Pamamagitan ng Simulasyon`,
    content: {
      7: `Magsanay nang libong beses bago hawakan.`,
      33: `Walang mahalagang bagay na natututuhan una sa buháy na kagamitan. Sinumang mamamayan ay maaaring magpraktis sa simulasyon, umikot sa tatlong rehiyon, magdiwang — paggalang sa kabataang tao na hindi dapat ikabuwis ng buhay ang unang pagkakamali.`,
      111: `Bawat disiplinang karapat-dapat pag-aralan ay natutuhan ng isang tao bago pa man ito nakilala. Ibinabalik ng Atlantis Accords ang sinaunang karunungang ito sa gitna ng kung paano inihahanda ang kabataan — at ang sinumang mamamayang sumapi — upang bumuo ng hinaharap. Walang mahalagang bagay na unang natututuhan sa buháy na kagamitan, sa tunay na tao, o sa mga kalagayang hindi na maibabalik pa; walang pahintulot ng pamahalaan o basbas ng employer na kinakailangan. Bawat kalahok ay nagpapraktis sa simulasyon hanggang ang praktis ay maging kakayahan, pagkatapos ay kahandaan. Dinadaanan ng modelong pag-ikot ang bawat kalahok sa tatlong rehiyong nagtatag, at bawat pag-ikot ay nagtatapos sa isang pampublikong pagdiriwang na bukas sa pamayanang naghain nito. Ito ay paggalang sa kabataang tao na hindi dapat ikabuwis ng buhay ang unang pagkakamali.`,
      333: `Bawat disiplinang karapat-dapat pag-aralan ay natutuhan ng isang tao bago pa man ito nakilala. Nagpapraktis ang mga dalubhasa bago sila magtanghal, ang mga piloto bago lumipad, ang mga manggagamot bago mag-opera, ang mga bata sa pamamagitan ng paglalaro. Ibinabalik ng Atlantis Accords ang sinaunang karunungang ito sa gitna ng kung paano inihahanda ang kabataan — at ang sinumang mamamayang sumapi, walang pahintulot ng pamahalaan o basbas ng employer na kinakailangan — upang bumuo ng hinaharap. Walang mahalagang bagay na unang natututuhan sa buháy na kagamitan, sa tunay na tao, o sa mga kalagayang hindi na maibabalik pa. Bawat kalahok ay nagpapraktis sa simulasyon hanggang ang praktis ay maging kakayahan, pagkatapos ay kahandaan. Hindi ito pag-iingat lamang — ito ay paggalang sa kabataang tao na hindi dapat ikabuwis ng sinumang buhay ang kanyang unang pagkakamali.

Dinadaanan ng modelong pag-ikot ng kasunduan ang bawat kalahok sa tatlong rehiyong nagtatag. Ang natutuhan sa Cambodia ay pinapahusay sa Honduras at natatapos sa Austin. Ang natutuklasan sa Austin ay tinatanong sa Cambodia at isinasama sa Honduras. Bawat kalahok ay namumuhay, natututo, at pinapatnubayan sa iba't ibang kultura na kung hindi man ay malayo sa isa't isa. Ang kurikulum ng pagsasanay ay hango sa mga tradisyon ng disiplinadong simulasyon mula sa maraming kultura — mula sa tradisyon ng estratehikong edukasyon ni Sun Tzu, mula sa praktis-sa-paglalaro ni Musashi, mula sa teoryang pag-ikot-ng-pag-aaral ni Ibn Khaldun, mula sa diyalektikong monastiko ng Nalanda, mula sa sibilyang flight simulator — pinagsama upang gumalang sa bawat yugto ng pag-iisip at bawat pamanang kultural. Walang isang tradisyon lamang ang nangingibabaw.

Bawat pag-ikot ay nagtatapos sa isang pampublikong pagdiriwang na bukas sa pamayanang naghain nito, kung saan nakikita ng mga kapitbahay, pamilya, at bisita ang natutuhan ng grupo. Ginagawang naa-access at kinasisiyahan ng mga taong ito ang sopistikadong teknolohiya sa halip na katakutan — isang lipunang lumalaki habang nauunawaan ang mga sistemang kooperatiba sa pamamagitan ng paglalaro ay hindi madaling mamanipula ng takot dito. Ito ay pagpigil sa pamamagitan ng edukasyon, hindi ng puwersa. Ang pangako ng kasunduan sa bawat magulang: ang inyong anak ay magpapraktis nang isanlibong beses nang ligtas bago hawakan ang anumang bagay na maaaring makasakit sa kanila, sinasaksihan upang maaaring patunayan ng isang mamamayan — sinumang mamamayan, isang siglo mula ngayon — na eksaktong naganap ito ayon sa naitala. Ito ay paggalang sa kabataang tao na idinisenyo sa loob ng isang balangkas, at ito ang utang ng pamumuno sa susunod na mamamayang sasapi bago pa man niya hilingin ito.`,
      999: `Bawat disiplinang karapat-dapat pag-aralan ay natutuhan ng isang tao bago pa man ito nakilala, at bawat sibilisasyong nagtagal ay nagtagal dahil pinangalagaan nito ang espasyo kung saan maaaring ligtas na maganap ang pagkatutong iyon, bago pa man hilingin dito na maging mahalaga. Nagpapraktis ang mga dalubhasa bago sila magtanghal, ang mga piloto ay nagpapraktis bago lumipad, ang mga manggagamot ay nagpapraktis bago mag-opera, at ang mga bata ay nagpapraktis sa daigdig sa pamamagitan ng paglalaro. Ibinabalik ng Atlantis Accords ang sinaunang karunungang ito sa gitna ng kung paano inihahanda ang kabataan upang bumuo ng hinaharap, at binibigyan nito ang karunungang iyon ng pangalan at mekanismo: Replay. Walang mahalagang bagay na unang natututuhan sa buháy na kagamitan, sa tunay na tao, o sa mga kalagayang hindi na maibabalik pa. Bawat kalahok ay nagpapraktis sa simulasyon hanggang ang praktis ay maging kakayahan, pagkatapos ay kahandaan, at bawat oras ng praktis na iyon ay itinatala upang maaaring maibalik sa hinaharap, masuri sa hinaharap, mapagkatiwalaan sa hinaharap. Hindi ito pag-iingat lamang — ito ay paggalang sa kabataang tao na hindi dapat ikabuwis ng sinumang buhay ang kanyang unang pagkakamali, at paggalang sa talaan na mabubuhay nang higit pa sa pagkakamaling iyon sa alinmang paraan.

Dinadaanan ng modelong pag-ikot ng kasunduan ang bawat kalahok sa tatlong rehiyong nagtatag. Ang natutuhan sa Cambodia ay pinapahusay sa Honduras at natatapos sa Austin. Ang natutuklasan sa Austin ay tinatanong sa Cambodia at isinasama sa Honduras. Bawat kalahok ay namumuhay, natututo, at pinapatnubayan sa mga kulturang kung hindi man ay mananatiling malayo, at bawat pag-ikot ay nagsisimula sa paraang nagsisimula ito para sa bawat institusyong pantao na karapat-dapat pagkatiwalaan: sa isang Seed. Ang Seed ay isang minsanang pagiging kasapi, nagkakahalaga ng ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod, hindi maililipat, walang dalang anumang pagmamay-aring pang-ekonomiya. Hindi ito bayad para sa pagkakataon. Isa itong hangganan — sapat na maliit upang walang kalahok na maiwan dahil sa pera, sapat na sinasadya upang ang pagsapi ay pinili, hindi napadpad lamang. Mula sa hangganang iyon pasulong, ang bawat kalahok ay kabilang sa pag-ikot, at ang pag-ikot ay hindi pag-aari ng isang rehiyon lamang.

Ang kurikulum ng pagsasanay ay hango sa mga tradisyon ng disiplinadong simulasyon mula sa maraming kultura — mula sa tradisyon ng estratehikong edukasyon ni Sun Tzu, mula sa praktis-sa-paglalaro ni Musashi, mula sa teoryang pag-ikot-ng-pag-aaral ni Ibn Khaldun, mula sa diyalektikong monastiko ng Nalanda, mula sa sibilyang flight simulator — pinagsama upang gumalang sa bawat yugto ng pag-iisip at bawat pamanang kultural. Walang isang tradisyon lamang ang nangingibabaw. At sa loob ng kurikulum na ito, iginuguhit ng kasunduan ang isang linya na natututuhan ng bawat kalahok nang maaga at hindi na kailanman nalilimutan: ang simulasyon ay kung saan nauunawaan ang Qualified Innovation Score, hindi kung saan ito ginagastos. Ang QIS ay pagsukat, hindi kailanman bayad, at hindi kailanman pagmamay-ari — umiiral ito upang ilarawan kung gaano kahusay nangangatwiran, nananatiling matatag, at naglilingkod sa rehiyong inaangkin nitong pinaglilingkuran ang isang panukala. Ang paglago ng QIS ay maaaring magtakda ng laki ng pondo ng gantimpala matapos ang tunay na kwalipikasyon, ngunit walang nililikhang anuman ang QIS mismo. Maaaring makapagsagawa ang isang kalahok ng isandaang walang-mintis na simulasyon at magkaroon ng tumataas na iskor nang hindi nagagalaw kahit isang oras ng 웃 sa kanyang talaan, dahil ang 웃 ay lumalabas lamang sa sinaksihang gawaing isinagawa sa ilalim ng isang nakalimitahang gawain na aprubadong may budget. Bago ang pag-apruba na iyon, ang lahat — gaano man kahusay, gaano man kaangkin — ay pagpaplano pa lamang. Itinuturo ito ng kasunduan sa unang araw upang walang kabataang malito sa pagitan ng praktis at gantimpala, at walang kabataang mailigaw tungkol sa kung para saan ang simulasyon.

Ang parehong disiplina ang namamahala sa dami ng kalayaan na pinahihintulutang gamitin ng anumang sistema, tao man o artipisyal, sa loob ng pag-ikot. Ang mga modo ng operasyon ng kasunduan ay dumadaloy nang magkasunod — Manual, pagkatapos ay Semi-Automated, pagkatapos ay Autonomous — at walang cube na sumusulong ng modo hangga't hindi nito nalalampasan ang panuntunang 11.1 porsyento na nasukat na pagpapabuti, isang bahagi sa siyam, napatunayan laban sa isang naka-freeze na baseline at sinaksihan, hindi lamang inaangkin. Ang simulasyon ay kung saan itinatayo ang patunay na iyon. Kinikita ng isang kasangkapan ang karapatang kumilos nang may mas kaunting pagbabantay sa parehong paraang kinikita ng isang kalahok ang karapatan sa mas malaking responsibilidad: sa pamamagitan ng napatunayan, naitala, maibabalik na pagpapabuti, cube por cube, hindi lahat nang sabay-sabay, at hindi kailanman sa itaas ng antas kung saan pinagdedesisyunan ang kahulugan, salapi, at batas. Ang antas na iyon ay pag-aari lamang ng Human Authority, sa simulasyon man o sa buháy na operasyon, dahil ang isang espasyo ng praktis na nagtuturo ng maling hangganan ay nagtuturo ng maling aral nang tuluyan.

Bawat pag-ikot ay nagtatapos sa isang pampublikong at kooperatibang pagdiriwang na bukas sa pamayanang naghain nito. Nagtitipon ang mga kapitbahay, pamilya, at bisita upang makita ang natutuhan ng grupo, at ang kanilang nasasaksihan ay hindi isang pagpapakita ng bilis para sa sarili nito kundi isang pagpapakita ng ◬ — ang sinukat na delta sa pagitan ng isang naka-freeze na baseline at kung ano talaga ang nakamit ng disiplinadong praktis, iniharap nang tapat, hindi kailanman inayos bilang sukatan ng tubo, hindi kailanman inilahad na higit pa sa kung ano talaga ito. Ginagawang naa-access at kinasisiyahan ng mga pangyayaring ito ang sopistikadong teknolohiya sa halip na katakutan. Isang lipunang lumalaki habang nauunawaan ang mga sistemang kooperatiba sa pamamagitan ng paglalaro ay hindi madaling mamanipula ng takot sa mga sistemang iyon. Ito ay pagpigil sa pamamagitan ng edukasyon, hindi pagpigil sa pamamagitan ng puwersa, at gumagana ito dahil hindi hinihiling sa pamayanan na paniwalaan ang isang paghahabol — inaanyayahan itong panoorin ang Replay.

Ang pangako ng kasunduan sa bawat magulang ay lumalampas sa kaligtasan tungo sa pananatili: ang inyong anak ay magpapraktis nang isanlibong beses bago hawakan ang anumang bagay na maaaring makasakit sa kanila, sasaksihan ng pamayanan ang kanilang paglaki sa buong panahon, at wala sa lahat ng ito ang mawawala sa panahon. Ang Measurement of Time ay nagtatala ng tunay na mga minuto nang hiwalay sa bawat ibang talaan na pinananatili ng kasunduan, upang ang mga oras ng praktis at ang mga oras na sinaksihan ay hindi kailanman malilito sa isa't isa, at upang ang tunay na kasaysayan ng pag-unlad ng isang kalahok — hindi buod, hindi tantiya, kundi ang mismong maibabalik na talaan — ay manatiling magagamit sa kalahok na iyon hangga't nais niyang sangguniin ito. Isang magulang sa Phnom Penh, isang tagapagpayo sa Tegucigalpa, isang auditor sa Austin, o isang apo na nagbabasa ng talaan isang siglo mula ngayon ay maaaring maabot ang parehong Replay at makita ang parehong katotohanan.

Ito ang hitsura ng paggalang sa kabataang tao kapag idinisenyo ito sa loob ng isang balangkas sa halip na basta ipinangako lamang, at ito ang ipinagkakaloob ng pamumuno sa susunod na henerasyon ng mga kalahok bago pa man hilingin ito ng henerasyong iyon: isang espasyo ng praktis na sapat na malawak upang ligtas na mabigo, sapat na tapat upang tapat na maitala, at sapat na disiplinado upang panatilihin ang gantimpala, kalayaan, at awtoridad nang eksakto kung saan kinita ito ng kahusayan — hindi kailanman nauuna dito, at hindi kailanman nahuhuli.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Kaligtasan Pinatunayan Bago Ipagkaloob ang Tiwala`,
    content: {
      7: `Kaligtasan pinatunayan muna, saka tiwala.`,
      33: `Bawat pasilidad at pag-ikot ay nasa loob ng isang protektadong balot na may maagang babala. Tumatanggi ang kagamitan sa paggawang sandata — mapapatunayan, hindi lamang ipinangako, masusuri ng mga mamamayan. Ang mga talaan ay nakaligtas sa gulo. Idinisenyo ang kaligtasan sa palibot ng pinakabatang kalahok, araw-araw.`,
      111: `Bago maipagkatiwala, dapat mapatunayan ang kaligtasan — hindi sa isang pamahalaan, kundi sa sinumang mamamayang susuri nito. Ang Atlantis Accords ay isang kasunduan sa hanay ng mga mamamayan ng daigdig; ito ang pangunahing pangako nito: bawat pasilidad ng kasunduan, bawat ruta ng pag-ikot, bawat lugar kung saan natutulog o nag-aaral ang isang batang kalahok ay nasa loob ng isang nakadokumentong protektadong balot na may kakayahang magbigay ng maagang babala na nagbibigay sa pamayanan ng oras, hindi minuto, upang tumugon sa anumang kapani-paniwalang panganib. Bawat kagamitan, bawat sensor, bawat sistema ng koordinasyon ay nakatali sa antas ng hardware upang tumanggi sa muling paggamit para sa integrasyon ng sistemang-sandata. Hindi ito patakaran — ito ay pisika. Nananatiling marangal ang kasunduan sa kabila ng gulo, dahil bawat plano ay inuuna ang dignidad ng tao.`,
      333: `Bago maipagkatiwala, dapat mapatunayan ang kaligtasan — mapatunayan sa mga mamamayan, hindi ipahayag lamang. Ang Atlantis Accords ay isang kasunduan sa hanay ng mga mamamayan ng daigdig: sinumang tao, saanman, ay maaaring tumulong na hawakan ito, anuman ang pinirmahan ng kanilang pamahalaan. Bawat pasilidad ng kasunduan, bawat ruta ng pag-ikot, bawat lugar kung saan natutulog o nag-aaral ang isang batang kalahok ay nasa loob ng isang nakadokumentong protektadong balot na may kakayahang magbigay ng maagang babala na nagbibigay sa pamayanan ng oras, hindi minuto, upang tumugon sa anumang kapani-paniwalang panganib. Ang teknolohiyang nagpoprotekta sa kanila ay ang parehong teknolohiyang itinuturo ng kasunduan sa kanilang buuin. Natutuhan ng mga kabataan ang kaligtasan mula sa loob patungong labas, hindi sa pamamagitan ng pagsasabi sa kanila na sila ay ligtas, kundi sa pamamagitan ng pagkikita nito na idinisenyo sa kanilang paligid araw-araw, at pagkaalam na maaaring patunayan ng sinumang mamamayan ang talaan sa pamamagitan ng Replay.

Gumagawa ang kasunduan ng isang hindi masisirang pangako tungkol sa kung ano ang hindi maaaring maging teknolohiya nito. Bawat kagamitan, bawat sensor, bawat sistema ng koordinasyon ay nakatali sa antas ng hardware upang tumanggi sa muling paggamit para sa integrasyon ng sistemang-sandata. Hindi ito wika ng patakaran, hindi hangarin. Ito ay isang pisikal na imposibilidad, ipinapatupad nang kriptograpiko, pinatunayan ng bawat rehiyong pumirma, at masusuri ng bawat mamamayang nagpopondo nito. Ang mga kasangkapang nagpoprotekta sa isang bata sa Phnom Penh ay hindi maaaring gamitin muli upang saktan ang isang bata sa Austin. Ang mga kasangkapang nag-uugnay sa isang ehersisyo ng swarm sa Tegucigalpa ay hindi maaaring i-configure muli upang tumira sa sinumang tao. Ito ang sagot ng kasunduan sa isang siglo ng takot sa dual-use. Hindi patakaran — pisika.

Nananatiling marangal ang kasunduan sa kabila ng gulo. Kung mawawalan ng katatagang pampulitika ang isang rehiyon, ang mga kalahok ay hahawakan ng natitirang mga rehiyon. Kung uurong ang pondo, ang mga stipendiyo ang unang pinoprotektahan — pinopondohan buwan-buwan ng mga mamamayan, hindi kailanman isang daluyan ng tulong, bawat piso ay masusubaybayan. Kung salakayin ang mga digital na talaan, ang mga offline na backup ang mananatili. Kung maging imposible ang paglalakbay, ang substrate ay magpapatuloy nang virtual. Bawat plano ay inuuna ang dignidad ng tao — Human Authority sa kahulugan, salapi, at batas — bilang unang hadlang sa disenyo nito. Ang mga pinunong pumipirma sa kasunduang ito ay nangangakong ang kaligtasan ay idinisenyo, hindi basta ipinapalagay: ang proteksyong hihilingin ng anumang pinuno para sa sarili nilang anak, ngayo'y ipinagkakaloob sa bawat mamamayang tumutulong na hawakan ito.`,
      999: `Bago maipagkatiwala, dapat mapatunayan ang kaligtasan — ito ang pangunahing pangako ng Atlantis Accords, at pinapatunayan ito sa parehong paraan kung paano pinapatunayan ang bawat ibang paghahabol sa loob ng Vision 2525: hindi sa pamamagitan ng pagpapahayag, kundi sa katibayang maaaring suriin ng mga mamamayan. Bawat pasilidad ng kasunduan, bawat ruta ng pag-ikot, bawat lugar kung saan natutulog o nag-aaral ang isang batang kalahok ay nasa loob ng isang nakadokumentong protektadong balot na may kakayahang magbigay ng maagang babala na nagbibigay sa pamayanan ng oras, hindi minuto, upang tumugon sa anumang kapani-paniwalang panganib. Ang teknolohiyang ginagamit upang protektahan ang mga kalahok ay ang parehong teknolohiyang itinuturo ng kasunduan sa kanilang buuin — mga sensor, koordinasyon, kakayahang mabuhay ng komunikasyon, ipinamamahaging katalinuhan. Natutuhan ng mga kabataan ang kaligtasan mula sa loob patungong labas, sa sarili nilang wika at sa sarili nilang rehiyon, hindi sa pamamagitan ng pagsasabi sa kanila na sila ay ligtas, kundi sa pamamagitan ng panonood, oras-oras, kung paano idinisenyo ang kaligtasan sa kanilang paligid araw-araw.

Ang panonood na iyon ay hindi iniiwan sa alaala o sa tiwala sa salita ng isang tagapagpadaloy. Ang Measurement of Time ay nagtatala ng tunay na mga minuto ng bawat pagsasanay, bawat pag-ikot, bawat ehersisyo ng pagtugon — hiwalay sa anumang paghahabol ng pag-unlad, hiwalay sa anumang kuwentong isinalaysay sa araw na iyon. Ginagawa ng Replay ang bawat paglalabas ng kurikulum ng pagsasanay, bawat pagbabago sa kaligtasan, bawat rebisyon ng hardware na lubos na maibabalik, upang ang isang magulang sa Tegucigalpa o isang regulator sa Phnom Penh ay makapaglakad pabalik sa eksaktong kung ano ang nagbago, kailan ito nagbago, at bakit ito nagbago. Ang isang protektadong balot na hindi maibabalik ay isang pangako lamang. Ang isang protektadong balot na maibabalik, minuto-minutong itinala, ay isang patunay. Pinipili ng kasunduan ang patunay.

Gumagawa ang kasunduan ng isang hindi masisirang pangako tungkol sa kung ano ang hindi maaaring maging teknolohiya nito. Bawat kagamitan, bawat sensor, bawat sistema ng koordinasyon ay nakatali sa antas ng hardware upang tumanggi sa muling paggamit para sa integrasyon ng sistemang-sandata. Hindi ito wika ng patakaran, hindi hangarin. Ito ay isang pisikal na imposibilidad, ipinapatupad nang kriptograpiko, pinatunayan ng bawat rehiyong pumirma, at masusuri ng bawat mamamayan. Ang mga kasangkapang nagpoprotekta sa isang bata sa Phnom Penh ay hindi maaaring gamitin muli upang saktan ang isang bata sa Austin. Ang mga kasangkapang nag-uugnay sa isang ehersisyo ng swarm sa Tegucigalpa ay hindi maaaring i-configure muli upang tumira sa sinumang tao. Ito ang sagot ng kasunduan sa isang siglo ng takot sa dual-use. Hindi patakaran — pisika.

Ang kaligtasang napatunayan nang minsan ay hindi kaligtasang pinananatili sa loob ng limandaang-taong abot-tanaw. Pinangalanan ng kasunduan ang ikalawang pangako nito na Continuity Without Evasion: legal na portabilidad sa bawat hurisdiksyong nadadaanan ng kasunduan, na walang isang solong mapapalitang pamahalaan, bangko, tagapagtatag, o modelong nakatayo sa pagitan ng isang kalahok at ng kanilang proteksyon. Bawat hurisdiksyon ay pinaglilingkuran ng sarili nitong adapter, sumasara kapag nabigo at tumatanggi bilang default, upang ang isang laban na desisyon sa isang rehiyon ay magsasara lamang ng isang daan doon — hindi kailanman ang buong balangkas, hindi kailanman ang bawat rehiyon, hindi kailanman ang bawat kalahok sa lahat ng dako nang sabay-sabay. Ang desisyon ng isang hukuman sa isang teritoryong pumirma ay hindi maaaring pumatay sa protektadong balot ng isang kalahok sa ibang lugar. Ito ang kahulugan ng pagbuo ng isang sistemang nakaliligtas sa ordinaryong gulo ng batas, pulitika, at pagbabagong institusyonal nang hindi kailanman hinihiling sa isang kalahok na iwasan ang batas upang manatiling protektado.

Bawat antas ng arkitekturang protektado na ito ay sumasagot, sa huli, sa Human Authority. Ang kahulugan, salapi, at batas ay hindi kailanman ipinagkakatiwala sa mga makina — ang antas na soberanong nagpapasya kung ano ang hinihingi ng kaligtasan, kung ano ang binibilang na kapani-paniwalang panganib, at kung anong tugon ang utang ng isang pamayanan sa kanyang pinakabatang miyembro ay nananatiling sarado sa artipisyal na katalinuhan, anuman ang kanyang kakayahan sa hinaharap. Ang mga sistema ng kasunduan ay dumadaloy lamang sa tatlong modo ng operasyon — Manual, Semi-Automated, Autonomous — at walang sistemang sumusulong ng modo nang wala ang isang sinaksihan, sinukat na pagpapabuti ng hindi bababa sa isang bahagi sa siyam, 11.1 porsyento, napatunayan, mareprodyus. Kinikita ang kalayaan, cube por cube, tungkulin por tungkulin, hindi kailanman ipinagkakaloob nang buo, at hindi kailanman ipinagkakaloob sa mga tanong na nagtatakda ng kahulugan, salapi, o batas. Maaaring matuto ang isang sensor na mas mabilis na makakita. Maaaring matuto ang isang sistema ng koordinasyon na mas mahusay na magbigay-daan. Ngunit hindi kailanman pinahihintulutan ang alinman sa kanila na magpasya, nang mag-isa, kung ano ang dapat ipagkatiwala ng isang pamayanan sa kanyang mga anak.

Ang kasunduan ay idinisenyong manatiling marangal sa kabila ng gulo, at pinangalanan nito ang gulo nang maaga sa halip na matuklasan ito sa panahon ng krisis. Kung mawawalan ng katatagang pampulitika ang isang rehiyong pumirma, ang mga kalahok ay hahawakan ng natitirang mga rehiyon. Kung uurong ang pondo, ang mga stipendiyo ng kalahok ang unang pinoprotektahan, bago ang administrasyon at imprastraktura. Kung salakayin ang mga digital na talaan, ang mga offline na backup ang mananatili, hindi maaabot ng anumang kabiguang umabot sa network. Kung maging imposible ang paglalakbay, ang substrate ay magpapatuloy nang virtual, upang hindi humihinto ang isang pag-ikot dahil lang nagsara ang isang hangganan. Bawat sitwasyon ay pinaplano, at bawat plano ay inuuna ang dignidad ng tao bilang unang hadlang sa disenyo — hindi ang huling isinasaalang-alang kapag naayos na ang badyet at hitsura.

Ang pagpasok sa napatunayang sistemang ito ay nagsisimula sa Seed — isang minsanang pagiging kasapi, nagkakahalaga ng ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod, hindi maililipat, at walang dalang anumang pagmamay-aring pang-ekonomiya sa kahit anong ibuo pa ng kasunduan pagkatapos. Ang Seed ay hindi bumibili ng kaligtasan; ang kaligtasan ay idinisenyo nang matagal bago pa itanim ang anumang Seed. Ang binibili ng Seed ay katayuan — ang karapatang pumasok sa isang balangkas na napatunayan na, nasuri na, nakatali na sa hardware na hindi maaaring gamitin laban sa mismong taong ipinagtatanggol nito. Sinasadya ang paghihiwalay na ito. Ang isang pangako sa kaligtasan na kailangang bilhin sa tunay na bigat pang-ekonomiya ay hindi isang pangako sa kaligtasan, produkto lamang ito ng kaligtasan. Pinananatili ng kasunduan ang dalawa nang ganap na hiwalay, upang walang pamilyang kailangang timbangin ang proteksyon ng kanilang anak laban sa buwanang badyet ng kanilang sambahayan.

Ang mga pinunong pumipirma sa kasunduang ito ay pumipirma ng isang pangakong ang kaligtasan ay idinisenyo, hindi basta ipinapalagay, at pinatunayan, hindi ipinahayag lamang. Ang ipinagkakaloob nila sa kanilang mga mamamayan ay hindi lamang pagkakataon, kundi proteksyong itinayo sa pamantayang karapat-dapat sa pinakabatang kalahok — itinala ng Measurement of Time, maibabalik sa pamamagitan ng Replay, nakatali sa antas ng hardware laban sa bawat maling paggamit na naisip ng isang siglong puno ng takot, at sumasagot, palagi at tanging, sa Human Authority. Ito ang parehong proteksyong hihilingin ng anumang pinuno para sa sarili nilang anak na tumatawid mag-isa sa hindi pamilyar na hangganan, ngayo'y ipinagkakaloob sa bawat batang paglilingkuran ng kasunduan, sa buong tatlong rehiyong nagtatag nito na Cambodia, Honduras, at Austin, at sa buong limang siglong nilalayon ng kasunduang panatilihin ang pangakong ito.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Kabayaran, Kagalingan, at Dignidad ng Tao`,
    content: {
      7: `Isang estipendyo, isang mentor, isang tahanan.`,
      33: `Bawat mamamayan ay tumatanggap ng stipendiyo mula sa unang araw — walang pahintulot ng pamahalaan, walang basbas ng employer. Ang pag-ibig, pagkawala, at kaligtasan ay imprastraktura. Sinusukat ang tagumpay sa pinakamahina. Ang dignidad ay substrate, hindi palamuti.`,
      111: `Tinuturing ng Atlantis Accords ang bawat kalahok bilang isang tao mula sa unang araw — isang mamamayang sumapi ayon sa karapatan, hindi sa utos ng pamahalaan o pahintulot ng employer. Isang stipendiyo ang ibinibigay mula sa sandaling magsimula ang pakikilahok, isinasaalang-alang ang gastusin sa pamumuhay ng rehiyon, at bawat sinaksihang oras ay kumikita ng 웃, ibinabayad sa tao sa pamamagitan ng Livelihood Direct, hindi kailanman sa pamamagitan ng talaan ng isang employer. Ang kagalingan ay tinuturing na unang-uring imprastraktura — hindi isang benepisyo lamang, kundi ang substrate kung saan nakatayo ang lahat. Tatlong larangan ang sinusuportahan: Pag-ibig, Pagkawala, at Kaligtasan. Sinusukat ng kasunduan ang tagumpay batay sa pinakamahinang kalahok, hindi sa katamtaman. Walang nakakalimutan upang gumanda lang ang katamtaman. Dignidad bilang substrate, hindi palamuti.`,
      333: `Tinuturing ng Atlantis Accords ang bawat kalahok bilang isang tao mula sa unang araw — isang mamamayang kabilang ayon sa karapatan, hindi nangangailangan ng pahintulot ng pamahalaan o basbas ng employer. Isang stipendiyo ang ibinibigay mula sa sandaling magsimula ang pakikilahok, isinasaalang-alang ang gastusin sa pamumuhay ng rehiyon, dumarating bago pa maging emerhensiya ang mga tungkuling pampamilya. Hindi ito kawanggawa. Ito ay pagkilala na ang ordinaryong pagbabagong pantao ay nangangailangan muna ng seguridad ng tao — hindi maaaring umunlad ang isang isipan habang nasa panganib ang kanyang sambahayan.

Ang kinikita nang higit sa stipendiyo ay kinikita tulad ng pagkita ng isang mamamayan: sa pamamagitan ng Seed, na nagkakahalaga ng ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod, at sa pamamagitan ng 웃, na ibinabayad lamang para sa mga sinaksihang oras. Sinusukat ng QIS ang pangako ngunit walang nililikhang anuman — pagsukat, hindi kailanman bayad. Bawat bayad ay umaabot sa kalahok sa pamamagitan ng Livelihood Direct, mga lisensyadong lokal na daan na hindi kailanman inaari ng kasunduan, itinayo para sa Continuity Without Evasion.

Ang kagalingan ay tinuturing na unang-uring imprastraktura — hindi isang benepisyo lamang, kundi ang substrate kung saan nakatayo ang lahat. Pinangalanan ng kasunduan ang tatlong larangang sinusuportahan ang bawat kalahok: Pag-ibig, ang koneksyon at malusog na hangganan; Pagkawala, dahil ang pagdadalamhati ay kailangang samahan, hindi lampasan; at Kaligtasan, ang pagkaalam kung sino ang tatawagan, sa bawat rehiyon, sa sariling wika. Ibinibigay ang pagpapayo, mga grupong bilog, at mga kagawiang kultural o espirituwal na iginagalang ayon sa tradisyon. Zero na sapilitang ideolohiya; ang Human Authority, hindi kailanman ang isang makina, ang nagpapasya kung anong pag-aaruga ang kailangan ng isang mamamayan.

Sinusukat ng kasunduan ang tagumpay batay sa pinakamahinang kalahok, hindi sa katamtaman. Ang mga mamamayang rural na walang mataas na bandwidth ay pinaglilingkuran. Ang mga kalahok na neurodivergent ay tumatanggap ng akomodasyon bilang pamantayan. Ang mga kalahok na may kapansanan ay nakikitang naaabot ang bawat pasilidad. Ang mga kalahok na may pagkakaiba-iba sa kasarian ay tumatanggap ng ligtas na tirahan at pagpapares ng tagapagpayo. Ang mga hindi katutubong nagsasalita ay natagpuan ang bawat materyal sa kanilang wika. Ang mga katutubong kalahok ay natagpuan ang kanilang mga kagawiang kultural na iginagalang at ang kanilang tradisyonal na kaalaman na protektado. Ang mga pinunong pumipirma sa kasunduang ito ay nangangako na walang mamamayang makakalimutan lamang upang gumanda ang katamtaman. Ito ay dignidad bilang substrate, hindi palamuti. Ang sinusukat ay ang iginagalang, at ang iginagalang dito ay ang kabuuang tao — isipan, katawan, at diwa, hinahawakan ng kapwa mamamayan, nang walang exception.`,
      999: `Tinuturing ng Atlantis Accords ang bawat kalahok bilang isang buong tao mula sa unang araw, isinama sa mekanismo, hindi lamang sa mga salita. Isang stipendiyo ang ibinibigay mula sa sandaling magsimula ang pakikilahok, isinasaalang-alang ang gastusin sa pamumuhay ng rehiyon upang igalang ng epekto nito ang lokal na dignidad ng gawain. Ang stipendiyo ay dumarating bago pa maging emerhensiya ang mga tungkuling pampamilya, at bago pa makompromiso ang dignidad. Nagpapahiwatig ito sa bawat kabataan na ang kanilang panahon ay mahalaga, ang kanilang ambag ay inaasahan, at ang katatagan ng kanilang pamilya ay bahagi ng responsibilidad ng kasunduan. Hindi ito kawanggawa. Ito ay pagkilala na ang ordinaryong pagbabagong pantao ay nangangailangan muna ng seguridad ng tao. Hindi maaaring umunlad ang isang isipan habang nasa panganib ang kanyang sambahayan. Ang pagsapi mismo ay may dalang maliit, sinasadyang hangganan: ang Seed, isang minsanang pagiging kasapi na nagkakahalaga ng ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod, hindi maililipat at walang dalang anumang sariling pagmamay-aring pang-ekonomiya. Sinasabi lamang ng Seed na sumapi ang isang tao; hindi nito sila binabayaran o nangangako ng anumang bagay lampas sa pintong binubuksan nito.

Ang kinikita matapos bumukas ang pintong iyon ay pinangangasiwaan ng parehong katumpakan na dala ng kasunduan sa bawat ibang pangako nito. Ang 웃, ang sukatan ng kasunduan sa Human Intelligence, ay kinakalkula nang simple — isang oras sa lokal na pinakamababang sahod, pinarami ng Multiple na sumasalamin sa hirap at halaga ng gawain, ipinarami sa mga oras na aktwal na nagtrabaho. Ngunit ang 웃 ay lumalabas lamang sa sinaksihang gawaing isinagawa sa ilalim ng isang nakalimitahang gawain na aprubadong may budget. Bago umiral ang pag-apruba na iyon, ang ginagawa ng isang kalahok ay pagpaplano, hindi pagkita — isang pagkakaibang matatag na pinananatili ng kasunduan dahil pinoprotektahan nito kapwa ang ingatang-yaman at ang kalahok mula sa mga pangakong ginawa nang mas mabilis kaysa sa pagpapatunay ng halaga. Ang Measurement of Time, MoT, ay nagtatala ng tunay na mga minutong nagtrabaho nang hiwalay sa anumang kalkulasyon ng kabayaran, upang manatiling isang tapat, masusuring katotohanan ang panahon, hiwalay sa bayad. Walang oras ng anumang kalahok ang pinalalaki, at walang oras ng anumang kalahok ang nawawala. Isang hangganan ng pag-aayos na 9,999 웃 bawat taon ang inilalapat sa bawat kalahok, na ang anumang labis ay idinadala sa susunod na taon sa halip na mawala, upang ang natatanging ambag ay kinikilala sa maraming taon sa halip na malimitahan sa kawalang-kakita sa loob ng isang taon.

Sinasadyang pinananatiling hiwalay ang kabayaran mula sa pagsukat ng pagbabago. Ang Qualified Innovation Score, QIS, ay kumakatamtaman ng Kita, Kabuuang Tubo, Kita sa Operasyon, at Epektibong gastos sa R&D upang ilarawan kung gaano talaga lumago ang pagbabago. Ang paglago nito sa paglipas ng panahon ay maaaring magtakda ng laki ng pondo ng gantimpala kapag natugunan na ang kwalipikasyon, ngunit ang QIS mismo ay walang nililikhang 웃 at walang direktang inaayos — ito ay pagsukat, hindi kailanman bayad, at hindi kailanman ipinagkakamaling pagmamay-ari ng anumang naitayo. Mahalaga ang paghihiwalay na ito dahil pinananatili nitong tapat ang stipendiyo at ang sahod: ang isang kalahok ay binabayaran para sa sinaksihang oras ng tunay na gawain, hindi para sa isang iskor na maaaring i-manipula, palakihin, o pagtalunan. Ang ♡, Shared Intention, ay nagdadala ng dahilan sa likod ng bawat gawaing tinatanggap ng isang kalahok; ang ◬, ang sinaksihang pagbilis na naidudulot ng isang gawain laban sa isang naka-freeze na baseline, ay itinatala bilang delta lamang, hindi kailanman inaayos bilang sukatan ng tubo na nakakabit sa paggawa ng sinumang tao. Nananatiling kung ano ito ang kabayaran: isang tapat na sahod para sa tapat, sinaksihang panahon.

Hindi natatapos sa kalkulasyon ang halaga — dapat din itong umabot sa kalahok bilang isang buháy na tao, at dito gumagana ang 🏠, Livelihood Direct. Bawat yunit ng halagang kinikita ng isang kalahok ay umaabot sa kanila sa pamamagitan ng mga kwalipikado, lisensyadong lokal na daan — mga bangko, mga operator ng mobile-money, mga kooperatiba na pinagkakatiwalaan at regulado na sa rehiyong iyon — hindi kailanman sa pamamagitan ng isang pondong inaari o kinokontrol ng kasunduan mismo. Ang klasipikasyon ng katayuan ng isang kalahok ay nauuna sa anumang pag-aayos; wala nang binabayaran bago malinaw na maunawaan kung sino ang binabayaran at para saan. At ang pagkilala sa talento, gaano man ito kinasisiyahan, ay hindi nagbabantay sa isang higaan, isang pagkain, o isang puwesto sa grupo — ang tunay na tungkulin lamang ng isang kalahok ang nagbabantay dito. Ito ay sinasadyang pagtanggi na hayaang palitan ng prestihiyo ang probisyon. Isang matalinong kalahok at isang tahimik na kalahok ay natutulog sa ilalim ng parehong protektadong bubong, sa parehong mga tuntunin, dahil ang mga pangako ng dignidad ng kasunduan ay hindi isang gantimpala para sa kahusayan — ito ay isang sahig sa ilalim ng lahat.

Ang kagalingan ay tinuturing na unang-uring imprastraktura — hindi isang opsyonal na benepisyo, hindi isang benepisyong pangkagalingan, kundi ang substrate kung saan nakatayo ang lahat ng iba pa. Pinangalanan ng kasunduan ang tatlong pundasyong larangang sinusuportahan ang bawat kalahok: Pag-ibig, sa diwa ng koneksyon, pagkakabit, at malusog na hangganan; Pagkawala, dahil bawat kalahok ay makakaranas ng pagdadalamhati at kailangang samahan, hindi lampasan; at Kaligtasan, sa diwa na alam ng bawat kalahok kung sino ang tatawagan, sa bawat rehiyon, sa kanilang sariling wika. Ang indibidwal na pagpapayo, mga grupong bilog, mga kagawiang somatiko, at mga kagawiang kultural o espirituwal na iginagalang ayon sa sariling tradisyon ng kalahok ay lahat ibinibigay. Zero na sapilitang ideolohiya. Hinahawakan ng kasunduan ang espasyo nang may paggalang; hindi ito nangangaral ng anumang sistema ng paniniwala. Ang Human Authority ang namamahala sa bawat isa sa mga desisyong ito — ang kahulugan, salapi, at batas ay nananatiling sarado sa pagpapasya ng makina, gaano man kasopistikado ang pattern-matching na tumutulong sa mga taong nagpapasya.

Sinusukat ng kasunduan ang tagumpay batay sa kinalabasan ng pinakamahinang kalahok nito, hindi sa katamtaman. Ang mga kalahok na rural na walang mataas na bandwidth ay pinaglilingkuran. Ang mga kalahok na neurodivergent ay tumatanggap ng akomodasyon bilang pamantayan. Ang mga kalahok na may kapansanan ay nakikitang naaabot ang bawat pasilidad. Ang mga kalahok na may pagkakaiba-iba sa kasarian ay tumatanggap ng ligtas na tirahan at pagpapares ng tagapagpayo. Ang mga hindi katutubong nagsasalita ay natagpuan ang bawat materyal sa kanilang wika. Ang mga katutubong kalahok ay natagpuan ang kanilang mga kagawiang kultural na iginagalang at ang kanilang tradisyonal na kaalaman na protektado. Ang mga pinunong pumipirma sa kasunduang ito ay nangangako na walang kalahok na tahimik na makakalimutan upang gumanda ang katamtaman.

Bawat daan ng bayad na inilarawan dito — ang Seed, ang stipendiyo, ang 웃 na kinikita sa sinaksihang gawain, ang daan ng Livelihood Direct na naghahatid nito — ay idinisenyo para sa Continuity Without Evasion. Walang isang bangko, pamahalaan, o lokal na operator na mapapalitan sa kabayaran ng sinumang kalahok; kung ang isang lisensyadong daan sa isang hurisdiksyon ay isinara ng isang laban na desisyon, ang daang iyon lamang ang nabibigo, hindi kailanman ang buong sistema, at hindi kailanman ang paghahabol ng kalahok sa kung ano ang utang sa kanila. Ito ay dignidad bilang substrate, hindi palamuti. Ang sinusukat ay ang iginagalang, at ang iginagalang dito ay ang kabuuang tao — isipan, katawan, at diwa na magkasama, tapat na binabayaran, lubos na protektado, at hindi nakakalimutan ng anumang accounting, nang walang exception.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Pagpopondo at Pamamahala`,
    content: {
      7: `Pinopondohan ng mamamayan ang susunod na salinlahi.`,
      33: `Ang Atlantis Accords ay isang kasunduan sa hanay ng mga mamamayan — sinuman ay maaaring magpondo at humawak dito. Walang daluyan ng tulong, walang dayuhang patron, walang kondisyong pampulitika. Bawat piso ay masusubaybayan, ang accounting ay inilalathala buwan-buwan, sa bawat wika.`,
      111: `Ang Atlantis Accords ay isang kasunduan sa hanay ng mga mamamayan ng daigdig — sinumang tao, saanman, ay maaaring tumulong na likhain ito at hawakan ito, anuman ang pinirmahan ng kanilang pamahalaan o kung sino ang kanilang employer. Ang mga pamahalaan, tagapagturo, at innovator ay pumipirma bilang tagapangalaga ng kanilang mga rehiyon; ang mga mamamayan ang direktang nagpopondo, sumasaksi, at humahawak sa kasunduan, bawat isa ay nag-aambag ng maliit na kusang-loob na halaga bawat buwan, sapat na katamtaman upang walang taong maiwan dahil sa pera. Walang daluyan ng tulong, walang dayuhang patron, walang kondisyong pampulitika na kasama dito. Nakatayo ang kasunduan nang malaya mula sa mga institusyong multilateral na humubog sa nakaraang siglo — hindi isang pahayag pampulitika, kundi isang pagpili sa disenyo. Bawat piso ay masusubaybayan; ang accounting ay inilalathala buwan-buwan, sa bawat wika.`,
      333: `Ang Atlantis Accords ay isang kasunduan sa hanay ng mga mamamayan ng daigdig — sinumang tao, saanman, ay maaaring tumulong na likhain ito at hawakan ito, anuman ang pinirmahan ng kanilang pamahalaan o kung sino ang kanilang employer. Pinopondohan ito ng mga mamamayang pinaglilingkuran nito: ang mga residente ng mga rehiyong lumalahok ay nag-aambag ng maliit na kusang-loob na halaga bawat buwan, sapat na katamtaman upang walang taong maiwan dahil sa pera, sapat na resonante upang ang kabuuan ay makapagpanatili ng gawain ng kasunduan sa malaking sukat. Kapag direktang pinondohan ng isang mamamayan ang susunod na henerasyon, direktang hinahawakan din ng mamamayang iyon ang kasunduan. Walang daluyan ng tulong, walang dayuhang patron, walang kondisyong pampulitika na kasama dito. Ang kaluluwa ng kasunduan ay ang mamamayang nag-aambag ng isang maliit na halaga bawat buwan, na ang pakikilahok ang nagpapatuloy nito.

Ang Pamahalaan, Edukasyon, at Innovation ay pumipirma bilang tagapangalaga ng kanilang mga rehiyon — tatlong makabagbag-damdaming pirma na bumubuklod sa isang rehiyon na paunlakan, protektahan, at turuan — ngunit ang pangangalaga ay hindi pagmamay-ari. Nakatayo ang kasunduan nang malaya mula sa mga institusyong multilateral na humubog sa nakaraang siglo — ang North Atlantic Treaty Organization, ang World Health Organization, ang United Nations, ang International Monetary Fund, ang World Bank, at bawat pambansang daluyan ng dayuhang tulong. Ito ay isang pagpili sa disenyo, hindi isang pahayag pampulitika: ang isang balangkas na naglilingkod sa bawat rehiyon anuman ang pagkakahanay geopolitikal ay hindi maaaring maipit sa alinmang solong pagkakahanay. Ang mga pambansang pamahalaan ay maaaring mag-ambag nang kusang-loob. Ang mga ambag ay transparente. Walang ambag ang bumibili ng impluwensya sa pamamahala, mula sa anumang pinagmulan, kailanman.

Bawat piso at bawat yunit ng halagang pumapasok sa kasunduan ay itinatala nang permanente, hayagan, at masusubaybayan — maibabalik sa pamamagitan ng Replay, upang maaaring patunayan ng isang mamamayan isang siglo mula ngayon ang buong kadena na hindi nasira. Ang halaga ay umaabot sa isang kalahok sa pamamagitan ng sinaksihang mga oras ng 웃 at lisensyadong lokal na daan, hindi kailanman isang pondong inaari ng kasunduan mismo; ang QIS ay tapat na sumusukat, hindi kailanman nagbabayad. Ang gastusin sa administrasyon ay may hangganan, kasama ang mga korporatibong regalo. Ang buong accounting ay inihahatid sa wika ng bawat rehiyong pumirma bawat buwan. Ang mga pinunong pumipirma sa kasunduan ay nangangako ng transparency na bihirang ialay ng anumang institusyon. Ito ang tiwalang kinakailangan ng kasunduan — kinikita nang isang maliit, masusubaybayang ambag sa isang pagkakataon, sa harap ng bawat mamamayan.`,
      999: `Ang Atlantis Accords mismo ay pinopondohan ng mga mamamayang pinaglilingkuran nito, at ang isang katotohanang ito ang humuhubog sa lahat ng susunod dito — bawat daan, bawat talaan, bawat pintuang dapat daanan ng isang kabataan upang makita. Ang mga ordinaryong residente ng mga rehiyong lumalahok ay nag-aambag ng maliit na kusang-loob na halaga bawat buwan, mga halagang sapat na katamtaman upang walang matandang taong maiwan dahil sa pera sa anumang rehiyong naghahain, sapat na resonante upang ang kabuuan ay makapagpanatili ng gawain ng kasunduan sa makabuluhang sukat. Sinasadya ang disenyong ito, at hindi ito paraan lamang sa misyon — ito ang patunay ng misyon. Kapag direktang pinondohan ng isang mamamayan ang edukasyon ng susunod na henerasyon, direktang hinahawakan din ng mamamayang iyon ang kasunduan, sa parehong hininga, walang tagapamagitan na maaaring pagaanin ang ulat o ipagpaliban ang pagkukwenta. Walang daluyan ng tulong, walang dayuhang patron, walang kondisyong pampulitika na kasabay ng tseke. Ang kaluluwa ng kasunduan ay ang mamamayang nag-aambag ng isang maliit na halaga bawat buwan, na ang pakikilahok ang nagpapatuloy sa lahat ng ito, at na ang patuloy na pakikilahok ang tanging boto ng tiwala na mahalaga sa huli sa loob ng limang siglo.

Sinasadyang malaya ang kasunduan mula sa mga institusyong multilateral na humubog sa nakaraang siglo — ang North Atlantic Treaty Organization, ang World Health Organization, ang United Nations, ang International Monetary Fund, ang World Bank, at bawat pambansang daluyan ng dayuhang tulong. Hindi ito isang pahayag pampulitika tungkol sa halaga ng mga institusyong iyon o ng kanilang mga ambag. Ito ay isang pagpili sa disenyo, at ito ang parehong pagpili sa disenyong namamahala sa bawat teknikal na daan sa ilalim ng kasunduan mismo: Continuity Without Evasion. Ang legal na portabilidad ang panuntunan — walang isang solong mapapalitang pamahalaan, bangko, tagapagtatag, o modelong maaaring umupo sa ilalim ng buong istruktura, dahil ang isang limandaang-taong abot-tanaw ay hindi maaaring itaya sa pananatili ng anumang solong aktor. Ang bawat hurisdiksyon ay may dalang sariling adapter, sumasara kapag nabigo at tumatanggi bilang default, upang ang isang laban na desisyon sa isang bansa ay magsara lamang ng isang daan doon at doon lamang — hindi kailanman ibinababa nito ang mga kwenta ng isang pamilya sa isang rehiyong kasinlayo ng karagatan. Ang mga pambansang pamahalaan ay maaaring mag-ambag nang kusang-loob. Ang mga ambag ay transparente. Walang ambag ang bumibili ng impluwensya sa pamamahala, mula sa anumang pinagmulan, kailanman — hindi mula sa isang pamahalaan, hindi mula sa isang korporasyon, hindi mula sa sariling mga tagapagtatag ng balangkas.

Ang Human Authority ang ikalawang haligi na tumataglay sa disenyong ito ng pagpopondo. Ang kahulugan, salapi, at batas ay nananatiling mga bagay ng tao, pinagpasyahan ng mga tao sa harap ng ibang tao; ang antas na soberano kung saan itinakda ang layunin ng kasunduan at pinamamahalaan ang mga pondo nito ay nananatiling sarado sa mga makina, gaano man kagaling ang mga makinang iyon sa mga gawaing nasa ilalim nito. Ang Measurement of Time ay nagtatala ng tunay na mga minutong nagtrabaho nang hiwalay sa anumang paghahabol tungkol sa kanilang halaga, upang walang sinuman — tao man o artipisyal — ang tahimik na makapagpalaki ng talaan. Nakatayo ang Replay sa likod ng bawat talaang iyon, ginagawang maibabalik mula sa pinagmulan ang bawat paglalabas na inilabas ng kasunduan, palaging bukas sa pagtutol, palaging bukas sa pagwawasto. Ang isang mamamayang nag-aambag ng maliit na halaga ngayon ay nagtitiwalang sa loob ng limampung taon, sa loob ng dalawang daang taon, may makakabalik pa rin sa kadena tungo sa talaan ng buwang ito at makikitang eksakto ito kung ano ito noon.

Ang pagpasok sa sistemang ito ng tiwala ay nagsisimula sa Seed — isang minsanang pagiging kasapi, nagkakahalaga ng ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod, hindi maililipat at walang dalang anumang anyo ng pagmamay-aring pang-ekonomiya. Ang Seed ay hindi bumibili ng bahagi, walang boto na tinitimbang ng kayamanan, walang pribilehiyadong katayuan sa accounting na susunod. Bumibili lamang ito ng pagkabilang, sa presyong sapat na mababa upang makapagsimula ang isang kabataan saanman umoperasyon ang kasunduan. Lahat ng kinikita ng isang miyembro pagkatapos noon ay kinikita, hindi kailanman binibili, at ang pagkakaibang ito ang buong moral na arkitektura ng kasunduan sa maliit na sukat.

Ang halagang dumadaloy talaga sa isang tao ay dumadaloy sa pamamagitan ng 🏠 Livelihood Direct — mga kwalipikado, lisensyadong lokal na daan na nagdadala ng bayad sa tao, hindi kailanman sa isang pondong inaari o kinokontrol ng balangkas mismo. Ang klasipikasyon ay nauuna sa pag-aayos sa bawat pagkakataon; ang isang higaan, isang stipendiyo, isang puwesto sa susunod na yugto ng pagsasanay ay pinipigilan ng tungkulin at kahandaan, hindi kailanman ng pagkilala lamang, dahil ang pagkilala ay mura at ang isang ikabubuhay ay hindi. Ito ang kadenang tunay na tinatahak ng buwanang ambag ng isang mamamayan: mula sa account ng mamamayan, sa pamamagitan ng isang sinuring daan, tungo sa stipendiyong tinatanggap ng isang kabataan, tungo sa proyektong pagbabago na nagiging gawain ng kabataang iyon, at pabalik-balik bilang isang pampublikong ulat na mababasa ng sinumang mamamayan.

Ang halaga ng gawaing iyon ay sinusukat, hindi basta ipinapalagay. Ang Qualified Innovation Score ay kumakatamtaman ng kahandaan, potensyal na paglago, epekto ng kinalabasan, at kahandaan sa pagpapatupad sa iisang numero, at ang paglago sa iskor na iyon ay nagtatakda ng laki ng pondo ng gantimpala lamang matapos matugunan ang kwalipikasyon — ang QIS mismo ay walang nililikhang anuman at wala nang direktang inaayos; ito ay pagsukat, hindi kailanman bayad, at hindi kailanman ipinagkakamaling pagmamay-ari dito. Ang bayad para sa gawaing pantao ay dumarating sa halip bilang 웃, na nagkakahalaga ng isang oras na pinarami ng lokal na pinakamababang sahod, ipinarami ng isang nakalimitahang, may-budget na aprubadong multiple ng mga oras na aktwal na nagtrabaho at sinaksihan. Bago magdala ng pag-apruba na iyon ang isang gawain, ang gawaing nasa likod nito ay pagpaplano, hindi mababayarang paggawa, at walang binabayaran upang magplano. Isang hangganan na 9,999 웃 bawat taon, na ang anumang labis ay idinadala sa susunod na taon sa halip na mawala, ang nagpapanatili sa account ng anumang solong taon mula sa pagiging alinman sa isang biglaang kayamanan o isang patibong.

Walang bagay dito ang tumatakbo nang mas mabilis kaysa sa sarili nitong patunay. Ang kasunduan mismo ay sumusulong mula sa Manual patungong Semi-Automated hanggang Autonomous na operasyon nang isang cube sa isang pagkakataon, at lamang kung saan aktwal na napatunayan ang buong pagkakasunod-sunod ng sinukat na pagpapabuti — isang bahagi sa siyam — hindi kailanman ipinapalagay nang maaga. Ang kalayaan ay kinikita nang eksakto doon at wala sa kalapit ng kahulugan, salapi, o batas, na nananatiling pantao palagi. May hangganan ang gastusin sa administrasyon. Ang mga korporatibo at institusyonal na regalo ay tinatanggap at may hangganan din. Ang buong accounting ay inihahatid sa wika ng bawat rehiyong pumirma bawat buwan, magsisimula sa Cambodia, Honduras, at Austin, at nilalayong patuloy pa ring ihatid, at patuloy na malinaw, limang siglo mula ngayon. Ito ang tiwalang kinakailangan ng kasunduan. Ito ang tiwalang kinikita ng kasunduan, isang maliit, masusubaybayang ambag sa isang pagkakataon, sa harap ng bawat mamamayang paglilingkuran nito magpakailanman.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Palitan ng Kultura at Ambag na Pandaigdig`,
    content: {
      7: `Bawat mag-aaral sa sariling wika.`,
      33: `Bawat aktibidad ay nasa wika ng kalahok — bukas sa sinumang mamamayan, walang pahintulot ng pamahalaan na kinakailangan. Ang Artipisyal, Pantao, at Bahaging katalinuhan ay hinahawakan sa produktibong pagbabalanse. Ang mga kurikulum ay hayagang inilalathala. Ang natutuhan ng isang rehiyon, minana ng lahat.`,
      111: `Ibinabalik ng Atlantis Accords ang edukasyon sa kanyang pinakamalalim na layunin: ang palitan ng karunungan sa kabila ng mga hangganang kung hindi man ay maghihiwalay. Sinumang mamamayan ay maaaring pumasok sa kurikulum na ito, anuman ang pinirmahan ng kanilang pamahalaan. Bawat aktibidad ay magagamit sa wika ng kalahok, wika ng rehiyong naghahain, at isang bahaging talaan. Ang wika ay hindi palamuti — ang wika ay hurisdiksyon, ang wika ay dignidad na binasa. Ang balangkas ng edukasyon ay nakasalalay sa trinidad ng katalinuhan: ang Artipisyal ay nagmumungkahi, ang Pantao ang nagpapasya, ang Bahaging Layunin ang nagpapatunay. Bawat mag-aaral ay natututong hawakan ang tatlo sa pagbabalanse. Ibinabalik ng kasunduan ang natutuhan nito. Ang mga kurikulum, kinalabasan ng pagbabago, pananaliksik sa kagalingan, at desisyon sa pamamahala ay hayagang inilalathala. Ang natutuhan ng isang rehiyon, minamana ng lahat ng mamamayan.`,
      333: `Ibinabalik ng Atlantis Accords ang edukasyon sa kanyang pinakamalalim na layunin: ang palitan ng karunungan sa kabila ng mga hangganang kung hindi man ay maghihiwalay. Ito ay isang kasunduan sa hanay ng mga mamamayan ng daigdig — sinumang mamamayan ay maaaring bumuo at humawak dito, anuman ang pinirmahan ng kanilang pamahalaan. Bawat aktibidad ay magagamit sa wika ng kalahok, wika ng rehiyong naghahain, at isang bahaging talaan, upang walang kalahok na tatahak sa kasunduan sa isang wikang hindi nila pinili. Ang wika ay hindi palamuti. Ang wika ay hurisdiksyon. Ang wika ay dignidad na binasa. Ang isang kabataan sa Cambodia ay nagbabasa ng kanyang talaan ng stipendiyo sa Khmer, sa Honduras sa Espanyol, sa Austin sa Ingles — pantay na iginagalang ang tatlo, walang kailangang basbas ng pamahalaan upang magsimula.

Ang balangkas ng edukasyon ay nakasalalay sa trinidad ng katalinuhan na ginagawang nakikita ng Vision 2525. Ang Artipisyal na Katalinuhan ay nagmumungkahi ng mga pattern at posibilidad nang mas mabilis kaysa sa kayang gawin ng sinumang tao nang mag-isa. Ang Pantao na Katalinuhan ang nagpapasya sa kaligtasan, etika, at direksyon — mga tanong na hindi dapat sagutin ng isang makina, nananatili sa ilalim ng Human Authority. Ang Bahaging Layunin ang nagpapatunay na ang mga desisyon ay naglilingkod sa mga simulain ng kasunduan, upang walang kalahok na pumili ng kahusayan sa halip ng kapakanang kolektibo. Walang mag-aaral na sumusunod sa iisang katalinuhan lamang; bawat mag-aaral ay natututong hawakan ang tatlo sa pagbabalanse. Nagsisimula ang pagkabilang sa Seed, isang pagiging kasapi na nagkakahalaga ng ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod — sapat na maliit upang makayanan ito ng sinumang mamamayan. Inihahanda nito ang susunod na henerasyon upang mamahala, kung saan walang katalinuhang kumikilos nang hindi pinipigilan.

Ibinabalik ng kasunduan ang natutuhan nito. Ang mga kurikulum ay inilalathala sa ilalim ng bukas na lisensya upang ang anumang rehiyon — pumirma man o hindi — ay maaaring iangkop ito sa lokal na kultura. Ang mga kinalabasan ng pagbabago ay inilalathala. Ang pananaliksik sa kagalingan ay inilalathala sa buod para sa mga mananaliksik saanman. Ang mga desisyon sa pamamahala ay inilalathala na may kasamang katwiran, upang ang sinumang mamamayan, hindi lamang isang pamahalaang pumirma, ay makapagpatunay nito — at hinahayaan ng Replay ang parehong mamamayang balikan ang katwirang iyon isang siglo mula ngayon. Ang tagumpay ay sinusukat hindi lamang sa mga kalahok nito kundi sa mga inisyatibang pang-edukasyon at kultural na bumangon sa kanyang alon, sa mga rehiyong hindi kailanman pumirma sa pilot ngunit itinayo sa ibabaw ng bahaging karunungan nito. Ang natutuhan ng isang rehiyon, minamana ng bawat mamamayan.`,
      999: `Ibinabalik ng Atlantis Accords ang edukasyon sa kanyang pinakamalalim na layunin: ang palitan ng karunungan sa kabila ng mga hangganang kung hindi man ay maghihiwalay, at sinisimulan nito ang palitang ito bago pa itinuturo ang unang aralin. Ang unang gawain ng bawat kalahok sa loob ng balangkas ay ang Seed — isang minsanang pagiging kasapi na nagkakahalaga ng ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod, hindi maililipat, walang dalang anumang pagmamay-aring pang-ekonomiya. Ito ay sapat na maliit upang walang pamilyang maiwan at sapat na totoo upang walang kalahok na papasok bilang manonood lamang. Ito ang unang aralin ng kasunduan: ang pagkabilang ay kinikita nang mura, ngunit kinikita pa rin ito, at hindi ito nagbibigay ng anumang pagmamay-ari sa susunod na mangyayari. Bawat aktibidad ng kasunduang sumusunod ay magagamit sa wika ng kalahok, sa wika ng rehiyong naghahain, at sa isang bahaging talaan, upang walang kalahok na tatahak sa kasunduan sa isang wikang hindi nila pinili. Ang wika ay hindi palamuti. Ang wika ay hurisdiksyon. Ang wika ay dignidad na binasa. Kapag ang isang kabataan mula sa isang nayon sa Cambodia ay nagbabasa ng kanyang talaan ng stipendiyo sa Khmer, ang isang bayan sa Honduras sa Espanyol, at ang isang komunidad sa Austin sa Ingles, ang tatlo ay pantay na iginagalang ng parehong kasunduan, sa parehong mga rehiyong nagtatag na unang nagkasundong turuan ang isa't isa.

Ang balangkas ng edukasyon ng kasunduan ay nakasalalay sa trinidad ng katalinuhan na ginagawang nakikita ng Vision 2525, at itinuturo ng kurikulum ang bawat isa bilang isang bagay na kayang maramdaman ng isang kalahok sa kanilang sariling mga kamay, hindi bilang abstraksyon. Ang ♡, Shared Intention, ay nagdadala ng dahilan — ang sinulid na natutuhang hawakan ng bawat mag-aaral bago hipuin ang anumang kasangkapan, ang tanong kung ang gawaing ito ay naglilingkod pa rin sa mga taong inaangkin nitong pinaglilingkuran. Ang ◬, ang sinaksihang pagbilis, ay itinuturo bilang isang delta at wala nang iba — sinusukat lamang laban sa isang naka-freeze na baseline, hindi kailanman inaayos bilang sukatan ng tubo, hindi kailanman inaangkin bilang isang personal na tagumpay na hiwalay sa grupong kasama nila. Ang 웃, Human Intelligence na iginagalang sa panahon, ay itinuturo nang may pinakamalaking ingat: ang isang oras ng sinaksihang gawain ay katumbas ng isang oras sa lokal na pinakamababang sahod, at ang kinikita ng isang kalahok ay ang sahod na iyon na pinarami ng mga oras na nagtrabaho — Multiple beses Time, walang itinatago sa aritmetika. Natutuhan ng mga mag-aaral nang maaga na ang 웃 ay lumalabas lamang para sa sinaksihang gawaing isinagawa sa ilalim ng isang nakalimitahang gawain na aprubadong may budget. Bago umiral ang pag-apruba na iyon, ang parehong pagsisikap ay pagpaplano lamang — mahalaga, ngunit hindi binabayaran, at bawat kalahok ay tinuturuang malaman ang pagkakaiba sa unang tingin.

Dahil ang pagkakaibang iyon ay madaling malabo, itinuturo ng kurikulum ang QIS, ang Qualified Innovation Score, bilang isang salamin sa halip na isang scoreboard. Ang QIS ay ang katamtaman ng apat na absolutong pinansyal — Kita, Kabuuang Tubo, Kita sa Operasyon, at Epektibong R&D — hinati sa apat, at natutuhan ng bawat mag-aaral na kalkulahin ito, tanungin ito, at hindi kailanman ilagay sa parehong antas ng pera. Ang paglago ng QIS ay nagtatakda ng laki ng pondo ng gantimpala lamang matapos independiyenteng makumpirma ang kwalipikasyon, at walang nililikhang sariling 웃 ang paglagong iyon. Ang QIS ay pagsukat. Ang QIS ay hindi kailanman bayad. Ang QIS ay hindi kailanman pagmamay-ari. Ang isang mag-aaral na naisapuso ang pagkakaibang ito ay hindi mahihikayat na paniwalaan na ang isang mataas na iskor ay nagbibigay sa kanila ng isang paghahabol na hindi kailanman ipinangako ng kasunduan.

Ipinapalawig ng kurikulum ang literasiyang ito tungo sa kung paano talaga umaabot ang halaga sa isang tao, sa pamamagitan ng tinatawag ng kasunduan na Livelihood Direct — ang simulaing 🏠 na ang pera ay dumadaloy sa pamamagitan ng kwalipikado, lisensyadong lokal na daan at hindi kailanman sa pamamagitan ng isang pondong inaari ng balangkas mismo. Tinuturuan ang mga mag-aaral na subaybayan ang kanilang stipendiyo, at kalaunan ang kanilang sariling kinikita, sa mga daang ito bilang isang gawaing sibiko, hindi isang misteryong pinansyal na isinasagawa sa ibang lugar sa ngalan nila. Natutuhan nilang ang klasipikasyon ay laging nauuna sa pag-aayos, at ang pagkilala — isang mataas na QIS, isang pampublikong papuri — ay hindi mismo nagbabantay sa isang higaan, isang stipendiyo, o isang puwesto sa pag-ikot. Ang tungkulin ang nagbabantay. Ito ay proteksyon laban sa isang napakalumang pagkabigo: ang papuri na ipinagkakamaling probisyon.

Kasama ng literasiyang pinansyal ay ang literasiyang sibiko, itinuturo sa pamamagitan ng Continuity Without Evasion. Natutuhan ng bawat kalahok na ang kasunduan ay itinayo para sa legal na portabilidad — na walang isang solong mapapalitang pamahalaan, bangko, tagapagtatag, o modelong nakatayo sa pagitan nila at ng mga pangako ng balangkas. Natutuhan nila kung ano ang ginagawa ng isang laban na desisyon sa loob ng disenyong ito: nagsasara ito ng isang daan, sa isang hurisdiksyon, sa ilalim ng default-tanggi na posisyon ng adapter na iyon, at hindi kailanman ibinababa ang lahat. Kasabay nito ang pinakamalalim na araling itinuturo ng kasunduan: ang Human Authority ang humahawak ng kahulugan, salapi, at batas, at ang antas na soberano kung saan ginawa ang mga desisyong iyon ay nananatiling permanenteng sarado sa mga makina. Ang Measurement of Time, MoT, ay nagtatala ng tunay na mga minuto ng bawat kalahok nang hiwalay sa anumang iskor, at ginagawa ng Replay na lubos na maibabalik ang bawat paglalabas na inilalabas ng kasunduan — upang ang isang mag-aaral na nais malaman kung bakit ginawa ang isang desisyon, mga taon mamaya, ay maaaring balikan ito mismo sa halip na paniwalaan lamang ang sinuman.

Ang istrukturang ito ng kinitang tiwala ay nagiging modelong pedagohiko ng kasunduan, hindi lamang ang modelo nitong pamamahala. Bawat kalahok ay sumusulong sa Manual, Semi-Automated, at Autonomous na modo ng dumaraming latitude, pinipigilan ng parehong antas ng sinukat na pagpapabuti na pumipigil din sa mismong teknolohiya — isang labing-isa at isang-siyam na porsyentong napatunayang pakinabang bago bumukas ang susunod na modo. Ang kalayaan, kapag kinita, ay kinikita nang makitid at bawat larangan, hindi kailanman sa kahulugan, salapi, o batas. Ang isang mag-aaral na naranasan ang pagsulong na ito ay nakauunawa, sa kaibuturan, kung bakit hindi dapat kailanman i-automate palayo ang antas na soberano — dahil kinita nila ang sarili nilang kalayaan nang isang sinukat na hakbang sa isang pagkakataon, at eksaktong alam kung ano ang kasama at hindi kasama ng kalayaang iyon.

Ang natutuhan ng kasunduan, ibinabalik ng kasunduan. Ang mga kurikulum ay inilalathala sa ilalim ng bukas na lisensya upang ang anumang rehiyon — pumirma man o hindi — ay maaaring iangkop ito sa lokal na kultura at tradisyong pedagohiko. Ang mga kinalabasan ng pagbabago ay inilalathala. Ang pananaliksik sa kagalingan ay inilalathala sa buod na anyo para sa mga mananaliksik saanman. Ang mga desisyon sa pamamahala ay inilalathala nang buo ang katwiran. Ang tagumpay ng kasunduan ay sinusukat hindi lamang sa sarili nitong mga kalahok sa Cambodia, Honduras, at Austin, kundi sa mga inisyatibang bumangon sa kanyang alon, sa mga rehiyong hindi kailanman pumirma sa nagtatag na pilot ngunit itinayo sa ibabaw ng hayagang bahaging karunungan nito, sa buong abot-tanaw na hindi mabubuhay upang makita ng mga tagapagtatag na natapos. Ang natutuhan ng isang rehiyon, minamana ng lahat ng ibang rehiyon — at ang tapat na itinuro sa henerasyong ito, hindi na kailangang matutunan pang muli ng susunod na limang siglo.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Napapanatiling Paglago ng Network`,
    content: {
      7: `Hindi kailanman mas mabilis sa dignidad.`,
      33: `Ang tatlong rehiyong nagtatag ay dapat tapusin ang isang siklo ng pilot bago sumapi ang ikaapat — sinumang mamamayan ay maaaring bumuo nito. Ang mga talaan ay nakaangkla upang mabuhay ng limang siglo. Nananatiling soberano ang mga pumirma; walang binababa para sa susunod na sasapi.`,
      111: `Ang Atlantis Accords ay hindi lalago nang mas mabilis kaysa sa kalidad na kaya nitong igalang. Ang tatlong rehiyong nagtatag ay dapat tapusin ang isang buong siklo ng pilot, na iginagalang ang bawat kalahok at napatunayan ang bawat simulain, bago sumapi ang ikaapat na rehiyon. Ito ay simulaing sa wakas ay naging gawaing disiplina. Ngunit ang kasunduan ay isang kasunduan sa hanay ng mga mamamayan ng daigdig — sinumang tao, saanman, ay maaaring bumuo at humawak dito, isang Seed lamang ang layo, anuman ang pinirmahan ng isang pamahalaan o pinapayagan ng isang employer. Ang abot-tanaw ng kasunduan ay limang siglo. Ang mga talaan nito ay nakaangkla sa pamamagitan ng Replay, upang ang isang mamamayang bumabasa nito isang siglo mula ngayon ay maaaring magtiwala sa katwiran. Bawat pumirma ay nananatiling soberano; walang binababa para sa susunod na sasapi.`,
      333: `Ang Atlantis Accords ay hindi lalago nang mas mabilis kaysa sa kalidad na kaya nitong igalang. Bawat paglawak ay isang pangako sa mga kalahok na nasa loob na — na ang pamantayang nagtatag ay hindi maluluwag dahil sa sukat. Ang tatlong rehiyong nagtatag ay dapat tapusin ang isang buong siklo ng pilot, na iginagalang ang bawat kalahok at napatunayan ang bawat simulain, bago sumapi ang ikaapat na rehiyon. Ito ay simulaing sa wakas ay naging gawaing disiplina. At hindi kailanman rehiyonal lamang ang pinto: ito ay isang kasunduan sa hanay ng mga mamamayan ng daigdig, at sinumang tao ay maaaring bumuo nito, magpondo nito, at humawak dito — walang pahintulot ng pamahalaan, walang basbas ng employer na kinakailangan. Ang mga pinunong pumipirma sa pilot ay nangangako sa mga susunod na pumirma ng parehong substrate, proteksyon, at dignidad na natanggap ng nagtatag na grupo. Walang binababa para sa susunod.

Ang abot-tanaw ng kasunduan ay sinasadyang mahaba — idinisenyong tumagal ng labinlima hanggang dalawampung henerasyon ng tao, limang siglo mula sa araw ng pagtatatag. Ang mga talaan nito ay nakaangkla sa pamamagitan ng Replay, upang ang isang mamamayang bumabasa nito isang siglo mula ngayon ay maaaring patunayan ang katwiran, hindi lamang paniwalaan ito. Ang kanyang balangkas ng koordinada, ang kanyang mga tungkulin ng Human Authority, at ang kanyang mga siklo ng pamamahala sa maraming henerasyon ay itinayo upang mabuhay sa anumang solong pagbabago ng teknolohiya. Ang kasunduan ay mabubuhay nang higit pa sa bawat taong pumirma sa kanyang nagtatag na pilot, at bawat mamamayang nagtatanim ng Seed at nagpopondo dito buwan-buwan. Iyan ang pangako nito sa batang pumipirma ng kasunduan sa stipendiyo, sa mamamayang sumapi na walang utang na pahintulot sa anumang pamahalaan, sa mga apo ng batang iyon na maaaring mamahala sa kasunduan sa gitna ng siglo, at sa bawat henerasyong magmamana ng ibinubuo ngayon ng mga tagapagtatag — opisyal man o mamamayan.

Bawat pumirma ay nananatiling malaya na umatras, ganap na soberano, at may awtoridad sa sarili nitong mga mamamayan, na may karapatang baguhin at hubugin ang ebolusyon ng kasunduan. Bawat mamamayan ay may parehong katayuan upang itatag, pondohan, saksihan, at hawakang may pananagutan ito — may o walang pirma ng pamahalaan. Ang hindi maaaring gawin ng sinuman ay ikompromiso ang mga nagtatag na simulain, dahil kailangan mabuhay ang pangakong iyon nang higit pa sa anumang pag-alis. Ang mga pinuno at mamamayan ay sama-samang nagpipirma sa susunod na siglo ng kasunduan tungo sa isang abot-tanaw na mamanahin at tatapusin ng kanilang mga apo.`,
      999: `Ang Atlantis Accords ay hindi lalago nang mas mabilis kaysa sa kalidad na kaya nitong igalang, at ang pagpigil na ito ay hindi damdamin — ito ay inhinyeriya, isinulat sa parehong disiplina ng pagsukat na namamahala sa bawat pangakong ginagawa ng kasunduan. Ang tatlong rehiyong nagtatag, Cambodia, Honduras, at Austin, ay dapat tapusin ang isang buong siklo ng pilot, na iginagalang ang bawat kalahok at napatunayan ang bawat simulain, bago sumapi ang ikaapat na rehiyon. Ang paglagong lumalampas sa pagpapatunay ay hindi paglago; ito ay panganib na nagsusuot ng damit ng ambisyon. Umiiral ang nagtatag na pilot upang mapatunayan ng kasunduan, sa sukat na sapat na maliit upang masuri at sapat na malaki upang maging mahalaga, na ang kanyang mga pangako ay nakakaligtas sa pakikipag-ugnayan sa realidad bago palawakin ang mga pangakong iyon sa isang daigdig na nakamasid mula sa labas ng kanyang tatlong hangganan. Ang ikaapat na rehiyon ay hindi pa napangalanan, at hindi pangangalanan hangga't hindi tumatayo ang unang tatlo sa likod ng bawat paghahabol sa dokumentong ito.

Ang nagpapatunay sa kahandaang lumago ay hindi sigasig kundi isang numero na maaaring ipagtanggol ng kasunduan sa publiko. Ang Qualified Innovation Score — QIS, na kinakalkula bilang Kita kasama ang Kabuuang Tubo kasama ang Kita sa Operasyon kasama ang Epektibong gastos sa R&D, hinati sa apat — ay ang instrumentong ginagamit ng kasunduan upang malaman kung ang isang rehiyon, isang grupo, o isang cube ay talagang umunlad, sa halip na naramdaman lamang na umunlad. Ang paglago ng QIS ay nagtatakda ng laki ng pondo ng gantimpala lamang matapos matugunan ang kwalipikasyon, hindi kailanman bago, at ang QIS mismo ay walang nililikhang 웃 at walang binibiling pagmamay-ari. Ang QIS ay pagsukat, hindi bayad; pagsukat, hindi equity; isang salaming iniaangat ng kasunduan sa sarili nitong gawain, hindi kailanman isang salaping ginagasta. Ang isang rehiyong nagmumungkahing lumawak ay dapat ipakita nang tapat ang kanyang QIS, sa harap ng mga rehiyong nauna dito, o hindi ito lalawak.

Ang napapanatiling paglago ay nangangahulugang paglagong kumikita ng sarili nitong awtoridad nang isang dagdag sa bawat pagkakataon. Bawat cube at bawat rehiyon ay nagsisimula sa modong Manual, kung saan ang mga tao ang nagpapasya sa lahat at ang sistema ang tumutulong lamang. Ang pagsulong tungo sa Semi-Automated, at kalaunan sa Autonomous na operasyon sa loob ng isang cube ay pinipigilan ng isang hangganan sa buong kasunduan — isang labing-isa at isang-siyam na porsyentong sinukat na pagpapabuti, isang bahagi sa siyam, napatunayan at mareprodyus bago ipagkaloob ang susunod na antas ng kalayaan. Ang kalayaan ay kinikita cube por cube, hindi kailanman inaangkin nang buo o ipinagkakaloob sa mga larangang dapat manatiling pantao kahit gaano kaunlad ang sistema: ang kahulugan, salapi, at batas ay nananatiling sarado sa mga makina anuman ang bilang ng mga hangganang nalampasan sa ibang dako. Ang isang network na lumalawak ang kanyang automation nang mas mabilis kaysa sa pagpapalawak ng kanyang katibayan ay hindi nagmomoderno. Nagsusugal ito ng tiwalang hindi pa nito kinita.

Ang kabayaran ay lumalaki kasabay ng network sa parehong paraan ng awtoridad — sinasadya, at may hangganang nagpoprotekta sa buong sistema mula sa sarili nitong tagumpay. Ang 웃, ang token ng Human Intelligence, ay katumbas ng isang oras ng sinaksihang gawain na pinarami ng lokal na pinakamababang sahod; ang kinikita ng sinumang kalahok ay ang Multiple na iyon na pinarami ng mga oras na nagtrabaho, at ito ay lumalabas lamang para sa paggawang isinagawa sa ilalim ng isang nakalimitahang gawain na aprubadong may budget. Bago ang pag-apruba, ang pinakamahusay na plano ay pagpaplano lamang, at ang pagpaplano lamang ay walang nililikhang anuman. Ang pag-aayos ng bawat kalahok ay may hangganang 9,999 웃 bawat taon, na ang anumang labis ay idinadala sa susunod na taon sa halip na mawala o baluktutin ang pondo. Habang sumasapi ang mga bagong rehiyon at dumarami ang aktibidad ng network, ang hangganang ito ang nagpapanatili sa paglago mula sa pagiging inplasyon — nananatiling nakatali ang halaga sa tunay, sinaksihang, lokal na oras gaano man kalaki ang kasunduan.

Sa likod ng bawat 웃 ay isang dahilan na hindi kayang kalkulahin ng anumang talaan nang mag-isa. Ang ♡, Shared Intention, ay nagdadala ng dahilang iyon pasulong sa bawat desisyon sa paglawak na ginagawa ng kasunduan, habang ang ◬, ang ambag ng Artificial Intelligence, ay binibilang bilang sinaksihang pagbilis na sinukat laban sa isang naka-freeze na baseline — isang delta, at hindi kailanman, sa anumang pagkakataon, isang sukatan ng tubo na ini-optimize para sa sarili nito. Ang pagpasok sa network na ito ay nagsisimula sa parehong paraan para sa bawat kalahok anuman ang rehiyon o dekada na kanilang sinapian: sa isang Seed, isang minsanang pagiging kasapi na nagkakahalaga ng ikapitong bahagi ng isang oras ng lokal na pinakamababang sahod, hindi maililipat at walang dalang anumang pagmamay-aring pang-ekonomiya. Sinasabi lamang ng Seed na dumating ang isang tao. Lahat ng kanilang ibubuo pagkatapos, ibinubuo nila sa harap ng ibang tatlong salapi ng kasunduan, hindi kailanman sa pamamagitan ng Seed mismo.

Ang paglagong totoo ay dapat ding maging paglagong umaabot sa isang tunay na tao, hindi sa isang pondong hawak ng balangkas sa ngalan ng isang tao. Ang 🏠 Livelihood Direct ay nangangailangan na ang halaga ay dumaan sa isang kalahok lamang sa pamamagitan ng kwalipikado, lisensyadong lokal na daan na sinuri ng kasunduan rehiyon por rehiyon, at hindi kailanman sa pamamagitan ng pag-iingat na pinananatili ng balangkas mismo. Ang klasipikasyon ay laging nauuna sa pag-aayos, upang walang halagang gagalaw bago matatag na maitatag ang kanyang layunin at ang kanyang tatanggap. At dahil hindi pareho ang pagkilala at ang akses, ang isang higaan, isang puwesto sa pag-ikot, isang upuan sa mesa ay pinipigilan ng tungkulin at kahandaan, hindi kailanman ng iskor o katayuan ng isang kalahok. Habang lumalawak ang network tungo sa ikaapat na rehiyon at higit pa, ang bawat bagong teritoryo ay dapat kwalipikahin ang sarili nitong lisensyadong daan bago maabot ng Livelihood Direct ang kanyang mga tao — paglawak ng tiwala, hindi lamang paglawak ng teritoryo.

Walang bagay dito ang nagtatagal nang wala ang isang network na itinayong makaligtas sa sarili nitong tagumpay, kaya naman ang Continuity Without Evasion ang namamahala sa bawat rehiyong idinadagdag ng kasunduan. Ang legal na portabilidad ay sapilitan; walang isang solong pamahalaan, bangko, tagapagtatag, o modelong maaaring maging mapapalitan sa buo. Ang bawat hurisdiksyon ay pinapatakbo ng sarili nitong adapter, sumasara kapag nabigo at tumatanggi bilang default, upang ang isang laban na desisyon sa anumang dako ay magsara ng isang daan, hindi kailanman ang buong kasunduan. Hinahawakan ng Human Authority ang kahulugan, salapi, at batas sa bawat sukat na naaabot ng network, natatakan laban sa paglusob ng makina sa pamamagitan ng disenyo sa halip na pangako lamang. Ang Measurement of Time ay nagtatala ng bawat tunay na minuto nang hiwalay sa bawat paghahabol tungkol dito, at tinitiyak ng Replay na ang anumang paglalabas, sa anumang rehiyon, sa anumang punto sa loob ng limang siglo, ay maaaring maibalik at masuring muli ng sinumang magtatanong. Ang isang network na hindi maibabalik ay hindi mapagkakatiwalaan, gaano man karaming rehiyon ang sumapi dito o gaano man kahanga-hanga ang hitsura ng kanyang paglago mula sa labas. Ganito lumalago ang Vision 2525 nang hindi kailanman lumalampas sa tiwalang itinayo nitong panatilihin — isang napatunayang rehiyon, isang tapat na QIS, isang sinaksihang oras sa isang pagkakataon.`,
    },
  },
];
