import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_TR: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Yeniliğin Başladığı Yer`,
    content: {
      7: `Liderler, hiçbir yüzyılın başlamadığını başlatır.`,
      33: `Üç bölge — Kamboçya, Honduras, Austin — vatandaşların birlikte inşa ettiği bir vaadi açar: öğrenenleri barındırmak, onları korumak, geleceğin araçlarını ellerine teslim etmek. Hükümet, Eğitim, İnovasyon birer vasi olarak imzalar; vatandaşlar onu sahiplenir. Tek bir başlangıç.`,
      111: `Atlantis Antlaşmaları, dünya vatandaşları arasında yapılmış bir anlaşmadır — hükümeti ne imzalarsa imzalasın, işvereni neye izin verirse versin, dünyanın herhangi bir yerindeki herhangi bir kişinin kurabileceği ve sahiplenebileceği bir vaat. Kurucu bölgeleri Kamboçya, Honduras ve Austin, Teksas, nadir bulunan tek bir nitelik için seçildi: gençlere, onlara öğretecek zaman daha varken geleceğin araçlarına güvenme isteği. Hükümetler, eğitimciler ve yenilikçiler bölgelerinin vasisi olarak imzalar — her biri üç vizyoner imza: Hükümet, Eğitim, İnovasyon — ama antlaşmayı finanse eden, çalışmasına tanıklık eden ve onu doğrudan hesap verebilir kılan vatandaşlardır. Antlaşmaya dahil olmak için ne bir hükümetin izni ne de bir işverenin onayı gerekir. Üç bölge, tek bir ortak başlangıç.`,
      333: `Her uygarlık, başlatmayı seçtiği şeyle hatırlanır. Atlantis Antlaşmaları dünya vatandaşları arasında bir vaattir — hükümeti ne imzalarsa imzalasın, dünyanın herhangi bir yerindeki herhangi bir kişi onu başlatabilir. Kurucu bölgeleri Kamboçya, Honduras ve Austin, Teksas, ekonomik güç, askeri kudret ya da kurumsal itibar için değil, daha nadir bir nitelik için seçildi: gençlere geleceğin araçlarına güvenme isteği. Önümüzdeki yüzyılda liderlik bunu ifade eder — anahtarları, onlara nasıl kullanılacağını öğretecek zaman daha varken bir sonraki nesle teslim etme cesareti.

Antlaşma, bu an için özel olarak inşa edilmiş bir örgütleyici güç olan eXeL tarafından bir araya getirilir; eXeL, geçen yüzyılı biçimlendiren koordinasyon kanallarının dışında var olur — diplomatik antlaşma yapılarının, çok taraflı bürokrasilerin ve herhangi bir ulus devletin siyasi karmaşasının dışında. eXeL, vizyoner liderleri ortak bir çerçeve, ortak bir ivme çarkı ve ortak bir beş yüz yıllık ufuk etrafında bir araya getiren güvenilir düzenleyicidir. Her imzacı tam egemenliğini, kendi vatandaşları üzerindeki tam yetkisini ve her an geri çekilme özgürlüğünü korur. İmzacıların kazandığı — ve bir Seed bedeli karşılığında, yerel asgari ücretin bir saatinin yedide biri karşılığında, herhangi bir vatandaşın da kazandığı — yalnızca amaca özel inşa edilmiş bir çerçevenin sağlayabileceği ağ etkisidir: herhangi bir siyasi tahakküm biçimi olmaksızın koordinasyon.

Antlaşmayı imzalamak bir vaadi imzalamaktır: bölgenin kültürler arasında öğrenenleri barındıracağı, yalnızca kendisinin sunabileceği şeyi katkı olarak vereceği ve kendini mevcut düzenlemelerin gerektirdiğinden daha yüksek bir standarda — kamuya açık, şeffaf biçimde, onu finanse eden, tanıklık eden ve hesap sorabilen vatandaşlara karşı — tutacağı vaadi; dahil olmak için ne bir hükümetin izni ne de bir işverenin onayı gerekir. Her bölgeden üç imza gerekir — Hükümet, Eğitim ve İnovasyon — sahip olarak değil, vasi olarak imzalayan üç imza. Evet demek için üç vizyoner, imzaladıklarını sahiplenmek için de vatandaşlar gerekir. Üç vizyoner, üç bölge, tek bir başlangıç — bir çerçeve, onu var etmeye istekli liderlerin güveniyle hayata işte böyle girer.`,
      999: `Her uygarlık, başlatmayı seçtiği şeyle hatırlanır ve Vision • 2525, bu uygarlığın kurucularından fetihle değil alçakgönüllülükle başlamalarını ister. Atlantis Antlaşmaları, daha önce var olmamış bir şeyi başlatmaya istekli liderlerin verdiği bir vaattir — dünyanın her köşesine ulaşan, her sesi onurlandıran ve yıllarla değil yüzyıllarla ölçülen nesiller boyunca süren, insan yenilikçiliği için ortak bir temel. Kamboçya, Honduras ve Austin, Teksas'taki kurucu imzacılar ekonomik güç, askeri kudret ya da kurumsal itibar için seçilmedi. Daha nadir bir nitelik için seçildiler: gençlere geleceğin araçlarına güvenme isteği ve beş yüz yıllık bir ufkun herhangi bir yönetimin alkışından daha uzun süreceğine dair sabır. Önümüzdeki yüzyılda liderlik bunu ifade eder — anahtarları, onlara nasıl kullanılacağını öğretecek zaman daha varken bir sonraki nesle teslim etme cesareti.

Antlaşma, bu an için özel olarak inşa edilmiş bir örgütleyici güç olan eXeL tarafından bir araya getirilir. eXeL, geçen yüzyılı biçimlendiren koordinasyon kanallarının dışında var olur — diplomatik antlaşma yapılarının dışında, çok taraflı bürokrasilerin dışında, herhangi bir ulus devletin siyasi karmaşasının dışında. eXeL, vizyoner liderleri ortak bir çerçeve, ortak bir ivme çarkı ve ortak bir beş yüz yıllık ufuk etrafında bir araya getiren güvenilir düzenleyicidir. Her imzacı tam egemenliğini, kendi vatandaşları üzerindeki tam yetkisini ve her an geri çekilme özgürlüğünü korur. İmzacıların kazandığı, yalnızca amaca özel inşa edilmiş bir çerçevenin sağlayabileceği ağ etkisidir. Her katılımcının bu çerçeveye girişi aynı mütevazı şekilde başlar: yerel asgari ücretin bir saatinin yedide biri fiyatına, devredilemez ve hiçbir türden ekonomik hak talebi taşımayan, tek seferlik bir üyelik olan Seed ile. Bir Seed ne mülkiyet ne de ödül vaadi satın alır — yalnızca aidiyeti, çerçevenin içinde durup başlama hakkını satın alır. Bu, herhangi bir siyasi tahakküm biçimi olmaksızın koordinasyondur; herkesin karşılayabileceği kadar küçük bir başlangıç üzerine inşa edilmiştir.

Egemenlik teslim edilmek yerine korunduğu için antlaşma, Continuity Without Evasion ilkesi üzerine inşa edilmiştir. Hiçbir vazgeçilmez hükümet, banka, kurucu ya da model, çerçevenin tamamını kendi hayatta kalması uğruna rehin tutamaz. Her yargı alanı kendi yasal bağdaştırıcısı aracılığıyla hizmet görür; uyumluluk kanıtlanana kadar varsayılan olarak reddeder, böylece değer yalnızca o yargı alanındaki bir mahkemenin meşru sayacağı kanallardan hareket eder. Bir bölgedeki bir düzenleyici olumsuz bir karar verirse, yalnızca o tek kanal kapanır — şeffaf biçimde, içindeki hiçbir katılımcıya zarar vermeden — diğer tüm bölgeler ise kesintisiz devam eder. Antlaşmanın tamamı, bir hükümet fikrini değiştirdi diye asla çökmez. Bu, krizden sonra keşfedilen bir yedek plan değil, kurucu bir vaat olarak tasarlanmış taşınabilirliktir.

Antlaşmayı imzalamak bir vaadi imzalamaktır. Bölgenin kültürler arasında öğrenenleri barındıracağı vaadini. Bölgenin yalnızca kendisinin sunabileceği şeyi katkı olarak vereceği vaadini. Bölgenin kendini mevcut düzenlemelerin gerektirdiğinden daha yüksek bir standarda tutacağı vaadini. Bölgenin bunu kamuya açık, şeffaf biçimde, hizmet ettiği her vatandaşın gözü önünde yapacağı vaadini. Her bölgeden üç imza gerekir — Hükümet, Eğitim ve İnovasyon. Hiçbir makam antlaşmayı tek başına bağlamaz. Evet demek için üç vizyoner gerekir. Bu üçlü imza, Human Authority'nin ilk ifadesidir: anlam, para ve hukuk, egemen katmanda insan elinde kalır — bu katman, o makineler ne kadar yetkin hale gelirse gelsin, makinelere kalıcı olarak kapalıdır. Measurement of Time, yani MoT, kayda imza anından itibaren başlar — herhangi bir otomatik tahminden ayrı tutulan, gerçek insan emeğinin gerçek dakikaları — ve antlaşmanın çalışmasının her sonraki yayını, Replay aracılığıyla yeniden inşa edilebilecek şekilde tasarlanmıştır; böylece bir yüzyıl sonra doğacak bir vatandaş, bugünün kurucu kararlarının nasıl alındığını yeniden izleyebilir.

Pilotun temellendirdiği şey, para olmadan önce ölçümdür. Çerçeveye giren her yenilik, Qualified Innovation Score — QIS — ile puanlanır: Gelir, Brüt Kâr, Faaliyet Geliri ve Etkin Ar-Ge harcamasının ortalaması, dörde bölünür. QIS bir ödeme değildir ve asla mülkiyet değildir; kurucu topluluğun, herhangi bir ödül büyüklüğü belirlenmeden önce kendi ilerlemesini görmeyi öğrendiği araçtır. Nitelik kazanma sağlandıktan sonra QIS'teki büyüme, sonrasında gelen ödül havuzunun büyüklüğünü belirler — ama QIS'teki büyüme tek başına hiçbir şey basmaz. Üç bölge, tek bir başlangıç ve tek bir ortak disiplin: hazineye dokunmadan önce puanı kanıtla.

Tanıklık edilen emek yoluyla kazanılan değer kendi adını taşır: 웃; bir saatin yerel asgari ücretle çarpımı olarak hesaplanır ve hizmet edilen saatlere uygulanan bir Multiple ile ölçeklenir. 웃 yalnızca kapsamı belirlenmiş, bütçesi onaylanmış bir görev altında tanıklık edilen emek için verilir; bu onayın altında kalan her şey hâlâ planlamadır ve planlama tek başına hiçbir şey basmaz. Yıllık 9.999 웃'luk bir ödeme tavanı, her katılımcıyı denetimsiz yoğunlaşmadan korur; fazlası kaybolmak yerine bir sonraki yıla devreder. Her 웃'un arkasında, bir görevin ilk etapta neden onaylandığını taşıyan ♡ — Shared Intention — ve bir görevin donmuş bir taban çizgisine karşı ürettiği, tanıklık edilmiş hızlanma olan ◬ durur — yalnızca bir fark, asla bir kârlılık ölçütüyle karıştırılmaz. Pilot, çerçeve kurucularının ötesine ölçeklenmeden önce bu üç glifin bölge bölge dürüstçe birlikte hareket edebildiğini kanıtlamak için vardır.

Değer bir kişiye ulaştığında, ona Livelihood Direct — 🏠 — aracılığıyla ulaşır: eXeL'in asla kendi fonu olarak gözetim altında tutmadığı, nitelikli ve lisanslı yerel kanallar. Sınıflandırma her durumda ödemeden önce gelir ve bir katkının tanınması asla bir gecelik yatağın kapısını açmaz; yalnızca kişinin kapsamı belirlenmiş bir görevdeki rolü açar. Pilotun ötesindeki büyüme de kapılıdır: çerçevenin her küpü, dokuzda bir oranında ölçülen iyileştirmeyi, yani yüzde 11,1 kuralını aşmadan Manuel'den Yarı Otomatik'e, oradan Otonom'a geçmez; bu kazanım küp küp elde edilir, asla toptan iddia edilmez — ve hiçbir koşulda anlam, para ve hukukun egemen katmanı üzerinde de asla iddia edilmez. Bölge başına üç vizyoner, üç bölge ve tek bir başlangıç, beş yüz yıllık bir vaade işte böyle dönüşür: hızlı hareket ederek değil, her adımın kendinden sonraki adımı hak ettiğini kamuya açık biçimde kanıtlayarak.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Simülasyon Yoluyla Öğrenmek`,
    content: {
      7: `Dokunmadan önce bin kez pratik yapın.`,
      33: `Hiçbir sonuç doğurucu şey ilk kez canlı donanımda öğrenilmez. Herhangi bir vatandaş simülasyonda prova yapabilir, üç bölge arasında rotasyona girebilir, kutlayabilir — ilk hatası asla bir hayata mal olmaması gereken genç insana duyulan saygı budur.`,
      111: `Öğrenilmeye değer her disiplin, bilinir hale gelmeden önce birileri tarafından öğrenilmiştir. Atlantis Antlaşmaları bu kadim bilgeliği, gençlerin — ve katılan herhangi bir vatandaşın — geleceği inşa etmeye nasıl hazırlandığının merkezine geri getirir. Hiçbir sonuç doğurucu şey ilk kez canlı donanımda, gerçek insanlar üzerinde ya da geri döndürülemez koşullarda öğrenilmez; ne bir hükümetin izni ne de bir işverenin onayı gerekir. Her katılımcı, pratik yetkinliğe, ardından hazırlığa dönüşene kadar simülasyonda pratik yapar. Rotasyon modeli her katılımcıyı üç kurucu bölge boyunca taşır ve her rotasyon, ev sahibi topluluğa açık bir kamuya açık kutlamayla sona erer. İlk hatası asla bir hayata mal olmaması gereken genç insana duyulan saygı budur.`,
      333: `Öğrenilmeye değer her disiplin, bilinir hale gelmeden önce birileri tarafından öğrenilmiştir. Usta zanaatkârlar performanstan önce, pilotlar uçuştan önce, hekimler ameliyattan önce prova yapar; çocuklar ise oyun yoluyla prova eder. Atlantis Antlaşmaları bu kadim bilgeliği, gençlerin — ve katılan herhangi bir vatandaşın, ne bir hükümetin izni ne de bir işverenin onayı gerekmeksizin — geleceği inşa etmeye nasıl hazırlandığının merkezine geri getirir. Hiçbir sonuç doğurucu şey ilk kez canlı donanımda, gerçek insanlar üzerinde ya da geri döndürülemez koşullarda öğrenilmez. Her katılımcı, pratik yetkinliğe, ardından hazırlığa dönüşene kadar simülasyonda pratik yapar. Bu bir tedbirlilik meselesi değildir — ilk hatası asla birinin hayatına mal olmaması gereken genç insana duyulan saygıdır.

Antlaşmanın rotasyon modeli her katılımcıyı üç kurucu bölge boyunca taşır. Kamboçya'da öğrenilen, Honduras'ta rafine edilir ve Austin'de tamamlanır. Austin'de keşfedilen, Kamboçya'da sorgulanır ve Honduras'ta bütünleştirilir. Her katılımcı, aksi takdirde birbirinden uzak kalacak kültürler arasında yaşar, öğrenir ve mentorluk alır. Eğitim müfredatı birçok kültürdeki disiplinli simülasyon geleneklerinden beslenir — Sun Tzu'nun stratejik eğitim geleneğinden, Musashi'nin oyun yoluyla pratiğinden, İbn Haldun'un döngüsel öğrenme kuramından, Nalanda'nın manastır diyalektiğinden, sivil uçuş simülatöründen — her bilişsel aşamayı ve kültürel mirası gözetecek şekilde harmanlanmıştır. Tek bir gelenek baskın değildir.

Her rotasyon, komşuların, ailelerin ve ziyaretçilerin topluluğun neler öğrendiğini gördüğü, ev sahibi topluluğa açık kamuya açık bir kutlamayla sona erer. Bu etkinlikler, gelişmiş teknolojiyi korkutucu olmaktan çıkarıp erişilebilir ve kutlanan bir şeye dönüştürür — işbirlikçi sistemleri oyun yoluyla anlayarak büyüyen bir toplum, bu sistemlere duyulan korkuyla kolayca manipüle edilemez. Bu, güç yoluyla değil eğitim yoluyla caydırıcılıktır. Antlaşmanın her ebeveyne verdiği söz şudur: çocuğunuz, kendisine zarar verebilecek herhangi bir şeye dokunmadan önce güvenlik içinde bin kez pratik yapacak ve bu, bir vatandaşın — bir yüzyıl sonra herhangi bir vatandaşın — bunun tam olarak kayıtlara geçtiği gibi gerçekleştiğini doğrulayabilmesi için tanıklıkla kayıt altına alınacaktır. Bu, bir çerçeveye mühendislik ürünü olarak işlenmiş genç insana saygıdır ve liderliğin, katılan bir sonraki vatandaşa, o vatandaş bunu talep etmek zorunda kalmadan önce borçlu olduğu şeydir.`,
      999: `Öğrenilmeye değer her disiplin, bilinir hale gelmeden önce birileri tarafından öğrenilmiştir ve varlığını sürdüren her uygarlık, bunu, önemli hale gelmesi istenmeden önce o öğrenmenin güvenle gerçekleşebileceği alanı koruduğu için başarmıştır. Usta zanaatkârlar performanstan önce, pilotlar uçuştan önce, hekimler ameliyattan önce prova yapar; çocuklar ise dünyayı oyun yoluyla prova eder. Atlantis Antlaşmaları bu kadim bilgeliği, gençlerin geleceği inşa etmeye nasıl hazırlandığının merkezine geri getirir ve bu bilgeliğe bir ad ve bir mekanizma verir: Replay. Hiçbir sonuç doğurucu şey ilk kez canlı donanımda, gerçek insanlar üzerinde ya da geri döndürülemez koşullarda öğrenilmez. Her katılımcı, pratik yetkinliğe, ardından hazırlığa dönüşene kadar simülasyonda pratik yapar ve o pratiğin her saati, daha sonra yeniden inşa edilebilmesi, incelenebilmesi, güvenilebilmesi için kayıt altına alınır. Bu bir tedbirlilik meselesi değildir — ilk hatası asla birinin hayatına mal olmaması gereken genç insana duyulan saygıdır ve her hâlükârda hatadan daha uzun yaşayacak olan kayda duyulan saygıdır.

Antlaşmanın rotasyon modeli her katılımcıyı üç kurucu bölge boyunca taşır. Kamboçya'da öğrenilen, Honduras'ta rafine edilir ve Austin'de tamamlanır. Austin'de keşfedilen, Kamboçya'da sorgulanır ve Honduras'ta bütünleştirilir. Her katılımcı, aksi takdirde uzak kalacak kültürler arasında yaşar, öğrenir ve mentorluk alır; her rotasyon, güvenilmeye değer her insani kurum için başladığı şekilde başlar: bir Seed ile. Seed, yerel asgari ücretin bir saatinin yedide biri fiyatına, devredilemez ve hiçbir türden ekonomik hak talebi taşımayan, tek seferlik bir üyeliktir. Bu, fırsata erişim için alınan bir ücret değildir. Bu bir eşiktir — istekli hiçbir katılımcının dışarıda kalmayacağı kadar küçük, girişin sürüklenerek değil bilinçli seçilerek yapılacağı kadar kararlı. Bu eşikten itibaren her katılımcı rotasyona aittir ve rotasyon tek bir bölgeye değil, hepsine birden aittir.

Eğitim müfredatı birçok kültürdeki disiplinli simülasyon geleneklerinden beslenir — Sun Tzu'nun stratejik eğitim geleneğinden, Musashi'nin oyun yoluyla pratiğinden, İbn Haldun'un döngüsel öğrenme kuramından, Nalanda'nın manastır diyalektiğinden, sivil uçuş simülatöründen — her bilişsel aşamayı ve kültürel mirası gözetecek şekilde harmanlanmıştır. Tek bir gelenek baskın değildir. Ve bu müfredat içinde antlaşma, her katılımcının erken öğrendiği ve asla unutmadığı bir çizgi çizer: simülasyon, Qualified Innovation Score'un anlaşıldığı yerdir, harcandığı yer değil. QIS bir ölçümdür, asla bir ödeme değildir ve QIS asla mülkiyet değildir — bir önerinin ne kadar iyi akıl yürüttüğünü, ayakta kaldığını ve hizmet ettiğini iddia ettiği bölgeye ne kadar iyi hizmet ettiğini tanımlamak için vardır. QIS'teki büyüme, gerçek nitelik kazanmadan sonra bir ödül havuzunun büyüklüğünü belirleyebilir, ama tek başına hiçbir şey basmaz. Bir katılımcı yüz kusursuz simülasyon çalıştırıp yükselen bir puan kazanabilir, ama defterine tek bir saat 웃 bile dokunmaz; çünkü 웃 yalnızca kapsamı belirlenmiş, bütçesi onaylanmış bir görev altında tanıklık edilen emek için verilir. Bu onaydan önce her şey — ne kadar becerikli, ne kadar umut vadedici olursa olsun — planlamadır. Antlaşma bu ayrımı ilk günden öğretir, böylece hiçbir genç insan provayı ödülle karıştırmaz ve hiçbir genç insan simülasyonun ne için olduğu konusunda asla yanıltılmaz.

Bu aynı disiplin, ister insan ister yapay olsun, herhangi bir sistemin rotasyon içinde ne kadar özerklik kullanmasına izin verildiğini de yönetir. Antlaşmanın işletim modları sırayla ilerler — önce Manuel, sonra Yarı Otomatik, sonra Otonom — ve hiçbir küp, donmuş bir taban çizgisine karşı kanıtlanmış ve iddia edilmek yerine tanıklıkla doğrulanmış, dokuzda bir oranındaki yüzde 11,1 ölçülen-iyileştirme kuralını aşana kadar bir sonraki moda geçmez. Bu kanıtın inşa edildiği yer simülasyondur. Bir araç, daha az gözetimle hareket etme hakkını, tıpkı bir katılımcının daha büyük sorumluluk hakkını kazandığı şekilde kazanır: gösterilmiş, kayıt altına alınmış, yeniden inşa edilebilir iyileştirme yoluyla, küp küp, asla hepsi bir anda değil ve asla anlamın, paranın ve hukukun karara bağlandığı katman üzerinde değil. O katman, hem simülasyonda hem de canlı işletimde yalnızca Human Authority'ye aittir; çünkü yanlış sınırı öğreten bir prova alanı, yanlış dersi kalıcı olarak öğretir.

Her rotasyon, ev sahibi topluluğa açık, kamuya açık ve işbirlikçi bir kutlamayla sona erer. Komşular, aileler ve ziyaretçiler, topluluğun neler öğrendiğini görmek için bir araya gelir ve tanıklık ettikleri şey, kendi başına hız gösterisi değil, ◬'nin gösterimidir — donmuş bir taban çizgisi ile disiplinli pratiğin fiilen başardığı şey arasındaki ölçülen fark, dürüstçe sunulur, asla bir kârlılık ölçütü kılığına sokulmaz, asla olduğundan fazlaymış gibi sunulmaz. Bu etkinlikler, gelişmiş teknolojiyi korkutucu olmaktan çıkarıp erişilebilir ve kutlanan bir şeye dönüştürür. İşbirlikçi sistemleri oyun yoluyla anlayarak büyüyen bir toplum, bu sistemlere duyulan korkuyla kolayca manipüle edilemez. Bu, güç yoluyla değil eğitim yoluyla caydırıcılıktır ve işe yaramasının nedeni, topluluktan bir iddiaya güvenmesinin istenmemesidir — topluluk, Replay'i izlemeye davet edilir.

Antlaşmanın her ebeveyne verdiği söz, güvenliğin ötesine, kalıcılığa uzanır: çocuğunuz, kendisine zarar verebilecek herhangi bir şeye dokunmadan önce bin kez pratik yapacak, topluluk bu süreç boyunca büyümesine tanıklık edecek ve hiçbiri zamana kaybolmayacaktır. Measurement of Time, gerçek dakikaları antlaşmanın tuttuğu diğer her defterden ayrı kaydeder; böylece pratik yapılan saatler ile tanıklık edilen saatler asla birbirine karıştırılmaz ve bir katılımcının gerçek gelişim geçmişi — bir özet değil, bir yaklaşık değer değil, yeniden inşa edilebilir kaydın kendisi — o katılımcı danışmak istediği sürece erişilebilir kalır. Phnom Penh'teki bir ebeveyn, Tegucigalpa'daki bir mentor, Austin'deki bir denetçi ya da bir yüzyıl sonra kaydı okuyan bir torun, hepsi aynı Replay'e ulaşabilir ve aynı gerçeği görebilir.

Genç insana duyulan saygının, bir çerçeve tarafından yalnızca vaat edilmek yerine ona mühendislik ürünü olarak işlendiğinde nasıl göründüğü budur ve liderliğin, bir sonraki katılımcı nesline, o nesil bunu talep etmek zorunda kalmadan önce teslim ettiği şey de budur: güvenle başarısız olunabilecek kadar geniş, sadakatle kayıt tutacak kadar dürüst ve ödülü, özerkliği ve yetkiyi tam olarak ustalığın hak ettiği yerde tutacak kadar disiplinli bir prova alanı — ne onun ilerisinde, ne de gerisinde.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Güven Uzatılmadan Önce Doğrulanan Güvenlik`,
    content: {
      7: `Önce güvenlik kanıtlanır, sonra güven uzatılır.`,
      33: `Her tesis ve rotasyon, erken uyarı kapasitesine sahip koruyucu bir zarf içinde yer alır. Donanım silahlaştırılmayı reddeder — vaat edilmiş değil, kanıtlanmış, vatandaşlarca denetlenebilir. Kayıtlar türbülansı atlatır. Güvenlik, her gün en genç katılımcı etrafında mühendislikle tasarlanır.`,
      111: `Güven verilmeden önce güvenlik kanıtlanmalıdır — bir hükümete değil, onu denetleyen herhangi bir vatandaşa. Atlantis Antlaşmaları dünya vatandaşları arasında bir anlaşmadır; kurucu taahhüdü şudur: her antlaşma tesisi, her rotasyon güzergâhı, genç bir katılımcının uyuduğu veya çalıştığı her yer, topluluğa herhangi bir güvenilir riske yanıt vermek için dakikalar değil saatler tanıyan, erken uyarı kapasitesine sahip belgelenmiş bir koruyucu zarf içinde yer alır. Her cihaz, her sensör, her koordinasyon sistemi, donanım katmanında, silah sistemleri entegrasyonu için yeniden amaçlandırılmayı reddedecek şekilde bağlanmıştır. Bu bir politika değildir — bu fiziktir. Antlaşma türbülans içinde de onurlu kalır, çünkü her plan insan onurunu önce koyar.`,
      333: `Güven verilmeden önce güvenlik kanıtlanmalıdır — vatandaşlara kanıtlanmalı, yalnızca iddia edilmemelidir. Atlantis Antlaşmaları dünya vatandaşları arasında bir anlaşmadır: hükümeti ne imzalarsa imzalasın, dünyanın herhangi bir yerindeki herhangi bir kişi onu sahiplenmeye yardımcı olabilir. Her antlaşma tesisi, her rotasyon güzergâhı, genç bir katılımcının uyuduğu veya çalıştığı her yer, topluluğa herhangi bir güvenilir riske yanıt vermek için dakikalar değil saatler tanıyan, erken uyarı kapasitesine sahip belgelenmiş bir koruyucu zarf içinde yer alır. Onları koruyan teknoloji, antlaşmanın onlara inşa etmeyi öğrettiği teknolojinin ta kendisidir. Gençler güvenliği içeriden dışarıya doğru öğrenir — güvende olduklarının söylenmesiyle değil, bunun her gün etraflarında mühendislikle tasarlandığını görerek ve herhangi bir vatandaşın kaydı Replay aracılığıyla doğrulayabileceğini bilerek.

Antlaşma, teknolojisinin ne olamayacağı konusunda kırılmaz bir söz verir. Her cihaz, her sensör, her koordinasyon sistemi, donanım katmanında, silah sistemleri entegrasyonu için yeniden amaçlandırılmayı reddedecek şekilde bağlanmıştır. Bu bir politika ifadesi değil, bir özlem değildir. Bu, kriptografik olarak uygulanan, her imzacı bölge tarafından doğrulanan ve onu finanse eden her vatandaş tarafından denetlenebilir olan fiziksel bir imkânsızlıktır. Phnom Penh'teki bir çocuğu koruyan araçlar, Austin'deki bir çocuğa zarar vermek üzere yeniden amaçlandırılamaz. Tegucigalpa'daki bir sürü alıştırmasını birbirine bağlayan araçlar, herhangi bir yerde bir insanı hedef alacak şekilde yeniden yapılandırılamaz. Bu, antlaşmanın bir yüzyıllık çifte kullanım korkusuna verdiği yanıttır. Politika değil — fizik.

Antlaşma türbülans içinde de onurlu kalır. Bir bölge siyasi istikrarını kaybederse, katılımcılar kalan bölgeler tarafından desteklenir. Finansman daralırsa, ödenekler önce korunur — vatandaşlar tarafından aylık olarak finanse edilir, asla bir yardım hattı değildir, her dolar izlenebilir. Dijital kayıtlara saldırılırsa, çevrimdışı yedeklemeler kalıcılığını korur. Seyahat imkânsız hale gelirse, alt yapı sanal olarak devam eder. Her plan, insan onurunu — anlam, para ve hukuk üzerindeki Human Authority'yi — ilk tasarım kısıtı olarak koyar. Bu antlaşmayı imzalayan liderler, güvenliğin varsayılan değil mühendislikle tasarlanmış olduğuna söz verir: herhangi bir liderin kendi çocuğu için talep edeceği koruma, şimdi onu sahiplenmeye yardımcı olan her vatandaşa genişletilmiştir.`,
      999: `Güven verilmeden önce güvenlik kanıtlanmalıdır — bu, Atlantis Antlaşmaları'nın kurucu taahhüdüdür ve Vision • 2525 içindeki diğer her iddianın kanıtlandığı şekilde kanıtlanır: iddiayla değil, vatandaşların denetleyebileceği kanıtla. Her antlaşma tesisi, her rotasyon güzergâhı, genç bir katılımcının uyuduğu veya çalıştığı her yer, topluluğa herhangi bir güvenilir riske yanıt vermek için dakikalar değil saatler tanıyan, erken uyarı kapasitesine sahip belgelenmiş bir koruyucu zarf içinde yer alır. Katılımcıları korumak için kullanılan teknoloji, antlaşmanın onlara inşa etmeyi öğrettiği teknolojinin ta kendisidir — sensörler, koordinasyon, iletişimin hayatta kalabilirliği, dağıtık zekâ. Gençler güvenliği içeriden dışarıya doğru, kendi dillerinde ve kendi bölgelerinde öğrenir — güvende olduklarının söylenmesiyle değil, güvenliğin her gün etraflarında saat saat nasıl mühendislikle tasarlandığını izleyerek.

Bu izleme, hafızaya ya da bir kolaylaştırıcının sözüne duyulan güvene bırakılmaz. Measurement of Time, her tatbikatın, her rotasyonun, her müdahale alıştırmasının gerçek dakikalarını — herhangi bir ilerleme iddiasından ayrı, o gün anlatılan herhangi bir hikâyeden ayrı olarak — kaydeder. Replay, eğitim müfredatının her yayınını, her güvenlik güncellemesini, her donanım revizyonunu tamamen yeniden inşa edilebilir kılar; böylece Tegucigalpa'daki bir ebeveyn ya da Phnom Penh'teki bir düzenleyici, tam olarak neyin, ne zaman ve neden değiştiğini geriye doğru izleyebilir. Yeniden oynatılamayan bir koruyucu zarf yalnızca bir vaattir. Kayıtlı dakika dakika yeniden oynatılabilen bir koruyucu zarf ise bir kanıttır. Antlaşma kanıtı seçer.

Antlaşma, teknolojisinin ne olamayacağı konusunda kırılmaz bir söz verir. Her cihaz, her sensör, her koordinasyon sistemi, donanım katmanında, silah sistemleri entegrasyonu için yeniden amaçlandırılmayı reddedecek şekilde bağlanmıştır. Bu bir politika ifadesi değil, bir özlem değildir. Bu, kriptografik olarak uygulanan, her imzacı bölge tarafından doğrulanan ve her vatandaş tarafından denetlenebilir olan fiziksel bir imkânsızlıktır. Phnom Penh'teki bir çocuğu koruyan araçlar, Austin'deki bir çocuğa zarar vermek üzere yeniden amaçlandırılamaz. Tegucigalpa'daki bir sürü alıştırmasını birbirine bağlayan araçlar, herhangi bir yerde bir insanı hedef alacak şekilde yeniden yapılandırılamaz. Bu, antlaşmanın bir yüzyıllık çifte kullanım korkusuna verdiği yanıttır. Politika değil — fizik.

Bir kez kanıtlanmış güvenlik, beş yüz yıllık bir ufuk boyunca sürdürülen güvenlik değildir. Antlaşma ikinci taahhüdünü Continuity Without Evasion olarak adlandırır: antlaşmanın dokunduğu her yargı alanında yasal taşınabilirlik, hiçbir tek vazgeçilmez hükümetin, bankanın, kurucunun ya da modelin bir katılımcı ile koruması arasında durmaması. Her yargı alanına kendi bağdaştırıcısı hizmet verir; arıza durumunda kapanan ve varsayılan olarak reddeden bu bağdaştırıcı sayesinde, herhangi bir bölgedeki olumsuz bir karar yalnızca o kanalı kapatır — asla çerçevenin tamamını, asla her bölgeyi, asla her yerdeki her katılımcıyı aynı anda değil. Bir imzacı bölgedeki mahkeme kararı, başka bir yerdeki katılımcının güvenlik zarfını kapatamaz. Bir katılımcıdan korunmaya devam etmek için hukuku ihlal etmesini asla istemeden, hukukun, siyasetin ve kurumsal değişimin olağan türbülansından sağ çıkan bir sistem inşa etmek budur.

Bu koruyucu mimarinin her katmanı, sonuçta Human Authority'ye hesap verir. Anlam, para ve hukuk asla makinelere devredilmez — güvenliğin neyi gerektirdiğine, neyin güvenilir bir risk sayıldığına ve bir topluluğun en genç üyelerine ne yanıt borçlu olduğuna karar veren egemen katman, yapay zekâ ne kadar yetkin hale gelirse gelsin ona kapalı kalır. Antlaşmanın sistemleri yalnızca üç işletim modundan geçer — Manuel, Yarı Otomatik, Otonom — ve hiçbir sistem, dokuzda birde, yani yüzde on bir virgül birde en az doğrulanmış, tekrarlanabilir, tanıklıkla ölçülmüş bir iyileştirme olmadan bir sonraki moda geçmez. Özerklik, küp küp, işlev işlev kazanılır, asla toptan verilmez ve anlamı, parayı ya da hukuku belirleyen sorular üzerinde bir kez bile genişletilmez. Bir sensör daha hızlı algılamayı öğrenebilir. Bir koordinasyon sistemi daha verimli yönlendirmeyi öğrenebilir. Ama hiçbiri, bir topluluğun çocuklarıyla ilgili neye güveneceğine tek başına karar vermesine asla izin verilmez.

Antlaşma, türbülans içinde de onurlu kalacak şekilde tasarlanmıştır ve türbülansı krizde keşfetmek yerine önceden adlandırır. Bir imzacı bölge siyasi istikrarını kaybederse, katılımcılar kalan bölgeler tarafından desteklenir. Finansman daralırsa, katılımcı ödenekleri, yönetim ve altyapıdan önce ilk sırada korunur. Dijital kayıtlara saldırılırsa, ağa ulaşan her ne arıza olursa olsun erişilemez kalan çevrimdışı yedeklemeler kalıcılığını korur. Seyahat imkânsız hale gelirse, alt yapı sanal olarak devam eder; böylece bir sınırın kapanması bir rotasyonu durdurmaz. Her senaryo için plan yapılmıştır ve her plan, insan onurunu — bütçeler ve görünüm netleştikten sonra düşünülecek son mesele olarak değil — ilk tasarım kısıtı olarak koyar.

Bu kanıtlanmış sisteme giriş, Seed ile başlar — yerel asgari ücretin bir saatinin yedide biri fiyatına, devredilemez ve antlaşmanın daha sonra inşa edeceği hiçbir şey üzerinde ekonomik hak talebi taşımayan, tek seferlik bir üyelik. Seed güvenliği satın almaz; güvenlik, herhangi bir Seed dikilmeden çok önce mühendislikle tasarlanmıştır. Seed'in satın aldığı şey statüdür — zaten kanıtlanmış, zaten denetlenmiş ve korumak için var olduğu kişinin aleyhine asla çevrilemeyecek donanımla zaten bağlanmış bir çerçeveye girme hakkı. Bu ayrım bilinçlidir. Gerçek bir ekonomik ağırlıkla satın alınması gereken bir güvenlik vaadi, hiç de bir güvenlik vaadi değildir, yalnızca bir güvenlik ürünüdür. Antlaşma bu ikisini kesin biçimde ayrı tutar; böylece hiçbir aile, çocuğunun korunmasını hane bütçesinin aylık dengesiyle tartmak zorunda kalmaz.

Bu antlaşmayı imzalayan liderler, güvenliğin varsayılan değil mühendislikle tasarlanmış, yalnızca iddia edilmiş değil kanıtlanmış olduğuna dair bir söz imzalar. Vatandaşlarına genişlettikleri şey yalnızca fırsat değil, en genç katılımcının hak ettiği standartta inşa edilmiş bir korumadır — Measurement of Time tarafından kaydedilen, Replay aracılığıyla yeniden inşa edilebilen, korkulu bir yüzyılın hayal edebileceği her kötüye kullanıma karşı donanım katmanında bağlanmış ve her zaman ve yalnızca Human Authority'ye hesap veren bir koruma. Bu, her liderin yabancı bir sınırı tek başına geçen kendi çocuğu için talep edeceği aynı korumadır; şimdi antlaşmanın hizmet edeceği her çocuğa, üç kurucu bölgesi Kamboçya, Honduras ve Austin boyunca ve antlaşmanın bu sözü tutmayı amaçladığı beş yüzyıl boyunca genişletilmiştir.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Ödüllendirme, Esenlik ve İnsan Onuru`,
    content: {
      7: `Bir burs, bir mentor, bir yuva.`,
      33: `Her vatandaş ilk günden itibaren bir ödenek alır — ne bir hükümetin izni ne de bir işverenin onayı gerekir. Sevgi, kayıp ve güvenlik birer altyapıdır. Başarı, en savunmasız olanla ölçülür. Onur bir alt katmandır, asla süsleme değil.`,
      111: `Atlantis Antlaşmaları her katılımcıya ilk günden itibaren bir insan olarak davranır — hükümet kararnamesiyle değil, işveren izniyle değil, hak ile katılan bir vatandaş olarak. Katılım başladığı andan itibaren, bölgenin yaşam maliyetine endekslenmiş bir ödenek sağlanır ve tanıklık edilen her saat 웃 kazandırır; bu, bir işverenin defteri üzerinden değil, Livelihood Direct aracılığıyla doğrudan kişiye ödenir. Refah, birinci sınıf bir altyapı olarak ele alınır — bir ayrıcalık değil, her şeyin üzerinde durduğu alt katman. Üç alan desteklenir: Sevgi, Kayıp ve Güvenlik. Antlaşma başarıyı ortalamayla değil, en savunmasız katılımcısıyla ölçer. Ortalamalar iyi görünsün diye kimse unutulmaz. Onur bir alt katmandır, süsleme değil.`,
      333: `Atlantis Antlaşmaları her katılımcıya ilk günden itibaren bir insan olarak davranır — ne bir hükümetin izni ne de bir işverenin onayı gerektirmeksizin, hak ile ait olan bir vatandaş olarak. Katılım başladığı andan itibaren, bölgenin yaşam maliyetine endekslenmiş bir ödenek sağlanır ve aile yükümlülükleri acil duruma dönüşmeden önce ulaşır. Bu bir hayırseverlik değildir. Bu, sıradan insan yenilikçiliğinin önce insani güvenlik gerektirdiğinin kabulüdür — bir zihin, hanesi tehdit altındayken gelişemez.

Ödeneğin ötesinde kazanılan şey, bir vatandaşın kazandığı şekilde kazanılır: yerel asgari ücretin bir saatinin yedide biri fiyatına Seed aracılığıyla ve yalnızca tanıklık edilen saatler için ödenen 웃 aracılığıyla. QIS vaadi ölçer ama hiçbir şey basmaz — bir ölçümdür, asla bir ödeme değildir. Her ödeme, katılımcıya, antlaşmanın asla gözetim altında tutmadığı, Continuity Without Evasion için inşa edilmiş lisanslı yerel kanallar olan Livelihood Direct aracılığıyla ulaşır.

Refah, birinci sınıf bir altyapı olarak ele alınır — bir ayrıcalık değil, her şeyin üzerinde durduğu alt katman. Antlaşma, her katılımcının desteklendiği üç alanı adlandırır: Sevgi — bağ ve sağlıklı sınır; Kayıp — çünkü yasla etrafından değil, birlikte yürünmelidir; ve Güvenlik — her bölgede, kendi dilinde, kimi arayacağını bilmek. Danışmanlık, grup çemberleri ve her geleneğe göre onurlandırılan kültürel ya da manevi pratikler sağlanır. Sıfır dayatılan ideoloji; bir vatandaşın hangi bakıma ihtiyaç duyduğuna asla bir makine değil, Human Authority karar verir.

Antlaşma başarıyı ortalamayla değil, en savunmasız katılımcısıyla ölçer. Yüksek bant genişliği olmayan kırsal vatandaşlara hizmet verilir. Nörofarklı katılımcılar, norm olarak uyarlama alır. Engelli katılımcılar için her tesis erişilebilirdir. Cinsiyet çeşitliliğine sahip katılımcılar güvenli barınma ve mentor eşleştirmesi alır. Ana dili farklı olan katılımcılar her belgeyi kendi dillerinde bulur. Yerli katılımcılar, kültürel pratiklerinin onurlandırıldığını ve geleneksel bilgilerinin korunduğunu görür. Bu antlaşmayı imzalayan liderler, ortalamalar iyi görünsün diye hiçbir vatandaşın unutulmayacağına söz verir. Bu, süsleme değil, alt katman olarak onurdur. Ölçülen şey, onurlandırılacak şeydir ve burada onurlandırılan, istisnasız olarak diğer vatandaşlarca sahiplenilen bütün insandır — zihin, beden ve ruh.`,
      999: `Atlantis Antlaşmaları her katılımcıya ilk günden itibaren, yalnızca sözde değil mekanizmaya işlenmiş biçimde, tam bir insan olarak davranır. Katılım başladığı andan itibaren, etkisi yerel iş onurunu gözetsin diye bölgenin yaşam maliyetine endekslenmiş bir ödenek sağlanır. Ödenek, aile yükümlülükleri acil duruma dönüşmeden ve onur zedelenmeden önce ulaşır. Bu, her genç insana zamanının değerli olduğu, katkısının beklendiği ve ailesinin istikrarının antlaşmanın sorumluluğunun bir parçası olduğu sinyalini verir. Bu bir hayırseverlik değildir. Bu, sıradan insan yenilikçiliğinin önce insani güvenlik gerektirdiğinin kabulüdür. Bir zihin, hanesi tehdit altındayken gelişemez. Girişin kendisi küçük, bilinçli bir eşik taşır: yerel asgari ücretin bir saatinin yedide biri fiyatına, devredilemez ve kendine ait hiçbir ekonomik hak talebi taşımayan, tek seferlik bir üyelik olan Seed. Seed yalnızca bir kişinin katıldığını söyler; ne ödeme yapar ne de açtığı kapının ötesinde bir şey vaat eder.

O kapı açıldıktan sonra kazanılan şey, antlaşmanın diğer her vaadine getirdiği aynı hassasiyetle yönetilir. Antlaşmanın Human Intelligence ölçütü olan 웃, basitçe hesaplanır — yerel asgari ücretle bir saat, görevin zorluğunu ve değerini yansıtan Multiple ile çarpılır, ardından fiilen çalışılan saatlerle çarpılır. Ama 웃 yalnızca kapsamı belirlenmiş, bütçesi onaylanmış bir görev altında tanıklık edilen emek için verilir. Bu onay var olmadan önce bir katılımcının yaptığı şey kazanmak değil planlamaktır — antlaşmanın sıkı biçimde koruduğu bir ayrım, çünkü bu ayrım hem hazineyi hem de katılımcıyı, değer doğrulanmadan önce yapılan vaatlerden korur. Measurement of Time, yani MoT, çalışılan gerçek dakikaları herhangi bir ücret hesaplamasından ayrı olarak kaydeder; böylece zaman, ödemeden bağımsız, dürüst ve denetlenebilir bir gerçek olarak kalır. Hiçbir katılımcının saatleri şişirilmez ve hiçbir katılımcının saatleri yok olmaz. Her katılımcı için yıllık 9.999 웃'luk bir ödeme tavanı uygulanır; fazlası kaybolmak yerine bir sonraki yıla devreder, böylece olağanüstü katkı bir yıl içinde görünmezliğe hapsedilmek yerine yıllar boyunca tanınır.

Ücretlendirme, yenilikçiliğin ölçümünden bilinçli olarak ayrı tutulur. Qualified Innovation Score, yani QIS, yenilikçiliğin gerçekte ne kadar büyüdüğünü tanımlamak için Gelir, Brüt Kâr, Faaliyet Geliri ve Etkin Ar-Ge harcamasının ortalamasını alır. Zaman içindeki büyümesi, nitelik kazanma sağlandıktan sonra bir ödül havuzunun büyüklüğünü belirleyebilir, ama QIS'in kendisi ne 웃 basar ne de doğrudan bir şey öder — bir ölçümdür, asla bir ödeme değildir ve asla inşa edilen şeyin mülkiyetiyle karıştırılmaz. Bu ayrım önemlidir çünkü ödeneği ve ücreti dürüst tutar: bir katılımcıya, oyuna getirilebilecek, şişirilebilecek ya da tartışmaya açık bir puan için değil, gerçek işin tanıklık edilen saatleri için ödeme yapılır. ♡, Shared Intention, bir katılımcının üstlendiği her görevin arkasındaki nedeni taşır; bir görevin donmuş bir taban çizgisine karşı sağladığı, tanıklık edilmiş hızlanma olan ◬ ise yalnızca bir fark olarak kaydedilir, asla bir kişinin emeğine iliştirilmiş bir kârlılık ölçütü kılığına sokulmaz. Ücretlendirme olduğu şey olarak kalır: dürüst, tanıklık edilmiş zaman için dürüst bir ücret.

Değer hesaplamada durmaz — yaşayan bir kişi olarak katılımcıya da ulaşmalıdır ve 🏠, Livelihood Direct'in işini yaptığı yer burasıdır. Bir katılımcının kazandığı her değer birimi, ona nitelikli, lisanslı yerel kanallar aracılığıyla ulaşır — bankalar, mobil para operatörleri, o bölgede zaten güvenilir ve düzenlenmiş kooperatifler — asla antlaşmanın kendisinin gözetim altında tuttuğu ya da kontrol ettiği bir fon aracılığıyla değil. Bir katılımcının statüsünün sınıflandırılması her zaman ödemeden önce gelir; kimin ne için ödeme aldığı doğru biçimde anlaşılmadan hiçbir ödeme yapılmaz. Ve yetenek tanınması, ne kadar kutlanırsa kutlansın, bir yatağa, bir yemeğe ya da topluluktaki bir yere erişimin kapısını açmaz — yalnızca katılımcının fiilî rolü açar. Bu, prestijin sağlanan hizmetin yerine geçmesine izin vermeme konusunda bilinçli bir reddir. Parlak bir katkı sunan ile sessiz biri, aynı korunaklı çatı altında, aynı koşullarda uyur; çünkü antlaşmanın onur taahhütleri mükemmellik için verilen bir ödül değildir — herkesin altındaki bir tabandır.

Refah, birinci sınıf bir altyapı olarak ele alınır — isteğe bağlı bir fayda ya da bir sağlık ayrıcalığı değil, geri kalan her şeyin üzerinde durduğu alt katman. Antlaşma, her katılımcının desteklendiği üç temel alanı adlandırır: Sevgi — bağ, bağlanma ve sağlıklı sınır anlamında; Kayıp — çünkü her katılımcı yas yaşayacak ve bu yasla etrafından değil birlikte yürünmelidir; ve Güvenlik — her katılımcının, her bölgede, kendi dilinde kimi arayacağını bilmesi anlamında. Bireysel danışmanlık, grup çemberleri, bedensel pratikler ve katılımcının kendi geleneğine göre onurlandırılan kültürel ya da manevi pratikler sağlanır. Sıfır dayatılan ideoloji. Antlaşma bu alanı saygıyla tutar; hiçbir inanç sistemini vaaz etmez. Human Authority bu kararların her birini yönetir — karar veren insanlara yardımcı olan örüntü eşleştirmesi ne kadar gelişmiş olursa olsun, anlam, para ve hukuk makine belirlemesine kapalı kalır.

Antlaşma başarıyı ortalamayla değil, en savunmasız katılımcısının sonucuyla ölçer. Yüksek bant genişliği olmayan kırsal katılımcılara hizmet verilir. Nörofarklı katılımcılar, norm olarak uyarlama alır. Engelli katılımcılar için her tesis erişilebilirdir. Cinsiyet çeşitliliğine sahip katılımcılar güvenli barınma ve mentor eşleştirmesi alır. Ana dili farklı olan katılımcılar her belgeyi kendi dillerinde bulur. Yerli katılımcılar, kültürel pratiklerinin onurlandırıldığını ve geleneksel bilgilerinin korunduğunu görür. Bu antlaşmayı imzalayan liderler, ortalamalar iyi görünsün diye hiçbir katılımcının sessizce unutulmayacağına söz verir.

Burada anlatılan her ödeme yolu — Seed, ödenek, tanıklık edilen emek üzerinde kazanılan 웃, bunu teslim eden Livelihood Direct kanalı — Continuity Without Evasion için tasarlanmıştır. Hiçbir tek banka, hükümet ya da yerel operatör, herhangi bir katılımcının ücretlendirmesi için vazgeçilmez değildir; bir yargı alanındaki lisanslı bir kanal olumsuz bir kararla kapatılırsa, yalnızca o kanal başarısız olur, asla sistemin tamamı değil ve asla katılımcının hak ettiği şey üzerindeki talebi değil. Bu, süsleme değil, alt katman olarak onurdur. Ölçülen şey, onurlandırılacak şeydir ve burada onurlandırılan, dürüstçe ödenen, tamamen korunan ve hiçbir muhasebe tarafından, istisnasız biçimde unutulmayan bütün insandır — zihin, beden ve ruh birlikte.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finansman ve Yönetişim`,
    content: {
      7: `Vatandaşlar sonraki nesli doğrudan finanse eder.`,
      33: `Atlantis Antlaşmaları vatandaşlar arasında bir anlaşmadır — herkes onu finanse edebilir ve sahiplenebilir. Yardım hattı yok, yabancı bağışçı yok, siyasi bağ yok. Her dolar izlenebilir, muhasebe her dilde aylık olarak yayımlanır.`,
      111: `Atlantis Antlaşmaları dünya vatandaşları arasında bir anlaşmadır — hükümeti ne imzalarsa imzalasın, işvereni kim olursa olsun, dünyanın herhangi bir yerindeki herhangi bir kişi onu kurmaya ve sahiplenmeye yardımcı olabilir. Hükümetler, eğitimciler ve yenilikçiler bölgelerinin vasisi olarak imzalar; antlaşmayı finanse eden, tanıklık eden ve onu doğrudan hesap verebilir kılan vatandaşlardır — her biri her ay, hiçbir yetişkinin dışarıda kalmayacağı kadar mütevazı, küçük gönüllü tutarlar katkıda bulunur. Hiçbir yardım hattı, hiçbir yabancı bağışçı, hiçbir siyasi bağ yoktur. Antlaşma, geçen yüzyılı biçimlendiren çok taraflı kurumlardan bağımsız durur — bu bir siyasi tutum değil, bir tasarım tercihidir. Her dolar izlenebilir; her muhasebe her dilde aylık olarak yayımlanır.`,
      333: `Atlantis Antlaşmaları dünya vatandaşları arasında bir anlaşmadır — hükümeti ne imzalarsa imzalasın, işvereni kim olursa olsun, dünyanın herhangi bir yerindeki herhangi bir kişi onu kurmaya ve sahiplenmeye yardımcı olabilir. Hizmet ettiği vatandaşlar tarafından finanse edilir: katılımcı bölgelerin sakinleri her ay, hiçbir yetişkinin dışarıda kalmayacağı kadar mütevazı, toplamı antlaşmanın çalışmasını ölçekte sürdürecek kadar da anlamlı, küçük gönüllü tutarlar katkıda bulunur. Bir vatandaş bir sonraki nesli doğrudan finanse ettiğinde, o vatandaş antlaşmayı doğrudan hesap verebilir kılar. Hiçbir yardım hattı, hiçbir yabancı bağışçı, hiçbir siyasi bağ yoktur. Antlaşmanın ruhu, her ay küçük bir tutar katkıda bulunan, katılımı bunu mümkün kılan vatandaştır.

Hükümet, Eğitim ve İnovasyon, bölgelerinin vasisi olarak imzalar — bir bölgeyi barındırmaya, korumaya ve öğretmeye bağlayan üç vizyoner imza — ama vesayet mülkiyet değildir. Antlaşma, geçen yüzyılı biçimlendiren çok taraflı kurumlardan bağımsızdır — Kuzey Atlantik Antlaşması Örgütü, Dünya Sağlık Örgütü, Birleşmiş Milletler, Uluslararası Para Fonu, Dünya Bankası ve her ulusal dış yardım kanalı. Bu bir siyasi tutum değil, bir tasarım tercihidir: jeopolitik uyumdan bağımsız olarak her bölgeye hizmet eden bir çerçeve, herhangi bir uyumla iç içe geçemez. Ulusal hükümetler gönüllü olarak katkıda bulunabilir. Katkılar şeffaftır. Hiçbir katkı, hiçbir kaynaktan, hiçbir zaman yönetişim etkisi satın almaz.

Antlaşmaya giren her dolar ve her değer birimi kalıcı, kamuya açık ve izlenebilir biçimde kaydedilir — Replay aracılığıyla yeniden inşa edilebilir, böylece bir yüzyıl sonra bir vatandaş zincirin kesintisiz olduğunu doğrulayabilir. Değer, bir katılımcıya tanıklık edilen 웃 saatleri ve lisanslı yerel kanallar aracılığıyla ulaşır, asla antlaşmanın kendisinin gözetim altında tuttuğu bir fon aracılığıyla değil; QIS dürüstçe ölçer, asla ödeme yapmaz. İdari giderler sınırlandırılmıştır, kurumsal bağışlar da bununla birlikte sınırlandırılmıştır. Tam muhasebe, her imzacı bölgenin dilinde her ay teslim edilir. Antlaşmayı imzalayan liderler, herhangi bir kurumun nadiren sunduğu bir şeffaflığa söz verir. Antlaşmanın gerektirdiği güven budur — her vatandaşın gözü önünde, seferinde küçük, izlenebilir bir katkıyla kazanılır.`,
      999: `Atlantis Antlaşmaları'nın kendisi, hizmet ettiği vatandaşlar tarafından finanse edilir ve bu tek gerçek, bundan sonra gelen her şeyi biçimlendirir — her kanal, her defter, genç bir insanın görülmek için geçmesi gereken her kapı. Katılımcı bölgelerin sıradan sakinleri her ay, hiçbir bölgede hiçbir yetişkinin katılımın dışında kalmayacağı kadar mütevazı, toplamı antlaşmanın çalışmasını anlamlı bir ölçekte sürdürecek kadar da anlamlı, küçük gönüllü tutarlar katkıda bulunur. Bu tasarım bilinçlidir ve misyona tesadüfi eklenmiş bir şey değildir — misyonun kanıtıdır. Bir vatandaş bir sonraki neslin eğitimini doğrudan finanse ettiğinde, o vatandaş, hesabı yumuşatabilecek ya da hesaplaşmayı erteleyebilecek bir aracı olmaksızın, aynı nefeste antlaşmayı doğrudan hesap verebilir kılar. Çekin arkasında hiçbir yardım hattı, hiçbir yabancı bağışçı, hiçbir siyasi bağ yoktur. Antlaşmanın ruhu, her ay küçük bir tutar katkıda bulunan, katılımı bütünü mümkün kılan ve sürekli katılımı beş yüz yıl boyunca nihayetinde önemli olan tek güven oyu olan vatandaştır.

Antlaşma, geçen yüzyılı biçimlendiren çok taraflı kurumlardan bilinçli olarak bağımsızdır — Kuzey Atlantik Antlaşması Örgütü, Dünya Sağlık Örgütü, Birleşmiş Milletler, Uluslararası Para Fonu, Dünya Bankası ve her ulusal dış yardım kanalı. Bu, o kurumların değeri ya da katkıları hakkında siyasi bir tutum değildir. Bu bir tasarım tercihidir ve antlaşmanın kendisinin altındaki her teknik kanalı yöneten aynı tasarım tercihidir: Continuity Without Evasion. Yasal taşınabilirlik kuraldır — hiçbir tek vazgeçilmez hükümet, banka, kurucu ya da model, yapının tamamının altında oturamaz; çünkü beş yüz yıllık bir ufuk, tek bir aktörün kalıcılığına bağlanamaz. Her yargı alanı kendi bağdaştırıcısını taşır; arıza durumunda kapanan ve varsayılan olarak reddeden bu bağdaştırıcı sayesinde, bir ulustaki olumsuz bir karar yalnızca ve tek başına o kanalı kapatır — bir okyanus ötesindeki bir bölgede bir ailenin hesaplarını asla çökertmez. Ulusal hükümetler gönüllü olarak katkıda bulunabilir. Katkılar şeffaftır. Hiçbir katkı, hiçbir kaynaktan — ne bir hükümetten, ne bir şirketten, ne de çerçevenin kendi kurucularından — hiçbir zaman yönetişim etkisi satın almaz.

Human Authority, bu finansman tasarımının altındaki ikinci taşıyıcı sütundur. Anlam, para ve hukuk insani meseleler olarak kalır; başka insanların gözü önünde insanlar tarafından karara bağlanır — antlaşmanın amacının belirlendiği ve fonlarının yönetildiği egemen katman, altındaki görevlerde ne kadar yetkin hale gelirlerse gelsinler makinelere kapalı kalır. Measurement of Time, çalışılan gerçek dakikaları değerleri hakkındaki herhangi bir iddiadan ayrı olarak kaydeder; böylece ne insan ne de yapay hiçbir aktör kaydı sessizce şişiremez. Replay, bu kayıtların her birinin arkasında durur ve antlaşmanın kendisinin yayımladığı her sürümü, kaynağından itibaren yeniden inşa edilebilir, sonsuza dek itiraza açık, sonsuza dek düzeltmeye açık kılar. Bugün küçük bir tutar katkıda bulunan bir vatandaş, elli yıl sonra, iki yüz yıl sonra birinin hâlâ zinciri bu ayın defterine kadar geriye izleyebileceğine ve onu tam olarak olduğu gibi bulacağına güvenmektedir.

Bu güven sistemine giriş, Seed ile başlar — yerel asgari ücretin bir saatinin yedide biri fiyatına, devredilemez ve hiçbir türden ekonomik hak talebi taşımayan, tek seferlik bir üyelik. Seed ne bir pay satın alır, ne servetle ağırlıklandırılmış bir oy, ne de bundan sonraki muhasebede ayrıcalıklı bir statü. Yalnızca aidiyeti satın alır; antlaşmanın faaliyet gösterdiği herhangi bir yerdeki genç bir insanın başlamayı karşılayabileceği kadar düşük bir fiyata. Bir üyenin o noktadan sonra kazandığı her şey kazanılır, asla satın alınmaz ve bu ayrım, antlaşmanın tüm ahlaki mimarisinin küçük ölçekte özetidir.

Bir kişiye akan değer, 🏠 Livelihood Direct aracılığıyla akar — ödemeyi kişiye taşıyan, asla çerçevenin kendisinin gözetim altında tuttuğu ya da kontrol ettiği bir fona değil, nitelikli, lisanslı yerel kanallar. Sınıflandırma her durumda ödemeden önce gelir; bir yatak, bir ödenek, bir sonraki eğitim aşamasında bir yer, yalnızca tanınma ile değil, rol ve hazırlıkla kapılanır; çünkü tanınma ucuzdur, bir geçim kaynağı ise değildir. Bir vatandaşın aylık katkısının fiilen izlediği zincir budur: vatandaşın hesabından, denetlenmiş bir kanal üzerinden, genç bir insanın aldığı ödeneğe, o genç insanın çalışmasının dönüştüğü yenilik projesine ve oradan geri, herhangi bir vatandaşın okuyabileceği kamuya açık bir hesaba.

O çalışmanın değeri varsayılmaz, ölçülür. Qualified Innovation Score, hazırlığı, büyüme potansiyelini, sonuç etkisini ve uygulama hazırlığını tek bir sayıya ortalar ve bu puandaki büyüme, ancak nitelik kazanma sağlandıktan sonra ödül havuzunun büyüklüğünü belirler — QIS'in kendisi ne hiçbir şey basar ne de hiçbir şey öder; bir ölçümdür, asla bir ödeme değildir ve ölçüm burada asla mülkiyetle karıştırılmaz. İnsan emeğinin ödemesi bunun yerine 웃 olarak gelir; yerel asgari ücretle çarpılan bir saat değerinde, fiilen çalışılan ve tanıklık edilen saatlerin kapsamı belirlenmiş, bütçesi onaylanmış bir katsayıyla çarpılır. Bir görev bu onayı taşımadan önce arkasındaki çalışma, ücretlendirilebilir emek değil planlamadır ve kimseye planlama için ödeme yapılmaz. Yıllık 9.999 웃'luk bir tavan — fazlası kaybolmak yerine bir sonraki yıla devrederek — herhangi bir tek yılın kendi hesabının ne beklenmedik bir kazanca ne de bir tuzağa dönüşmesini engeller.

Bunların hiçbiri kendi kanıtından daha hızlı ilerlemez. Antlaşmanın kendisi, Manuel'den Yarı Otomatik'e, oradan Otonom işletime, seferinde bir küp olmak üzere ve yalnızca dokuzda bir oranındaki tam bir ölçülen iyileştirme fiilen gösterildiğinde ilerler, önceden asla varsayılmaz. Özerklik tam olarak orada kazanılır ve her zaman insani kalan anlamdan, paradan ya da hukuktan uzakta. İdari giderler sınırlandırılmıştır. Kurumsal ve kurumlar arası bağışlar karşılanır ve bunlarla birlikte sınırlandırılır. Tam muhasebe, Kamboçya, Honduras ve Austin'de başlayarak her imzacı bölgenin dilinde her ay teslim edilir ve beş yüz yıl sonra da hâlâ teslim edilmesi, hâlâ okunabilir olması amaçlanır. Antlaşmanın gerektirdiği güven budur. Antlaşmanın hizmet edeceği her vatandaşın gözü önünde, seferinde küçük, izlenebilir bir katkıyla kazandığı güven budur.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Kültürler Arası Değişim ve Küresel Katkı`,
    content: {
      7: `Her öğrenen kendi dilinde.`,
      33: `Her etkinlik katılımcının kendi dilinde — bir hükümetin izni gerekmeksizin herhangi bir vatandaşa açık. Yapay, İnsan ve Paylaşılan zekâlar üretken bir gerilim içinde tutulur. Müfredatlar açık biçimde yayımlanır. Bir bölgenin öğrendiğini, herkes miras alır.`,
      111: `Atlantis Antlaşmaları, eğitimi en derin amacına geri getirir: aksi takdirde ayıracak sınırlar arasında bilgeliğin alışverişi. Hükümetlerinin ne imzaladığından bağımsız olarak herhangi bir vatandaş bu müfredata girebilir. Her etkinlik katılımcının dilinde, ev sahibi bölgenin dilinde ve ortak bir kayıtta erişilebilirdir. Dil bir süsleme değildir — dil yargı alanıdır, dil okunabilir kılınmış onurdur. Eğitim çerçevesi zekâların üçlemesine dayanır: Yapay önerir, İnsan karar verir, Paylaşılan Niyet doğrular. Her öğrenci üçünü de bir gerilim içinde tutmayı öğrenir. Antlaşmanın öğrendiği şey geri verilir. Müfredatlar, yenilik sonuçları, refah araştırması ve yönetişim kararları açık biçimde yayımlanır. Bir bölgenin öğrendiğini, tüm vatandaşlar miras alır.`,
      333: `Atlantis Antlaşmaları, eğitimi en derin amacına geri getirir: aksi takdirde ayıracak sınırlar arasında bilgeliğin alışverişi. Bu, dünya vatandaşları arasında bir antlaşmadır — hükümeti ne imzalarsa imzalasın, herhangi bir vatandaş onu kurabilir ve sahiplenebilir. Her etkinlik katılımcının dilinde, ev sahibi bölgenin dilinde ve ortak bir kayıtta erişilebilirdir; böylece hiçbir katılımcı antlaşmada seçmediği bir dilde yol almaz. Dil bir süsleme değildir. Dil yargı alanıdır. Dil okunabilir kılınmış onurdur. Kamboçya'daki genç bir insan ödenek kaydını Khmerce, Honduras'taki İspanyolca, Austin'deki İngilizce okur — üçü de eşit ölçüde onurlandırılır, hiçbiri başlamak için bir hükümetin onayına ihtiyaç duymaz.

Eğitim çerçevesi, Vision • 2525'in görünür kıldığı zekâlar üçlemesine dayanır. Artificial Intelligence, herhangi bir insanın tek başına yapabileceğinden daha hızlı örüntüler ve olasılıklar önerir. Human Intelligence güvenlik, etik ve yön konusunda karar verir — hiçbir makinenin yanıtlamaması gereken, Human Authority altında tutulan sorular. Shared Intent, kararların antlaşmanın ilkelerine hizmet ettiğini doğrular, böylece hiçbir katılımcı mükemmelliği ortak iyiliğin önüne koymaz. Hiçbir öğrenci tek bir zekâya teslim olmaz; her öğrenci üçünü de bir gerilim içinde tutmayı öğrenir. Aidiyet, yerel asgari ücretin bir saatinin yedide biri fiyatına bir üyelik olan Seed ile başlar — herhangi bir vatandaşın karşılayabileceği kadar küçük. Bu, bir sonraki nesli, hiçbir zekânın denetimsiz hareket etmediği bir yerde yönetmeye hazırlar.

Antlaşmanın öğrendiği şey geri verilir. Müfredatlar açık lisans altında yayımlanır, böylece imzacı olsun ya da olmasın herhangi bir bölge bunları yerel kültüre uyarlayabilir. Yenilik sonuçları yayımlanır. Refah araştırması, her yerdeki araştırmacılar için toplu biçimde yayımlanır. Yönetişim kararları gerekçeleriyle birlikte yayımlanır; böylece yalnızca imzacı bir hükümet değil, herhangi bir vatandaş da bunları doğrulayabilir — ve Replay, aynı vatandaşın bir yüzyıl sonra gerekçeyi yeniden izlemesine olanak tanır. Başarı yalnızca katılımcılarıyla değil, pilotu hiç imzalamamış ama onun ortak bilgeliği üzerine inşa edilmiş bölgelerde ortaya çıkan eğitim ve kültür girişimleriyle de ölçülür. Bir bölgenin öğrendiğini, her vatandaş miras alır.`,
      999: `Atlantis Antlaşmaları, eğitimi en derin amacına geri getirir: aksi takdirde ayıracak sınırlar arasında bilgeliğin alışverişi ve bu alışverişe tek bir ders öğretilmeden önce başlar. Her katılımcının çerçeve içindeki ilk eylemi Seed'dir — yerel asgari ücretin bir saatinin yedide biri fiyatına, devredilemez ve hiçbir türden ekonomik hak talebi taşımayan, tek seferlik bir üyelik. Hiçbir ailenin dışlanmayacağı kadar küçük ve hiçbir katılımcının seyirci olarak girmeyeceği kadar gerçektir. Bu, antlaşmanın ilk dersidir: aidiyet ucuza kazanılır, ama yine de kazanılır ve sonrasında gelen üzerinde hiçbir mülkiyet vermez. Bunu izleyen her antlaşma etkinliği, katılımcının dilinde, ev sahibi bölgenin dilinde ve ortak bir kayıtta erişilebilirdir; böylece hiçbir katılımcı antlaşmada seçmediği bir dilde yol almaz. Dil bir süsleme değildir. Dil yargı alanıdır. Dil okunabilir kılınmış onurdur. Kamboçyalı bir köyden genç bir insan ödenek kaydını Khmerce, Honduraslı bir kasaba İspanyolca ve Austin'de bir mahalle İngilizce okuduğunda, üçü de, birbirlerine öğretmeye ilk kez razı olan aynı kurucu bölgelerde, aynı antlaşma tarafından eşit ölçüde onurlandırılır.

Antlaşmanın eğitim çerçevesi, Vision • 2525'in görünür kıldığı zekâlar üçlemesine dayanır ve müfredat her birini bir soyutlama olarak değil, katılımcının kendi elleriyle hissedebileceği bir şey olarak öğretir. ♡, Shared Intention, nedeni taşır — her öğrencinin herhangi bir araca dokunmadan önce tutmayı öğrendiği iplik, bu çalışmanın hâlâ hizmet ettiğini iddia ettiği insanlara hizmet edip etmediği sorusu. Tanıklık edilen hızlanma olan ◬, yalnızca bir fark olarak öğretilir — yalnızca donmuş bir taban çizgisine karşı ölçülür, asla bir kârlılık ölçütü kılığına sokulmaz, asla etraflarındaki takımdan ayrı kişisel bir başarı olarak iddia edilmez. Zaman içinde onurlandırılmış Human Intelligence olan 웃 en dikkatli biçimde öğretilir: tanıklık edilen emeğin bir saati, yerel asgari ücretle bir saate eşittir ve bir katılımcının kazandığı şey, çalışılan saatlerle çarpılan o ücrettir — Multiple çarpı Time, aritmetikte hiçbir şey gizli değildir. Öğrenciler erken öğrenir ki 웃 yalnızca kapsamı belirlenmiş, bütçesi onaylanmış bir görev altında tanıklık edilen emek için verilir. Bu onay var olmadan önce aynı çaba yalnızca planlamadır — değerlidir, ama ücretsizdir ve her katılımcıya bu farkı görür görmez tanıması öğretilir.

Bu fark kolayca bulanıklaştığı için müfredat, QIS'i, Qualified Innovation Score'u, bir gösterge tablosu değil bir ayna olarak öğretir. QIS, dört mutlak mali değerin — Gelir, Brüt Kâr, Faaliyet Geliri ve Etkin Ar-Ge'nin — ortalamasıdır, dörde bölünür ve her öğrenci onu hesaplamayı, sorgulamayı ve asla parayla karıştırmamayı öğrenir. QIS'teki büyüme, ancak nitelik kazanma bağımsız biçimde doğrulandıktan sonra ödül havuzunun büyüklüğünü belirler ve bu büyüme kendi başına hiçbir 웃 basmaz. QIS bir ölçümdür. QIS asla bir ödeme değildir. QIS asla mülkiyet değildir. Bu ayrımı içselleştirmiş bir öğrenci, yüksek bir puanın kendisine antlaşmanın hiç vaat etmediği bir hak talebi verdiğine ikna edilemez.

Müfredat, bu okuryazarlığı, değerin bir kişiye fiilen nasıl ulaştığına, antlaşmanın Livelihood Direct dediği şeye — paranın nitelikli, lisanslı yerel kanallar aracılığıyla hareket ettiği ve asla çerçevenin kendisinin gözetim altında tuttuğu bir fon aracılığıyla değil biçiminde işleyen 🏠 ilkesine — kadar genişletir. Öğrencilere, ödeneklerini ve daha sonra kendi kazançlarını, kendi adlarına başka bir yerde gerçekleştirilen mali bir gizem olarak değil, bir vatandaşlık alıştırması olarak bu kanallar boyunca izlemeleri öğretilir. Sınıflandırmanın her zaman ödemeden önce geldiğini ve tanınmanın — yüksek bir QIS, kamuya açık bir takdirin — tek başına bir yatağın, bir ödeneğin ya da rotasyonda bir yerin kapısını açmadığını öğrenirler. Rol açar. Bu, çok eski bir hataya karşı bir korumadır: övgünün sağlanan hizmetle karıştırılması.

Mali okuryazarlığın yanında, Continuity Without Evasion aracılığıyla öğretilen vatandaşlık okuryazarlığı yer alır. Her katılımcı, antlaşmanın yasal taşınabilirlik için inşa edildiğini — hiçbir tek vazgeçilmez hükümetin, bankanın, kurucunun ya da modelin kendisi ile çerçevenin vaatleri arasında durmadığını öğrenir. Bu tasarım içinde olumsuz bir kararın ne yaptığını öğrenirler: yalnızca bir yargı alanında, o bağdaştırıcının varsayılan olarak reddetme duruşu altında bir kanalı kapatır ve asla bütünü çökertmez. Bununla eşleşen, antlaşmanın öğrettiği en derin derstir: Human Authority anlamı, parayı ve hukuku elinde tutar ve bu kararların alındığı egemen katman, makinelere kalıcı olarak kapalı kalır. Measurement of Time, yani MoT, her katılımcının gerçek dakikalarını herhangi bir puandan ayrı olarak kaydeder ve Replay, antlaşmanın yayımladığı her sürümü tamamen yeniden inşa edilebilir kılar — böylece yıllar sonra bir kararın neden alındığını öğrenmek isteyen bir öğrenci, kimsenin sözüne güvenmek yerine bunu kendisi yeniden izleyebilir.

Bu kazanılmış güven yapısı, yalnızca antlaşmanın yönetişim modeli değil, pedagojik modeli hâline gelir. Her katılımcı, teknolojinin kendisini kapılayan aynı ölçülen-iyileştirme eşiği tarafından kapılanan, giderek artan serbestlik alanına sahip Manuel, Yarı Otomatik ve Otonom modlar boyunca ilerler — bir sonraki mod açılmadan önce yüzde on bir virgül bir oranında doğrulanmış bir kazanım. Özerklik, kazanıldığında, dar biçimde ve alan başına kazanılır, asla anlam, para ya da hukuk üzerinde değil. Bu ilerlemeyi yaşamış bir öğrenci, egemen katmanın neden asla otomasyona kurban edilmemesi gerektiğini bedeniyle anlar — çünkü kendi özerkliğini seferinde ölçülen bir adımla kazanmıştır ve o özerkliğin tam olarak neyi kapsayıp neyi kapsamadığını bilir.

Antlaşmanın öğrendiği şey, antlaşma tarafından geri verilir. Müfredatlar açık lisans altında yayımlanır, böylece imzacı olsun ya da olmasın herhangi bir bölge bunları yerel kültüre ve pedagojik geleneğe uyarlayabilir. Yenilik sonuçları yayımlanır. Refah araştırması, her yerdeki araştırmacılar için toplu biçimde yayımlanır. Yönetişim kararları, gerekçeleri eksiksiz olarak yayımlanır. Antlaşmanın başarısı yalnızca Kamboçya, Honduras ve Austin'deki kendi katılımcılarıyla değil, kurucu pilotu hiç imzalamamış ama onun açıkça paylaşılan bilgeliği üzerine inşa edilmiş bölgelerde, kurucuların tamamlandığını görecek kadar yaşamayacağı bir ufuk boyunca ortaya çıkan girişimlerle de ölçülür. Bir bölgenin öğrendiğini tüm diğer bölgeler miras alır — ve bu neslin dürüstçe öğretildiği şeyi, önümüzdeki beş yüz yıl yeniden unutmak zorunda kalmayacaktır.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Ağın Sürdürülebilir Büyümesi`,
    content: {
      7: `Asla onurun ilerleyebileceğinden hızlı değil.`,
      33: `Dördüncü bir bölge katılmadan önce üç kurucu bölge bir pilot döngüsünü tamamlar — herhangi bir vatandaş onu kurabilir. Kayıtlar beş yüzyıla dayanacak şekilde sabitlenir. İmzacılar egemenliklerini korur; bir sonraki katılım için hiçbir şey aşağı çekilmez.`,
      111: `Atlantis Antlaşmaları, onurlandırabileceği kaliteden daha hızlı büyümeyecektir. Dördüncü bir bölge katılmadan önce üç kurucu bölge, her katılımcı onurlandırılmış ve her ilke doğrulanmış olarak tam bir pilot döngüsünü tamamlamalıdır. Bu, sonunda çalışan bir disipline dönüşmüş ilkedir. Ama antlaşma dünya vatandaşları arasında bir anlaşmadır — bir hükümet ne imzalarsa imzalasın, bir işveren neye izin verirse versin, dünyanın herhangi bir yerindeki herhangi bir kişi bir Seed uzaklıkta onu kurabilir ve sahiplenebilir. Antlaşmanın ufku beş yüzyıldır. Kayıtları Replay aracılığıyla sabitlenir; böylece bir yüzyıl sonra bunları okuyan bir vatandaş gerekçeye güvenebilir. Her imzacı egemenliğini korur; bir sonraki katılım için hiçbir şey aşağı çekilmez.`,
      333: `Atlantis Antlaşmaları, onurlandırabileceği kaliteden daha hızlı büyümeyecektir. Her genişleme, zaten içeride olan katılımcılara verilen bir vaattir — kurucu standardın ölçekle sulandırılmayacağına dair. Dördüncü bir bölge katılmadan önce üç kurucu bölge, her katılımcı onurlandırılmış ve her ilke doğrulanmış olarak tam bir pilot döngüsünü tamamlamalıdır. Bu, sonunda çalışan bir disipline dönüşmüş ilkedir. Ve kapı hiçbir zaman yalnızca bölgesel olmadı: bu, dünya vatandaşları arasında bir anlaşmadır ve herhangi bir kişi onu kurabilir, finanse edebilir ve hesap verebilir kılabilir — ne bir hükümetin izni ne de bir işverenin onayı gerekir. Pilotu imzalayan liderler, imzacılara kurucu topluluğun aldığı aynı alt katmanı, korumayı ve onuru vaat eder. Bir sonraki için hiçbir şey aşağı çekilmez.

Antlaşmanın ufku bilinçli olarak uzundur — kuruluş gününden itibaren beş yüzyıl, on beş ila yirmi insan nesli boyunca dayanacak şekilde tasarlanmıştır. Kayıtları Replay aracılığıyla sabitlenir; böylece bir yüzyıl sonra bunları okuyan bir vatandaş gerekçeye güvenmek yerine onu doğrulayabilir. Koordinat çerçevesi, Human Authority rolleri ve nesiller arası yönetişim döngüleri, herhangi bir tek-teknoloji geçişinden sağ çıkacak şekilde inşa edilmiştir. Antlaşma, kurucu pilotunu imzalayan her insandan ve bir Seed diken, onu her ay finanse eden her vatandaştan daha uzun yaşayacaktır. Bu, bir ödenek anlaşması imzalayan çocuğa, hiçbir hükümetin iznine borçlu olmadan katılan vatandaşa, yüzyılın ortasında antlaşmayı yönetebilecek o çocuğun torunlarına ve kurucuların — resmi olanların da vatandaş olanların da — şimdi inşa ettiği şeyi miras alacak her nesle verdiği vaattir.

Her imzacı, geri çekilme özgürlüğünü, tam egemenliği ve kendi vatandaşları üzerindeki yetkiyi, antlaşmanın evrimini değiştirme ve biçimlendirme hakkıyla birlikte korur. Her vatandaş, kurma, finanse etme, tanıklık etme ve hesap sorma konusunda — bir hükümet imzası olsun ya da olmasın — aynı statüyü korur. Hiçbirinin yapamayacağı şey kurucu ilkelerden ödün vermektir; çünkü bu vaat herhangi bir ayrılıştan sağ çıkmalıdır. Liderler ve vatandaşlar birlikte, antlaşmanın bir sonraki yüzyılını, torunlarının miras alıp tamamlayacağı bir ufka imzalar.`,
      999: `Atlantis Antlaşmaları, onurlandırabileceği kaliteden daha hızlı büyümeyecektir ve bu kısıtlama bir duygusallık değildir — antlaşmanın verdiği her vaadi yöneten aynı ölçüm disiplinine yazılmış bir mühendisliktir. Dördüncü bir bölge katılmadan önce üç kurucu bölge, Kamboçya, Honduras ve Austin, her katılımcı onurlandırılmış ve her ilke doğrulanmış olarak tam bir pilot döngüsünü tamamlamalıdır. Doğrulamayı geride bırakan büyüme, büyüme değildir; hırs kostümü giymiş bir açık kapıdır. Kurucu pilot, antlaşmanın, denetlenebilecek kadar küçük ve önemli olacak kadar büyük bir ölçekte, vaatlerinin gerçeklikle temastan sağ çıktığını, bu vaatler üç sınırının dışından izleyen bir dünyaya genişletilmeden önce kanıtlayabilmesi için vardır. Dördüncü bölge henüz adlandırılmamıştır ve ilk üçü bu belgenin yaptığı her iddianın arkasında durana kadar da adlandırılmayacaktır.

Büyümeye hazır olduğunu kanıtlayan şey coşku değil, antlaşmanın kamuya açık biçimde savunabileceği bir sayıdır. Qualified Innovation Score — Gelir artı Brüt Kâr artı Faaliyet Geliri artı Etkin Ar-Ge harcamasının toplamının dörde bölünmesiyle hesaplanan QIS — antlaşmanın, bir bölgenin, bir topluluğun ya da bir küpün iyileştiğini hissetmek yerine gerçekten iyileşip iyileşmediğini bilmek için kullandığı araçtır. QIS'teki büyüme, yalnızca nitelik kazanma sağlandıktan sonra, önce değil, ödül havuzunun büyüklüğünü belirler ve QIS'in kendisi ne 웃 basar ne de mülkiyet satın alır. QIS bir ölçümdür, bir ödeme değildir; bir ölçümdür, bir hisse değildir; antlaşmanın kendi çalışmasına tuttuğu bir aynadır, asla harcadığı bir para birimi değildir. Ağı genişletmeyi öneren bir bölge, QIS'ini kendinden önceki bölgelerin gözü önünde dürüstçe göstermelidir, yoksa genişlemez.

Sürdürülebilir büyüme, kendi yetkisini seferinde bir artışla kazanan büyüme demektir. Her küp ve her bölge, insanların her şeye karar verdiği ve sistemin yardımcı olduğu Manuel modda başlar. Belirli bir küp içinde Yarı Otomatik'e ve nihayetinde Otonom işletime ilerleme, antlaşma boyunca tek bir eşik tarafından kapılanır — bir sonraki özerklik derecesi verilmeden önce kanıtlanmış ve tekrarlanabilir, dokuzda bir oranında, yani yüzde on bir virgül bir oranında ölçülen bir iyileştirme. Özerklik küp küp kazanılır, asla toptan iddia edilmez ya da sistem ne kadar gelişmiş hâle gelirse gelsin insani kalması gereken alanlar üzerinde genişletilmez: başka yerlerde ne kadar eşik aşılırsa aşılsın, anlam, para ve hukuk makinelere kapalı kalır. Otomasyonunu kanıtından daha hızlı genişleten bir ağ modernleşmiyordur. Henüz kazanmadığı bir güvenle kumar oynuyordur.

Ücretlendirme, ağla birlikte tıpkı yetki gibi ölçeklenir — bilinçli biçimde ve sistemin tamamını kendi başarısından koruyan bir tavanla. Human Intelligence'ın jetonu olan 웃, tanıklık edilen bir saat emeğin yerel asgari ücretle çarpımına eşittir; herhangi bir katılımcının kazandığı şey, bu Multiple'ın çalışılan saatlerle çarpımıdır ve yalnızca kapsamı belirlenmiş, bütçesi onaylanmış bir görev altında gerçekleştirilen emek için verilir. Onaydan önce en güzel plan bile yalnızca planlamadır ve planlama tek başına hiçbir şey basmaz. Her katılımcının ödemesi yıllık 9.999 웃 ile sınırlandırılır; fazlası kaybolmak ya da havuzu bozmak yerine bir sonraki yıla devreder. Yeni bölgeler katıldıkça ve ağın etkinliği çoğaldıkça, bu tavan büyümenin enflasyona dönüşmesini engelleyen şeydir — antlaşma ne kadar büyürse büyüsün değer, gerçek, tanıklık edilmiş, yerel saatlere bağlı kalır.

Her 웃'un arkasında, hiçbir defterin tek başına hesaplayamayacağı bir neden durur. ♡, Shared Intention, bu nedeni antlaşmanın verdiği her genişleme kararı boyunca ileriye taşırken, Artificial Intelligence'ın katkısı olan ◬ ise donmuş bir taban çizgisine karşı ölçülen, tanıklık edilmiş bir hızlanma olarak sayılır — bir fark, ve hiçbir koşulda kendi başına optimize edilecek bir kârlılık ölçütü değildir. Bu ağa giriş, hangi bölgeye ya da hangi on yılda katılırsa katılsın, her katılımcı için aynı şekilde başlar: yerel asgari ücretin bir saatinin yedide biri fiyatına, devredilemez ve hiçbir türden ekonomik hak talebi taşımayan, tek seferlik bir üyelik olan Seed ile. Seed yalnızca bir kişinin geldiğini söyler. Sonrasında inşa ettikleri her şeyi, Seed'in kendisi aracılığıyla değil, antlaşmanın diğer üç para biriminin tam görüş alanında inşa ederler.

Gerçek olan büyüme, aynı zamanda çerçevenin birinin adına tuttuğu bir fona değil, gerçek bir kişiye ulaşan büyüme olmalıdır. 🏠 Livelihood Direct, değerin bir katılımcıya yalnızca antlaşmanın bölge bölge denetlediği nitelikli, lisanslı yerel kanallar aracılığıyla ulaşmasını, asla çerçevenin kendisinin elinde tuttuğu bir gözetim aracılığıyla değil, gerektirir. Sınıflandırma her zaman ödemeden önce gelir, böylece hiçbir değer, amacı ve alıcısı şüphe götürmez biçimde belirlenmeden hareket etmez. Ve tanınma erişimle aynı şey olmadığı için, bir yatak, rotasyonda bir yer, masada bir koltuk, bir katılımcının puanı ya da statüsüyle değil, rol ve hazırlıkla kapılanır. Ağ dördüncü bir bölgeye ve ötesine genişledikçe, her yeni bölge, Livelihood Direct halkına ulaşabilmeden önce kendi lisanslı kanallarını nitelendirmelidir — yalnızca toprağın genişlemesi değil, güvenin genişlemesi.

Bunların hiçbiri, kendi başarısından sağ çıkacak şekilde inşa edilmiş bir ağ olmadan sürmez; bu yüzden Continuity Without Evasion, antlaşmanın eklediği her bölgeyi yönetir. Yasal taşınabilirlik zorunludur; hiçbir tek hükümet, banka, kurucu ya da model bütün için vazgeçilmez hale gelemez. Her yargı alanı kendi bağdaştırıcısını işletir; arıza durumunda kapanan ve varsayılan olarak reddeden bu bağdaştırıcı sayesinde, herhangi bir yerdeki olumsuz bir karar yalnızca bir kanalı kapatır, antlaşmanın tamamını asla. Human Authority, ağın ulaştığı her ölçekte anlamı, parayı ve hukuku elinde tutar; bu, bir vaatle değil tasarımla makine istilasına karşı mühürlenmiştir. Measurement of Time her gerçek dakikayı onun hakkındaki her iddiadan ayrı olarak kaydeder ve Replay, beş yüzyıl boyunca herhangi bir bölgede, herhangi bir noktada yapılan herhangi bir yayının, soran herkes tarafından yeniden inşa edilip yeniden incelenebilmesini sağlar. Yeniden oynatılamayan bir ağa, kaç bölge katılmış olursa olsun ya da büyümesi dışarıdan ne kadar etkileyici görünürse görünsün, güvenilemez. Vision • 2525'in, korumak için inşa edildiği güveni asla aşmadan büyümesinin yolu budur — seferinde bir doğrulanmış bölge, bir dürüst QIS, bir tanıklık edilmiş saat.`,
    },
  },
];
