import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_TR: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Yeniliğin Başladığı Yer`,
    content: {
      7: `Liderler, hiçbir yüzyılın başlamadığını başlatır.`,
      33: `Üç bölge — Kamboçya, Honduras, Austin — genç öğrenenleri ağırlamayı, onları korumayı ve geleceğin araçlarını ellerine vermeyi vaat ediyor. Hükümet, Eğitim, Yenilik: her bölge için üç vizyoner imza. Birlikte tek bir başlangıç.`,
      111: `Atlantis Anlaşması, daha önce var olmayan bir şeyi başlatmaya istekli liderlerin verdiği bir sözdür. Kamboçya, Honduras ve Austin, Teksas'taki kurucu imzacılar nadir bir nitelik için seçildi: gençlere onları öğretecek zaman hâlâ varken geleceğin araçlarını emanet etme isteği. Anlaşmayı imzalamak, bölgeyi kültürler arası öğrenenleri ağırlamaya, yalnızca kendisinin sunabileceği eşsiz katkıyı vermeye ve kendini mevcut düzenlemenin gerektirdiğinden daha yüksek bir standartta tutmaya bağlar. Üç vizyoner imza — Hükümet, Eğitim, Yenilik — anlaşmaya birlikte girer. Üç vizyoner, üç bölge, tek bir ortak başlangıç.`,
      333: `Her uygarlık, başlatmayı seçtiği şeyle hatırlanır. Atlantis Anlaşması, daha önce var olmayan bir şeyi başlatmaya istekli liderlerin verdiği bir sözdür — dünyanın her köşesine ulaşan, her sesi onurlandıran ve nesiller boyunca süren, sıradan insan yeniliği için ortak bir temel. Kamboçya, Honduras ve Austin, Teksas'taki kurucu imzacılar ekonomik güç, askeri kuvvet ya da kurumsal prestij için seçilmedi. Daha nadir bir nitelik için seçildiler: gençlere geleceğin araçlarını emanet etme isteği. Önümüzdeki yüzyılda liderliğin anlamı budur — sonraki nesle nasıl kullanacaklarını öğretecek zaman hâlâ varken anahtarları onlara teslim etme cesareti.\n\nAnlaşma, tam da bu an için özel olarak inşa edilmiş bir örgütleyici güç olan eXeL tarafından bir araya getirilir. eXeL, geçen yüzyıla şekil veren geleneksel koordinasyon kanallarının dışında — diplomatik antlaşma yapılarının dışında, çok taraflı bürokrasilerin dışında, herhangi bir ulus-devletin siyasi çıkmazlarının dışında — bilinçli olarak var olur. eXeL, vizyoner liderleri ortak bir çerçeve, ortak bir çark ve ortak bir beş yüz yıllık ufuk etrafında bir araya getiren güvenilir bir toplayıcıdır. Her imzacı tam egemenliğini, kendi vatandaşları üzerindeki tam yetkisini ve her an çekilme özgürlüğünü korur. İmzacıların kazandığı şey, yalnızca amaca özel inşa edilmiş bir çerçevenin sağlayabileceği ağ etkisidir. Bu, herhangi bir siyasi tahakküm biçimi olmaksızın koordinasyondur.\n\nAnlaşmayı imzalamak, bir söz vermektir. Bölgenin kültürler arası genç öğrenenleri ağırlayacağına dair. Bölgenin yalnızca kendisinin eşsiz biçimde sunabileceği katkıyı vereceğine dair. Bölgenin kendini mevcut düzenlemenin gerektirdiğinden daha yüksek bir standartta tutacağına dair. Bölgenin bunu kamuya açık biçimde, şeffafça, hizmet ettiği her vatandaşın gözü önünde yapacağına dair. Her bölgeden üç imza gerekir — Hükümet, Eğitim ve Yenilik. Hiçbir makam anlaşmayı tek başına bağlamaz. Evet demek için üç vizyoner gerekir. Üç vizyoner, üç bölge, tek bir başlangıç — herhangi bir çerçeve, onu var etmeye istekli liderlerin karşılıklı güveni aracılığıyla işte böyle hayata geçer.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Simülasyon Yoluyla Öğrenmek`,
    content: {
      7: `Dokunmadan önce bin kez pratik yapın.`,
      33: `Sonuç doğuran hiçbir şey ilk kez canlı donanımda öğrenilmez. Her katılımcı simülasyonda pratik yapar, üç bölge arasında dönüşümlü ilerler, kamuya açık kutlar. Bu, ilk hatası asla bir cana mal olmaması gereken genç insana duyulan saygıdır.`,
      111: `Ustalaşmaya değer her disiplin, bilinmeden önce biri tarafından öğrenildi. Atlantis Anlaşması bu kadim bilgeliği, gençlerin geleceği inşa etmeye nasıl hazırlandığının merkezine geri getirir. Sonuç doğuran hiçbir şey ilk kez canlı donanımda, gerçek insanlar üzerinde ya da geri döndürülemez koşullarda öğrenilmez. Her katılımcı, pratik yetkinliğe, yetkinlik de hazır olmaya dönüşene dek simülasyonda pratik yapar. Rotasyon modeli her katılımcıyı üç kurucu bölge boyunca taşır ve her rotasyon, geniş ev sahibi topluluğa açık kamuya açık ve iş birlikçi bir kutlamayla sona erer. Bu, ilk hatası asla bir cana mal olmaması gereken genç insana duyulan saygıdır.`,
      333: `Ustalaşmaya değer her disiplin, bilinmeden önce biri tarafından öğrenildi. Usta zanaatkârlar gösteriden önce prova yapar, pilotlar uçuştan önce prova yapar, hekimler ameliyattan önce prova yapar ve çocuklar dünyayı oyun yoluyla prova eder. Atlantis Anlaşması bu kadim bilgeliği, gençlerin geleceği inşa etmeye nasıl hazırlandığının merkezine geri getirir. Sonuç doğuran hiçbir şey ilk kez canlı donanımda, gerçek insanlar üzerinde ya da geri döndürülemez koşullarda öğrenilmez. Her katılımcı, pratik yetkinliğe, yetkinlik de hazır olmaya dönüşene dek simülasyonda pratik yapar. Bu bir ihtiyat değildir — bu, ilk hatası asla kimsenin canına mal olmaması gereken genç insana duyulan saygıdır.\n\nAnlaşmanın rotasyon modeli her katılımcıyı üç kurucu bölge boyunca taşır. Kamboçya'da öğrenilen, Honduras'ta inceltilir ve Austin'de tamamlanır. Austin'de keşfedilen, Kamboçya'da sorgulanır ve Honduras'ta bütünleştirilir. Her katılımcı, aksi takdirde uzak kalacak kültürler arasında yaşar, öğrenir ve mentorluk alır. Eğitim müfredatı birçok kültürden disiplinli simülasyon geleneklerinden beslenir — Sun Tzu'nun stratejik eğitim geleneğinden, Musashi'nin oyun yoluyla pratiğinden, İbn Haldun'un döngüsel öğrenme kuramından, Nalanda'nın manastır diyalektiğinden, sivil uçuş simülatöründen — her bilişsel evreye ve kültürel mirasa saygı gösterecek biçimde sentezlenir. Hiçbir gelenek egemen olmaz.\n\nHer rotasyon, geniş ev sahibi topluluğa açık kamuya açık ve iş birlikçi bir kutlamayla sona erer. Komşular, aileler ve meraklı ziyaretçiler, kohortun neler öğrendiğini görmek için toplanır. Bu etkinlikler, gelişmiş teknolojiyi korkulan değil, erişilebilir ve kutlanan bir şey kılar. İş birlikçi sistemleri oyun yoluyla anlayarak büyüyen bir toplum, o sistemlere dair korkuyla kolayca manipüle edilemez. Bu, kuvvet yoluyla değil, eğitim yoluyla caydırıcılıktır. Anlaşmanın her ebeveyne verdiği söz: çocuğunuz, kendisine zarar verebilecek herhangi bir şeye dokunmadan önce güven içinde bin kez pratik yapacak ve topluluk her adımda onun gelişimine tanık olacak. Bir çerçevenin içine mühendislikle işlendiğinde genç insana duyulan saygı işte böyle görünür ve liderliğin, o nesil talep etmek zorunda kalmadan önce sonraki katılımcı neslinin eline verdiği şey budur.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `Güven Uzatılmadan Önce Doğrulanan Güvenlik`,
    content: {
      7: `Önce güvenlik kanıtlanır, sonra güven uzatılır.`,
      33: `Her tesis ve her rotasyon, erken uyarılı koruyucu bir zarfın içinde yer alır. Donanım silahlandırılmayı reddeder. Kayıtlar türbülanstan sağ çıkar. Güvenlik yalnızca vaat edilmez ya da varsayılmaz; her gün en genç katılımcının etrafında mühendislikle kurulur.`,
      111: `Güven uzatılmadan önce, güvenliğin kanıtlanması gerekir. Atlantis Anlaşması bunu kurucu taahhüdü kılar. Her anlaşma tesisi, her rotasyon güzergâhı, genç bir katılımcının uyuduğu ya da çalıştığı her yer, topluluğa herhangi bir inandırıcı riske dakikalarla değil saatlerle yanıt verme olanağı tanıyan erken uyarı yeteneğine sahip, belgelenmiş koruyucu bir zarfın içinde yer alır. Her cihaz, her sensör, her koordinasyon sistemi, silah sistemlerine entegrasyon amacıyla yeniden kullanımı reddedecek biçimde donanım katmanında bağlanır. Bu bir politika değil — bu fiziktir. Anlaşma, türbülans içinde onurlu kalacak biçimde tasarlanmıştır: siyasi istikrarsızlık, fon daralması, siber saldırı ya da seyahat kesintisi. Her senaryo için plan yapılır ve her plan, insan onurunu ilk tasarım kısıtı olarak yerleştirir.`,
      333: `Güven uzatılmadan önce, güvenliğin kanıtlanması gerekir. Atlantis Anlaşması bunu kurucu taahhüdü kılar. Her anlaşma tesisi, her rotasyon güzergâhı, genç bir katılımcının uyuduğu ya da çalıştığı her yer, topluluğa herhangi bir inandırıcı riske dakikalarla değil saatlerle yanıt verme olanağı tanıyan erken uyarı yeteneğine sahip, belgelenmiş koruyucu bir zarfın içinde yer alır. Katılımcıları korumak için kullanılan teknoloji, anlaşmanın onlara inşa etmeyi öğrettiği teknolojinin ta kendisidir — sensörler, koordinasyon, iletişim dayanıklılığı, dağıtık zekâ. Gençler güvenliği içeriden dışarıya, kendi dillerinde ve kendi bölgelerinde öğrenirler; güvende oldukları kendilerine söylenerek değil, güvenliğin her gün etraflarında nasıl mühendislikle kurulduğunu görerek.\n\nAnlaşma, teknolojisinin neye dönüşemeyeceğine dair bozulmaz bir söz verir. Her cihaz, her sensör, her koordinasyon sistemi, silah sistemlerine entegrasyon amacıyla yeniden kullanımı reddedecek biçimde donanım katmanında bağlanır. Bu bir politika dili değildir. Bir özlem değildir. Bu, kriptografik olarak uygulanan, her imzacı bölge tarafından doğrulanan ve her vatandaş tarafından denetlenebilen fiziksel bir imkânsızlıktır. Phnom Penh'te bir çocuğu koruyan araçlar, Austin'de bir çocuğa zarar vermek için yeniden kullanılamaz. Tegucigalpa'da bir sürü tatbikatını koordine eden araçlar, herhangi bir yerde bir insanı hedef almak için yeniden yapılandırılamaz. Bu, anlaşmanın bir yüzyıllık çift kullanım korkusuna verdiği yanıttır. Politika değil — fizik.\n\nAnlaşma, türbülans içinde onurlu kalacak biçimde tasarlanmıştır. Bir imzacı bölge siyasi istikrarını kaybederse, katılımcılar kalan bölgeler tarafından ağırlanır. Fonlar daralırsa, katılımcı bursları yönetim ve altyapıdan önce, ilk olarak korunur. Dijital kayıtlar saldırıya uğrarsa, çevrimdışı yedekler kalıcı olur. Seyahat imkânsız hâle gelirse, altyapı sanal olarak devam eder. Her senaryo için plan yapılır ve her plan, insan onurunu ilk tasarım kısıtı olarak yerleştirir. Bu anlaşmayı imzalayan liderler, güvenliğin varsayılmadığına, mühendislikle kurulduğuna dair bir söz imzalar. Vatandaşlarına uzattıkları şey yalnızca fırsat değil, en genç katılımcının hak ettiği standartta inşa edilmiş korumadır — her liderin, tanımadığı bir sınırı tek başına geçen kendi çocuğu için talep edeceği aynı koruma.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Ödüllendirme, Esenlik ve İnsan Onuru`,
    content: {
      7: `Bir burs, bir mentor, bir yuva.`,
      33: `Her katılımcı ilk günden itibaren geçimlik bir burs alır. Sevgi, kayıp ve güvenlik birinci sınıf altyapı olarak ele alınır. Başarı, ortalamayla değil, en kırılgan katılımcıyla ölçülür. Onur, süsleme değil, alt tabakadır.`,
      111: `Atlantis Anlaşması her katılımcıyı ilk günden itibaren tam bir insan olarak ele alır. Katılım başladığı andan itibaren, etkisinin işin yerel onurunu gözetmesi için bölgenin yaşam maliyetine endekslenmiş bir burs verilir. Esenlik birinci sınıf altyapı olarak ele alınır — isteğe bağlı bir yan hak, bir esenlik ayrıcalığı değil, üzerine her şeyin durduğu alt tabaka. Üç temel alan desteklenir: Sevgi, Kayıp ve Güvenlik. Anlaşma başarıyı, ortalamayla değil, en kırılgan katılımcısının sonucuyla ölçer. Ortalamalar iyi görünsün diye hiçbir katılımcı sessizce unutulmayacak. Süsleme değil, alt tabaka olarak onur.`,
      333: `Atlantis Anlaşması her katılımcıyı ilk günden itibaren tam bir insan olarak ele alır. Katılım başladığı andan itibaren, etkisinin işin yerel onurunu gözetmesi için bölgenin yaşam maliyetine endekslenmiş bir burs verilir. Burs, aile yükümlülükleri acil durumlara dönüşmeden ve onur zedelenmeden önce ulaşır. Her gence, zamanının değerli olduğunu, katkısının beklendiğini ve ailesinin istikrarının anlaşmanın sorumluluğunun bir parçası olduğunu bildirir. Bu bir hayırseverlik değildir. Bu, sıradan insan yeniliğinin önce sıradan insan güvenliğini gerektirdiğinin kabulüdür. Bir zihin, hanesi tehdit altındayken serpilemez.\n\nEsenlik birinci sınıf altyapı olarak ele alınır — isteğe bağlı bir yan hak, bir esenlik ayrıcalığı değil, üzerine her şeyin durduğu alt tabaka. Anlaşma, her katılımcının aracılığıyla desteklendiği üç temel alanı adlandırır: bağlantı, aidiyet ve sağlıklı sınır anlamında Sevgi; her katılımcının yas yaşayacağı ve etrafından değil, yanında yürünmesi gerektiği için Kayıp; ve her katılımcının her bölgede, kendi dilinde kimi arayacağını bildiği anlamda Güvenlik. Bireysel danışmanlık, grup çemberleri, bedensel uygulamalar ve katılımcının kendi geleneğine göre onurlandırılan kültürel ya da manevi uygulamaların tümü sağlanır. Sıfır dayatılan ideoloji. Anlaşma alanı hürmetle tutar; hiçbir inanç sistemini yaymaya çalışmaz.\n\nAnlaşma başarıyı, ortalamayla değil, en kırılgan katılımcısının sonucuyla ölçer. Yüksek bant genişliği olmayan kırsal katılımcılara hizmet verilir. Nörolojik açıdan farklı katılımcılar, uyarlamayı bir norm olarak alır. Engelli katılımcılar her tesisi erişilebilir bulur. Cinsiyet açısından çeşitli katılımcılar güvenli barınma ve mentor eşleştirmesi alır. Ana dili yerel olmayan konuşmacılar her belgeyi kendi dilinde bulur. Yerli katılımcılar kültürel uygulamalarını onurlandırılmış, geleneksel bilgilerini korunmuş bulur. Bu anlaşmayı imzalayan liderler, ortalamalar iyi görünsün diye hiçbir katılımcının sessizce unutulmayacağına söz verir. Bu, süsleme değil, alt tabaka olarak onurdur. Ölçülen şey, onurlandırılacak olan şeydir ve burada onurlandırılan şey, bütün insandır — zihin, beden ve ruh birlikte, hiçbir istisna olmaksızın.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Finansman ve Yönetişim`,
    content: {
      7: `Vatandaşlar sonraki nesli doğrudan finanse eder.`,
      33: `Sıradan sakinler her ay küçük miktarlar katkıda bulunur. Yardım kanalı yok, yabancı hami yok, siyasi bağ yok. Her dolar izlenebilir. Her muhasebe her bölgenin dilinde, her ay, kamuya açık biçimde yayımlanır.`,
      111: `Atlantis Anlaşması, hizmet ettiği vatandaşlar tarafından finanse edilir. Sıradan sakinler her ay küçük gönüllü miktarlar katkıda bulunur — hiçbir yetişkini dışlamayacak kadar mütevazı, toplamın anlaşmanın işini anlamlı ölçekte sürdürecek kadar yankı uyandıran. Bir vatandaş sonraki nesli doğrudan finanse ettiğinde, o vatandaş anlaşmayı doğrudan hesap verebilir kılar. Anlaşma, geçen yüzyıla şekil veren çok taraflı kurumlardan bilinçli olarak bağımsızdır. Bu bir siyasi beyan değil — bir tasarım seçimidir. Her dolar kalıcı ve izlenebilir biçimde kaydedilir. Her vatandaş katkısı, kaynağından bursa ve yeniliğe dek izlenebilir. Herhangi bir kurum tarafından nadiren sunulan türden bir şeffaflık.`,
      333: `Atlantis Anlaşması, hizmet ettiği vatandaşlar tarafından finanse edilir. Katılan bölgelerin sıradan sakinleri her ay küçük gönüllü miktarlar katkıda bulunur — hiçbir ev sahibi bölgedeki hiçbir yetişkini katılımdan dışlamayacak kadar mütevazı, toplamın anlaşmanın işini anlamlı ölçekte sürdürecek kadar yankı uyandıran miktarlar. Bu tasarım bilinçlidir. Bir vatandaş sonraki neslin eğitimini doğrudan finanse ettiğinde, o vatandaş anlaşmayı doğrudan hesap verebilir kılar. Yardım kanalı yok, yabancı hami yok, çeke bağlı hiçbir siyasi bağ yok. Anlaşmanın ruhu, her ay küçük bir miktar katkıda bulunan ve katılımı bütünü mümkün kılan vatandaştır.\n\nAnlaşma, geçen yüzyıla şekil vermiş çok taraflı kurumlardan — Kuzey Atlantik Antlaşması Örgütü, Dünya Sağlık Örgütü, Birleşmiş Milletler, Uluslararası Para Fonu, Dünya Bankası ve her ulusal dış yardım kanalından — bilinçli olarak bağımsızdır. Bu, o kurumların değeri ya da katkıları hakkında bir siyasi beyan değildir. Bir tasarım seçimidir. Tek noktalı bağımlılıklar, beş yüz yıllık bir ufuk boyunca dayanıklılığı zedeler. Jeopolitik hizalanmasından bağımsız olarak her bölgeye hizmet etmeyi amaçlayan bir çerçeve, hiçbir hizalanmaya dolanamaz. Ulusal hükümetler gönüllü olarak katkıda bulunabilir. Katkılar şeffaftır. Hiçbir katkı, hiçbir kaynaktan, asla yönetişim etkisi satın almaz.\n\nAnlaşmaya giren her dolar ve her değer birimi kalıcı, kamuya açık ve izlenebilir biçimde kaydedilir. Her vatandaş katkısı, kaynağından dönüştüğü bursa, hizmet ettiği gence, o gencin çalışmasından doğan yenilik projesine dek izlenebilir. Yönetim giderleri sınırlandırılmıştır. Kurumsal ve kurumdışı bağışlar hoş karşılanır ve sınırlandırılır. Her imzacı bölgenin dilinde her ay tam muhasebe sunulur. Anlaşmayı imzalayan liderler, vatandaşlarına herhangi bir kurum tarafından nadiren sunulan türden bir şeffaflık vaat eder — her imzacı görevden ayrıldıktan yüzyıllar sonra bile okunabilir kalacak bir şeffaflık. Anlaşmanın gerektirdiği güven budur. Anlaşmanın, her seferinde küçük ve izlenebilir bir katkıyla, her vatandaşın gözü önünde kazandığı güven budur.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Kültürler Arası Değişim ve Küresel Katkı`,
    content: {
      7: `Her öğrenen kendi dilinde.`,
      33: `Her etkinlik katılımcının dilinde erişilebilir. Yapay, İnsan ve Ortak zekâlar üretken bir gerilim içinde tutulur — hiçbir öğrenci tek birine tabi olmaz. Müfredatlar ve sonuçlar açıkça yayımlanır. Bir bölgenin öğrendiğini herkes miras alır.`,
      111: `Atlantis Anlaşması, eğitimi en derin amacına geri döndürür: aksi takdirde bölecek sınırlar arasında bilgeliğin değişimi. Her etkinlik katılımcının kendi dilinde, ev sahibi bölgenin dilinde ve kanonik bir ortak kayıtta erişilebilirdir. Dil bir süsleme değil — dil yetki alanıdır, dil okunabilir kılınmış onurdur. Eğitim çerçevesi zekâlar üçlüsüne dayanır: Yapay olan önerir, İnsan olan karar verir, Ortak Niyet doğrular. Her öğrenci üçünü de üretken bir gerilim içinde tutmayı öğrenir. Anlaşmanın öğrendiğini anlaşma geri verir. Müfredatlar, yenilik sonuçları, esenlik araştırmaları ve yönetişim kararlarının tümü açıkça yayımlanır. Bir bölgenin öğrendiğini tüm bölgeler miras alır.`,
      333: `Atlantis Anlaşması, eğitimi en derin amacına geri döndürür: aksi takdirde bölecek sınırlar arasında bilgeliğin değişimi. Her anlaşma etkinliği, katılımcının kendi dilinde, ev sahibi bölgenin resmi dilinde ve kanonik bir ortak kayıtta erişilebilirdir; böylece hiçbir katılımcı, seçmediği bir dilde anlaşmada yol almaz. Dil bir süsleme değildir. Dil yetki alanıdır. Dil okunabilir kılınmış onurdur. Kamboçyalı bir köyden bir genç kendi burs kaydını Khmer dilinde okuduğunda, Honduraslı bir kasabadan bir genç onu İspanyolca okuduğunda, bir Austin mahallesinden bir genç onu İngilizce okuduğunda, üçü de aynı anlaşma tarafından eşit biçimde onurlandırılmış olur.\n\nAnlaşmanın eğitim çerçevesi, Vision 2525'in görünür kıldığı zekâlar üçlüsüne dayanır. Yapay Zekâ, herhangi bir insanın tek başına yapabileceğinden daha hızlı biçimde örüntüler, seçenekler ve olasılıklar önerir. İnsan Zekâsı, güvenlik, etik ve yön hakkında karar verir — hiçbir makinenin yanıtlamaması gereken sorular. Ortak Niyet, kararların anlaşmanın kurucu ilkeleriyle uyumlu olduğunu doğrular ve hiçbir katılımcının bireysel mükemmellik ile ortak iyilik arasında seçim yapmaya zorlanmamasını güvence altına alır. Hiçbir öğrenciye tek bir zekâya tabi olması öğretilmez. Her öğrenci üçünü de üretken bir gerilim içinde tutmayı öğrenir. Sonraki nesil liderler, bu üç zekânın hiçbirinin asla tek başına ya da denetimsiz davranmayacağı bir dünyada sorumlu ve bilgece yönetmeye işte böyle hazırlanır.\n\nAnlaşmanın öğrendiğini anlaşma geri verir. Müfredatlar açık lisans altında yayımlanır; böylece herhangi bir bölge — imzacı olsun olmasın — onları kendi yerel kültürüne ve pedagojik geleneğine özgürce uyarlayabilir. Yenilik sonuçları yayımlanır. Esenlik araştırmaları, her yerdeki araştırmacılar için toplulaştırılmış biçimde yayımlanır. Yönetişim kararları, gerekçeleriyle tam olarak yayımlanır. Anlaşmanın başarısı, yalnızca kendi katılımcılarıyla değil, ardında doğan eğitim, yenilik ve kültür girişimlerinin sayısıyla da ölçülür; kurucu pilotu asla imzalamamış ama onun açıkça paylaşılan bilgeliği üzerine inşa etmiş bölgelerde. Bir bölgenin öğrendiğini diğer tüm bölgeler miras alır.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Ağın Sürdürülebilir Büyümesi`,
    content: {
      7: `Asla onurun ilerleyebileceğinden hızlı değil.`,
      33: `Üç kurucu bölge, dördüncüsü katılmadan önce bir pilot döngüyü tamamlar. Kayıtlar beş yüzyıl dayanacak biçimde çıpalanır. Her imzacı egemenliğini korur. Sonraki imzacıya yer açmak için hiçbir şey aşağı çekilmez.`,
      111: `Atlantis Anlaşması, onurlandırabileceği kaliteden daha hızlı büyümeyecek. Üç kurucu bölge, dördüncü bir bölge katılmadan önce, her katılımcı onurlandırılmış ve her ilke doğrulanmış biçimde tam bir pilot döngüyü tamamlamalıdır. Bu, nihayet işleyen bir disipline dönüşmüş ilkedir. Anlaşmanın ufku bilinçli olarak uzundur — kurucu günden itibaren beş yüzyıl. Kayıtları, bunları yüz yıl sonra okuyan bir vatandaşın gerekçeye güvenebilmesi için çıpalanmıştır. Her imzacı tam egemenliğini, tam yetkisini ve tam çekilme özgürlüğünü korur. Hiçbir imzacı kurucu ilkeleri zedeleyemez — çünkü o ilkeler, anlaşmanın her nesil boyunca katılımcılarına verdiği sözdür.`,
      333: `Atlantis Anlaşması, onurlandırabileceği kaliteden daha hızlı büyümeyecek. Her genişleme, zaten içeride olan katılımcılara bir sözdür — anlaşmanın kurucu standardının ölçek heyecanıyla sulandırılmayacağına dair. Üç kurucu bölge, dördüncü bir bölge katılmadan önce, her katılımcı onurlandırılmış ve her ilke doğrulanmış biçimde tam bir pilot döngüyü tamamlamalıdır. Bu, ilke kılığına sokulmuş bir ihtiyat değildir. Bu, her kurucu bölgede nihayet işleyen bir disipline dönüşmüş ilkedir. Kurucu pilotu imzalayan liderler, gelecekteki imzacılara kurucu kohortun aldığı aynı alt tabakayı, aynı korumayı, aynı onuru vaat eder. Sonrakine yer açmak için hiçbir şey aşağı çekilmez.\n\nAnlaşmanın ufku bilinçli olarak uzundur. Yaklaşık on beş ilâ yirmi insan nesli boyunca — kurucu günden itibaren beş yüzyıl — dayanacak biçimde tasarlanmıştır. Kayıtları, bunları yüz yıl sonra okuyan bir vatandaşın gerekçeye güvenebilmesi için çıpalanmıştır. Koordinat çerçevesi, insan yetki rolleri ve nesiller arası yönetişim döngülerinin tümü, herhangi bir tek teknolojili geçişten sağ çıkacak biçimde inşa edilmiştir. Anlaşma, kurucu pilotunu imzalayan her insandan daha uzun yaşayacaktır. Bu, onaydan sonraki yıl bir burs sözleşmesi imzalayan çocuğa, yüzyıl ortasında anlaşmayı yönetebilecek o çocuğun torunlarına ve kurucuların şimdi inşa ettiğini miras alan her nesle verdiği sözdür.\n\nHer imzacı, önceden bildirimde bulunarak çekilme özgürlüğünü korur. Her imzacı tam egemenliğini korur. Her imzacı kendi vatandaşları üzerindeki yetkisini korur. Her imzacı, her diğer imzacıyla birlikte değişiklikler önerme, anlaşmazlıkları dile getirme ve anlaşmanın evrimine şekil verme hakkını korur. Hiçbir imzacının yapamayacağı şey, alt tabakanın kurucu ilkelerini zedelemektir — çünkü o ilkeler, anlaşmanın katılımcılarına verdiği sözdür ve o söz, herhangi bir imzanın ayrılışından sağ çıkmalıdır. Bu anlaşmayı şimdi imzalayan liderler, herhangi bir siyasi görev döneminden daha büyük bir şeye katılır. Anlaşmanın sonraki yüzyılını ve ötesindeki yüzyılları, kendi torunlarının miras alıp tamamlayacağı bir ufka imzalıyorlar.`,
    },
  },
];
