import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_VI: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Nơi đổi mới bắt đầu`,
    content: {
      7: `Những nhà lãnh đạo khởi đầu điều chưa thế kỷ nào khởi đầu.`,
      33: `Ba khu vực — Campuchia, Honduras, Austin — mở ra một lời hứa mà công dân chung tay xây dựng: đón nhận người học, bảo vệ họ, trao cho họ công cụ của tương lai. Chính phủ, Giáo dục, Đổi mới ký kết với tư cách người quản lý; công dân nắm giữ nó. Một khởi đầu.`,
      111: `Hiệp ước Atlantis là một thỏa thuận giữa các công dân trên toàn thế giới — một lời hứa mà bất kỳ ai, ở bất cứ đâu, đều có thể tạo lập và gìn giữ, bất kể chính phủ của họ ký kết điều gì hay người sử dụng lao động của họ cho phép điều gì. Các khu vực sáng lập của hiệp ước, Campuchia, Honduras, và Austin, Texas, được lựa chọn vì một phẩm chất hiếm có: sự sẵn lòng trao cho thế hệ trẻ những công cụ của tương lai trong khi vẫn còn thời gian để dạy họ sử dụng. Chính phủ, nhà giáo dục, và nhà đổi mới ký kết với tư cách người quản lý của khu vực mình — mỗi bên ba chữ ký mang tầm nhìn, Chính phủ, Giáo dục, Đổi mới — nhưng chính công dân mới là người tài trợ cho hiệp ước, chứng kiến công việc của nó, và trực tiếp buộc nó chịu trách nhiệm. Không cần sự cho phép của chính phủ nào, không cần sự chuẩn thuận của người sử dụng lao động nào để được thuộc về nó. Ba khu vực, một khởi đầu chung.`,
      333: `Mọi nền văn minh đều được nhớ đến qua những gì nó chọn để bắt đầu. Hiệp ước Atlantis là một lời hứa giữa các công dân trên toàn thế giới — bất kỳ ai, ở bất cứ đâu, đều có thể khởi xướng nó, bất kể chính phủ của họ ký kết điều gì. Các khu vực sáng lập, Campuchia, Honduras, và Austin, Texas, không được chọn vì sức mạnh kinh tế, sức mạnh quân sự, hay uy tín thể chế, mà vì một phẩm chất hiếm có hơn: sự sẵn lòng trao cho thế hệ trẻ những công cụ của tương lai. Đây chính là ý nghĩa của sự lãnh đạo trong thế kỷ sắp tới — lòng can đảm để trao lại chìa khóa cho thế hệ kế tiếp trong khi vẫn còn thời gian để dạy họ cách cầm lái.

Hiệp ước được triệu tập bởi eXeL, một lực lượng tổ chức được xây dựng riêng cho thời khắc này, tồn tại bên ngoài những kênh phối hợp đã định hình thế kỷ trước — bên ngoài các cấu trúc hiệp ước ngoại giao, các bộ máy quan liêu đa phương, và những ràng buộc chính trị của bất kỳ quốc gia đơn lẻ nào. eXeL là bên triệu tập đáng tin cậy, quy tụ các nhà lãnh đạo có tầm nhìn quanh một khung khổ chung, một bánh đà chung, và một chân trời chung năm trăm năm. Mỗi bên ký kết vẫn giữ trọn chủ quyền, trọn quyền lực đối với công dân của mình, và trọn quyền tự do rút lui bất cứ lúc nào. Điều mà các bên ký kết nhận được — và điều mà bất kỳ công dân nào cũng nhận được, với giá của một Seed, bằng một phần bảy giờ lương tối thiểu địa phương — là hiệu ứng mạng lưới mà chỉ một khung khổ được xây dựng riêng mới có thể mang lại: sự phối hợp không mang bất kỳ hình thức thống trị chính trị nào.

Ký hiệp ước là ký một lời hứa: rằng khu vực sẽ đón nhận người học từ mọi nền văn hóa, đóng góp những gì chỉ riêng mình có thể mang lại, và tự đặt mình vào một chuẩn mực cao hơn những gì quy định hiện hành đòi hỏi — một cách công khai, minh bạch, chịu trách nhiệm trước những công dân tài trợ, chứng kiến, và buộc nó chịu trách nhiệm, không cần sự cho phép của chính phủ hay sự chuẩn thuận của người sử dụng lao động để được thuộc về nó. Mỗi khu vực cần ba chữ ký — Chính phủ, Giáo dục, và Đổi mới — ký kết với tư cách người quản lý, không phải chủ sở hữu. Cần ba người có tầm nhìn để nói lời đồng ý, và cần công dân để gìn giữ những gì họ đã ký. Ba người có tầm nhìn, ba khu vực, một khởi đầu — đây là cách một khung khổ bước vào đời sống qua niềm tin của những nhà lãnh đạo sẵn lòng ký nó vào hiện hữu.`,
      999: `Mọi nền văn minh đều được nhớ đến qua những gì nó chọn để bắt đầu, và Vision • 2525 mời gọi những người sáng lập của nền văn minh này bắt đầu bằng sự khiêm nhường thay vì chinh phục. Hiệp ước Atlantis là một lời hứa do những nhà lãnh đạo sẵn lòng khởi xướng điều chưa từng tồn tại — một nền tảng chung cho sự đổi mới của con người, vươn tới mọi ngóc ngách trên thế giới, tôn trọng mọi tiếng nói, và trường tồn qua nhiều thế hệ được đo không phải bằng năm mà bằng thế kỷ. Các bên ký kết sáng lập tại Campuchia, Honduras, và Austin, Texas không được chọn vì sức mạnh kinh tế, sức mạnh quân sự, hay uy tín thể chế. Họ được chọn vì một phẩm chất hiếm có hơn: sự sẵn lòng trao cho thế hệ trẻ những công cụ của tương lai, và sự kiên nhẫn để một chân trời năm trăm năm tồn tại lâu hơn tiếng vỗ tay của bất kỳ chính quyền nào. Đây chính là ý nghĩa của sự lãnh đạo trong thế kỷ sắp tới — lòng can đảm để trao lại chìa khóa cho thế hệ kế tiếp trong khi vẫn còn thời gian để dạy họ cách cầm lái.

Hiệp ước được triệu tập bởi eXeL, một lực lượng tổ chức được xây dựng riêng cho thời khắc này. eXeL tồn tại bên ngoài những kênh phối hợp đã định hình thế kỷ trước — bên ngoài các cấu trúc hiệp ước ngoại giao, bên ngoài các bộ máy quan liêu đa phương, bên ngoài những ràng buộc chính trị của bất kỳ quốc gia nào. eXeL là bên triệu tập đáng tin cậy, quy tụ các nhà lãnh đạo có tầm nhìn quanh một khung khổ chung, một bánh đà chung, và một chân trời chung năm trăm năm. Mỗi bên ký kết vẫn giữ trọn chủ quyền, trọn quyền lực đối với công dân của mình, và trọn quyền tự do rút lui bất cứ lúc nào. Điều mà các bên ký kết nhận được là hiệu ứng mạng lưới mà chỉ một khung khổ được xây dựng riêng mới có thể mang lại. Sự tham gia của mỗi người vào khung khổ đó đều bắt đầu theo cùng một cách khiêm tốn: bằng một Seed, một khoản thành viên một lần được định giá bằng một phần bảy giờ lương tối thiểu địa phương, không thể chuyển nhượng và không mang bất kỳ quyền đòi hỏi kinh tế nào. Một Seed không mua quyền sở hữu, không mua lời hứa phần thưởng — chỉ mua sự thuộc về, quyền được đứng trong khung khổ và bắt đầu. Đây là sự phối hợp không mang bất kỳ hình thức thống trị chính trị nào, được xây dựng trên một khởi đầu đủ nhỏ để bất kỳ ai cũng có thể chi trả.

Bởi chủ quyền được giữ lại chứ không bị từ bỏ, hiệp ước được xây dựng cho Continuity Without Evasion. Không một chính phủ, ngân hàng, người sáng lập, hay mô hình nào là không thể thay thế đến mức có thể bắt cả khung khổ làm con tin cho sự tồn vong của riêng nó. Mỗi thẩm quyền tài phán được phục vụ qua bộ điều hợp hợp pháp của riêng mình, mặc định từ chối cho đến khi được chứng minh tuân thủ, để giá trị chỉ di chuyển qua những kênh mà tòa án tại thẩm quyền tài phán đó công nhận là hợp pháp. Nếu một cơ quan quản lý tại một khu vực đưa ra phán quyết bất lợi, chỉ riêng kênh đó đóng lại một cách an toàn — minh bạch, không gây hại cho bất kỳ ai bên trong nó — trong khi mọi khu vực khác vẫn tiếp tục không gián đoạn. Toàn bộ hiệp ước không bao giờ sụp đổ chỉ vì một chính phủ đổi ý. Đây là tính khả chuyển được thiết kế như một lời hứa sáng lập, chứ không phải một phương án dự phòng được phát hiện sau khủng hoảng.

Ký hiệp ước là ký một lời hứa. Rằng khu vực sẽ đón nhận người học từ mọi nền văn hóa. Rằng khu vực sẽ đóng góp những gì chỉ riêng mình có thể mang lại. Rằng khu vực sẽ tự đặt mình vào một chuẩn mực cao hơn những gì quy định hiện hành đòi hỏi. Rằng khu vực sẽ làm điều đó một cách công khai, minh bạch, trước mắt mọi công dân mà nó phục vụ. Mỗi khu vực cần ba chữ ký — Chính phủ, Giáo dục, và Đổi mới. Không một cơ quan đơn lẻ nào có thể ràng buộc hiệp ước một mình. Cần ba người có tầm nhìn để nói lời đồng ý. Chữ ký ba bên này là biểu hiện đầu tiên của Human Authority: ý nghĩa, tiền bạc, và luật pháp vẫn nằm trong tay con người ở tầng chủ quyền, một tầng vĩnh viễn đóng cửa với máy móc dù chúng có trở nên tài giỏi đến đâu. Measurement of Time, MoT, bắt đầu ghi nhận từ khoảnh khắc ký kết — những phút giây thực sự của công việc thực sự của con người, được giữ tách biệt khỏi bất kỳ ước tính tự động nào — và mọi bản phát hành tiếp theo của công việc hiệp ước đều được xây dựng để có thể tái dựng qua Replay, để một công dân sinh ra một thế kỷ sau có thể lần lại cách những quyết định sáng lập hôm nay đã được đưa ra.

Điều mà giai đoạn thí điểm sáng lập là phép đo trước khi là tiền bạc. Mọi sáng kiến bước vào khung khổ được chấm điểm bởi Qualified Innovation Score, QIS — trung bình của Doanh thu, Lợi nhuận gộp, Thu nhập hoạt động, và chi tiêu R&D hiệu quả, chia cho bốn. QIS không phải là khoản thanh toán và không bao giờ là quyền sở hữu; đó là công cụ để một thế hệ sáng lập học cách nhìn thấy tiến bộ của chính mình trước khi bất kỳ phần thưởng nào được định lượng. Tăng trưởng QIS, một khi đạt điều kiện, sẽ định lượng quỹ phần thưởng theo sau — nhưng tăng trưởng QIS tự nó không tạo ra bất cứ điều gì. Ba khu vực, một khởi đầu, và một kỷ luật chung: chứng minh điểm số trước khi chạm vào ngân khố.

Giá trị kiếm được qua công việc được chứng kiến mang tên riêng của nó, 웃, được tính bằng một giờ nhân với mức lương tối thiểu địa phương, được điều chỉnh theo một Hệ số áp dụng cho số giờ đã phục vụ. 웃 chỉ được phát hành cho công việc được chứng kiến trong phạm vi một nhiệm vụ đã được xác định phạm vi, được duyệt ngân sách; bất cứ điều gì chưa đạt sự phê duyệt đó vẫn chỉ là lập kế hoạch, và lập kế hoạch đơn thuần không tạo ra bất cứ điều gì. Trần thanh toán 9.999 웃 mỗi năm bảo vệ mọi người tham gia khỏi sự tập trung mất kiểm soát, với bất kỳ phần dư nào được chuyển tiếp sang năm sau thay vì biến mất. Đứng sau mỗi 웃 là ♡, Shared Intention, mang theo lý do vì sao một nhiệm vụ được phê duyệt ngay từ đầu, và ◬, sự tăng tốc được chứng kiến mà một nhiệm vụ tạo ra so với một đường cơ sở đã đóng băng — chỉ là một mức chênh lệch, không bao giờ bị nhầm lẫn với một chỉ số lợi nhuận. Giai đoạn thí điểm tồn tại để chứng minh ba biểu tượng này có thể vận hành cùng nhau một cách trung thực, khu vực này đến khu vực khác, trước khi khung khổ mở rộng vượt ra ngoài những người sáng lập của nó.

Khi giá trị đến tay một con người, nó đến qua Livelihood Direct — 🏠 — những kênh địa phương được cấp phép hợp lệ mà eXeL không bao giờ nắm giữ như một quỹ của riêng mình. Việc phân loại luôn diễn ra trước khi thanh toán trong mọi trường hợp, và sự công nhận một đóng góp không bao giờ là điều kiện để có một chỗ ngủ qua đêm; chỉ vai trò thực tế của một người trong một nhiệm vụ đã được xác định phạm vi mới là điều kiện đó. Sự tăng trưởng vượt ra ngoài giai đoạn thí điểm cũng có cổng kiểm soát: mỗi khối của khung khổ chỉ chuyển từ Thủ công sang Bán tự động rồi sang Tự động sau khi vượt qua quy tắc 11,1 phần trăm, một phần chín của cải thiện đã đo lường được, kiếm được từng khối một và không bao giờ được nhận trọn gói — và không bao giờ, trong bất kỳ hoàn cảnh nào, vượt qua tầng chủ quyền của ý nghĩa, tiền bạc, và luật pháp. Đây là cách ba người có tầm nhìn trên mỗi khu vực, ba khu vực, và một khởi đầu trở thành một lời hứa năm trăm năm: không phải bằng cách tiến nhanh, mà bằng cách chứng minh, trước mắt công chúng, rằng mỗi bước đi đều xứng đáng với bước tiếp theo.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Học qua mô phỏng`,
    content: {
      7: `Luyện tập ngàn lần trước khi chạm vào.`,
      33: `Không điều gì hệ trọng được học lần đầu trên phần cứng thực. Bất kỳ công dân nào cũng có thể luyện tập trong mô phỏng, luân chuyển qua ba khu vực, cùng ăn mừng — sự tôn trọng dành cho người trẻ mà sai lầm đầu tiên của họ không bao giờ được phép trả giá bằng một mạng người.`,
      111: `Mọi bộ môn đáng để tinh thông đều từng được ai đó học trước khi nó được biết đến. Hiệp ước Atlantis đưa trí tuệ cổ xưa này trở lại trung tâm của cách người trẻ — và bất kỳ công dân nào tham gia — được chuẩn bị để xây dựng tương lai. Không điều gì hệ trọng được học lần đầu trên phần cứng thực, trên con người thực, hay trong những điều kiện không thể đảo ngược; không cần sự cho phép của chính phủ hay sự chuẩn thuận của người sử dụng lao động. Mỗi người tham gia luyện tập trong mô phỏng cho đến khi luyện tập trở thành năng lực, rồi trở thành sự sẵn sàng. Mô hình luân chuyển đưa mỗi người tham gia qua ba khu vực sáng lập, và mỗi vòng luân chuyển kết thúc bằng một lễ ăn mừng công khai mở cửa cho cộng đồng chủ nhà. Đây là sự tôn trọng dành cho người trẻ mà sai lầm đầu tiên của họ không bao giờ được phép trả giá bằng một mạng người.`,
      333: `Mọi bộ môn đáng để tinh thông đều từng được ai đó học trước khi nó được biết đến. Những nghệ nhân bậc thầy luyện tập trước khi trình diễn, phi công luyện tập trước khi bay, bác sĩ luyện tập trước khi phẫu thuật, trẻ em học qua trò chơi. Hiệp ước Atlantis đưa trí tuệ cổ xưa này trở lại trung tâm của cách người trẻ — và bất kỳ công dân nào tham gia, không cần sự cho phép của chính phủ hay sự chuẩn thuận của người sử dụng lao động — được chuẩn bị để xây dựng tương lai. Không điều gì hệ trọng được học lần đầu trên phần cứng thực, trên con người thực, hay trong những điều kiện không thể đảo ngược. Mỗi người tham gia luyện tập trong mô phỏng cho đến khi luyện tập trở thành năng lực, rồi trở thành sự sẵn sàng. Đây không phải là sự thận trọng — đây là sự tôn trọng dành cho người trẻ mà sai lầm đầu tiên của họ không bao giờ được phép khiến ai đó trả giá bằng mạng sống.

Mô hình luân chuyển của hiệp ước đưa mỗi người tham gia qua ba khu vực sáng lập. Điều học được ở Campuchia được trau chuốt ở Honduras và hoàn thiện ở Austin. Điều khám phá được ở Austin được đặt câu hỏi ở Campuchia và tích hợp ở Honduras. Mỗi người tham gia sống, học, và được dìu dắt qua những nền văn hóa vốn dĩ xa cách nhau. Chương trình đào tạo lấy cảm hứng từ các truyền thống mô phỏng có kỷ luật trên nhiều nền văn hóa — từ truyền thống giáo dục chiến lược của Tôn Tử, từ phương pháp luyện tập-qua-chơi của Musashi, từ lý thuyết học tập theo chu kỳ của Ibn Khaldun, từ phép biện chứng tu viện của Nalanda, từ mô phỏng bay dân dụng — được tổng hợp để tôn trọng mọi giai đoạn nhận thức và di sản văn hóa. Không một truyền thống đơn lẻ nào chiếm ưu thế.

Mỗi vòng luân chuyển kết thúc bằng một lễ ăn mừng công khai mở cửa cho cộng đồng chủ nhà, nơi hàng xóm, gia đình, và khách thăm chứng kiến những gì nhóm học viên đã học được. Những sự kiện này khiến công nghệ tinh vi trở nên dễ tiếp cận và được chào đón thay vì đáng sợ — một xã hội lớn lên với sự thấu hiểu các hệ thống hợp tác qua trò chơi thì không dễ bị thao túng bởi nỗi sợ hãi về chúng. Đây là sự răn đe qua giáo dục, không phải qua vũ lực. Lời hứa của hiệp ước với mỗi phụ huynh: con bạn sẽ luyện tập hàng ngàn lần trong an toàn trước khi chạm vào bất cứ điều gì có thể gây hại, được chứng kiến để bất kỳ công dân nào — dù một thế kỷ sau — cũng có thể xác minh rằng nó đã diễn ra đúng như đã ghi lại. Đây là sự tôn trọng dành cho người trẻ được cài đặt vào trong một khung khổ, và đây là điều mà sự lãnh đạo nợ công dân kế tiếp tham gia trước khi công dân đó phải lên tiếng đòi hỏi.`,
      999: `Mọi bộ môn đáng để tinh thông đều từng được ai đó học trước khi nó được biết đến, và mọi nền văn minh trường tồn đều làm được điều đó bởi nó bảo vệ không gian nơi việc học ấy có thể diễn ra an toàn, trước khi nó được yêu cầu phải trở nên hệ trọng. Những nghệ nhân bậc thầy luyện tập trước khi trình diễn, phi công luyện tập trước khi bay, bác sĩ luyện tập trước khi phẫu thuật, và trẻ em luyện tập với thế giới qua trò chơi. Hiệp ước Atlantis đưa trí tuệ cổ xưa này trở lại trung tâm của cách người trẻ được chuẩn bị để xây dựng tương lai, và nó trao cho trí tuệ ấy một cái tên và một cơ chế: Replay. Không điều gì hệ trọng được học lần đầu trên phần cứng thực, trên con người thực, hay trong những điều kiện không thể đảo ngược. Mỗi người tham gia luyện tập trong mô phỏng cho đến khi luyện tập trở thành năng lực, rồi trở thành sự sẵn sàng, và mỗi giờ luyện tập ấy được ghi lại để có thể được tái dựng sau này, xem xét sau này, tin cậy sau này. Đây không phải là sự thận trọng — đây là sự tôn trọng dành cho người trẻ mà sai lầm đầu tiên của họ không bao giờ được phép khiến ai đó trả giá bằng mạng sống, và đây cũng là sự tôn trọng dành cho hồ sơ sẽ tồn tại lâu hơn chính sai lầm đó, dù thế nào đi nữa.

Mô hình luân chuyển của hiệp ước đưa mỗi người tham gia qua ba khu vực sáng lập. Điều học được ở Campuchia được trau chuốt ở Honduras và hoàn thiện ở Austin. Điều khám phá được ở Austin được đặt câu hỏi ở Campuchia và tích hợp ở Honduras. Mỗi người tham gia sống, học, và được dìu dắt qua những nền văn hóa vốn dĩ xa cách nhau, và mỗi vòng luân chuyển bắt đầu theo cách nó bắt đầu với mọi thể chế nhân loại đáng được tin cậy: bằng một Seed. Seed là khoản thành viên một lần, định giá bằng một phần bảy giờ lương tối thiểu địa phương, không thể chuyển nhượng, không mang bất kỳ quyền đòi hỏi kinh tế nào. Đó không phải là một khoản phí để tiếp cận cơ hội. Đó là một ngưỡng cửa — đủ nhỏ để không ai sẵn lòng tham gia bị loại vì giá cả, đủ chủ đích để việc gia nhập là một lựa chọn, chứ không phải một sự trôi dạt tình cờ. Từ ngưỡng cửa đó trở đi, mỗi người tham gia thuộc về vòng luân chuyển, và vòng luân chuyển không thuộc riêng về một khu vực nào.

Chương trình đào tạo lấy cảm hứng từ các truyền thống mô phỏng có kỷ luật trên nhiều nền văn hóa — từ truyền thống giáo dục chiến lược của Tôn Tử, từ phương pháp luyện tập-qua-chơi của Musashi, từ lý thuyết học tập theo chu kỳ của Ibn Khaldun, từ phép biện chứng tu viện của Nalanda, từ mô phỏng bay dân dụng — được tổng hợp để tôn trọng mọi giai đoạn nhận thức và di sản văn hóa. Không một truyền thống đơn lẻ nào chiếm ưu thế. Và trong chương trình này, hiệp ước vạch ra một ranh giới mà mọi người tham gia học được sớm và không bao giờ quên: mô phỏng là nơi Qualified Innovation Score được thấu hiểu, không phải nơi nó được tiêu dùng. QIS là phép đo, không bao giờ là khoản thanh toán, và QIS không bao giờ là quyền sở hữu — nó tồn tại để mô tả một đề xuất suy luận tốt đến đâu, đứng vững ra sao, và phục vụ khu vực mà nó tuyên bố phục vụ tốt đến đâu. Tăng trưởng QIS có thể định lượng một quỹ phần thưởng sau khi đạt điều kiện thực sự, nhưng tự nó không tạo ra bất cứ điều gì. Một người tham gia có thể chạy một trăm mô phỏng hoàn hảo và có điểm số tăng dần mà không một giờ 웃 nào chạm vào sổ cái của họ, bởi 웃 chỉ phát hành cho công việc được chứng kiến, thực hiện trong phạm vi một nhiệm vụ đã được xác định phạm vi, được duyệt ngân sách. Trước sự phê duyệt đó, mọi thứ — dù khéo léo đến đâu, dù hứa hẹn đến đâu — vẫn chỉ là lập kế hoạch. Hiệp ước dạy sự phân biệt này ngay từ ngày đầu tiên để không người trẻ nào nhầm lẫn giữa việc luyện tập và phần thưởng, và không người trẻ nào từng bị hiểu lầm về mục đích của mô phỏng.

Chính kỷ luật này cũng chi phối mức độ tự chủ mà bất kỳ hệ thống nào, con người hay nhân tạo, được phép thực thi trong vòng luân chuyển. Các chế độ vận hành của hiệp ước di chuyển theo trình tự — Thủ công, rồi Bán tự động, rồi Tự động — và không khối nào tiến lên một chế độ mới cho đến khi vượt qua quy tắc cải thiện đo lường được 11,1 phần trăm, một phần chín, được chứng minh so với một đường cơ sở đã đóng băng và được chứng kiến, chứ không phải được khẳng định suông. Mô phỏng là nơi bằng chứng đó được xây dựng. Một công cụ giành được quyền hành động với ít giám sát hơn theo cùng cách một người tham gia giành được quyền có trách nhiệm lớn hơn: qua sự cải thiện được chứng minh, được ghi lại, có thể tái dựng, từng khối một, không bao giờ tất cả cùng lúc, và không bao giờ vượt qua tầng nơi ý nghĩa, tiền bạc, và luật pháp được quyết định. Tầng đó chỉ thuộc về Human Authority, cả trong mô phỏng lẫn trong vận hành thực, bởi một không gian luyện tập dạy sai ranh giới sẽ dạy một bài học sai vĩnh viễn.

Mỗi vòng luân chuyển kết thúc bằng một lễ ăn mừng công khai và hợp tác, mở cửa cho cộng đồng chủ nhà. Hàng xóm, gia đình, và khách thăm tụ họp để chứng kiến những gì nhóm học viên đã học được, và điều họ chứng kiến không phải là một màn trình diễn tốc độ vì tốc độ, mà là một màn trình diễn của ◬ — mức chênh lệch đã đo lường được giữa một đường cơ sở đã đóng băng và những gì luyện tập có kỷ luật thực sự đạt được, được trình bày một cách trung thực, không bao giờ được khoác lên như một chỉ số lợi nhuận, không bao giờ được trình bày như nhiều hơn những gì nó thực sự là. Những sự kiện này khiến công nghệ tinh vi trở nên dễ tiếp cận và được chào đón thay vì đáng sợ. Một xã hội lớn lên với sự thấu hiểu các hệ thống hợp tác qua trò chơi thì không dễ bị thao túng bởi nỗi sợ hãi về những hệ thống đó. Đây là sự răn đe qua giáo dục, không phải sự răn đe qua vũ lực, và nó hiệu quả bởi cộng đồng không được yêu cầu phải tin vào một tuyên bố suông — họ được mời xem Replay.

Lời hứa của hiệp ước với mỗi phụ huynh vượt ra ngoài sự an toàn để chạm tới sự trường tồn: con bạn sẽ luyện tập hàng ngàn lần trước khi chạm vào bất cứ điều gì có thể gây hại, cộng đồng sẽ chứng kiến sự trưởng thành của con bạn suốt quá trình đó, và không điều gì trong số đó bị thời gian xóa nhòa. Measurement of Time ghi lại những phút giây thực sự tách biệt khỏi mọi sổ cái khác mà hiệp ước lưu giữ, để những giờ luyện tập và những giờ được chứng kiến không bao giờ bị nhầm lẫn với nhau, và để lịch sử phát triển thực sự của một người tham gia — không phải một bản tóm tắt, không phải một ước lượng, mà chính hồ sơ có thể tái dựng — vẫn sẵn có cho người đó tra cứu bao lâu tùy ý. Một phụ huynh ở Phnom Penh, một người cố vấn ở Tegucigalpa, một kiểm toán viên ở Austin, hay một cháu chắt đọc lại hồ sơ một thế kỷ sau đều có thể tiếp cận cùng một Replay và thấy cùng một sự thật.

Đây là hình hài của sự tôn trọng dành cho người trẻ khi nó được cài đặt vào trong một khung khổ chứ không chỉ đơn thuần được hứa hẹn bởi nó, và đây là điều mà sự lãnh đạo trao cho thế hệ người tham gia kế tiếp trước khi thế hệ đó phải lên tiếng đòi hỏi: một không gian luyện tập đủ rộng lớn để thất bại an toàn trong đó, đủ trung thực để ghi chép trung thành, và đủ kỷ luật để giữ phần thưởng, quyền tự chủ, và thẩm quyền đúng nơi mà sự tinh thông đã giành được chúng — không sớm hơn, và không muộn hơn.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `An toàn được kiểm chứng trước khi trao gửi niềm tin`,
    content: {
      7: `An toàn chứng minh trước, niềm tin trao sau.`,
      33: `Mọi cơ sở và vòng luân chuyển đều nằm trong một vành đai bảo vệ có cảnh báo sớm. Phần cứng từ chối bị vũ khí hóa — được chứng minh, không chỉ hứa hẹn, có thể kiểm tra bởi công dân. Hồ sơ vượt qua biến động. An toàn được thiết kế quanh người tham gia trẻ nhất, mỗi ngày.`,
      111: `Trước khi niềm tin được trao, an toàn phải được chứng minh — không phải cho một chính phủ, mà cho bất kỳ công dân nào kiểm tra nó. Hiệp ước Atlantis là một thỏa thuận giữa các công dân trên toàn thế giới; cam kết sáng lập của nó là: mọi cơ sở của hiệp ước, mọi tuyến luân chuyển, mọi nơi một người tham gia trẻ ngủ hay học tập đều nằm trong một vành đai bảo vệ được ghi chép với khả năng cảnh báo sớm, cho cộng đồng hàng giờ, chứ không phải hàng phút, để ứng phó với bất kỳ rủi ro đáng tin nào. Mọi thiết bị, mọi cảm biến, mọi hệ thống phối hợp đều bị ràng buộc ở tầng phần cứng để từ chối việc tái sử dụng cho tích hợp hệ thống vũ khí. Đây không phải là chính sách — đây là vật lý. Hiệp ước vẫn giữ được sự chính trực qua biến động, bởi mọi kế hoạch đều đặt phẩm giá con người lên hàng đầu.`,
      333: `Trước khi niềm tin được trao, an toàn phải được chứng minh — chứng minh cho công dân, không phải được khẳng định suông. Hiệp ước Atlantis là một thỏa thuận giữa các công dân trên toàn thế giới: bất kỳ ai, ở bất cứ đâu, đều có thể giúp gìn giữ nó, bất kể chính phủ của họ ký kết điều gì. Mọi cơ sở của hiệp ước, mọi tuyến luân chuyển, mọi nơi một người tham gia trẻ ngủ hay học tập đều nằm trong một vành đai bảo vệ được ghi chép với khả năng cảnh báo sớm, cho cộng đồng hàng giờ, chứ không phải hàng phút, để ứng phó với bất kỳ rủi ro đáng tin nào. Công nghệ bảo vệ họ chính là công nghệ mà hiệp ước dạy họ xây dựng. Người trẻ học về an toàn từ bên trong ra ngoài, không phải bằng cách được nói rằng họ an toàn, mà bằng cách chứng kiến nó được thiết kế quanh mình mỗi ngày, và biết rằng bất kỳ công dân nào cũng có thể xác minh hồ sơ qua Replay.

Hiệp ước đưa ra một lời hứa không thể phá vỡ về những gì công nghệ của nó không thể trở thành. Mọi thiết bị, mọi cảm biến, mọi hệ thống phối hợp đều bị ràng buộc ở tầng phần cứng để từ chối việc tái sử dụng cho tích hợp hệ thống vũ khí. Đây không phải là ngôn ngữ chính sách, không phải là khát vọng. Đây là một sự bất khả thi về mặt vật lý, được thực thi bằng mật mã học, được xác minh bởi mọi khu vực ký kết, và có thể kiểm tra bởi mọi công dân tài trợ cho nó. Những công cụ bảo vệ một đứa trẻ ở Phnom Penh không thể được tái sử dụng để gây hại cho một đứa trẻ ở Austin. Những công cụ kết nối một bài tập bầy đàn ở Tegucigalpa không thể bị cấu hình lại để nhắm vào bất kỳ con người nào, ở bất cứ đâu. Đây là câu trả lời của hiệp ước cho một thế kỷ lo sợ về công nghệ lưỡng dụng. Không phải chính sách — mà là vật lý.

Hiệp ước vẫn giữ được sự chính trực qua biến động. Nếu một khu vực mất ổn định chính trị, người tham gia được các khu vực còn lại đón nhận. Nếu nguồn tài trợ thu hẹp, các khoản trợ cấp được bảo vệ trước tiên — được công dân tài trợ hàng tháng, không bao giờ là một kênh viện trợ, mọi đồng đô la đều có thể truy vết. Nếu hồ sơ số bị tấn công, các bản sao lưu ngoại tuyến vẫn tồn tại. Nếu việc di chuyển trở nên bất khả thi, nền tảng vẫn tiếp tục vận hành ảo. Mọi kế hoạch đều đặt phẩm giá con người — Human Authority đối với ý nghĩa, tiền bạc, và luật pháp — làm ràng buộc thiết kế đầu tiên. Các nhà lãnh đạo ký hiệp ước này hứa rằng an toàn được thiết kế, chứ không được mặc định: sự bảo vệ mà bất kỳ nhà lãnh đạo nào cũng đòi hỏi cho con mình, nay được mở rộng cho mọi công dân giúp gìn giữ nó.`,
      999: `Trước khi niềm tin được trao, an toàn phải được chứng minh — đây là cam kết sáng lập của Hiệp ước Atlantis, và nó được chứng minh theo cùng cách mọi tuyên bố khác trong Vision • 2525 được chứng minh: không phải bằng sự khẳng định, mà bằng bằng chứng mà công dân có thể kiểm tra. Mọi cơ sở của hiệp ước, mọi tuyến luân chuyển, mọi nơi một người tham gia trẻ ngủ hay học tập đều nằm trong một vành đai bảo vệ được ghi chép với khả năng cảnh báo sớm, cho cộng đồng hàng giờ, chứ không phải hàng phút, để ứng phó với bất kỳ rủi ro đáng tin nào. Công nghệ dùng để bảo vệ người tham gia chính là công nghệ mà hiệp ước dạy họ xây dựng — cảm biến, phối hợp, khả năng tồn tại của truyền thông, trí tuệ phân tán. Người trẻ học về an toàn từ bên trong ra ngoài, bằng chính ngôn ngữ và tại chính khu vực của mình, không phải bằng cách được nói rằng họ an toàn, mà bằng cách quan sát, từng giờ một, cách an toàn được thiết kế quanh mình mỗi ngày.

Sự quan sát đó không được phó mặc cho trí nhớ hay niềm tin vào lời nói của một người hướng dẫn. Measurement of Time ghi lại những phút giây thực sự của mỗi buổi diễn tập, mỗi vòng luân chuyển, mỗi bài tập ứng phó — tách biệt khỏi bất kỳ tuyên bố tiến bộ nào, tách biệt khỏi bất kỳ câu chuyện nào được kể trong ngày hôm đó. Replay khiến mọi bản phát hành của chương trình đào tạo, mọi cập nhật an toàn, mọi bản sửa đổi phần cứng có thể được tái dựng đầy đủ, để một phụ huynh ở Tegucigalpa hay một cơ quan quản lý ở Phnom Penh có thể lần ngược lại chính xác điều gì đã thay đổi, khi nào nó thay đổi, và tại sao nó thay đổi. Một vành đai bảo vệ không thể được phát lại chỉ là một lời hứa. Một vành đai bảo vệ có thể được phát lại, từng phút được ghi nhận, là một bằng chứng. Hiệp ước chọn bằng chứng.

Hiệp ước đưa ra một lời hứa không thể phá vỡ về những gì công nghệ của nó không thể trở thành. Mọi thiết bị, mọi cảm biến, mọi hệ thống phối hợp đều bị ràng buộc ở tầng phần cứng để từ chối việc tái sử dụng cho tích hợp hệ thống vũ khí. Đây không phải là ngôn ngữ chính sách, không phải là khát vọng. Đây là một sự bất khả thi về mặt vật lý, được thực thi bằng mật mã học, được xác minh bởi mọi khu vực ký kết, và có thể kiểm tra bởi mọi công dân. Những công cụ bảo vệ một đứa trẻ ở Phnom Penh không thể được tái sử dụng để gây hại cho một đứa trẻ ở Austin. Những công cụ kết nối một bài tập bầy đàn ở Tegucigalpa không thể bị cấu hình lại để nhắm vào bất kỳ con người nào, ở bất cứ đâu. Đây là câu trả lời của hiệp ước cho một thế kỷ lo sợ về công nghệ lưỡng dụng. Không phải chính sách — mà là vật lý.

An toàn được chứng minh một lần không phải là an toàn được duy trì suốt một chân trời năm trăm năm. Hiệp ước gọi cam kết thứ hai của mình là Continuity Without Evasion: tính khả chuyển hợp pháp qua mọi thẩm quyền tài phán mà hiệp ước chạm tới, không một chính phủ, ngân hàng, người sáng lập, hay mô hình đơn lẻ nào đứng giữa một người tham gia và sự bảo vệ của họ. Mỗi thẩm quyền tài phán được phục vụ bởi bộ điều hợp riêng của mình, thất bại an toàn và mặc định từ chối, để một phán quyết bất lợi tại một khu vực chỉ đóng kênh đó lại — không bao giờ toàn bộ khung khổ, không bao giờ mọi khu vực, không bao giờ mọi người tham gia ở khắp mọi nơi cùng lúc. Một phán quyết tòa án tại một lãnh thổ ký kết không thể tắt vành đai an toàn của một người tham gia ở nơi khác. Đây là ý nghĩa của việc xây dựng một hệ thống sống sót qua những biến động thông thường của luật pháp, chính trị, và thay đổi thể chế mà không bao giờ yêu cầu một người tham gia phải trốn tránh luật pháp để được bảo vệ.

Mỗi tầng của kiến trúc bảo vệ này, cuối cùng, đều chịu trách nhiệm trước Human Authority. Ý nghĩa, tiền bạc, và luật pháp không bao giờ được giao phó cho máy móc — tầng chủ quyền quyết định điều gì an toàn đòi hỏi, điều gì cấu thành một rủi ro đáng tin, và cộng đồng nợ những thành viên trẻ nhất của mình phản ứng nào, vẫn đóng cửa với trí tuệ nhân tạo, dù nó có trở nên tài giỏi đến đâu. Các hệ thống của hiệp ước chỉ di chuyển qua ba chế độ vận hành — Thủ công, Bán tự động, Tự động — và không hệ thống nào tiến lên một chế độ mới mà không có một sự cải thiện được chứng kiến, đo lường được ít nhất một phần chín, mười một phẩy một phần trăm, được xác minh, có thể tái tạo. Quyền tự chủ được giành được, từng khối một, từng chức năng một, không bao giờ được cấp trọn gói, và không bao giờ mở rộng qua những câu hỏi quyết định ý nghĩa, tiền bạc, hay luật pháp. Một cảm biến có thể học cách phát hiện nhanh hơn. Một hệ thống phối hợp có thể học cách định tuyến hiệu quả hơn. Không hệ thống nào được phép, một mình, quyết định điều gì một cộng đồng nên tin tưởng giao phó cho con em mình.

Hiệp ước được thiết kế để giữ được sự chính trực qua biến động, và nó gọi tên biến động trước, thay vì phát hiện nó trong khủng hoảng. Nếu một khu vực ký kết mất ổn định chính trị, người tham gia được các khu vực còn lại đón nhận. Nếu nguồn tài trợ thu hẹp, các khoản trợ cấp của người tham gia được bảo vệ trước tiên, trước cả hành chính và hạ tầng. Nếu hồ sơ số bị tấn công, các bản sao lưu ngoại tuyến vẫn tồn tại, không thể chạm tới bởi bất kỳ sự cố nào đã ảnh hưởng đến mạng lưới. Nếu việc di chuyển trở nên bất khả thi, nền tảng vẫn tiếp tục vận hành ảo, để một vòng luân chuyển không dừng lại chỉ vì một biên giới đóng cửa. Mọi kịch bản đều được lên kế hoạch trước, và mọi kế hoạch đều đặt phẩm giá con người làm ràng buộc thiết kế đầu tiên — chứ không phải cân nhắc cuối cùng sau khi ngân sách và hình ảnh đã được thu xếp.

Việc gia nhập hệ thống đã được chứng minh này bắt đầu với Seed — một khoản thành viên một lần, định giá bằng một phần bảy giờ lương tối thiểu địa phương, không thể chuyển nhượng, và không mang bất kỳ quyền đòi hỏi kinh tế nào đối với bất cứ điều gì hiệp ước xây dựng sau đó. Seed không mua an toàn; an toàn được thiết kế từ rất lâu trước khi bất kỳ Seed nào được gieo trồng. Điều Seed mua là tư cách — quyền bước vào một khung khổ đã được chứng minh, đã được kiểm tra, đã bị ràng buộc bởi phần cứng không thể bị quay ngược lại chống chính người mà nó tồn tại để bảo vệ. Sự tách biệt này là có chủ đích. Một lời hứa an toàn phải được mua bằng một cái giá kinh tế thực sự thì không phải là một lời hứa an toàn, mà chỉ là một sản phẩm an toàn. Hiệp ước giữ hai điều này tách biệt tuyệt đối, để không gia đình nào phải cân nhắc giữa sự bảo vệ của con mình và ngân sách hàng tháng của gia đình.

Các nhà lãnh đạo ký hiệp ước này đang ký một lời hứa rằng an toàn được thiết kế, chứ không được mặc định, và được chứng minh, chứ không chỉ đơn thuần được tuyên bố. Điều họ mở rộng cho công dân của mình không chỉ là cơ hội, mà là sự bảo vệ được xây dựng theo chuẩn mực mà người tham gia trẻ nhất xứng đáng có được — được Measurement of Time ghi lại, có thể tái dựng qua Replay, bị ràng buộc ở tầng phần cứng chống lại mọi sự lạm dụng mà một thế kỷ đầy lo sợ đã tưởng tượng ra, và chịu trách nhiệm, luôn luôn và chỉ, trước Human Authority. Đây là chính sự bảo vệ mà bất kỳ nhà lãnh đạo nào cũng sẽ đòi hỏi cho con mình khi vượt qua một biên giới xa lạ một mình, nay được mở rộng cho mọi đứa trẻ mà hiệp ước sẽ từng phục vụ, qua ba khu vực sáng lập Campuchia, Honduras, và Austin, và qua năm thế kỷ mà hiệp ước dự định giữ lời hứa này.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Đãi ngộ, an sinh và phẩm giá con người`,
    content: {
      7: `Một khoản trợ cấp, một người dìu dắt, một mái nhà.`,
      33: `Mọi công dân nhận trợ cấp từ ngày đầu tiên — không cần sự cho phép của chính phủ, không cần sự chuẩn thuận của người sử dụng lao động. Tình yêu, mất mát, và an toàn là hạ tầng. Thành công được đo bằng người dễ tổn thương nhất. Phẩm giá là nền tảng, không bao giờ là trang trí.`,
      111: `Hiệp ước Atlantis đối xử với mỗi người tham gia như một con người ngay từ ngày đầu tiên — một công dân đã gia nhập theo quyền của mình, không phải theo sắc lệnh của chính phủ hay sự cho phép của người sử dụng lao động. Một khoản trợ cấp được cung cấp từ khoảnh khắc sự tham gia bắt đầu, được điều chỉnh theo mức sinh hoạt của khu vực, và mỗi giờ được chứng kiến tạo ra 웃, được trả cho con người qua Livelihood Direct, không bao giờ qua sổ sách của một người sử dụng lao động. Sự an lành được đối xử như hạ tầng hạng nhất — không phải một đặc quyền, mà là nền tảng mà mọi thứ khác đứng trên đó. Ba lĩnh vực được hỗ trợ: Tình yêu, Mất mát, và An toàn. Hiệp ước đo lường thành công bằng người tham gia dễ tổn thương nhất, không phải mức trung bình. Không ai bị lãng quên chỉ để những con số trung bình trông đẹp mắt. Phẩm giá là nền tảng, không phải trang trí.`,
      333: `Hiệp ước Atlantis đối xử với mỗi người tham gia như một con người ngay từ ngày đầu tiên — một công dân thuộc về nó theo quyền của mình, không cần sự cho phép của chính phủ, không cần sự chuẩn thuận của người sử dụng lao động. Một khoản trợ cấp được cung cấp từ khoảnh khắc sự tham gia bắt đầu, được điều chỉnh theo mức sinh hoạt của khu vực, đến trước khi các trách nhiệm gia đình trở thành những tình huống khẩn cấp. Đây không phải là từ thiện. Đây là sự công nhận rằng sự đổi mới bình thường của con người trước tiên cần sự an toàn của con người — một tâm trí không thể phát triển khi mái ấm của nó đang bị đe dọa.

Điều kiếm được ngoài khoản trợ cấp được kiếm theo cách một công dân kiếm nó: qua Seed, định giá bằng một phần bảy giờ lương tối thiểu địa phương, và qua 웃, chỉ trả cho những giờ được chứng kiến. QIS đo lường triển vọng nhưng không tạo ra bất cứ điều gì — đó là phép đo, không bao giờ là thanh toán. Mọi khoản thanh toán đến với người tham gia qua Livelihood Direct, những kênh địa phương được cấp phép mà hiệp ước không bao giờ nắm giữ, được xây dựng cho Continuity Without Evasion.

Sự an lành được đối xử như hạ tầng hạng nhất — không phải một đặc quyền, mà là nền tảng mà mọi thứ khác đứng trên đó. Hiệp ước gọi tên ba lĩnh vực mà mọi người tham gia được hỗ trợ: Tình yêu, sự kết nối và ranh giới lành mạnh; Mất mát, bởi nỗi đau buồn phải được đồng hành, không phải bị né tránh; và An toàn, biết gọi ai, ở mọi khu vực, bằng chính ngôn ngữ của mình. Tư vấn tâm lý, những vòng tròn nhóm, và các thực hành văn hóa hay tâm linh được tôn trọng theo từng truyền thống đều được cung cấp. Không hệ tư tưởng nào bị ép buộc; Human Authority, không bao giờ là máy móc, quyết định một công dân cần sự chăm sóc gì.

Hiệp ước đo lường thành công bằng người tham gia dễ tổn thương nhất, không phải mức trung bình. Công dân nông thôn không có băng thông cao được phục vụ. Người tham gia có sự khác biệt thần kinh nhận được sự hỗ trợ như một chuẩn mực. Người tham gia khuyết tật thấy mọi cơ sở đều dễ tiếp cận. Người tham gia đa dạng giới tính nhận được chỗ ở an toàn và được ghép cặp với người cố vấn. Người nói ngôn ngữ không phải bản ngữ thấy mọi tài liệu bằng ngôn ngữ của mình. Người tham gia bản địa thấy các thực hành văn hóa của mình được tôn trọng và tri thức truyền thống của mình được bảo vệ. Các nhà lãnh đạo ký hiệp ước này hứa rằng không công dân nào bị lãng quên chỉ để những con số trung bình trông đẹp mắt. Đây là phẩm giá như nền tảng, không phải trang trí. Điều được đo lường là điều sẽ được tôn trọng, và điều được tôn trọng ở đây là con người toàn vẹn — tâm trí, thể xác, và tinh thần, được đồng bào công dân nâng đỡ, không có ngoại lệ.`,
      999: `Hiệp ước Atlantis đối xử với mỗi người tham gia như một con người trọn vẹn ngay từ ngày đầu tiên, được cài đặt thành cơ chế, không chỉ đơn thuần là ngôn từ. Một khoản trợ cấp được cung cấp từ khoảnh khắc sự tham gia bắt đầu, được điều chỉnh theo mức sinh hoạt của khu vực để tác động của nó tôn trọng phẩm giá lao động địa phương. Khoản trợ cấp đến trước khi các trách nhiệm gia đình trở thành những tình huống khẩn cấp, và trước khi phẩm giá bị tổn hại. Nó báo hiệu cho mỗi người trẻ rằng thời gian của họ có giá trị, đóng góp của họ được kỳ vọng, và sự ổn định của gia đình họ là một phần trách nhiệm của hiệp ước. Đây không phải là từ thiện. Đây là sự công nhận rằng sự đổi mới bình thường của con người trước tiên cần sự an toàn của con người. Một tâm trí không thể phát triển khi mái ấm của nó đang bị đe dọa. Chính việc gia nhập mang theo một ngưỡng cửa nhỏ, có chủ đích: Seed, một khoản thành viên một lần định giá bằng một phần bảy giờ lương tối thiểu địa phương, không thể chuyển nhượng và không mang bất kỳ quyền đòi hỏi kinh tế nào của riêng nó. Seed chỉ nói rằng một người đã gia nhập; nó không trả tiền cho họ và không hứa hẹn gì với họ ngoài cánh cửa mà nó mở ra.

Điều kiếm được sau khi cánh cửa đó mở ra được điều hành với cùng sự chính xác mà hiệp ước mang đến cho mọi lời hứa khác của mình. 웃, thước đo Trí tuệ Con người của hiệp ước, được tính đơn giản — một giờ theo lương tối thiểu địa phương, nhân với Hệ số phản ánh độ khó và giá trị của nhiệm vụ, nhân với số giờ thực sự làm việc. Nhưng 웃 chỉ phát hành cho công việc được chứng kiến, thực hiện trong phạm vi một nhiệm vụ đã được xác định phạm vi, được duyệt ngân sách. Trước khi sự phê duyệt đó tồn tại, điều một người tham gia đang làm là lập kế hoạch, không phải lao động được trả công — một sự phân biệt mà hiệp ước giữ vững bởi nó bảo vệ cả ngân khố lẫn người tham gia khỏi những lời hứa được đưa ra nhanh hơn giá trị được xác minh. Measurement of Time, MoT, ghi lại những phút giây thực sự làm việc tách biệt khỏi bất kỳ phép tính thù lao nào, để thời gian vẫn là một sự thật trung thực, có thể kiểm toán, độc lập với thanh toán. Không giờ làm việc nào của người tham gia bị thổi phồng, và không giờ làm việc nào của người tham gia biến mất. Một trần thanh toán 9.999 웃 mỗi năm áp dụng cho mọi người tham gia, với bất kỳ phần dư nào được chuyển tiếp sang năm sau thay vì biến mất, để đóng góp xuất sắc được ghi nhận qua nhiều năm thay vì bị giới hạn vô hình trong một năm.

Thù lao được giữ tách biệt có chủ đích khỏi phép đo đổi mới. Qualified Innovation Score, QIS, lấy trung bình Doanh thu, Lợi nhuận gộp, Thu nhập hoạt động, và chi tiêu R&D hiệu quả để mô tả mức độ đổi mới thực sự đã tăng trưởng. Sự tăng trưởng của nó theo thời gian có thể định lượng một quỹ phần thưởng một khi đạt điều kiện, nhưng bản thân QIS không tạo ra 웃 và không thanh toán trực tiếp bất cứ điều gì — đó là một phép đo, không bao giờ là thanh toán, và không bao giờ bị nhầm lẫn với quyền sở hữu những gì đã được xây dựng. Sự tách biệt này quan trọng bởi nó giữ khoản trợ cấp và mức lương trung thực: một người tham gia được trả cho những giờ được chứng kiến của công việc thực sự, không phải cho một điểm số có thể bị thao túng, thổi phồng, hay tranh cãi. ♡, Ý định Chung, mang theo lý do đằng sau mỗi nhiệm vụ mà một người tham gia đảm nhận; ◬, sự tăng tốc được chứng kiến mà một nhiệm vụ mang lại so với một đường cơ sở đã đóng băng, được ghi lại chỉ như một mức chênh lệch, không bao giờ được tô vẽ thành một chỉ số lợi nhuận gắn với lao động của bất kỳ ai. Thù lao vẫn giữ đúng bản chất của nó: một mức lương trung thực cho thời gian trung thực, được chứng kiến.

Giá trị không dừng lại ở phép tính — nó cũng phải đến tay người tham gia như một con người đang sống, và đây là nơi 🏠, Livelihood Direct, thực hiện công việc của mình. Mỗi đơn vị giá trị mà một người tham gia kiếm được đến với họ qua những kênh địa phương đã được cấp phép hợp lệ — ngân hàng, nhà điều hành tiền di động, hợp tác xã đã được tin cậy và quản lý tại khu vực đó — không bao giờ qua một quỹ mà chính hiệp ước nắm giữ hay kiểm soát. Việc phân loại tình trạng của một người tham gia luôn diễn ra trước bất kỳ khoản thanh toán nào; không gì được trả trước khi biết rõ ai đang được trả và vì điều gì. Và sự công nhận tài năng, dù được ca ngợi đến đâu, không phải là điều kiện để có một chỗ ngủ, một bữa ăn, hay một vị trí trong nhóm — chỉ vai trò thực tế của người tham gia mới là điều kiện đó. Đây là một sự từ chối có chủ đích để không cho phép uy tín thay thế cho sự cung cấp. Một người đóng góp xuất sắc và một người trầm lặng ngủ dưới cùng một mái nhà được bảo vệ, theo cùng những điều kiện, bởi các cam kết về phẩm giá của hiệp ước không phải là một giải thưởng trao cho sự xuất sắc — chúng là một sàn nền dưới chân mọi người.

Sự an lành được đối xử như hạ tầng hạng nhất — không phải một phúc lợi tùy chọn, không phải một đặc quyền chăm sóc sức khỏe, mà là nền tảng mà mọi thứ khác đứng trên đó. Hiệp ước gọi tên ba lĩnh vực nền tảng mà mọi người tham gia được hỗ trợ: Tình yêu, theo nghĩa kết nối, sự gắn bó, và ranh giới lành mạnh; Mất mát, bởi mọi người tham gia sẽ trải qua nỗi đau buồn và phải được đồng hành, không phải bị né tránh; và An toàn, theo nghĩa mọi người tham gia biết gọi ai, ở mọi khu vực, bằng chính ngôn ngữ của mình. Tư vấn cá nhân, những vòng tròn nhóm, các thực hành thân thể, và các thực hành văn hóa hay tâm linh được tôn trọng theo truyền thống riêng của người tham gia đều được cung cấp. Không hệ tư tưởng nào bị ép buộc. Hiệp ước giữ không gian với sự tôn kính; nó không truyền bá bất kỳ hệ thống niềm tin nào. Human Authority chi phối mọi quyết định trong số này — ý nghĩa, tiền bạc, và luật pháp vẫn đóng cửa với sự quyết định của máy móc, dù việc khớp mẫu hỗ trợ những con người đưa ra quyết định có tinh vi đến đâu.

Hiệp ước đo lường thành công bằng kết quả của người tham gia dễ tổn thương nhất, không phải mức trung bình. Người tham gia nông thôn không có băng thông cao được phục vụ. Người tham gia có sự khác biệt thần kinh nhận được sự hỗ trợ như một chuẩn mực. Người tham gia khuyết tật thấy mọi cơ sở đều dễ tiếp cận. Người tham gia đa dạng giới tính nhận được chỗ ở an toàn và được ghép cặp với người cố vấn. Người nói ngôn ngữ không phải bản ngữ thấy mọi tài liệu bằng ngôn ngữ của mình. Người tham gia bản địa thấy các thực hành văn hóa của mình được tôn trọng và tri thức truyền thống của mình được bảo vệ. Các nhà lãnh đạo ký hiệp ước này hứa rằng không người tham gia nào bị lặng lẽ lãng quên chỉ để những con số trung bình trông đẹp mắt.

Mọi con đường thanh toán được mô tả ở đây — Seed, khoản trợ cấp, 웃 kiếm được từ công việc được chứng kiến, kênh Livelihood Direct chuyển giao nó — đều được thiết kế cho Continuity Without Evasion. Không một ngân hàng, chính phủ, hay nhà điều hành địa phương đơn lẻ nào là không thể thay thế đối với thù lao của bất kỳ người tham gia nào; nếu một kênh được cấp phép tại một thẩm quyền tài phán bị đóng bởi một phán quyết bất lợi, chỉ riêng kênh đó thất bại, không bao giờ toàn bộ hệ thống, và không bao giờ quyền đòi hỏi của người tham gia đối với những gì họ đáng được nhận. Đây là phẩm giá như nền tảng, không phải trang trí. Điều được đo lường là điều sẽ được tôn trọng, và điều được tôn trọng ở đây là con người toàn vẹn — tâm trí, thể xác, và tinh thần cùng nhau, được trả công trung thực, được bảo vệ trọn vẹn, và không bị lãng quên bởi bất kỳ sổ sách nào, không có ngoại lệ nào cả.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Tài trợ và quản trị`,
    content: {
      7: `Công dân trực tiếp tài trợ thế hệ kế tiếp.`,
      33: `Hiệp ước Atlantis là một thỏa thuận giữa các công dân — ai cũng có thể tài trợ và gìn giữ nó. Không có kênh viện trợ, không có nhà tài trợ nước ngoài, không có ràng buộc chính trị. Mọi đồng đô la đều có thể truy vết, sổ sách công khai hàng tháng, bằng mọi ngôn ngữ.`,
      111: `Hiệp ước Atlantis là một thỏa thuận giữa các công dân trên toàn thế giới — bất kỳ ai, ở bất cứ đâu, đều có thể giúp tạo lập và gìn giữ nó, bất kể chính phủ của họ ký kết điều gì hay ai thuê họ làm việc. Chính phủ, nhà giáo dục, và nhà đổi mới ký kết với tư cách người quản lý khu vực của mình; công dân trực tiếp tài trợ, chứng kiến, và buộc hiệp ước chịu trách nhiệm, mỗi người đóng góp những khoản nhỏ tự nguyện mỗi tháng, đủ khiêm tốn để không người trưởng thành nào bị loại vì giá cả. Không có kênh viện trợ, không có nhà tài trợ nước ngoài, không có ràng buộc chính trị nào đi kèm. Hiệp ước đứng độc lập với các thể chế đa phương đã định hình thế kỷ trước — không phải một tuyên bố chính trị, mà là một lựa chọn thiết kế. Mọi đồng đô la đều có thể truy vết; mọi sổ sách được công bố hàng tháng, bằng mọi ngôn ngữ.`,
      333: `Hiệp ước Atlantis là một thỏa thuận giữa các công dân trên toàn thế giới — bất kỳ ai, ở bất cứ đâu, đều có thể giúp tạo lập và gìn giữ nó, bất kể chính phủ của họ ký kết điều gì hay ai thuê họ làm việc. Nó được tài trợ bởi chính những công dân mà nó phục vụ: cư dân của các khu vực tham gia đóng góp những khoản nhỏ tự nguyện mỗi tháng, đủ khiêm tốn để không người trưởng thành nào bị loại vì giá cả, đủ vang vọng để tổng số duy trì công việc của hiệp ước ở quy mô cần thiết. Khi một công dân trực tiếp tài trợ cho thế hệ kế tiếp, công dân đó trực tiếp buộc hiệp ước chịu trách nhiệm. Không có kênh viện trợ, không có nhà tài trợ nước ngoài, không có ràng buộc chính trị nào đi kèm. Linh hồn của hiệp ước là người công dân đóng góp một khoản nhỏ mỗi tháng, người mà sự tham gia của họ khiến tất cả trở nên khả thi.

Chính phủ, Giáo dục, và Đổi mới ký kết với tư cách người quản lý khu vực của mình — ba chữ ký mang tầm nhìn ràng buộc một khu vực phải đón nhận, bảo vệ, và giảng dạy — nhưng vai trò quản lý không phải là quyền sở hữu. Hiệp ước độc lập với các thể chế đa phương đã định hình thế kỷ trước — Tổ chức Hiệp ước Bắc Đại Tây Dương, Tổ chức Y tế Thế giới, Liên Hợp Quốc, Quỹ Tiền tệ Quốc tế, Ngân hàng Thế giới, và mọi kênh viện trợ nước ngoài của các quốc gia. Đây là một lựa chọn thiết kế, không phải một tuyên bố chính trị: một khung khổ phục vụ mọi khu vực bất kể liên kết địa chính trị thì không thể bị vướng mắc với bất kỳ liên kết nào. Các chính phủ quốc gia có thể đóng góp tự nguyện. Các khoản đóng góp minh bạch. Không khoản đóng góp nào mua được ảnh hưởng quản trị, từ bất kỳ nguồn nào, bao giờ.

Mỗi đồng đô la và mỗi đơn vị giá trị đi vào hiệp ước đều được ghi lại vĩnh viễn, công khai, và có thể truy vết — có thể tái dựng qua Replay, để một công dân một thế kỷ sau có thể xác minh chuỗi liên kết không đứt đoạn. Giá trị đến tay người tham gia qua những giờ 웃 được chứng kiến và những kênh địa phương được cấp phép, không bao giờ qua một quỹ mà chính hiệp ước nắm giữ; QIS đo lường trung thực, nó không bao giờ trả tiền. Chi phí hành chính bị giới hạn, các khoản quà tặng doanh nghiệp cũng bị giới hạn tương tự. Sổ sách đầy đủ được cung cấp bằng ngôn ngữ của mỗi khu vực ký kết mỗi tháng. Các nhà lãnh đạo ký hiệp ước hứa hẹn một sự minh bạch hiếm khi được bất kỳ thể chế nào cung cấp. Đây là niềm tin mà hiệp ước đòi hỏi — được kiếm được từng khoản đóng góp nhỏ có thể truy vết một lần, trước mắt mọi công dân.`,
      999: `Chính Hiệp ước Atlantis được tài trợ bởi những công dân mà nó phục vụ, và sự thật đơn giản đó định hình mọi thứ tiếp theo — mọi kênh, mọi sổ cái, mọi cổng mà một người trẻ phải vượt qua để được nhìn thấy. Những cư dân bình thường của các khu vực tham gia đóng góp những khoản nhỏ tự nguyện mỗi tháng, những khoản đủ khiêm tốn để không người trưởng thành nào tại bất kỳ khu vực chủ nhà nào bị loại khỏi sự tham gia vì giá cả, đủ vang vọng để tổng số duy trì công việc của hiệp ước ở quy mô có ý nghĩa. Thiết kế này là có chủ đích, và nó không phải là ngẫu nhiên đối với sứ mệnh — nó chính là bằng chứng của sứ mệnh. Khi một công dân trực tiếp tài trợ cho việc giáo dục thế hệ kế tiếp, công dân đó trực tiếp buộc hiệp ước chịu trách nhiệm, trong cùng một hơi thở, không qua một trung gian nào có thể làm mềm sổ sách hay trì hoãn sự thanh toán. Không có kênh viện trợ, không có nhà tài trợ nước ngoài, không có ràng buộc chính trị nào đi kèm tấm séc. Linh hồn của hiệp ước là người công dân đóng góp một khoản nhỏ mỗi tháng, người mà sự tham gia của họ khiến toàn bộ trở nên khả thi, và sự tham gia liên tục của họ là lá phiếu tín nhiệm duy nhất thực sự quan trọng qua năm trăm năm.

Hiệp ước độc lập một cách có chủ đích với các thể chế đa phương đã định hình thế kỷ trước — Tổ chức Hiệp ước Bắc Đại Tây Dương, Tổ chức Y tế Thế giới, Liên Hợp Quốc, Quỹ Tiền tệ Quốc tế, Ngân hàng Thế giới, và mọi kênh viện trợ nước ngoài của các quốc gia. Đây không phải là một tuyên bố chính trị về giá trị của những thể chế đó hay đóng góp của chúng. Đây là một lựa chọn thiết kế, và đó là cùng lựa chọn thiết kế chi phối mọi kênh kỹ thuật bên dưới chính hiệp ước: Continuity Without Evasion. Tính khả chuyển hợp pháp là quy tắc — không một chính phủ, ngân hàng, người sáng lập, hay mô hình đơn lẻ nào được không thể thay thế đến mức có thể nằm bên dưới toàn bộ cấu trúc, bởi một chân trời năm trăm năm không thể đặt cược vào sự trường tồn của bất kỳ chủ thể đơn lẻ nào. Mỗi thẩm quyền tài phán mang bộ điều hợp riêng của mình, thất bại an toàn và mặc định từ chối, để một phán quyết bất lợi tại một quốc gia chỉ đóng riêng kênh đó lại — nó không bao giờ kéo sập tài khoản của một gia đình tại một khu vực cách xa một đại dương. Các chính phủ quốc gia có thể đóng góp tự nguyện. Các khoản đóng góp minh bạch. Không khoản đóng góp nào mua được ảnh hưởng quản trị, từ bất kỳ nguồn nào, bao giờ — không từ một chính phủ, không từ một doanh nghiệp, không từ chính những người sáng lập khung khổ.

Human Authority là trụ cột chịu lực thứ hai bên dưới thiết kế tài trợ này. Ý nghĩa, tiền bạc, và luật pháp vẫn là những vấn đề của con người, được quyết định bởi con người trước mắt những con người khác; tầng chủ quyền nơi mục đích của hiệp ước được thiết lập và quỹ của nó được quản trị vẫn đóng cửa với máy móc, dù chúng có trở nên tài giỏi đến đâu ở những nhiệm vụ bên dưới nó. Measurement of Time ghi lại những phút giây thực sự làm việc tách biệt khỏi bất kỳ tuyên bố nào về giá trị của chúng, để không ai — con người hay nhân tạo — có thể lặng lẽ thổi phồng hồ sơ. Replay đứng sau mỗi hồ sơ trong số đó, khiến mọi bản phát hành mà hiệp ước từng công bố có thể được tái dựng từ nguồn gốc, mãi mãi mở cho sự thách thức, mãi mãi mở cho sự sửa chữa. Một công dân đóng góp một khoản nhỏ hôm nay đang đặt niềm tin rằng năm mươi năm sau, hai trăm năm sau, ai đó vẫn có thể lần theo chuỗi liên kết trở lại sổ sách của tháng này và thấy nó y hệt như trước.

Việc gia nhập hệ thống niềm tin này bắt đầu với Seed — một khoản thành viên một lần, định giá bằng một phần bảy giờ lương tối thiểu địa phương, không thể chuyển nhượng và không mang bất kỳ quyền đòi hỏi kinh tế nào. Seed không mua một cổ phần, không mua một lá phiếu được cân theo tài sản, không mua một địa vị đặc quyền trong sổ sách tiếp theo. Nó chỉ mua sự thuộc về, với một mức giá đủ thấp để một người trẻ ở bất cứ đâu hiệp ước hoạt động cũng có thể chi trả để bắt đầu. Mọi thứ một thành viên kiếm được sau thời điểm đó đều được kiếm, không bao giờ được mua, và sự phân biệt này chính là toàn bộ kiến trúc đạo đức của hiệp ước thu nhỏ lại.

Giá trị thực sự chảy đến một con người chảy qua 🏠 Livelihood Direct — những kênh địa phương được cấp phép hợp lệ mang khoản thanh toán đến tay người đó, không bao giờ vào một quỹ mà chính khung khổ nắm giữ hay kiểm soát. Việc phân loại luôn diễn ra trước khi thanh toán trong mọi trường hợp; một chỗ ngủ, một khoản trợ cấp, một vị trí trong giai đoạn đào tạo tiếp theo được xác định bởi vai trò và sự sẵn sàng, không bao giờ chỉ bởi sự công nhận, bởi sự công nhận thì rẻ còn sinh kế thì không. Đây là con đường mà khoản đóng góp hàng tháng của một công dân thực sự đi qua: từ tài khoản của công dân, qua một kênh được kiểm toán, vào khoản trợ cấp mà một người trẻ nhận được, vào dự án đổi mới mà công việc của người trẻ đó trở thành, và quay trở lại như một sổ sách công khai mà bất kỳ công dân nào cũng có thể đọc.

Điều mà công việc đó đáng giá được đo lường, không phải được mặc định. Qualified Innovation Score lấy trung bình sự sẵn sàng, tiềm năng tăng trưởng, tác động kết quả, và sự sẵn sàng thực thi thành một con số duy nhất, và sự tăng trưởng của điểm số đó chỉ định lượng quỹ phần thưởng sau khi đạt điều kiện — bản thân QIS không tạo ra và không thanh toán bất cứ điều gì; đó là phép đo, không bao giờ là thanh toán, và phép đo không bao giờ bị nhầm lẫn ở đây với quyền sở hữu. Thù lao cho lao động con người thay vào đó đến dưới dạng 웃, được định giá bằng một giờ nhân với lương tối thiểu địa phương, nhân với một hệ số đã xác định phạm vi, được duyệt ngân sách của số giờ thực sự làm việc và được chứng kiến. Trước khi một nhiệm vụ mang sự phê duyệt đó, công việc đằng sau nó là lập kế hoạch, không phải lao động có thể trả công, và không ai được trả để lập kế hoạch. Một trần 9.999 웃 mỗi năm, với bất kỳ phần dư nào được chuyển tiếp thay vì biến mất, giữ cho sổ sách của bất kỳ năm đơn lẻ nào không trở thành một khoản trúng thưởng bất ngờ hay một cái bẫy.

Không điều nào trong số này vận hành nhanh hơn bằng chứng của chính nó. Chính hiệp ước tiến từ vận hành Thủ công sang Bán tự động rồi sang Tự động từng khối một, và chỉ khi một mức cải thiện đo lường được đầy đủ — một phần chín — thực sự đã được chứng minh, không bao giờ được giả định trước. Quyền tự chủ được kiếm được chính xác ở đó và không bao giờ gần với ý nghĩa, tiền bạc, hay luật pháp, những thứ luôn thuộc về con người. Chi phí hành chính bị giới hạn. Các khoản quà tặng doanh nghiệp và thể chế được chào đón và bị giới hạn tương tự. Sổ sách đầy đủ được cung cấp bằng ngôn ngữ của mỗi khu vực ký kết mỗi tháng, bắt đầu tại Campuchia, Honduras, và Austin, và có ý định vẫn được cung cấp, và vẫn có thể đọc được, năm trăm năm sau. Đây là niềm tin mà hiệp ước đòi hỏi. Đây là niềm tin mà hiệp ước kiếm được, từng khoản đóng góp nhỏ có thể truy vết một lần, trước mắt mọi công dân mà nó sẽ từng phục vụ.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Giao lưu liên văn hóa và đóng góp toàn cầu`,
    content: {
      7: `Mỗi người học bằng chính ngôn ngữ của mình.`,
      33: `Mọi hoạt động bằng ngôn ngữ của người tham gia — mở cho bất kỳ công dân nào, không cần sự cho phép của chính phủ. Trí tuệ Nhân tạo, Con người, và Chung được giữ trong thế cân bằng hữu ích. Chương trình học được công bố công khai. Điều một khu vực học được, tất cả đều thừa hưởng.`,
      111: `Hiệp ước Atlantis đưa giáo dục trở lại mục đích sâu xa nhất của nó: sự trao đổi trí tuệ qua những ranh giới vốn dĩ có thể chia cắt. Bất kỳ công dân nào cũng có thể gia nhập chương trình học này, bất kể chính phủ của họ đã ký kết điều gì. Mọi hoạt động đều có sẵn bằng ngôn ngữ của người tham gia, ngôn ngữ của khu vực chủ nhà, và một hồ sơ chung. Ngôn ngữ không phải là trang trí — ngôn ngữ là thẩm quyền tài phán, ngôn ngữ là phẩm giá được làm cho dễ đọc. Khung giáo dục dựa trên bộ ba trí tuệ: Nhân tạo đề xuất, Con người quyết định, Ý định Chung xác nhận. Mỗi học viên học cách giữ cả ba trong thế cân bằng. Điều hiệp ước học được, nó trao lại. Chương trình học, kết quả đổi mới, nghiên cứu về sự an lành, và các quyết định quản trị được công bố công khai. Điều một khu vực học được, mọi công dân đều thừa hưởng.`,
      333: `Hiệp ước Atlantis đưa giáo dục trở lại mục đích sâu xa nhất của nó: sự trao đổi trí tuệ qua những ranh giới vốn dĩ có thể chia cắt. Đây là một hiệp ước giữa các công dân trên toàn thế giới — bất kỳ công dân nào cũng có thể xây dựng và gìn giữ nó, bất kể chính phủ của họ đã ký kết điều gì. Mọi hoạt động đều có sẵn bằng ngôn ngữ của người tham gia, ngôn ngữ của khu vực chủ nhà, và một hồ sơ chung, để không người tham gia nào phải điều hướng hiệp ước bằng một ngôn ngữ họ không chọn. Ngôn ngữ không phải là trang trí. Ngôn ngữ là thẩm quyền tài phán. Ngôn ngữ là phẩm giá được làm cho dễ đọc. Một người trẻ ở Campuchia đọc hồ sơ trợ cấp của mình bằng tiếng Khmer, ở Honduras bằng tiếng Tây Ban Nha, ở Austin bằng tiếng Anh — cả ba đều được tôn trọng như nhau, không cần sự chuẩn thuận của chính phủ nào để bắt đầu.

Khung giáo dục dựa trên bộ ba trí tuệ mà Vision • 2525 làm cho hữu hình. Trí tuệ Nhân tạo đề xuất các mô hình và khả năng nhanh hơn bất kỳ con người đơn lẻ nào có thể làm được. Trí tuệ Con người quyết định về an toàn, đạo đức, và định hướng — những câu hỏi mà không máy móc nào nên trả lời, được giữ dưới Human Authority. Ý định Chung xác nhận rằng các quyết định phục vụ những nguyên tắc của hiệp ước, để không người tham gia nào chọn sự xuất sắc cá nhân thay vì lợi ích chung. Không học viên nào phó mặc cho một trí tuệ đơn lẻ; mỗi học viên học cách giữ cả ba trong thế cân bằng. Sự thuộc về bắt đầu với Seed, một khoản thành viên định giá bằng một phần bảy giờ lương tối thiểu địa phương — đủ nhỏ để bất kỳ công dân nào cũng có thể chi trả. Điều này chuẩn bị cho thế hệ kế tiếp để quản trị, nơi không trí tuệ nào hành động mà không bị kiểm soát.

Điều hiệp ước học được, nó trao lại. Chương trình học được công bố dưới giấy phép mở để bất kỳ khu vực nào — dù là bên ký kết hay không — cũng có thể điều chỉnh chúng theo văn hóa địa phương. Kết quả đổi mới được công bố. Nghiên cứu về sự an lành được công bố tổng hợp cho các nhà nghiên cứu ở khắp mọi nơi. Các quyết định quản trị được công bố kèm lý do, để bất kỳ công dân nào, không chỉ một chính phủ ký kết, cũng có thể xác minh chúng — và Replay cho phép chính công dân đó lần lại lý do một thế kỷ sau. Thành công được đo lường không chỉ bởi những người tham gia của nó mà còn bởi những sáng kiến giáo dục và văn hóa nảy sinh trong dấu vết của nó, tại những khu vực chưa từng ký kết dự án thí điểm nhưng đã xây dựng trên trí tuệ chung của nó. Điều một khu vực học được, mọi công dân đều thừa hưởng.`,
      999: `Hiệp ước Atlantis đưa giáo dục trở lại mục đích sâu xa nhất của nó: sự trao đổi trí tuệ qua những ranh giới vốn dĩ có thể chia cắt, và nó bắt đầu sự trao đổi đó trước khi một bài học duy nhất được giảng dạy. Hành động đầu tiên của mỗi người tham gia trong khung khổ là Seed — một khoản thành viên một lần định giá bằng một phần bảy giờ lương tối thiểu địa phương, không thể chuyển nhượng, không mang bất kỳ quyền đòi hỏi kinh tế nào. Nó đủ nhỏ để không gia đình nào bị loại trừ và đủ thực để không người tham gia nào bước vào như một khán giả. Đây là bài học đầu tiên của hiệp ước: sự thuộc về được kiếm rẻ, nhưng vẫn được kiếm, và nó không trao bất kỳ quyền sở hữu nào đối với những gì đến sau. Mọi hoạt động của hiệp ước tiếp theo đều có sẵn bằng ngôn ngữ của người tham gia, bằng ngôn ngữ của khu vực chủ nhà, và trong một hồ sơ chung, để không người tham gia nào phải điều hướng hiệp ước bằng một ngôn ngữ họ không chọn. Ngôn ngữ không phải là trang trí. Ngôn ngữ là thẩm quyền tài phán. Ngôn ngữ là phẩm giá được làm cho dễ đọc. Khi một người trẻ từ một ngôi làng Campuchia đọc hồ sơ trợ cấp của mình bằng tiếng Khmer, một thị trấn Honduras bằng tiếng Tây Ban Nha, và một khu phố Austin bằng tiếng Anh, cả ba đều được cùng một hiệp ước tôn trọng như nhau, trong cùng những khu vực sáng lập đã đồng ý dạy dỗ lẫn nhau đầu tiên.

Khung giáo dục của hiệp ước dựa trên bộ ba trí tuệ mà Vision • 2525 làm cho hữu hình, và chương trình học dạy mỗi trí tuệ như một điều một người tham gia có thể cảm nhận bằng chính đôi tay mình, không phải như một sự trừu tượng. ♡, Ý định Chung, mang theo lý do — sợi chỉ mà mỗi học viên học cách nắm giữ trước khi chạm vào bất kỳ công cụ nào, câu hỏi liệu công việc này có còn phục vụ những người mà nó tuyên bố phục vụ hay không. ◬, sự tăng tốc được chứng kiến, được dạy như một mức chênh lệch và không hơn — chỉ được đo so với một đường cơ sở đã đóng băng, không bao giờ được tô vẽ thành một chỉ số lợi nhuận, không bao giờ được nhận là một thành tựu cá nhân tách rời khỏi nhóm xung quanh. 웃, Trí tuệ Con người được tôn vinh qua thời gian, được dạy cẩn thận nhất: một giờ công việc được chứng kiến bằng một giờ theo lương tối thiểu địa phương, và điều một người tham gia kiếm được là mức lương đó nhân với số giờ làm việc — Hệ số nhân Thời gian, không có gì ẩn giấu trong phép tính. Học viên học sớm rằng 웃 chỉ phát hành cho công việc được chứng kiến, thực hiện trong phạm vi một nhiệm vụ đã được xác định phạm vi, được duyệt ngân sách. Trước khi sự phê duyệt đó tồn tại, cùng nỗ lực ấy chỉ là lập kế hoạch — có giá trị, nhưng không được trả công, và mỗi người tham gia được dạy để nhận ra sự khác biệt ngay lập tức.

Bởi sự khác biệt đó dễ bị mờ nhòe, chương trình học dạy QIS, Qualified Innovation Score, như một tấm gương chứ không phải một bảng điểm. QIS là trung bình của bốn con số tài chính tuyệt đối — Doanh thu, Lợi nhuận gộp, Thu nhập hoạt động, và R&D hiệu quả — chia cho bốn, và mỗi học viên học cách tính nó, đặt câu hỏi về nó, và không bao giờ nhầm lẫn nó với tiền bạc. Tăng trưởng QIS chỉ định lượng quỹ phần thưởng sau khi điều kiện được xác nhận độc lập, và sự tăng trưởng đó không tự tạo ra 웃. QIS là phép đo. QIS không bao giờ là thanh toán. QIS không bao giờ là quyền sở hữu. Một học viên đã thấm nhuần sự phân biệt này không thể bị thuyết phục rằng một điểm số cao mang lại cho họ một quyền đòi hỏi mà hiệp ước chưa từng hứa hẹn.

Chương trình học mở rộng khả năng đọc hiểu này sang cách giá trị thực sự đến tay một con người, qua điều hiệp ước gọi là Livelihood Direct — nguyên tắc 🏠 rằng tiền di chuyển qua những kênh địa phương được cấp phép hợp lệ và không bao giờ qua một quỹ mà chính khung khổ nắm giữ. Học viên được dạy để lần theo khoản trợ cấp của mình, và sau này là thu nhập của chính mình, qua những kênh này như một bài tập công dân, không phải một điều bí ẩn về tài chính được thực hiện ở đâu đó thay mặt họ. Họ học rằng việc phân loại luôn diễn ra trước khi thanh toán, và rằng sự công nhận — một QIS cao, một lời khen công khai — tự nó không phải là điều kiện để có một chỗ ngủ, một khoản trợ cấp, hay một vị trí trong vòng luân chuyển. Vai trò mới là điều kiện đó. Đây là sự bảo vệ trước một thất bại rất cũ: sự khen ngợi bị nhầm lẫn với sự cung cấp.

Song song với khả năng đọc hiểu tài chính là khả năng đọc hiểu công dân, được dạy qua Continuity Without Evasion. Mỗi người tham gia học rằng hiệp ước được xây dựng cho tính khả chuyển hợp pháp — rằng không một chính phủ, ngân hàng, người sáng lập, hay mô hình đơn lẻ nào đứng giữa họ và những lời hứa của khung khổ. Họ học điều một phán quyết bất lợi làm trong thiết kế này: nó đóng một kênh lại, tại một thẩm quyền tài phán, dưới tư thế mặc định từ chối của bộ điều hợp đó, và không bao giờ kéo sập toàn bộ. Đi kèm với điều này là bài học sâu sắc nhất mà hiệp ước dạy: Human Authority giữ ý nghĩa, tiền bạc, và luật pháp, và tầng chủ quyền nơi những quyết định đó được đưa ra vẫn vĩnh viễn đóng cửa với máy móc. Measurement of Time, MoT, ghi lại những phút giây thực sự của mỗi người tham gia tách biệt khỏi bất kỳ điểm số nào, và Replay khiến mọi bản phát hành mà hiệp ước công bố có thể được tái dựng đầy đủ — để một học viên muốn biết tại sao một quyết định đã được đưa ra, nhiều năm sau, có thể tự mình lần lại nó thay vì tin lời bất kỳ ai.

Cấu trúc niềm tin được kiếm được này trở thành mô hình sư phạm của hiệp ước, không chỉ là mô hình quản trị của nó. Mỗi người tham gia tiến qua các chế độ Thủ công, Bán tự động, và Tự động với mức độ tự do ngày càng tăng, được kiểm soát bởi cùng ngưỡng cải thiện đo lường được chi phối chính công nghệ đó — một mức tăng đã xác minh mười một phẩy một phần chín phần trăm trước khi chế độ tiếp theo mở ra. Quyền tự chủ, khi đã được kiếm, được kiếm hẹp và theo từng lĩnh vực, không bao giờ vượt qua ý nghĩa, tiền bạc, hay luật pháp. Một học viên đã trải qua tiến trình này hiểu, một cách sâu sắc, tại sao tầng chủ quyền không bao giờ được tự động hóa mất — bởi họ đã kiếm được quyền tự chủ của chính mình từng bước đo lường một, và biết chính xác quyền tự chủ đó bao gồm và không bao gồm điều gì.

Điều hiệp ước học được, hiệp ước trao lại. Chương trình học được công bố dưới giấy phép mở để bất kỳ khu vực nào — dù là bên ký kết hay không — cũng có thể điều chỉnh chúng theo văn hóa và truyền thống sư phạm địa phương. Kết quả đổi mới được công bố. Nghiên cứu về sự an lành được công bố dưới dạng tổng hợp cho các nhà nghiên cứu ở khắp mọi nơi. Các quyết định quản trị được công bố kèm đầy đủ lý do nguyên vẹn. Thành công của hiệp ước được đo lường không chỉ bởi những người tham gia của chính nó tại Campuchia, Honduras, và Austin, mà còn bởi những sáng kiến nảy sinh trong dấu vết của nó, tại những khu vực chưa từng ký kết dự án thí điểm sáng lập nhưng đã xây dựng trên trí tuệ được chia sẻ công khai của nó, qua một chân trời mà những người sáng lập sẽ không sống để chứng kiến hoàn thành. Điều một khu vực học được, mọi khu vực khác đều thừa hưởng — và điều thế hệ này được dạy một cách trung thực, năm trăm năm tiếp theo sẽ không phải học lại từ đầu.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Tăng trưởng bền vững của mạng lưới`,
    content: {
      7: `Không bao giờ nhanh hơn tốc độ phẩm giá có thể đi.`,
      33: `Ba khu vực sáng lập hoàn thành một chu kỳ thí điểm trước khi khu vực thứ tư gia nhập — bất kỳ công dân nào cũng có thể xây dựng nó. Hồ sơ được neo giữ để trường tồn năm thế kỷ. Các bên ký kết giữ nguyên chủ quyền; không gì bị hạ cấp cho lần gia nhập tiếp theo.`,
      111: `Hiệp ước Atlantis sẽ không phát triển nhanh hơn chất lượng mà nó có thể tôn trọng. Ba khu vực sáng lập phải hoàn thành một chu kỳ thí điểm đầy đủ, với mọi người tham gia được tôn trọng và mọi nguyên tắc được xác minh, trước khi một khu vực thứ tư gia nhập. Đây là nguyên tắc cuối cùng trở thành kỷ luật vận hành. Nhưng hiệp ước là một thỏa thuận giữa các công dân trên toàn thế giới — bất kỳ ai, ở bất cứ đâu, đều có thể xây dựng và gìn giữ nó, chỉ cách một Seed, bất kể một chính phủ ký kết gì hay một người sử dụng lao động cho phép gì. Chân trời của hiệp ước là năm thế kỷ. Hồ sơ của nó được neo giữ qua Replay, để một công dân đọc chúng một thế kỷ sau có thể tin tưởng lý lẽ. Mỗi bên ký kết giữ nguyên chủ quyền; không gì bị hạ cấp cho lần gia nhập tiếp theo.`,
      333: `Hiệp ước Atlantis sẽ không phát triển nhanh hơn chất lượng mà nó có thể tôn trọng. Mỗi lần mở rộng là một lời hứa với những người tham gia đã có mặt bên trong — rằng chuẩn mực sáng lập sẽ không bị pha loãng bởi quy mô. Ba khu vực sáng lập phải hoàn thành một chu kỳ thí điểm đầy đủ, với mọi người tham gia được tôn trọng và mọi nguyên tắc được xác minh, trước khi một khu vực thứ tư gia nhập. Đây là nguyên tắc cuối cùng trở thành kỷ luật vận hành. Và cánh cửa chưa bao giờ chỉ dành riêng cho khu vực: đây là một thỏa thuận giữa các công dân trên toàn thế giới, và bất kỳ ai cũng có thể xây dựng nó, tài trợ nó, và buộc nó chịu trách nhiệm — không cần sự cho phép của chính phủ, không cần sự chuẩn thuận của người sử dụng lao động. Các nhà lãnh đạo ký dự án thí điểm hứa với các bên ký kết cùng một nền tảng, sự bảo vệ, và phẩm giá mà nhóm sáng lập đã nhận được. Không gì bị hạ cấp cho lần tiếp theo.

Chân trời của hiệp ước có chủ đích dài — được thiết kế để trường tồn mười lăm đến hai mươi thế hệ con người, năm thế kỷ kể từ ngày sáng lập. Hồ sơ của nó được neo giữ qua Replay, để một công dân đọc chúng một thế kỷ sau có thể xác minh lý lẽ, chứ không chỉ tin vào nó. Khung tọa độ của nó, các vai trò Human Authority của nó, và các chu kỳ quản trị xuyên thế hệ của nó được xây dựng để sống sót qua bất kỳ sự chuyển đổi công nghệ đơn lẻ nào. Hiệp ước sẽ tồn tại lâu hơn mọi con người ký dự án thí điểm sáng lập của nó, và mọi công dân gieo một Seed và tài trợ nó hàng tháng. Đó là lời hứa của nó với đứa trẻ ký một thỏa thuận trợ cấp, với công dân gia nhập mà không cần bất kỳ sự cho phép nào của chính phủ, với những đứa cháu của đứa trẻ đó có thể quản trị hiệp ước vào giữa thế kỷ, và với mọi thế hệ thừa hưởng những gì những người sáng lập — cả chính thức lẫn công dân — xây dựng bây giờ.

Mỗi bên ký kết giữ quyền tự do rút lui, trọn vẹn chủ quyền, và thẩm quyền đối với công dân của chính mình, cùng quyền sửa đổi và định hình sự phát triển của hiệp ước. Mỗi công dân giữ cùng tư cách để sáng lập, tài trợ, chứng kiến, và buộc nó chịu trách nhiệm — dù có hay không có chữ ký của chính phủ. Điều không ai có thể làm là thỏa hiệp những nguyên tắc sáng lập, bởi lời hứa đó phải sống sót qua bất kỳ sự rời đi nào. Cả lãnh đạo lẫn công dân cùng ký thế kỷ tiếp theo của hiệp ước vào một chân trời mà cháu chắt của họ sẽ thừa hưởng và hoàn thành.`,
      999: `Hiệp ước Atlantis sẽ không phát triển nhanh hơn chất lượng mà nó có thể tôn trọng, và sự tiết chế này không phải là cảm tính — đó là kỹ thuật, được viết vào cùng kỷ luật đo lường chi phối mọi lời hứa mà hiệp ước đưa ra. Ba khu vực sáng lập, Campuchia, Honduras, và Austin, phải hoàn thành một chu kỳ thí điểm đầy đủ, với mọi người tham gia được tôn trọng và mọi nguyên tắc được xác minh, trước khi một khu vực thứ tư gia nhập. Sự tăng trưởng vượt quá khả năng xác minh không phải là tăng trưởng; đó là sự phơi bày khoác lên trang phục của tham vọng. Dự án thí điểm sáng lập tồn tại để hiệp ước có thể chứng minh, ở một quy mô đủ nhỏ để kiểm tra và đủ lớn để có ý nghĩa, rằng những lời hứa của nó sống sót qua sự va chạm với thực tế trước khi những lời hứa đó được mở rộng cho một thế giới đang quan sát từ bên ngoài ba biên giới của nó. Khu vực thứ tư chưa được đặt tên, và sẽ không được đặt tên cho đến khi ba khu vực đầu tiên đứng sau mọi tuyên bố mà văn kiện này đưa ra.

Điều chứng minh sự sẵn sàng để phát triển không phải là nhiệt huyết mà là một con số hiệp ước có thể bảo vệ trước công chúng. Qualified Innovation Score — QIS, được tính bằng Doanh thu cộng Lợi nhuận gộp cộng Thu nhập hoạt động cộng chi tiêu R&D hiệu quả, chia cho bốn — là công cụ mà hiệp ước dùng để biết liệu một khu vực, một nhóm học viên, hay một khối có thực sự tiến bộ, thay vì chỉ cảm thấy như đã tiến bộ. Tăng trưởng QIS chỉ định lượng quỹ phần thưởng sau khi điều kiện được đáp ứng, không bao giờ trước đó, và bản thân QIS không tạo ra 웃 và không mua quyền sở hữu. QIS là phép đo, không phải thanh toán; phép đo, không phải cổ phần; một tấm gương mà hiệp ước soi lại công việc của chính mình, không bao giờ là một loại tiền tệ nó chi tiêu. Một khu vực đề xuất mở rộng mạng lưới phải trình bày QIS của mình một cách trung thực, trước mắt những khu vực đi trước, nếu không nó sẽ không mở rộng.

Tăng trưởng bền vững nghĩa là tăng trưởng tự kiếm được thẩm quyền của chính nó từng bước một. Mỗi khối và mỗi khu vực bắt đầu ở chế độ Thủ công, nơi con người quyết định mọi thứ và hệ thống chỉ hỗ trợ. Việc tiến lên chế độ Bán tự động, và cuối cùng là Tự động, trong một khối nhất định được kiểm soát bởi cùng một ngưỡng xuyên suốt hiệp ước — một sự cải thiện đo lường được mười một phẩy một phần chín phần trăm, một phần chín, được chứng minh và có thể tái tạo trước khi mức độ tự chủ tiếp theo được cấp. Quyền tự chủ được kiếm từng khối một, không bao giờ được nhận trọn gói hay mở rộng qua những lĩnh vực phải luôn thuộc về con người dù hệ thống có tiên tiến đến đâu: ý nghĩa, tiền bạc, và luật pháp vẫn đóng cửa với máy móc bất kể bao nhiêu ngưỡng đã được vượt qua ở những nơi khác. Một mạng lưới mở rộng khả năng tự động hóa của nó nhanh hơn mở rộng bằng chứng của nó không phải là hiện đại hóa. Đó là đánh cược với niềm tin mà nó chưa kiếm được.

Thù lao mở rộng cùng mạng lưới theo cùng cách thẩm quyền mở rộng — có chủ đích, và với một trần bảo vệ toàn bộ hệ thống khỏi chính thành công của nó. 웃, biểu tượng của Trí tuệ Con người, bằng một giờ công việc được chứng kiến nhân với lương tối thiểu địa phương; điều bất kỳ người tham gia nào kiếm được là Hệ số đó nhân với số giờ làm việc, và nó chỉ phát hành cho lao động thực hiện trong phạm vi một nhiệm vụ đã được xác định phạm vi, được duyệt ngân sách. Trước khi được phê duyệt, kế hoạch tinh vi nhất cũng chỉ là lập kế hoạch, và lập kế hoạch đơn thuần không tạo ra bất cứ điều gì. Khoản thanh toán của mỗi người tham gia bị giới hạn ở 9.999 웃 mỗi năm, với bất kỳ phần dư nào được chuyển tiếp thay vì biến mất hay làm méo mó quỹ. Khi các khu vực mới gia nhập và hoạt động của mạng lưới nhân lên, trần này chính là điều giữ cho sự tăng trưởng không trở thành lạm phát — giá trị luôn gắn liền với những giờ địa phương thực sự, được chứng kiến, dù hiệp ước có lớn mạnh đến đâu.

Đằng sau mỗi 웃 là một lý do mà không sổ cái nào có thể tự tính toán. ♡, Ý định Chung, mang lý do đó tiến về phía trước qua mọi quyết định mở rộng mà hiệp ước đưa ra, trong khi ◬, đóng góp của Trí tuệ Nhân tạo, được tính là sự tăng tốc được chứng kiến, đo lường so với một đường cơ sở đã đóng băng — một mức chênh lệch, và không bao giờ, trong bất kỳ hoàn cảnh nào, một chỉ số lợi nhuận được tối ưu hóa vì lợi ích riêng của nó. Việc gia nhập mạng lưới này bắt đầu theo cùng một cách với mọi người tham gia bất kể họ gia nhập vào khu vực nào hay thập kỷ nào: với một Seed, một khoản thành viên một lần định giá bằng một phần bảy giờ lương tối thiểu địa phương, không thể chuyển nhượng và không mang bất kỳ quyền đòi hỏi kinh tế nào. Seed chỉ nói rằng một người đã đến. Mọi thứ họ xây dựng sau đó, họ xây dựng trước mắt ba đồng tiền còn lại của hiệp ước, không bao giờ qua chính Seed.

Tăng trưởng thực sự cũng phải là tăng trưởng chạm đến một con người thực, không phải một quỹ mà khung khổ nắm giữ thay mặt ai đó. 🏠 Livelihood Direct đòi hỏi giá trị chỉ di chuyển đến một người tham gia qua những kênh địa phương được cấp phép hợp lệ mà hiệp ước đã kiểm định từng khu vực một, và không bao giờ qua sự nắm giữ mà chính khung khổ duy trì. Việc phân loại luôn diễn ra trước khi thanh toán, để không giá trị nào di chuyển trước khi mục đích và người nhận của nó đều được xác lập không còn nghi ngờ. Và bởi sự công nhận không giống với sự tiếp cận, một chỗ ngủ, một vị trí trong vòng luân chuyển, một chỗ ngồi tại bàn được xác định bởi vai trò và sự sẵn sàng, không bao giờ bởi điểm số hay địa vị của người tham gia. Khi mạng lưới mở rộng vào một khu vực thứ tư và xa hơn nữa, mỗi lãnh thổ mới phải xác định điều kiện cho những kênh được cấp phép của riêng mình trước khi Livelihood Direct có thể đến được với người dân của họ — mở rộng niềm tin, không chỉ đơn thuần mở rộng lãnh thổ.

Không điều gì trong số này tồn tại được nếu không có một mạng lưới được xây dựng để sống sót qua chính thành công của nó, và đó là lý do Continuity Without Evasion chi phối mọi khu vực mà hiệp ước từng thêm vào. Tính khả chuyển hợp pháp là bắt buộc; không một chính phủ, ngân hàng, người sáng lập, hay mô hình đơn lẻ nào được trở nên không thể thay thế đối với toàn bộ. Mỗi thẩm quyền tài phán vận hành bộ điều hợp riêng của mình, thất bại an toàn và mặc định từ chối, để một phán quyết bất lợi ở bất cứ đâu đóng một kênh, không bao giờ toàn bộ hiệp ước. Human Authority nắm giữ ý nghĩa, tiền bạc, và luật pháp ở mọi quy mô mà mạng lưới vươn tới, được niêm phong chống lại sự xâm lấn của máy móc bằng thiết kế chứ không phải bằng lời hứa. Measurement of Time ghi lại mọi phút giây thực sự tách biệt khỏi mọi tuyên bố về nó, và Replay đảm bảo rằng bất kỳ bản phát hành nào, tại bất kỳ khu vực nào, tại bất kỳ thời điểm nào qua năm thế kỷ, đều có thể được tái dựng và xem xét lại bởi bất kỳ ai hỏi đến. Một mạng lưới không thể được phát lại thì không thể được tin tưởng, dù có bao nhiêu khu vực đã gia nhập nó hay sự tăng trưởng của nó trông ấn tượng đến đâu từ bên ngoài. Đây là cách Vision • 2525 phát triển mà không bao giờ vượt quá niềm tin mà nó được xây dựng để gìn giữ — từng khu vực đã xác minh, từng QIS trung thực, từng giờ được chứng kiến một lần.`,
    },
  },
];
