import type { AccordSection } from "@/lib/atlantis-accord-data";

export const ACCORD_VI: AccordSection[] = [
  {
    id: "pilot",
    page: 1,
    tag: "PILOT",
    title: `Nơi đổi mới bắt đầu`,
    content: {
      7: `Những nhà lãnh đạo khởi đầu điều chưa thế kỷ nào khởi đầu.`,
      33: `Ba khu vực — Campuchia, Honduras, Austin — cam kết đón nhận các bạn trẻ học tập, bảo vệ họ và trao cho họ những công cụ của tương lai. Chính quyền, Giáo dục, Đổi mới: ba chữ ký tầm nhìn cho mỗi khu vực. Một khởi đầu chung.`,
      111: `Hiệp ước Atlantis là lời hứa của những nhà lãnh đạo sẵn sàng khởi đầu điều chưa từng tồn tại trước đây. Các bên ký kết sáng lập tại Campuchia, Honduras và Austin, Texas được chọn vì một phẩm chất hiếm có: sự sẵn lòng tin tưởng trao cho người trẻ những công cụ của tương lai khi vẫn còn thời gian để dạy họ. Ký hiệp ước là cam kết khu vực sẽ đón nhận người học từ mọi nền văn hóa, đóng góp điều mà chỉ riêng nó mới có thể mang lại một cách độc đáo, và tự giữ mình theo một tiêu chuẩn cao hơn những gì quy định hiện hành đòi hỏi. Ba chữ ký tầm nhìn — Chính quyền, Giáo dục, Đổi mới — cùng bước vào hiệp ước. Ba người có tầm nhìn, ba khu vực, một khởi đầu chung.`,
      333: `Mọi nền văn minh được ghi nhớ bởi điều mà nó chọn để khởi đầu. Hiệp ước Atlantis là lời hứa của những nhà lãnh đạo sẵn sàng khởi đầu điều chưa từng tồn tại trước đây — một nền tảng chung cho sự đổi mới bình thường của con người, vươn tới mọi ngóc ngách của thế giới, tôn vinh mọi tiếng nói và trường tồn qua các thế hệ. Các bên ký kết sáng lập tại Campuchia, Honduras và Austin, Texas không được chọn vì sức mạnh kinh tế, sức mạnh quân sự hay uy tín thể chế. Họ được chọn vì một phẩm chất hiếm có hơn: sự sẵn lòng tin tưởng trao cho người trẻ những công cụ của tương lai. Đây chính là ý nghĩa của sự lãnh đạo trong thế kỷ phía trước — lòng can đảm trao lại chìa khóa cho thế hệ kế tiếp khi vẫn còn thời gian để dạy họ cách cầm lái.\n\nHiệp ước được triệu tập bởi eXeL, một lực lượng tổ chức được kiến tạo có chủ đích cho thời khắc này. eXeL tồn tại một cách cố ý bên ngoài các kênh phối hợp truyền thống đã định hình thế kỷ trước — bên ngoài các cấu trúc hiệp ước ngoại giao, bên ngoài các bộ máy quan liêu đa phương, bên ngoài những vướng mắc chính trị của bất kỳ quốc gia dân tộc nào. eXeL là bên triệu tập đáng tin cậy, quy tụ các nhà lãnh đạo có tầm nhìn quanh một khuôn khổ chung, một guồng quay chung và một chân trời chung kéo dài năm trăm năm. Mỗi bên ký kết vẫn giữ trọn chủ quyền, trọn quyền lực đối với công dân của mình và trọn tự do rút lui vào bất kỳ lúc nào. Điều các bên ký kết nhận được là hiệu ứng mạng lưới mà chỉ một khuôn khổ được kiến tạo cho mục đích này mới có thể mang lại. Đây là sự phối hợp mà không có bất kỳ hình thức thống trị chính trị nào.\n\nKý hiệp ước là ký một lời hứa. Rằng khu vực sẽ đón nhận các bạn trẻ học tập từ mọi nền văn hóa. Rằng khu vực sẽ đóng góp điều mà chỉ riêng nó mới có thể mang lại một cách độc đáo. Rằng khu vực sẽ tự giữ mình theo một tiêu chuẩn cao hơn những gì quy định hiện hành đòi hỏi. Rằng khu vực sẽ làm điều đó một cách công khai, minh bạch, trước mắt mọi công dân mà nó phục vụ. Cần ba chữ ký từ mỗi khu vực — Chính quyền, Giáo dục và Đổi mới. Không một cơ quan đơn lẻ nào tự mình ràng buộc hiệp ước. Phải có ba người có tầm nhìn cùng nói vâng. Ba người có tầm nhìn, ba khu vực, một khởi đầu — đây là cách bất kỳ khuôn khổ nào bước vào cuộc sống qua sự tin cậy lẫn nhau của những nhà lãnh đạo sẵn sàng ký nó thành hình.`,
    },
  },
  {
    id: "replay",
    page: 2,
    tag: "REPLAY",
    title: `Học qua mô phỏng`,
    content: {
      7: `Luyện tập ngàn lần trước khi chạm vào.`,
      33: `Không điều hệ trọng nào được học lần đầu trên thiết bị thật. Mỗi người tham gia luyện tập trong mô phỏng, luân chuyển qua ba khu vực, ăn mừng công khai. Đây là sự tôn trọng người trẻ mà sai lầm đầu tiên không bao giờ nên đánh đổi bằng một mạng sống.`,
      111: `Mọi bộ môn đáng để tinh thông đều từng được ai đó học trước khi nó được biết đến. Hiệp ước Atlantis đưa trí tuệ cổ xưa này trở lại trung tâm của cách chuẩn bị cho người trẻ xây dựng tương lai. Không điều hệ trọng nào được học lần đầu trên thiết bị thật, trên con người thật, hay trong những điều kiện không thể đảo ngược. Mỗi người tham gia luyện tập trong mô phỏng cho đến khi luyện tập trở thành năng lực, và năng lực trở thành sự sẵn sàng. Mô hình luân chuyển đưa mỗi người tham gia đi qua ba khu vực sáng lập, và mỗi vòng luân chuyển kết thúc bằng một lễ ăn mừng công khai và hợp tác, mở ra cho cộng đồng chủ nhà rộng lớn hơn. Đây là sự tôn trọng người trẻ mà sai lầm đầu tiên không bao giờ nên đánh đổi bằng một mạng sống.`,
      333: `Mọi bộ môn đáng để tinh thông đều từng được ai đó học trước khi nó được biết đến. Những nghệ nhân bậc thầy tập dượt trước khi trình diễn, phi công tập dượt trước khi bay, thầy thuốc tập dượt trước khi phẫu thuật, và trẻ em tập dượt thế giới qua trò chơi. Hiệp ước Atlantis đưa trí tuệ cổ xưa này trở lại trung tâm của cách chuẩn bị cho người trẻ xây dựng tương lai. Không điều hệ trọng nào được học lần đầu trên thiết bị thật, trên con người thật, hay trong những điều kiện không thể đảo ngược. Mỗi người tham gia luyện tập trong mô phỏng cho đến khi luyện tập trở thành năng lực, và năng lực trở thành sự sẵn sàng. Đây không phải là sự thận trọng — đây là sự tôn trọng người trẻ mà sai lầm đầu tiên không bao giờ nên khiến bất kỳ ai phải trả giá bằng mạng sống.\n\nMô hình luân chuyển của hiệp ước đưa mỗi người tham gia đi qua ba khu vực sáng lập. Điều học được ở Campuchia được tinh chỉnh ở Honduras và hoàn thiện ở Austin. Điều khám phá ở Austin được chất vấn ở Campuchia và tích hợp ở Honduras. Mỗi người tham gia sống, học và được dìu dắt qua những nền văn hóa mà lẽ ra vẫn còn xa cách. Chương trình đào tạo rút ra từ các truyền thống mô phỏng có kỷ luật của nhiều nền văn hóa — từ truyền thống giáo dục chiến lược của Tôn Tử, từ lối luyện tập qua trò chơi của Musashi, từ lý thuyết học tập theo chu kỳ của Ibn Khaldun, từ phép biện chứng tu viện của Nalanda, từ buồng mô phỏng bay dân dụng — được tổng hợp để tôn trọng mọi giai đoạn nhận thức và mọi di sản văn hóa. Không truyền thống đơn lẻ nào chiếm ưu thế.\n\nMỗi vòng luân chuyển kết thúc bằng một lễ ăn mừng công khai và hợp tác, mở ra cho cộng đồng chủ nhà rộng lớn hơn. Hàng xóm, gia đình và những vị khách hiếu kỳ tụ họp để thấy điều mà nhóm học viên đã học được. Những sự kiện này khiến công nghệ tinh vi trở nên dễ tiếp cận và được tôn vinh thay vì đáng sợ. Một xã hội lớn lên với sự thấu hiểu các hệ thống hợp tác qua trò chơi không dễ bị thao túng bởi nỗi sợ hãi về những hệ thống ấy. Đây là sự răn đe qua giáo dục, chứ không phải răn đe qua vũ lực. Lời hứa của hiệp ước với mỗi bậc cha mẹ: con của bạn sẽ luyện tập ngàn lần trong an toàn trước khi chạm vào bất cứ điều gì có thể gây hại cho chúng, và cộng đồng sẽ chứng kiến sự trưởng thành của chúng trên mỗi bước đường. Đây là dáng vẻ của sự tôn trọng người trẻ khi nó được thiết kế ngay trong một khuôn khổ, và đây là điều mà sự lãnh đạo trao cho thế hệ người tham gia kế tiếp trước khi thế hệ ấy phải đòi hỏi nó.`,
    },
  },
  {
    id: "qualify",
    page: 3,
    tag: "QUALIFY",
    title: `An toàn được kiểm chứng trước khi trao gửi niềm tin`,
    content: {
      7: `An toàn chứng minh trước, niềm tin trao sau.`,
      33: `Mỗi cơ sở và mỗi vòng luân chuyển nằm trong một lớp vỏ bảo vệ có cảnh báo sớm. Phần cứng từ chối bị vũ khí hóa. Hồ sơ sống sót qua biến động. An toàn được thiết kế quanh người tham gia nhỏ tuổi nhất mỗi ngày, không chỉ được hứa hẹn hay giả định.`,
      111: `Trước khi niềm tin được trao gửi, an toàn phải được chứng minh. Hiệp ước Atlantis biến điều này thành cam kết nền tảng của mình. Mỗi cơ sở của hiệp ước, mỗi tuyến luân chuyển, mỗi nơi một người tham gia trẻ tuổi ngủ hay học đều nằm trong một lớp vỏ bảo vệ được ghi chép, với năng lực cảnh báo sớm cho cộng đồng hàng giờ, chứ không phải hàng phút, để ứng phó với bất kỳ rủi ro đáng tin nào. Mỗi thiết bị, mỗi cảm biến, mỗi hệ thống phối hợp đều bị ràng buộc ở tầng phần cứng để từ chối bị tái sử dụng cho tích hợp hệ thống vũ khí. Đây không phải là chính sách — đây là vật lý. Hiệp ước được thiết kế để giữ danh dự qua biến động: bất ổn chính trị, thu hẹp tài trợ, tấn công mạng, hay gián đoạn di chuyển. Mỗi kịch bản đều được dự liệu, và mỗi kế hoạch đặt phẩm giá con người làm ràng buộc thiết kế đầu tiên.`,
      333: `Trước khi niềm tin được trao gửi, an toàn phải được chứng minh. Hiệp ước Atlantis biến điều này thành cam kết nền tảng của mình. Mỗi cơ sở của hiệp ước, mỗi tuyến luân chuyển, mỗi nơi một người tham gia trẻ tuổi ngủ hay học đều nằm trong một lớp vỏ bảo vệ được ghi chép, với năng lực cảnh báo sớm cho cộng đồng hàng giờ, chứ không phải hàng phút, để ứng phó với bất kỳ rủi ro đáng tin nào. Công nghệ dùng để bảo vệ người tham gia chính là công nghệ mà hiệp ước dạy họ xây dựng — cảm biến, phối hợp, khả năng sống sót của liên lạc, trí tuệ phân tán. Người trẻ học về an toàn từ trong ra ngoài, bằng chính ngôn ngữ của mình và tại chính khu vực của mình, không phải bằng việc được bảo rằng họ an toàn, mà bằng việc nhìn thấy an toàn được thiết kế quanh họ mỗi ngày.\n\nHiệp ước đưa ra một lời hứa không thể phá vỡ về điều mà công nghệ của nó không được phép trở thành. Mỗi thiết bị, mỗi cảm biến, mỗi hệ thống phối hợp đều bị ràng buộc ở tầng phần cứng để từ chối bị tái sử dụng cho tích hợp hệ thống vũ khí. Đây không phải là ngôn từ chính sách. Đây không phải là khát vọng. Đây là một điều bất khả về mặt vật lý, được thực thi bằng mật mã, được xác minh bởi mỗi khu vực ký kết và có thể được kiểm tra bởi mỗi công dân. Những công cụ bảo vệ một đứa trẻ ở Phnom Penh không thể bị tái sử dụng để làm hại một đứa trẻ ở Austin. Những công cụ kết nối một bài tập bầy đàn ở Tegucigalpa không thể bị cấu hình lại để nhắm vào một con người ở bất cứ đâu. Đây là câu trả lời của hiệp ước cho một thế kỷ sợ hãi về lưỡng dụng. Không phải chính sách — vật lý.\n\nHiệp ước được thiết kế để giữ danh dự qua biến động. Nếu một khu vực ký kết mất ổn định chính trị, người tham gia được các khu vực còn lại tiếp nhận. Nếu tài trợ thu hẹp, trợ cấp cho người tham gia được bảo vệ trước tiên, trước cả quản trị và hạ tầng. Nếu hồ sơ số bị tấn công, các bản sao lưu ngoại tuyến vẫn tồn tại. Nếu di chuyển trở nên bất khả, nền tảng vẫn tiếp tục theo cách ảo. Mỗi kịch bản đều được dự liệu, và mỗi kế hoạch đặt phẩm giá con người làm ràng buộc thiết kế đầu tiên. Những nhà lãnh đạo ký hiệp ước này đang ký một lời hứa rằng an toàn được thiết kế, chứ không phải được giả định. Điều họ trao cho công dân của mình không chỉ là cơ hội, mà là sự bảo vệ được dựng xây theo tiêu chuẩn mà người tham gia nhỏ tuổi nhất xứng đáng nhận — chính sự bảo vệ mà bất kỳ nhà lãnh đạo nào cũng sẽ đòi hỏi cho con của mình khi một mình vượt qua một biên giới xa lạ.`,
    },
  },
  {
    id: "certify",
    page: 4,
    tag: "CERTIFY",
    title: `Đãi ngộ, an sinh và phẩm giá con người`,
    content: {
      7: `Một khoản trợ cấp, một người dìu dắt, một mái nhà.`,
      33: `Mỗi người tham gia nhận một khoản trợ cấp sinh hoạt từ ngày đầu tiên. Yêu thương, mất mát và an toàn được coi là hạ tầng bậc nhất. Thành công được đo bằng người tham gia dễ tổn thương nhất, không bao giờ bằng mức trung bình. Phẩm giá là nền tảng, không bao giờ là trang trí.`,
      111: `Hiệp ước Atlantis coi mỗi người tham gia là một con người trọn vẹn ngay từ ngày đầu. Một khoản trợ cấp được trao từ khoảnh khắc bắt đầu tham gia, được điều chỉnh theo chi phí sinh hoạt của khu vực để tác động của nó tôn trọng phẩm giá địa phương của lao động. An sinh được coi là hạ tầng bậc nhất — không phải phúc lợi tùy chọn, không phải đặc quyền, mà là nền tảng nâng đỡ mọi thứ khác. Ba lĩnh vực nền tảng được nâng đỡ: Yêu thương, Mất mát và An toàn. Hiệp ước đo thành công bằng kết quả của người tham gia dễ tổn thương nhất, không phải mức trung bình. Không người tham gia nào bị lặng lẽ lãng quên để các con số trung bình trông đẹp. Phẩm giá là nền tảng, không phải trang trí.`,
      333: `Hiệp ước Atlantis coi mỗi người tham gia là một con người trọn vẹn ngay từ ngày đầu. Một khoản trợ cấp được trao từ khoảnh khắc bắt đầu tham gia, được điều chỉnh theo chi phí sinh hoạt của khu vực để tác động của nó tôn trọng phẩm giá địa phương của lao động. Khoản trợ cấp đến trước khi những nghĩa vụ gia đình trở thành khẩn cấp, và trước khi phẩm giá bị tổn hại. Nó báo hiệu với mỗi người trẻ rằng thời gian của họ là quý giá, rằng đóng góp của họ được mong đợi, và rằng sự ổn định của gia đình họ là một phần trách nhiệm của hiệp ước. Đây không phải là từ thiện. Đây là sự thừa nhận rằng đổi mới bình thường của con người trước hết cần đến an toàn bình thường của con người. Một tâm trí không thể nở hoa khi mái nhà của nó đang bị đe dọa.\n\nAn sinh được coi là hạ tầng bậc nhất — không phải phúc lợi tùy chọn, không phải đặc quyền, mà là nền tảng nâng đỡ mọi thứ khác. Hiệp ước gọi tên ba lĩnh vực nền tảng mà mỗi người tham gia được nâng đỡ qua đó: Yêu thương, theo nghĩa kết nối, gắn bó và ranh giới lành mạnh; Mất mát, bởi mỗi người tham gia sẽ trải qua đau buồn và cần được đồng hành cùng, chứ không phải đi vòng qua; và An toàn, theo nghĩa mỗi người tham gia biết gọi ai, ở mỗi khu vực, bằng chính ngôn ngữ của mình. Tư vấn cá nhân, các vòng tròn nhóm, thực hành thân thể, và thực hành văn hóa hay tâm linh được tôn trọng theo truyền thống riêng của người tham gia đều được cung cấp. Không hề có hệ tư tưởng áp đặt. Hiệp ước giữ không gian bằng sự tôn kính; nó không cải đạo bất kỳ hệ thống niềm tin nào.\n\nHiệp ước đo thành công bằng kết quả của người tham gia dễ tổn thương nhất, không phải mức trung bình. Những người tham gia ở nông thôn không có băng thông cao vẫn được phục vụ. Những người tham gia có khác biệt thần kinh nhận được sự thích ứng như một chuẩn mực. Những người tham gia khuyết tật thấy mọi cơ sở đều tiếp cận được. Những người tham gia đa dạng giới nhận được nơi ở an toàn và ghép cặp người dìu dắt. Những người nói ngôn ngữ không phải tiếng mẹ đẻ thấy mọi tài liệu bằng ngôn ngữ của mình. Những người tham gia bản địa thấy thực hành văn hóa của mình được tôn trọng và tri thức truyền thống của mình được bảo vệ. Những nhà lãnh đạo ký hiệp ước này đang hứa rằng không người tham gia nào bị lặng lẽ lãng quên để các con số trung bình trông đẹp. Đây là phẩm giá như nền tảng, không phải như trang trí. Điều được đo lường là điều sẽ được tôn vinh, và điều được tôn vinh ở đây là con người trọn vẹn — tâm trí, thân thể và tinh thần cùng nhau, không hề có bất kỳ ngoại lệ nào.`,
    },
  },
  {
    id: "adopt",
    page: 5,
    tag: "ADOPT",
    title: `Tài trợ và quản trị`,
    content: {
      7: `Công dân trực tiếp tài trợ thế hệ kế tiếp.`,
      33: `Những cư dân bình thường đóng góp những khoản nhỏ hằng tháng. Không kênh viện trợ, không nhà hảo tâm nước ngoài, không ràng buộc chính trị. Mỗi đồng đô la đều truy vết được. Mọi hạch toán đều được công bố, bằng ngôn ngữ của mỗi khu vực, mỗi tháng, công khai.`,
      111: `Hiệp ước Atlantis được tài trợ bởi chính những công dân mà nó phục vụ. Những cư dân bình thường đóng góp những khoản tự nguyện nhỏ mỗi tháng — đủ khiêm tốn để không người trưởng thành nào bị loại ra, đủ vang vọng để tổng số nuôi dưỡng công việc của hiệp ước ở quy mô có ý nghĩa. Khi một công dân trực tiếp tài trợ thế hệ kế tiếp, công dân ấy trực tiếp buộc hiệp ước chịu trách nhiệm. Hiệp ước độc lập một cách có chủ đích với các thể chế đa phương đã định hình thế kỷ vừa qua. Đây không phải là một tuyên bố chính trị — đó là một lựa chọn thiết kế. Mỗi đồng đô la được ghi lại vĩnh viễn và có thể truy vết. Mỗi đóng góp của công dân có thể được lần theo từ nguồn gốc đến khoản trợ cấp đến sự đổi mới. Một sự minh bạch hiếm khi được bất kỳ thể chế nào mang lại.`,
      333: `Hiệp ước Atlantis được tài trợ bởi chính những công dân mà nó phục vụ. Những cư dân bình thường của các khu vực tham gia đóng góp những khoản tự nguyện nhỏ mỗi tháng — những khoản đủ khiêm tốn để không người trưởng thành nào ở bất kỳ khu vực chủ nhà nào bị loại khỏi sự tham gia, đủ vang vọng để tổng số nuôi dưỡng công việc của hiệp ước ở quy mô có ý nghĩa. Thiết kế này là có chủ đích. Khi một công dân trực tiếp tài trợ cho việc giáo dục thế hệ kế tiếp, công dân ấy trực tiếp buộc hiệp ước chịu trách nhiệm. Không có kênh viện trợ, không có nhà hảo tâm nước ngoài, không có ràng buộc chính trị gắn vào tấm séc. Linh hồn của hiệp ước là người công dân đóng góp một khoản nhỏ mỗi tháng, mà sự tham gia của họ làm cho cái toàn thể trở nên khả thi.\n\nHiệp ước độc lập một cách có chủ đích với các thể chế đa phương đã định hình thế kỷ vừa qua — Tổ chức Hiệp ước Bắc Đại Tây Dương, Tổ chức Y tế Thế giới, Liên Hợp Quốc, Quỹ Tiền tệ Quốc tế, Ngân hàng Thế giới, và mọi kênh viện trợ nước ngoài của các quốc gia. Đây không phải là một tuyên bố chính trị về giá trị của những thể chế đó hay những đóng góp của chúng. Đó là một lựa chọn thiết kế. Những phụ thuộc vào một điểm duy nhất làm tổn hại độ bền vững qua một chân trời năm trăm năm. Một khuôn khổ nhằm phục vụ mọi khu vực bất kể liên minh địa chính trị không thể bị vướng vào bất kỳ liên minh nào. Các chính phủ quốc gia có thể đóng góp một cách tự nguyện. Các đóng góp đều minh bạch. Không đóng góp nào mua được ảnh hưởng quản trị, từ bất kỳ nguồn nào, không bao giờ.\n\nMỗi đồng đô la và mỗi đơn vị giá trị đi vào hiệp ước đều được ghi lại vĩnh viễn, công khai và có thể truy vết. Mỗi đóng góp của công dân có thể được lần theo từ nguồn gốc của nó đến khoản trợ cấp mà nó trở thành, đến người trẻ mà nó phục vụ, đến dự án đổi mới nảy sinh từ công việc của người trẻ ấy. Chi phí hành chính bị giới hạn. Những món quà từ doanh nghiệp và thể chế được hoan nghênh và bị giới hạn. Bản hạch toán đầy đủ được cung cấp bằng ngôn ngữ của mỗi khu vực ký kết mỗi tháng. Những nhà lãnh đạo ký hiệp ước đang hứa với công dân của mình một sự minh bạch hiếm khi được bất kỳ thể chế nào mang lại — sự minh bạch vẫn còn đọc được trong nhiều thế kỷ sau khi mỗi bên ký kết đã rời nhiệm sở. Đây là niềm tin mà hiệp ước đòi hỏi. Đây là niềm tin mà hiệp ước giành được, mỗi lần một đóng góp nhỏ có thể truy vết, trước mắt mỗi công dân.`,
    },
  },
  {
    id: "educate",
    page: 6,
    tag: "EDUCATE",
    title: `Giao lưu liên văn hóa và đóng góp toàn cầu`,
    content: {
      7: `Mỗi người học bằng chính ngôn ngữ của mình.`,
      33: `Mỗi hoạt động đều có sẵn bằng ngôn ngữ của người tham gia. Trí tuệ Nhân tạo, Con người và Chung được giữ trong sự căng thẳng hữu ích — không học viên nào nhượng bộ chỉ một trí tuệ. Chương trình và kết quả được công bố công khai. Điều một khu vực học được, tất cả cùng thừa hưởng.`,
      111: `Hiệp ước Atlantis đưa giáo dục trở về mục đích sâu xa nhất của nó: sự trao đổi trí tuệ qua những ranh giới lẽ ra sẽ chia rẽ. Mỗi hoạt động đều có sẵn bằng chính ngôn ngữ của người tham gia, bằng ngôn ngữ của khu vực chủ nhà, và trong một bản ghi chung chuẩn mực. Ngôn ngữ không phải là trang trí — ngôn ngữ là quyền tài phán, ngôn ngữ là phẩm giá được làm cho đọc được. Khuôn khổ giáo dục dựa trên bộ ba trí tuệ: Nhân tạo đề xuất, Con người quyết định, Ý định Chung xác thực. Mỗi học viên học cách giữ cả ba trong sự căng thẳng hữu ích. Điều hiệp ước học được, hiệp ước trao lại. Chương trình, kết quả đổi mới, nghiên cứu an sinh và các quyết định quản trị đều được công bố công khai. Điều một khu vực học được, mọi khu vực đều thừa hưởng.`,
      333: `Hiệp ước Atlantis đưa giáo dục trở về mục đích sâu xa nhất của nó: sự trao đổi trí tuệ qua những ranh giới lẽ ra sẽ chia rẽ. Mỗi hoạt động của hiệp ước đều có sẵn bằng chính ngôn ngữ của người tham gia, bằng ngôn ngữ chính thức của khu vực chủ nhà, và trong một bản ghi chung chuẩn mực, để không người tham gia nào phải điều hướng hiệp ước bằng một thứ tiếng mà họ không lựa chọn. Ngôn ngữ không phải là trang trí. Ngôn ngữ là quyền tài phán. Ngôn ngữ là phẩm giá được làm cho đọc được. Khi một người trẻ từ một ngôi làng Campuchia đọc bản ghi trợ cấp của chính mình bằng tiếng Khmer, khi một người trẻ từ một thị trấn Honduras đọc nó bằng tiếng Tây Ban Nha, khi một người trẻ từ một khu phố Austin đọc nó bằng tiếng Anh, cả ba đều được cùng một hiệp ước tôn vinh ngang nhau.\n\nKhuôn khổ giáo dục của hiệp ước dựa trên bộ ba trí tuệ mà Vision 2525 làm cho hiển hiện. Trí tuệ Nhân tạo đề xuất các khuôn mẫu, lựa chọn và khả năng nhanh hơn bất kỳ con người đơn lẻ nào có thể. Trí tuệ Con người quyết định về an toàn, đạo đức và phương hướng — những câu hỏi mà không cỗ máy nào nên trả lời. Ý định Chung xác thực rằng các quyết định phù hợp với những nguyên tắc nền tảng của hiệp ước, bảo đảm không người tham gia nào bị buộc phải lựa chọn giữa xuất sắc cá nhân và lợi ích tập thể. Không học viên nào được dạy phải nhượng bộ chỉ một trí tuệ. Mỗi học viên học cách giữ cả ba trong sự căng thẳng hữu ích. Đây là cách thế hệ lãnh đạo kế tiếp được chuẩn bị để quản trị một cách có trách nhiệm và khôn ngoan trong một thế giới nơi không một trong ba trí tuệ này sẽ hành động một mình hay không được kiểm soát.\n\nĐiều hiệp ước học được, hiệp ước trao lại. Các chương trình được công bố theo giấy phép mở để bất kỳ khu vực nào — dù ký kết hay không — đều có thể tự do điều chỉnh chúng cho phù hợp với văn hóa địa phương và truyền thống sư phạm. Các kết quả đổi mới được công bố. Nghiên cứu an sinh được công bố dưới dạng tổng hợp cho các nhà nghiên cứu ở khắp nơi. Các quyết định quản trị được công bố cùng với lập luận đầy đủ. Thành công của hiệp ước được đo không chỉ bằng chính những người tham gia của nó mà còn bằng số lượng sáng kiến giáo dục, đổi mới và văn hóa nảy sinh theo sau nó, ở những khu vực chưa bao giờ ký chương trình thí điểm sáng lập nhưng đã xây dựng trên trí tuệ được chia sẻ công khai của nó. Điều một khu vực học được, mọi khu vực khác đều thừa hưởng.`,
    },
  },
  {
    id: "expand",
    page: 7,
    tag: "EXPAND",
    title: `Tăng trưởng bền vững của mạng lưới`,
    content: {
      7: `Không bao giờ nhanh hơn tốc độ phẩm giá có thể đi.`,
      33: `Ba khu vực sáng lập hoàn thành một chu kỳ thí điểm trước khi có khu vực thứ tư gia nhập. Hồ sơ được neo giữ để trường tồn năm thế kỷ. Mỗi bên ký kết giữ trọn chủ quyền. Không gì bị hạ thấp để nhường chỗ cho bên ký kết kế tiếp gia nhập.`,
      111: `Hiệp ước Atlantis sẽ không tăng trưởng nhanh hơn chất lượng mà nó có thể tôn vinh. Ba khu vực sáng lập phải hoàn thành một chu kỳ thí điểm trọn vẹn, với mỗi người tham gia được tôn vinh và mỗi nguyên tắc được xác minh, trước khi có khu vực thứ tư gia nhập. Đây là nguyên tắc cuối cùng trở thành kỷ luật vận hành. Chân trời của hiệp ước dài một cách có chủ đích — năm thế kỷ kể từ ngày sáng lập. Hồ sơ của nó được neo giữ để một công dân đọc chúng một trăm năm sau vẫn có thể tin vào lập luận. Mỗi bên ký kết giữ trọn chủ quyền, trọn quyền lực và trọn tự do rút lui. Không bên ký kết nào có thể làm tổn hại những nguyên tắc nền tảng — bởi những nguyên tắc ấy là lời hứa của hiệp ước với người tham gia của nó qua mọi thế hệ.`,
      333: `Hiệp ước Atlantis sẽ không tăng trưởng nhanh hơn chất lượng mà nó có thể tôn vinh. Mỗi lần mở rộng là một lời hứa với những người tham gia đã ở bên trong — rằng tiêu chuẩn sáng lập của hiệp ước sẽ không bị pha loãng bởi sự hào hứng của quy mô. Ba khu vực sáng lập phải hoàn thành một chu kỳ thí điểm trọn vẹn, với mỗi người tham gia được tôn vinh và mỗi nguyên tắc được xác minh, trước khi có khu vực thứ tư gia nhập. Đây không phải là sự thận trọng khoác áo nguyên tắc. Đây là nguyên tắc cuối cùng trở thành kỷ luật vận hành trên khắp mỗi khu vực sáng lập. Những nhà lãnh đạo ký chương trình thí điểm sáng lập đang hứa với các bên ký kết tương lai cùng một nền tảng, cùng một sự bảo vệ, cùng một phẩm giá mà nhóm sáng lập đã nhận được. Không gì bị hạ thấp để nhường chỗ cho bên kế tiếp.\n\nChân trời của hiệp ước dài một cách có chủ đích. Nó được thiết kế để trường tồn khoảng mười lăm đến hai mươi thế hệ con người — năm thế kỷ kể từ ngày sáng lập. Hồ sơ của nó được neo giữ để một công dân đọc chúng một trăm năm sau vẫn có thể tin vào lập luận. Khung tọa độ của nó, các vai trò thẩm quyền con người của nó, và các chu kỳ quản trị liên thế hệ của nó đều được xây dựng để sống sót qua bất kỳ chuyển đổi công nghệ đơn lẻ nào. Hiệp ước sẽ sống lâu hơn mọi con người ký chương trình thí điểm sáng lập của nó. Đó là lời hứa của nó với đứa trẻ ký một thỏa thuận trợ cấp trong năm tiếp sau khi phê chuẩn, với các cháu của đứa trẻ ấy có thể quản trị hiệp ước vào giữa thế kỷ, và với mỗi thế hệ thừa hưởng những gì mà các nhà sáng lập xây dựng bây giờ.\n\nMỗi bên ký kết giữ trọn tự do rút lui có báo trước. Mỗi bên ký kết giữ trọn chủ quyền. Mỗi bên ký kết giữ quyền lực đối với công dân của chính mình. Mỗi bên ký kết giữ quyền đề xuất sửa đổi, nêu tranh chấp, và định hình sự tiến hóa của hiệp ước cùng với mọi bên ký kết khác. Điều mà không bên ký kết nào có thể làm là làm tổn hại những nguyên tắc nền tảng của nền tảng — bởi những nguyên tắc ấy là lời hứa của hiệp ước với người tham gia của nó, và lời hứa ấy phải sống sót qua sự ra đi của bất kỳ chữ ký đơn lẻ nào. Những nhà lãnh đạo ký hiệp ước này bây giờ đang gia nhập điều gì đó lớn hơn bất kỳ nhiệm kỳ chính trị nào. Họ đang ký thế kỷ kế tiếp của hiệp ước, và những thế kỷ xa hơn nữa, vào một chân trời mà chính các cháu của họ sẽ thừa hưởng và hoàn thành.`,
    },
  },
];
