// manta-render.mjs — render the Manta-2525 review-gate tracker, assumptions register and
// risk matrix FROM docs/manta-2525/manta-trinity.v1.7.1.json. One source, three views —
// never hand-copy a status or a number into a markdown file (the registers lesson).
//
// Run: node scripts/manta-render.mjs            (writes the three .md files)
//      node scripts/manta-render.mjs --check    (exit 1 if any rendered file is stale)
import fs from 'fs';

const SRC = 'docs/manta-2525/manta-trinity.v1.7.1.json';
const M = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const CHECK = process.argv.includes('--check');

const WARN = `> **This output is for conceptual critique only.** It is not a design baseline, safety case,
> certification approval, procurement authority, construction authorization, operational doctrine,
> hurricane-safety advice, or human-test plan. All safety-critical domains remain 🔴 Red until validated
> by qualified human experts.
>
> *Generated by \`scripts/manta-render.mjs\` from \`manta-trinity.v1.7.1.json\` — edit the JSON, never this file.*\n`;

const light = (s) => (/^Red/.test(s) ? '🔴 ' + s : /^Yellow/.test(s) ? '🟡 ' + s : /^Green/.test(s) ? '🟢 ' + s : s);
const pname = (id) => {
  const ids = String(id).split('|');
  return ids.map((i) => (M.platforms.find((p) => p.id === i) || { name: i }).name).join(' / ');
};

/* ── REVIEW_GATES.md ─────────────────────────────────────────────────────── */
const gates = [
  `# Manta-2525 — Review-Gate Tracker (v${M.project.version})\n`, WARN,
  `**Decision rule.** ${M.decision_rule}\n`,
  `**Project status.** ` + Object.entries(M.project.status).map(([k, v]) => `${k.replace('_', ' ')}: ${light(v)}`).join(' · ') + '\n',
  `## First gate — ${M.first_gate.name}\n`,
  `| | |\n|---|---|\n| Platform | ${pname(M.first_gate.platform)} |\n| Validator | ${M.first_gate.required_validator} |\n| Required output | ${M.first_gate.required_output} |\n| Status | ${light(M.first_gate.status)} |\n| Why first | ${M.first_gate.why_first} |\n`,
  `## The eight review lanes\n`,
  `| # | Review lane | Reviewer type | Required output | Status |\n|---|---|---|---|---|`,
  ...M.gates.map((g, i) => `| ${i + 1} | ${g.lane} | ${g.reviewer} | ${g.required_output} | ${light(g.status)} |`),
  ``,
  `**${M.gates.filter((g) => g.status === 'Green').length} of ${M.gates.length} lanes Green.** ` +
  (M.gates.every((g) => g.status !== 'Green') ? 'No lane has been validated. Build, procurement and human testing remain closed on every platform.' : ''),
  ``,
  `## Ladder\n`, M.project.ladder.join(' → ') + '\n',
  `## Doctrine\n`, `*${M.project.doctrine}*\n`,
].join('\n');

/* ── ASSUMPTIONS_REGISTER.md ─────────────────────────────────────────────── */
const asm = [
  `# Manta-2525 — Assumptions Register (v${M.project.version})\n`, WARN,
  `Every assumption carries its validator, the evidence that would move it, and the failure modes it hides.\n`,
  `| ID | Assumption | Platform(s) | Status | Validator | Evidence required | Failure modes |\n|---|---|---|---|---|---|---|`,
  ...M.assumptions.map((a) => `| ${a.id} | ${a.assumption} | ${pname(a.platform)} | ${light(a.status)} | ${a.validator} | ${a.evidence_required} | ${a.failure_modes.join('; ')} |`),
  ``,
  `**Counts.** ${M.assumptions.filter((a) => /^Red/.test(a.status)).length} Red · ${M.assumptions.filter((a) => /^Yellow/.test(a.status)).length} Yellow (arithmetic only) · 0 Green.\n`,
].join('\n');

/* ── RISK_MATRIX.md — sorted by severity, then likelihood, then validator ────── */
const SEV = { Catastrophic: 0, Critical: 1, Major: 2, Moderate: 3, Minor: 4 };
const LIK = { Certain: 0, High: 1, Medium: 2, Low: 3 };
const risks = [...M.risks].sort((a, b) => (SEV[a.severity] - SEV[b.severity]) || (LIK[a.likelihood_if_unvalidated] - LIK[b.likelihood_if_unvalidated]) || a.validator.localeCompare(b.validator));
const byValidator = {};
for (const r of risks) (byValidator[r.validator] ||= []).push(r.id);
const risk = [
  `# Manta-2525 — Risk Matrix (v${M.project.version})\n`, WARN,
  `Sorted by severity (Catastrophic → Minor), then likelihood **if left unvalidated**, then validator. Likelihood is the risk of the *claim* being wrong, not an operational probability — nothing here has been built.\n`,
  `| # | Risk | Platform(s) | Severity | Likelihood if unvalidated | Validator | Assumptions |\n|---|---|---|---|---|---|---|`,
  ...risks.map((r) => `| ${r.id} | ${r.risk} | ${pname(r.platforms)} | **${r.severity}** | ${r.likelihood_if_unvalidated} | ${r.validator} | ${r.assumptions.join(', ') || '—'} |`),
  ``,
  `## By validator — who must be in the room\n`,
  `| Validator | Risks |\n|---|---|`,
  ...Object.entries(byValidator).map(([v, ids]) => `| ${v} | ${ids.join(', ')} |`),
  ``,
  `## Reading it\n`,
  `- ${risks.filter((r) => r.severity === 'Catastrophic').length} catastrophic risks; every one waits on a **class society, battery expert or rescue planner** — none can be retired by analysis alone.`,
  `- The two risks marked *Certain* (${risks.filter((r) => r.likelihood_if_unvalidated === 'Certain').map((r) => r.id).join(', ')}) are documentation risks and are the only ones this repository can retire itself — see CRITIQUE_v${M.project.version}.md.`,
  ``,
].join('\n');

const out = { 'docs/manta-2525/REVIEW_GATES.md': gates, 'docs/manta-2525/ASSUMPTIONS_REGISTER.md': asm, 'docs/manta-2525/RISK_MATRIX.md': risk };
let stale = 0;
for (const [p, body] of Object.entries(out)) {
  if (CHECK) {
    const cur = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
    if (cur !== body) { stale++; console.error(`STALE  ${p} — re-run node scripts/manta-render.mjs`); } else console.log(`ok     ${p}`);
  } else { fs.writeFileSync(p, body); console.log(`wrote  ${p}`); }
}
if (CHECK && stale) process.exit(1);
