// Reusable chrome strings for the sealed 1x-read reader (engine, not content).
// Rides INSIDE each language block of the encrypted payload so the standalone HTML
// can switch its whole UI when the in-reader language selector changes. Post-unlock
// strings only. {n} in sealedSection is replaced by the clearance level at runtime.
// 33 languages: en + 32 from the Master of Thought translation workflow (2026-07-05).

export interface ReaderUI {
  title: string;
  clearance: string;
  words: string;
  closeSeal: string;
  touchSeal: string;
  sealedSection: string;
  doneClosed: string;
  doneFresh: string;
  burn: string;
  steps: string[];
}

export const READER_UI_EN: ReaderUI = {
  "title": "The Atlantis Accords",
  "clearance": "Clearance: Level",
  "words": "words",
  "closeSeal": "Close & Seal",
  "touchSeal": "Touch the seal to open",
  "sealedSection": "Sealed at Clearance: Level {n}. A higher clearance is required to open this section.",
  "doneClosed": "This copy has been closed and cannot be reopened",
  "doneFresh": "Request a fresh copy from the sender.",
  "burn": "Burn this file",
  "steps": [
    "PILOT",
    "REPLAY",
    "QUALIFY",
    "CERTIFY",
    "ADOPT",
    "EDUCATE",
    "EXPAND"
  ]
};

export const READER_UI: Record<string, ReaderUI> = {
  en: READER_UI_EN,
  ar: {"title":"مواثيق أتلانتس","clearance":"مستوى التصريح","words":"كلمة","closeSeal":"إغلاق وختم","touchSeal":"المس الختم لفتحه","sealedSection":"مختوم عند مستوى التصريح {n}. يلزم تصريح أعلى لفتح هذا القسم.","doneClosed":"أُغلقت هذه النسخة ولا يمكن إعادة فتحها","doneFresh":"اطلب نسخة جديدة من المُرسِل.","burn":"أتلف هذا الملف","steps":["تجربة","إعادة","تأهيل","اعتماد","تبنّي","تثقيف","توسّع"]},
  da: {"title":"Atlantis-Overenskomsterne","clearance":"Klarering: Niveau","words":"ord","closeSeal":"Luk og forsegl","touchSeal":"Rør ved seglet for at åbne","sealedSection":"Forseglet på Klarering: Niveau {n}. En højere klarering kræves for at åbne dette afsnit.","doneClosed":"Denne kopi er blevet lukket og kan ikke åbnes igen","doneFresh":"Anmod om en ny kopi fra afsenderen.","burn":"Brænd denne fil","steps":["PILOT","GENAFSPIL","KVALIFICÉR","CERTIFICÉR","INDFØR","OPLYS","UDVID"]},
  de: {"title":"Die Verträge von Atlantis","clearance":"Freigabe: Stufe","words":"Wörter","closeSeal":"Schließen & Versiegeln","touchSeal":"Zum Öffnen das Siegel berühren","sealedSection":"Versiegelt mit Freigabe: Stufe {n}. Zum Öffnen dieses Abschnitts ist eine höhere Freigabe erforderlich.","doneClosed":"Dieses Exemplar wurde geschlossen und kann nicht erneut geöffnet werden","doneFresh":"Fordern Sie ein neues Exemplar beim Absender an.","burn":"Diese Datei verbrennen","steps":["Pilot","Wiederholung","Qualifizieren","Zertifizieren","Übernehmen","Schulen","Erweitern"]},
  el: {"title":"Οι Συμφωνίες της Ατλαντίδας","clearance":"Διαβάθμιση: Επίπεδο","words":"λέξεις","closeSeal":"Κλείσιμο & Σφράγιση","touchSeal":"Αγγίξτε τη σφραγίδα για να ανοίξετε","sealedSection":"Σφραγισμένο σε Διαβάθμιση: Επίπεδο {n}. Απαιτείται υψηλότερη διαβάθμιση για το άνοιγμα αυτής της ενότητας.","doneClosed":"Αυτό το αντίγραφο έχει κλείσει και δεν μπορεί να ανοίξει ξανά","doneFresh":"Ζητήστε νέο αντίγραφο από τον αποστολέα.","burn":"Καταστρέψτε αυτό το αρχείο","steps":["ΠΙΛΟΤΙΚΟ","ΕΠΑΝΑΛΗΨΗ","ΑΞΙΟΛΟΓΗΣΗ","ΠΙΣΤΟΠΟΙΗΣΗ","ΥΙΟΘΕΤΗΣΗ","ΕΚΠΑΙΔΕΥΣΗ","ΕΠΕΚΤΑΣΗ"]},
  es: {"title":"Los Acuerdos de Atlantis","clearance":"Autorización: Nivel","words":"palabras","closeSeal":"Cerrar y sellar","touchSeal":"Toque el sello para abrir","sealedSection":"Sellado con Autorización: Nivel {n}. Se requiere una autorización superior para abrir esta sección.","doneClosed":"Esta copia ha sido cerrada y no puede volver a abrirse","doneFresh":"Solicite una nueva copia al remitente.","burn":"Destruir este archivo","steps":["PROBAR","REPETIR","CALIFICAR","CERTIFICAR","ADOPTAR","EDUCAR","EXPANDIR"]},
  fr: {"title":"Les Accords d'Atlantis","clearance":"Habilitation : Niveau","words":"mots","closeSeal":"Fermer et sceller","touchSeal":"Touchez le sceau pour ouvrir","sealedSection":"Scellé à l'habilitation : Niveau {n}. Une habilitation supérieure est requise pour ouvrir cette section.","doneClosed":"Cette copie a été fermée et ne peut être rouverte","doneFresh":"Demandez une nouvelle copie à l'expéditeur.","burn":"Détruire ce fichier","steps":["PILOTE","REJOUER","QUALIFIER","CERTIFIER","ADOPTER","FORMER","ÉTENDRE"]},
  hi: {"title":"अटलांटिस संधि-पत्र","clearance":"अनुमति स्तर:","words":"शब्द","closeSeal":"बंद करें और मुद्रांकित करें","touchSeal":"खोलने के लिए मुद्रा को स्पर्श करें","sealedSection":"अनुमति स्तर: {n} पर मुद्रांकित। इस खंड को खोलने के लिए उच्चतर अनुमति स्तर आवश्यक है।","doneClosed":"यह प्रति बंद कर दी गई है और पुनः नहीं खोली जा सकती","doneFresh":"प्रेषक से एक नई प्रति का अनुरोध करें।","burn":"इस दस्तावेज़ को भस्म करें","steps":["प्रायोगिक","पुनरावृत्ति","योग्यता","प्रमाणन","अंगीकरण","शिक्षण","विस्तार"]},
  id: {"title":"Pakta Atlantis","clearance":"Izin Akses: Tingkat","words":"kata","closeSeal":"Tutup & Segel","touchSeal":"Sentuh segel untuk membuka","sealedSection":"Tersegel pada Izin Akses: Tingkat {n}. Diperlukan izin akses yang lebih tinggi untuk membuka bagian ini.","doneClosed":"Salinan ini telah ditutup dan tidak dapat dibuka kembali","doneFresh":"Mintalah salinan baru dari pengirim.","burn":"Musnahkan berkas ini","steps":["UJI COBA","ULANG","SELEKSI","SERTIFIKASI","ADOPSI","EDUKASI","PERLUAS"]},
  it: {"title":"Gli Accordi di Atlantis","clearance":"Autorizzazione: Livello","words":"parole","closeSeal":"Chiudi e Sigilla","touchSeal":"Tocca il sigillo per aprire","sealedSection":"Sigillato al livello di autorizzazione {n}. È necessaria un'autorizzazione superiore per aprire questa sezione.","doneClosed":"Questa copia è stata chiusa e non può essere riaperta","doneFresh":"Richiedi una nuova copia al mittente.","burn":"Distruggi questo file","steps":["PILOTA","REPLICA","QUALIFICA","CERTIFICA","ADOTTA","FORMA","ESPANDI"]},
  ja: {"title":"アトランティス協定","clearance":"機密区分：レベル","words":"語","closeSeal":"閉じて封印する","touchSeal":"封印に触れて開く","sealedSection":"機密区分：レベル {n} にて封印されています。このセクションを開くには、より高い機密区分が必要です。","doneClosed":"この写しは閉じられ、再び開くことはできません","doneFresh":"送信者に新しい写しをご請求ください。","burn":"このファイルを焼却する","steps":["試行","再現","適格","認証","採用","教育","拡大"]},
  ko: {"title":"아틀란티스 협정","clearance":"기밀 등급: 레벨","words":"단어","closeSeal":"닫고 봉인","touchSeal":"봉인을 눌러 여십시오","sealedSection":"기밀 등급 레벨 {n}(으)로 봉인됨. 이 부분을 열려면 더 높은 기밀 등급이 필요합니다.","doneClosed":"이 사본은 닫혔으며 다시 열 수 없습니다","doneFresh":"발신자에게 새 사본을 요청하십시오.","burn":"이 파일 소각","steps":["시범","재현","검증","인증","채택","교육","확장"]},
  ms: {"title":"Perjanjian Atlantis","clearance":"Kebenaran: Tahap","words":"patah perkataan","closeSeal":"Tutup & Meteraikan","touchSeal":"Sentuh meterai untuk membuka","sealedSection":"Dimeteraikan pada Kebenaran: Tahap {n}. Kebenaran yang lebih tinggi diperlukan untuk membuka bahagian ini.","doneClosed":"Salinan ini telah ditutup dan tidak boleh dibuka semula","doneFresh":"Mohon salinan baharu daripada pengirim.","burn":"Bakar fail ini","steps":["RINTIS","ULANG TAYANG","LAYAK","SAHKAN","GUNA PAKAI","DIDIK","PERLUAS"]},
  nl: {"title":"De Atlantis-Akkoorden","clearance":"Autorisatie: Niveau","words":"woorden","closeSeal":"Sluiten & Verzegelen","touchSeal":"Raak het zegel aan om te openen","sealedSection":"Verzegeld op Autorisatie: Niveau {n}. Een hogere autorisatie is vereist om deze sectie te openen.","doneClosed":"Dit exemplaar is gesloten en kan niet opnieuw worden geopend","doneFresh":"Vraag een nieuw exemplaar aan bij de afzender.","burn":"Vernietig dit bestand","steps":["PROEF","HERHALEN","TOETSEN","CERTIFICEREN","AANNEMEN","OPLEIDEN","UITBREIDEN"]},
  pl: {"title":"Traktaty Atlantydzkie","clearance":"Poziom dostępu","words":"słów","closeSeal":"Zamknij i zapieczętuj","touchSeal":"Dotknij pieczęci, aby otworzyć","sealedSection":"Zapieczętowane na poziomie dostępu: {n}. Do otwarcia tej sekcji wymagany jest wyższy poziom dostępu.","doneClosed":"Ten egzemplarz został zamknięty i nie może zostać ponownie otwarty","doneFresh":"Poproś nadawcę o nowy egzemplarz.","burn":"Spal ten dokument","steps":["PILOTAŻ","POWTÓRKA","KWALIFIKACJA","CERTYFIKACJA","ADOPCJA","EDUKACJA","EKSPANSJA"]},
  pt: {"title":"Os Acordos de Atlantis","clearance":"Autorização: Nível","words":"palavras","closeSeal":"Fechar e Selar","touchSeal":"Toque no selo para abrir","sealedSection":"Selado com Autorização: Nível {n}. É necessária uma autorização superior para abrir esta secção.","doneClosed":"Esta cópia foi fechada e não pode ser reaberta","doneFresh":"Solicite uma nova cópia ao remetente.","burn":"Destruir este ficheiro","steps":["PILOTO","REPETIR","QUALIFICAR","CERTIFICAR","ADOTAR","EDUCAR","EXPANDIR"]},
  ru: {"title":"Соглашения Атлантиды","clearance":"Допуск: уровень","words":"слов","closeSeal":"Закрыть и запечатать","touchSeal":"Коснитесь печати, чтобы открыть","sealedSection":"Запечатано на уровне допуска {n}. Для открытия этого раздела требуется более высокий уровень допуска.","doneClosed":"Эта копия закрыта и не может быть открыта повторно","doneFresh":"Запросите новую копию у отправителя.","burn":"Сжечь этот файл","steps":["Пилот","Повтор","Отбор","Сертификация","Внедрение","Обучение","Расширение"]},
  sv: {"title":"Atlantisfördragen","clearance":"Behörighet: Nivå","words":"ord","closeSeal":"Stäng och försegla","touchSeal":"Rör vid sigillet för att öppna","sealedSection":"Förseglad vid Behörighet: Nivå {n}. En högre behörighet krävs för att öppna detta avsnitt.","doneClosed":"Detta exemplar har stängts och kan inte öppnas igen","doneFresh":"Begär ett nytt exemplar från avsändaren.","burn":"Bränn denna fil","steps":["Pilot","Repris","Kvalificera","Certifiera","Anta","Utbilda","Utöka"]},
  th: {"title":"สนธิสัญญาแอตแลนติส","clearance":"ระดับการเข้าถึง: ชั้น","words":"คำ","closeSeal":"ปิดและผนึก","touchSeal":"แตะที่ตราผนึกเพื่อเปิด","sealedSection":"ผนึกไว้ที่ระดับการเข้าถึง: ชั้น {n} ต้องมีระดับการเข้าถึงที่สูงกว่าจึงจะเปิดส่วนนี้ได้","doneClosed":"สำเนาฉบับนี้ถูกปิดผนึกแล้วและไม่สามารถเปิดซ้ำได้","doneFresh":"โปรดขอสำเนาฉบับใหม่จากผู้ส่ง","burn":"ทำลายไฟล์นี้","steps":["นำร่อง","ทวนซ้ำ","รับรอง","ออกใบรับรอง","นำไปใช้","ให้ความรู้","ขยายผล"]},
  uk: {"title":"Атлантичні угоди","clearance":"Рівень допуску:","words":"слів","closeSeal":"Закрити й запечатати","touchSeal":"Торкніться печатки, щоб відкрити","sealedSection":"Запечатано на рівні допуску: {n}. Для відкриття цього розділу потрібен вищий рівень допуску.","doneClosed":"Цю копію було закрито, і її неможливо відкрити повторно","doneFresh":"Запросіть нову копію у відправника.","burn":"Спалити цей файл","steps":["Пілот","Повтор","Кваліфікація","Сертифікація","Впровадження","Навчання","Розширення"]},
  zh: {"title":"亚特兰蒂斯协定","clearance":"权限等级：","words":"字","closeSeal":"关闭并封缄","touchSeal":"轻触封印以开启","sealedSection":"本节封缄于权限等级 {n}。需具备更高权限方可开启此部分。","doneClosed":"此副本已封闭，无法再次开启","doneFresh":"请向发送者索取新的副本。","burn":"焚毁此文件","steps":["试点","复演","甄选","认证","采纳","教育","拓展"]},
  bn: {"title":"আটলান্টিস সন্ধি","clearance":"ছাড়পত্র: স্তর","words":"শব্দ","closeSeal":"বন্ধ করুন ও সিলমোহর দিন","touchSeal":"খুলতে সিলমোহর স্পর্শ করুন","sealedSection":"ছাড়পত্র: স্তর {n}-এ মুদ্রাঙ্কিত। এই অংশটি খুলতে উচ্চতর ছাড়পত্র প্রয়োজন।","doneClosed":"এই অনুলিপিটি বন্ধ করা হয়েছে এবং পুনরায় খোলা যাবে না","doneFresh":"প্রেরকের কাছ থেকে একটি নতুন অনুলিপির অনুরোধ করুন।","burn":"এই ফাইলটি পুড়িয়ে ফেলুন","steps":["সূচনা","পুনরাবৃত্তি","যোগ্যতা","প্রত্যয়ন","গ্রহণ","শিক্ষা","সম্প্রসারণ"]},
  pa: {"title":"ਐਟਲਾਂਟਿਸ ਸੰਧੀਆਂ","clearance":"ਪ੍ਰਵਾਨਗੀ: ਪੱਧਰ","words":"ਸ਼ਬਦ","closeSeal":"ਬੰਦ ਕਰੋ ਤੇ ਮੋਹਰ ਲਾਓ","touchSeal":"ਖੋਲ੍ਹਣ ਲਈ ਮੋਹਰ ਨੂੰ ਛੂਹੋ","sealedSection":"ਪ੍ਰਵਾਨਗੀ: ਪੱਧਰ {n} ਉੱਤੇ ਮੋਹਰਬੰਦ। ਇਹ ਭਾਗ ਖੋਲ੍ਹਣ ਲਈ ਉੱਚੀ ਪ੍ਰਵਾਨਗੀ ਲੋੜੀਂਦੀ ਹੈ।","doneClosed":"ਇਹ ਨਕਲ ਬੰਦ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ ਅਤੇ ਦੁਬਾਰਾ ਨਹੀਂ ਖੋਲ੍ਹੀ ਜਾ ਸਕਦੀ","doneFresh":"ਭੇਜਣ ਵਾਲੇ ਤੋਂ ਨਵੀਂ ਨਕਲ ਦੀ ਮੰਗ ਕਰੋ।","burn":"ਇਸ ਫ਼ਾਈਲ ਨੂੰ ਸਾੜ ਦਿਓ","steps":["ਪਾਇਲਟ","ਦੁਹਰਾਓ","ਯੋਗਤਾ","ਪ੍ਰਮਾਣਨ","ਅਪਣਾਓ","ਸਿੱਖਿਆ","ਵਿਸਤਾਰ"]},
  vi: {"title":"Hiệp Ước Atlantis","clearance":"Cấp Phép: Bậc","words":"từ","closeSeal":"Đóng & Niêm Phong","touchSeal":"Chạm vào con dấu để mở","sealedSection":"Được niêm phong ở Cấp Phép: Bậc {n}. Cần cấp phép cao hơn để mở phần này.","doneClosed":"Bản sao này đã được đóng và không thể mở lại","doneFresh":"Hãy yêu cầu một bản sao mới từ người gửi.","burn":"Thiêu hủy tập tin này","steps":["Thử Nghiệm","Tái Hiện","Thẩm Định","Chứng Nhận","Áp Dụng","Đào Tạo","Mở Rộng"]},
  tl: {"title":"Ang mga Kasunduang Atlantis","clearance":"Kaltas: Antas","words":"salita","closeSeal":"Isara at Selyuhan","touchSeal":"Hipuin ang selyo upang buksan","sealedSection":"Nakaselyo sa Kaltas: Antas {n}. Kinakailangan ang mas mataas na kaltas upang buksan ang bahaging ito.","doneClosed":"Ang kopyang ito ay naisara na at hindi na maaaring muling buksan","doneFresh":"Humiling ng bagong kopya mula sa nagpadala.","burn":"Sunugin ang talaang ito","steps":["PILOTO","ULITIN","PROBAHAN","PATUNAYAN","TANGGAPIN","TURUAN","PALAWAKIN"]},
  tr: {"title":"Atlantis Antlaşmaları","clearance":"Yetki Düzeyi:","words":"kelime","closeSeal":"Kapat ve Mühürle","touchSeal":"Açmak için mühre dokunun","sealedSection":"Yetki Düzeyi {n} ile mühürlendi. Bu bölümü açmak için daha yüksek bir yetki gereklidir.","doneClosed":"Bu nüsha kapatılmıştır ve yeniden açılamaz","doneFresh":"Göndericiden yeni bir nüsha talep edin.","burn":"Bu dosyayı yak","steps":["Pilot","Yeniden Oynat","Yeterlilik","Sertifika","Benimseme","Eğitim","Genişleme"]},
  ro: {"title":"Acordurile Atlantis","clearance":"Nivel de acces:","words":"cuvinte","closeSeal":"Închide și sigilează","touchSeal":"Atinge sigiliul pentru a deschide","sealedSection":"Sigilat la nivelul de acces {n}. Este necesar un nivel de acces superior pentru a deschide această secțiune.","doneClosed":"Această copie a fost închisă și nu poate fi redeschisă","doneFresh":"Solicitați o copie nouă de la expeditor.","burn":"Arde acest fișier","steps":["Pilot","Reluare","Calificare","Certificare","Adoptare","Educare","Extindere"]},
  cs: {"title":"Atlantské dohody","clearance":"Prověrka: úroveň","words":"slov","closeSeal":"Uzavřít a zapečetit","touchSeal":"Dotkněte se pečeti pro otevření","sealedSection":"Zapečetěno na úrovni prověrky {n}. K otevření této části je vyžadována vyšší prověrka.","doneClosed":"Tato kopie byla uzavřena a nelze ji znovu otevřít","doneFresh":"Vyžádejte si novou kopii od odesílatele.","burn":"Spálit tento soubor","steps":["PILOT","PŘEHRÁNÍ","KVALIFIKACE","CERTIFIKACE","PŘIJETÍ","VZDĚLÁVÁNÍ","ROZŠÍŘENÍ"]},
  fi: {"title":"Atlantiksen sopimukset","clearance":"Turvaluokitus: taso","words":"sanaa","closeSeal":"Sulje ja sinetöi","touchSeal":"Avaa koskettamalla sinettiä","sealedSection":"Sinetöity turvaluokituksella: taso {n}. Tämän osion avaaminen edellyttää korkeampaa turvaluokitusta.","doneClosed":"Tämä kappale on suljettu, eikä sitä voi avata uudelleen","doneFresh":"Pyydä lähettäjältä uusi kappale.","burn":"Polta tämä tiedosto","steps":["PILOTOI","TOISTA","KELPUUTA","SERTIFIOI","OMAKSU","KOULUTA","LAAJENNA"]},
  no: {"title":"Atlantis-avtalene","clearance":"Klarering: Nivå","words":"ord","closeSeal":"Lukk og forsegl","touchSeal":"Berør seglet for å åpne","sealedSection":"Forseglet på Klarering: Nivå {n}. En høyere klarering kreves for å åpne denne delen.","doneClosed":"Denne kopien er lukket og kan ikke åpnes på nytt","doneFresh":"Be om en ny kopi fra avsenderen.","burn":"Brenn denne filen","steps":["PILOTERE","REPRISE","KVALIFISERE","SERTIFISERE","INNFØRE","OPPLÆRE","UTVIDE"]},
  he: {"title":"אמנות אטלנטיס","clearance":"סיווג: רמה","words":"מילים","closeSeal":"סגור וחתום","touchSeal":"גע בחותם כדי לפתוח","sealedSection":"חתום בסיווג: רמה {n}. נדרש סיווג גבוה יותר כדי לפתוח חלק זה.","doneClosed":"עותק זה נסגר ולא ניתן לפותחו מחדש","doneFresh":"בקש עותק חדש מהשולח.","burn":"שרוף קובץ זה","steps":["פיילוט","שחזור","כשירות","הסמכה","אימוץ","הדרכה","הרחבה"]},
  sw: {"title":"Mikataba ya Atlantis","clearance":"Kibali: Ngazi","words":"maneno","closeSeal":"Funga na Kutia Muhuri","touchSeal":"Gusa muhuri ili kufungua","sealedSection":"Imetiwa muhuri kwa Kibali: Ngazi {n}. Kibali cha juu zaidi kinahitajika ili kufungua sehemu hii.","doneClosed":"Nakala hii imefungwa na haiwezi kufunguliwa tena","doneFresh":"Omba nakala mpya kutoka kwa mtumaji.","burn":"Choma faili hili","steps":["Jaribio","Rudia","Stahili","Thibitisha","Kubali","Elimisha","Panua"]},
  ne: {"title":"एटलान्टिस सन्धिहरू","clearance":"अनुमति स्तर:","words":"शब्द","closeSeal":"बन्द गर्नुहोस् र मुद्रा लगाउनुहोस्","touchSeal":"खोल्न मुद्रामा छुनुहोस्","sealedSection":"अनुमति स्तर {n} मा मुद्रित। यो खण्ड खोल्न उच्च अनुमति आवश्यक छ।","doneClosed":"यो प्रति बन्द गरिएको छ र पुनः खोल्न सकिँदैन","doneFresh":"प्रेषकबाट नयाँ प्रति अनुरोध गर्नुहोस्।","burn":"यो फाइल भस्म गर्नुहोस्","steps":["परीक्षण","पुनरावृत्ति","योग्यता","प्रमाणन","अङ्गीकार","शिक्षा","विस्तार"]},
};

export function getReaderUI(lang: string): ReaderUI {
  return READER_UI[lang] ?? READER_UI_EN;
}
