/**
 * CELESTIAL-2525 · learning content — 12 bodies × 4 reading levels, each authored by an Ascended Master.
 * =================================================================================================
 * Family/education reader for /main/Celestial-2525 (nieces & nephews learn the solar system). Four
 * reading levels per body (Atlantis-Accord tier model): 33 (kids) · 111 (middle) · 333 (high school,
 * 3 paragraphs) · 999 (collegiate/adult, 3 sections). Bundled-static + deterministic (no runtime fetch).
 * Vision 2525 · "Humanity decides. Technology assists. Wisdom guides." Facts are canonical (NASA fact
 * sheets); v1 adult tier is a solid 3-section overview and grows toward the full 999-word treatment.
 */

export type ReadingLevel = "kids" | "middle" | "high" | "adult";
export const READING_LEVELS: { id: ReadingLevel; label: string; fill: string; stroke: string }[] = [
  { id: "kids", label: "Elementary", fill: "#ef4444", stroke: "#ef4444" },      // red
  { id: "middle", label: "Middle School", fill: "#22c55e", stroke: "#22c55e" },  // green
  { id: "high", label: "High School", fill: "#3b82f6", stroke: "#3b82f6" },      // blue
  { id: "adult", label: "College Level", fill: "#c084fc", stroke: "#c084fc" },   // violet
];

export interface CelestialEntry {
  id: string; name: string; emoji: string; master: string; group: string;
  text: Record<ReadingLevel, string>;
}

// Three progressive-reveal circles (operator: "3 circles that expand to all planets; 9 or 12 is final,
// okay to use Moon, Sun, and Polaris to reach 9 or 12").
export const CELESTIAL_GROUPS: { id: string; label: string; stroke: string }[] = [
  { id: "sun-rocky", label: "Sun & Rocky Worlds", stroke: "#ffd400" },
  { id: "giants", label: "The Giants", stroke: "#19c8cf" },
  { id: "far", label: "Far Reaches & Stars", stroke: "#c084fc" },
];

export const CELESTIAL_BODIES: CelestialEntry[] = [
  {
    id: "sun", name: "The Sun", emoji: "☀️", master: "Asar", group: "sun-rocky",
    text: {
      kids: "The Sun is a giant ball of glowing gas, so huge that about a million Earths could fit inside it! Its warm light zooms across space and takes eight minutes to reach us.",
      middle: "The Sun is our nearest star, a giant glowing ball of hydrogen and helium gas about 1,391,000 km wide — roughly 109 times the width of Earth. It holds about 99.86% of all the mass in the solar system, and its gravity keeps every planet in orbit. Deep in its core, hydrogen fuses into helium at around 15 million °C, releasing the light and heat that make life on Earth possible. That light takes about 8 minutes and 20 seconds to reach us. The Sun is roughly 4.6 billion years old and about halfway through its life as a stable, hydrogen-burning star.",
      high: "The Sun is a G-type main-sequence star (a yellow dwarf) at the heart of the solar system, about 1.39 million km in diameter and 333,000 times the mass of Earth. It is a plasma sphere of about 73% hydrogen and 25% helium by mass, with the rest heavier elements forged by earlier stars.\n\nEnergy is generated in the core by nuclear fusion — the proton-proton chain converting hydrogen into helium at ~15 million K. That energy takes tens of thousands of years to migrate outward through the radiative and convective zones before escaping the visible surface (the photosphere, ~5,500 °C). Above it lie the chromosphere and the corona, which paradoxically reaches millions of degrees.\n\nThe Sun rotates faster at its equator (~25 days) than its poles (~35 days). Its tangled magnetic field drives an 11-year cycle of sunspots, flares, and coronal mass ejections — space weather that can disturb satellites and power grids. In roughly 5 billion years it will swell into a red giant, then shed its layers to become a slowly cooling white dwarf.",
      adult: "PHYSICAL & FORMATION — The Sun is a G2V main-sequence star, ~1.391 million km across (109 Earths) and ~1.989×10^30 kg (99.86% of the solar system's mass). It condensed ~4.6 billion years ago from a collapsing molecular cloud; conservation of angular momentum flattened the remaining material into the protoplanetary disk that became the planets. It is ~73% hydrogen / ~25% helium by mass, the balance heavier elements inherited from earlier stellar generations.\n\n---\n\nINTERIOR & ENERGY — In the core (~15 million K, ~150× the density of water) the proton-proton chain fuses ~600 million tonnes of hydrogen into helium each second, converting ~4 million tonnes of mass into energy (E=mc²). Photons random-walk outward through the radiative zone for tens of millennia, then convection carries energy to the photosphere (~5,772 K), which radiates the sunlight we see. The tenuous corona above reaches millions of kelvin — heated by magnetic processes still being studied — and streams outward as the solar wind.\n\n---\n\nACTIVITY & SIGNIFICANCE — Differential rotation winds the Sun's magnetic field into an ~11-year cycle of sunspots, flares, and coronal mass ejections that drive space weather across the solar system. Nearly all life on Earth ultimately runs on sunlight via photosynthesis. Across cultures the Sun has been worshiped as a life-giver — Ra, Helios, Surya. In ~5 billion years, with core hydrogen spent, it will expand into a red giant, likely engulfing the inner planets, then eject a planetary nebula and settle into a white dwarf.",
    },
  },
  {
    id: "mercury", name: "Mercury", emoji: "☿", master: "Enki", group: "sun-rocky",
    text: {
      kids: "Mercury is the tiniest planet and races closest to the Sun, zipping all the way around it in just 88 days. One side bakes hot enough to melt lead while the other freezes in shadow!",
      middle: "Mercury is the smallest planet, only about 4,879 km across — a bit more than a third the width of Earth. It orbits closest to the Sun (about 58 million km) and races around it in just 88 Earth-days, the fastest planet of all. But it spins very slowly, so one Mercury day-night cycle lasts about 176 Earth-days. With almost no atmosphere to trap heat, temperatures swing wildly: up to about 430 °C in sunlight and down to about −180 °C at night. Its grey, cratered surface looks a lot like our Moon, and it even hides pockets of ice in deep polar craters the sunlight never reaches.",
      high: "Mercury is the innermost and smallest planet (4,879 km diameter), a dense, rocky world with an oversized iron core making up about 60% of its mass — which is why it is the second-densest planet after Earth.\n\nIt orbits the Sun every 88 days on the most eccentric planetary orbit, ranging from 46 to 70 million km. Its rotation is locked in a 3:2 spin-orbit resonance: it turns exactly three times for every two orbits, so a single solar day (sunrise to sunrise) lasts about 176 Earth-days. With only a whisper of an exosphere, it cannot retain heat, giving the largest surface temperature range of any planet — roughly −180 °C to +430 °C.\n\nMercury's surface is heavily cratered like the Moon, marked by the vast Caloris impact basin and by long cliffs (rupes) that formed as the planet's core cooled and the whole world shrank. Permanently shadowed polar craters hold water ice. It has a weak global magnetic field, studied by Mariner 10, MESSENGER, and now the BepiColombo mission.",
      adult: "PHYSICAL & INTERIOR — Mercury is the smallest planet (2,440 km radius) and, after Earth, the densest, thanks to an iron-rich core spanning ~85% of its radius and ~60% of its mass. Its thin silicate mantle and crust suggest a violent history — perhaps a giant impact stripped much of the original rock, or intense early solar heating vaporized it.\n\n---\n\nORBIT & ROTATION — Mercury has the most eccentric orbit (e≈0.206), swinging from 46 to 70 million km from the Sun over its 88-day year. Tidal forces locked it into a 3:2 spin-orbit resonance — three rotations per two orbits — producing a solar day of ~176 Earth-days. General relativity is beautifully confirmed by the anomalous precession of its perihelion (~43 arcseconds/century). Its exosphere is so thin that day/night temperatures span ~610 °C.\n\n---\n\nSURFACE, FIELD & EXPLORATION — The surface is ancient and cratered, dominated by the 1,550-km Caloris basin and crossed by lobate scarps recording global contraction as the core cooled. A weak dipole magnetic field (~1% of Earth's) implies a partially molten core. Water ice survives in permanently shadowed polar craters. Mariner 10 (1974-75) and MESSENGER (2011-15) mapped it; ESA/JAXA's BepiColombo, arriving mid-2020s, will probe its interior and field in unprecedented detail.",
    },
  },
  {
    id: "venus", name: "Venus", emoji: "♀", master: "Aset", group: "sun-rocky",
    text: {
      kids: "Venus is the hottest planet, wrapped in thick yellow clouds that trap heat like a blanket. It spins backwards, so on Venus the Sun rises in the west and sets in the east!",
      middle: "Venus is the second planet from the Sun and almost exactly Earth's twin in size — about 12,104 km across. But it is the hottest planet in the solar system, around 465 °C, hot enough to melt lead. A thick atmosphere of carbon dioxide with clouds of sulfuric acid traps heat in a runaway greenhouse effect, and the surface pressure is about 90 times Earth's. Venus spins backwards (retrograde) and so slowly that a single day lasts longer than its year: 243 Earth-days to spin once, but only 225 to orbit the Sun. From Earth it shines as the brilliant 'morning star' or 'evening star,' the brightest natural object in our sky after the Sun and Moon.",
      high: "Venus is Earth's near-twin in size and mass (12,104 km diameter, 0.82 Earth masses) but a hostile world beneath a dense atmosphere 96.5% carbon dioxide, cloaked in clouds of sulfuric acid.\n\nThat atmosphere drives the strongest greenhouse effect in the solar system: surface temperatures average ~465 °C — hotter than Mercury despite being farther from the Sun — and the surface pressure is ~92 bar, like being 900 m underwater. Venus rotates retrograde (east to west) and extraordinarily slowly, taking 243 Earth-days per rotation, longer than its 225-day orbit, while its upper clouds super-rotate around the planet in just four days.\n\nRadar (Venus's clouds hide the surface from visible light) has revealed volcanic plains, highland 'continents' like Ishtar Terra and Aphrodite Terra, and few impact craters — signs of a young, volcanically resurfaced world. Missions from the Soviet Venera landers (which survived minutes on the surface) to Magellan's radar maps studied it; new missions (DAVINCI, VERITAS, EnVision) are planned for the 2030s.",
      adult: "PHYSICAL & ATMOSPHERE — Venus is 0.95 Earth radii and 0.815 Earth masses, a rocky planet with a similar bulk composition to Earth but a radically different surface environment. Its atmosphere is 96.5% CO₂ with a mass ~90× Earth's, producing 92 bar of surface pressure and, via a runaway greenhouse, a near-uniform ~737 K surface temperature. High-altitude clouds of sulfuric acid reflect ~75% of sunlight, making Venus brilliant but opaque.\n\n---\n\nROTATION & DYNAMICS — Venus rotates retrograde with a 243-day sidereal period — the slowest of any planet — likely the result of atmospheric tides and past collisions. Its solar day is ~117 Earth-days. Curiously, the thick atmosphere super-rotates ~60× faster than the surface. Venus has no intrinsic magnetic field; instead the solar wind induces one in its ionosphere and slowly strips its atmosphere.\n\n---\n\nSURFACE & EXPLORATION — Radar mapping (Magellan, 1990-94) shows ~80% volcanic plains, two elevated 'continents,' vast lava channels, and only ~1,000 impact craters — implying a global resurfacing ~300-600 Myr ago. Whether volcanism continues today is a live question. Soviet Venera probes returned the only surface images (1975-82) before failing in the heat. Venus, once perhaps ocean-bearing, is a cautionary tale of climate — and the target of DAVINCI, VERITAS, and EnVision this coming decade.",
    },
  },
  {
    id: "earth", name: "Earth", emoji: "🌍", master: "Christo", group: "sun-rocky",
    text: {
      kids: "Earth is our home — the only place we know with oceans, air, and living things! It spins once a day and circles the Sun once a year, wrapped in a blanket of air that keeps us just right.",
      middle: "Earth is the third planet from the Sun and the only world known to have life. It is about 12,742 km across, mostly covered by liquid water — about 71% ocean — under an atmosphere of nitrogen and oxygen that we can breathe. Earth orbits the Sun once every 365.25 days and spins once every 24 hours, and its axis is tilted 23.5°, which gives us the seasons. A protective magnetic field, generated by its molten iron core, shields us from harmful solar radiation. Earth has one large Moon that steadies its tilt and makes the tides. It sits in the 'habitable zone,' the just-right distance where water can stay liquid — the foundation of all life.",
      high: "Earth is the largest and densest of the rocky planets (12,742 km diameter) and the only known home of life. About 71% of its surface is liquid water, and its atmosphere — 78% nitrogen, 21% oxygen — supports a biosphere while shielding the surface with an ozone layer.\n\nEarth orbits the Sun at ~150 million km (defining the astronomical unit) every 365.25 days, and its 23.5° axial tilt produces the seasons as different hemispheres lean toward the Sun. Its interior is layered — a solid inner core, liquid outer core, mantle, and crust — and convection in the molten iron outer core generates a global magnetic field that deflects the solar wind and prevents atmospheric loss.\n\nEarth's surface is uniquely active: plate tectonics recycles crust, builds mountains, and helps regulate climate over geologic time. The single large Moon, likely formed by a giant impact ~4.5 billion years ago, stabilizes the axial tilt and drives ocean tides. Life has shaped the planet in turn — photosynthesis created the oxygen atmosphere over billions of years.",
      adult: "PHYSICAL & COMPOSITION — Earth (6,371 km mean radius, 5.97×10^24 kg) is the densest planet, differentiated into a solid iron-nickel inner core, a liquid outer core, a silicate mantle, and a thin crust. Radiogenic heat and primordial heat drive mantle convection and plate tectonics — a process unique among known worlds that recycles carbon, builds continents, and buffers climate across geologic time.\n\n---\n\nORBIT, ATMOSPHERE & FIELD — Earth orbits at 1 AU with a 23.44° obliquity that drives the seasons and a nearly circular orbit (e≈0.017). Its atmosphere (N₂/O₂ with trace greenhouse gases) keeps the mean surface temperature near 15 °C and liquid water stable across ~71% of the surface. The geodynamo in the convecting outer core sustains a magnetosphere that deflects the solar wind, protecting the atmosphere and surface life from radiation.\n\n---\n\nLIFE, MOON & CONTEXT — Life arose at least ~3.7 billion years ago; oxygenic photosynthesis transformed the atmosphere and, ultimately, the planet's surface chemistry and climate. The Moon — ~1/4 Earth's diameter, likely formed from debris of a Mars-sized impact (Theia) — stabilizes Earth's axial tilt and raises the tides that may have aided life's origin. Earth sits within the Sun's habitable zone; understanding what makes it work is the reference for the search for life elsewhere.",
    },
  },
  {
    id: "moon", name: "The Moon", emoji: "🌙", master: "Sofia", group: "sun-rocky",
    text: {
      kids: "The Moon is Earth's only natural satellite, a rocky world that circles us about once a month. Its pull makes the ocean tides, and it always shows us the same face!",
      middle: "The Moon is Earth's only natural satellite, about 3,474 km across — roughly a quarter of Earth's width. It orbits us every 27.3 days, and because it spins once per orbit (tidal locking) it always shows Earth the same near side. Sunlight lighting different parts of the Moon as it orbits gives us the phases — new, crescent, quarter, gibbous, and full — over about 29.5 days. The Moon has almost no atmosphere, so its grey surface of craters, mountains, and dark lava 'seas' (maria) is unchanged for billions of years, still holding astronauts' footprints. Its gravity pulls Earth's oceans into the tides, and it slowly steadies Earth's tilt, keeping our climate stable.",
      high: "The Moon is Earth's only natural satellite and the fifth-largest in the solar system (3,474 km diameter — about a quarter of Earth's). It most likely formed ~4.5 billion years ago when a Mars-sized body struck the young Earth and the debris coalesced in orbit.\n\nIt is tidally locked, rotating once per 27.3-day orbit so the same near side always faces Earth; the cycle of phases takes 29.5 days as the Sun illuminates different fractions of the disk. Its surface — heavily cratered highlands and darker basaltic maria formed by ancient volcanism — is essentially fossilized, preserved by the lack of atmosphere and weather. Surface temperatures swing from about +120 °C in sunlight to −130 °C at night, and permanently shadowed polar craters hold water ice.\n\nThe Moon's gravity is the main driver of ocean tides and gradually slows Earth's rotation while receding ~3.8 cm per year. It stabilizes Earth's axial tilt, moderating our climate. Apollo astronauts walked its surface (1969-72) and returned samples; a new wave of robotic and crewed Artemis missions now targets the water-rich south pole.",
      adult: "ORIGIN & COMPOSITION — The Moon (1,737 km radius, 1/81 Earth's mass) most likely formed via the giant-impact hypothesis: a Mars-sized protoplanet (Theia) struck the proto-Earth ~4.5 Gyr ago, and the ejected debris accreted into the Moon. Its composition closely matches Earth's mantle, with a small iron core. An early magma ocean produced the anorthosite highlands; later basaltic volcanism flooded impact basins to form the maria.\n\n---\n\nORBIT & DYNAMICS — Tidally locked in synchronous rotation, the Moon keeps one hemisphere toward Earth; libration reveals ~59% of its surface over time. Its 27.3-day sidereal orbit and the Earth-Sun geometry yield the 29.5-day synodic cycle of phases and the rhythm of eclipses. Lunar tides dominate Earth's oceans, drive tidal braking that lengthens the day, and cause the Moon to recede ~3.8 cm/yr — measured by retroreflectors left by Apollo.\n\n---\n\nENVIRONMENT & EXPLORATION — With a near-vacuum exosphere, the surface preserves an unweathered record of solar-system history and human footprints alike; temperatures range ~250 °C between lunar day and night. Water ice in permanently shadowed polar craters is a key resource. Six Apollo landings (1969-72) returned 382 kg of samples that anchor our chronology of the inner solar system; the Artemis program and international robotic landers now aim to establish a sustained presence.",
    },
  },
  {
    id: "mars", name: "Mars", emoji: "♂", master: "Thor", group: "sun-rocky",
    text: {
      kids: "Mars is the red planet, colored rusty by iron in its dust. It has giant volcanoes, a canyon longer than a country, and robots exploring it right now looking for signs of old water!",
      middle: "Mars is the fourth planet from the Sun and about half Earth's width (6,779 km). It looks red because its soil is full of rusty iron oxide. Mars has a thin carbon-dioxide atmosphere, so it is cold — averaging about −60 °C — and dust storms can cover the whole planet. A Mars day is close to ours (24 hours 37 minutes), but a year is 687 Earth-days. It boasts the tallest volcano in the solar system, Olympus Mons (about 22 km high), and a vast canyon system, Valles Marineris, that would stretch across the United States. Dry riverbeds and lakebeds show liquid water once flowed there, which is why rovers like Perseverance search Mars for signs of ancient life. It has two tiny moons, Phobos and Deimos.",
      high: "Mars is the fourth planet, a cold desert world about half Earth's diameter (6,779 km) and one-tenth its mass, its surface tinted red by iron-oxide dust.\n\nIts thin atmosphere — 95% CO₂ at less than 1% of Earth's pressure — cannot hold heat, so temperatures average ~−60 °C, though summer days near the equator can rise above freezing. The axial tilt (25°) and 687-day orbit give Mars Earth-like seasons, amplified by planet-wide dust storms; a Martian solar day ('sol') is 24 h 37 m. Mars hosts extremes: Olympus Mons, a shield volcano ~22 km tall (the largest known), and Valles Marineris, a canyon system over 4,000 km long.\n\nAbundant evidence — dry river valleys, deltas, clay minerals, and polar ice caps of water and dry ice — shows Mars was once warmer and wetter, with lakes and perhaps a northern ocean billions of years ago. That makes it the prime target in the search for past life and for future human exploration. Its two small moons, Phobos and Deimos, are likely captured asteroids. A fleet of orbiters, landers, and rovers (Perseverance, Curiosity) explores it today.",
      adult: "PHYSICAL & INTERIOR — Mars (3,390 km radius, 0.107 Earth masses) is a differentiated rocky planet with a crust, mantle, and a partially liquid iron-sulfur core (confirmed by NASA's InSight seismometer). It lacks a global magnetic field today, though crustal magnetism records an ancient dynamo. Its low mass and lost magnetosphere allowed the solar wind to strip most of its once-thicker atmosphere.\n\n---\n\nSURFACE, ATMOSPHERE & SEASONS — The surface divides into ancient cratered southern highlands and smoother northern lowlands. Tharsis hosts giant shield volcanoes including Olympus Mons (~22 km), and Valles Marineris scars the equator for >4,000 km. The tenuous CO₂ atmosphere (~6 mbar) supports water-ice clouds, seasonal CO₂ polar caps, and global dust storms; obliquity (25.2°) and eccentricity give pronounced, variable seasons over its 687-day year.\n\n---\n\nWATER, LIFE & EXPLORATION — Valley networks, deltas, hydrated clays, and sulfate deposits show liquid water was stable in Mars's first billion years; subsurface and polar ice persist today. This makes Mars the leading venue for astrobiology — Perseverance is caching samples for return, seeking biosignatures in Jezero Crater's ancient lakebed. Its moons Phobos and Deimos may be captured asteroids or impact debris. Mars is the focal point of planned human missions in the coming decades.",
    },
  },
  {
    id: "jupiter", name: "Jupiter", emoji: "♃", master: "Enlil", group: "giants",
    text: {
      kids: "Jupiter is the biggest planet — so huge all the other planets could fit inside it! It's a giant ball of gas with a storm called the Great Red Spot bigger than the whole Earth.",
      middle: "Jupiter is the largest planet, about 143,000 km across — you could fit more than 1,300 Earths inside it. It is a gas giant made mostly of hydrogen and helium, with no solid surface to stand on. Jupiter spins faster than any other planet, turning once in under 10 hours, which makes it bulge at the equator and whips its clouds into colorful stripes. Its famous Great Red Spot is a storm bigger than Earth that has raged for centuries. Jupiter has a powerful magnetic field and at least 95 known moons, including the four large 'Galilean' moons Io, Europa, Ganymede, and Callisto. Europa hides a salty ocean under its icy crust — a promising place to look for life.",
      high: "Jupiter is the solar system's largest planet — 139,820 km in diameter, more massive than all the other planets combined — a gas giant of roughly 90% hydrogen and 10% helium with no solid surface.\n\nIt rotates in under 10 hours, the fastest of any planet, flattening its poles and organizing its atmosphere into alternating bright zones and dark belts of ammonia clouds. Enormous storms swirl within them, the largest being the Great Red Spot, an anticyclone wider than Earth that has persisted for at least 350 years. Deep inside, hydrogen is compressed into a metallic liquid whose currents generate the strongest planetary magnetic field in the solar system, trapping intense radiation belts.\n\nJupiter has at least 95 known moons. The four large Galilean moons — discovered in 1610 — are worlds in themselves: volcanic Io, ice-shelled Europa with a subsurface ocean, giant Ganymede (larger than Mercury), and cratered Callisto. Jupiter's immense gravity shapes the asteroid belt and shepherds comets. Missions Galileo and Juno have studied it; ESA's JUICE and NASA's Europa Clipper now head for its icy moons.",
      adult: "STRUCTURE & COMPOSITION — Jupiter (69,911 km radius, 318 Earth masses) is the archetypal gas giant, ~90% H / ~10% He by number, resembling the Sun in composition. It likely has a dilute, partially dissolved core of heavier elements. There is no surface: gaseous hydrogen transitions with depth to a vast layer of liquid metallic hydrogen under millions of bars of pressure. Jupiter radiates ~1.6× the energy it receives, still slowly contracting and releasing primordial heat.\n\n---\n\nATMOSPHERE, FIELD & DYNAMICS — Its ~9.9-hour rotation drives powerful zonal jets that split the visible ammonia-cloud deck into belts and zones; embedded vortices include the centuries-old Great Red Spot. Metallic-hydrogen currents generate a magnetic field ~20,000× stronger than Earth's total moment, creating a magnetosphere larger than the Sun and lethal radiation belts. Juno's gravity data reveal deep-rooted jet streams and a fuzzy core.\n\n---\n\nMOONS & ROLE — Jupiter has 95+ known moons and a faint ring. The Galilean moons anchor comparative planetology: Io is the most volcanically active body in the solar system (tidal heating); Europa and Ganymede host subsurface saltwater oceans — prime astrobiology targets; Ganymede has its own magnetic field. Jupiter's gravity sculpts the asteroid belt, captures Trojan asteroids, and deflects or draws in comets. Europa Clipper and JUICE (both en route) will assess the habitability of its ocean moons.",
    },
  },
  {
    id: "saturn", name: "Saturn", emoji: "♄", master: "Krishna", group: "giants",
    text: {
      kids: "Saturn is the ringed planet, wrapped in thousands of shiny rings made of ice and rock. It's so light for its size that it would float in a giant bathtub of water!",
      middle: "Saturn is the sixth planet and the second-largest, about 120,500 km across. It is a gas giant of hydrogen and helium, famous for its spectacular rings — countless chunks of ice and rock, from grains to house-sized boulders, spread wide but only about 10 meters thick. Saturn is the least dense planet; it is so light for its size that it would float in water. It spins fast (about 10.7 hours a day) but takes about 29 Earth-years to orbit the Sun. Saturn has at least 146 known moons — more than any other planet — including giant Titan, which has a thick atmosphere and lakes of liquid methane, and little Enceladus, which shoots geysers of water from a hidden ocean into space.",
      high: "Saturn is the second-largest planet (120,536 km diameter) and the most distant one easily visible to the naked eye — a gas giant of hydrogen and helium famous for its magnificent ring system.\n\nThe rings span up to ~280,000 km yet average only ~10 m thick, composed of countless particles of water ice and rock ranging from dust to boulders, shaped by gravity and shepherd moons into thousands of ringlets. Saturn is the least dense planet (less than water) and rotates in ~10.7 hours, giving it a pronounced equatorial bulge and banded, pale-gold clouds; a curious hexagonal jet stream circles its north pole. Its year lasts ~29 Earth-years.\n\nSaturn has 146+ confirmed moons. Titan, larger than Mercury, has a thick nitrogen atmosphere and surface lakes of liquid methane and ethane — a uniquely Earth-like weather cycle with an alien chemistry. Icy Enceladus vents plumes of water vapor and organic molecules from a subsurface ocean through its south-polar 'tiger stripes,' making it a top target in the search for life. The Cassini-Huygens mission (2004-2017) transformed our understanding of the whole system.",
      adult: "STRUCTURE & COMPOSITION — Saturn (58,232 km equatorial radius, 95 Earth masses) is a gas giant of ~96% hydrogen and ~3% helium, with the lowest mean density of any planet (0.69 g/cm³). Like Jupiter it grades from molecular to metallic hydrogen with depth over a heavier-element core, and radiates ~2.5× the sunlight it absorbs — partly from helium 'raining' toward the interior.\n\n---\n\nRINGS & ATMOSPHERE — The rings, likely young (perhaps tens to hundreds of Myr) and possibly the debris of a shattered moon, are >99% water ice, spanning A through E rings divided by gaps such as the Cassini Division and organized by resonances with shepherd moons. Saturn's ~10.7-hour rotation and internal heat drive banded winds up to ~1,800 km/h and the persistent north-polar hexagon. Its axial tilt (26.7°) yields seasons and changing ring illumination over its 29.4-year orbit.\n\n---\n\nMOONS & EXPLORATION — Of 146+ moons, Titan and Enceladus stand out: Titan's dense atmosphere hosts a methane hydrologic cycle, dunes, and hydrocarbon seas (target of NASA's Dragonfly rotorcraft, launching this decade); Enceladus erupts ocean water rich in salts and organics, sampled in flight by Cassini. Cassini-Huygens (2004-17), including the Huygens Titan landing, remains the defining exploration of the Saturnian system and a cornerstone of ocean-world science.",
    },
  },
  {
    id: "uranus", name: "Uranus", emoji: "⛢", master: "Pangu", group: "giants",
    text: {
      kids: "Uranus is a pale blue-green ice giant that spins on its side, like a ball rolling around the Sun! It's so cold that it's one of the chilliest planets of all.",
      middle: "Uranus is the seventh planet, an ice giant about 51,000 km across — four times wider than Earth. It looks blue-green because methane in its atmosphere absorbs red light. Uranus is unique: it is tipped over on its side, with its axis tilted about 98°, so it essentially rolls around the Sun. This gives it extreme seasons — each pole gets about 42 years of continuous sunlight followed by 42 years of darkness during its 84-year orbit. It is one of the coldest planets, with cloud tops near −220 °C. Uranus has faint rings and 28 known moons named after characters from Shakespeare and Alexander Pope. Only one spacecraft, Voyager 2, has ever visited it, flying by in 1986.",
      high: "Uranus is the seventh planet and the first 'ice giant' — 50,724 km in diameter, larger and less massive than the gas giants, made largely of water, methane, and ammonia ices over a small rocky core.\n\nIts most striking feature is an axial tilt of ~98°: Uranus is tipped completely on its side, likely knocked over by a giant collision early in its history. As a result it 'rolls' along its 84-year orbit, and each pole experiences ~42 years of continuous daylight then ~42 years of night. Methane in the upper atmosphere absorbs red light, giving Uranus its serene cyan color, though it is far more dynamic than Voyager's bland 1986 view suggested. It is the coldest planetary atmosphere in the solar system, dipping to ~−224 °C.\n\nUranus has a tilted, offset magnetic field, 13 known rings, and 28 moons named for characters in Shakespeare and Pope — Titania and Oberon are the largest, and Miranda shows dramatic cliffs and terrain. Never orbited by a dedicated mission, Uranus is a high priority for a future flagship orbiter.",
      adult: "STRUCTURE & COMPOSITION — Uranus (25,362 km radius, 14.5 Earth masses) is an ice giant: beneath a hydrogen-helium-methane atmosphere lies a hot, dense fluid mantle of 'ices' (water, methane, ammonia) surrounding a small rocky core. Unusually, it emits little more heat than it receives — its internal heat flow is anomalously low, perhaps trapped by compositional layering or released in the collision that tipped it over.\n\n---\n\nTILT, SEASONS & FIELD — Its 97.8° obliquity — essentially lying on its side — is the defining puzzle, most likely the result of one or more giant impacts. Over the 84-year orbit this produces the solar system's most extreme seasons, with decades-long polar day and night. The magnetic field is bizarre: tilted ~59° from the rotation axis and offset from the center, producing an asymmetric, tumbling magnetosphere. Cloud-top temperatures reach ~49 K, the coldest measured.\n\n---\n\nRINGS, MOONS & EXPLORATION — Uranus has 13 narrow, dark rings and 28 known moons; the five major moons (Miranda, Ariel, Umbriel, Titania, Oberon) show evidence of past geologic activity — Miranda's chaotic terrain is especially striking. Only Voyager 2 has visited (Jan 1986). The U.S. Planetary Science Decadal Survey ranks a Uranus Orbiter and Probe as the top flagship priority, to resolve its interior, field, and the potential ocean-world nature of its moons.",
    },
  },
  {
    id: "neptune", name: "Neptune", emoji: "♆", master: "Athena", group: "giants",
    text: {
      kids: "Neptune is the farthest planet, a deep blue ice giant with the fastest winds in the solar system — storms that blow faster than a jet plane! It's so far it takes 165 years to circle the Sun.",
      middle: "Neptune is the eighth and most distant planet, an ice giant about 49,000 km across and a vivid deep blue from methane in its atmosphere. It is the windiest planet, with supersonic storms roaring up to about 2,000 km/h. Neptune is so far from the Sun — about 4.5 billion km — that it takes 165 Earth-years to complete one orbit, and its cloud tops are extremely cold, around −220 °C. Amazingly, Neptune was discovered in 1846 through mathematics: astronomers predicted its position from the way its gravity tugged on Uranus, then pointed a telescope and found it. It has faint rings and 16 known moons, the largest being Triton, which orbits backwards and has geysers of nitrogen — hints it was captured from the distant Kuiper Belt.",
      high: "Neptune is the eighth and outermost planet, an ice giant 49,244 km in diameter and the densest of the giant planets, glowing a deep azure from atmospheric methane.\n\nDespite receiving little sunlight at ~30 AU, Neptune is remarkably active: it has the fastest winds in the solar system, up to ~2,100 km/h, and large dark storms that appear and vanish over years, such as the Great Dark Spot Voyager 2 saw in 1989. It radiates ~2.6× the energy it receives from the Sun, driving that dynamic weather. Its 164-year orbit means it has completed just one circuit since its discovery. Neptune is famous as the planet found 'on paper' — predicted in 1846 from irregularities in Uranus's motion and located within a degree of the prediction.\n\nNeptune has five faint rings and 16 known moons. Triton, the largest, is unique: it orbits retrograde, suggesting it is a captured Kuiper Belt object, and its cold surface erupts nitrogen geysers. Like Uranus, Neptune has been visited only once, by Voyager 2, and awaits a dedicated mission.",
      adult: "STRUCTURE & COMPOSITION — Neptune (24,622 km radius, 17.1 Earth masses) is an ice giant denser than Uranus, with a hydrogen-helium-methane atmosphere over a hot fluid mantle of water, methane, and ammonia and a rocky core. Unlike Uranus it has a strong internal heat source, radiating ~2.6× the absorbed sunlight — the engine behind its vigorous weather despite feeble insolation at ~30 AU.\n\n---\n\nATMOSPHERE & DYNAMICS — Neptune hosts the fastest winds measured on any planet (~2,100 km/h) and transient anticyclonic storms (the Great Dark Spot and successors) tracked by Voyager 2 and Hubble. Methane absorbs red light and an unidentified component deepens its blue relative to Uranus. Its magnetic field, like Uranus's, is strongly tilted (~47°) and offset, implying a dynamo in a convecting icy layer rather than a core.\n\n---\n\nDISCOVERY, MOONS & EXPLORATION — Neptune is the triumph of celestial mechanics: Le Verrier and Adams predicted it from perturbations in Uranus's orbit, and Galle found it in 1846 near the predicted spot. Of its 16 moons, Triton (2,707 km) orbits retrograde and is almost certainly a captured Kuiper Belt dwarf planet; Voyager 2 imaged active nitrogen geysers on its ~38 K surface. Only Voyager 2 has visited (1989); a Neptune-Triton orbiter is a compelling future flagship for ice-giant and ocean-world science.",
    },
  },
  {
    id: "pluto", name: "Pluto", emoji: "♇", master: "Odin", group: "far",
    text: {
      kids: "Pluto is a small, icy dwarf planet far out past Neptune. It even has a big heart-shaped patch of frozen ice on its surface, and a moon almost as big as itself!",
      middle: "Pluto is a dwarf planet in the Kuiper Belt, the ring of icy worlds beyond Neptune. It is small — about 2,377 km across, smaller than Earth's Moon — and made of rock and ice. Pluto is so far from the Sun that it takes 248 Earth-years to orbit once, and its surface is a frigid −230 °C. It was discovered in 1930 and counted as the ninth planet until 2006, when it was reclassified as a 'dwarf planet' after astronomers found many similar icy worlds nearby. In 2015 the New Horizons spacecraft flew past and revealed a stunning world: a huge heart-shaped plain of frozen nitrogen, water-ice mountains, and possible ice volcanoes. Pluto has five moons; the largest, Charon, is so big that the two orbit a point in space between them.",
      high: "Pluto is a dwarf planet and the best-known member of the Kuiper Belt — a region of icy bodies beyond Neptune. About 2,377 km across (smaller than Earth's Moon), it is a mix of rock and nitrogen, methane, and water ices.\n\nPluto's orbit is eccentric and tilted, ranging from 30 to 49 AU over 248 years — for 20 years of each orbit it comes closer to the Sun than Neptune, though a 3:2 resonance means they never collide. Surface temperatures hover near −230 °C. Discovered by Clyde Tombaugh in 1930, Pluto was the ninth planet until 2006, when the IAU, recognizing many similar Kuiper Belt objects (like Eris), defined 'dwarf planet' — a body that orbits the Sun and is round but has not cleared its orbital neighborhood.\n\nNASA's New Horizons flyby in July 2015 transformed Pluto from a blur into a complex world: the vast nitrogen-ice plain Sputnik Planitia (half of the bright 'heart'), water-ice mountains, glaciers, and hazy blue skies hinting at a possible subsurface ocean. Pluto has five moons; Charon is so large (half Pluto's diameter) that the pair orbit a common point in space between them — a true double system.",
      adult: "CLASSIFICATION & COMPOSITION — Pluto (1,188 km radius) is a dwarf planet and the prototype of the 'plutoids' — trans-Neptunian bodies large enough to be rounded by self-gravity. It is ~2/3 rock, ~1/3 ice by mass, with a differentiated interior possibly harboring a subsurface liquid-water ocean beneath an ice shell, its surface coated in nitrogen, methane, and carbon-monoxide ices.\n\n---\n\nORBIT & THE DEFINITION DEBATE — Its orbit (e≈0.25, i≈17°) spans 29.7-49.3 AU over 248 years and is locked in a 3:2 mean-motion resonance with Neptune, preventing close encounters. Discovered in 1930, Pluto lost planet status in 2006 when the IAU required a planet to have 'cleared its orbital neighborhood' — which Pluto, embedded in the populous Kuiper Belt alongside Eris, Haumea, and Makemake, has not. The decision remains culturally contentious.\n\n---\n\nSURFACE & EXPLORATION — New Horizons (July 2015) revealed astonishing geologic youth and diversity: Sputnik Planitia, a convecting nitrogen-ice glacier filling an ancient basin; water-ice mountains kilometers high; possible cryovolcanoes; and a layered nitrogen atmosphere with photochemical haze. Charon (606 km radius) forms a barycentric binary with Pluto and shows its own tectonic canyons and a dark polar deposit. Pluto reframed the outer solar system as a rich, active frontier rather than a static deep freeze.",
    },
  },
  {
    id: "polaris", name: "Polaris (North Star)", emoji: "⭐", master: "Thoth", group: "far",
    text: {
      kids: "Polaris is the North Star. It sits almost exactly above Earth's North Pole, so it barely moves in the sky while all the other stars circle around it — the perfect star for finding your way!",
      middle: "Polaris is the North Star — not a planet, but a star far outside our solar system, about 433 light-years away. It looks special because it sits almost directly above Earth's North Pole. As Earth spins, all the other stars appear to circle around Polaris while it stays nearly still, which has made it a guide for travelers and sailors for thousands of years to find north. Polaris is actually much bigger and brighter than the Sun — a yellow supergiant about 2,000 times more luminous. It is also a 'Cepheid variable,' a type of star that pulses and changes brightness in a regular rhythm. Astronomers use Cepheids like Polaris as 'standard candles' to measure the vast distances to other stars and galaxies.",
      high: "Polaris, the North Star, is not part of the solar system but a luminous star ~433 light-years away in the constellation Ursa Minor — the tip of the Little Dipper's handle. Its fame comes from its position: it lies within ~0.7° of the north celestial pole, so as Earth rotates, the entire sky appears to wheel around it while Polaris holds nearly still, making it a timeless navigational marker for finding true north and latitude.\n\nPolaris is a yellow supergiant, about 5-6 times the Sun's mass and ~2,000 times its luminosity. It is the closest and brightest Cepheid variable — a class of pulsating stars whose brightness rises and falls in a regular cycle. Because a Cepheid's pulsation period is tightly linked to its true luminosity, these stars serve as 'standard candles' that let astronomers measure cosmic distances — a cornerstone of the cosmic distance ladder.\n\nBecause Earth's axis slowly wobbles (precession) over ~26,000 years, Polaris has not always been — and will not always be — the pole star. Thousands of years ago the pole pointed elsewhere, and in the future stars like Vega will take the role.",
      adult: "NATURE & DISTANCE — Polaris (α Ursae Minoris) is a multiple star system ~433 light-years away, dominated by Polaris Aa, an F-type yellow supergiant of ~5.4 solar masses and ~1,260-2,000 solar luminosities, orbited by smaller companions (Ab and B). It is the nearest and brightest classical Cepheid variable, though its pulsation amplitude has notably changed over the last century — a live topic in stellar astrophysics.\n\n---\n\nTHE POLE STAR & PRECESSION — Polaris currently lies ~0.7° from the north celestial pole, so it appears nearly fixed while the sky rotates about it — the anchor of celestial navigation for latitude and true north. This alignment is temporary: the ~25,772-year precession of Earth's axis moves the celestial pole among the stars. Thuban (in Draco) was the pole star ~4,700 years ago; Polaris is closest around 2100 CE; Gamma Cephei and later Vega will follow.\n\n---\n\nCEPHEIDS & THE DISTANCE LADDER — As a Cepheid, Polaris obeys the period-luminosity relation discovered by Henrietta Leavitt: pulsation period predicts intrinsic brightness, so measuring the period yields distance. Cepheids calibrate the cosmic distance ladder out to nearby galaxies, underpinning the measurement of the Hubble constant and the scale of the universe. Culturally, the steadfast North Star has guided navigators, mapped stories across civilizations, and — fittingly for Thoth — kept the measure of the heavens.",
    },
  },
];

export const CELESTIAL_BY_ID: Record<string, CelestialEntry> = Object.fromEntries(CELESTIAL_BODIES.map((b) => [b.id, b]));
