import { SUPPORTED_LANGUAGES } from "@/lib/constants";

// ─── Types ───────────────────────────────────────────────────────

export interface LexiconLanguage {
  code: string;
  nameEn: string;
  nameNative: string;
  direction: "ltr" | "rtl";
  status: "approved" | "pending" | "rejected";
  proposerEmail?: string;
  proposedAt?: string;
  approvedBy?: string;
  approvedAt?: string;
}

export interface TranslationEntry {
  key: string;
  englishDefault: string;
  context: string;
  cubeId: number;
}

/** langCode → key → translated text */
export type LanguageTranslations = Record<string, Record<string, string>>;

export interface CubeGroup {
  cubeId: number;
  label: string;
  keys: TranslationEntry[];
}

// ─── Constants ───────────────────────────────────────────────────

export const ADMIN_EMAIL = "explore@eXeL-AI.com";

// ─── Translation keys organized per cube ─────────────────────────

const shared: TranslationEntry[] = [
  { key: "shared.tokens.heart", englishDefault: "♡ Tokens", context: "♡ token label", cubeId: 0 },
  { key: "shared.tokens.unity", englishDefault: "◬ Tokens", context: "◬ token label", cubeId: 0 },
  { key: "shared.tokens.human", englishDefault: "웃 Tokens", context: "웃 token label", cubeId: 0 },
  { key: "shared.feedback.button", englishDefault: "Give Feedback", context: "Persistent feedback button", cubeId: 0 },
  { key: "shared.feedback.placeholder", englishDefault: "Tell us what you think...", context: "Feedback textarea placeholder", cubeId: 0 },
  { key: "shared.feedback.submit", englishDefault: "Submit Feedback", context: "Submit feedback button", cubeId: 0 },
  { key: "shared.feedback.thanks", englishDefault: "Thank you for your feedback!", context: "Post-submit confirmation", cubeId: 0 },
  // Navigation & common UI
  { key: "shared.nav.settings", englishDefault: "Settings", context: "Settings menu item", cubeId: 0 },
  { key: "shared.nav.sign_out", englishDefault: "Sign out", context: "Logout menu item", cubeId: 0 },
  { key: "shared.nav.loading", englishDefault: "Loading...", context: "Loading spinner text", cubeId: 0 },
  { key: "shared.nav.continue", englishDefault: "Continue", context: "Continue button", cubeId: 0 },
  { key: "shared.nav.back", englishDefault: "Back", context: "Back button", cubeId: 0 },
  { key: "shared.nav.back_to_home", englishDefault: "Back to home", context: "Return to landing button", cubeId: 0 },
  // Landing page
  { key: "shared.landing.hero_title", englishDefault: "Governance at Scale", context: "Landing hero heading (full)", cubeId: 0 },
  { key: "shared.landing.hero_title_primary", englishDefault: "Governance", context: "Landing hero heading — primary color word", cubeId: 0 },
  { key: "shared.landing.hero_title_secondary", englishDefault: "at Scale", context: "Landing hero heading — muted color words", cubeId: 0 },
  { key: "shared.landing.hero_subtitle", englishDefault: "AI-powered polling, theming, and prioritization for groups of any size. Secure, deterministic, and transparent.", context: "Landing hero description", cubeId: 0 },
  { key: "shared.landing.feature_ai", englishDefault: "AI Theming", context: "Feature card title — maps to A.I. (Artificial Intelligence) in SoI Trinity", cubeId: 0 },
  { key: "shared.landing.feature_ai_desc", englishDefault: "Automatic clustering and summarization of responses in seconds", context: "Feature card description", cubeId: 0 },
  { key: "shared.landing.feature_scale", englishDefault: "Scale to Millions", context: "Feature card title — maps to S.I. (Shared Intent) in SoI Trinity", cubeId: 0 },
  { key: "shared.landing.feature_scale_desc", englishDefault: "Handle 100K+ concurrent participants with real-time results", context: "Feature card description", cubeId: 0 },
  { key: "shared.landing.feature_governance", englishDefault: "Human Governance", context: "Feature card title — maps to H.I. (Human Intelligence) in SoI Trinity", cubeId: 0 },
  { key: "shared.landing.feature_governance_desc", englishDefault: "Auditable Consensus at the Speed of Thought", context: "Feature card description", cubeId: 0 },
  { key: "shared.landing.facilitator_cta", englishDefault: "Are you a Session Facilitator?", context: "CTA question", cubeId: 0 },
  { key: "shared.landing.facilitator_button", englishDefault: "Session Facilitator Access", context: "CTA button", cubeId: 0 },
  // Error states
  { key: "shared.error.something_wrong", englishDefault: "Something went wrong", context: "Error boundary heading", cubeId: 0 },
  { key: "shared.error.unexpected", englishDefault: "An unexpected error occurred. Please try refreshing the page.", context: "Error boundary description", cubeId: 0 },
  { key: "shared.error.retry", englishDefault: "Retry", context: "Error retry button", cubeId: 0 },
  // Auth
  { key: "shared.auth.loading", englishDefault: "Loading...", context: "Auth loading spinner text", cubeId: 0 },
  { key: "shared.auth.error", englishDefault: "Authentication Error", context: "Auth error heading", cubeId: 0 },
  { key: "shared.auth.try_again", englishDefault: "Try again", context: "Auth retry link", cubeId: 0 },
  { key: "shared.auth.login_failed", englishDefault: "Login failed", context: "Login error heading", cubeId: 0 },
  { key: "shared.auth.signing_in", englishDefault: "Signing you in...", context: "Auth callback loading text", cubeId: 0 },
  // Simulation overlay
  { key: "shared.sim.simulation_mode", englishDefault: "Simulation Mode", context: "Simulation overlay label", cubeId: 0 },
  { key: "shared.sim.exit", englishDefault: "Exit simulation", context: "Exit simulation button title", cubeId: 0 },
  { key: "shared.sim.audio_unavailable", englishDefault: "Audio unavailable", context: "Simulation audio error", cubeId: 0 },
  { key: "shared.sim.loading", englishDefault: "Loading", context: "Simulation audio loading label", cubeId: 0 },
  { key: "shared.sim.volume", englishDefault: "Volume", context: "Volume slider title", cubeId: 0 },
  // Common UI
  { key: "shared.nav.cancel", englishDefault: "Cancel", context: "Cancel button", cubeId: 0 },
  { key: "shared.nav.participants", englishDefault: "participants", context: "Participant count suffix", cubeId: 0 },
  { key: "shared.nav.off", englishDefault: "Off", context: "Toggle off label", cubeId: 0 },
  { key: "shared.nav.chars", englishDefault: "chars", context: "Character count suffix", cubeId: 0 },
];

const cube1: TranslationEntry[] = [
  // Join flow
  { key: "cube1.join.title", englishDefault: "Join Session", context: "Join page heading", cubeId: 1 },
  { key: "cube1.join.enter_code", englishDefault: "Enter session code", context: "Code input placeholder", cubeId: 1 },
  { key: "cube1.join.scan_qr", englishDefault: "Scan QR Code", context: "QR scan button", cubeId: 1 },
  { key: "cube1.join.select_language", englishDefault: "Select Your Language", context: "Language step heading", cubeId: 1 },
  { key: "cube1.join.select_language_desc", englishDefault: "Choose one of 33 languages you'd like to participate in", context: "Language step description", cubeId: 1 },
  { key: "cube1.join.identity_title", englishDefault: "How Would You Like to Join?", context: "Identity step heading", cubeId: 1 },
  { key: "cube1.join.identity_anonymous", englishDefault: "This session is anonymous", context: "Anonymous session note", cubeId: 1 },
  { key: "cube1.join.identity_prompt", englishDefault: "Enter a display name or join anonymously", context: "Identity step description", cubeId: 1 },
  { key: "cube1.join.display_name", englishDefault: "Display Name", context: "Name input label", cubeId: 1 },
  { key: "cube1.join.your_name", englishDefault: "Your name", context: "Name input placeholder", cubeId: 1 },
  { key: "cube1.join.join_anonymously", englishDefault: "Join Anonymously", context: "Anonymous join button", cubeId: 1 },
  { key: "cube1.join.receive_results", englishDefault: "Receive Results?", context: "Results step heading", cubeId: 1 },
  { key: "cube1.join.results_question", englishDefault: "Would you like to receive the session results when they're ready?", context: "Results step description", cubeId: 1 },
  { key: "cube1.join.results_paid", englishDefault: "Results access requires payment", context: "Paid results notice", cubeId: 1 },
  { key: "cube1.join.results_yes_button", englishDefault: "Yes, I want results", context: "Accept results button", cubeId: 1 },
  { key: "cube1.join.results_no_button", englishDefault: "No thanks, just participate", context: "Decline results button", cubeId: 1 },
  { key: "cube1.join.joining", englishDefault: "Joining session...", context: "Join progress text", cubeId: 1 },
  { key: "cube1.join.unable_to_join", englishDefault: "Unable to Join", context: "Error heading", cubeId: 1 },
  { key: "cube1.join.session_ended", englishDefault: "This session has ended.", context: "Closed session message", cubeId: 1 },
  { key: "cube1.join.results_optin", englishDefault: "Would you like to receive the results?", context: "Results opt-in prompt", cubeId: 1 },
  { key: "cube1.join.results_yes", englishDefault: "Yes, send me results", context: "Opt-in accept button", cubeId: 1 },
  { key: "cube1.join.results_no", englishDefault: "No thanks", context: "Opt-in decline button", cubeId: 1 },
  { key: "cube1.join.payment_required", englishDefault: "Payment required to join", context: "Cost-split payment notice", cubeId: 1 },
  { key: "cube1.join.fee_per_user", englishDefault: "Your share:", context: "Per-user fee label", cubeId: 1 },
  { key: "cube1.join.pay_now", englishDefault: "Pay & Join", context: "Payment submit button", cubeId: 1 },
  { key: "cube1.join.joined", englishDefault: "You've joined the session!", context: "Successful join confirmation", cubeId: 1 },
  { key: "cube1.join.expired", englishDefault: "This session has expired.", context: "Expired session message", cubeId: 1 },
  { key: "cube1.join.full", englishDefault: "This session is full.", context: "Capacity reached message", cubeId: 1 },
  // Moderator
  { key: "cube1.moderator.create_session", englishDefault: "Create Session", context: "Create session button", cubeId: 1 },
  { key: "cube1.moderator.session_name", englishDefault: "Session Name", context: "Session name input label", cubeId: 1 },
  { key: "cube1.moderator.session_type", englishDefault: "Session Type", context: "Type selector label", cubeId: 1 },
  { key: "cube1.moderator.polling_mode", englishDefault: "Polling Mode", context: "Single/Multi-round selector", cubeId: 1 },
  { key: "cube1.moderator.pricing_tier", englishDefault: "Pricing Tier", context: "Free/Paid/Split selector", cubeId: 1 },
  { key: "cube1.moderator.session_fee", englishDefault: "Session Fee", context: "Fee input label", cubeId: 1 },
  { key: "cube1.moderator.cost_splitting", englishDefault: "Split cost with participants", context: "Cost split toggle label", cubeId: 1 },
  { key: "cube1.moderator.reward_amount", englishDefault: "Gamified Reward Amount", context: "CQS reward input label", cubeId: 1 },
  { key: "cube1.moderator.ranking_mode", englishDefault: "Ranking Mode", context: "Ranking mode selector", cubeId: 1 },
  { key: "cube1.moderator.response_limit", englishDefault: "Response Character Limit", context: "Char limit input", cubeId: 1 },
  { key: "cube1.moderator.question_limit", englishDefault: "Question Character Limit", context: "Char limit input", cubeId: 1 },
  { key: "cube1.moderator.open_session", englishDefault: "Open Session", context: "State transition button", cubeId: 1 },
  { key: "cube1.moderator.close_session", englishDefault: "Close Session", context: "State transition button", cubeId: 1 },
  { key: "cube1.moderator.share_link", englishDefault: "Share Link", context: "Copy join link button", cubeId: 1 },
  { key: "cube1.moderator.qr_code", englishDefault: "QR Code", context: "Show QR modal button", cubeId: 1 },
  // Session states
  { key: "cube1.session.draft", englishDefault: "Draft", context: "Session state label", cubeId: 1 },
  { key: "cube1.session.open", englishDefault: "Open", context: "Session state label", cubeId: 1 },
  { key: "cube1.session.polling", englishDefault: "Polling", context: "Session state label", cubeId: 1 },
  { key: "cube1.session.ranking", englishDefault: "Ranking", context: "Session state label", cubeId: 1 },
  { key: "cube1.session.closed", englishDefault: "Closed", context: "Session state label", cubeId: 1 },
  { key: "cube1.session.archived", englishDefault: "Archived", context: "Session state label", cubeId: 1 },
  { key: "cube1.session.participants", englishDefault: "Participants", context: "Participant count label", cubeId: 1 },
  { key: "cube1.session.waiting", englishDefault: "Waiting for moderator to start...", context: "Participant waiting state", cubeId: 1 },
  // Scoping
  { key: "cube1.session.project_id", englishDefault: "Project ID", context: "Scoping field label", cubeId: 1 },
  { key: "cube1.session.spec_id", englishDefault: "Specification ID", context: "Scoping field label", cubeId: 1 },
  { key: "cube1.session.diff_id", englishDefault: "Differentiator ID", context: "Scoping field label", cubeId: 1 },
  { key: "cube1.session.scoping_context", englishDefault: "Scoping Context", context: "Scoping selector label", cubeId: 1 },
  // Multi-device
  { key: "cube1.moderator.phone_mode", englishDefault: "Phone Control", context: "Phone-optimized moderator UI label", cubeId: 1 },
  { key: "cube1.moderator.sync_status", englishDefault: "Synced", context: "Multi-device sync indicator", cubeId: 1 },
  // Session view — polling steps
  { key: "cube1.session.step_objectives", englishDefault: "Objectives", context: "Polling step label", cubeId: 1 },
  { key: "cube1.session.step_feedback", englishDefault: "Feedback", context: "Polling step label", cubeId: 1 },
  { key: "cube1.session.step_ranking", englishDefault: "Ranking", context: "Polling step label", cubeId: 1 },
  { key: "cube1.session.step_results", englishDefault: "Results", context: "Polling step label", cubeId: 1 },
  // Session view — participant lobby
  { key: "cube1.session.participants_joined", englishDefault: "participants joined", context: "Lobby participant counter suffix", cubeId: 1 },
  { key: "cube1.session.waiting_polling", englishDefault: "Waiting for moderator to start polling...", context: "Lobby waiting message", cubeId: 1 },
  { key: "cube1.session.session_code", englishDefault: "Session Code", context: "Session code display label", cubeId: 1 },
  // Session view — question display
  { key: "cube1.session.question_prefix", englishDefault: "Question", context: "Question N of M prefix", cubeId: 1 },
  { key: "cube1.session.question_of", englishDefault: "of", context: "Question N of M connector", cubeId: 1 },
  { key: "cube1.session.waiting_question", englishDefault: "Waiting for question...", context: "No question loaded yet", cubeId: 1 },
  // Session view — submission states
  { key: "cube1.session.all_submitted", englishDefault: "All responses submitted!", context: "All questions answered", cubeId: 1 },
  { key: "cube1.session.waiting_others", englishDefault: "Waiting for other participants to finish...", context: "Post-submit waiting", cubeId: 1 },
  { key: "cube1.session.response_submitted", englishDefault: "Response submitted!", context: "Single response confirmed", cubeId: 1 },
  { key: "cube1.session.respond_again", englishDefault: "Respond Again", context: "Button to submit another response", cubeId: 1 },
  { key: "cube1.session.next_question", englishDefault: "Next Question", context: "Advance to next question button", cubeId: 1 },
  { key: "cube1.session.submit_next", englishDefault: "Submit & Next", context: "Submit and advance button", cubeId: 1 },
  { key: "cube1.session.submit_btn", englishDefault: "Input Complete", context: "Final submit button — last question", cubeId: 1 },
  // Session view — theme voting
  { key: "cube1.session.theme_voting", englishDefault: "Theme Voting", context: "Ranking state heading", cubeId: 1 },
  { key: "cube1.session.theme_voting_desc", englishDefault: "Vote on the themes that emerged from responses", context: "Ranking state description", cubeId: 1 },
  { key: "cube1.session.theme_voting_soon", englishDefault: "Theme voting interface coming soon (Cube 7)", context: "Ranking stub placeholder", cubeId: 1 },
  // Session view — session ended
  { key: "cube1.session.session_ended", englishDefault: "Session Ended", context: "Closed session heading", cubeId: 1 },
  { key: "cube1.session.session_closed_msg", englishDefault: "This session has been closed. If you opted in for results, you'll receive them when they're ready.", context: "Closed session description", cubeId: 1 },
  // Session code input
  { key: "cube1.session.enter_code_error", englishDefault: "Please enter a session code", context: "Empty code validation error", cubeId: 1 },
  // Moderator dashboard
  { key: "cube1.moderator.dashboard_title", englishDefault: "Dashboard", context: "Dashboard page heading", cubeId: 1 },
  { key: "cube1.moderator.facilitator_access", englishDefault: "Session Facilitator Access", context: "Dashboard subtitle", cubeId: 1 },
  { key: "cube1.moderator.create_new", englishDefault: "Create New Session", context: "Create dialog title", cubeId: 1 },
  { key: "cube1.moderator.create_new_desc", englishDefault: "Set up a new polling session for your participants", context: "Create dialog description", cubeId: 1 },
  { key: "cube1.moderator.session_title", englishDefault: "Session Title", context: "Title input label", cubeId: 1 },
  { key: "cube1.moderator.description_label", englishDefault: "Outcome Desired (optional)", context: "Outcome desired input label", cubeId: 1 },
  { key: "cube1.moderator.ai_provider", englishDefault: "AI Provider", context: "Provider selector label", cubeId: 1 },
  { key: "cube1.moderator.max_response_label", englishDefault: "Max Response Length", context: "Max response input label", cubeId: 1 },
  { key: "cube1.moderator.max_participants_label", englishDefault: "Max Participants", context: "Max participants input label", cubeId: 1 },
  { key: "cube1.moderator.gamified_reward", englishDefault: "Gamified Reward", context: "Reward toggle label", cubeId: 1 },
  { key: "cube1.moderator.reward_cqs", englishDefault: "Award top contributor by CQS", context: "Reward description", cubeId: 1 },
  { key: "cube1.moderator.reward_amount_label", englishDefault: "Reward Amount ($)", context: "Reward amount input label", cubeId: 1 },
  { key: "cube1.moderator.start_polling", englishDefault: "Start Polling", context: "Start polling transition button", cubeId: 1 },
  { key: "cube1.moderator.start_ranking", englishDefault: "Start Ranking", context: "Start ranking transition button", cubeId: 1 },
  { key: "cube1.moderator.close_label", englishDefault: "Close", context: "Close session button", cubeId: 1 },
  { key: "cube1.moderator.archive_label", englishDefault: "Archive", context: "Archive session button", cubeId: 1 },
  { key: "cube1.moderator.join_link", englishDefault: "Join Link", context: "Join link label", cubeId: 1 },
  { key: "cube1.moderator.present_qr", englishDefault: "Present QR", context: "QR presentation button", cubeId: 1 },
  { key: "cube1.moderator.scan_join", englishDefault: "Scan to join this session", context: "QR presentation subtitle", cubeId: 1 },
  { key: "cube1.moderator.or_enter_code", englishDefault: "Or enter code:", context: "QR presentation alt text", cubeId: 1 },
  { key: "cube1.moderator.configuration", englishDefault: "Configuration", context: "Config section heading", cubeId: 1 },
  { key: "cube1.moderator.type_label", englishDefault: "Type", context: "Config type label", cubeId: 1 },
  { key: "cube1.moderator.anonymity_label", englishDefault: "Anonymity", context: "Config anonymity label", cubeId: 1 },
  { key: "cube1.moderator.max_response_config", englishDefault: "Max Response", context: "Config max response label", cubeId: 1 },
  { key: "cube1.moderator.pricing_config", englishDefault: "Pricing", context: "Config pricing label", cubeId: 1 },
  { key: "cube1.moderator.reward_config", englishDefault: "Reward", context: "Config reward label", cubeId: 1 },
  { key: "cube1.moderator.no_sessions", englishDefault: "No sessions yet", context: "Empty sessions list heading", cubeId: 1 },
  { key: "cube1.moderator.create_first", englishDefault: "Create your first polling session to get started", context: "Empty sessions list description", cubeId: 1 },
  { key: "cube1.moderator.back_sessions", englishDefault: "Back to sessions", context: "Back navigation button", cubeId: 1 },
  { key: "cube1.moderator.live_feed", englishDefault: "Live Response Feed", context: "Live feed heading", cubeId: 1 },
  { key: "cube1.moderator.expand_feed", englishDefault: "Expand Feed", context: "Maximize live feed button", cubeId: 1 },
  { key: "cube1.moderator.collapse_feed", englishDefault: "Collapse", context: "Minimize live feed button", cubeId: 1 },
  { key: "cube1.moderator.waiting_responses", englishDefault: "Waiting for responses...", context: "Empty feed placeholder", cubeId: 1 },
  // Live feed — summary toggle (Task A6 / BR-4)
  { key: "cube1.feed.toggle_live", englishDefault: "Live Feedback", context: "Feed toggle option A — raw clean_text (default)", cubeId: 1 },
  { key: "cube1.feed.toggle_summary", englishDefault: "33-Word Summary", context: "Feed toggle option B — AI summary_33", cubeId: 1 },
  { key: "cube1.feed.summary_loading", englishDefault: "Generating summary...", context: "Shown while Phase A is processing (before summary_ready broadcast)", cubeId: 1 },
  { key: "cube1.feed.summary_unavailable", englishDefault: "Summary unavailable", context: "Shown when Phase A retry exhausted", cubeId: 1 },
  { key: "cube1.feed.summary_short", englishDefault: "Response is already concise", context: "Shown when BR-1 short-circuit applies (≤33 words)", cubeId: 1 },
  { key: "cube1.moderator.poll_duration", englishDefault: "Poll Duration", context: "Static poll duration label", cubeId: 1 },
  // Countdown timer
  { key: "cube1.timer.days", englishDefault: "days", context: "Timer phase label — days", cubeId: 1 },
  { key: "cube1.timer.hours", englishDefault: "hours", context: "Timer phase label — hours", cubeId: 1 },
  { key: "cube1.timer.minutes", englishDefault: "min", context: "Timer phase label — minutes", cubeId: 1 },
  { key: "cube1.timer.seconds", englishDefault: "sec", context: "Timer phase label — seconds", cubeId: 1 },
  { key: "cube1.timer.poll_ends", englishDefault: "Poll Ends:", context: "Day timer prefix", cubeId: 1 },
  { key: "cube1.timer.poll_ended", englishDefault: "Poll has ended", context: "Timer ended label", cubeId: 1 },
  { key: "cube1.timer.at", englishDefault: "at", context: "Day timer date/time connector", cubeId: 1 },
  { key: "cube1.moderator.timer_display", englishDefault: "Timer Display", context: "Timer display mode label", cubeId: 1 },
  { key: "cube1.moderator.timer_day", englishDefault: "Day Timer", context: "Timer mode option", cubeId: 1 },
  { key: "cube1.moderator.timer_flex", englishDefault: "Flex Timer", context: "Timer mode option", cubeId: 1 },
  { key: "cube1.moderator.timer_both", englishDefault: "Both", context: "Timer mode option", cubeId: 1 },
  { key: "cube1.timer.sim_duration", englishDefault: "Sim Duration", context: "Simulation duration selector label", cubeId: 1 },
  { key: "cube1.moderator.mode_live", englishDefault: "Live", context: "Live Interactive polling mode badge", cubeId: 1 },
  { key: "cube1.moderator.mode_static", englishDefault: "Static", context: "Static Poll polling mode badge", cubeId: 1 },
  { key: "cube1.moderator.poll_deadline", englishDefault: "Poll Deadline", context: "Poll deadline label", cubeId: 1 },
  // Settings panel
  { key: "cube1.settings.color_scheme", englishDefault: "Session Color Scheme", context: "Theme section heading", cubeId: 1 },
  { key: "cube1.settings.color_set_by_mod", englishDefault: "Color scheme is set by your session moderator.", context: "Disabled theme note", cubeId: 1 },
  { key: "cube1.settings.color_applies_all", englishDefault: "Applies to all participants in this session.", context: "Moderator theme note", cubeId: 1 },
  { key: "cube1.settings.custom", englishDefault: "Custom", context: "Custom color picker label", cubeId: 1 },
  { key: "cube1.settings.title", englishDefault: "Settings", context: "Settings panel title (user)", cubeId: 1 },
  { key: "cube1.settings.moderator_title", englishDefault: "Moderator Settings", context: "Settings panel title (moderator)", cubeId: 1 },
  // Cube Architecture Status
  { key: "cube1.settings.cube_architecture", englishDefault: "Cube Architecture", context: "Cube status section heading", cubeId: 1 },
  { key: "cube1.settings.deployed", englishDefault: "Deployed", context: "Cube status label", cubeId: 1 },
  { key: "cube1.settings.in_progress_status", englishDefault: "In Progress", context: "Cube status label", cubeId: 1 },
  { key: "cube1.settings.not_started", englishDefault: "Not Started", context: "Cube status label", cubeId: 1 },
  { key: "cube1.settings.planned", englishDefault: "Planned", context: "Cube status label", cubeId: 1 },
  { key: "cube1.settings.legend", englishDefault: "Legend", context: "Legend toggle label", cubeId: 1 },
  { key: "cube1.settings.collapse", englishDefault: "Collapse", context: "Collapse section button", cubeId: 1 },
  { key: "cube1.settings.layer1", englishDefault: "Layer 1", context: "Grid layer 1 label", cubeId: 1 },
  { key: "cube1.settings.layer2_center", englishDefault: "Layer 2 — Center", context: "Grid layer 2 label", cubeId: 1 },
  // Language Lexicon panel
  { key: "cube1.settings.language_lexicon", englishDefault: "Language Lexicon", context: "Language lexicon section heading", cubeId: 1 },
  { key: "cube1.settings.languages_count", englishDefault: "languages", context: "Language count suffix", cubeId: 1 },
  { key: "cube1.settings.propose_new", englishDefault: "Propose New Language", context: "Propose language button", cubeId: 1 },
  { key: "cube1.settings.pending_approvals", englishDefault: "Pending Approvals", context: "Admin approvals button", cubeId: 1 },
  { key: "cube1.settings.language_proposed", englishDefault: "Language proposed!", context: "Proposal success heading", cubeId: 1 },
  { key: "cube1.settings.admin_approve", englishDefault: "An admin must approve it before it becomes active.", context: "Proposal success note", cubeId: 1 },
  { key: "cube1.settings.propose_heading", englishDefault: "Propose New Language", context: "Propose form heading", cubeId: 1 },
  { key: "cube1.settings.iso_code", englishDefault: "ISO Code", context: "ISO code input label", cubeId: 1 },
  { key: "cube1.settings.english_name", englishDefault: "English Name", context: "English name input label", cubeId: 1 },
  { key: "cube1.settings.native_name", englishDefault: "Native Name", context: "Native name input label", cubeId: 1 },
  { key: "cube1.settings.text_direction", englishDefault: "Text Direction", context: "Direction select label", cubeId: 1 },
  { key: "cube1.settings.ltr", englishDefault: "Left-to-Right (LTR)", context: "LTR option", cubeId: 1 },
  { key: "cube1.settings.rtl", englishDefault: "Right-to-Left (RTL)", context: "RTL option", cubeId: 1 },
  { key: "cube1.settings.submit_proposal", englishDefault: "Submit Proposal", context: "Submit proposal button", cubeId: 1 },
  { key: "cube1.settings.back_languages", englishDefault: "Back to Languages", context: "Back to language list button", cubeId: 1 },
  { key: "cube1.settings.no_pending", englishDefault: "No pending language proposals.", context: "Empty approvals state", cubeId: 1 },
  { key: "cube1.settings.all_tab", englishDefault: "All", context: "All cubes filter tab", cubeId: 1 },
];

const cube2: TranslationEntry[] = [
  { key: "cube2.input.placeholder", englishDefault: "Type your response...", context: "Text input placeholder", cubeId: 2 },
  { key: "cube2.input.submit", englishDefault: "Submit Response", context: "Submit button", cubeId: 2 },
  { key: "cube2.input.char_remaining", englishDefault: "characters remaining", context: "Char counter suffix", cubeId: 2 },
  { key: "cube2.input.too_long", englishDefault: "Response exceeds character limit", context: "Validation error", cubeId: 2 },
  { key: "cube2.input.empty", englishDefault: "Please enter a response", context: "Validation error", cubeId: 2 },
  { key: "cube2.input.profanity_warning", englishDefault: "Please revise — inappropriate content detected", context: "PII/profanity filter notice", cubeId: 2 },
  { key: "cube2.input.submission_failed", englishDefault: "Submission failed", context: "Error toast title on submission failure", cubeId: 2 },
  { key: "cube2.input.submitted", englishDefault: "Response submitted!", context: "Success confirmation", cubeId: 2 },
  { key: "cube2.input.tokens_earned", englishDefault: "Tokens earned:", context: "Post-submit token display label", cubeId: 2 },
  { key: "cube2.feed.title", englishDefault: "Live Responses", context: "Live feed heading (host PC)", cubeId: 2 },
  { key: "cube2.feed.toggle", englishDefault: "Show live feed", context: "Toggle live feed on/off", cubeId: 2 },
  { key: "cube2.feed.empty", englishDefault: "No responses yet", context: "Empty feed state", cubeId: 2 },
  { key: "cube2.feed.summary", englishDefault: "33-word summary", context: "Per-response summary label", cubeId: 2 },
  { key: "cube2.feed.paid_only", englishDefault: "Live feed available on paid tiers", context: "Free tier gate message", cubeId: 2 },
];

const cube3: TranslationEntry[] = [
  { key: "cube3.voice.record", englishDefault: "Hold to record", context: "Voice record button label", cubeId: 3 },
  { key: "cube3.voice.recording", englishDefault: "Recording...", context: "Active recording indicator", cubeId: 3 },
  { key: "cube3.voice.processing", englishDefault: "Converting speech to text...", context: "STT processing indicator", cubeId: 3 },
  { key: "cube3.voice.preview", englishDefault: "Preview transcript", context: "Transcript preview heading", cubeId: 3 },
  { key: "cube3.voice.confirm", englishDefault: "Submit transcript", context: "Confirm transcript button", cubeId: 3 },
  { key: "cube3.voice.retry", englishDefault: "Record again", context: "Re-record button", cubeId: 3 },
  { key: "cube3.voice.mic_permission", englishDefault: "Microphone access required", context: "Permission prompt", cubeId: 3 },
  { key: "cube3.voice.mic_denied", englishDefault: "Microphone access denied. Please enable in browser settings.", context: "Permission denied message", cubeId: 3 },
  { key: "cube3.voice.not_supported", englishDefault: "Voice input not supported in this browser", context: "Browser compatibility message", cubeId: 3 },
  { key: "cube3.voice.too_short", englishDefault: "Recording too short — please try again", context: "Minimum duration error", cubeId: 3 },
  { key: "cube3.voice.tokens_earned", englishDefault: "Tokens earned:", context: "Post-submit token display label", cubeId: 3 },
  // Voice input button states
  { key: "cube3.voice.captured", englishDefault: "Voice captured", context: "Voice capture success toast title", cubeId: 3 },
  { key: "cube3.voice.stt_pending", englishDefault: "STT integration pending (Cube 3).", context: "STT stub notice", cubeId: 3 },
  { key: "cube3.voice.access_denied", englishDefault: "Microphone access denied", context: "Mic denied toast title", cubeId: 3 },
  { key: "cube3.voice.allow_mic", englishDefault: "Please allow microphone access to use voice input.", context: "Mic denied toast description", cubeId: 3 },
  { key: "cube3.voice.stop", englishDefault: "Stop recording", context: "Stop recording button title", cubeId: 3 },
  { key: "cube3.voice.processing_audio", englishDefault: "Processing audio...", context: "Processing state button title", cubeId: 3 },
  { key: "cube3.voice.record_response", englishDefault: "Record voice response", context: "Record button title", cubeId: 3 },
  { key: "cube3.voice.no_speech", englishDefault: "No speech detected — please try again", context: "Empty recording error", cubeId: 3 },
  { key: "cube3.voice.low_confidence", englishDefault: "Low transcription confidence — please review", context: "Low confidence warning toast", cubeId: 3 },
  { key: "cube3.voice.confidence_label", englishDefault: "confidence", context: "Confidence percentage label", cubeId: 3 },
  { key: "cube3.voice.reduce_to_33", englishDefault: "Reduce to 33 words", context: "On-demand 33-word summary button in live feed (MoT-1)", cubeId: 3 },
  // V2T provider settings (Moderator Settings panel)
  { key: "cube3.settings.v2t_provider", englishDefault: "Voice-to-Text Provider", context: "V2T settings section heading", cubeId: 3 },
  { key: "cube3.settings.v2t_desc", englishDefault: "Select the speech-to-text engine for voice responses in this session.", context: "V2T settings description", cubeId: 3 },
  { key: "cube3.settings.v2t_active", englishDefault: "Active Provider", context: "Currently active provider label", cubeId: 3 },
  { key: "cube3.settings.v2t_fallback", englishDefault: "Circuit breaker failover: if primary fails, system auto-switches to next available provider.", context: "Fallback explanation note", cubeId: 3 },
  { key: "cube3.settings.v2t_languages", englishDefault: "languages supported", context: "Provider language count suffix", cubeId: 3 },
  { key: "cube3.settings.v2t_pricing", englishDefault: "Cost Estimates", context: "Toggle label for pricing section", cubeId: 3 },
  { key: "cube3.settings.v2t_estimate_title", englishDefault: "Estimated cost per 1,000 users (2 min avg)", context: "Pricing table heading", cubeId: 3 },
  { key: "cube3.settings.v2t_estimate_note", englishDefault: "Based on ~2 min average voice response per user. Actual costs vary by audio length and provider pricing.", context: "Pricing disclaimer", cubeId: 3 },
];

const cube4: TranslationEntry[] = [
  { key: "cube4.presence.online", englishDefault: "Online", context: "Presence status badge", cubeId: 4 },
  { key: "cube4.presence.idle", englishDefault: "Idle", context: "Presence status badge", cubeId: 4 },
  { key: "cube4.presence.offline", englishDefault: "Offline", context: "Presence status badge", cubeId: 4 },
  { key: "cube4.presence.count", englishDefault: "participants online", context: "Presence counter suffix", cubeId: 4 },
  { key: "cube4.desired_outcome.title", englishDefault: "Desired Outcome", context: "Outcome setup heading (M2/M3)", cubeId: 4 },
  { key: "cube4.desired_outcome.placeholder", englishDefault: "Describe your desired outcome...", context: "Outcome textarea placeholder", cubeId: 4 },
  { key: "cube4.desired_outcome.confirm", englishDefault: "Confirm Outcome", context: "Outcome confirm button", cubeId: 4 },
  { key: "cube4.desired_outcome.achieved", englishDefault: "Achieved", context: "Outcome status option", cubeId: 4 },
  { key: "cube4.desired_outcome.partial", englishDefault: "Partially Achieved", context: "Outcome status option", cubeId: 4 },
  { key: "cube4.desired_outcome.not_achieved", englishDefault: "Not Achieved", context: "Outcome status option", cubeId: 4 },
  { key: "cube4.results_log.title", englishDefault: "Results Log", context: "Outcome results heading", cubeId: 4 },
  { key: "cube4.results_log.sign_off", englishDefault: "Sign Off on Results", context: "Confirm results button", cubeId: 4 },
  { key: "cube4.results_log.all_confirmed", englishDefault: "All participants confirmed", context: "Full sign-off indicator", cubeId: 4 },
  { key: "cube4.presence.you_joined", englishDefault: "You're in the session", context: "Joined confirmation toast", cubeId: 4 },
  { key: "cube4.desired_outcome.description", englishDefault: "What do you want to achieve?", context: "Outcome description label", cubeId: 4 },
  { key: "cube4.desired_outcome.time_estimate", englishDefault: "Estimated time (minutes)", context: "Time estimate input label", cubeId: 4 },
  { key: "cube4.desired_outcome.waiting", englishDefault: "Waiting for all participants to confirm...", context: "Waiting for confirmations state", cubeId: 4 },
  { key: "cube4.desired_outcome.all_confirmed", englishDefault: "All participants confirmed — ready to start!", context: "Gate opened state", cubeId: 4 },
  { key: "cube4.results_log.prompt", englishDefault: "What was the outcome?", context: "Results log input label", cubeId: 4 },
  { key: "cube4.results_log.submit", englishDefault: "Submit results", context: "Submit results button", cubeId: 4 },
  { key: "cube4.collector.saving", englishDefault: "Saving responses...", context: "Write-in-progress indicator", cubeId: 4 },
  { key: "cube4.collector.saved", englishDefault: "All responses saved", context: "Save complete indicator", cubeId: 4 },
];

const cube5: TranslationEntry[] = [
  { key: "cube5.timer.active", englishDefault: "Timer active", context: "Active time tracking indicator", cubeId: 5 },
  { key: "cube5.timer.paused", englishDefault: "Timer paused", context: "Paused tracking indicator", cubeId: 5 },
  { key: "cube5.timer.elapsed", englishDefault: "Time elapsed:", context: "Duration label", cubeId: 5 },
  { key: "cube5.timer.tokens_accrued", englishDefault: "Tokens accrued:", context: "Running token count label", cubeId: 5 },
  { key: "cube5.pipeline.processing", englishDefault: "Processing responses...", context: "AI pipeline running indicator", cubeId: 5 },
  { key: "cube5.pipeline.complete", englishDefault: "Processing complete", context: "Pipeline done indicator", cubeId: 5 },
  { key: "cube5.pipeline.queued", englishDefault: "Queued for processing", context: "Back-pressure queue state", cubeId: 5 },
  { key: "cube5.gate.confirm_presence", englishDefault: "Confirm your presence", context: "M2/M3 confirmation gate", cubeId: 5 },
  { key: "cube5.gate.waiting_others", englishDefault: "Waiting for others to confirm...", context: "Gate waiting state", cubeId: 5 },
  { key: "cube5.gate.all_confirmed", englishDefault: "All confirmed — starting!", context: "Gate passed confirmation", cubeId: 5 },
  { key: "cube5.gate.assess_outcome", englishDefault: "Assess the outcome", context: "Post-task outcome prompt", cubeId: 5 },
  { key: "cube5.gate.sign_off", englishDefault: "Sign off", context: "Post-task sign-off button", cubeId: 5 },
];

const cube6: TranslationEntry[] = [
  { key: "cube6.themes.processing", englishDefault: "Generating themes...", context: "Theme pipeline running", cubeId: 6 },
  { key: "cube6.themes.theme1_ready", englishDefault: "Primary themes ready", context: "Theme1 lock notification", cubeId: 6 },
  { key: "cube6.themes.theme2_generating", englishDefault: "Generating sub-themes...", context: "Theme2 generation in progress", cubeId: 6 },
  { key: "cube6.themes.risk", englishDefault: "Risk & Concerns", context: "Theme1 category: Risk", cubeId: 6 },
  { key: "cube6.themes.supporting", englishDefault: "Supporting Comments", context: "Theme1 category: Supporting", cubeId: 6 },
  { key: "cube6.themes.neutral", englishDefault: "Neutral Comments", context: "Theme1 category: Neutral", cubeId: 6 },
  { key: "cube6.themes.confidence", englishDefault: "Confidence:", context: "Confidence percentage label", cubeId: 6 },
  { key: "cube6.themes.responses_in_theme", englishDefault: "responses in this theme", context: "Theme member count suffix", cubeId: 6 },
  { key: "cube6.themes.summary_33", englishDefault: "33-word summary", context: "Short summary label", cubeId: 6 },
  { key: "cube6.themes.summary_111", englishDefault: "111-word summary", context: "Medium summary label", cubeId: 6 },
  { key: "cube6.themes.summary_333", englishDefault: "333-word summary", context: "Long summary label", cubeId: 6 },
  { key: "cube6.themes.cqs_label", englishDefault: "Contribution Quality Score", context: "CQS section heading", cubeId: 6 },
  { key: "cube6.themes.ready_badge", englishDefault: "{count} themes ready", context: "Badge shown when theming pipeline completes (count is dynamic)", cubeId: 6 },
  { key: "cube6.themes.progressive_reveal", englishDefault: "Revealing themes...", context: "Progressive reveal animation label", cubeId: 6 },
  { key: "cube6.themes.vote_level", englishDefault: "Voting level:", context: "Theme2 voting level label (9/6/3)", cubeId: 6 },
  { key: "cube6.themes.marble_sampling", englishDefault: "Sampling responses...", context: "Marble Method sampling phase", cubeId: 6 },
  { key: "cube6.themes.reducing", englishDefault: "Consolidating themes...", context: "Theme reduction phase (all→9→6→3)", cubeId: 6 },
  { key: "cube6.themes.assigning", englishDefault: "Assigning themes to responses...", context: "Theme assignment phase", cubeId: 6 },
  { key: "cube6.themes.pipeline_complete", englishDefault: "Theme analysis complete!", context: "Pipeline success notification", cubeId: 6 },
  { key: "cube6.themes.pipeline_error", englishDefault: "Theme analysis encountered an error", context: "Pipeline failure notification", cubeId: 6 },
  { key: "cube6.themes.scale_sampling", englishDefault: "Sampling {count} of {total} responses", context: "Scale pipeline sampling status", cubeId: 6 },
  { key: "cube6.themes.theme_library", englishDefault: "{count} candidate themes discovered", context: "Theme library size before reduction", cubeId: 6 },
];

const cube7: TranslationEntry[] = [
  { key: "cube7.ranking.title", englishDefault: "Rank the Themes", context: "Ranking page heading", cubeId: 7 },
  { key: "cube7.ranking.instructions", englishDefault: "Drag to reorder themes by priority", context: "Ranking instructions", cubeId: 7 },
  { key: "cube7.ranking.submit", englishDefault: "Submit Ranking", context: "Submit ranking button", cubeId: 7 },
  { key: "cube7.ranking.submitted", englishDefault: "Ranking submitted!", context: "Success confirmation", cubeId: 7 },
  { key: "cube7.ranking.waiting_results", englishDefault: "Waiting for final results...", context: "Post-submit waiting state", cubeId: 7 },
  { key: "cube7.ranking.live_results", englishDefault: "Live Results", context: "Live aggregation heading", cubeId: 7 },
  { key: "cube7.ranking.final_results", englishDefault: "Final Results", context: "Final results heading", cubeId: 7 },
  { key: "cube7.ranking.rank", englishDefault: "Rank", context: "Rank column header", cubeId: 7 },
  { key: "cube7.ranking.theme", englishDefault: "Theme", context: "Theme column header", cubeId: 7 },
  { key: "cube7.ranking.votes", englishDefault: "Votes", context: "Vote count column header", cubeId: 7 },
  { key: "cube7.ranking.governance_weight", englishDefault: "Governance Weight", context: "Weighted score column header", cubeId: 7 },
  { key: "cube7.ranking.your_rank", englishDefault: "Your ranking:", context: "User's own ranking label", cubeId: 7 },
  { key: "cube7.ranking.tap_instructions", englishDefault: "Tap to select your ranking order", context: "Mobile touch instructions", cubeId: 7 },
  { key: "cube7.ranking.waiting", englishDefault: "Waiting for others to rank...", context: "Waiting state while others complete", cubeId: 7 },
  { key: "cube7.ranking.results_title", englishDefault: "Ranked Priorities", context: "Results header after aggregation", cubeId: 7 },
  { key: "cube7.ranking.rank_label", englishDefault: "#{rank}", context: "Rank position display", cubeId: 7 },
  { key: "cube7.ranking.score", englishDefault: "Score: {score}", context: "Aggregated score display", cubeId: 7 },
  { key: "cube7.ranking.top_theme", englishDefault: "Top Priority", context: "Badge for #1 theme", cubeId: 7 },
  { key: "cube7.ranking.override_applied", englishDefault: "Ranking adjusted by Lead", context: "Override notice (MVP3)", cubeId: 7 },
  { key: "cube7.ranking.override_justification", englishDefault: "Reason: {text}", context: "Override justification display", cubeId: 7 },
  { key: "cube7.ranking.no_rankings_yet", englishDefault: "No rankings submitted yet", context: "Empty state", cubeId: 7 },
  { key: "cube7.ranking.themes_generating", englishDefault: "Generating themes...", context: "Progressive theme reveal loading", cubeId: 7 },
  { key: "cube7.ranking.theme_revealed", englishDefault: "New theme discovered!", context: "Progressive reveal notification", cubeId: 7 },
  { key: "cube7.ranking.voting_opens_soon", englishDefault: "Voting opens when all themes are ready", context: "Pre-voting state", cubeId: 7 },
  { key: "cube7.ranking.winner", englishDefault: "#1 Theme", context: "Winning theme badge", cubeId: 7 },
  { key: "cube7.ranking.reward_eligible", englishDefault: "Eligible for reward!", context: "CQS reward eligibility notice", cubeId: 7 },
  { key: "cube7.ranking.progressive_reveal", englishDefault: "Results revealing...", context: "Progressive reveal label (paid tiers)", cubeId: 7 },
  { key: "cube7.ranking.level_9", englishDefault: "9-theme level", context: "Theme2 voting level label", cubeId: 7 },
  { key: "cube7.ranking.level_6", englishDefault: "6-theme level", context: "Theme2 voting level label", cubeId: 7 },
  { key: "cube7.ranking.drag_hint", englishDefault: "Hold and drag to reorder", context: "DnD ranking instruction hint", cubeId: 7 },
  { key: "cube7.ranking.confirm_order", englishDefault: "Confirm Rankings", context: "Submit button after drag-to-rank", cubeId: 7 },
];

const cube8: TranslationEntry[] = [
  { key: "cube8.tokens.balance", englishDefault: "Token Balance", context: "Balance heading", cubeId: 8 },
  { key: "cube8.tokens.heart_total", englishDefault: "Total ♡", context: "♡ total label", cubeId: 8 },
  { key: "cube8.tokens.unity_total", englishDefault: "Total ◬", context: "◬ total label", cubeId: 8 },
  { key: "cube8.tokens.human_total", englishDefault: "Total 웃", context: "웃 total label", cubeId: 8 },
  { key: "cube8.tokens.ledger", englishDefault: "Token Ledger", context: "Ledger view heading", cubeId: 8 },
  { key: "cube8.tokens.pending", englishDefault: "Pending", context: "Lifecycle state label", cubeId: 8 },
  { key: "cube8.tokens.approved", englishDefault: "Approved", context: "Lifecycle state label", cubeId: 8 },
  { key: "cube8.tokens.finalized", englishDefault: "Finalized", context: "Lifecycle state label", cubeId: 8 },
  { key: "cube8.payment.processing", englishDefault: "Processing payment...", context: "Payment in progress", cubeId: 8 },
  { key: "cube8.payment.success", englishDefault: "Payment successful!", context: "Payment confirmation", cubeId: 8 },
  { key: "cube8.payment.failed", englishDefault: "Payment failed — please try again", context: "Payment error", cubeId: 8 },
  { key: "cube8.payment.stripe", englishDefault: "Pay with Card", context: "Stripe payment label", cubeId: 8 },
  { key: "cube8.payment.google_pay", englishDefault: "Google Pay", context: "GPay label", cubeId: 8 },
  { key: "cube8.payment.apple_pay", englishDefault: "Apple Pay", context: "Apple Pay label", cubeId: 8 },
  { key: "cube8.dispute.title", englishDefault: "Dispute Token", context: "Dispute form heading", cubeId: 8 },
  { key: "cube8.dispute.reason", englishDefault: "Reason for dispute", context: "Dispute reason input label", cubeId: 8 },
  { key: "cube8.dispute.submit", englishDefault: "Submit Dispute", context: "Dispute submit button", cubeId: 8 },
  // Donation (post-results)
  { key: "cube8.donation.support_this_session", englishDefault: "Support This Session", context: "Donation prompt heading", cubeId: 8 },
  { key: "cube8.donation.results_ready", englishDefault: "Your results are ready! If this session was valuable, consider a donation to support the platform.", context: "Donation prompt description", cubeId: 8 },
  { key: "cube8.donation.donate_button", englishDefault: "Donate", context: "Donation submit button prefix", cubeId: 8 },
  { key: "cube8.donation.maybe_later", englishDefault: "Maybe Later", context: "Donation dismiss button", cubeId: 8 },
  { key: "cube8.donation.complete", englishDefault: "Complete Your Donation", context: "Stripe payment form heading", cubeId: 8 },
  { key: "cube8.donation.minimum", englishDefault: "Minimum donation is $0.50", context: "Validation message", cubeId: 8 },
  { key: "cube8.donation.estimated_cost", englishDefault: "Estimated session cost", context: "Cost estimate prefix", cubeId: 8 },
  { key: "cube8.donation.thank_you", englishDefault: "Thank you!", context: "Donation success toast title", cubeId: 8 },
  { key: "cube8.donation.thank_you_desc", englishDefault: "Your donation supports the platform.", context: "Donation success toast description", cubeId: 8 },
  // Payment (Cube 8)
  { key: "cube8.payment.session_payment", englishDefault: "Session Payment", context: "Moderator checkout heading", cubeId: 8 },
  { key: "cube8.payment.minimum_fee_desc", englishDefault: "Minimum $11.11 USD to create this session. Your participants join free.", context: "Moderator checkout description", cubeId: 8 },
  { key: "cube8.payment.redirecting", englishDefault: "Redirecting...", context: "Payment redirect loading", cubeId: 8 },
  { key: "cube8.payment.loading", englishDefault: "Loading payment...", context: "Payment loading state", cubeId: 8 },
  { key: "cube8.payment.moderator_share", englishDefault: "Moderator Share (50%)", context: "Cost split moderator label", cubeId: 8 },
  { key: "cube8.payment.your_share", englishDefault: "Your Share", context: "Cost split participant label", cubeId: 8 },
  { key: "cube8.payment.participant_share", englishDefault: "Your share: 50% / {count} users", context: "Cost split per-user", cubeId: 8 },
  { key: "cube8.payment.setup_failed", englishDefault: "Payment setup failed", context: "Payment error toast", cubeId: 8 },
  // Pricing tier (Cube 8)
  { key: "cube8.pricing.tier_label", englishDefault: "Pricing Tier", context: "Pricing selector label", cubeId: 8 },
  { key: "cube8.pricing.free", englishDefault: "Free", context: "Free tier name", cubeId: 8 },
  { key: "cube8.pricing.free_desc", englishDefault: "Up to 19 participants", context: "Free tier description", cubeId: 8 },
  { key: "cube8.pricing.free_detail", englishDefault: "Donation prompt after results", context: "Free tier detail", cubeId: 8 },
  { key: "cube8.pricing.moderator_paid", englishDefault: "Moderator Paid", context: "Paid tier name", cubeId: 8 },
  { key: "cube8.pricing.unlimited_desc", englishDefault: "Unlimited participants", context: "Paid tier description", cubeId: 8 },
  { key: "cube8.pricing.moderator_detail", englishDefault: "You pay upfront, participants join free", context: "Paid tier detail", cubeId: 8 },
  { key: "cube8.pricing.cost_split", englishDefault: "Cost Split", context: "Split tier name", cubeId: 8 },
  { key: "cube8.pricing.cost_split_detail", englishDefault: "50% you + 50% split among users", context: "Split tier detail", cubeId: 8 },
  { key: "cube8.pricing.amount_label", englishDefault: "Amount: $", context: "Custom amount input label", cubeId: 8 },
  { key: "cube8.pricing.minimum_note", englishDefault: "(min $11.11)", context: "Minimum fee note", cubeId: 8 },
  // Cube 8 — Lifecycle & Dispute Resolution (SPIRAL v2)
  { key: "cube8.lifecycle.simulated", englishDefault: "Simulated", context: "Lifecycle state label", cubeId: 8 },
  { key: "cube8.lifecycle.reversed", englishDefault: "Reversed", context: "Lifecycle state label", cubeId: 8 },
  { key: "cube8.lifecycle.transition_success", englishDefault: "State updated", context: "Lifecycle transition toast", cubeId: 8 },
  { key: "cube8.lifecycle.transition_blocked", englishDefault: "This transition is not allowed", context: "409 error message", cubeId: 8 },
  { key: "cube8.dispute.resolved", englishDefault: "Dispute Resolved", context: "Dispute resolution heading", cubeId: 8 },
  { key: "cube8.dispute.rejected", englishDefault: "Dispute Rejected", context: "Dispute rejection heading", cubeId: 8 },
  { key: "cube8.dispute.resolution_notes", englishDefault: "Resolution Notes", context: "Admin resolution notes label", cubeId: 8 },
  { key: "cube8.dispute.status_open", englishDefault: "Open", context: "Dispute status badge", cubeId: 8 },
  { key: "cube8.tokens.reward_winner", englishDefault: "CQS Reward Winner!", context: "CQS reward notification", cubeId: 8 },
  { key: "cube8.tokens.summary", englishDefault: "Token Summary", context: "Moderator token summary heading", cubeId: 8 },
  // Cube 9 — Analytics & Dashboard (SPIRAL v2)
  { key: "cube9.analytics.title", englishDefault: "Session Analytics", context: "Analytics dashboard heading", cubeId: 9 },
  { key: "cube9.analytics.participation", englishDefault: "Participation Rate", context: "Analytics metric label", cubeId: 9 },
  { key: "cube9.analytics.summary_coverage", englishDefault: "Summary Coverage", context: "Analytics metric label", cubeId: 9 },
  { key: "cube9.analytics.theme_distribution", englishDefault: "Theme Distribution", context: "Analytics chart heading", cubeId: 9 },
  { key: "cube9.ranking_summary.title", englishDefault: "Ranking Summary", context: "Ranking results heading", cubeId: 9 },
  { key: "cube9.ranking_summary.algorithm", englishDefault: "Algorithm", context: "Ranking algorithm label", cubeId: 9 },
  { key: "cube9.ranking_summary.participants", englishDefault: "Participants", context: "Participant count label", cubeId: 9 },
  { key: "cube9.cqs.title", englishDefault: "CQS Scoring Dashboard", context: "CQS dashboard heading", cubeId: 9 },
  { key: "cube9.cqs.winner", englishDefault: "CQS Winner", context: "Winner section heading", cubeId: 9 },
  { key: "cube9.cqs.composite_score", englishDefault: "Composite Score", context: "CQS score label", cubeId: 9 },
  { key: "cube9.destroy.title", englishDefault: "Destroy Session Data", context: "Data destruction heading", cubeId: 9 },
  { key: "cube9.destroy.warning", englishDefault: "This action is IRREVERSIBLE. All response text and summaries will be permanently deleted.", context: "Destruction warning", cubeId: 9 },
  { key: "cube9.destroy.confirm", englishDefault: "I understand — destroy data", context: "Destruction confirm button", cubeId: 9 },
  // SDK / API (SPIRAL v2)
  { key: "sdk.api_key.title", englishDefault: "API & SDK", context: "SDK settings panel heading", cubeId: 0 },
  { key: "sdk.api_key.generate", englishDefault: "Generate API Key", context: "API key generation button", cubeId: 0 },
  { key: "sdk.api_key.copy", englishDefault: "Copy Key", context: "Copy API key button", cubeId: 0 },
  { key: "sdk.api_key.revoke", englishDefault: "Revoke Key", context: "Revoke API key button", cubeId: 0 },
  { key: "sdk.embed.title", englishDefault: "Embed Code", context: "Embed configuration heading", cubeId: 0 },
  { key: "sdk.embed.iframe", englishDefault: "iframe Embed", context: "iframe embed option", cubeId: 0 },
  { key: "sdk.embed.headless", englishDefault: "Headless API", context: "Headless API option", cubeId: 0 },
  { key: "sdk.usage.title", englishDefault: "API Usage", context: "Usage metrics heading", cubeId: 0 },
  { key: "sdk.usage.total_calls", englishDefault: "Total API Calls", context: "Usage metric label", cubeId: 0 },
  // Dashboard toasts & UI labels
  { key: "cube1.moderator.code_copied", englishDefault: "Code copied", context: "Toast after copying join code", cubeId: 1 },
  { key: "cube1.moderator.link_copied", englishDefault: "Join link copied", context: "Toast after copying join URL", cubeId: 1 },
  { key: "cube1.moderator.action_failed", englishDefault: "Action failed", context: "Generic action error toast", cubeId: 1 },
  { key: "cube1.moderator.session_created", englishDefault: "Session created", context: "Session creation success toast", cubeId: 1 },
  { key: "cube1.moderator.session_ready", englishDefault: "is ready", context: "Session ready suffix", cubeId: 1 },
  { key: "cube1.moderator.demo_reset", englishDefault: "Demo reset", context: "Demo reset success toast", cubeId: 1 },
  { key: "cube1.moderator.session_deleted", englishDefault: "Session deleted permanently", context: "Delete success toast", cubeId: 1 },
  { key: "cube1.moderator.delete_failed", englishDefault: "Delete failed", context: "Delete error toast", cubeId: 1 },
  { key: "cube1.moderator.switch_to_summary", englishDefault: "Switch to 33-word summary", context: "Feed toggle tooltip", cubeId: 1 },
  { key: "cube1.moderator.switch_to_raw", englishDefault: "Switch to raw feedback", context: "Feed toggle tooltip", cubeId: 1 },
  { key: "cube1.moderator.raw_mode", englishDefault: "Raw", context: "Feed display mode button", cubeId: 1 },
  { key: "cube1.moderator.summary_mode", englishDefault: "Summary", context: "Feed display mode button", cubeId: 1 },
  // Shared navigation/UI
  { key: "shared.nav.collapse", englishDefault: "Collapse", context: "Collapsible section toggle", cubeId: 0 },
  { key: "shared.nav.expand", englishDefault: "Expand", context: "Collapsible section toggle", cubeId: 0 },
  { key: "shared.nav.fullscreen", englishDefault: "Fullscreen", context: "Fullscreen button tooltip", cubeId: 0 },
  { key: "shared.nav.cancel", englishDefault: "Cancel", context: "Cancel button", cubeId: 0 },
  { key: "shared.currency.usd", englishDefault: "USD", context: "Currency code label", cubeId: 0 },
  // Cube status labels
  { key: "cube1.settings.status_deployed", englishDefault: "Deployed", context: "Cube architecture status", cubeId: 1 },
  { key: "cube1.settings.status_in_progress", englishDefault: "In Progress", context: "Cube architecture status", cubeId: 1 },
  { key: "cube1.settings.status_not_started", englishDefault: "Not Started", context: "Cube architecture status", cubeId: 1 },
  { key: "cube1.settings.status_planned", englishDefault: "Planned", context: "Cube architecture status", cubeId: 1 },
  // Simulation labels
  { key: "cube10.sim.status_draft", englishDefault: "Draft", context: "SIM state label", cubeId: 10 },
  { key: "cube10.sim.status_open", englishDefault: "Open", context: "SIM state label", cubeId: 10 },
  { key: "cube10.sim.status_polling", englishDefault: "Polling", context: "SIM state label", cubeId: 10 },
  { key: "cube10.sim.status_closed", englishDefault: "Closed", context: "SIM state label", cubeId: 10 },
  { key: "cube10.sim.status_theming", englishDefault: "AI Theming", context: "SIM state label", cubeId: 10 },
  { key: "cube10.sim.status_visuals", englishDefault: "Theme Visuals", context: "SIM state label", cubeId: 10 },
  { key: "cube10.sim.status_ranking", englishDefault: "Ranking", context: "SIM state label", cubeId: 10 },
  { key: "cube10.sim.status_archived", englishDefault: "Archived", context: "SIM state label", cubeId: 10 },
  { key: "cube10.sim.mode_live", englishDefault: "LIVE", context: "Session mode badge", cubeId: 10 },
  { key: "cube10.sim.mode_static", englishDefault: "STATIC", context: "Session mode badge", cubeId: 10 },
];

const cube9: TranslationEntry[] = [
  { key: "cube9.export.csv", englishDefault: "Export CSV", context: "CSV export button", cubeId: 9 },
  { key: "cube9.export.pdf", englishDefault: "Export PDF", context: "PDF export button", cubeId: 9 },
  { key: "cube9.export.generating", englishDefault: "Generating export...", context: "Export in progress", cubeId: 9 },
  { key: "cube9.export.ready", englishDefault: "Export ready — click to download", context: "Export complete", cubeId: 9 },
  { key: "cube9.pixelated.title", englishDefault: "Pixelated Token", context: "Token image heading", cubeId: 9 },
  { key: "cube9.pixelated.download", englishDefault: "Download Token Image", context: "Download button", cubeId: 9 },
  { key: "cube9.pixelated.send_sms", englishDefault: "Send via SMS", context: "SMS delivery button", cubeId: 9 },
  { key: "cube9.pixelated.send_email", englishDefault: "Send via Email", context: "Email delivery button", cubeId: 9 },
  { key: "cube9.pixelated.delivered", englishDefault: "Token delivered!", context: "Delivery confirmation", cubeId: 9 },
  { key: "cube9.pixelated.data_destroyed", englishDefault: "Your token data has been removed from our servers.", context: "Post-delivery data destruction notice", cubeId: 9 },
  { key: "cube9.results.title", englishDefault: "Session Results", context: "Results page heading", cubeId: 9 },
  { key: "cube9.results.distribution", englishDefault: "Distributing results...", context: "Results distribution in progress", cubeId: 9 },
  { key: "cube9.results.sent", englishDefault: "Results sent!", context: "Distribution complete", cubeId: 9 },
  { key: "cube9.results.cqs_dashboard", englishDefault: "CQS Dashboard", context: "CQS analytics heading", cubeId: 9 },
  { key: "cube9.results.talent_recommendations", englishDefault: "Talent Recommendations", context: "Talent section heading", cubeId: 9 },
  { key: "cube9.results.reward_announcement", englishDefault: "Reward Winner", context: "Reward announcement heading", cubeId: 9 },
  { key: "cube9.results.reward_winner", englishDefault: "Congratulations!", context: "Winner notification", cubeId: 9 },
  { key: "cube9.results.lead_access", englishDefault: "Lead access — results included", context: "Lead/Dev free access notice", cubeId: 9 },
  { key: "cube9.results.feedback_prompt", englishDefault: "How was your experience?", context: "Post-session feedback prompt", cubeId: 9 },
  { key: "cube9.results.risk_label", englishDefault: "Where people are most concerned", context: "Risk partition legend label in results chart", cubeId: 9 },
  { key: "cube9.results.support_label", englishDefault: "#1 item to get right", context: "Supporting partition legend label in results chart", cubeId: 9 },
  { key: "cube9.results.neutral_label", englishDefault: "Balanced perspectives", context: "Neutral partition legend label in results chart", cubeId: 9 },
  { key: "cube9.results.response_distribution", englishDefault: "Response Distribution", context: "Results bar chart heading", cubeId: 9 },
];

const cube10: TranslationEntry[] = [
  { key: "cube10.sim.title", englishDefault: "Simulation", context: "Simulation page heading", cubeId: 10 },
  { key: "cube10.sim.new_run", englishDefault: "New Simulation Run", context: "Start simulation button", cubeId: 10 },
  { key: "cube10.sim.replay", englishDefault: "Replay Session", context: "Replay button", cubeId: 10 },
  { key: "cube10.sim.compare", englishDefault: "Compare Metrics", context: "Comparison view button", cubeId: 10 },
  { key: "cube10.sim.running", englishDefault: "Simulation running...", context: "In-progress indicator", cubeId: 10 },
  { key: "cube10.sim.complete", englishDefault: "Simulation complete", context: "Done indicator", cubeId: 10 },
  { key: "cube10.sim.pass", englishDefault: "PASS — exceeds production metrics", context: "Simulation pass result", cubeId: 10 },
  { key: "cube10.sim.fail", englishDefault: "FAIL — does not exceed production metrics", context: "Simulation fail result", cubeId: 10 },
  { key: "cube10.sim.version", englishDefault: "Cube Version:", context: "Version label", cubeId: 10 },
  { key: "cube10.sim.rollback", englishDefault: "Rollback to previous version", context: "Rollback button", cubeId: 10 },
  { key: "cube10.sim.editor_title", englishDefault: "Code Editor", context: "In-browser editor heading", cubeId: 10 },
  { key: "cube10.sim.editor_run", englishDefault: "Run", context: "Editor run button", cubeId: 10 },
  { key: "cube10.sim.editor_save", englishDefault: "Save", context: "Editor save button", cubeId: 10 },
  { key: "cube10.sim.metric_system", englishDefault: "System Metrics", context: "System metric category", cubeId: 10 },
  { key: "cube10.sim.metric_user", englishDefault: "User Metrics", context: "User metric category", cubeId: 10 },
  { key: "cube10.sim.metric_outcome", englishDefault: "Outcome Metrics", context: "Outcome metric category", cubeId: 10 },
  { key: "cube10.sim.dataset", englishDefault: "Replay Dataset", context: "Dataset selector label", cubeId: 10 },
  { key: "cube10.feedback.title", englishDefault: "Improvement Feedback", context: "Feedback section heading", cubeId: 10 },
  { key: "cube10.feedback.system_prompt", englishDefault: "How can we improve this cube?", context: "System-prompted feedback", cubeId: 10 },
  { key: "cube10.feedback.submit", englishDefault: "Submit Improvement", context: "Submit button", cubeId: 10 },
  { key: "cube10.feedback.backlog", englishDefault: "View Backlog", context: "Backlog view link", cubeId: 10 },
  // Cube 10 — Code Submission + Voting + Deployment (Self-Evolving Platform)
  { key: "cube10.submit.title", englishDefault: "Improve This Cube", context: "Code submission heading", cubeId: 10 },
  { key: "cube10.submit.ai_or_human", englishDefault: "AI or Human submission?", context: "Submitter type selector", cubeId: 10 },
  { key: "cube10.submit.function_target", englishDefault: "Target Function", context: "Function to improve selector", cubeId: 10 },
  { key: "cube10.submit.upload_diff", englishDefault: "Upload Code Changes", context: "Code diff upload area", cubeId: 10 },
  { key: "cube10.submit.testing", englishDefault: "Running sandbox tests...", context: "Test execution progress", cubeId: 10 },
  { key: "cube10.submit.tests_passed", englishDefault: "All tests passed!", context: "Test success notification", cubeId: 10 },
  { key: "cube10.submit.tests_failed", englishDefault: "Tests failed — submission rejected", context: "Test failure notification", cubeId: 10 },
  { key: "cube10.vote.title", englishDefault: "Community Vote", context: "Voting phase heading", cubeId: 10 },
  { key: "cube10.vote.compare", englishDefault: "Compare: Current vs Proposed", context: "Side-by-side metrics view", cubeId: 10 },
  { key: "cube10.vote.approve", englishDefault: "Approve This Change", context: "Approve vote button", cubeId: 10 },
  { key: "cube10.vote.reject", englishDefault: "Reject This Change", context: "Reject vote button", cubeId: 10 },
  { key: "cube10.vote.supermajority", englishDefault: "66.6% supermajority required", context: "Threshold indicator", cubeId: 10 },
  { key: "cube10.vote.quorum", englishDefault: "10% quorum required", context: "Quorum indicator", cubeId: 10 },
  { key: "cube10.vote.approved", englishDefault: "Community approved! Awaiting admin deployment.", context: "Vote success", cubeId: 10 },
  { key: "cube10.vote.rejected", englishDefault: "Community rejected this change.", context: "Vote rejection", cubeId: 10 },
  { key: "cube10.deploy.title", englishDefault: "Deploy Update", context: "Admin deployment heading", cubeId: 10 },
  { key: "cube10.deploy.hot_swap", englishDefault: "Hot-swap into live system", context: "Deploy action button", cubeId: 10 },
  { key: "cube10.deploy.rollback", englishDefault: "Rollback to previous version", context: "Revert action button", cubeId: 10 },
  { key: "cube10.deploy.success", englishDefault: "Update deployed successfully!", context: "Deployment confirmation", cubeId: 10 },
  { key: "cube10.deploy.reverted", englishDefault: "Reverted to previous version.", context: "Rollback confirmation", cubeId: 10 },
  { key: "cube10.vision.tagline", englishDefault: "Where Shared Intention moves at the Speed of Thought", context: "SoI Trinity vision statement", cubeId: 10 },
  { key: "cube10.vision.ai_competes", englishDefault: "AI and humans compete to build the future", context: "AI vs HI competition description", cubeId: 10 },
  { key: "cube10.vision.community_decides", englishDefault: "The community decides what ships", context: "Governance description", cubeId: 10 },
  // Cube 10 — Admin Access (H.I.→A.I.→S.I. + code)
  { key: "cube10.admin.enter_code", englishDefault: "Enter Admin Access Code", context: "Admin code popup heading", cubeId: 10 },
  { key: "cube10.admin.code_placeholder", englishDefault: "8-digit code", context: "Admin code input placeholder", cubeId: 10 },
  { key: "cube10.admin.welcome", englishDefault: "Admin Access Granted", context: "Admin unlock success", cubeId: 10 },
  { key: "cube10.admin.deploy_panel", englishDefault: "Deployment Control Panel", context: "Admin deployment view heading", cubeId: 10 },
  { key: "cube10.admin.wrong_code", englishDefault: "Invalid code — access denied", context: "Wrong admin code", cubeId: 10 },
  // Cube 10 — Challenger Access (S.I.→A.I.→H.I. + code)
  { key: "cube10.challenger.enter_code", englishDefault: "Enter Challenger Code", context: "Challenger code popup heading", cubeId: 10 },
  { key: "cube10.challenger.code_placeholder", englishDefault: "6-digit code", context: "Challenger code input placeholder", cubeId: 10 },
  { key: "cube10.challenger.welcome", englishDefault: "Challenge Accepted!", context: "Challenger unlock success", cubeId: 10 },
  { key: "cube10.challenger.arena", englishDefault: "Code Challenge Arena", context: "Challenger competition view heading", cubeId: 10 },
  { key: "cube10.challenger.ai_vs_hi", englishDefault: "AI vs Human — may the best code win", context: "Competition tagline", cubeId: 10 },
  { key: "cube10.challenger.wrong_code", englishDefault: "Invalid code — try again", context: "Wrong challenger code", cubeId: 10 },
  // Cube 10 — 2525 Vision (Challenger Inspiration)
  { key: "cube10.vision.2525_intro", englishDefault: "The next 500 years begin with your contribution", context: "Challenger welcome vision", cubeId: 10 },
  { key: "cube10.vision.civilizational", englishDefault: "Every line of code is an act of civilizational architecture", context: "Challenger motivation", cubeId: 10 },
  { key: "cube10.vision.me_decree", englishDefault: "ME — Sacred decree becomes governance protocol", context: "Ancient→modern translation", cubeId: 10 },
  { key: "cube10.vision.maat_balance", englishDefault: "Ma'at — Living balance becomes SSSES verification", context: "Ancient→modern translation", cubeId: 10 },
  { key: "cube10.vision.tri_council", englishDefault: "◬ Precision at Scale · ♡ Governance by Community · 웃 Empathy & Wisdom", context: "Tri-Council of Intelligences", cubeId: 10 },
  { key: "cube10.vision.stewardship", englishDefault: "Your code carries conscience — what you automate reflects who you are", context: "Challenger oath", cubeId: 10 },
  { key: "cube10.vision.augmented", englishDefault: "If responsibility grows alongside amplification, we inaugurate an Augmented Civilization", context: "2525 vision statement", cubeId: 10 },
  { key: "cube10.vision.infinity_model", englishDefault: "Structure and spirit in continuous reciprocity — the Infinity Model", context: "Outer arc + inner arc", cubeId: 10 },
  { key: "cube10.sim.role_moderator", englishDefault: "Moderator Experience", context: "Sim role label for moderator preview", cubeId: 10 },
  { key: "cube10.sim.role_poller", englishDefault: "Participant Experience", context: "Sim role label for participant preview", cubeId: 10 },
  { key: "cube10.sim.live_poll", englishDefault: "Live Poll", context: "Live interactive poll type label", cubeId: 10 },
  { key: "cube10.sim.static_poll", englishDefault: "Static Poll", context: "Static poll type label", cubeId: 10 },
  { key: "cube10.sim.sim_type", englishDefault: "Simulation Type", context: "Sim type selector heading", cubeId: 10 },
  { key: "cube10.sim.auto_advancing", englishDefault: "Auto-advancing...", context: "Auto-advance status indicator", cubeId: 10 },
  { key: "cube10.sim.participants_joining", englishDefault: "Participants joining...", context: "Sim participant counter label", cubeId: 10 },
  { key: "cube10.sim.create_session", englishDefault: "Create Session", context: "Sim create session button", cubeId: 10 },
  { key: "cube10.sim.select_session", englishDefault: "Select a Session", context: "Session picker heading", cubeId: 10 },
  { key: "cube10.sim.select_session_desc", englishDefault: "Choose a session to simulate", context: "Session picker description", cubeId: 10 },
  { key: "cube10.sim.transport_step", englishDefault: "Step", context: "Transport step counter label", cubeId: 10 },
  { key: "cube10.sim.state_theming", englishDefault: "AI Theming", context: "Theming phase label", cubeId: 10 },
  { key: "cube10.sim.state_visuals", englishDefault: "Theme Visuals", context: "Visuals phase label", cubeId: 10 },
  { key: "cube10.sim.state_closed", englishDefault: "Session Closed", context: "Closed phase label", cubeId: 10 },
  { key: "cube10.sim.session_closed_msg", englishDefault: "Preparing AI theming...", context: "Closed state description", cubeId: 10 },
  { key: "cube10.sim.translate_question", englishDefault: "Translate to my language", context: "Question translate button tooltip", cubeId: 10 },
  { key: "cube10.sim.translated", englishDefault: "Translated", context: "Translate button label when active", cubeId: 10 },
  { key: "cube10.sim.original", englishDefault: "Original", context: "Translate button label when inactive", cubeId: 10 },
  { key: "cube10.sim.create_new", englishDefault: "Create New", context: "Create new session button in picker", cubeId: 10 },
  { key: "cube10.sim.jump_to_start", englishDefault: "Jump to start", context: "Transport skip-back button tooltip", cubeId: 10 },
  // SIM flow optimization keys (2026-02-25)
  { key: "cube10.sim.rank_themes", englishDefault: "Rank These Themes", context: "Ranking UI heading", cubeId: 10 },
  { key: "cube10.sim.rank_instruction", englishDefault: "Tap themes in order of priority (1st = most important)", context: "Ranking UI instruction", cubeId: 10 },
  { key: "cube10.sim.theming_complete", englishDefault: "Cube 6 AI Theming Complete", context: "Theming analysis banner", cubeId: 10 },
  { key: "cube10.sim.responses_to_themes", englishDefault: "{0} responses → {1} themes identified", context: "Theming summary with placeholders", cubeId: 10 },
  { key: "cube10.sim.rankings_submitted", englishDefault: "Rankings submitted!", context: "Ranking confirmation message", cubeId: 10 },
  { key: "cube10.sim.session_complete", englishDefault: "Session Complete", context: "Session complete heading", cubeId: 10 },
  { key: "cube10.sim.results_summary", englishDefault: "Session Results", context: "Results phase heading", cubeId: 10 },
  { key: "cube10.sim.response_submitted", englishDefault: "Response submitted", context: "Toast after response submit", cubeId: 10 },
  { key: "cube10.sim.themes_ready", englishDefault: "Themes identified — Ranking ready!", context: "Toast when themes are ready", cubeId: 10 },
  { key: "cube10.sim.ranked_by_priority", englishDefault: "Ranked by priority", context: "Read-only ranking label in poller SIM", cubeId: 10 },
  { key: "cube10.sim.themes_identified", englishDefault: "themes", context: "Theme count suffix", cubeId: 10 },
  { key: "cube10.sim.responses_count", englishDefault: "responses", context: "Response count suffix", cubeId: 10 },
  { key: "cube10.sim.confidence", englishDefault: "confidence", context: "Confidence percentage suffix", cubeId: 10 },
  { key: "cube10.sim.sim_results_desc", englishDefault: "AI theming and ranking complete", context: "Results phase description", cubeId: 10 },
  { key: "cube10.sim.clustering_responses", englishDefault: "Clustering {0} responses into themes", context: "Theming progress with placeholder", cubeId: 10 },
  { key: "cube10.sim.final_stats", englishDefault: "{0} responses · {1} themes · Rankings submitted", context: "Final stats summary with placeholders", cubeId: 10 },
  { key: "cube10.sim.return_to_polls", englishDefault: "Return to Polls", context: "Back to session picker button", cubeId: 10 },
  { key: "cube10.sim.rank_number", englishDefault: "#{0}", context: "Rank badge with placeholder", cubeId: 10 },
];

// ─── Aggregated cube groups ──────────────────────────────────────

export const CUBE_GROUPS: CubeGroup[] = [
  { cubeId: 0, label: "Shared", keys: shared },
  { cubeId: 1, label: "Cube 1 — Session", keys: cube1 },
  { cubeId: 2, label: "Cube 2 — Text", keys: cube2 },
  { cubeId: 3, label: "Cube 3 — Voice", keys: cube3 },
  { cubeId: 4, label: "Cube 4 — Collector", keys: cube4 },
  { cubeId: 5, label: "Cube 5 — Gateway", keys: cube5 },
  { cubeId: 6, label: "Cube 6 — AI Theming", keys: cube6 },
  { cubeId: 7, label: "Cube 7 — Ranking", keys: cube7 },
  { cubeId: 8, label: "Cube 8 — Tokens", keys: cube8 },
  { cubeId: 9, label: "Cube 9 — Reports", keys: cube9 },
  { cubeId: 10, label: "Cube 10 — Simulation", keys: cube10 },
];

/** Flat lookup: key → TranslationEntry (for English defaults + context) */
export const DEFAULT_ENGLISH_TRANSLATIONS: Record<string, TranslationEntry> =
  Object.fromEntries(
    CUBE_GROUPS.flatMap((g) => g.keys).map((entry) => [entry.key, entry])
  );

/** All translation keys as a flat array */
export const ALL_KEYS: string[] = CUBE_GROUPS.flatMap((g) =>
  g.keys.map((k) => k.key)
);

// ─── Initial languages from SUPPORTED_LANGUAGES ─────────────────

const RTL_CODES = new Set(["ar", "he"]);

export const INITIAL_LANGUAGES: LexiconLanguage[] = SUPPORTED_LANGUAGES.map(
  (lang) => ({
    code: lang.code,
    nameEn: lang.name,
    nameNative: lang.native,
    direction: RTL_CODES.has(lang.code) ? ("rtl" as const) : ("ltr" as const),
    status: "approved" as const,
  })
);
