/**
 * Pre-seeded translations for all 33 supported languages.
 * Generated by Claude LLM — community-editable via CSV upload in Language Lexicon.
 * Each language maps translation keys to their localized strings.
 */

import type { LanguageTranslations } from "@/lib/lexicon-data";

export const SEEDED_TRANSLATIONS: LanguageTranslations = {
  // English is the master — stored in DEFAULT_ENGLISH_TRANSLATIONS, not here.
};
