/**
 * pod-rates.ts — the region, the minimum-wage table, and what a 웃 settles as.
 *
 * OPERATOR ASK, 2026-09-10 (docs/asks/2026-09-10_minimum_wage_rate_table.md):
 *   "let me know when pod has region, mini wage table, and rates built in
 *    Consolidated Table — Published Numeric Rates First, NULL Records Last"
 *
 * GENERATED FROM docs/asks/2026-09-10_minimum_wage_rate_table.psv — the operator's own file, transcribed once and
 * committed before this code existed. If a rate is wrong, the source is wrong; do not edit a figure here.
 *
 * THE MINT NEVER READS THIS FILE. 웃 = M × T, and no wage, currency or jurisdiction may enter the mint — that
 * placement error is the defect the paper spent thirty-four releases removing. A region decides ONLY what an already
 * minted 웃 settles as, and the rate is STAMPED at mint (D9, the vintage rule) rather than looked up later.
 *
 * NO CURRENCY IS EVER CONVERTED INTO ANOTHER. The table publishes one hourly rate per region in that region's own
 * currency and nothing else. There are no exchange rates here because the paper publishes none, and a settlement
 * figure in a currency the operator did not give me would be invented.
 *
 * A NULL RATE IS NOT ZERO. unit.settle: "No contributor settles at zero merely because their government has not yet
 * legislated." Such a region settles under the Global Agreed Standard, and until that number is published the pod
 * shows no figure at all and says which of the three reasons applies.
 */

import { US_STATE_RATES, COUNTRY_RATES, type ResolvedRegion } from "@/lib/min-wage";

/** One row of the operator's table. `rate` is the hourly minimum wage in `currency`; null where none is published. */
export interface RegionRate {
  lang: string;          // Language
  cc: string;            // Country Code (ISO 3166-1 alpha-2)
  name: string;          // Country / Jurisdiction, as printed
  currency: string;      // Currency Code (ISO 4217)
  rate: number | null;   // Hourly Wage Rate — NULL where not published
  published: boolean;    // Official Published
  noSingleRate: boolean; // No Single National Rate
  note: string;          // Notes, verbatim
  /**
   * Set on rows the operator APPROVED from the fleet's proposal (docs/asks/2026-09-11_rule_b_approved.md) — the date
   * of the approval. Absent on his own 114 rows. Every approved row remains "verified = no" in its provenance file:
   * he approved the rule, not the sources, and no official source is reachable from this environment.
   */
  approved?: string;
}

/**
 * The operator's 114 rows, in his order (published numeric rates first, NULL records last), followed by the rows he
 * approved from the fleet's proposal under Rule B. REGENERATED by scripts/gen-pod-rates.mjs from the two source files;
 * never edited by hand.
 */
export const REGION_RATES: RegionRate[] = [
  { lang: "English", cc: "US", name: "United States — Austin, Texas", currency: "USD", rate: 7.250, published: true, noSingleRate: false, note: "Federal rate applicable in Texas" },
  { lang: "English", cc: "GB", name: "United Kingdom", currency: "GBP", rate: 12.710, published: true, noSingleRate: false, note: "Age 21+" },
  { lang: "English", cc: "CA", name: "Canada — Federal", currency: "CAD", rate: 18.150, published: true, noSingleRate: true, note: "Federal sector; provinces set most rates" },
  { lang: "English", cc: "AU", name: "Australia", currency: "AUD", rate: 26.440, published: true, noSingleRate: false, note: "National minimum" },
  { lang: "English", cc: "NZ", name: "New Zealand", currency: "NZD", rate: 23.950, published: true, noSingleRate: false, note: "Adult minimum" },
  { lang: "English", cc: "NG", name: "Nigeria", currency: "NGN", rate: 402.739, published: true, noSingleRate: false, note: "National rate converted from monthly" },
  { lang: "French", cc: "CM", name: "Cameroon — Yaoundé", currency: "XAF", rate: 240.925, published: true, noSingleRate: false, note: "Government-sector reference" },
  { lang: "Spanish", cc: "ES", name: "Spain", currency: "EUR", rate: 8.196, published: true, noSingleRate: false, note: "National annual minimum converted to hourly" },
  { lang: "Spanish", cc: "MX", name: "Mexico", currency: "MXN", rate: 39.380, published: true, noSingleRate: false, note: "General rate; northern border differs" },
  { lang: "Spanish", cc: "CO", name: "Colombia", currency: "COP", rate: 10073.700, published: true, noSingleRate: false, note: "National base minimum" },
  { lang: "Spanish", cc: "CL", name: "Chile", currency: "CLP", rate: 3101.087, published: true, noSingleRate: false, note: "National rate converted from monthly" },
  { lang: "German", cc: "DE", name: "Germany", currency: "EUR", rate: 13.900, published: true, noSingleRate: false, note: "National rate" },
  { lang: "German", cc: "LU", name: "Luxembourg", currency: "EUR", rate: 15.557, published: true, noSingleRate: false, note: "National unskilled reference" },
  { lang: "Portuguese", cc: "BR", name: "Brazil", currency: "BRL", rate: 9.326, published: true, noSingleRate: false, note: "National rate converted from monthly" },
  { lang: "Russian", cc: "RU", name: "Russia", currency: "RUB", rate: 155.878, published: true, noSingleRate: false, note: "Federal rate converted from monthly" },
  { lang: "Chinese", cc: "CN", name: "China — Beijing", currency: "CNY", rate: 27.700, published: true, noSingleRate: true, note: "Municipal rate; no single national rate" },
  { lang: "Japanese", cc: "JP", name: "Japan — Tokyo", currency: "JPY", rate: 1226.000, published: true, noSingleRate: true, note: "Prefectural rate" },
  { lang: "Korean", cc: "KR", name: "South Korea", currency: "KRW", rate: 10320.000, published: true, noSingleRate: false, note: "National rate" },
  { lang: "Arabic", cc: "EG", name: "Egypt", currency: "EGP", rate: 40.274, published: true, noSingleRate: false, note: "National rate converted from monthly" },
  { lang: "Arabic", cc: "MA", name: "Morocco", currency: "MAD", rate: 19.694, published: true, noSingleRate: true, note: "Nonagricultural reference" },
  { lang: "Punjabi", cc: "PK", name: "Pakistan — Punjab", currency: "PKR", rate: 230.137, published: true, noSingleRate: true, note: "Provincial rate" },
  { lang: "Thai", cc: "TH", name: "Thailand — Bangkok", currency: "THB", rate: 50.000, published: true, noSingleRate: true, note: "Bangkok daily rate converted to hourly" },
  { lang: "Vietnamese", cc: "VN", name: "Vietnam — Region I", currency: "VND", rate: 30550.685, published: true, noSingleRate: true, note: "Highest official regional rate" },
  { lang: "Indonesian", cc: "ID", name: "Indonesia — Jakarta", currency: "IDR", rate: 32967.608, published: true, noSingleRate: true, note: "Provincial rate converted from monthly" },
  { lang: "Malay", cc: "MY", name: "Malaysia", currency: "MYR", rate: 9.781, published: true, noSingleRate: false, note: "National rate converted from monthly" },
  { lang: "Filipino", cc: "PH", name: "Philippines — Metro Manila", currency: "PHP", rate: 86.875, published: true, noSingleRate: true, note: "Regional daily rate converted to hourly" },
  { lang: "Turkish", cc: "TR", name: "Türkiye", currency: "TRY", rate: 190.036, published: true, noSingleRate: false, note: "National rate converted from monthly" },
  { lang: "Polish", cc: "PL", name: "Poland", currency: "PLN", rate: 27.651, published: true, noSingleRate: false, note: "National rate converted from monthly" },
  { lang: "Hebrew", cc: "IL", name: "Israel", currency: "ILS", rate: 33.830, published: true, noSingleRate: false, note: "National rate converted from monthly" },
  { lang: "English", cc: "IE", name: "Ireland", currency: "EUR", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "English", cc: "IN", name: "India", currency: "INR", rate: null, published: true, noSingleRate: true, note: "Not Published — varies by state, skill and occupation" },
  { lang: "French", cc: "FR", name: "France", currency: "EUR", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "French", cc: "BE", name: "Belgium", currency: "EUR", rate: null, published: true, noSingleRate: true, note: "Not Published — interprofessional and sectoral floors" },
  { lang: "French", cc: "CH", name: "Switzerland", currency: "CHF", rate: null, published: true, noSingleRate: true, note: "Not Published — selected cantons publish rates" },
  { lang: "French", cc: "CA", name: "Canada — Québec", currency: "CAD", rate: null, published: true, noSingleRate: true, note: "Not Published — provincial rate" },
  { lang: "French", cc: "CD", name: "Democratic Republic of the Congo", currency: "CDF", rate: null, published: true, noSingleRate: true, note: "Not Published — occupational categories" },
  { lang: "French", cc: "CI", name: "Côte d’Ivoire", currency: "XOF", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "French", cc: "SN", name: "Senegal", currency: "XOF", rate: null, published: true, noSingleRate: true, note: "Not Published — agricultural and nonagricultural rates" },
  { lang: "French", cc: "ML", name: "Mali", currency: "XOF", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "French", cc: "HT", name: "Haiti", currency: "HTG", rate: null, published: true, noSingleRate: true, note: "Not Published — industry-specific daily rates" },
  { lang: "Spanish", cc: "GT", name: "Guatemala", currency: "GTQ", rate: null, published: true, noSingleRate: true, note: "Not Published — varies by activity and region" },
  { lang: "Spanish", cc: "HN", name: "Honduras", currency: "HNL", rate: null, published: true, noSingleRate: true, note: "Not Published — employer size and industry" },
  { lang: "Spanish", cc: "SV", name: "El Salvador", currency: "USD", rate: null, published: true, noSingleRate: true, note: "Not Published — sector-specific" },
  { lang: "Spanish", cc: "NI", name: "Nicaragua", currency: "NIO", rate: null, published: true, noSingleRate: true, note: "Not Published — industry-specific" },
  { lang: "Spanish", cc: "CR", name: "Costa Rica", currency: "CRC", rate: null, published: true, noSingleRate: true, note: "Not Published — occupation and skill-specific" },
  { lang: "Spanish", cc: "PA", name: "Panama", currency: "PAB", rate: null, published: true, noSingleRate: true, note: "Not Published — region, occupation and business size" },
  { lang: "Spanish", cc: "CU", name: "Cuba", currency: "CUP", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Spanish", cc: "DO", name: "Dominican Republic", currency: "DOP", rate: null, published: true, noSingleRate: true, note: "Not Published — employer size and sector" },
  { lang: "Spanish", cc: "VE", name: "Venezuela", currency: "VES", rate: null, published: true, noSingleRate: false, note: "Not Published — currency value highly unstable" },
  { lang: "Spanish", cc: "EC", name: "Ecuador", currency: "USD", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Spanish", cc: "PE", name: "Peru", currency: "PEN", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Spanish", cc: "BO", name: "Bolivia", currency: "BOB", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Spanish", cc: "PY", name: "Paraguay", currency: "PYG", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Spanish", cc: "AR", name: "Argentina", currency: "ARS", rate: null, published: true, noSingleRate: false, note: "Not Published — frequently adjusted" },
  { lang: "Spanish", cc: "UY", name: "Uruguay", currency: "UYU", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Spanish", cc: "GQ", name: "Equatorial Guinea", currency: "XAF", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "German", cc: "AT", name: "Austria", currency: "EUR", rate: null, published: false, noSingleRate: true, note: "Not Published — collective agreements" },
  { lang: "German", cc: "CH", name: "Switzerland", currency: "CHF", rate: null, published: true, noSingleRate: true, note: "Not Published — cantonal rates only" },
  { lang: "German", cc: "LI", name: "Liechtenstein", currency: "CHF", rate: null, published: false, noSingleRate: true, note: "Not Published — collective and sectoral" },
  { lang: "Italian", cc: "IT", name: "Italy", currency: "EUR", rate: null, published: false, noSingleRate: true, note: "Not Published — collective agreements" },
  { lang: "Italian", cc: "CH", name: "Switzerland", currency: "CHF", rate: null, published: true, noSingleRate: true, note: "Not Published — cantonal rates only" },
  { lang: "Italian", cc: "SM", name: "San Marino", currency: "EUR", rate: null, published: true, noSingleRate: true, note: "Not Published — sectoral and collective" },
  { lang: "Italian", cc: "VA", name: "Vatican City", currency: "EUR", rate: null, published: false, noSingleRate: true, note: "Not Published" },
  { lang: "Portuguese", cc: "PT", name: "Portugal", currency: "EUR", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Portuguese", cc: "AO", name: "Angola", currency: "AOA", rate: null, published: true, noSingleRate: true, note: "Not Published — category-specific" },
  { lang: "Portuguese", cc: "MZ", name: "Mozambique", currency: "MZN", rate: null, published: true, noSingleRate: true, note: "Not Published — sector-specific" },
  { lang: "Portuguese", cc: "CV", name: "Cape Verde", currency: "CVE", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Portuguese", cc: "TL", name: "Timor-Leste", currency: "USD", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Dutch", cc: "NL", name: "Netherlands", currency: "EUR", rate: null, published: true, noSingleRate: false, note: "Not Published — age-based hourly rate" },
  { lang: "Dutch", cc: "BE", name: "Belgium", currency: "EUR", rate: null, published: true, noSingleRate: true, note: "Not Published — interprofessional and sectoral" },
  { lang: "Dutch", cc: "SR", name: "Suriname", currency: "SRD", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Russian", cc: "BY", name: "Belarus", currency: "BYN", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Russian", cc: "KZ", name: "Kazakhstan", currency: "KZT", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Russian", cc: "KG", name: "Kyrgyzstan", currency: "KGS", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Chinese", cc: "TW", name: "Taiwan", currency: "TWD", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Chinese", cc: "SG", name: "Singapore", currency: "SGD", rate: null, published: true, noSingleRate: true, note: "Not Published — occupational wage models" },
  { lang: "Korean", cc: "KP", name: "North Korea", currency: "KPW", rate: null, published: false, noSingleRate: true, note: "Not Published — no transparent comparable rate" },
  { lang: "Arabic", cc: "SA", name: "Saudi Arabia", currency: "SAR", rate: null, published: true, noSingleRate: true, note: "Not Published — category and citizenship-specific" },
  { lang: "Arabic", cc: "IQ", name: "Iraq", currency: "IQD", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Arabic", cc: "DZ", name: "Algeria", currency: "DZD", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Arabic", cc: "SD", name: "Sudan", currency: "SDG", rate: null, published: true, noSingleRate: false, note: "Not Published — currency-date control required" },
  { lang: "Arabic", cc: "AE", name: "United Arab Emirates", currency: "AED", rate: null, published: false, noSingleRate: true, note: "Not Published — no universal national rate" },
  { lang: "Arabic", cc: "JO", name: "Jordan", currency: "JOD", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Arabic", cc: "LB", name: "Lebanon", currency: "LBP", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Arabic", cc: "SY", name: "Syria", currency: "SYP", rate: null, published: true, noSingleRate: false, note: "Not Published — currency-date control required" },
  { lang: "Arabic", cc: "YE", name: "Yemen", currency: "YER", rate: null, published: false, noSingleRate: true, note: "Not Published — no reliable comparable rate" },
  { lang: "Arabic", cc: "OM", name: "Oman", currency: "OMR", rate: null, published: true, noSingleRate: true, note: "Not Published — citizen-specific" },
  { lang: "Arabic", cc: "QA", name: "Qatar", currency: "QAR", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Arabic", cc: "BH", name: "Bahrain", currency: "BHD", rate: null, published: true, noSingleRate: true, note: "Not Published — category and citizenship-specific" },
  { lang: "Arabic", cc: "KW", name: "Kuwait", currency: "KWD", rate: null, published: true, noSingleRate: true, note: "Not Published — worker-category-specific" },
  { lang: "Hindi", cc: "IN", name: "India", currency: "INR", rate: null, published: true, noSingleRate: true, note: "Not Published — state, occupation and skill" },
  { lang: "Bengali", cc: "BD", name: "Bangladesh", currency: "BDT", rate: null, published: true, noSingleRate: true, note: "Not Published — sector wage-board rates" },
  { lang: "Bengali", cc: "IN", name: "India — West Bengal", currency: "INR", rate: null, published: true, noSingleRate: true, note: "Not Published — state and occupation-specific" },
  { lang: "Punjabi", cc: "IN", name: "India — Punjab", currency: "INR", rate: null, published: true, noSingleRate: true, note: "Not Published — state and occupation-specific" },
  { lang: "Malay", cc: "BN", name: "Brunei", currency: "BND", rate: null, published: true, noSingleRate: true, note: "Not Published — selected industries" },
  { lang: "Malay", cc: "SG", name: "Singapore", currency: "SGD", rate: null, published: true, noSingleRate: true, note: "Not Published — occupational wage floors" },
  { lang: "Turkish", cc: "CY", name: "Cyprus", currency: "EUR", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Ukrainian", cc: "UA", name: "Ukraine", currency: "UAH", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Romanian", cc: "RO", name: "Romania", currency: "RON", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Romanian", cc: "MD", name: "Moldova", currency: "MDL", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Greek", cc: "GR", name: "Greece", currency: "EUR", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Greek", cc: "CY", name: "Cyprus", currency: "EUR", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Czech", cc: "CZ", name: "Czechia", currency: "CZK", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "Swedish", cc: "SE", name: "Sweden", currency: "SEK", rate: null, published: false, noSingleRate: true, note: "Not Published — collective agreements" },
  { lang: "Swedish", cc: "FI", name: "Finland", currency: "EUR", rate: null, published: false, noSingleRate: true, note: "Not Published — collective agreements" },
  { lang: "Danish", cc: "DK", name: "Denmark", currency: "DKK", rate: null, published: false, noSingleRate: true, note: "Not Published — collective agreements" },
  { lang: "Finnish", cc: "FI", name: "Finland", currency: "EUR", rate: null, published: false, noSingleRate: true, note: "Not Published — collective agreements" },
  { lang: "Norwegian", cc: "NO", name: "Norway", currency: "NOK", rate: null, published: true, noSingleRate: true, note: "Not Published — designated industries only" },
  { lang: "Swahili", cc: "TZ", name: "Tanzania", currency: "TZS", rate: null, published: true, noSingleRate: true, note: "Not Published — sector-specific" },
  { lang: "Swahili", cc: "KE", name: "Kenya", currency: "KES", rate: null, published: true, noSingleRate: true, note: "Not Published — occupation and locality-specific" },
  { lang: "Swahili", cc: "UG", name: "Uganda", currency: "UGX", rate: null, published: false, noSingleRate: true, note: "Not Published — no current broadly applicable rate" },
  { lang: "Swahili", cc: "CD", name: "Democratic Republic of the Congo", currency: "CDF", rate: null, published: true, noSingleRate: true, note: "Not Published — occupational categories" },
  { lang: "Swahili", cc: "RW", name: "Rwanda", currency: "RWF", rate: null, published: false, noSingleRate: true, note: "Not Published — no reliable current general benchmark" },
  { lang: "Nepali", cc: "NP", name: "Nepal", currency: "NPR", rate: null, published: true, noSingleRate: false, note: "Not Published" },
  { lang: "English", cc: "AG", name: "Antigua and Barbuda", currency: "XCD", rate: 9.000, published: true, noSingleRate: false, note: "National minimum wage EC$9.00/hour effective 2023-01-01 (from 8.20 since 2015). Published directly as hourly. No later increase known to either agent. XCD pegged 2.70:1 USD.", approved: "2026-09-11" },
  { lang: "Armenian", cc: "AM", name: "Armenia", currency: "AMD", rate: 432.700, published: true, noSingleRate: false, note: "AMD 75,000 gross/month since 1 January 2023 (68,000 before). Both agents note a discussed rise to AMD 85,000 for 2026, unconfirmed. Labour Code normal week 40 h; no statutory divisor. URL unverified.", approved: "2026-09-11" },
  { lang: "Azerbaijani", cc: "AZ", name: "Azerbaijan", currency: "AZN", rate: 2.308, published: true, noSingleRate: false, note: "AZN 400/month from 1 January 2025 (345 from 2023), Presidential Decree of Dec 2024 under Labour Code art. 155. A further 2026 increase reported, unverified. 40 h week, no statutory divisor. URL unverified.", approved: "2026-09-11" },
  { lang: "Bosnian", cc: "BA", name: "Bosnia and Herzegovina — Federation of Bosnia and Herzegovina", currency: "BAM", rate: 5.769, published: true, noSingleRate: false, note: "BAM 1,000 NET/month from 1 January 2025 (from 619 net), FBiH Government decision under the amended Labour Law art. 78. Figure is NET — gross roughly BAM 1,550–1,600, so not comparable to gross rows. 2026 increase (BAM 1,100 mooted) unconfirmed by either agent. URL unverified.", approved: "2026-09-11" },
  { lang: "English", cc: "BB", name: "Barbados", currency: "BBD", rate: 8.500, published: true, noSingleRate: true, note: "National minimum wage BDS$8.50/hour effective 2021-04-01; security guards have a higher sectoral rate (9.25). A Minimum Wage Board review / general increase was under discussion in 2024–25; neither agent can confirm a new order, so the 2021 rate is cited. BBD pegged 2:1 to USD.", approved: "2026-09-11" },
  { lang: "Bulgarian", cc: "BG", name: "Bulgaria", currency: "EUR", rate: 3.736, published: true, noSingleRate: false, note: "Bulgaria adopted the euro 1 January 2026; 2026 minimum is EUR 620.20/month (= BGN 1,213 at the fixed 1.95583), set by Council of Ministers decree under Labour Code art. 244 (50% of average gross wage formula). The decree also prints an hourly figure; both agents infer a 166 h divisor from the 2025 pair (BGN 1,077 / BGN 6.49 per hour, high confidence). Verify the euro hourly line in the 2026 decree. URL unverified.", approved: "2026-09-11" },
  { lang: "French", cc: "BJ", name: "Benin", currency: "XOF", rate: 300.006, published: true, noSingleRate: false, note: "A and B agree: SMIG raised from 40,000 to 52,000 XOF/month effective 1 January 2023 by decree (Council of Ministers, Dec 2022). Legal week 40 h. National rate, no sub-national floors. Decree number not recalled with certainty by either researcher.", approved: "2026-09-11" },
  { lang: "French", cc: "BL", name: "France — Saint-Barthélemy", currency: "EUR", rate: 11.880, published: true, noSingleRate: false, note: "Collectivité d'outre-mer where the Code du travail and national SMIC apply. €11.88/hour gross since 2024-11-01; 2026-01-01 revalorisation not confirmed by either agent.", approved: "2026-09-11" },
  { lang: "English", cc: "BM", name: "United Kingdom — Bermuda", currency: "BMD", rate: 16.400, published: true, noSingleRate: false, note: "British Overseas Territory (North Atlantic, grouped here with the Caribbean dependencies). Bermuda's first statutory minimum hourly wage BD$16.40 effective 2023-06-01. Subject to periodic review by the Wage Commission; a 2025/26 uprating may have occurred — not confirmed by either agent. BMD at par with USD. Agents differ on the parent Act (A: Employment Act 2000 as amended 2021; B: Employment (Minimum Hourly Wage) Act 2022).", approved: "2026-09-11" },
  { lang: "English", cc: "BS", name: "Bahamas", currency: "BSD", rate: 6.500, published: true, noSingleRate: false, note: "National minimum wage B$260.00/week effective 2023-01-01 (from 210). Published weekly; hourly from the 40-hour standard week. Proposals for a further increase were aired in 2025; not confirmed enacted by either agent. BSD at par with USD. Agents cite the Act as 2001 (A) vs 2002 (B). Confidence: A high, B medium — lower kept.", approved: "2026-09-11" },
  { lang: "Belarusian", cc: "BY", name: "Belarus", currency: "BYN", rate: 4.189, published: true, noSingleRate: false, note: "BYN 726/month from 1 January 2025 (626 in 2024), Council of Ministers resolution of Dec 2024; indexed intra-year to inflation, base figure shown. Neither agent could confirm the 2026 resolution (A recalls ~787 discussed). Operator holds BY as a null-rate row; this fills beside it. Russian is the working language of the legal texts. URL unverified.", approved: "2026-09-11" },
  { lang: "English", cc: "BZ", name: "Belize", currency: "BZD", rate: 5.000, published: true, noSingleRate: false, note: "National minimum wage BZ$5.00/hour effective 2023-01-01 (from 3.30). Government has stated an intent to move toward BZ$6.00 by 2026; neither agent can confirm a further Order took effect, so the 2023 rate is cited. BZD pegged 2:1 to USD.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Alberta", currency: "CAD", rate: 15.000, published: true, noSingleRate: true, note: "General rate $15.00 unchanged since 2018-10-01 — now the lowest general rate in Canada. Students under 18 (first 28 h/week) $13.00. Separate weekly/monthly minimums for certain salespersons and domestic workers. Not indexed; no increase announced to either agent's knowledge.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — British Columbia", currency: "CAD", rate: 17.850, published: true, noSingleRate: true, note: "General rate $17.85 effective 2025-06-01 (from 17.40). Separate rates for live-in camp leaders, resident caretakers and piece-rate farm workers. Indexed to BC CPI each 1 June; the 2026-06-01 adjustment (~2%, roughly $18.2x) will have applied but neither agent can confirm the figure, so the 2025 rate is cited.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Manitoba", currency: "CAD", rate: 16.000, published: true, noSingleRate: false, note: "$16.00 effective 2025-10-01 (from 15.80 on 2024-10-01). Indexed to Manitoba CPI each 1 October; the 2026-10-01 adjustment is not yet in effect on this date.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — New Brunswick", currency: "CAD", rate: 15.650, published: true, noSingleRate: false, note: "$15.65 effective 2025-04-01 (from 15.30). Indexed to CPI each 1 April; the 2026-04-01 rate (~$15.90–16.00) will have applied but is not confirmed by either agent, so the 2025 rate is cited. Agents cite different regulation numbers (A: NB Reg 2019-24; B: NB Reg 2017-20) — verify the current consolidation.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Newfoundland and Labrador", currency: "CAD", rate: 16.000, published: true, noSingleRate: false, note: "$16.00 effective 2025-04-01 (from 15.60). Indexed to CPI each 1 April; the 2026-04-01 figure is not confirmed by either agent, so the 2025 rate is cited.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Northwest Territories", currency: "CAD", rate: 16.950, published: true, noSingleRate: false, note: "$16.95 effective 2025-09-01 (from 16.70 on 2024-09-01). Indexed each 1 September to Yellowknife CPI and average hourly wage. Both agents recall the same figure from memory; the exact cents are the weakest part.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Nova Scotia", currency: "CAD", rate: 16.500, published: true, noSingleRate: false, note: "$16.50 effective 2025-10-01 (two-step year: 15.70 on 2025-04-01, then 16.50). Indexed to CPI + 1% each 1 April; the 2026-04-01 adjustment is not confirmed by either agent.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Nunavut", currency: "CAD", rate: 19.000, published: true, noSingleRate: false, note: "$19.00 effective 2024-01-01 (from 16.00) — highest general minimum in Canada. No indexation formula; no later change known to either agent. Confidence: A high, B medium — lower kept.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Ontario", currency: "CAD", rate: 17.600, published: true, noSingleRate: true, note: "General rate $17.60 effective 2025-10-01 (from 17.20). Students under 18 (≤28 h/week) $16.60; homeworkers $19.35; hunting/fishing/wilderness guides paid daily rates. Indexed to Ontario CPI each 1 October; a 2026-10-01 increase (reported ~$17.95) is scheduled but not in effect on this date. Confidence: A high, B medium — lower kept.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Prince Edward Island", currency: "CAD", rate: 16.500, published: true, noSingleRate: false, note: "$16.50 effective 2025-10-01 (from 16.00 on 2025-04-01; 15.40 in 2024). Set by Minimum Wage Order after Employment Standards Board review; a 2026 order may have been made but is not confirmed by either agent.", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Saskatchewan", currency: "CAD", rate: 15.350, published: true, noSingleRate: false, note: "$15.35 effective 2025-10-01 (from 15.00 on 2024-10-01, the end of the legislated step-ups). Indexed each 1 October by the statutory formula (average of CPI and average hourly wage change).", approved: "2026-09-11" },
  { lang: "English", cc: "CA", name: "Canada — Yukon", currency: "CAD", rate: 17.940, published: true, noSingleRate: false, note: "$17.94 effective 2025-04-01 (from 17.59). Indexed to Whitehorse CPI each 1 April; the 2026-04-01 figure is not confirmed by either agent, so the 2025 rate is cited.", approved: "2026-09-11" },
  { lang: "French", cc: "CH", name: "Switzerland — Geneva", currency: "CHF", rate: 24.480, published: true, noSingleRate: false, note: "Cantonal minimum wage under LIRT art. 39K (popular vote 27 Sept 2020), indexed each 1 January to Geneva CPI by arrêté du Conseil d'État: CHF 23.00 (2020), 23.27 (2022), 24.00 (2023), 24.32 (2024), 24.48 (2025). Both agents believe the 2026 indexed figure is ~CHF 24.6–24.7 but neither holds it with confidence, so the 2025 rate is cited. Exclusions: agriculture/floriculture (separate lower rate), apprentices, some internships.", approved: "2026-09-11" },
  { lang: "Chinese", cc: "CN", name: "China — Shanghai", currency: "CNY", rate: 24.000, published: true, noSingleRate: true, note: "Both agree: from 1 Jul 2023 Shanghai monthly CNY 2,690 (highest monthly floor in mainland China) and non-full-time hourly CNY 24. Both recall an unverified 1 Jul 2025 adjustment to ~2,740/month (A: hourly possibly 25; B: hourly reportedly unchanged at 24) — neither can confirm, so 24 is the last figure both stand behind. Shanghai's monthly rate excludes the employee's own social-insurance/housing-fund contributions, so it is not directly comparable to Beijing/Shenzhen.", approved: "2026-09-11" },
  { lang: "Chinese", cc: "CN", name: "China — Shenzhen", currency: "CNY", rate: 22.200, published: true, noSingleRate: true, note: "Both agree: Shenzhen carries its own line within Guangdong's provincial table — monthly CNY 2,360, non-full-time hourly CNY 22.2, effective 1 Jan 2022 (Guangdong notice of Dec 2021; Guangzhou Class I is 2,300 / 22.2). Both recall reports of a 2025/2026 Guangdong adjustment but neither can name new figures; 2022 edition is the last both are sure of. Verify on hrss.gd.gov.cn / hrss.sz.gov.cn.", approved: "2026-09-11" },
  { lang: "Spanish", cc: "CU", name: "Cuba", currency: "CUP", rate: 11.014, published: true, noSingleRate: false, note: "State-sector minimum wage CUP 2,100/month since 2021-01-01 (Tarea Ordenamiento), unchanged to either agent's knowledge. Statutory workweek 44 h (Código de Trabajo, Ley 116/2013, art. 87), so the divisor is 44 × 52 ÷ 12 = 190.67 h rather than 173.33. Nominal only given official vs. informal exchange rates. Agents cite the instrument differently (A: Resolución 29/2021 MTSS; B: Decreto-Ley 20/2020 + Resolución 29/2020 MTSS, Gaceta Oficial Extraordinaria No. 69 of 2020-12-10). Operator's CU row is null Y/N; this is a fill candidate beside it.", approved: "2026-09-11" },
  { lang: "Greek", cc: "CY", name: "Cyprus", currency: "EUR", rate: 5.769, published: true, noSingleRate: true, note: "National statutory minimum (since 2023): EUR 1,000 gross/month from 1 January 2024, EUR 900 for the first six months with a new employer — two tiers by tenure. Domestic, agricultural and shipping workers under separate sector orders. A 2026 revision (~1,050/950 reported) was pending in late 2025, unverified by either agent. Operator holds CY as a null-rate row; this fills beside it. URL unverified.", approved: "2026-09-11" },
  { lang: "Czech", cc: "CZ", name: "Czechia", currency: "CZK", rate: 134.400, published: true, noSingleRate: false, note: "2026: CZK 22,400/month and CZK 134.40/hour (40 h week), first full year of the automatic valorisation mechanism in Labour Code §111 (Act 230/2024). 2025 was 20,800 / 124.40. Private-sector guaranteed-wage bands reduced/abolished in 2025. Hourly is a published statutory figure. Operator holds CZ as a null-rate row; this fills beside it. URL unverified.", approved: "2026-09-11" },
  { lang: "Arabic", cc: "DZ", name: "Algeria", currency: "DZD", rate: 115.387, published: true, noSingleRate: false, note: "A and B agree: SNMG DZD 20,000/month since 1 June 2020 (Décret présidentiel n° 20-137 du 30 mai 2020), no later revision known to either (2022–2024 measures raised net pay via IRG exemption, not the SNMG). Legal week 40 h (Loi 90-11 art. 22 as amended by Ordonnance 97-03), so 173.33 h is the statutory month. Arithmetic fix only: 20,000 ÷ 173.33 = 115.3868 → 115.387 (A had truncated to 115.386). Fills the operator's null DZ row.", approved: "2026-09-11" },
  { lang: "French", cc: "FR", name: "France", currency: "EUR", rate: 12.020, published: true, noSingleRate: false, note: "SMIC gross hourly EUR 12.02 from 1 January 2026 (annual revaluation by décret, ~+1.2% on the EUR 11.88 in force from 1 Nov 2024 through 2025). Monthly gross EUR 1,823.06 on the legal 35-h week (151.67 h/month — France's statutory divisor, not 173.33). Both agents rate the 2026 figure medium (recall of the Dec 2025 decree); the EUR 11.88 (2025-01-01) figure is high confidence if the merge prefers certainty. Automatic mid-year uplift only if CPI rises >2% — none known as of Sept 2026. Lower SMIC in Mayotte. Operator row is null; this fills it.", approved: "2026-09-11" },
  { lang: "Georgian", cc: "GE", name: "Georgia", currency: "GEL", rate: 0.115, published: true, noSingleRate: true, note: "SWEEP. The only statutory private-sector floor is GEL 20/month under Presidential Decree No. 351 of 1999 — obsolete and unenforced; public servants GEL 115/month (Decree No. 43 of 2005). Included only as the nominal figure on the books; a real floor has been debated but not enacted.", approved: "2026-09-11" },
  { lang: "French", cc: "GF", name: "France — French Guiana", currency: "EUR", rate: 11.880, published: true, noSingleRate: false, note: "A=B. French Guiana is a département/région d'outre-mer; the metropolitan SMIC applies in full (Mayotte alone has a reduced SMIC). SMIC brut = EUR 11.88/h from 1 Nov 2024 (Décret n° 2024-951 du 23 octobre 2024, anticipatory +2%; unchanged 1 Jan 2025); monthly for the legal 35-h week = 11.88 × 151.67 h = EUR 1,801.80. Both flag that a 1 Jan 2026 revaluation almost certainly occurred (B recalls ≈ EUR 12.02/h) and cannot be confirmed — treat as possibly stale. Operator holds FR as Y/N null; this row carries the French figure by inheritance and sits beside his.", approved: "2026-09-11" },
  { lang: "English", cc: "GH", name: "Ghana", currency: "GHS", rate: 2.496, published: true, noSingleRate: false, note: "A and B agree: National Daily Minimum Wage GHS 19.97/day effective 1 March 2025 (10% over GHS 18.15 in 2024), set by the National Tripartite Committee under s.113 of the Labour Act 2003. Statutory day 8 h (s.33). Both flag that a 2026 determination has probably been made on the annual cycle and neither can confirm its figure — 19.97 may be superseded.", approved: "2026-09-11" },
  { lang: "French", cc: "GP", name: "France — Guadeloupe", currency: "EUR", rate: 11.880, published: true, noSingleRate: false, note: "French overseas department: the national SMIC applies in full. Gross SMIC €11.88/hour effective 2024-11-01 (€1,801.80/month for 35 h; no change 2025-01-01). Both agents recall a 2026-01-01 revalorisation (~€12.02) but cannot confirm it, so the last confidently held figure is cited. The operator's FR row is null Y/N; this figure applies to metropolitan France as well and is offered beside it.", approved: "2026-09-11" },
  { lang: "Greek", cc: "GR", name: "Greece", currency: "EUR", rate: 5.280, published: true, noSingleRate: false, note: "EUR 880 gross/month for salaried employees (14 payments/year) and EUR 39.30/day for wage-earners from 1 April 2025. Both agents apply the Greek ×0.006 convention (÷ 25 days ÷ 6.667 h, equivalently ÷ 166.67 h) = 5.28. Seniority (triennia) increments sit on top. A step to ~EUR 920 from 1 April 2026 was announced, unverified by either. Operator holds GR as a null-rate row; this fills beside it. URL unverified.", approved: "2026-09-11" },
  { lang: "English", cc: "US", name: "United States — Guam", currency: "USD", rate: 9.250, published: true, noSingleRate: false, note: "ISO GU — a locality of the United States in this record. A and B agree on rate, currency and flags ($9.25/h; local statute above the $7.25 FLSA floor; steps $8.25 → $8.75 → $9.25). They DISAGREE on the enacting public law and the effective dates: A cites P.L. 34-06 with steps on 16 Mar 2018 and 16 Mar 2021; B cites P.L. 35-38 with steps on 1 Sep 2020 and 1 Sep 2021. Summarizer's recollection is P.L. 35-38 (2019) with 16 March 2020 and 16 March 2021 steps — i.e. B's law and A's day-month — so the as_of is given as the year only and confidence is lowered to medium; the operator should confirm the instrument and date with Guam DOL. Neither researcher knows a later enacted increase. Guam applies the full local rate to tipped employees (A, moderate confidence). English and Chamorro co-official; English is the working language of the statute. URL not fetched from this environment.", approved: "2026-09-11" },
  { lang: "English", cc: "GY", name: "Guyana", currency: "GYD", rate: 347.000, published: true, noSingleRate: false, note: "A=B. Private-sector national minimum wage under the Labour (National Minimum Wage) Order 2022 (B recalls Order No. 22 of 2022), effective 1 Jul 2022: GYD 347/hour, 2,776/day, 13,880/week, 60,147/month — the Order publishes all four, internally consistent on a 40-h week (previous 2017 order: GYD 255/h, 44,200/month). Public-service minimum (GYD 100,000+/month from 2024–25 budgets) is a separate pay-scale floor, not the statutory national minimum. Neither researcher can confirm whether a newer private-sector Order (2025/26) has superseded 2022. New row (not in operator's record).", approved: "2026-09-11" },
  { lang: "Chinese", cc: "HK", name: "Hong Kong", currency: "HKD", rate: 42.100, published: true, noSingleRate: false, note: "Both agree: Statutory Minimum Wage published directly as an hourly rate. HK$42.1 from 1 May 2025 (previous HK$40.0 from 1 May 2023), the first uplift under the annual review formula (inflation + 20% of real GDP growth, no downward revision) adopted in 2024. A further annual adjustment effective 1 May 2026 is expected under that formula; neither agent can state the 2026 figure, so the 2025 rate is given (as_of 2025-05-01 is therefore possibly superseded on today's date). Exempt: live-in domestic workers, student interns/work-experience students. Official languages Chinese and English; Chinese entered as primary. Confidence taken as the lower of the two (A high, B medium) because of the possible 2026 supersession.", approved: "2026-09-11" },
  { lang: "Croatian", cc: "HR", name: "Croatia", currency: "EUR", rate: 6.058, published: true, noSingleRate: false, note: "EUR 1,050 gross/month for 2026 (970 in 2025, 840 in 2024), Government regulation adopted by 31 October 2025 under the Minimum Wage Act. No statutory divisor (Croatian payroll often uses 174 h → 6.03). URL unverified.", approved: "2026-09-11" },
  { lang: "Hungarian", cc: "HU", name: "Hungary", currency: "HUF", rate: 1672.000, published: true, noSingleRate: true, note: "Two statutory floors. 2025 minimálbér: HUF 290,800/month, 66,860 weekly, 13,380 daily, 1,672 hourly (published in the decree on a 174 h basis); garantált bérminimum HUF 348,800/month (2,005 hourly) for jobs needing at least secondary qualification. Nov 2024 three-year agreement scheduled +13% for 2026 (~328,600 / ~1,889 hourly) but neither agent could confirm the 2026 decree; 2025 cited. URL unverified.", approved: "2026-09-11" },
  { lang: "English", cc: "IE", name: "Ireland", currency: "EUR", rate: 14.150, published: true, noSingleRate: false, note: "National Minimum Wage EUR 14.15/hour for adults (20+) from 1 January 2026, up EUR 0.65 from EUR 13.50 (2025), announced in Budget 2026 on the Low Pay Commission's recommendation. Sub-minima: under 18 = 70% (EUR 9.91), age 18 = 80% (EUR 11.32), age 19 = 90% (EUR 12.74). Operator row is null; this fills it.", approved: "2026-09-11" },
  { lang: "English", cc: "JE", name: "Jersey", currency: "GBP", rate: 13.000, published: true, noSingleRate: false, note: "Crown Dependency with its own minimum wage: GBP 13.00/hour from 1 April 2025 (GBP 11.64 from April 2024), by Order under the Employment (Jersey) Law 2003 on the Employment Forum's recommendation (policy target two-thirds of median earnings by 2026). A further uplift on 1 April 2026 is likely (A recalls ~13.7, B ~13.5 — neither confident), so the April 2025 rate is cited. Trainee rate and accommodation/food offsets apply.", approved: "2026-09-11" },
  { lang: "English", cc: "JM", name: "Jamaica", currency: "JMD", rate: 400.000, published: true, noSingleRate: true, note: "National minimum wage J$16,000 per 40-hour week effective 2025-06-01 (from 15,000 in June 2024; 13,000 in 2023). Industrial security guards have a higher rate (~J$18,000/week). A 2026-06-01 adjustment may have been gazetted; not confirmed by either agent. Confidence: A high, B medium — lower kept.", approved: "2026-09-11" },
  { lang: "English", cc: "KE", name: "Kenya — Nairobi", currency: "KES", rate: 71.510, published: true, noSingleRate: true, note: "General labourer / cleaner / gardener / sweeper rate for the cities (Nairobi, Mombasa, Kisumu) under the Regulation of Wages (General) (Amendment) Order 2024, which raised all rates 6% from 1 Nov 2024: about KES 16,113.75/month (from 15,201.65 set May 2022). The Order publishes a matrix by occupation and three locality zones plus a separate Agricultural Industry order, so no single national rate. The Order defines the normal week as 52 h, so the hourly is derived on 52 × 52 ÷ 12 = 225.33 h, not 173.33; the Order prints its own daily/hourly columns which neither researcher can reproduce. Operator holds KE null Y/Y — this row is a cross-check beside his. Monthly recalled (medium), hourly derived. Arithmetic re-checked: 16,113.75 ÷ 225.333 = 71.512.", approved: "2026-09-11" },
  { lang: "Khmer", cc: "KH", name: "Cambodia", currency: "USD", rate: 1.010, published: true, noSingleRate: true, note: "A (1.010) and B (1.0096) are the same quotient at different rounding — kept at 4 dp. Minimum wage applies ONLY to the textile, garment, footwear, travel-goods and bag sector (no economy-wide floor, hence no_single_rate); set in US dollars. 2024 = USD 204, 2025 = USD 208 (Prakas Sept 2024, high confidence), 2026 = USD 210/month (National Council on Minimum Wage decision Sept 2025 incl. PM top-up — from memory, medium confidence; confirm the Prakas number). Probationary workers lower (A recalls ~USD 2, B recalls USD 5 — unresolved, not load-bearing). Labour Law 1997 Art. 137: 8 h/day, 48 h/week → 208 h/month divisor.", approved: "2026-09-11" },
  { lang: "English", cc: "KY", name: "United Kingdom — Cayman Islands", currency: "KYD", rate: 6.000, published: true, noSingleRate: true, note: "British Overseas Territory. National minimum basic wage CI$6.00/hour since 2016-03-01; CI$4.50/hour for service employees who customarily receive gratuities (with a make-up requirement). The Minimum Wage Advisory Committee recommended CI$8.75 and Cabinet indicated adoption from 2026; neither agent can confirm the new Order is in force, so the 2016 figure is cited. KYD pegged 1 KYD = 1.20 USD.", approved: "2026-09-11" },
  { lang: "Kazakh", cc: "KZ", name: "Kazakhstan", currency: "KZT", rate: 490.394, published: true, noSingleRate: false, note: "KZT 85,000/month, raised from 70,000 on 1 January 2024 and held at 85,000 in the 2025–2027 and 2026–2028 Republican Budget Laws (both agents; the 2026 hold is medium confidence). Labour Code art. 104 defines the hourly minimum as monthly ÷ the production calendar's average monthly hours (~164–166 h → ~KZT 515); 173.33 h shown for comparability. Operator holds KZ as a null-rate row; this fills beside it. Russian co-official. URL unverified.", approved: "2026-09-11" },
  { lang: "Sinhala", cc: "LK", name: "Sri Lanka", currency: "LKR", rate: 105.000, published: true, noSingleRate: false, note: "A=B. National Minimum Wage of Workers Act No. 3 of 2016 sets a single national floor for all workers in any industry/service (originally Rs 10,000/month, Rs 400/day), amended by Act No. 16 of 2021 (Rs 12,500 / Rs 500), by Act No. 25 of 2024 (Rs 17,500/month, Rs 700/day, absorbing the budgetary relief allowance; A recalls effective 1 January 2024), and — implementing Budget 2025 — by a 2025 Amendment Act to Rs 21,000/month and Rs 840/day (both agents recall passage in 2025; exact Act number and commencement to verify). If the 2025 amendment is not yet in force the operative figures are Rs 17,500 / Rs 700 (= 87.50/h). The statute publishes both monthly and daily; the daily rate is for an 8-hour working day (Wages Boards Ordinance / Shop and Office Employees Act, 8 h/day, 45–48 h/week), so hourly = 840 ÷ 8; monthly 21,000 = 25 d × 840. Sectoral Wages Boards set higher trade-specific minima above the floor; Budget Relief Allowance Acts historically added fixed allowances. Monthly ÷ 173.33 would give 121.16 — not used, statute defines the day.", approved: "2026-09-11" },
  { lang: "English", cc: "LR", name: "Liberia", currency: "USD", rate: 0.680, published: true, noSingleRate: true, note: "A and B agree: Decent Work Act 2015 sets the minimum wage in US dollars (co-legal tender): USD 0.68/hour (USD 5.50 per 8-h day) for unskilled formal-sector workers and USD 0.43/hour (USD 3.50/day) for casual, agricultural and domestic workers — two floors. Published hourly; currency USD, not LRD.", approved: "2026-09-11" },
  { lang: "Lithuanian", cc: "LT", name: "Lithuania", currency: "EUR", rate: 7.050, published: true, noSingleRate: false, note: "2026: EUR 1,153/month (MMA) and EUR 7.05/hour (MVA), Government resolution of Oct 2025 (2025: 1,038 / 6.35, high confidence). Hourly is a published figure. Minimum wage payable only for unskilled work (Labour Code art. 141(2)). URL unverified.", approved: "2026-09-11" },
  { lang: "Latvian", cc: "LV", name: "Latvia", currency: "EUR", rate: 4.500, published: true, noSingleRate: false, note: "EUR 780/month from 1 January 2026 (740 in 2025, 700 in 2024), amendment to Cabinet Regulation No. 656. No fixed hourly: the Regulation prescribes monthly ÷ that month's normal working hours, so the official hourly varies (~4.3–4.9); 173.33 h shown as annual average. URL unverified.", approved: "2026-09-11" },
  { lang: "French", cc: "MC", name: "Monaco", currency: "EUR", rate: 12.020, published: true, noSingleRate: false, note: "Monaco's SMIC tracks the French SMIC hourly rate by ministerial order, with a mandatory 5% supplement (majoration/indemnité exceptionnelle de 5%) on top of the base. Base cited = French rate EUR 12.02/h from 1 Jan 2026 (medium confidence, dependent on the French figure; EUR 11.88 from Nov 2024 is high confidence). Effective floor with the 5% uplift ≈ EUR 12.62/h.", approved: "2026-09-11" },
  { lang: "Romanian", cc: "MD", name: "Moldova", currency: "MDL", rate: 32.544, published: true, noSingleRate: false, note: "Single national minimum MDL 5,500 gross/month from 1 January 2025 (5,000 in 2024), Government Decision of Dec 2024, which defines the wage for a 169-hour average month and prints the hourly 32.54. A 2026 rise (~MDL 6,300 reported) unconfirmed by either. Transnistria not covered. Operator holds MD as a null-rate row; this fills beside it. URL unverified.", approved: "2026-09-11" },
  { lang: "Montenegrin", cc: "ME", name: "Montenegro", currency: "EUR", rate: 3.462, published: true, noSingleRate: true, note: "'Evropa sad 2': minimum wage is NET and two-tiered — EUR 600/month up to level V qualification, EUR 800/month for jobs requiring higher education (previously single 450 net). Lower tier shown; gross is materially higher. Agents differ only on the start date (B: 1 Oct 2024; A: 1 Jan 2025) — row carries 2024-10-01, the reform's launch date; the rate is identical either way. URL unverified.", approved: "2026-09-11" },
  { lang: "French", cc: "MF", name: "France — Saint-Martin", currency: "EUR", rate: 11.880, published: true, noSingleRate: false, note: "Collectivité d'outre-mer where the Code du travail and national SMIC apply. €11.88/hour gross since 2024-11-01; 2026-01-01 revalorisation not confirmed by either agent. Shares the island with Sint Maarten (SX), which has its own NAf minimum.", approved: "2026-09-11" },
  { lang: "French", cc: "ML", name: "Mali", currency: "XOF", rate: 230.774, published: true, noSingleRate: false, note: "A and B agree: SMIG 40,000 XOF/month from 1 Jan 2016 (second step of the 2015 decree; 35,000 from 1 Jan 2015; previously 28,460). Neither can confirm a later revaluation (discussed after 2021). Legal week 40 h (Loi 92-020). Mali left ECOWAS in January 2025 (AES) but remains in the region. Operator's ML row is null; offered beside it.", approved: "2026-09-11" },
  { lang: "Burmese", cc: "MM", name: "Myanmar", currency: "MMK", rate: 600.000, published: true, noSingleRate: false, note: "A and B agree: statutory base MMK 4,800 per 8-hour day (National Committee for Minimum Wage Notification No. 2/2018, effective 14 May 2018; applies to workplaces with 10+ workers) = 600/h. The statutory rate has not been revised since; the committee (under the post-2021 military administration) added mandatory daily allowances of +1,000 from Oct 2023 and a further +1,000 from 1 Aug 2024, giving an effective 6,800/day (850/h) in practice. Only the 4,800 base is the legal minimum wage; the allowance total is medium confidence. Verify whether a 2025–26 revision occurred.", approved: "2026-09-11" },
  { lang: "Mongolian", cc: "MN", name: "Mongolia", currency: "MNT", rate: 3928.571, published: true, noSingleRate: false, note: "Both agree: single national floor set by resolution of the National Tripartite Committee on Labour and Social Consensus under the Law on Minimum Wage. MNT 550,000/month (hourly 3,273.81) from 2023-01-01; MNT 660,000/month from 2024-01-01. The resolution states its own hourly figure on a 168-hour month (40-h week × 4.2 weeks), so 168 is used as the divisor rather than 173.33. A later increase (2025 or 2026) may have been decided — neither can cite it. A's alternative figure at 173.33 h was mis-stated as 3,807.65; corrected here to 3,807.77.", approved: "2026-09-11" },
  { lang: "Chinese", cc: "MO", name: "Macau", currency: "MOP", rate: 34.000, published: true, noSingleRate: false, note: "Both agree: universal minimum wage (Law No. 5/2020, in force 1 Nov 2020 at MOP 32/hour, 256/day, 6,656/month) raised to MOP 34/hour, MOP 272/day, MOP 7,072/month effective 1 Jan 2024. Law is reviewed every two years, so a 2026-01-01 adjustment is possible (A recalls MOP 35 being discussed) — neither can confirm, so 34 is the last figure both stand behind. Exempt: domestic workers and workers with disabilities (art. 3). Official languages Chinese and Portuguese; Chinese entered as primary.", approved: "2026-09-11" },
  { lang: "English", cc: "US", name: "United States — Northern Mariana Islands", currency: "USD", rate: 7.250, published: true, noSingleRate: false, note: "ISO MP — a locality of the United States in this record. A and B agree. Federal FLSA floor and effective local rate coincide; no local statute above the federal floor. The CNMI's own Commonwealth Minimum Wage and Hour Act (4 CMC §9211 et seq., historically $3.05/h) was overtaken by the federal phase-in: P.L. 110-28 §8103 (2007) raised the CNMI rate in $0.50 steps, with the schedule adjusted by P.L. 111-244 (2010) and P.L. 113-34 (2013), reaching the full federal $7.25 on 30 September 2018. Since then 29 U.S.C. §206(a)(1) governs; no higher local rate enacted to either researcher's knowledge. English, Chamorro and Carolinian co-official; English is the working language. URL not fetched from this environment.", approved: "2026-09-11" },
  { lang: "French", cc: "MQ", name: "France — Martinique", currency: "EUR", rate: 11.880, published: true, noSingleRate: false, note: "French overseas department: national SMIC applies in full. €11.88/hour gross since 2024-11-01; the 2026-01-01 revalorisation (~€12.02) is not confirmed by either agent. Same instrument as Guadeloupe.", approved: "2026-09-11" },
  { lang: "Maltese", cc: "MT", name: "Malta", currency: "EUR", rate: 5.545, published: true, noSingleRate: false, note: "SWEEP (European island state). National minimum wage EUR 221.78 per week for workers 18+ in 2025 (213.54 in 2024; 192.73 in 2023), under the 2023 agreement on annual COLA plus fixed increments through 2027. 2026 figure (~EUR 230) unverified. Published weekly for a statutory 40-h week.", approved: "2026-09-11" },
  { lang: "Dhivehi", cc: "MV", name: "Maldives", currency: "MVR", rate: 38.462, published: true, noSingleRate: true, note: "A=B. First statutory minimum wage under Chapter 8 of the Employment Act (Law No. 2/2008) as added by the 6th Amendment (Act 22/2020); Minimum Wage Order issued 8 Nov 2021 by the Ministry of Economic Development, effective 1 January 2022. Three tiers by employer size, hence no single rate: small enterprises MVR 4,500/month (published hourly 21.63); medium MVR 7,000 (33.65/h); large enterprises and public sector MVR 8,000 (38.46/h). The Order itself publishes the hourly figures on a 48-hour week (208 h/month), so no 173.33 conversion is applied. Applied initially to Maldivian citizens only; extension to expatriate workers scheduled later. Both agents recall a revision under discussion / possibly effective 2024–25 with higher tiers but cannot confirm figures — treat 2022 rates as possibly superseded. Rate shown = top tier (large enterprise/public sector).", approved: "2026-09-11" },
  { lang: "English", cc: "MW", name: "Malawi", currency: "MWK", rate: 432.690, published: true, noSingleRate: true, note: "General national minimum wage raised to MWK 90,000/month effective 1 January 2024 (A recalls the prior figure as MWK 52,000 from 2022, B as 50,000 — the prior value is immaterial to the row), by ministerial notice under the Employment Act; a lower rate applies to domestic workers (~MWK 60,000/month per B) and the notice prints daily equivalents. Employment Act sets a 48-h normal week, so hourly derived on 48 × 52 ÷ 12 = 208 h (on 173.33 h it would be 519.24). 2025/26 revision not known. Arithmetic re-checked: 90,000 ÷ 208 = 432.692.", approved: "2026-09-11" },
  { lang: "Spanish", cc: "MX", name: "Mexico — Zona Libre de la Frontera Norte", currency: "MXN", rate: 55.109, published: true, noSingleRate: true, note: "Northern Border Free Zone (43 municipios in Baja California, Sonora, Chihuahua, Coahuila, Nuevo León, Tamaulipas): MXN 440.87/day effective 2026-01-01 (+5% from 419.88). Same CONASAMI resolution as the general rate; professional minimums are identical in both zones. Confidence: A high, B medium — lower kept.", approved: "2026-09-11" },
  { lang: "French", cc: "NE", name: "Niger", currency: "XOF", rate: 173.352, published: true, noSingleRate: false, note: "A and B agree: SMIG 30,047 XOF/month by 2012 decree (from 28,347); neither knows of a later private-sector revaluation (B notes public-sector increases announced 2023-24). Legal week 40 h (Loi 2012-45). Niger left ECOWAS in January 2025 (AES) but remains in the region.", approved: "2026-09-11" },
  { lang: "English", cc: "NF", name: "Australia — Norfolk Island", currency: "AUD", rate: 24.950, published: true, noSingleRate: false, note: "Fair Work Act 2009 extended to Norfolk Island from 1 July 2016 (Norfolk Island Legislation Amendment Act 2015); the mainland National Minimum Wage applies unchanged. Same 1 July 2026 caveat as the Australia row. A keyed this row cc=NF, B keyed it cc=AU — a keying difference only, rate and flags identical; NF kept so the row does not collide with Australia.", approved: "2026-09-11" },
  { lang: "Dutch", cc: "NL", name: "Netherlands", currency: "EUR", rate: 14.710, published: true, noSingleRate: false, note: "Statutory hourly minimum wage (wettelijk minimumuurloon, single hourly rate since 1 Jan 2024) for age 21+: EUR 14.71 from 1 January 2026 (EUR 14.06 Jan 2025, EUR 14.40 Jul 2025). Indexed every 1 January and 1 July; a 1 July 2026 uplift will have applied (B believes ~EUR 14.9–15.0, unconfirmed). Youth rates 15–20 are fixed percentages. Operator row is null; this fills it. A rates high, B medium — medium kept.", approved: "2026-09-11" },
  { lang: "Nepali", cc: "NP", name: "Nepal", currency: "NPR", rate: 89.000, published: true, noSingleRate: false, note: "A=B (rate, currency and flags identical; A tagged unit 'monthly', B 'hourly' — the gazette publishes all three, so the hourly is taken as published, not derived). National minimum remuneration fixed biennially by the Ministry of Labour, Employment and Social Security under s. 106 of the Labour Act 2074 (2017) by Nepal Gazette notice. From 1 Shrawan 2080 (17 July 2023): monthly NPR 17,300 (basic 10,820 + dearness allowance 6,480), daily NPR 667–668 (agents differ by 1 rupee on the daily), hourly NPR 89 — the hourly figure is the ministry's own. Check: 17,300 ÷ 26 d ÷ 7.5 h = 88.72 ≈ 89; note 17,300 ÷ 208 h (8-h day) would be 83.17, lower than the gazette's hourly. Both agents recall a biennial revision from 1 Shrawan 2082 (17 July 2025) at c. NPR 19,550/month but cannot confirm the gazetted daily/hourly figures, so the 2023 hourly is reported. Tea-estate workers have a separate lower rate. Fills the operator's NP Y/N null row.", approved: "2026-09-11" },
  { lang: "English", cc: "PG", name: "Papua New Guinea", currency: "PGK", rate: 3.500, published: true, noSingleRate: false, note: "National minimum wage PGK 3.50/h — Minimum Wages Board Determination 2014 raised the floor from K2.29 to K3.20 with phased steps to K3.36 and K3.50 (final step 2016; youth rate 75%). A new Minimum Wages Board review ran 2023-25; neither researcher is aware of a gazetted new determination — treat 3.50 as possibly superseded. A dates the row 2014 (determination), B 2016 (final step).", approved: "2026-09-11" },
  { lang: "Spanish", cc: "US", name: "United States — Puerto Rico", currency: "USD", rate: 10.500, published: true, noSingleRate: false, note: "ISO PR — a locality of the United States in this record. A and B agree. U.S. territory; the $7.25 FLSA floor applies (and still governs employees outside Act 47 coverage, e.g. certain agricultural/administrative categories), but the local statute is higher. Ley Núm. 47-2021 set $8.50 (1 Jan 2022), $9.50 (1 Jul 2023) and $10.50 (1 Jul 2024, confirmed by the Comisión Evaluadora de Salario Mínimo's mandatory decree). The Commission may decree further increases; neither researcher knows a confirmed figure above $10.50. Tipped workers follow the federal $2.13 cash wage with tip credit. Spanish and English co-official; Spanish is the working language of the statute. URL not fetched from this environment.", approved: "2026-09-11" },
  { lang: "Spanish", cc: "PY", name: "Paraguay", currency: "PYG", rate: 13937.730, published: true, noSingleRate: false, note: "A=B. Salario Mínimo Legal for non-specified activities: Gs 2,899,048/month from 1 Jul 2025 (Executive decree of June/July 2025, +3.5–3.6% over Gs 2,798,309 of Jul 2024; 2024's decree recalled by B as 1.938/2024), per Código del Trabajo (Ley 213/93) annual CPI-linked adjustment. MTESS publishes the jornal diario = monthly ÷ 26 = Gs 111,502; statutory day is 8 h (48 h/week, art. 194), so hourly = 111,502 ÷ 8 = 13,937.7, which equals monthly ÷ 208 h. Domestic workers equalised to 100% of the SML by Ley 6338/2019. Both flag that a July 2026 readjustment has very likely occurred (~Gs 3.0M) and cannot be confirmed. Operator holds PY as Y/N null.", approved: "2026-09-11" },
  { lang: "French", cc: "RE", name: "France — Réunion", currency: "EUR", rate: 11.880, published: true, noSingleRate: false, note: "French overseas department: the full metropolitan SMIC applies. €11.88 gross/hour from 1 November 2024 (Décret n° 2024-951), held for 1 January 2025. A 1 January 2026 indexation has very likely raised it (B recalls ~€12.02/h) but neither can confirm the decree. Operator holds FR null; this is the dependency row at the same rate as metropolitan France.", approved: "2026-09-11" },
  { lang: "Romanian", cc: "RO", name: "Romania", currency: "RON", rate: 24.496, published: true, noSingleRate: false, note: "RON 4,050 gross/month from 1 January 2025 (HG 1506/2024), which itself states RON 24.496/hour for an average 165.333 h month — statutory divisor. Construction sector floor 4,582 (B); agri-food aligned at 4,050. A 2026 freeze at 4,050 was reported late 2025, unconfirmed by either. Operator holds RO as a null-rate row; this fills beside it. URL unverified.", approved: "2026-09-11" },
  { lang: "Slovenian", cc: "SI", name: "Slovenia", currency: "EUR", rate: 7.372, published: true, noSingleRate: false, note: "EUR 1,277.72 gross/month from 1 January 2025 (1,253.90 in 2024), minister's notice in Uradni list each January. 2026 figure (~EUR 1,346 announced) unconfirmed by either; 2025 cited. No statutory divisor (payroll practice often 174 h). URL unverified.", approved: "2026-09-11" },
  { lang: "Slovak", cc: "SK", name: "Slovakia", currency: "EUR", rate: 5.259, published: true, noSingleRate: true, note: "2026: EUR 915 gross/month and EUR 5.259/hour (Act formula: 60% of the average wage two years prior; hourly = monthly ÷ 174 h per the Act). 2025 was 816 / 4.690 (high confidence). Six job-difficulty degrees multiply the base (Labour Code § 120) — degree 1 shown, hence no_single_rate. URL unverified.", approved: "2026-09-11" },
  { lang: "English", cc: "SL", name: "Sierra Leone", currency: "SLE", rate: 4.615, published: true, noSingleRate: false, note: "A and B agree: national minimum wage Le 800 (new leones, SLE)/month from 1 January 2023 (was Le 600 in 2020; Le 500,000 old leones under the 2015 Act). Neither can confirm whether the 2024-25 budgets raised it further (~Le 1,000 proposed). 40-h week (Employment Act 2023) → 173.33 h.", approved: "2026-09-11" },
  { lang: "French", cc: "TD", name: "Chad", currency: "XAF", rate: 346.160, published: true, noSingleRate: false, note: "A and B agree: SMIG raised from 25,480 to 60,000 XAF/month by 2011 decree (tripartite settlement); neither knows of a later statutory revaluation. B notes the Code du travail sets a 39-h non-agricultural week (169 h/month → 355.03/h); the operator-standard 173.33 h divisor is shown for comparability.", approved: "2026-09-11" },
  { lang: "French", cc: "TG", name: "Togo", currency: "XOF", rate: 302.890, published: true, noSingleRate: false, note: "A and B agree: SMIG raised from 35,000 to 52,500 XOF/month by decree of December 2022, effective 1 January 2023. Legal week 40 h (Loi 2021-012).", approved: "2026-09-11" },
  { lang: "Portuguese", cc: "TL", name: "Timor-Leste", currency: "USD", rate: 0.603, published: true, noSingleRate: false, note: "A (0.603) and B (0.6031) are the same quotient at different rounding — kept at 4 dp. National minimum wage USD 115/month set by Government Decree in June 2012 under the Labour Code (Law 4/2012 Art. 39); to both researchers' knowledge never formally revised despite National Labour Council / tripartite proposals (USD 150–200) circulating 2023–25 — if a revision took effect after their knowledge, this row is stale; verify no 2025–26 decree. Decree number unresolved (A: Government Decree No. 9/2012 of 6 June, unsure; B: No. 29/2012). Official languages Tetum and Portuguese; statutes published in Portuguese in the Jornal da República. Labour Code Art. 24: 8 h/day, 44 h/week → 44 × 52 ÷ 12 = 190.67 h. Fills the operator's null Y/N row if 2012 is accepted as still current.", approved: "2026-09-11" },
  { lang: "English", cc: "TT", name: "Trinidad and Tobago", currency: "TTD", rate: 22.500, published: true, noSingleRate: false, note: "National minimum wage TT$22.50/hour, published directly as hourly. Agents agree on the figure but not its effective date: A says 2024-01-01 (from 17.50, Order 2023); B says 2025-01-01 (from 20.50 since January 2024, Order 2024). B's two-step history (17.50 → 20.50 → 22.50) is the fuller account and is the as_of shown; verify the Order year. No later change known to either agent. Confidence: A high, B medium — lower kept.", approved: "2026-09-11" },
  { lang: "Chinese", cc: "TW", name: "Taiwan", currency: "TWD", rate: 196.000, published: true, noSingleRate: false, note: "Both agree: since the Minimum Wage Act (promulgated 27 Dec 2023, in force 1 Jan 2024) replaced the Labor Standards Act 'basic wage', the Minimum Wage Review Committee sets a monthly (full-time) and an hourly (part-time) rate each September. 2025: NT$28,590/month, NT$190/hour. 2026 (approved Sept 2025, effective 1 Jan 2026): NT$29,500/month, NT$196/hour. The hourly figure is a separately published statutory rate set above monthly ÷ hours (covers part-timers' rest-day pay), not a conversion. Operator's TW row is null — this fills it; confidence medium because the 2026 figures are from memory of the Sept 2025 decision.", approved: "2026-09-11" },
  { lang: "Ukrainian", cc: "UA", name: "Ukraine", currency: "UAH", rate: 51.881, published: true, noSingleRate: false, note: "The annual State Budget Law fixes both a monthly and an hourly minimum. 2025: UAH 8,000/month, 48.00/hour (both high confidence). 2026 Budget Law: UAH 8,647/month from 1 January 2026 (both medium); neither agent could read the law's own 2026 hourly line, so the figure is derived with the 166.67 h divisor implied by the 2025 pair. Arithmetic corrected from A's 51.9 to 51.881. Martial law in force; rate is national. Operator holds UA as a null-rate row; this fills beside it. URL unverified.", approved: "2026-09-11" },
  { lang: "English", cc: "US", name: "United States — District of Columbia", currency: "USD", rate: 17.950, published: true, noSingleRate: false, note: "A and B agree. Local statute far above the $7.25 FLSA floor. Fair Shot Minimum Wage Amendment Act of 2016 (D.C. Law 21-144) reached $15.00 on 1 Jul 2020, then indexes to CPI-U (Washington metro) every 1 July: $17.00 (2023) → $17.50 (2024) → $17.95 (2025). A further CPI adjustment was due 1 July 2026 and has almost certainly taken effect by today's date; neither researcher can vouch for that figure from memory, so the last verifiable figure (1 Jul 2025) is cited — the operator should check the DOES notice for the 2026 figure. Tipped minimum cash wage $10.00/h (Initiative 82 phase-in; the Council paused/modified the scheduled tipped-wage steps in 2025). URL not fetched from this environment.", approved: "2026-09-11" },
  { lang: "English", cc: "US", name: "United States — Federal (FLSA floor)", currency: "USD", rate: 7.250, published: true, noSingleRate: false, note: "A and B agree. Federal floor underlying every jurisdiction in this region: $7.25/h since 24 July 2009 (final step of the Fair Minimum Wage Act of 2007, P.L. 110-28). Tipped cash wage $2.13/h with tip credit. Applies directly as the floor in DC, Puerto Rico, Guam, USVI and CNMI (CNMI reached parity 30 Sep 2018); where a local statute is higher, the higher rate governs (DC, PR, GU, VI). American Samoa is the sole exception (special industry rates under FLSA §6(a)(3), see AS row). Cross-check of the operator's US — Austin, Texas row (7.250): Texas adopts the federal rate, so the figures coincide. URL not fetched from this environment.", approved: "2026-09-11" },
  { lang: "English", cc: "US", name: "United States — U.S. Virgin Islands", currency: "USD", rate: 10.500, published: true, noSingleRate: false, note: "ISO VI — a locality of the United States in this record. A and B agree. U.S. territory; the $7.25 FLSA floor applies, local statute is higher. Act No. 7856 (2016) stepped the territorial rate to $8.35 (1 Jun 2016), $9.50 (1 Jun 2017) and $10.50 (1 Jun 2018). Tipped (tourist service and restaurant) employees: cash wage of 40% of the minimum = $4.20/h with tip credit. The Act directed a Wage Board to review the rate; no subsequent legislated or published step is known to either researcher. URL not fetched from this environment.", approved: "2026-09-11" },
  { lang: "English", cc: "WS", name: "Samoa", currency: "WST", rate: 3.000, published: true, noSingleRate: false, note: "Private-sector minimum wage WST 3.00/h from 2020 (from WST 2.60; 2.30 in 2015). Effective date differs between researchers (A: 1 July 2020; B: 1 January 2020) — not a rate difference; as_of given as the year. Both recall a later increase (reported WST 4.00/h, July 2024) that neither can confirm; treat 3.00 as possibly superseded.", approved: "2026-09-11" },
  { lang: "Albanian", cc: "XK", name: "Kosovo", currency: "EUR", rate: 2.019, published: true, noSingleRate: false, note: "New Law on Minimum Wage (adopted by the Assembly 2024) set a single EUR 350 gross/month floor, replacing the 2011 age-tiered 130/170. Both agents believe it applied from 2025 (B: 1 January 2025) but cannot confirm the exact entry-into-force date. Kosovo is partially recognised; XK is the user-assigned code. 40 h week. URL unverified.", approved: "2026-09-11" },
]

/**
 * The key of a ROW. The operator's rows keep `lang:cc` (elections and ledgers already hold those ids); an APPROVED row
 * that would collide with one of his — the federal floor beside Austin, a fill beside his NULL — carries its name too, so
 * no row can ever overwrite another in the index.
 */
const slug = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
export const regionId = (r: Pick<RegionRate, "lang" | "cc"> & { name?: string; approved?: string }): string =>
  r.approved ? `${r.lang}:${r.cc}:${slug(r.name ?? "")}` : `${r.lang}:${r.cc}`;

/**
 * O(1) row lookup. This was `REGION_RATES.find(r => regionId(r) === id)` — a 114-row scan building a string per row,
 * on every render, and now called once per pod member. Built once at module load instead.
 */
const REGION_INDEX: ReadonlyMap<string, RegionRate> = (() => {
  const m = new Map<string, RegionRate>();
  for (const r of REGION_RATES) if (!m.has(regionId(r))) m.set(regionId(r), r);   // first wins; the operator's rows come first
  return m;
})();
export const findRegion = (id: string): RegionRate | undefined => REGION_INDEX.get(id);

/**
 * unit.settle's settlement ladder, derived from each row's own two flags. Counting the table this way reproduces the
 * paper's published partition exactly — 29 / 37 / 35 / 13 — which is how the transcription was verified.
 */
export type SettleTier = "published" | "pending" | "no_single_rate" | "no_official_rate";
export function tierOf(r: RegionRate): SettleTier {
  if (r.rate !== null) return "published";
  if (!r.published) return "no_official_rate";
  return r.noSingleRate ? "no_single_rate" : "pending";
}

/** What to tell a person whose region cannot settle yet — never a figure, never zero, always what is missing. */
export const TIER_REASON: Record<SettleTier, string> = {
  published: "",
  pending: "A national rate exists but is not yet loaded here. Recoverable by data entry, not by policy.",
  no_single_rate: "Rates here are sectoral, regional or collectively bargained. A published selection rule is required.",
  no_official_rate: "No statutory minimum exists at any level. Settles under the Global Agreed Standard.",
};

/**
 * JURISDICTIONS — the 106 distinct PLACES behind the 114 rows.
 *
 * OPERATOR RULING, 2026-09-11 (docs/asks/2026-09-11_election_of_locality.md): "ensure optimized and includes
 * election of locality and regional min wage." Six countries appear more than once as the SAME jurisdiction under
 * different languages — Switzerland three times, Belgium, the DRC, Cyprus, Finland and Singapore twice — every one
 * with the same rate. Offering those repeatedly makes a person choose a LANGUAGE in order to be given a WAGE. They
 * elect a place; the language comes from the app's own 33-language selector.
 *
 * No row is lost: a jurisdiction keeps every language it is published under, and the gate reconciles 106 back to 114.
 */
export interface Jurisdiction {
  id: string;              // the canonical row's regionId — what a member elects
  cc: string;              // ISO 3166-1 alpha-2
  name: string;            // the full published name, e.g. "Canada — Québec"
  country: string;         // the part before the em dash, e.g. "Canada"
  locality: string | null; // the part after it, e.g. "Québec" — null where the row names no locality
  currency: string;
  rate: number | null;
  tier: SettleTier;
  note: string;
  langs: string[];         // every language this jurisdiction is published under
  /**
   * Where the figure comes from. The operator's 2026-09-10 table is the reference; `hi_rates.py` is the table the paper
   * itself names as "the live settlement table" (fund.token), mirrored in lib/min-wage.ts — 50 US states and 9 countries
   * in USD. Both are kept verbatim; neither is edited to agree with the other.
   */
  source: "operator-2026-09-10" | "approved-2026-09-11" | "hi_rates.py";
  /** The USD figure hi_rates.py holds for the same country, where the operator's row is in local currency. Never converted. */
  usdMirror: number | null;
  /** True when the PLACE was created from one of the operator's own rows — unchanged by a later approved fill. */
  fromOperator: boolean;
}

/** "Canada — Québec" → ["Canada", "Québec"]. The em dash is the paper's own separator. */
const splitName = (name: string): [string, string | null] => {
  const i = name.indexOf(" — ");
  return i < 0 ? [name, null] : [name.slice(0, i), name.slice(i + 3)];
};

export const JURISDICTIONS: Jurisdiction[] = (() => {
  const byName = new Map<string, Jurisdiction>();
  for (const r of REGION_RATES) {
    const key = `${r.cc}|${r.name}`;
    const found = byName.get(key);
    if (found) {
      if (!found.langs.includes(r.lang)) found.langs.push(r.lang);
      // AN APPROVED FILL REPLACES THE OPERATOR'S NULL (Rule B loads fills; a cross-check of his numeric row is never
      // loaded, so a figure here can only be filling a NULL). His row stays in REGION_RATES verbatim; the PLACE settles.
      if (r.approved && found.rate === null && r.rate !== null) {
        found.rate = r.rate; found.currency = r.currency; found.tier = tierOf(r); found.note = r.note; found.source = "approved-2026-09-11"; found.id = regionId(r);
      }
      continue;
    }
    const [country, locality] = splitName(r.name);
    byName.set(key, {
      id: regionId(r), cc: r.cc, name: r.name, country, locality,
      currency: r.currency, rate: r.rate, tier: tierOf(r), note: r.note, langs: [r.lang],
      source: r.approved ? "approved-2026-09-11" : "operator-2026-09-10", usdMirror: COUNTRY_RATES[country] ?? null,
      fromOperator: !r.approved,
    });
  }
  const out = Array.from(byName.values());
  // THE REGION, NOT THE WIDER COUNTRY (fund.token): "The anchor is always the posted minimum wage of the region the
  // contributor lives in." hi_rates.py carries the 50 US state floors the operator's table does not — a Californian's
  // posted floor is $16.00, not Texas's $7.25 — so each state is a locality of the United States, tagged with its source.
  for (const [state, rate] of Object.entries(US_STATE_RATES)) {
    out.push({
      id: `hi_rates:US-${state.replace(/\s+/g, "_")}`, cc: "US", name: `United States — ${state}`, country: "United States",
      locality: state, currency: "USD", rate, tier: "published", note: "State rate — hi_rates.py (the live settlement table)",
      langs: ["English"], source: "hi_rates.py", usdMirror: rate, fromOperator: false,
    });
  }
  // Cambodia is in both existing tables and absent from the operator's 103 — merged in with its source, and flagged.
  for (const [country, rate] of Object.entries(COUNTRY_RATES)) {
    if (out.some((j) => j.country === country)) continue;
    const cc = country === "Cambodia" ? "KH" : country.slice(0, 2).toUpperCase();
    out.push({
      id: `hi_rates:${cc}`, cc, name: country, country, locality: null, currency: "USD", rate, tier: "published",
      note: "Country rate — hi_rates.py; not in the operator's 2026-09-10 table (flagged)", langs: ["English"],
      source: "hi_rates.py", usdMirror: rate, fromOperator: false,
    });
  }
  return out;
})();

/** The pre-existing region detector's result → the jurisdiction it names here, or undefined when it names none. */
export function jurisdictionFromResolved(r: ResolvedRegion | null | undefined): Jurisdiction | undefined {
  if (!r) return undefined;
  if (r.state) return JURISDICTIONS.find((j) => j.cc === "US" && j.locality === r.state);
  return JURISDICTIONS.find((j) => j.country === r.country && j.rate !== null) ?? JURISDICTIONS.find((j) => j.country === r.country);
}

const JURIS_INDEX: ReadonlyMap<string, Jurisdiction> = new Map(JURISDICTIONS.map((j) => [j.id, j]));
export const findJurisdiction = (id: string): Jurisdiction | undefined => JURIS_INDEX.get(id);

/**
 * The four settlement tiers, grouped ONCE at module load. This was four `.filter(r => tierOf(r) === tier)` passes
 * rebuilt on every render in two places — 456 tierOf calls per render per picker, about to be tripled by per-member
 * election. Now it is a lookup.
 */
export const BY_TIER: Readonly<Record<SettleTier, Jurisdiction[]>> = (() => {
  const g: Record<SettleTier, Jurisdiction[]> = { published: [], pending: [], no_single_rate: [], no_official_rate: [] };
  for (const j of JURISDICTIONS) g[j.tier].push(j);
  return g;
})();

/** The tier headings, in the paper's own order. */
export const TIER_ORDER: readonly SettleTier[] = ["published", "pending", "no_single_rate", "no_official_rate"];
export const TIER_LABEL: Record<SettleTier, string> = {
  published: "Published rate",
  pending: "Rate exists, not yet loaded",
  no_single_rate: "No single national rate",
  no_official_rate: "No official rate",
};

/**
 * ELECTION OF LOCALITY, step two. The jurisdictions within one country, when the paper publishes more than one.
 * Today that is Canada (Federal · Québec) and India (national · West Bengal · Punjab) — everywhere else a country is
 * one place and the election is a single click. Derived, so a locality row added later just works.
 */
const BY_COUNTRY: ReadonlyMap<string, Jurisdiction[]> = (() => {
  const m = new Map<string, Jurisdiction[]>();
  for (const j of JURISDICTIONS) (m.get(j.cc) ?? m.set(j.cc, []).get(j.cc)!).push(j);
  return m;
})();
export const localitiesOf = (cc: string): Jurisdiction[] => {
  const all = BY_COUNTRY.get(cc) ?? [];
  return all.length > 1 ? all : [];
};

/** One entry per country for the first step of the election — the jurisdiction that carries a rate, where one does. */
export const COUNTRIES: Jurisdiction[] = Array.from(BY_COUNTRY.values())
  .map((js) => js.find((j) => j.rate !== null) ?? js[0]);

/** The jurisdiction a country resolves to before any locality is chosen — the one that publishes a rate, if any. */
const COUNTRY_DEFAULT: ReadonlyMap<string, Jurisdiction> = new Map(COUNTRIES.map((j) => [j.cc, j]));
export const defaultForCountry = (cc: string): Jurisdiction | undefined => COUNTRY_DEFAULT.get(cc);

/** Countries grouped by settlement tier, for the first step of the election. Precomputed, like BY_TIER. */
export const COUNTRIES_BY_TIER: Readonly<Record<SettleTier, Jurisdiction[]>> = (() => {
  const g: Record<SettleTier, Jurisdiction[]> = { published: [], pending: [], no_single_rate: [], no_official_rate: [] };
  for (const j of COUNTRIES) g[j.tier].push(j);
  return g;
})();

/**
 * D9 IN FULL (unit.regional, r272): "At settlement the payout takes the greater of two values from the same jurisdiction's
 * table: the vintage-locked rate at earning, or the current rate at settlement — a floor, never a ceiling, so time can only
 * preserve or improve real buying power … A contributor who relocates keeps the earning jurisdiction's vintage by
 * default; converting to the new schedule at settlement is an explicit election, closing jurisdiction-shopping."
 *
 * Grok, open.external #15: the figure moves only because a statutory wage moved. No conversion between currencies —
 * a relocation election settles on the NEW schedule at its current rate; it is never a max across two currencies.
 */
export interface D9Settlement { amount: number | null; rate: number | null; which: "vintage" | "current" | "equal" | "relocated" | "none"; currency: string | null }
export function settleD9(yug: number, vintage: { rate: number | null; currency: string | null } | null, current: Jurisdiction | undefined): D9Settlement {
  if (!(yug > 0)) return { amount: null, rate: null, which: "none", currency: null };
  const cur = current && current.rate !== null ? current.rate : null;
  const vin = vintage && vintage.rate !== null ? vintage.rate : null;
  if (vin !== null && vintage?.currency && current && current.currency !== vintage.currency) {
    // relocation: an explicit election onto another schedule — its current rate, never a cross-currency max
    return cur === null ? { amount: null, rate: null, which: "none", currency: current.currency }
                        : { amount: yug * cur, rate: cur, which: "relocated", currency: current.currency };
  }
  if (vin === null && cur === null) return { amount: null, rate: null, which: "none", currency: current?.currency ?? vintage?.currency ?? null };
  const rate = Math.max(vin ?? -Infinity, cur ?? -Infinity);
  const which = vin === null ? "current" : cur === null ? "vintage" : vin === cur ? "equal" : vin > cur ? "vintage" : "current";
  return { amount: yug * rate, rate, which, currency: current?.currency ?? vintage?.currency ?? null };
}

/**
 * The two decisions only the operator can take, exactly as the register records them (open.decisions, open since r57,
 * both "Blocks operation"). Shown as PROPOSALS on the rows they govern; nothing settles under them until ruled.
 */
export const OPEN_DECISION: Partial<Record<SettleTier, string>> = {
  no_single_rate: "D1, open since r57 — recommended default: the lowest generally-applicable adult rate in the contributor's own region, published with its source. Unsettled until the operator rules; blocks operation.",
  no_official_rate: "D2, open since r57 — the Global Agreed Standard: pegged to a published international reference, peg Stable, value Adaptive, reviewed annually. Unsettled until the operator rules; blocks operation.",
  pending: "Recoverable by data entry: a national rate exists and is not yet loaded here.",
};

/**
 * Settlement — `$ = 웃 × the region's hourly minimum wage`, in that region's own currency.
 * Returns null when the region publishes no rate: no contributor settles at zero, and no figure is guessed.
 */
export function settleInRegion(yug: number, r: { rate: number | null } | undefined): number | null {
  if (!r || r.rate === null || !(yug > 0)) return null;
  return yug * r.rate;
}

/**
 * Format an amount in its own currency. Falls back to "<code> <amount>" where a runtime has no data for the code —
 * printing the code is honest; substituting a symbol from another currency would not be.
 */
export function formatLocal(amount: number, currency: string, locale = "en"): string {
  try {
    return new Intl.NumberFormat(locale, { style: "currency", currency, maximumFractionDigits: 2 }).format(amount);
  } catch {
    return `${currency} ${amount.toLocaleString(locale, { maximumFractionDigits: 2 })}`;
  }
}

/** The pod's default region — the paper's own worked example throughout is the Texas vintage (unit.ceiling). */
export const DEFAULT_REGION_ID = "English:US";
