import { fromLedgerJson, type LedgerInput } from "@/lib/2525-core/revisions";

/** SensorFusion-2525 only. Not the Financial-2525 ledger. */
export const SENSOR_FUSION_LEDGER: LedgerInput = {
  section: "SensorFusion-2525",
  route: "/SensorFusion-2525",
  note: "Append-only. This record is for Sensor Fusion · 2525 and no other surface.",
  entries: [
    {
      rev: 1,
      date: "2026-10-02",
      kind: "ask",
      text: "Sensor Fusion · 2525 is accessible from multiple devices: a Windows PC, an Android phone, an iPhone, a Raspberry Pi, or Ubuntu. The System Operator signs in on the device, then turns the camera on.",
      commit: "5141b16",
    },
    {
      rev: 2,
      date: "2026-10-02",
      kind: "decision",
      text: "The public link is /SensorFusion-2525. /main stays the hub page. The folder is Home/SensorFusion. Windows uses a backslash.",
      commit: "5141b16",
    },
    {
      rev: 3,
      date: "2026-10-02",
      kind: "release",
      text: "The page opens with log in, device choice, SENSOR 1, annotate, and the session colors, including the Atlantis Accords and Vision • 2525. Pictures stay on the device until a trainer is connected.",
      commit: "5141b16",
    },
    {
      rev: 4,
      date: "2026-10-02",
      kind: "release",
      text: "The R-CORE target sits at the bottom of Sensor Fusion · 2525. The first click shows the icon with the word art. The second click opens version history for SensorFusion-2525 only.",
      commit: "",
    },
    {
      rev: 5,
      date: "2026-10-02",
      kind: "release",
      text: "The page uses the Raspberry Pi screen: SENSOR 1 in the top bar, one camera, and the model list as a dropdown. The menu starts Sensor Fusion or Check ID with Coral or without it. Pose is not in the app. The same downloadable app runs on a Raspberry Pi, Ubuntu, or a Windows PC. The phone uses this page.",
      commit: "",
    },
    {
      rev: 6,
      date: "2026-10-02",
      kind: "release",
      text: "Download is the same full-screen file as the page you can open. It runs on a Raspberry Pi, Ubuntu, a Windows PC, an iPhone, or an Android phone. Pose is not designed yet.",
      commit: "",
    },
    {
      rev: 7,
      date: "2026-10-03",
      kind: "release",
      text: "A phone or a PC runs detect.tflite in the browser, the same way the Python script does: resize the frame, run the model, draw the box and the name. Coral's file stays on a computer that has the chip.",
      commit: "",
    },
    {
      rev: 8,
      date: "2026-10-03",
      kind: "release",
      text: "Held upright, the controls stay under the camera. Turned sideways, the camera keeps the height and the controls sit beside it.",
      commit: "",
    },
    {
      rev: 9,
      date: "2026-10-03",
      kind: "release",
      text: "The download button saves the program the same way Vision-2525 saves its page. The phone stores the file. Each run pulls the latest copy into Home/SensorFusion.",
      commit: "4d6736d",
    },
    {
      rev: 10,
      date: "2026-10-03",
      kind: "release",
      text: "The controls sit on one line under the picture, including when the phone is sideways. Info opens the Raspberry Pi menu labels.",
      commit: "2190ca8",
    },
    {
      rev: 11,
      date: "2026-10-03",
      kind: "release",
      text: "Tap the picture, or press F, to show the frame rate. The file path and the yellow running line are gone. The download mark matches Vision-2525.",
      commit: "ccc8ee6",
    },
    {
      rev: 12,
      date: "2026-10-03",
      kind: "release",
      text: "Tap Demo.90 and the model list opens above the bar. It was there before, but the bar was cutting it off.",
      commit: "52f9cb2",
    },
    {
      rev: 13,
      date: "2026-10-03",
      kind: "release",
      text: "In the image labeler, each side of the box has a dot outside the line. Left and right move sideways. Top and bottom move up and down.",
      commit: "8b183bc",
    },
    {
      rev: 14,
      date: "2026-10-03",
      kind: "release",
      text: "Capture saves video frames as numbered pictures in a SensorFusion folder. Android asks you to create that folder, then choose it.",
      commit: "5513816",
    },
    {
      rev: 15,
      date: "2026-10-03",
      kind: "release",
      text: "The accuracy meter is the thin bar on the left of the video. Capture takes pictures from the sensor or from this device. Annotate opens those pictures.",
      commit: "72a1ee9",
    },
    {
      rev: 16,
      date: "2026-10-03",
      kind: "release",
      text: "Capture, Annotate, and Upload are separate. Sensor pictures and phone pictures go in one set. Names continue, such as head.0001.jpg, and do not start over. Upload does not send the pictures anywhere.",
      commit: "538de1a",
    },
    {
      rev: 17,
      date: "2026-10-03",
      kind: "release",
      text: "Training uses the six icons from the original training video: capture video, add annotations, upload images, develop models, download the model, and run live. Develop, download, and run live are not connected yet.",
      commit: "95f8156",
    },
    {
      rev: 18,
      date: "2026-10-03",
      kind: "release",
      text: "Each training step is a button with the icon from the original training video. Capture, Annotate, and Upload run. Develop, Download, and Run Live say they are not connected yet.",
      commit: "fb56262",
    },
    {
      rev: 19,
      date: "2026-10-03",
      kind: "release",
      text: "The training icons are the buttons. There is no text card around them. Capture, Annotate, and Upload are the first three icons on the bar. The Train icon opens all six.",
      commit: "ff59939",
    },
    {
      rev: 20,
      date: "2026-10-03",
      kind: "release",
      text: "The six training steps are line icons in the page colour. Capture Images, Annotate, Upload, and Run Live use them. A strip shows the current step. A 45–60 second capture keeps one frame every half second. Training does not start until a server is chosen.",
      commit: "d67072a",
    },
    {
      rev: 21,
      date: "2026-10-03",
      kind: "correction",
      text: "The model button uses the original cube icon again. The line icon stays on the training steps.",
      commit: "0be3cc9",
    },
    {
      rev: 22,
      date: "2026-10-03",
      kind: "release",
      text: "R1. One model list, models.json, version 1. The page, the browser detector, and both copies of the computer program read it. The name picker shows only that model's labels. Group projects, upload, and paid time wait on your decision.",
      commit: "c336aff",
    },
    {
      rev: 23,
      date: "2026-10-03",
      kind: "decision",
      text: "Each picture is edited as its own XML. JSON is written only after every box on those files is Level 2, and that JSON is for training.",
      commit: "02872b9",
    },
    {
      rev: 24,
      date: "2026-10-03",
      kind: "decision",
      text: "Pictures from the sensor and from this device are saved as PNG. JPEG changes the colours, so Light Codex cannot ride on it. The colour strip is still not painted onto the training picture.",
      commit: "c49a9d4",
    },
    {
      rev: 25,
      date: "2026-10-03",
      kind: "release",
      text: "R4a. A guest cannot read or add pictures or labels. A signed-in person can do so only for a project they belong to. A member of one project cannot see another.",
      commit: "0c25475",
    },
    {
      rev: 26,
      date: "2026-10-03",
      kind: "release",
      text: "Sensor Fusion is one menu row. Coral is a switch under Settings. Check ID stays a model inside that run, so the old with-Coral and no-Coral rows are gone.",
      commit: "3acb1d5",
    },
    {
      rev: 27,
      date: "2026-10-03",
      kind: "release",
      text: "The info button labels the Sensor Fusion screen that is open: camera, meter, model including Check ID, Capture, Annotate, and Upload. The old tutorial picture is gone.",
      commit: "f59aae1",
    },
    {
      rev: 28,
      date: "2026-10-03",
      kind: "release",
      text: "Settings opens with a Sensor Fusion section. Inside it, Edge Compute is CPU or Coral.",
      commit: "26d9d12",
    },
    {
      rev: 29,
      date: "2026-10-03",
      kind: "release",
      text: "The member rule runs with the site build. The screen says only that the boxes stay on this device. Only the server can add a member. A live guest check runs once that rule is on the database.",
      commit: "48c6b03",
    },
    {
      rev: 30,
      date: "2026-10-03",
      kind: "release",
      text: "Edge Compute sits at the top of Settings. The choices are CPU and CORAL. CPU is the default.",
      commit: "80e6a1c",
    },
    {
      rev: 31,
      date: "2026-10-03",
      kind: "release",
      text: "Sensor 1 can use the iPhone 12 Pro Max back cameras: 1 wide, 2 ultra, 3 tele. Front stays available.",
      commit: "",
    },
    {
      rev: 32,
      date: "2026-10-03",
      kind: "release",
      text: "CPU is the default and the switch reads CPU CORAL. A new screen starts on the original Sensor Fusion green. A color choice changes the screen.",
      commit: "0140439",
    },
    {
      rev: 33,
      date: "2026-10-03",
      kind: "release",
      text: "A box named ??? is not drawn. Annotate starts on the open model's names. Capture from the sensor turns the camera on. Save, Level 2, Merge, and Share stay on one line.",
      commit: "37df2c1",
    },
    {
      rev: 34,
      date: "2026-10-04",
      kind: "release",
      text: "The menu shows four rows again: Sensor Fusion, Stop, Image labeler, and Pose. An empty model list can no longer hide them.",
      commit: "b86dc67",
    },
    {
      rev: 35,
      date: "2026-10-04",
      kind: "release",
      text: "Alerts are a setting. They start on. A found object shows only while Alerts is on. There is no school-alert mode.",
      commit: "4be0652",
    },
    {
      rev: 36,
      date: "2026-10-04",
      kind: "release",
      text: "Cameras read 0.5x, Wide, 2.5x, and Front. Capture asks where to save. The annotate box fits on the screen.",
      commit: "bac70a6",
    },
    {
      rev: 37,
      date: "2026-10-04",
      kind: "release",
      text: "The XML is saved next to the picture. A saved box comes back. A name with & reads back correctly. Level 2 is Accept, Fix, or Reject by a different person. The first box is smaller.",
      commit: "fea6971",
    },
    {
      rev: 38,
      date: "2026-10-04",
      kind: "release",
      text: "Nineteen review passes. The picture fits in landscape. A fix updates the same box. Files save once. A review must be a different person. Added pictures use the same names as capture.",
      commit: "2f58089",
    },
    {
      rev: 39,
      date: "2026-10-04",
      kind: "release",
      text: "The next picture is one past the last file in the folder. head_1111.png is followed by head_1112.png. head_3333.png is followed by head_3334.png.",
      commit: "5dd25c8",
    },
    {
      rev: 40,
      date: "2026-10-04",
      kind: "release",
      text: "Info opens one still picture with five Demo.90 objects: person, bicycle, car, dog, and traffic light. The tool line stays short. The gear stays in settings.",
      commit: "fdd707e",
    },
    {
      rev: 41,
      date: "2026-10-04",
      kind: "correction",
      text: "Saving an annotated picture says where the file went and that the boxes stay on this device. Revision 38 had dropped the second half, so the build check stopped every deploy.",
      commit: "ed4af60",
    },
    {
      rev: 42,
      date: "2026-10-05",
      kind: "release",
      text: "Info opens the Austin street photo. Each Demo.90 object has a box and a tag from the real model run: person 77%, person 68%, bicycle 69%, car 75%, dog 77%, traffic light 77%. The live camera now names objects right. A traffic light no longer reads boat. SAVE BOX adds a new box each time. Fix still changes the same box. A name with & or quotes reads back as written. Every dialog fits a phone held sideways and closes with Escape or a tap outside. With SENSOR 1 off, the alert and the boxes leave the screen. Back on the camera screen, the picture shows again.",
      commit: "b108692",
    },
    {
      rev: 43,
      date: "2026-10-05",
      kind: "release",
      text: "The labeler scrolls. Every box row, the film strip and SAVE BOX can be reached on a phone held upright or sideways. SAVE BOX, LEVEL 2, MERGE and FILES stay at the bottom while the rest scrolls. SAVE BOX refuses a box that is already saved. Each saved box shows its number and name on the picture, and its row reads Box 3 · person · labeled. A tap on a row lights its box. Accept, Fix and Reject are big enough for a thumb. One capture runs at a time, so a double tap no longer saves the same names twice. How many takes 1 to 12 and says so. The saved note says what happened, such as Shared 4 pictures, and lists at most three names. Upload keeps its own title and is not ticked, because nothing is uploaded yet. With CORAL picked, Settings says Coral runs on a computer with the Coral chip and this page uses the processor. Settings and the model list close with Escape.",
      commit: "3f9bc4e",
    },
    {
      rev: 44,
      date: "2026-10-05",
      kind: "release",
      text: "Info keeps the Austin picture and the Demo.90 boxes. The words under it are the Sensor Fusion menu: Sensor Fusion, Stop, Image labeler, Pose, Coral as a switch, Check ID in the list, and the six training steps.",
      commit: "8e12609",
    },
    {
      rev: 45,
      date: "2026-10-05",
      kind: "release",
      text: "Info is one screen, the same as the camera. The Austin picture sits in the center with the Demo.90 boxes. Sensor 1, the bar, FPS, and the bottom buttons stay. Held sideways, the badge is hidden and the picture uses the room that is left.",
      commit: "8d2e855",
    },
    {
      rev: 46,
      date: "2026-10-05",
      kind: "release",
      text: "On a computer, and with the phone sideways, the camera fills the screen. The camera list and the model list are short, so the boxes stay visible. The info picture keeps its boxes on the objects when the screen is wide.",
      commit: "8fcdbf7",
    },
    {
      rev: 47,
      date: "2026-10-05",
      kind: "release",
      text: "The R-CORE icon sits on its own row, just above the buttons. On a computer the button words and the box names stay one size, so they do not grow with the picture.",
      commit: "9a04962",
    },
    {
      rev: 48,
      date: "2026-10-05",
      kind: "release",
      text: "The buttons sit at the bottom of the screen. The R-CORE icon lies on the picture, just above them. Box names are drawn at the screen's own size, so they stay sharp on a computer.",
      commit: "5843db1",
    },
    {
      rev: 49,
      date: "2026-10-05",
      kind: "release",
      text: "Capture Images opens on Live. The camera shows 1 / 4 as each picture is saved. A video can be chosen instead, and the person says every other frame or every third, and how many pictures to keep.",
      commit: "5843db1",
    },
    {
      rev: 50,
      date: "2026-10-05",
      kind: "release",
      text: "After you choose how many pictures, Live asks how often: 1 to 6 a second, or one every 2 or 3 seconds. It says how many seconds that takes. The camera waits that long, so the pictures are not all the same.",
      commit: "2f9903a",
    },
    {
      rev: 51,
      date: "2026-10-05",
      kind: "release",
      text: "When the name is already on the box, it is not repeated on a bar across the picture. With names off, the one name being read sits under the meter, only as wide as the words.",
      commit: "bd5c35e",
    },
    {
      rev: 52,
      date: "2026-10-05",
      kind: "release",
      text: "The info picture points at each control. SENSOR 1, the camera name, the bar, FPS, the box, %, Labels, the model, Capture, Annotate, and Upload each say what they do. On a narrow screen the notes stay off the picture.",
      commit: "a50a32a",
    },
    {
      rev: 53,
      date: "2026-10-05",
      kind: "release",
      text: "The opening menu is this device, then Sensor Fusion, Stop, and Pose. Annotate stays on the camera screen. A label is a name you type. Capture shows the camera only, with no boxes. The picture fills the annotate screen.",
      commit: "2ad2183",
    },
    {
      rev: 54,
      date: "2026-10-05",
      kind: "release",
      text: "The device card keeps its name and its line apart when it is selected. The page picks the device from the computer or phone in your hand.",
      commit: "f28bee6",
    },
    {
      rev: 55,
      date: "2026-10-05",
      kind: "release",
      text: "A tap does not change what the page found. A Windows computer stays a Windows computer. Raspberry Pi is chosen only when the machine says it is one.",
      commit: "fbae0d4",
    },
    {
      rev: 56,
      date: "2026-10-05",
      kind: "release",
      text: "Annotate fits the whole picture in the window, the way LabelImg does. A picture that already has a box opens with the corners on that box.",
      commit: "8274729",
    },
    {
      rev: 57,
      date: "2026-10-05",
      kind: "release",
      text: "Level 1 is XML. Level 2 is XML. One JSON packet is written only after every picture in the open project has both.",
      commit: "2cb13b1",
    },
    {
      rev: 58,
      date: "2026-10-05",
      kind: "release",
      text: "Info starts quiet. Tap a control and only that note appears.",
      commit: "7d9a98c",
    },
    {
      rev: 59,
      date: "2026-10-05",
      kind: "release",
      text: "An info note sits next to the control you tap. SENSOR 2 opens a second camera beside SENSOR 1 when the phone allows two at once.",
      commit: "5285e1b",
    },
    {
      rev: 60,
      date: "2026-10-05",
      kind: "release",
      text: "Two cameras stack top and bottom when the phone is upright, and sit side by side when the phone or the computer is sideways.",
      commit: "df3db25",
    },
    {
      rev: 61,
      date: "2026-10-05",
      kind: "release",
      text: "THERMAL takes the second view and says the thermal camera is not connected. It does not use the phone camera as heat.",
      commit: "70f74be",
    },
    {
      rev: 62,
      date: "2026-10-05",
      kind: "release",
      text: "SENSOR 2 is one list: Camera, Thermal, Lidar, Ultrasonic, Radar, and Sonar. Only Camera opens a picture. The others say they are not connected, and name Phone, MASS-AI, or Manta.",
      commit: "cb2d9f7",
    },
    {
      rev: 63,
      date: "2026-10-05",
      kind: "release",
      text: "On a phone held upright, the sensor names wrap onto a second line instead of sitting on top of each other. A note on the second camera sits along the bottom of that picture.",
      commit: "d7963ec",
    },
    {
      rev: 64,
      date: "2026-10-05",
      kind: "release",
      text: "Thermal, lidar, ultrasonic, radar, and sonar stay hidden until a device with that name is connected. On a phone, two cameras are kept only if both stay on at a small size and a slow rate. If not, SENSOR 2 goes away and the phone stays on one camera.",
      commit: "6208434",
    },
    {
      rev: 65,
      date: "2026-10-05",
      kind: "release",
      text: "The six training marks are the original pictures: capture, annotate, upload, develop, download, and run live. The annotate mark is the corner box with the plus.",
      commit: "5614877",
    },
    {
      rev: 66,
      date: "2026-10-05",
      kind: "release",
      text: "Capture uses the same dark button as Annotate and Upload. The camera mark stays cyan, and the words sit centered under it.",
      commit: "8c81059",
    },
  ],
};

export const SENSOR_FUSION_RCORE_HISTORY = fromLedgerJson(SENSOR_FUSION_LEDGER);
