import { fromLedgerJson, type LedgerInput } from "@/lib/2525-core/revisions";

/** SensorFusion-2525 only. Not the Financial-2525 ledger. */
export const SENSOR_FUSION_LEDGER: LedgerInput = {
  section: "SensorFusion-2525",
  route: "/SensorFusion-2525",
  note: "Append-only. This record is for Sensor Fusion · 2525 and no other surface.",
  entries: [
    {
      rev: 1,
      date: "2026-10-02",
      kind: "ask",
      text: "Sensor Fusion · 2525 is accessible from multiple devices: a Windows PC, an Android phone, an iPhone, a Raspberry Pi, or Ubuntu. The System Operator signs in on the device, then turns the camera on.",
      commit: "5141b16",
    },
    {
      rev: 2,
      date: "2026-10-02",
      kind: "decision",
      text: "The public link is /SensorFusion-2525. /main stays the hub page. The folder is Home/SensorFusion. Windows uses a backslash.",
      commit: "5141b16",
    },
    {
      rev: 3,
      date: "2026-10-02",
      kind: "release",
      text: "The page opens with log in, device choice, SENSOR 1, annotate, and the session colors, including the Atlantis Accords and Vision • 2525. Pictures stay on the device until a trainer is connected.",
      commit: "5141b16",
    },
    {
      rev: 4,
      date: "2026-10-02",
      kind: "release",
      text: "The R-CORE target sits at the bottom of Sensor Fusion · 2525. The first click shows the icon with the word art. The second click opens version history for SensorFusion-2525 only.",
      commit: "",
    },
    {
      rev: 5,
      date: "2026-10-02",
      kind: "release",
      text: "The page uses the Raspberry Pi screen: SENSOR 1 in the top bar, one camera, and the model list as a dropdown. The menu starts Sensor Fusion or Check ID with Coral or without it. Pose is not in the app. The same downloadable app runs on a Raspberry Pi, Ubuntu, or a Windows PC. The phone uses this page.",
      commit: "",
    },
    {
      rev: 6,
      date: "2026-10-02",
      kind: "release",
      text: "Download is the same full-screen file as the page you can open. It runs on a Raspberry Pi, Ubuntu, a Windows PC, an iPhone, or an Android phone. Pose is not designed yet.",
      commit: "",
    },
    {
      rev: 7,
      date: "2026-10-03",
      kind: "release",
      text: "A phone or a PC runs detect.tflite in the browser, the same way the Python script does: resize the frame, run the model, draw the box and the name. Coral's file stays on a computer that has the chip.",
      commit: "",
    },
    {
      rev: 8,
      date: "2026-10-03",
      kind: "release",
      text: "Held upright, the controls stay under the camera. Turned sideways, the camera keeps the height and the controls sit beside it.",
      commit: "",
    },
    {
      rev: 9,
      date: "2026-10-03",
      kind: "release",
      text: "The download button saves the program the same way Vision-2525 saves its page. The phone stores the file. Each run pulls the latest copy into Home/SensorFusion.",
      commit: "4d6736d",
    },
    {
      rev: 10,
      date: "2026-10-03",
      kind: "release",
      text: "The controls sit on one line under the picture, including when the phone is sideways. Info opens the Raspberry Pi menu labels.",
      commit: "2190ca8",
    },
    {
      rev: 11,
      date: "2026-10-03",
      kind: "release",
      text: "Tap the picture, or press F, to show the frame rate. The file path and the yellow running line are gone. The download mark matches Vision-2525.",
      commit: "ccc8ee6",
    },
    {
      rev: 12,
      date: "2026-10-03",
      kind: "release",
      text: "Tap Demo.90 and the model list opens above the bar. It was there before, but the bar was cutting it off.",
      commit: "52f9cb2",
    },
    {
      rev: 13,
      date: "2026-10-03",
      kind: "release",
      text: "In the image labeler, each side of the box has a dot outside the line. Left and right move sideways. Top and bottom move up and down.",
      commit: "8b183bc",
    },
    {
      rev: 14,
      date: "2026-10-03",
      kind: "release",
      text: "Capture saves video frames as numbered pictures in a SensorFusion folder. Android asks you to create that folder, then choose it.",
      commit: "5513816",
    },
    {
      rev: 15,
      date: "2026-10-03",
      kind: "release",
      text: "The accuracy meter is the thin bar on the left of the video. Capture takes pictures from the sensor or from this device. Annotate opens those pictures.",
      commit: "72a1ee9",
    },
    {
      rev: 16,
      date: "2026-10-03",
      kind: "release",
      text: "Capture, Annotate, and Upload are separate. Sensor pictures and phone pictures go in one set. Names continue, such as head.0001.jpg, and do not start over. Upload does not send the pictures anywhere.",
      commit: "538de1a",
    },
    {
      rev: 17,
      date: "2026-10-03",
      kind: "release",
      text: "Training uses the six icons from the original training video: capture video, add annotations, upload images, develop models, download the model, and run live. Develop, download, and run live are not connected yet.",
      commit: "95f8156",
    },
    {
      rev: 18,
      date: "2026-10-03",
      kind: "release",
      text: "Each training step is a button with the icon from the original training video. Capture, Annotate, and Upload run. Develop, Download, and Run Live say they are not connected yet.",
      commit: "fb56262",
    },
    {
      rev: 19,
      date: "2026-10-03",
      kind: "release",
      text: "The training icons are the buttons. There is no text card around them. Capture, Annotate, and Upload are the first three icons on the bar. The Train icon opens all six.",
      commit: "ff59939",
    },
    {
      rev: 20,
      date: "2026-10-03",
      kind: "release",
      text: "The six training steps are line icons in the page colour. Capture Images, Annotate, Upload, and Run Live use them. A strip shows the current step. A 45–60 second capture keeps one frame every half second. Training does not start until a server is chosen.",
      commit: "d67072a",
    },
    {
      rev: 21,
      date: "2026-10-03",
      kind: "correction",
      text: "The model button uses the original cube icon again. The line icon stays on the training steps.",
      commit: "0be3cc9",
    },
    {
      rev: 22,
      date: "2026-10-03",
      kind: "release",
      text: "R1. One model list, models.json, version 1. The page, the browser detector, and both copies of the computer program read it. The name picker shows only that model's labels. Group projects, upload, and paid time wait on your decision.",
      commit: "c336aff",
    },
    {
      rev: 23,
      date: "2026-10-03",
      kind: "decision",
      text: "Each picture is edited as its own XML. JSON is written only after every box on those files is Level 2, and that JSON is for training.",
      commit: "02872b9",
    },
  ],
};

export const SENSOR_FUSION_RCORE_HISTORY = fromLedgerJson(SENSOR_FUSION_LEDGER);
