// GENERATED by scripts/drone-render.mjs from docs/drone-2525/drone-2525.v00.00.json — do not hand-edit.
// The app imports THIS, never the docs file: a static export may not reach outside the frontend root, and a
// typed module is checked by tsc where a raw JSON import is not. `node scripts/drone-render.mjs --check`
// (in test:ci) refuses any drift between the two, so there is still exactly one editable source.
import type { DomainSource } from "./arena-model";

export interface DroneMode { id: string; label: string; mount: string; roles?: string[]; pass: number | string }
export interface DroneCrsRow {
  id: string; title: string; statement: string; in: string; out: string; section: string; uwf: string[];
  phase: string; mode: string; metric: string; verify: string; dtm: string; stretch: string; status: string;
}
export type DroneDomain = DomainSource & {
  project: { name: string; family: string; version: string; revision: string; stampPrefix: string;
             handoff: string; handoffSha256: string; ledger: string; disclaimer: string; mode: string; phase: string };
  revisions: { revision: string; date: string; kind: string; why: string; commit: string }[];
  gimbal: Record<string, number | string>;
  airframe: Record<string, number | string>;
  battery: Record<string, number | string>;
  sensor: { profile: string; note: string };
  targets: Record<string, number | string>;
  modes: DroneMode[];
  crs: DroneCrsRow[];
  status: Record<string, string>;
};

export const DRONE_DOMAIN = {
 "project": {
  "name": "Drone-2525",
  "family": "Vision • 2525 Level-3 Domain Play on WIREFRAME-CORE",
  "version": "00.00",
  "revision": "0.003",
  "stampPrefix": "eXeL v0.001",
  "handoff": "docs/asks/2026-09-15_drone_2525_first_pass.md",
  "handoffSha256": "0d3987649112c0222a87795167eb1aa85b68df698c55b76dd929bab86233d1e2",
  "ledger": "docs/traceability/drone-2525.ledger.json",
  "disclaimer": "Simulation for play and critique only. Bounding estimates, not design evidence. Not flight authorisation and not a weapons system.",
  "mode": "Manual (MODE_R-CORE_SPEC: no commit without a named Human-Authority event)",
  "phase": "pilot"
 },
 "revisions": [
  {
   "revision": "0.001",
   "date": "2026-09-15",
   "kind": "ask",
   "why": "Drone-2525 1st Pass persisted verbatim; the CRS ladder opens at Version 00.00.",
   "commit": "7b0b790"
  },
  {
   "revision": "0.002",
   "date": "2026-09-15",
   "kind": "decision",
   "why": "The MoT ladder replaces the four-tier fidelity table: 5 compute bands x 5 resolution steps, 1.1 the arcade rung and the fastest. Demand and capability are separated. Multi-sensor fusion EO->CHEM sheds from the top and never sheds EO. The unit holds 1080p30 and names every step down. A self-test walks the ladder in 6 to 15 minutes and reports the rung this machine actually holds.",
   "commit": "ea91e01"
  },
  {
   "revision": "0.003",
   "date": "2026-09-15",
   "kind": "release",
   "why": "The flying modes. A fixed-wing VTOL hovers on rotors and cruises on a wing, with the stall speed as the number the transition turns on. A machine may hold the pilot's seat, the camera operator's seat, or both — and a machine that is aiming must ask a named person before any shot, a gate with no bypass. All four of the operator's modes are unlocked.",
   "commit": "a3cb92f"
  }
 ],
 "arena": {
  "origin": {
   "lat": 30.27467,
   "lon": -97.74035,
   "mslM": 163
  },
  "radiusM": 450,
  "maxAltitudeM": 100,
  "note": "The Texas Capitol lawn and its bounding streets — 11th (S), 15th (N), Colorado (W), Brazos (E).",
  "demSource": "hand-authored 9x9 lawn rise; replace via scripts/security-2525/build_dem.py capitol-lawn --dataset ned10m",
  "elevation": {
   "nx": 9,
   "ny": 9,
   "spanM": 900,
   "note": "metres MSL on a 9x9 grid over the arena, row-major from the NORTH-west corner. The Capitol sits on a rise of about 12 m above 11th Street; the ground falls away south and west.",
   "grid": [
    [
     154,
     155,
     156,
     157,
     157,
     157,
     156,
     155,
     154
    ],
    [
     155,
     157,
     158,
     159,
     160,
     159,
     158,
     157,
     155
    ],
    [
     156,
     158,
     160,
     162,
     162,
     162,
     160,
     158,
     156
    ],
    [
     157,
     159,
     162,
     163,
     163,
     163,
     162,
     159,
     157
    ],
    [
     157,
     160,
     162,
     163,
     163,
     163,
     162,
     160,
     157
    ],
    [
     156,
     159,
     161,
     162,
     162,
     162,
     161,
     159,
     156
    ],
    [
     154,
     157,
     159,
     160,
     160,
     160,
     159,
     157,
     154
    ],
    [
     152,
     154,
     156,
     157,
     157,
     157,
     156,
     154,
     152
    ],
    [
     150,
     151,
     152,
     153,
     153,
     153,
     152,
     151,
     150
    ]
   ]
  }
 },
 "buildings": [
  {
   "id": "capitol",
   "label": "TEXAS CAPITOL",
   "footprint": [
    [
     -30,
     55
    ],
    [
     30,
     55
    ],
    [
     30,
     20
    ],
    [
     88,
     20
    ],
    [
     88,
     -20
    ],
    [
     30,
     -20
    ],
    [
     30,
     -55
    ],
    [
     -30,
     -55
    ],
    [
     -30,
     -20
    ],
    [
     -88,
     -20
    ],
    [
     -88,
     20
    ],
    [
     -30,
     20
    ]
   ],
   "heightM": 29,
   "doors": [
    {
     "at": [
      0,
      -55
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "carried",
   "confidence": "high",
   "note": "footprint carried verbatim from components/security-2525/mission-planning.tsx TX_CAPITOL — not re-authored"
  },
  {
   "id": "sam-houston",
   "label": "SAM HOUSTON BLDG",
   "footprint": [
    [
     269,
     319
    ],
    [
     331,
     319
    ],
    [
     331,
     361
    ],
    [
     269,
     361
    ]
   ],
   "heightM": 32,
   "doors": [
    {
     "at": [
      300,
      319
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "reagan",
   "label": "JOHN H. REAGAN BLDG",
   "footprint": [
    [
     -331,
     319
    ],
    [
     -269,
     319
    ],
    [
     -269,
     361
    ],
    [
     -331,
     361
    ]
   ],
   "heightM": 32,
   "doors": [
    {
     "at": [
      -300,
      319
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "johnson",
   "label": "ROBERT E. JOHNSON BLDG",
   "footprint": [
    [
     -42,
     410
    ],
    [
     42,
     410
    ],
    [
     42,
     450
    ],
    [
     -42,
     450
    ]
   ],
   "heightM": 28,
   "doors": [
    {
     "at": [
      0,
      410
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "zavala",
   "label": "LORENZO DE ZAVALA ARCHIVES",
   "footprint": [
    [
     272,
     37
    ],
    [
     328,
     37
    ],
    [
     328,
     83
    ],
    [
     272,
     83
    ]
   ],
   "heightM": 20,
   "doors": [
    {
     "at": [
      272,
      60
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "supreme",
   "label": "SUPREME COURT",
   "footprint": [
    [
     -328,
     37
    ],
    [
     -272,
     37
    ],
    [
     -272,
     83
    ],
    [
     -328,
     83
    ]
   ],
   "heightM": 20,
   "doors": [
    {
     "at": [
      -272,
      60
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "clark",
   "label": "TOM C. CLARK BLDG",
   "footprint": [
    [
     -326,
     -80
    ],
    [
     -274,
     -80
    ],
    [
     -274,
     -40
    ],
    [
     -326,
     -40
    ]
   ],
   "heightM": 22,
   "doors": [
    {
     "at": [
      -274,
      -60
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "price-daniel",
   "label": "PRICE DANIEL SR. BLDG",
   "footprint": [
    [
     -326,
     -205
    ],
    [
     -274,
     -205
    ],
    [
     -274,
     -165
    ],
    [
     -326,
     -165
    ]
   ],
   "heightM": 22,
   "doors": [
    {
     "at": [
      -274,
      -185
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "visitors",
   "label": "CAPITOL VISITORS CENTER",
   "footprint": [
    [
     164,
     -198
    ],
    [
     196,
     -198
    ],
    [
     196,
     -172
    ],
    [
     164,
     -172
    ]
   ],
   "heightM": 16,
   "doors": [
    {
     "at": [
      180,
      -172
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "insurance",
   "label": "INSURANCE ANNEX",
   "footprint": [
    [
     289,
     -201
    ],
    [
     331,
     -201
    ],
    [
     331,
     -169
    ],
    [
     289,
     -169
    ]
   ],
   "heightM": 18,
   "doors": [
    {
     "at": [
      289,
      -185
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "mansion",
   "label": "GOVERNOR'S MANSION",
   "footprint": [
    [
     -401,
     -269
    ],
    [
     -359,
     -269
    ],
    [
     -359,
     -233
    ],
    [
     -401,
     -233
    ]
   ],
   "heightM": 14,
   "doors": [
    {
     "at": [
      -380,
      -233
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low",
   "note": "anchored to the landmark already in mission-planning.tsx AOS.capitol (30.2724, -97.7443)"
  },
  {
   "id": "workforce",
   "label": "TEXAS WORKFORCE COMMISSION",
   "footprint": [
    [
     -458,
     159
    ],
    [
     -402,
     159
    ],
    [
     -402,
     201
    ],
    [
     -458,
     201
    ]
   ],
   "heightM": 26,
   "doors": [
    {
     "at": [
      -402,
      180
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "greer",
   "label": "DEWITT C. GREER BLDG",
   "footprint": [
    [
     -456,
     -78
    ],
    [
     -404,
     -78
    ],
    [
     -404,
     -42
    ],
    [
     -456,
     -42
    ]
   ],
   "heightM": 24,
   "doors": [
    {
     "at": [
      -404,
      -60
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "extension-n",
   "label": "CAPITOL EXTENSION SKYLIGHTS",
   "footprint": [
    [
     -35,
     107
    ],
    [
     35,
     107
    ],
    [
     35,
     153
    ],
    [
     -35,
     153
    ]
   ],
   "heightM": 3,
   "doors": [
    {
     "at": [
      0,
      107
     ],
     "w": 3.2,
     "h": 2.6
    }
   ],
   "source": "hand-authored",
   "confidence": "low",
   "note": "the extension is underground; only its north-lawn skylight band is above grade"
  }
 ],
 "treeRows": [
  {
   "id": "great-walk-w",
   "label": "GREAT WALK · WEST ROW",
   "from": [
    -28,
    -72
   ],
   "to": [
    -28,
    -240
   ],
   "count": 13,
   "trunkH": 3.5,
   "canopyR": 3.2,
   "canopyH": 5.5,
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "great-walk-e",
   "label": "GREAT WALK · EAST ROW",
   "from": [
    28,
    -72
   ],
   "to": [
    28,
    -240
   ],
   "count": 13,
   "trunkH": 3.5,
   "canopyR": 3.2,
   "canopyH": 5.5,
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "north-lawn-w",
   "label": "NORTH LAWN · WEST",
   "from": [
    -150,
    90
   ],
   "to": [
    -150,
    270
   ],
   "count": 7,
   "trunkH": 4,
   "canopyR": 4,
   "canopyH": 6.5,
   "source": "hand-authored",
   "confidence": "low"
  },
  {
   "id": "north-lawn-e",
   "label": "NORTH LAWN · EAST",
   "from": [
    150,
    90
   ],
   "to": [
    150,
    270
   ],
   "count": 7,
   "trunkH": 4,
   "canopyR": 4,
   "canopyH": 6.5,
   "source": "hand-authored",
   "confidence": "low"
  }
 ],
 "roads": [
  {
   "id": "11th",
   "label": "E 11TH ST",
   "tier": 3,
   "p": [
    [
     -450,
     -250
    ],
    [
     450,
     -250
    ]
   ]
  },
  {
   "id": "15th",
   "label": "E 15TH ST",
   "tier": 3,
   "p": [
    [
     -450,
     300
    ],
    [
     450,
     300
    ]
   ]
  },
  {
   "id": "colorado",
   "label": "COLORADO ST",
   "tier": 2,
   "p": [
    [
     -230,
     -350
    ],
    [
     -230,
     400
    ]
   ]
  },
  {
   "id": "brazos",
   "label": "BRAZOS ST",
   "tier": 2,
   "p": [
    [
     230,
     -350
    ],
    [
     230,
     400
    ]
   ]
  },
  {
   "id": "lavaca",
   "label": "LAVACA ST",
   "tier": 2,
   "p": [
    [
     -350,
     -350
    ],
    [
     -350,
     400
    ]
   ]
  },
  {
   "id": "sanjacinto",
   "label": "SAN JACINTO",
   "tier": 2,
   "p": [
    [
     350,
     -350
    ],
    [
     350,
     400
    ]
   ]
  },
  {
   "id": "congress",
   "label": "CONGRESS AVE",
   "tier": 4,
   "p": [
    [
     0,
     -250
    ],
    [
     0,
     -450
    ]
   ]
  },
  {
   "id": "10th",
   "label": "E 10TH ST",
   "tier": 2,
   "p": [
    [
     -450,
     -380
    ],
    [
     450,
     -380
    ]
   ]
  },
  {
   "id": "16th",
   "label": "E 16TH ST",
   "tier": 2,
   "p": [
    [
     -450,
     420
    ],
    [
     450,
     420
    ]
   ]
  },
  {
   "id": "greatwalk",
   "label": "THE GREAT WALK",
   "tier": 1,
   "p": [
    [
     0,
     -58
    ],
    [
     0,
     -250
    ]
   ]
  }
 ],
 "turrets": [
  {
   "id": "t-south",
   "label": "TURRET · SOUTH LAWN",
   "at": [
    0,
    -210
   ],
   "heightM": 3,
   "homeAz": 0,
   "homeEl": 5
  },
  {
   "id": "t-west",
   "label": "TURRET · WEST",
   "at": [
    -210,
    0
   ],
   "heightM": 3,
   "homeAz": 90,
   "homeEl": 5
  },
  {
   "id": "t-east",
   "label": "TURRET · EAST",
   "at": [
    210,
    0
   ],
   "heightM": 3,
   "homeAz": 270,
   "homeEl": 5
  }
 ],
 "gimbal": {
  "panMinDeg": -180,
  "panMaxDeg": 180,
  "tiltMinDeg": -30,
  "tiltMaxDeg": 60,
  "slewDegPerSec": 45,
  "hfovDeg": 34,
  "vfovDeg": 20,
  "nearM": 5,
  "rangeM": 400,
  "note": "ONE gimbal. The same record drives a fixed turret and an airframe mount — the operator's rule: 'design must be the same for both'."
 },
 "airframe": {
  "id": "vtol-01",
  "class": "fixed-wing VTOL (quadcopter <-> plane), Quantum-Systems-class",
  "massKg": 5,
  "wingAreaM2": 0.9,
  "CLmax": 1.3,
  "CLcruise": 0.6,
  "CD0": 0.04,
  "cruiseMs": 17,
  "VneMs": 30,
  "rotors": 4,
  "rotorThrustMaxN": 110,
  "hoverPowerW": 900,
  "cruisePowerW": 180,
  "transitionMinAglM": 20,
  "rhoKgM3": 1.18,
  "note": "Brochure-class public figures for a 5 kg VTOL. BOUNDING ESTIMATE ONLY — not design evidence."
 },
 "battery": {
  "capacityWh": 300,
  "reserveFrac": 0.2,
  "note": "Reserve is never spent by the sim; endurance is quoted on the usable 80%."
 },
 "sensor": {
  "profile": "pi-baseline",
  "note": "Edge extraction budget comes out of the frame before the renderer (lib/wire-core/fidelity.ts)."
 },
 "targets": {
  "kind": "door",
  "seed": 20260915,
  "upMs": 14000,
  "downMs": 6000,
  "concurrent": 3,
  "note": "Every building door is a pop-up target. Tag it by CAPTURE (store the sensor edge set) then SHOOT (line of sight must reach it). The up-window is not a taste value: a target must stay up longer than the worst swing to reach it (4s at 45°/s for half a turn) plus time to aim and press, or the round is unwinnable by construction. Gated in tests/drone-gimbal.test.mjs."
 },
 "modes": [
  {
   "id": "turrets",
   "label": "Security Turrets",
   "mount": "turret",
   "movingTargets": false,
   "pass": 1
  },
  {
   "id": "capital",
   "label": "Security Capital",
   "mount": "turret",
   "movingTargets": false,
   "pass": 1
  },
  {
   "id": "drone",
   "label": "2 HI operated drone",
   "mount": "airframe",
   "roles": [
    "pilot",
    "targeteer"
   ],
   "pass": "1b"
  },
  {
   "id": "multi",
   "label": "HI/AI pilot + targeteer, HI approves every shot",
   "mount": "airframe",
   "roles": [
    "pilot",
    "targeteer",
    "approver"
   ],
   "pass": "1c"
  }
 ],
 "crs": [
  {
   "id": "DRN-01",
   "title": "Arena frame and tiles",
   "statement": "The arena is an ENU frame on the Texas Capitol origin, and every building, tree, road and contour it draws is either carried from the repo, hand-authored and badged, or read from a map extract.",
   "in": "DRN-01.IN",
   "out": "DRN-01.OUT",
   "section": "VII",
   "uwf": [
    "U-WF-01"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "tile gate green; every element carries a source",
   "verify": "tests/drone-capitol-tiles.test.mjs",
   "dtm": "hand-authored block renders",
   "stretch": "OSM extract replaces it with zero code change",
   "status": "implemented"
  },
  {
   "id": "DRN-02",
   "title": "Canonical wire model and one-step export",
   "statement": "One model feeds the browser and the four engine targets, and a change is visible in all of them or none.",
   "in": "DRN-02.IN",
   "out": "DRN-02.OUT",
   "section": "VIII",
   "uwf": [
    "U-WF-02",
    "U-WF-05",
    "U-WF-08"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "lossless round trip on the X-BAT wireframe",
   "verify": "tests/wire-export.test.mjs",
   "dtm": "py/obj/cs/cpp from one model",
   "stretch": "every domain exports through it",
   "status": "implemented"
  },
  {
   "id": "DRN-03",
   "title": "Edge primitives",
   "statement": "Buildings, trees, roads and contours draw as edges only, with door and window openings in their real wall.",
   "in": "DRN-03.IN",
   "out": "DRN-03.OUT",
   "section": "XII",
   "uwf": [
    "U-WF-02",
    "U-WF-10"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "no fill on any drawn element",
   "verify": "tests/wire-core.test.mjs · tests/vector-law.test.mjs",
   "dtm": "Capitol block renders as edges",
   "stretch": "shared with Architect and Security",
   "status": "implemented"
  },
  {
   "id": "DRN-04",
   "title": "One gimbal for turret and airframe",
   "statement": "The same mount and gimbal record drives a fixed turret and a drone, so nothing learned on the turret is thrown away on the airframe.",
   "in": "DRN-04.IN",
   "out": "DRN-04.OUT",
   "section": "IV",
   "uwf": [
    "U-WF-02"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "identical frustum model from both mounts",
   "verify": "tests/drone-gimbal.test.mjs",
   "dtm": "turret slews and frames a door",
   "stretch": "airframe mount reuses it unchanged",
   "status": "implemented"
  },
  {
   "id": "DRN-05",
   "title": "Capture and shoot with line of sight",
   "statement": "A capture stores the sensor's extracted edges, and a shot only counts when the ray actually reaches the door.",
   "in": "DRN-05.IN",
   "out": "DRN-05.OUT",
   "section": "V",
   "uwf": [
    "U-WF-06"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "occluded shots are refused",
   "verify": "tests/drone-game.test.mjs",
   "dtm": "tag a door by capture then shot",
   "stretch": "live camera behind the same interface",
   "status": "implemented"
  },
  {
   "id": "DRN-06",
   "title": "Score and replay",
   "statement": "A completed capture or shot is written to the replay log before the score moves, so nothing that happened can be lost.",
   "in": "DRN-06.IN",
   "out": "DRN-06.OUT",
   "section": "VI",
   "uwf": [
    "U-WF-06",
    "U-WF-08"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "replay reproduces the score and the hash",
   "verify": "tests/drone-game.test.mjs",
   "dtm": "a round replays identically",
   "stretch": "portable .drn2525 file",
   "status": "implemented"
  },
  {
   "id": "DRN-07",
   "title": "Command surface, route and unlock",
   "statement": "The domain has its own route and its card is enterable, drawn under the vector law at any viewport down to 375 px.",
   "in": "DRN-07.IN",
   "out": "DRN-07.OUT",
   "section": "I",
   "uwf": [
    "U-WF-12"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "route builds; card enters",
   "verify": "next build · tests/vector-law.test.mjs",
   "dtm": "arena visible on a phone",
   "stretch": "two devices in one session",
   "status": "implemented"
  },
  {
   "id": "DRN-08",
   "title": "Flight and energy, bounded",
   "statement": "The flight model is a bounding estimate that says so on every run, and its published numbers reproduce from the source constants.",
   "in": "DRN-08.IN",
   "out": "DRN-08.OUT",
   "section": "IX",
   "uwf": [],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "--reproduce reports zero drift",
   "verify": "tests/drone-flight.test.mjs",
   "dtm": "hover and cruise endurance",
   "stretch": "VTOL transition envelope",
   "status": "implemented"
  },
  {
   "id": "DRN-09",
   "title": "Two operators, two devices",
   "statement": "The pilot is the only sender of flight state and the targeteer the only sender of gimbal commands.",
   "in": "DRN-09.IN",
   "out": "DRN-09.OUT",
   "section": "III",
   "uwf": [],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "role authority refuses a wrong sender",
   "verify": "tests/drone-link.test.mjs",
   "dtm": "two phones share one round",
   "stretch": "hosted realtime",
   "status": "implemented"
  },
  {
   "id": "DRN-10",
   "title": "AI roles under human approval",
   "statement": "An AI-initiated shot never fires without a human approval event.",
   "in": "DRN-10.IN",
   "out": "DRN-10.OUT",
   "section": "X",
   "uwf": [],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "no shot without an approve event",
   "verify": "tests/drone-game.test.mjs",
   "dtm": "AI proposes, human approves",
   "stretch": "both AI seats with humans watching",
   "status": "implemented"
  },
  {
   "id": "DRN-11",
   "title": "Vector law, the 13, and adaptive fidelity",
   "statement": "Everything drawn is edges in one of the 13 colours, and resolution and frame rate rise only with compute left over after the Edge sensor's CNN reserve.",
   "in": "DRN-11.IN",
   "out": "DRN-11.OUT",
   "section": "XI",
   "uwf": [
    "U-WF-07",
    "U-WF-09",
    "U-WF-11"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "model hash identical at every tier; LOW holds a Pi budget",
   "verify": "tests/drone-fidelity.test.mjs · tests/vector-law.test.mjs",
   "dtm": "four tiers, one truth",
   "stretch": "accelerator profile reaches ULTRA",
   "status": "implemented"
  },
  {
   "id": "DRN-12",
   "title": "Every word in 33 languages",
   "statement": "No user-facing string is English in the source; every one is a lexicon key present in all 33 languages.",
   "in": "DRN-12.IN",
   "out": "DRN-12.OUT",
   "section": "XIII",
   "uwf": [],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "lexicon coverage green with no pending keys",
   "verify": "tests/lexicon-coverage.test.mjs · tests/drone-i18n.test.mjs",
   "dtm": "keys staged and listed",
   "stretch": "filled in all 32 non-English",
   "status": "implemented"
  },
  {
   "id": "DRN-13",
   "title": "Versioned, revisioned, comparable",
   "statement": "Every edition of this specification appends a revision that cites its commit, and any two revisions can be replayed and compared.",
   "in": "DRN-13.IN",
   "out": "DRN-13.OUT",
   "section": "II",
   "uwf": [
    "U-WF-12"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "ledger validates; render --check clean",
   "verify": "tests/traceability.test.mjs · tests/drone-crs.test.mjs",
   "dtm": "Version 00.00 revision 0.001",
   "stretch": "CRS rows compare in /crs",
   "status": "implemented"
  },
  {
   "id": "DRN-11.01",
   "title": "The MoT ladder: five compute bands by five resolution steps",
   "statement": "Detail and sensing are asked for on a 25-rung ladder, 1.1 through 5.5, where the band is the edge-compute class and the step is the resolution; rung 1.1 is the 1983 vector arcade and is the fastest picture the machine can make.",
   "in": "DRN-11.01.IN",
   "out": "DRN-11.01.OUT",
   "section": "XI",
   "uwf": [
    "U-WF-07",
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "ladder monotonic in both axes; 1.1 asks for more frames than 5.5",
   "verify": "tests/mot-ladder.test.mjs",
   "dtm": "25 rungs selectable",
   "stretch": "a robot picks its own rung unattended",
   "status": "implemented"
  },
  {
   "id": "DRN-11.04",
   "title": "Demand and capability are separate, and never mixed",
   "statement": "What the picture asks for (the rung) and what the machine can deliver (the HAL class and the measured frame rate) are different quantities held in different modules, and only calibration is allowed to reconcile them.",
   "in": "DRN-11.04.IN",
   "out": "DRN-11.04.OUT",
   "section": "XI",
   "uwf": [
    "U-WF-07"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "a richer rung never asks for a faster picture",
   "verify": "tests/mot-ladder.test.mjs",
   "dtm": "the old inverted four-tier table is gone",
   "stretch": "the same split serves every 2525 domain",
   "status": "implemented"
  },
  {
   "id": "DRN-05.03",
   "title": "Multi-sensor fusion, shed from the top and never blind",
   "statement": "Sensing runs EO, IR, ACOUSTIC, MAG and CHEM, one more module per compute band; when the frame will not hold, modules are shed from the top of that ladder and EO is never shed, because a unit that cannot see is not degraded but blind.",
   "in": "DRN-05.03.IN",
   "out": "DRN-05.03.OUT",
   "section": "V",
   "uwf": [
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "EO survives every degradation path",
   "verify": "tests/mot-ladder.test.mjs",
   "dtm": "five modules declared per band",
   "stretch": "a real sensor replaces the simulated one behind the same interface",
   "status": "implemented"
  },
  {
   "id": "DRN-11.05",
   "title": "Hold 1080p30, and name every step down from it",
   "statement": "The unit tries to hold a 1920x1080 30 Hz reference stream; when it cannot it sheds a sensor module, then resolution, then frame rate, in that order, and every step is named on screen rather than taken silently.",
   "in": "DRN-11.05.IN",
   "out": "DRN-11.05.OUT",
   "section": "XI",
   "uwf": [
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "degradation order fixed; climb needs sustained headroom",
   "verify": "tests/mot-ladder.test.mjs",
   "dtm": "stream ladder live in the HUD",
   "stretch": "the same ladder drives a real encoder",
   "status": "implemented"
  },
  {
   "id": "DRN-11.06",
   "title": "Self-test: the rung this machine actually holds, in 6 to 15 minutes",
   "statement": "Pointed at a new board or a new sensor, the unit walks the ladder from 1.1 upward under real drawing load, measures a sustained frame rate at each rung, and reports the highest rung it holds at the reference stream, inside a declared 6 to 15 minute budget.",
   "in": "DRN-11.06.IN",
   "out": "DRN-11.06.OUT",
   "section": "XI",
   "uwf": [
    "U-WF-06",
    "U-WF-09"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "dwell derived from the budget; sweep stops early after two failures",
   "verify": "tests/self-cal-runner.test.mjs",
   "dtm": "a saved result file naming the ceiling",
   "stretch": "run headless on the robot itself",
   "status": "implemented"
  },
  {
   "id": "DRN-11.07",
   "title": "The robot may pick its own compute class",
   "statement": "Three compute classes are declared with their frame budgets and sensor costs, and AUTO lets the unit choose its own class from the frame rate it measures rather than from a label someone typed.",
   "in": "DRN-11.07.IN",
   "out": "DRN-11.07.OUT",
   "section": "XI",
   "uwf": [
    "U-WF-07"
   ],
   "phase": "pilot",
   "mode": "Manual",
   "metric": "AUTO thresholds derived from the budgets themselves",
   "verify": "tests/mot-ladder.test.mjs",
   "dtm": "PI / EDGE-SOC / ACCELERATOR selectable",
   "stretch": "a fourth class added without touching a caller",
   "status": "implemented"
  }
 ],
 "status": {
  "conceptual_critique": "Amber",
  "build": "Amber",
  "human_testing": "Red",
  "operations": "Red"
 },
 "motLadder": {
  "bands": 5,
  "steps": 5,
  "rungs": 25,
  "min": "1.1",
  "max": "5.5",
  "sensorLadder": [
   "EO",
   "IR",
   "ACOUSTIC",
   "MAG",
   "CHEM"
  ],
  "note": "Band = edge-compute class (how many sensor modules and how much CNN). Step = resolution (pixel density and curve roundness). Rung 1.1 is the 1983 vector arcade and asks for the fastest picture; 5.5 is the dense fused mesh. A higher rung asks for MORE work and therefore FEWER frames per second — demand, not capability."
 },
 "hal": {
  "profiles": [
   {
    "id": "pi",
    "label": "PI-CLASS",
    "frameBudgetMs": 66,
    "cnnMs": 18
   },
   {
    "id": "edge",
    "label": "EDGE-SOC",
    "frameBudgetMs": 33,
    "cnnMs": 12
   },
   {
    "id": "accel",
    "label": "ACCELERATOR",
    "frameBudgetMs": 16,
    "cnnMs": 8
   }
  ],
  "auto": "the unit picks its class from its own measured frame rate",
  "rule": "the CNN reserve is subtracted from the frame before the renderer may want any of it"
 },
 "stream": {
  "reference": "1080p30",
  "ladder": [
   "1080p30",
   "720p30",
   "480p30",
   "480p15"
  ],
  "rule": "shed a sensor module first, then resolution, then frame rate — and name every step"
 },
 "selfCal": {
  "budgetMinutesMin": 6,
  "budgetMinutesMax": 15,
  "minDwellS": 12,
  "maxDwellS": 36,
  "failStreakToStop": 2,
  "goal": "report the highest rung this machine holds at the reference stream"
 }
} as unknown as DroneDomain;
export default DRONE_DOMAIN;
